### ISSUE TITLE
Quick Debug should re-open the debugged C file when it was accidentally closed

### ISSUE THREAD

**Issue by chaosAD** [eranif/codelite#1001]
When I accidentally closed the C file which I was debugging, the stepping button failed to re-open it. Also, when I re-opened the C file after that, the green cursor was gone and was not responding to my stepping commands. I have to stop the debugging session and start all over to get it functioning again.

codelite version: 9.0.1
os: windows 7  (x64)

**Comment by eranif** [comment]
Usually such issues are configuration problems and not bugs.
Please open a thread on the forum + add all the information including the debugger log
