### ISSUE TITLE
Running Program on Windows requires wxWidgets DLL 

### ISSUE THREAD

**Issue by mtangoo** [eranif/codelite#1002]
I have noticed this little bug on Windows where Program cannot run complaining missing wx DLLs.
In previous versions (I don't remember the version, as I develop mainly on Linux) you could just compile and run and it will auto-detect DLL location. Its no longer the case.

CL 9.0.2 Weekly

Here is My Environment:
```bash
CodeLiteDir=C:\Program Files (x86)\CodeLite
UNIT_TEST_PP_SRC_DIR=C:\UnitTest++-1.3 
WXWIN=C:\wxWidgets-3.0.2
WXCFG=gcc_dll\mswud
```

I get this error

![Error Message](https://cloud.githubusercontent.com/assets/1502872/10906533/e83d98f8-822a-11e5-92e5-604971316385.png)

**Comment by eranif** [comment]
This was always the case, I _always_ has to add to the environment variables the path to the **debug** dll (it will work with release build because wxWidgets DLL exists in CodeLite path)

You need to adjust your PATH environment variable:
```
PATH=$PATH;C:\wxWidgets-3.0.2\lib\gcc_dll
```

**Comment by mtangoo** [comment]
>(it will work with release build because wxWidgets DLL exists in CodeLite path)

Can you help me why will this work? I have specified debug (mswud) not release (mswu).

**Comment by eranif** [comment]
Because your executable does not know where is the wxWidgets DEBUG DLL is located (i.e. `C:\wxWidgets-3.0.2\lib\gcc_dll`)
The release will work because it will load the DLL from `C:\Program Files\CodeLite`

**Comment by mtangoo** [comment]
Ah! I see. CodeLite comes with wxWidgets ;)
Excuse my ignorance. Your solution works fine, thanks!
Sorry for opening a non-bug.
