### ISSUE TITLE
Pretty printing is not working

### ISSUE THREAD

**Issue by hsiemannwork** [eranif/codelite#1003]
Is there a guide to have a look inside e.g. stl::vector? I use version 9.0.0 and gdb 7.10 with ubuntu 14.04

**Comment by eranif** [comment]
Does `settings->gdb settings->enable GDB pretty printer` checked?

**Comment by hsiemannwork** [comment]
Yes.
After starting the application i get this output on the console:

DEBUG>>Python Exception <type 'exceptions.ImportError'> No module named gdb:
Python Exception <type 'exceptions.ImportError'> No module named gdb:
DEBUG>>gdb: warning: Could not load the Python gdb module from `/usr/local/share/gdb/python'.
gdb: warning: Could not load the Python gdb module from `/usr/local/share/gdb/python'.
DEBUG>>Limited Python support is available from the _gdb module.

**Comment by eranif** [comment]
It looks like your gdb is broken... (these are not CodeLite errors)
