### ISSUE TITLE
When compiler error occurs, editor focus is recaptured for every project compiled, instead of only once

### ISSUE THREAD

**Issue by ntpg** [eranif/codelite#1005]
Version 9.0.3 - c++ workspace - Ubuntu

Description: When a compiler error occurs the editor changes focus to show you this error. If you have multiple projects being compiled, each project compiled after the one that contained the error changes the focus again back to the first error. This is a bit annoying, especially for a very long compile. I often find that I will start working in a different file for the remainder of the compilation. However, this becomes impossible because focus is constantly shifted back to the error site.

Desire: I think shifting the focus to the error is fine, ideally it would only this once per workspace compilation though, and not after every project.

Steps:
- Create a workspace with two or more projects
- In the first project intentionally add a compiler error
- In the others, add enough source files that the compilation takes several seconds per project
- Compile workspace
- Observe the first error reported, changes the editors focus to the error site
- Switch to another file, start typing
- Observe after the second project is finished compiling, editor changes focus back to first error
- This will happen for every subsequent project compiled in the workspace

**Comment by eranif** [comment]
I am guessing that this happens only when you use `Build Workspace` option?

**Comment by ntpg** [comment]
Yes, and only when the workspace contains multiple projects
