### ISSUE TITLE
C++ auto-completion of std class members cannot be triggered

### ISSUE THREAD

**Issue by renkun-ken** [eranif/codelite#1009]
I'm using CodeLite 9.0.2 with mingw64 distribution with g++ 4.9.3 in Rtools under Windows 10 x64.

I create a workspace and a hello-world g++ console project in the workspace. In the `Settings -> Code Completion` the search paths looks correct:

```
C:\Rtools\mingw_64\lib\gcc\x86_64-w64-mingw32\4.9.3\include
C:\Rtools\mingw_64\lib\gcc\x86_64-w64-mingw32\4.9.3\include-fixed
C:\Rtools\mingw_64\x86_64-w64-mingw32\include
C:\Rtools\mingw_64\x86_64-w64-mingw32\include\c++
C:\Rtools\mingw_64\x86_64-w64-mingw32\include\c++\backward
C:\Rtools\mingw_64\x86_64-w64-mingw32\include\c++\x86_64-w64-mingw32
```

And all other settings are default settings. However I click `Workspace - Parse Workspace` and the status looks like everything necessary is parsed but I can never trigger the auto completion with `CTRL+SPACE` or type-in several character.

I'm not sure what's the problem?

**Comment by renkun-ken** [comment]
Tried many times and find out the completion hides in a secret place beyond the screen CodeLite shows (I'm working with 3 monitors)

Dup of https://github.com/eranif/codelite/issues/997

**Comment by renkun-ken** [comment]
But the completion list does not work for objects like `vector<double> x` when I try to see `x.size()` or `x.push_back()`, and it does not show anything imported with headers like `<string>` or `<vector>` in `std::`.

**Comment by eranif** [comment]
it does... all our unit tests pass correct with GCC TDM 4.9.2 / 64 on Windows.
There is something wrong with your setup.
Please provide a minimal workspace with a single (or more) files that shows the problem

Thanks

**Comment by renkun-ken** [comment]
I use the mingw64 4.9.3 distributed by [Rtools 3.3](https://cran.r-project.org/bin/windows/Rtools/Rtools33.exe) (at `Rtools/mingw_64/`) and the [official CodeLite 9.0.2 weekly release](http://downloads.codelite.org/downloads.php?windows_weekly_64).

My workspace is zipped as below:
https://onedrive.live.com/redir?resid=6C952BE6E1A02D79!12520&authkey=!ABV7kaef7XN-s9Y&ithint=file%2czip

**Comment by renkun-ken** [comment]
![codelite-no-completion](https://cloud.githubusercontent.com/assets/4662568/10991446/37f3e054-8498-11e5-88e0-d9b1ee0b62c1.png)

I set the number of characters to type to trigger auto-completion to 1, and I type in `x` it looks like it does not find `x`, and I type `.` and nothing happens.

**Comment by eranif** [comment]
You know that I can reply with an image from my side, showing that it works, right? ;) (see below)

![works](https://cloud.githubusercontent.com/assets/3677711/10991520/9ceaa510-8466-11e5-95b7-d037959b23ad.png)

I need a sample workspace **not** images. A workspace that I can open on my side of the ocean and see the problem

**Comment by eranif** [comment]
Sorry, I missed your previous post... with the download link to the workspace

**Comment by eranif** [comment]
Still no luck: 
![one-drive](https://cloud.githubusercontent.com/assets/3677711/10991560/013a83b4-8467-11e5-880b-53cb35689a40.png)

**Comment by renkun-ken** [comment]
Change to [dropbox file](https://www.dropbox.com/s/hrdqaa8t71auapn/cpptest.zip?dl=0)

**Comment by renkun-ken** [comment]
I defined a class like 

```cpp
// A person with basic information
class person
{
public:
    string name;
    unsigned age;    
};
```

and the auto-completion work perfect. It looks like something wrong with the tagging of the header files in my mingw64 distribution?

**Comment by eranif** [comment]
Your sample works here..

Try this:

* Install another version of MinGW (**there is no need to remove your current version**), I recommend: http://tdm-gcc.tdragon.net/download
* After the installation is completed, let CodeLite know about this new compiler from: `settings->Build Settings->Compilers tab->Add an existing compiler` and point it to the `bin` folder of the newly installed compiler
* For the sake of code completion only, change the paths in the code completion (this does not change the build process, its only used for code completion): ` settings->code completion->ctags->search paths` click on the "Suggest" button and select the MinGW-TDM compiler you just installed
* Re-parse your workspace: `workspace->parse workspace`

This should get you working

**Comment by renkun-ken** [comment]
Thanks a lot for your suggestions! The problem is indeed from the mingw64 included in Rtools.
