### ISSUE TITLE
Dialog positioning problem with mulitple screens

### ISSUE THREAD

**Issue by renkun-ken** [eranif/codelite#1010]
The dialogs (e.g. project settings, build settings, environment variables) do not appear in the screen where I put CodeLens main editor. Some dialog appears in screen 2, some appears in screen 3.

I'm using Windows 10 x64.

**Comment by fwsGonzo** [comment]
Also, code suggestions (ctrl+space) appear on my main monitor, and not where I have the IDE

**Comment by eranif** [comment]
This should be fixed now
