### ISSUE TITLE
Keyboard search in tree controls is shown for non-typing keys

### ISSUE THREAD

**Issue by MaartenBent** [eranif/codelite#1012]
Almost all keys on the keyboard trigger the search function (numpad keys; ins, del home, etc; capslock, scroll lock).

These keys should probably be excluded. Numpad could be useful but currently it generates strange characters.

**Comment by eranif** [comment]
Thanks for reporting this.
This feature is new and still under improvements.
If you find something else with it, please let me know

**Comment by MaartenBent** [comment]
You should probably use `event.GetUnicodeKey()` instead of `event.GetKeyCode()`, as wxWidgets [suggests](http://docs.wxwidgets.org/trunk/classwx_key_event.html). Also the first character is capitalized while `shift` is being disabled.. If `shift` is not used as an accelerator for some functions, you could allow it like:
```c++
    if ((event.GetModifiers() != wxMOD_NONE && event.GetModifiers() != wxMOD_SHIFT) || ignoreKeys.count(ch)) {
        event.Skip();
        return;
    }

    if (!m_text->IsShown()) {
        DoShowTextBox();
    }
    
    wxString chStr(event.GetUnicodeKey());
    if (!event.ShiftDown())
        chStr.MakeLower();
    m_text->ChangeValue(chStr);
```

**Comment by MaartenBent** [comment]
One last suggestion. You could also use the following instead of using the ignore list:
```c++
    wxChar ch = event.GetUnicodeKey();
    if((event.GetModifiers() != wxMOD_NONE && event.GetModifiers() != wxMOD_SHIFT) || ch == WXK_NONE) {
        event.Skip();
        return;
    }

    if(!m_text->IsShown()) {
        DoShowTextBox();
    }
    
    wxString chStr(ch);
```
(Only shortly tested)

**Comment by eranif** [comment]
This does not work for all keyboard keys (e.g. ESCAPE, BACKSPACE)
