### ISSUE TITLE
codelite gdb pretty printing not working for me

### ISSUE THREAD

**Issue by whoisjohngalt** [eranif/codelite#1014]
codelite pretty printing not working.
Ubuntu 15.10. Codelite 9.00.
I trying to enable gdb pretty printing. But still not see strings.
I followed http://codelite.org/LiteEditor/GdbPrettyPrinting instrucctions, but pretty printing still not working. Can you help me? What i am duing wrong?

**Comment by eranif** [comment]
It works just fine. Please visit the forum and post there.
http://forums.codelite.org make sure you read the [HOW TO POST](http://forums.codelite.org/viewtopic.php?f=3&t=804) thread before posting
