### ISSUE TITLE
Feature Request: external tool: multi instances

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1016]
Feature Request: external tool: multi instances

I'm using the External Tool plugin to launch various visual differs terminal etc.

But the External Tool plugin refuses to launch another instance of a tool until the first have terminated - that is useful sometimes but not always.

It would be nice with an option per external tool indicating if it should allow multiple instances or not.

**Comment by eranif** [comment]
Here is a screenshot on how it looks: http://codelite.org/LiteEditor/ReleaseNotesCodeLite91#toc10

**Comment by uffejakobsen** [comment]
:+1:  Thanks :-)
