### ISSUE TITLE
Unable instal because clang-3.6

### ISSUE THREAD

**Issue by SalahAdDin** [eranif/codelite#1017]
I can't install the lastest CodeLite version because i was using clang-3.7 and now i'm using clang-3.6, will you do support clang-3.6? Is the lastest stable version. Thanks.

**Comment by eranif** [comment]
Which OS / Distro ?

**Comment by SalahAdDin** [comment]
Ubuntu 15.10 man, i install clang and llvm 3.6, i want install 3.7 but isn't stable yet.

**Comment by eranif** [comment]
CodeLite is compiler agnostic, it can work with any version of clang / gcc  etc - it does not really care about the version. So the question is: What is the error you are getting when installing CodeLite ?

**Comment by SalahAdDin** [comment]
He ask me for LLDM 3.5, so, i need install clang and llvm 3.5, but, i don't know why ask me this.

**Comment by eranif** [comment]
Can you paste the error you get?

**Comment by SalahAdDin** [comment]
Ok:
![centro de software de ubuntu_007](https://cloud.githubusercontent.com/assets/5034215/11320624/6d654388-906c-11e5-8c22-78f129539145.png)
It's the problem, and if i try install in terminal, it ask me to install llvm 3.4.

**Comment by eranif** [comment]
Where did you downloaded this deb file from?

**Comment by SalahAdDin** [comment]
I donwloand this deb from the download pages man. Yes man, it's a wrong logo because i have Numix-Icon-Theme, think so.

**Comment by SalahAdDin** [comment]
Ok guy, i did it and:

```bash

sudo apt-get install codelite wxcrafter
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
wxcrafter ya está en su versión más reciente.
Se instalarán los siguientes paquetes extras:
  libclang1-3.5 libllvm3.5v5 libwxsqlite3-3.0-0 wx-common
Paquetes sugeridos:
  codelite-plugins
Se instalarán los siguientes paquetes NUEVOS:
  codelite libclang1-3.5 libllvm3.5v5 libwxsqlite3-3.0-0 wx-common
0 actualizados, 5 nuevos se instalarán, 0 para eliminar y 0 no actualizados.
Se necesita descargar 16,5 MB de archivos.
Se utilizarán 64,4 MB de espacio de disco adicional después de esta operación.
¿Desea continuar? [S/n] 
```

It says that i need install clang 3.5, but i have clang 3.6. What have i do?
