### ISSUE TITLE
Right Click -> 'Find References'

### ISSUE THREAD

**Issue by Karkus476** [eranif/codelite#1020]
When I right click on a highlighted variable or function (most importantly), I would like to be able to search for times this is used. It is useful when working on unknown code

**Comment by mtangoo** [comment]
Did you try CScope? I use it mostly and have no issues so far

**Comment by Karkus476** [comment]
I don't know what that is or how to use it. Any guidance to resources on the Internet would be helpful, I will look it up.

- Karkus

**Comment by mtangoo** [comment]
http://cscope.sourceforge.net/

**Comment by mtangoo** [comment]
If you are interested the right place to ask is [CL forums](http://forums.codelite.org/viewforum.php?f=6)

**Comment by eranif** [comment]
Its already built-in into CodeLite for ages:
`Right click -> Search -> Find References`

**Comment by AndersBillLinden** [comment]
I tried
`Right click -> Search -> Find References`
and got no output at all...
