### ISSUE TITLE
Custom makefile, custom make

### ISSUE THREAD

**Issue by fwsGonzo** [eranif/codelite#1021]
At present I can't choose which make to run, as on windows there is no "make" only "mingw32-make", so it would be nice to simply be able to define which commands to run on "per OS settings."

Otherwise, I could add some shortcut from make to mingw32-make somehow..I guess

**Comment by eranif** [comment]
From the project settings: `Project settings->customize->custom build`
Double click on the `Build` command and replace `make` with whatever you want...

You can do this for all other commands (`clean`, `rebuild`) and add some custom ones
See here for more info:

http://codelite.org/LiteEditor/CustomMakefiles
