### ISSUE TITLE
Workspace view elements have horrible padding in 9.0.3 OSX

### ISSUE THREAD

**Issue by Kanimies** [eranif/codelite#1024]
The OSX version now shows Workspace explorer with horrible (1 line high?) paddings, which makes the directory tree grow unnecessarily tall and hard to use.

**Comment by eranif** [comment]
Can you post a screenshot?

**Comment by Kanimies** [comment]
Sure!
<img width="388" alt="nayttokuva 2015-11-17 kello 8 34 50" src="https://cloud.githubusercontent.com/assets/7421922/11204313/1e52f9ac-8d06-11e5-983e-11ee20b32fae.png">

**Comment by eranif** [comment]
Do you have retina display?

**Comment by Kanimies** [comment]
Yes

**Comment by eranif** [comment]
Are you using a self compiled version of wxWidgets?

**Comment by eranif** [comment]
and / or self compiled CodeLite ?

**Comment by Kanimies** [comment]
Pre-compiled binary download of latest weekly build (9.0.3). Nothing self-compiled.

**Comment by Kanimies** [comment]
OS X 10.10.5 (14F27)

**Comment by eranif** [comment]
Let me check with my Mac book, this error is usually a result of a control does not know how to display a `@2x` (hi-res image) which all should be fixed. I mainly tested on C++ workspace, I will try a PHP workspace

**Comment by Kanimies** [comment]
Cheers!

**Comment by eranif** [comment]
btw, we can continue this discussion here: https://gitter.im/eranif/codelite#

**Comment by eranif** [comment]
the problem indeed, only seen on the PHP workspace, it works for C++/Explorer

**Comment by eranif** [comment]
Fixed
Please re-download the 9.0.3 version (its actually 9.0.4 for OSX now) http://downloads.codelite.org/
and test it

**Comment by eranif** [comment]
it was the workspace icon which was mistakenly re-registered by the PHP plugin and overwritten the default hi-res PHP image associated with PHP workspace. I just re-tested it with my website workspace (which is also in PHP and its working as expected)
