### ISSUE TITLE
Shortcut for Find in folder on Workspace tab not add directory to search

### ISSUE THREAD

**Issue by anatooly** [eranif/codelite#1026]
CL 9.0.4, Ubuntu, Workspace tab empty.
Tab 'Explorer' left sidebar files/directory tree, I think not work Find in folder shortcut, dialog box open but...
1) Select folder and press Ctrl+Shift+F, folder not add to 'Look in' field;
2) Select folder and mouse click 'Find in Files', folder changes on 'Look in' field;

UPD.: On tab 'Workspace' PHP project, too, shortcut not add path to Look in.

**Comment by anatooly** [comment]
Fix problem, shortcut Ctrl+Shift+F and mouse event Find in files not identical actions, when combine actions.

Now origin action:
1) I select one or two folders and mouse click 'Find in Files' and into open dialog box folders path add to filed 'Look in', prev path clear;
2) I select one or two folders and keyboard press 'Ctrl+Shift+F' and into open dialog box folders path append to some prev folders, not clear prev path.

Problem that I find is:
1) When combination mouse & keyboard actions. After use mouse event 'Find in path' keyboard 'Ctrl+Shift+F' append selected folder and not remove prev result.
2) If use only mouse event 'Find in path' prev result always clear.
3) If use only keyboard event 'Ctrl+Shift+F' prev result always clear.

**Comment by eranif** [comment]
this was the intent

**Comment by anatooly** [comment]
@eranif Why? I don't understand logic.
Example 1: In first day I use only keyboard for search in folders. all path add & prev path clear.
On second day I use only mouse for search in folders (or another computer/home/work), all path add & prev path clear.
On three day I combine keyboard & mouse search in folders and see another logic of append path to search :-( and not clear mouse selected folders.
Example 2:
This not indent add path 'Search into Folders' JetBrains apps (WebStorm, PhpStrom, AppCode). How people know that after mouse select - keyboard select not clear prev path in search.

Sorry that my english.

**Comment by anatooly** [comment]
May be accustomed of 'Find in Directory' and not understand 'Find In Files'.
- /folder1
  - /subfolder2
   - file2.txt
 - file1.txt

I select file1.txt and possible press Ctrl+Shift+F, I think into open dialog box 'Look In' need path /folder1 parent folder (folder1) of select files. Select file2.txt add path /subfolder2.

**Comment by eranif** [comment]
The second behavior is wrong, i.e. the "Search paths" should always be cleared (unless explicitly added to the find-in-files dialog)
