### ISSUE TITLE
Wiki: Building codelite requires wxrc

### ISSUE THREAD

**Issue by g40** [eranif/codelite#1027]
Add a short note to the Wikit detailing about the need to build and install wxrc in a suitable folder?

**Comment by eranif** [comment]
I don't think we do... I keep in git the files after wxrc generation, so there is no need to re-generate them.
I am guessing that for some reason the file `LiteEditor/resources.xrc` is newer than `LiteEditor/resources.cpp`

Also, can you post here the build error message you get?

**Comment by g40** [comment]
Hi Eran, Apologies, not sure I made myself clear. I'm building Codelite x86 from master on Windows using TDM gcc as suggested. Once I'd built wxwidgets I opened the Codelite workspace to build Codelite itself. That compilation failed as wxrc had not been built yet .. .make sense? i.e there as no wxrc.exe on my system.

Also it might be worth detailing which DLL files are required where to run a fresh build. Can you accept a PR for Wiki entries?

TAIA

**Comment by eranif** [comment]
Sure I can accept PR. My comment is still valid: you should run `touch` (or just open and close the file `LiteEditor/resources.cpp` to get a new timestamp)
Once done `wxrc` is not needed

**Comment by eranif** [comment]
Just post here the text you want to add to the wiki and I will update the wiki

**Comment by eranif** [comment]
I just tested this on several clean machines, and CodeLite does not require `wxrc` from sources on Windows / Linux nor OSX

**Comment by g40** [comment]
It may have been a timestamp issue. No matter. I have built OK on both Mint and Windows anyway. If I see this again I will post the relevant details. Thanks again for the support.
