### ISSUE TITLE
Bug: Unable to close codelite

### ISSUE THREAD

**Issue by solewalker** [eranif/codelite#1029]
With new prompt before exit feature, if you select, "Remember my answer" and then click "No", after that clicking close button doesn't brings up the dialogue, hence you are unable to close codelite.

**Comment by eranif** [comment]
settings->preferences->misc->history->reset annoying dialogs answers

**Comment by solewalker** [comment]
So, this was the expected behavior? o_O I see.

**Comment by eranif** [comment]
Well, CodeLite prompted: "Closing CodeLite, Continue?" you replied with "No, and don't annoy me with this question again"

It only did what you requested. The "Reset annoying dialogs" is there for these kind of mistakes

**Comment by solewalker** [comment]
But strange thing is if I click "Remember my answer..." and click the top right close button of the dialogue, it's as if I have clicked "No". It still saves when I close the dialogue. No worries if closing and clicking "No" is same.

**Comment by eranif** [comment]
indeed, this scenario sounds like a bug
