### ISSUE TITLE
add library to install instructions

### ISSUE THREAD

**Issue by Goddard** [eranif/codelite#1031]
On Ubuntu 14.04 I found you needed an additional library in order to compile.

libsqlite3-dev

Just figured I would post it so you can update it.

**Comment by Goddard** [comment]
Also missing - libwxbase3.0-dev

**Comment by Goddard** [comment]
Not sure if these are required as it wasn't an error but also could add optionally?

lldb-3.4-dev
libhunspell-dev

**Comment by Goddard** [comment]
finally I think another optional library?

libclang-3.4-dev

**Comment by eranif** [comment]
It is all documented, follow these steps and you should be fine:

http://codelite.org/Developers/Linux

**Comment by Goddard** [comment]
sweet thanks
