### ISSUE TITLE
55% compiliation error

### ISSUE THREAD

**Issue by Goddard** [eranif/codelite#1033]
fatal error: lldb/API/SBBlock.h: No such file or directory

Any help is appreciated.  I am running Ubuntu 14.04

make
[  1%] Built target wxsqlite3
[  4%] Built target wxshapeframework
[  5%] Built target databaselayersqlite
[ 15%] Built target libcodelite
[ 32%] Built target plugin
[ 32%] Built target abbreviation
[ 33%] Built target CallGraph
[ 34%] Built target ContinuousBuild
[ 34%] Built target DebuggerGDB
[ 35%] Built target Wizards
[ 36%] Built target Outline
[ 37%] Built target QMakePlugin
[ 37%] Built target UnitTestsPP
[ 38%] Built target cppchecker
[ 38%] Built target cscope
[ 39%] Built target wxFormBuilder
[ 40%] Built target MemCheck
[ 41%] Built target Tweaks
[ 42%] Built target CodeFormatter
[ 42%] Built target Copyright
[ 46%] Built target DatabaseExplorer
[ 47%] Built target ExternalTools
[ 48%] Built target SnipWiz
[ 50%] Built target Subversion
[ 51%] Built target ZoomNavigator
[ 52%] Built target git
[ 52%] Built target CMakePlugin
[ 52%] Built target CodeLiteDiff
[ 53%] Built target SpellCheck
[ 54%] Built target SFTP
[ 55%] Building CXX object LLDBDebugger/LLDBProtocol/CMakeFiles/LLDBProtocol.dir/LLDBNetworkListenerThread.cpp.o
In file included from /home/goddard/projects/codelite/LLDBDebugger/LLDBProtocol/LLDBReply.h:32:0,
                 from /home/goddard/projects/codelite/LLDBDebugger/LLDBProtocol/LLDBNetworkListenerThread.cpp:27:
/home/goddard/projects/codelite/LLDBDebugger/LLDBProtocol/LLDBBacktrace.h:34:33: fatal error: lldb/API/SBBlock.h: No such file or directory
 #   include "lldb/API/SBBlock.h"
                                 ^
compilation terminated.
make[2]: *** [LLDBDebugger/LLDBProtocol/CMakeFiles/LLDBProtocol.dir/LLDBNetworkListenerThread.cpp.o] Error 1
make[1]: *** [LLDBDebugger/LLDBProtocol/CMakeFiles/LLDBProtocol.dir/all] Error 2
make: *** [all] Error 2

**Comment by eranif** [comment]
You should run cmake with LLDB disabled:

`cmake -DCMAKE_BUILD_TYPE=Release .. -DENABLE_LLDB=0`
