### ISSUE TITLE
Expand all folding marks when folding margin is disabled

### ISSUE THREAD

**Issue by renkun-ken** [eranif/codelite#1035]
Sometimes I accidentally click the folding mark and a code chunk is collapsed. If I go to Settings -> Preferences -> Folding and disable folding margin, the code chunk will stay collapsed. 

Is it better to expand all folding marks when the folding margin is disabled?

**Comment by eranif** [comment]
The margin is hidden, but collapsing is still enabled via keyboard
`Alt-RIGHT` to toggle the current block

**Comment by renkun-ken** [comment]
Thanks!

**Comment by eranif** [comment]
FYI:
Settings->Keyboard Shortcuts
Type in the search field: `fold`
