### ISSUE TITLE
Broken background color of line with breakpoint when breakpoint margin is disabled

### ISSUE THREAD

**Issue by renkun-ken** [eranif/codelite#1036]
I'm using latest weekly build (v9.0.4) and Tomorrow Night theme.

When I set a breakpoint at a c++ code line, and go to Settings -> Preference -> Bookmarks and uncheck Display Breakpoints / Bookmarks margin, the margin disappears as supposed but the background color of the line becomes white, which looks like a bug? When I turn on the checkbox, everything becomes normal again.

![codelite-breakpoint-margin](https://cloud.githubusercontent.com/assets/4662568/11333637/30392b88-920a-11e5-98b0-6f203fb8e1fd.png)

**Comment by eranif** [comment]
Indeed, when hiding the symbol bookmark margin, CodeLite defaults to "text background" marker (i.e. colour the entire row. I am guessing that your bookmark colour was set to white?
You can fix this by setting a proper colour from `settings->preferences->bookmarks->background colour`

**Comment by renkun-ken** [comment]
My color settings are all default and bookmarks->background colour currently defaults to pink (theme defaults?) and I change this but nothing happens and the line bgcolor still is white :(

**Comment by eranif** [comment]
Sorry, I thought you meant "bookmark", I just re-read your bug and clearly you meant "breakpoints" :)

**Comment by renkun-ken** [comment]
Thanks!

**Comment by eranif** [comment]
:+1:
