### ISSUE TITLE
namespace inconsistencies

### ISSUE THREAD

**Issue by underdoeg** [eranif/codelite#1040]
When creating a class within a namespace then then the implementation within the cpp file creates the following code which makes sense:

``` c++
#include "TestClass.h"

namespace testNamespace
{

TestClass::TestClass()
{
}

TestClass::~TestClass()
{
}


}
```

When declaring a new function and then adding the implementation automatically tough it creates this:
``` c++
#include "TestClass.h"

namespace testNamespace
{

TestClass::TestClass()
{
}

TestClass::~TestClass()
{
}


}

void testNamespace::TestClass::testFunction()
{
}
```
 I don't think any way is wrong but it is inconsistent when using the editor.

**Comment by eranif** [comment]
Note that I chose to use the second method:: `NS::CLASS::FuncName` its simpler to implement...

**Comment by underdoeg** [comment]
great thanks
