### ISSUE TITLE
Codelite Often Crashes at the end of "Build and Run" if no executable found

### ISSUE THREAD

**Issue by Karkus476** [eranif/codelite#1041]
Also when I change branch in git it forgets the executable path (possibly intentional)

**Comment by eranif** [comment]
can you provide a steps to reproduce? also, always state your codelite version and os

**Comment by Karkus476** [comment]
Linux Mint 17.2, Codelite - git commit d280ea2a22816

**Comment by Karkus476** [comment]
Yes, I need to be clearer: I am working on [supertux](http://supertux.github.io/) which uses cmake. I am using Cmake (version 3.4.0-rc2) to create a codelite project in supertux/build/codelite. Cmake does not correctly assign where the executable is (it tries ./PROJECT_NAME), so I have to change it in the project settings. If I forget to do this, codelite  crashes (would you like to attach to a debugger?). This, as far as I know, only happens after I change git branch. For some reason this sets the executable path back to ./PROJECT_NAME

**Comment by eranif** [comment]
This is now fixed
