### ISSUE TITLE
On OS X with 9.0.4, CMake Build Directory bug

### ISSUE THREAD

**Issue by Scapal** [eranif/codelite#1044]
When I create a new custom build project (in order to import existing code), once I convert it to a CMake project, I'm unable to change the Build Directory afterwards.

Another bug, if I set for example ${ProjectPath}/Release , when building it will try to build in a folder ../../../../../Release instead of a Release folder under the project path.

**Comment by eranif** [comment]
> When I create a new custom build project (in order to import existing code), once I convert it to a 
> CMake project, I'm unable to change the Build Directory afterwards.
I don't understand this... how do you convert it to `CMake` ? where do you fail to change the build directory?

> Another bug, if I set for example ${ProjectPath}/Release , when building it will try to build in a folder 
> ../../../../../Release instead of a Release folder under the project path.
Set it where? which project type?

Please provide a minimal steps / workspace that shows the problem

**Comment by Scapal** [comment]
> I don't understand this... how do you convert it to CMake ? where do you fail to change the build directory?

I choose custom build in order to have an empty project, then I go in the project settings, disable custom build, click Apply, then enable the CMake: `Enable CMake for this project`.

If I click OK, then go back an try to change the build path, the path changes won't be saved at all.

>> Another bug, if I set for example ${ProjectPath}/Release , when building it will try to build in a folder 
../../../../../Release instead of a Release folder under the project path.
>> Set it where? which project type?

> Please provide a minimal steps / workspace that shows the problem

The CMake settings are in the attached screenshot.
The project path is `/Users/pascalfautre/Projects/bitstreamdb-workspace/bitstreamdb-lib`, so `../../../../../Release` would be equal to `/Release`like if `${ProjectPath}` resolved to an empty string.

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C "bitstreamdb-lib" -f "bitstreamdb-lib.mk"
"/usr/local/bin/cmake" -E make_directory "../../../../../Release"
Error making directory "../../../../../Release".


![codelite cmake settings](https://cloud.githubusercontent.com/assets/3873855/11441712/fd1b89aa-950e-11e5-90f4-4dec61c72a82.png)

**Comment by eranif** [comment]
This is because CodeLite does not support this kind of variables: `${ProjectPath}` it should be `$(ProjectPath)`

**Comment by Scapal** [comment]
I found the bug concerning the settings not being saved. In fact changing something in the CMake setting tab doesn't enable the "Apply" button. If I change something else in another tab (i.e. enable custom build and disable it immediately), the Apply button is enabled and the CMake settings will be saved.

**Comment by eranif** [comment]
This will soon will no longer be relevant as this plugin is getting a re-write and will be replaced with a new workspace type designed for `CMake`, `QMake` and other similar tools (e.g. `PreMake`)

**Comment by Scapal** [comment]
Hi Eran,

Could you tell me more about this?

I’m using CMake with a custom CMakeFile, I used to develop using Eclipse CDT, but we are a team of developper, each using it’s preferred IDE. I find it awkward having to manage a virtual project structure in CodeLite instead of just viewing the files in the project folder. Each time I do a pull from the Git server, I have to check for new files in order to add them in the project.

Isn’t there a way to use ‘unmanaged CMake’, ie. where CodeLite doesn’t try to keep track of included files and just shows the real folder structure?

About GIT integration, would it be possible to show the status of a git file (New, Modified…) in the Workspace tree directly?

Cheers and congratulation for your project,
Pascal
