### ISSUE TITLE
On OS X with 9.0.4, the startup size of the CodeLite window is always the same

### ISSUE THREAD

**Issue by Scapal** [eranif/codelite#1045]
CodeLite doesn't seem to save the size and location of the app, always starting with something close to 640x480.

**Comment by eranif** [comment]
This is intentional and caused bugs in the past. If you think this is annoying, feel free to fix this and send a pull request with the fix

**Comment by jockm** [comment]
If you are going to pass the buck on this (which still is an issue) then a pointer in the right direction would be appreciated
