### ISSUE TITLE
.editorconfig

### ISSUE THREAD

**Issue by TurkeyMan** [eranif/codelite#1046]
CodeLite doesn't seem to support .editorconfig files (http://editorconfig.org/).
My projects all have comprehensive .editorconfig, and it's making it really hard to use CodeLite, since it keeps ruining the formatting of files.

Most modern editors have either builtin support for .editorconfig, or convenient plugins available.

**Comment by eranif** [comment]
There are no plans on adding support for `.editorconfig` files ( never heard of them)
Feel free to implement this and send a pull request

**Comment by TurkeyMan** [comment]
Did you look at the website? You'll find a very long list of editors who have heard of them.
I'm surprised you never ran into it, I thought they were almost totally ubiquitous. How do you guarantee people's patches are formatted correctly?

**Comment by eranif** [comment]
> Did you look at the website?

Yes I did. 

> You'll find a very long list of editors who have heard of them

I saw the list, still never heard of it... sorry... (maybe because I only use CodeLite...)

> How do you guarantee people's patches are formatted correctly?

I use `Ctrl-I` to format the source files to fit my coding style (you can also format an entire project using the  CodeFormatter plugin)

**Comment by eranif** [comment]
I have reopened this issue to see if anyone else is interested in this functionality

**Comment by TurkeyMan** [comment]
> I use `Ctrl-I` to format the source files to fit my coding style (you can also format an entire project using the CodeFormatter plugin)

Cool.

If you work on a variety of projects with different standards, or with many users (who never configure their editors correctly), and want to merge patches without annoying conversation about formatting, then I expect you'll come to find this feature invaluable, as I think most developers using other editors do. Editor support for `.editorconfig` files just makes a while class of annoying problem go away.

**Comment by eranif** [comment]
Can anyone of you guys upload a sample of `.editorconfig` file?
I read the official documentation, but I still would like to examine a real world `.editorconfig` file

**Comment by xenogenesi** [comment]
[Here for example, node's .editorconfig](https://github.com/nodejs/node/blob/master/.editorconfig), I've seen it used by some node module (`node_modules/`).

I use emacs, vim and some other editor, lately codelite!, but beside the editor people use different settings, having a per-project shared setup is great.

**Comment by eranif** [comment]
Thanks for sharing this file, will have a look

**Comment by eranif** [comment]
This is now implemented in CodeLite git HEAD
