### ISSUE TITLE
Source code formatting fails

### ISSUE THREAD

**Issue by hsiemannwork** [eranif/codelite#1050]
Set indention to 4 and tabsize to 8. if you load a file with these settings, sometimes the tabs are not shown correctly (4 instead of 8 spaces). After pressing Alt+F2 (show whitespace) everything works fine.

**Comment by eranif** [comment]
which version of CodeLite? which OS?

**Comment by hsiemannwork** [comment]
Codelite 9.0 and Ubuntu 14.04LTS

**Comment by eranif** [comment]
This is already fixed. Duplicate of https://github.com/eranif/codelite/issues/1013
You can grab a weekly build with the fix from our download page http://downloads.codelite.org/ (note: weekly builds are not published via the repository)

**Comment by hsiemannwork** [comment]
Ok. Thanks.
