### ISSUE TITLE
Codelite deletes all project settings every time I regenerate my makefile from Cmake

### ISSUE THREAD

**Issue by derkomai** [eranif/codelite#1055]
Codelite 9.0.0 deletes all project settings every time I change my  CmakeLists. All working directories, build directories, custom targets, etc... are lost. In fact, if I just open CmakeLists in a code editor, Codelite will refresh the project and delete all settings. Is this the expected behaviour?

I work under elementary OS Freya 64 bits.

**Comment by eranif** [comment]
Please provide a steps to reproduce + an example workspace

**Comment by derkomai** [comment]
[Here's the example](https://www.dropbox.com/s/ni90ec5r42a4umw/test.tar?dl=0)

Steps to reproduce:

1. Run Cmake and feed it with the CMakeLists provided under /sources. Use the Codelite - Unix Makefiles generator. Use /build dir as the target path.

2.  Open the workspace generated or create one new from Codelite (this was my case as Codelite had some trouble opening it) and import the test project.

3. As the build dir and data dir are not the same, we must configure the project settings:

* Customize > Custom build > Working Directory: set this to build dir. (The name "working directory was confusing me")
* General > Working directory: set this to data dir, but now codelite searches here the binaries, so we have to check our third setting.
* General > Executable to run/debug: path to our binaries, /build/test

4. Run the project and test it works. It should show "Hello world!"
5. Re-run Cmake configuration or open CMakeLists in an editor, not changing anything.
6. Return to Codelite. You'll se a project refresh and all settings in step 3 are gone.
