### ISSUE TITLE
There is no "Reset Editor Settings to their defaults" Button

### ISSUE THREAD

**Issue by tomay3000** [eranif/codelite#1056]
![editor settings](https://cloud.githubusercontent.com/assets/10688223/11656053/e6412724-9db2-11e5-875b-9972419d6aa6.JPG)

Is this feature missing or I just can't find it !?

**Comment by eranif** [comment]
There is no such button. Given the workaround is simple 
* Close CodeLite
* `rm %appdata%\CodeLite\config\codelite.*`

I don't plan on investing time on fixing this. Pull requests are most welcomed

**Comment by tomay3000** [comment]
Thank you ;)
