### ISSUE TITLE
[CodeLite v9.0.0 Under Windows] The Project Context Menu has "Rebuild" items duplicated which does not act the same, and a weird arrow displayed

### ISSUE THREAD

**Issue by tomay3000** [eranif/codelite#1058]
![project context menu](https://cloud.githubusercontent.com/assets/10688223/11656440/83b57846-9db5-11e5-9c5a-6df95d5f98bb.JPG)
All is displayed and marked with red borders.

Thank you for your understanding.

**Comment by eranif** [comment]
Is this under Virtual Box or something?

**Comment by tomay3000** [comment]
No, it is under Windows Server 2003 R2 32-bit
Strange hah!

**Comment by eranif** [comment]
In any case, you should report this to the wxWidgets team. CodeLite is using the wxWidgets abstraction layer it does not interfere directly with the menu creation
