### ISSUE TITLE
[CodeLite v9.0.0 Under Windows] The Workspace Pane Tabs - when placed on the left side of the Workspace View, its context menu will not be displayed NEAR where you clicked

### ISSUE THREAD

**Issue by tomay3000** [eranif/codelite#1059]
![workspace pane tabs](https://cloud.githubusercontent.com/assets/10688223/11656551/4118a5c0-9db6-11e5-877b-dbf07d057bfd.JPG)
1) As illustrated in the screen capture with the blue arrow, there is a long distance between the context menu and the The Workspace Pane Tabs.
2) The Workspace Pane Tabs arrow in the bottom should be repositioned to the top is more convenient (I think) as illustrated with the red arrow.

Thank you for your understanding.

**Comment by eranif** [comment]
The position is looks like a wxWidgets bug.. as it works on all other Windows systems I have tested (7, 8.1 and 10)
I agree with the re positioning of the arrow  (should be placed at the top)

**Comment by tomay3000** [comment]
I think it is a wxWidgets bug.
I think that it has been fixed and will be released in the next version whitch will be: version 3.1.0
because I found in list of changes this:
Line 158 - Fix setting label of submenu items (Artur Wieczorek).
take a look here:
https://github.com/wxWidgets/wxWidgets/blob/master/docs/changes.txt
