### ISSUE TITLE
master branch can't open version 9.0.4 workspaces

### ISSUE THREAD

**Issue by Goddard** [eranif/codelite#1061]
I always get an error saying workspace is corrupted.  I just did a git pull yesterday on the codelite github and compiled it.  I tried to open my project I created in 9.0.4 on ubuntu with the deb file and it worked fine.

Is this normal?  Something I should add or change to be able to use both for testing?

**Comment by eranif** [comment]
When you get this error message, it means that the workspace that you are trying to open is not supported by CodeLite. By default, CodeLite support only C++ workspace type. The plugins allows for PHP and Node.js workspace types as well. If you get this message, it means that:
You are attempting to open a PHP or Node.js workspace, however the plugin handling this workspace type is not loaded by CodeLite (Node.js workspace is handled by the WebTools plugin and the PHP is handled by the PHP plugin)

I am guessing that you have built CodeLite yourself and failed to install it properly afterwards.
Please follow the build instructions as described in our wiki page: http://codelite.org/Developers/Linux
