### ISSUE TITLE
Idea : add feature to git plugin

### ISSUE THREAD

**Issue by Goddard** [eranif/codelite#1062]
Currently in the left hand pane inside the git plugin view.  You can see a list of "modified" files and new files.  It would be nice to add a context menu function to add that file to the "ignore list" or something and just add it to the .gitignore file.

Just an idea I thought I would throw out if you didn't already have it on the roadmap.  Maybe that is something I could work on if no one else is?

**Comment by eranif** [comment]
> Maybe that is something I could work on if no one else is?

Ofc, pull requests are always welcomed
Feel free to ask questions on either the Gitter chat or on #IRC channel (#codelite on irc.freenode.net)
