### ISSUE TITLE
Idea : add intellihide/auto hide of side panes/plugin tabs

### ISSUE THREAD

**Issue by Goddard** [eranif/codelite#1063]
Another idea I have no idea if it is on the roadmap, but figured I would suggest it.  This one is probably a little harder then my previous idea.

How hard would it be to add the ability to add a "auto hide" feature to the side and bottom dock-able windows.  Right now you can ctrl+alt+w to toggle it, but I was thinking making it so the tabs are still visible on the left side, but when you mouse over them you can display the full view...

**Comment by eranif** [comment]
It will probably be better to implement it in a "button" way. i.e. only show the tab headers, when a tab  label is clicked, show the tab content, re-click to hide it. Auto hide is annoyting especially when you did not mean to show it, but you just hover your mouse in the area...

**Comment by Goddard** [comment]
Yeah a button is not a bad idea, or just clicking the tab when it is in "autohide" mode or what ever makes it display?

**Comment by eranif** [comment]
Yes, when I say "button" I don't really mean an actual button, but rather a shape similar to a button
My current implementation are using curved tabs design which I suspect will not fit well with an auto-hide feature. I will need to extend the notebook control

**Comment by AJenbo** [comment]
Is this feature not more or less there at this point?
By double clicking a file tab you can show/hide the side pannel, and by closing the buttom tab you can hide it and then show it again by clicking the git icon in the status bar.

**Comment by eranif** [comment]
Yes, you can also achieve this by simple clicking on `Ctrl-M` from the keyboard to toggle everything
