### ISSUE TITLE
New Project dialogue (PHP workspace) disappears when trying to copy paths from Code completion input textarea

### ISSUE THREAD

**Issue by Kanimies** [eranif/codelite#1064]
OS X, 9.0.5 latest weekly build.
PHP workspace

How I get this:
New PHP Project
->Create a project from an existing source files (ps., strip the 'an' here as it's plural!)
->Run as website

Code Completion
Browse for code completion folder.. 
 -> I choose two folders
-> Paint the area with cmd + a
-> Press cmd + c to copy => the whole process aborts / window disappears.

**Comment by eranif** [comment]
its a long standing bug in wxwidgets. I already opened a bug and it is still pending a fix
