### ISSUE TITLE
"struct/class an_identifier final" syntaxic coloration 

### ISSUE THREAD

**Issue by padget** [eranif/codelite#1067]
Hi Eranif, 

I detect a bug with  syntaxic coloration. I added the word "final" to set of keyword in order to color them.  This coloration is correct but the coloration of "an_identifier" seems to be neutralized by the one. 
And when there is no final keyword after "an_identifier" the coloration works well.

Thanks for your work and for this very well done IDE.

**Comment by eranif** [comment]
Can you give a simple code snippet?

Thanks

**Comment by padget** [comment]
```cpp
       class fundamental final
        {
        };
```

**Comment by padget** [comment]
thanks a lot. This will be for the 9.0.7 so ?

**Comment by eranif** [comment]
Yes it will.
