### ISSUE TITLE
Confirmation dialog when closing IDE

### ISSUE THREAD

**Issue by mpotocnik** [eranif/codelite#1068]
On confirmation dialog there is option "remember my answer and don't ask again". When the users checks this option and chooses NO, then application cannot be closed anymore.

You know silent one infinite road :D

**Comment by eranif** [comment]
Similar bug was opened https://github.com/eranif/codelite/issues/1029 
Which is already fixed and closed

In your case, you should be careful of what you are choosing (CodeLite did exactly what you asked it: "I don't want to close CodeLite and don't ask me again"...)

You can always reset the annoying dialogs answers from: Settings->Preferences->Misc->History->Reset annoying dialogs answers
