### ISSUE TITLE
Feature Request: copy relative path to clipboard

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1069]
Feature Request: copy relative path to clipboard

It would be nice to have a "copy relative path to clipboard"  the editor tab context menu under "Copy file name"

**Comment by eranif** [comment]
Relative to what? project/workspace?

**Comment by eranif** [comment]
Implemented it relative to workspace (so its available for all 3 workspace types)

**Comment by uffejakobsen** [comment]
Yes I meant relative to work space - sorry for being unclear :-)
