### ISSUE TITLE
Idea : add refresh to context menu for workspaces 

### ISSUE THREAD

**Issue by Goddard** [eranif/codelite#1071]
When you create a file outside of codelite often times it isn't recognized.  It would be nice to have a "refresh" context menu item that would regenerate all items within that folder.

**Comment by eranif** [comment]
Its not that simple, the project layout does not represent the directory structure on the file system, also there could be stale files (i.e. files which are part of the project but don't exist on the file system)
For this purpose we implemented the `Reconcile Project` feature http://codelite.org/LiteEditor/ReconcileProject

**Comment by Goddard** [comment]
I might be confused but it says "Workspace > Reconcile" .. not seeing that.

**Comment by eranif** [comment]
I fixed the docs, its by Right click project->Reconcile project
