### ISSUE TITLE
SFTP workspace view do not have horizontal scroll bar

### ISSUE THREAD

**Issue by diablogatox** [eranif/codelite#1076]
hello, i was a eclipse ide user, now i am happy coding with codelite, because i am using SFTP a lot and i found SFTP workspace in codelite do not have horizontal scroll bar when files nested too deep in the directories

![2015-12-22 14 35 59](https://cloud.githubusercontent.com/assets/7379371/11949526/5c369f46-a8bb-11e5-85f1-173158ac0076.png)

i'd like to have scroll bar enabled like eclipse, is it possible?
![2015-12-22 14 37 33](https://cloud.githubusercontent.com/assets/7379371/11949542/675b8346-a8bb-11e5-948e-22232d12fad9.png)

sorry for my english

**Comment by anatooly** [comment]
Yeap this actual for last 9.0.7 build. On all Pane scrollbars work correck, I think problem because SFTP realiase like Plugins.

**Comment by eranif** [comment]
The problem if because the SFTP uses wxDataViewCtrl and not wxTreeCtrl

**Comment by eranif** [comment]
This is fixed
