### ISSUE TITLE
Minor editor highlight problem

### ISSUE THREAD

**Issue by TG55AA** [eranif/codelite#1077]
Thank you really much for creating this IDE. I really like it!!! But there exist some minor bugs in highlight coloration:

1. In some cases of variable initialization such as
![1](https://cloud.githubusercontent.com/assets/16409566/11971519/4f17ef9e-a97a-11e5-8136-d5ae941b666d.png)

    "i" is recognized as an identifier and colored(in my setting) White whereas other vars are local 
    variables and colored Blue, but if I write the code in this way:
![2](https://cloud.githubusercontent.com/assets/16409566/11971524/66f972c2-a97a-11e5-975b-be86ac3c269a.png)
    where i is before an array, all are recognized as local vars.
2. If I write 

![4](https://cloud.githubusercontent.com/assets/16409566/11971666/0f866eee-a97c-11e5-8d36-17cb6876c266.png)
    the array is recognized as a identifier whereas
![3](https://cloud.githubusercontent.com/assets/16409566/11971651/c28cf0b8-a97b-11e5-9405-88babc189422.png)
    it shows digitsPwr as a variable
3. Functions in declaration or implication, where function name follows a type name, are 
    colored the same as local vars are.
![5](https://cloud.githubusercontent.com/assets/16409566/11971696/5dbd0884-a97c-11e5-9ef1-90deeda85c0e.png)

also, I wonder if formal parameters should be viewed as local vars. If they shouldn't, could you please
    make them correctly colored as local vars both in the head and the body of a function? ;-)

Of course, a programmer should not care too much about the editor. But I like CodeLite sooooo much that I wish everybody could use a perfect version of it. I would appreciate if you could please consider my proposals. Hope you enjoy your Xmas!

**Comment by eranif** [comment]
Fixed
