### ISSUE TITLE
different style of tab switching

### ISSUE THREAD

**Issue by verybigelephants** [eranif/codelite#1078]
is it possible to swtich tabs when hitting ctrl+tab right away instead of showing the list of all existing tabs?  also, it is not very convenient for me to switch tabs in their chronological order of modification, could it be possible to switch tabs in order they actually show up on the list?

**Comment by eranif** [comment]
Sorry, due to resource limitation this I will not be able to implement this.
A pull request with the suggested enhancement will be highly appreciated
