### ISSUE TITLE
 Ubuntu 14.04 Codelite9.0.0 GCC/G++: Can not add other compiler options in the popup window.(Can add directly in the field)

### ISSUE THREAD

**Issue by LCtech** [eranif/codelite#1081]
In the popup window, I can only add the options listed in the windows by checking the box before one option. When I try to manually enter other options in the 'Enter Other Options' textbox, the textbox is not allowed me to input. 

After several tries, finally, I figure out that I can add other options in the C++ Compiler Options field directly without poping up the window. 

Should we allow to add other options in the popup window as well?

**Comment by eranif** [comment]
it does work in the popup window here (OSX)
Can you please explain what exactly fails for you?
