### ISSUE TITLE
Feature request : allow to use a custom .clang-format

### ISSUE THREAD

**Issue by Folcogh** [eranif/codelite#1082]
Would it be possible to allow to use a .clang-format, as documented here : http://clang.llvm.org/docs/ClangFormat.html , please ?
It would throw a command like clang-format -i <specified .clang-format> *.?pp>, it could save and reload automagically the formatted files.

What do you think about that ? Thanks in advance.

Notes :
- I have tried to get that with the External Tools, but something fails in file reloading, IIRC. I could investigate again if you wish.
- I ask for such a feature because it's handy to have only one .clang-format for all its IDE and projects.

Last note : the ClangFormat Options dialog is incomplete or outdated, so providing this way to format sources would easily fix that flaw, avoiding you to maintain too often that dialog.

**Comment by eranif** [comment]
New option was added from `Plugins->Source Code Formatter->clang-format` you can now select a new style: "File"
When selected, the `.clang-format` file is used

**Comment by Folcogh** [comment]
Oh, many thanks Eran, good job !
