### ISSUE TITLE
Feature request: hiding scrollbars

### ISSUE THREAD

**Issue by jaw86** [eranif/codelite#1083]
Would it be possible to add the option to hide the horizontal and vertical scrollbars on the main window? For small screens and dark colour schemes, the scrollbars can be distracting.

Failing that, would it be possible to change the scrollbar colours? Apologies if this is already possible via CodeLite or system-wide settings.

Thanks!

**Comment by eranif** [comment]
Which CodeLite version are you using? which OS?
For h-scrollbars you can enable the "settings->preferences->editor->guides->auto adjust horizontal scrollbar width" this ensures that the h-scrollbar is only shown when needed.

I am not sure if it is possible to hide completely while retain the scrolling functionality

**Comment by eranif** [comment]
I could not find any way to hide the v-scrollbar, if you do find such an api or a way to implement this - please feel free to send a pull request
