### ISSUE TITLE
Not able to see values in watch for vector elements of std::pair type.

### ISSUE THREAD

**Issue by ankitdbst** [eranif/codelite#1084]
![watch_bug](https://cloud.githubusercontent.com/assets/1544263/12037175/70c13392-ae72-11e5-85c3-48fe304aa0f3.JPG)
I am using `vector<pair<int,int>>` and when I output the variable in watch, it shows empty value for the first and second element (the vector is non-empty).

**Comment by eranif** [comment]
Which version of CodeLite? which version of GDB and GCC?
Please also enable GDB pretty printer (if its not enabled): settings->GDB Settings->Enable GDB pretty printing
![pair](https://cloud.githubusercontent.com/assets/3677711/12181077/c9f703c0-b588-11e5-8b81-ee2d5b56cea5.png)
