### ISSUE TITLE
Plugin tab invisible

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#1085]
Hi Eran,

using the latest daily build on Ubuntu, I have a small problem with plugin tabs.
When starting CL I forgot to enable cscope. I enabled the plugin, but the output
tab was invisible and I couldn't find a was to make to visible, except editing codelite.conf
manually. 

Regards,
  René

**Comment by eranif** [comment]
Its already there, you just missed it:
on any pane caption, next to the close button, there is a 3-dots button - click it and select which tabs to show/hide

<img width="297" alt="3-dots" src="https://cloud.githubusercontent.com/assets/3677711/12075262/205e4fc0-b183-11e5-9c87-b047d1ba969e.png">

**Comment by upCASE** [comment]
Ah ok.
Problem was that I don't have the captions set visible.
