### ISSUE TITLE
would you mind to support pkg-config for C/C++

### ISSUE THREAD

**Issue by fcolecumberri** [eranif/codelite#1086]
Hi,
I'm trying your IDE, I really like it, but I find the lack of support for pkg-config very problematic, even you have pkg-config as a prerequisite for your own compilation.

or if you have already the support, I cant find it neither your IDE nor your documentation.

**Comment by eranif** [comment]
In the project settings->compiler->c++ options (or C options) you can type either:
`$(shell pkg-config ...)`  or  `` `pkg-config ..` ``

To set linker options: project settings->linker->linker options and use the same as above

**Comment by fcolecumberri** [comment]
thanks

**Comment by Zac610** [comment]
only the $(shell ..) solution worked for me (v. 9.1.0)

**Comment by BillKek** [comment]
`$(shell pkg-config --cflags $(PKGS))`  if you use environment variable for package names;
and link options with `$(shell pkg-config --libs $(PKGS))`

For example, my environment text is `PKGS=--static freeglut glfw3`
