### ISSUE TITLE
[Core] Quick Outline close by Esc like Find Resources...

### ISSUE THREAD

**Issue by anatooly** [eranif/codelite#1087]
System: Linux anatooly 3.16.0-57-generic #77~14.04.1-Ubuntu SMP Thu Dec 17 23:20:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
CL version: 9.0.7
Workspace: PHP Project

1) Use 'Find Resoures...' for find files (Ctrl+Shift+N) - open dialog box and close by 'ESC' keyboard button.
2) Into some PHP file use 'Quick Outline...' (Ctrl+Shift+O) - open dialog box but don't close by 'ESC' keyboard button, only mouse click for system button.

**Comment by eranif** [comment]
Fixed
