### ISSUE TITLE
[Core][Ubuntu] Change tabs when open another Workspace

### ISSUE THREAD

**Issue by anatooly** [eranif/codelite#1093]
System: Linux anatooly 3.16.0-57-generic #77~14.04.1-Ubuntu SMP Thu Dec 17 23:20:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Version: 9.0.7

Last time I have two project one PHP and another CI on C++;
When I open CI C++ project open many tabs some changes and open another project, click File - Open - Open Workspace... select php workspace project, it opened but I see all prev tabs of C++ project.

When I open some index.php and reopen C++ project all tabs is clear.

**Comment by eranif** [comment]
This is a bug in wxWidgets.
The menu item File -> Open -> Open Workspace should be disabled and you should not be allowed to load another workspace while another is opened
