### ISSUE TITLE
Is there any shortcut key for "next/prev tab" and "focus to some view or editor"

### ISSUE THREAD

**Issue by echoma** [eranif/codelite#1094]
1. I found that ctrl+PageUp/Down will show a menu which let me to select a tab in editor. But Is there a shortcut key let me quickly switch to the next or previous tab?
2. I found that ctrl+alt+w will toggle the workspace view, but the focus is still in the editor. Is there a shortcut key let me focus in the workspace view, and a shortcut key let me focus back to the editor?

Thanks for developing this wonderful IDE.

**Comment by nghiaho12** [comment]
Have a look at my PR #1109

**Comment by noNameInCity** [comment]
What about second point ? :D 

Is there a way to switch focus/active between editor and project tree(explorer) – basically globally change focus to any pane (Workspace, Explorer, Outline, back to Editor)

For example in Eclise I have:
[CTRL + 1] - focus to editor
[CTRL + 2] - focus to project explorer 
[CTRL + 3] focus to outline
