### ISSUE TITLE
Enable local debug with lldb for windows

### ISSUE THREAD

**Issue by RedSkotina** [eranif/codelite#1096]
In accordance with http://lists.llvm.org/pipermail/lldb-dev/2016-January/009248.html lldb can now use most of  common function.
But codelite still block lldb using as local debugger.
![image](https://cloud.githubusercontent.com/assets/1965405/12218346/9cab3a98-b72d-11e5-9cfa-c7c75447b489.png)

Can we have enabled local lldb for codelite at windows ?

**Comment by eranif** [comment]
Unfortunately, lldb does not support debugging Windows binaries, yet.
