### ISSUE TITLE
When opening multiple files in full screen mode, last file is pushed off screen

### ISSUE THREAD

**Issue by rwthompsonii** [eranif/codelite#1098]
I've experimented with several files, a lot of my files will have longer file names (22 characters is a good average).  Sometimes, the last (most recently opened) file is pushed to the point where I only get a few pixels to click on.  In one case it actually pushed it completely off screen, so I had to close one of the other files to be able to click on it at all.

A horizontal scroll bar would be nice in that situation.

While I'm on the subject, the ability to reorder the files (via clicking and dragging the tabs) would be a nice feature, along with the ability to right click on unselected files, or even just the ability to close unselected files via the x on the tab.

Finally, a last missing tab use case I came across is when diving through classes, frequently I end up 7 or 8 files deep when I find the one I want, and want to close the ones to the left, not the right.

**Comment by eranif** [comment]
> While I'm on the subject, the ability to reorder the files (via clicking and dragging the tabs) would be a 
> nice feature, along with the ability to right click on unselected files, or even just the ability to close 
> unselected files via the x on the tab.

You can DnD tabs to reorder them... 
Also, to close unselected files, you can click on the mouse scroll button while hovering an unselected tab

**Comment by eranif** [comment]
This is not going to be fixed due to lack of resources. Feel free to submit a pull request with a fix
