### ISSUE TITLE
Window postition not restored correctly

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#1099]
Hi Eran,

using latest git head on Ubuntu I have a problem with the Outline Window position.
I use to detach it and attached it on the right side of the screen. When reopening CL
the Outline window just floats.
I deleted all layout files, but that didn't change a thing.

Regards,
  René

**Comment by yckart** [comment]
Same here on OS X 10.11.3, iMac 27" 2011

**Comment by denk-mal** [comment]
It seems that the outline window is not stored into the default.layout perspective, so as a workaround you could save a different perspective after placing the outline window on the preferred place (e.g. default_ol.layout) and simply switch to the new perspective on startup.

HTH
denk_mal

**Comment by upCASE** [comment]
Hmmm...
Using the latest git head the problem still persists...
Saving a new perspective and loading that after start the placement of the outline pane works, but whatever I do to the default.ayout doesn't.

**Comment by eranif** [comment]
Strange, this code works perfectly on Windows
On Linux, I see that the detached pane is "floating"

**Comment by upCASE** [comment]
Glad you see it as well :-)
What's even more strange is that this used to work.

**Comment by eranif** [comment]
It was broken withe introduction of the "..." buttons on the panes captions (at least according to what I saw last night)

**Comment by eranif** [comment]
Try it now please

**Comment by upCASE** [comment]
Yes! Works charming! Thanks!

**Comment by denk-mal** [comment]
sorry for the late responds; works like a charm. Thanks a lot.
