### ISSUE TITLE
Path misbehavior on creating new workspace

### ISSUE THREAD

**Issue by nickname13** [eranif/codelite#1104]
While creating a new workspace I encounter strange behavior.

If I change the path  it doesn't take it into consideration. (only if i change the name THEN it takes it into consideration)

e.x.
a)
new workspace
workspace name: 
workspace path: /home/username/Documents (default)
Generated file:

b)
workspace name: trunk
workspace path:  /home/username/Documents (default)
Generated file:
/home/username/Documents/trunk/trunk.workspace

c) (here is the problem)
workspace name: trunk
workspace path:  /home/username/Work/Project 
Generated file:
/home/username/Documents/trunk/trunk.workspace The generated file is NOT updated!

In order to update it i have to edit the name (even removing a letter and re-inserted it again)

d) (here is the "workaround")
workspace name: trunk2
workspace path:  /home/username/Work/Project 
Generated file:
/home/username/Work/Project/trunk2/trunk2.workspace 

I have the corresponded screenshots if you want.

using codelite 9.0.7 in arch linux.

Thanks

**Comment by eranif** [comment]
Which workspace type are you using? (PHP, C/C++ or Node.js)

**Comment by nickname13** [comment]
I am using C.

**Comment by eranif** [comment]
Fixed
