### ISSUE TITLE
Feature request : Advanced SFTP features

### ISSUE THREAD

**Issue by Inglebard** [eranif/codelite#1105]
Hi,
I use Codelite since one week as PHP IDE and here are some improvements which can be good to add to the SFTP plugin :
- Manage multiple SFTP sessions can be interesting to switch quickly between 2 different projects on different locations (Personally I work often on more than 2 website in the same time )
- The possibility to upload/download folders.
- Manage rights on folders/files and add default rights in "Account manager Dialog" (actually, on linux server it seems to be 700 for folder and 644 for file. It's frustrating to use ssh or filezilla for change that.)
- Improve Drag'n Drop, when the mouse is released above a folder, upload data to this folder instead of open a dialog with current highlighted folder.
- Improve error message/socket , I have often "Socket error : Unknown error"

So here is my feedback, maybe some ideas are not good or not possible.
So what do you think about it ?

**Comment by azlux** [comment]
For the default right, it's your umask who define it. But for others improvement, I think it's a good idea, Especially for multiple SFTP sessions.

**Comment by eranif** [comment]
Note that this feature is delayed until we release CodeLite 9.1
