### ISSUE TITLE
Slow tab loading?

### ISSUE THREAD

**Issue by nghiaho12** [eranif/codelite#1110]
I've noticed the tabs take like a couple of 100 milliseconds to switch, which makes it feel unresponsive. Is this a rendering issue? Where should I look to fix this?

**Comment by eranif** [comment]
You can try by disabling some of the plugins (e.g. ZoomNavigator)
Also, try and disable the "Link Editor" tool button  (it is located on top of the workspace tree view)

Basically, each time you switch a file the event wxEVT_ACTIVE_EDITOR_CHANGED is fired.
So try and look which class registers this event and code review their handler

**Comment by nghiaho12** [comment]
It's definitely something related wxEVT_ACTIVE_EDITOR_CHANGED. I commented out in mainbook.cpp line 1089

        //wxCommandEvent event(wxEVT_ACTIVE_EDITOR_CHANGED);
        //EventNotifier::Get()->AddPendingEvent(event);

and it's insanely fast switching tabs now. The tabs appear to load correctly as well. I'll try and narrow down what's going on since commenting them out probably breaks something.

**Comment by eranif** [comment]
Note that this is probably the most used event by CodeLite... most of the plugins are relying on it
So disabling it is not a good idea.

To check which plugin affects the most do this:
* Disable all plugins
* Enable the plugins why by one

(Note: on my Mac Book and Windows tab switching is really instant with all plugins loaded...)

**Comment by nghiaho12** [comment]
Tried disabling all plugins, no difference.

**Comment by nghiaho12** [comment]
I'm switching tabs with my keyboard shortcut PR, so the speed is very noticeable when I hold the keys down.

**Comment by nghiaho12** [comment]
I think I narrowed it down to 

void clMainFrame::SelectBestEnvSet()

Every tab switch calls this function twice. Each call takes about 150 ms.

**Comment by nghiaho12** [comment]
Ok, it maybe wxWidgets fault. The slow code is

m_doc.Save(m_fileName) 

from bool ConfigurationToolBase::WriteObject(const wxString &name, SerializedObject *obj)

m_doc is a wxXmlDocument object. There have been some old post regarding slow performance.

**Comment by eranif** [comment]
I am aware that `wxXmlDocument` is quite slow to write on the file system.
However, there is a workaround (which is used all over CodeLite, but not in that specific location)

Instead of:
`m_doc.Save(m_filenName);`
It should be:
`return ::SaveXmlToFile(&m_doc, m_fileName);`

I committed a fix, can you give it a try?
Thanks

**Comment by nghiaho12** [comment]
Just tested it. It works!

**Comment by nghiaho12** [comment]
Curious though, what is being saved every time you switch TAB, and is it necessary?

**Comment by palikacska** [comment]
I have the same issue. All my plugins are disabled. Checked it with SysInternals filemon when switching tabs. I'm pretty sure this is not necessary. It writes to **debuggers.xml** around 200 times (!) and around 50 times to **environment_variables.xml**.

Seriously... WHY?

Please make it possible to turn this off (make it optional) whatever other feature it would disable. Codelite is a great IDE but a basic feature (tab switching) should not be bloated by XML-writing overhead.
