### ISSUE TITLE
wxC does not work for 9.0.9 Windows

### ISSUE THREAD

**Issue by mtangoo** [eranif/codelite#1112]
In 9.0.7 that I was using I could edit wxC file on RAD just fine. With 9.0.9 its not possible. Simple inspection makes me suspect the plugin is not correctly loaded (or missing something). I can see it in Manage plugins but it does not work

**Comment by eranif** [comment]
wxC was not built against the latest SDK which caused this error.
This is fixed and will be uploaded in the next release

**Comment by eranif** [comment]
Re-download 9.0.9 package - should be fixed now.
