### ISSUE TITLE
Ctrl+Click code navigation shortcut issue

### ISSUE THREAD

**Issue by fadeevab** [eranif/codelite#1113]
Hi, Eran,

There is an issue:
1. when *Ctrl+Alt+Click* is used as a code navigation it makes *"Goto implementation"*.
2. when *Ctrl+Click* is used as a code navigation - it makes *"Goto declaration"*, and also it is the same shortcut as "add multiple cursors". So there is also a *conflict* with 2 shortcuts - when you try to click several times on the function it resets all cursors (actually just unpredictable behavior).

Sincerely,
Alexander

**Comment by fadeevab** [comment]
I'm not very close to the code, but quick search shows me the next possible place of the issue:
LEditor::OnLeftUp -> DoQuickJump (isMiddle=false) -> GoHyperlink.

LiteEditor/context.cpp:
`2672:            wxCommandEvent e(wxEVT_COMMAND_MENU_SELECTED, alt ? XRCID("find_impl") : XRCID("find_decl"));
`

**Comment by fadeevab** [comment]
P.S.: I can prepare pull request, but I don't know desired behavior, I see some logic with middle key  (obsolete?), so I don't want to corrupt some specific shortcuts.

**Comment by eranif** [comment]
Middle click is used by 'Paste' on Linux

**Comment by fadeevab** [comment]
Could we just always Goto implementation?

**Comment by fadeevab** [comment]
There is pull request https://github.com/eranif/codelite/pull/1115, very simple patch. Thank you for your attention!

**Comment by fadeevab** [comment]
Submitted.
