### ISSUE TITLE
Focus not set in code when a breakpoint hits

### ISSUE THREAD

**Issue by nezos** [eranif/codelite#1114]
(C++ / MinGW64/Win10/Console Application) Set a breakpoint, start debugging, breakpoint hits. Try to press a shortcut key to move to the next line, nothing. You have to click first inside the code window and then use the shortcut keys.

**Comment by eranif** [comment]
Works fine on Windows 7.
Since I dont have Win10, you will need to debug this one yourself...

**Comment by AncientGrief** [comment]
Using C++, Win10, Console application but with MinGW32 and codelite 9.1.0, works just fine for me. I also disabled the "Build and debug" dialog that pops up before debugging starts, works like a charm. Does the codelite window loose it's focus, after clicking on "debug"?

**Comment by nezos** [comment]
After upgrading to 9.1.1 the problem disappeared, no idea how.
