### ISSUE TITLE
Updated and now Codelite crashes if i try to open or create new files in projects

### ISSUE THREAD

**Issue by skvoruganti** [eranif/codelite#1116]
Yesterday, I have updated Codelite to 9.0.9. Now, every time i try to open .cpp file it crashes. I have no idea why it crashes. is there a way where i can look at log file? did any of you experienced this problem? do you guys have any possible solutions for this issue? Any help is appreciated. thank you.

System OS:
 -- Running windows 10
 -- Running more than 3 programs.
 -- 8gb RAM
 -- I7 Processor 2.4 CPU
 -- NVIDIA 650M Graphics card

Problem details:
Attempt #1 Created new project, tried to open main but crashed.
Attempt #2 Opened old folder, I was able to open main file now but when i tried to create new .h file or .cpp, it crashes.
Attempt #3 Opened old folder, I was able to open main file now and created .h file but when i open .h file it crashes.
Attempt #4 Any time if i try to have more two tabs, program crashes.

Tried the following solutions but problem still exist
1) Downgraded to version 9.0. 
2) uninstalled (still have saved settings from version 9.0.9), restarted and reinstalled
3) Deleted AppData\Roaming\codelite
4)  Created new workspace and inside of it created new project and tried creating .h file and .cpp file, some how program closes.

**Comment by eranif** [comment]
Hi,
Can you please delete the folder `%updata%\codelite` and see if this helps. 
If this does not help you, can you load codelite without the plugins? To do this, open a `cmd.exe` and type: `c:\program files\codelite\codelite.exe --no-plugins`

**Comment by skvoruganti** [comment]
Thank you for quick response.
> Can you please delete the folder %updata%\codelite and see if this helps.

Where is this %updata% \codelite located in windows? Appdata? or Program Files or Program Files(x86).
>If this does not help you, can you load codelite without the plugins? To do this, open a cmd.exe and type: c:\program files\codelite\codelite.exe --no-plugins
I tried this option, it did not help, as soon as i double click on .h file 4 or 5 seconds later program closes.

thank you again for  response.

**Comment by eranif** [comment]
it's appdata

**Comment by skvoruganti** [comment]
I tried deleting this "AppData\Roaming\codelite" entire folder but still it dint help. thank you for help

**Comment by eranif** [comment]
did you try running without plugins? (codelite is a 64 but app)

try the following:
* disable clang code completion (settings-code completion-clang)
* try disable variable coloring (settings-code completion-?) (sorry, i am not in front of a computer right now)
*

**Comment by eranif** [comment]
also, when it crashes, do you get a crash dialog?

**Comment by skvoruganti** [comment]
<also, when it crashes, do you get a crash dialog?

No, I do not get any dialog, program just quits.

<Disable clang code completion (settings-code completion-clang)

there is nothing in macros(clang), unticked c++ standard 11 and 14

<try disable variable coloring (settings-code completion-colouring) and disable both options:

I am not sure what you mean by both options, I have not found coloruing in my project settings so i went to view and made coloring default just plain white and black and it still crashed

<Colour local variables

not sure what you mean by this?

<Track pre-processor blocks

dont know how to do this ? 

Problem not resolved, program still crashes. thank you for helping

**Comment by skvoruganti** [comment]
I was able to figure it out and resolved the issue. Apparently, that updated triggered my antivirus to block application without permission and no warning at all. I had to whitelist the program in order to run the application. Thank you for help and have a great day.
