### ISSUE TITLE
New workspace => Path get's not updated

### ISSUE THREAD

**Issue by AncientGrief** [eranif/codelite#1119]
Using V 9.1.0 with Windows 10.

File => New Workspace => Change Directory => "Generated File" gets not updated and still points to "Documents". Upon saving the Workspace, it gets generated in the wrong folder. See image.

![image1](https://cloud.githubusercontent.com/assets/7722670/12760589/6329e540-c9e7-11e5-9f26-ec71910a525a.jpg)

**Comment by AncientGrief** [comment]
Just installed 9.1.1
Still the same issue. The path gets correctly updated when I uncheck/recheck "Create the workspace under a separate directory". Seems like choosing a Workspace Path does not trigger the event correctly.

**Comment by eranif** [comment]
This is fixed in git master not released yet

**Comment by AncientGrief** [comment]
Okay, thought the "What's new" page points to the fixes, included in the latest build offered on your homepage and since "Fixed false "New Version is available" message" seems to be gone with 9.1.1
