### ISSUE TITLE
Feature Request: Combine .hpp and .cpp in Workspace and Editor

### ISSUE THREAD

**Issue by AncientGrief** [eranif/codelite#1120]
I really miss a feature for codelite:
Combining .hpp and .cpp files inside the editor. Meaning, that when I open up a .hpp file, it opens up inside the text editor, but merges it's content with the .cpp file ... maybe separated by a line, but looking as if I "opened up just one file" (...one file I can scroll through, at the top is always the header content, down below the cpp content). 

I created an image, to better explain what I mean. Maybe it's possible to switch this behaviour. This way the tabs and Workspace wouldn't get so messy.

![newfeature](https://cloud.githubusercontent.com/assets/7722670/12760816/9cd94848-c9e8-11e5-8402-40ecf84a48a2.jpg)

**Comment by eranif** [comment]
The current implementation is that each editor subclass `wxStyledTextCtrl` which is the wxWidgets implementation of scintilla. This means that each control can contains a single document and cannot be split into two different documents (the same document can displayed twice in the same window, but not the other way around)

To change this beahvior it requires a massive effort which I simply don't have
