### ISSUE TITLE
First tab file won't scroll using Touchpad

### ISSUE THREAD

**Issue by chhlatnash** [eranif/codelite#1124]
The file open in the first tab won't scroll using **touch pad** but it scroll normally by using **mouse wheel**.
Tested on Windows 10 Enterprise N on Dell Inspiron N5110.
Codelite version 9.1.0 and 9.0.7.

**Comment by eranif** [comment]
The scrolling is handled by the GUI framework and cannot be altered by CodeLite
CodeLite uses wxWidgets, please open this bug to this project
