### ISSUE TITLE
git plugin: problem with list modified files dialog

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1125]
git plugin: problem with git: list modified files dialog

double clicking on a file in the list view only selects the file in the workspace tree - nothing else
(multiple files can be selected by entering the git: list modified files dialog multiple times)

It would be nice if the git: list modified files dialog had the following actions (buttons) available
1) goto file (in editor)
2) display diff of file (in editor)

seen with CL 9.0.0 64bit on archlinux

/Uffe

**Comment by uffejakobsen** [comment]
same problem for CL 9.1.0/64bit @ archlinux

**Comment by eranif** [comment]
I am not sure I am following...
How do I reproduce this?

**Comment by uffejakobsen** [comment]
Sorry - I was a bit unclear in my description of the problem.

Open a workspace/project that is under git scm control

Do some random changes to some two or more files that are included in the repo - 
Then save the changes to disk - but do not commit them.
Then close the editor tabs containing the files

Now go into the menu path:
Plugins/Git/List modified files

You should now see a listview dialog that shows the files that you have changed.

Try double clicking on any of the files in the listview dialog...

What happens is that it just selects the file in the workspace tree 
And if you repeat the process it will select another file - etc

I expected that it would open a editor window for the file - or a diff/merge window

Actually it would be nice if the listview dialog had buttons forboth  "edit" and and "diff/merge"

I hope that you can reproduce from this description

Seen on CL 9.1.0/64bit/archlinux

/Uffe
