### ISSUE TITLE
git plugin: problem with show current diffs dialog

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1126]
git plugin: problem with show current diffs dialog

git: show current diffs dialog view does not list the individual filenames of changes files in the left listview - only the text entry "diff" is shown in listview

seen with CL 9.0.0 64bit on archlinux

/Uffe

**Comment by uffejakobsen** [comment]
same problem for CL 9.1.0/64bit @ archlinux

**Comment by AJenbo** [comment]
Can you check if this is still an issue with CL 10.0.5, it seams to work for me:

![billede](https://cloud.githubusercontent.com/assets/204594/26655189/199662d2-465a-11e7-9974-ec9d64ad2b96.png)

**Comment by eranif** [comment]
Closing this, if you still facing problem - please open a new bug
