### ISSUE TITLE
Context menu on editor file tabs should display plugin actions

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1128]
Context menu (right click) on editor file tabs should display plugin actions - just like right click on the same file in the workspace tree does

Seen on CL 9.0.0 64bit on archlinux

/Uffe

**Comment by uffejakobsen** [comment]
same problem for CL 9.1.0/64bit @ archlinux

**Comment by eranif** [comment]
The number of plugins is big and the context menu is already too big...
I am not going to implement this due to lack of time - a pull request with a fix is most welcomed
