### ISSUE TITLE
git plugin: "show file diff" from workspace tree looks really wierd

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1129]
git plugin: "show file diff" from workspace tree looks really wierd

Right clicking on a file in the workspace tree then selecting "git" -> "show file diff" shows a really wierd dialog that does seem to show the whole file (not the diff) in a view that cannot be scrolled or resized.

seen on CL 9.0.0 64bit on archlinux

**Comment by uffejakobsen** [comment]
same problem for CL 9.1.0/64bit @ archlinux

**Comment by AJenbo** [comment]
This looks to work for me on Ubuntu 16.04. Can you provide a screen shot please?

![billede](https://cloud.githubusercontent.com/assets/204594/26655066/6f294c7e-4659-11e7-9c53-e354f678cacd.png)

**Comment by eranif** [comment]
This is fixed
