### ISSUE TITLE
git plugin: does not respect config file conventions

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1130]
git plugin: does not respect config file conventions

When saving the git settings within CL the git plugin messes up the git config files.

git has a 3 layered config file concept: system, user-global and local

if an attribute if not found on the nearest level it searches up through the config layers for that attribute.

The git plugin fields for Global/Local user name and Global/Local email does not have a disable state - indicating that they should not be saved.

For example saving the git settings will always write user.name into the local repo .git/config.
Even when leaving the field empty it will write user.name= 
That breaks the conventions for layered git configs since it will find an empty attribute at local level and will hence end the config arrtibute search and not go upwards.

Seen with CL 9.1.0/64bit/archlinux

/Uffe

**Comment by Anunkas** [comment]
Same problem here. Should be an easy fix, the Git plugin should just NOT write user name and email into the config if they are empty in the configuration dialog.
