### ISSUE TITLE
Certain char in comments makes preprocessor coloring fail

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1131]
Certain char in comments makes preprocessor coloring fail

#if 0 // some text containing one of the following chars = + ? ( ) will make preprocessor coloring fail
some code here
#endif

CL 9.1.0/archlinux/64bit

/Uffe

**Comment by eranif** [comment]
This is something done internally by scintilla - CodeLite has no control over it
Please submit a bug to either wxWidgets or to scintilla.org
