### ISSUE TITLE
Cannot make keyboard shortcut for keyboard shortcut menu entry

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1134]
Cannot make keyboard shortcut for keyboard shortcut menu entry
It is simply not present in the keyboard short cut system :-)

CL/9.1.0/64bit/archlinux

**Comment by hurzl** [comment]
I see "Comment line" as "Ctrl-/". This doesn't work on a non-english keyboard if you need shift for a "/".

And why is the keyboard shortcut windo ḿodal so I have to close and reopen it to look up every single code?

**Comment by uffejakobsen** [comment]
@hurzl: this is a bug/issue tracker system - you are capturing my bug report with a problem not related to my report - please create your own issue so that they can be tracked and solved independently - thanks
