### ISSUE TITLE
Find not correctly position edit window horizontally, default find settings incorrect

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1135]
Using find (v9.10, Win7 x64) with F3 doesn't not scroll horizontally to the found item's horizontal location (if not already within viewable area). Vertically scrolls fine.

Also the settings "Match case" and "Match whole word only" should not be on by default. I can't think of a single scenario where I've found these useful compared to them being off.

**Comment by eranif** [comment]
> Also the settings "Match case" and "Match whole word only" should not be on by default. I can't think of a single scenario where I've found these useful compared to them being off.

I disagree here. And this is why this is configurable

**Comment by mattreecebentley** [comment]
Where is it configurable?
And why do you disagree?
Match case I can kind of understand, match whole word I don't.

**Comment by eranif** [comment]
> Where is it configurable?

You can uncheck these options...

> And why do you disagree?

Because I prefer my search is case-sensitive and match a whole word
When I search in the IDE, I usually know what I am searching for so I prefer to omit any noise by having the 'whole-word' option ticked

For example, if I search for a **word** `Get` and without the option 'whole-word' enabled, I will get tons of matches which are not relevant (e.g. GetName(), GetValue() etc)

**Comment by mattreecebentley** [comment]
On 8/02/2016 7:00 p.m., Eran Ifrah wrote:
>     Where is it configurable?
>
> You can uncheck these options...

Yeah, and, where??

**Comment by mattreecebentley** [comment]
>     Where is it configurable?
>
> You can uncheck these options...

Wait, you don't seriously mean the tickboxes on the dialog?
That's not configurable.
By configurable I thought you meant you could actually change the 
defaults. That would've been useful.

**Comment by eranif** [comment]
I think I am missing something here.. can you post a screenshot of the dialog?

**Comment by mattreecebentley** [comment]
I think we just misunderstood each other-
I thought that you were saying there was a way to set the default of the 
find/replace (ctrl-h) dialog, so that 'Match Case' and/or 'Match Whole 
Word Only' could be off or on by default.

What I think you were saying was that you can untick those options, but 
can't set their defaults. Is that correct?

I think an good workaround would be to set the default of the 
find/replace dialog options to whatever their last settings were. Ie. If 
you untick 'Match case', the next time you open the find/replace dialog 
that option is still unticked - even if you've shut down the program and 
subsequently opened it again (currently it doesn't do this).
