### ISSUE TITLE
ver 9.0.0 cannot delete files/projects correctly.

### ISSUE THREAD

**Issue by SLAVE-FEM** [eranif/codelite#1137]
ver 9.0.0 64bit
os win7 64bit

in the left workspace panel, select several projects or files or folders, right click and delete files/folders/projects, only one of them can be deleted.

i donot know if this bug is fixed in the new version but probably not and i also donot know if someone else have already raised this bug. anyway please check it.

**Comment by eranif** [comment]
The current way it works: it can delete multiple files, but only a single project/folder
A pull request with a fix is most welcomed
