### ISSUE TITLE
lua support

### ISSUE THREAD

**Issue by daurnimator** [eranif/codelite#1140]
I'm wondering if it would be possible to add Lua support.

What are the bare necessities for a new language to be supported?

**Comment by eranif** [comment]
IMO, to support Lua, the **minimum** should include:

* Syntax highlight
* The ability to format (aka "beautify") Lua files
* Some kind of project management

Extras are:

* Debugger
* Code completion for Lua

**Comment by daurnimator** [comment]
Should this be done as a PR to codelite? or can it be done as an external plugin?

**Comment by eranif** [comment]
This kind of functionality should be added as an external plugin (similar to how Node.js and PHP support is enabled in CodeLite)

The only thing that needs to be added as core functionality is the syntax highlight, the rest (debugger, code completion, project management) should be implemented in an external plugin

**Comment by daurnimator** [comment]
> The only thing that needs to be added as core functionality is the syntax highlight

Okay, well lets start there :)

Is there a particular file that should be used as a starting point/template?

**Comment by eranif** [comment]
Adding new language support is not a single file job ...
It needs to support everything that other languages does.

**Step 1**
First, you will need to create an 'Eclipse' importer
Have a look at this class `EclipseJavaScriptThemeImporter`  for an example.

This class allow CodeLite to import any theme from XML format from [this site](http://eclipsecolorthemes.org/) to CodeLite's format

The 'Eclipse' importer should be registered in the `EclipseThemeImporterManager` class

**Step 2**
Creating the proper 'Context'. The editor ("view") contains a context class per language
which holds the language specifics, for example: it implements the base context function `IsCommentOrString` which is different per langauge
It also implements the auto indentation (i.e. where should CodeLite place the caret once an ENTER is hit)
etc, see [the PHP context](https://github.com/eranif/codelite/blob/master/LiteEditor/ContextPhp.cpp) for reference

**Step 3**
Register the context under the `lua` in the `ContextManager` class

**Step 4**
Add new file type `TypeLua` in the [File Extension Manager class](https://github.com/eranif/codelite/blob/master/CodeLite/fileextmanager.cpp)
and register it for the proper file extension

Good luck :)

**Comment by eranif** [comment]
Since I am not going to implement this, I don't see any reason why keeping this opened.
A pull request with the changes will be highly appreciated.
