### ISSUE TITLE
[Design Request] Recent Workspace not available once a workspace is opened.

### ISSUE THREAD

**Issue by Yekyaa-** [eranif/codelite#1142]
This is less of a bug and more of a design request.
I'd like to switch between workspaces easily, and to do so, selecting "File > Recent Workspace" presents me with a grayed out option as if changing my workspace is unavailable.
I'm sure this is by design, but would it be ok to request the addition of enabling said option.
In doing so, I would expect it to perform a combination of "File > Close Workspace" followed by "File > Recent Workspace > xxxxxx.workspace".

It would make it more efficient and less of a click-fest to switch between two or more commonly used workspaces.

**Comment by eranif** [comment]
This caused a lot of problems in earlier versions of CodeLite (mainly crashes)
At the end (mainly because I am out of resources to handle this) - I have decided to disable this option

Feel free to implement this and send a pull request

**Comment by Yekyaa-** [comment]
I've been trying to compile wxWidgets on my 64-bit system but I constantly
end up with errors, even following the guide.
I've made the modifications to the setup.h file and the config file as well
to suppress assertions.
LD keeps coming back with Error 1, or I end up with missing characters when
trying to link the *.o files together.
I copied the files to the directories it was searching for them in as a
temporary fix.
codeLite requires wxWidgets to compile from what I understand.
I don't believe I'd be able to implement this myself unless you know what
the updated make commands are for Makefile.gcc on Windows.

If you have any tips, please suggest them to me.  Thank you.

**Comment by eranif** [comment]
Please follow these steps:

http://codelite.org/Developers/BuildingWxWidgetsWin

Also, I recommend that you use MinGW TDM-GCC

**Comment by Yekyaa-** [comment]
Those are the directions I followed and even found the setup.h file in a
different location and was still able to apply the fix. I'm also using the
latest version of TDM-GCC on 64-bit Windows 10 Pro, running the commands
from an administrative console with no directory conflicts in PATH
environment variables and disabled antivirus to avoid memory issues.

The errors I'm having involved missing characters from the directory name
for a few .o files which I resolved by copying them to the directory it was
searching for them in.

I've done multiple cleans and builds with differing attempts on flags and
always copied the new .o files into the mangled directory names manually.

One of the major issues I'm running into even running without multi core
support is the final linking with all the obj files.
ld returns an error with exit code 1 after multiple linker errors.

My Google-fu suggests it's ld running out of memory and I'm wondering if
there's a 64-bit version to alleviate that issue.
This is the exact reason I contacted you after you suggested I implement it
myself.

Do you have any other ideas so that I might get the build up and running?

**Comment by Yekyaa-** [comment]
I have no idea what you did, but I loaded up CodeLite tonight (still not
yet to get WxWidgets to compile, and now Recent Workspaces is enabled when
I have a workspace loaded already. So, now I can switch workspaces quickly
as requested. I haven't done any updates to it or anything.  This is just
weird to me, at least you already closed it.
