### ISSUE TITLE
Code refactoring not working

### ISSUE THREAD

**Issue by sab24** [eranif/codelite#1145]
Code refactoring does nothing when pressing the button. No popup shows up to type in the new name for the symbol, as it does in code:blocks or Eclipse. Nothing happens when typing on both windows and osx

**Comment by eranif** [comment]
The code refactoring is working as expected... I am not sure which button are you trying to click since there is no such button (only context menu)

If you need assistance configuring CodeLite please join the forum http://codelite.org

**Comment by sab24** [comment]
Code factoring works only when adding the files to the workspace. When only just opening a file with file, open

**Comment by eranif** [comment]
**all** CodeLite features (code completion, refactoring etc) are working when the file is part of the workspace
