### ISSUE TITLE
Feature Request: tern should not be running unless needed

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1154]
Feature Request: tern should not be running unless needed

tern (node js) consumes a lot of memoty

It would be nice with some sort of option or other solution that only starts tern if needed by the project (or something like that)

**Comment by eranif** [comment]
Plugins->Web Tools->Code Completion->Enable JavaScript Code Completion

**Comment by uffejakobsen** [comment]
ahhh so easy :-)   thx :+1:
