### ISSUE TITLE
Feature request - add "Save All" toolbar button + keyboard shortcut

### ISSUE THREAD

**Issue by bigangrydog** [eranif/codelite#1155]
Add "Save All" toolbar button + keyboard shortcut. (Using version 9.1.1)

**Comment by eranif** [comment]
I won't mind adding one, if you got the icon for it...

**Comment by bigangrydog** [comment]
Here's a couple. Derived from one in the "Primo Icons" free set (no restrictions) -- I re-colored it to match the open icon, and created a double "save all" version.
![save multi](https://cloud.githubusercontent.com/assets/17156238/13210904/acf4dd76-d92b-11e5-9d88-0de5f8a21d77.png)
![save single](https://cloud.githubusercontent.com/assets/17156238/13210905/acf99a82-d92b-11e5-8e99-6682da016075.png)

**Comment by bigangrydog** [comment]
Lemme know if you need specific sizes.
