### ISSUE TITLE
files (.htaccess, .gitignore etc)not being list in workspace

### ISSUE THREAD

**Issue by mrshahrukh123** [eranif/codelite#1156]
I am using CodeLite 9.1.1 on Windows 7.

In the project settings of a workspace under General->View there is an option Project file types I added .htaccess, .gitignore these 2 file types, apply and ok after this, but still I am unable to see these files in the workspace pane. please help. I have attached the image.
![codeliteissue1](https://cloud.githubusercontent.com/assets/4292418/13102313/d38ccd2e-d56e-11e5-88e5-324fd6e706a2.png)

**Comment by sgchris** [comment]
Please add it to PHP projects too
