### ISSUE TITLE
Search/Find and Replace/Replace... menu shows wrong hotkey

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1158]
Search/Find and Replace/Replace... menu shows wrong hotkey

No matter what hotkey I assign to menu function "Search/Find and Replace/Replace..." it shows CTRL-R a the hotkey in the menu

The assigned hotkey works it is just the display in the menu that is wrong

CL/9.1.0/archlinux/64bit

**Comment by eranif** [comment]
I suspect that this is one of wxWidgets attempts on being smarter than the programmer...
They tend to set default shortcuts for known actions (e.g. wxID_FIND / wxID_REPLACE)
