### ISSUE TITLE
Codelite can't open on OS 10.8.5

### ISSUE THREAD

**Issue by coralied** [eranif/codelite#1160]
Hi,

I downloaded codelite 9.1 which is supposed to work with OS 10.8, but the app can't open with my OS (10.8.5).

Any idea?

Thank you

Coralie

**Comment by eranif** [comment]
Its clearly stated on the download page that CodeLite work on OSX 10.10 and later.
I don't have an older Mac... so you will need to build it from sources

**Comment by coralied** [comment]
There is an older version for os 10.8...

**Comment by eranif** [comment]
I looked at the "Weekly" section in the download page.
However, the truth remain: I only build and release CodeLite for 10.10 and later (I have updated the website to reflect this)
