### ISSUE TITLE
Search and Replace is confusing - possible simplification?

### ISSUE THREAD

**Issue by bigangrydog** [eranif/codelite#1161]
FEEDBACK: I'm using Codelite alot now, and use often use the search/replace and search/replace in files. For one thing, the search menu options are two submenus down but, apart from that, there appears to be different and confusing search/replace dialogs. If I click "Search" it shows an inplace search/replace panel in the main window with a replace option, but if I click "Replace...", I get a completely different dialog window. Then there is the "Find in Files", which brings up a different dialog box again. I often find myself searching one way, and a few moments later, wondering why when I search again, I am presented with a different way of doing it.

Is a redesign of this something that would be considered?

As an initial starting point, mirroring the way search/replace on Codeblocks (or in Notepad++ but without the plethora of search menu options) wouldn't be too bad. Perhaps, a way to dock a common floating search/replace dialog box could then be added. (I happen to like the current search panel in the main window of Codelite, but find it eats up vertical real estate adding to the letter box code view problem on widescreen monitors).

**Comment by fadeevab** [comment]
+1
Also there is "Search..." menu on the right click (context menu) to do "Find References" and "Goto the beginning..." functions, not so obvious too.

As a note: as I noticed, you have much more chances to see your proposal in the next release, if you propose your own patch by pull request. Good luck!

**Comment by eranif** [comment]
The "traditional" replace dialog was removed from CodeLite and now the find/replace is using the same docked panel at the bottom of the editor.
