### ISSUE TITLE
Shortcut Configuration Feature Request

### ISSUE THREAD

**Issue by bigangrydog** [eranif/codelite#1162]
The ability edit keyboard shortcuts is great.

What would be really useful, however, is a way to see a list of free (unused) shortcut combinations. Perhaps a button can be added which shows a list dialog, from where an unused combination can be selected.

**Comment by eranif** [comment]
![kbd1](https://cloud.githubusercontent.com/assets/3677711/13312473/8dbf69f0-db9f-11e5-94d9-9da4042b7670.png)
![kbd2](https://cloud.githubusercontent.com/assets/3677711/13312475/8f4dbaec-db9f-11e5-82b3-59091b8b490a.png)
