### ISSUE TITLE
GUI spacing Issues in workspace editor settings window.

### ISSUE THREAD

**Issue by salamanderrake** [eranif/codelite#1163]
Ubuntu 15.10
CodeLite versions this happens with:
* 9.1.0 release
* 9.1.2 weekly build
* 9.1.3 master git branch

Where you click in the menus to switch 'tabs' its shrunk down to where you can't read anything.

[Screen Shot](http://imgur.com/9nc4gwI) of the workspace editor settings window that I can reproduce this issue.

If there is any other information you need please let me know.

**Comment by eranif** [comment]
I had to replace the `wxTreebook` with `wxNotebook`
