### ISSUE TITLE
'Exclude from build' is not imported from VS2015

### ISSUE THREAD

**Issue by harry-g** [eranif/codelite#1168]
When importing a project from VS2015, the 'Exclude from build' status is not considered.
This can be a killer for huge projects where you manually have to rework all the 'Exclude from build' flags!

E.g. the JUCE framework works with this to exclude all .cpp and include only headers from their library dir.

Found no workaround like a possibility to do a mass change (like mark all .cpp files in a certain subdir tree and exclude them) for this neither in IDE nor by editing readable project files.

**Comment by eranif** [comment]
PR applied - bug closed
