### ISSUE TITLE
'Trim only modified lines' checkbox UI problem

### ISSUE THREAD

**Issue by nghiaho12** [eranif/codelite#1171]
For a long time I thought the "Trim Trailing Spaces" option was broken. It wasn't until after looking at the code that I found there's an option that controls whether it trims modified lines or not. 

Currently, this option is under Editor -> Save Options

To turn this option off I have to do
1. click "When saving files, trim empty lines"
2. click "Trim only modified lines"
3. click  "When saving files, trim empty lines" again (to de-activate this option)

**Comment by eranif** [comment]
The checkboxes are no automatically cleared if the "global" option is disabled

**Comment by oranagra** [comment]
FYI, i noticed (codelite 17) that the `Trim only modified lines` doesn't work (nothing is trimmed) if `modified lines` checkbox in `guides` / `what to highlight` is off.

**Comment by eranif** [comment]
Thanks Oran. Re-opening this issue

**Comment by eranif** [comment]
@oranagra which OS are you using?

**Comment by eranif** [comment]
NVM, I see the problem here. We use the same data structure that keeps tracking of modified lines for the trim action.

**Comment by eranif** [comment]
This should be fixed now. I will release CodeLite 17.2 for macOS, Windows & Ubuntu 22.04 this weekend (hopefully...)
It will be great if you can report that it fixes the issue for you
