### ISSUE TITLE
New version notification window opens under Scanning workspace notification - blocking startup

### ISSUE THREAD

**Issue by Kanimies** [eranif/codelite#1176]
When a newer version of Codelite is available, the program displays a notification window of this on startup. It is a dialog window requiring user input (Wonder what's the difference between Cancel and No -actions? Are they both needed?)

This window however gets hidden underneath the
 Scanning workspace -notification, requiring the user to actually guess that there is a dialogue open behind it and move the notification away to be able to react to the new version notification.

<img width="603" alt="notification_hidden" src="https://cloud.githubusercontent.com/assets/7421922/13421049/24514aa8-df94-11e5-90c4-474121b755fc.png">

<img width="600" alt="user_action_required" src="https://cloud.githubusercontent.com/assets/7421922/13421056/2f928242-df94-11e5-9da1-109140772690.png">

**Comment by Kanimies** [comment]
The new version notification screen also reappears on every restart, clicking on No or Cancel only closes the window for the time being - if Codelite is closed and reopened, the nag screen appears again.

**Comment by eranif** [comment]
You can disable the new version notification dialog: Preferences->Misc->Check for new version on startup

> Wonder what's the difference between Cancel and No -actions? Are they both needed?

Cancel is there so in case of "I am not sure what to do" you can hit the ESCAPE button to make it go away
