### ISSUE TITLE
Editor split view

### ISSUE THREAD

**Issue by calcyss** [eranif/codelite#1179]
Coming from Code::Blocks IDE.
I've been using CodeLite for a while now, and so far it seems to be excellent.
However, there is one crucial feature (for me) missing, or at least i cant find it.
Is there a way to split view the editor? So we can have multiple different files open in 2 views? Say, header and implementation file at the same time, for example? In Code::Blocks for example, you can simply drag a tab/file to some edge of the IDE and it will automatically create a seperate editor frame.

**Comment by eranif** [comment]
This was the case in CodeLite a year ago, however, since then we switched to different tab system which does not support this.
There are multiple bugs that needs to be fixed before we can switch back to `wxAuiNotebook`

**Comment by calcyss** [comment]
forgive me for repeating the comparison with CB, but as far as i know CB is also based on wxWidgets, ans CB itself has been working relatively bugfree as long as ive used it? i suppose they use `wxAuiNotebook` ?

**Comment by eranif** [comment]
C::B forked and maintain several wxWidgets control (to name a few: `wxScintilla`, `wxAuiNotebook`) while I prefer to use the builtin ones (e.g. CodeLite uses `wxStyledTextCtrl` instead of `wxScintilla`)

I don't like to keep the extra maintenance - its a simple man power question nothing more

**Comment by calcyss** [comment]
Ah, i see. Great work on CodeLite though! love it :)

**Comment by eranif** [comment]
I closed this, note that if you will provide a pull-request, I will be happy to apply it

**Comment by milasudril** [comment]
The tabs are just confusing. Especially when you have 20 files open. Drop them and use a vertical panel that can show all open files. Something like `Tab` tab in the workspace view. Add highlight to the current file, and maybe also add a tree view. Then use that instead.

**Comment by AJenbo** [comment]
@milasudril your commenting on a close issue. The current file in Tab is already highlighted and you can move the panel where you like. Also Explorer already gives you a treeview.

**Comment by milasudril** [comment]
@AJenbo What I thought was:

 1. The tab cannot handle split editor
 2. Tabs are not needed. A vertical list of open files is much more useful

(1) and (2) => Remove the tabs, so this issue can be solved.

**Comment by AJenbo** [comment]
Hmm I see. As eranif said, it's not that it can't be solved. its a question of man power. Pull request are welcome. With something like this I think a series of small changes and preparations would the way to go instead of attempting to do it all at once.

**Comment by dghart** [comment]
Hi,
Another point to add to what's already been said: not everyone will agree that a vertical panel is better. I much prefer tabs.

So any pull request or patch should be adding the option of using a vertical panel, not making it compulsory.

**Comment by canmetan** [comment]
I personally prefer a split view with tabs as well.
It's very convenient to look at the header file, see the variables etc. while you're working on a cpp file.
Plus you can look at other headers if you're going to use functions from there or if you have an input text file that you will parse, it's useful. Since we already have tabs and since C::B source code is open source, I figure it shouldn't be extremely difficult to simply incorporate existing code. I'm not familiar with the code base and don't have much time unfortunately. I know it's easy to ask and hard to do, so I will just say that the person who does this will be my hero 👶  Enjoying code lite for now, might go back to C::B in the future just because of this back and forth switch. Thank you for providing this awesome IDE devs.

**Comment by guy-rouillier** [comment]
Found this issue via search.  eranif said he wants to stick with standard wxWidgets controls.  I see that wxWidgets has a wxSplitterWindow:

[http://docs.wxwidgets.org/3.0/overview_splitterwindow.html](http://docs.wxwidgets.org/3.0/overview_splitterwindow.html)

Maybe this wasn't available when this question was first raised?  I know, I know, submit a patch.  Thanks.

**Comment by eranif** [comment]
This is now implemented in git master, hope that this is what you meant:

<img width="939" alt="splitter-view" src="https://user-images.githubusercontent.com/3677711/40466473-9957cb1c-5f2e-11e8-8ded-a283273412e9.png">

**Comment by aviallon** [comment]
That's an awesome feature!
Thanks @eranif

**Comment by guy-rouillier** [comment]
Thanks, much appreciated!

**Comment by canmetan** [comment]
@eranif the hero! Thanks mate I will definitely check this out.

**Comment by jdyatsin** [comment]
Thanks! very nice feature. 
I installed git master, but I cannot find this option. Can you please explain how I can enable this feature?

Thanks
