### ISSUE TITLE
Press Add Folder let CodeLite close

### ISSUE THREAD

**Issue by benqqq** [eranif/codelite#1180]
1. open [Find in File] dialog
2. Press [+] button to popup menu
3. Click [Add Folder...] item
4. Codelite be closed abnormally

![crash](https://cloud.githubusercontent.com/assets/13009249/13518380/fa46016a-e207-11e5-914f-959b2d9c6639.png)

**Comment by eranif** [comment]
I am unable to reproduce this here..
Windows 7/64 bit

Can you please provide more details on your CodeLite version and OS?

**Comment by benqqq** [comment]
CodeLite version: v9.1.3
OS: Windows 7 64-bit (6.1, Build 7601) Service Pack 1

**Comment by eranif** [comment]
Are using CodeLite 64 or 32 bit? ( I am still unable to reproduce this)

**Comment by benqqq** [comment]
CodeLite x64 version.

**Comment by eranif** [comment]
I am afraid I am out of ideas.. I teste this on 3 different machines, it works well on all of them
Can you try and delete `%appdata%\CodeLite` folder and see if it changes anything?

**Comment by benqqq** [comment]
After delete the %appdata%\CodeLite folder, ColeLite become normal and not close anymore, even I overwrite with my %appdata%\CodeLite files, too.

Although I didn't know why and find the root cause, I thanks for your help!
