### ISSUE TITLE
Strange code completion behavior for PHP

### ISSUE THREAD

**Issue by jgmdev** [eranif/codelite#1181]
I have been fully using codelite now that it has PHP support to maintain a very old style code that uses functions all over the place and no classes. Recently I noticed that code completion is skipping results that better match the typed characters and I have to keep typing in order to get the function that I'm looking for, here some screen shots:

![](https://raw.githubusercontent.com/jgmdev/images/master/codelite/codelite-codecompletion.png)

That is what I get when I type print, I have to keep typing in order to get:

![](https://raw.githubusercontent.com/jgmdev/images/master/codelite/codelite-codecompletion-after.png)

Is this the desired behavior?

**Comment by eranif** [comment]
By default, CodeLite sets a 50 items limit per query when fetching the matches from the symbol database. For C++ this is configurable from: `Settings->Code completion->display and behavior->number of items to display in the completion box` 

This value was not honoured for PHP.
Note that this value does not guarantee to display exactly 50 or N items in the box, but is allows CodeLite to search more items in the symbols database

Obviously, changing it to higher number will cause the CC to take a little more time

**Comment by jgmdev** [comment]
Great, I set it to 20,000 (maybe a bit exaggerated) and it works much better and not slow at all at least on my machine :)

Thanks!

**Comment by eranif** [comment]
@jgmdev are you using a self compiled version of CodeLite?

**Comment by jgmdev** [comment]
@eranif I'm using this https://aur.archlinux.org/packages/codelite-git/ which I maintain my self and it automatically fetches and compiles the newest changes as updates package version automatically.

**Comment by eranif** [comment]
I always had in mind that you are a CodeBlocks developer & user... (maybe you are)

> I'm using this https://aur.archlinux.org/packages/codelite-git/ which I maintain my self

Ah, I was not aware of this repo... is it OK to link it from CodeLite website?

**Comment by jgmdev** [comment]
Back when I was coding C++ applications I used CodeBlocks and on my learning path I developed the AutoVersioning plugin, but nothing more, also I was playing with https://github.com/jgmdev/cpp-parser but never got to finish it. Nowadays I'm mostly a php coder. And sure, that archlinux pkgbuild is public like it should be :)

**Comment by eranif** [comment]
> Nowadays I'm mostly a php coder
Nice. Come visit us at ZendCon this year we are hosting it in Vegas ;)
