### ISSUE TITLE
need improve intellisense for include wxWidget header file

### ISSUE THREAD

**Issue by binhengzhao** [eranif/codelite#1182]
![image](https://cloud.githubusercontent.com/assets/13463192/13547244/ca5d2758-e27f-11e5-946e-11ba8263f915.png)

after hit "Tab", it will input header file like below

![image](https://cloud.githubusercontent.com/assets/13463192/13547274/94a5987e-e280-11e5-801f-9fce438f722c.png)

env: window7 64bit, codelite9.1

**Comment by eranif** [comment]
This is a problem with your setup.
Somewhere in your settings, you added `/path/to/wx-folder/` as search folder
and this is what CodeLite found.
![3-5-2016 1-21-57 pm](https://cloud.githubusercontent.com/assets/3677711/13547285/531b55a6-e2d5-11e5-81c6-aee3d53e0f01.png)
