### ISSUE TITLE
Closable tabs

### ISSUE THREAD

**Issue by flederwiesel** [eranif/codelite#1184]
Tabs, tabs, tabs... I'm lost. More tabs don't mean more usability for me... The output pane e.g. contains far too many unwanted areas. It would really be nice if I could close some of them.

From time to time people tend to using the mouse - even developers (I have to admit). If in the editor window there are many windows to be closed, it would be helpful, if all tabs contained close button, instead of only the active.

**Comment by eranif** [comment]
![2](https://cloud.githubusercontent.com/assets/3677711/13549123/3eface3e-e308-11e5-95bf-954c1794a6ca.png)
Click on the 3 dots to hide tabs.
If you want to close non active tab, use the mouse scroll button - hover a tab and click it

**Comment by flederwiesel** [comment]
??? Looks different here... What am I doing wrong?

![untitled](https://cloud.githubusercontent.com/assets/12841716/13549239/c8cf49ca-e301-11e5-86cf-2266cd8f6043.png)

**Comment by eranif** [comment]
You hide the docking windows captions.
`Settings->Preferences->Windows & Tabs->Hide docking windows captions`

**Comment by flederwiesel** [comment]
Better, thanks. Only one of the two GITs will not disappear. But still better.

**Comment by eranif** [comment]
You have relics from older versions of CodeLite (from the time that the output tab was named `git` in lowercase and not `Git`)
