### ISSUE TITLE
Working with watch expressions

### ISSUE THREAD

**Issue by flederwiesel** [eranif/codelite#1185]
Watch pane seems to be missing keyboard support for <copy>, <rename>.
Suggestion: Ability to copy value OR (member)name+value with i.e. Ctrl+C and Ctrl+Shift+C (best: configurable).

Good thing: Opening class/structure under watch is working!

Also, change of variable format is lost as soon as ending the debugger. This is aggravating, if working in something you better watch in hex... I used to work with VC6 a good while ago; there was a very nice feature on watch expressions: You could specify the format amongst the name as:

> m_value,x

, which would automatically set the format to sprintf-like %x. I would really be happy to see this in CL.

**Comment by eranif** [comment]
> Watch pane

Do you mean the debugger "Watches" tab? or the "Locals"?

>Watch pane seems to be missing keyboard support for , .

I dont understand this one

**Comment by flederwiesel** [comment]
1) I am talking about watches tab.
2) I would have expected somnething like <F2> for changing value and <Ctrl+C> for copy value.

**Comment by eranif** [comment]
what do you expect when user clicks on `,` or `.` ?

**Comment by flederwiesel** [comment]
Sorry, I didn't notice I forgot to escape the \< \>, so the important part of the message went missing. I fixed the original issue now. Please see above (if using the same ordering).
