### ISSUE TITLE
Debugger commands

### ISSUE THREAD

**Issue by flederwiesel** [eranif/codelite#1186]
I am missing a "Go to line", if from time to time I want to re-run a function, which takes a time to get there.

A "Run to line" might also not be the worst...

**Comment by eranif** [comment]
![3](https://cloud.githubusercontent.com/assets/3677711/13549252/721504f4-e30a-11e5-8f71-fb415e51926a.png)
You have 2 options:

* Run to cursor (i.e. execute all code until the debugger reaches the caret line
* Jump to cursor (i.e. skip execution and go directly to the caret line, this also works backward, i.e. you can re-run statement)

**Comment by flederwiesel** [comment]
Jump to cursor: Didn't find it in the main debugger menu, when looking for the keyboard shortcut. Seems it's not in the list of shortcut functions.
Run to cursor: Seems only possible, if the debugger is already running, (I was used to somthing different) but I can live with it.

**Comment by eranif** [comment]
Both options are only available via the context menu and when the debugger is running

**Comment by flederwiesel** [comment]
Is there a chance to implement a keyboard shortcut for "Jump to cursor"?
