### ISSUE TITLE
Next/previous editor window

### ISSUE THREAD

**Issue by flederwiesel** [eranif/codelite#1188]
Sorry, me again... I don't find a setting to go to the previous/next editor window. I am used to something line Ctrl+PgUp/PgDn, which seems not to work here - although I am the opinion, this used to work in previous versions, correct me, if I am mistaken.
I find it far easier to go to _adjacent_ windows this way instead of Ctrl+Tab (which also makes sense though!).

**Comment by eranif** [comment]
`View->Next Tab` and `View->Previous Tab`
You can assign shortcuts from `Settings->Keyboard Shortcuts`

**Comment by flederwiesel** [comment]
> You can assign shortcuts from Settings->Keyboard Shortcuts

I desperately tried it but there doesn't seem to be `View->Next Tab` and `View->Previous Tab` under keyboard shortcuts:

![untitled](https://cloud.githubusercontent.com/assets/12841716/13553329/119eb1ca-e386-11e5-8bd8-2d0ed29240c9.png)
![untitled](https://cloud.githubusercontent.com/assets/12841716/13553340/45baeabe-e386-11e5-8bd8-44850f0733d7.png)

**Comment by eranif** [comment]
You need to click on the "Defaults" button - to get the new additions (this was recently added)
