### ISSUE TITLE
LLDB plugin causes Codelite to exit on startup

### ISSUE THREAD

**Issue by hugin84** [eranif/codelite#1191]
Codelite shows the spash screen and then exits without any error messages, exit code is 1.
When run with `--no-plugins` it seemed to run fine.
I stepped through in GDB, the cause lies in somewhere in the LLDB plugin.

Workaround:
deleting `/usr/lib/codelite/LLDBDebugger.so` allows CodeLite to run normally

Arch Linux 64bit
Kernel 4.4.1-2-ARCH
glibc 2.23-1
commit 575cc821c82c798109d4bf22a4910412dde281b2

related to my old issue at https://github.com/eranif/codelite/issues/1053 ?
(new OS installation in the current case, CodeLite was never installed before)

**Comment by eranif** [comment]
Is it a self compiled CodeLite?
We don't provide an official installer for Arch, so the simple solution is to build CodeLite with LLDB disabled, this is done by passing `-DENABLE_LLDB=0` to cmake
