### ISSUE TITLE
$(OutputFile) PostBuild macro not working anymore

### ISSUE THREAD

**Issue by davidecapod** [eranif/codelite#1193]
$(OutputFile) macro does not work anymore in PostBuild (it is empty).

Using 9.1.0 on Ubuntu 14.04 from http://repos.codelite.org/ubuntu.

**Comment by davidecapod** [comment]
Strangely, works on Windows with both 9.1.0 and 9.1.3.
Maybe the problem is only on Linux build?

**Comment by eranif** [comment]
I will look at this today.
Do you have any value set for `OutputFile` in project settings->general page?

**Comment by davidecapod** [comment]
Yes it is set; it does not work with the default value of $(IntermediateDirectory)/$(ProjectName) and neither with an explicit value.
Quite sure this is a regression, because I am using this PostBuild in a project where $(OutputFile) was working in the near past.

**Comment by eranif** [comment]
I checked the code and this macro was never supported in the Project Settings
If it worked for you for some reason, then it must be via the Makefile (where a **Makefile** variable with this name is created)

However, if you click on the Help button of the project settings, you will not see this macro.

**Comment by davidecapod** [comment]
Well, I do not know why, but if you just put "echo $(OutputFile)" in PostBuild on Windows it works correctly, but not in 9.1.0 on ubuntu 14.04 anymore...

**Comment by eranif** [comment]
It works because there is a variable in the **Makefile** with this exact same name.
At the top of the makefile, you will see:
```
OutputFile             := .... 
```
I have now fixed it to support it regardless of the generated Makefile

**Comment by davidecapod** [comment]
Ok perfect, thanks!
