### ISSUE TITLE
Toolbar will be hided by Reload Workspace

### ISSUE THREAD

**Issue by benqqq** [eranif/codelite#1195]
1. Open a workspace
2. Click "Reload Workspace"
3. Wait Codelite close file tabs and reload workspace
4. Toolbar become hidden <-- problem

**Comment by eranif** [comment]
I am unable to reproduce this. Please provide more info

**Comment by eranif** [comment]
I am unable to reproduce this issue, however, I don't see this issue as a priority bug and due to lack of resources, this issue won't be addressed (at least not by me) pull request with a fix are most welcomed

**Comment by benqqq** [comment]
sorry for my late reply.

It can be reproduce when checked "Use Native Toolbar" on Codelite win64 v9.1.4 or older version.
