### ISSUE TITLE
Tabs keep in hiding even space free

### ISSUE THREAD

**Issue by benqqq** [eranif/codelite#1196]
For example,

1. Open CodeLite and no files opened. The first tab is "Welcome!" tab.
![c1](https://cloud.githubusercontent.com/assets/13009249/13658109/263da8e4-e6af-11e5-948c-e01ba3850073.png)

2. Press enough times of Ctrl+N to create new tabs and make the first(leftmost) tabs be hidden.
![c2](https://cloud.githubusercontent.com/assets/13009249/13658166/90d7aa1a-e6af-11e5-857c-c91ab4d7441c.png)
 
3. Close a few rightmost tabs, but the hidden tabs not be pulled back. <--problem
![c3](https://cloud.githubusercontent.com/assets/13009249/13658455/0b69bc44-e6b2-11e5-9653-2c31f3be90e6.png)

4. But if try to minimize CodeLite, trigger panes or bars, the hidden tabs will back.
![c4](https://cloud.githubusercontent.com/assets/13009249/13658555/2f3ec690-e6b3-11e5-84ba-1cd8d1da87fc.png)

**Comment by eranif** [comment]
There were few attempts on fixing this in the past, the results were even worse.
I am not going to invest more time on this. You are most welcome to submit a pull request
