### ISSUE TITLE
Code completion does not refocus

### ISSUE THREAD

**Issue by dljr0122** [eranif/codelite#1198]
I just built release version on my iMac.  When the code completion window popup is shown, I have to manually use mouse to proceed.  This is in version 9.1.4.  This was not an issue in 9.1.3.

**Comment by eranif** [comment]
Working just fine on my Mac book... OSX 10.10

**Comment by eranif** [comment]
I have uploaded 9.1.4 OSX build, built on my MacBook.
Can you try it please?
http://codelite.org/downloads/codelite/weekly/wip/codelite.app.tar.gz

**Comment by dljr0122** [comment]
I'm not sure why, but it says "Error 1 - Operation not permitted."

**Comment by eranif** [comment]
Where does it says it?

**Comment by dljr0122** [comment]
When I try to extract the file.

**Comment by eranif** [comment]
so you are unable to extract `codelite.tar.gz` ? I just downloaded to my Linux box and I was able to extract it

Did you try running it from command line?

**Comment by dljr0122** [comment]
I was able to extract the file you gave me.  And that version works.  I haven't investigated why my build didn't work.  I'm somewhat inexperienced with git.  So I'm guessing messed up somewhere along the lines following instructions.  Thank you for your prompt responses.

By the way did you want me to run anything else for you?

**Comment by eranif** [comment]
> By the way did you want me to run anything else for you?

No thanks.

Going to close this, since it looks like an issue with your local build
