### ISSUE TITLE
Code Completion problem

### ISSUE THREAD

**Issue by Kaendan** [eranif/codelite#1200]
Hi! I am having a problem with code completion. It automatically completes when I use classes I created, but it does not complete with `std::` or other imported libraries.

I am on OS X but I am having the same problem on Linux. I enabled **C++11 Standard** in workspace and in project. I created a new workspace with a new project and it does not change anything.

It does not complete and the word `std::` is not colored as I saw on screenshots.

Here is my code : 
```c++
#include <string>

int main(int argc, char **argv)
{
    std::string message = "Hello"; 
    message. //no completion here
}
```

**Comment by eranif** [comment]
What settings do you have under settings->code completion->ctags->search paths ?
for me it works fine, so I am pretty sure that CodeLite simply does not know where your STL headers are located.

for me the search paths are set to:

```
/Library/Developer/CommandLineTools/usr/include
/Library/Developer/CommandLineTools/usr/include/c++/v1
/Library/Developer/CommandLineTools/usr/lib/clang/7.0.2/include
/Library/Frameworks
/System/Library/Frameworks
/usr/include
/usr/local/include
```

**Comment by Kaendan** [comment]
I had nothing under `settings->code completion->ctags->search`.
I added your tags. It works! `Suggest` does nothing on my OS X is that normal? I tried on Linux it works.

Thanks a lot!

**Comment by eranif** [comment]
If it does nothing, then it means that CodeLite did not detect any compiler ...
What happens when you go to: `settings->build settings->compilers->add compiler button->scan computer for installed compilers`

**Comment by Kaendan** [comment]
It works well. Thanks a lot! I like your work a lot!
