### ISSUE TITLE
Segfault error while saving a PHP file

### ISSUE THREAD

**Issue by demos** [eranif/codelite#1201]
The BT:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff9659d700 (LWP 26587)]
0x00007ffff29ed78e in _IO_new_fclose (fp=0x7fff8c164810) at iofclose.c:57
57	iofclose.c: Aucun fichier ou dossier de ce type.
(gdb) bt
#0  0x00007ffff29ed78e in _IO_new_fclose (fp=0x7fff8c164810) at iofclose.c:57
#1  0x00007ffff51412a7 in wxFFile::Close() () from /usr/lib/x86_64-linux-gnu/codelite/libwx_baseu_unofficial-3.1.so.0
#2  0x00007ffff37cf0d2 in PHPSourceFile::PHPSourceFile(wxFileName const&) () from /usr/lib/x86_64-linux-gnu/codelite/liblibcodelite.so
#3  0x00007fff966fa00b in PHPParserThread::ParseFile(PHPParserThreadRequest*) () from /usr/lib/x86_64-linux-gnu/codelite/codelitephp.so
#4  0x00007ffff3876461 in WorkerThread::Entry() () from /usr/lib/x86_64-linux-gnu/codelite/liblibcodelite.so
#5  0x00007ffff5250022 in wxThread::CallEntry() () from /usr/lib/x86_64-linux-gnu/codelite/libwx_baseu_unofficial-3.1.so.0
#6  0x00007ffff5258fcb in ?? () from /usr/lib/x86_64-linux-gnu/codelite/libwx_baseu_unofficial-3.1.so.0
#7  0x00007ffff2d506aa in start_thread (arg=0x7fff9659d700) at pthread_create.c:333
#8  0x00007ffff2a85e9d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

I use the 9.1.0 version provided in Ubuntu's official PPA as i'm unable to build since my last dist-upgrade and I just noticed that a weekly build existed. I hope this crash is not already fixed.

Btw, I have two questions : 
+ Is there a ppa for a beta or a nightly channel to be able to betatest without being able to build?
+ Would it be rude if I asked you an other way than PayPal to donate (for political reasons). I recently found an other software whom coders proposed https://stripe.com as an alternative?

**Comment by eranif** [comment]
> 57  iofclose.c: Aucun fichier ou dossier de ce type.

 Can you please translate this message 

Is it possible to get the source file that caused this error? Is this persistent? (i.e. does next time you restart CodeLite, does it keep on crashing?)

> as i'm unable to build since my last dist-upgrade 

What error do you get? which Ubuntu version?

> Is there a ppa for a beta or a nightly channel to be able to betatest without being able to build?

Did you try to install the weekly deb? from the download page

> Would it be rude if I asked you an other way than PayPal to donate (for political reasons)

You don't have to open a PayPal account to donate using the PayPal channel, you can use debit/credit card. I will check stripe site (have to admint, never heard of it)

**Comment by demos** [comment]
> Can you please translate this message 

Aucun fichier ou dossier de ce type. => no file or directory of this type found

> Is it possible to get the source file that caused this error?

[ReportingTest.txt](https://github.com/eranif/codelite/files/167790/ReportingTest.txt)
It's normally a PHP file but GitHub doesn't accept it.

> Is this persistent? (i.e. does next time you restart CodeLite, does it keep on crashing?)

This error occured at least 2 or 3 times recently but it's the first time with gdb enabled.

> does it keep on crashing?

What do you mean by "keep on"?

> Did you try to install the weekly deb

I just did it while I opened the bug. 

> What error do you get? which Ubuntu version?

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBSSH_LIB
    linked by target "libcodelite" in directory /home/jean/dev/codelite/CodeLite

-- Configuring incomplete, errors occurred!
```

With Xubuntu wily from a dist-upgrade (the error doesn't occur with a fresh install).

I've been able to go forward doing this to LiteEditor/CMakeLists.txt :

```
+#        find_package(GTK2)
+#        if (GTK2_FOUND)
+#            include_directories(${GTK2_INCLUDE_DIRS})
+#        else (GTK2_FOUND)
+#            message(FATAL_ERROR "Could not locate GTK.")
+#        endif (GTK2_FOUND)
+
+		find_package(PkgConfig)
+		pkg_check_modules(GTK gtk+-2.0)
+		include_directories(${GTK_INCLUDE_DIRS})
```
But I don't really know what I do here (copy paste from a deep mail exchange found on the web) and I had to patch all the CMakeLists.txt files so I gave up :)

> You don't have to open a PayPal account to donate using the PayPal channel, you can use debit/credit card. I will check stripe site (have to admint, never heard of it)

I just don't want to give more money to PayPal (I'm already forced to do it too often because of their quasi-monopoly). I really dislike the ultra-neo-liberal positions of their CEO and I hate monopolies so I'll wait to see if Stripe suites you :)

**Comment by eranif** [comment]
Is your workspace located on a network drive or anything of this type?

>  I'll wait to see if Stripe suites you :)

It does. However, Israel is not supported at the moment, so its out of my hands...
You can contribute by debugging this bug ;)

**Comment by demos** [comment]
> Is your workspace located on a network drive or anything of this type?

Nope, my main SSD.

> It does. However, Israel is not supported at the moment, so its out of my hands...

Sad...

> You can contribute by debugging this bug ;)

I will probably begin by the build issue as it won't be easy to debug without it ;)

**Comment by eranif** [comment]
Any progress on debugging this?
