### ISSUE TITLE
Autocompletion not working correctly

### ISSUE THREAD

**Issue by calcyss** [eranif/codelite#1204]
As the title says, auto correction is not working properly for me. 
[See this related SO question](http://stackoverflow.com/questions/35991003/codelite-autocompletion-not-really-working). Just posting this here, in case it is indeed a bug.

**Comment by eranif** [comment]
What do you have under `Settings->Code Completion->CTags->Search Paths`?

**Comment by eranif** [comment]
I just tested this and it works for me.
![mutex](https://cloud.githubusercontent.com/assets/3677711/13752533/d154e858-ea17-11e5-9c18-1fe6db594ded.png)
![chrono](https://cloud.githubusercontent.com/assets/3677711/13752534/d189ade0-ea17-11e5-88aa-3d2fe588d75f.png)


Few notes:
* After you type, try to hit `Ctrl-S` (parsing is done on file save)
* Double check that the search paths for code completion are set up properly

**Comment by calcyss** [comment]
Well, cant check right now - but i believe only the TDM GCC default search paths. i Got autocompletion mostly fixed though - autocomplete delay set to 1 char seemed to fix it. the weird header path autocompletion persists though.

**Comment by eranif** [comment]
See my comment on SO

**Comment by eranif** [comment]
The file completion is not going to be fixed  - a simple workaround: keep on typing and it will shrink the results properly

**Comment by calcyss** [comment]
Weird, after 2 days of it working like it should, autocompletion isnt working again.
Didn't change a thing either.

**Comment by calcyss** [comment]
![pic](https://cloud.githubusercontent.com/assets/15906669/13818228/5c6d3a5c-eb95-11e5-87ad-5884a3e2b0ec.PNG) 

It just suddenly stopped working.
Here are my search paths for CTags:

![pic2](https://cloud.githubusercontent.com/assets/15906669/13818305/a90a188a-eb95-11e5-8acb-e23dbc394324.PNG)

Do you have any idea why?
It shows namespaces and some members, but it wont show others. weird.

**Comment by eranif** [comment]
I have no idea why, try:
main menu bar->workspace->parse workspace
and see if it helps
You can also enable `clang` code completion

**Comment by calcyss** [comment]
tried everything. nothing is working so far. already parsed the workspace a number of times.
Now, when bressing CTRL+ENTER after the opening dots of the `std::chono::` namespace, there are symbols in there that dont belong there, like my `GameWindo`, which is in the `cyss` namespace!

![unbenannt333](https://cloud.githubusercontent.com/assets/15906669/13818819/b27b5544-eb97-11e5-83c4-b9a39ae42d24.PNG)

**Comment by eranif** [comment]
`Ctrl-ENTER` and `Ctrl-SPACE` are two different things.
`Ctrl-ENTER`  - is the "Word Completion" plugin it will complete based on words found in all open editors
`Ctrl-SPACE` - triggers code completion (context aware)

**Comment by calcyss** [comment]
A minor side not: Sometimes codelite kicks out my compiler settings, like now, i had to set the compiler again to build my project and then the path to GDB was invalid. fixing that, then restarting laptop+CL

**Comment by calcyss** [comment]
wtf... it still doesn't want to work. what a shame, really. and it yesterday still, too.

**Comment by eranif** [comment]
Can you attach a sample source file with the problem? and let me debug it here
Thanks

**Comment by calcyss** [comment]
i will. 

[main2.zip](https://github.com/eranif/codelite/files/176441/main2.zip)

See attached zip, github wont let me upload .cpp/.cxx files.

**Comment by eranif** [comment]
I managed to reproduce your original problem (from SO). The difference is that I was testing using MinGW GCC 4.9.2 / 64 and you are using v5.1

I am investigating this now, will update - stay tuned!

**Comment by calcyss** [comment]
alright thank you! BTW, CodeLite is pretty awesome, thanks for the IDE :D

**Comment by eranif** [comment]
Update: I found the problem: 
When calling `Workspace->Parse Workspace` CodeLite collects a list of files that should be parsed (i.e. it crawls through the include statements in the code and creates a list of files to parse)

`chrono` has no extension and therefor it was filtered out...
I solved this issue along time by examining the file content by [searching for patterns](https://github.com/eranif/codelite/blob/master/CodeLite/fileextmanager.cpp#L132)

This logic is now also applied for parsing.

You might ask: OK, so why it worked sometimes !?
The answer is simple:
when hitting `Ctrl-S` CodeLite parses a single file + all its includes - and this code does not filter any header files.

Ok, so why different logics ? because a workspace may contain binary files (e.g. executables and basically any file type that you might think of) so when parsing the entire workspace we filter only relevant files ;)

**Comment by eranif** [comment]
Please try this installer with a fix and keep me updated:
http://codelite.org/downloads/codelite/weekly/wip/codelite-amd64-9.15.exe

**Comment by calcyss** [comment]
![unbenannt24](https://cloud.githubusercontent.com/assets/15906669/13824963/92967f10-ebb0-11e5-9381-4fba1a26aa4a.PNG)

just installed it... seems to work now :+1:  :smile: thanks for your time! i really appreciate all your work.

**Comment by eranif** [comment]
Good to hear ;)
Can you also close SO question ? thanks!

**Comment by calcyss** [comment]
OK, sorry to still bug you about this, but this is weird:
This is in the file main2.cpp that i sent you:

![file1](https://cloud.githubusercontent.com/assets/15906669/13825080/37029692-ebb1-11e5-98a3-ff9b6c4a3aff.PNG)

And this is in the file main.cpp in the same workspace and project:

![file2](https://cloud.githubusercontent.com/assets/15906669/13825111/5c7f2494-ebb1-11e5-8db3-33538c4b706a.PNG)

How come it works in one file, but not in the other one? i already reparsed the project and all that.
Weirdly enough, in both cases, it finds the `micro`- and `milliseconds` members.

**Comment by eranif** [comment]
Can you send me the workspace? or is it closed source?
Eran

**Comment by calcyss** [comment]
oh, no it's not. i'm just gonna push to the repo and send you the link, hold on a sec.

**Comment by calcyss** [comment]
the `origin/new` branch contains the code.

**Comment by eranif** [comment]
of which project? (github link)

**Comment by calcyss** [comment]
[sorry, but the project is hosted on gitlab :stuck_out_tongue: ](https://gitlab.com/calcyss/cysslib)

**Comment by calcyss** [comment]
and? have you found anything out? code completion works only in main2.cpp, but not in main.cpp or the `cysslib` namespace at all, for that matter.

**Comment by eranif** [comment]
I checked out the sources last night, and was not able to switch the the branch you mentioned...
It was late so I must have be done something stupid... will try again this evening

**Comment by calcyss** [comment]
hm
weird. the `new` branch defo exists, just pushed to it.

**Comment by eranif** [comment]
I agree, it must be the late hours ;)

**Comment by calcyss** [comment]
be aware that the `.codelite` and `.clang` directories are ignored on the git repo, so i guess it will reparse when you open the workspace. Autocompletion doesn't work, even with multiple full reparses.

**Comment by eranif** [comment]
I noticed that you added many files that should not be part of the repo. 
All the folders that start with `.` (e.g. `.clang`, `.codelite`) should not be added to the repo.

Also, don't add the `.txt` file and generated makefiles

**Comment by calcyss** [comment]
Did you find anything out? Code Completion is still only partially working.
btw, updated the .gitignore file a while back.

**Comment by eranif** [comment]
It works for me. 

You can enable the `clang` code completion (which works as complementary system to the in-house parser) - usually this works pretty well (i.e. if your project can compile, than the clang code completion will code complete what the in-house parser fails to complete)

To enable it:
Settings->code completion->clang->enable clang code completion
Once enabled, its recommended to run a full rebuild of your workspace

**Comment by calcyss** [comment]
really weird. The autocompletion works for the same workspace in CodeLite
6.1.1, flawlessly.

**Comment by eranif** [comment]
Did you enable `clang` ?

**Comment by calcyss** [comment]
not yet, will try it out later this evening.
