### ISSUE TITLE
Install warning using Ubuntu Software Centre

### ISSUE THREAD

**Issue by iwbnwif** [eranif/codelite#1205]
A "The package is of bad quality" warning is generated when installing Codelite 9.1.4 (and 9.1.3) from the .deb using Ubuntu Software Centre (default action for a .deb).

The full error message is:
`The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.`

And the details are:
`Lintian check results for /home/mikerothon/Downloads/CodeLite-9.1.4-ubuntu-trusty-x86_64.deb:
E: codelite: control-file-has-bad-permissions md5sums 0664 != 0644`

**Comment by eranif** [comment]
This is not going to be fixed (as explained in numerous of times)
The package is generated via `CPack` and this is the quality it gets - this particular error can not be fixed unless a new CMake version is installed (3.0 and later)

The package runs just fine, you can choose to install it or simply wait for an official release (for which the deb files are generated in a different way and are used via our apt system)

**Comment by iwbnwif** [comment]
Apologies, I did search to see if it had been asked before but didn't find anything. Clearly not thoroughly enough.

It installed just fine with dpkg.
