### ISSUE TITLE
Strange color highlight at Search result

### ISSUE THREAD

**Issue by benqqq** [eranif/codelite#1207]
It can reproduce on Codelite win64 v9.4.1 and older versions.

For example, the screenshot is to search "shift" keyword at workspace
![search2](https://cloud.githubusercontent.com/assets/13009249/13801384/2a5a25f8-eb6c-11e5-9374-2fc32db04256.png)

![search](https://cloud.githubusercontent.com/assets/13009249/13801315/c5a243b6-eb6b-11e5-9647-a0503303eb20.png)

**Comment by eranif** [comment]
It has to do with the file encoding. Is it possible to attach the file `ceir.c` to this issue?

**Comment by benqqq** [comment]
sorry, because the source code is proprietary not open source, I can't provide the entire file.
Is there any other way I can support you to this issue?
