### ISSUE TITLE
Cannot build project with mingw-w64 (x86_64-5.3.0-release-posix-seh-rt_v4-rev0)

### ISSUE THREAD

**Issue by renkun-ken** [eranif/codelite#1208]
I download the mingw-w64 (x86_64-5.3.0-release-posix-seh-rt_v4-rev0) toolchain and use CodeLite to build my test project. But the following errors occur:

```
C:\WINDOWS\system32\cmd.exe /C C:/mingw-w64/x86_64-5.3.0-release-posix-seh-rt_v4-rev0/mingw64/bin/mingw32-make.exe -j4 SHELL=cmd.exe -e -f  Makefile
"----------Building project:[ basics - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'D:/Workspaces/learn-cpp/basics'
g++.exe: error: main.cpp\: Invalid argument
g++.exe: fatal error: no input files
compilation terminated.
mingw32-make.exe[1]: *** [Debug/main.cpp.o.d] Error 1
mingw32-make.exe[1]: *** Waiting for unfinished jobs....
basics.mk:99: recipe for target 'Debug/main.cpp.o.d' failed
mingw32-make.exe: *** [All] Error 2
mingw32-make.exe[1]: Leaving directory 'D:/Workspaces/learn-cpp/basics'
Makefile:4: recipe for target 'All' failed
====1 errors, 0 warnings====
```

If __pass object list to the linker via file__ is checked, the error will be same as #1008. I uncheck it according to http://stackoverflow.com/questions/33544658/linker-error-in-codelite-with-mingw-w64/33562052#33562052 but the error changes to the above.

**Comment by eranif** [comment]
Your problem is in the compile stage, not at the link time, so the **pass object list to the linker via file** solution is not relevant.

This looks like a buggy `mingw32-make` to me. Can you try this:

- Download (TDM-GCC-64)][http://sourceforge.net/projects/tdm-gcc/files/TDM-GCC%20Installer/tdm64-gcc-5.1.0-2.exe/download]  and extract it somewhere
- Copy TDM's `mingw32-make` with the one that comes in your package and try again

**Comment by renkun-ken** [comment]
Thanks. I use TDM-GCC-64 as you suggested in another issue and CodeLite works perfectly with it. One of my project needs mingw-w64 and I want to try this but this error prevents me from compiling the project. Let me try the copy.

**Comment by renkun-ken** [comment]
I copy TDM's `mingw32-make` to mingw-w64 and the build works. Since I also want to try `gdb.exe` in the mingw-w64 distribution, I start debugger but an error message says: _Debugger exited with the following error string: "During startup program exited with code 0xc000007b."_ The debugger does not seem to work either :(

**Comment by eranif** [comment]
This means that you have a problem with your build. i.e. you are building a 64 bit application but there is some image mismatch (i.e. your application tried to load a 32 bit dll)

http://stackoverflow.com/questions/10492037/the-application-was-unable-to-start-correctly-0xc000007b

This is not really related to CodeLite and you are more than welcome to continue this discussion on either our [gitter chat](https://gitter.im/eranif/codelite) or on [CodeLite's forum](http://forums.codelite.org)

**Comment by renkun-ken** [comment]
Thanks!
