### ISSUE TITLE
Replace with regular example

### ISSUE THREAD

**Issue by Efluminor** [eranif/codelite#1209]
I'm able to search/find in the code using regular expresion, but not for replace. For example something like that:
find: (color)(\[)(([A-B]|[_]|[a-z])*)(\]\[)(0)(\])
replace: \1\2\3\4R\6

the find it's working fine, but not the replace.

May be the format for replace it's other, but i don't see nothing relative in the documentation.

Regards.

**Comment by eranif** [comment]
Working fine here. Which version of CodeLite are you using?

**Comment by Efluminor** [comment]
CodeLite version: 9.1.0
I'm using the dialog
string Match:
glColor4ub(COLOR[M_RED][0], COLOR[M_RED][1], COLOR[M_RED][2], COLOR[M_RED][3]);
expected :
glColor4ub(COLOR[M_RED][R], COLOR[M_RED][1], COLOR[M_RED][2], COLOR[M_RED][3]);
obtained:
glColor4ub(,  \1\2\3\4R\6, COLOR[M_RED][1], COLOR[M_RED][2], COLOR[M_RED][3]);

**Comment by eranif** [comment]
The dialog does not support replace place holder (\1, \2 etc)
Use the "Find" (`Ctrl-F`) - the replace field there support this.

Note that in 9.1.4 and later the dialog was removed and its functionality was moved to the find bar at the bottom

**Comment by Efluminor** [comment]
Ok, thanks.

The problem is with "Find", I can't find in all project code files, isnt it?

Codelite 9.1.0, elementary OS 0.3.2 Freya (64-bit) (ubuntu 14.04), not self build.

**Comment by eranif** [comment]
When you mentioned earlier that you are using the dialog, which one? Can you post a screenshot?
To search the entire workspace (or replace) use: `Ctrl+Shift+F`

**Comment by Efluminor** [comment]
I'm using Ctrl+Shift+F
You can see the screenshot
![findinfiles](https://cloud.githubusercontent.com/assets/6470284/13872335/32e7a3ba-ecea-11e5-8a50-b3b843bf98f6.png)
