### ISSUE TITLE
Jumps to methods by clicking on their name in the outline is wrong when some are folded in PHP

### ISSUE THREAD

**Issue by jclaveau** [eranif/codelite#1210]
If you fold a lot of methods of a class in PHP then jump to one which is under the folded ones, the folded number of lines is not considered. And the caret will be placed far below the expected line.

**Comment by eranif** [comment]
I can't seem to reproduce this, I folded all functions and it always expand and select the correct one
Any more hints on how to reproduce this? (also: OS, CodeLite version)

**Comment by jclaveau** [comment]
Xubuntu 15.10 with Codelite 9.1.4.

I'm able to reproduce it with a trait and a class. I fold the several upper methods and then, when I jump to methods below, I arrive some lines under the expected one. If I unfold the methods, it works well again.

One weird thing is that I folded 45 lines and jumped ~30 lines under the method declaration.
