### ISSUE TITLE
Find in files: Unable to add locations after removing existing one

### ISSUE THREAD

**Issue by rp42** [eranif/codelite#1212]
* Open Find in Files dialog
* Click [-] button to remove entries from "look in" list
* Click [+] to add new entry to list
* All option on drop down menu are greyed out:
<img width="974" alt="screen shot 2016-03-21 at 14 28 16" src="https://cloud.githubusercontent.com/assets/8833792/13921744/3f3cb0b8-ef71-11e5-9c7f-9b993278e201.png">
* Problem persists after restarting codelite and changing workspace

I think this used to work, but perhaps I did things in a different order this time

Running Codelite 9.1.4 on OS X 10.11.3

**Comment by eranif** [comment]
Thanks for reporting this, I guess that this is OSX only.
Try this: 
- In the left tree, select the "Explorer" tab
- If you don't have any folder opened there, open one (right click on the grey pane and select "Open Folder")
- Select one of the folders and open the find-in-files dialog - this should add the location automatically to the find-in-files dialog

**Comment by rp42** [comment]
It seems that works to add individual directories :-). The drop down in the Find in Files dialog is still grey though, but this if fine as a workaround.

**Comment by eranif** [comment]
A better workaround:
* Close CodeLite
* Open the `/Users/YOU/Library/Application Support/codelite/config/codelite.conf`
* Look for `"m_lookIn":` field
* Add `"<Entire Workspace>"` to the array of options

**Comment by eranif** [comment]
This appears to be a new bug introduced in wxWidgets 3.1 version (the 9.1.4 build is using this build)
http://trac.wxwidgets.org/ticket/17459

**Comment by eranif** [comment]
Since the wxWidgets bug is not fixed, I implemented a workaround for OSX only.
It no longer uses a drop down menu for adding locations, instead you get a small helper dialog where you can add/remove all at once
