### ISSUE TITLE
Missing debugger functions in the main menu and hotkey list

### ISSUE THREAD

**Issue by xuancong84** [eranif/codelite#1216]
During debugging, the functions "jump to cursor" and "run to cursor" are available only in the right-click context menu, but they are not present in the main menu, neither can I assign hotkeys to them. So it is very inconvenient during debugging -:(

**Comment by flederwiesel** [comment]
I would like to see this one as well...

**Comment by eranif** [comment]
NOTE: in order to see the new menu entries in the shortcuts dialog, you wll need to click on the "Defaults" button in the "Keyboard Shortcuts" dialog

**Comment by xuancong84** [comment]
It crashes, by popping up a dialogue, "codelite crashed: you may attach to it using gdb
or let it crash silently..
Attach debugger?"

I am using Ubuntu 14.04.4, all dependencies are installed by first "dpkg -i Codelite.9.1.4.deb" and then "apt-get -f install". It crashes immediately upon start.

**Comment by eranif** [comment]
What crashed? This fix was not yet released...

**Comment by xuancong84** [comment]
I mean the Codelite in git hub repository, after the additional "Keyboard Shortcuts" patch.

**Comment by eranif** [comment]
Do you get an error in `~/.codelite/codelite-stdout-stderr.log` probably a missing symbol from a bad build

**Comment by xuancong84** [comment]
No, the log file is empty.
The console output is:
*** Error in `./codelite': free(): invalid pointer: 0x00007fcd0100d3f8 ***
Aborted (core dumped)

**Comment by xuancong84** [comment]
Thanks a lot! It is working in the new version 9.1.5
