### ISSUE TITLE
Unable to start bash

### ISSUE THREAD

**Issue by GFdevelop** [eranif/codelite#1217]
git plugin work right with git for windows but if I uninstall git for windows and install msys2 git, work all but the bash not start, I have error "don't know how to start MSYSGIT..."

**Comment by eranif** [comment]
CodeLite uses the regsitry to locate GIT bash shell location.
It searches in these locations:

```
SOFTWARE\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Git_is1
SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Git_is1
```

for the key:

```
InstallLocation
```

Can you tell me what is the equivalent locations on your machine?
Eran

**Comment by eranif** [comment]
@GFdevelop alternatively, can you point me to the installer you used for installing GIT bash?

**Comment by GFdevelop** [comment]
I am installed git with the msys2 by the command "pacman -S git", it install git in the default path there is C:\msys64\usr\bin
The bug is the registry search, you have to change the find location dinamically...

**Comment by eranif** [comment]
> The bug is the registry search

I know

> you have to change the find location dinamically

How does this works exactly? every user can install MSYS git where he/she wants, how should CodeLite guess the location? it can only work with pre-existing registry entries

**Comment by GFdevelop** [comment]
You can make that the user give the install path and git plugin look in this location if it exists...
