### ISSUE TITLE
Is Qt Project still as http://codelite.org/LiteEditor/QmakePlugin ?

### ISSUE THREAD

**Issue by jiapei100** [eranif/codelite#1221]
Looks like Codelite is still **NOT** well dealing with qt project ???
Do we need a **.pro** to build Qt project?
It looks like a simple Qt Test project doesn't come with a .pro file, which is supposed to be generated automatically?

What's more, Codelite 9.1.5 is still using** Qt4**? Well, Qt5.6.0 is out already. I changed the environmental settings for my Qt Project, after building, it doesn't run at all...
```
Current working directory: ...../testonly/Debug
Running program: /usr/bin/codelite_xterm './testonly ' '/bin/sh -f /usr/bin/codelite_exec LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/Qt-5.6.0/lib ./testonly'
**Program exited with return code: 0**
```

Cheers
Pei

**Comment by eranif** [comment]
> What's more, Codelite 9.1.5 is still using** Qt4**?

CodeLite does not use Qt4/5 or any Qt at all... 

> It looks like a simple Qt Test project doesn't come with a .pro file, which is supposed to be generated automatically?

Yes, the QMake plugin should do so

**Comment by eranif** [comment]
Seems like no one touched Qt based projects with CodeLite in over 6 years now...
it seems broken :(

Looks like its time to re-write the QMake plugin

**Comment by jiapei100** [comment]
^_^ Yup... It's already 6 years... How is your life there in Spain? ^_^
If you don't support Qt, I'll go for qtcreator... ^_^

**Comment by eranif** [comment]
> ^^ Yup... It's already 6 years... How is your life there in Spain? ^^

??

> If you don't support Qt, I'll go for qtcreator... ^_^

So I suggest you switch to QtCreator

**Comment by mtangoo** [comment]
>So I suggest you switch to QtCreator

Lol!
