### ISSUE TITLE
Environment variables not working right

### ISSUE THREAD

**Issue by GFdevelop** [eranif/codelite#1222]
In the release 9.1.5 codelite is unable to scan for installed compilers in the path of environment variables of codelite (not global variables).

**Comment by eranif** [comment]
I don't understand this one...
can you please provide an example (a detailed one)

**Comment by GFdevelop** [comment]
I have added this environment variable "PATH=C:\msys64\mingw64\bin;$PATH" from the menù of codelite, after this, I have used "scan for installed compilers" and it not find gcc compiler...in the 9.1.4 it not have this problem.

**Comment by eranif** [comment]
I doubt this worked before. The compiler detection code was not modified...
The current code loads the environment variable `PATH` and searches for `gcc.exe` or `g++.exe` - but without applying CodeLite's environment variables
