### ISSUE TITLE
Git plugin

### ISSUE THREAD

**Issue by GFdevelop** [eranif/codelite#1224]
Codelite crash when I try to push, I have this error:

**error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument**

from command line I have typed

**git config user.name**

and it give me "GFdevelop".

**Comment by eranif** [comment]
This bug is not very useful. Please run CodeLite under debugger and attach a backtrace

**Comment by GFdevelop** [comment]
How to run codelite under debugger? I have find the solution, the problem is not global settings but system settings, I have open bash and I have typed git config --system user.name "GFdevelop" and then the email and now work done.

**Comment by eranif** [comment]
```
gdb /usr/bin/codelite
...
```

When gdb prompt appears:
```
(gdb)
```

type
```
(gdb)run
```

**Comment by GFdevelop** [comment]
$ gdb '/c/Program Files/CodeLite/codelite.exe'
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from C:/Program Files/CodeLite/codelite.exe...(no debugging symbols found)...done.
(gdb) run
Starting program: C:\Program Files\CodeLite\codelite.exe
[New Thread 6256.0x26ec]
[New Thread 6256.0x1d10]
[New Thread 6256.0x15c4]
[New Thread 6256.0x2890]
[New Thread 6256.0x1d0c]
[New Thread 6256.0x215c]
[New Thread 6256.0x50c]
[New Thread 6256.0x2228]
[New Thread 6256.0x598]
[New Thread 6256.0x2510]
[New Thread 6256.0x9fc]
[New Thread 6256.0x14d0]
[Thread 6256.0x2510 exited with code 0]
[New Thread 6256.0x2c18]
[New Thread 6256.0x480]
[New Thread 6256.0xc10]
[New Thread 6256.0x2930]
[New Thread 6256.0x1bb0]
[New Thread 6256.0x1a90]
[New Thread 6256.0x1660]
[New Thread 6256.0xed0]
[New Thread 6256.0x1108]
[New Thread 6256.0x20d4]
[New Thread 6256.0x229c]
[New Thread 6256.0x2c10]
[New Thread 6256.0x2fec]
[New Thread 6256.0x2044]
[New Thread 6256.0xa04]
[New Thread 6256.0x2264]
[New Thread 6256.0x2a4c]
[New Thread 6256.0xac0]
[Thread 6256.0xac0 exited with code 0]
[New Thread 6256.0x2d6c]
[Thread 6256.0x2d6c exited with code 0]
[New Thread 6256.0x2694]
[Thread 6256.0x2694 exited with code 0]
[New Thread 6256.0x2388]
[Thread 6256.0x2388 exited with code 0]
[New Thread 6256.0x2524]
[Thread 6256.0x2524 exited with code 0]
[New Thread 6256.0x16d0]
[Thread 6256.0x16d0 exited with code 0]
[New Thread 6256.0x27ec]
[Thread 6256.0x27ec exited with code 0]
[New Thread 6256.0x2570]
[Thread 6256.0x2570 exited with code 0]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00000000623c49d0 in git!GetPluginInfo ()
   from C:\Program Files\CodeLite\plugins\git.dll

**Comment by eranif** [comment]
is this a self compiled CodeLite? or an official one?

**Comment by GFdevelop** [comment]
Official 64 bit version 9.1.5

**Comment by eranif** [comment]
when CodeLite crashes, please run:
```
(gdb)bt
```

**Comment by mtangoo** [comment]
I faced this issue for sometimes and here are helpful details.
CL cannot push changes to password protected repository. 
So it seems CL Git plugin does not handle password-ed repos

**Comment by GFdevelop** [comment]
(gdb) bt
#0  0x00000000623c49d0 in git!GetPluginInfo ()
   from C:\Program Files\CodeLite\plugins\git.dll
#1  0x00000000699c3386 in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const ()
   from C:\Program Files\CodeLite\wxmsw310u_gcc_cl.dll
#2  0x0000000069b27f1f in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()
   from C:\Program Files\CodeLite\wxmsw310u_gcc_cl.dll
#3  0x0000000069b284a4 in wxEvtHandler::SearchDynamicEventTable(wxEvent&) ()
   from C:\Program Files\CodeLite\wxmsw310u_gcc_cl.dll
#4  0x0000000069b2878e in wxEvtHandler::TryHereOnly(wxEvent&) ()
   from C:\Program Files\CodeLite\wxmsw310u_gcc_cl.dll
#5  0x0000000069b2882d in wxEvtHandler::ProcessEventLocally(wxEvent&) ()
   from C:\Program Files\CodeLite\wxmsw310u_gcc_cl.dll
#6  0x0000000069b28888 in wxEvtHandler::ProcessEvent(wxEvent&) ()
   from C:\Program Files\CodeLite\wxmsw310u_gcc_cl.dll
#7  0x0000000069b29717 in wxEvtHandler::ProcessPendingEvents() ()
   from C:\Program Files\CodeLite\wxmsw310u_gcc_cl.dll
#8  0x00000000699c51ef in wxAppConsoleBase::ProcessPendingEvents() ()
   from C:\Program Files\CodeLite\wxmsw310u_gcc_cl.dll
#9  0x00000000699fde41 in wxEventLoopManual::ProcessEvents() ()
   from C:\Program Files\CodeLite\wxmsw310u_gcc_cl.dll
#10 0x00000000699fdf1b in wxEventLoopManual::DoRun() ()
   from C:\Program Files\CodeLite\wxmsw310u_gcc_cl.dll
#11 0x00000000699fdc24 in wxEventLoopBase::Run() ()
   from C:\Program Files\CodeLite\wxmsw310u_gcc_cl.dll
#12 0x00000000699c7601 in wxAppConsoleBase::MainLoop() ()
   from C:\Program Files\CodeLite\wxmsw310u_gcc_cl.dll
#13 0x0000000069a472f8 in wxEntryReal(int&, wchar_t**) ()
   from C:\Program Files\CodeLite\wxmsw310u_gcc_cl.dll
#14 0x00000000004013e8 in ?? ()
#15 0x00000000004014eb in ?? ()
#16 0x00007fff3a768102 in KERNEL32!BaseThreadInitThunk ()
   from C:\WINDOWS\system32\kernel32.dll
#17 0x00007fff3a98c5b4 in ntdll!RtlUserThreadStart ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#18 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**Comment by eranif** [comment]
Does this still happens with CodeLite 10?

**Comment by mtangoo** [comment]
Since somewhere in 9.x it have been solved on my Ubuntu box. I will try to see on Mac and Windows.
Others can help confirm though
