### ISSUE TITLE
Search in file check marks uncheck themselves

### ISSUE THREAD

**Issue by bigangrydog** [eranif/codelite#1226]
This one is infuriating me at the moment. If I do search/replace in files it brings up a list with "red triangle" check marks for each item. This is great.

The problem is when I click a link (not a check), it them unchecks everything. The thing is, on a complex search/replace operation, I can spend 5 minutes or so carefully working my way through each item, deciding whether I want to replace it or not. Then if I click a link to see the code on particular item, it automatically unchecks everything, undoing all the options. Version 9.1.5.

Options should not uncheck themselves like this.

**Comment by eranif** [comment]
> This one is infuriating me at the moment.

Hence the name? 

> Options should not uncheck themselves like this.

Sounds like a bug to me, will look into it

**Comment by bigangrydog** [comment]
Yeah! :)
