### ISSUE TITLE
How to display UTF8 characters in debug variable display?

### ISSUE THREAD

**Issue by xuancong84** [eranif/codelite#1227]
When I have a string of UTF-8 content, variable watch displays '\234\254\122' etc. instead of the actual UTF-8 character. So how to show UTF-8 characters?

**Comment by eranif** [comment]
Please use the proper platform to ask questions:
* Gitter: https://gitter.im/eranif/codelite
* IRC channel #codelite / irc.freenode.net
* Forum http://forums.codelite.org

**Comment by xuancong84** [comment]
Since you have applied the patch for Issue #1225, would you add the following line into the built-in GDB pretty printer init script as well:
`set print sevenbit-strings off`

If you have UTF-8 string, std::string s("￥，。；【】");
By default, the debug display when viewing string s is `"\357\277\245\357\274\214\343\200\202\357\274\233\343\200\220\343\200\221"`

After you set the GDB sevenbit-strings off, the debug display becomes `"￥，。；【】"`.

The latter is more suitable and appropriate, and thus should be set as the default behaviour.
Thanks!

**Comment by eranif** [comment]
> Since you have applied the patch for Issue #1225

what patch?

> set print sevenbit-strings off

You can add it locally from: settings->GDB Settings->Startup commands

> The latter is more suitable and appropriate, and thus should be set as the default behaviour

Usually, such changes (especially when it comes to display strings) comes with a performance penalty.
I will give it a try and see if it affects performance

**Comment by xuancong84** [comment]
Thanks! Yup, appending `set print sevenbit-strings off` to the end of `settings->GDB Settings->Startup commands` works.
However, appending it to the end of $HOME/.gdbinit does not work.

**Comment by eranif** [comment]
If you look closely into how CodeLite starts gdb, you will notice is "sources" a different file and not $HOME/.gdbinit
