### ISSUE TITLE
Cannot install codelite 9

### ISSUE THREAD

**Issue by weaponx69** [eranif/codelite#1228]
I cannot install codelite 9.  I purged the old codelite as instructed and did a sudo apt-get update before running this.  I have everything added to my repos like instructed also.  I'm using the Wily version.  Everytime I try to install codelite, I get this error.  

 sudo apt-get install codelite wxcrafter
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 codelite : Depends: libclang1-3.6 (>= 3.2) but it is not going to be installed
            Depends: liblldb-3.6 but it is not going to be installed
            Depends: libclang1 but it is not going to be installed
            Recommends: lldb (>= 3.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
brian@brian-MS-7699:~$

It always breaks my repo too and I have to fix it.

**Comment by xuancong84** [comment]
Hi. This is the Ubuntu repository problem, not Codelite's problem. They have not yet settle all the dependencies properly. You can install Codelite by:
1. download the .deb file (latest version is 9.1.5)
2. sudo dpkg -i codelite-9.1.5.deb (this install the package)
3. sudo apt-get install -f (this fixes all dependency issues)
It works on my Ubuntu 14.04.3.
