### ISSUE TITLE
Upon clicking on error code, codelite asks to choose between two files which are the same

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1229]
Under:
Xubuntu 15, Codelite 9.15 (non-self-built)

With multiple projects in a single workspace, and two of the projects referencing the same files eg. a single file "dance.h" is included in the src for both project A and project B,
if I compile project A, get an error in the dance.h, try to click on the error to find the location in the file, codelite will ask me whether I want to look at the dance.h in project A or B, even though they're the same file with the same path.

**Comment by eranif** [comment]
Can you provide a screenshot with this dialog?
