### ISSUE TITLE
Codelite hangs when using autocompletion.

### ISSUE THREAD

**Issue by darkdan92** [eranif/codelite#1230]
Under:
Windows 7, Codelite 9.1.5

Steps to reproduce:
Press Ctrl+Space, but autocompletion after . or -> works fine.

I did a little investigation, and that's what I noticed.
Call stack at the time freezing looks like this:
CxxTemplateFunction::CanTemplateArgsDeduced
TagsManager::TagsByScopeAndName
TagsManager::WordCompletionCandidates

**Comment by eranif** [comment]
Usually in such cases, a small workspace to show the problem is the preferred way

**Comment by eranif** [comment]
@darkdan92 can you please provide the full backtrace? and not only just these 3 entries
