### ISSUE TITLE
Codelite will not open file from build error message if file is not in source list

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1233]
Version: 9.15, non-self-compiled
OS: Windows 7

If a file is included as a header, and it's location is specified in the project's include list, but the file itself is not included in the project's source list,
codelite will identify any errors in the header file on compilation, but clicking on the error message will not load the file in the codelite editor window.

**Comment by xuancong84** [comment]
It is best for you to do it in Visual Studio's way, create a virtual folder called "headers", and add all header files.
This is actually not a bug. What is indeed a bug is that when you delete a source file externally, and not delete that file in the project, you will get a compilation error, "No rule in makefile".

**Comment by mattreecebentley** [comment]
Perhaps I'm not understanding this correctly, but surely if codelite can read the file, it should be able to load it in the editor?

**Comment by xuancong84** [comment]
Codelite does not read the file. Codelite captures the error message from compilation, and parse it to know the filename and the line number. Thus, if the filename is not in the project's include list, currently, for simplicity, it will not do anything.

**Comment by mattreecebentley** [comment]
Okay, I understand what you're saying, but for the purposes of editing, if the compiler is able to report an error in a file then that proves it exists - therefore, codelite should be able to open it, regardless of whether it's officially included in the project? Codelite is able to identify which file the compiler identifies as having an error, including the path of the file (at least from gcc output) so is it not trivial to open it?
