### ISSUE TITLE
Build output messages cannot display Chinese text correctly

### ISSUE THREAD

**Issue by neolib** [eranif/codelite#1236]
For example, on my Chinese Windows 10, if a post-build script has copy command, the output text of copy is messed up.

**Comment by neolib** [comment]
I guess most of CodeLite components are not i18n ready.

![cl-term](https://cloud.githubusercontent.com/assets/10727052/14451669/7eb4a826-00bb-11e6-8a12-eef6b22911e7.png)

**Comment by eranif** [comment]
Since I don't have the ability to test this, I don't plan on investing time fixing this.
please feel free to fix this and send a pull requset
