### ISSUE TITLE
Horizontal scrollbar does not always reach end of line when auto-adjust horizontal scrollbar disabled

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1237]
v9.15 nonself-compiled, 
Win 7 x64

On long lines (> 248 characters wide), with auto-adjust horizontal scrollbar disabled, dragging the horizontal scrollbar all the way to the right doesn't actually reach end of line (stops a certain number of characters back from end of line - this character amount varies, suggesting a type problem). Re-enabling auto-adjust horizontal scrollbar fixes this. 
Closing the file, disabling auto-adjust, reloading the file and going to the same line re-instantiates the problem.

**Comment by eranif** [comment]
This is just how wxStyledTextCtrl works it uses a predefined length (which I agree is too small)
There is a simple workaround for reaching to the end of line: just hit END on the lengthy line with the keyboard and it will take you to the end of the line (and a side effect, the scrollbar will adjust its scrolling range)
