### ISSUE TITLE
editor display bug: incorrect handling of sticky characters

### ISSUE THREAD

**Issue by xuancong84** [eranif/codelite#1238]
It is quite amazing that the developers of Codelite, they themselves never use Codelite to develop C/C++ programs. If I am not correct, how could they NOT discover that for all non-monospace fonts, when you type 'f' followed by 'i', it will be joined into one single character 'fi' for display, so that the total number of characters is reduced by 1, and then the cursor position gets messed up.

To reproduce the bug: simply type the word "file", and use left/right arrow key to move your cursor and try to insert a character before 'l' or 'e', see what you get.

**Comment by eranif** [comment]
You really have a bad attitude. (I assume that it's also you here: https://sourceforge.net/projects/codelite/?source=directory in the 1 star comment)

FYI: we do use CodeLite to develop CodeLite and all our C++ work. I can't seem to reproduce this bug and frankly, I am not going to invest on this bug. 

Feel free to fix this and send us a pull request with a fix

**Comment by xuancong84** [comment]
Don't worry. I have already deleted my 1-star rating.

The problem is that this project has too many external dependencies. Compiling is really a headache. Some of the 3rd-party packages also has version compatibility problem. Only if you install a fresh copy of Ubuntu and try to build it from raw scratch, you will know how difficult it is.

**Comment by nessotrin** [comment]
I don't know if I should create a new issue since I have the exact issue described here.

When typing certain combination of characters ("ff" by example), the characters become fused and the visual cursor is shifted one caracter compared to the real one.
The issue can be repeated on the same line but stops at it's end.
I've had this problem ever since I started to use codelite (9.0 alpha), never found a way around it.

I'm on Manjaro linux (Archlinux derived, up-to-date) 64bit with codelite 9.2.0 coding in C++

**Comment by xuancong84** [comment]
I guess it might not be codelite's problem if codelite uses some external module to handle the edit window and that module is still buggy for now. The cause is that for certain true-type fonts such as "times new roman", when there is an i followed by f, it will output the joined cartograph "fi" instead of two separate cartographs f and i. Some ignorant developers does not know this, they always assume that the cartographical position of the cursor is always the character position, which is not true for this kind of fonts.

For a temporary workaround, you can change the font to any monospace font.

**Comment by AmmarkoV** [comment]
> I guess it might not be codelite's problem if codelite uses some external module to handle the edit window and that module is still buggy for now. The cause is that for certain true-type fonts such as "times new roman", when there is an f followed by i, it will output the joined pictograph "fi" instead of two separate pictographs f and i. Some ignorant developers does not know this, they always assume that the pictographical position of the cursor is always the character position, which is not true for this kind of fonts.
> 
> For a temporary workaround, you can change the font to any monospace font.

Had the same issue, switched to monospace font and its ok , thx!
