### ISSUE TITLE
Dependency of executable on library

### ISSUE THREAD

**Issue by jmansion** [eranif/codelite#1240]
What's the preferred way to declare that an executable depends on a library?

It would be nice to do this in a way that maps the build variant automatically.

I'm currently building ffptest which is a peer to ffplib, and I have:

```
  <Linker Options="" Required="yes">
    <LibraryPath Value="../ffplib/$(IntermediateDirectory)"/>
    <Library Value="ffplib"/>
  </Linker>
```

It seems unfortunate that ffplib is built in the project and is in the default location and I have specified that the library be built first (which seems to be the nearest to an automatic dependency thing).

Ideally I'd like to say:
 A depends on B

and have the include paths, link items set up automatically.

Have I missed it and there's a way to do it?

(Have just upgraded to 9.1 on Ubuntu, but it seemed the same in 8.0)

**Comment by eranif** [comment]
You did not miss it, it was never requested, so it was never implemented - simple as that ..
This looks like a big feature to implement, this means that it will take until I will get to it.
A pull request with the fix is the quickest way to implement this ;)

**Comment by eranif** [comment]
I don't think I will have time to implement  this. A PR with this is highly appreciated
