### ISSUE TITLE
allow modelines to override syntax highlighting

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#1242]
The files in LibreOffice all have something like this at the top of their files:

    #! /usr/bin/env python3
    # -*- Mode: python; tab-width: 4; indent-tabs-mode: t -*-

or

    /* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */

Which is useful when the file has no suffix, so that a smart editor can know what formatting to apply.

I believe these are called "vim modelines", although I could be wrong.

It would be nice if Codelite at least read the "mode" part of this to apply the correct syntax highlighting

thanks

**Comment by eranif** [comment]
FYI:
CodeLite already supports these kind syntax highlight detection:
https://github.com/eranif/codelite/blob/master/CodeLite/fileextmanager.cpp#L132
Its only matter of adding the proper "pattern" to search

Should be easy to fix - will do this later on today

**Comment by grandinj** [comment]
Thanks!
