### ISSUE TITLE
codelite endless loop in Edit / Replace

### ISSUE THREAD

**Issue by jjvbsag** [eranif/codelite#1248]
I wanted to comment out some lines with a text comment.
I selected the lines and did the following replace form

Find What: `^`   ¹)
Replace with `//DEADCODE//`
[x] Match case
[ ] Match whole word
[x] Regular expression
[ ] Search up
[x] Search / Replace in selected text

On `Replace all` codelite freezes with 100% CPU-Load

¹) Note: `^` is the regular expression for `Begin of line`

**Comment by eranif** [comment]
Which version of CodeLite? which OS?
Note that I am unable to reproduce this, is `^ ¹)` the correct search string? seems a bit odd...

**Comment by jjvbsag** [comment]
Sorry for the incomplete information.
Running CodeLite 9.1.0 on Kubuntu 14.04 LTS
The search string is a single `^` (Circumflex). 
The ¹) is my footnote (it was not highlighted as `code`).
Maybe also important: In the selected text there also was empty lines. Something like

```c++
	UBYTE     Len,
	Approved,
	ErrorFillChar;
	UWORD    i,
	j;
	WgWeight_t  Weight = *Weight_ptr;

	*Print_ptr_ptr = PrintBuf_ptr;

```

which was expected to be changed to

```c++
//DEADCODE//	UBYTE     Len,
//DEADCODE//	Approved,
//DEADCODE//	ErrorFillChar;
//DEADCODE//	UWORD    i,
//DEADCODE//	j;
//DEADCODE//	WgWeight_t  Weight = *Weight_ptr;
//DEADCODE//
//DEADCODE//	*Print_ptr_ptr = PrintBuf_ptr;
//DEADCODE//
```

**Comment by eranif** [comment]
The Find/Replace dialog was removed in CodeLite 9.1.5 and is now unified with the "Find" bar
Can you please try CodeLite 9.1.5? http://forums.codelite.org/viewtopic.php?f=20&t=3309

**Comment by jjvbsag** [comment]
I shall not install the weekly build on my production machine, as there is no way back due missing available versions in synaptic and the "trusty" repositories.

But I may try on a VM this weekend.
I will come back to you then...
Regards

**Comment by mtangoo** [comment]
@jjvbsag Weekly download does not need repo
Just uninstall CL and wxC if you installed it and install deb file from [here](http://downloads.codelite.org/downloads.php?ubuntu_1404_64_weekly)

**Comment by jjvbsag** [comment]
@mtangoo You got me wrong. I only wanted to say "On my _production machine_, where I cannot risk any problems, I will only install released versions of codelite, which can be installed from official repositories. And I will only install versions after a deep going test, that the new version has no breaking changes"

I will surely test the weekly build on a VM, where there is no risk of loosing anything.

Regards

**Comment by jjvbsag** [comment]
Ok, did a test of 9.1.5 on a vanilla xubuntu16.04LTS VM. 
Replace now seems to work (sometimes?), but "Find All" still freezes.
![codelite-replace-freeze](https://cloud.githubusercontent.com/assets/8567887/14762119/06b359ec-0973-11e6-8f1b-e6c364e7327a.png)
