### ISSUE TITLE
Duplicate Project with different name and Path

### ISSUE THREAD

**Issue by mtangoo** [eranif/codelite#1250]
Hi,
I have this need of duplicating project.  My need is simple:
1. Duplicate project with new Name
2. Give option of which files to include in new project or None
3. Path to put that project

I want to implement it myself and send PR. I need help where to start and which file to modify, just ABC kind of point  :smile: 

Thanks!

**Comment by eranif** [comment]
Since the project files are XML files, you can simply read the XML document - modify it (remove unneeded files) and save it elsewhere.
You can have a look at `Project::CopyTo` function which does something similar but it also removes all virtual directories from the "new" project

**Comment by mtangoo** [comment]
Thanks for pointing that out. 
Where is that file? And where should I add the menu item for it to show up under project menu? I mean the file to modify
