### ISSUE TITLE
Cannot leave codelite

### ISSUE THREAD

**Issue by jjvbsag** [eranif/codelite#1253]
Installed codelite 9.1.5 on a vanilla xubuntu 16.04LTS VM

Neither `File / Exit`, [Ctrl]+[Q] nor using the windows close button exits codelite. Only solution is to kill the process from commandline.

**Comment by eranif** [comment]
This was already reported and fixed.
For now, the solution is to: settings->preferences->misc->history tab->reset annoying dialogs answers

**Comment by jjvbsag** [comment]
@eranif Ok I begin to remember, we discussed this already. But for me it looks there is no progress in 9.1.5, still the same issue.

After resetting the annoying dialog answers on exit I get a dialog
```
Closing CodeLite
Save perspective and exit?
[ ] Remember my answer and dont ask me again
  [ No ] [ Yes]
```
Now I can
- click [No] => Codelite stays open
- click [Yes] => Codelite saves the perspective and exits

I see multiple problems.

1. When I check the "Remember" box and then click [No], I'm trapped in codelite, as it will never exit again.
2. When I want to leave CodeLite _without_ saving the perspective, there is no way to do this

I'd suggest to change the dialog to something like
```
Closing CodeLite
[ ] Save perspective?
[ ] Remember my answer and dont ask me again
Exit?
  [ No ] [ Yes]
```

AND : when I click No, then the "Remember" checkbox must never be saved (!)
