### ISSUE TITLE
Crashes on Windows 7 on startup

### ISSUE THREAD

**Issue by doggerman** [eranif/codelite#1254]
Installed 64 bit version of Codelite 9.1.0. But it crashes when I try to  start the program.

![imgcodelite](https://cloud.githubusercontent.com/assets/624817/14765874/9d1b0cb8-0a13-11e6-8dd2-f4b737ad963e.png)

**Comment by eranif** [comment]
Sounds like a corrupt configuration.
Two things to do here:

* Can you try and remove the folder `%appdata%\CodeLite` and see if it helps?
* Also, when this happens, can you click on the "View problem details" ?

**Comment by eranif** [comment]
Ping

**Comment by doggerman** [comment]
Hi,

I installed Codelite a second time after uninstalling and it is working! It
is also showing a message that a new version of Codelite is available for
download.

Thanks for your effort.

[image: Inline image 1]



Ram K Prakash
