### ISSUE TITLE
Code completion list not including following variables in one-line definition

### ISSUE THREAD

**Issue by renkun-ken** [eranif/codelite#1258]
I'm using CodeLite v9.1.5 under Ubuntu 16.04 LTS. When I write the following code:

``` cpp
double var1 = 0, var2 = 0, var3 = 0;
```

The code completion includes `var1` but omits `var2` and `var3`. The code theme also highlights `var1` but ignores `var2` and `var3`.

**Comment by AJenbo** [comment]
I think i might be having the same issue 9.1.0 with php:
Triggeres code completion:
$var1 = $this->

Does not trigger code compleation:
$var1 = 20 + $this->

**Comment by anatooly** [comment]
@AJenbo As for me **PHP** $this->... nothing autocomplete, example on this code:

```php
<?php

class Test
{
    public $foo = 9;
    private $bar = 10;
    
    function __construct() {
        $this->baz = 8;
        return $this->
    }
}
```

Variable list too:

![php_short_variables](https://cloud.githubusercontent.com/assets/317380/17093347/5f983cfe-5251-11e6-917f-3bb526d6b2f0.png)
