### ISSUE TITLE
Cannot debug Unicode build

### ISSUE THREAD

**Issue by neolib** [eranif/codelite#1260]
I have a very simple test project. If I define
`UNICODE;_UNICODE`
and add -municode to linker flags, then I will not be able to debug the program. When I hit F5, CodeLIte simply runs the program.

If I remove UNICODE;_UNICODE; defines and -municode linker flag, then everything works fine.
[test.zip](https://github.com/eranif/codelite/files/236765/test.zip)

Tested with CodeLite version 9.1.5 and 9.1.6 and the latest MinGW64 gcc 5.3.0.

**Comment by eranif** [comment]
Does this works from the command line? Where is the debugger log?
Usually, such things are problems with GDB and not really CodeLite issues

**Comment by neolib** [comment]
Yes. I works on command line. I built test.exe using MinGW 32-bit compiler. Here is a sample output of command line debugging:

`D:\Build\cb\test\bin\Debug>c:\Programs\gnu\mingw32\bin\gdb test.exe
GNU gdb (GDB) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from test.exe...done.
(gdb) b wmain
Breakpoint 1 at 0x401b5c: file D:/Build/cb/test/test.cxx, line 58.
(gdb) step
The program is not being run.
(gdb) run
Starting program: D:\Build\cb\test\bin\Debug\test.exe
[New Thread 10400.0xf4]
[New Thread 10400.0x2ec8]

Breakpoint 1, wmain (argc=1, argv=0xcd0db8) at D:/Build/cb/test/test.cxx:58
58          _tprintf(_T("Program: %s\n"), argv[0]);
(gdb) s
Program: D:\Build\cb\test\bin\Debug\test.exe
59          printf("Built on %s %s\n", __DATE__, __TIME__);
(gdb) s
Built on Apr 26 2016 22:43:22
60          printf("Compiled using GCC version %d.%d.%d\n", __GNUC__ , __GNUC_MINOR__, __GNUC_PATCHLEVEL__);
(gdb) s
Compiled using GCC version 5.3.0
61          printf("__cplusplus = %ld\n", __cplusplus);
(gdb)
__cplusplus = 201103
62          puts("");
(gdb) c
Continuing.`

**Comment by neolib** [comment]
BTW, I have some other weird issues with CodeLite. But they are not easy to understand. I think if you can fix this the other problems may be gone with it.

I am testing this problem on a physical Windows 10 64-bit and a Windows 7 64-bit VM.

**Comment by eranif** [comment]
Lets continue this discusssion on the forum as I am pretty sure its not a CodeLite issue.
But a gdb issue.

Also, please read this post: http://forums.codelite.org/viewtopic.php?f=3&t=804 before posting on the forum

**Comment by neolib** [comment]
Actually I wanted to post this problem in forum, but I could not receive my activation email. I don't know whom I can contact by looking around in the forum index.
