### ISSUE TITLE
Editing 9.1 compiler option settings

### ISSUE THREAD

**Issue by wittend** [eranif/codelite#1261]
Not a big deal, but:

When editing Project->Settings->Compiler->C++ Compiler options, the "enter other options" text box does not always appear.  I can directly edit the C++ Compiler options on the parent dialog, but that gives limited access.  I am experiencing this in both Debug & Release mode.  This appears to be true in the C options as well.

I'm using Mint Rosa/Ubuntu 14.04.  Codelite 9.1 (or 9.1.1  - not totally sure).  Tried it on two installations, one native and one in a VirtualBox VM.

**Comment by eranif** [comment]
Can you provide a screenshot showing the problem?

**Comment by wittend** [comment]
Here is what I mean.  The textbox to 'Enter Other Options' is collapsed.
(the horizontal line above the test'Command Line'. The options may be
entered on the parent page in the 'Compiler Options' line, but this is
tricky and not what I think you intended.

Dave

**Comment by eranif** [comment]
Seems OK to me (tested on various machines)
Closing this bug
