### ISSUE TITLE
Interface instability in 9.1

### ISSUE THREAD

**Issue by wittend** [eranif/codelite#1262]
Not a big deal, but:

In 9.1 (or 9.9.1, not sure) I am experiencing more instability in the editor than I am used to.  It is not entirely new, but I keep hitting one manifestation that irritates me.  Some combination of key clicks or mouse clicks, usually close to but not on the menu bar, suddenly closes the workspace pane, and probably the output/build/etc pane.   Clicking View->Toggle All Panes restores everything.

I am using Mint (cinnamon)/Ubuntu 14.04

**Comment by eranif** [comment]
Its a feature not a bug... usually this will happen when you double click a tab label or hit `Ctrl-M`
Both actions are "toggle" this means, re-doing them restores to previous layout

**Comment by wittend** [comment]
Ok, I get it!  It just takes me by surprise.  I'll get used to it.

Dave
