### ISSUE TITLE
Interface request

### ISSUE THREAD

**Issue by wittend** [eranif/codelite#1263]
Using the classic environment for codelite 9.1, I really wish that there were toolbar buttons for two things I use constantly - "Run" without debug (Ctrl-F5) and a "Save All" button next to the Save Button in the toolbar. 

Probably just my preference.

Linux Mint Rosa (cinnamon)/Ubuntu 14.04

**Comment by eranif** [comment]
The `Ctrl-F5` exists in CodeLite since day one
Its the 3 gears icon (Tooltip `Run Active Project`)
`Save-All` was added somewhere between 9.1.1 and 9.1.6 (can't remember when) http://codelite.org/LiteEditor/ReleaseNotesCodeLite92

**Comment by wittend** [comment]
Ok, I just suppose I have not updated on these machines.  I guess that
someone else wanted "save All" too.

What I meant about the Ctrl-f5 "run" was that I would like to have a button
equivalent in the toolbar.  But if no one else wants it, I guess life will
go on.  I'm a complete klutz with the keyboard, so I use a mouse for
absolutely everything I can.

Dave

**Comment by eranif** [comment]
> What I meant about the Ctrl-f5 "run" was that I would like to have a button equivalent in the toolbar.

There is such a button since day 1...

![1](https://cloud.githubusercontent.com/assets/3677711/14870074/615cf9a0-0ce0-11e6-84bd-b047624128d2.png)

**Comment by wittend** [comment]
Thick of me.  Every so often I have to prove how very unobservant and
generally dense I am!

Thanks,

Dave
