### ISSUE TITLE
Invalid linkage when including other library

### ISSUE THREAD

**Issue by vzam** [eranif/codelite#1264]
So apparently there is something wrong with the path being set when importing a library in another library (using 9.1.0 on arch linux). I've tried to put the path into the field where only the lib name belogs and it worked. Here's what I mean exactly:

Project1: just a .h file for testing, create the static library.
Project2: more test files, static library
Libraries Search Path: (doesn't matter, won't work)
Libraries ../Project1/Debug/libProject1.a (workaround, usually I would put Project1 here and the respective path above)

critical line:
/usr/bin/llvm-ar rcu ./Debug/libProject2.a ./Debug/test2.cpp.o "../Project1/Debug/libProject1.a"

without workaround:
/usr/bin/llvm-ar rcu ./Debug/libProject2.a ./Debug/Project2.cpp.o "Project1"
/usr/bin/llvm-ar: Project1: No such file or directory.
Project2.mk:76: recipe for target 'Debug/libProject2.a' failed

**Comment by eranif** [comment]
This is not a bug, but merely a configuration issue. Please post such topics on the forum where its more appropriate
