### ISSUE TITLE
build and run project not working

### ISSUE THREAD

**Issue by shahinfarcry** [eranif/codelite#1267]
hi i'm using macbook pro. OS 10.11.4 and latest version of codelite 9.1.6. i followed the video but xcode doesnt have same option like the video. so i download Command_Line_Tools_OS_X_10.11_for_Xcode_7.3    from apple developer site and install and open codelite i'm still getting errors. everytime i click on build and run projects i get this error. please help. 
![screen shot 2016-05-02 at 20 19 43](https://cloud.githubusercontent.com/assets/14102038/14965812/47c22d74-10a7-11e6-80b2-a4be5928e4fe.png)

**Comment by eranif** [comment]
I just tested this on my mac book and seems to be working fine.
It would be great if you could post the entire backtrace and not just a partial screenshot

**Comment by eranif** [comment]
No reply - closed
