### ISSUE TITLE
Save perspective dialogue, problematic behavior

### ISSUE THREAD

**Issue by amotzg** [eranif/codelite#1270]
The save perspective dialogue supply a 'No' button that behave like a cancel. It doesn't leave the option to exit without saving, only to abort exit.
After marking the don't ask check box and pushing the 'No' button, the IDE can't exit.
Ubuntu 14.04.4

![160505_0816_codelite_perspective_save_dialogue](https://cloud.githubusercontent.com/assets/3259765/15036617/6649e83c-129a-11e6-85f7-44d7dbf11be7.png)

**Comment by eranif** [comment]
This was already fixed in 9.1.5 (or 9.1.4)
