### ISSUE TITLE
Feature Request: Remember checkbox for new version dialogue

### ISSUE THREAD

**Issue by amotzg** [eranif/codelite#1271]
Would be nice to have a "don't ask again" check box in the new version pop up, to avoid searching the setting for it. Moreover, if I could choose to only ignore it till the next version, this would have been perfect.

Also, it seems that the 'No' and 'Cancel' buttons are redundant.
Ubuntu 14.04.4

![160505_0824_codelite_new_version_dialogue](https://cloud.githubusercontent.com/assets/3259765/15036684/4aaa3bda-129b-11e6-859c-ccab783cd16d.png)

**Comment by eranif** [comment]
You can disable this from: settings->preferences->misc->check for new version on startup
