### ISSUE TITLE
Unable to find libclang.so.3.8 during runtime

### ISSUE THREAD

**Issue by Dimenus** [eranif/codelite#1273]
System is Arch x64 / 4.5.1. LLVM/Clang/LLDB release 3.8 were all compiled from source.

Codelite fails to start, it can't find libclang:

> codelite: error while loading shared libraries: libclang.so.3.8: cannot open shared object file: No such file or directory

CMAKE found clang: 

>--- clang link line /usr/local/lib/libclang.so 
--- clang include path /usr/local/include 
--- clang binary /usr/local/lib/libclang.so

libclang location: 
`/usr/local/lib/libclang.so.3.8`

**Comment by eranif** [comment]
Do you have `/usr/local/lib` in your `LD_LIBRARY_PATH`?
The fact that `CMake` found it, does not mean its in the correct `LD_LIBRARY_PATH`...

**Comment by Dimenus** [comment]
That was it. `LD_LIBRARY_PATH` does not exist on boot on my workstation. But that's an ARCH issue not a codelite issue. Is codelite required to search for so using 'LD_LIBRARY_PATH' or is that in a config file somewhere?

**Comment by eranif** [comment]
Its not something that CodeLite does, its how the runtime linker works

**Comment by Dimenus** [comment]
The runtime linker checks the RPATH. I was not able to get the application to work by modifying the RPATH. Are you saying that's a viable option?
