### ISSUE TITLE
"Welcome!" window should be resizable

### ISSUE THREAD

**Issue by gabrii** [eranif/codelite#1274]
The small size forces you to scroll left and right constantly to read the full description of the plugins, which could be solved by making this window resizable.

**Comment by eranif** [comment]
can you post a screenshot showing your problem?

**Comment by gabrii** [comment]
To reproduce I only removed my ~/.codelite folder. 
![screenshot from 2016-05-09 13-39-25](https://cloud.githubusercontent.com/assets/3278243/15112025/ad1859fc-15eb-11e6-80fa-71eb3dc7c913.png)
See the scrollbars that could be eliminated just by enabling the maximization of the window? Later I found the much better plugins manager at Plugins > Manage Plugins; I think it's an important detail, as this is one of the first interactions the user has with the program. Btw, running on Ubuntu16.04.

**Comment by eranif** [comment]
We just confirmed that this bug does exist, however, its a wxWidgets bug
In fact, I could resize the wizard, but the layout get messed up...

We tested this on another wxWidgets based application to confirm. Please open this bug to the wxWidgets project (the offending control is called `wxWizard`)

**Comment by gabrii** [comment]
Reported there. Thanks for the details

**Comment by eranif** [comment]
FYI:
I have updated the welcome wizard to display the full plugin description
