### ISSUE TITLE
Feature Request: put intermediate files in intermediate folder

### ISSUE THREAD

**Issue by neolib** [eranif/codelite#1277]
I see that CL (9.1.6 as of writing) places intermediate files like Makefile and PROJECTNAME.TXT in project folder. It's not friendly to version control systems (git/svn, etc). I think it would be a better idea that  these files be placed in the intermediate folder instead of project folder.

**Comment by eranif** [comment]
Generating the `Makefile` in a different folder is simply too much work only to avoid your situation.
I am short on time, please feel free to fix this and send a pull request
