### ISSUE TITLE
[Feature Request] Synchronized Edit for Code Refactoring

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#1278]
This editing mode is greatly a time saver while doing project refactoring. It is present in Delphi, C++ Builder and Lazarus IDEs, as far as I know.

It works as the following:
1. You select a portion of source code. On bottom-left corner of selection, there is an icon for "synchronized edit". It looks as this:
![synchro edit 01](https://cloud.githubusercontent.com/assets/14065837/15121604/f396c194-15e0-11e6-8387-817c3ec96264.jpg)
2. If you click on "synchro edit" icon, the selection changes in color and you can continue editing the document only inside the selection. Icon itself now appears on top-left corner and by clicking on it (or pressing ESC) you exit "synchro edit" mode. It looks like this (note that due to how I've cut the image, only few pixels of "synchro edit" icon are visible on top left, sorry):
![synchro edit 02](https://cloud.githubusercontent.com/assets/14065837/15122385/89bbedcc-15e4-11e6-9dc3-4f0631636362.jpg)

In "synchro edit" mode, you can only edit identifiers and when you do, every other identifier with the same name gets updated. So for instance, on above screenshot, when you change "BytesToCopy" to "NumberOfBytes", every other "BytesToCopy" identifier in selected area changes to "NumberOfBytes", similarly as if you would have used "Search and Replace" with same terms in selected text. Similarly, the identifier that you are editing gets highlighted and every other identifier that will be (or is being) changed.

The method can be either dumb and just use "Search and Replace" method when editing identifiers, or be smarter and change only those identifiers of the same kind (i.e. if you edit variable name, only other variables having the same name get edited, but not data types and/or comments, for instance).

This "synchro edit" mode is highly effective during refactoring, where you can select several functions (or portions of thereof) in code editor and quickly refactor multiple variable names, data types, function names and so on.

Please consider this as an addition to core editor functionality.

**Comment by eranif** [comment]
Thank your for the time you took to write this issue, however, due to really lack of time and resources I don't see this feature implemented.

A pull request that implements this is greatly appreciated
