### ISSUE TITLE
Invoking "Undo" does not restore previous selection

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#1281]
CodeLite 9.1.7, revision 820962ceeebfbf42b48674d0ffea3a949f3fda01.

1. In CodeLite, select some portion of code.
2. Press "x". Notice that the selected portion was replaced by "x".
4. Edit - Undo (or press "Ctrl + Z"). 
5. Expected: previous selection is preserved. Actual: previous selection is permanently lost.

In above example, when we pressed "x", we could have actually meant "Ctrl + X", but failed to press "Ctrl" properly, and even though we did "Undo", our selection wasn't restored, so we have select required portion all over again, spending additional time and effort.

The expected behavior can be seen, for instance, in "gedit" (Linux), Notepad or Visual Studio (Windows) - repeat above steps 1-5 to see that previous selection is restored after Undo.

**Comment by eranif** [comment]
Hi,
I tested this today on OSX, Linux and Windows. 
It works well on cases :/
Can you please provide some more details on your machine specifics etc?

Thanks

**Comment by yunkot** [comment]
Sorry, forgot to mention. I'm experiencing this on Ubuntu 16.04 64-bit w/Unity. I just checked, exactly same issue occurs in CodeLite 9.1.5 on Windows 7 x64-bit running inside VirtualBox: either "Ctrl + Z" or "Edit - Undo" restores previous text content, but not the selection.

**Comment by yunkot** [comment]
By selection, I mean the whole selection, not just cursor position, like this:
![codelite lost selection](https://cloud.githubusercontent.com/assets/14065837/15296448/01429604-1b5b-11e6-849d-e5b4718b0292.jpg)

**Comment by eranif** [comment]
OK, so you expect the selection to be restored?
This is not supported by the editor component Scintilla... so I guess its not supported in CodeLite

I don't think that the scintilla developers are planning on adding this any time soon
