### ISSUE TITLE
Code completion: gives invalid results when listing struct/class member options

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1288]
If I have a class iterator, which has a member 'group_pointer', which is a pointer to a class of type group, when I type 'iterator.grou' codelite gives me not just the iterator member name but also the constructor and copy constructor for the group class. It should only give the member name in this context, I believe.

Host: Win7 x64,
Codelite ver: 9.16, non-self-compiled

**Comment by eranif** [comment]
Can you please provide a code example?

**Comment by mattreecebentley** [comment]
Nothing small- but if you download plf_colony from
http://www.plflib.org/colony.htm

And edit it in codelite, then type out (somewhere in a member function):
iterator new_iterator;
new_iterator.grou

You'll get the four options, only one of which is a member of iterator - the other three are members of colony and group.

**Comment by eranif** [comment]
I am not going to pull huge / big code base, without a minimal sample - I am afraid I don't have time to fix this. Please try to provide a simple snippet that I can copy paste into an existing project and try this

**Comment by mattreecebentley** [comment]
plf_colony is a single .h file, zip file download... not exactly a big ask. I can mock together something, but I don't know for sure whether the problem arises from the iterator being within in the same class as the group struct, or what. So it would actually -save- time if you use the .h and just type in there.

**Comment by AJenbo** [comment]
@mattreecebentley it would be a big help if you can identify what exact case triggers the issue. I get that reproducing the issue might be simple with the particular code you are referring to, but debugging would take much longer.

**Comment by mattreecebentley** [comment]
I'm not sure if the issue exists anymore - I'll let you know if I run across it again - this is a year old.
