### ISSUE TITLE
add "switch workspace" command

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#1296]
I regularly do the "close workspace", "open workspace" dance.

It would be really nice if there was a command "switch workspace" which allowed me to shortcut that process.

Perhaps a new menu item in the context menu for the workspace?

**Comment by AJenbo** [comment]
At least in 10.0.4 you are able to open a workspace with out having to close the current first. You can also witch to one of the 7 most recent workspaces via Files->Recent Workspaces.
