### ISSUE TITLE
Debugging: Locals not updating when stepping through code

### ISSUE THREAD

**Issue by lkamp** [eranif/codelite#1301]
I use CodeLite to compile the C++ code below. When debugging and stepping through the code line by line, the values in the "Locals" view do not change. When examining variables in the "Watches" view they are updated after every executed line.

I compiled the code with both clang++ and g++ with no effect. I use gdb as a debugger.

Used versions:
- clang++ 3.5.0
- g++ 4.8.4
- gdb 7.7.1
- CodeLite 9.1.5

``` c++
class testclass {
public:
    int a;
    int b;
    int c;

    testclass();
    int foo(int a);
    int bar(int a);

private:
    int pa;
    int pb;
    int pc;
};

testclass::testclass()
{
    a = 0;
    b = 0;
    c = 0;
    pa = 0;
    pb = 0;
    pc = 0;
}

int testclass::foo(int a)
{
    pa = a;
    pc = pa + pb;

    return a;
}

int testclass::bar(int a)
{
    pb = a;
    pc = pa + pb;

    return a;
}

int main(void)
{
    testclass t;

    t.foo(1);
    t.bar(2);

    return 0;
}
```

**Comment by eranif** [comment]
For clarification: the local variables are being updated.
The ones that are not being updated are the class members (`pa`, `pb`, `pc`)

If you will change `testclass::foo` to:
```
int testclass::bar(int a)
{
    int aa, bb, cc;
    aa = 0;
    bb = 0;
    cc = 0;
    
    ++aa;
    ++bb;
    ++cc;
    
    pb = a;
    pc = pa + pb;

    return a;
}
```
You will notice that `aa` `bb` and `cc` and being updated

(CodeLite issues the command: `-stack-list-variables 2` to gdb to get their new value, and apparently, it does not include the class members...
