### ISSUE TITLE
Change active project not working

### ISSUE THREAD

**Issue by DanqingZ** [eranif/codelite#1302]
Hi all, I found changing active project not working. I have been searching online to find the solution, but failed...could someone help me with this? Thanks!

"To make a project active, double-click the project folder in the workspace tree-view. Or right-click on the project folder and select Set As Active in the menu."[http://stackoverflow.com/questions/33091228/codelite-build-error](url)

**Comment by eranif** [comment]
Hi,
This works perfectly fine for me.
I tested this on OSX, Linux and Windows.
Can you please provide your CodeLite version and some information on your OS?

**Comment by pedrobagatin** [comment]
Check if correct source file is used, you need to change src file of the correct project.
