### ISSUE TITLE
[Clang Code Completion] ClangCC recognizes neither <chrono> nor keyword constexpr.

### ISSUE THREAD

**Issue by denchat** [eranif/codelite#1306]
Platform: Windows x64
Version: 9.1.7 ([Weekly Binary](http://downloads.codelite.org/))
Configured Compiler: [MinGW-w64 5.3.0](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/5.3.0/threads-posix/seh/)

﻿
When accessing anything in namespace `std::chrono`, clang code completion reports
> no member named 'chrono' in namespace 'std'

and things in `<ctime>` which is sub-included within `<chrono>` seem undefined either
> no member named 'localtime' in namespace 'std'
> no member named 'put_time' in namespace 'std'

It's like `<chrono>` isn't there at all.

When using `constexpr`, clang code completion reports
>  unknown type name 'constexpr'

﻿
﻿
CTags and Clang CC Search path:
> C:\gcc\mingw64\lib\gcc\x86_64-w64-mingw32\5.3.0\include
> C:\gcc\mingw64\lib\gcc\x86_64-w64-mingw32\5.3.0\include-fixed
> C:\gcc\mingw64\x86_64-w64-mingw32\include
> C:\gcc\mingw64\x86_64-w64-mingw32\include\c++
> C:\gcc\mingw64\x86_64-w64-mingw32\include\c++\x86_64-w64-mingw32
> C:\gcc\mingw64\x86_64-w64-mingw32\include\c++\backward

﻿
﻿
Demo ([coliru](http://coliru.stacked-crooked.com/a/f6c9a153c67b5ac5))
```c++
#include <iostream>    // cout, endl
#include <chrono>      // time_point, system_clock, put_time, localtime
#include <iomanip>     // hex, dec, showbase, noshowbase

constexpr const size_t SIZE = SIZE_MAX;

int main(int argc, char **argv)
{
    std::chrono::system_clock::time_point time1 = std::chrono::system_clock::now();
    time_t now_c = std::chrono::system_clock::to_time_t(time1);
    std::cout << "Now : " << std::put_time(std::localtime(&now_c), "%I:%M:%S %p (%z)")
              << std::endl;

    std::cout << std::hex << std::showbase
              << "Maximum size : " << SIZE << std::endl
              << std::dec << std::noshowbase;

    return 0;
}
```
Clang CC window
> clang: unknown type name 'constexpr'
> expected unqualified-id
> no member named 'chrono' in namespace 'std'
> no member named 'put_time' in namespace 'std'
> no member named 'localtime' in namespace 'std'
> use of undeclared identifier 'SIZE'

**Comment by eranif** [comment]
Just gave it a try here on Windows with MinGW64/4.9.3 (TDM build)
It seems that `chrono` is properly identified and members are presented

![clang-cc](https://cloud.githubusercontent.com/assets/3677711/15800343/1b132bec-2a7f-11e6-8c60-1767d48f0024.png)

The only difference is that I use TDM-GCC 4.9.3 and you are using GCC5.3

However, for the sake of the test, can you please 

* Install TDM-GCC (don't add it to the path, so it won't interfere with your current setup)
* [define it in CodeLite ](codelite.org/AddNewCompiler/AddNewCompiler)
* Tell clang code completion to use the paths from the TDM-GCC build instead of the one you have installed

Does this help?

**Comment by denchat** [comment]
After configuring using TDM-GCC latest version (5.1), the behaviour remains the same as MinGW-w64's.
If "Only use clang code completion" is checked, the pop-ups are not working.
If "Only use clang code completion" is unchecked, the pop-ups are working.
However, clang window in the output pane reports the same issues regardless how "Only use clang code completion" is configured.

TDM-GCC 5.1
"Only use clang code completion" is checked
![TDM-GCC 5.1 "Only use clang code completion" is checked](https://cloud.githubusercontent.com/assets/19730041/15803093/6dc4f99c-2af7-11e6-95e6-c0050b5c103d.png)

TDM-GCC 5.1
"Only use clang code completion" is unchecked
![TDM-GCC 5.1 "Only use clang code completion" is unchecked](https://cloud.githubusercontent.com/assets/19730041/15802994/1aad76a8-2af2-11e6-8d7c-2792f1137365.png)

I could not find TDM-GCC 4.9.3 in sourceforge. So I tried TDM-GCC 4.9.2, and it works!
Unfortunately, 4.9.2 doesn't have `std::put_time` in `<ctime>`, so I have to commented out the line.
Anyway 4.9.2 makes clang cc works.

TDM-GCC 4.9.2
"Only use clang code completion" is checked
![TDM-GCC 4.9.2 "Only use clang code completion" is checked](https://cloud.githubusercontent.com/assets/19730041/15803373/79a9cf1e-2b04-11e6-9c42-25bd3274c46e.png)

This behaviour is the same on MinGW-w64 4.9.3.
So it seems both 4.9.2 and 4.9.3 makes clang cc working.

MinGW-w64 4.9.3
"Only use clang code completion" is checked
![MinGW-w64 4.9.3 "Only use clang code completion" is checked](https://cloud.githubusercontent.com/assets/19730041/15803414/926b44d6-2b06-11e6-913d-2480d2175767.png)

I tried MinGW-w64 5.1.
As expected, 5.1 makes clang cc not working.

MinGW-w64 5.1
"Only use clang code completion" is checked
![MinGW-w64 5.1 "Only use clang code completion" is checked](https://cloud.githubusercontent.com/assets/19730041/15803445/344c98bc-2b08-11e6-9bf2-7f33023fe6da.png)

Well, in conclusion, it seems the last version that clang cc works is 4.9.3 in both MinGW-w64 and TDM-GCC. The earliest version that clang cc doesn't work is 5.1 in both MinGW-w64 and TDM-GCC.

**Comment by denchat** [comment]
This is about how compilers treat "-std=c++17" differently at present time.
It's not a bug of codelite.
You may now close this issue then.
