### ISSUE TITLE
CodeLite trims BOM from UTF8 source files

### ISSUE THREAD

**Issue by minghonlai** [eranif/codelite#1307]
We have some projects which share source files with Microsoft Visual Studio.
The source files is encoded in UTF8 with BOM.
( Because Visual Studio just accepts UTF8 with BOM as source files. )
( Refer to https://msdn.microsoft.com/en-us/library/xwy0e8f2.aspx for more information. )

However, when we modified source files with CodeLite 9.1 on the Ubuntu.
The CodeLite will trim BOM when saving files.

We try to use gedit and vim, there is no such issue.
( The gedit and vim will not trim BOM when saving file. )

Is any setting which supports saving with trimming BOM?

Thanks.

**Comment by MaartenBent** [comment]
I encountered the same problem. BOM is stored when reading the file, but not written when saving. 

A fix I use:
`cl_editor.cpp r1543`:
```c++
file.Write(m_fileBom.GetData(), m_fileBom.Len());
```

`globals.h` class `BOM`:
```c++
void* GetData();
```

`globals.cpp`:
```c++
void* BOM::GetData()
{
	return m_bom.GetData();
}
```
Note: I don't know if the BOM is based on the encoding of the current file or on the `Encoding Locale` setting.
