### ISSUE TITLE
Underscore symbol is shown as Blank Space

### ISSUE THREAD

**Issue by tarzylove** [eranif/codelite#1308]
Underscore symbol is shown as Blank Space in CodeLite v9.1.7. I have Ubuntu 16.04 LTS. How can I make it show the '_' symbol?

**Comment by eranif** [comment]
Try changing the font family / size of it
Otherwise there is not much we can do about this (the editing component is builtin into wxWidgets and CodeLite has no control over it, beside configuring it, like changing font)

**Comment by tarzylove** [comment]
Thank you so much. It worked finally..
