### ISSUE TITLE
cscope plugin not working 

### ISSUE THREAD

**Issue by zenera** [eranif/codelite#1309]
Cscope plugin is not working on Codelite 9.1.8 in Ubuntu 16.04.
Cscope database files are created but, "Find..." context menu does nothing. Only the command is displayed on statusbar.

Codelite 9.1 package in Ubuntu 16.04 also has the same problem.
(So I have to build Codelite 9.1.8 from the source by using git.)

By the way, ~/.codelite/codelite.log said:
"libwx_gtk2u_unofficial_aui-3.1.so.0: cannot open shared object file: No such file or directory"

Because Ubuntu 16.04 has wxWidgets 3.0 libs, I followed the build instruction in codelite site(http://codelite.org/Developers/Linux) as the line below:
cmake -DCMAKE_BUILD_TYPE=Release .. -DCOPY_WX_LIBS=1

Cscope problem is related to the wxWidgets libs?

**Comment by eranif** [comment]
It is working just fine here...
Can you please try and install this `.deb` file:

http://codelite.org/downloads/codelite/weekly/wip/CodeLite-9.1.8-ubuntu-xenial-x86_64.deb
sha1sum: `601b0ba236d204582dcfc8bb2cca048a8789f944  CodeLite-9.1.8-ubuntu-xenial-x86_64.deb`

To proerly install CodeLite, make sure you first uninstall the old version:
```
sudo apt-get purge codelite wxcrafter
sudo apt-get install gdebi
sudo gdebi CodeLite-9.1.8-ubuntu-xenial-x86_64.deb
```

**Comment by zenera** [comment]
I couldn't install your package due to dependency problems.

$ sudo gdebi CodeLite-9.1.8-ubuntu-xenial-x86_64.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Cannot install 'liblldb-3.5-dev'

I'v installed liblldb-3.8-dev and clang-3.8. Are these libs incompatible with codelite-9.1.8?

**Comment by eranif** [comment]
Please re-download the package (same link): http://codelite.org/downloads/codelite/weekly/wip/CodeLite-9.1.8-ubuntu-xenial-x86_64.deb

I have updated it: 
`15a6ed8b8ae319037266ca578a4fd685baaff0aa  /home/eran/devl/codelite/build-release/CodeLite-9.1.8-ubuntu-xenial-x86_64.deb`

**Comment by zenera** [comment]
I found what's wrong.
I had been retained old ~/.codelite directory for newly built and installed codelite-9.1.8. This old configuration directory makes all the troubles.

After moving old configuration directory to a backup folder, newly started codelite-9.1.8 works well including cscope plugin. Both liblldb-3.8-dev and clang-3.8 libs are compatible with codelite-9.1.8 on Ubuntu 16.04/64bit.

I have to find a solution to restore old configurations including themes. Configuration incompatibility problem is bad thing though...

Anyway, thank you for your kindness, eranif.
