### ISSUE TITLE
Windows control panel - uninstall a program [problem]

### ISSUE THREAD

**Issue by hgabe** [eranif/codelite#1310]
Codelite is clearly installed in my [pc] but does not appear on the uninstall or change a program list so I can uninstall and install a new version

**Comment by eranif** [comment]
CodeLite uses InnoSetup for the installation process.
And it does create entries for uninstall, see attached (Windows 7/64 bit):
![uninstall2](https://cloud.githubusercontent.com/assets/3677711/15988737/f8a9050a-3063-11e6-8bd2-29800614f2e8.png)
![uninstall](https://cloud.githubusercontent.com/assets/3677711/15988736/f8a859a2-3063-11e6-81dc-7dddcb7892c8.png)
