### ISSUE TITLE
Windows version does not allow UNC paths in directory lists

### ISSUE THREAD

**Issue by dl748** [eranif/codelite#1313]
Tried adding \\MyServer\cincludes\usr\include but it keeps putting in /MyServer/cincludes/usr/include instead which doesn't exist.  It keeps turning \ into / and then removing duplicates.

**Comment by eranif** [comment]
> Tried adding

Please provide an **exact** steps for reproducing the problem

Thanks

**Comment by dl748** [comment]
Project Settings -> Compiler -> Include Path

appended `;\\MyServer\cincludes\usr\include`

Click Ok

Code Lite will not find ANY of the files in that directory.

Open Project Settings

Include Paths now shows `;/MyServer/cincludes/usr/include` instead of `;\\MyServer\cincludes\usr\include`

It changes `\` to `/` and then it changes the double `\\` into a single `/`

**Comment by dl748** [comment]
If I copy the files to my machine and put in `;C:\Path\To\CIncludes\`, it changes to `C:/Path/To/CIncludes/`, but when i right click on a `#include <stdio.h>` and select open included file, it works.  I just don't want to have to keep copying those files every day if they get updated.

**Comment by eranif** [comment]
Ok, thanks for the detailed explanation

**Comment by dl748** [comment]
Sorry, I thought it was understood that I was adding an include path to system files.
