### ISSUE TITLE
Unable to block paste correctly

### ISSUE THREAD

**Issue by nghiaho12** [eranif/codelite#1316]
I can block copy/cut using alt+shift but pasting does not paste as expected. It moves everything after the paste onto a newline.

**Comment by eranif** [comment]
I tested this on [wxSTC](http://docs.wxwidgets.org/3.1/classwx_styled_text_ctrl.html) sample
and this is how it works... it needs to be fixed in wxWidgets to fix this.
Nothing I can do about this

**Comment by nghiaho12** [comment]
ahh bummer
