### ISSUE TITLE
[Feature request]wxCrafter support for using device independent units (with wxDLG_UNIT?)

### ISSUE THREAD

**Issue by bagrif** [eranif/codelite#1317]
When creating interfaces that need to support both HiDPI and normal monitors unit specification for things like minimum sizes and borders is currently only pixel based which can result in borders and/or minimum control sizes that differ depending on monitor DPI. I have seen some mentions that wxGlade and DialogBlocks support use of wxDLG_UNIT for specifying device independent sizes in their UI builder which should make it much easier to create layouts that display well (correctly) on both HiDPI and standard monitors.

Another, perhaps better, option here might be to use wxWindow's FromDIP method to convert the values specified in the interface builder to monitor appropriate pixel sizes.

I'm new to wxWidgets so don't know the pros/cons of wxDLG_UNIT versus FromDIP but based on the documentation FromDIP() actually seems like it would be a more appropriate option for using device independent sizes in this case?

**Comment by eranif** [comment]
This is now fixed.
The size of the controls is now determined using `wxDLG_UNIT`for the sizer borders, I now use `wxWindow::FromDIP`

Tested on Windows and confirmed

**Comment by bagrif** [comment]
Great, I just purchased a wxCrafter license. Thanks for the quick fix!

- Brian

**Comment by eranif** [comment]
Thanks!
Which OS are you using? As I might send you an early version for you to try out

**Comment by bagrif** [comment]
> Which OS are you using? As I might send you an early version for you to try out

Mac, Windows and Linux. My primary development platform is Mac, however my current top priority is a new Windows product so a Windows (64bit) build would be ideal. I'm unusually busy at the moment (this new product is running months overdue...), so couldn't get too involved with testing at the moment but I have HiDPI systems running Mac OS X 10.6-10.11, Windows 8 through 10, Linux Mint, Ubuntu and Fedora and could provide quick test feedback on any of them.

I've been using the wxCrafter 2.5 binary build on Windows. Currently my final builds are going through Visual Studio 2015 on Windows though I have TDM-GCC 5.1 and Clang setup there too.

I tried to do a quick build of the latest source for CodeLite last night through CodeLite and TDM-GCC 5.1 but was having troubles with it finding my build of wxWidgets. Thought I had all the environment variables setup correctly, but I have a couple different wxWidgets builds going right now so some setting somewhere is probably just not right. I plan to try a fresh build again this morning.

Best regards,
Brian Griffith
Iridient Digital
