### ISSUE TITLE
alter welcome pop-up's plugin selector

### ISSUE THREAD

**Issue by futagoza** [eranif/codelite#1319]
When we first start CodeLite the welcome pop-up appears, then the plugin selector.

I noticed that the plugin selector view is not resizeable, and even if we try to change the column size (make them smaller or larger) they don't change. This might not seem much of a problem to most people, but if your trying to read the description of the plugins it's annoying because you can't read it properly.

For example, the first line of this issue within the plugin selector view becomes:

```
When we first start Code..., then the plugin selector
```

It would be anoying if I started the issue like this, wouldn't it?

**Comment by eranif** [comment]
Fixed
