### ISSUE TITLE
osx indentation doesn't work correctly

### ISSUE THREAD

**Issue by cytadelle** [eranif/codelite#1321]
9.1.8 on osx

,"id" and ,"ttl" have the same chars 56 chars (works on windows) with the same font "consolas"
![capture d ecran 2016-06-25 a 21 57 03](https://cloud.githubusercontent.com/assets/20144910/16358804/ebd68cd2-3b1f-11e6-9451-56078595d94a.png)

**Comment by Razish** [comment]
Can confirm, there are very specific font + size combinations which produce correct alignment.
I have reported this previously in Gitter, with a good way to test/reproduce:
>@Razish Mar 16 15:29
Most monospace fonts do not have consistent character widths unless used at specific sizes - This only occurs on Mac and only within CodeLite. I like to test this with repeated "===<space>" and "===<tab>" strings.
CodeLite, Andale Mono
Size 10: ![size 10](https://dl.dropbox.com/s/hxrp4fdour7p1v8/andale-mono_10.png)
Size 12: ![size 12](https://dl.dropbox.com/s/3vzwd1hga32yj1s/andale-mono_12.png)
Geany (GTK), Andale Mono:
Size 10: ![size 10](https://dl.dropbox.com/s/2fk6ddlr5hf9b5t/andale-mono_10_geany.png)
Size 12: ![size 12](https://dl.dropbox.com/s/yux5m0nvmkwomms/andale-mono_12_geany.png)
This is a pretty big issue for alignment and column limits in shared codebases.

>@eranif Mar 16 16:00
will check this issue later on today (I have a Macbook 10.10, but I guess that it should be same as 10.11)

>@eranif Mar 17 19:29
how do I install these fonts? could not find them on my Mac, so I guess they require some custom installation?

>@Razish Mar 17 23:31
you can copy the .TTF files to `/Library/Fonts` or open them and click install
[Andale Mono](http://fonts.cooltext.com/Downloader.aspx?ID=11521), [Terminus (TTF)](http://files.ax86.net/terminus-ttf/files/latest.zip)

**Comment by cytadelle** [comment]
Thank you very much for working on this issue, as Razish said it's a pretty big one :)

**Comment by eranif** [comment]
I have tested this on Mac, and the bug is a bit different too me.
I tried Andale Mono font, the chars size seems equal to me. However, I added 'right margin indicator' and it seems to be placed on the wrong position (at about 78 chars instead of 80)

So it's definitely a bug in scintilla or wxStyledTextCtrl (both are external libraries used by CodeLite)
Please report this to the proper mailing list (wxWidgets.org or scintilla.org)
