### ISSUE TITLE
How to set up vs compiler for codelite?

### ISSUE THREAD

**Issue by zhouxs1023** [eranif/codelite#1322]
codelite 9.1.8+vs 2013 compiler,it can identify the vs compiler, but can not successfully compiler any program，I set  up compiler as below:
![qq 20160626182354](https://cloud.githubusercontent.com/assets/905931/16361768/4ad9d70e-3bcd-11e6-8b58-e531385ce1aa.png)

Pls help me how to set up VS compiler for codelite ?

**Comment by eranif** [comment]
Try this:

1. Change the "Make" tool to the full path to "nmake.exe"
2. In the project settings->General->Makefile generator change it to use `NMakefile for MSVC toolset` generator

**Comment by zhouxs1023** [comment]
After setting,turn on errors u1073 and u1077,There is no way to solve,VS compiler settings are too cumbersome.

advise to write a VS compiler  settings on the wiki!
