### ISSUE TITLE
Cannot use GDB

### ISSUE THREAD

**Issue by milasudril** [eranif/codelite#1323]
I try to run the debugger (I am on Ubuntu 16.04) I get the message "Failed to start terminal for debugger".  How can I fix that?

**Comment by eranif** [comment]
Please see the forum:
http://forums.codelite.org/viewtopic.php?f=11&t=3377&hilit=terminal#p15177

**Comment by milasudril** [comment]
Ok, but my `x-terminal-emulator` is not `xterm`, but `Konsole`. Therefore, you should hardcode `xterm` in that script and also notify any packager that `xterm` is required.
