### ISSUE TITLE
Enable mouse zoom -option not working

### ISSUE THREAD

**Issue by Kanimies** [eranif/codelite#1326]
CodeLite 9.1.8 - Weekly Build Jun 11, 2016 on OS X in PHP Workplace doesn't respect the mouse zoom -checkbox value in settings - the code view gets zoomed when pressing cmd during scroll regardless of the checkbox state.

**Comment by eranif** [comment]
Which Mac are you using? Is this a MacBook i.e. are you scrolling using 2 fingers on the touch pad or actually using a scroll button on the mouse?

Note that I have implemented this feature using the wxWidgets `EVT_MOUSEWHEEL`
This might be one explanation for why it does not work on Mac

**Comment by Kanimies** [comment]
Using touch pad. I would recall that this has worked correctly before.

**Comment by eranif** [comment]
so the only thing that can think of is the move the a newer version of wxwidgets.

I will consult with the wx-dev list

**Comment by Kanimies** [comment]
I'll retest this with a mouse tomorrow, but usually i've been using the touchpad so I'm presuming it worked earlier.

**Comment by Kanimies** [comment]
Same with an actual mouse.

**Comment by eranif** [comment]
I did test this with touchpad and it works (i.e. the "disable" checkbox actually disables the zoom)
Using MacBook Pro OSX10.10

**Comment by Kanimies** [comment]
Macbook Pro with Yosemite 10.10.5, disabling zoom does not affect zooming either with external mouse or touchpad - cmd+scroll keeps zooming.
Issue still affects Codelite 9.2.0
<img width="457" alt="zoom_setting" src="https://cloud.githubusercontent.com/assets/7421922/16832527/4b3e0fa0-49b3-11e6-8601-b98537d48b06.png">
<img width="337" alt="zoom_in" src="https://cloud.githubusercontent.com/assets/7421922/16832612/a948cdec-49b3-11e6-8e4b-bd5b5941b8f2.png">
<img width="239" alt="zoom_out" src="https://cloud.githubusercontent.com/assets/7421922/16832613/aea6db94-49b3-11e6-9c0b-9f58fa3b7f52.png">

**Comment by Kanimies** [comment]
There's no disable -checkbox for zoom, though, only enable - which I've left unchecked. Tried checking it, too - no effect either way.

**Comment by Kanimies** [comment]
Also is there a possibility to zoom using the keyboard? CMD + '+' and CMD + '-' would be nice.

**Comment by Kanimies** [comment]
Now it seems to work as it should - could have been related to my Macbook (has been restarted once in the meantime).
