### ISSUE TITLE
Virus Found in CodeLite 9.1.0 for Windows 64 bit Installer Direct Link 

### ISSUE THREAD

**Issue by sleary78** [eranif/codelite#1329]
CodeLite 9.1.0 for Windows 64 bit Installer Direct Link  has a Trojan.Gen.2 

Please call th elocal Helpdesk if actions to clean or quarantine are not successfull.

Scan type: Auto-Protect Scan
Event: Risk Found!
Security risk detected: Trojan.Gen.2
File: C:\Program Files\CodeLite\codelite-cc.exe
Location: C:\Program Files\CodeLite
Action taken: Pending Side Effects Analysis : Access denied
Date found: 01 July 2016  09:52:10

**Comment by eranif** [comment]
Its not a virus. Its a false positive
