### ISSUE TITLE
wxC: JSON Lexer

### ISSUE THREAD

**Issue by mtangoo** [eranif/codelite#1330]
New Scintilla have been added to wxWidgets development that [adds JSON lexer](http://www.scintilla.org/ScintillaHistory.html) (since 3.6.5 actually).  While you can easily hand edit wxC file and add JSON, it will be nice to have new addition to wxC.

**Comment by eranif** [comment]
I assume that you are talking about wx-trunk - which I don't use for CodeLite.
Am I correct here?

**Comment by mtangoo** [comment]
>I assume that you are talking about wx-trunk - which I don't use for CodeLite.
Am I correct here?

Yes you are correct. I didn't knew that. Should I close it or leave it open until CL start using that version of wx?

**Comment by eranif** [comment]
I will close it.
Thanks
