### ISSUE TITLE
Invoking codelite makefile generation in continuous integration server environment

### ISSUE THREAD

**Issue by renqian** [eranif/codelite#1335]
Invoking codelite makefile generation in continuous integration environment is still a problem for me in attempt to build my codelite projects with shared runners provided by [gitlab-ci](https://about.gitlab.com/gitlab-ci/).

In #642, `codelite-make` was mentioned as the command-line tool, but in a typical CI environment it is still not possible to do the job without installing the entire codelite(which requires GUI-related packages absent in server systems). 

So is there any advice on configuring automatic build with codelite projects in CI server environment? Is it possible to invoke `codelite-make` as a standalone command-line tool? Thanks.

**Comment by eranif** [comment]
> which requires GUI-related packages absent in server systems

I don't see why you should not be able to install `codelite-make` on CI machine (via the CodeLite package).

The `codelite-make` tool does **not** require any GUI to work - this is the whole purpose of this tool: to be able to execute it from a script / ssh that does not have GUI capabilities. The only reason you need to install CodeLite is that there is no separate package for `codelite-make`

**Comment by renqian** [comment]
Executing
```
apt-get update -qq && apt-get install -y -qq codelite
```
produces the following output:

```
(...)
Setting up codelite (6.1.1+dfsg-4) ...

Setting up policykit-1 (0.105-8) ...

Setting up colord-data (1.2.1-1) ...

Setting up colord (1.2.1-1+b2) ...

Setting up gdb (7.7.1+dfsg-5) ...

Setting up gdbserver (7.7.1+dfsg-5) ...

Setting up libfile-copy-recursive-perl (0.38-1) ...

Setting up libgphoto2-l10n (2.5.4-1.1) ...

Setting up libgtk2.0-bin (2.24.25-3+deb8u1) ...

Setting up libsane-extras-common (1.0.22.3) ...

Setting up libsane-extras:amd64 (1.0.22.3) ...

Setting up libutempter0 (1.1.5-4) ...

Creating utempter group...

Setting up pkgconf (0.9.7-1) ...

Setting up update-inetd (4.43) ...

debconf: unable to initialize frontend: Dialog

debconf: (TERM is not set, so the dialog frontend is not usable.)

debconf: falling back to frontend: Readline

Setting up sane-utils (1.0.24-8+deb8u1) ...

debconf: unable to initialize frontend: Dialog

debconf: (TERM is not set, so the dialog frontend is not usable.)

debconf: falling back to frontend: Readline

Adding saned group and user...

Adding user saned to group scanner

invoke-rc.d: policy-rc.d denied execution of start.

Setting up unzip (6.0-16+deb8u2) ...

Setting up wx-common (3.0.2-1+b1) ...

Setting up x11-utils (7.7+2) ...

Setting up xbitmaps (1.1.1-2) ...

Setting up xterm (312-2) ...

update-alternatives: using /usr/bin/xterm to provide /usr/bin/x-terminal-emulator (x-terminal-emulator) in auto mode

update-alternatives: using /usr/bin/lxterm to provide /usr/bin/x-terminal-emulator (x-terminal-emulator) in auto mode

Setting up zip (3.0-8) ...

Setting up libc6-dbg:amd64 (2.19-18+deb8u4) ...

Setting up libgtk-3-common (3.14.5-1+deb8u1) ...

Setting up libgtk-3-0:amd64 (3.14.5-1+deb8u1) ...

Setting up libgtk-3-bin (3.14.5-1+deb8u1) ...

Setting up adwaita-icon-theme (3.14.0-2) ...

Setting up libcanberra-gtk3-0:amd64 (0.30-2.1) ...

Setting up libcanberra-gtk3-module:amd64 (0.30-2.1) ...

Setting up notification-daemon (0.7.6-2) ...

Processing triggers for libc-bin (2.19-18+deb8u4) ...

Processing triggers for systemd (215-17+deb8u4) ...

Processing triggers for dbus (1.8.20-0+deb8u1) ...

03:28:53: Error: Unable to initialize GTK+, is DISPLAY set properly?
```

Looks like it needs a display or something.

**Comment by renqian** [comment]
The runner configurations are described here:

https://about.gitlab.com/gitlab-com/settings/#shared-runners

**Comment by eranif** [comment]
> Setting up codelite (6.1.1+dfsg-4) 

Is this CodeLite version 6.1.1?

**Comment by renqian** [comment]
@eranif Everything works as expected when I switch the docker image to `ubuntu`. Thanks for your time!
