### ISSUE TITLE
php short echo tags

### ISSUE THREAD

**Issue by wommel** [eranif/codelite#1338]
Short echo tags <?= are neither offered for completion nor is php-completion offered inside of them.

**Comment by anatooly** [comment]
@wommel Can you make an example of the code. As for me all right on last build version 9.2.0

![php_short_tag](https://cloud.githubusercontent.com/assets/317380/17093035/4c56282e-524f-11e6-9549-2becc0745d15.png)

**Comment by wommel** [comment]
That screenshot came quite suprising to me. After some playing around i realized it only works before the first end of a php-tag in the file.

So if it is the first php-tag in the file completion works but if there is any other php-tag before, long or short, it dose not.
