### ISSUE TITLE
"open resource" feature is not available for NodeJS

### ISSUE THREAD

**Issue by idangozlan** [eranif/codelite#1340]
"Open Resource" feature is working fine for PHP projects, but for NodeJS it shows blank window

**Comment by anatooly** [comment]
I don't understand C++, but I think some problem on _Plugin/open_resource_dialog.cpp_ file, like m_manager->GetWorkspace()->GetProjectList(projects);

because C++ and PHP workspace have project, Node.Js create workspace without any project.
