### ISSUE TITLE
Code completion doesn't show some classes

### ISSUE THREAD

**Issue by cisou98** [eranif/codelite#1342]
The code completion engine doesn't suggest some classes, for instance vector and string.

Even though I have included these file and I am using std's namespace

```
#include <string>
#include <string.h>
#include <vector>
#include <stdio.h>

using namespace std;
```

I already fixed the CTag search path on every MinGW's include files. I am running on Windows 8.1

**Comment by eranif** [comment]
It works perfectly fine. This looks like a configuration issue, please open a forum thread
