### ISSUE TITLE
Problem with the return code of the terminal on Linux

### ISSUE THREAD

**Issue by Nserk** [eranif/codelite#1343]
Hi to all!

Maybe it's a dumb question, but I have a problem with the terminal when I execute a console program: anyhow the program execute, the return code shown in the output tab is "0", even when the program is brutally terminated, whereas when I run it on Windows the return code shows that something has gone wrong (like "-1073741510").
Moreover, the return code is shown even before the closing of the terminal, so before the program could return a value...

My Codelite version is 9.2.0, run on Linux Mint Cinnamon 18 x64 fully updated.

Thanks in advance for any help.

**Comment by eranif** [comment]
This is because on Linux, the command is not executed directly but it goes through a wrapper script `/usr/bin/codelite_xterm` and the return value you see is the return value of the terminal (which is usually 0)

**Comment by Nserk** [comment]
Thank You for the quick answer.
Is there any workaround in order to get the return code, maybe editing the terminal options?

**Comment by eranif** [comment]
I tried changing it with no luck.. I will ping @dghart whom might have an answer for this

**Comment by Nserk** [comment]
Thanks for Your patience.

**Comment by dghart** [comment]
Hi,

Are you talking about executing the console program or debugging it? 
I ask because CodeLite has a different mechanism for each. Though, having asked, both seem to have the problem :(

**Comment by Nserk** [comment]
I mean when I run the program...

**Comment by dghart** [comment]
I've spent some time looking at this. It's easy to make the wrapper, codelite_exec, return correct value: just change the last lines to:
```
$@
return_value=$?

echo "Press ENTER to continue..."
read key
exit $return_value
```
However that value doesn't get passed to CodeLite.

The problem seems to be that the program is run using wxWidgets functions, but they don't seem to give the correct value back; in particular wxExecuteData::OnSomeChildExited always returns an exitcode of 0.

I'm sorry, but I don't see an easy solution for this.

**Comment by eranif** [comment]
Note that CodeLite executes `codelite_xterm`

**Comment by eranif** [comment]
Also: for executing processes, we don't use `wxExecute` (or any of its variants) but rather I have implemented a custom (more robust) version of it which passes the correct return code (among other improvements)

**Comment by Nserk** [comment]
So, I need to edit codelite_exec or codelite_xterm?

**Comment by dghart** [comment]
>So, I need to edit codelite_exec or codelite_xterm?

It's codelite_exec (if either) for running, codelite_xterm for debugging. However, as I wrote above, that doesn't actually work in practice; you don't see the correct return value.

Experimenting a bit more I found that, if you tick "Project Settings > General > execution > This program is a GUI application", the wrapper script is not used. I then get a correct return value from the test program; or at least I do some of the time. Values of 0 or 1 are often correctly returned, but e.g. 123 results in a random-looking number :/

Doing that also loses the 'Pause when execution ends' feature, so it might not be very useful for you. But it's an answer of sorts...

**Comment by Nserk** [comment]
Well, I think it's something...
Thank You for Your efforts.

**Comment by Nserk** [comment]
Turning a bit the tables, how could it be to make the wrappers show the return value within the terminal, next to "Press ENTER to continue...", something like "Return value: x \n Press ENTER to continue..."?

**Comment by dghart** [comment]
There's no easy way to do this; CodeLite doesn't receive information from the wrappers.

Possible solutions:

1. Rewrite the code. This is _very_ unlikely to happen.
2. Do something clever with e.g. named pipes to allow the wrapper to contact CodeLite direct.
3. Get the wrapper to save its exit code to a log file (in /tmp/ perhaps) with a name that CodeLite supplies to the wrapper. Then CodeLite can read that file and extract the code to return.

Of those possibilities, 3) is the least elegant; but it's the least likely to cause problems and should be the easiest to implement. As usual, patches are welcome ;)

**Comment by Nserk** [comment]
Well, thanks again for You effort...

I don't have the ability to implement these solutions, but I'd be really grateful to whoever would be able to do this!
