### ISSUE TITLE
HiDPI support on Linux

### ISSUE THREAD

**Issue by eranif** [eranif/codelite#1347]
As Windows and OSX, make CodeLite HiDPI aware on Linux as well

**Comment by tareefdev** [comment]
With Codelite 10, the elements still appear tiny on 4k screen
OS: linux - opensuse 42.3

![screenshot_20171002_173431](https://user-images.githubusercontent.com/17391433/31082639-30fc8862-a798-11e7-80d3-efc67644e8be.png)

**Comment by DougBeney** [comment]
Any update on this? Thought a newer version of WxWidgets supports HiDPI, but I am not an expert.

**Comment by eranif** [comment]
Which version of CodeLite?
And what resolution are you using?

On 2560x1600 it looks fine to me

**Comment by eranif** [comment]
This should be fixed now. It's actually a bug in wxWidgets but I did found a workaround.
Here is my bug report to the wxWidgets team: https://trac.wxwidgets.org/ticket/18016

**Comment by DougBeney** [comment]
Glad you found a fix! :D

Is the only way to get the fixed version currently through building the code myself, or are there binaries available?

**Comment by eranif** [comment]
The weekly builds include Ubuntu 16.04, 14.04, OSX 11 (and later) and Windows
So unless you are using one of these (Debian & Mint also works with the Ubuntu binaries), you will need to download and build CodeLite from sources

**Comment by eranif** [comment]
@AJenbo Yes. This is on purpose. The weekly builds are "bleeding edge" and should not be distributed unless you really know what you are doing. The repo holds stable versions only.

**Comment by DougBeney** [comment]
Just built it and nicely done! Labels are scaled properly now. 

Still, the icons are the same size. Is this known?

![Labels look good. Icons tiny.](https://i.imgur.com/NKtAlgS.png)

**Comment by DougBeney** [comment]
![codelite](https://i.imgur.com/XJKlU10.png)

Gave Codelite 12 a shot. Looks like certain text elements are gigantic. Everything looks perfect except for the big text on this screen. The menubar items and preferences windows look perfect.

12.0.0
