### ISSUE TITLE
Apt repository: compatibility with Ubuntu 14 is broken (?)

### ISSUE THREAD

**Issue by fadeevab** [eranif/codelite#1348]
I used manual http://codelite.org/LiteEditor/Repositories#toc1 to install CodeLite 9.2 on Ubuntu 14, but fail. CodeLite refers to very fresh package, versions are higher than Ubuntu 14 has.

Rebuild CodeLite sources from github on the host helped me.

**Comment by eranif** [comment]
It's not a bug.
Our policy for supporting Ubuntus is simple:
* Support the latest Ubuntu release out there
* Support the latest **LTS** Ubuntu

Its just happen that when CodeLite 9.2. was released, Ubuntu 16.04 qualified for both criteria.
For backward compatability, we keep our CodeLite 9.1 for Ubuntu 14.04 (and this is what you get when you install CodeLite from our repository)

**Comment by fadeevab** [comment]
Thank you for an answer!
