### ISSUE TITLE
function call tooltip size

### ISSUE THREAD

**Issue by gbuntu127** [eranif/codelite#1350]
For the 9.2 release (built on Ubuntu 14.04 with wxWidgets 3.0.2), the function signature popped up as tooltip is not fully displayed. I do not find a place to change the size of the tooltip. Changing font size at Settings-colors and fonts-customize-styles-tooltip does not help. Not sure if it is related to wxwidgets or codelite. 
![tooltip1](https://cloud.githubusercontent.com/assets/1526055/17089767/859feb02-51ef-11e6-8690-8250cda42e97.png)

**Comment by eranif** [comment]
This is now fixed in git master
