### ISSUE TITLE
C++ Program is not working with cin.get();

### ISSUE THREAD

**Issue by prem-narain** [eranif/codelite#1352]
> #include <iostream>
> using namespace std;
> int GetString()
> {
> cout<<"Please enter a string"<<endl;
> char str[100];
> cin.getline(str,100);
> cout<<"Your long string"<<str<<endl;
> strlen(str);
> cin.get();
> return 0;
> }
> 

I did write this program while compiling and executing ,its compiling and executing as it should but 
 **cin.get** not working .. ?

**Comment by eranif** [comment]
This is not related to CodeLite.
Please post this on a relevant C++ board

**Comment by prem-narain** [comment]
Ohk fine ... sorry but it is  running onto other IDE(Eclipse).
