### ISSUE TITLE
Code completion extremely slow

### ISSUE THREAD

**Issue by cisou98** [eranif/codelite#1354]
Hi, I am running on Windows 8.1 with a very good configuration. When I type some code and the code completion engine is triggered, it may freeze up to 15 minutes, which is not nice. Have you got any tips and tricks to accelerate the code completion ?

**Comment by eranif** [comment]
The only way I can thin of this to happen is if your workspace is located on a network drive. Is this the case?

Also try reduce the number of entries to display:
Settings->Code completion->Number of items to display

Reduce it to 50, does it make any difference?

**Comment by cisou98** [comment]
My workspace is located on a SSD drive, which is really fast. I have also reduced the number of entries to display to 50. For the moment I work without code completion activated.
However if I start typing a object name and add a dot, Codelite sorts me the object's member function. Now, if I delete the dot I just added, the program freeze for about 15 min, using 20% of my CPU and growing in RAM. Weird :/

**Comment by eranif** [comment]
* Try also disabling this option: Settings->Code completion->triggering->auto display code completion ...
* What is the size of the code completion db? (it is located under: `WORKSAPCE_PATH/.codelite/<workspce-name>.tags`
* Try disabling the option: `settings->code completion->display and behavior->scan all include files to locate using namespace`

If non of the above helped, increase the log file verbosity, reproduce the problem and try locating the problematic section in the log file:

* Settings->preferences->log->log file verbosity, and set it to `Developer`
* While on the same page, click on the "Open.." button
* Clear and save it
* reproduce the proble
* Reload the file

If you can't find it - attach it to the bug

**Comment by cisou98** [comment]
I already have disabled all these settings, I'll try to catch the error in the log. 
My code completion db is about 102 Mo.

**Comment by eranif** [comment]
Without a reproduction environment, I won't be able to debug this.

**Comment by M-griffin** [comment]
I'm also seeing something strange that just started tonight with code completion.  
Latest Build codelite-amd64-9.2.6.7z  on Windows 10.

My project.tags is around 60 megs and all off a sudden anytime I start typing it will freeze up like it's looking up the code completion, about 1-2 minutes later it will pop up with some completion stuff.  I've tried purging and recreating the .tags the file and also changing from 500 to 10 in the settings.  

Very strange, never had any issues like this before.  
I'm wondering if it's acting funny with the GIT plugin as that is that only recent change I've made is directly working with the repo and using the git functions in the IDE for commit.  It seems to scan changes all the time.  I wonder if something is getting tripped up.

**Comment by eranif** [comment]
what happens if you disable the git plugin and restart CodeLite ? does it still slow?

**Comment by M-griffin** [comment]
actually changing it from 500 to 10 did the trick for now.  I'll try disabling git an set it back to 500 and see what happens though

**Comment by M-griffin** [comment]
No luck with GIT. if it's any help.. i'm typing std::  maybe 500 for the standard lib is a little too many.  But again this seems recent.  Maybe I should try a few reboots, but i have other stuff going right now.  I'll keep ya posted if I find anything else.

**Comment by eranif** [comment]
Please re-open when you have new findings

**Comment by hinst** [comment]
I also have this bug; CodeLite freezes completely when I type code. I guess the bug is caused by large number of included files. I have these libraries included to project:

- C++ Boost
- https://github.com/vinniefalco/Beast

**Comment by LCWilliams** [comment]
Hey!  I've only just recently bumped into this issue and thought my computer was being a derp.

Disabling automatic prompts removes the freezing (regardless of number of entries).  I'm not really sure what the root problem is-  there's been several updates to the machine since I last used Codelite. :/
