### ISSUE TITLE
Add file outside of IDE not shown

### ISSUE THREAD

**Issue by budirec** [eranif/codelite#1355]
So every time a file is added or removed from a project folder, it never reflected in the IDE, even doing reload workspace not help.
The only work around is to close and open the workspace.

**Comment by eranif** [comment]
- Steps to reproduce...
- Workspace type? (C++, PHP, JS)
- CodeLite version?
- Your OS?

Please provide information if you need help

**Comment by budirec** [comment]
Step to reproduce. 
1. Open a workspace(PHP) 
2. Add a file inside the project through explorer(not make new file in IDE) 
Result: new file is not shown
3. Do reload workspace
Result: new file is still not shown

Only close and open workspace or IDE will list the new file. 

Codelite version 9.2
OS Ubuntu 16.04

**Comment by eranif** [comment]
Right click on the project and select `Sync project with file system`
