### ISSUE TITLE
CodeLite does not process hotkey events just after startup

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1356]
CodeLite does not process hotkey events just after startup

Just updated to CL 9.2.0

When I starting CL it does not process any hotkey events until I click (using the mouse) somewhere on the CL main window.

As an example it is not anymore possible to launch CL and then right away (after CL GUI appears) just press ALT+F to open the file menu - this has work fine for years up to and including CL 9.1.0

Now I need to click somewhere in the window using the mouse - and then the hotkey events are processed (working) correctly - and yes the window is focused when I attempt to use the hotkeys :-)

When ever I see this problem CL spews out the following error on stdout:

(codelite:19203): Gtk-CRITICAL **: IA__gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

Seen with CodeLite-9.2.0 on ArchLinux (x86_64)

**Comment by eranif** [comment]
No changes were done that can trigger this. I will test this tomorrow on Linux box (2 different setups: Ubuntu 14.04 and Debian 8.1)

**Comment by uffejakobsen** [comment]
This is still a problem with CL-10.0.0@archlinux

I've managed to get a little closer to an explanation.

If you click on the "View -> Show Welcome Page" you'll see that big "New workspace / Create a new workspace" button has focus (a dimmed blue border is placed around the button).

If you enable "View -> Load Welcome Page at Startup" and reastart CL - the same is not the case here. There is no focus on big "New workspace / Create a new workspace" button (the dimmed blue border is not presend around the button)

Clicking once with the mouse somewhere in the main window clearly outs the focus there as a dimmed blue border now is drawn around the big "New workspace / Create a new workspace" button on the welcome tab - and now hotkey like ALT+F works...

I believe the reason is that the initial widget focus is placed somewhere else at startup.
This may be a linux/ specific issue that focus is undefined unless specificly set by the code...
