### ISSUE TITLE
Weird crashing in debug mode

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1357]
I'm getting weird crashing + breakpoints disappearing in debug mode in v9.2, win 7 x64, non-self-compiled.
It's complex code so I'm not sure how I'd reproduce with a reduced case, but happy to attach the code files if that'll help.
Problems start when 'stepping in' to a member function, then if I right-click on a variable to try and see it's value, empty white boxes start appearing and the whole thing gradually freaks out.
Have tried several times.

Never seen this kind of behaviour in previous versions, so guessing it's new.

**Comment by mattreecebentley** [comment]
Correction - Ctrl-clicking, not right-clicking.
just tried with 9.0.0, also occurs there, tried with 8.2, does not occur there.
However 9.0.0 recognised the breakpoint on second run, 9.2 didn't.

In this case it seems to be ctrl-clicking on a vector that caused the crash in 9.x. 8.2 seems to handle it fine.
mingw GCC tdm x64

**Comment by mattreecebentley** [comment]
I suspect crash is occurring because of large number (3600) of elements in vector, so ctrl by default will bring up a list of those.

**Comment by eranif** [comment]
Sounds to me like a GDB pretty printing issue.
Try disabling it from: settings->gdb settings->enable gdb pretty printing

**Comment by mattreecebentley** [comment]
Closed, as just retested in 9.2 and can't reproduce, suspect the problem occurred because Ctrl-clicking on the vector took so long to respond because of the vector size, so I was trying to ctrl-click on other things, and then it seemed to freeze.
You're right though, disabling pretty-printing removes the delay.
Thanks,
Matt
