### ISSUE TITLE
outline symbol tree collapsed when the current source file changed, eventhough it's expanded before

### ISSUE THREAD

**Issue by kipade** [eranif/codelite#1359]
Here, when the source file changed, the outline symbols list will collapse.
However, I expanded it before I saving the file.
I have to expand the symbols tree by hand, times and times....
I home it should remember its status before, and then restore its status after source file changed.

**Comment by eranif** [comment]
There is no state to remember - the tree is destroyed and then constructed for the active editor.
This is done each time you switch between source files in the editor.

There are 2 possible solutions here:
* Expand all items in the tree by default
* Keep the current behavior

Another option (which is orthogonal to the above):
Let the outline view to "track" the current position in the editor. i.e. the selection in the tree will reflect current caret position in the active editor.

This bug report is similar to this feature request: https://github.com/eranif/codelite/issues/412
