### ISSUE TITLE
Crashing on Window 10 (Enterprise Edition)

### ISSUE THREAD

**Issue by patrizi** [eranif/codelite#1360]
Hi, 
before send this issue I've have done several attempts to use CodeLite into my PC (installs, uninstalls, etc.).
All the software versions, from the 9.0 to the last 9.2, have had always problems to works (the application go in block, see the image attached) after this 3 steps: 
1) launch (run) codelite;
2) open a folder on "workspace view" 
3) click to open any file (of any type) in the folder.

Sometimes, I've used versions 8.x of CodeLite for development with PHP (especially with Windows 7 or 8) without problems, but from version 9 I aren't been able to use this software.

![codelite_crash_01](https://cloud.githubusercontent.com/assets/418807/17326407/77010928-58b1-11e6-8aa4-3477b3e14718.jpg)

This is the PC Configuration: 
OS Name: Microsoft Windows 10 Enterprise 2015 LTSB
OS Version: 10.0.10240 N / build 10240
System Manufacturer: Gigabyte Technology Co., Ltd.
System Model: Z97M-DS3H
System Type: x64-based PC
Processor: 1 processor (s) installed.
  [01]: Intel64 Family 6 Model 60 Stepping 3 GenuineIntel ~ 3401 Mhz
BIOS version: American Megatrends Inc. F5, 06/03/2014
Total Physical Memory: 16.245 MB
Available Physical Memory: 8,606 MB
Virtual memory: maximum size: 18,677 MB
Virtual Memory: Available: 10,275 MB
Virtual memory: in use: 8,402 MB
paging file locations: C: \ pagefile.sys
Network adapters: 3 installed NIC.
  [01]: Realtek PCIe GBE Family Controller, Connection name: Ethernet
  [02]: VMware Virtual Ethernet Adapter for VMnet1, Connection name: VMware Network Adapter VMnet1
  [03]: VMware Virtual Ethernet Adapter for vmnet8, Connection name: VMware Network Adapter vmnet8
Requirements Hyper-V: 
  Extensions virtual machine monitor mode: Yes
  Virtualization enabled in firmware: Yes
  second level address translation: Yes
  Data Execution Prevention Available: Yes

**Comment by eranif** [comment]
I am afraid that without an exact steps for how to reproduce this hang, I will not be able to fix this, as this is not reproducible on my Windows machine

**Comment by patrizi** [comment]
I know that,
I hope I will have more information as soon as possible ...
But really, the steps are no more no less than those above specified: CodeLite hangs when opens a file located in a folder in the "workspace view".

**Comment by eranif** [comment]
Can you try deleting the folder `%appdata%\CodeLite` and see if the crash is reproduced?

Thanks
Eran

**Comment by patrizi** [comment]
Hi Eran, 
sorry for the late reply. 

**Your hint has worked for me.**

Here the steps I've done:
1) uninstalled codelite
2) deleted the folder %AppData%\Codelite 
3) launched CCleaner to delete entries of codelite in system registry (probably equivalent to the reboot the PC after uninstall) 
4) installed last version of Codelite 
5) launched Codelite, added a folder to the "Workspace View" and opened more than one files.

Thank you very much for your support.
