### ISSUE TITLE
Bug: tabgroups not loaded at startup

### ISSUE THREAD

**Issue by mx75** [eranif/codelite#1361]
HI,
My name is Mihaly Fazekas. Sorry, my english is not good.

System: Ubuntu 16.04, Codelite: 9.2.0

My problem: saved tabgroups does not restore at startup (Workspace view->Tabgroups).
Last opened tabs are restored.
Tabgroup files found under WORKSPACE_DIR/.codelite/tabgroups directory.

I can load tabgroup with File->Load a group of tabs, loads a definied tabs, but i cannot see in Workspace View->Tabgroups. :(

**Comment by dghart** [comment]
Hi,

I cannot make it fail here (debian jessie, 9.2.0) :/

I created a new workspace, added a new C++ project, created a new tabgroup and saved a couple of project files into the tabgroup.
I then closed CodeLite and opened it again. The tabgroup appeared correctly in Workspace View->Tabgroups, and tabs could be loaded from it.

If that doesn't work for you, please could you create a new workspace/project/tabgroup that fails to load properly, tarball the workspace and attach it here so I can test it.

Or, if I did not understand you correctly and I was doing something different, please tell me how to make it happen.

Regards,

David

**Comment by mx75** [comment]
Hi,

I make porbe again from "zero" (totally new workspace, no import existing files, ...).
(One new workspace for C++ probe, and another new workspace for PHP probe)

Create new workspace -> create new project -> add src files ->make tabgroups (File->Save tabs As group) -> restart CodeLite

With C++: working (after restart CodeLite: i can see tabgroups)
With PHP: NOT working (after restart CodeLite: i canNOT see tabgroups)

The *.tabgroup file exists under $WORKSPACE_DIR/.codleite/tabgroups.


Thanks,

Michael

**Comment by eranif** [comment]
Ah, this was the info that was missing: a `PHP` workspace
