### ISSUE TITLE
Source Code Formatter deletes strings.

### ISSUE THREAD

**Issue by yogiman3** [eranif/codelite#1365]
Hello, i had tried to format my old php code using **builtin** code formater. 
The result is nice, but every string that contains unicode character is missing after formatting.

eg.:

```
      public function actionLogout(){
                $this->getUser()->logout();
                $this->flashMessage('Odhlásenie prebehlo úspešne!');
                $this->redirect("Login:");
        }
```

is formatted to:

```
    public function actionLogout() {
        $this->getUser()->logout();
        $this->flashMessage();
        $this->redirect("Login:");
    }
```

Codelite 9.2.0
Source Code Formatter plugin with default settings.

Can you reproduce this behaviour?
Thanks.

**Comment by eranif** [comment]
Thanks for reporting this, will look into it

**Comment by yogiman3** [comment]
On Windows 7 with Codelite 9.2.1 is formatting result:

```
    public function actionLogout() {
        $this->getUser()->logout();
        $this->flashMessage('OdhlĂˇsenie prebehlo ĂşspeĹˇne!');
        $this->redirect("Login:");
    }
```

It looks like change of cahracters encoding or something like that.
