### ISSUE TITLE
Issue with an Icon

### ISSUE THREAD

**Issue by KranthiRemala** [eranif/codelite#1369]
Hello Team,

Great Stuff! Absolutely love your Tool.

However, I do have an issue. I see that there's "cubes.png" which is being used as your icon in your tool. It's a copyright breach. I wanted to bring it to your notice that this icon needs to be removed as it's the logo of our proprietary application.

I also see that Codelite now has an improvised icon in shape of an 'L' which is lot more intuitive and metro styled. 

Thus, Kindly request you to get rid of the "cubes.png" from your icon library. 

Regards,
Kranthi

**Comment by eranif** [comment]
Thanks.
This icons is no longer used and I will remove it.

**FYI**
This icon was purchased as part of an icon set by me (or my former partner, almost 10 years ago!) and the license was "Royalty free" which means I can distribute it with my software without additional payments. I can't remember the company name, I think I still have the receipt for the icons somewhere in my email archives...) 

Thanks for reporting this

**Comment by eranif** [comment]
The icon was removed from the GitHub and from the installers

**Comment by KranthiRemala** [comment]
Great! Thank you so much!

I'd be interested to know the receipt and the acknowledgement of the
Royalty Free attribute of these Icons. Please feel reassured that this
request doesn't have anything to do with your software and it's
proprietaries, I'd like to do further due diligence on my product (I work
for Product Development as a Senior Software Engineer for my product) as it
seems little critical.

Thanks once again for confirming.

Best Regards,
Kranthi

**Comment by KranthiRemala** [comment]
On second thought, the screenshot on your website would need updating with
latest icon perhaps, that's how I could get to the bottom of this issue.

Thanks,
Kranthi

**Comment by eranif** [comment]
Could you point me to the relevant screenshot?
Thanks

**Comment by eranif** [comment]
Nvm, I fixed the screenshot
