### ISSUE TITLE
"Find Next" and "Find Previous" on highlighted text

### ISSUE THREAD

**Issue by gbuntu127** [eranif/codelite#1372]
Using codelite 9.2-1unofficial.xenial
Here is the scenario with "Find Next" on highlighted text

scenario 1:
------
1. Ctrl+F calls out the search bar, input "word1"
2. "Find Next"  will jump to "word1"
3. mouse double click to highlight "word2"
4. "Find Next" will jump to "word1" instead of "word2"

Please confirm that this is by design. I remember back in codelite 8.x, "Find Next" takes whatever the highlighted word instead of the input from the search bar.  

another scenario 2:
------

1. Ctrl+F calls out the search bar, input "word1"
2. "Find Next"  will jump to "word1"
3. delete "word1" in search bar, the search bar is still showing
4. mouse double click to highlight "word2"
5. "Find Next" does not jump to anywhere

this does not seem to be consistent with scenario 3:
------
1. close search bar by "ESC"
2. mouse double click to highlight "word2"
3. "Find Next" will jump to hightlighted "word2"

**Comment by eranif** [comment]
You are not the first one that complains about it ...
It was done intentionally by this PR: https://github.com/eranif/codelite/pull/1255

I am going to revert this change

**Comment by gbuntu127** [comment]
Thanks.

**Comment by eranif** [comment]
PR #1255 was reverted and it should be working as expected now
