### ISSUE TITLE
Blank editor when lost focus

### ISSUE THREAD

**Issue by pattisahusiwa** [eranif/codelite#1375]
When open a dialog (for example Colours and Fonts) and focus to another apps, Codelite Editor turn to blank after close the dialog and go back to the editor.

![a](https://cloud.githubusercontent.com/assets/11484016/17593571/8a279682-6010-11e6-8ca2-c106182d3828.png)

**Comment by eranif** [comment]
Which CodeLite version and OS?

**Comment by pattisahusiwa** [comment]
Codelite 9.2.0

OS: Arch Linux x86_64 + i3wm

**Comment by eranif** [comment]
Does it happens with a different window manager?

**Comment by pattisahusiwa** [comment]
I don't know. Only have one WM.

**Comment by eranif** [comment]
We don't really support ArchLinux (i.e. the build you are using was not provided by us.
So its either a self compiled binary or from a 3rd maintainer

In either case, I suspect that it is relatd to the window manager.
It will be great if you could try install another one alongside the current one you are using and give it a try

**Comment by pattisahusiwa** [comment]
Yes, it's self compiled based on github archive. I'm using this repository to install codelite https://aur.archlinux.org/packages/codelite/.

Btw, can you give me some advices to debug/test the codelite source to get more information about the issue? considering codelite is a huge project, so you can narrow me directly to the source/part of code instead of dive into the whole code.

Maybe I can help you to solve this issue. i3wm is one of the popular WM, so maybe many users also face the same issue with me.

**Comment by eranif** [comment]
http://codelite.org/Developers/Linux
http://codelite.org/Developers/DebugCodeLiteLinux

Note that its really a wxWidgets bug and not CodeLite, so I doubt debugging CodeLite will help here

**Comment by eranif** [comment]
does this also happens in the wxWidgets stc sample?

**Comment by pattisahusiwa** [comment]
Maybe you're right, maybe it's related to wxWidgets or i3WM. You can close this issue until we found the source of this issue.

Thank you.
