### ISSUE TITLE
Files not being properly removed from project when removed in codelite editor

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1377]
Steps to reproduce:
Have a project with a single .cpp file in it.
Remove the file in the editor. Do not delete.
Add a different .cpp file. Try and compile.
Compiler will issue complaints based on original file still being present and compiled.

Inspection of .project and .mk files shows original .cpp file still present as objects.

9.2.1, non-self-compiled, win7 x64

**Comment by eranif** [comment]
I am unable to reproduce this using the above steps.
tbh, I removed and added files **thousands** of times from within CodeLite and never had an issue.

I suspect its something environmental (e.g. the .project is read only or something like that)
Can you try this on a different machine and see if it still happens?
Also, "Remove file from the editor. Do not delete it" should be: 

* Right click on the file in the workspace view and select  `Remove` 
* Answer "Yes" for the first dialog and "No" for the second one

**Comment by mattreecebentley** [comment]
I can't reproduce using the steps above either, so I'm not sure what initially triggered the problem in the existing project, though I'm sure it wasn't read only because I had to edit it manually.
