### ISSUE TITLE
Removing file from project does not update .txt

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1379]
Removing a .cpp file from a project with other (excluded) .cpp files in it, then cleaning and rebuilding, did not update the project's .txt file.

In this instance, because there were other .cpp files in the project, it was not necessary to edit the .project and .mk files as well.

**Comment by eranif** [comment]
I am really confused here: which .txt file are we talking about here?
Other no cirumsentece, you should edit the .project file manually

**Comment by mattreecebentley** [comment]
As mentioned in another bug report I've had to edit the .project several 
times with the latest version of codelite due to it not correctly 
removing objects from the project when that object was the only one in 
the project.

Secondly, the .txt file I'm referring to is the one containing the list 
of compile objects, eg.
std_map_int.txt (for std_map_int.project) contains 
"./Release/std_map_double.cpp.o"

**Comment by eranif** [comment]
I am not able to reproduce this, can you please provide a minimal workspace and steps on how to reproduce the problem?
