### ISSUE TITLE
FR: Projects currently not retaining expansion status in Workspace tab

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1380]
Feature request - retain expansion/contraction status between codelite sessions in workspace view.

Desired behaviour: when expanding/contracting branches of various projects in workspace view, that expansion/contraction should stay the same when loading the Workspace next time.

Current behaviour: doesn't retain expansion/contraction status for anything, expands current active project but only to first level (exposing src folder, nothing else most cases)

v9.2.1, non-self-compiled,. win7 x64

**Comment by eranif** [comment]
Due to lack of resources, this is not going to be implemented.
As usual, patches implementing this are most welcome

**Comment by mattreecebentley** [comment]
Just add it to a list somewhere.
It was listed as a feature request, not a bug report.
The timeframe isn't critical, but in my opinion this is a more useful 
change than many of the interface changes which've been implemented.
Cheers,
Matt

**Comment by eranif** [comment]
I know. I am just being realistic here: **I** will not have time for this at all. I don't see a point in keeping open bugs/features just incase someone in the future will implement it...
From my experience, it does not happen and only makes the issues list and hard to focus on the real issues

**Comment by mattreecebentley** [comment]
Fair enough-
