### ISSUE TITLE
[Feature request] Left shift last tab when needed

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#1382]
Hi Eran,

it would be nice if the file-tabs could left shift in case the last tab is selected but not fully visible because of the window size.

![image](https://cloud.githubusercontent.com/assets/1535691/17766162/113228f4-652a-11e6-853e-2bf2ad39d6e7.png)
As in the screenshot the last tab is selected but not fully visible. It would be great if the tabs would simply left shift until the rightmost tab is fully visible when selected. Likewise I would expect that to happen for the leftmost tab.

Best,
 René

**Comment by eranif** [comment]
My plate is currently full and I don't think I will be able to address this issue any time in the foreseen future. So unless you are going to provide a pull request with the fix, I am going to close this issue

**Comment by upCASE** [comment]
Hi Eran,

I just had a look into this and it's trivial to fix, but too much hassle for a pull request.
In Notebook.cpp, IsActiveTabVisible(), line 284, simply change "Intersects" to "Contains".
Works perfectly fine for me using GTK.

Best,
  René

**Comment by upCASE** [comment]
Hi Eran,

sorry for the long wait. Just got around to create a fork and send a pull request.

Best regards,
  René
