### ISSUE TITLE
PHP plugin: *.ctp extension

### ISSUE THREAD

**Issue by giuntim** [eranif/codelite#1383]
I use CodeLite 9.1.0 (Ubuntu 16.04 64bit).
In CakePHP projects (http://www.cakephp.org) view files use .ctp extension.
They contain html+php code.
Would be nice have them included in PHP projects.
At the moment I have to manually edit .phprj file to manually add ;*.ctp to m_importFileSpec to have CodeLite see them.

**Comment by eranif** [comment]
Note: you can edit the view files from the UI:
Right click on the project: `Project Settings -> General -> View`
And add `*.ctp` to the list of files.

This workaround, will display the ctp file in the tree view, but it will not enable PHP code completion for these file types.

Commit https://github.com/eranif/codelite/commit/8c731ebe8c82d7681de8502609292a072e9533fb fixes this
