### ISSUE TITLE
[Feature request] need to support more PHPDoc tags

### ISSUE THREAD

**Issue by pattisahusiwa** [eranif/codelite#1385]
These are the valid PHPDoc tags that currently are not supported by codelite:

1. property: https://phpdoc.org/docs/latest/references/phpdoc/tags/property.html
2. property-read: https://phpdoc.org/docs/latest/references/phpdoc/tags/property-read.html
3. property-write: https://phpdoc.org/docs/latest/references/phpdoc/tags/property-write.html
4. method: https://phpdoc.org/docs/latest/references/phpdoc/tags/method.html

**Comment by eranif** [comment]
How would you suggest to add them? i.e. what does CodeLite should do when it encounter these tags.
For example, the `@property` tag?

**Comment by pattisahusiwa** [comment]
The bug in the last PR that I've sent is found when I'm trying to implement `@property` tag. But, currently I don't have more free time to dig into the code. 
`@property` is similar to `@var`, so you can implement the same logic. Also, `@method` is similar to a function definition in class or interface.
```php
<?php
/** @property $foobar */
class foo
{
    /** @var $bar */
    public $bar;
    
    public function __get()
    {
    }
}
```
By using this example, when a user type
```php
$f = new foo();
$f->
```
editor can suggest that `$f` have 2 property `foobar` and `bar`.

**Comment by eranif** [comment]
Ok, thanks. So, `property` will add new members to the class/interface completion list
FYI: you don't need to add `@var` to get it listed in the completion list, the `@var <type> <name>` provide an easy way for the IDE to get the typehint for member (or any variable)

**Comment by pattisahusiwa** [comment]
Ok, thanks for the info. I prefer to add `@var` for documentation stuff :).

**Comment by eranif** [comment]
Ofc, I mentioned what **CodeLite** does with it:
* Uses it for better code completion
* Shows a tooltip

**Comment by pattisahusiwa** [comment]
I need your opinion about this problem. Consider I have code like this
````php
<?php
class StructA{public $a;}
class StructB extends StructA{public $b;}
class ClassA
{
    protected $struct;
    public function __construct(StructA $a)
    {
        $this->struct = $a;
    }
}
class ClassB extends ClassA
{
    public function __construct(StructB $b)
    {
        $this->struct = $b;
    }
}
````
Any idea how to make codelite knows that `$this->struct` in `ClassB` is `StructB`?

**Comment by eranif** [comment]
This is a problem. In the symbol lookup table, we only keep one instance of `ClassA` - this means that `protected $struct` can only be "commented" once.

By this can be an enhancement for the `@property` feature (which I have not yet implemented):
By adding `@property StructB $struct` CodeLite will create a new "instance" in the lookup symbol for `ClassB` for `$struct`

What do you think?

**Comment by pattisahusiwa** [comment]
It'll work. But, according to the doc, `@property` and `@method` have special job to serve magic method `__get`, `__set`, and `__call`. I don't know whether it will break the convention or not.

Another approach is keep parsing every `@var` tags. Little hack shows that this approach is working perfectly. In the image, the last record is added manually with `DOC_COMMENT=/** @var StructB */` and it works.
![](https://cloud.githubusercontent.com/assets/11484016/18180306/806bdfe4-70b0-11e6-9fe8-587123e2bfe3.png)

**Comment by eranif** [comment]
The problem is that CodeLite will not add the last entry `9999` by itself, since the `struct` is a member of `ClassA` and only one `struct` exist. So we cant keep both in the database. Personally, I think that the `@property` approach is the fastest and easiest solution, but I am not sure how it will affect the phpdoc conventions.

The full solution should be:
* Add new table to the database `PHPDOC_OVERRIDE_TABLE` (maybe we go with a different name....)
* Each `@var <type> <name>` defined in the class **body** (not in functions) are kept in this table
* When CodeLite loads a variable from the lookup table, it will perform a quick search on this table to replace the typehint based on this table.

So to get what you want, your code should look like this:

```PHP
<?php
class StructA{public $a;}
class StructB extends StructA{public $b;}
class ClassA
{
    protected $struct;
    public function __construct(StructA $a)
    {
        $this->struct = $a;
    }
}
class ClassB extends ClassA
{
    /// adding the below line will tell CodeLite that $struct is of type StructB when used from ClassB
    /** @var StrcutB $struct */
    
    public function __construct(StructB $b)
    {
        $this->struct = $b;
    }
}
```

**Comment by pattisahusiwa** [comment]
Yes, exactly same with what I mean. You can look at the image, ID 9996 and 9999 exactly pointed to the same variable but with different scope so they can't violate any SQL constraint. I mean you don't need to add another table. As in your code and mine (in the image), users MUST put `@var` tag before the variable, eq. inside a function, in order this approach to works.

**Comment by eranif** [comment]
You initial hack duplicated the entry in the database - something I really prefer **not** to do.
Using an additional table is just another way of adding an additional information for the real entry, its not about "SQL constraints" its about correctness.

I have implemented my method of adding new table

<img width="617" alt="php-extends-with-diff-type" src="https://cloud.githubusercontent.com/assets/3677711/18218651/ec8ccb5e-716c-11e6-9a7a-54946eca8fab.png">

**Comment by pattisahusiwa** [comment]
Ok, this will work for both editor and documentation
````php
/**
* for codelite purpose
* @var \StructB $struct
*/
/**
* for documentation purpose
*
* @param \StructB $b
* @return void
*/
public function __construct(StructB $b)
{
    $this->struct = $b;
}
````

**Comment by eranif** [comment]
Just an FYI: the second comment is also used by CodeLite

**Comment by pattisahusiwa** [comment]
Yes thank you. Second comment only works for `$b`.

Latest commit breaks something.

**Codelite 9.2.0**
![good](https://cloud.githubusercontent.com/assets/11484016/18224714/6c4e9ff6-7209-11e6-9744-8e4d5f2cf5ab.png)

**Latest code**
![error](https://cloud.githubusercontent.com/assets/11484016/18224723/a2723976-7209-11e6-9f63-ed97a65c18d9.png)

it fails to parse
````php
namespace phpseclib\Net;

/**
 * Pure-PHP implementations of SFTP.
 *
 * @package SFTP
 * @author  Jim Wigginton <terrafrost@php.net>
 * @access  public
 */
class SFTP extends SSH2
{
````
and breaks code completion.

btw, your latest code can't be compiled without add `algorithm` in `PHPLookupTable` and `PHPEntityClass` files (`std::reverse` and `std::for_each`).

**Comment by eranif** [comment]
I am not sure I follow what was broken - as all the PHP code completion unit tests passed successfully
Please provide a detailed example of what is not working in terms of: expected results vs actual result

**Comment by pattisahusiwa** [comment]
Ok, confirmed.
