### ISSUE TITLE
Can't unhide panels in the workspane pane

### ISSUE THREAD

**Issue by thompsonsed** [eranif/codelite#1388]
Running a macbook with OS X 10.11.6 and Codelite version 9.2.1. I hid a workspace pane as there was something graphically buggy with the file viewer (separate issue maybe). Now I can't re-open - can't find the option anywhere and wondering if it's a bug. Tested by closing the remaining plugin windows. Now presented a blank pane with no options (shown). Is this a bug or am I missing an option somewhere?
<img width="1247" alt="screen shot 2016-08-24 at 14 19 05" src="https://cloud.githubusercontent.com/assets/18483171/17920239/cf87e28c-6a05-11e6-9986-12f966e24017.png">

**Comment by thompsonsed** [comment]
I got around this by removing all application files for codelite from /Library/Application Support and ~/Library/Application Support. Now appears properly.

**Comment by thompsonsed** [comment]
Okay, so the problem was I had "Hide docking windows captions" ticked under Editor Settings so couldn't re-enable the panes. This was way more difficult than it should have been!

**Comment by eranif** [comment]
`CMD+F11` for quickly toggling the captions and tool bar
