### ISSUE TITLE
Target remake on every build

### ISSUE THREAD

**Issue by hsiemannwork** [eranif/codelite#1389]
When there are multiple projects in the workspace and a build order is defined I always observe a remake of the main target although nothing has changed after pressing F7. Attached is a build log with make option --debug=a.

[BuildOutput.txt](https://github.com/eranif/codelite/files/436407/BuildOutput.txt)

Operating system is Ubuntu 14.04 LTS
Compiler is gcc 4.9.3
Codelite Version 9.1.2

**Comment by eranif** [comment]
From the log above, I don't see an **real** build commands executed, only the deps are being scanned and generated

**Comment by hsiemannwork** [comment]
This is just a small example workspace. What I see in my Workspace with more than 100 Projects is, that the linker is calling on each build even if nothing changed. In detail the following line from the make log is not true:

   Prerequisite `"../.build-debug/Dep1"' of target `Debug/TestProject1' does not exist.

The file that make is looking for does exist. After this wrong estimation the following line is the result.

  Must remake target `Debug/TestProject1'.

This is what i found so far. I cannot explain myself why the build process wants to remake the target.

**Comment by eranif** [comment]
I see your point. I am afraid that I am not going to invest time on fixing this, as I am afraid changing anything in the build system will do more harm than good.

Waiting for the linker to link each project is acceptable (for me at least)
If you know nothing was changed and want to build only a single project, you can workaround it by right clicking **that** project and select `Project only->Build` this will skip the dependency list and will attempt to compile that project only
