### ISSUE TITLE
Cannot assign hotkey to Quick Find All

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1390]
Cannot assign hotkey to Quick Find All from menu Search/Find And Replach/Quick Find All

Quick Add Next has same problem

**Comment by eranif** [comment]
Does `Ctrl-K` / `Ctrl-Shift-K` does not work for you?
Also, I can change these settings from: settings->keyboard shortcuts

If you don't find these options (just type `quick` in the filter field)
Click on the `Defaults` button to make them re-appear

**Comment by eranif** [comment]
Sorry... I was referring to a different functionality...
