### ISSUE TITLE
#include autocomplete does not use correct paths?

### ISSUE THREAD

**Issue by hsnabn** [eranif/codelite#1391]
When trying to autocomplete header paths in an `#include` directive, I noticed that it gives technically correct paths, but not "relative" (not sure if that is the correct word for it).

For example, in my workspace code completion search paths I have this line:
```
C:/Projects/Game Development/Engines/Urho3D-1.6-Build/include
```
This `include` folder contains another folder `Urho3D`, which contains headers and other folders with their own headers.
Illustration:
```
Urho3D-1.6-Build
	|__include
		|__Urho3D
			|__Core
				Object.h
				Context.h
			Urho3D.h
```
...and so on.

But when I'm actually doing typing out `#include <Urho3D`, the code completion hints I get are in the form of:
```
Urho3D-1.6-Build/include/Urho3D/Core/Object.h
Urho3D-1.6-Build/include/Urho3D/Core/Context.h
Urho3D-1.6-Build/include/Urho3D/Urho3D.h
```
...and so on.

What I'm actually expecting is this:
```
Urho3D/Core/Object.h
Urho3D/Core/Context.h
Urho3D/Urho3D.h
```
Is there any way to enable this kind of behaviour? I looked around in the settings but could not find anything that seemed like it.

Thank you for any help.

**Comment by eranif** [comment]
This will not get fixed. As a workaround, once you type part of the path, e.g.:

`Urho3D/Core` and hit `Ctrl-SPACE` the list will "fix" itself
