### ISSUE TITLE
[PHP][Ubuntu] Open resources... show php extension icon for all files

### ISSUE THREAD

**Issue by anatooly** [eranif/codelite#1394]
OS: Linux anatooly 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 16.04)
CL version: 9.2.2 (manual compile) 

PHP Workspace -> Open resources... (Ctrl+Shift+R) for all files show only php icon, but on files tree we see actual icon.

![7238df6851f2074965bfd2a97a6c46041](https://cloud.githubusercontent.com/assets/317380/18043521/14f7d04c-6dd1-11e6-8f0a-186ec8c86ab9.png)

On screenshot all reproduce for JS, CSS files.

On C++ Workspace all right, C++ & H extension icons.

**Comment by eranif** [comment]
By default, `.less` files are not known to CodeLite. The fact that CodeLite shows a `CSS` icon for this file type, tells me that you either patched your CodeLite locally or did some configuration changes

**Comment by eranif** [comment]
I was wrong. Seems like a bug :/
