### ISSUE TITLE
failed to match pair of braces in less file

### ISSUE THREAD

**Issue by pattisahusiwa** [eranif/codelite#1396]
![a bug](https://cloud.githubusercontent.com/assets/11484016/18155641/c6b6a1a4-7039-11e6-86c2-7de99d858c4c.png)

**Comment by anatooly** [comment]
`
// testing
// ===================
li{
    > .active > a {
        &,
        &:hover,
        &:focus {
        }
    }
}
`

I tested your code and it show two problem:
1) One line comment highlight not work for me `//` only `/* */`
2) Parsing problem on  colon chars `:` if we write that all highlight correct:

`
// testing
// ===================

li {
    > .active > a {
        &,
        &hover,
        &focus {
        }
    }
}
`

P.S: LESS & SCSS language now only clone CSS syntax.
