### ISSUE TITLE
Editor Theme

### ISSUE THREAD

**Issue by Williams1996** [eranif/codelite#1397]
Hello! Excuse me ,I like this IDE very much, but there is a problem that I can`t choose the editor theme in my dell computer. 
![codelite-editor-theme](https://cloud.githubusercontent.com/assets/20469981/18162665/f37570c8-7069-11e6-845d-69b63fa732c7.png)
As the picture shows, this button is unable to selected.Could you show me how to setting it ,please?

**Comment by eranif** [comment]
This picture indicates that you are using an old version of CodeLite.
Please upgrade to the latest.

In the future, please specify which CodeLite version you are using, which OS and is it a self compiled CodeLite or an officical release. **NOTE** installing CodeLite from the official Ubuntu repository is not considered our official release. By official, I mean you should install it by following these instructions: http://codelite.org/LiteEditor/Repositories
