### ISSUE TITLE
Autocomplete data

### ISSUE THREAD

**Issue by Untonyst** [eranif/codelite#1400]
Add autocomplete data from a included files.

**Comment by eranif** [comment]
please provide more information.
I have no idea what you mean

**Comment by Untonyst** [comment]
> please provide more information.
> I have no idea what you mean

Well, when you write code, names of functions, constants and other things from include files (*.h) are shown in the form of tips from my project.
You already have autocomplete, but this worked in a current file.

![Screen](http://i.imgur.com/BoeeQhb.png)

Sorry for my English ;)

**Comment by eranif** [comment]
this is a basic functionality of codelite which works.
you need to save the file to get it parsed properly
