### ISSUE TITLE
Code completion "gives up" on typos

### ISSUE THREAD

**Issue by Quargzon** [eranif/codelite#1401]
**UPDATE:** I never realized this, but hitting ctrl+space seems to "wake" the suggestion box back up. Although it would make more sense to me for it to happen automatically, I've found the solution to my issue and it can safely be closed. Sorry!

**Original post:**
When typing, the code completion dropdown will appear as expected. However, if the user makes a typo and the symbol no longer matches any of the suggestions, the dropdown dissappears. This is the expected behavior.

**Unfortunately, it seems that if the user backspaces the incorrect characters, code completion does not recover despite matches existing for the remaining untouched characters. The suggestion dropdown does not reappear unless the symbol name is backspaced completely and retyped from the beginning.**

This can get frustrating when working with large libraries that expose many functions and constants with long names, as a single typo might force you to start the whole line over if you're not familiar with the precise names. I've worked with CodeLite for at least a year or so, and the issue has always been present.

**Comment by eranif** [comment]
I was about to ask: what's wrong with hitting `ctrl+ space`?
