### ISSUE TITLE
"Save as" issue

### ISSUE THREAD

**Issue by gigabyte7ipev** [eranif/codelite#1404]
When I save a file in php, in the workspace, I have to manually sync the project in order to see the new file.

**Comment by eranif** [comment]
Can you please provide a steps to reproduce?

**Comment by gigabyte7ipev** [comment]
Steps (over ubuntu): 
1 - open a php file
2 - save as "new name"
3 - nothing new in workspace
4 - manually "sync projects with file system" in order to see it

**Comment by gigabyte7ipev** [comment]
Same issue with "Duplicate tab"
