### ISSUE TITLE
Inconsistent variable visibility

### ISSUE THREAD

**Issue by pattisahusiwa** [eranif/codelite#1406]
I was wondering why code-completion still shows private or protected variables outside the class. Probably this incosistency is one of the causes.Variables visibility don't match between code-completion and outline.

OS: Arch Linux x86_64
Codelite: 9.2.2

![inconsistent](https://cloud.githubusercontent.com/assets/11484016/18386692/bc4bb3fa-76c2-11e6-9bae-d7a0ed1bc9bf.png)

**Comment by eranif** [comment]
This is because the code completion does not really check if it is inside or outside the class scope.
This is not something we are going to change since the way I see it, the code completion is just a
helper, its up to the user to decide whether or not to choose that option
