### ISSUE TITLE
Feature Request - Independent Executable While Debugging

### ISSUE THREAD

**Issue by mirage335** [eranif/codelite#1408]
Allow executable files to run independently with the debugger. This is useful when the application is actually a chain of commands, or simply reads serial port to console. Specifically, when debugging Arduino output that will be fed into a chain of programs for signal processing, as with https://github.com/mirage335/BiosignalProcessor .

**Comment by eranif** [comment]
I can see how it is useful, but it requires a massive redesign and time which I don't have
