### ISSUE TITLE
Outline Plugin - Recognize *.ino as cpp.

### ISSUE THREAD

**Issue by mirage335** [eranif/codelite#1409]
Please consider configuring the outline plugin to recognize "*.ino" files (Arduino sketches) as having C++ content, essentially identical to "*.cpp" files.

Also, the outline plugin does not always immediately recognize all entities in a file, requiring a change to be made followed by "Ctrl+S" (save). Performing a few extra refreshes upon initialization would save some unnecessary edits.

**Comment by eranif** [comment]
About the `Ctrl-S` update: this is not going to change.
What I will change is adding a new plugin to auto-saves files

**Comment by mirage335** [comment]
Neither problem reported in this issue requires the Ctrl+S update behavior to change.
In particular, the first problem, recognizing "*.ino" files, simply requires these files be treated as if they were "*.cpp" by the outline plugin.
The second issue has been difficult to reproduce under the very latest versions of CodeLite (-git package for Arch), and is much less critical.
