### ISSUE TITLE
The directory name is no longer included in .o files

### ISSUE THREAD

**Issue by FaTony** [eranif/codelite#1410]
Previous versions of CodeLite had directory names added to .o files while latest version doesn't. I have foo.cpp and bar/foo.cpp and they both get compiled to foo.cpp.o which, of course, breaks everything.

**Comment by eranif** [comment]
Not a bug,  a settings option.
`Settings->Build Settings->Compilers->Your Compiler Name->Advanced`
and uncheck the option: `Object name is same as the file name`

**Comment by FaTony** [comment]
I've just checked and it is unticked. Please reopen.

**Comment by eranif** [comment]
I retested this and it works...
please provide more information

**Comment by eranif** [comment]
try deleting ~/.codelite folder and try it again

**Comment by FaTony** [comment]
Tried it and still occuring, here's a part of my .project file:

<VirtualDirectory Name="src">
    <VirtualDirectory Name="ALSA">
      <File Name="../../Src/ALSA/OutputDevice.cpp"/>
    </VirtualDirectory>
    <File Name="../../Src/OutputDevice.cpp"/>
</VirtualDirectory>

**Comment by eranif** [comment]
I will need a reproduction workspace to be able to look in this further.
I can't make it happen on Windows nor Linux.

**Comment by FaTony** [comment]
Here's the full project: https://gitlab.com/ftz/midi
I will try to make a small test case.

**Comment by eranif** [comment]
BTW, I see that you use `CMake` - you can enable this from CodeLite to use CMake as well...
`Project Settings->Makefile Generator->CMake`

For more info: http://codelite.org/LiteEditor/TheCMakePlugin

**Comment by FaTony** [comment]
Well, I've made a hello world project but for some reason can't upload it on GitHub, this happens for other files too.

**Comment by eranif** [comment]
Can you send it to me directly? (my email can be found on my profile)

**Comment by FaTony** [comment]
Done.

**Comment by eranif** [comment]
I fixed the object prefix generation function.
It did not work due to your unique workspace layout... the fix should handle this now (and any other layout in the future)
```
/bin/sh -c '/usr/bin/make -j4 -e -f  Makefile'
----------Building project:[ Test - Debug ]----------
make[1]: Entering directory '/home/eran/Downloads/test/IDE/CodeLite'
codelite-cc g++  -c  "/home/eran/Downloads/test/Src/Test/Main.cpp" -g -O0 -std=c++14 -Wall  -o ./Debug/up_up_Src_Test_Main.cpp.o -I. -I.
codelite-cc g++  -c  "/home/eran/Downloads/test/Src/Main.cpp" -g -O0 -std=c++14 -Wall  -o ./Debug/up_up_Src_Main.cpp.o -I. -I.
/usr/bin/g++ -o ./Debug/Test @"Test.txt" -L.
make[1]: Leaving directory '/home/eran/Downloads/test/IDE/CodeLite'
====0 errors, 0 warnings====
```
