### ISSUE TITLE
Code completion on MacOS

### ISSUE THREAD

**Issue by kilon** [eranif/codelite#1411]
I have installed Codelite 9.2.0 and I am on MacOS Yosemite, full updated including XCODE.
I have added to CTag settings the following paths
``` bash
/usr
/usr/include
/Applications/Xcode.app/Contents/Developer
```

It should be able to find iostream but each time I type std:: it never automcompletes as I would expect also it does not auto complete includes. Is this normal behavior ? 

Also tried same paths with Clang autocompletion

**Comment by eranif** [comment]
No... it should work.
I am near my Mac atm, I will be able to look into this later today

**Comment by eranif** [comment]
For me there are many more paths. Did you install the command line tools from XCode?

Here is how the ctags->search paths looks on my MacBook:

```
/Library/Developer/CommandLineTools/usr/include
/Library/Developer/CommandLineTools/usr/include/c++/v1
/Library/Developer/CommandLineTools/usr/lib/clang/7.0.2/include
/Library/Frameworks
/System/Library/Frameworks
/usr/include
/usr/local/include
```

**Comment by eranif** [comment]
Ping

**Comment by eranif** [comment]
It seems to me like a configuration issue. Closing this issue, if you still need help please start a discussion on CodeLite forum.

**Comment by kilon** [comment]
yes thank you, indeed this is not a bug

I did what you suggested, for a moment it did not work even with parsing workspace and then I built my project and it worked :)

One more very happy customer, and by the way amazing IDE, no clue how you manage to do this by yourself, keep up the awesome work, I will use the forums from nown on.
