### ISSUE TITLE
Finished Support for ubuntu 12.04 ?

### ISSUE THREAD

**Issue by ronigonzalez** [eranif/codelite#1417]
I'm trying to install CodeLite 5.4 con al Ubuntu 12.04 LTS virtual Machine to use a compilation machine,
but repos are not available and I can not find a .deb file.
How can I proceed to install codelite 5.4 in ubuntu 12.04 (32 bits)  ?
Thanks !

**Comment by eranif** [comment]
This is now a bug.
Please start such discussions on the forum
