### ISSUE TITLE
Importing an old FB project problem

### ISSUE THREAD

**Issue by tester0077** [eranif/codelite#1418]
Just tried to import an old and rather big 1.25 MB FB project into both wxCrafter stand-alone 2.5 & 2.6 and the main base frame header causes problems because it starts with
//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxSRf.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef **3_0_**WXSR_WXCR_WXSRF_BASE_CLASSES_H  <<<<< 
#define 3_0_WXSR_WXCR_WXSRF_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>

Where the 3_0 causes problems becayse identifiers may not start with a digit

PS: might it not be an idea to include the wxCrafter version in the 'header" ?? :-)

**Comment by eranif** [comment]
The `3_0` is not coming from the wxC version, but rather from the source file/class name that is being imported

**Comment by tester0077** [comment]
OK, it actually seems to come from the grand-parent directory??
I had
.../msvc2015/3.0/proj/xxxx.wcp
                   ----
Changing the 3.0 to M3.0 got me: #ifndef M3_0_
So the mystery is explained and I can carry on, but ....
why use any part the path in this??

**Comment by eranif** [comment]
To generate a unique `if/ndef` block
I will ensure that the block guard starts with an underscore to avoid such cases in the future

**Comment by tester0077** [comment]
Sounds good; thank you.

**Comment by eranif** [comment]
Fixed
