### ISSUE TITLE
comment/uncomment with different select(highlight) direction

### ISSUE THREAD

**Issue by gbuntu127** [eranif/codelite#1419]
`Codelite version 9.2.2`
`Kernel: 4.4.0-34-generic x86_64 (64 bit) Desktop: Cinnamon 3.0.7, Distro: Linux Mint 18 Sarah`

**Scenario**: 
A.this is c++ code line one
this is c++ code line two.B
1. Select both lines use mouse, select "Edit-Comment-Comment Line". Result: both lines will be commented out.
2. Use mouse cursor to select both lines. Specifically, click from letter A, hold and drag mouse to highlight to letter B. Select "Edit-Comment-Comment Line". Result: both lines will be added one more "//" in front. Expected: the two lines of code are un-commented. 

_However_, if in step 2 we do "click from letter B, hold and drag highlight to letter A" (different highlight direction). Select "Edit-Comment-Comment Line". Result: both lines are correctly un-commented.  

This actually happens to single line of code as well.

**Comment by eranif** [comment]
I am unable to reproduce this (for me, no matter the highlight direction, it always "toggles" the selection)
Can you upload a sample file? maybe there are some tabs/spaces before the code section that causes unpredictable behavior?

**Comment by gbuntu127** [comment]
This happens even to the simplest file. It has nothing to do with the tabs/spaces as it happens even when no space/tabs before the characters. Note that at Step 2 above for "Use mouse cursor to select both lines", I meant to select everything including the added "//" from step 1. 

I am not sure what your expected behavior for selecting lines of code with leading "//". For me, I expect the leading "//" being removed. In fact, when I highlighted from //A to B (as shown below), it indeed toggles the comment. Highlight from the other direction only adds more leading comment "//" for both lines. 

//A.this is c++ code line one
//this is c++ code line two.B



[test.cpp.txt](https://github.com/eranif/codelite/files/480672/test.cpp.txt)

**Comment by eranif** [comment]
Still, works...
See this short mp4 video I captured:

http://codelite.org/tmp/toggle-comment.mp4

**Comment by gbuntu127** [comment]
It still does not work for me. I did the same thing as you did but having different behaviors. See my captured video:

![toggle-comment2](https://cloud.githubusercontent.com/assets/1526055/18719668/f117f4a2-7fed-11e6-8d9e-507c0b405668.gif)

I guess it is just system related bug.

**Comment by gbuntu127** [comment]
I also tried to use a fresh ~/.codelite folder and it was the same result.

**Comment by eranif** [comment]
The only difference is that I am using Windows and you are using Linux, will try on my Linux box

**Comment by pattisahusiwa** [comment]
> Still, works...
See this short mp4 video I captured:

Actually, the issue is also shown on your video. you selected 2 lines, but 3 lines have been commented.

**Comment by gbuntu127** [comment]
That was how codelite did it when I highlighted from the line start to the line end.
