### ISSUE TITLE
Compiling error caused by clTabRenderer.cpp

### ISSUE THREAD

**Issue by snowxmas** [eranif/codelite#1421]
In clTabRenderer.cpp, line 93 need to be surrounded by "#if CL_BUILD".
And I have a problem that what's the difference between the macro "WXUSINGDLL_CL" and "WXUSINGDLL"?

**Comment by eranif** [comment]
The build error is fixed.
`WXUSINGDLL` is used when building wxWidgets as a DLL, while `WXUSINGDLL_CL` is used for building `libcodelite.dll` as DLL (this is the declspec macro for exporting symbols from the DLL for Windows)
