### ISSUE TITLE
always get error when running with SDL2, I don't get this issue in QT and previous version of codelite

### ISSUE THREAD

**Issue by nullptr023** [eranif/codelite#1427]
I build it successfully but I can't run it properly I get this error
./SDL_game: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory

Note: I have this file in /usr/local/lib/SDL2/ that's why I'm confuse why it doesn't see it

In QT everything works fine, and before I unistall the old version of codelite sdl2 is working.
I setup the lib location /usr/local/lib/SDL2/ 
and I put all this link option -lSDL2 -lSDL2_image -lSDL2_mixer  -lSDL2_ttf 
and I also add this include files /home/SDL2.0.4/SDL2-2.0.4/include

and I still got this error

**Comment by eranif** [comment]
Can you run program from a terminal? I suspect it will fail to start from the same error...

It's not CodeLite fault - its how the runtime linker works (QtCreator probably tweaks the environment variables for you so it will work within the IDE, but it will fail outside of the IDE)

Your executable requires `libSDL2-2.0.so.0` the location must be in the `LD_LIBRARY_PATH` so it will be found when running it, or you should pass `rpath` to the linker with the location of the SDL directory where the shared object can be found.

To make it work (from within CodeLite or from a plain Terminal), add this to the project settings->linker->linker options:

`-Wl,-rpath,/usr/local/lib/SDL2/`

**Comment by nullptr023** [comment]
It still doesnt run. I used the previous old version of codelite before and
I just set the linker like i mentioned here and the includes path and it
works fine. But now it's not working.

On Sep 26, 2016 12:57 AM, "Eran Ifrah" <notifications@github.com> wrote:

Can you run program from a terminal? I suspect it will fail to start from
the same error...

It's not CodeLite fault - its how the runtime linker works (QtCreator
probably tweaks the environment variables for you so it will work within
the IDE, but it will fail outside of the IDE)

Your executable requires libSDL2-2.0.so.0 the location must be in the
LD_LIBRARY_PATH so it will be found when running it, or you should pass
rpath to the linker with the location of the SDL directory where the shared
object can be found.

To make it work (from within CodeLite or from a plain Terminal), add this
to the project settings->linker->linker options:

-Wl,-rpath,/usr/local/lib/SDL2/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/eranif/codelite/issues/1427#issuecomment-249485324>,
or mute
the thread

**Comment by eranif** [comment]
But: can you run your program from a terminal?

**Comment by nullptr023** [comment]
It runs before so im not sure why it doesnt run now. Cause before i use any
ide i will try to run it first in terminal. I already set up all possible
things to run it but no luck.  But it's not codelite I think if it stops
working on terminal. Thanks if you got any idea it doesnt run let me know.
I wanted codelite that's why i uninstall the old one i just need to
configure why sdl doesnt work now. Thanks again

**Comment by nullptr023** [comment]
I already solved the issue. now I setup properly the LD_LIBRARY_PATH and it
works in terminal. but it doesn't recognize in codelite I think. cause I
need to put LD_LIBRARY_PATH=/librarypath/ as additional environment variable

On Tue, Sep 27, 2016 at 6:56 AM, Austin Villanueva <programmer9323@gmail.com
> wrote:

> It runs before so im not sure why it doesnt run now. Cause before i use
> any ide i will try to run it first in terminal. I already set up all
> possible things to run it but no luck.  But it's not codelite I think if it
> stops working on terminal. Thanks if you got any idea it doesnt run let me
> know. I wanted codelite that's why i uninstall the old one i just need to
> configure why sdl doesnt work now. Thanks again
>
