### ISSUE TITLE
Cannot make hotkeys for menu options View/Next tab and View/Previous tab

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1430]
Cannot make hotkeys for menu options View->Next tab and View->Previous tab

Seen with CodeLite-9.2.0 @ ArchLinux 64 bit

**Comment by eranif** [comment]
For me I have the options in Settings->Keyboard Shortcuts
(Just type in the filter: tab next)

If you don't get them, you will need to click on the "Default" button to get them showing for you
