### ISSUE TITLE
Editor is not auto recognize encoding of file

### ISSUE THREAD

**Issue by expo87** [eranif/codelite#1431]
If encoding file is cp1251, when save this file in CodeLite he auto encoding this file in utf-8. Thats broken file. Need auto recognize encoding of file and when doing save operation - save file in the same encoding.
http://joxi.ru/LmG7yOjcRVbdwm.jpg
Thanks!

**Comment by eranif** [comment]
This was requested many times before but due to lack of resources, I will not be able to implement this.
A pull request will be highly appreciated
