### ISSUE TITLE
Search & replace doesn't show buttons

### ISSUE THREAD

**Issue by patlefort** [eranif/codelite#1432]
The search and replace windows isn't showing any buttons on the right. This is on Fedora with the latest build.
![search_replace_problem_codelite](https://cloud.githubusercontent.com/assets/3423714/18907563/1629a73a-853a-11e6-9d99-b1b1ac7a71ee.png)

**Comment by eranif** [comment]
@dghart any ideas?

**Comment by dghart** [comment]
Hi,
>This is on Fedora with the latest build.

Which version of fedora? And which 'latest build' of CodeLite? The packages that we supply, or one you built yourself?

I can't reproduce this on fedora 24 with our CodeLite package. However I know fc24 uses a recent version of gtk+3, which has caused various sizing problems for programs like CodeLite that use the wxWidgets toolkit: see http://trac.wxwidgets.org/ticket/17585 
So this may be another instance. Does resizing CodeLite with the mouse make any difference?

Regards,

David

**Comment by patlefort** [comment]
Fedora 24, all up to date. I have tried the stable version and the latest version built from git. Strangely I don't get the problem on my laptop (only tested stable on laptop), only on my desktop. Both are running the same Fedora and XFCE. I tried changing GTK theme.

**Comment by dghart** [comment]
My guess was obviously wrong then. And my next guess was going to be to try a different theme.

As you say, it's strange it only happens on the desktop. You could try copying over the laptop's ~./codelite/ dir to the desktop (after renaming the original).

Failing that, maybe it's some gtk configuration issue. Or xfce's; you could try a different DE...

**Comment by patlefort** [comment]
I figured out why it happens. It happens when you input a very long search string, then close and reopen codelite. It seem that the long string in the drop down menu for the history is expanding the text box and pushing out the buttons.

**Comment by eranif** [comment]
This sounds like a bug in wxWidgets to me.
Can you please report this to wxWidgets [issues tracker](http://trac.wxwidgets.org/browser/wxWidgets)?
