### ISSUE TITLE
PHP Parser not Working with Special Characters

### ISSUE THREAD

**Issue by jgmdev** [eranif/codelite#1433]
Adding special characters to comments like áéíóúäëïöü, etc... breaks the PHP Parser resulting in a empty outline and code completion symbols database. This worked before so it seems that a recent commit broke it.

Here is some sample code that previously worked and now doesn't (notice the **á**):

```php
<?php
/**
 * Something
 * @author First Lást Name
 */

 class MyClass
 {
     private $var1;

     private $var2;

     public function functionOne(){}

     public function functionTwo(){}
 }
```
but if I remove the **á** then it works:

```php
<?php
/**
 * Something
 * @author First Last Name
 */

 class MyClass
 {
     private $var1;

     private $var2;

     public function functionOne(){}

     public function functionTwo(){}
 }
```

**Comment by eranif** [comment]
Seems to be working here...
<img width="569" alt="works" src="https://cloud.githubusercontent.com/assets/3677711/18932931/263bb626-85db-11e6-93a5-7c5903132f90.png">

**Comment by jgmdev** [comment]
thats strange... I just built the latest code from github (ArchLinux) using https://aur.archlinux.org/packages/codelite-git (which I maintain) and it isn't working...

**Comment by jgmdev** [comment]
Here is a screenshot of mine
![test](https://cloud.githubusercontent.com/assets/1702572/18933471/f6321700-85a2-11e6-82fc-c3b9c7c7d59c.png)

**Comment by eranif** [comment]
There is a bug that if the caret is the last char, the completion is not working. add some empty lines at the end of the file and try to code complete while making sure that the caret is *not* at the last position

**Comment by jgmdev** [comment]
Doesn't seems to be the case, I even compiled wxWidgets with gtk3 and various different flags but it didn't worked, here some screenshots that show the version with special character and non special character

![acute](https://cloud.githubusercontent.com/assets/1702572/18943919/83b206ba-85f0-11e6-8054-0e9826b908b0.png)

no special character

![non-acute](https://cloud.githubusercontent.com/assets/1702572/18943925/8dc404dc-85f0-11e6-938c-672d5b575ba2.png)

Also, I compiled the latest stable version 9.2.0 and that one works.

**Comment by eranif** [comment]
Works on Debian 8 as well :/ is it possible to get a minimal workspace that mimic the problem? (maybe its not that single file that causes the problem)

**Comment by pattisahusiwa** [comment]
Works here. Arch Linux x86_64, kernel 4.7.4-1-ARCH, i3-wm, Codelite 9.2.2

![bugs](https://cloud.githubusercontent.com/assets/11484016/18951092/5e30de70-866d-11e6-898e-5fe781de1790.png)

**Comment by jgmdev** [comment]
@pattisahusiwa I'm using Codelite 9.2.4 which is the latest here on github (master). Since you are on ArchLinux as me, would you try building the latest with codelite-git PKGBUILD from AUR that uses the git repo, to see if you also get the same issue? I can even upload my .pkg.tar.xz build of yesterday somewhere in case you don't want to build again.

@eranif I created a new PHP workspace and added a new single file to it with the sample code as the screenshots above. Like I said before, it works properly on 9.2.0 and as I see from pattisahusiwa screenshot it also works on 9.2.2, unless something is busted on my machine (which I doubt, but who knows :smile:)

**Comment by eranif** [comment]
Can you try and revert commit e5fd43561f5f87d504da8544f233d1fbf430b13f and see if it helps?

**Comment by jgmdev** [comment]
Reverting that commit does fix the issue! I was inspecting every PHP related commit and reverting it, glad you found cause already since I'm not familiar with codelite codebase :)

**Comment by eranif** [comment]
This indicates that your locale is set differently.
what is the value of your `LC_ALL` ?

**Comment by jgmdev** [comment]
```sh
echo $LC_ALL
```
Output:
en_US.UTF-8

**Comment by jgmdev** [comment]
Changing this:
```cpp
wxCharBuffer cb = content.mb_str();
```
to this
```cpp
wxConvAuto autoConvert;
wxCharBuffer cb = content.mb_str(autoConvert);
```
works as expected

**Comment by eranif** [comment]
I now needs to check that it does not break the original bug it fixed...

**Comment by jgmdev** [comment]
Already checked and yes it does break it, im testing another solution involving 

```cpp
void* phpLexerNew(const wxString& content, size_t options, bool convert=true)
{
    yyscan_t scanner;
    phplex_init(&scanner);
    wxCharBuffer cb;
    if(convert) {
        wxConvAuto autoConvert;
        wxCharBuffer cb = content.mb_str(autoConvert);
    } else {
        cb = content.mb_str();
    }
    struct yyguts_t * yyg = (struct yyguts_t*)scanner;
    yyg->yyextra_r = new phpLexerUserData(options);
    php_switch_to_buffer(php_scan_string(cb.data(), scanner), scanner);
    yylineno = 0;
    return scanner;
}
```
and 
```cpp
m_scanner = ::phpLexerNew(buffer, kPhpLexerOpt_ReturnComments | kPhpLexerOpt_ReturnAllNonPhp, false);
```

**Comment by jgmdev** [comment]
I have tried almost every wxMBConv* class and I don't understand what is causing the builtin formatter to fail... In any case I put a patch where the conversion explicit conversion using wxConvAuto can be omitted but I'm not sure if it is my end or what... the code formatter doesn't do anything... The php-cs-fixer works as intended but not the builtin one, in any case here I post the patch:

[workaround.txt](https://github.com/eranif/codelite/files/501817/workaround.txt)

**Comment by jgmdev** [comment]
So I was doing some more testing since the builtin codeformatter wasn't doing anything I deduced that the mb_str conversion was failing and when I revised it was returning an empty string and 0 lenght, so thats why phpLexerNew wasn't doing anything. Thinking it was an encoding issue from wxWidgets I tried the following:

```cpp
void* phpLexerNew(const wxString& content, size_t options, bool convert)
{
    yyscan_t scanner;
    phplex_init(&scanner);
    struct yyguts_t * yyg = (struct yyguts_t*)scanner;
    yyg->yyextra_r = new phpLexerUserData(options);

    if(!convert) {
        wxString tempFileName = wxFileName::CreateTempFileName("codelitetemp");
        wxFile* tempFile = new wxFile(tempFileName, wxFile::OpenMode::write);
        tempFile->Write(content);
        size_t tempSize = tempFile->Length();
        tempFile->Close();
        delete tempFile;

        FILE* fp = ::fopen(tempFileName.mb_str().data(), "rb");
        if(!fp) {
            return NULL;
        }

        char fileContent[tempSize];
        ::fread((void*)fileContent, 1, tempSize, fp);

        ::fclose(fp);

        php_switch_to_buffer(php_scan_bytes(fileContent, (int) tempSize, scanner), scanner);

        wxRemoveFile(tempFileName);

    } else {
        wxConvAuto autoConvert;
        wxCharBuffer cb = content.mb_str(autoConvert);

        php_switch_to_buffer(php_scan_string(cb.data(), scanner), scanner);
    }

    yylineno = 0;

    return scanner;
}
```
Now the builtin codeformatter works again on my end but it strips all non ascii characters like in issue #1365 so my conclusion is that this isn't something that should be fixed on the parser, I think the issue resides somewhere on the codeformatter which I deduce does some kind of conversion when inserting the code back to the editor which messes up with non ascii characters. 

Other possible cause can be an issue with locales and wxWidgets but i'm not sure about that, would need more testers to determine the cause of this issue.

**Comment by jgmdev** [comment]
Jumm, so I tried something else to be sure:

```php
<?php
/**
 * Something
 * @author First Lást Name
 */

class MyClass
{
    private $var1;

    private $var2;

    /**
     * Som tést
     * @return int 
     */
    public function functionOne(){}

    /**
     * Some other test
     * @return  void
     */
    public function functionTwo(){}

    public function actionLogout(){$this->getUser()->logout();
        $this->flashMessage('Odhlásenie prebehlo úspešne!');
        $this->redirect("Login:");
    }
 }
```
The code completion list doesn't not displays the description of functionOne(), which means that the issue does resides on the parser :confused:, seems that the parser isn't capable of properly handling utf8 strings or am I missing something...

Anyways, thats all the testing for me today and trying to fix the issue :disappointed: .

**Comment by eranif** [comment]
Please try my latest commit https://github.com/eranif/codelite/commit/3cbec863f51640f92c16e45d4334addffb744ed6

The fix (which works here) removes all the auto conversion from `std::string` to `wxString` and explicitly converts `std::string` to `wxString` using the `wxConvUTF8` object

**Comment by jgmdev** [comment]
Great :D, thanks a lot! it works! Now I only see 1 issue on the outline but I don't think people will use utf8 characters to name PHP elements, but who knows..., php seems to support it (just tested naming a function with 'á' character and calling it and worked).

![works](https://cloud.githubusercontent.com/assets/1702572/18982261/a901670e-86b2-11e6-943a-620ad279e225.png)
