### ISSUE TITLE
minor OSX build codelite issue:  wx wouldn't build because  QTKit has been deprecated

### ISSUE THREAD

**Issue by timtoomay** [eranif/codelite#1435]
QTKit has been deprecated in 10.9. AVFoundation and AVKit are the frameworks recommended for all new development involving time-based audiovisual media on OS X. In order to transition your project from QTKit to AVFoundation please refer to: "Technical Note TN2300 Transitioning QTKit code to AV Foundation".

Resolution:   
```
../configure --enable-shared --enable-monolithic --with-osx_cocoa CXX='clang++ -std=c++11 -stdlib=libc++' CC=clang --with-macosx-version-min=10.8 --disable-mediactrl --disable-debug
```

**Comment by eranif** [comment]
Thanks, I have updated the wiki on how to properly build wxWidgets
