### ISSUE TITLE
Codelite freezes at startup logo

### ISSUE THREAD

**Issue by lenoil98** [eranif/codelite#1436]
Unable to build codelite on FreeBSD/PowerPC64 from ports due to numerous wxTextCtrl errors.  Port will not build against wxWidgets 3.1, only 3.0.  So tried to build from GitHub ources.  No errors encounters. Resulting build freezes at startup logo.  However, codelite will startup if plugins are disabled, using "codelite -n" command-line.  Seems to work okay, but no plugin support.

Build environment: FreeBSD 10.2, GCC 5.0, wxWidgets 3.1.1, cmake 3.5.2

**Comment by eranif** [comment]
I don't have FreeBSD, can you start CodeLite under debugger and see why it hangs?

**Comment by lenoil98** [comment]
Problem solved! I had to replace the stock gcc runtime library (/lib/libgcc_s.so.1) with the newer one from gcc5.0.  Apparently, newer versions of gcc use functions that are not in the older gcc runtime library.

 

Regards,

Curtis
