### ISSUE TITLE
wxAuiPaneInfo in XRC

### ISSUE THREAD

**Issue by MaverickTse** [eranif/codelite#1438]
While wxCrafter (in codelite 9.2.4) support adding wxAuiManager in C++ mode, the XRC code generated(notably, wxAuiPaneInfo) is wrong and unusable with wxWidget 3.1.1 (compiled from github master branch).

I can't find relevant issue reported here so I assume few notice this.

Can someone starts working on this and meanwhile give a warning to user, say a popup dialog, stating the auimanager is not yet supported in XRC, until it is fixed?

**Comment by eranif** [comment]
When I added support for wxAuiPaneInfo in wxCrafter, wxWidgets did not have an handler for it so I had to come up with one...
They now added support (will be available in wx3.1.1), obviously my XML property field names do not match their names - this needs to be adjusted in order to make it work

**Comment by eranif** [comment]
This is now fixed.
wxCrafter now generates wxWidgets compatible XRC for both `wxAuiPaneInfo` and `wxAuiManager`
