### ISSUE TITLE
Smart pointer is not recognize

### ISSUE THREAD

**Issue by Psyrkoz** [eranif/codelite#1440]
Hi,

I have found a problem with Smart Pointer. Some screenshot to explain:

http://www.noelshack.com/2016-40-1475768168-decl.png
http://www.noelshack.com/2016-40-1475768169-init1.png

So, basically, when i use the `->` to say "HEY IM USING A POINTER", he don't recognize anything 😢  BUT the code work... The completion just don't recognize my smart pointer as a pointer.

He should do something like that:

http://www.noelshack.com/2016-40-1475768169-aworkingpointer.png

**Comment by eranif** [comment]
By default CodeLite uses it own parser, which is not fully supporting all the C++ capabilities.
For this purpose, CodeLite also supports code completion using `libclang` (which is a full compiler).

I just checked and indeed,out of the box this code:
```c++
std::unique_ptr<std::string> p;
p. // works
p-> // does not work
```

You have two options here:

1. In the `Settings->code completion->CTags tab->Advanced tab->Types tab` add this entry at the bottom `std::unique_ptr::pointer=_Tp` - and it should work
2. Enable `clang` code completion from: `Settings->code completion->Clang->Enable clang code completion` (**Dont** tick the second option on that page)

I will make option `1` default in future CodeLite builds
