### ISSUE TITLE
Build project : No rule to make target '".build-xxxx', needed by 'xxx' . Stop.

### ISSUE THREAD

**Issue by Althar93** [eranif/codelite#1443]
Hello,

I am currently experiencing an issue with Codelite / premake-codelite. Specifically, when building one of the projects in my workspace with "Build Project", I get : 

**make[1]: **\* No rule to make target '".build-linux64', needed by 'bin/Biosphere_debug'. Stop.**

From the looks of it, the auto-generated **.mk** file is missing the entry for **.build-linux64**.

_Note, I am able to build the workspace & both of its projects using "Build Workspace" - the executable then runs fine & I am also able to debug it._

I have attached my premake lua configuration as well as the auto-generated **.mk** file. I will attach the Codelite **.project** file as soon as I have access to my working machine.

[no_target.tar.gz](https://github.com/eranif/codelite/files/521289/no_target.tar.gz)

Thanks,

**Comment by eranif** [comment]
We don't support .project files generated by external tools (i.e. premake)
