### ISSUE TITLE
PHP postback debugging request

### ISSUE THREAD

**Issue by jtmurphy1k** [eranif/codelite#1444]
Codelite is an excellent interface for PHP web site development that would be even better if debugging could be continued from a web page postback.

**Comment by eranif** [comment]
Do you mean: writing something like this in the browser:
```
http://localhost/test.php?XDEBUG_SESSION_START=codeliteide
```
and CodeLite will start debugging?

**Comment by jtmurphy1k** [comment]
Using the XDEBUG parameter in the browser url still does not toggle CodeLite to listen for the debug request. My browser (Iceweasel) passes the codeliteide cookie back to the server just fine. It appears that CodeLite only listens for the web server debug request when the hit request (F5) is initiated from within the CodeLite IDE. Once the initial page is debugged within the CodeLite IDE (works great) and the web page is returned to the browser, subsequent postbacks initiated from the browser will not toggle CodeLite into debugging because CodeLite is no longer listening for debug requests. I would like a way to toggle the CodeLite IDE into listening for web server debug requests other than the IDE F5 key or green play arrow. I believe MS Visual Studio solves this with a built-in IDE browser that is integrated with the IDE debugger.

**Comment by eranif** [comment]
You answered my question.
I know it does not work in the version you have, I just committed this today (wanted to confirm that this is what you expected)

I added new button in the workspace view, when clicked, CodeLite will start listening for new connections from the debugger (initiated by the browser)
<img width="252" alt="php-server-side-debugger" src="https://cloud.githubusercontent.com/assets/3677711/20149952/209d4b74-a6bc-11e6-8c9a-81c30a443827.png">
