### ISSUE TITLE
[Feature Request] Virtual Folders for Projects

### ISSUE THREAD

**Issue by yaakuro** [eranif/codelite#1445]
Hi CodeLite Team

CodeLite has already Virtual Folders for files. I would be nice to have Virtual Folders for Projects in a Workspace too. For example that it is possible to put Projects into a Virtual Folder.

**Comment by eranif** [comment]
<img width="212" alt="workspace-folders" src="https://cloud.githubusercontent.com/assets/3677711/19827721/d3da2324-9dbb-11e6-8dc1-6f30aba83b34.png">

You can now create a workspace folder and place your projects in it.
I have also enabled DragAndDrop of projects to the new workspace folder. The workspace folder uses a gray colour to distinguish them from the normal virtual folder (they have a different purpose and context menus)

**Comment by yaakuro** [comment]
Wow awesome, thx a lot man. CodeLite is really nice peace of software.

**Comment by eranif** [comment]
Important: when you use this new feature, anyone with an older version of CodeLite who attempts to open the workspace will only see the projects which are a direct children of the workspace, not those inside workspace folders. So use with caution
