### ISSUE TITLE
Mouse cursor not visible with dark themes

### ISSUE THREAD

**Issue by Arandhras** [eranif/codelite#1446]
Hello,
I have noticed that the mouse cursor is barely visible (when not at all) when it is hovering the editor area when using a dark theme. Is it possible to set it to white instead of black?

**Comment by eranif** [comment]
Hi,
As someone who uses dark themes, It does not occurs here (the default caret colour is set to white for dark themes)

Can you post a screenshot?
Also:

* Which version of CodeLite?
* Which OS?
* What happens when you click on the button: `Settings->Colours and Fonts->Revert the default settings`  (the button is placed in the toolbar of that dialog and has a blue refresh icon on white page) - does this fixes your issue?

**Comment by Arandhras** [comment]
CodeLite's version is the latest, 9.2.0 compiled for x86.
The OS is Windows 7 Enterprise 64 bit SP1, with the "basic" desktop enabled (in other words, no Aero / composite desktop engine).
Reverting to default settings in the `Colours and Fonts` dialog unfortunately does not change the appearance.

All of this is happening at my workplace's computer. Screenshots taken through Windows' Problem Steps Recorder program show a white cursor while on a dark background, however what I get on the real screen is a black cursor.

What I can do now is to try to reproduce this issue at home on my personal computer and see if it is any different; I will keep you updated.

**Comment by eranif** [comment]
This is now reproducible here (Windows), to fix this:

* from : `settings->colours and fonts->customize->styles` select the proper language on the left list and then in the RIGHT list select 'caret colour' and set its foreground colour to white

* Or: close CodeLite,  try deleting the folder `%appdata%\CodeLite` and see if it helps

**Comment by Arandhras** [comment]
Unfortunately neither solution solves my problem... I have checked for the caret colour foreground for any applicable language used in my project, and everywhere it is set to `white`. I have also tried to delete the entire profile but to no avail; using a different dark theme (I am using Monokai_2) doesn't help either.

**Comment by eranif** [comment]
The caret colour is control from the settings.
You are changing the wrong parameter

**Comment by eranif** [comment]
Try installing the 64 bit version of CodeLite (note: I am using Windows 7, 64 bit here as well with dark theme and it is working OK)
