### ISSUE TITLE
Code Complete for C language

### ISSUE THREAD

**Issue by benqqq** [eranif/codelite#1447]
My environment: 
- CodeLite v9.2.4 Windows x64 
- C language custom makefile project.
- Code Complete with CTags.

The following C code not work with Code Complete.

1. When typing struct designator(.) initialization.
2. When access struct member by . operator like following examples.
```
typedef struct
{
    struct
    {
        FIELD init      : 1;    /* 1 if service is inited */
    } field;

    Task task;
    int interval;
} Service;
```
```
typedef union
{
    uint32 dword;

    struct
    {
        uint16  w           : 15;       // [bit 14:0]
        FIELD   is_enable   : 1;        // [bit 15]
        FIELD   c           : 1;        // [bit 16]
        uint16  time        : 7;        // [bit 23:17]
        uint16  reserved    : 8;        // [bit 31:24]
    } field;
} PSetting; 
```

**Comment by eranif** [comment]
Please enable clang code completion and it will work.
You do this from: `settings->code completion->clang->enable clang code completion`

**Comment by benqqq** [comment]
It still not work after enable clang code.
Is it suitable for use custom makefile project?
My project is compile by the external cr16c compiler, not the internal clang compiler.
