### ISSUE TITLE
wxwidgets problem

### ISSUE THREAD

**Issue by GFdevelop** [eranif/codelite#1450]
I have installed wxwidgets with msys2 but codelite not found WXWIN and WXCFG, i have see the source of codelite and there is a problem with the search path, you can see the install directory of wxwidgets and fix it on this gist.
https://gist.github.com/GFdevelop/dc7ab3b9d2749c83b4c6a5dd90844967

**Comment by eranif** [comment]
This is because the MSYS paths are not recognized outside of the MSYS shell
`/msys2/...` is not a valid Windows path
