### ISSUE TITLE
Workspace - Previous project selected Stays bold after new selection

### ISSUE THREAD

**Issue by M-griffin** [eranif/codelite#1451]
![screent shot](https://cloud.githubusercontent.com/assets/8034111/19436926/9d4d9a5c-9438-11e6-83ba-9d80b22e17cf.png)

**Screen shot attached.**  

When changing from the first project **SqliteWrapped**, to the third project **xrm-unittests** by double clicking, the previous project SqliteWrapped is still bold showing both as the active project.  

_The first project in the list_ appears to stay bold always,  if I switch between the second and third project, then it appears to work correctly, even though the first project stays bold all the time.

Running the latest 9.2.5 in 64 Bit Windows 10.
However I've noticed this issue since some later 8.x releases.

**Comment by eranif** [comment]
this can only happen if the workspace was edited manually
