### ISSUE TITLE
QuickOutline: search - first char is wrong if shift is pressed

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1453]
In Quick Outline dialog

when search textfield is not yet visible:

if the first char that I type is a char that needs to be accessed through SHIFT+key  - for example "$" or "_" - then the non-shifted key appears in the search textfield.

If the search field is already visible the problem does not appear.

CL-9.2.0@archlinux

**Comment by uffejakobsen** [comment]
This is still a problem with CL-10.0.0@archlinux

**Comment by eranif** [comment]
I am ware of this. Hence, the bug is still opened.
