### ISSUE TITLE
Terminal error 2

### ISSUE THREAD

**Issue by mosmonov** [eranif/codelite#1454]
Hello there,
Does anyone can help me with this issue? I am getting an error in the following statement:
codelite-terminal error could not set current working directory (error 2: No such file or directory)
I am trying the basic sample when I open cpp, I have been using it for a long time, but yesterday I updates my OS system and all of a sudden codelite started acting crazy. It was not showing me the right answer etc.

**Comment by dghart** [comment]
Hi,

A bug-tracker isn't the right place to discuss your problem. I suggest you ask on [the forum](http://codelite.org/forum/), providing sufficient information e.g. your OS, the paths of the relevant directories, the exact error message...

Regards,
David
