### ISSUE TITLE
Usability Bugs: Saving files

### ISSUE THREAD

**Issue by MusorGaming** [eranif/codelite#1456]
I use hotkey combination `Alt+F, S` for "Save File" and `Alt+F, A` for "Save As". 

Unfortunately this doesn't work well in CodeLite:
1.  "Save File" option is grayed out if the file is not _dirty_ and while that makes perfect sense - it causes a usability issue. If you press `Alt+F, S` the `File` menu leaves hanging since the `S` key cannot be consumed (if a file is not _dirty_).
   **FIX:** don't gray-out  `File->Save File` option even if the file is _fresh_.
2. "Save As" option is not selectable using `Alt+F, A` because "Save As" doesn't have letter A marked.
   **FIX:** add a underlined A for "Save _As".

What I'm suggesting here is to fix codelite to be in line with how well-behaved software handles saving files through usage of menu hotkeys.

**Comment by eranif** [comment]
I agree if the second, but I dont agree with the first.
If the menu hanging, just hit `ESC` and it will get closed.

**Comment by MusorGaming** [comment]
@eranif 
Thank you for adding the Alt+F, S hotkey!

There is a wide amount of evidence that "graying out Save menu" goes against UI conventions:
- Windows software doesn't do this - Visual Studio doesn't, Notepad++ doesn't, notepad doesn't, Word doesn't, Sublime text doesn't. *Nobody* does this.
- Even Linux desktop software doesn't do this - GEdit doesn't, Inkscape doesn't, Gimp doesn't.

Please fix this minor tidbit. Codelite is fantastic piece of software and small details like these hold it back from achieving greatness.
