### ISSUE TITLE
Feature Request: Add an editable linker build command

### ISSUE THREAD

**Issue by SeanRamey** [eranif/codelite#1457]
For a quick description of what I need: http://forums.codelite.org/viewtopic.php?f=11&t=3504

Add a way to change the build command of the linker, similar to the compiler build command for each file type.

**Comment by SeanRamey** [comment]
Fantastic.

**Comment by SeanRamey** [comment]
Bruh, it's been 3 years... Add it already.

**Comment by eranif** [comment]
Here you go, Bruh

**Comment by SeanRamey** [comment]
Thanks, Bruh!
