### ISSUE TITLE
Forever expanding dialog box height due to poor coding style

### ISSUE THREAD

**Issue by xuancong84** [eranif/codelite#1459]
In Codelite, if you open any dialog box (e.g., project setting) and close it, open it and close it again, do it again and again, every time, the height of the dialog box will increase by a line until the user have to vertically shrink it. Otherwise, the button will go out of the screen. This stupid behaviour is very annoying.

I wonder how the developer has created the program and why will this bug come into play. This kind of bug must be due to poor coding style.

**Comment by eranif** [comment]
It's actually a bug in the underlying GUI library [wxWidgets](https://wxwidgets.org) [http://trac.wxwidgets.org/ticket/17228](http://trac.wxwidgets.org/ticket/17228)
NOTE:
There is no need to insult... if you think you can do better - by all means, go ahead and write another IDE or use another one
