### ISSUE TITLE
How to upgrade from 9.2 to 9.2.5?

### ISSUE THREAD

**Issue by mohrd** [eranif/codelite#1462]
Hi, I installed CodeLite 9.2 from official Ubuntu 16.04 repository. But now I need v9.2.5 (weekly build) which is not available in repos. 

How to upgrade?

I ran `apt-get purge codelite` then tried to install `CodeLite-9.2.5-ubuntu-xenial-x86_64.deb` using `dpkg -i CodeLite-9.2.5-ubuntu-xenial-x86_64.deb`, but it failed:

> Preparing to unpack CodeLite-9.2.5-ubuntu-xenial-x86_64.deb ...
> Unpacking codelite (9.2.5) ...
> dpkg: error processing archive CodeLite-9.2.5-ubuntu-xenial-x86_64.deb (--install):
>  trying to overwrite '/usr/lib/x86_64-linux-gnu/codelite/wxCrafter.so', which is also in package wxcrafter 2.6-1.xenial
> dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
> Errors were encountered while processing:
>  CodeLite-9.2.5-ubuntu-xenial-x86_64.deb

Note that, I installed wxWidgets using this tutorial (http://codelite.org/LiteEditor/WxWidgets31Binaries#toc2)

**Comment by eranif** [comment]
IN general, the issue tracker is not the place to ask your questions, its for issues.
Please follow the installation insturctions for weekly builds as described on the forum, for example:

http://forums.codelite.org/viewtopic.php?f=20&t=3491
