### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by krvajalmiguelangel** [eranif/codelite#1463]
I am running CodeLite version 9.2.5 on Windows, fresh install. And I can't compile a single cpp file.
I dont have MinGW installed but have clang and vs compilers. It detected both of them properly with the wizzard setup but when i try to compile i get the following
~~~
C:\windows\system32\cmd.exe /C mingw32-make.exe -j8 -e -f  Makefile
'mingw32-make.exe' is not recognized as an internal or external command,
operable program or batch file.
====0 errors, 0 warnings====
~~~
It seems like the app is trying to run mingw32-make but i dont have that installed and it nows it. Why then is launching the makefile generator of mingw.
Also if I set the makefile generator to cmake it makes cmake to generate a mingw32 makefile.

**Comment by eranif** [comment]
This is really not a bug, but a configuration issue. Please post on the forum and not on the issue tracker
