### ISSUE TITLE
Empty projects when opening LiteEditor.workspace using codelite 9.2.2

### ISSUE THREAD

**Issue by pattisahusiwa** [eranif/codelite#1464]
![bug](https://cloud.githubusercontent.com/assets/11484016/19833013/3114d9fc-9e5d-11e6-9f41-a35910bc92cb.png)

**Comment by eranif** [comment]
This is because CodeLite's workspace now contains virtual folders which were not supported by CodeLite 9.2.2
Assuming this is Linux, build CodeLite from the command line as described here:
http://codelite.org/Developers/Linux

Install and re-open the workspace
