### ISSUE TITLE
Two issues: Conditional breakpoints mutate into regular breakpoints, build paths with ../../ create needless rebuilds

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1465]
Building a file which is included in the project using relative addressing (../../../something/something) creates long build names (example, up_up_up_up_up_up_projects_plf_bench_individual_tests_colony_standard_testing_std_list_char.cpp.o) and always rebuilds regardless of whether files have changed. Not present in 9.18.

Conditional breakpoints change into regular breakpoints after one run + trigger.

win7, non-self-compiled 9.2

**Comment by mattreecebentley** [comment]
Just wanted to note that this issue appears to be no longer present (using 10.0) - but the .o names are still up_up_up_up...etc.

**Comment by eranif** [comment]
This is unlikely to be changed with the current build system. You can also use `CMake` with CodeLite which uses different approach
