### ISSUE TITLE
Codelite does not correctly detect that a file has changed for build process

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1466]
If you replace a C++ header file in your chain with another version of it, go into codelite, hit ctrl-r on that file so that codelite properly reloads it (if it doesn't detect the change - which it usually doesn't if it's a header), then build, codelite will not properly rebuild, it'll just do a link to the previous object files.

win7, codelite 9.2, non-self-compiled

**Comment by eranif** [comment]
The Makefile generates the dependencies and does the actual rebuild if needed.
Usually, if the file is included somewhere by any of the C++ files, all the relevant C++ files are rebuilt.

There are 2 cases where this will not work:

1. The only case that it won't work is when using MSVC on Windows as your compiler.
2. The timestamp of the modified file is in the past (i.e. the object files timestamps are more recent)

My advise: use the `CMake` makefile generator if things are not working as you expect.

**Comment by mattreecebentley** [comment]
Nope. Neither of those things are true on my setup.

**Comment by eranif** [comment]
The above page still works, but there is an easier way:

http://codelite.org/LiteEditor/TheCMakePlugin
