### ISSUE TITLE
autocomplete won't shown

### ISSUE THREAD

**Issue by pattisahusiwa** [eranif/codelite#1467]
Tested in codelite 9.2.2 and 9.2.6.

Autocomplete won't shown if followed by `//` or `/*`.

**Comment by eranif** [comment]
Can you please give a step-by-step how-to reproduce example?

IIUC, then this is by design. Just need to confirm this.

**Comment by pattisahusiwa** [comment]
Only add `//` or `/*` before typing.

![bugs](https://cloud.githubusercontent.com/assets/11484016/19838841/fece6168-9f09-11e6-95fd-4947d70ad1dc.png)

**Comment by eranif** [comment]
What I thought, this is **by design** - and it wont change (this is because comments are free text without any rules which can break the parser completely)
If you want some kind of code assist, you can use the word-completion `Ctrl-ENTER` which completes words from all the open documents

**Comment by pattisahusiwa** [comment]
It's not a big problem, I can add a `space` before `//` and auto-complete will works again. Maybe you can consider to add this feature because it's working in another editor, for example in geany.

![eq](https://cloud.githubusercontent.com/assets/11484016/19838975/a98bd7e6-9f0c-11e6-8418-9b6e73e8bb0e.png)

**Comment by eranif** [comment]
OK, I misunderstood you... I thought you meant: code completion does not work **inside** comment
What you meant: if the `//` is adjacent to the actual code, code completion does not work and you need to insert at least a single space to make it work again. right?
FYI: this same bug also exists if the next char is string
```C++
int a|"some string"
```

**Comment by pattisahusiwa** [comment]
> What you meant: if the // is adjacent to the actual code, code completion does not work and you need to insert at least a single space to make it work again. right?

Yes, correct. If you can make it works, then it's really help.

**Comment by pattisahusiwa** [comment]
also, this will not work too.
1. add `int test;`
2. place cursor before `i` then type e.q. `const`.
