### ISSUE TITLE
codelite crash when adding virtual folder to nested workspace

### ISSUE THREAD

**Issue by pattisahusiwa** [eranif/codelite#1468]
codelite: version 9.2.6
OS: Arch Linux.

workaround:
1. Open codelite, create new workspace (e.q. `test`)
2. Under `test` workspace, add another workspace folder (e.q. `test-workspace`)
3. Add new project to `test-workspace` (e.q. `test-project`)
4. Add new virtual folder to `test-project`, codelite will crash.

![crash](https://cloud.githubusercontent.com/assets/11484016/19838641/8b439eaa-9f06-11e6-8d9d-524965efe694.png)

**Comment by eranif** [comment]
Thanks for reporting this. I see this is a high priority and it will be fixed in the next hour

**Comment by pattisahusiwa** [comment]
Please also check why codelite won't remove physical folder of the project or workspace. Tried to remove those project and workspace above, the physicall folder still there.

**Comment by eranif** [comment]
The workspace view does not delete projects from the file systems (nor folders) - this is to avoid errors
You can do this from your File Manager or from CodeLite's Explorer tab which provides a similar functionality

**Comment by eranif** [comment]
BTW, this bug revealed (so far) at least 3 other bugs - working on them now

**Comment by eranif** [comment]
Please check the fix.
I tested all the virtual-folders's context menu entries + the project context menu

**Comment by pattisahusiwa** [comment]
won't compile

````
MESSAGE: Entering directory `/codelite/build-debug'
/bin/sh -c 'make -j4'
----------Building project:[ CodeLiteIDE - CMake_Debug ]----------
make: *** No targets specified and no makefile found.  Stop.
====0 errors, 0 warnings====
````

**Comment by eranif** [comment]
Just compiled it (from the command line) on 2 different Linux boxes

**Comment by eranif** [comment]
Which OS?
Did you run `cmake` before building (in any case please re-run it)

**Comment by pattisahusiwa** [comment]
Can you add cmake configuration to save `*.cpp.o` inside `/home/eran/root`so we don't need to compile all files everytime the repository is updated? because it tooks long time to compile all files.

**Comment by eranif** [comment]
I am not going to invest time on this - feel free to send PR

**Comment by pattisahusiwa** [comment]
Tested. The bug is fixed.

**Comment by eranif** [comment]
Thank you for testing
