### ISSUE TITLE
Backspace break input (Russian keyboard layout)

### ISSUE THREAD

**Issue by eranif** [eranif/codelite#147]
Russian keyboard layout: typing "backspace" breaks further input russian characters. Switching the layout (Russian -> English -> Russian) or typing "space" symbol restores normal input
OS: Ubuntu 11.04 x32
Codelite: 3.0.5259 from trunk (File font encoding: windows-1251)
wxWidget: 2.8.11.0-0ubuntu8.1

**Comment by eranif** [comment]
If you have a fix (and the problem still exist) please submit a PR

**Comment by galkinvv** [comment]
I recently tested that the problem still exist in 7.0 with ubuntu 12.04 (32-bit). To try preparing the PR I need to know what the "Enable localization" option in unselected state is designed to do?

Is it designed to affect only UI language leaving libc locale corresponding to system locale (may be non-english) so libc's and other libs error messages would stay in system locale?
(In this case its needed to add default locale initialization)

Or is it designed to force english locale for both UI and system lib messages?
(In this case its needed to add C locale initialization)

**Comment by eranif** [comment]
It designed to affect UI only
