### ISSUE TITLE
delete entry from "Look In" in "Find In Files" using DEL key

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#1470]
would be nice if the delete key would delete an entry from the "Look In" list in the "Find In Files" dialog

probably applies to any other similar list type thingy in CodeLite

**Comment by eranif** [comment]
It is not possible to capture keyboard events on the drop down list part of the wxComboBox (at least according to the documentation)

**Comment by grandinj** [comment]
That control is not a wxComboBox, it's a wxListBox, in which case it should be possible?

Unless that dialog is doing something odd? Certainly there is no editable component to that list.

**Comment by eranif** [comment]
Oh, I thought (dunno why...) you were talking about the "Find What" entry :/

**Comment by grandinj** [comment]
nice, thanks!
