### ISSUE TITLE
what should I do to close output view?

### ISSUE THREAD

**Issue by kttis** [eranif/codelite#1471]
codelite is an awesome ide,it work fine on my notebook,but when I run my c++ project with ctrl+F5 the OUTPUT VIEW is showing even though I close all tabs,I want to make hide everytime only when using ctrl+~,what should i do about it? thank you

**Comment by eranif** [comment]
You have several options:

* `Ctrl-M` to toggle all unneeded views 
* `Ctrl-~` toggles the output view
* Settings->Preferences->Windows & Tabs ->Debug / Output panes, tick the option: "When user clicks inside the editor, hide the output pane"

**Comment by mariamashraf731** [comment]
I accidentally hided all the tools in output pane and i can't get them back and I've tried many solutions but none of them worked and now i can't see my errors or anything on the output pane what should i do ?

**Comment by Gust1-1** [comment]
Hi. My Codelite output pane view is checked in 'view' but not showing at the bottom
![Codelite image](https://user-images.githubusercontent.com/68816952/90338214-3e5e5e00-dfe8-11ea-922d-e10f81d7ff03.jpg)
