### ISSUE TITLE
Unable to install codelite on Ubuntu 14.04.5 LTS

### ISSUE THREAD

**Issue by SteveAdem** [eranif/codelite#1475]
Hi,
I'm trying to install codelite on Ubuntu 14.04.5 LTS. After I add the codelite repository to apt sources list (deb http://repos.codelite.org/ubuntu/ trusty universe) when I run apt-get update I'm getting the following message:

**W: Failed to fetch http://repos.codelite.org/ubuntu/dists/trusty/universe/binary-i386/Packages  HttpError404**

If I try to open the URL http://repos.codelite.org on my web browser I'm redirected to https://forums.codelite.org/.

If I open https://repos.codelite.org on my web browser I go to the repository page. However,  if I change the URL on apt sources list to https (deb https://repos.codelite.org/ubuntu/ trusty universe) I get the following output:

W: Failed to fetch https://repos.codelite.org/ubuntu/dists/trusty/universe/binary-i386/Packages  SSL: certificate subject name (www.codelite.org) does not match target host name 'repos.codelite.org'

Could you help me with this case? Thanks in advance

**Comment by eranif** [comment]
Please try now.
I moved CodeLite website to use HTTPS, and the certificate indeed, does not include `repos.codelite.org`
I will fix this later, for now: I moved the repos virtual host to use `http` for now, until this is fixed
