### ISSUE TITLE
Highlight issues with struct field and global function

### ISSUE THREAD

**Issue by elch10** [eranif/codelite#1476]
Here, the local variable count, somehow defined as global. And when I'm using the count function from the STL, it is defined as a variable. This is evident as the present of printf, it is different from the count of the STL.
![noname](https://cloud.githubusercontent.com/assets/15147137/20461032/85bbae18-af06-11e6-895c-caf9d3275a14.png)

**Comment by yunkot** [comment]
I've previously reported this in issue #1251, but according [one of the comments](https://github.com/eranif/codelite/issues/1251#issuecomment-249613275), coloring is not scope-aware.
