### ISSUE TITLE
CodeFormatter looses it's left panel after first configurations

### ISSUE THREAD

**Issue by AJenbo** [eranif/codelite#1480]
This has happened to me on multiple systems
![options](https://cloud.githubusercontent.com/assets/204594/20560371/48e4658c-b179-11e6-963a-491e23e5d342.png)
Once it happens the only way to get it back is to delete the configurations :/

**Comment by eranif** [comment]
what happens when you resize the dialog?

**Comment by AJenbo** [comment]
The left panel stays the same width, everything else resizes normally. I also tried maximizing, shaking and pulling on it in every other way I could think of.

**Comment by eranif** [comment]
Thanks, its a bug in wxWidgets... I got reports in teh past for the various dialog using the same control the solution was to replace it with normal notebook control

**Comment by AJenbo** [comment]
Fix confirmed
