### ISSUE TITLE
Changing Terminal in Codelite 9.2.6 on macOS Sierra

### ISSUE THREAD

**Issue by vdidonato** [eranif/codelite#1485]
I want to use _Terminal_ as default terminal in CodeLite.

I tried two things with no results.
1. Preferences -> Terminal and I unchecked the checkbox "Use CodeLite's built-in terminal emulator". 
2.  Set /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal in the textbox "Enter here the command to be used by CodeLite for launching consoles".

I am on macOS Sierra and I am using Codelite 9.2.6.

**Comment by eranif** [comment]
This is now fixed in git master.
CodeLite will now **only** use the native `Terminal.app`
