### ISSUE TITLE
C++14 integer literals with single quotes (') separator syntax highlight

### ISSUE THREAD

**Issue by dudanov** [eranif/codelite#1488]
Hello, please implementing syntax highlighting of integer C++14 literals with single quotes separator.
Thanks.

**Comment by eranif** [comment]
Are you talking about this https://en.wikipedia.org/wiki/C%2B%2B14#Digit_separators ?

**Comment by dudanov** [comment]
Yes. About this. It would be nice.

**Comment by eranif** [comment]
This looks to be supported by CodeLite:
<img width="277" alt="c 14" src="https://cloud.githubusercontent.com/assets/3677711/20867584/e5a783e2-ba50-11e6-911a-e6b194f1e35c.png">
It is not something I implemented myself, but rather a feature of the underlying edit control `wxStyledTextCtrl` (based on: http://scintilla.org)

**Comment by dudanov** [comment]
![2016-12-04 20-52-54](https://cloud.githubusercontent.com/assets/10439739/20867712/22e6136e-ba64-11e6-9250-0c3e2ae54912.png)
Hmm... This my code... File extension is .cxx.

**Comment by eranif** [comment]
which OS?
also, in the trace tab (at the bottom view) one of the first lines is the Scintilla version, can you please check which version are you using?

**Comment by dudanov** [comment]
OS Linux based on Ubuntu 16.04.
In trace tab:
21:24:58: Using Scintilla 3.21

**Comment by eranif** [comment]
is it a self compiled codelite?
or from the website?

**Comment by dudanov** [comment]
This is precompiled deb binary version from site.
In Scintilla website version 3.21 is absent in History. May be v3.2.1? Then it's a very old version.

**Comment by dudanov** [comment]
I download Scintilla and compile. In bin/ directory of source tree appear scintilla.a static library. Now I need rebuild CodeLite?

**Comment by dudanov** [comment]
I build CodeLite from source to the test directory. Problem not solved. Version of Scintilla 3.21.

**Comment by eranif** [comment]
I will upload a new weekly soon with a more recent version of wxwidgets

**Comment by dudanov** [comment]
Thank you. Waiting for update. :)

**Comment by dudanov** [comment]
![2016-12-05 21-00-15](https://cloud.githubusercontent.com/assets/10439739/20894211/faa66c1c-bb2d-11e6-90ea-cbaf445bc07d.png)
Today download and compile latest wxWidgets 3.1.1 from github. Now it's ok, used version of Scintilla 3.6.6 (latest on official library site - 3.7.1).

**Comment by eranif** [comment]
I have built new CodeLite with our release of wxWidgets (we also provide wxWidgets binaries on CodeLite website) - it now uses scintailla v3.5.5 which fixes this issue

**Comment by dudanov** [comment]
Thank you. So, this issue can be considered closed?

**Comment by eranif** [comment]
I am uploading CodeLite 9.2.8 - once its done will close this issue
