### ISSUE TITLE
CMake error on custom PREFIX variable in Linux

### ISSUE THREAD

**Issue by dudanov** [eranif/codelite#1489]
I want to compile CodeLite with custom PREFIX installation directory (not /usr), but CMake crush while generating building Makefile on testing compilers stage.
My CMake command: $ cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DPREFIX="/home/sergey/clite" ..
CMakeError.log included
[CMakeErro.log.txt](https://github.com/eranif/codelite/files/629737/CMakeErro.log.txt)

**Comment by dudanov** [comment]
Changing name of PREFIX variable in main CMakeLists.txt to IPREFIX solves the problem.

**Comment by eranif** [comment]
Maybe now `PREFIX` is a reserved word in `CMake` - which version of `CMake` are you using?

**Comment by dudanov** [comment]
May be. CMake version 3.5.1.

**Comment by dghart** [comment]
Hi,

FWIW I use -DPREFIX builds all the time. I just tested with cmake 3.5.2 (ubuntu 16.10) and it worked without a problem.

cmake sometimes fails to clean properly after a failed build, so I suggest you try in a fresh build  directory. If the same thing happens you could try updating to 3.5.2.

**Comment by dudanov** [comment]
I'am trying to run `cmake` again in clean build directory and get the same result. If `cmake` will be run clean in version 3.5.2, then need set up minimum required version to 3.5.2 in main `CMakeLists.txt` file. Better solution is rename `PREFIX` variable to another similar name. May be I wrong.

**Comment by dghart** [comment]
But 3.5.2 isn't the minimum: I normally use debian jessie which has 3.0.2.

Which distro/version are you using, that supplies 3.5.1?

**Comment by dudanov** [comment]
I use `Linux Mint 18 x64` based on Ubuntu 16.04.
Just now I download sources and build newest `cmake 3.7.1`, which give same result...
See output of my `cmake`.
[cmake.txt](https://github.com/eranif/codelite/files/643749/cmake.txt)

**Comment by dudanov** [comment]
Update: after `cmake` makefile generation `make` run normally, building process ok. But yet such behavior of `cmake` is abnormal on compilers detecting stage and required `CMakeLists.txt` correction.

**Comment by dudanov** [comment]
Problem in internal `CMake` scripts for compilers detection (for GCC is `GNU-DetermineCompiler.cmake`).
This file contains:
sergey@nb491 /usr/local/share/cmake-3.7/Modules/Compiler $ cat GNU-DetermineCompiler.cmake 
set(_compiler_id_pp_test "defined(__GNUC__)")
set(_compiler_id_version_compute "
# define @PREFIX@COMPILER_VERSION_MAJOR @MACRO_DEC@(__GNUC__)
# if defined(__GNUC_MINOR__)
#  define @PREFIX@COMPILER_VERSION_MINOR @MACRO_DEC@(__GNUC_MINOR__)
# endif
# if defined(__GNUC_PATCHLEVEL__)
#  define @PREFIX@COMPILER_VERSION_PATCH @MACRO_DEC@(__GNUC_PATCHLEVEL__)
# endif")

Using of PREFIX variable is the source of this issue.

**Comment by dghart** [comment]
I still  can't make it go wrong. Using your build line (s/sergey/david) in Mint 18, cmake  works fine :/

Is there anything unusual about your compiler, or its location? For me, which g++ gives /usr/bin/g++. The gcc version is 5.3.1, as is the cmake version.

**Comment by dudanov** [comment]
GCC v5.4.0, cmake v3.7.1.
My cmake output with & without using PREFIX variable:
[cmake_with_prefix.txt](https://github.com/eranif/codelite/files/644363/cmake_with_prefix.txt)
[cmake_without_prefix.txt](https://github.com/eranif/codelite/files/644364/cmake_without_prefix.txt)

**Comment by dghart** [comment]
And where is you gcc? Mine is in the usual /usr/bin/ and cmake finds it easily. Is yours somewhere else?

**Comment by dudanov** [comment]
My compiler in it's usual place `/usr/bin` and `cmake` find it in both cases (w & wo PREFIX).
I'll say it again: the problem is not that the `cmake` can not find compiler, problem in not correct determining version of compiler, because PREFIX variable used by internal `cmake` scripts.
In my `cmake` logs it can be clearly seen.

**Comment by dghart** [comment]
>I'll say it again: the problem is not that the cmake can not find compiler, problem in not correct determining version of compiler, because PREFIX variable used by internal cmake scripts.

I _

do_ understand what you're saying. However I'm trying to work out why you are the only one who has this problem. CodeLite has been using cmake for some years now, and nobody else has mentioned it. I've never had it happen, and I'm failing to make it happen here.

I've just updated to gcc 5.4.0; it is still detected, even with a -DPREFIX. 

Your cmake_with_prefix.txt log is hard to read, due to the annoying warnings. Here's my log, created by passing the -Wno-dev flag. Please would you post yours when using that flag.
[CMakeOutput.txt](https://github.com/eranif/codelite/files/644509/CMakeOutput.txt)

**Comment by dghart** [comment]
Ah, I now understand your comment:
>Update: after cmake makefile generation make run normally, building process ok. But yet such behavior of cmake is abnormal on compilers detecting stage and required CMakeLists.txt correction.

So whatever was causing the original crash has disappeared, and we are left with just a worrying message. Compared with a crash, clearly that's far less important.

**Comment by dudanov** [comment]
Yes, first my `cmake` is really crashed. Now it's only can't correctly determine GCC version and output too many warnings for developers. Using of `PREFIX` variable highly undesirable and must be renamed in main `CMakeLists.txt` file to solve this problem.

**Comment by dghart** [comment]
This should now be fixed in git, so will be in the next release.
