### ISSUE TITLE
Doxygen: Support @param[in] and @param[out] and @param[in,out]

### ISSUE THREAD

**Issue by TheComet93** [eranif/codelite#1490]
I would like to have these statements not appear as "errors" in doxygen comment blocks:
 - @param[in]
 - @param[out]
 - @param[in,out]

**Comment by eranif** [comment]
This is not CodeLite doing, but rather wxStyledTextCtrl (a third party library, part of wxWidgets)
I believe that this is eventually coming from http://scintilla.org the editing components. So you will need to take it up with them
