### ISSUE TITLE
Paste is applied only on the last selected item

### ISSUE THREAD

**Issue by sgchris** [eranif/codelite#1492]
When selecting several strings (using Ctrl-K) and then pasting (Ctrl-V), only the last selected string is affected, while all the other selected occurrences are deleted.

**Comment by eranif** [comment]
Which CodeLite version? and which OS

**Comment by sgchris** [comment]
Ubuntu 16.04.1 LTS
CodeLite 9.2.7

**Comment by eranif** [comment]
Install 9.2.8 and it will be OK
