### ISSUE TITLE
Codelite will not detect that debug session is over if program quits on startup

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1494]
In my case I'm running an SDL2 program, if the DLL's aren't in the same folder, the program will quit, but codelite doesn't detect that it's quit, and when I try to hit F5 it asks whether I want to quit the existing debug session.

non-self-compiled, v9.28 win7 x64

**Comment by mattreecebentley** [comment]
Also, it's still including the folder path in .o files if the files in question are within include paths that include "../". eg. "up_up_projects_plf_colony_code_plf_colony_test_suite_benchmark.cpp.o"
M

**Comment by eranif** [comment]
Is it possible to have a reproducible workspace? (with minimal SDL2 code)
Thanks

**Comment by mattreecebentley** [comment]
Any SDL2 program will trigger it under windows 7 if you try running the 
program in Codelite without having the requisite SDL2 DLL's in your 
debug folder (SDL2.dll, etc).

Can confirm this still occurs with v10 of codelite, although strangely 
codelite doesn't pop up it's usual 'program didn't start etc' message 
with this version.

**Comment by mattreecebentley** [comment]
ps. the "Hello world" code here should be sufficient:
http://lazyfoo.net/tutorials/SDL/01_hello_SDL/01_hello_SDL.zip

**Comment by eranif** [comment]
I just created SDL2 project, compiled it successfully and then tried to debug (I intentionally removed the .dll from the binary folder to reproduce the error) - and I got this error dialog:

<img width="306" alt="debug-error" src="https://cloud.githubusercontent.com/assets/3677711/21879057/ec02737a-d89e-11e6-8302-8a0c9e60e813.png">

and then the debug session terminated.
The only reason I can think of is that we are using different debugger version..
Which MinGW version are you using, and more importantly, which GDB version?

**Comment by eranif** [comment]
@mattreecebentley ping

**Comment by mattreecebentley** [comment]
You are correct - I tried with mingw TDM 5.1 and there was no problem-
the problem only occurred wwith nuwen's mingw 6.1 distro, and updating 
that to the more recent 6.3 solved the problem - thanks!
