### ISSUE TITLE
Run option doesn't print any output on Windows

### ISSUE THREAD

**Issue by min050820** [eranif/codelite#1495]
When launching application by 'Run' option, it only runs, but it doesn't print any output. Running the application manually prints it as normal. The IDE's 'Run' feature shows CMD window, but it ignores any output from my program. It does print 'Press any key to continue...' however.

My computer is running Windows 10. And I'm using MinGW with the latest update. The project I'm trying to launch is a console application, with CMake. I believe there's nothing wrong about the application. It's a simple _Hello, world!_ program after all.

Here's the build log:
```
C:\Windows\system32\cmd.exe /C cd S:\projects\HelloWorld\cmake-build-Debug && C:/MinGW/bin/mingw32-make.exe -j8 SHELL=cmd.exe -e
-- Configuring done
-- Generating done
-- Build files have been written to: S:/projects/HelloWorld/cmake-build-Debug
[100%] Built target HelloWorld
====0 errors, 0 warnings====
```
And Here's the output log:
```
Current working directory: S:\projects\KorWikiParser\ConsoleWikiParser
Running program: le_exec.exe S:\projects\KorWikiParser\cmake-build-Debug-ConsoleWikiParser\bin\ConsoleWikiParser
Program exited with return code: 0
```

**Comment by eranif** [comment]
Please provide a working example workspace.
It works here

**Comment by min050820** [comment]
After rebooting, my original project worked. So I think it was my computer bad.

I created another workspace to investigate more, and it turned out to be a duplicate of #1474, causing IDE to not build the binary at all. It would be appreciated if le_exec.exe printed some kind of error if the binary was not available.

I'll attach the newly created workspace (the one IDE decided not to build the binary) on #1474.

**Comment by min050820** [comment]
I managed to reproduce the problem! The executable is there, and it runs correctly, but not output when run via IDE's _Run_ feature. (It correctly outputs when run with CMD manually)

[Here's the project file. (Uploaded via GitHub)](https://github.com/eranif/codelite/files/659314/KorWikiParser.zip)

**Comment by eranif** [comment]
Ok, here is the problem:

The build is taken place in this folder: `S:/projects/HelloWorld/cmake-build-Debug`
However, you are attempting to run: `S:\projects\KorWikiParser\cmake-build-Debug-ConsoleWikiParser\bin\ConsoleWikiParser`

I created an new empty workspace + project and all the settings are properly populated.
In your project, the "Executable to Run/Debug" is set to:

`$(WorkspacePath)\cmake-build-$(WorkspaceConfiguration)-$(ProjectName)\bin\$(ProjectName)`
I am pretty sure that CodeLite did not add the extra `-$(ProjectName)` but it was added manually by you.

**Comment by bharathkalyan00** [comment]
@eranif  Hi sir. I'm new to coding and I recently started learning C.
Installed Codelite. I am getting an output if i use g++ but not when i use gcc.
When i build the code and run, the cmd console shows up and closes instantly. I'm getting no output.
I didn't understand where to find those paths, from your previous comment.

**Comment by danielmacho72** [comment]
I had the same issue, it turned out that for me the project was a problem with white spaces in some of the default Windows folders where I had my workspace and projects. 

It was the default C:\Users\<user>\Documents one, where <user> had a white space, so apparently CodeLite not dealing well with such folders. The solution has been to move all workspaces from that folder to C:\CodeLite simple one and then my projects started running properly (Debug and Release)...

**Comment by deima96** [comment]
Hello, I'm trying  to run a simple Hello World C++ program, it doesn't show any output and the program exit with a code 32762
