### ISSUE TITLE
unusable. why?

### ISSUE THREAD

**Issue by Zibri** [eranif/codelite#1496]
I installed codelite 9.2 adding the repository and key on Ubuntu 16.10

codelite/yakkety,now 9.2+dfsg-1 amd64 [installed]

I run it and open a C file.
The c file is displayed correctly.
I compile and run it and nothing happens.
I go to configuration manager and the window is empty and when I click cancel the program crashes.

The program correctly detected 3 compilers on my system.
What should I do?!

**Comment by Zibri** [comment]
all I need is a f*cking editor with C code completion...
I tried also running   codelite hello.c   it shows the hello.c file with correct highlighting but no code completion... maybe it's me but this sucks.

**Comment by eranif** [comment]
> all I need is a f*cking editor with C code completion...

please use the forum if you have any more questions, but not like this

**Comment by Zibri** [comment]
Sorry.. I was really angry after trying like 3 different huge programs for a "stupid" purpose. 
Then, I found codeblocks, fortunately.
Anyway, let me kindly apologize for barging in in that way.
But at the same time, try to understand that one of the reasons Linux hardly gets into desktops is because of situations like this.
And who is speaking is a system and security engineer since 28 years ago.
Not just an angry kid.

Regards, 
Zibri


Inviato da Samsung Mobile

-------- Messaggio originale --------
Da: Eran Ifrah <notifications@github.com> 
Data:17/12/2016  21:46  (GMT+02:00) 
A: eranif/codelite <codelite@noreply.github.com> 
Cc: Zibri <zibri@zibri.org>,Author <author@noreply.github.com> 
Oggetto: Re: [eranif/codelite] unusable. why? (#1496) 

all I need is a f*cking editor with C code completion...

please use the forum if you have any more questions, but not like this
