### ISSUE TITLE
Codelite (Surface Pro 4) Workspace Not Opening

### ISSUE THREAD

**Issue by davidjp999** [eranif/codelite#1497]
hi,
just to give context i've added the laptop factor, incase that makes a difference.
I'm running 64bit 9.2.0

when i open the programme, it launches the last used workspace and were the workspace
should be, is grey and i can not do anything.
Initially it worked when i first installed. I have tried re-installing fresh with the same issue.

any help appreciated

-David

**Comment by eranif** [comment]
Basically, these kind of bug reports does not help us solving the bug..
You should at least provide steps to reproduce.

Can you open other workspace files? or create a new one?

In anycase, in order to move forward with this bug, please provide a steps to reproduce

**Comment by eranif** [comment]
I have tested this, and this is an environmental issue (i.e. something wrong with your setup)
