### ISSUE TITLE
Download links should specify that it is a "shasum"

### ISSUE THREAD

**Issue by TamaHobbit** [eranif/codelite#1499]
[On this page](https://downloads.codelite.org/), the shasum of each download should have the word "shasum" in front (or any other way that you can tell that it is that kind of checksum).

As it is, I just had to run all the checksum programs I could find until I hit one that happened to have the correct checksum. If there was indeed a download error, I would've been unable to tell whether you used some other checksum program, or that there was a download error.

**Comment by eranif** [comment]
Fixed
