### ISSUE TITLE
Detached output window retains mouse focus indefinitely

### ISSUE THREAD

**Issue by Coder666** [eranif/codelite#1501]
If I detach the output window from the main application and place it on a second monitor, double clicking on an error message will change the source code view to the correct file & line, this works as expected. 

However, the output window retains mouse focus.  I can type in the source code window, but any mouse scrolling, clicking etc goes to the output window.  Menu items, buttons etc in the main application cannot be selected using the mouse.  This effect lasts until I close and re-open the application (which has to be done from the terminal because nothing outside of the output window can be clicked.)

Platform Ubuntu 16.10
Cinnamon Desktop

**Comment by eranif** [comment]
I am unable to reproduce this. Which CodeLite version?
