### ISSUE TITLE
No way to change Default Column Limit (It's alwasys set to 80)

### ISSUE THREAD

**Issue by Dr-Xperience** [eranif/codelite#1503]
I have set the ColumnLimit to 150 in .clang-format and placed it inside the project folder. But when I open a file having text more than 80 column for the first time (Which I have created manually using other editor in pasr) in the IDE. It for some reason breaks the line after 80 column and messes up with my comments. 

If there is any way to change the Editor's default column limit, kindly advice with same.

**Comment by eranif** [comment]
The settings from `.clang-format` are used during file formatting (i.e. when you hit `Ctrl-I`)
To make sure that CodeLite will use the settings from `.clang-format` and not from the UI itself, you need to set it from: `Plugins->Source Code Formatter->C++ tab->clang-format->Style` and set it to `File`

**Comment by Dr-Xperience** [comment]
Thanks for reply, but that is not my problem. I have already set it to File. 

I am talking about auto line break when opening an existing file inside the editor. When it is opened for the first time the editor automatically breaks the line having more that 80 column.

Example:

```
/*****************************0*0 **********************************************
    BinaryTreeOperations Library (It uses Iterative technique to perform all operation (Some are iterations converted from recursion).
    Copyright (C) 2016  Anubhav Arun <dr.xperience@gmail.com>
**********************************************************************************/

```
A file having the above comment if opened inside the editor will automatically be wrapped like this 

```
/****************************************************************************
    BinaryTreeOperations Library (It uses Iterative technique to perform all 
operation (Some are iterations converted
from recursion).
    Copyright (C) 2016  Anubhav Arun <dr.xperience@gmail.com>
*****************************************************************************/
```
When its opened inside the editor for the first. Now even if I press Ctrl+I the comments will not change. This is just an example, but we have long mathematical equations inside the comment as well and it creates a mess.

I am using version 9.2.8 (It scales well on 2k screen)

**Comment by eranif** [comment]
I am not sure I am following.
Can you please upload a zip file containing an example workspace with sample files and steps for reproduction? Thanks

**Comment by Dr-Xperience** [comment]
I deeply apologize it seems yesterday was a really bad day. I recreated the project from scratch today and everything magically is working well. 

I apologize again for wasting your time. I don't know what when wrong yesterday. 

Thanks again for entertaining my stupidity.
(You may delete this issue, this was some ghost effect, I apologize again.)
