### ISSUE TITLE
CodeLite internal update checker did not notice 9.2->10.0

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1504]
Hi,

CodeLite internal update checker did not notice 9.2->10.0 update

I've also tried checking it manually from Heip->Check updates... 

No result

Seen on Arch Linux 64bit

**Comment by eranif** [comment]
Can you please do this:
Settings->Preferences->Misc->Log->Debug

Run:
Help->Check for update

And check the output in CodeLite's log file: `~/.codelite/codelite.log`
It should print the content it fetched from the website.

I debugged the code and it seems to be working fine *code wise*, I did however, got some cached version of http://codelite.org/packages.json

I disabled this and it is now working properly for me

**Comment by uffejakobsen** [comment]
Did some tests with CL-9.2.0 and it still does not work on my system.

I did some more testing with CL-10.0.0 - and found an explanation (bug)

It seems that CL downloads the "codelite-packages.json" file to /tmp on my system

To protecting file "/tmp/codelite-packages.json" from being written by my desktop user I did a chown to root:root on the file.
That allowed me to change and manipulate the contents of the file.

CL correctly reads the manipulated changes - see codelite.log snip:

[17:20:52:308 DBG] Keyboard manager: Initializing keyboard manager
[17:20:52:316 DBG] Current platform details: linux , others , x86_64 , 10.0.0
[17:20:52:316 DBG] ---> msw-dbg , Windows , x86_64 , 920
[17:20:52:316 DBG] ---> msw , Windows , x86_64 , 920
[17:20:52:316 DBG] ---> msw , Windows , i386 , 920
[17:20:52:317 DBG] ---> osx , 10.8 , x86_64 , 920
[17:20:52:317 DBG] ---> linux , Debian GNU/Linux 8 , x86_64 , 920
[17:20:52:317 DBG] ---> linux , Ubuntu 14.04 , x86_64 , 920
[17:20:52:317 DBG] ---> linux , others , N/A , 1234

In the above test I would have thought that I'd flagged that there was an update to 12.3.4 available for my distribution... but I does not react on that - and hence I'm not notified...

Changing the "acrh" field from "N/A" to "x86_64" makes the update notification work...

Something in your matching code fails to handle field arch "N/A" as a wildcard...

/Uffe

**Comment by eranif** [comment]
The simple solution should be:
Change the `packages.json` file to have 2 entries like this:
```json
[{
  "os": "linux",
  "codename": "others",
  "arch": "x86_64",
  "version": 1000,
  "url": "http://codelite.org/LiteEditor/ReleaseNotesCodeLite10"
},{
  "os": "linux",
  "codename": "others",
  "arch": "i386",
  "version": 1000,
  "url": "http://codelite.org/LiteEditor/ReleaseNotesCodeLite10"
}]
```

What do you think?

**Comment by eranif** [comment]
Fixed on the website `packages.json` file

**Comment by uffejakobsen** [comment]
Yes I think that it is a good solution 
Thanks 👍
