### ISSUE TITLE
unable to fetch URI error getting keys

### ISSUE THREAD

**Issue by qt1** [eranif/codelite#1507]
Tried to follow instructions on [http://codelite.org/LiteEditor/Repositories#toc1](http://codelite.org/LiteEditor/Repositories#toc1) on Ubuntu 16.04

    sudo apt-key adv --fetch-keys https://repos.codelite.org/CodeLite.asc

Getting keys fail:

    Executing: /tmp/tmp.IQugCF6Jtu/gpg.1.sh --fetch-keys
    https://repos.codelite.org/CodeLite.asc
    gpgkeys: protocol `https' not supported
    gpg: no handler for keyserver scheme `https'
    gpg: WARNING: unable to fetch URI https://repos.codelite.org/CodeLite.asc: keyserver error

**Comment by eranif** [comment]
Hi, please try like this:
`sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc`

**Comment by qt1** [comment]
Workaround: this seems to work:

    sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc

**Comment by eranif** [comment]
I have updated the wiki
