### ISSUE TITLE
Outline view missing from workspace view

### ISSUE THREAD

**Issue by bjarne89** [eranif/codelite#1508]
I only have the "Workspace"-, "Explorer"-, "Tabs"-, and "Tabgroups"-tab in my workspace view. I'm currently using CodeLite v10.0 on a Ubuntu computer (16.04.01).

I use Codelite on another computer with the same setup, and the outline view is not missing there.

**Comment by bjarne89** [comment]
All the missing tabs can be seen for a split second during application startup, but disappears again.

**Comment by eranif** [comment]
Its a matter of settings.
Click on the 3 vertical dots and select which tabs should be visible.
See this screenshot:

![1](https://cloud.githubusercontent.com/assets/3677711/21750149/266a98fe-d5b5-11e6-901c-e30b3c99a663.png)

If you don't have the caption with the 3 vertical dots, hit `Ctrl-F11` to toggle it (or from the menu: `View->Toggle Minimal View`)

**Comment by bjarne89** [comment]
*facepalm*

Thank you for the help, and also for the awesome CodeLite IDE :)
