### ISSUE TITLE
compile and build errors building codelite 10 on FreeBSD

### ISSUE THREAD

**Issue by timtoomay** [eranif/codelite#1509]
Hi eranif I found two compile errors so far which I worked around, see the end of this post.
I need help with the latest problem, a link error which I don't know how to handle:

[  1%] Built target wxsqlite3
[  2%] Built target codelite-cc
[  7%] Built target codelite_indexer
[  9%] Built target PHPParser
[  9%] Built target codelite-echo
[ 13%] Built target codelite_cppcheck
[ 14%] Built target databaselayersqlite
[ 17%] Built target wxshapeframework
[ 17%] Linking CXX shared library ../lib/liblibcodelite.so
/usr/bin/ld: cannot find -ldl
c++: error: linker command failed with exit code 1 (use -v to see invocation)
--- lib/liblibcodelite.so ---
*** [lib/liblibcodelite.so] Error code 1

Any advice would be appreciated.

Here are the two compile errors, the first related to backtrace, the second related to
ambiguous use of NULL.  Please advise if you want further action on the changes I made.

[  1%] Built target wxsqlite3
[  2%] Built target codelite-cc
[  7%] Built target codelite_indexer
[  9%] Built target PHPParser
[  9%] Built target codelite-echo
Scanning dependencies of target codelite_cppcheck
[  9%] Building CXX object sdk/codelite_cppcheck/CMakeFiles/codelite_cppcheck.dir/cli/cppcheckexecutor.cpp.o
[  9%] Building CXX object sdk/wxshapeframework/CMakeFiles/wxshapeframework.dir/src/ControlShape.cpp.o
[  9%] Linking CXX executable ../../bin/codelite_cppcheck
CMakeFiles/codelite_cppcheck.dir/cli/cppcheckexecutor.cpp.o: In function `CppcheckSignalHandler(int, __siginfo*, void*)':
/home/tim/cl/100/codelite/sdk/codelite_cppcheck/cli/cppcheckexecutor.cpp:(.text+0x243d): 
undefined reference to `backtrace_symbols'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
--- bin/codelite_cppcheck ---
*** [bin/codelite_cppcheck] Error code 1

make[2]: stopped in /usr/home/tim/cl/100/codelite/bldrel
1 error

Satisfied the build by copying in some code from sqlite3.
/*
** The backtrace functionality is only available with GLIBC
*/
#ifdef __GLIBC__
  extern int backtrace(void**,int);
  extern void backtrace_symbols_fd(void*const*,int,int);
#else
# define backtrace(A,B) 1
# define backtrace_symbols(A,B) 0
# define backtrace_symbols_fd(A,B,C)
#endif

The second error was an ambiguous use of NULL
   if( lstParentsToUpdate.Find( parent ) == NULL ) lstParentsToUpdate.Append( parent );
   I changed the NULL to 0 and that satisfied the compile.  Here is context.

[ 16%] Building CXX object sdk/wxshapeframework/CMakeFiles/wxshapeframework.dir/src/ShapeDataObject.cpp.o
/home/tim/cl/100/codelite/sdk/wxshapeframework/src/ShapeCanvas.cpp:3228:48: error: conversion from 'nullptr_t' to 'const wxString' is ambiguous
                                                if( lstParentsToUpdate.Find( parent ) == NULL ) lstParentsToUpdate.Append( parent );
                                                                                         ^~~~
/usr/include/sys/_null.h:35:14: note: expanded from macro 'NULL'
#define NULL    nullptr
                ^~~~~~~
/usr/local/include/wx-3.1/wx/string.h:1125:3: note: candidate constructor
  wxString(const char *psz)
  ^
/usr/local/include/wx-3.1/wx/string.h:1138:3: note: candidate constructor
  wxString(const unsigned char *psz)
  ^
/usr/local/include/wx-3.1/wx/string.h:1151:3: note: candidate constructor
  wxString(const wchar_t *pwz)
  ^
1 error generated.
--- sdk/wxshapeframework/CMakeFiles/wxshapeframework.dir/src/ShapeCanvas.cpp.o ---
*** [sdk/wxshapeframework/CMakeFiles/wxshapeframework.dir/src/ShapeCanvas.cpp.o] Error code 1

**Comment by eranif** [comment]
I am sorry, we don't officially support FreeBSD.
Maybe you can consult with the FreshPorts guys to see how do they make CodeLite build

https://www.freshports.org/editors/codelite/

**Comment by timtoomay** [comment]
Thanks Eran
