### ISSUE TITLE
Cannot build Release, always switch back to Debug by default...

### ISSUE THREAD

**Issue by jiapei100** [eranif/codelite#1513]
Hi, @eranif 

I built your most recent codelite (git clone from github), upon the most recent wxWidgets-3.1.0 ... My Environment is: Ubuntu 16.04.1, with GCC/G++ 5.4.0.

My issue is: I cannot build a Release version of my code. 
Project->Settings->Top Selector (Debug -> Release).
However, it seems CodeLite will automatically jump back to Debug and build a Debug version library.

Any suggestions???

Thank you very much..
Pei

**Comment by eranif** [comment]
Please read the wiki about the configuration manager:
http://codelite.org/LiteEditor/ConfigurationManager
