### ISSUE TITLE
Feature Request: Make auto complete box resizable and has scroll bar

### ISSUE THREAD

**Issue by zufuliu** [eranif/codelite#1516]
The current (10.0.0 Windows x64) auto complete box is not resizable, and has no scroll bar make is hard to chose item from a long list. 
As I known, the auto complete box in Scintilla (as used in SciTE, Notepad++ and others) is resizable and has scroll bar. The max width and height of the box can be set using `SCI_AUTOCSETMAXWIDTH` and `SCI_AUTOCSETMAXHEIGHT` message in Scintilla, however I don't known whether it can be achieved or not in the WX port, sine is seems use the 3.5.x version of Scintilla (current is 3.7.2).

**Comment by eranif** [comment]
The current completion box is not using the wxStyledTextCtrl (Scintilla's wrapper) completion box, instead we implemented our own completion box.

What you have suggested is not going to get implemented.

You can narrow down the list by continuing typing or limit the number of displayed characters.
Another possible fix, is to implement a mouse middle button scroll feature (i.e. implement scrolling with the mouse)

**Comment by eranif** [comment]
As I suggested, I have implemented scrolling with the mouse. Each scroll tick moves 1 page (up or down) this should make the process of searching a long list faster

**Comment by zufuliu** [comment]
I just build CL from source, and find that, 
void wxCodeCompletionBox::OnMouseScroll(wxMouseEvent& event)
not triggered, scroll occurs in the main editor, not in completion box.

**Comment by eranif** [comment]
The mouse needs to hover the completion box, otherwise the editor will capture the mouse.
Is that the case for you?

**Comment by zufuliu** [comment]
Tested on Win7 64, the mouse is always the hand in the completion box (however arrow in tooltip windows), can only click.

**Comment by eranif** [comment]
This seems to be working on Linux / OSX, but indeed fails on Windows.
I will see how can this be fixed for all platforms

**Comment by eranif** [comment]
I committed a fix that is working for Windows. Please give it a try

**Comment by zufuliu** [comment]
It works now, thank you.
