### ISSUE TITLE
Search files not working

### ISSUE THREAD

**Issue by John-Henrique** [eranif/codelite#1518]
Trying use search files, but never get result. Search in cocument works fine.

(I try download last version, but .exe package is corrupted)

SO: Windows 10 (64)
CodeLite: 9.2.0

**Comment by eranif** [comment]
The more disturbing part is that the .exe is corrupted...
We provide .7z files not exe, is it corrupted?

**Comment by John-Henrique** [comment]
When download ([Windows 10 64 bit installer](https://downloads.codelite.org/downloads.php?windows_64)) is complete I need extract, so I have a .exe  ;-)  every time display this message
![codelite-error](https://cloud.githubusercontent.com/assets/332925/22152849/d6ae8da6-df0b-11e6-94b3-04df1fc885e4.png)

I try download five times...

**Comment by eranif** [comment]
Can you try with 7-zip and not with WinRAR? 
I opened the archive file without an error (although on OSX) - but I used a dedicated 7-zip software

**Comment by John-Henrique** [comment]
I installed 7-zip and with him I can extract correctly

**Comment by eranif** [comment]
Back to the main problem:
Make sure that the `File Mask` and `Look In` fields are properly set.

**Comment by John-Henrique** [comment]
I try again, really don't work.

**Step to reproduce**

In 'workspace view', I can see files of project, there, I click right buttom and choose 'find in files', the window 'Find in files' is opened and I can fill "Find what", "File mask" is marked as "*.php;*.inc;...", the input "Look in" is auto set with the name of directory where I click.

When I click in button "Find", after process the panel "Output view" is opened whitout informations. The tab "Tail" is selected.

**Other informations**

Project: PHP
CodeLite: 10.0.0
SO: Windows 10 (64)

**Comment by eranif** [comment]
Hmm, you don't have the "Search" tab available?

**Comment by eranif** [comment]
Please follow this bug report and see how we fixed it for him:
https://github.com/eranif/codelite/issues/1511

**Comment by John-Henrique** [comment]
Yes, is correct. Thanks again.

**Comment by mh-tp** [comment]
search files * instead of *.* helped

(search engine brought me here, so it might help others)
