### ISSUE TITLE
No Watch Option with LLDB debugger

### ISSUE THREAD

**Issue by mtangoo** [eranif/codelite#1520]
CL 10, OSX El Capitan.
I run debugger but cannot see context menu for add Watch.
I can inspect variables just fine.

Ubuntu Box with GCC is just fine

**Comment by eranif** [comment]
Under OSX, please use LLDB and not GDB (its not supported)

**Comment by mtangoo** [comment]
>Under OSX, please use LLDB and not GDB (its not supported)

That is what I use and works great with exception of context menu to add watched variable.

If I use watch local variable Icon it works too for variables (not expressions though)
