### ISSUE TITLE
32bit GDB version 7.12.1-1  thru 7.12.1-1 cuases pretty printer issue and crashes when trying to walkthrough code.

### ISSUE THREAD

**Issue by genusistimelord** [eranif/codelite#1521]
Hello Well using GDB 7.12 for 32bit seems to be competently broken for codelite. I am not sure if they essentially did this or if they just removed features and replaced them with new. However anytime i try the newer 32bit releases i find that they all have failed to work with codelite. I do know that gdb 7.11 and down still work fine for 32bit with codelite. I just wanted to know why exactly. 

Anyways to get technical this is what occurs when GDB is ran with pretty printers enabled:
`DEBUG>>&"python\n"
DEBUG>>&"Traceback (most recent call last):\n"
DEBUG>>&"  File \"<string>\", line 4, in <module>\n"
DEBUG>>&"  File \"c:\\msys64\\mingw32\\share\\gdb/python/../../gcc-6.3.0/python/libstdcxx/v6/printers.py\", line 1334, in register_libstdcxx_printers\n"
DEBUG>>&"    gdb.printing.register_pretty_printer(obj, libstdcxx_printer)\n"
DEBUG>>&"  File \"c:\\msys64\\mingw32\\share\\gdb/python/gdb/printing.py\", line 152, in register_pretty_printer\n"
DEBUG>>This application has requested the Runtime to terminate it in an unusual way.
This application has requested the Runtime to terminate it in an unusual way.
DEBUG>>Please contact the application's support team for more information.
Please contact the application's support team for more information.
DEBUG>>&"    printer.name)\n"
DEBUG>>&"RuntimeError: pretty-printer already registered: libstdc++-v6\n"`

when i remove register_libstdcxx_printers (None) from the script in gdb it starts up fine then but can not navigate through code without crashing.

`79\t\ttest = init_sprite("./images/gui/background.png");
DEBUG>>*stopped,reason="breakpoint-hit",disp="keep",bkptno="2",frame={addr="0x00401824",func="main",args=[],file="C:/msys64/home/genusis/glfw_opengl_glad/source/main.c",fullname="C:\\msys64\\home\\genusis\\glfw_opengl_glad\\source\\main.c",line="79"},thread-id="1",stopped-threads="all"
DEBUG>>00000013-file-list-exec-source-file
DEBUG>>00000014-break-list
DEBUG>>00000013^done,line="79",file="C:/msys64/home/genusis/glfw_opengl_glad/source/main.c",fullname="C:\\msys64\\home\\genusis\\glfw_opengl_glad\\source\\main.c",macro-info="0"
DEBUG>>00000014^done,BreakpointTable={nr_rows="1",nr_cols="6",hdr=[{width="7",alignment="-1",col_name="number",colhdr="Num"},{width="14",alignment="-1",col_name="type",colhdr="Type"},{width="4",alignment="-1",col_name="disp",colhdr="Disp"},{width="3",alignment="-1",col_name="enabled",colhdr="Enb"},{width="10",alignment="-1",col_name="addr",colhdr="Address"},{width="40",alignment="2",col_name="what",colhdr="What"}],body=[bkpt={number="2",type="breakpoint",disp="keep",enabled="y",addr="0x00401824",func="main",file="C:/msys64/home/genusis/glfw_opengl_glad/source/main.c",fullname="C:\\msys64\\home\\genusis\\glfw_opengl_glad\\source\\main.c",line="79",thread-groups=["i1"],times="1",original-location="C:/msys64/home/genusis/glfw_opengl_glad/source/main.c:79"}]}
DEBUG>>00000015-exec-step
DEBUG>>This application has requested the Runtime to terminate it in an unusual way.
This application has requested the Runtime to terminate it in an unusual way.
DEBUG>>Please contact the application's support team for more information.
Please contact the application's support team for more information.
DEBUG>>00000015^running
Continuing...
DEBUG>>*running,thread-id="all"
*running,thread-id="all"`

Now the program will run completely fine with GDB as long as I do not add a break point and or try to navigate the code though. Any ideas?

**Comment by eranif** [comment]
> This application has requested the Runtime to terminate it in an unusual way. This application has requested the Runtime to terminate it in an unusual way. DEBUG>>Please contact the application's support team for more information. Please contact the application's support team for more information

This is GDB crashing, not CodeLite, I really have nothing to do here.
Try disable python pretty printers completely and see if it works for you from:
Settings->GDB Settings->Display->Enable pretty printing

Other than that, I have no idea why it crashes
