### ISSUE TITLE
git blame on line selection in editor

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#1522]
it would be nice if I could select a handful of lines in the editor, right-click, and select "Git blame" in the context menu, and have it run 'git blame -Lx,y' on those line numbers for that file

**Comment by dghart** [comment]
Hi,

I'd originally intended to add a separate -Lx,y option to the git blame dialog, but now the blame of the whole file is easily seen it seemed pointless to narrow down the area. Even in a large file it's easy to scroll to the lines you want.

You can already open the 'blame' dialog from a context menu: it's one of the 'Git' options when you right-click on a file in the Workspace View.

BTW, if you really do want to specify a line range, you can add it by hand in the 'blame' dialog's Extra Arguments field.

Regards,

David

**Comment by grandinj** [comment]
thanks
