### ISSUE TITLE
wxCrafter doesn't work in Archlinux

### ISSUE THREAD

**Issue by sapjunior** [eranif/codelite#1524]
CodeLite Version : 10.0 from AUR [https://aur.archlinux.org/packages/codelite-bin/]
I already try multiple wxCrafter.so file from http://repos.codelite.org/wxCrafter-2.7/ none of them work!
The nearest match is the one from xenial official. After investigate error in .codelite/crash.log and codelite.log there is nothing in those file and codelite start normally (but without wxCrafter)

**Comment by eranif** [comment]
We don't provide wxCrafter for ArchLinux.

**Comment by sapjunior** [comment]
Thank you for your response.
Just for your information for Codelite 9.3 + wxCrafter2.6 (from :http://codelite.org/LiteEditor/Repositories) ubuntu yakkety official version work perfectly fine without any problem
