### ISSUE TITLE
Right margin is not showing well

### ISSUE THREAD

**Issue by fulgor3** [eranif/codelite#1525]
Hello,
The problem is that I set the indicator column to 80, but I really appears in the column 57.

Best regards.

**Comment by eranif** [comment]
Which OS? CodeLite version?

**Comment by fulgor3** [comment]
Debian Testing (stretch).
CodeLite version 9.2.0.

Best regards.

**Comment by fulgor3** [comment]
Each line seems to show different column numeration. Could be because of a different letter dimensions or something? This is the first time I see something like this. If you want an screenshot or something, ask for it. I really like this IDE :). Congrats.

**Comment by eranif** [comment]
Try changing the font, this is usually the case. Settings->Preferences->Colours and Fonts

Which font do you use?

**Comment by fulgor3** [comment]
Cantarell. I am going to try to change it and let's see if this fix the issue. Is this the first issue related to this?

**Comment by eranif** [comment]
Reported in the past numerous times, everytime the user was using a font which was not drawn properly by scintilla (CodeLite's editor component)

**Comment by fulgor3** [comment]
I think it is solved and maybe it was because I needed a monospaced font. Maybe my fault but the font was the default.
Thank you and tomorrow I will work more on it to confirm the solution :+1:
