### ISSUE TITLE
crash after completing include path

### ISSUE THREAD

**Issue by nuclear-afk** [eranif/codelite#1528]
i have a main.cpp file. i am adding includes to the file. i have one half typed in and codelite helpfully suggests a completion, i click it and it instantly closes without making any new windows. lost a lot of work :( (the include was wx/button.h btw)

**Comment by eranif** [comment]
Is this reproducible? Which CodeLite version and which OS?
Please provide a *step by step* instructions on how to reproduce it. An example workspace will be better

**Comment by nuclear-afk** [comment]
ok
i am on kali linux uname -r returns

4.8.0-kali2-amd64

codelite --version returns

21:00:37: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1009,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1010,wx containers,compatible with 2.8).
CodeLite IDE v9.2.0

link to workspace
https://drive.google.com/open?id=0B9s7NtKF4NP1aFNBSEFCUHE1elU
to see it crash open the workspace and main.cpp start typing under the includes there

#include <wx/but

for me it suggests button.h if i click it it instantly crashes.
i also manually added /usr/include/wx-3.0/wx/ to my search paths btw
Thanks a lot!

**Comment by eranif** [comment]
Where did you get this CodeLite version? we don't provide builds for Kali Linux.
Is this a self compiled version? 

This is not crashing on various Linux boxes I have tested (and again, non have a library mismatch error)
Having an ABI mismatch is the cause of the crash - you will need to fix this yourself (usually, by building CodeLite from sources)
