### ISSUE TITLE
Error installing wxWidgets 3.02

### ISSUE THREAD

**Issue by Kowalski555** [eranif/codelite#1529]
Hi,

im trying to install wxWidgets on my Raspberry Pi 3 (Raspian, Debian).  After adding 'deb http://repos.codelite.org/wx3.0.2/debian/ wheezy libs' to 'etc/apt/sources.list' I run 'sudo apt-get update' and get the error message:
'W: GPG-Fehler: http://repos.codelite.org wheezy InRelease: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 6856E1DB1AC82609
W: Fehlschlag beim Holen von http://repos.codelite.org/wx3.0.2/debian/dists/wheezy/libs/binary-armhf/Packages  404  Not Found'

Any ideas how to resolve this issue?

Thanks for your Help!

**Comment by eranif** [comment]
I am not sure if we provide wxWidgets 3.0.2 for Arm, but I could be wrong here.
In anycase, this is definitely not a CodeLite bug
