### ISSUE TITLE
Program Arguments TOO LONG???

### ISSUE THREAD

**Issue by jiapei100** [eranif/codelite#1530]
Weird that I built the executable with codelite 10.0.2 successfully. And I'm able to run the executable by command line, but NOT able to debug it within codelite IDE.
And, it's reporting **Could not launch terminal for debugger** .

Since all of my other projects under the workspace work properly, I believe this is NOT the issue reported [https://github.com/eranif/codelite/issues/1206](https://github.com/eranif/codelite/issues/1206) .

So, is it possible that my Program Arguments is **TOO LONG**???

Cheers
Pei

**Comment by eranif** [comment]
I really have no idea.
I don't really see a **general** bug here, maybe a configuration issue.
Please start a thread on the forum

**Comment by jiapei100** [comment]
Yes, 2 possible reasons:

1. Argument **TOO LONG**
2. Argument containing non-digit special characters, in my case: "**_**"

Cheers
Pei
