### ISSUE TITLE
LLDB not opening lldb-debugger.layout

### ISSUE THREAD

**Issue by StMartin81** [eranif/codelite#1531]
I have a gtest project where the main function is outside of my project. When I want to debug a project using the LLDB debugger CodeBlocks is not opening the lldb-debugger.layout perspective (at least no checkmark is set on the perspective). When I start to debug the project the debugger does not stop at the previously set breakpoint. I have to select "Next" as run option and then the program will stop at the breakpoint. If I chose "Start / Continue Debugger" instead the program will not stop at the breakpoint.

This behavior occured with CodeBlock 10.0 on Manjaro.

[workspace.zip](https://github.com/eranif/codelite/files/742919/workspace.zip)

**Comment by eranif** [comment]
> This behavior occured with CodeBlock 10.0 on Manjaro.
You mean CodeLite

I am unable to reproduce this here on Debian

Can you please load a minimal workspace that does not rely on various external libraries?
