### ISSUE TITLE
codelite-make doesn't complete on OSX

### ISSUE THREAD

**Issue by jazzbre** [eranif/codelite#1534]
When I run:

`MyMac:Test me$ /Applications/codelite.app/Contents/MacOS/codelite-make -v -w Test.workspace -c Debug
`

It generates the makefiles etc, but then it is stuck at the last line (meaning that it doesn't exit from codelite-make, I have to ctrl-C it to exit):

`
[INFO  ] -- Generating makefile for workspace file /Users/me/Projects/CodeLite/Test/Test.workspace
[INFO  ] -- Makefile generation completed successfully!
[INFO  ] -- To use the makefile, run the following commands from a terminal:
cd /Users/me/Projects/CodeLite/Test && /usr/bin/make -j8 -e -f  Makefile
`

nothing happens from here on.
Works normally from IDE on OSX and it works normally on Windows in IDE and codelite-make.
Any ideas?

(Os version: 10.12.3)

**Comment by eranif** [comment]
You need to add `--execute` 
Run `codelite-make -h` to get the list of options

**Comment by jazzbre** [comment]
The problem is that even with -e, it stays there and does nothing, but only on OSX.
But it doesn't exit codelite-make, so I have to ctrl-C to exit.
