### ISSUE TITLE
Find and Replace form widget sizes became unusable

### ISSUE THREAD

**Issue by Lyberta** [eranif/codelite#1535]
I was using find and replace and for some reason all buttons got pushed to the right which made the form unusable.

![screenshot at 2017-02-03 23-18-36](https://cloud.githubusercontent.com/assets/10873185/22607233/5f035334-ea70-11e6-9482-3938f2502312.png)

**Comment by eranif** [comment]
its a bug in wxWidgets. Once of the strings u used was too big which caused the control to use too much space. delete the files: `~/.codelite/config/codelite.xml` and `~/.codelite/config/codelite.conf`

**Comment by Lyberta** [comment]
Can you just say what text should I delete from these files? I don't want to lose my config.
