### ISSUE TITLE
Inconsistent tab coloring, mostly don't follow desktop theme.

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [eranif/codelite#1536]
## Context

Trying codelite. Trying dark theme.

This is related to issue #1122 that I have read and went further along.

A sensible thing to do is to configure desktop to use a dark theme. Makes sense: codelite actually complies with what your desktop *requires*. If your desktop has a bright theme, so will codelite. In Ubuntu 16.04, consider themes Ambiance (few changes), NOX (more changes), Xfce-dusk (all white on dark).

## Issue: tab titles stay bright.

Even after that, codelite does not obey the requested colors or desktop theme on some areas.
More specifically, the workspace pane tabs and output pane tabs are still black text on light background. See below.

![codelite_dark_not_all](https://cloud.githubusercontent.com/assets/2843528/22619344/470c6b84-eaf3-11e6-993a-1ab137e999bd.png)

Interestingly, when no workspace is open, the main editor tabs are wrong (black text on light background, see "Welcome!" thab on attached picture) but they become right as soon as one file is opened, and become wrong again when the file is closed. See below.

![codelite_dark_not_all_but_after_file_open](https://cloud.githubusercontent.com/assets/2843528/22619345/49f8e87c-eaf3-11e6-8e16-c1c850bc525b.png)

## Additional information

Xubuntu 16.04, codelite 9.1.0 from regular Ubuntu package repos.

Perhaps PR #1510 fixed that? Haven't checked, though.

Sidenote: people using dark theme often express concerns about eye fatigue at night. This is a relevant though orthogonal issue. Any person (except people relying on exact colors like graphic artists) using a computer at night will benefit from [Redshift](http://jonls.dk/redshift/). Since I use redshift I've been able to use "white"-background themes apps late at night with comfort.

Thank you for your attention.

**Comment by eranif** [comment]
> Perhaps PR #1510 fixed that? Haven't checked, though.

Will make the tabs dark. Always (all of them not only the "Editor" ones) so it should fix your problem

**Comment by fidergo-stephane-gourichon** [comment]
Thank you.

Then things should be fine. I you allow me to risk commenting on something that you already fixes, in "colours and fonts", "general", the word "global" is IMHO a misnomer (at least in 9.1.0).

They are not truly global:

* "global font" and "global theme" affect some panels, including editor.
* "global foreground color" and "global background color" affect another set of panels, disjoint from the first.

Currently, users that have set their desktop to use a dark theme get an inconsistent behavior because all those four settings are not automatically correlated with desktop theme.

In other words, does any user wish to have light-on-dark source code and dark-on-light side panels until they fiddle with settings? If anyone testifies, I'll admit it, but until that I feel no one likes that.

To make the best experience to them, two suggestions:

* Perhaps the "global theme" could be auto-selected depending on desktop theme.  For example, if desktop environment text color is darker than background color, choose theme "default" (bright), else (text color is lighter than background color), choose theme "Monokai_2".
* Perhaps the "global colors" could by default match desktop theme at any time, so that side panels are consistent with overall behavior. Then these options are only an optional override (just in case some user do want e.g. light-on-dark source code and dark-on-light side panels).

Side note: have you written codelite alone? That's impressive!

Thank you for your attention.

**Comment by eranif** [comment]
> Side note: have you written codelite alone? That's impressive!

I would say 90+ perecent of CodeLite was written by me. I Started it at 2007... people contributed patches along the years, except for @dghart who is a permenant developer of CodeLite, most of them are no longer contributing
