### ISSUE TITLE
Default "match brace" key shortcut fails on non-US keyboard.

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [eranif/codelite#1538]
Hello.

Codelite seems good because it seems lightweight, fast, versatile and does the job.

## Context

`Ctrl-]` calls "match brace" which goes back and forth between opening and matching closing brace.

On French keyboard it is a combination including `AltGr` key. 

## Expected

CodeLite does match-brace.

## Observed

CodeLite inserts `]` in editor window.

## Additional information

Ubuntu 16.04, Codelite 9.1.0.

Switching to US keyboard layout makes the feature work as expected.
Switching back to French keyboard layout makes the feature fail again.

Using the US key combo while in French layout does nothing (those same keys mean `Ctrl-$` in French layout and are not supposed to do anything anyway).

Thank you.

**Comment by eranif** [comment]
Can't you just change it?

**Comment by fidergo-stephane-gourichon** [comment]
Short answer: I can change it but not in a satisfactory way and not to the one I'm accustomed to. 

Long answer: The bug is twofold: "default is broken" + "many keys that Codelite can't use for shortcut". 

Spirit: Don't think I'm "complaining for myself", I'm rather concerned about all those countries where this twofold problem occurs.


The first point is that it doesn't work out-of-the-box, and it is generally a good policy to get used to whatever software provides as default because author generally takes care of using consistent settings. Plus every customization will have to be repeated on all instances of the software, so you better avoid it at all.

More concretely, this keyboard shortcut is broken out-of-the-box on a number of international keyboard layout. I'm (mostly) not complaining here, just willing to raise awareness and hope it can be fixed.

## Changing it does not satisfy.

I tried to change it. I open "settings->keyboard shortcut".

Pressing `Ctrl-]`, program does not get it. It believes that I pressed `Ctrl-)`, which is without `AltGr`.
`Ctrl-}` would not match either, it would become `Ctrl-=` without AltGr.

Anyway, my preference would be `Ctrl-%` which I am accustomed to in emacs. Alas, it does not catch it. Actually it's not a matter of `Ctrl`. Codelite does not catch the key at all.

Neighbouring keys are `ù', `^' which it can't get either, so neither with shift (`%` and `¨`).

All those keys work fine when typing. They just aren't caught at all when trying to set them as shortcut.

Hope this helps.
