### ISSUE TITLE
Re-add "File Types" settings option

### ISSUE THREAD

**Issue by Enhex** [eranif/codelite#1543]
CodeLite used to have settings option for "File Types" in CTag -> Advanced, which is missing now.
To edit this option users have to somehow discover `m_fileSpec` in the auto-completion.conf.

**Comment by eranif** [comment]
This is not going to get re-added.
What is the problem you are facing (obviously, the above is the solution you found for a problem)?

**Comment by Enhex** [comment]
It can be useful for some users.
One use case is for users that want to use CodeLite with AngelScript scripting language, they need to add its file extension to the list:
http://discourse.urho3d.io/t/configuring-codelite-for-editing-as-scripts/68
https://wiki.frictionalgames.com/hpl3/3rdparty/codelite

**Comment by eranif** [comment]
So IIRC, we want to handle *.as as valid C++ files, right? (it behaves the same except for the `@` thingi?)
Or better: can you give me list of files to add? I will make sure it will be included everywhere so less configuration by your users is needed

**Comment by Enhex** [comment]
Yeah, the languages are similar enough for C++ IDEs to be usable with AngelScript code, but they're not identical so I'm not sure if it's a good idea to officially add it since it's a hack after all (No good IDEs for AngelScript AFAIK).

`.as` seems  to be the common choice for AngelScript source file extension, but it conflicts with the file extension for the more popular Flash ActionScript.

Since it's a rather special use case I think leaving it for the user to config is ok.

**Comment by eranif** [comment]
>  Flash ActionScript.

This is a dead language... no one uses it anymore, so I don't mind adding it as AngelScript

**Comment by Enhex** [comment]
The only problem I can imagine is importing *.as files by mistake into C++ only project, and vice versa (if someone is messy enough to mix them somehow).
Other than that it could be a quick hack solution for people looking for a good AngelScript IDE, so it does have value.

**Comment by eranif** [comment]
The docs mentions `*.hps` while you are talking about `*.as` is this a typo or both are valid file extensions for AngelScript?

**Comment by Enhex** [comment]
I didn't find any place in AngelScript's docs that describes a standard file extension, it's up to the users to choose.

**Comment by eranif** [comment]
But it there some kind of defacto standard? (also in C++, there is no *must* have extension, just standard)

**Comment by Enhex** [comment]
AngelScript's docs use `.as` in one place:
http://www.angelcode.com/angelscript/sdk/docs/manual/doc_hello_world.html

Why not let the user add extensions via the settings menu?

**Comment by eranif** [comment]
As a strategic decision, I am trying to reduce the number of configuration options. There are tons of them
I prefer to avoid it

**Comment by Enhex** [comment]
Completely removing configuration options makes the software less versatile, having them hidden virtually creates the same effect.

If the goal is simpler menus to make them easier to use, perhaps provide some sort of "advanced" checkbox to show options which are hidden by default?
Rarely used options should be hidden behind the advanced option, this way we hide usually unused options from cluttering the menus without removing them.
