### ISSUE TITLE
Option to disable block comment formatting

### ISSUE THREAD

**Issue by Enhex** [eranif/codelite#1544]
If I start a block comment line `/*` and press enter, it will automatically add ` * ` to the new line.
Please make this optional.

**Comment by hdastwb** [comment]
Have you tried Settings > Preferences > Tweaks > Code > Hitting <ENTER> in a C style comment automatically adds a '*' to the next line? Or are you missing that option?

**Comment by eranif** [comment]
What he said...

**Comment by Enhex** [comment]
Missed that option, thanks!
