### ISSUE TITLE
PHP: No autocomplete on namspaces in "use" section

### ISSUE THREAD

**Issue by sgchris** [eranif/codelite#1546]
There's no autocomplete for "use" under namespace declaration, but only when adding leading slash "\".
Example
```php
namespace Foo;
use Some\Namespace\.. // <--- no autocomplete here
use \Some\Namespace\.. // <--- here it works
```

Please make it available without the leading slash

**Comment by sgchris** [comment]
Any news here?

**Comment by eranif** [comment]
Greg, as you know, I am still on vacation :) Will look it when I will come back
