### ISSUE TITLE
CMake Error string sub-command STRIP requires two arguments.

### ISSUE THREAD

**Issue by qt1** [eranif/codelite#1547]
Trying this tutorial:
[http://codelite.org/LiteEditor/WxCrafterHelloWorld](http://codelite.org/LiteEditor/WxCrafterHelloWorld)

After creating the project, build says: 

> make: *** No targets specified and no makefile found.  Stop.

Run CMake fails with:

> CMake Error at dialogApp/CMakeLists.txt:29 (string):
>  string sub-command STRIP requires two arguments.

codelite version 10.0.0
cmake version 3.5.1
wxcrafter 2.7

**Comment by eranif** [comment]
Could you please post the generated workspace?
What happens when you select non-CMake build system? (Project Settings->General->Makefile Generator->Default)

**Comment by qt1** [comment]
The makfile option gives the following error:
wx-config: Command not found

please find attached the worksapce with CMake and makefile projects - as created by the wizard:

[wx1.zip](https://github.com/eranif/codelite/files/780616/wx1.zip)

**Comment by eranif** [comment]
Clearly this is a configuration error. You need to install wxWidgets properly
