### ISSUE TITLE
Windows: wxLogDebug: OutputDebugString: nothing printed in output pane

### ISSUE THREAD

**Issue by flederwiesel** [eranif/codelite#1550]
Hi,
for convenience, I would like to use the wxLogDebug() function to print to the CodeLite output pane. However, no output appears at all.
Building a simple application using MinGW with/without wxWidgets shows output in DbgView as well as under gdb. My impression is that CodeLite is not (properly) reading the message back from gdb in this case. Is this the expected (normal) behaviour? Am I doing something wrong?

Any more info needed?

Regards,
Tobias

**Comment by eranif** [comment]
> DbgView 

What is this view? I am not sure we have one named like this

> My impression is that CodeLite is not (properly) reading the message back from gdb in this case

CodeLite reads everything that GDB prints to the stdout/stderr

**Comment by flederwiesel** [comment]
Hi eranif,
Dbgview is a [Windows Sysinternals](https://technet.microsoft.com/en-us/sysinternals/debugview) tool showing messages coming from OutputDebugString.

If using OutputDebugString() - which is eventually called by wxLogDebug() - the message is visible in Dbgview as well as gdb ([one at a time](http://unixwiz.net/techtips/outputdebugstring.html#perms) - MS seems to have planned exclusive access here (?)).

A program a simple as this is able to printo to both:

```
$ cat wxLogDebug.cpp
#include <wx/wx.h>
#include <wx/log.h>

int main(int argc, char **argv)
{
        wxLogDebug("Hmm...\n");
        return 0;
}

$ make
g++ -o wxLogDebug.exe wxLogDebug.cpp -I C:\wxWidgets/lib/gcc_dll/mswu -I C:\wxWidgets/include -LC:\wxWidgets/lib/gcc_dll -lwxmsw31ud_core -lwxbase31ud -lkernel32 -luser32

$ gdb wxLogDebug.exe
GNU gdb (GDB) 7.8.1
Copyright (C) 2014 Free Software Foundation, Inc.
...
Reading symbols from wxLogDebug.exe...done.
(gdb) run
Starting program: e:\src\flederwiesel\codelite\wxLogDebug\wxLogDebug.exe
[New Thread 2428.0x1da0]
warning: Hmm...


[Inferior 1 (process 2428) exited normally]
(gdb) q

```

Running the same program under CL however does not print any message for me.

**Comment by eranif** [comment]
The `Output` tab will not capture and print messages printed via `OutputDebugString`
