### ISSUE TITLE
make file error

### ISSUE THREAD

**Issue by jayarayee** [eranif/codelite#1551]
/bin/sh -c '/usr/bin/make -j8 -e -f  Makefile'
----------Building project:[ bag - Debug ]----------
/usr/lib/libcmph.dylib: /usr/lib/libcmph.dylib: cannot execute binary file
make[1]: *** [Debug/main.cpp.o.d] Error 126
make: *** [All] Error 2
====1 errors, 0 warnings====

**Comment by eranif** [comment]
What are you trying to do here? Version of CodeLite, OS, etc
Steps to reproduce... please take the effort to open a proper bug report or don't open at all

**Comment by jayarayee** [comment]
I'm trying to run my code on OS
i think the project couldn't build
instead this massage showed up in my console.
/bin/sh -c '/usr/bin/make -j8 -e -f Makefile'
----------Building project:[ bag - Debug ]----------
/usr/lib/libcmph.dylib: /usr/lib/libcmph.dylib: cannot execute binary file
make[1]: *** [Debug/main.cpp.o.d] Error 126
make: *** [All] Error 2
====1 errors, 0 warnings====

**Comment by eranif** [comment]
This is not a bug. You configured something wrong on your project, please post all the details (CodeLite version, Which OS, and **exact** steps to reproduce) on the forum and not here.
