### ISSUE TITLE
External tools are out of order in the toolbar

### ISSUE THREAD

**Issue by Espyo** [eranif/codelite#1553]
If one sets up the external tools in the order they want, there is a chance that the toolbar will display the buttons out of order. For example, creating the tools "A", "B", "C", "D", and "E", in that order, might make the toolbar show the icons in the order "Configure external tools...", "Show Running Tools...", "C", "B", "A", "D", "E" (the first two are correct, naturally).

This can happen even if the user adds them to the list of tools in order, and makes sure that the external tool ID (external_tool_0, external_tool_1, etc.) matches the order. Once Codelite decides on an order to set the buttons in, it will stay that way until the tools are all deleted and re-created, where it might arrange them randomly in a different order.

I've checked the Codelite settings folder to see if anything was amiss, but the only thing I could find was in .codelite/config/codelite.xml, where I once again confirmed that every tool was declared in order.

Codelite versions tested: 9.2.0, 10.0.0.

**Comment by eranif** [comment]
I am unable to reproduce this. Whatever I do, my tools are in the correct order...
Which OS are you using?

**Comment by Espyo** [comment]
I'm currently running Codelite 10.0.0 on a Lubuntu 16.04.2 64-bit machine, where the problem still occurs.

I also tried messing with the tools under Codelite 9.2.0, on a Ubuntu 14.04 32-bit laptop, and in that case, they always came out in the opposite order ("E", D", "C", "B", "A").

**Comment by eranif** [comment]
This is what I see, it is not random, but reversed order (with CodeLite / HEAD)

**Comment by eranif** [comment]
Fixed
