### ISSUE TITLE
G+/Facebook/Twitter links

### ISSUE THREAD

**Issue by silvioprog** [eranif/codelite#1561]
Hello masters,

Thanks for this awesome IDE! I'm a CLion user, but CodeLite impressed me a lot and I'm planning to use it to develop my open source C projects.

So, I want to share it in social networks, however I can't find a G+/Facebook/Twitter link, could you add it to the CodeLite home page? :-)

Thank you!

**Comment by eranif** [comment]
Hi,
We don't have an offical facebook / G+ or Twitter account for CodeLite IDE.
You can mention us by adding the `#codeliteide` in your twitter + useful link(s) ... Thanks
