### ISSUE TITLE
CurrentFileName or CurrentFileFullName macro doesn't expand in output file

### ISSUE THREAD

**Issue by michelesalvador** [eranif/codelite#1562]
Codelite 10.0.2
Windows 10

I have a simple project with only one file called _main.c_.
In Project Settings > General > Output File I write `$(IntermediateDirectory)/$(CurrentFileName)`.
After building the project, the output file in _Debug_ folder is named "**_.exe_**" instead of "**_main.exe_**" as expected.
The same with the macro `$(IntermediateDirectory)/$(CurrentFileFullName)`.

**Comment by eranif** [comment]
> In Project Settings > General > Output File I write $(IntermediateDirectory)/$(CurrentFileName).

There is no sense in using this macro on that field.
Which file should CodeLite use? if the user has 100 files, which one should it pick?

You should only use "Project/Workspace" macros (output folder, project name, workspace name etc)
