### ISSUE TITLE
Minor commenting bug

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1563]
Selecting two lines of code with shift-down and then hitting shift-'/' also comments/uncomments out the line below the two lines selected.

Ver 10.02-10.04 x64, non-self-compiled, Win7 Sp1

**Comment by mattreecebentley** [comment]
ps. Did not occur with versions prior to 10. Maybe a side effect of the resolution of this bug? : https://github.com/eranif/codelite/issues/1419

**Comment by mattreecebentley** [comment]
This has actually become my no. 1 issue at present - I have to adjust my  thinking to accomodate the fact that codelite won't comment/uncomment my code the way it indicates it will.

**Comment by bergfi** [comment]
I too am having this issue in version 10.0.4, Arch Linux. Like mattreecebentley, it is also my number one issue as it is quite annoying to keep this in mind.

**Comment by bergfi** [comment]
Having a look at the diff (a8f30e74e1edbf1aa730fac6aba4e41c8e517cbd), it seems this part might be what provided that logic, but I am not quite familiar with all functions:
```c++
    if(LineFromPosition(PositionBefore(end)) != LineFromPosition(end)) {
        end = wxMax(start, PositionBefore(end));
    }
```

**Comment by mattreecebentley** [comment]
Still unfixed 10.05

**Comment by bergfi** [comment]
Thanks! That fixed it for me.
