### ISSUE TITLE
Pre & Post build options not considered in CMake

### ISSUE THREAD

**Issue by srini2174** [eranif/codelite#1565]
Steps to Reproduce
1) Create a New Workspace Named "BugReportWS"
2) Create a New Project Named "mylibrary" with CMake Build System Option
3) Create a New Class named "helloCls" using the "New Class" contextual menu
4) Select "Settings" from the project contextual menu.
5) Select the "Post build" menu item in the settings dialog
6) Set the following commands to run in the post build stage
    cd $(WorkspacePath)/cmake-build-$(ConfigurationName)/$(ProjectName) && mingw32-make -j4 SHELL=cmd.exe -e install
7) Select "Run CMake" from the project contextual menu (Configuration should complete without error)
8) Select "Build" from the project contextual menu.  The library is built but the post build command which installs it in the right place is never called

**Comment by eranif** [comment]
Note, that `CMake` has no way of adding a real **pre-build** commands (the **pre-build** is actually a **pre-link**). but the **post** build commands are working as intended. 

See this https://cmake.org/pipermail/cmake/2004-April/004979.html
Its an old thread, but the problem remains even with the latest `CMake`
