### ISSUE TITLE
No way available to install a target using CMake Build System 

### ISSUE THREAD

**Issue by srini2174** [eranif/codelite#1566]
1) Create a New Workspace Named "SimpletestWS
    2) Create a New Project Named "mylibrary" with CMake Build System Option
    3) Delete the default "include" and "src" virtual folders
    4) Create 2 New Virtual Folders named "include" & "src" with the option to "Create folders on file system" enabled
    3) Create a New Class named "helloCls" using the "New Class" contextual menu
    4) Create a config.hpp.in with the content below
         #define MYLIBRARY_MAJOR_VERSION (@MYLIBRARY_MAJOR_VERSION@)
         #define MYLIBRARY_MINOR_VERSION (@MYLIBRARY_MINOR_VERSION@)
         #define MYLIBARY_VERSION_STRING "@MYLIBRARY_VERSION@"
    5) Create CMakeLists.txt in the project folder with the contents in the attached file
[CMakeLists.txt](https://github.com/eranif/codelite/files/801758/CMakeLists.txt)
    6)Select "Run CMake" from the project contextual menu (Configuration should complete without error)
    7)Select "Build" from the project contextual menu. The library is built.
    8)Now I want to install the targets.  There is no option to install all the targets.

If I create a custom build target with install option the next time I run CMake all the contents of the CMakeLists.txt is wiped out.  I loose all the customization I have done in the CMakeLists.txt file

**Comment by eranif** [comment]
The solution is probably to collect all the "CMake" related items in the project context menu to a single sub menu named "CMake" which will include:

- Run CMake
- Open CMakeLists.txt
- Export CMakeLists.txt
- Install

**Comment by srini2174** [comment]
How to call other targets if any?  There should be some way to query the targets generated by CMake and add them if required.  It would be good to group the targets like Build, Clean, Install etc. and other CMake comments like Run CMake, Open CMakeLists.txt, Export CMakeLists.txt etc.,
