### ISSUE TITLE
Check for new updates has no option to disable weekly builds

### ISSUE THREAD

**Issue by styles784** [eranif/codelite#1571]
I would love to be notified of new versions of CodeLite, but do not have any interest in the weekly builds - it is annoying to be told that there is a new version every time I start the program, only to discover after loading the website that the new version is not a major stable build. There should be an option to opt out of weekly builds, or at the very least the notification should indicate whether the new version it found is a weekly (the former is preferred - I still don't want to have to say no every time I start the program, but at least with the latter suggestion I would know before opening my browser)

**Comment by eranif** [comment]
There is a new option. If you install a weekly build you will have it ;) 
It was fixed in 10.0.2 

https://github.com/eranif/codelite/issues/1533

**Comment by megapro17** [comment]
Why it isn't enabled by default in stable releases?

**Comment by indeed-a-genius** [comment]
I'm running 12.0 stable and getting info about a new version available. So looks like it detects a new weekly version.
Where is this option to check only for stable releases located?

**Comment by eranif** [comment]
Settings->Preferences->Misc->General tab
