### ISSUE TITLE
Delete word (C-BS) is applied only on the last occurrence in multiple selection

### ISSUE THREAD

**Issue by sgchris** [eranif/codelite#1573]
When selecting several similar words/phrases (Ctrl-K), and hitting Ctrl-BSpace (delete word), it's applied on the last occurrence only.

I'm not sure whether it's general behavior or only my machine's (ubuntu 16.04), but the cursor on the last occurrence is situated at the beginning of the last word, and not at the end, as expected. Therefore, Ctrl-BSpace deletes what comes before the last occurrence.

**Comment by eranif** [comment]
This will be fixed once wxWidgets will release a newer version with a Scintilla version higher than 3.5.5 (next release of wxWidgets)
