### ISSUE TITLE
No completion list when the type is given in the parameter type-hint

### ISSUE THREAD

**Issue by sgchris** [eranif/codelite#1574]
```php
	public function foo(\PDO $p) {
		$p-> // <------ no completion here!
	}
```

**Comment by sgchris** [comment]
Please note that the type-hint can be only the partial name, where the full name is defined in the "use" clause. example:
```php
namespace MyNS;

use \MyOther\NSpace\Foo;

// ...

function barbaz(Foo $f) {
    $f-> // <------- you should be aware of the full $f's namespace
}
```

**Comment by surafel911** [comment]
Make sure to save all files you're working with when starting to work on new functions/classes and have everything you need included. I heard that CodeLite parses the workspace when you save.

**Comment by pattisahusiwa** [comment]
If you didn't add phpdoc comment to the function, then this issue is related to #1708.
