### ISSUE TITLE
Crash in clJSCTagsZipJob::Process

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#1577]
Hi Eran,

using the latest git head (a2ac34d9d0) on Linux (GTK3), I get a crash in clJSCTagsZipJob::Process.
The zip is extracted just fine, but apparently the CallAfter causes this crash.

Best regards,
  René

**Comment by eranif** [comment]
Can you please try the latest master?

**Comment by upCASE** [comment]
Doesn't crash so far!

I noticed that it was a bit lagging when I changed editor tabs the first time, but that might just be me hallucinating...
Thanks, I suppose this is solved then.
