### ISSUE TITLE
SVN integration fails on commit if special characters are present in comment

### ISSUE THREAD

**Issue by Kanimies** [eranif/codelite#1583]
Message in commit: käkkönen

svn: E000022: Commit failed (details follow):
svn: E000022: Error normalizing log message to internal format
svn: E000022: Can't convert string from native encoding to 'UTF-8':
svn: E000022: kakkonen

Works from OS X command line - does the program use a more restricted character set internally or why would the commit fail when done via Codelite?

**Comment by Kanimies** [comment]
From command line, same command (

 svn --config-dir "/Users/xxx/Library/Application Support/codelite/subversion" commit yyy.php  -m "käkkönen"
Sending        yyy.php
Transmitting file data .done
Committing transaction...
Committed revision 21.

**Comment by tommeschberlin** [comment]
can be solved by choosing the right encoding in Settings/Preferences/Misc/Encoding Locale.
I choosed UTF-8 x-enable localization de_DE:German and it was solved for me.

**Comment by Kanimies** [comment]
Didn't fix for me
<img width="594" alt="settings" src="https://cloud.githubusercontent.com/assets/7421922/23955047/780449f6-09a1-11e7-8fe5-8b43c45ce7ec.png">
<img width="394" alt="error" src="https://cloud.githubusercontent.com/assets/7421922/23955052/7b837dea-09a1-11e7-9c97-dc1210e3dba3.png">

**Comment by eranif** [comment]
I changed it so now the commit message is first written to a file and then passed to SVN command line.
Should be fixed now
