### ISSUE TITLE
PHP closing tag is not inline recognized in mixed (HTML/PHP) mode

### ISSUE THREAD

**Issue by sgchris** [eranif/codelite#1584]
![image](https://cloud.githubusercontent.com/assets/475849/23590228/d4cbdc0e-01e4-11e7-9a64-7b7eb9b92dad.png)

The error sign disappears only after refreshing the buffer (C-R)

reproduce: 
type:
```php 
<?php echo 'something'; 
```
at this point, hit save - the error sign appears, which is fine, but when adding:
```php 
?> 
```
the error sign remains until the next buffer refresh

**Comment by AJenbo** [comment]
The issue happens when the caret is out side of a php section as you saving the file. I have submitted a fix for it, so hopefully this will be solved in the next version.
