### ISSUE TITLE
clang-format header sorting inconsistent

### ISSUE THREAD

**Issue by sebholt** [eranif/codelite#1586]
When using _clang-format_ from the _Source Code Formatter_ the _own_ header of the source file is not put on top but rather placed in the alphabetical order.

Consider a file `b.cpp` with the following content
```
// b.cpp
#include "b.hpp"
#include "a.hpp"
...
```
After _clang-format_ in _codelite_ it becomes
```
// b.cpp
#include "a.hpp"
#include "b.hpp"
...
```
which differs from the result of `clang-format -i b.cpp` which would leave `b.hpp` at the top.

Besides this the `clang-format` plugin is a great tool!

**Comment by eranif** [comment]
I doubt that there is anything we can do about this.
CodeLite passes all the arguments to `clang-format` as described by the settings dialog. Maybe it's one of the settings that does that. If you fail to find such file, you can use `Plugins->Source Code Formatter->C++->clang-format->Style->File` option.

This option tells `clang-format` to read the settings from your `.clang-format` file

**Comment by sebholt** [comment]
Am 08.03.2017 um 15:47 schrieb Eran Ifrah:
> I doubt that there is anything we can do about this.
> CodeLite passes all the arguments to |clang-format| as described by the
> settings dialog. Maybe it's one of the settings that does that. If you
> fail to find such file, you can use |Plugins->Source Code
> Formatter->C++->clang-format->Style->File| option.

I don't think this is an option issue, (I'm using the File setting btw.)
but rather the fact that clang-format in codelite formats anonymous raw
data or a temporary randomly named file.
Therefore it doesn't known that it actually works on b.cpp and that
b.hpp is the *own* header that should be on top.

Fix suggestions:
- Use clangs "-assume-filename" option
- Or name a potential temporary file exactly like the source file


-- 
Sebastian Holtermann

**Comment by eranif** [comment]
Thanks for clar

**Comment by sebholt** [comment]
Great, thanks!

**Comment by AJenbo** [comment]
My refactoring has reintroduced this issue. I will make sure to fix it with in the next few dayes.
