### ISSUE TITLE
warning: GDB: Failed to set controlling terminal: Operation not permitted

### ISSUE THREAD

**Issue by computersarecool** [eranif/codelite#1587]
Hello, I just downloaded Codelite version 10.0.3 for Linux.  I am currently using Ubuntu 16.04
I am trying just a simple "hello world", using iostream to cout and the console

```
#include <iostream>

int main(int argc, char** argv)
{
    std::cout << "Test" << std::endl;
    return 0;
}
```
When I run it the console window immediately shuts down but I can see that it has printed:

"warning: GDB: Failed to set controlling terminal: Operation not permitted"
followed by "Test"

This happens when I toggle using codelite's built in editor nor not.
No difference.  Any idea on how to fix this?

**Comment by eranif** [comment]
This error message is harmless and can be ignored.
If the terminal does not "pause" when your code terminate, you can enable this from Project Settings->General->Pause when execution ends

**Comment by computersarecool** [comment]
Ah right, so that is the frustrating behavior. The terminal immediately closes even _when_ that checkbox is ticked.

I noticed that this started happening when I added `return 0` to the code.  (Initially the console window was pausing after completion).

Once or twice toggling the "pause" flag, hitting "apply" and then un-toggling it again helped, but now it seems stuck with or without `return 0`.

This is my first time using this editor ever. Really hoping to get it working.

**Comment by eranif** [comment]
Which terminal is used? Not all terminals behaves the same...
CodeLite uses `x-terminal-emulator` as the terminal (you can view the script `/usr/bin/codelite_xterm`)

I recommend using `xterm` to get a proper working terminal

**Comment by computersarecool** [comment]
Currently I have `Use CodeLite's built-in terminal emulator checked`

I am using ubuntu's default "terminal" app
I just updated the path to `usr/bin/xterm` but I get the same bad behaviro.
I saw that (When the console's were staying open) the console that appeared briefly was still "terminal" (in other words it looks like that path is not being used?)

Also a strange gray window that says "Debug" appears in the bottom right hand corner? Do you know if this could be related?

I really appreciate the help.

**Comment by eranif** [comment]
To configure different temrinal, you do it from Ubuntu's terminal, like this:
`sudo update-alternatives --config x-terminal-emulator`

> Also a strange gray window that says "Debug" appears in the bottom right hand corner? Do you know if 
> this could be related?

Maybe post a screenshot?

**Comment by eranif** [comment]
This is a configuration issue. Please use the forum for future discussion on this topic

**Comment by NewMKE** [comment]
Hi computersarecool,
I don't know if you have fixed this problem already? Because I have the same issue. Do you mind telling me how to fix it? Thank you so much!

**Comment by mecchmatProjects** [comment]
Please, someone fix this already. Does someone makes Codelight debug working on LInux?

**Comment by eranif** [comment]
@mecchmatProjects please open a separate issue with the problem you are experiencing. using a 4.5 years old issue is not the way to go
