### ISSUE TITLE
[C++17] Editor prevents typing selection statement with initializer

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#1588]
As per [P0305 specification](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0305r1.html) "Selection statements with initializer" of C++17, the following code would be valid (latest versions of GCC and CLang):

`if (auto res = map.insert({"name", 25}); res.second)`

However, in CodeLite 10.0.0, when typing ";" inside IF's parenthesis, editor automatically jumps to the end of ")" parenthesis, so it is not possible to really type aforementioned code without using copy/paste to place ";" character between init and condition statements. Same issue applies to SWITCH statement.

Either the editor should have an option to "Enable C++17 Standard" in "Code Completion" portion of "Project Settings" and understand the syntax, or simply not jump to the end of parenthesis after encountering ";" symbol.

**Comment by AJenbo** [comment]
You can disable this behaviour by checking Settings->Settings->Editor->Guides->Disable semicolon shift
