### ISSUE TITLE
Macros like $(ProjectName) not replaced in Program Arguments

### ISSUE THREAD

**Issue by tomekjaworski** [eranif/codelite#1590]
Macro ProjectName (and probably others) are not recognized and replaced in Program Arguments.
Example: "--plugin=./plugins/$(ProjectName)-Debug" gives $(ProgramName) in program's arguments after execution.

**Comment by eranif** [comment]
Which CodeLite are you using? I just tested this and it works.
Also, what kind of workspace (C/C++, JavaScript or PHP)

**Comment by eranif** [comment]
Closed, due to inactivity
