### ISSUE TITLE
Distinguishing enabled projects in workspace window

### ISSUE THREAD

**Issue by tomekjaworski** [eranif/codelite#1593]
Hi,
It would be useful to display the project name in Workspace tree in some other color when project is disabled.
Best regards,
TJ

**Comment by eranif** [comment]
Closed by mistake (wrong URL passed to the commit message)

**Comment by eranif** [comment]
When a project is active, it is marked with bold font.
I can set the active project to _**bold italic**_ - thats the best I can do
