### ISSUE TITLE
C++ local variables not coloured correctly when comma-declared

### ISSUE THREAD

**Issue by Paul17041993** [eranif/codelite#1594]
For example; "int iA = 0, iB = 0;", iA will be coloured correctly as a local variable, but iB will not.

Solution; check for a comma where you would a type and jump to the start of the line (ie before the last semicolon or bracket) and check for a type there.

**Comment by eranif** [comment]
Which version of CodeLite? 

This is working fine here:
![screenshot from 2017-04-13 16 02 06](https://cloud.githubusercontent.com/assets/3677711/25005674/88045292-2062-11e7-81b4-45b173974713.png)

**Comment by Paul17041993** [comment]
10.0, the same as on the site.

And why are you so trigger-happy with the close button...?

**Comment by eranif** [comment]
> And why are you so trigger-happy with the close button...?

Usually, these kind of bugs if they won't happen to me (using the reproduction steps you provide) they won't be fixed (unless you plan on sending a patch)
It's just from experience, if I don't fix this, no one will, so I don't see the point of having a bug opened which I can't reproduce, i.e. I can't fix

**Comment by Paul17041993** [comment]
Then use a label, that's what they're for...
