### ISSUE TITLE
Re-compile IDE with Qt (WxQt) enabled?

### ISSUE THREAD

**Issue by Paul17041993** [eranif/codelite#1597]
So the gui works properly in non-GTK platforms, it currently uses GTK2 and is very problematic, especially with dark themes.

[WxQt](https://wiki.wxwidgets.org/WxQt) (for convenience)
Nothing bleedingly obvious that there may be problems with...

**Comment by eranif** [comment]
wxQT is not stable and I don't see this happening in the near future
