### ISSUE TITLE
Please fix CodeLite on Windows XP

### ISSUE THREAD

**Issue by palikacska** [eranif/codelite#1599]
I have downloaded the latest CodeLite 10.0 to give it a try and see what's new. Got this.

![errpr](http://i2.imgbus.com/doimg/5cdo7m9m7o0nfa9.PNG)

OS: Windows XP x64 edition with all updates installed until 2014.

This is caused by CodeLite being compiled against a newer runtime library (VCRT) or Windows API. In Visual Studio you can target older versions of the API so that it could work on Windows XP as well.

**Comment by eranif** [comment]
Sorry, we dont support Windows XP. Nor I have access to such a machine

**Comment by palikacska** [comment]
If I try to build CodeLite using the necessary tools and test environments, and if there are changes to be made either to the codebase or to the build tools, would you merge those changes if I create a pull request?

**Comment by eranif** [comment]
Yes, as long it does not break the WIn10/7 builds
