### ISSUE TITLE
autocomplete list hides if typing wrong and does'nt come back if correct the wrong char

### ISSUE THREAD

**Issue by tommeschberlin** [eranif/codelite#1600]
Autocomplete starts after typing 3 characters for default, this works as expected.
For instance, typing "rec" gets a list of {recv,recvfrom,...} to select from,
but if one types the 4th character wrong e.g. "recc" the list went off and does'nt come back if the last "c" was deleted. If one has typed a long word and one character goes wrong you have to guess the rest or start typing again, this is really annoying for me.

**Comment by eranif** [comment]
You can simply hit Ctrl+SAPCE and it will re-appear
