### ISSUE TITLE
Codelite fails to load with libclang version 3.9.1 installed

### ISSUE THREAD

**Issue by capSAR273** [eranif/codelite#1602]
Output from term: `codelite: error while loading shared libraries: libclang.so.3.8: cannot open shared object file: No such file or directory
`

I'm running Fedora 25, and codelite recently broke for me, most likely because codelite requires clang 3.8.0 and it recently updated to 3.9.1. This is just an assumption, I can probably downgrade clang but I don't want to break things further. Would this be a simple change to dependencies to allow the newer version of clang? Apologies if this is a simple fix, only one previous issue #1273 referenced the clang library but was a slightly different problem.

**Comment by dghart** [comment]
Hi,

Thank you for reporting this. As you say, fedora updated libclang to 3.9 and removed the 3.8 libs, so breaking any binaries that link to the 3.8 ones. It would never happen in debian...

I've rebuilt and uploaded the CodeLite rpms and updated the links on http://codelite.org/LiteEditor/Repositories#toc3

Regards,

David
