### ISSUE TITLE
AutoComplete missing Typedef and Using symbols

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#1604]
I'm using CodeLite 10.0.0 with "Enable C++11 Standard" and "Enable C++14 Standard" checkboxes enabled in Code Completion dialog of the Project Settings. 

Please consider the following example:

```
#include <memory>

struct TestStruct
{
  int value1;
  int value2;
};

using TestStructPtr = std::unique_ptr<TestStruct>;
typedef  std::unique_ptr<TestStruct> TestStructPtr2;
using SomeStructPtr = TestStruct*;

void testFunc()
{
  TestStructPtr a;
  TestStructPtr2 b;
  SomeStructPtr c;
  std::unique_ptr<TestStruct> d;
  TestStruct* e;

  // a->   autocomplete doesn't work
  // b->   autocomplete doesn't work
  // c->   autocomplete doesn't work
  // d->   autocomplete works
  // e->   autocomplete works
}
```
In aforementioned examples, as long as the data type is using an alias either through "typedef" or "using", autocomplete won't recognize it. However, if you declare the variable type directly as in case of last two test cases, autocomplete works.

Note that checking "Enable clang code completion" enables autocompletion of the aforementioned statements, but since it intermittently crashes CodeLite 10 without notice while typing (couldn't figure out exact steps to reproduce that, so can't report it), it would be great if CodeLite could understand these language constructs natively.

**Comment by eranif** [comment]
Without clang enabled, CodeLite understand `b` `d` and `e`
In other words, it does not understand aliasing via `using` 

(just tested the above code and it fails with `using` and works elsewhere)

**Comment by yunkot** [comment]
Thanks, but are you saying that "typedef" aliased autocomplete works? Because in CodeLite 10.0.0 the option "b" doesn't seem to show autocomplete window.
