### ISSUE TITLE
Bug: ZoomNavigator eats too many CPU at 10.0.0

### ISSUE THREAD

**Issue by eitijupaenoithoowohd** [eranif/codelite#1605]
ZoomNavigator is mandatory, useful and very suitable feature but it uses too many CPU all the time (more than 40%). Could you please fix this bug. This bug can be reproduced  with file size more than 3-5 pages. Ubuntu 16.04 package of CodeLite 10.0.0 from official repository "https://repos.codelite.org/ubuntu/ xenial universe" Thanks in advance.

**Comment by eranif** [comment]
Fixed, thanks for reporting this

**Comment by eitijupaenoithoowohd** [comment]
Thank you very much.
