### ISSUE TITLE
git plugins lower left window doesn't apply background colour from "Settings->Colours and Fonts..."

### ISSUE THREAD

**Issue by Mutantpenguin** [eranif/codelite#1606]
But the foreground colour gets applied. So if you select a black background and white foreground colour, you get white text on white background.
![bildschirmfoto von 2017-03-21 22-57-39](https://cloud.githubusercontent.com/assets/9027507/24172805/e63d7176-0e89-11e7-8096-40e3c03c8c07.png)

The lower right window uses both foreground and background colour correctly.

**Comment by eranif** [comment]
I am afraid that this is a bug in wxWidgets.
On Windows it works as expected but not on Linux / OSX (where native controls are being used, while on Windows the generic version is used)

It will be need to be fixed in the wxWidgets library, not in CodeLite (the control is wxDataViewCtrl)

**Comment by Mutantpenguin** [comment]
Thanks for the info. Seems as if the next release might get a fix for this:
https://github.com/wxWidgets/wxWidgets/commit/1bbc44daff4ee823e4fe385c46c5eba269617c17
