### ISSUE TITLE
Feature Request: tab switching using the mouse scroll wheel does not work at 10.0.0

### ISSUE THREAD

**Issue by eitijupaenoithoowohd** [eranif/codelite#1607]
Tab switching using the mouse scroll wheel does not work. Ubuntu 16.04 package of CodeLite 10.0.0 from official repository "https://repos.codelite.org/ubuntu/ xenial universe". I'm sure that feature have been worked at CodeLite 6.1 perfectly.

**Comment by eranif** [comment]
I have updated this to feature request since this is not really a bug. This is a nice to have feature, but not a bug

**Comment by eitijupaenoithoowohd** [comment]
Thank you very much. It should be very useful feature.
