### ISSUE TITLE
Replacing string with the same string is stuck in an endless loop

### ISSUE THREAD

**Issue by sebholt** [eranif/codelite#1609]
When replacing a string _FOO_ in a file with the same string _FOO_, the replace tool seems to be stuck in an endless loop.

**Comment by eranif** [comment]
Which version of CodeLite? Which OS? please be specific

**Comment by eranif** [comment]
I will assume that you are using 10.0 or lower version of CodeLite
This bug was already reported and fixed, you can download and try the latest CodeLite.

For reference, here is the original bug report:
https://github.com/eranif/codelite/issues/1526
