### ISSUE TITLE
showing all targets for sub-projects in cmake builds

### ISSUE THREAD

**Issue by gabyx** [eranif/codelite#1610]
Would it be possible to have windows which lists every target generated in a cmake build?
also multiple targets in a project (cmake command PROJECT(...))?

Thanks alot for the awesome project!

**Comment by eranif** [comment]
CodeLite does not parse CMake output file. Patches are most welcome

**Comment by gabyx** [comment]
Ok, will see if i have time to look into this, do you have some hints to get started?

Von meinem iPhone gesendet
