### ISSUE TITLE
Request: Remove `nodejs` apt dependency

### ISSUE THREAD

**Issue by daemonburrito** [eranif/codelite#1611]
This may be the wrong forum, if there is somewhere else dedicated to packaging, but the dependency on `nodejs` in the package causes pain (see older github issues).

Basically nobody uses Ubuntu's official node package, and perhaps most people who hack with nodejs a lot have some environment-switching solution; e.g., bash scripts and a separate home tree or an out-of-the-box solution like [nvm](https://github.com/creationix/nvm).

There's more than one way to address this, and I'm not proposing one since I just found this project and know nothing about it, but it would be super nice if it didn't pull down `nodejs` (put it in recommends?)

**Comment by daemonburrito** [comment]
Nevermind... just realized that it's a dependency of `codelite-plugins`.

**Comment by eranif** [comment]
FYI: `codelite-plugins` this means that you are using the official ubuntu package not the one that we provide from https://codelite.org

**Comment by daemonburrito** [comment]
Sorry, I could have been clearer about that, but it does bring up the fact that codelite.org `codelite` package also depends on `nodejs`.

I went ahead and installed it, and found that the Ubuntu `nodejs` install doesn't break nvm, so it's not much of an issue for me now.
