### ISSUE TITLE
Make status bar  more useful

### ISSUE THREAD

**Issue by zufuliu** [eranif/codelite#1612]
currently the status bar shows Ln, Pos, Len
where 
Ln: current line number
Pos: current position in the document, 
Len: current length (in bytes) of the document

however if we change the format to Ln/LnCount Col/ColCount Ch/ChCount Len
where
Ln: current line number
LnCount: line count for the document
Col: current column in current line
ColCount: total column for current line
Ch: current character index in current line
ChCount: current character count for current line
Len: current length (in bytes or KB or MB ) of the document

it will be more useful, especially when to locate error and warning produced by build tool.

Here are some code snippets for  void LEditor::OnSciUpdateUI(wxStyledTextEvent& event) in LiteEditor/cl_editor.cpp :
``` cpp
static wxString FormatSize(int value) {
    if (value >= 1024*1024) {
        return wxString::Format(wxT("%.2f MB"), ((double)value) / (1024*1024));
    }
    if (value >= 1024) {
        return wxString::Format(wxT("%.2f KB"), ((double)value) / 1024);
    }
    return wxString::Format(wxT("%d B"), value);
}

void LEditor::OnSciUpdateUI(wxStyledTextEvent& event)
{
    int curPos = GetCurrentPosition();                      // current position
    int curLine = LineFromPosition(curPos);                 // current line number
    int totalLine = GetLineCount();                         // total line count
    int lineStart = PositionFromLine(curLine);              // start position for current line
    int lineEnd = GetLineEndPosition(curLine);              // end position for current line
    int colIndex = GetColumn(curPos) + 1;                   // column index in current line
    int colCount = GetColumn(lineEnd);                      // total column for current line
    int chIndex = CountCharacters(lineStart, curPos) + 1;   // character index in current line
    int chCount = CountCharacters(lineStart, lineEnd);      // total character for current line

    // update line number and position
    wxString message;

    message << wxT("Ln ") << curLine + 1 << "/" << totalLine << " Col " << colIndex << "/" << colCount << " Ch " << chIndex << "/" << chCount << " " << FormatSize(GetLength());

    // Always update the status bar with event, calling it directly causes performance degredation
    m_mgr->GetStatusBar()->SetLinePosColumn(message);
}
```

**Comment by eranif** [comment]
There is one problem with this: the status bar is not big enough to contain all these information

**Comment by zufuliu** [comment]
maybe we can omit `colCount` and `chCount` like Visual Studio 2015, so it will fill.

**Comment by dghart** [comment]
Hi,

I missed Col too, though not the others. So I've now:
1) Reimplemented Col (it used to be shown until a few months ago)
2) Let the user choose which of the 4 items are displayed. You can set this in Settings > Preferences > Misc: Status Bar.

I won't be adding the others on your list, but maybe eranif will choose to do so...

Regards,

David
