### ISSUE TITLE
Provide individual colour options for each individual symbol

### ISSUE THREAD

**Issue by Paul17041993** [eranif/codelite#1613]
Provide individual colour options for each individual symbol, instead of colouring them all the same.

https://github.com/eranif/codelite/issues/1595
https://github.com/eranif/codelite/issues/1596

**Comment by Paul17041993** [comment]
Apparently there isn't even a colour option for these at all, it's just a hard-coded algae green that cannot be customised...?

**Comment by eranif** [comment]
Everything that can be coloured is configurable. Instead of opening issues, please use the forum to start a discussion with examples of what you want. All your reports are rather "short" and do not contains steps to reproduce the behaviour you want to achieve
