### ISSUE TITLE
Some Unicode characters become corrupted when loading and saving file

### ISSUE THREAD

**Issue by milasudril** [eranif/codelite#1615]
Version: 10.0.0 (Installed from unofficial CodeLite repo. Version 9 is also affected by this bug.
OS: Xubuntu 16.04

Input file:

 ```C++
//@	{
//@	 "targets":[{"name":"vgacell.o","type":"object"}]
//@	}

#include "vgacell.hpp"

using namespace Glinde;

static const char32_t* codepoints=
	U"\0☺☻♥♦♣♠•◘○◙♂♀𝅘𝅥𝅯♬☼"
	 U"►◄↕‼¶§▬↨↑↓→←∟↔▲▼"
	U" !\"#$%&'()*+,-./"
	 U"0123456789:;<=>?"
	 U"@ABCDEFGHIJKLMNO"
	 U"PQRSTUVWXYZ[\\]^_"
	 U"`abcdefghijklmno"
	 U"pqrstuvwxyz{|}~⌂"
	 U"ÇüéâäàåçêëèïîìÄÅ"
	 U"ÉæÆôöòûùÿÖÜ¢£¥₧ƒ"
	 U"áíóúñÑªº¿⌐¬½¼¡«»"
	 U"░▒▓│┤╡╢╖╕╣║╗╝╜╛┐"
	 U"└┴┬├─┼╞╟╚╔╩╦╠═╬╧"
	 U"╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀"
	 U"αßΓπΣσµτΦΘΩδ∞φε∩"
	 U"≡±≥≤⌠⌡÷≈°∙·√ⁿ²■\0xa0";

uint32_t VGACell::codepoint() const noexcept
	{
	return codepoints[m_ch];
	}
```

File content after saving

```C++
...
       U"\0☺☻♥♦♣♠•◘○◙♂♀������٬☼"
```

The bad guy is 𝅘𝅥𝅯   U+1D161, "Musical symbol sixteenth node". This symbol is not in BMP, maybe that is the problem.

**Comment by eranif** [comment]
It seems as if wxSctinilla is unable to handle this text and it crashes... (in debug mode)
I am going to test the stc sample of wxWidgets and see if also happens there, if it does I will close this bug and pass it on to the wxWidgets team (CodeLite GUI framework)

**Comment by milasudril** [comment]
Notice that it works in QScintilla for Qt5. I also suspect wxScintilla, because when debuging CodeLite, I saw that it actually uses 32-bit codepoints. Therefore the symbol should fit in one codepoint word.
