### ISSUE TITLE
How to work?

### ISSUE THREAD

**Issue by mrkaban** [eranif/codelite#1616]
Generally I can not understand, and could not find the answer in the help system.

Here is a simple example of "Hello World", the compiler installed and it was detected after scanning. When you try to collect the next window and i
![1](https://cloud.githubusercontent.com/assets/14289360/24829867/7a569018-1ca4-11e7-8eb7-be2532856d77.jpg)
t's not clear what he needs from me.

**Comment by eranif** [comment]
Please follow this guide http://codelite.org/LiteEditor/QuickStart
