### ISSUE TITLE
Build from source fails for MinGW 64.

### ISSUE THREAD

**Issue by flederwiesel** [eranif/codelite#1618]
Building from git on a 64bit-MinGW machine, the build process for Debug fails as follows:

`"----------Building project:[ Cscope - Win_x64_Debug ]----------"
mingw32-make.exe[1]: Entering directory '/path/to/codelite/cscope'
...
C:/TDM-GCC-64/bin/g++.exe -shared -fPIC -o Win_x64_Debug/Cscope-dbg.dll @"Cscope.txt" -L. -L../lib/gcc_lib  -lplugin_sdkud -lCodeLiteud   -mthreads -LC:/wxWidgets/lib/gcc_dll -lwxmsw31ud_richtext -lwxmsw31ud_xrc -lwxmsw31ud_aui -lwxmsw31ud_html -lwxmsw31ud_adv -lwxmsw31ud_core -lwxbase31ud_xml -lwxbase31ud_net -lwxbase31ud -lwxscintillad -lwxtiffd -lwxjpegd -lwxpngd -lwxzlibd -lwxregexud -lwxexpatd -lkernel32 -luser32 -lgdi32 -lcomdlg32 -lwxregexud -lwinspool -lwinmm -lshell32 -lcomctl32 -lversion -lshlwapi -lole32 -loleaut32 -luuid -lrpcrt4 -ladvapi32 -lwsock32
Win_x64_Debug/cscopetab.cpp.o: In function `Clear':
/path/to/codelite/cscope/cscopetab.cpp:79: undefined reference to `__imp__ZN16wxStyledTextCtrl8ClearAllEv'
Win_x64_Debug/cscopetab.cpp.o: In function `BuildTable':
/path/to/codelite/cscope/cscopetab.cpp:113: undefined reference to `__imp__ZNK16wxStyledTextCtrl12GetLineCountEv'
Win_x64_Debug/cscopetab.cpp.o: In function `ClearText':
/path/to/codelite/cscope/cscopetab.cpp:201: undefined reference to `__imp__ZN16wxStyledTextCtrl8ClearAllEv'
Win_x64_Debug/cscopetab.cpp.o: In function `OnHotspotClicked':
/path/to/codelite/cscope/cscopetab.cpp:228: undefined reference to `__imp__ZN16wxStyledTextCtrl10ToggleFoldEi'
Win_x64_Debug/CscopeTabBase.cpp.o: In function `CscopeTabBase::CscopeTabBase(wxWindow*, int, wxPoint const&, wxSize const&, long)':
/path/to/codelite/cscope/CscopeTabBase.cpp:37: undefined reference to `__imp_wxSTCNameStr'
/path/to/codelite/cscope/CscopeTabBase.cpp:37: undefined reference to `__imp__ZN16wxStyledTextCtrlC1EP8wxWindowiRK7wxPointRK6wxSizelRK8wxString'
/path/to/codelite/cscope/CscopeTabBase.cpp:39: undefined reference to `__imp__ZN16wxStyledTextCtrl13SetMarginTypeEii'
/path/to/codelite/cscope/CscopeTabBase.cpp:40: undefined reference to `__imp__ZN16wxStyledTextCtrl13SetMarginMaskEii'
/path/to/codelite/cscope/CscopeTabBase.cpp:41: undefined reference to `__imp__ZN16wxStyledTextCtrl18SetMarginSensitiveEib'
/path/to/codelite/cscope/CscopeTabBase.cpp:42: undefined reference to `__imp__ZN16wxStyledTextCtrl14SetMarginWidthEii'
/path/to/codelite/cscope/CscopeTabBase.cpp:45: undefined reference to `__imp__ZN16wxStyledTextCtrl14SetMarginWidthEii'
/path/to/codelite/cscope/CscopeTabBase.cpp:48: undefined reference to `__imp__ZN16wxStyledTextCtrl13SetMarginTypeEii'
/path/to/codelite/cscope/CscopeTabBase.cpp:49: undefined reference to `__imp__ZN16wxStyledTextCtrl13SetMarginMaskEii'
/path/to/codelite/cscope/CscopeTabBase.cpp:50: undefined reference to `__imp__ZN16wxStyledTextCtrl14SetMarginWidthEii'
/path/to/codelite/cscope/CscopeTabBase.cpp:51: undefined reference to `__imp__ZN16wxStyledTextCtrl18SetMarginSensitiveEib'
/path/to/codelite/cscope/CscopeTabBase.cpp:54: undefined reference to `__imp__ZN16wxStyledTextCtrl13SetMarginTypeEii'
/path/to/codelite/cscope/CscopeTabBase.cpp:55: undefined reference to `__imp__ZN16wxStyledTextCtrl14SetMarginWidthEii'
/path/to/codelite/cscope/CscopeTabBase.cpp:58: undefined reference to `__imp__ZN16wxStyledTextCtrl13SetMarginTypeEii'
/path/to/codelite/cscope/CscopeTabBase.cpp:59: undefined reference to `__imp__ZN16wxStyledTextCtrl13SetMarginMaskEii'
/path/to/codelite/cscope/CscopeTabBase.cpp:60: undefined reference to `__imp__ZN16wxStyledTextCtrl14SetMarginWidthEii'
/path/to/codelite/cscope/CscopeTabBase.cpp:62: undefined reference to `__imp__ZN16wxStyledTextCtrl8SetLexerEi'
/path/to/codelite/cscope/CscopeTabBase.cpp:64: undefined reference to `__imp__ZN16wxStyledTextCtrl13StyleClearAllEv'
/path/to/codelite/cscope/CscopeTabBase.cpp:65: undefined reference to `__imp__ZN16wxStyledTextCtrl11SetWrapModeEi'
/path/to/codelite/cscope/CscopeTabBase.cpp:66: undefined reference to `__imp__ZN16wxStyledTextCtrl20SetIndentationGuidesEi'
/path/to/codelite/cscope/CscopeTabBase.cpp:67: undefined reference to `__imp__ZN16wxStyledTextCtrl11SetKeyWordsEiRK8wxString'
/path/to/codelite/cscope/CscopeTabBase.cpp:68: undefined reference to `__imp__ZN16wxStyledTextCtrl11SetKeyWordsEiRK8wxString'
/path/to/codelite/cscope/CscopeTabBase.cpp:69: undefined reference to `__imp__ZN16wxStyledTextCtrl11SetKeyWordsEiRK8wxString'
/path/to/codelite/cscope/CscopeTabBase.cpp:70: undefined reference to `__imp__ZN16wxStyledTextCtrl11SetKeyWordsEiRK8wxString'
/path/to/codelite/cscope/CscopeTabBase.cpp:71: undefined reference to `__imp__ZN16wxStyledTextCtrl11SetKeyWordsEiRK8wxString'
/path/to/codelite/cscope/CscopeTabBase.cpp:122: undefined reference to `__imp_wxEVT_STC_HOTSPOT_CLICK'
Win_x64_Debug/CscopeTabBase.cpp.o: In function `CscopeTabBase::~CscopeTabBase()':
/path/to/codelite/cscope/CscopeTabBase.cpp:137: undefined reference to `__imp_wxEVT_STC_HOTSPOT_CLICK'
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[1]: *** [Win_x64_Debug/Cscope-dbg.dll] Error 1
mingw32-make.exe: *** [All] Error 2
Cscope.mk:80: recipe for target 'Win_x64_Debug/Cscope-dbg.dll' failed
mingw32-make.exe[1]: Leaving directory '/path/to/codelite/cscope'
Makefile:4: recipe for target 'All' failed
====32 errors, 92 warnings, total time: 00:06:25 seconds====
`

For the Release build it is even worse:
`C:\windows\system32\cmd.exe /C C:/TDM-GCC-64/bin/mingw32-make.exe -j8 SHELL=cmd.exe -e -f  Makefile
"----------Building project:[ sqlite3 - Win_x64_Release ]----------"
mingw32-make.exe[1]: Entering directory '/path/to/codelite/sqlite3'
mingw32-make.exe[1]: Nothing to be done for 'all'.
mingw32-make.exe[1]: Leaving directory '/path/to/codelite/sqlite3'
mingw32-make.exe[1]: Entering directory '/path/to/codelite/sqlite3'
Executing Post Build commands ...
copy "Win_x64_Release\libsqlite3.a" ..\lib\gcc_lib
        1 file(s) copied.
Done
mingw32-make.exe[1]: Leaving directory '/path/to/codelite/sqlite3'
"----------Building project:[ wxsqlite3 - Win_x64_Release ]----------"

Please use the --prefix flag (as in wx-config --prefix=C:/wxWidgets)
or set the environment variable WXWIN (as in WXWIN=C:/wxWidgets)
to specify where is your installation of wxWidgets.

Please use the --prefix flag (as in wx-config --prefix=C:/wxWidgets)
or set the environment variable WXWIN (as in WXWIN=C:/wxWidgets)
to specify where is your installation of wxWidgets.

Please use the --prefix flag (as in wx-config --prefix=C:/wxWidgets)
or set the environment variable WXWIN (as in WXWIN=C:/wxWidgets)
to specify where is your installation of wxWidgets.

Please use the --prefix flag (as in wx-config --prefix=C:/wxWidgets)
or set the environment variable WXWIN (as in WXWIN=C:/wxWidgets)
to specify where is your installation of wxWidgets.
mingw32-make.exe[1]: Entering directory '/path/to/codelite/sdk/wxsqlite3'
C:/TDM-GCC-64/bin/g++.exe -c  ../../PCH/precompiled_header_release.h wx-config Error: wxWidgets hasn't been found installed at 'D:/src/wxWidgets'. -O2
g++.exe: error: wx-config: No such file or directory
g++.exe: error: Error:: Invalid argument
g++.exe: error: wxWidgets: No such file or directory
g++.exe: error: hasn't: No such file or directory
g++.exe: error: been: No such file or directory
g++.exe: error: found: No such file or directory
g++.exe: error: installed: No such file or directory
g++.exe: error: at: No such file or directory
g++.exe: error: 'D:/src/wxWidgets'.: Invalid argument
mingw32-make.exe[1]: *** [../../PCH/precompiled_header_release.h.gch] Error 1
wxsqlite3.mk:105: recipe for target '../../PCH/precompiled_header_release.h.gch' failed
mingw32-make.exe[1]: Leaving directory '/path/to/codelite/sdk/wxsqlite3'
mingw32-make.exe: *** [All] Error 2
Makefile:4: recipe for target 'All' failed
====1 errors, 0 warnings====
`

FYI: I tried compiling wxWidgets-MinGW as in http://codelite.org/Developers/BuildingWxWidgetsWin, but the DEBUG version could not get linked (Memory exhausted - which seems to be a know bug in MinGW >= 4.8.2), so I built the non-monolithic version.

**What am I doing wrong?**

**Comment by eranif** [comment]
You must use the same GCC version to build both CodeLite and wxWidgets.
I personally use GCC 4.9.2

**Comment by flederwiesel** [comment]
Which according to my conception is true. From the msys shell I used to build wxWidgets:

```
$ echo $PATH
.:/usr/local/bin:/mingw/bin:/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/c/cygwin64/bin:/c/cygwin64/usr/local/bin:/c/cygwin64/usr/bin:/c/Program Files (x86)/GTK2-Runtime/bin:/c/Program Files (x86)/Subversion/bin:/c/usr/xampp/php:/c/Program Files (x86)/TeX Live/bin/win32:/c/Program Files (x86)/Subversion-1.8.10/bin:/c/Program Files/Oracle/VirtualBox:/c/Program Files (x86)/Sudowin/Clients/Console:/c/wxWidgets/lib/gcc_dll:/mingw/bin:/c/Program Files/CodeLite:/e/ProgramData/Oracle/Java/javapath:/c/Program Files/doxygen/bin:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/c/usr/Python-3.5/Scripts/:/c/usr/Python-3.5:/c/Program Files (x86)/Windows Resource Kits/Tools/:/c/Program Files/TortoiseSVN/bin:/c/Program Files (x86)/Common Files/Acronis/VirtualFile/:/c/Program Files (x86)/Common Files/Acronis/VirtualFile64/:/c/Program Files (x86)/Common Files/Acronis/SnapAPI/:.:/usr/local/lib

$ which gcc
/mingw/bin/gcc.exe

$ mount
E:\home\FLEDER~1\AppData\Local\Temp on /tmp type user (binmode,noumount)
C:\TDM-GCC-64\msys on /usr type user (binmode,noumount)
C:\TDM-GCC-64\msys on / type user (binmode,noumount)
c:\TDM-GCC-64 on /mingw type user (binmode)

```
Codelite build uses:

`C:/TDM-GCC-64/bin/g++.exe -shared -fPIC -o Win_x64_Debug/Cscope-dbg.dll @"Cscope.txt" ...`

I read that _C:/TDM-GCC-64/bin/g++.exe_ is the same as _/mingw/bin/gcc.exe_ with _/mingw_ being _c:\TDM-GCC-64_.

**Comment by flederwiesel** [comment]
After looking at the wxWidgets build process, I am not quite sure how to build wxWidgets. Let alone building CL properly.

CL build instructions say to `mingw32-make -f makefile.gcc setup_h` without further flags and then to edit the built `lib\gcc_dll\mswu\wx\setup.h`. However, the build process creates the `setup.h` in `gcc_lib` as opposed to the build instructions:
`$ mingw32-make -f makefile.gcc setup_hif not exist ..\..\lib\gcc_lib mkdir ..\..\lib\gcc_lib
if not exist ..\..\lib\gcc_lib\mswud mkdir ..\..\lib\gcc_lib\mswud
if not exist ..\..\lib\gcc_lib\mswud\wx mkdir ..\..\lib\gcc_lib\mswud\wx
if not exist ..\..\lib\gcc_lib\mswud\wx\setup.h copy ..\..\include\wx\msw\setup.h ..\..\lib\gcc_lib\mswud\wx\setup.h
        1 file(s) copied.
if not exist ..\..\lib\gcc_lib\mswud\wx\msw mkdir ..\..\lib\gcc_lib\mswud\wx\msw
gcc -E "..\..\include\wx\msw\genrcdefs.h" > "..\..\lib\gcc_lib\mswud\wx\msw\rcdefs.h"`

If using the flags from the actual build `mingw32-make -j8 -f Makefile.gcc SHARED=1 UNICODE=1 BUILD=debug VENDOR=cl CXXFLAGS="-fno-keep-inline-dllexport -std=c++11" MONOLITHIC=1` also for the `setup_h` target, the `setup.h` will be generated in the mentioned directory `lib\gcc_dll\mswud\wx`.

Using the exact method from CL's wxWidget build instructions, the CL build fails with 
`C:/TDM-GCC-64/bin/g++.exe  -c  "/path/to/codelite/Plugin/project_settings.cpp" -g -Wall -mthreads -DHAVE_W32API_H -D__WXMSW__ -D__WXDEBUG__ -D_UNICODE -IC:/wxWidgets/lib/gcc_dll/mswud -IC:/wxWidgets/include -DWXUSINGDLL -Wno-ctor-dtor-privacy -pipe -fmessage-length=0  -fno-keep-inline-dllexport -std=c++11  -Winvalid-pch -DASTYLE_LIB -DWXUSINGDLL_CL -DWXMAKINGDLL_SDK -DWXUSINGDLL_WXSQLITE3 -DUSE_SFTP=1  -o Win_x64_Debug/project_settings.cpp.o -I. -I. -I./include -I../CodeLite -I../sdk/wxsqlite3/include -I../Interfaces -I../sdk/libssh/include
In file included from ./cl_aui_tb_are.h:32:0,
                 from ../Interfaces/plugin.h:39,
                 from E:/home/flederwiesel/x-doc/prj/src/flederwiesel/codelite/codelite/Plugin/editor_config.h:36,
                 from E:/home/flederwiesel/x-doc/prj/src/flederwiesel/codelite/codelite/Plugin/build_config.cpp:30:
./drawingutils.h:91:35: error: 'wxGCDC' has not been declared
     static bool GetGCDC(wxDC& dc, wxGCDC& gdc);
                                   ^
`
which holds true, as `wxGCDC` is not defined due to `wxUSE_GRAPHICS_CONTEXT` being 0 for `gcc_dll\mswud`, which was only generated when invoking the second `mingw32-make` with flags.

Changing the `wxUSE_GRAPHICS_CONTEXT` in the `lib\gcc_dll\mswu\wx\setup.h` built by `mingw32-make -f Makefile.gcc SHARED=1 UNICODE=1 BUILD=debug VENDOR=cl setup_h` takes us a bit further, but finally complains about `undefined reference to __imp__ZN16wxStyledTextCtrl8ClearAllEv` et al. I am further investigating on the case...

Apart fom that, both Release builds refused to find wx-config still. I.e. unless I changed the `LiteEditor.workspace` which defined `<Environment>WXWIN=D:/src/wxWidgets
WXCFG=gcc_dll\mswu</Environment>` which is not the actual path on my machine, but is not visible in the project properties (?!).

**Comment by eranif** [comment]
`wx-config` is a single source executable, you can download and build it from here:
https://github.com/eranif/codelite/tree/master/sdk/wxconfig

Once built, place it somewhere in the path of your machine. Otherwise, you should have one `wx-config.exe` under the installation folder of CodeLite itself

**Comment by flederwiesel** [comment]
`$ which wx-config.exe

/c/Program Files/CodeLite/wx-config.exe`

As the Debug build *does* find it and the installed CL is in the path, I don't think it is an issue of the host machine.

**Comment by eranif** [comment]
Just an FYI:
CodeLite is not supposed to be built from MSYS/Cygwin shell, it was never tested. Only from within CodeLite itself

**Comment by flederwiesel** [comment]
Never tried it. Maybe I should have said: 
![path](https://cloud.githubusercontent.com/assets/12841716/25074499/517bcc04-22fc-11e7-8697-ac1c3bb6bd48.png)

**Comment by eranif** [comment]
Please open a a thread for this on the forum, as I don't think there is a problem on CodeLite sources, but more of a specific issue that is related to your environment

**Comment by guy-rouillier** [comment]
I just started yesterday trying to build CodeLite from within Codelite, using the source snapshot.  I encountered the same issue as the OP.  I also have a locally compiled WxWidgets build (3.1.0) built with MingW-w64, and even though I had set the required environment variables via Settings-Environment Variables.. , I was still getting the error messages shown:

Please use the --prefix flag (as in wx-config --prefix=C:/wxWidgets)
or set the environment variable WXWIN (as in WXWIN=C:/wxWidgets)
to specify where is your installation of wxWidgets.

After a day of digging, I finally found where to fix this.  Right click the LiteEditor workspace, and select Workspace Settings.  In the resulting dialog, set the Environment sets to Default to use the values you've defined globally.  Then, in the box underneath labelled "Specify here an additional environment variables that will be shared with other people who are using this workspace", you find the values shown in the error messages:

WXWIN=D:\src\wxWidgets
WXCFG=gcc_dll\mswu

Delete both these values.  Now you can build from within CodeLite and get passed those errors.  I am still getting a bunch more that I need to work through.  I'd suggest removing the above lines from LiteEditor.workspace as they only seem to cause problems.
