### ISSUE TITLE
-pg not working mingw

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1620]
I've used profiling under codelite before in previous versions (8, 9) and the same compiler, so I'm not sure what's stopping it from operating now.

Win7 sp1
Codelite 10.0.3 non-self-compiled

TDM Mingw 5.1 x64 and Nuwen Mingw x64 6.3 both give the following error multiple times when attempting to compile with -pg turned on:
undefined reference to `__fentry__'

It doesn't seem to matter what code is being compiled. Have also tested it with the x86 version of TDM, same occurence.

**Comment by eranif** [comment]
This does not look related to CodeLite itself, but rather a MinGW compiler issue.
Also, notice that -pg should be placed both in the linker and in the compiler settings

**Comment by mattreecebentley** [comment]
Ah, yes it was the missing option to the linker which did it
