### ISSUE TITLE
Crash when attempting to run without an active project

### ISSUE THREAD

**Issue by Espyo** [eranif/codelite#1621]
Steps:

1. Have CodeLite open, with a workspace open.
2. Set one of the workspace's projects as the active one.
3. Edit the workspace's file and remove the project you had set active.
3. Return to CodeLite. It will have asked you to refresh the workspace. Answer yes. After the refresh, no project will be marked as active on the Workspace View.
5. Click on either Start / Continue debugger, or Run Active Project.
6. CodeLite's crash handler will show up, with the message "codelite crashed: you may attach to it using gdb or let it crash silently.. Attach debugger?"

OS: Ubuntu 14.04.
CodeLite version: 9.1.0.

**Comment by eranif** [comment]
I am unable to reproduce this. I am using CodeLite 10.0.4 on Debian 8
Version 9.1 is old please upgrade to 10.0 at least.

I also checked the source code, and in both cases (Execute or Debug) there is a sanity check that checks for a valid active project. Please Upgrade to 10.0 and reopen if this still reproduces for you
