### ISSUE TITLE
Disappearing conditional breakpoints

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1622]
Creating a breakpoint based on (anything) == NULL means when the program stops, the breakpoint icon disappears. The breakpoint is still there, and the option to remove it is still there. However the breakpoint does not trigger. And the icon disappears. Doesn't matter whether (anything) is a pointer or a scalar type. You can set it to (anything) == 0 and this behaviour does not occur.

Win7 sp1. Non-self-compiled. 10.0.3

**Comment by eranif** [comment]
Please provide the full debugger log (enable debugger log)

**Comment by mattreecebentley** [comment]
With TDM GCC 5.1 x64:
"Using gdbinit file: v:\SYSTEM~2\codelite_gdbinit.txt
Current working dir: D:\programming\Workspaces\plf_list\plf_list_test
Launching gdb from : ./Debug
Starting debugger  : D:/programming/libraries/mingw/bin/gdb.exe --command="v:\SYSTEM~2\codelite_gdbinit.txt" --interpreter=mi "./plf_list_test"
DEBUG>>set  new-console on
DEBUG>>set unwindonsignal on
DEBUG>>set breakpoint pending on
DEBUG>>set print object on
DEBUG>>set width 0
DEBUG>>set height 0
DEBUG>>set print elements 200
DEBUG>>python
DEBUG>>import sys
DEBUG>>sys.path.insert(0, 'C:\Users\MattyB\AppData\Roaming\codelite\gdb_printers')
DEBUG>>from libstdcxx.v6.printers import register_libstdcxx_printers
DEBUG>>register_libstdcxx_printers (None)
DEBUG>>from qt4 import register_qt4_printers
DEBUG>>register_qt4_printers (None)
DEBUG>>from wx import register_wx_printers
DEBUG>>register_wx_printers (None)
DEBUG>>end
DEBUG>>00000001-break-insert -f -t main
DEBUG>>00000002-enable-pretty-printing
Debug session started successfully!
DEBUG>>00000003-exec-arguments 
DEBUG>>00000004-exec-run 
DEBUG>>=thread-group-added,id="i1"
=thread-group-added,id="i1"
DEBUG>>~"GNU gdb (GDB) 7.9.1\n"
GNU gdb (GDB) 7.9.1
DEBUG>>~"Copyright (C) 2015 Free Software Foundation, Inc.\n"
Copyright (C) 2015 Free Software Foundation, Inc.
DEBUG>>~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\n"
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type "show copying"\nand "show warranty" for details.
DEBUG>>~"This GDB was configured as \"x86_64-w64-mingw32\".\nType \"show configuration\" for configuration details."
This GDB was configured as "x86_64-w64-mingw32".\nType "show configuration" for configuration details.
DEBUG>>~"\nFor bug reporting instructions, please see:\n"
\nFor bug reporting instructions, please see:
DEBUG>>~"<http://www.gnu.org/software/gdb/bugs/>.\n"
<http://www.gnu.org/software/gdb/bugs/>.
DEBUG>>~"Find the GDB manual and other documentation resources online at:\n<http://www.gnu.org/software/gdb/documentation/>.\n"
Find the GDB manual and other documentation resources online at:\n<http://www.gnu.org/software/gdb/documentation/>.
DEBUG>>~"For help, type \"help\".\n"
For help, type "help".
DEBUG>>~"Type \"apropos word\" to search for commands related to \"word\"...\n"
Type "apropos word" to search for commands related to "word"...
DEBUG>>~"Reading symbols from ./plf_list_test..."
Reading symbols from ./plf_list_test...
DEBUG>>~"done.\n"
done.
DEBUG>>&"Traceback (most recent call last):\n"
DEBUG>>&"  File \"<string>\", line 5, in <module>\n"
DEBUG>>&"  File \"C:\\Users\\MattyB\\AppData\\Roaming\\codelite\\gdb_printers\\libstdcxx\\v6\\printers.py\", line 1023, in register_libstdcxx_printers\n"
DEBUG>>&"    gdb.printing.register_pretty_printer(obj, libstdcxx_printer)\n"
DEBUG>>&"  File \"d:\\programming\\libraries\\mingw\\gdb64\\share\\gdb/python\\gdb\\printing.py\", line 152, in register_pretty_printer\n"
DEBUG>>&"    printer.name)\n"
DEBUG>>&"RuntimeError: pretty-printer already registered: libstdc++-v6\n"
DEBUG>>&"v:\\SYSTEM~2\\codelite_gdbinit.txt:14: Error in sourced command file:\n"
DEBUG>>&"Error while executing Python code.\n"
DEBUG>>&"set  new-console on\n"
DEBUG>>=cmd-param-changed,param="new-console",value="on"
=cmd-param-changed,param="new-console",value="on"
DEBUG>>^done
DEBUG>>&"set unwindonsignal on\n"
DEBUG>>=cmd-param-changed,param="unwindonsignal",value="on"
=cmd-param-changed,param="unwindonsignal",value="on"
DEBUG>>^done
DEBUG>>&"set breakpoint pending on\n"
DEBUG>>=cmd-param-changed,param="breakpoint pending",value="on"
=cmd-param-changed,param="breakpoint pending",value="on"
DEBUG>>^done
DEBUG>>&"set print object on\n"
DEBUG>>=cmd-param-changed,param="print object",value="on"
=cmd-param-changed,param="print object",value="on"
DEBUG>>^done
DEBUG>>&"set width 0\n"
DEBUG>>=cmd-param-changed,param="width",value="4294967295"
=cmd-param-changed,param="width",value="4294967295"
DEBUG>>^done
DEBUG>>&"set height 0\n"
DEBUG>>^done
DEBUG>>&"set print elements 200\n"
DEBUG>>^done
DEBUG>>&"python\n"
DEBUG>>&"Traceback (most recent call last):\n"
DEBUG>>&"  File \"<string>\", line 4, in <module>\n"
DEBUG>>&"  File \"C:\\Users\\MattyB\\AppData\\Roaming\\codelite\\gdb_printers\\libstdcxx\\v6\\printers.py\", line 1023, in register_libstdcxx_printers\n"
DEBUG>>&"    gdb.printing.register_pretty_printer(obj, libstdcxx_printer)\n"
DEBUG>>&"  File \"d:\\programming\\libraries\\mingw\\gdb64\\share\\gdb/python\\gdb\\printing.py\", line 152, in register_pretty_printer\n"
DEBUG>>&"    printer.name)\n"
DEBUG>>&"RuntimeError: pretty-printer already registered: libstdc++-v6\n"
DEBUG>>&"Error while executing Python code.\n"
DEBUG>>^error,msg="Error while executing Python code."
^error,msg="Error while executing Python code."
DEBUG>>00000001^done,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x0000000000401693",func="main(int, char**)",file="D:/programming/projects/plf_list/main.cpp",fullname="D:\\programming\\projects\\plf_list\\main.cpp",line="73",thread-groups=["i1"],times="0",original-location="main"}
Storing internal breakpoint ID=1
DEBUG>>00000002^done
DEBUG>>00000003^done
>> Debuggee process ID: 1416
DEBUG>>=thread-group-started,id="i1",pid="1416"
=thread-group-started,id="i1",pid="1416"
DEBUG>>=thread-created,id="1",group-id="i1"
=thread-created,id="1",group-id="i1"
DEBUG>>~"[New Thread 1416.0x4c0]\n"
[New Thread 1416.0x4c0]
DEBUG>>00000004^running
Continuing...
DEBUG>>*running,thread-id="all"
*running,thread-id="all"
DEBUG>>=library-loaded,id="C:\\Windows\\SYSTEM32\\ntdll.dll",target-name="C:\\Windows\\SYSTEM32\\ntdll.dll",host-name="C:\\Windows\\SYSTEM32\\ntdll.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\SYSTEM32\\ntdll.dll",target-name="C:\\Windows\\SYSTEM32\\ntdll.dll",host-name="C:\\Windows\\SYSTEM32\\ntdll.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\kernel32.dll",target-name="C:\\Windows\\system32\\kernel32.dll",host-name="C:\\Windows\\system32\\kernel32.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\kernel32.dll",target-name="C:\\Windows\\system32\\kernel32.dll",host-name="C:\\Windows\\system32\\kernel32.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\KernelBase.dll",target-name="C:\\Windows\\system32\\KernelBase.dll",host-name="C:\\Windows\\system32\\KernelBase.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\KernelBase.dll",target-name="C:\\Windows\\system32\\KernelBase.dll",host-name="C:\\Windows\\system32\\KernelBase.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\msvcrt.dll",target-name="C:\\Windows\\system32\\msvcrt.dll",host-name="C:\\Windows\\system32\\msvcrt.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\msvcrt.dll",target-name="C:\\Windows\\system32\\msvcrt.dll",host-name="C:\\Windows\\system32\\msvcrt.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\user32.dll",target-name="C:\\Windows\\system32\\user32.dll",host-name="C:\\Windows\\system32\\user32.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\user32.dll",target-name="C:\\Windows\\system32\\user32.dll",host-name="C:\\Windows\\system32\\user32.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\gdi32.dll",target-name="C:\\Windows\\system32\\gdi32.dll",host-name="C:\\Windows\\system32\\gdi32.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\gdi32.dll",target-name="C:\\Windows\\system32\\gdi32.dll",host-name="C:\\Windows\\system32\\gdi32.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\lpk.dll",target-name="C:\\Windows\\system32\\lpk.dll",host-name="C:\\Windows\\system32\\lpk.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\lpk.dll",target-name="C:\\Windows\\system32\\lpk.dll",host-name="C:\\Windows\\system32\\lpk.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\usp10.dll",target-name="C:\\Windows\\system32\\usp10.dll",host-name="C:\\Windows\\system32\\usp10.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\usp10.dll",target-name="C:\\Windows\\system32\\usp10.dll",host-name="C:\\Windows\\system32\\usp10.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\apphelp.dll",target-name="C:\\Windows\\system32\\apphelp.dll",host-name="C:\\Windows\\system32\\apphelp.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\apphelp.dll",target-name="C:\\Windows\\system32\\apphelp.dll",host-name="C:\\Windows\\system32\\apphelp.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\AppPatch\\AppPatch64\\AcGenral.dll",target-name="C:\\Windows\\AppPatch\\AppPatch64\\AcGenral.dll",host-name="C:\\Windows\\AppPatch\\AppPatch64\\AcGenral.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\AppPatch\\AppPatch64\\AcGenral.dll",target-name="C:\\Windows\\AppPatch\\AppPatch64\\AcGenral.dll",host-name="C:\\Windows\\AppPatch\\AppPatch64\\AcGenral.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\sspicli.dll",target-name="C:\\Windows\\system32\\sspicli.dll",host-name="C:\\Windows\\system32\\sspicli.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\sspicli.dll",target-name="C:\\Windows\\system32\\sspicli.dll",host-name="C:\\Windows\\system32\\sspicli.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\rpcrt4.dll",target-name="C:\\Windows\\system32\\rpcrt4.dll",host-name="C:\\Windows\\system32\\rpcrt4.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\rpcrt4.dll",target-name="C:\\Windows\\system32\\rpcrt4.dll",host-name="C:\\Windows\\system32\\rpcrt4.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\shlwapi.dll",target-name="C:\\Windows\\system32\\shlwapi.dll",host-name="C:\\Windows\\system32\\shlwapi.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\shlwapi.dll",target-name="C:\\Windows\\system32\\shlwapi.dll",host-name="C:\\Windows\\system32\\shlwapi.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\ole32.dll",target-name="C:\\Windows\\system32\\ole32.dll",host-name="C:\\Windows\\system32\\ole32.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\ole32.dll",target-name="C:\\Windows\\system32\\ole32.dll",host-name="C:\\Windows\\system32\\ole32.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\shell32.dll",target-name="C:\\Windows\\system32\\shell32.dll",host-name="C:\\Windows\\system32\\shell32.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\shell32.dll",target-name="C:\\Windows\\system32\\shell32.dll",host-name="C:\\Windows\\system32\\shell32.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\sfc.dll",target-name="C:\\Windows\\system32\\sfc.dll",host-name="C:\\Windows\\system32\\sfc.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\sfc.dll",target-name="C:\\Windows\\system32\\sfc.dll",host-name="C:\\Windows\\system32\\sfc.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\sfc_os.dll",target-name="C:\\Windows\\system32\\sfc_os.dll",host-name="C:\\Windows\\system32\\sfc_os.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\sfc_os.dll",target-name="C:\\Windows\\system32\\sfc_os.dll",host-name="C:\\Windows\\system32\\sfc_os.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\userenv.dll",target-name="C:\\Windows\\system32\\userenv.dll",host-name="C:\\Windows\\system32\\userenv.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\userenv.dll",target-name="C:\\Windows\\system32\\userenv.dll",host-name="C:\\Windows\\system32\\userenv.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\profapi.dll",target-name="C:\\Windows\\system32\\profapi.dll",host-name="C:\\Windows\\system32\\profapi.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\profapi.dll",target-name="C:\\Windows\\system32\\profapi.dll",host-name="C:\\Windows\\system32\\profapi.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\dwmapi.dll",target-name="C:\\Windows\\system32\\dwmapi.dll",host-name="C:\\Windows\\system32\\dwmapi.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\dwmapi.dll",target-name="C:\\Windows\\system32\\dwmapi.dll",host-name="C:\\Windows\\system32\\dwmapi.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\advapi32.dll",target-name="C:\\Windows\\system32\\advapi32.dll",host-name="C:\\Windows\\system32\\advapi32.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\advapi32.dll",target-name="C:\\Windows\\system32\\advapi32.dll",host-name="C:\\Windows\\system32\\advapi32.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\SYSTEM32\\sechost.dll",target-name="C:\\Windows\\SYSTEM32\\sechost.dll",host-name="C:\\Windows\\SYSTEM32\\sechost.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\SYSTEM32\\sechost.dll",target-name="C:\\Windows\\SYSTEM32\\sechost.dll",host-name="C:\\Windows\\SYSTEM32\\sechost.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\mpr.dll",target-name="C:\\Windows\\system32\\mpr.dll",host-name="C:\\Windows\\system32\\mpr.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\mpr.dll",target-name="C:\\Windows\\system32\\mpr.dll",host-name="C:\\Windows\\system32\\mpr.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\imm32.dll",target-name="C:\\Windows\\system32\\imm32.dll",host-name="C:\\Windows\\system32\\imm32.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\imm32.dll",target-name="C:\\Windows\\system32\\imm32.dll",host-name="C:\\Windows\\system32\\imm32.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\system32\\msctf.dll",target-name="C:\\Windows\\system32\\msctf.dll",host-name="C:\\Windows\\system32\\msctf.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\system32\\msctf.dll",target-name="C:\\Windows\\system32\\msctf.dll",host-name="C:\\Windows\\system32\\msctf.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=breakpoint-modified,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x0000000000401693",func="main(int, char**)",file="D:/programming/projects/plf_list/main.cpp",fullname="D:\\programming\\projects\\plf_list\\main.cpp",line="73",thread-groups=["i1"],times="1",original-location="main"}
=breakpoint-modified,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x0000000000401693",func="main(int, char**)",file="D:/programming/projects/plf_list/main.cpp",fullname="D:\\programming\\projects\\plf_list\\main.cpp",line="73",thread-groups=["i1"],times="1",original-location="main"}
DEBUG>>~"\nTemporary breakpoint "
\nTemporary breakpoint
DEBUG>>~"1, main (argc=1, argv=0x5b2580) at D:/programming/projects/plf_list/main.cpp:73\n"
1, main (argc=1, argv=0x5b2580) at D:/programming/projects/plf_list/main.cpp:73
DEBUG>>~"73\t\tfreopen(\"errors.log\",\"w\", stderr);\n"
73\t\tfreopen("errors.log","w", stderr);
DEBUG>>*stopped,reason="breakpoint-hit",disp="del",bkptno="1",frame={addr="0x0000000000401693",func="main",args=[{name="argc",value="1"},{name="argv",value="0x5b2580"}],file="D:/programming/projects/plf_list/main.cpp",fullname="D:\\programming\\projects\\plf_list\\main.cpp",line="73"},thread-id="1",stopped-threads="all"
Internal breakpoint was hit (id=1), Applying user breakpoints and continuing
DEBUG>>00000005-break-insert -f -c "node_group == NULL" "D:/programming/projects/plf_list/plf_list.h:651"
DEBUG>>00000006-exec-continue
DEBUG>>=breakpoint-deleted,id="1"
=breakpoint-deleted,id="1"
DEBUG>>00000005^error,msg="No symbol \"NULL\" in current context."
Breakpoint creation unsuccessful
ERROR: failed to place breakpoint: "^error,msg="No symbol \"NULL\" in current context.""
No symbol "NULL" in current context.
DEBUG>>00000006^running
Continuing...
DEBUG>>*running,thread-id="all"
*running,thread-id="all"
Debug session ended
"

**Comment by mattreecebentley** [comment]
And with nuwen GCC 6.3 x64:
"Using gdbinit file: v:\SYSTEM~2\codelite_gdbinit.txt
Current working dir: D:\programming\Workspaces\plf_list\plf_list_test
Launching gdb from : ./Debug
Starting debugger  : D:/programming/libraries/mingw63/bin/gdb.exe --command="v:\SYSTEM~2\codelite_gdbinit.txt" --interpreter=mi "./plf_list_test"
DEBUG>>set  new-console on
DEBUG>>set unwindonsignal on
DEBUG>>set breakpoint pending on
DEBUG>>set print object on
DEBUG>>set width 0
DEBUG>>set height 0
DEBUG>>set print elements 200
DEBUG>>python
DEBUG>>import sys
DEBUG>>sys.path.insert(0, 'C:\Users\MattyB\AppData\Roaming\codelite\gdb_printers')
DEBUG>>from libstdcxx.v6.printers import register_libstdcxx_printers
DEBUG>>register_libstdcxx_printers (None)
DEBUG>>from qt4 import register_qt4_printers
DEBUG>>register_qt4_printers (None)
DEBUG>>from wx import register_wx_printers
DEBUG>>register_wx_printers (None)
DEBUG>>end
DEBUG>>00000007-break-insert -f -t main
DEBUG>>00000008-enable-pretty-printing
Debug session started successfully!
DEBUG>>00000009-exec-arguments 
DEBUG>>00000010-exec-run 
DEBUG>>=thread-group-added,id="i1"
=thread-group-added,id="i1"
DEBUG>>~"GNU gdb (GDB) 7.12\n"
GNU gdb (GDB) 7.12
DEBUG>>~"Copyright (C) 2016 Free Software Foundation, Inc.\n"
Copyright (C) 2016 Free Software Foundation, Inc.
DEBUG>>~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\n"
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type "show copying"\nand "show warranty" for details.
DEBUG>>~"This GDB was configured as \"x86_64-w64-mingw32\".\nType \"show configuration\" for configuration details."
This GDB was configured as "x86_64-w64-mingw32".\nType "show configuration" for configuration details.
DEBUG>>~"\nFor bug reporting instructions, please see:\n"
\nFor bug reporting instructions, please see:
DEBUG>>~"<http://www.gnu.org/software/gdb/bugs/>.\n"
<http://www.gnu.org/software/gdb/bugs/>.
DEBUG>>~"Find the GDB manual and other documentation resources online at:\n<http://www.gnu.org/software/gdb/documentation/>.\n"
Find the GDB manual and other documentation resources online at:\n<http://www.gnu.org/software/gdb/documentation/>.
DEBUG>>~"For help, type \"help\".\n"
For help, type "help".
DEBUG>>~"Type \"apropos word\" to search for commands related to \"word\"...\n"
Type "apropos word" to search for commands related to "word"...
DEBUG>>~"Reading symbols from ./plf_list_test..."
Reading symbols from ./plf_list_test...
DEBUG>>~"done.\n"
done.
DEBUG>>&"v:\\SYSTEM~2\\codelite_gdbinit.txt:14: Error in sourced command file:\n"
DEBUG>>&"Scripting in the \"Python\" language is not supported in this copy of GDB.\n"
DEBUG>>&"set  new-console on\n"
DEBUG>>=cmd-param-changed,param="new-console",value="on"
=cmd-param-changed,param="new-console",value="on"
DEBUG>>^done
DEBUG>>&"set unwindonsignal on\n"
DEBUG>>=cmd-param-changed,param="unwindonsignal",value="on"
=cmd-param-changed,param="unwindonsignal",value="on"
DEBUG>>^done
DEBUG>>&"set breakpoint pending on\n"
DEBUG>>=cmd-param-changed,param="breakpoint pending",value="on"
=cmd-param-changed,param="breakpoint pending",value="on"
DEBUG>>^done
DEBUG>>&"set print object on\n"
DEBUG>>=cmd-param-changed,param="print object",value="on"
=cmd-param-changed,param="print object",value="on"
DEBUG>>^done
DEBUG>>&"set width 0\n"
DEBUG>>=cmd-param-changed,param="width",value="4294967295"
=cmd-param-changed,param="width",value="4294967295"
DEBUG>>^done
DEBUG>>&"set height 0\n"
DEBUG>>^done
DEBUG>>&"set print elements 200\n"
DEBUG>>^done
DEBUG>>&"python\n"
DEBUG>>&"Scripting in the \"Python\" language is not supported in this copy of GDB.\n"
DEBUG>>^error,msg="Scripting in the \"Python\" language is not supported in this copy of GDB."
^error,msg="Scripting in the \"Python\" language is not supported in this copy of GDB."
DEBUG>>00000007^done,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x0000000000401699",func="main(int, char**)",file="D:/programming/projects/plf_list/main.cpp",fullname="D:\\programming\\projects\\plf_list\\main.cpp",line="73",thread-groups=["i1"],times="0",original-location="main"}
Storing internal breakpoint ID=1
DEBUG>>00000008^done
DEBUG>>00000009^done
>> Debuggee process ID: 2856
DEBUG>>=thread-group-started,id="i1",pid="2856"
=thread-group-started,id="i1",pid="2856"
DEBUG>>=thread-created,id="1",group-id="i1"
=thread-created,id="1",group-id="i1"
DEBUG>>~"[New Thread 2856.0x878]\n"
[New Thread 2856.0x878]
DEBUG>>&"warning: Can not parse XML library list; XML support was disabled at compile time\n"
DEBUG>>00000010^running
Continuing...
DEBUG>>*running,thread-id="all"
*running,thread-id="all"
DEBUG>>=breakpoint-modified,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x0000000000401699",func="main(int, char**)",file="D:/programming/projects/plf_list/main.cpp",fullname="D:\\programming\\projects\\plf_list\\main.cpp",line="73",thread-groups=["i1"],times="1",original-location="main"}
=breakpoint-modified,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x0000000000401699",func="main(int, char**)",file="D:/programming/projects/plf_list/main.cpp",fullname="D:\\programming\\projects\\plf_list\\main.cpp",line="73",thread-groups=["i1"],times="1",original-location="main"}
DEBUG>>~"\n"

DEBUG>>~"Temporary breakpoint 1, main (argc=1, argv=0x322580) at D:/programming/projects/plf_list/main.cpp:73\n"
Temporary breakpoint 1, main (argc=1, argv=0x322580) at D:/programming/projects/plf_list/main.cpp:73
DEBUG>>~"73\t\tfreopen(\"errors.log\",\"w\", stderr);\n"
73\t\tfreopen("errors.log","w", stderr);
DEBUG>>*stopped,reason="breakpoint-hit",disp="del",bkptno="1",frame={addr="0x0000000000401699",func="main",args=[{name="argc",value="1"},{name="argv",value="0x322580"}],file="D:/programming/projects/plf_list/main.cpp",fullname="D:\\programming\\projects\\plf_list\\main.cpp",line="73"},thread-id="1",stopped-threads="all"
Internal breakpoint was hit (id=1), Applying user breakpoints and continuing
DEBUG>>00000011-break-insert -f -c "node_group == NULL" "D:/programming/projects/plf_list/plf_list.h:651"
DEBUG>>00000012-exec-continue
DEBUG>>=breakpoint-deleted,id="1"
=breakpoint-deleted,id="1"
DEBUG>>00000011^error,msg="No symbol \"NULL\" in current context."
Breakpoint creation unsuccessful
ERROR: failed to place breakpoint: "^error,msg="No symbol \"NULL\" in current context.""
No symbol "NULL" in current context.
DEBUG>>00000012^running
Continuing...
DEBUG>>*running,thread-id="all"
*running,thread-id="all"
Debug session ended
"

**Comment by mattreecebentley** [comment]
Note: in both contexts node_group is a pointer, NULL is valid.
