### ISSUE TITLE
Open a second instance, it will load the same workspace as the first one

### ISSUE THREAD

**Issue by kipade** [eranif/codelite#1623]
1. codelite closed and saved the last workspace normally.
2. Reopen codelite, the saved workspace will be loaded automatically.
3. Start a new instance, it will also load the same workspace as the first instance.

I think codelite should open with any workspace or a different one with the first instance. right?

**Comment by eranif** [comment]
Since both instances are sharing the same configuration, they will act the same.
I don't see a way of changing this.

**Comment by kipade** [comment]
I just think the second instance might know the workspace was opened by the last instance, if so, the second instance has the chance to do the different thing, starting without any workspace for example.

**Comment by eranif** [comment]
Again, they are using the **same** configuration path, so it can't be done.
The only way to achieve what you want is to run CodeLite from a terminal using `--data-dir` option which specify a different location for configuration per instance, for example:

`codelite --data-dir=/home/eran/cl-instance-1 &`
and the second instance can be run like this:
`codelite --data-dir=/home/eran/cl-instance-2 &`
This way each instance is running and using different configuration paths
