### ISSUE TITLE
xenial Release does not have a Release file, Cannot build 

### ISSUE THREAD

**Issue by RickyS** [eranif/codelite#1624]
## Building gnuShell, need wxWidgets, [following instructions](http://codelite.org/LiteEditor/WxWidgets30Binaries#toc2).

**sudo apt-add-repository 'deb http://repos.codelite.org/wx3.0.2/ubuntu/ xenial universe'
sudo apt update**
...
Err:26 http://repos.codelite.org/wx3.0.2/ubuntu *xenial* Release
  **404  Not Found**
...
E: The repository 'http://repos.codelite.org/wx3.0.2/ubuntu xenial Release' **does not have a Release file**.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

```
Description:	Ubuntu 16.04.2 LTS
Codename:	xenial
Linux Who 4.8.0-49-generic #52~16.04.1-Ubuntu SMP Thu Apr 20 10:55:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
stretch/sid

```

**Comment by dghart** [comment]
Hi,
That misleading error message is what happens when there are no files available for that release in the repository. Why not? Because you are following the old instructions for installing wx3.0.2. As the page you linked to says, we supply those packages for ubuntu saucy, trusty and utopic, plus debian wheezy.

The latest instructions, which you can find at http://codelite.org/LiteEditor/WxWidgets31Binaries (see the top of the previous page), contain instructions for installing the latest wx release, wx3.1.0, on xenial. It's also the one that CodeLite packages use.

I stopped creating wx3.0.2 packages when ubuntu provided official ones itself. If you need wx3.0.2 to build a different program, why not use the official package?

Regards,

David

**Comment by RickyS** [comment]
Dghart:
    
    
      Thank You.
        
      3.1.0 was marked as not stable, so I thought I
          was being conservative.
      The system eventually prompted me to install
          the official versions, so I have.
        
    
    
    On 04/27/2017 08:20 PM, dghart wrote:
    
    
      Hi,
        That misleading error message is what happens when there are no
        files available for that release in the repository. Why not?
        Because you are following the old instructions for installing
        wx3.0.2. As the page you linked to says, we supply those
        packages for ubuntu saucy, trusty and utopic, plus debian
        wheezy.
      The latest instructions, which you can find at http://codelite.org/LiteEditor/WxWidgets31Binaries
        (see the top of the previous page), contain instructions for
        installing the latest wx release, wx3.1.0, on xenial. It's also
        the one that CodeLite packages use.
      I stopped creating wx3.0.2 packages when ubuntu provided
        official ones itself. If you need wx3.0.2 to build a different
        program, why not use the official package?
      Regards,
      David
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/eranif/codelite","title":"eranif/codelite","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/eranif/codelite"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dghart in #1624: Hi,\r\nThat misleading error message is what happens when there are no files available for that release in the repository. Why not? Because you are following the old instructions for installing wx3.0.2. As the page you linked to says, we supply those packages for ubuntu saucy, trusty and utopic, plus debian wheezy.\r\n\r\nThe latest instructions, which you can find at http://codelite.org/LiteEditor/WxWidgets31Binaries (see the top of the previous page), contain instructions for installing the latest wx release, wx3.1.0, on xenial. It's also the one that CodeLite packages use.\r\n\r\nI stopped creating wx3.0.2 packages when ubuntu provided official ones itself. If you need wx3.0.2 to build a different program, why not use the official package?\r\n\r\nRegards,\r\n\r\nDavid"}],"action":{"name":"View Issue","url":"https://github.com/eranif/codelite/issues/1624#issuecomment-297781742"}}}
