### ISSUE TITLE
Reload workspace disables F7 (build project)

### ISSUE THREAD

**Issue by ysblokje** [eranif/codelite#1627]
Like the title says. 

This happens if for some reason I modify a project file, in my case a modification of a cmake file. During the build it detects the change and asks if I want to reload.  If I choose yes I can't build using F7 anymore.

**Comment by eranif** [comment]
can you please provide an exact steps for reproduction?

**Comment by ysblokje** [comment]
I tried the smallest example I could think of :)

main.cpp
`
int main() {
 return -1;
}
`

CMakeLists.txt
`
project(t-main)

#add_definitions(-DWHOOOO)
add_executable(t-main main.cpp)
'

with these 2 files do the following : 
mkdir
cd build
cmake -GCodeLite 

open the project
press F7 and it should compile

go and remove the # from the CMakeLists.txt

press F7 again in CL and again it should compile

Now depending on your WM / desktop it should prompt for a possible reload of the workspace (for me it only came up when it lost focus and got it back again but that's a different matter because I'm trying out i3wm)

Now, if I select reload and want to recompile by pressing F7, nothing happens and the item is disabled in the menu.
