### ISSUE TITLE
[C++17] autocompletion doesn't work for structured bindings in range based for loop

### ISSUE THREAD

**Issue by Mutantpenguin** [eranif/codelite#1628]
Just tell me if bugs for C++17 are not wanted yet (since codelite doesn't advertise compatibility with it).

The following code won't show neither "hans" nor "franz" in the autocompletion popup inside the range based for loop. Interestingly enough, placing the "dot" behind "franz" shows its members "no" and "name" in the popup.
```c++
#include <iostream>

#include <map>
#include <cstdint>

struct test
{
	int no;
	std::string name;
};

int main(int argc, char **argv)
{
	const std::map< std::uint16_t, test > exampleMap { { 1, { 1, "one" } }, { 2, { 2, "two" } }, { 3, { 3, "three" } } };

	std::cout << "new c++17 structured bindings" << std::endl;
	for( const auto & [ hans, franz ] : exampleMap )
	{
		std::cout << hans << " - " << franz.name << std::endl;
	}

    return 0;
}
```

**Comment by eranif** [comment]
This is now supported via the `Language Server` plugin.
https://wiki.codelite.org/pmwiki.php/Main/LanguageServer

![cc-17](https://user-images.githubusercontent.com/3677711/64067630-7d0ed300-cc34-11e9-88fc-b4038cc84120.png)
