### ISSUE TITLE
Setting up php [laravel] environment 

### ISSUE THREAD

**Issue by Anan5a** [eranif/codelite#1632]
Hi
I'm unable to get code completion for my laravel project. Also php-cs-fixer don't work in the application. (tried with both composer and phar)
Can anyone help please?

**Comment by eranif** [comment]
I don't have much experience with laravel, however, I can assist you if you could pack a minimal workspace / or give me an instructions on what you did so far and how to reproduce this

**Comment by Anan5a** [comment]
![img_20170510_121006](https://cloud.githubusercontent.com/assets/16373480/25885389/e47e2170-3579-11e7-8f33-adb1750b759a.JPG)
![img_20170510_121049](https://cloud.githubusercontent.com/assets/16373480/25885404/f6289716-3579-11e7-930a-8221682b8e2d.JPG)
Here is what i did :
```
1. Installed laravel using composer
2. Created a workspace to the installation directory (/root/blog)
3. Changed the settings for code style fix.
```

**Comment by eranif** [comment]
After you changed the options, hitting `Ctrl-I` did nothing? it should run PHP-CS-fixer on the current file.
What you described here is only changing the settings, you still need to execute it using `Ctrl-I`

**Comment by AJenbo** [comment]
@Anan5a what version are you running. For me the 10.0 that packaged with Ubuntu 17.04 had broken autocompleate, installing 10.0.4 via the .deb package solved that issue.

As for PHP-CS-Fixser, I actually use the phpcs package from the debian archives, but the phar should work the same. Firstly make sure you picked PHP-CS-Fixer as the PHP Formatter under the general tab. Here is how I have it setup:
![billede](https://cloud.githubusercontent.com/assets/204594/26284128/3f30e6a8-3e34-11e7-96e2-2d531b4703ec.png)
![billede](https://cloud.githubusercontent.com/assets/204594/26284131/494b39f4-3e34-11e7-911a-55e33bf13801.png)
Hope that helps

**Comment by AJenbo** [comment]
Also can you include the log ~/.codelite/codelite.log

**Comment by AJenbo** [comment]
Closed since two likely solutions whet given followed by no response
