### ISSUE TITLE
Add/change syntax highlighting for file (extension)

### ISSUE THREAD

**Issue by pimlie** [eranif/codelite#1635]
Is it possible to change the syntax highlighting for a given file (extension)? 

I am using `.vue` files to develop vue components, those components contain both javascript as html and css. At the moment these files have no highlighting at all. I tried to add the *.vue extension to all javascript theme's in `/usr/share/codelite/lexers/lexers.json`, but that doesnt seem to work unfortunately.

**Comment by eranif** [comment]
You can do this from:
`settings->colours and fonts->customize->javascript (on the left side)->File extensions`

and add the extension:
`*.vue`, you will need to close and reopen the file to it to take affect

**Comment by pimlie** [comment]
Works indeed, many thanks for the quick help! :+1:
