### ISSUE TITLE
Spell Checker Plugin links against outdated libhunspell

### ISSUE THREAD

**Issue by mparuzel** [eranif/codelite#1636]
It appears that the Spell Checker plugin links against linhunspell 1.3 meanwhile v1.6 is already out. This plugin breaks each time a new version of libhunspell is released, forcing me to create a simlink to the old version. Is there a way to update the build to link against libhunspell.so rather than libhunspell-1.3.so.0?

**Comment by eranif** [comment]
Which version and OS are you using?

**Comment by eranif** [comment]
I added new build options to build against latest versions of the library
