### ISSUE TITLE
Pos count shows char in file rather then char on current line since 10.0

### ISSUE THREAD

**Issue by AJenbo** [eranif/codelite#1637]
The Pos indicator in the bottom has been changed to show the carrot position relative to the start of the file rather then the start of the file. The old behaviour was more helpful in figuring out if you are close to the line width for a given code style.

**Comment by eranif** [comment]
This was already fixed.

For your current use case (figuring out if you are close to a line width) you can enable the right line margin from:
`Settings->Preferences->Editor->Right Margin Indicator`

Set it to "Line" and set the column width, you will then get a vertical line showing you when you are getting close to the line width

**Comment by AJenbo** [comment]
Well it also would be nice to know what character the carrot is on, some error messages give there position in a line+position format.

**Comment by eranif** [comment]
Like I said, this was already fixed in Git master

**Comment by AJenbo** [comment]
Arh, I see i miss under stood that part.
