### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by zodott** [eranif/codelite#1641]
hi,
I am trying to build a project in which I need to insert a .txt file with a list inside (number, name, author, etc) but while running it codelite for mac seems not to find the file (iMac-zodo-7:~ zodott$ cd /Users/zodott/Desktop/VINCE/C/aiuto/aiuto/Debug && ./aiuto 
-bash: ./aiuto: No such file or directory)
where should I place it to be read?
thanks

**Comment by eranif** [comment]
Its not really a CodeLite issue, but more of a local settings problem.
Can you please open a forum thread?
