### ISSUE TITLE
Pasting to a block/strip selection will only paste to the last line.

### ISSUE THREAD

**Issue by Paul17041993** [eranif/codelite#1643]
Pasting to a block/strip selection will only paste to the last line, for example;
```
a
b
c
```
if you copied '1' from somewhere, strip selected all 3 above lines to paste said '1' at the end you end up with
```
a
b
c1
```

**Comment by eranif** [comment]
Which version of CodeLite? and which OS?

**Comment by eranif** [comment]
I just checked this on 3 different machines (OSX, Windows and Linux Debian 8) and it works on all of them, i.e. this is the output I get:

```
a1
b1
c1
```

You should upgrade your CodeLite version

**Comment by Paul17041993** [comment]
It was the latest release and on linux.

**Comment by Paul17041993** [comment]
And seriously, stop closing bug reports without letting the reporter respond, it makes you look like a complete asshat and people wont want to support you. Use labels to mark reports with certain statuses and priority, it's what they're there for.

**Comment by Paul17041993** [comment]
https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/
https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/
https://help.github.com/articles/filtering-issues-and-pull-requests-by-labels/

**Comment by eranif** [comment]
I am closing bugs without useful information. You dont specify your OS, your CodeLite version.
So I assume that you are using an old version - and the problem does not occurs on my end...

**Comment by AJenbo** [comment]
https://github.com/textmate/textmate/wiki/Writing-Bug-Reports

What actual version are you running (many people mistakenly think they are running "the latest"), how did you aquire it, what distribution do you use.

**Comment by Paul17041993** [comment]
@eranif use a 'needsinfo' label

exact version is 10.0.0, the latest ubuntu/debian release at the time of reporting

**Comment by AJenbo** [comment]
I have had issues with the version in the Ubuntu repository. The latest version is 10.0.6 please download it from the Codelite website and see if that solves the issue.
