### ISSUE TITLE
instructions for debian binaries

### ISSUE THREAD

**Issue by androclus** [eranif/codelite#1644]
I am on debian/jessie (8.8.0), trying to download the wxwidgets31 binaries. I follow the instructions at [http://codelite.org/LiteEditor/WxWidgets31Binaries](http://codelite.org/LiteEditor/WxWidgets31Binaries). About 2/3 down the page, after adding the repo to my `/etc/apt/sources.list`,
```
deb http://repos.codelite.org/wx3.1.0/debian/ jessie libs
```
..and `apt-get update`-ing, it says I can now run:
```
apt-get install libwxbase3.1-0-unofficial \
                 libwxbase3.1-dev \
                 libwxgtk3.1-0-unofficial \
                 libwxgtk3.1-dev \
                 wx3.1-headers \
                 wx-common \
                 libwxgtk-webview3.1-0-unofficial \
                 libwxgtk-webview3.1-dev \
                 libwxgtk-media3.1-0-unofficial \
                 libwxgtk-media3.1-dev \
                 libwxbase3.1-dbg \
                 libwxgtk3.1-dbg \
                 libwxgtk-webview3.1-0-unofficial-dbg \
                 libwxgtk-media3.1-0-unofficial-dbg \
                 wx3.1-i18n \
                 wx3.1-examples \
                 wx3.1-doc
```
..but when I run that, I get the following message:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libwxbase3.1-dbg
E: Couldn't find any package by regex 'libwxbase3.1-dbg'
E: Unable to locate package libwxgtk3.1-dbg
E: Couldn't find any package by regex 'libwxgtk3.1-dbg'
E: Unable to locate package wx3.1-doc
E: Couldn't find any package by regex 'wx3.1-doc'
```
Was that instruction just for Ubuntu, perhaps?  Do some of those packages not exist on debian?

Thanks.
JS

**Comment by dghart** [comment]
Hi,

You're right. I think what happened is this:
For wx3.0 builds I use an old, much-altered and updated, debian/ from the wxWidgets source. For the wx3.1 builds I decided to simplify things a little by adapting the new, official debian/. However I'd not noticed two differences:
1)  the dbg debs now have 'unofficial' in their names e.g. libwxbase3.1-0-unofficial-dbg. This is preferable to the 3.0 way, but I forgot to change the instructions to match.
2)  I'd not noticed that the 'doc' package was no longer built (from what I know of debian policy I guess it's been separated out into a different package).

So I've updated the 3.1 instructions about the dbg packages, and removed the 'doc' file from the list. That's unnecessary anyway, as it contained only the changelog.

Thank you for reporting this. You're the first in 15 months to bother to do so, or maybe the first to notice!

Regards,

David

**Comment by androclus** [comment]
Hi David,

Thank you for your quick response!

I wish that solved it.  Unfortunately, now when I run..
```
sudo apt-get install libwxbase3.1-0-unofficial \
                 libwxbase3.1-dev \
                 libwxgtk3.1-0-unofficial \
                 libwxgtk3.1-dev \
                 wx3.1-headers \
                 wx-common \
                 libwxgtk-webview3.1-0-unofficial \
                 libwxgtk-webview3.1-dev \
                 libwxgtk-media3.1-0-unofficial \
                 libwxgtk-media3.1-dev \
                 libwxbase3.1-unofficial-dbg \
                 libwxgtk3.1-unofficial-dbg \
                 libwxgtk-webview3.1-0-unofficial-dbg \
                 libwxgtk-media3.1-0-unofficial-dbg \
                 wx3.1-i18n \
                 wx3.1-examples
```
..I get similar error messages regarding the 'unofficial' versions...
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libwxbase3.1-unofficial-dbg
E: Couldn't find any package by regex 'libwxbase3.1-unofficial-dbg'
E: Unable to locate package libwxgtk3.1-unofficial-dbg
E: Couldn't find any package by regex 'libwxgtk3.1-unofficial-dbg'
```
Any ideas?
Thx
Jeff

**Comment by androclus** [comment]
i figured it out.  Your two lines..
```
                 libwxgtk3.1-unofficial-dbg \
                 libwxgtk-webview3.1-0-unofficial-dbg \
```
are missing the extra `-0`s.  So they should be:
```
                 libwxbase3.1-0-unofficial-dbg \
                 libwxgtk3.1-0-unofficial-dbg \
```
Now all packages install.

**Comment by dghart** [comment]
You're right again. Sorry for the new mistake, which I've now corrected.

**Comment by paulspignon** [comment]
None of that works for me:
E: Unable to locate package libwxbase3.1-0-unofficial
E: Couldn't find any package by glob 'libwxbase3.1-0-unofficial'
E: Couldn't find any package by regex 'libwxbase3.1-0-unofficial'
E: Unable to locate package libwxbase3.1-dev
E: Couldn't find any package by glob 'libwxbase3.1-dev'
E: Couldn't find any package by regex 'libwxbase3.1-dev'
E: Unable to locate package libwxgtk3.1-0-unofficial
E: Couldn't find any package by glob 'libwxgtk3.1-0-unofficial'
E: Couldn't find any package by regex 'libwxgtk3.1-0-unofficial'
E: Unable to locate package libwxgtk3.1-dev
E: Couldn't find any package by glob 'libwxgtk3.1-dev'
E: Couldn't find any package by regex 'libwxgtk3.1-dev'
E: Unable to locate package wx3.1-headers
E: Couldn't find any package by glob 'wx3.1-headers'
E: Couldn't find any package by regex 'wx3.1-headers'
E: Unable to locate package libwxgtk-webview3.1-0-unofficial
E: Couldn't find any package by glob 'libwxgtk-webview3.1-0-unofficial'
E: Couldn't find any package by regex 'libwxgtk-webview3.1-0-unofficial'
E: Unable to locate package libwxgtk-webview3.1-dev
E: Couldn't find any package by glob 'libwxgtk-webview3.1-dev'
E: Couldn't find any package by regex 'libwxgtk-webview3.1-dev'
E: Unable to locate package libwxgtk-media3.1-0-unofficial
E: Couldn't find any package by glob 'libwxgtk-media3.1-0-unofficial'
E: Couldn't find any package by regex 'libwxgtk-media3.1-0-unofficial'
E: Unable to locate package libwxgtk-media3.1-dev
E: Couldn't find any package by glob 'libwxgtk-media3.1-dev'
E: Couldn't find any package by regex 'libwxgtk-media3.1-dev'
E: Unable to locate package libwxbase3.1-0-unofficial-dbg
E: Couldn't find any package by glob 'libwxbase3.1-0-unofficial-dbg'
E: Couldn't find any package by regex 'libwxbase3.1-0-unofficial-dbg'
E: Unable to locate package libwxgtk3.1-0-unofficial-dbg
E: Couldn't find any package by glob 'libwxgtk3.1-0-unofficial-dbg'
E: Couldn't find any package by regex 'libwxgtk3.1-0-unofficial-dbg'
E: Unable to locate package libwxgtk-webview3.1-0-unofficial-dbg
E: Couldn't find any package by glob 'libwxgtk-webview3.1-0-unofficial-dbg'
E: Couldn't find any package by regex 'libwxgtk-webview3.1-0-unofficial-dbg'
E: Unable to locate package libwxgtk-media3.1-0-unofficial-dbg
E: Couldn't find any package by glob 'libwxgtk-media3.1-0-unofficial-dbg'
E: Couldn't find any package by regex 'libwxgtk-media3.1-0-unofficial-dbg'
E: Unable to locate package wx3.1-i18n
E: Couldn't find any package by glob 'wx3.1-i18n'
E: Couldn't find any package by regex 'wx3.1-i18n'
E: Unable to locate package wx3.1-examples
E: Couldn't find any package by glob 'wx3.1-examples'
E: Couldn't find any package by regex 'wx3.1-examples'
:-(

**Comment by dghart** [comment]
More details would help considerably ;) .
Distro/version; the relevant line(s) in your /etc/apt/sources.list (or wherever); and perhaps the command that produced that output.
And anything else that might be relevant (e.g. x86_64 or something else?).
