### ISSUE TITLE
Display of SFTP folder structure on OS X

### ISSUE THREAD

**Issue by Malalicious** [eranif/codelite#1647]
I have used CodeLite on Windows for a while especially because of the direct editing of PHP files on a remote server using SFTP. On my Mac I have used Coda 2 for this but I decided to switch from Coda to CodeLite, however SFTP folder structure isn't  displayed correctly.

The SFTP folder structure on OS X does not apply any indentation which causes a very annoying display. On Windows it works correctly.

[See here](https://pasteboard.co/a8SVoflgX.png)

**Comment by eranif** [comment]
Thanks, I will look at this later at home when I will have my Mac access

**Comment by eranif** [comment]
This is now fixed and will be available in the next release (10.0.5)
