### ISSUE TITLE
skip to next error (ignoring warnings) feature

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#1648]
It would be nice if there was a shortcut, similar to the F4 shortcut, which jumped to the next error, skipping the warnings in between.
Shift-F4 or Ctrl-F4 ?

Useful because with modern template libraries there are often __tons__ of warnings and info messages.

thanks

**Comment by eranif** [comment]
You can skip warnings from:
settings->build settings->Build Output Appearance->Skip warnings

**Comment by grandinj** [comment]
Thanks
