### ISSUE TITLE
Upgrade cppcheck to latest

### ISSUE THREAD

**Issue by Gibbon3** [eranif/codelite#1649]
Maybe this is easy, the version of Cppcheck installed with Codelite is 1.68, but the latest is Cppcheck 1.79

Reason: Hoping newer version doesn't report errors on a 3rd party header file I have to include.

**Comment by dghart** [comment]
Hi,

Though I seldom use it myself, I do upgrade Cppcheck every year or two.

However I'd welcome outside help ;) . If you're interested, the last 2 upgrades, commits eaeb5ea and 7a39564, were just a straightforward replacement of the old Cppcheck files with the new, followed of course by testing that they compiled and worked.

Regards,

David

**Comment by AJenbo** [comment]
Pull request ready :)

**Comment by dghart** [comment]
I've now merged it. Thanks!

**Comment by AJenbo** [comment]
Your welcome, I learned a bit about CMake in the process :)
