### ISSUE TITLE
Caret displayed on incorrect position

### ISSUE THREAD

**Issue by pimlie** [eranif/codelite#1654]
Please see the following [file](https://gist.github.com/pimlie/ee2282c1a0c33caf12142ad330c5ad19). When I save that file locally and open it in Codelite 10.0.0, everything seems normal.

But when I try to select some part of the `'fields.mapping'` string, the caret is not displayed on the correct position anymore. E.g. when I use `CTRL` to move to the begin of the word `mapping`, the caret is shown between the `m` and `a`: 
![image](https://cloud.githubusercontent.com/assets/1067403/26577416/9f1c2d6c-452c-11e7-9987-c7d4940f73f5.png)

Then if I try to select the word `mapping` by using `CTRL+SHIFT+RIGHT_ARROW`, it looks like this: 
![image](https://cloud.githubusercontent.com/assets/1067403/26577507/e02f6594-452c-11e7-83c1-fb0b5816daab.png)

(If you look closely you see that the `g` is displayed light gray on the right side of the selection)

This is getting quite confusing as I have to guess where the caret really is when I am entering text. Any idea what I could do to prevent this behaviour?

**Comment by eranif** [comment]
This usually indicates a problem with encoding.
Are you using some non ASCII chars on that file? Is it possible to upload the file for testing purposes?
Have you changed the encoding to something else?

**Comment by pimlie** [comment]
As far as I am aware off I have not changed any encoding's, but I am sure I am only using normal ASCII characters in that file. I added the file as a link to a gist. If I download that gist as a raw file I can reproduce the issue.

Here is the full url: https://gist.githubusercontent.com/pimlie/ee2282c1a0c33caf12142ad330c5ad19/raw/7da0c26f790deab7160f56bbdcd7dbc2e41308cb/Tags.php

When I check the settings (Misc -> Encoding Locale) the `File font encoding` reads `UTF-8` and `Enable localization` is unticked.

**Comment by eranif** [comment]
Another possible problem: you are using non monospaced font (from the screenshot)
Try changing the font to monospaced

**Comment by pimlie** [comment]
Thanks, that seems to solve the issue indeed. I use the theme `Monokai_2` and the global font was set to 'Noto Sans'. If I change the global font to `Noto Mono` the text is correctly selected.

I am happy to close this issue, but I am quite sure I have never specifically set the Global font. Is that a default setting from the theme?

**Comment by eranif** [comment]
Probably the default font could not be found (you did not mention your OS) - so I think that wxWidgets  (the GUI toolkit) chose a font for you...

**Comment by pimlie** [comment]
Ah, that is it indeed. I am running Linux Mint 18.1 and that uses Noto Sans as default font.

Many thanks for the quick help! :+1:

**Comment by AJenbo** [comment]
The system would also have a default monospace font, so it should be possible to find a better fallback for this sort of case.

**Comment by AJenbo** [comment]
This might be helpful:

wxFont font('Nice font');
if (!font.IsFixedWidth()) {
font = wxFont(wxFONTFAMILY_TELETYPE);
}
