### ISSUE TITLE
Add option to duplicate a file

### ISSUE THREAD

**Issue by AJenbo** [eranif/codelite#1656]
Some times it makes more sense to duplicate and existing file rather then creating a new one. For this a "Duplicate", with a prompt for the new name and possibly folder path, option in the context menu for the file would be helpful.

**Comment by eranif** [comment]
This feature already exists in CodeLite
Right click on a file tab and select 'Duplicate'

**Comment by AJenbo** [comment]
Ok, slightly unexpected place for that, but also when doing so it tells me that "the file is read only, continue?" and i get the options no, cancle and yes. I don't really get what it's about, the original file wasn't read only and after clicking yes everything works like it should.
