### ISSUE TITLE
Codelite Not Opening

### ISSUE THREAD

**Issue by rlparmele** [eranif/codelite#1661]
I recently downloaded codelite.  It was working great for a while until recently.  I clicked to try and open codelite and the icon's app appeared on the side flashing and my cursor was a loading symbol.  The icon then disappeared and codelite never opened.  I've tried turning off my machine and turning it back on.  I have uninstalled and reinstalled codelite from the source website and still it been doing the same thing as before.  Any help as to why this is occurring and how to fix it would be greatly appreciated.  I am using codelite on Ubuntu 17.04 through Oracle VM VirtualBox.  Thanks.

**Comment by AJenbo** [comment]
Try renaming ~/.codelite
Also look in that folder to see what is at the end of the 3 .log files.

CodeLite exists for both Mac and Windows so why use a VM? You can also install Linux nativly on your machine ;)

**Comment by rlparmele** [comment]
At the end of the log files I'm seeing this : 

[20:50:12:408 ERR] Failed to load plugin's dll: /usr/lib/x86_64-linux-gnu/codelite/SpellCheck.so
[20:50:12:408 ERR] libhunspell-1.3.so.0: cannot open shared object file: No such file or directory
[20:50:12:417 ERR] execvp(' svn --config-dir /home/robert/.codelite/subversion status ') error: No such file or directory
[20:50:12:433 ERR] execvp(' svn --config-dir /home/robert/.codelite/subversion --version  ') error: No such file or directory
[18:38:48:940 ERR] Failed to load configuration file: /home/robert/.codelite/config/codelite.xml

That last line repeats a bit.  Also how do I go about renaming codelite?  Sorry I'm kind of new to all of this and using linux lol.  I was just told by a co-worker it was a good method to use linux while still being on windows was to download a virtual box and installing ubuntu on there.

**Comment by eranif** [comment]
the last line is the problem. 

Delete the folder `~/.codelite` and start CodeLite again

**Comment by rlparmele** [comment]
That worked!! Thank you so much I really appreciate it.  To help understand why this problem was occurring how come I had to delete the folder and start it again?  Was there just a bug causing the "Failed to load configuration file: /home/robert/.codelite/config/codelite.xml" error?

**Comment by eranif** [comment]
Your XML settings file was probably corrupted somehow.
Also, please remember to mention your codelite version

**Comment by rlparmele** [comment]
Alright cool that makes sense and sounds good I will for future issues. The version for this issue was codelite 10.04.  Thank you again for your help!

**Comment by dapobelieve** [comment]
I am having this issue on windows and ths is the second time, the first time I had to uninstall it and reinstall again. I have clicked to open the program but its just not coming up, How can I fix this?

**Comment by satwikpatel** [comment]
I recently downloaded codelite. It was working great for a while until recently. I clicked to try and open codelite and the icon's app appeared on the side flashing and my cursor was a loading symbol. The icon then disappeared and codelite never opened. I've tried turning off my machine and turning it back on. I have uninstalled and reinstalled codelite from the source website and still it been doing the same thing as before. Any help as to why this is occurring and how to fix it would be greatly appreciated. I am using codelite on windows 10. what should i do?

**Comment by AJenbo** [comment]
@satwikpatel did you try deleting/renaming the configuration folder?

**Comment by sheikh-haji** [comment]
yes still the problem is there'

**Comment by eranif** [comment]
- Close CodeLite
- Delete the folder `%appdata%\CodeLite`
