### ISSUE TITLE
Inline Editors. New feature request.

### ISSUE THREAD

**Issue by eitijupaenoithoowohd** [eranif/codelite#1664]
Instead of jumping between file tabs, inline editing lets you open a window into the code you care about most. IDE Adobe Brackets for example: 

![51521a340aeff8d05c7ce74613da1abb](https://cloud.githubusercontent.com/assets/13496056/26776248/18fb3462-49e1-11e7-950a-2aa1151d6b86.png)

**Comment by eranif** [comment]
I did some checks, and the editor component used by CodeLite (http://scintilla.org) does not support this.
So it can't be implemented

**Comment by eitijupaenoithoowohd** [comment]
((( So sad.
