### ISSUE TITLE
Old keyboard shortcut would not be replaced

### ISSUE THREAD

**Issue by BenQoo** [eranif/codelite#1668]
The reproduce steps as follow:

1. As the default setting:
`[Help] - [About]` without shortcut assigned.
`[Edit] - [Delete Line]` assign `[Ctrl-L]`.

2. Set `[Help] - [About]` to `[Ctrl-L]`.

3. CodeLite will popup this window, then choose `Yes` to replace.
![codelite_shortcut](https://user-images.githubusercontent.com/29389982/27062401-5201827e-501d-11e7-82b6-f13c12997fc2.png)

4. `[Edit] - [Delete Line]` shortcut is still exist, not be cleared. (problem)
![codelite_replace](https://user-images.githubusercontent.com/29389982/27062483-e5534ef4-501d-11e7-838e-dd22b23a2376.png)

**Comment by AJenbo** [comment]
I have the same issue, looks like some are correctly removed while others aren't.
