### ISSUE TITLE
Reloading workspace loads previous workspace

### ISSUE THREAD

**Issue by AJenbo** [eranif/codelite#1672]
When changing workspace by (either directly using workspace->open workspace or file->recent worspaces), with out first closing the current workspace, reloading the workspace (either via workspace->reload workspace or a prompt because of a changed workspace) will switch CL back to the previous workspace.

**Comment by eranif** [comment]
Not really a bug. The workspace must be closed first. I will disable the option to load workspace without closing the first one first

**Comment by eranif** [comment]
I know its not the answer you expected, but I have a very long experience with this and best solution is to force this

**Comment by AJenbo** [comment]
Yeah what I expected was that it should implicitly close the current workspace when opening another one :)

**Comment by eranif** [comment]
I just tried this on my Linux box and all the options to load a workspace are disabled when a workspace is opened. Using Debian 8/LXDE

**Comment by AJenbo** [comment]
Maybe it's only avalible because of Ubuntu global menu (menu is exported to the shell)?

**Comment by dghart** [comment]
(I switch workspaces frequently, so I patch my local install to allow me to load a different one without first closing the current. Doing so has never caused a problem here; maybe the reported crashes were OS-specific.)
FWIW, I can't reproduce the bug on debian 8, kde. A subsequent reload does what it's supposed to.
