### ISSUE TITLE
Linker flags changing automatically

### ISSUE THREAD

**Issue by jkmathew** [eranif/codelite#1677]
I am using Codelite 10.0.4(weekly build) on macOS Sierra (10.12)
I am trying to set linker flag as `pkg-config --cflags --libs opencv`
When I close settings window and open again it is showing as `pkg-config âcflags âlibs opencv` and showing error regarding no library.

How I can set linker flags properly.

**Comment by eranif** [comment]
I just tried it on OSX and it seems to work for me.
If the copy paste is correct in your post, than the `--` was converted to some unicode character `â` thus causing an error.

I am not sure why this is happening for you but maybe if you could provide an EXACT step by step reproduction I might be able to reproduce this and debug it here

**Comment by jkmathew** [comment]
It seems like working without any issue aster a system restart
