### ISSUE TITLE
OSX Debug Program Arguments

### ISSUE THREAD

**Issue by veriotis** [eranif/codelite#1680]
Under OSX when trying to apply (typing in) under **Program Settings -> General -> Debug Program Arguments** some normal (non typographic) quoted entries, like for example **"Layer"** etc. into the text field or text box, these are always wrong quoted in this word processor like fashion **„Layer“**!

I wasn't able to type in such usual "" quotes under OSX from a german keyboard, had to copy/paste from the clipboard or edit the project file afterwards. - So wrong quote entries are always written into the project file and one has to edit those with an text editor afterwards.

**Comment by AJenbo** [comment]
What language is your OS configured to use?
Try seeing what is returned by "locale" from the terminal.
Try setting it to standard English and see if the file is correctly encoded then (run code lite from the same terminal as you changed the language in):
export LANG=C

**Comment by veriotis** [comment]
It's OSX and uses the german language as default. - Well the problem is more that the Codelite IDE's UI settings text boxes seem to work like rich text interpretet input for several characters instead of plain text. Note that other IDEs and tools I use here under the same localized OS don't behave this way!

**Comment by eranif** [comment]
This seems like a wxWidgets issue, I have passed this bug to their mailing list. I will update once **I** will get an update :)

**Comment by eranif** [comment]
Here is the reply I got from Stefan Csomor (OSX maintainer of the wxWidgets library):

> This is the native behavior of a textcontrol under macOS, or rather of its ‘spell checker’. you can turn it off in several ways
> - System-wide in the keyboard system preferences, in the text tab on the right, this option is “use smart quotes and dashes”, you also see all the other ‘automatic’ options
> - In a text control instance manually via the context menu
> - Using methods Vàclav added last October :  I’d recommend the wxTextCtrl::OSXDisableAllSmartSubstitutions (=OSXEnableAutomaticDashSubstitution + OSXEnableAutomaticQuoteSubstitution)

The only option I can see here is using the first method and disabling it from the system preferences.
The third option is not a viable option since I am using an instance of `wxPropertyGridManager` and I don't have a direct access to the wxTextCtrl instance, so I can't call the new method he added `wxTextCtrl::OSXDisableAllSmartSubstitutions (=OSXEnableAutomaticDashSubstitution + OSXEnableAutomaticQuoteSubstitution)`

**Comment by veriotis** [comment]
Well switching this off system-wide is no real solution, since one will probably need those default settings for other OSX apps. So switching it back and forth just for an individual apps behaviour is not much desired. - Further other OSX apps which make use OSX textcontrols allow to type in all sort of quotes and dashes, smart and plain ones, via common OSX keyboard layouts. Thus I think it's first of all more a  wxWidgets library handling problem here.

However, thanks for your efforts in this regard!
