### ISSUE TITLE
Forward/BackSlash problem

### ISSUE THREAD

**Issue by naydef** [eranif/codelite#1690]
Hello everyone,
the picture is self-explanatory
![capture 43png](https://user-images.githubusercontent.com/14336376/27870636-0beca188-61ac-11e7-89d2-6903fcce6013.PNG)
This prevents me from building my dynamic library with the error:
cannot open input file
As you can see, the forward slash is replaced with back slash, for unknown reason. This only happens in the Build Settings
Compiler: Visual C++ 2012 (x86)
MakeFile generator: NMakeFile for MSVC toolset
Codelite version 10.0.6

**Comment by AJenbo** [comment]
Does it work with - instead of /?

**Comment by naydef** [comment]
Thanks, now it compiles fine, but still, is the slash thing a bug?

**Comment by eranif** [comment]
> Does it work with - instead of /?

Yes it does. I just checked the default settings in CodeLite, it comes like this (after the auto detection code is run):
```
D:/software/VS2013/VC/bin/link.exe -DLL -nologo
```
The reason that it changes to `\` is because of this https://github.com/eranif/codelite/blob/master/Plugin/builder_NMake.cpp#L1200

**Comment by eranif** [comment]
Fixed in git head
