### ISSUE TITLE
Error v10 stable, Build Settings window, Input error checking and or list deletion

### ISSUE THREAD

**Issue by genbtc** [eranif/codelite#1696]
Version 10.0.0 windows 10 x64 - Stable.  Fresh Install.
In the "Build Settings" window, when you go to "Add an Existing Compiler" it pops up a message asking you what to name it.  All sorts of weird behavior, surrounding that box. 
## Symptoms:
  Outright hard exit / crash or  If it doesnt crash from the bad input, it still messes up. 

## How to Reproduce: 
Simply feed bad input into that textbox.

## Desired Outcome:
Do not crash the program, dont overflow a buffer and re-display the input question window.

## Other bug i found that may be related. how to reproduce:
Settings > Build Settings.
Click + Icon to Add a new Compiler, browse to a \mingw32 directory, Select Folder
Accept Default Name (it adds successfully)
Left click the new entry, Right Click it to Delete it.
Again Click + Icon to Add a new Compiler, browse to a \mingw32 directory, Select Folder
**ERROR**: It provides the detected default name as some OTHER existing name in the list (like Visual C++ 10 (x86)), and changing the name crashes the program.

**I made a 1.5MB animated gif of what im talking about.**
[https://www.dropbox.com/s/ok35guij1nlfi0d/CodeLite%20compilerwindow%20bug%20error.gif?dl=0](https://www.dropbox.com/s/ok35guij1nlfi0d/CodeLite%20compilerwindow%20bug%20error.gif?dl=0)
After selecting/Adding a \mingw32 directory, it keeps trying to tell me the name of it its Visual C++ 14 (i guess because thats the next in the list?) and then crashes when I change the name.  In the video it crashed even before I could change the name..

## My thoughts
First I thought it was invalid input will crash the program, but now In fact I'm not even sure its "input" the program may be corrupting its own structures on its own. Because in the video below I did not alter the default inputs, just hit Select/OK.
Now I think it has something to do with the Delete operation, that an array is not being updated properly, and the array's indexes end up being mismatched and overflowing.

**Comment by eranif** [comment]
I am unable to reproduce this with latest build of CodeLite 10.0.7 (Git master build)

**Comment by genbtc** [comment]
:( well thats unfortunate. It might exist for a while then, I dont think I can get around to it. 

**Workaround:** Don't edit your compilers with unsaved source files :)
