### ISSUE TITLE
Couldn't use $ sign while using php language on CodeLite (Mac OSX)

### ISSUE THREAD

**Issue by hamidebadi** [eranif/codelite#1701]
I try to make new variable by using $sign on mac OSX, but it couldn't work for me. #PHP

**Comment by AJenbo** [comment]
What language settings is your keyboard, and what keyboard  layout do you have

**Comment by hamid96Macking** [comment]
@AJenbo 
I use Finnish keyboard and layout. For using $ sign I need to press option button and 4.
I had to change keyboard layout to English to making $ sign possible.
is there any option to do that without changing keyboard layout?

**Comment by AJenbo** [comment]
On my Linux machine I have to press alt-gr + 4. Not sure what would be different about Mac sorry.

**Comment by Kanimies** [comment]
No problems here with finnish keyboard and alt (option) + 4 - did you have a keyboard shortcut bound to that combination? 

I recall a similar issue when I first started using Codelite - check Settings->Keyboard shortcuts and remove possible shortcut bindings from the key combination - altough at the moment it would seem that none of the alt+key combinations there actually do anything, and those labelled with CTRL+another key actually mean CMD+key (such as Go to line; CTRL-G being actually CMD+G on Mac OS X)
