### ISSUE TITLE
Source code Formatter -> wrong UTF-8 literal handling

### ISSUE THREAD

**Issue by davidwed** [eranif/codelite#1702]
If you use a u8 literal the source code formatter sets the u8 String in the wrong format.

before:
const char* = u8"not a directory"

after:
const char* = u8 "not a directory"

**Comment by AJenbo** [comment]
Do you use clang-format or AStyle?

**Comment by davidwed** [comment]
clang-format

**Comment by AJenbo** [comment]
In that case the bug should be filed with the clang project. 

http://lists.llvm.org/mailman/listinfo/llvm-bugs
