### ISSUE TITLE
CodeLite runs 100% CPU when search occurrences appear in large files

### ISSUE THREAD

**Issue by sgchris** [eranif/codelite#1703]
When the search results appear in a large file (e.g. minified JS files), CL becomes very slow, 100% CPU and even freezes the system. (Ubuntu 14)

**Comment by dghart** [comment]
Just on the off-chance that this is relevant to your situation:

I've had something similar happen with large files when the Zoom Navigator plugin is active. It would be worth trying without it: Plugins > Zoom Navigator > Settings.

I'm not sure, but you may then need to restart CodeLite.
