### ISSUE TITLE
Feature request: workspace tree view - customizable directory background color 

### ISSUE THREAD

**Issue by xenogenesi** [eranif/codelite#1704]
I think would help a lot visually in projects with many directories (in particular where the sub-directories have the same name)

example:

    ├── a
    │   ├── aa
    │   ├── bb
    │   └── cc
    ├── b
    │   ├── aa
    │   ├── bb
    │   └── cc

giving directory *a* the background color red would make *a, a/aa a/bb a/cc* red (*a* and all its subdirectories)

**Comment by eranif** [comment]
I am pretty sure that wxWidgets wxTreeCtrl does not support this (the GUI toolkit)
I will check

**Comment by xenogenesi** [comment]
Thanks, appreciate you're considering (seems to have a virtual [get/set](http://docs.wxwidgets.org/trunk/classwx_tree_ctrl.html#ae55f83069faef927b8d4a4d3e45daae6)), I don't know any editor with this feature, working on project of the kind mentioned above and thought about how much would help a simple visual separation.

**Comment by eranif** [comment]
This only provide an item background colour. I dont think that this is the effect that we want, I will check this

**Comment by eranif** [comment]
Here is an example of what it looks like ( you can right click on a folder and select `Set custom background colour`):

![workspace-colouring](https://user-images.githubusercontent.com/3677711/28830294-fd895a44-76de-11e7-9cf2-f0e3b64a31de.png)

**Comment by eranif** [comment]
NOTE: I assumed here that you were talking about the C++ workspace.
This can be extended to other workspaces as well

**Comment by xenogenesi** [comment]
@eranif sorry I didn't see the message before, looks great!, and yes right click is perfect, I'm gonna try to build the master this evening. Thank you very much!

**Comment by xenogenesi** [comment]
Currently I'm working on a php project (which is the one that made me think about the colors) but I've in mind a couple of C/C++ projects for which I'm sure will be useful
