### ISSUE TITLE
console

### ISSUE THREAD

**Issue by manoshi0197** [eranif/codelite#1706]
when i build and run a project no output like "hello world" is displayed on the console window just a message prompts up saying "press any key to continue" on the console window. My version for the codelite is for windows 7 and compiler that i use is mingw.

**Comment by lovesanxx** [comment]
Can you show us your source code inside main.cpp?

**Comment by eranif** [comment]
> when i build and run a project no output like "hello world" is displayed on the console window just a message prompts up saying "press any key to continue" on the console window. My version for the codelite is for windows 7 and compiler that i use is mingw.

This is a forum question and not a bug in CodeLite. Please use [the forum](https://forums.codelite.org) for asking questions. When you do use the forum, remember to read the [HOW TO POST thread](http://forums.codelite.org/viewtopic.php?f=3&t=804)
