### ISSUE TITLE
add feature to show phpcs errors

### ISSUE THREAD

**Issue by pattisahusiwa** [eranif/codelite#1707]
Please add an option to show phpcs errors instead of auto fix the errors.

Example of the error log

![Vim error log](https://user-images.githubusercontent.com/11484016/28984768-84d900f4-799a-11e7-8f47-31fcbbaeaced.png)

**Comment by AJenbo** [comment]
You can already do this with the phpLint tool. It places a little marker to the left of the offending line that you can hover to see the error message.

![billede](https://user-images.githubusercontent.com/204594/28994292-dc05cd50-79ca-11e7-9fb9-c604b013926b.png)

**Comment by pattisahusiwa** [comment]
Just tested it. It doesn't work with `phpcs.xml` or `phpcs.xml.dist` and `ruleset.xml` (for `phpmd`) files placed on workspace directory.

**Comment by AJenbo** [comment]
What OS are you on, what version of Codelite are you using? 

Does phpcs just default to PEAR or does it not show any errors at all?

**Comment by pattisahusiwa** [comment]
OS: Arch Linux
Codelite: 10.0.7 (compiled with latest commit 828b65644b118cb79592e479dd62e1d1fe8b8850)

No, I'm using PSR2 rules and several custom rules from Generic, Squiz and PEAR. Both phpcs and phpcbf are working perfectly when executed on console directly.

**Comment by pattisahusiwa** [comment]
Also, please decide which one to use. PHPLint plugin use `phpcs` [(PHP_CodeSniffer)](https://github.com/squizlabs/PHP_CodeSniffer), while Source Code Formatter plugin use `php-cs-fixer` [(PHP-CS-Fixer)](https://github.com/FriendsOfPHP/PHP-CS-Fixer).

**Comment by AJenbo** [comment]
The Source Code Formatter plugin works with both PHP-CS-Fixer and PHP_CodeSniffer ([phpbcf](https://github.com/squizlabs/PHP_CodeSniffer/releases)). Both tools have different capabilities, witch one you want to use is up to you.

![billede](https://user-images.githubusercontent.com/204594/29002733-619cf7f2-7aa9-11e7-8b25-23ff5a3796c7.png)
![billede](https://user-images.githubusercontent.com/204594/29002729-58836cd2-7aa9-11e7-9b96-4fac598ec178.png)

Personally I find PHP-CS-Fixer useful when cleaning up an existing code base (it's able to fix issues that phpbcf doesn't handle), but use PHP_CodeSniffer on a daily basis when writing new code.

Also PHP-CS-Fixer does not appear to be usable as a linter as it only outputs a per file summery and not a per line list of issues.

**Comment by AJenbo** [comment]
I think you misunderstood my question in regards to PEAR. My question is if your issue is that it ignores your phpcs.xml configuration or doesn't place any markers at all.

Please set your log verbosity to Debug (Settings->Settings->Misc->Log), run PHP Linter on your current file (Plugins->PHP Linter->Lint Current Source). Then open the code lite log (~/.codelite/codelite.log) and look for lines contaning "PHPLint: " and post them here so I can better see what the issue might be.

**Comment by AJenbo** [comment]
It would also be helpful to see your PHP Linter configuration and general php settings (in CodeLite).

**Comment by pattisahusiwa** [comment]
Thanks. By using the log file, I can fix the issue. But, This is another issue.

On the log
```` [21:31:08:547 DBG] CodeFormatter formatting file:  errorhandler.php-code-formatter-tmp.php
[21:31:08:548 DBG] CodeFormatter running:  /usr/bin/php /usr/bin/phpcbf --encoding=UTF-8 errorhandler.php-code-formatter-tmp.php
[21:31:08:800 DBG] CodeFormatte file formatted:  errorhandler.php-code-formatter-tmp.php
[21:31:08:875 DBG] PHP: 'PRAGMA quick_check' returned: ok
[21:31:08:885 DBG] PHPLint: process terminated. output: No syntax errors detected in errorhandler.php

[21:31:09:153 DBG] PHPLint: process terminated. output: E

<?xml version="1.0" encoding="UTF-8"?>
<phpcs version="3.0.2">
<file name="errorhandler.php" errors="4" warnings="0" fixable="0">
 <error line="23" column="2" source="Squiz.Commenting.ClassComment.SpacingAfter" severity="5" fixable="0">There must be no blank lines after the class comment</error>
 <error line="37" column="8" source="Squiz.Commenting.FunctionComment.ParamCommentFullStop" severity="5" fixable="0">Parameter comment must end with a full stop</error>
 <error line="151" column="15" source="Squiz.Commenting.FunctionComment.Missing" severity="5" fixable="0">Missing function doc comment</error>
 <error line="193" column="8" source="Generic.Commenting.DocComment.NonParamGroup" severity="5" fixable="0">Tag cannot be grouped with parameter tags in a doc comment</error>
</file>
</phpcs>

[21:31:09:464 DBG] PHPLint: process terminated. output: <?xml version="1.0" encoding="UTF-8" ?>
<pmd version="@project.version@" timestamp="2017-08-06T19:31:09+07:00">
  <file name="errorhandler.php">
    <violation beginline="80" endline="80" rule="UnusedFormalParameter" ruleset="Unused Code Rules" externalInfoUrl="http://phpmd.org/rules/unusedcode.html#unusedformalparameter" priority="3">
      Avoid unused parameters such as '$errcontext'.
    </violation>
    <violation beginline="93" endline="93" rule="ExitExpression" ruleset="Design Rules" externalInfoUrl="http://phpmd.org/rules/design.html#exitexpression" priority="1">
      The method errorHandler() contains an exit expression.
    </violation>
    <violation beginline="211" endline="211" rule="UnusedLocalVariable" ruleset="Unused Code Rules" externalInfoUrl="http://phpmd.org/rules/unusedcode.html#unusedlocalvariable" priority="3">
      Avoid unused local variables such as '$key'.
    </violation>
    <violation beginline="217" endline="217" rule="UnusedLocalVariable" ruleset="Unused Code Rules" externalInfoUrl="http://phpmd.org/rules/unusedcode.html#unusedlocalvariable" priority="3">
      Avoid unused local variables such as '$args'.
    </violation>
  </file>
</pmd>

[21:31:09:465 DBG] PHPLint: searching editor for file: errorhandler.php
[21:31:09:465 DBG] PHPLint: adding error marker @%d 79
[21:31:09:465 DBG] PHPLint: adding error marker @%d 92
[21:31:09:465 DBG] PHPLint: adding error marker @%d 210
[21:31:09:465 DBG] PHPLint: adding error marker @%d 216
````
error line numbers from phpcs: 23, 37, 151, 193
and from phpmd: 80, 93, 211, 217

PHPLint add markers on phpmd errors only. Is it normal?

Also, it's hard to know are there any errors on the file without scrolling through the whole file.

**Comment by AJenbo** [comment]
It looks like your phpcs is spitting out and "E\n\n" before the actual XML part, this means that CodeLite is unable to process the result since it isn't valid XML.

I have just upgraded from phpcs 3.0.1 to 3.0.2 (the version you where using), but I don't see the issue here. Try with a smal test.php file and see if you get the same issue with the phpcs output:
`<?php

echo 'a very very very very very very very very very very very very very very very very very very very very very very long line';
`
If yes then i think you have an issue with your phpcs installation, if no then there must be something in your code that is triggering an issue in phpcs and you should probably repport the issue with them.

**Comment by AJenbo** [comment]
Just out of curiosity, what was the issue you corrected? Maybe we could update the wiki or make the setup more intuitive.

As for having a list of issues in the bottom pannel. I sort of have it on my todo list, but for now I'm working on better configuration options for php-cs-fixer and next will be phpunit intergration, so it could be a couple of months before i get around to working on that.

**Comment by pattisahusiwa** [comment]
Just several wrong configurations.

Ok, I think I've found the issue. Check both results below:

index.php
````php
<?php

echo 'a very very very very very very very very very very very very very very very very very very very very very very long line';
````

**works:**
phpcs.xml
````xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset name="PHP_CodeSniffer">
    <description>The coding standard for PHP_CodeSniffer itself.</description>
    <rule ref="PSR2"/>
</ruleset>
````
output:
````
[22:45:53:393 DBG] CodeFormatter formatting file:  index.php-code-formatter-tmp.php
[22:45:53:394 DBG] CodeFormatter running:  /usr/bin/php /usr/bin/phpcbf --encoding=UTF-8 index.php-code-formatter-tmp.php
[22:45:53:476 DBG] CodeFormatte file formatted:  index.php-code-formatter-tmp.php
[22:45:53:520 DBG] PHP: 'PRAGMA quick_check' returned: ok
[22:45:53:529 DBG] PHPLint: process terminated. output: No syntax errors detected in index.php

[22:45:53:605 DBG] PHPLint: process terminated. output: <?xml version="1.0" encoding="UTF-8"?>
<phpcs version="3.0.2">
<file name="index.php" errors="0" warnings="1" fixable="0">
 <warning line="3" column="129" source="Generic.Files.LineLength.TooLong" severity="5" fixable="0">Line exceeds 120 characters; contains 129 characters</warning>
</file>
</phpcs>

[22:45:53:613 DBG] ZombieReaperPOSIX: process 15986 exited with status code 1
[22:45:53:615 DBG] PHPLint: searching editor for file: index.php
[22:45:53:615 DBG] PHPLint: adding error marker @%d 2
[22:45:53:721 DBG] PHPLint: process terminated. output: <?xml version="1.0" encoding="UTF-8" ?>
<pmd version="@project.version@" timestamp="2017-08-06T20:45:53+07:00">
</pmd>
````

**Doesn't work:**
phpcs.xml (add `<arg value="np"/>` only)
````xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset name="PHP_CodeSniffer">
    <description>The coding standard for PHP_CodeSniffer itself.</description>
    <arg value="np"/>
    <rule ref="PSR2"/>
</ruleset>
````

output:
````
[22:47:28:066 DBG] CodeFormatter formatting file:  index.php-code-formatter-tmp.php
[22:47:28:067 DBG] CodeFormatter running:  /usr/bin/php /usr/bin/phpcbf --encoding=UTF-8 index.php-code-formatter-tmp.php
[22:47:28:154 DBG] CodeFormatte file formatted:  index.php-code-formatter-tmp.php
[22:47:28:199 DBG] PHP: 'PRAGMA quick_check' returned: ok
[22:47:28:210 DBG] PHPLint: process terminated. output: No syntax errors detected in index.php

[22:47:28:289 DBG] PHPLint: process terminated. output: .

<?xml version="1.0" encoding="UTF-8"?>
<phpcs version="3.0.2">
</phpcs>
Time: 48ms; Memory: 4Mb


[22:47:28:397 DBG] PHPLint: process terminated. output: <?xml version="1.0" encoding="UTF-8" ?>
<pmd version="@project.version@" timestamp="2017-08-06T20:47:28+07:00">
</pmd>
````

**Comment by AJenbo** [comment]
The p would enable phpcs' progresbar in the output so that explains the issue you are having. We might be able to suppress it with the q parameter, I can look in to that later today.

**Comment by AJenbo** [comment]
Closing this as the -q parameter is now being used in master, and the list of issues is already on my todo list.
