### ISSUE TITLE
[bug] Semicolon shift when typing for statement

### ISSUE THREAD

**Issue by pattisahusiwa** [eranif/codelite#1712]
Codelite: 10.0.7
OS: Arch Linux

In codelite with `Disable semicolon shift` is unchecked, when typing
````php
for ($i=0;)
````
semicolon will be shifted to the right of the close brace.

Expected:
````php
for($i = 0;)
````

Actual:
````php
for($i=0);
````

**Comment by dghart** [comment]
The `Disable semicolon shift` help string says:
"By default when typing ";" next to a close brace ")" CodeLite will move the ";" to the right. This option enables or disables this behavior".

So the behaviour you describe is actually intended. Why do you feel this is a bug?

Regards,
David

**Comment by pattisahusiwa** [comment]
Yes, I know that. This feature is really useful. I think this feature needs to consider the position of semicolon in syntax. We all know that for example
````php
var_dump(parse_url($url));
````
The semicolon must be on the right side of the close brace. But, How about this syntax?
````php
for ($i = 1; $i <= 10; $i++) {
    echo $i;
}
````
