### ISSUE TITLE
Loading of Code Completion Causes Pauses During Typing(codelite 10.0.0&10.0.6)

### ISSUE THREAD

**Issue by djqcp** [eranif/codelite#1719]
Please don't mind my poor English skills.

First,thanks to codelite team for the fantasic IDE ! Here is my report of an issue in 10.0.0 , and I did not find description on solving this issue on "what's new in 10.0.6".

Assume your editor is in c++ mode , and you've set 
"settings->code_completion->triggering->minimum_chars_to_type" to 3.
Then , please type "return 0;" in the main function at your top speed .  After "t" is displayed in the editor , there is a pause , and then "u" is displayed , together with the code_completion option of "return" . The pause is really annoying when typing fast . I guess the pause is caused by the loading of code_completion.
I think , it will be better if the editor can display what you are typing , while code_completion is simultaneously searching for what you previously typed . Wish you will solve it.

One thousand thanks again.

**Comment by eranif** [comment]
I have this option enabled and it never affected my typing speed.
Out of curiosity, what is your computer spec? (SSD drive? CPU? Number of cores? etc)

**Comment by djqcp** [comment]
ssd,i5 6200U,dual core
