### ISSUE TITLE
Code completion fails to recognize enum members on lines [2..n]

### ISSUE THREAD

**Issue by green-eyed-bear** [eranif/codelite#1720]
Code completion for "enum class" works fine if all the enum members are on the same line, but if the enum members span multiple lines like the example below, only the member from the first line shows up (in this case "apple").

enum class Foo {  apple,
                             bannana,
                             carrot };

-----------------------------------
CodeLite Version:   10.0.0
OS:  Debian 9

**Comment by eranif** [comment]
This is now fixed in git master
