### ISSUE TITLE
[HelpWanted] How to force makefile generation per project?

### ISSUE THREAD

**Issue by Mazuh** [eranif/codelite#1721]
I saw that I have an auto generated ```Makefile``` for my whole workspace. But I want CodeLite to create a simple makefile for each individual project. Is it possible? If it is, how do I do it?

I tried to select "GNU makefile onestep build" at project creation menu, but when I try to build it and run, it fails and here's the output:

> /bin/sh -c '/usr/bin/make -j4 -e -f  Makefile'
> ----------Building project:[ q1_geometria - Release ]----------
> make[1]: Entering directory '/home/mazuh/Projects/algs/src/ufrn_lp1/lab1/q1_geometria'
> make[1]: *** No rule to make target 'Release/main.c.o', needed by 'Release/q1_geometria'.  Stop.
> make[1]: *** Waiting for unfinished jobs....
> make[1]: Leaving directory '/home/mazuh/Projects/algs/src/ufrn_lp1/lab1/q1_geometria'
> Makefile:4: recipe for target 'All' failed
> make: *** [All] Error 2
> ====1 errors, 0 warnings====

For now, I'm just trying to build a "hello world" project for ```g++``` with an autogenerated makefile.

I'm new to C++ and CodeLite as well and -- just guessing -- those *.mk files are somehow related to my workspace workfile. But I don't want them! I need a simple and single makefile for my project.

**Comment by eranif** [comment]
CodeLite generates makefile per project. The global makefile just invoke them one-by-one.
