### ISSUE TITLE
Code-Completion documentation out of date

### ISSUE THREAD

**Issue by green-eyed-bear** [eranif/codelite#1723]
The documentation for "code completion", found at **http://codelite.org/LiteEditor/SettingUpCodeCompletion**, seems to be out of date.  There's a lot of references to "Retag", and I'm using version 10.0.0 and I don't see any option for "Retag".

Also, at **http://codelite.org/LiteEditor/ClangIntegration41**, you state "_This document refers to codelite 4.1 and up, if you are still using an older version of codelite please use this guide_".  While this is useful information, I don't think it's the best way to organize/display documentation.  I would think that each version of CodeLite should have it's own official documentation. In doing this, you would not have to worry about having "if using this version, then do this, otherwise to something else".

One possible way to organize it would be:

http://codelite.org/LiteEditor/Documentation/Beta/
http://codelite.org/LiteEditor/Documentation/10.0/
http://codelite.org/LiteEditor/Documentation/9.0/
http://codelite.org/LiteEditor/Documentation/8.0/

You're probably thinking now that "Hey, I don't want to maintain a bunch of different versions of documentation", and I would agree with that.  So don't.  Just leave older documentation "as-is" and move on and only maintain the current version. 

Then you could also package the documentation up with each released version of CodeLite, so people could use it offline as well, and the documentation they had would be specific to the version they were using.

For people using Linux builds (like Debian), it would also be great if you offered "apt-get install codelite-doc".

**Comment by mtangoo** [comment]
Am pretty sure it will need some way of autogeneration or else burden will be very big. If this is going to be accepted, I suggest that some automated tool i picked up and then put on github where people can contribute and @eranif and his team will be just proof-reading before they run `generate` and upload it to the site.

https://www.process.st/software-documentation/
