### ISSUE TITLE
"Build->Rebuild_Workspace" should stop when first build error is hit.

### ISSUE THREAD

**Issue by green-eyed-bear** [eranif/codelite#1727]
**Problem:**
The "Build->Rebuild_Workspace" option is great.  It allows me to build multiple related projects with a single click.  However, if there's a build error any any of those projects, CodeLite just skips to the next project and starts to build it, and the build error is no longer seen unless I manually scroll though all the output.

**Solution:**
Give user option if they want it to stop on first error, or continue building what it can.

When done, display a list of projects that were build and green/red indication of success/failure.  This "quick glance" info is important, as nobody wants to have to manually scroll though all their build output manually looking for errors.

**Comment by eranif** [comment]
This is not the purpose of this feature.
If you want to build a related projects, do this:
* Select one project as active
* Right click it and select "build order"
* select all the related projects and their build order
* Hit F7 ("build active project")

It will stop if an error occured
