### ISSUE TITLE
PHP Autocomplete list is irrelevant on "T_" (Available PHP tokens list)

### ISSUE THREAD

**Issue by sgchris** [eranif/codelite#1731]
The list should start with constants starting with "T_"

![image](https://user-images.githubusercontent.com/475849/29750533-ddea1744-8b49-11e7-8ac5-aa48bfec7ca7.png)

**Comment by AJenbo** [comment]
I belive you should be able to switch between having it suges lines containing the string (what you are currently seeing) and only lines beginning with the string (want to see)

**Comment by pattisahusiwa** [comment]
How to find those settings?

**Comment by eranif** [comment]
This can not be configured. It needs to be changed in the code
