### ISSUE TITLE
PHPDoc bug

### ISSUE THREAD

**Issue by pattisahusiwa** [eranif/codelite#1734]
Test code
````php
<?php

namespace Test;

class TestBug
{
    /** @var \PDO Database connection */
    private $var;
}
````

Inside `phpsymbols.db` file, Type hint for `$var` is `\Test\Database`. Obviously, code completion won't works.

**Comment by pattisahusiwa** [comment]
Actually, the correct syntax for `@var` is `@var [“Type”] [$element_name] [<description>]` ([http://docs.phpdoc.org/references/phpdoc/tags/var.html](http://docs.phpdoc.org/references/phpdoc/tags/var.html)), `reVarType3` is not necessary.

**Comment by eranif** [comment]
this is because we have users that have a legacy code which users the wrong order. 
`@var $name Type`

**Comment by pattisahusiwa** [comment]
Oh, I see. Just out of curiosity, I've fixed this issue on my computer and also simplify the pattern (not needed for `reVarType2`), I've found duplicate code in `PHPDocComment.cpp` and `PHPDocVar.cpp`. Why are you need both files?

Please check #1708, probably it's related to php lexer.
