### ISSUE TITLE
SFTP automatic upload

### ISSUE THREAD

**Issue by realjay007** [eranif/codelite#1737]
I have an issue with the ide when using the sftp automatic upload feature. It prefixes the project name with the name of the uploaded file.

For example, let's say I have a project 'Website' within a workspace 'Work' with 'index.php' file at the root. The web root in the remote server is usually '/var/www/html'.
After saving 'index.php', the file gets uploaded to '/var/www/html/Website/index.php' instead of '/var/www/html/index.php'. 

Is there a workaround for this?

Thanks.

**Comment by eranif** [comment]
The folder paths are set based on the **workspace** file location and the remote folder you set
Can you describe your workspace directory structure? (a screenshot or something will be great)

**Comment by realjay97** [comment]
I think I get it now. The auto upload setting is workspace level, not project level.

**Comment by eranif** [comment]
As a workaround, you could create a symlink on the server side from:

`ln -sf /var/www/html /var/www/html/Website`
