### ISSUE TITLE
horizontal scroll -> overlapping text

### ISSUE THREAD

**Issue by freanux** [eranif/codelite#1742]
if you scroll the text window to the right and the cursor IS NOT at the end of a line, on the left side, the text overlaps into the line number bar (EDIT: all lines below the cursor overlap):

![edit_bug](https://user-images.githubusercontent.com/11588703/30079350-363094fe-9280-11e7-9952-5d999bd7e29d.png)

**Comment by eranif** [comment]
What OS? which CodeLite version?
Is this a self build?

Just an FYI: this looks like a wxWidgets bug... (the editor control is part of the GUI toolkit used by CodeLite)

**Comment by freanux** [comment]
GNU/Linux Ubuntu 16.04 LTS. I just pulled and compiled CodeLite from scratch two hours ago. But this display bug has been there for a few versions.

wxWidget bug: Thanks for that info. I will get the newest version of wxWidget and recompile it. Will see what happens.

**Comment by eranif** [comment]
@freanux Can you compile the wxSTC sample and see if this problem occurs there as well? (this is the demo for the `wxStyledTextCtrl` control which is the editing component)

**Comment by dghart** [comment]
FWIW, I can't reproduce this in CodeLite 10.0.0/wx3.1.0. That's on ubuntu 16.04 running inside VirtualBox, with unity as DE.

Which DE do you use? If it's not unity, does changing it help?

**Comment by freanux** [comment]
I built the the newest version 3.1.1 with same effect.

@eranif The stc demo works correctly.
@dghart I use unity as well.

I found out, that the display error appears, if you're working with the block cursor (caret) shape.

**Comment by eranif** [comment]
@freanux this is reproducible for me also if I set the cursor to block
Is this reproducible in the wxSTC sample when using the block caret shape?

**Comment by freanux** [comment]
Unfortunately no. I changed in the wxSTC edit class the caret style to 2 (block), but it seems to work. No display error:

![edit_bug](https://user-images.githubusercontent.com/11588703/30112549-0b115424-9312-11e7-8972-d353e7da6e04.png)

**Comment by eranif** [comment]
Fixed, on GTK calling these 2 methods in `wxStyledTextCtrl` subclass:

```C++
SetTwoPhaseDraw(false);
SetBufferedDraw(false);
```

Causes this overlapping. This is now fixed in git master

**Comment by freanux** [comment]
Thanks a lot.
