### ISSUE TITLE
[Improvement] Add "exclude" option in "Find In Files" dialog

### ISSUE THREAD

**Issue by sgchris** [eranif/codelite#1743]
That would be useful to avoid looking for the search string in minified files, or some irrelevant files for the project. 
The exclude data can be provided as a mask. e.g: 
`*.min.js, *.min.css`

There should be an option to exclude folders too, e.g:
`node_modules/*`

**Comment by eranif** [comment]
I added new syntax to the "File Mask" field.
You can now use `!*min.js;!*.min.js` (notice the operator `!`)
