### ISSUE TITLE
Codelite only starts if the no plugins switch is enabled

### ISSUE THREAD

**Issue by SolarAquarion** [eranif/codelite#1744]

**Comment by eranif** [comment]
Which version of CodeLite? which platform? Please provide more information

**Comment by SolarAquarion** [comment]
CodeLite IDE v10.0.7

Archlinux x86_64

**Comment by eranif** [comment]
So I guess that this is a self built of CodeLite (we dont support ArchLinux)
You will need to debug this yourself...
Some hints:
* Have a look at `~/.codelite/codelite.log`
* Have a look at `~/.codelite/codelite-stdout-stderr.log`

**Comment by SolarAquarion** [comment]
[07:13:26:203 ERR] Failed to create single instance socket: CreateServer: bind operation failed: Address already in use

: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options

**Comment by eranif** [comment]
I would suggest to build CodeLite with LLDB debugger disabled:

1. Remove old CodeLite completely like this, from the build directory run this: `sudo xargs rm < install_manifest.txt`
2. Run CMake again, this time pass this flag `-DENABLE_LLDB=0`
3. Install CodeLite and run it

**Comment by SolarAquarion** [comment]
it works now
