### ISSUE TITLE
Zeal update to 0.4.0 

### ISSUE THREAD

**Issue by davidwed** [eranif/codelite#1745]
After the update Zeal is no longer recognized by the help plugin.

<img width="324" alt="zeal" src="https://user-images.githubusercontent.com/12169308/30165981-3ef1ef1c-93e2-11e7-8b6f-9382f5762047.PNG">

**Comment by eranif** [comment]
Thanks, is this on Windows?

**Comment by davidwed** [comment]
Yes, no problem.

**Comment by davidwed** [comment]
You can close this issue because the problem is related to the Zeal Windows installer. 

Prior to version 0.4.0 Zeal was a 32 bit application. So the dash and the dash-plugin registry command path was pointing to "C:\Program Files (x86)\Zeal\zeal.exe" "%1". After updating to version 0.4.0 the Zeal executable is a 64-bit executable ( so it is now in "C:\Program Files\Zeal\zeal.exe" ).

But the Installer don't change the registry paths ( even if I uninstall the application ).

To solve this problem you have to manually adjust the registry Values or delete the "dash" and "dash-plugin" entry's before you install Zeal 0.4.0.

The 2 registry paths:
"HKEY_CURRENT_USER\Software\Classes\dash-plugin"
"HKEY_CURRENT_USER\Software\Classes\dash"

**Comment by AJenbo** [comment]
Closing this as per the comment above and that it is confirmed to work on Linux.
