### ISSUE TITLE
Restoring rightclick remove in workspace

### ISSUE THREAD

**Issue by rayjs** [eranif/codelite#1746]
So in the workspace when I right click on a file and select remove. It would remove the file only from the workspace. There was an option that would let me also choose to remove the file from the disk. I had enabled this option. 
But now I only want to remove the file from the workspace and not delete the file from the disk. Is there an way to restore this, so that when I remove the file only gets removed from the workspace and not get deleted from the disk.

**Comment by eranif** [comment]
Settings->Preferences->Misc->History->Reset annoying dialogs answers
