### ISSUE TITLE
[Discussion] suggest build Windows CodeLite using recent MinGW-w64 GCC

### ISSUE THREAD

**Issue by zufuliu** [eranif/codelite#1747]
TDM-GCC (http://tdm-gcc.tdragon.net/bugs, https://sourceforge.net/p/tdm-gcc/bugs/321/) and pthreads-win32 (https://sourceware.org/pthreads-win32/, ftp://sourceware.org/pub/pthreads-win32/) did not updated since 2015, they are most likely discontinued.

On the other hand MinGW-w64 GCC is synchronized with main GCC development and contains many bug fixes and improvements in the compiler and runtime library. GCC is rapid evolution in recent years, has better diagnosis than ever (say issue #1748).

MinGW-w64 GCC is also used by many other open source projects (especially those build under MSYS2 environment or cross build under Linux), and available in other systems other than Windows.

I suggest build Windows CodeLite x64 using recent MinGW-w64 GCC (latest is 7.1.0, 7.2.0 is available in MSYS2) posix-seh (default in 64 bit MSYS2 and Cygwin), CodeLite x86 using posix-dwarf (default in 32 bit MinGW, MSYS2 and Cygwin). 

The posix thread model is used to enable develop CodeLite using C++11 thread and maintains portability. The SEH exception is used to provide best performance and compatibility. Since 32 bit GCC currently doesn't implement SEH (SEH for 32 bits at http://mingw-w64.org/doku.php/contribute) dwarf is chosen (SJLJ is overhead) to provide best performance.

These suites is also suggested by Qt5 (http://wiki.qt.io/MinGW-64-bit, contains detail but somewhat out dated info.), and can be directly downloaded from SourceForge (https://sourceforge.net/projects/mingw-w64/files/) or installed inside MYSY2 or installed by using other package managers.

Currently GCC runtime library is static linked in CodeLite. this can be achieved in MinGW-w64 GCC by adding linker flags `-static-libgcc -static-libstdc++` (result depends on libwinpthread-1.dll) or `-static` (no runtime library dependency). These linker flags doesn't need to add to every project in CodeLite, since most CodeLite project use linker flags that build wxWidgets, they can be added by pass LDFLAGS while building wxWidgets. (Node: If this suggestion is adopted, extras linker flags `-Wl,--allow-multiple-definition` may required to prevent windres error.)

Compare to official weekly build at https://downloads.codelite.org/, there are visualized performance improvements (especially launch and shutdown speed) by build CodeLite using x86_64-7.1.0-release-posix-seh (https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/7.1.0/threads-posix/seh/).  

Hopes this suggestion can be adopted. thanks.

**Comment by TheMasterMaind** [comment]
I did switched from the "acient" tdm gcc to MSYS2 MinGW-w64 GCC myself for my projects and it is great!

I also recommend it for codelite.

**Comment by eranif** [comment]
CodeLite for Windows 64 is now built against MinGW64/GCC7.1 SEH-WIN32 thread model
