### ISSUE TITLE
Tab cannot remember session after I closed codelite.

### ISSUE THREAD

**Issue by kwyip** [eranif/codelite#1749]
The tabs are gone and replaced by some very old ones.

**Comment by AJenbo** [comment]
What OS?

Make sure you have write permissions to the project and the settings folder.

**Comment by kwyip** [comment]
@AJenbo Mac OS

**Comment by AJenbo** [comment]
I's it possible that you do not have write permission to the project file for the workspace you have opened? Did you open the same workspace as last time?
