### ISSUE TITLE
wxWidgets 3.1: wxPrintf needs crt.h to work in console project

### ISSUE THREAD

**Issue by moonbase3** [eranif/codelite#1751]
New project 'simple executable wxWidgets enabled' (using wxWidgets 3.1):
wxPrintf does not work unless #include <wx/crt.h> added.

ref: https://www.wxwidgets.org/news/2016/02/wxwidgets-3.1.0-released/
(near bottom of page)

**Comment by dghart** [comment]
Thank you for reporting this. The project didn't compile for wx3 unless wx was built with WXWIN_COMPATIBILITY_2_8 defined.

I've now fixed this in git, commit 4e4ae8505.
