### ISSUE TITLE
gTK3 support?

### ISSUE THREAD

**Issue by jiapei100** [eranif/codelite#1753]
Hi, Eran:

Is codelite now be able to use gtk3, instead of gtk2?

Cheers
Pei

**Comment by dghart** [comment]
Hi,

On Linux, CodeLite is built against wxGTK, the Linux flavour of wxWidgets. wxGTK itself uses either gtk+2 or gtk+3, depending on the distro/version (or the whim of the self-builder).
CodeLite is perfectly happy with either gtk+2 or 3.

We provide unofficial CodeLite packages for the major distros, and use whichever gtk version is standard for that distro/version. So openSUSE packages currently use gtk+2; the fedora ones gtk+3.

Of course if you self-build wxGTK and CodeLite, you can use whichever gtk+ you prefer.

Regards,

David
