### ISSUE TITLE
PHP class generators - fix method names (camelCase) and return $this in the setter

### ISSUE THREAD

**Issue by sgchris** [eranif/codelite#1755]
![image](https://user-images.githubusercontent.com/475849/30538738-05a73f8e-9c78-11e7-81e2-07e08bfae33b.png)
1) The first letter of the method name should be lowercase
2) There should be an empty line between the methods (after the method ends)
3) Usually setters return `$this` object - so please add the return statment and add it to the PHPDoc of the method

**Comment by AJenbo** [comment]
You can change the code style with the code formatter plugin.

I might look at return $thid.

**Comment by AJenbo** [comment]
Heres what i get when generating settes and getters for a property called $dataFilePath. How did you generate yours?

![billede](https://user-images.githubusercontent.com/204594/30560764-2e1e4f16-9cb9-11e7-86d5-51582de40fa8.png)

![billede](https://user-images.githubusercontent.com/204594/30560699-fd431106-9cb8-11e7-876f-9b40fc8e4e18.png)

**Comment by AJenbo** [comment]
As noted 1 & 2 was already there as options.
I added the space between the methods and some other minor adjustments to better comply with Symfony (PSR-2) code style by default.

![billede](https://user-images.githubusercontent.com/204594/30616631-2c251250-9d93-11e7-8f44-0a748a1c1773.png)
