### ISSUE TITLE
Copy & paste functions in SVN Commit dialog are not available

### ISSUE THREAD

**Issue by Kanimies** [eranif/codelite#1757]
It's not possible to paste text into or copy text from the svn commit comment text input for some peculiar reason on OS X.
<img width="357" alt="commit dialog input" src="https://user-images.githubusercontent.com/7421922/30587312-5e7825ba-9d3b-11e7-8c1f-582a2d8d7360.png">

**Comment by Kanimies** [comment]
This problem still seems to exist as of today.

**Comment by eranif** [comment]
Fixed. Should be available next week in CodeLite 12.0.5

**Comment by Kanimies** [comment]
Still not available in 12.0.6 SVN Commit dialog on OS X

**Comment by Kanimies** [comment]
Does not work in 12.0.10
