### ISSUE TITLE
Reloading files clears the undo history

### ISSUE THREAD

**Issue by AJenbo** [eranif/codelite#1758]
It would be preferable if reloading a file from disk was seen as a new file history event, that way if the loaded copy is not what the user wanted it could still be reverted to the edited copy that was in the editor before the reload.

**Comment by AJenbo** [comment]
I see that it's by design, so possibly this should be a configurable option if some have a preference on way or the other?

**Comment by eranif** [comment]
I tried fixing this, but it seems "broken" when u do not clear the undo-buffer.
Maybe its something inside scintilla...

**Comment by AJenbo** [comment]
What issues where you having? I applied some of your changes to my local build (I'm a dummy and this functionality has saved my ass more then once), it does seam that the oldest undo-step is lost but mostly works as expected.

I use Geany as an editor and it doesn't appear to have any issues with undo after a file reload, and is also based on Scintilla afaik.

**Comment by AJenbo** [comment]
Maybe this is relevant:
https://github.com/geany/geany/blob/b1e0d0948c48153ec11e6f4b6c5fa5012c87293d/src/document.c#L1357

**Comment by eranif** [comment]
It seems to lose the last undo step, I committed it anyways

**Comment by AJenbo** [comment]
Cool, I might dig in to it a bit once I fix the issue with src-formatter. Was going to investigate another issue where the onlLad event is fired for the file in the first tab instead of the newly opened tab anyways.
