### ISSUE TITLE
The "Minimal View" is toggled automatically anytime I "Reconcile a project".

### ISSUE THREAD

**Issue by green-eyed-bear** [eranif/codelite#1761]
Whenever I add/remove files from a project, then run "Reconcile Project", when I'm done, the "Minimal View" has automatically been toggled.

To fix this (AKA to get back to my original state), I have to click "View->Toggle Minimal View" twice.

Notes:
1) My original state is NOT in "Minimal View".
2) OS: Debian 9
3) CodeLite version:  10.0.0

**Comment by eranif** [comment]
Just a FYI: if you remove a file from within CodeLite, you don't need to run reconcile project
This functionality is needed when you remove files from the file system and you want to sync the project with the actual file system

Other than that, I will look into this
