### ISSUE TITLE
Unsure about "Case sensitive match".

### ISSUE THREAD

**Issue by green-eyed-bear** [eranif/codelite#1763]
If I press "ctl-h" when a file is open, the find/replace window is displayed at the bottom of the screen.  In it, there's a button with the text "Aa", and it's tool-tip says "Case sensitive match".  The problem is, I have no idea if selecting the button turns it on or off.

I would suggest changing the "tool-tip" to give some indication if it's on or off, like in the two strings below.

"Case sensitive match:  On"

"Case sensitive match:  Off"

**Comment by eranif** [comment]
Its easy: pressed is ON, otherwise its OFF
