### ISSUE TITLE
Bad scroll performance in editor

### ISSUE THREAD

**Issue by hecaex** [eranif/codelite#1773]
I experience very bad scrolling performance inside the code editor. Whenever I scroll up or down it lags using touchpad and mouse on macOS (Both Sierra and High Sierra). 
I've tried the following Codelite versions:
Codelite Stable (10.0)
Codelite Weekly (10.0.7)

My system:
MacBook 12" early 2016
macOS 10.13 High Sierra
1.1 GHz Core m3 Processor
Intel HD 515
8GB RAM

The scrolling seem to happen on the CPU rather on the GPU. Could be some issue with syntax highlighting. 
I made a video of this issue (link below).
[https://streamable.com/bw578](https://streamable.com/bw578)

**Comment by eranif** [comment]
The scrolling is implemented by wxStyledTextCtrl which is part of the GUI toolkit we use: wxWidgets.
Please open the bug there: https://github.com/wxWidgets/wxWidgets
