### ISSUE TITLE
Adjust doxygen settings when using /*!

### ISSUE THREAD

**Issue by Phidelux** [eranif/codelite#1774]
Typing `/*!` indicates that you would like to use Qt style doc comments. It would be nice if it automatically switches to the correct scheme. However, if you manually switch the behaviour under `Settings -> Preferences -> Tweaks -> Doxygen` you can only change the block comment style to `/*!`, the class and function template. However, you can't change the general style of parameters like `@brief`, `@param` or `@return` to another scheme like `\brief `, `\param` or `\return`. Thus, if you create a new doxygen comment for a function it generates it with your scheme (in my case `/*!`), but with `@param` and `@return` attributes. So it would be nice if there where something like an attribute template.

**Comment by eranif** [comment]
CodeLite will now adjust it's "prefix" (`@` or `\`) based on the class template pattern (under `Preferences -> Tweaks -> Doxygen`)
