### ISSUE TITLE
Can't search for new line character

### ISSUE THREAD

**Issue by n0nag0n** [eranif/codelite#1776]
I just noticed when I search for the `\n` that codelite can't find it, and I think I've got it set correctly. See screenshot. I'm simply trying to search for `\n` and replace it with a comma so it's all on one line, and it can't find it.

![image](https://user-images.githubusercontent.com/2322095/31187929-2dbb95f2-a8e8-11e7-8087-870a90110c29.png)

Also, I think it'd be helpful to have hovers over what each of the different toggles for search do? From left to right I'm guessing "Close", "Case Sensitive", "Whole Phrase?" "Regex", (no idea what the pencil is). Maybe a hover over those would be helpful?

**Comment by n0nag0n** [comment]
Yeah I understand it’s not a life or death fix, and I can just use another editor to do what I need, just wondered if it could be slipped as something low priority for the future. I don’t know c++ and don’t want to try and hack and slash my way through your code base trying to put in a sub par fix for it.

**Comment by eranif** [comment]
> just wondered if it could be slipped as something low priority for the future.

this is why i did not close the ticket

**Comment by dghart** [comment]
There is already a way to do what you want:

Use the mouse to highlight the 'text' between the end of one line and the beginning of the next; then press Ctrl-R (or whatever your 'Replace' shortcut is). A unicode marker will appear in the 'Find' field; it will represent the newline character(s). Replacing with a comma will work as expected.

**Comment by n0nag0n** [comment]
Ahh I see, you guys are great! Thanks!
