### ISSUE TITLE
Why is the codelite version written to the .workspace file?

### ISSUE THREAD

**Issue by jjvbsag** [eranif/codelite#1777]
```diff
--- example.workspace	(Revision 305493)
+++ example.workspace	(Arbeitskopie)
@@ -1,5 +1,5 @@
 <?xml version="1.0" encoding="utf-8"?>
-<CodeLite_Workspace Name="example">
+<CodeLite_Workspace Name="example" Version="10.0.0">
   <Project Name="example" Path="example.project" Active="Yes"/>
   <BuildMatrix>
     <WorkspaceConfiguration Name="Debug" Selected="no"/>
```

This makes it impossible to share a project via subversion/git/... with other people using version 9.x.
You will always get conflicts on syncing. 
:disappointed:

**Comment by eranif** [comment]
The `.workspace` file is rarely modified (only when changing active project or when adding new project)
The version is needed cause I plan on changing the workspace format in the future and this needs to be part of the workspace XML file.

Another idea: tell your friends to upgrade to CodeLite 10 or later

**Comment by jjvbsag** [comment]
@eranif Sorry, but this already causes a lot of trouble right now.
Some of the developers already updated to "11.0.0", others didn't. 
```diff
--- example.workspace   (Revision 307374)
+++ example.workspace   (Arbeitskopie)
@@ -1,5 +1,5 @@
 <?xml version="1.0" encoding="utf-8"?>
-<CodeLite_Workspace Name="example" Database="./example.tags" Version="10.0.0">
+<CodeLite_Workspace Name="example" Database="./example.tags" Version="11.0.0">
```
And our build system rejects to make a release build, if there are pending changes in the project.

**Comment by eranif** [comment]
In CodeLite 10 (or was it 11 ...), we added support for workspace folder (a folder where you can group several projects), this needed a change to the workspace file format and required the addition of the Version attribute
