### ISSUE TITLE
Ctrl/Alt/Shift+F-keys hotkey issue

### ISSUE THREAD

**Issue by opravdin** [eranif/codelite#1780]
Hello! I had an issue with some hotkeys. There keyboard shortcuts that contain F keys with modificators don't work. For example (all shortcuts set to default):
- Ctrl+F: OK
- F5: OK
- F7: OK
- Ctrl+F5: Not working
- Shift+F11 (in debugging): Not working, but variables list become empty
- Alt+F7: Not working, but it switch window to maximized and back.
There is russian (serbian) and english keyboard layout

**Comment by AJenbo** [comment]
What operating system?

**Comment by opravdin** [comment]
Xubuntu 16.04
Linux D3DLAPT 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by opravdin** [comment]
Oh, when you ask me for my OS, you gave me idea. There are system global keyboard shortcuts in xubuntu: Ctrl+F(1-12) - switch to (1-12) workspace and some Alt hotkeys (basicly, to expand window etc). Here is how to change them: https://askubuntu.com/questions/90513/how-do-i-change-my-keyboard-shortcuts-in-xubuntu
