### ISSUE TITLE
Feature request: Find In Files: all files relative from workspace (and down)

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1781]
Feature request: Find In Files: all files relative from workspace (and down)

It would be nice if CodeLite for the Find In Files dialog had a pseudo path "<all files relative from workspace>" just like the existing "<Entire workspace>" - except that it would search in all files relative from workspace and down - and not only those that is included in the project/workspace

**Comment by eranif** [comment]
Is it similar to using Find-In-Files from the Explorer view?
Select the folder you want to search in the "Explorer" tab and hit `Ctrl-Shift-F` - CodeLite will open the Find-In-Files dialog with search-in field set to the the selected folder

**Comment by uffejakobsen** [comment]
Well, yes more or less (I've forgot all about the explorer for some time now :-) )
The idea was more or less that the "Add Path" button in "Find In Files" had a shortcut that would insert the path to the workspace root folder...

**Comment by AJenbo** [comment]
@eranif Would it be possible to add an exclude path. In PHP project you ofthen don't want to search the vendor folder and it can be very time consuming.
