### ISSUE TITLE
Codelite 11.0 reporting new version available, when it isn't

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1783]

**Comment by eranif** [comment]
OS? 64 or 32? can you please add some more info?

**Comment by mattreecebentley** [comment]
Sorry about that - win7 x64 sp1, non-self-compiled, x64 version. 11.0.0

**Comment by eranif** [comment]
the reason it says there is z new version is because there is a newer version. 11.0.1 (only for sin 64}. this is due to s high cpu bug.
if you don't see it (the high cpu issue). stay with 11.0.0

**Comment by mattreecebentley** [comment]
Okay, cool- you might want to note the minor version number on the download page in that case. All that's there is 11.0 presently.
Thanks-
