### ISSUE TITLE
Does codelite support embedded terminal or iTerm2 on Mac?

### ISSUE THREAD

**Issue by riguzlee** [eranif/codelite#1784]
Hi,
each time I run an application it opens a new terminal window, so I wonder if an embedded terminal is supported? Or somehow I could change the default terminal to iTerm？
I also notice that there is an option of terminal setting, but it's selected "Use build-in terminal..." and disabled.

**Comment by NoeMurr** [comment]
I have the same problem right now... Is there a solution?

**Comment by eranif** [comment]
CodeLite (master) supports Terminal or iTerm. Both are creating new instances for each terminal requested.
