### ISSUE TITLE
Problem with highlight html+php

### ISSUE THREAD

**Issue by expo87** [eranif/codelite#1786]
HI, CodeLite 11.0.2.
![9be8dbc380](https://user-images.githubusercontent.com/19946469/31889721-78f017f2-b809-11e7-971f-363366afe9fd.jpg)

**Comment by eranif** [comment]
is it possible to get a reproducible text

**Comment by expo87** [comment]
you mean source code?

**Comment by eranif** [comment]
yes, a snippet will do.

**Comment by expo87** [comment]
`<section class="works-deitals">
<div class="container">
	<div class="row works-deitals-nav">
		<div class="col-md-10 col-md-offset-1">
			<div class="row"><?

if (0 < $arResult["SECTIONS_COUNT"])
{
?>

<?foreach ($arResult['SECTIONS'] as &$arSection)
			{
				$this->AddEditAction($arSection['ID'], $arSection['EDIT_LINK'], $strSectionEdit);
				$this->AddDeleteAction($arSection['ID'], $arSection['DELETE_LINK'], $strSectionDelete, $arSectionDeleteParams);

				if (false === $arSection['PICTURE'])
					$arSection['PICTURE'] = array(
						'SRC' => $arCurView['EMPTY_IMG'],
						'ALT' => (
							'' != $arSection["IPROPERTY_VALUES"]["SECTION_PICTURE_FILE_ALT"]
							? $arSection["IPROPERTY_VALUES"]["SECTION_PICTURE_FILE_ALT"]
							: $arSection["NAME"]
						),
						'TITLE' => (
							'' != $arSection["IPROPERTY_VALUES"]["SECTION_PICTURE_FILE_TITLE"]
							? $arSection["IPROPERTY_VALUES"]["SECTION_PICTURE_FILE_TITLE"]
							: $arSection["NAME"]
						)
					);
				?>
				<div class="col-md-4 col-sm-4" id="<? echo $this->GetEditAreaId($arSection['ID']); ?>">
				<div class="item">
					<a href="<? echo $arSection['SECTION_PAGE_URL']; ?>" title="<? echo $arSection['PICTURE']['TITLE']; ?>">
					<figure><img src="<? echo $arSection['PICTURE']['SRC']; ?>"/></figure>
					<p><?=$arSection["NAME"]?></p>
					</a>
				</div>
				</div><?
			}
			
?>

<?

}
?>
</div>
</div>
</div>
</div>
</section>`

**Comment by expo87** [comment]
[codeT.zip](https://github.com/eranif/codelite/files/1407154/codeT.zip)

**Comment by pattisahusiwa** [comment]
@eranif, try this

1. Working
````html
<div>
    <div>
    </div>
</div>
````

2. Not working
````html
<div>
    <div class="">
    </div>
</div>
````

**Comment by eranif** [comment]
Thanks for the minimal example, this is now fixed
