### ISSUE TITLE
Windows recognize program as danger software

### ISSUE THREAD

**Issue by expo87** [eranif/codelite#1788]
After downloading CodeLite, Windows (1709 version) tell me next:
![1](https://user-images.githubusercontent.com/19946469/31905053-97c4801a-b835-11e7-9c66-70de3fb5a3fc.jpg)

Translate:
Windows protected your computer
The Windows Defender SmartScreen filter prevented the launch of an unidentified application that could expose the computer to a risk.

**Comment by eranif** [comment]
switch to Linux,?
now seriously, there is nothing we can do about this

**Comment by AJenbo** [comment]
English tekst:
"Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk."

You can find a guide on how to tell Windows that it is ok to run the installer:
https://www.itsupportguides.com/knowledge-base/windows-10/windows-defender-smartscreen-prevented-an-unrecognized-app-error/
