### ISSUE TITLE
Execution time

### ISSUE THREAD

**Issue by HolyFredy** [eranif/codelite#1794]
Can execution time at the end of process be add ?
Like on Code:Blocks. it is very usefull to improve coding time execution.

**Comment by eranif** [comment]
Fixed

**Comment by fullm3tal** [comment]
Can't see execution time in Ubuntu 16.04 !!

**Comment by eranif** [comment]
Why the double exclamation marks? 
Please post on the forum and provide all the information missing (CodeLite version, steps to reproduce etc)

**Comment by fullm3tal** [comment]
Hi,
Thank you for your response. The double exclamation marks weren't supposed to mean anything. I'm sorry if it bothered you.
I've posted this issue in the forums.

**Comment by FaresSalem** [comment]
Hi eranif, how can I show the execution time on CMD, I'm using version 13.0.1 on windows 10.
