### ISSUE TITLE
Error found on MacOS Sierra (10.12.6)

### ISSUE THREAD

**Issue by abitofalchemy** [eranif/codelite#1798]
Error found on MacOS Sierra (10.12.6).

I followed the instruction to compile and install wxWidgets and still get this error message on step make -j4 for codelite (note that I have Apple LLVM version 9.0.0 installed):

[ 31%] Linking CXX shared library ../lib/libplugin.dylib
<snip>
      clDockingManager::~clDockingManager() in clDockingManager.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libplugin.dylib] Error 1
make[1]: *** [Plugin/CMakeFiles/plugin.dir/all] Error 2
make: *** [all] Error 2```

**Comment by s172262** [comment]
See https://github.com/eranif/codelite/pull/1797 and Homebrew/homebrew-core#19848.
