### ISSUE TITLE
11.0.2 :code completion doesn't show abbreviations without finding other kinds of key words

### ISSUE THREAD

**Issue by djqcp** [eranif/codelite#1800]
My language is c++ . As an example,my triggering of code completion has been set to 4 chars . After  I defined an abbreviation named "linkedlist" , I typed "link" and a code completion window containing "linkedlist" " LINK_MAX" and "link" popped out . Then I changed its name into " li_nklist" and typed "li_nk" , this time nothing popped out , even after I typed its whole name "li_nklist" and waited for a while . Therefore this abbreviation  is useless , as I have no way to trigger it except by pressing enter in code completion window . I tried other names of abbreviations , and it seemed that , after typing its prefix , an abbreviation can be showed in the code completion window only if there'll be other entries appearing together with it in the window . 
If this is an issue in Codelite , I hope it would be solved . Thanks a lot to codelite team.

**Comment by djqcp** [comment]
111.0.2 -> 11.0.2 sorry

**Comment by eranif** [comment]
This is now fixed.
The solution was: 

* The word-completion plugin action (Ctrl-ENTER) was moved into CodeLite itself
* A new event is now replacing this action (wxEVT_CC_WORD_COMPLETE)
* The new event is handled by both the word-completion and the abbreviations plugin

In short:
Hit Ctrl-ENTER to see the abbreviations even without any word matches the default code completion

**Comment by djqcp** [comment]
thanks.
