### ISSUE TITLE
Horizontal tabs don't get displayed

### ISSUE THREAD

**Issue by Havoc2** [eranif/codelite#1801]
The horizontal tabs don't get displayed anymore after updating to CodeLite 11.0.3 (Windows 10 64-bit).

**Comment by eranif** [comment]
Can you post a screenshot?

**Comment by eranif** [comment]
OK, I just saw this :/
This seems to happen on some themes while working properly on other.
I did not see this at home, but when I switched to Aero theme (Windows 7) - it does shows the exact same problem

**Comment by eranif** [comment]
Changing to "Windows Classic" theme and restarting CodeLite fixes this issue...
This is very strange. I will have to look at this when I am back home.For now, you can either download CodeLite 11 or change the Windows theme.

I will remove this faulty version from the site and link back 11.0.2

**Comment by eranif** [comment]
FYI: I reverted the link on the site, you can download CodeLite 11.0.2 again

**Comment by Havoc2** [comment]
Alright, posting a screenshot anyway, just to show you how it looks at my end:

![tabs](https://user-images.githubusercontent.com/12006431/32168976-e084bcaa-bd6e-11e7-8317-75a8b3b12a72.png)

**Comment by eranif** [comment]
Out of curiosity, when change the Windows theme to "Windows Classic" does it also fixes your problem?

**Comment by Havoc2** [comment]
There is no "Windows Classic" theme under Windows 10 as far as I know.

**Comment by eranif** [comment]
Thanks. Just revert to CodeLite 11.0.2 (the link on the site which is pointing to 11.0.3 for Windows, is actually pointing to 11.0.2)

**Comment by eranif** [comment]
This is now fixed in git master

**Comment by eranif** [comment]
I have released CodeLite 11.0.4 with a fix

**Comment by Havoc2** [comment]
I can confirm that the horizontal tabs are displayed again. Thanks, eranif!
