### ISSUE TITLE
Bad font and selection color in the workspace view

### ISSUE THREAD

**Issue by Havoc2** [eranif/codelite#1802]
The colors for the font and selection in the workspace view are badly chosen, when changing the global foreground color to white and the global background color to black(-ish).

A screenshot without focus on the workspace view:

![workspace_view_selection_without_focus](https://user-images.githubusercontent.com/12006431/32170671-cb9f3eee-bd75-11e7-8aec-f2674d72a15c.png)

A screenshot with focus on the workspace view:

![workspace_view_selection_with_focus](https://user-images.githubusercontent.com/12006431/32170687-d9bc4292-bd75-11e7-9b4b-9ec0eda5451f.png)

**Comment by eranif** [comment]
CodeLite does not support true dark theme. it is written with wxwidgets which supports native controls only. the only solution is to select a non black color like grey

**Comment by Havoc2** [comment]
What a pity. Oh well, I will use gray then.
