### ISSUE TITLE
main() can't be recognized in <global> region

### ISSUE THREAD

**Issue by w4du** [eranif/codelite#1803]
In any C/C++ source file, the main() is displayed as in its previous function's region when getting focused, nor can it be displayed in "Outline" content.
(Windows 7 x64 codelite version: 11.0.4)

**Comment by eranif** [comment]
Can you post a screenshot? here is how it looks for me:
<img width="254" alt="main" src="https://user-images.githubusercontent.com/3677711/32266791-6e42999e-bef1-11e7-9510-968fa1c46c70.png">

**Comment by w4du** [comment]
![image](https://user-images.githubusercontent.com/17057675/32266973-81864a72-bf24-11e7-8818-3b73aa2d08ff.png)

**Comment by eranif** [comment]
It is displayed in the previous method, because it does not able to parse main for some reason. The two problems you described are the same.

Its probably related to that specific source code.
Is it possible to get a copy of a source code that causes this problem?

**Comment by w4du** [comment]
If there's 2 projects with 2 main() in one workspace, one main() will be missing, or maybe importing large project (with many main() in different files) from files will also result the mistake.

**Comment by eranif** [comment]
Thanks, I will look into this

**Comment by w4du** [comment]
[hello.zip](https://github.com/eranif/codelite/files/1433708/hello.zip)
Sometimes main() works fine but other functions like foo() and bar() get error blank display in the attached hello project(main.c)

**Comment by eranif** [comment]
I have re-written this entire part.
The outline and navigation bar now both parsing the file on the fly without relying on previous parsing done on the workspace (which might ignore duplicate methods with same scope and name)

I also re-written the way the "Navigation Bar" looks. It is now a custom control similar to the status bar at the bottom of the page
<img width="871" alt="nav-bar" src="https://user-images.githubusercontent.com/3677711/32298124-03ba819a-bf5a-11e7-94a2-6d0f78312cb2.png">
