### ISSUE TITLE
"Find in files" significantly slower in 11.x compared to 9.x

### ISSUE THREAD

**Issue by covex** [eranif/codelite#1807]
I've update from 9.2 Codelite to 11.0.1. Now after pressing Ctrl+Shift+F in Windows the search for a string takes significantly longer time. I thought this is just a "grep" in files on the disk so I do not understand where the performance hit cames from.

**Comment by eranif** [comment]
I just ran simple search and in files, and it behaves the same.
here is an example output:

```
====== Number of files scanned: 2611, Matches found: 29, elapsed time: 1:126 seconds ======
```

Can you post your find-in-files dialog screenshot before the search is executed? (i want to see which options are enabled)

**Comment by covex** [comment]
![image](https://user-images.githubusercontent.com/5057744/32536914-a91ae214-c460-11e7-8545-a7a920fcb517.png)

There is nothing special. My search on SSD takes now
====== Number of files scanned: 3545, Matches found: 21, elapsed time: 30:888 seconds ======

I may try somehow revert back to 9.2 to test there.

**Comment by eranif** [comment]
I have no idea... can you share your project? (if its possible)
I would like to test on the exact same conditions

**Comment by covex** [comment]
I've tried the 9.2.8 and the situation is the same there. I was pointed out that at the same time we have changed the antivirus solution, this leads me to conclusion, this is not a fault of Codelite, but the antivirus. The antivirus policy is enforced, I can not change it. Sorry for the noise.
