### ISSUE TITLE
Quick Add Previous

### ISSUE THREAD

**Issue by caibbor** [eranif/codelite#1814]
There is a feature I can't live without: Search -> Find And Replace -> Quick Add Next

I request a feature addition: Search -> Find And Replace -> Quick Add Previous

**Comment by eranif** [comment]
I assume: it adds the selection bug going backward in the document?

**Comment by caibbor** [comment]
Yes. It's really handy to be able to "Quick Add Next" and select multiple things and have several carets. So it would work the exact same way, just backward instead of forward.

It should ideally select the previous occurrence from the current caret position/item selection, even if it's already selected.
