### ISSUE TITLE
Invoking AStyle formatting with selection crashes CodeLite

### ISSUE THREAD

**Issue by audrius-u** [eranif/codelite#1819]
Invoking AStyle code formatting with selected (highlighted) text in active editor window crashes CodeLite. This has been happening quite a long time up to and including current 11.0.4. Versions before 11 simply hung, 11.0.x displays "Unhandled exception" dialog, where at least I can choose "Ignore" and save changes before restarting CodeLite.

**Comment by eranif** [comment]
Is this reproducible? I can't seems to make it crash here.
What I did:
* Changed the formatter to AStyle
* Selected text in the editor
* Hit Ctrl-I

The code was formatted successfully...
Do you have any special options enabled in AStyle?

**Comment by audrius-u** [comment]
Yes I was easily able to reproduce:
1. Install CodeLite 11.0.4 x64 on freshly installed Win10 x64 machine that has never seen CodeLite before, skip the initial wizard telling it I am happy with defaults
3. Create workspace named test, create new project named test, accept defaults (I chose MSVC, bare console project)
4. Change formatter to AStyle (in Plugins->Source code formatter->Options...->General tab)
5. Create test.cpp under src, type/paste any C/C++ code, select a few lines, press Ctrl+I
6. Resulting screenshot attached.

![image](https://user-images.githubusercontent.com/11535533/32746252-ac89d368-c8bd-11e7-92dd-ed59eddab312.png)

**Comment by eranif** [comment]
OK, this bug was hard to catch... 
This bug does not occur in debug builds, only in release builds of CodeLite.

This commit: 4bf3c545069b49302bbe17dc0c52ee8eb862711e fixes the crash

The crash itself... a tricky one to catch:
A local variable that shadowed the function argument caused the crash

The code before:

```C++
void CodeFormatter::DoFormatSelection(IEditor* editor,
                                      wxString& content,
                                      const FormatterEngine& engine,
                                      int& cursorPosition,
                                      const int& selStart,
                                      const int& selEnd)
{
    if(engine == kFormatEngineAStyle) {
        DoFormatWithAstyle(content, false);
        wxString content = editor->FormatTextKeepIndent(
                               content, selStart, Format_Text_Indent_Prev_Line | Format_Text_Save_Empty_Lines);
    } else if(engine == kFormatEngineClangFormat) {
        content = editor->GetEditorText();
        wxFileName fileName = editor->GetFileName();
        DoFormatWithClang(content, fileName, cursorPosition, selStart, selEnd);
    }
}
```

The fix changed this line:
```C++
wxString content = editor->FormatTextKeepIndent(
```

To
```C++
content = editor->FormatTextKeepIndent(
```

Note that there is already function argument named `content`

**Comment by AJenbo** [comment]
My bad :/
