### ISSUE TITLE
Codelite crash when formatting source code

### ISSUE THREAD

**Issue by ColinTaylor** [eranif/codelite#1821]
Windows 10 (64 bit) / Codelite 11.0.4

If a file is loaded into the editor, and then some text is selected, and then you do
Plugins -> Source Code Formatter -> Format Current Source
Codelite crashes

My codelite is configured to use AStyle as the formatter; I haven't tried it with the clang formatter.

Thanks, Colin

**Comment by eranif** [comment]
this bug was reported and fixed yesterday :)

**Comment by eranif** [comment]
this bug was reported and fixed yesterday :)

**Comment by eranif** [comment]
This is the commit that fixes it: 4bf3c545069b49302bbe17dc0c52ee8eb862711e
