### ISSUE TITLE
SFTP enhancement and fixes

### ISSUE THREAD

**Issue by radosi** [eranif/codelite#1822]
Hello, as I wrote in the forum : 
https://forums.codelite.org/viewtopic.php?f=3&t=3787

Could you please add the follow enhancement:

- Support sessions for SFTP accounts (e.g. re-open all previously opened for this account)
- Detect connection abort and close the tree as well (or recursively refresh the tree)
- Double click on the tree folder to expand it (same function as the icon in front of the folder name do now)
- Is it possible to mark opened files somehow ... with bold or by putting a black margin around file type icon.

That would be Awesome, since only codelite offer fast and reliable SFTP which is missing in all other modern editors even in paid.

Thanks Eran

**Comment by eranif** [comment]
Double click on the tree folder to expand it (same function as the icon in front of the folder name do now): this is now supported on latest git master
