### ISSUE TITLE
Codelite Error When Compiling Project (make.exe [All] Error)

### ISSUE THREAD

**Issue by keran96** [eranif/codelite#1823]
Hello, I get this error after compiling my project a few times. Everything goes well until it suddenly crashes. I've tried reinstalling and it doesn't help. I've also tried manually choosing a different compiler but that doesn't help either. It doesnt happen just in my computer, it happens to a few of my mates too. Im running Windows 10 (i7) on a new computer.

Help please! Thank you very much! (It does this with versions 10.0 and up)

![compilererror](https://user-images.githubusercontent.com/33696160/32846635-03254b60-ca28-11e7-8d02-a42bfaee29b7.png)

**Comment by eranif** [comment]
This is not a CodeLite bug. The compiler can't link.. you have permission denied error
Please note that CodeLite is not a compiler, just an IDE
You should post this on stackoverflow to get some help.

**Comment by AJenbo** [comment]
@keran96 this might be helpful:
https://stackoverflow.com/questions/7655471/ld-exe-cannot-open-output-file-permission-denied#7904469
