### ISSUE TITLE
add missing header feature

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#1826]
Feel free to close this if it's impractical, or just too much work.

If I see an error like:

   /home/noel/libo3/include/svl/itemset.hxx:138:16: error: no viable conversion from 'const SfxPoolItem' to incomplete type 'const XFillBmpStretchItem'

It means that I'm missing an include. It seems like Codelite (with the clang stuff enabled) should have enough information available to be able to add the correct include?

Maybe some kind of right-click refactoring tool type thingy?

Thanks.

**Comment by eranif** [comment]
Right click on the `XFillBmpStretchItem` and select "Add include file"

**Comment by grandinj** [comment]
I should have known it would be there already :-)

Unfortunately, in this case, it's template magic, so the file where the appropriate name shows up is another header file altogether, not the file where I need to add the include.

I suppose if I got around to improving the debug output pane to be more text-like and less table-like, things like this would be easier to add there.... but that's a stretch too far for me right now.

**Comment by eranif** [comment]
The dialog that pops, is editable (only the line that is marked with green). So you can fix it manually (for example: if you add a folder prefix such as: "string.h" -> "wx/string.h" CodeLite will remember this for next time and it will fix this for you.

You can also use the keyboard to move line or up

> I suppose if I got around to improving the debug output pane to be more text-like and less table-like, 
> things like this would be easier to add there.... but that's a stretch too far for me right now.

I am not sure which table are you talking about here :/

**Comment by grandinj** [comment]
For this specific case, what I have is this:

(1) I'm compiling a file called sdrattributecreator.cxx when the "incomplete type" compile error occurs.
(2) I click on the output of the compiler in the output pane, specifically on a line which says "note: forward declaration of XFillBmpStretchItem"
(3) this takes me to the xdef.hxx file
(4) where I right click on the name and select "Add include file for XFillBmpStretchItem"
(5) and it wants to add a include directive to xdef.hxx

...which  unfortunately, is not the right place to be adding the include directive - I need to add the include directive to sdrattributecreator.cxx

Now, if the build output pane was more flexible (i.e. less table-like), it should be possible to add a right-click option there to "Add include file for XFillBmpStretchItem", but I understand from a previous bugreport that the build output pane is a little restricted in it's flexibility (I can't select chunks of text there for example)

**Comment by eranif** [comment]
> he build output pane is a little restricted in it's flexibility (I can't select chunks of text there for example)
I disabled the visual effect of the "selection" (i.e. you won't see that a text is selected). BUT, it still selects :/

Also, you have a small toolbar on top of the "Build" view, one of them says: "Copy build output to clipboard" and another "paste output build into an empty editor"

Try them

**Comment by grandinj** [comment]
OK, so I copy the output to a new editor, copy the class name I need to the file where I want the action to occur, do a right-click-add-include in that file, and then delete the class name.

A little clunky, but it works, thanks!
