### ISSUE TITLE
Automatic phpDoc doesn't recognice all parameter hints correctly

### ISSUE THREAD

**Issue by AJenbo** [eranif/codelite#1828]
1: int is seen as an object
Expected
```PHP
<?php
/**
 * 
 * 
 * @param int $int 
 * 
 * @return  
 */
function test(int $int) {
}
```
Result
```PHP
<?php
/**
 * 
 * @param \int $int 
 * @return  
 */
function test(int $int) {
}
```
2: objects are always hinted as in a root namespace
Expected
```PHP
<?php
use Service\FileHandler;
/**
 * 
 * 
 * @param FileHandler $var 
 * 
 * @return  
 */
function test(FileHandler $var) {
}
```
Result
```PHP
<?php
use Service\FileHandler;
/**
 * 
 * @param \FileHandler $var 
 * @return  
 */
function test(FileHandler $var) {
}
```
3: Parameters aren't alligned
Expected
```PHP
<?php
/**
 * 
 * 
 * @param string $var 
 * @param bool   $var2 
 * 
 * @return  
 */
function test(string $var, bool $var2) {
}
```
Result
```PHP
<?php
/**
 * 
 * @param string $var 
 * @param bool $var2 
 * @return  
 */
function test(string $var, bool $var2) {
}
```
4: Nullable isn't detected
Expected
```PHP
<?php
/**
 * 
 * 
 * @param ?string   $var 
 * @param bool|null $var2 
 * 
 * @return  
 */
function test(?string $var, bool $var2 = null) {
}
```
Result
```PHP
<?php
/**
 * 
 * @param string $var 
 * @param bool $var2 
 * @return  
 */
function test(?string $var, bool $var2 = null) {
}
```
5: Nullable return types are ignored
Expected
```PHP
<?php
/**
 * 
 * 
 * @return ?bool
 */
function test(): ?bool {
}
```
Result
```PHP
<?php
/**
 * 
 * @return  
 */
function test(): ?bool {
}
```
6: Tags are not grouped
Expected
```PHP
<?php
/**
 * 
 * 
 * @param bool $var 
 * 
 * @return bool 
 */
function test(bool $var): bool {
}
```
Result
```PHP
<?php
/**
 * 
 * @param bool $var 
 * @return bool 
 */
function test(bool $var): bool {
}
```
7: Exceptions aren't automatically deteceted
Expected
```PHP
<?php
/**
 * 
 * 
 * @return  
 * 
 * @throws Exception
 */
function test() {
throw new Exception('Hi!');
}
```
Result
```PHP
<?php
/**
 * 
 * @return  
 */
function test() {
throw new Exception('Hi!');
}
```

**Comment by AJenbo** [comment]
Just to be clear:
1 & 2 are bugs
4, 5 & 7 are missing features
3 & 6 is code style to align with Symfony

**Comment by AJenbo** [comment]
I WILL work on this eventually if no one else do

**Comment by AJenbo** [comment]
Had a feeling this would come up today...

**Comment by PravinthR** [comment]
I can try to work on these issues

**Comment by AJenbo** [comment]
@PravinthR that would be grate, let me know if you need me to test or have any questions.

**Comment by AJenbo** [comment]
Case 2 happens because `PHPCodeCompletion::OnInsertDoxyBlock` removes all lines above the editor position (probably to avoid `/**` comments out all the following code), meaning that the aliases (`use` statements) are lost. This isn't an issue when using the context menu since the whole file is parsed in that case, but ironically this doesn't work with class methods for some reason.

**Comment by AJenbo** [comment]
All cases except 3 and 7 are now fixed in latest master.

Considering that throw would be a lengthy feature to implement and in my view it has little benefit, and that case 3 can be done by the code formatter plutin, I consider this issue fully fixed.
