### ISSUE TITLE
Unable to debug in W10

### ISSUE THREAD

**Issue by Icia-C** [eranif/codelite#1829]
Hi, I've been trying to debug C with codelite for weeks but until now it has been imposible, I can't find any solution anywhere.
The only clue that I've foud is that the full Output of the debugger pane shows this:
`Launching gdb from : ./Release`
Even if I try to run my program from "Debugger -> Start/Continue Debugger".
Now I'm using version 11.0.5, but I have tried this for the last 3 or 4 versions (all of them with the same results).
I already delete the "python thing" from Settings->Gdb Settings->Startup Commands.

The full Debug Output is this:

`
Using gdbinit file: C:\Users\ICA~1\AppData\Local\Temp\codelite_gdbinit.txt
Current working dir: D:\codelite_workspace\PR1
Launching gdb from : ./Release
Starting debugger  : C:\TDM-GCC-64\gdb64\bin\gdb.exe --command="C:\Users\ICA~1\AppData\Local\Temp\codelite_gdbinit.txt" --interpreter=mi "./UOCRentACar"
DEBUG>>set  new-console on
DEBUG>>set unwindonsignal on
DEBUG>>set breakpoint pending on
DEBUG>>set print object on
DEBUG>>set width 0
DEBUG>>set height 0
DEBUG>>set print elements 200
DEBUG>>00000001-break-insert -f -t main
DEBUG>>00000002-enable-pretty-printing
Debug session started successfully!
DEBUG>>00000003-exec-arguments 
DEBUG>>00000004-exec-run 
DEBUG>>=thread-group-added,id="i1"
=thread-group-added,id="i1"
DEBUG>>~"GNU gdb (GDB) 7.9.1\n"
GNU gdb (GDB) 7.9.1
DEBUG>>~"Copyright (C) 2015 Free Software Foundation, Inc.\n"
Copyright (C) 2015 Free Software Foundation, Inc.
DEBUG>>~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\n"
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type "show copying"\nand "show warranty" for details.
DEBUG>>~"This GDB was configured as \"x86_64-w64-mingw32\".\nType \"show configuration\" for configuration details."
This GDB was configured as "x86_64-w64-mingw32".\nType "show configuration" for configuration details.
DEBUG>>~"\nFor bug reporting instructions, please see:\n"
\nFor bug reporting instructions, please see:
DEBUG>>~"<http://www.gnu.org/software/gdb/bugs/>.\n"
<http://www.gnu.org/software/gdb/bugs/>.
DEBUG>>~"Find the GDB manual and other documentation resources online at:\n<http://www.gnu.org/software/gdb/documentation/>.\n"
Find the GDB manual and other documentation resources online at:\n<http://www.gnu.org/software/gdb/documentation/>.
DEBUG>>~"For help, type \"help\".\n"
For help, type "help".
DEBUG>>~"Type \"apropos word\" to search for commands related to \"word\"...\n"
Type "apropos word" to search for commands related to "word"...
DEBUG>>~"Reading symbols from ./UOCRentACar..."
Reading symbols from ./UOCRentACar...
DEBUG>>~"done.\n"
done.
DEBUG>>&"set  new-console on\n"
DEBUG>>=cmd-param-changed,param="new-console",value="on"
=cmd-param-changed,param="new-console",value="on"
DEBUG>>^done
DEBUG>>&"set unwindonsignal on\n"
DEBUG>>=cmd-param-changed,param="unwindonsignal",value="on"
=cmd-param-changed,param="unwindonsignal",value="on"
DEBUG>>^done
DEBUG>>&"set breakpoint pending on\n"
DEBUG>>=cmd-param-changed,param="breakpoint pending",value="on"
=cmd-param-changed,param="breakpoint pending",value="on"
DEBUG>>^done
DEBUG>>&"set print object on\n"
DEBUG>>=cmd-param-changed,param="print object",value="on"
=cmd-param-changed,param="print object",value="on"
DEBUG>>^done
DEBUG>>&"set width 0\n"
DEBUG>>=cmd-param-changed,param="width",value="4294967295"
=cmd-param-changed,param="width",value="4294967295"
DEBUG>>^done
DEBUG>>&"set height 0\n"
DEBUG>>^done
DEBUG>>&"set print elements 200\n"
DEBUG>>^done
DEBUG>>00000001^done,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x0000000000409600",at="<main+16>",thread-groups=["i1"],times="0",original-location="main"}
Storing internal breakpoint ID=1
DEBUG>>00000002^done
DEBUG>>00000003^done
>> Debuggee process ID: 13048
DEBUG>>=thread-group-started,id="i1",pid="13048"
=thread-group-started,id="i1",pid="13048"
DEBUG>>=thread-created,id="1",group-id="i1"
=thread-created,id="1",group-id="i1"
DEBUG>>~"[New Thread 13048.0x1dac]\n"
[New Thread 13048.0x1dac]
DEBUG>>00000004^running
Continuing...
DEBUG>>*running,thread-id="all"
*running,thread-id="all"
DEBUG>>=thread-created,id="2",group-id="i1"
=thread-created,id="2",group-id="i1"
DEBUG>>~"[New Thread 13048.0x3cbc]\n"
[New Thread 13048.0x3cbc]
DEBUG>>*running,thread-id="all"
*running,thread-id="all"
DEBUG>>=library-loaded,id="C:\\WINDOWS\\SYSTEM32\\ntdll.dll",target-name="C:\\WINDOWS\\SYSTEM32\\ntdll.dll",host-name="C:\\WINDOWS\\SYSTEM32\\ntdll.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\WINDOWS\\SYSTEM32\\ntdll.dll",target-name="C:\\WINDOWS\\SYSTEM32\\ntdll.dll",host-name="C:\\WINDOWS\\SYSTEM32\\ntdll.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\WINDOWS\\System32\\kernel32.dll",target-name="C:\\WINDOWS\\System32\\kernel32.dll",host-name="C:\\WINDOWS\\System32\\kernel32.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\WINDOWS\\System32\\kernel32.dll",target-name="C:\\WINDOWS\\System32\\kernel32.dll",host-name="C:\\WINDOWS\\System32\\kernel32.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\WINDOWS\\System32\\KernelBase.dll",target-name="C:\\WINDOWS\\System32\\KernelBase.dll",host-name="C:\\WINDOWS\\System32\\KernelBase.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\WINDOWS\\System32\\KernelBase.dll",target-name="C:\\WINDOWS\\System32\\KernelBase.dll",host-name="C:\\WINDOWS\\System32\\KernelBase.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\WINDOWS\\System32\\msvcrt.dll",target-name="C:\\WINDOWS\\System32\\msvcrt.dll",host-name="C:\\WINDOWS\\System32\\msvcrt.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\WINDOWS\\System32\\msvcrt.dll",target-name="C:\\WINDOWS\\System32\\msvcrt.dll",host-name="C:\\WINDOWS\\System32\\msvcrt.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=breakpoint-modified,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x0000000000409600",at="<main+16>",thread-groups=["i1"],times="1",original-location="main"}
=breakpoint-modified,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x0000000000409600",at="<main+16>",thread-groups=["i1"],times="1",original-location="main"}
DEBUG>>~"\nTemporary breakpoint "
\nTemporary breakpoint
DEBUG>>~"1, 0x0000000000409600 in main ()\n"
1, 0x0000000000409600 in main ()
DEBUG>>*stopped,reason="breakpoint-hit",disp="del",bkptno="1",frame={addr="0x0000000000409600",func="main",args=[]},thread-id="1",stopped-threads="all"
Internal breakpoint was hit (id=1), Applying user breakpoints and continuing
DEBUG>>00000005-break-insert -f "D:/codelite_workspace/PR1/src/main.c:20"
DEBUG>>00000006-break-insert -f "D:/codelite_workspace/PR1/src/menu.c:117"
DEBUG>>00000007-break-insert -f "D:/codelite_workspace/PR1/src/parkings.c:35"
DEBUG>>00000008-exec-continue
DEBUG>>=breakpoint-deleted,id="1"
=breakpoint-deleted,id="1"
DEBUG>>&"No source file named D:/codelite_workspace/PR1/src/main.c.\n"
DEBUG>>00000005^done,bkpt={number="2",type="breakpoint",disp="keep",enabled="y",addr="<PENDING>",pending="D:/codelite_workspace/PR1/src/main.c:20",times="0",original-location="D:/codelite_workspace/PR1/src/main.c:20"}
Found the breakpoint ID!
Storing debugger breakpoint Id=2
Successfully set breakpoint 2 at: D:\codelite_workspace\PR1\src\main.c:20
DEBUG>>&"No source file named D:/codelite_workspace/PR1/src/menu.c.\n"
DEBUG>>00000006^done,bkpt={number="3",type="breakpoint",disp="keep",enabled="y",addr="<PENDING>",pending="D:/codelite_workspace/PR1/src/menu.c:117",times="0",original-location="D:/codelite_workspace/PR1/src/menu.c:117"}
Found the breakpoint ID!
Storing debugger breakpoint Id=3
Successfully set breakpoint 3 at: D:\codelite_workspace\PR1\src\menu.c:117
DEBUG>>&"No source file named D:/codelite_workspace/PR1/src/parkings.c.\n"
DEBUG>>00000007^done,bkpt={number="4",type="breakpoint",disp="keep",enabled="y",addr="<PENDING>",pending="D:/codelite_workspace/PR1/src/parkings.c:35",times="0",original-location="D:/codelite_workspace/PR1/src/parkings.c:35"}
Found the breakpoint ID!
Storing debugger breakpoint Id=4
Successfully set breakpoint 4 at: D:\codelite_workspace\PR1\src\parkings.c:35
DEBUG>>00000008^running
Continuing...
DEBUG>>*running,thread-id="all"
*running,thread-id="all"
DEBUG>>~"[Thread 13048.0x3cbc exited with code 0]\n"
[Thread 13048.0x3cbc exited with code 0]
DEBUG>>=thread-exited,id="2",group-id="i1"
=thread-exited,id="2",group-id="i1"

`

Thank you very much. I will appreciate any help.

**Comment by eranif** [comment]
Not a bug. you can't debug  "Release" builds, it lacks debugging info. You should build your code with `-g` option
