### ISSUE TITLE
Pasting text with "Rectangle Selection" / Multiple Carets does not work as expected

### ISSUE THREAD

**Issue by caibbor** [eranif/codelite#1831]
Both of these features worked in CodeLite 10, and I think they are the same problem.

when editing with multiple selections (via "Quick Add Next"), The behavior when pasting onto these multiple selectiosn used to be that each selection would each individially be pasted onto. That was the expected behavior. Instead, now, pasting onto multiple selections results in the editor simply erasing and pasting only onto the most recently added "Quick Add Next" selection (at the most recently addeed caret)

Similarly, When copied text to clipboard which was selected using the "Rectangle Text Selection" (by holding Shift+Alt to selecting a rectangle of text on the screen) is pasted onto another rectangularly-selected section of text, the expected behavior is rectangular paste. Instead, now, the editor simply erases everything selected and pastes only on the last addeed caret.

These features greatly help with hacking out text very quickly and it would be nice to have them work again.

edit: I'm using a fairly recent version of codelite straight from git.

**Comment by caibbor** [comment]
FYI: Using the code auto-complete feature with multiple-carets seems to work properly. this is the sort of behavior that is expected from pasting as well.

**Comment by eranif** [comment]
This works as expected.
In anycase, it does not something implemented within CodeLite, its part of wxStyledTextCtrl
