### ISSUE TITLE
Loaded projects do not grey out excluded files

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1832]
If you exclude a file from a build, it greys it out.
Unfortunately it doesn't remember to do this when you load the project next time.

In addition, when swapping between builds (release to debug for example) the grey'd out files don't change, even if the excluded files are different in the other build.

**Comment by eranif** [comment]
> Unfortunately it doesn't remember to do this when you load the project next time.

Works here...
Which revision are you using?

**Comment by mattreecebentley** [comment]
Sorry, should've included that info in the first instance:
win7, non-self-compiled, 11.0.5

**Comment by eranif** [comment]
When I closed the initial bug, it is fixed in git master. i.e. 11.0.6

**Comment by eranif** [comment]
Note that even in 11.0.6 the second part of your bug report exists: it does not update it based on the current build configuration

**Comment by mattreecebentley** [comment]
Cool, thanks- why does it not work for changing build config, out of interest?

**Comment by eranif** [comment]
Since the FileView class does not capture the "Build Config Changed" event and updates the view
I will add this

**Comment by mattreecebentley** [comment]
Cool
