### ISSUE TITLE
'New look' for 11.05 does not create enough distinction between elements of the interface

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#1833]
When there's no dividing line between loaded files, or any UI hints to suggest that something can be clicked on, doesn't that render the point of a user interface redundant? Why not use a command line instead, if it's going to be so obtuse?

There's style, and then there's good UI design, and currently, codelite is bleeding into the 'flat look and no clue' crowd.

**Comment by eranif** [comment]
> When there's no dividing line between loaded files, or any UI hints to suggest that something can be 
> clicked on, doesn't that render the point of a user interface redundant? 

I assume you are talking here about the tabs. If you don't like the current style, change it.
Settings->preferences->windows and tabs->default. You will find this one to your liking

> Why not use a command line instead, if it's going to be so obtuse?

Let me know how it works for you

**Comment by mattreecebentley** [comment]
Thanks for that- I had no idea that option existed - having said that, I think a 'flat look' is bad from a usability point of view (even if it is the current 'norm').
Incidentally, where did the drop-down menu for selecting functions in the navigation bar go, in 11.0.5?

**Comment by eranif** [comment]
The drop down is going under changes now.
It is being replaced with a new bar. Which eventually will have the option to select functions for the current file. Currently it only displays the current class::function + drop down menu for the current file with various methods. Stay tuned

**Comment by eranif** [comment]
Next for the navigation bar is will be the possibility to jump to any of the bookmarks on the current file using a drop down menu as well

**Comment by mattreecebentley** [comment]
Cool.
