### ISSUE TITLE
Release build fails on openSUSE 42.3 x64

### ISSUE THREAD

**Issue by ashipov** [eranif/codelite#1834]
make fail message:
/home/user/dev/codelite/CodeLite/CxxPreProcessorScanner.cpp: In member function ‘bool CxxPreProcessorScanner::CheckIf(const Map_t&)’:
/home/user/dev/codelite/CodeLite/CxxPreProcessorScanner.cpp:265:66: error: cannot convert ‘wxString’ to ‘const char*’ for argument ‘1’ to ‘long int atol(const char*)’
             SET_CUR_EXPR_VALUE_RET_FALSE(atol(token.GetWXString()));
                                                                  ^
/home/user/dev/codelite/CodeLite/CxxPreProcessorScanner.cpp:219:31: note: in definition of macro ‘SET_CUR_EXPR_VALUE_RET_FALSE’
         cur->SetValue((double)v);
                               ^
/home/user/dev/codelite/CodeLite/CxxPreProcessorScanner.cpp:269:66: error: cannot convert ‘wxString’ to ‘const char*’ for argument ‘1’ to ‘long int atol(const char*)’
             SET_CUR_EXPR_VALUE_RET_FALSE(atol(token.GetWXString()));
                                                                  ^
/home/user/dev/codelite/CodeLite/CxxPreProcessorScanner.cpp:219:31: note: in definition of macro ‘SET_CUR_EXPR_VALUE_RET_FALSE’
         cur->SetValue((double)v);
                               ^
/home/user/dev/codelite/CodeLite/CxxPreProcessorScanner.cpp:273:66: error: cannot convert ‘wxString’ to ‘const char*’ for argument ‘1’ to ‘long int atol(const char*)’
             SET_CUR_EXPR_VALUE_RET_FALSE(atol(token.GetWXString()));
                                                                  ^
/home/user/dev/codelite/CodeLite/CxxPreProcessorScanner.cpp:219:31: note: in definition of macro ‘SET_CUR_EXPR_VALUE_RET_FALSE’
         cur->SetValue((double)v);
                               ^
/home/user/dev/codelite/CodeLite/CxxPreProcessorScanner.cpp:291:66: error: cannot convert ‘wxString’ to ‘const char*’ for argument ‘1’ to ‘double atof(const char*)’
             SET_CUR_EXPR_VALUE_RET_FALSE(atof(token.GetWXString()));
                                                                  ^
/home/user/dev/codelite/CodeLite/CxxPreProcessorScanner.cpp:219:31: note: in definition of macro ‘SET_CUR_EXPR_VALUE_RET_FALSE’
         cur->SetValue((double)v);
                               ^
CodeLite/CMakeFiles/libcodelite.dir/build.make:182: recipe for target 'CodeLite/CMakeFiles/libcodelite.dir/CxxPreProcessorScanner.cpp.o' failed
make[2]: *** [CodeLite/CMakeFiles/libcodelite.dir/CxxPreProcessorScanner.cpp.o] Error 1
CMakeFiles/Makefile2:252: recipe for target 'CodeLite/CMakeFiles/libcodelite.dir/all' failed
make[1]: *** [CodeLite/CMakeFiles/libcodelite.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dghart** [comment]
Hi,

Are you building CodeLite against the standard openSUSE wxWidgets? That wx is configured--with-stl, which is the reason for that sort of build error. 

I'm confused about which version of CodeLite you are building. As it happens, both CL 11.0 and yesterday's git head had stl build errors, but not the ones you report.

If you want to build CL 11.0, you will need first to apply the following patch:

     --- codelitephp/PHPParserUnitTests/main.cpp     2017-11-20 12:00:47.000000000 +0000
     +++ codelitephp/PHPParserUnitTests/main-patched.cpp     2017-11-20 12:00:41.000000000 +0000
     @@ -833,7 +833,7 @@
         PHPEntityBase::Ptr_t resolved = expr.Resolve(lookup, sourceFile.GetFilename().GetFullPath());
         CHECK_BOOL(resolved);
     
    -    CHECK_STRING(resolved->GetFullName(), "\\test_function_arg_type_hint_and_php_doc");
    +    CHECK_STRING(resolved->GetFullName().ToUTF8(), "\\test_function_arg_type_hint_and_php_doc");
     return true;
     }


Alternatively, the current git head, 33be4ab7, will build normally.

Regards,

David

**Comment by ashipov** [comment]
Thanks, it compiles now.
