### ISSUE TITLE
AStyle code formatting of highlighted text inserts extra newlines

### ISSUE THREAD

**Issue by audrius-u** [eranif/codelite#1838]
Invoking AStyle code formatting with highlighted text inserts extra newlines after each line (formatting without selection works correctly). Also, it should not indent the line below selection when no characters in that line are highlighted. 

Steps to reproduce: position the cursor at the beginning of any line, highlight a few indented lines with Shift+Cursor_down, hit Ctrl+I - empty lines are inserted after each highlighted line, and the next line after selection receives additional indent.

CodeLite version 11.0.5 on Win10 x64, tested on file with native Windows EOL sequence.

**Comment by AJenbo** [comment]
In regards to indenting the following line; If the cursor is on the line then the selection actually extends to that line (the line feed is selected). The formatting happens on a pr line basis and not for each individually selected character.

**Comment by audrius-u** [comment]
Your comment only arguably makes sense, I believe that  EOL character belongs to its line and not to the next. Obviously you cannot highlight EOL of last line without positioning cursor on next line, but I do not see why the next line is treated as part of highlight, when no characters of it are highlighted. Alternatively, you can select a piece of code with `Shift+cursor-up`, hit `Ctrl+I` and still the line after selection gets indented, although the cursor now was fully within selection.
It also contradicts to behavior of other actions invoked on selection, e.g. pressing TAB indents only (partially or fully) highlighted lines and not the one with cursor below selection. Same goes with `Ctrl+/` - comments out only highlighted lines, not the one below, where the cursor is. Why should code formatting behave differently from what is naturally expected?
