### ISSUE TITLE
AngelScript support

### ISSUE THREAD

**Issue by cmann1** [eranif/codelite#1839]
AngelScript is mostly  identical to c so it almost works perfectly out of the box.
One problem I have encountered though is that in recent versions code completion no longer works with object handles.
An object handles in AS uses the @ symbol, eg.
```
MyType@ var; // Declaring
@var = null; // Assigning
```
http://www.angelcode.com/angelscript/sdk/docs/manual/doc_script_handle.html

Would it be possible to fix/support this?

**Comment by eranif** [comment]
This is now fixed. This time I added a Unit Test to test for AngelScript local variables. So on the next I re-write the code completion parser, this won't get overlooked again

**Comment by cmann1** [comment]
Thanks! Really appreciate it.
