### ISSUE TITLE
[feature request:] Quick outline as a pane

### ISSUE THREAD

**Issue by Houkime** [eranif/codelite#1841]
Would be easier to navigate long files.
Right now I can't have it open and edit code at the same time because it blocks parent window input, so I need to open and close it every time. Annoying.

(OS: Arch)

**Comment by Houkime** [comment]
Ok, now that is strange.
You see, I don't have this tab in the workspace.
It might be sth with installation process I might borked out, so I need to recheck.

![wewewe](https://user-images.githubusercontent.com/32805122/33515796-8fef8616-d75f-11e7-942c-c4f50457ca0d.png)

**Comment by eranif** [comment]
Click on the 3 dots (next to the X button)
You will see list of other tabs

**Comment by Houkime** [comment]
No luck there either.
![reter](https://user-images.githubusercontent.com/32805122/33520388-dee7b2b4-d7b1-11e7-8fec-958691244ba0.png)

There are other oddities as well for example find references doesn't really work (always 0 matches).
It is highly probable that Arch AUR PKGBUILD for Codelite installation from git is screwed up somehow.
I will carefully check everything in a day or two and try to rewrite and public PKGBUILD so there are no such troubles in the future.

**Comment by eranif** [comment]
If you dont see the tabs in that list, then you don't have the plugins installed.
Probably a problem with your local build (cause I know we don't build for Arch)

**Comment by Houkime** [comment]
Rechecked. All good.
It was just not enabled in plugin management.
