### ISSUE TITLE
Code prompt remain in first monitor when codelite displayed in second extended monitor

### ISSUE THREAD

**Issue by w4du** [eranif/codelite#1843]
Windows 7 x64
Codelite 11.0.6.

**Comment by w4du** [comment]
Hi, any updates? I guess the terminology should be "code completion" rather than "code prompt", though I'm not sure what's the difference between "smart completion" and "code completion".

**Comment by anatooly** [comment]
Platform: macOS, CI 11.0.7
Code hint show on main monitor.

![2018-01-23 12-26-23](https://user-images.githubusercontent.com/317380/35274707-ca7ccf96-0045-11e8-80b8-af58cbfa414c.jpg)

Top main screen, bottom secondary.
