### ISSUE TITLE
stop build no longer working

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#1844]
Hi

Just updated from git (about two hours ago) and I see that 
    Build->Stop Build
is longer working.

This is on Linux (Ubuntu)

This is with a C++ project, with custom build commands, where the custom build command calls make.

Thanks

**Comment by eranif** [comment]
This seems to be working just fine here.
I too use CMake in custom build. It works both if I choose Build->Stop build from the menu, or if I click on the Stop build from the toolbar.

Can you check if the build process is running under the same user as CodeLite? (i.e. maybe it is a permission's problem)

**Comment by grandinj** [comment]
This is not cmake, I have 
  Customize->Custom Build
enabled, and the command is
   make connectivity
which runs regular GNU make and builds a LibreOffice module.

This is all running under the same user. 

Note that when I say "not working", I mean that the Stop Build command is greyed out.

**Comment by eranif** [comment]
> Note that when I say "not working", I mean that the Stop Build command is greyed out.

OK, this changes things :)
I need to check what are conditions to enable this button, stay tuned.

BTW, how big is your project (LibreOffice) and do you feel any speedup in loading/opening workspaces/files in CodeLite with 11.0.7?

**Comment by grandinj** [comment]
This project/workspace is very big. :-) And I have 3 different LibreOffice worksapces that I switch between regularly. 

Each workspace is about 80k files big, split into 70 projects.

CodeLite has always been pretty snappy for me, but this is a fairly powerful machine, with lots of RAM and an SSD.

Switching workspaces and opening files seems a little faster than before, but it wasn't noticeably slow before.

**Comment by eranif** [comment]
As suggested on IRC, the problem is with the UI events in the menus and not with CodeLite.
The toolbar button works as expected
