### ISSUE TITLE
Not Accepting Paths with Spaces

### ISSUE THREAD

**Issue by Sh0es** [eranif/codelite#1845]
This is how I entered my include path in my settings:
"C:\Users\gacm005user\Google Drive\Programming Docs\sauce"

and this is my build output

C:\WINDOWS\system32\cmd.exe /C C:/MinGW/bin/mingw32-make.exe -j4 SHELL=cmd.exe -e -f  Makefile
"----------Building project:[ ArrayTest - Debug ]----------"

- mingw32-make.exe[1]: Entering directory 'C:/Users/gacm005user/Google Drive/Programming Docs/CodeLite/Cpp/ArrayTest'
- clang++.exe: error: no such file or directory: 'Drive\Programming'
- clang++.exe: error: no such file or directory: 'Docs\sauce'
- clang++.exe: error: no such file or directory: 'Drive\Programming'
- clang++.exe: error: no such file or directory: 'Docs\sauce'
- mingw32-make.exe[1]: *** [Debug/up_up_up_sauce_ArrayTest.cpp.o.d] Error 1
- ArrayTest.mk:99: recipe for target 'Debug/up_up_up_sauce_ArrayTest.cpp.o.d' failed
- mingw32-make.exe[1]: Leaving directory 'C:/Users/gacm005user/Google Drive/Programming Docs/CodeLite/Cpp/ArrayTest'
- mingw32-make.exe: *** [All] Error 2
- Makefile:4: recipe for target 'All' failed

====1 errors, 0 warnings, total time: 00:00:11 seconds====

**Comment by eranif** [comment]
On Windows, don't use paths with spaces. Neither MinGW nor Clang play nicely with it

**Comment by ltqsoft** [comment]
Looks like MinGW can accept paths with spaces if we place them inside quotation marks ("").

**Comment by ShortRoundDev** [comment]
MinGW can handle paths with "" in them. If you set the path as an environment variable with quotes around them, then make/mingw can handle them. E.g:

JNI_INC = `"C:\Program Files (x86)\java\jdk-17.0.2"` (with quotes)

Include Paths = `.;$(JNI_INC)\include;$(JNI_INC)\include\win32`

Building with generated makefile, we get:

```
C:/ProgramData/chocolatey/bin/mingw32-make.exe -j4 SHELL=cmd.exe -e -f  Makefile
"----------Building project:[ kourier - Debug ]----------"
mingw32-make[1]: Entering directory 'C:/Users/shortround/source/repos/kourier/kourier/kourier'
C:/ProgramData/chocolatey/bin/g++.exe -o ..\build-Debug\bin\kourier.exe @../build-Debug/kourier/ObjectsList.txt -L. -L"C:\Program Files (x86)\java\jdk-17.0.2"\lib  -ljvm
mingw32-make[1]: Leaving directory 'C:/Users/shortround/source/repos/kourier/kourier/kourier'
=== build completed successfully (0 errors, 0 warnings) ===
```

BUT in our compile_flags.txt file, it generates:

```
-IC:\Users\shortround\source\repos\kourier\kourier\kourier
-I\\"C\Program Files (x86)\java\jdk-17.0.2"\include
-I\\"C\Program Files (x86)\java\jdk-17.0.2"\include\win32
-Ic:\programdata\chocolatey\lib\mingw\tools\install\mingw64\include\c++\11.2.0
-Ic:\programdata\chocolatey\lib\mingw\tools\install\mingw64\include\c++\11.2.0\x86_64-w64-mingw32
-Ic:\programdata\chocolatey\lib\mingw\tools\install\mingw64\include\c++\11.2.0\backward
-Ic:\programdata\chocolatey\lib\mingw\tools\install\mingw64\lib\gcc\x86_64-w64-mingw32\11.2.0\include
-Ic:\programdata\chocolatey\lib\mingw\tools\install\mingw64\include
-Ic:\programdata\chocolatey\lib\mingw\tools\install\mingw64\lib\gcc\x86_64-w64-mingw32\11.2.0\include-fixed
-Ic:\programdata\chocolatey\lib\mingw\tools\install\mingw64\x86_64-w64-mingw32\include
-target
x86_64-w64-mingw32
```

Notice lines 2 & 3. The paths are being mangled before being put into the file

There's no good reason codelite *can't* support them as well (though that's not the same thing as good reasons that codelite *won't* suport them)

BUT for anyone else searching in 2022 for a solution that doesn't involve renaming some major system folders, then a crappy workaround is to create a symlink for any folders in your path with spaces in them in Windows Terminal (Powershell), i.e:

`C:\> New-Item -ItemType SymbolicLink -Path "C:\pf86" -Target "C:\Program Files (x86)\"`
`C:\> New-Item -ItemType SymbolicLink -Path "C:\pf" -Target "C:\Program Files\"`

Then use those in your path like:

`C:\pf86\java\jdk-17.0.2\include`

the compile_flags.txt file spits out:

```
-IC:\Users\shortround\source\repos\kourier\kourier\kourier
-IC:\pf86\java\jdk-17.0.2\include
-IC:\pf86\java\jdk-17.0.2\include\win32
-Ic:\programdata\chocolatey\lib\mingw\tools\install\mingw64\include\c++\11.2.0
-Ic:\programdata\chocolatey\lib\mingw\tools\install\mingw64\include\c++\11.2.0\x86_64-w64-mingw32
-Ic:\programdata\chocolatey\lib\mingw\tools\install\mingw64\include\c++\11.2.0\backward
-Ic:\programdata\chocolatey\lib\mingw\tools\install\mingw64\lib\gcc\x86_64-w64-mingw32\11.2.0\include
-Ic:\programdata\chocolatey\lib\mingw\tools\install\mingw64\include
-Ic:\programdata\chocolatey\lib\mingw\tools\install\mingw64\lib\gcc\x86_64-w64-mingw32\11.2.0\include-fixed
-Ic:\programdata\chocolatey\lib\mingw\tools\install\mingw64\x86_64-w64-mingw32\include
-target
x86_64-w64-mingw32
```

So for any windows devs in 2022: no, you're not crazy, and here's a workaround
