### ISSUE TITLE
enhencement : automatically refresh outline page

### ISSUE THREAD

**Issue by s0cks5** [eranif/codelite#1848]
It seems that the outline plugin does not refresh itself even when I reopen a file(ctrl+R) or save a file . It can only refresh itself when I reopen the plugin . I suggest that outline refreshes the contents of its tab regularly(for example , every 30 sec ? ) .
Thanks a lot to Codelite developer(s) for this wonderful IDE and careful answers to our questions.

**Comment by eranif** [comment]
This is not an enhancement, it's a bug... I am looking into it now
