### ISSUE TITLE
(feature request) Add option to disable 'jumping' in explorer tree when selecting/closing another tab

### ISSUE THREAD

**Issue by pimlie** [eranif/codelite#1851]
Unfortunately I could not find any option under preferences to change this behaviour. I use folders to separate my php and javascript projects in the 'Explorer' tree and have often multiple folders/projects open at the same time (eg backend and frontend folders for a project). While working this way you have often opened multiple folders in multiple projects and have a large tree visible in the Explorer view.
Now when you have multiple files opened as tabs and close one, the explorer tree automatically jumps to the location of the next open file. This behaviour can be quite annoying when you are checking/searching multiple files and repeatedly have to click open/close multiple files. Eg if you are searching in project 'ZZZ' but the next open file is in project 'AAA' the tree jumps from project folder 'ZZZ' to the file in project 'AAA' and you first have to scroll the explorer view back to project 'ZZZ' again to open another file in that project.

Hope I explained it clearly :)

**Comment by eranif** [comment]
Which workspace are we talking about here (PHP, JS or C++)?

**Comment by pimlie** [comment]
I dont think I use workspaces in that sense, eg in my workspace pane I select the 'Explorer' tab and not Workspace, Tabs or Tabgroups.

**Comment by pimlie** [comment]
Hope this image clarifies the view I am using: ![image](https://user-images.githubusercontent.com/1067403/33826084-18514002-de64-11e7-9d88-5ce0bcfd3826.png)

**Comment by pimlie** [comment]
@eranif Thank you very much for adding this feature (and 1852), works great!
