### ISSUE TITLE
[bug] error when building optimized_cxx_project on CodeFormatter

### ISSUE THREAD

**Issue by aviallon** [eranif/codelite#1854]
When I try to compile I get "error: ‘for_each’ is not a member of ‘std’" on codeformatter.cpp file (line 678)
Adding `#include <algorithm>` at the begining of the file solves the problem, but you may want to solve that a little bit better than me.

**Comment by eranif** [comment]
As I explained in the PR, this branch is obsolete

**Comment by aviallon** [comment]
Oh ok I didn't see that. Thank you.
