### ISSUE TITLE
[Feature Request] Add line height settings to CodeLite

### ISSUE THREAD

**Issue by azrinaziz** [eranif/codelite#1861]
Adding line height setting according to user's preferences can improve readability on certain monospace fonts / reading in general. There are a lot of IDE / Text Editors which have this setting.

**Comment by eranif** [comment]
I just re-read the documentation of the editing component and it says that the line height is calculated based on the height of the font for that line. There is only the possibility of getting the line height, nothing more

http://www.scintilla.org/ScintillaDoc.html#SCI_TEXTHEIGHT
