### ISSUE TITLE
[Feature Request] Add another workspace as project in workspaces

### ISSUE THREAD

**Issue by iHardRock** [eranif/codelite#1862]
Say you have some independent projects (with CodeLite workspaces) in different repositories. Now you want to create another one with own CodeLite workspace and connect other as submodules, for example. 
Should be very useful to add another workspaces as projects in your current workspace. From main workspace you should able to build outer workspace with workspace configuration name == project configuration (as is workspace = project)
Really need this feature :)

**Comment by eranif** [comment]
Any mixing between multiple workspace will not be implemented.
One of the basic assumption is that there can be only one workspace. Changing that will need to re-write 1/2 of the IDE... You can workaround things like that by using custuom makefile projects within your workspace

**Comment by iHardRock** [comment]
Code browsing is a problem, right? But this not really needed, only build and configuration selection required. Custom makefile may be a solution, but this looks less comfortable for me in meantion of "module oriented development" 

I checked out code today and it's look promising. 
OK, I'll try to implement this feature. I'm using codelite as primary ide for about 4 years, may be it's time to start develop something useful for this :)

**Comment by eranif** [comment]
*You* assumes that "code browsing" is not needed, but another person will open this as a bug (simply because it is expected to work)
