### ISSUE TITLE
Left shift tab is broken

### ISSUE THREAD

**Issue by pattisahusiwa** [eranif/codelite#1866]
Feature #1382 has been broken on the last update.

OS: Arch Linux
Codelite version 11.0.7 (Custom build with latest commit 23fc0abd8dad7c63d7808cffc5c1028632a95427)

![bug](https://user-images.githubusercontent.com/11484016/34438885-37de82b2-eced-11e7-9062-4b2995e54bc5.png)

**Comment by eranif** [comment]
It's not broken. It's on purpose. The #1382 has an annoying side effect of moving the selected tab to the left (when not fully visible)
I am pretty happy with the current result. You can fork CodeLite and fix it locally.
