### ISSUE TITLE
UI Rendering Issue

### ISSUE THREAD

**Issue by cgloeckner** [eranif/codelite#1868]
I just installed CodeLite via CodeLite-11.0.7-gtk2-ubuntu-trusty-x86_64.deb on my Kubuntu 14.04 but the UI Rendering seems to be somehow broken:
![snapshot1](https://user-images.githubusercontent.com/3219690/34615830-73898642-f236-11e7-839b-c78c7b3de9a9.png)
I already tried all available themes but the problem remains.

```
glocke@glocke:~$ lspci -k | grep -EA3 'VGA'
01:00.0 VGA compatible controller: NVIDIA Corporation GF116 [GeForce GTS 450 Rev. 2] (rev a1)
	Subsystem: ASUSTeK Computer Inc. Device 83b9
	Kernel driver in use: nvidia
01:00.1 Audio device: NVIDIA Corporation GF116 High Definition Audio Controller (rev a1)
```

Which additional information do you need?

**Comment by AJenbo** [comment]
Have you tried rebooting. It looks like GTK is having problems accessing the system theme. I noticed you are using KDE, do other GTK applications look correct?

**Comment by eranif** [comment]
I just tested it and works fine on 2 machines I have tested.
Is it possible to try a different window manager? (maybe lightdm? or lxdm?)

**Comment by cgloeckner** [comment]
Thanks for your ideas. Unfortunately, neither reboot nor using lxdm helped.
![lxdm](https://user-images.githubusercontent.com/3219690/34639047-93757eb4-f2d8-11e7-99a4-6d926f3c0da1.png)

Other GTK Applications look correct (tested with gedit).

**Comment by dghart** [comment]
Hi,

The other thing to say is that trusty is old: xenial is the current LTS version, and that's only until April.

I no longer have my trusty kubuntu virtualbox guest. FWIW, my xenial kubuntu doesn't have this problem.

Regards,

David

**Comment by cgloeckner** [comment]
David is right, unfortunately I'm bound to KXStudio (based on 14.04) for multiple reasons. So I cannot upgrade that easy.

**Comment by eranif** [comment]
Is it possible to build CodeLite from sources?

**Comment by cgloeckner** [comment]
I need to find a repo for `libwxsqlite3-3.0-dev` first.

**Comment by eranif** [comment]
Have you looked at this page:
http://codelite.org/Developers/Linux ?

**Comment by cgloeckner** [comment]
Now I have a working CodeLite, built from source :-)
