### ISSUE TITLE
Codelite does not automatically detect 3rd party included headers

### ISSUE THREAD

**Issue by Pawn0** [eranif/codelite#1870]
Codelite should automatically detect 3rd party included headers and make them available for autocomplete.
 
I should provide an example for this to go anywhere. 
  
Example:

I wish to do SFML things, so I link and provide the includes.
However, for SFML to know of the headers, I must first include them with an #include 
In other IDEs, it works automatically.  
  
Is it possible that I am missing a feature or a setting?

**Comment by eranif** [comment]
Hmm... it does.
Can you please provide a minimal reproduction workspace? (zip and attach it, also please remember to state which 3rd party libraries I should install)

**Comment by eranif** [comment]
Closes. No response
