### ISSUE TITLE
Commit d3e1176 sdk/libssh/lib/libssh64.dll not built correctly

### ISSUE THREAD

**Issue by guy-rouillier** [eranif/codelite#1872]
See https://forums.codelite.org/viewtopic.php?f=13&t=3832

When I build CodeLite from git using MingW-w64, the build completes successfully.  But trying to run the resulting binaries results in a popup window saying the system cannot locate libssh.dll.  Copying libssh64.dll to libssh.dll allows the app to run.

If I look at the latest libssh64.dll and regex search for "libssh.*\.dll", I find the string libssh.dll.  If I do the same for the previous commit 84c9216, I find the string libssh64.dll.  I'm guessing that string is the exported module name.  That's probably why the loader is looking for libssh.dll instead of libssh64.dll.

The same condition exists in libssh64.dll.a.

**Comment by eranif** [comment]
In the installer file, I have this line:
```
Source: "{#CODELITE_ROOT}\sdk\libssh\lib\libssh64.dll"; DestDir: "{app}\"; DestName: "libssh.dll"; Flags: ignoreversion ; 
```
I have fixed `update64.bat` script to do the same
