### ISSUE TITLE
Codelite isn´t responding when I run it after build

### ISSUE THREAD

**Issue by Chetan6491** [eranif/codelite#1875]
Hello All,

I am using Codelite for the first time. I can successfully build code, but Codelite remains unresponsive to the Run command (or to ctrl+F5). Below is the screenshot of thhhe build log. 

![selection_020](https://user-images.githubusercontent.com/28564788/35046530-2360ec98-fb8f-11e7-9aaf-a1837145ea5a.png)

What could possibly be the cause of this issue? i can´t find any documentation on the subject.

Codelite version : 11.0.8

Best regards,
Chetan

**Comment by dghart** [comment]
There are 2 issues here:

1) The important thing is that the build is actually failing, as you can see from the output: 'cannot find -lgsl'. A quick google suggests you have a missing dev package...

2) CodeLite is failing to notice that error. It parses the build output looking for errors and warnings, but for some reason misses that one.

If you fix the first,  the second one won't matter ;)
