### ISSUE TITLE
[php] Autocomplete doesn't work properly with @property and @method

### ISSUE THREAD

**Issue by pattisahusiwa** [eranif/codelite#1877]
1. Autocomplete hint issue

**Test case:**
````php
<?php
/**
 * @property PDO $pdo1
 * @property DateTime $dt
 */
class ClassA
{
    public $name;
    /**
     * @var PDO
     */
    public $pdo2;
    public function __construct()
    {
        $this->pdo1-> // should display autocomplete here
    }
}
````

**Comment by pattisahusiwa** [comment]
2. Method doesn't show in autocomplete list
**Test case:**
````php
<?php
/**
 * @property PDO $pdo1
 * @method PDO getPDO()
 */
class ClassA
{
    public $name;
    /**
     * @var PDO
     */
    public $pdo2;
    public function __construct()
    {
        $this->    // getPDO?
    }
}
````

Change order of `@property` and `@method` also doesn't work.
````php
<?php
/**
 * @method PDO getPDO()
 * @property PDO $pdo1
 */
class ClassA
{
    public $name;
    /**
     * @var PDO
     */
    public $pdo2;
    public function __construct()
    {
        $this->    // getPDO?
    }
}
````

**Comment by anatooly** [comment]
I'm reproduce you @pattisahusiwa case on CL 11.0.7 macOS. Can it be all right?

![2018-01-23 12-10-53](https://user-images.githubusercontent.com/317380/35270160-ef7362ba-0036-11e8-9ff4-f6d61608c70d.png)
![2018-01-23 12-11-30](https://user-images.githubusercontent.com/317380/35270164-f108fc0c-0036-11e8-859f-fe24ac3710b0.png)
![2018-01-23 12-12-01](https://user-images.githubusercontent.com/317380/35270169-f2a85ca6-0036-11e8-917c-f6477da139a0.png)

**Comment by pattisahusiwa** [comment]
Build new one using code from commit b0cf5c391f2b7662d3fb7180fb463942c5d2c457 and these are the results.

**Test 1**
````php
<?php
/**
 * @property PDO $pdo1
 * @property DateTime $dt
 */
````
`$pdo1` works, `$dt` doesn't work. Checking `phpsymbols.db`, typehint for `$dt` is empty.


**Test 2**
````php
<?php
/**
 * @property PDO $pdo1
 * @method PDO getPDO()
 */
````
`getPDO()` method is not listed in autocomplete list, `$pdo1` doesn't show the hint (codelite doesn't know that `$pdo1` is a `PDO` class).

`getPDO` is not saved in `phpsymbols.db` and typehint for `$pdo1` is empty.
