### ISSUE TITLE
Typing in main text editor window causes application to hang and utilize 100% of CPU (Windows)

### ISSUE THREAD

**Issue by ctchadwick** [eranif/codelite#1879]
I'm not sure how to give useful information to help debug this one.  I've experienced this on prior versions of Codelite last year (after May 2017, but can't recall the version) as well.  The issue is when one begins to type in the text window (say modifying a file, in my case a C++ file) and after two letters are typed, the application hangs and consumes a full core rendering it unusable.   This happens with anti-virus on and off, as well as right after the application starts, doing nothing else than typing.   I was using v11.0.1 and upgraded to the lastest v11.0.7 and this was observed with both versions.   I also noticed this same issue with Eclipse CDT (version was Neon).  The issue seemed to clear up eventually, after about a week of this behavior in both applications.  I'm not sure if there were any updates to Windows that affected it.  In any case I am running currently an up to date Windows install.  This has happened on two different Windows version (Win10 Pro and Home) on two different machines. 

I can't attach gdb to it to see if I can identify where it might be hanging up, but I did use procexp64 to get a dump (too large to upload here, approx 115MB).  Not sure how to get the dump to whoever needs it.

**Comment by eranif** [comment]
Have you tried un-checking the option `settings->code completion->triggering->auto display code completion box when typing` option?
Also, please disable the option:
`settings->code completion->General->Crawl all files to locate using namespace calls`

**Comment by ctchadwick** [comment]
Disabling the "Crawl all files to locate 'using namespace' calls" did the trick.  This makes sense I guess given that I use the Boost libraries and have them added to my project so it'd be crawling a lot of files.   That is also the same conditions the last time I experienced this issue with the prior version.  Thanks Eran.
