### ISSUE TITLE
Rename Symbol is broken

### ISSUE THREAD

**Issue by mrDIMAS** [eranif/codelite#1881]
Hi Eran! First of all thank you for your excellent IDE. I ran into problems with "Rename Symbol" feature. 

I have 
`extern de_engine_t* engine;`
defined in some of my headers. When I do "Rename Symbol" from `engine` to `de_engine`, in some places of my code `engine` does not correctly renamed - "Rename Symbol" completely messes up my code: 

This is what I have before "Rename Symbol":
```
case WM_DESTROY:
        engine->running = DE_FALSE;
        break;
    case WM_KEYDOWN:
        engine->keys[de_remap_key(wParam, lParam)] = DE_TRUE;
        break;
    case WM_KEYUP:
        engine->keys[de_remap_key(wParam, lParam)] = DE_FALSE;
        break;
```

And this is what I got after:
```
 case WM_DESTROY:
        engine->running = DE_FALSE;
        brde_engine    case WM_KEYDOWN:
        de_engine->keys[de_remap_key(wParam, lParam)] = DE_TRUE;
        break;
    case WM_KEYUP:
        engine->keys[de_remap_key(wParam, lPde_engine = DE_FALSE;
        break;
```

I use latest version of CodeLite (11.0.7). I'm completely sure that few months ago this feature works pretty fine, but now something is broken.

UPD. I have reinstalled CodeLite, and removed my local settings, but it does not help.

**Comment by eranif** [comment]
This can happen when CodeLite's offsets are broken (usually when it encounters some unicode characters that it can't open successfully) Do the problematic files contain any non ASCII characters? (e.g. Cyrillic script)

**Comment by mrDIMAS** [comment]
No, files does not contain any non-ascii characters. Files are saved as UTF8 w\o BOM.
