### ISSUE TITLE
I can't use wxCrafter on Arch.

### ISSUE THREAD

**Issue by gladosfromaperturelabs** [eranif/codelite#1882]
I installed CodeLite from AUR ( https://aur.archlinux.org/packages/codelite/ ) but, wxCrafter doesn't work, when I create a project based on wxCrafter and then open the .wxcp file it opens in the editor not in the WYSIWYG interface of wxCrefter.

**Comment by eranif** [comment]
We dont provide wxCrafter for Arch Linux...
