### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by maxime-ohm-georges** [eranif/codelite#1883]
Hello,
I am using version 11.0.7 of Codelite under Ubuntu 17-10.

I applied the following theme :

![coloursandfonts](https://user-images.githubusercontent.com/35853772/35463634-e119c1e2-02f1-11e8-8e80-153d4e2801cd.png)

But colors are not applied to all screen:

![capture_2018-01-26 23-35-41](https://user-images.githubusercontent.com/35853772/35463591-b95567d8-02f1-11e8-914e-6028546ea0f8.png)

Is it normal ?

**Comment by eranif** [comment]
Yes...
CodeLite uses wxWidgets which uses the native controls, so custom colours are not fully supported.
If you wish to use a full dark theme, you will need to pick a true system wide dark theme
