### ISSUE TITLE
Run doesn't seem to do anything

### ISSUE THREAD

**Issue by kwint** [eranif/codelite#1889]
My project builds fine but when I try to run it nothing seems to happen.
Running a simple hello world program does run. I've tried this on an other computer, but also doesn't seem to work there. The original developer uses the same setup and he is having no problems. We all use Ubuntu 16.04. We have compared all the settings and files and can't find any difference.

When I execute the program manually from the debug folder the program works and runs fine. 

I'm pretty sure that with this information you can't do any debugging, but I'm not sure what information is of use for you, so please let me know what you need to debug this use and I'll provide it.

**Comment by eranif** [comment]
This sounds like a configuration issue and not a bug issue. Please report this on the forum and not here
