### ISSUE TITLE
Add CXX and other variables in custom build

### ISSUE THREAD

**Issue by iHardRock** [eranif/codelite#1891]
```
diff --git a/Plugin/macromanager.cpp b/Plugin/macromanager.cpp
index 8920404..0afcf28 100644
--- a/Plugin/macromanager.cpp
+++ b/Plugin/macromanager.cpp
@@ -146,7 +146,7 @@ wxString MacroManager::DoExpand(
     wxString expandedString(expression);
     clCxxWorkspace* workspace = clCxxWorkspaceST::Get();
     //IWorkspace* workspace = clWorkspaceManager::Get().IsWorkspaceOpened();
-    
+^M
     if(!manager) {
         manager = clGetManager();
     }
@@ -165,7 +165,7 @@ wxString MacroManager::DoExpand(
             } else {
                 expandedString.Replace("$(WorkspaceConfiguration)", "");
             }
-            
+^M
             ProjectPtr proj = workspace->GetProject(project);
             if(proj) {
                 wxString prjBuildWd;
@@ -199,6 +199,7 @@ wxString MacroManager::DoExpand(
                     expandedString.Replace(wxT("$(IntermediateDirectory)"), bldConf->GetIntermediateDirectory());
                     expandedString.Replace(wxT("$(ConfigurationName)"), bldConf->GetName());
                     expandedString.Replace(wxT("$(OutDir)"), bldConf->GetIntermediateDirectory());
+                    expandedString.Replace(wxT("$(CXX)"),  bldConf->GetCompiler()->GetTool(wxT("CXX")));^M
                 }
 
                 if(expandedString.Find(wxT("$(ProjectFiles)")) != wxNOT_FOUND)

```
In custom build many of variables are not supported. 
I add one of them - CXX.
Please add all other :)

May be good idea to create single function that will expand all supported variables and use this function in all places where you may use variables

**Comment by eranif** [comment]
The macro manager is not the place for replacing environment variables.
This class should only expand CodeLite macros.
When using custom makefile/build it is up to the user to replace everything it needs, including providing the proper CXX tool etc. 
What you are trying to do here is to tailor CodeLite to fit your needs

**Comment by iHardRock** [comment]
But this feature is really needed for cross-build. In my opinoin, CodeLite is the best IDE for cross-build, but not ideal yet :) So one step to make it better - add support for ALL variables to be accessible in build-related settings (Pre/Post and Custom build).

Look the way how i use it and why this really needed:
Many of my projects is cross-platform and may run on different embedded linux systems, as well as on "normal" Ubuntu. This means that i have diffrerent GCC compillers toolchains, provided by Buildroot.

In workspace I have only significant configurations like Debug, Release and some other, except compiler-related. Also in all projects I use single compiler name "GCC" for example.

So when I need to build workspace for some kind of device, i simply create new build_settings.xml file with compiler "GCC" pointing to needed toolchain and use codelite-make to build.
But this is not all :) 
Some projects is "external dependecies" configured to build via CodeLite as projects with custom make.
In this case you need to set actual compiller toolchain. Best way for that - is to pass path to compiler and autodetect all other paths in cusom build script.

Ofcourse you may create different workspace configurations for each toolchain, but it you have for example 5 toolchains + 10 projects + only 2 configurations (Release/Debug) - this is really become nightmare to create and support all of this 100 configurations. Much better to create one build_settings.xml file for new toolchain.
