### ISSUE TITLE
auto completion for wxwidgets 3.1 in codelite 11.0.7

### ISSUE THREAD

**Issue by haftado3** [eranif/codelite#1897]
i added this lines in Ctags search path  : `/usr/include/wx-3.1-unofficial/wx/unix`
`/usr/include/wx-3.1-unofficial/wx`
and enabled clang code completion with same path added to it,
my compiler options:`$(shell wx-config --cxxflags --unicode=yes --debug=yes)`
my linker options:`-O2;$(shell wx-config --debug=yes --unicode=yes --libs )`
make file generator:`CMake`
i get this error:
`no rule to make target 'debug/main.cpp.o.d' needed by 'debug/main.cpp.o'. stop.`
`codelite-cc: command not found`
`makefile: 4:recipe for target 'all' failed`

i tried to change compiler , debugger and make file generator , but not solved the issue , all of this happens cause i want code completion for wxWidgets ,app works without my change to clang path but no completion "ctrl+space" shows nothing about wxWidgets
it works when adding `--version=3.0 --debug=no` to compiler options and linker options and only with GCC compiler but not completely , for example not showing `GetTopWindow()` or `wxDefaultPosition` anyway its for version 3 and have limited completions

**Comment by dghart** [comment]
Hi,

A few points:

First a minor one: there should be no need to specify things like --unicode=yes --debug=yes when you invoke wx-config. It's almost always more sensible to make sure you are using the correct wx-config in the first place, and that's especially true when you have both wx3.0 and 3.1 installed. I suggest you replace those lines with e.g. $(shell /usr/bin/wx-config -cxxflags); alter the path to what is right for you, or use update-alternatives if your distro supports that.

Next, there should be no connection between your ctags/clang settings and whether the correct wx-config path is used in your makefile. Obviously you want it right in both places, but code-completion failing won't in itself break compilation. 

In your post you have 'make file generator:CMake'. Unless you have a good reason not to, I suggest you use the default makefile. Once you get that working, switch if you want or need to.

Finally, I suggest you create a new Project using one of the templates e.g. one of the wxWidgets GUI application ones. That should build correctly, once you get your wx path correct. Then try getting clang code completion working in that. Once everything works, you can compare the settings with your failing project...

Regards,

David

**Comment by haftado3** [comment]
`g++ `wx-config --cxxflags` -I/usr/lib/x86_64linux-gnu/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0/-D_File_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -Wall -g -c whatever.cpp -o whatever.o `wx-config --libs``
i've compiled my project with g++ with this code in konsole still codelite cant compile it .

**Comment by dghart** [comment]
It's good to know that the code _can_ build. So we need to work out what CodeLite does that's different.

Do you still get the error message that you previously posted? If not, what is the output that you now see in the Build tab of the Output View? Please paste it all here.

It may also help if you could paste the file ${whatever}.project (substitute the name of your project) which you will find inside CodeLite's workspace dir; that might be the same place as your code, depending how you set things up.

**Comment by haftado3** [comment]
//file whatever.cpp which codelite can compile without error
```
#include <wx/wx.h>

class myApp: public wxApp{

    public:
    virtual bool OnInit();
};
bool myApp::OnInit(){
    wxFrame *frame=new wxFrame(NULL,-1,wxT("hello world"));
    frame->Show(true);
    return true;
}
IMPLEMENT_APP(myApp);
```

//output when build which is not my current active directory

make[1]: Entering directory '/home/mahdi/Documents/wxworkspace/projectWhatever'
make[1]: codelitegcc: Command not found
projectWhatever.mk:99: recipe for target 'Debug/MainFrame.cpp.o.d' failed
make[1]: *** [Debug/MainFrame.cpp.o.d] Error 127
make[1]: Leaving directory '/home/mahdi/Documents/wxworkspace/projectWhatever'
Makefile:4: recipe for target 'All' failed
make: *** [All] Error 2
====1 errors, 0 warnings====

//its not even building my active project compiling another project which is default from new project "new -> frame based wxwidget application gui" i did not touch any code or setting on that project its default sample from codelite. and still fails in building


my current active directory is whatever project .
and its not building that directory.
its building default sample from new project which is not working.
if i compile my whatever.cpp there is no error.
but i cant build whatever project

**Comment by haftado3** [comment]
I'm using Kubuntu 17 in a VMWare 14.1
I've changed codelite settings a little 
my problems:
1-autocomplete not works correctly for wxwidgets 
2-"build" is not building active directory
3-is there any alternative to "OutputDebugString" or "_RPT1" which shows debugging results in output view in visual studio?
4-and how can i include /usr/lib/x86_64linux-gnu/wx/include/gtk2-unicode-3.0 this to my project , which setup.h file is in it

i changed almost everything to default but results is same

**Comment by dghart** [comment]
>make[1]: codelitegcc: Command not found

codelitecc was replaced in 2014: see https://github.com/eranif/codelite/commit/e1332da4a023ffe7797bf6011577a96233b9d6bb
Why is your project  trying to use it? Did you copy/paste your project from an old workspace? Or your ~/.codelite from elsewhere?

I suggest you create a new workspace, add a new gui template project as I suggested before, and get that working (if it doesn't, please paste the Build output and the project details as I asked above).

I suspect that will work with little alteration; probably just the /full/path/to/wx-config in the Compilation and Linking settings. If so, you could transplant your 'whatever' files etc into the new workspace/project.
