### ISSUE TITLE
CL update check notifies about new version on Arch Linux

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1903]
CL update check notifies about new version
CL is configured to only notify about stable releases - and no new versions seems to be around...

I'm already running CL 11.0.0 (ArchLinux 64bit)

From codelite.log
[11:53:25:628 DBG] Current platform details: linux , others , x86_64 , 11.0.0
[11:53:25:628 DBG] ---> msw-dbg , Windows , x86_64 , 1100
[11:53:25:628 DBG] ---> msw , Windows , x86_64 , 1108
[11:53:25:629 DBG] ---> msw , Windows , i386 , 1100
[11:53:25:629 DBG] ---> osx , 10.8 , x86_64 , 1108
[11:53:25:629 DBG] ---> linux , Debian GNU/Linux 8 , x86_64 , 1108
[11:53:25:629 DBG] ---> linux , Ubuntu 14.04 , x86_64 , 1108
[11:53:25:629 DBG] ---> linux , others , x86_64 , 1108
[11:53:25:629 DBG] Found new version!
[11:53:25:629 DBG] A new version of CodeLite found

The list above has 7 elements but the /tmp/codelite-packages.json has 8 elements
The last element in /tmp/codelite-packages.json is not shown in the log....
Maybe a syntax error in /tmp/codelite-packages.json ? as the last element has a different spacing
please note the missing space "},{" where the other elements has "}, {"

{
    "platforms": [{
            "os": "msw-dbg",
            "codename": "Windows",
            "arch": "x86_64",
            "version": 1100,
            "url": "http://codelite.org/LiteEditor/ReleaseNotesCodeLite11",
            "isRelease": false
        }, {
            "os": "msw",
            "codename": "Windows",
            "arch": "x86_64",
            "version": 1108,
            "url": "http://codelite.org/LiteEditor/ReleaseNotesCodeLite11",
            "isRelease": false
        }, {
            "os": "msw",
            "codename": "Windows",
            "arch": "i386",
            "version": 1100,
            "url": "http://codelite.org/LiteEditor/ReleaseNotesCodeLite11",
            "isRelease": true
        }, {
            "os": "osx",
            "codename": "10.8",
            "arch": "x86_64",
            "version": 1108,
            "url": "http://codelite.org/LiteEditor/ReleaseNotesCodeLite11",
            "isRelease": false
        }, {
            "os": "linux",
            "codename": "Debian GNU/Linux 8",
            "arch": "x86_64",
            "version": 1108,
            "url": "http://codelite.org/LiteEditor/ReleaseNotesCodeLite11",
            "isRelease": false
        }, {
            "os": "linux",
            "codename": "Ubuntu 14.04",
            "arch": "x86_64",
            "version": 1108,
            "url": "http://codelite.org/LiteEditor/ReleaseNotesCodeLite11",
            "isRelease": false
        }, {
            "os": "linux",
            "codename": "others",
            "arch": "x86_64",
            "version": 1108,
            "url": "http://codelite.org/LiteEditor/ReleaseNotesCodeLite11",
            "isRelease": true
        },{
            "os": "linux",
            "codename": "others",
            "arch": "i386",
            "version": 1100,
            "url": "http://codelite.org/LiteEditor/ReleaseNotesCodeLite11",
            "isRelease": true
        }
    ]
}

**Comment by uffejakobsen** [comment]
Hmm just noteced that the missing element is i386 - that is not my platform... so more elements seems to be missing from codelite-package.json is guess.....

**Comment by eranif** [comment]
This should be fixed now. The "Linux Others" (the default) was marked as "isRelease" = true while it should be false

**Comment by uffejakobsen** [comment]
+1 it works now - thanks :-)

**Comment by uffejakobsen** [comment]
Sorry - but now I took another look at the codelite-packages.json
There is still something missing - I think - if I've understood inner workings correct.

You've correctly marked the entry:
linux, others, x86_64, 1108 as false

But a real release entry for is missing for:
linux, others, x86_64, 1100, true

**Comment by eranif** [comment]
Yes, this is on purpose.
It seems that  the current code does not recognize `Ubuntu 16.04` it is mistakenly recognizes it as `other`
This entry is kept there for the sake of the Ubuntu users (we have much more Ubuntu users than Arch...)
This is fixed in GitHub, however, until this fix is rolled out, you will have to live with this false notification

**Comment by eranif** [comment]
There can't be duplicate entries for the same platform
