### ISSUE TITLE
Replace does not support EOL special characters `\r\n`

### ISSUE THREAD

**Issue by jupeos** [eranif/codelite#1914]
To reproduce:

1. Create a new file (Untiltled and unsaved)
2. Insert text
Thu, Feb 22, 2018 at 3:43 PMThu, Feb 22, 2018 at 3:47 PMThu, Feb 22, 2018 at 3:49 PMThu, Feb 22, 2018 at 3:51 PMThu, Feb 22, 2018 at 3:55 PM
3. Replace... (Ctrl-H) and select regular expression icon.
4. Enter the letter M in the find box
5. Enter M\r\n in the replace box
6. Hit Replace All

The results in:
Thu, Feb 22, 2018 at 3:43 PMrnThu, Feb 22, 2018 at 3:47 PMrnThu, Feb 22, 2018 at 3:49 PMrnThu, Feb 22, 2018 at 3:51 PMrnThu, Feb 22, 2018 at 3:55 PMrn

The correct result would be to insert CR/LF as:
Thu, Feb 22, 2018 at 3:43 PM
Thu, Feb 22, 2018 at 3:47 PM
Thu, Feb 22, 2018 at 3:49 PM
Thu, Feb 22, 2018 at 3:51 PM
Thu, Feb 22, 2018 at 3:55 PM

**Comment by zufuliu** [comment]
Lack an option to translate backslash like Notepad2 or Extended like Notepad++.

**Comment by jupeos** [comment]
This still has not been fixed and is most annoying having to use another editor for regex searches.

**Comment by jupeos** [comment]
@eranif - not sure what I'm supposed to do about this??? Your bot seems to want to disregard this issue and you have not commented on it. It's still an issue and needs to be fixed or at the very least an explanation given as to why it's not considered an issue.
