### ISSUE TITLE
Flickering when scrolling the editor

### ISSUE THREAD

**Issue by GeorgeKalovyrnas** [eranif/codelite#1915]
With the new version (i.e. 11.0.8) there is a heavy flickering when scrolling the editor. I think that the flickering existed before this version too, but now it is far more noticeable.

**Comment by AJenbo** [comment]
What system are you running it on?

**Comment by GeorgeKalovyrnas** [comment]
Linux Mint 18.1 64-bit

**Comment by AJenbo** [comment]
In that case what GPU and driver du you use

**Comment by GeorgeKalovyrnas** [comment]
I have an HP EliteBook 8530w with ATI FireGL V5700 256MB.

Running:
`lspci -nn | grep -i vga -A3`

Output:
```
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] RV635/M86 [Mobility Radeon HD 3650] [1002:9591]
	Subsystem: Hewlett-Packard Company RV635/M86 [Mobility Radeon HD 3650] [103c:3604]
	Kernel driver in use: radeon
	Kernel modules: radeon
```

**Comment by eranif** [comment]
The flicker is because of wxWidgets. Since the upgrade to Scintilla 3.7.2 (wx3.1)
It is very noticeable if you use dark theme

**Comment by GeorgeKalovyrnas** [comment]
So, I assume that there is no workaround for this issue

**Comment by eranif** [comment]
Not that I could found. I too have this, mainly when you scroll with the mouse, you can see the upper side of the editor flickers into white...
I got use to it :/

**Comment by eranif** [comment]
Disabling this option should reduce the flicker to minimum (for me, they are now gone)
`settings->preferences->caret & scrolling->auto adjust horizontal scrollbar width`
