### ISSUE TITLE
c++ syntax highlighting bug

### ISSUE THREAD

**Issue by abdelaziz321** [eranif/codelite#1920]
**Hi,**
I'm using version 9.1.0 - on Ubuntu14.04.
I noticed that:
_local variable color is affected by the variable with the same name in another scope._

**here is an example:**
variable 'm' in line 51:
![before](https://user-images.githubusercontent.com/21992961/36806468-c722abfa-1cc8-11e8-9a66-7bbe8ea4f138.png)

after commenting line 58
![screenshot from 2018-02-28 20 36 48](https://user-images.githubusercontent.com/21992961/36806512-ea8411f6-1cc8-11e8-98bf-17ba78566c58.png)
:

**Comment by eranif** [comment]
Hi,
This can not be fixed. It's a limitation of the text editor component (http://scintilla.org/)
I strongly recommend you to upgrade to CodeLite 12. 9.1 is very old version and is not supported

**Comment by abdelaziz321** [comment]
I didn't know there is version 12. 9.1
thanks eranif.

**Comment by AJenbo** [comment]
I would also recommend upgrading to either Ubuntu 16.04 or 18.04 (when it arrives in April). 14.04 has one year of support remaining.
