### ISSUE TITLE
[9264] InitSideBySide failed create an activation context. Error: 1814

### ISSUE THREAD

**Issue by rodrigmars** [eranif/codelite#1921]
>> Could you help with the message "[9264] InitSideBySide failed create an activation context. Error: 1814" when compiling the code, could help in this matter ...

Project c++
**Compilers: MinGW**

**SO: WINDOWS 10**

**CodeLite Version: 12.0.0**

**Output:**
Current working directory: E:\laboratorio\ProjetosC++\PrecisionText\exercise_one\Debug
Running program: le_exec.exe ./exercise_one
**_[9264] InitSideBySide failed create an activation context. Error: 1814_**
Program exited with return code: 0

**Comment by eranif** [comment]
This is not CodeLite related issue. Please search in the C++ forums.
Please, in the future, use the issue tracker to report CodeLite issues (e.g. CodeLite crashed etc.)

What you are showing here is a general Windows error or something, please google it

**Comment by rodrigmars** [comment]
Thanks now I have a north to track the problem in question ... Thanks for the tip
