### ISSUE TITLE
How to place Navigation Bar at top (CL-12.0.0)

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1922]
With the new CL-12.0.0 - can I move the navigation bar to the top - around the tabs or so ?

(CL-12.0.0 ArchLinux/64bit)

**Comment by eranif** [comment]
You can't. This requires code change. If you really need this and can't adjust with the new setup, please open a FR for making this configurable

**Comment by uffejakobsen** [comment]
ok thanks - I'll try out CL-12 and the current navigation bar for some days... 

BTW: thanks for your work with CL - it is the best :-)
