### ISSUE TITLE
CodeLite cannot quit (CL-12.0.0)

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1923]
Scenario:
Launching CodeLite without opening any workspace or project
Then letting it run for a few seconds and then quitting CL

Problem:
CL does not close/quit it just hangs and must be manually killed

When I've opened a workspace/project CL has no problem quitting

CL-12.0.0/ArchLinux/64bit

**Comment by eranif** [comment]
This is because CodeLite website was down. CodeLite could not exit until the connection attempt ends (either successful or by timeout)
You can avoid this by disabling the "check for new version" option. However, the website is up now and you shouldn't experience this
