### ISSUE TITLE
Connection timed out dialog (CL-12.0.0)

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#1924]
With the new CL-12.0.0

I get a "Connection timed out" dialog some time after starting CL

I have no idea about what has timed out - as I'm only typing code in the editor at the moment.
This seems to be a new thing with CL-12.0.0

CL-12.0.0/ArchLinux/64bit

**Comment by eranif** [comment]
See: https://github.com/eranif/codelite/issues/1923 
In short: CodeLIte website was down, the "check for new version" requires internet connection which eventually timed out
