### ISSUE TITLE
Abbreviation completion does not work after upgrading to codelite 12

### ISSUE THREAD

**Issue by galdralag** [eranif/codelite#1929]
After pressing keyboard shortcut for completing abbreviation nothing happens.

**Comment by eranif** [comment]
The abbreviation was changed.
It is not automatically added to your code completion OR you can activate it using the `Ctrl-ENTER` shortcut

All the changes (the important ones) are listed here:
http://codelite.org/LiteEditor/ReleaseNotesCodeLite111

**Comment by galdralag** [comment]
Typically abbreviations are unique. Pressing hot key immediately insert abbreviation value. Now value not inserted. Instead appears list with many values mixed with other words and need spend time to select needed abbreviation and press enter. Very very inconvenient.
