### ISSUE TITLE
x86 builds for Windows

### ISSUE THREAD

**Issue by ArmanHayots** [eranif/codelite#1933]
I'm using Codelite for hobby project on weak 16GB Atom laptop with x86 Windows and building Codelite from sources on it maybe possible, but very hard task.

**Comment by eranif** [comment]
I will try invest some time building CodeLite on Windows 32 bit, shouldn't be much of a problem

**Comment by ArmanHayots** [comment]
Thank you Eran, just a working x86 build will be enough — no support, no headache.
Codelite is a pretty good as a small yet powerful C++ IDE that fits in 1GB RAM and succesfully replaced the DevC++.

**Comment by eranif** [comment]
CodeLite 12.0 for Windows 32 bit has been released
