### ISSUE TITLE
Checking "Use Codelite's built-in terminal emulator" requires uninstall/reinstall

### ISSUE THREAD

**Issue by alan-kozlay** [eranif/codelite#1941]
[CentOS7]
I made the unfortunate decision to click the Settings->Preferences->Terminal "_Use CodeLite's built-in terminal emulator_" checkbox.   **Woops !!!**
When I debug, the stdout dialog created now only contains an error message about not being permitted to start the console.  But the checkbox is now greyed out so that this can't be undone without uninstall & reinstall of codelite.

**Comment by AJenbo** [comment]
Your settings are in your user folder and won't change when removing an application.
Specifically for code lite the user settings are in ~/.codelite ( a hidden folder in your home folder ).

**Comment by eranif** [comment]
This is now fixed

**Comment by EligiusSantori** [comment]
I faced same problem with 12.0.0 version.

**Comment by kluete** [comment]
same for me here with v12.0.0, any recommendation on which version to upgrade to that doesn't change the whole UI too much?

thx!
