### ISSUE TITLE
Connection error:Network is unreachable

### ISSUE THREAD

**Issue by green-eyed-bear** [eranif/codelite#1944]
When I run CodeLite (without Internet connection), I get an error popped up saying "**Connection error:Network is unreachable**".

Notes:
**1**) Why is it trying to connect to the Internet on its own (without any specific request from me)?  Seems rather dubious.

**2**) This is *probably* related to "check for updates".  If this is the case, the user should make the decision on if this is done each time program starts up.  Either turn off by default, or ask when first run if that is what the user wants. Having a program that just connects to the Internet on it's own, without prior approval is not what I'd call trust-worthy.  Just be up-front with user, and they will appreciate it.

**3**) If this was related to "check for updates", even if the user gives approval to check on startup, it seems like checking every time is wasteful.  Maybe once a day, or once a week, etc... would be better.  Also, this error should only pop-up when user explicitly asked to check for updates.  If they said it was OK to automatically check for them, but there's no Internet connection, don't display the error.

--------------------------
CodeLite Version:  12.0

OS:  Debian 9

Installation Method:
  1) Cloned repository.
  2) Set branch to "12.0".
  3) Manual build via "make/make install".

**Comment by eranif** [comment]
- CodeLite checks for new versions
- disable it from settings->preferences->misc->check for updates
