### ISSUE TITLE
Code navigation has a hard time with overloaded functions.

### ISSUE THREAD

**Issue by green-eyed-bear** [eranif/codelite#1948]
Let's say a class has these methods.  Both are named the same, but with different parameters.

    void foo();
    void foo( int x );

When I ask CodeLite to navigate to a specific one of these, via "Go to Implementation", it does not know which one to go to, even though I specifically asked for one in particular.

Instead of navigating to where I want, it pops up a menu, which makes me say again, which of the methods I want.  This menu will list all possible overloads.

What should happen, is the navigation logic should realize I clicked on a method with specific parameters, and take me to the one I requested.

--------------------------
CodeLite Version:  12.0

OS:  Debian 9

Installation Method:
  1) Cloned repository.
  2) Set branch to "12.0".
  3) Manual build via "make/make install".
  4) Build type: Release

**Comment by eranif** [comment]
This is the intended behavior. A patch to fix this is more than welcome
