### ISSUE TITLE
The preference for "Load last session on startup" does not seem to work.

### ISSUE THREAD

**Issue by green-eyed-bear** [eranif/codelite#1949]
Every time I start up CodeLite, I have to explicitly tell it to open a workspace.  I only have one, so this is annoying.

I think "Settings->Preferences->Misc->General->Load last session on startup" is supposed to do this for me.  It's checked, but does not seem to work.

--------------------------
CodeLite Version:  12.0

OS:  Debian 9

Installation Method:
  1) Cloned repository.
  2) Set branch to "12.0".
  3) Manual build via "make/make install".
  4) Build type: Release

**Comment by eranif** [comment]
I am unable to reproduce this, it works for me on Ubuntu 16, Windows and OSX (just tested these three)
Maybe you have a local issue with storing the settings?

This setting is kept in the same entry as "Maximize" on startup which sounds a bit odd to me
Can you delete the folder `~/.codelite` (or rename it) and try again?
I am 100% sure its a local issue
