### ISSUE TITLE
Navigation Bar, freezes up after change in file.

### ISSUE THREAD

**Issue by green-eyed-bear** [eranif/codelite#1950]
Prerequisites:
1) Check option "View->Navigation_Bar", so it appears at bottom of text editor.

Repro:
1) Open a file that has one or more functions, which the "Navigation Bar" can display.

2) Click on "Navigation Bar", and verify it displays possible functions.

3) Make a change to the file and save it.  (could just be adding white-space)

4) Try to click on "Navigation Bar".  Nothing happens.

5) Switch to different file tab, then switch back to original file tab (where change was made).

6) Click on "Navigation Bar", and notice it is working again.

--------------------------
CodeLite Version:  12.0

OS:  Debian 9

Installation Method:
  1) Cloned repository.
  2) Set branch to "12.0".
  3) Manual build via "make/make install".
  4) Build type: Release

**Comment by eranif** [comment]
Again, this works here (no hang...)
Can you try an official build of CodeLite? We provide builds for Debian 9 (via our repository
http://codelite.org/LiteEditor/Repositories

**Comment by green-eyed-bear** [comment]
I've been using version 10 of CodeLite since last June when Debian 9 first came out, so I do have some experience using it.  However, I don't trust anybody to build stuff for me, so sorry I can't download your pre-built stuff.

When I built my own version of CodeLite, I followed all the steps your provided for installing on Linux.  However, there was one item which was not exactly clear.  You said I needed "wxWidgets".  Well, unfortunately on Debian, there's no meta package for it, but rather a bunch of options to choose from.  Could you be more clear in documentation which wxWidget packages on Debian to install?  Thanks.

For now, I'm swamped with my own project and can't spare any more cycles to help debug further, and have switched (maybe just temporarily) to a different IDE.  I like what you got going on with CodeLite though, and maybe when Debian releases updated version, I'll try it out again.

**Comment by AJenbo** [comment]
Why do you true the Debian project to build things for you?

**Comment by AJenbo** [comment]
Please see this page on how to get wxWidget:
http://codelite.org/LiteEditor/WxWidgets30Binaries

**Comment by eranif** [comment]
Have you tried deleting the folder `~/.codelite/` ?

**Comment by dghart** [comment]
> You said I needed "wxWidgets". Well, unfortunately on Debian, there's no meta package for it, but rather a bunch of options to choose from. Could you be more clear in documentation which wxWidget packages on Debian to install?

apt install libwxgtk3.0-dev should bring in all the wx packages you need. But if your build already succeeded, you can't have got it wrong

**Comment by green-eyed-bear** [comment]
I seem to be seeing a lot of issues that others are not.  My best guess is:

1) It's possible, that due to various "git ignore" rules, the actual code I cloned from GitHub is not exactly the same as what you've got.  I've seen this before on a different project.  Maybe you could create a new clone, then do a "directory diff" and check for any differences.

2) My computer has gremlins, or some other user issue on my end.

**Comment by eranif** [comment]
Have you tried using CodeLite for Debian 9 that **we** provide?
Please install it for comparison (if you don't like it - remove it later)
but in any case, we should install our package so we can get any idea of what is wrong with your installation.

**Comment by AJenbo** [comment]
I compile from a clean clone and do not have the issues that you have mentioned

**Comment by green-eyed-bear** [comment]
Please just close out any bugs I filed, which you can't repro.  Must have been something on my end, and I don't have any free time to do any more investigating.  I'll just use the official packages provided by Debian.  Sorry for wasting any of your time.

**Comment by eranif** [comment]
The question is: does using our build solve your issues?
