### ISSUE TITLE
Unsure about how to "auto-hide" the "Output View".

### ISSUE THREAD

**Issue by green-eyed-bear** [eranif/codelite#1951]
I know that in version 10, somehow I got the "Output View" to "auto-hide" itself.  That is, when I would build something, it would pop-up, but then I could click in an open file, and the "Output View" would then hide itself.  I imagine this functionality probably still exists, but I looked and looked, but could not find it, which means it's not that intuitive.

--------------------------
CodeLite Version:  12.0

OS:  Debian 9

Installation Method:
  1) Cloned repository.
  2) Set branch to "12.0".
  3) Manual build via "make/make install".
  4) Build type: Release

**Comment by eranif** [comment]
`Settings->Preferences->Windows & Tabs->Debug/Output Panes`

**Comment by biciolea** [comment]
Where is this setting in version 16.4.0?
