### ISSUE TITLE
CodeLite not "maximized" when opened.

### ISSUE THREAD

**Issue by green-eyed-bear** [eranif/codelite#1952]
If I'm using CodeLite, and the window is "maximized", this preference is not acknowledged the next time I open it up.

Instead, it always opens in a size that takes up about 1/6th of my screen.

--------------------------
CodeLite Version:  12.0

OS:  Debian 9

Installation Method:
  1) Cloned repository.
  2) Set branch to "12.0".
  3) Manual build via "make/make install".
  4) Build type: Release

**Comment by AJenbo** [comment]
Can't confirm this on Ubuntu 16.04

**Comment by eranif** [comment]
I have tested this on Windows and macOSX as well, and it works. The code is there, so if it is broken then it must be on wxWidgets side. Can't do much about that
