### ISSUE TITLE
Highlight results on scrollbar

### ISSUE THREAD

**Issue by Johndeep** [eranif/codelite#1954]
Just as the title says, highlight results, be it search results or variables/functions/methods at, on or beside the scrollbar.

In contrast to the ZoomNavigator, which shows you a zoomed out variant of your document, a much less distracting function (similar to https://github.com/Aakash1312/scroll-searcher) would be just some highlight on, at or beside the vertical scrollbar, which would tell you immediately and with just a single glance, if and where a search result or marked variable/function can be found in the whole active document.

The best would be the scroll bar having the same theme as the the global theme (so dark editor, light-dark scrollbar), so more independent from desktop theme.

I hope this issue is no duplicate of something already existing, but after skimming through the Issues, I didn't find anything similar sounding, thus I created this Issue.

**Comment by eranif** [comment]
CodeLite uses wxWidgets which uses the *native* controls, your suggested functionality can't be implemented

**Comment by Johndeep** [comment]
Even not as an additional bar alongside the native bar? Hmm, okay then, I though wxWidget could do that much.. sorry for asking..
