### ISSUE TITLE
Smart Curly Brackets not working

### ISSUE THREAD

**Issue by albertobarbaro** [eranif/codelite#1956]
Hi all,
I'm using the latest version of CodeLite and I have the problem that if I create an If and open the curly bracket once I press enter the close brackets does not appear. Are you aware of this problem?

Thanks

**Comment by eranif** [comment]
Do you have this enabled: `Settings->Preferences->Editor->Edit->Smart Curly Brackets` ?

**Comment by abarbaro** [comment]
@eranif , sorry I should I have mentioned that... Yes the option is enabled.

Thanks

**Comment by eranif** [comment]
BTW, this will only works for C++ files (or PHP)
Is this file recognized an a NON text file? (at the bottom right, you should see the language CodeLite chose for this file)

**Comment by abarbaro** [comment]
@eranif , I have attached a screenshot.. I hope this can help you.

Thanks
![codelite](https://user-images.githubusercontent.com/4751670/37879937-92f56cfa-3078-11e8-985a-e8da6d58e94b.png)

**Comment by eranif** [comment]
Looking at the code, the "Smart Indent" option is relate to this.
So, do you have it *disabled* ?
It's under `Settings->Preferences->Editor->Indentation->Disable smart indent`

**Comment by gxhniip421** [comment]
My experience is, with Codelite 12.0.0, in Voidlinux package codelite-12.0_7, that Codelite is "seriously broken"!

Inserting closing curly brackets into C++ files is **ONLY** possible using "smart indentation" and "smart curly brackets"! (Why have we these options if we have no choice?)
Inserting closing curly brackets into into non-C++ files it is **IMPOSSIBLE**! (I have not found any way.)

(And a minor effect: when I type the '{' (in a C++ file), two lines of the screen are flashing (blinking). For a few milliseconds, the black background swithes to white.)

**Comment by veotaar** [comment]
I have the same problem. Smart quotes are working but smart curly brackets and smart square brackets / parentheses are not working. Tried everything mentioned in this issue, the problem is still present.  CodeLite version 13.0.0. Windows 10.

**Comment by nachiketsmore** [comment]
> NON text file? (at the bottom r

ty this annoyed me alot
