### ISSUE TITLE
(Feature request) - Make key combination "AltGr + ;" optional for Select Tab

### ISSUE THREAD

**Issue by Etrimon** [eranif/codelite#1961]
Hallo CodeLite Team,

I would like to ask you, if it is possible to remove or make optional the bind of key combination "AltGr + ;" to Select Tab.

In our language on programming keyboard we use this for typing the "semicolon".

Thank you very much!

**Comment by eranif** [comment]
Just making sure here: by "Select Tab" do you mean the dialog that comes up when using `Ctrl-TAB` ?
See attached screenshot
<img width="561" alt="select-tab" src="https://user-images.githubusercontent.com/3677711/37989357-e3bfffbc-320b-11e8-97f0-565aaec7037e.png">

**Comment by Etrimon** [comment]
Hello eranif,

yes, this window appears, only the difference is, that it switches only to "previous/next" tab.

Thanks a lot for you effort!

**Comment by Etrimon** [comment]
Hallo Eranif,

I just tested today the 12.0.1 version. 

The thing is, that if I turn "Enable Tab switching with Ctrl+TAB" off, when I press AltGr + ; -> nothing happens - I mean, it does not write the ";" into the opened document/file.

Thank you very much for your effort.

**Comment by eranif** [comment]
Note that with the new commit, you can now also change the default keyboard binding for this functionality (from `Settings->Keyboard shortcuts`, and type in the filter: "switch")

**Comment by Etrimon** [comment]
I am really sorry, maybe I am dumb, but if I type "switch" into the filter you mentioned, nothing appears.

I already tried to find the keyboard shortcut before (it was honestly the first place I was looking at), but didn't find it.

Could it be, because by updating I selected "Keep previous settings" ?

**Comment by eranif** [comment]
Sorry if I was not clear about it:
I **just** committed this fix with a better approach that should really fix your issue (this commit was done 10 mins ago...)
