### ISSUE TITLE
Makefile. IntermediateDirectory and Objects races

### ISSUE THREAD

**Issue by Tramort** [eranif/codelite#1964]
It happens very rare but sometimes when I am run `make -j` for makefiles generated by codelite it fails with something like:
```
Fatal error: Fatal error: can't create ./Release/src_FileIO.c.o: No such file or directory
can't create ./Release/src_blabla.c.o: No such file or directory
```

After investigation of makefiles I see potential race

```
all: $(OutputFile)
$(OutputFile): $(IntermediateDirectory)/.d $(Objects) 
`$(IntermediateDirectory)/.d:
	@test -d ./Release || $(MakeDirCommand) ./Release
```

$(IntermediateDirectory)/.d $(Objects) can be called in parallel
object file can be compiled before intermediate directory is created

Same on Codelite 11.0.0 and 12.0.0.0
Generated makefile attached
[test.mk.gz](https://github.com/eranif/codelite/files/1861013/test.mk.gz)

**Comment by eranif** [comment]
So basically, we need to put a dependency between $(Objects) and $(IntermediateDirectory)
