### ISSUE TITLE
(feature request) Show number of chars and/or bytes in text selection in the footer

### ISSUE THREAD

**Issue by pimlie** [eranif/codelite#1971]
Currently if you have a file open and move the cursor to a position somewhere in that file, the footer bar shows the line number and column number (below Ln 34, Col 0). It would be great if in that bar we could also see how many chars/bytes you have selected in the text. In other editors I often use that to quickly count how long a string or part of a string is or check for UTF8 encoding issues

Eg in the image below it would say 12 chars and/or bytes:
![image](https://user-images.githubusercontent.com/1067403/38322113-cc9cbdc8-3839-11e8-8031-773c442e1fb3.png)

**Comment by zufuliu** [comment]
Related #1612.

**Comment by zufuliu** [comment]
Column count and character count is not equal when Tab char `\t` is used, the former depends on Tab width settings (in Menu Settings -> Preferences -> Editor -> Indentation -> Columns per tab character  in document).

Selected length and selected character count may not equal.  it's depends on the file encoding, the former is the byte count of selected characters encoded in current encoding.

**Comment by pimlie** [comment]
Just curious but when do you use those columns in text files containing code?

Selected length/char count is why I said `and/or` in this request, but I dont think we really need both definitions at the same time. (afaik) Codelite aims to be an IDE (not a general purpose text-editor) so character length should be preferred I'd guess. That said, I agree there are situation being able to know the byte count would also be nice (eg as I said above to check utf8 issues). As would be a hex-mode to be able to view binary data ;)
