### ISSUE TITLE
[BUG] Broken codelite_xterm in latest repo

### ISSUE THREAD

**Issue by iHardRock** [eranif/codelite#1972]
Terminal for debugger not starting with error "Could not launch terminal for debugger" after 5 seconds timeout as expected @ Plugin/globals.cpp :  LaunchTerminalForDebugger.

Reason is in codelite_xterm script.

> eval ${terminal} "$3" -T \"$program_title\" -e /bin/bash -c 'export LD_LIBRARY_PATH=$0;shift;$@' $LD_LIBRARY_PATH "$@" 2> /dev/null

Not working, but old

>  ${terminal} $3 -T "$program_title" -e /bin/bash -c 'export LD_LIBRARY_PATH=$0;shift;$@' $LD_LIBRARY_PATH "$@" 2> /dev/null

Works well.

Ubuntu 14.04

**Comment by eranif** [comment]
is this include today's fix? i just reverted a commit they cause this problem
https://github.com/eranif/codelite/commit/ac77bae8fc21963154b84a097f41f10ebb5ccadb

**Comment by iHardRock** [comment]
Now is all OK. Seems like i pulled before revert
