### ISSUE TITLE
Explorer / workspace moves files around on Mac OS with Magic Mouse

### ISSUE THREAD

**Issue by Kanimies** [eranif/codelite#1975]
Having opened a file into editor, I expand another folder in the Workspace -- and Codelite automagically moves the last opened file into the folder just expanded (and asks if I want to remove it from SVN). This only seems to occur when using an external mouse (Magic Mouse in my case) and not with the touchpad. 

Occurs seemingly randomly but confirmed with two users, feature has appeared recently (in Codelite 12.0 or some recent version before that).

**Comment by Kanimies** [comment]
The affected file doesn't even have to be open - these moves seem to occur rather randomly, not sure if the last file that got moved was even selected in explorer.

**Comment by eranif** [comment]
I am afraid I am a bit lost here. I suspect that this happened when we upgrade wxWidgets library. Maybe it's an issue with WX not detecting mouse button released so it thinks that a DnD operation is in progress. Can you please explain what a "magic mouse" is? Can this be reproduced with simple Microsoft mouse connected to MacBook?

**Comment by Kanimies** [comment]
https://en.wikipedia.org/wiki/Magic_Mouse

will try to reproduce or test with a PC mouse. Mentioned the magic mouse as the file movement could be related to clicking while scroll is still active or whatnot which might happen with the touchy feely way the magic mouse works.
