### ISSUE TITLE
PDF Download

### ISSUE THREAD

**Issue by hanshultz10** [eranif/codelite#1977]
When I try to download codelite 12.0 it keeps downloading as a pdf and won't open, how do I fix this?

**Comment by dghart** [comment]
You don't say exactly what you tried to download, but I'd guess that you mean https://codelite.org/support.php
If you click on that link instead of trying to download it, you'll get another page that contains more links to the different platform binaries. Follow the appropriate one(s).

**Comment by eranif** [comment]
Windows installers come in the form of `7-zip` files. You might have these files associated with your PDF extension on your machine. You will need to download `7-zip` https://www.7-zip.org/ and extract the binary
