### ISSUE TITLE
crash if renaming a project after mv'ing its directory

### ISSUE THREAD

**Issue by rnsanchez** [eranif/codelite#1979]
Certainly a weird way to ("physically") rename a project, but I mv'ed its directory outside of Codelite, and it crashed.  Steps:

1. make a simple console application
2. outside of Codelite, rename the application's directory (e.g.: `cd .. ; mv old-dir new-dir`)
3. Codelite will ask what to do with externally-modified files (I simply ignored it in the hopes of fixing that afterwards)
3. right-click on project in the workspace tab; Rename Project; OK
4. upon renaming it, Codelite instantly crashed

Codelite 12.0.0.

**Comment by eranif** [comment]
I am unable to reproduce this, I have tried without success.
Can you attach GDB to CodeLite and provide the backtrace?

```
$gdb /usr/bin/codelite
...
(gdb)run
...
<when-it-crashes>
(gdb)bt
```

**Comment by rnsanchez** [comment]
I tested it again a few times, and indeed it did not crash as it happened before.  However, the renamed project vanishes.  There might be some memory issue that triggered the crash.  Running with Valgrind, any chance the following helps?

    ==00:00:29:34.118 24015== Conditional jump or move depends on uninitialised value(s)
    ==00:00:29:34.118 24015==    at 0x878FAF: clMainFrame::OnDebugEnded(clDebugEvent&) (in /usr/bin/codelite)
    ==00:00:29:34.118 24015==    by 0x9ABC37D: wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) (in /usr/lib64/libwx_baseu-3.0.so.0.3.0)
    ==00:00:29:34.118 24015==    by 0x9ABC799: wxEvtHandler::SearchDynamicEventTable(wxEvent&) (in /usr/lib64/libwx_baseu-3.0.so.0.3.0)
    ==00:00:29:34.118 24015==    by 0x9ABC82E: wxEvtHandler::TryHereOnly(wxEvent&) (in /usr/lib64/libwx_baseu-3.0.so.0.3.0)
    ==00:00:29:34.118 24015==    by 0x9ABC8E2: wxEvtHandler::ProcessEventLocally(wxEvent&) (in /usr/lib64/libwx_baseu-3.0.so.0.3.0)
    ==00:00:29:34.118 24015==    by 0x9ABC944: wxEvtHandler::ProcessEvent(wxEvent&) (in /usr/lib64/libwx_baseu-3.0.so.0.3.0)
    ==00:00:29:34.118 24015==    by 0x8F3E80: Manager::DbgStop() (in /usr/bin/codelite)
    ==00:00:29:34.118 24015==    by 0x8F4BBB: Manager::ReloadWorkspace() (in /usr/bin/codelite)
    ==00:00:29:34.118 24015==    by 0x9ABC37D: wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) (in /usr/lib64/libwx_baseu-3.0.so.0.3.0)
    ==00:00:29:34.118 24015==    by 0x9ABC799: wxEvtHandler::SearchDynamicEventTable(wxEvent&) (in /usr/lib64/libwx_baseu-3.0.so.0.3.0)
    ==00:00:29:34.118 24015==    by 0x9ABC82E: wxEvtHandler::TryHereOnly(wxEvent&) (in /usr/lib64/libwx_baseu-3.0.so.0.3.0)
    ==00:00:29:34.118 24015==    by 0x9ABC8E2: wxEvtHandler::ProcessEventLocally(wxEvent&) (in /usr/lib64/libwx_baseu-3.0.so.0.3.0)
    ==00:00:29:34.118 24015==  Uninitialised value was created by a heap allocation
    ==00:00:29:34.118 24015==    at 0x4C2F17F: operator new(unsigned long) (vg_replace_malloc.c:334)
    ==00:00:29:34.118 24015==    by 0x8A726F: clMainFrame::Initialize(bool) (in /usr/bin/codelite)
    ==00:00:29:34.118 24015==    by 0x6C097F: CodeLiteApp::OnInit() (in /usr/bin/codelite)
    ==00:00:29:34.118 24015==    by 0x99C9511: wxEntry(int&, wchar_t**) (in /usr/lib64/libwx_baseu-3.0.so.0.3.0)
    ==00:00:29:34.118 24015==    by 0x62B36D: main (in /usr/bin/codelite)
    ==00:00:29:34.118 24015== 

The following is more or less when I closed CodeLite (it's the only of such, so there is a chance it is related to the vanished entry):

    ==00:00:36:22.023 24015== Conditional jump or move depends on uninitialised value(s)
    ==00:00:36:22.023 24015==    at 0x3225ED8E: NodeJSWorkspace::~NodeJSWorkspace() (in /usr/lib64/codelite/WebTools.so)
    ==00:00:36:22.023 24015==    by 0x3225F5D8: NodeJSWorkspace::~NodeJSWorkspace() (in /usr/lib64/codelite/WebTools.so)
    ==00:00:36:22.023 24015==    by 0x3225DD55: NodeJSWorkspace::Free() (in /usr/lib64/codelite/WebTools.so)
    ==00:00:36:22.023 24015==    by 0x3228F05D: WebTools::~WebTools() (in /usr/lib64/codelite/WebTools.so)
    ==00:00:36:22.023 24015==    by 0x3228F3D8: WebTools::~WebTools() (in /usr/lib64/codelite/WebTools.so)
    ==00:00:36:22.023 24015==    by 0x96D6DB: PluginManager::UnLoad() (in /usr/bin/codelite)
    ==00:00:36:22.023 24015==    by 0x8F47E8: Manager::~Manager() (in /usr/bin/codelite)
    ==00:00:36:22.023 24015==    by 0x8F4B38: Manager::~Manager() (in /usr/bin/codelite)
    ==00:00:36:22.023 24015==    by 0x897384: clMainFrame::~clMainFrame() (in /usr/bin/codelite)
    ==00:00:36:22.023 24015==    by 0x897848: clMainFrame::~clMainFrame() (in /usr/bin/codelite)
    ==00:00:36:22.023 24015==    by 0x9938CC1: wxAppConsoleBase::DeletePendingObjects() (in /usr/lib64/libwx_baseu-3.0.so.0.3.0)
    ==00:00:36:22.023 24015==    by 0x9938D30: wxAppConsoleBase::ProcessIdle() (in /usr/lib64/libwx_baseu-3.0.so.0.3.0)
    ==00:00:36:22.023 24015==  Uninitialised value was created by a heap allocation
    ==00:00:36:22.023 24015==    at 0x4C2F17F: operator new(unsigned long) (vg_replace_malloc.c:334)
    ==00:00:36:22.023 24015==    by 0x3225ED29: NodeJSWorkspace::Get() (in /usr/lib64/codelite/WebTools.so)
    ==00:00:36:22.023 24015==    by 0x32294D0C: WebTools::WebTools(IManager*) (in /usr/lib64/codelite/WebTools.so)
    ==00:00:36:22.024 24015==    by 0x32295BEA: CreatePlugin (in /usr/lib64/codelite/WebTools.so)
    ==00:00:36:22.024 24015==    by 0x96F958: PluginManager::Load() (in /usr/bin/codelite)
    ==00:00:36:22.024 24015==    by 0x8A6B0E: clMainFrame::CompleteInitialization() (in /usr/bin/codelite)
    ==00:00:36:22.024 24015==    by 0x8A7328: clMainFrame::Initialize(bool) (in /usr/bin/codelite)
    ==00:00:36:22.024 24015==    by 0x6C097F: CodeLiteApp::OnInit() (in /usr/bin/codelite)
    ==00:00:36:22.024 24015==    by 0x99C9511: wxEntry(int&, wchar_t**) (in /usr/lib64/libwx_baseu-3.0.so.0.3.0)
    ==00:00:36:22.024 24015==    by 0x62B36D: main (in /usr/bin/codelite)

There is a significant amount of leaks, so one of them could be related:

    ==00:00:36:32.011 24015== LEAK SUMMARY:
    ==00:00:36:32.011 24015==    definitely lost: 49,686 bytes in 487 blocks
    ==00:00:36:32.011 24015==    indirectly lost: 904,291 bytes in 9,186 blocks
    ==00:00:36:32.011 24015==      possibly lost: 7,117,381 bytes in 69,024 blocks
    ==00:00:36:32.011 24015==    still reachable: 5,098,390 bytes in 69,432 blocks
    ==00:00:36:32.011 24015==                       of which reachable via heuristic:
    ==00:00:36:32.011 24015==                         stdstring          : 448 bytes in 8 blocks
    ==00:00:36:32.011 24015==                         length64           : 9,296 bytes in 119 blocks
    ==00:00:36:32.011 24015==                         newarray           : 2,914,672 bytes in 7,402 blocks
    ==00:00:36:32.011 24015==         suppressed: 0 bytes in 0 blocks

I've attached the log in case you want to have a look.  Unfortunately it is rather large.
[valgrind-20180425_160103.log.gz](https://github.com/eranif/codelite/files/1948623/valgrind-20180425_160103.log.gz)
