### ISSUE TITLE
CodeLite building, Windows, MinGW: version of wxWidgets

### ISSUE THREAD

**Issue by conductor111** [eranif/codelite#1981]
There is some incorrect information in article "Compiling wxWidgets with MinGW" (http://codelite.org/Developers/BuildingWxWidgetsWin). 
1. There is said: "Download wxWidgets sources, CodeLite requires wxWidgets 3.0 or later from here".
But CodeLite cannot be build with wxWidgets-3.1.1.7, because this version of wxWidgets doesn't contains  wxUxThemeEngine class.
2. So, it's necessary to use wxWidgets-3.0 (f.e. wxWidgets-3.0.2.). But to compile wxWidgets in C++11 -std=c++11 should be replaced by -std=gnu++11, because the result of using -std=c++11 is undefined references in build process (https://forums.wxwidgets.org/viewtopic.php?t=40362).

**Comment by eranif** [comment]
1. I don't think that the code that refers to wxUxThemeEngine is still require, I will remove this
2. CodeLite is built with `-std=c++11` and not `-std=gnu++11` successfully (both wxWidgets and CodeLite itself), It depends on the compiler you use. We recommend to use MinGW 7.1 64bit or later

**Comment by conductor111** [comment]
2. I said about wxWidgets build process (-std=gnu++11 for wxWidgets-3.0 build process, not for codelite build process). 
I use MinGW 7.1 64bit.
