### ISSUE TITLE
subversion plugin : cannot handle unversioned files

### ISSUE THREAD

**Issue by jjvbsag** [eranif/codelite#1983]
I believe, this is introduced with
_"(11.0.8) Svn plugin: removed the tree view and use a standard table view instead"_

In the old version there was a tree item for unversioned files:
![svn-unversioned-files](https://user-images.githubusercontent.com/8567887/38853807-b5e47456-421e-11e8-8306-3cde9617ab52.png)

There I could add the file to the project or ignore the file via context menu on the items.

In Codelite 12 with the table view unversioned files are not listed and I have to use the command line to add or ignore items

**Comment by eranif** [comment]
You can still achieve this from the "Explorer" tab or, if the file is part of your project, by right clicking it -> svn->add

**Comment by jjvbsag** [comment]
Sorry, but this is no real solution for me. Having a project with ~ 2000 files.
* The explorer tab has _no_ indication about the svn status
* The explorer tab has _no_ link to the project. Regardless which workspace I open, it stays on the same folder
* Also in the Workspace tab there is _no_ indication for the svn status.

_And_ : It is simply not practical to browse through project trees with thousands of files to search for files missing in subversion. So _please_ add the unversioned files to the subversion tab again, as it was before.

---
Please have a look at my implementation of a subversion plugin for ZeroBrane Studio:
![svn-zbs-status](https://user-images.githubusercontent.com/8567887/38860251-0f9c1ed4-4230-11e8-987c-b650bd06e958.png)

You have unversioned files listed in the pending changes tab and there you can simple add or ignore the files. Also I have status symbols attached in the file tree, so I can see, which files are affected there. 

Just a suggestion :beer:

**Comment by jjvbsag** [comment]
@eranif: is there any hope, the unversioned files will make it back into the subversion tab or do I need to continue using the command line?

**Comment by eranif** [comment]
This is now fixed in master
![svn-console](https://user-images.githubusercontent.com/3677711/39776086-8378c8a0-5308-11e8-9a6a-b0ae2e42035d.png)

**Comment by jjvbsag** [comment]
Nice solution, thanks :+1:
