### ISSUE TITLE
SVN panel does not display newly added files

### ISSUE THREAD

**Issue by sgchris** [eranif/codelite#1994]
If I add files outside of CL, they are not reflected in CL in SVN panel

**Comment by eranif** [comment]
click the refresh button

**Comment by sgchris** [comment]
The new files are displayed with a question mark ("svn st" command) only in a terminal.
In my case I had new folder (with two new files).

**Comment by eranif** [comment]
Non versioned files are not shown. Only indexed files. You will need to add them to SVN first. You can do this from the `Explorer` tab or by right clicking the file in the `Workspace` view and add them from there
