### ISSUE TITLE
Newly downloaded stable release immediately reports new version.

### ISSUE THREAD

**Issue by TELunus** [eranif/codelite#1997]
I just installed the stable release from the website (12.0 currently), and when I opened it there was immediately a dialog box telling me that there was a new version.  When I looked at the version number under Help->About... it said version 12.0.0.  So I went back to the website to check, and it said the stable release is 12.0, and the weekly build is version 12.0.1.

I can see how if I was running the weekly build it might be useful to tell me about a new weekly build, but since I specifically made the choice to use the stable version I expect not to be told that there's another version until another version is released as stable.

I'm running the 64 bit installer windows version on windows 10.

**Comment by eranif** [comment]
This is the default behaviour of CodeLite (notify about any new version)
You can change it to notify you for stable releases only from:
`Settings->Preferences->Misc->General->Prompt for stable releases only`
