### ISSUE TITLE
Error performing last git action on git --no-pager ls-files -m

### ISSUE THREAD

**Issue by An-S** [eranif/codelite#1998]
Without any obvious reason i frequently get the following error message with Codelite git plugin:

There was a problem while performing last git action.
Last command output:
mydir/myfile1.c
mydir/myheader1.h

The placeholders my* represent latest modified files in my repository. They consist of a path (without space, only lower case letters) and a filename with lowercase letters, an underscore and an extension separated by a period.
That's why i took the opportunity to open a new issue, which obviously is different from the space in filename issue.

The output of "git --no-pager ls-files -m" on the command line shows no error:
$/usr/bin/git --no-pager ls-files -m
mydir/myfile1.c
mydir/myheader1.h

The output of "git --no-pager status -s" on the command line shows also no error:
$/usr/bin/git --no-pager Status -s
M mydir/myfile1.c
M mydir/myheader1.h

Obviously the performed git actions succeeded despite the error message. This is a misleading behaviour probably caused neither by a bad repository state nor unsupported filenames and occurs only from within the codelite IDE.

**Comment by eranif** [comment]
It will be helpful to see the **exact** error message you are getting. This message printed when the output from `git` starts with the words `fatal` or `error` (partially or full)
