### ISSUE TITLE
Flashing on lower and upper parts of code editor C++

### ISSUE THREAD

**Issue by shadoww1028** [eranif/codelite#2000]
When scrolling up and down the editor flashes on the top or bottom depending on the direction scrolling. I tested this with version 11 and 9.3 in a Linux MATE VM (mint) and this was no longer present but after reinstalling version 12 it was back. I have seen this on Linux Mint Cinnamon (main machine) and Mate (VM).  Many tabs must be open.

This can only be seen if using a dark color scheme in the desktop environment. Also when starting a debugging session there is a lot of flashing.  I have also tried this on a second computer on Linux MINT MATE and have seen the same flashing in 12 and not 11.  If you only have one tab open it will not occur and it will start when 2 or more tabs are open (code files) the more tabs the worse it gets.

**Comment by eranif** [comment]
This is a side effect of the `wxStyledTextCtrl` when having the feature: `Settings -> Preferences -> Editor -> Caret & Scrolling -> Auto-adjust horizontal scrollbar width`, disable it and should be gone

**Comment by shadoww1028** [comment]
Thanks for the reply and Thank you for your hard work.
