### ISSUE TITLE
Changing terminal command has no effect

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#2001]
This might possibly be related to #1941. Using CodeLite 12 on Fedora 28: changing terminal command to "/usr/bin/gnome-terminal '$(TITLE)' '$(CMD)'" in Settings - Editor Settings - Terminal doesn't seem to make any effect and CodeLite continues to use XTerm.

**Comment by aviallon** [comment]
I have the same bug with codelite 12.0.1
I'll build it from source to be sure this problem isn't there anymore.

**Comment by yunkot** [comment]
This is still present in latest GitHub revision. I've tried to override this behavior by renaming "codelite_xterm" and creating a symlink to "gnome-terminal", but this doesn't work (terminal is opened without running application). Is there any known workaround?

**Comment by aviallon** [comment]
Well I would like to have my default Terminal when I get program output when debugging.

**Comment by yunkot** [comment]
The workflow is quite simple: open C or C++ project (that uses console), hit F5 and expect it to run within your favorite console application - in my case, it is gnome-terminal. In fact, any terminal would work other than xterm, which uses tiny unconfigurable fonts and doesn't respect GTK theme at all (everything uses dark theme, but codelite_xterm uses tiny black fonts on white background, which really hurts my eyes).

In earlier versions, I could uncheck "Use CodeLite's built-in terminal emulator", type aforementioned command and it would work, but now in either case CodeLite uses its built-in xterm console.

**Comment by eranif** [comment]
This is now fixed (git master)
You can pick one of `konsole`, `gnome-terminal` or `lxterminal` (more to be added soon)
When you select it from preferences->Terminal, it will affect the workflows within CodeLite
