### ISSUE TITLE
CodeLite's editor ignores Gnome's text hinting settings

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#2002]
This is somewhat related to issue #1958. I'm reproducing this in CodeLite 12 on fresh installation of Fedora 28. In Gnome, when you use **Tweaks tool** to adjust text hinting in **Fonts** - **Hinting** to **Full**, most of applications will respect it, except CodeLite, which for some reason will continue to use **Slight** settings. 

This is how it looks when using Consolas font at size 13 with **Text Hinting** - **Full** selected in Gnome:
![codelite-slight](https://user-images.githubusercontent.com/14065837/39589715-994854b8-4ec4-11e8-9456-aec409459f32.png)

Notice low-case letter "f" that has small distance between top cap and division. In Full text hinting, the distance should be bigger, text should look sharper and about 1-2 pixels less tall. This is especially noticeable on a Portrait monitor configuration as it affects how many lines of code you see. The correct appearance is the following (which looks almost identical to Visual Studio on Windows with the same font/size):
![codelite-full](https://user-images.githubusercontent.com/14065837/39590200-d59fdee4-4ec5-11e8-8270-6836eb814430.png)

I don't know if something can be done in CodeLite to make sure the editor respects Gnome settings, but there is a workaround: create **$HOME/.fonts.conf** file with the following contents:

```
<match target="font" >
  <edit name="hintstyle" mode="assign">
    <const>hintfull</const>
  </edit>
</match>

```
After creating above file, restart CodeLite and it should start to use proper hinting. If this cannot be fixed on CodeLite's side, I suggest to keep this issue alive with the workaround documented, in case anyone else encounters this problem.

**Comment by eranif** [comment]
CodeLite uses `wxStyledTextCtrl` (part of the wxWidgets library). If this can be fixed somewhere, then it should be in the `wxWidgets` toolkit.

I will copy this post to our wiki and will close this bug
