### ISSUE TITLE
help plz urgent.....

### ISSUE THREAD

**Issue by jakeblack24** [eranif/codelite#2011]
i made a new project and when I tried to run it it kept crashing after downloading  libgcc_s_dw2-1.dll it doesn't work the debugger writes
0  0x6fc92e94  libstdc++-6!_ZNSi6sentryC1ERSib    
1  0x6fc93a3f  libstdc++-6!_ZNSirsERi    
2  0x0040149a  _fu2___ZSt3cin  C:\\Users\\coder\\Desktop\\CPPProjects\\Section 4\\Firstprogram\\main.cpp  9

**Comment by eranif** [comment]
This is not related to CodeLite. Please find a C++ forum and post there
