### ISSUE TITLE
Ubunutu 18.04 Install issue - 12.0.2

### ISSUE THREAD

**Issue by iphorde** [eranif/codelite#2012]
(dpkg-preconfigure:813): Gtk-WARNING **: 07:58:20.210: Theme parsing error: gtk-main.css:73:38: Failed to import: Error opening file /usr/share/themes/Radiance/gtk-3.20/apps/gnome-builder.css: No such file or directory

(dpkg-preconfigure:811): Gtk-WARNING **: 07:58:20.249: Theme parsing error: gtk-main.css:73:38: Failed to import: Error opening file /usr/share/themes/Radiance/gtk-3.20/apps/gnome-builder.css: No such file or directory
Selecting previously unselected package clang-format-6.0.
(Reading database ... 538604 files and directories currently installed.)
Preparing to unpack .../0-clang-format-6.0_1%3a6.0-1ubuntu2_amd64.deb ...
Unpacking clang-format-6.0 (1:6.0-1ubuntu2) ...
Selecting previously unselected package libbsd-dev:amd64.
Preparing to unpack .../1-libbsd-dev_0.8.7-1_amd64.deb ...
Unpacking libbsd-dev:amd64 (0.8.7-1) ...
Selecting previously unselected package libclang-6.0-dev.
Preparing to unpack .../2-libclang-6.0-dev_1%3a6.0-1ubuntu2_amd64.deb ...
Unpacking libclang-6.0-dev (1:6.0-1ubuntu2) ...
Selecting previously unselected package libedit-dev:amd64.
Preparing to unpack .../3-libedit-dev_3.1-20170329-1_amd64.deb ...
Unpacking libedit-dev:amd64 (3.1-20170329-1) ...
Selecting previously unselected package libhunspell-dev:amd64.
Preparing to unpack .../4-libhunspell-dev_1.6.2-1_amd64.deb ...
Unpacking libhunspell-dev:amd64 (1.6.2-1) ...
Selecting previously unselected package liblldb-6.0.
Preparing to unpack .../5-liblldb-6.0_1%3a6.0-1ubuntu2_amd64.deb ...
Unpacking liblldb-6.0 (1:6.0-1ubuntu2) ...
Selecting previously unselected package python-lldb-6.0.
Preparing to unpack .../6-python-lldb-6.0_1%3a6.0-1ubuntu2_amd64.deb ...
Unpacking python-lldb-6.0 (1:6.0-1ubuntu2) ...
Selecting previously unselected package lldb-6.0.
Preparing to unpack .../7-lldb-6.0_1%3a6.0-1ubuntu2_amd64.deb ...
Unpacking lldb-6.0 (1:6.0-1ubuntu2) ...
Selecting previously unselected package liblldb-6.0-dev.
Preparing to unpack .../8-liblldb-6.0-dev_1%3a6.0-1ubuntu2_amd64.deb ...
Unpacking liblldb-6.0-dev (1:6.0-1ubuntu2) ...
Selecting previously unselected package libsqlite3-dev:amd64.
Preparing to unpack .../9-libsqlite3-dev_3.22.0-1_amd64.deb ...
Unpacking libsqlite3-dev:amd64 (3.22.0-1) ...
Setting up libsqlite3-dev:amd64 (3.22.0-1) ...
Setting up libhunspell-dev:amd64 (1.6.2-1) ...
Setting up libbsd-dev:amd64 (0.8.7-1) ...
Setting up clang-format-6.0 (1:6.0-1ubuntu2) ...
Setting up python-lldb-6.0 (1:6.0-1ubuntu2) ...
Setting up libclang-6.0-dev (1:6.0-1ubuntu2) ...
Setting up liblldb-6.0 (1:6.0-1ubuntu2) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Setting up libedit-dev:amd64 (3.1-20170329-1) ...
Processing triggers for man-db (2.8.3-2) ...
Setting up lldb-6.0 (1:6.0-1ubuntu2) ...
Setting up liblldb-6.0-dev (1:6.0-1ubuntu2) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Selecting previously unselected package codelite.
(Reading database ... 540263 files and directories currently installed.)
Preparing to unpack .../CodeLite-12.0.2-gtk2-ubuntu-bionic-x86_64.deb ...
Unpacking codelite (12.0.2-gtk2) ...
dpkg: error processing archive /home/bgg/Downloads/CodeLite-12.0.2-gtk2-ubuntu-bionic-x86_64.deb (--install):
 trying to overwrite '/usr/share/codelite/wxgui.zip', which is also in package wxcrafter 2.9-1unofficial.xenial
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Processing triggers for desktop-file-utils (0.23-1ubuntu3) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Errors were encountered while processing:
 /home/bgg/Downloads/CodeLite-12.0.2-gtk2-ubuntu-bionic-x86_64.deb

**Comment by eranif** [comment]
> trying to overwrite '/usr/share/codelite/wxgui.zip', which is also in package wxcrafter 2.9-1unofficial.xenial

You first need to purge any version of CodeLite/wxCrafter:

```
sudo apt-get purge codelite wxcrafter
```
and then re-install CodeLite + wxCrafter
