### ISSUE TITLE
New version available - 'download' opens thunderbird instead

### ISSUE THREAD

**Issue by cristiano-di-buduo** [eranif/codelite#2013]
The issue is captured succinctly in the caption: when CodeLite prompts at startup that "A new version is available for download", and subsequently pressing the "Download"-button, my ThunderBird email-client is run in stead of whatever is supposed to happen. This happened in version 11, and version 12 displays the same behaviour.

I use the latest Kubuntu (x86_64) just released, but the previous versions made no difference. Note that ThunderBird is not really started (opens no window) but Plasma turns the cursor into a bouncing ThunderBird icon and the taskbar shows a ThunderBird button for ten seconds until it disappears again. A 'thunderbird'-process does keep running invisibly on the background, however. When actually starting the email client afterwards the window does get created as expected.

**Comment by adamteale** [comment]
Similar for me too but rather Firefox is opened - running Ubuntu 16.04

**Comment by eranif** [comment]
CodeLite uses the default browser, it does not download the file itself.
It launches the program which is associated with the URL handler ("http") and should navigate to the download page. nothing more

This is what is configured on your machine (firefox in this case)
