### ISSUE TITLE
Editor flickers on vertical scrolling

### ISSUE THREAD

**Issue by zenera** [eranif/codelite#2014]
Codelite editor screen fickers on vertical mouse scrolling. Reproducible in black background.
- My system: Codelite 12.0/Ubutu 18.04

**Comment by eranif** [comment]
This is a known issue with latest wxWidgets library
The workaround is simple:
`Settings->Preferences->Caret & Scrolling->Auto adjust horizontal scrollbar width`
The new default is already updated in latest git master
