### ISSUE TITLE
Add keyboard short cut for tabs navigation [feature request]

### ISSUE THREAD

**Issue by givanz** [eranif/codelite#2016]
Hi

Great work, I have a small feature request that will probably help many other.

**View > Next/Previous Tabs** Commands don't have keyboard shortcuts, most editors use CTRL + Page Down/Up for easy tabs navigation, using CTRL+SHIFT+TAB for Select Tab window and then up/down arrows to select the tab is cumbersome.

This is probably easy to add and is useful to manage many open tabs.

Thanks.

**Comment by eranif** [comment]
This is already implemented in git master. I assume that you are using CodeLite 12.0?
