### ISSUE TITLE
How to change back the run command

### ISSUE THREAD

**Issue by izhakjakov** [eranif/codelite#2017]
How to change the run command to ask before executing?
(The way it is when installing fresh)

**Comment by izhakjakov** [comment]
To clarify I mean the menu entry under "Build" (ctrl+F5)

**Comment by dghart** [comment]
This is not a bug, but a question that should have been asked on the CodeLite forum: http://codelite.org/forum/

See 'Settings > Preferences > Misc: History: Reset annoying dialogs answers', which will reset all of those settings (there's no way to reset an individual one).

**Comment by izhakjakov** [comment]
Make sense
I will post in the forum next time I have a question.
Thank you for your answer, it worked  :-)
