### ISSUE TITLE
Codelite 12 loses project files not in a virtual directory

### ISSUE THREAD

**Issue by hipnition** [eranif/codelite#2021]
In 11 and earlier, you could have files in a project that were not part of a virtual directory and they showed and worked great on the UI. In 12, those files are missing on the UI. If, like a lot of people, you want project organization to be similar to directories, this is a great feature. Please bring it back.

In the below file...xx, yy, and zz no longer show up.

Project File:
<?xml version="1.0" encoding="UTF-8"?>
<CodeLite_Project Name="6510" InternalType="">
  <VirtualDirectory Name="src">
    <VirtualDirectory Name="include">
      <File Name="ssss.h"/>
    </VirtualDirectory>
    <VirtualDirectory Name="emulation">
      <File Name="qqqq.c"/>
    </VirtualDirectory>
    <File Name="src/main.gpj"/>
    <VirtualDirectory Name="help">
      <File Name="dddd.cpp"/>
    </VirtualDirectory>
  </VirtualDirectory>
  <File Name="xx.gpj"/>
  <File Name="yy.ld"/>
  <File Name="zz.gpj"/>
</CodeLite_Project>

**Comment by eranif** [comment]
It was never possible in CodeLite. Unless you hacked the project file by hand. Its by design
