### ISSUE TITLE
No build information ,v12.0.0

### ISSUE THREAD

**Issue by q962** [eranif/codelite#2025]
No build information ,v12.0.0

**Comment by eranif** [comment]
I am not sure what you mean by that. Anyways, I dont see a "real" bug here

**Comment by q962** [comment]
ok，[image](https://alatcg.dm.files.1drv.com/y4m0mnuQFvqmB9HKAL23UsFqnNlDUxjFjZlNjCh4wNUff3v9m-qi9I_Mf1EN4BMJwvt_ttE09jS0b41DY-Ys3THxyGe0jY2idr6UO9D7HwJ9PFb5MBbKXXxABr_bVdeTDDdTthzWeQn-uif8e6m-kT4x9Jbm9D9AqDS7PZF9qp1StyAhKmmQpEQ4ZD-k65Qvs05RN1oraZzeJRZW14Ht1RRCg?width=1284&height=922&cropmode=none)

Address backup
https://1drv.ms/u/s!AjEPM2qBuKhojlSwjPOzEPizlqYq


The new project has information. One minute ago, I changed the software language. There is no information at this time.
-- google translate

**Comment by q962** [comment]
The new project has information. One minute ago, I changed the software language. There is no information at this time.
-- google translate

I use Windows.

image 
![2018 5 30 16-53-55](https://user-images.githubusercontent.com/15686075/40714538-7fc86e3e-6435-11e8-94ef-21e4fe2c807c.gif)

**Comment by q962** [comment]
`
C:\WINDOWS\system32\cmd.exe /C ""C:/Program Files/mingw-w64/x86_64-7.2.0-release-posix-seh-rt_v5-rev0/mingw64/bin/mingw32-make.exe" -j4 SHELL=cmd.exe -e -f  Makefile"
"----------Building project:[ HELLO - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'C:/Users/q962_/Documents/Visual Studio 2017/Projects/设计模式/HELLO'
"C:/Program Files/mingw-w64/x86_64-7.2.0-release-posix-seh-rt_v5-rev0/mingw64/bin/g++.exe"  -c  "C:/Users/q962_/Documents/Visual Studio 2017/Projects/设计模式/HELLO/main.cpp" -g -O0 -Wall  -o ./Debug/main.cpp.o -I. -I.
g++.exe: error: C:/Users/q962_/Documents/Visual Studio 2017/Projects/设计模式/HELLO/main.cpp: No such file or directory
g++.exe: fatal error: no input files
compilation terminated.
mingw32-make.exe[1]: *** [HELLO.mk:97: Debug/main.cpp.o] Error 1
mingw32-make.exe: *** [Makefile:5: All] Error 2
mingw32-make.exe[1]: Leaving directory 'C:/Users/q962_/Documents/Visual Studio 2017/Projects/Éè¼ÆÄ£Ê½/HELLO'
====0 errors, 0 warnings====
`
This is the new project information

[HELLO.mk.txt](https://github.com/eranif/codelite/files/2053515/HELLO.mk.txt)

I think there is a problem with the module that created the makefile

**Comment by q962** [comment]
Very interesting, after a long time off, recompile, now display the message.
I did not change any options.

**Comment by q962** [comment]
I don't think non-ASCII encoding will prevent compilation. But he did happen.

I can only use ASCII characters.
