### ISSUE TITLE
CL fails to run application

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#2031]
Hi Eran,

CL stops enabling "Run" after some time.
I run my application and it works just fine, but after multiple runs it stops working. "Run" is disabled in the menu, hitting "Stop" or using the menu entry does nothing. After a restart of CL it works again. Unfortunately I can't put my finger on a commit when it stopped working.

This happens on git HEAD on Linux. The application is configured to pop up a terminal.

Best regards,
  René

**Comment by eranif** [comment]
when was the last time you updated your sources?

**Comment by upCASE** [comment]
This morning.
c826e8deb2eaabdc -  Fixed: Doxygen tweaks use wrong line ending

**Comment by eranif** [comment]
I did a commit today at around 14 pm that fixed this issue. 
can you please update and confirm?

**Comment by eranif** [comment]
this is the commit: 
https://github.com/eranif/codelite/commit/89437e2c1caf72611b935f868e28472cbf5f445d

**Comment by upCASE** [comment]
Just did some quick testing and up until now it works fine!
Thanks heaps!

I'll close this and reopen if this pops up again.

**Comment by eranif** [comment]
Thanks for checking this.  I thought i was the only one noticing this bug... ( it only happened for me on a certain workspace)

**Comment by upCASE** [comment]
No problem. It actually happend one more then one of my machines using a different setup. I thought I might have broken somehting in my setup. :-)
