### ISSUE TITLE
Can we add a "fullscreen editor" like NetBeans?

### ISSUE THREAD

**Issue by pbbob1** [eranif/codelite#2032]
NetBeans has an option to enable "full screen editor", under view -> show only editor. I know that you can make the entire codelite IDE fullscreen with alt+m, But the fullscreen editor mode makes only the actual code fullscreen. it hides all the toolbars and menus so that you can just focus on the code. Can we add a feature like this to codelite?

**Comment by eranif** [comment]
You can do that in CodeLite but hitting `Ctrl-M`, or double clicking an editor's tab label.

Note: If you are using the 'native' toolbar, it won't be hidden when doing so. You will need to disable this option. This can be done from: `Settings->Preferences->Misc->Use native toolbar`
