### ISSUE TITLE
Random empty Workspace view and editor at start

### ISSUE THREAD

**Issue by Zac610** [eranif/codelite#2038]
CodeLite version: 12.0.0

Tried to capture screenshot resizing the window, got also non updating graphic.

Workaround: restart codelite

https://www.dropbox.com/s/8bd3wfwf4hn5l5h/codelite-empty.png?dl=0

**Comment by eranif** [comment]
Can you try CodeLite 12.0.3? 
To install it, follow the instructions here: https://forums.codelite.org/viewtopic.php?f=20&t=3955

**Comment by Zac610** [comment]
Not appearing anymore in 12.0.1
