### ISSUE TITLE
Crashes when searching for shortcuts

### ISSUE THREAD

**Issue by Panda1638** [eranif/codelite#2041]
I freshly installed codelite from the official repos on Mint 18.3. I wanted to costumise the hotkeys. After codelite told me that the combination is in use, i tried to search the function blocking it. Soon after trying to type in the searchbar the programm crashes with a segmentation fault.
This does not happen when i start codelite with sodo.

**Comment by eranif** [comment]
This was already fixed in CodeLite 12.0.x (can't remember the exact version)
You can try one of .deb files I upload as weekly builds from here: https://downloads.codelite.org/
I am not sure if Ubuntu 16.04 / 18.04 will work for you, but you can try
