### ISSUE TITLE
Speed of the editor of 12.0.3 versus 12.0.0 / 12.0.1 / 12.0.2

### ISSUE THREAD

**Issue by jpduval2015** [eranif/codelite#2046]
The editor of the version 12.0.3 is very slow in comparison previous version. Especially when changing tab. Sometimes, it takes 10 seconds. Quite unusable. I think is linked to the syntax colouring but I am not sure.
Open numerous and large files to live the issue.
I uninstalled 12.0.3 and I am back in 12.0.0, which is working well for this issue.

**Comment by jpduval2015** [comment]
I have a large project and I am used to open many, many files. Sometimes, more than 50 cpp source files. On average 10 000 to 20 000 lines per file.
I used 12.0.0 for a while on Ubuntu 16.04 amd 64 bits. And one day, I made a mistake, I accepted the weekly build. So, to avoid the messages "do you want the new version", I accepted 12.0.1, then 12.0.2. No problem to use them for the same behaviour of myself. Even more stable, thanks.
I did the same for 12.0.3 a couple of days ago. And from the beginning, Code Lite was slower. And the average temperature of my laptop increased from 50°C to 57°C. 
I think it is linked to the syntax colouring or the database you use to maintain the keywords list. Or due to a component you use for the editor. It seems to be the real-time parsing of files is heavy.
From synaptic, quite right before sending you my message, I just removed Codelite 12.0.3 then installed the 12.0.0 one. And it works at normal speed again.

**Comment by eranif** [comment]
Can you upload a minimal workspace that reproduces this issue?

**Comment by jpduval2015** [comment]
Ok, I am downloading last source tarball, I will recompile after and I will tell you.

**Comment by jpduval2015** [comment]
In README.md, you wrote : 
    Run CMake and build CodeLite:
    cd codelite
    mkdir build-release
    cd build-release
    cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
    make -j4
    sudo make install

But  "cd build-release" is a mistake for the cmake command. We musn't. Here is the message : 

CMake Error: The source directory "/home/jpd/Téléchargements/codelite-master/build-release" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

Ok now recompiled in release mode and I installed from local. Not a 12.0.3 but a 12.0.4. Right for you ? I open the project and it is slow !

**Comment by jpduval2015** [comment]
Not as slow as 12.0.3 that was unusable. But slower that 12.0.0.
Something has change : the menu bar. And even the dialog boxes take more time to be opened. For example,  "Setting - Code completion". More than 1 second. The same for other dialog boxes.
It seems to be linked to "Code completion" / "Colouring" / "Apply context aware colouring". When not checked, speed is better.
Parsing policy was "On file load". I switched to "Lazy". Speed is better when changing tab and with "Apply context aware colouring" checked.

**Comment by jpduval2015** [comment]
It seems to be link to the use of libclang.so. You require version 4 of the library. I had only version 3.
With version 4 I just installed, the performance is better.
