### ISSUE TITLE
Missing shared libraries in debian package 12.03

### ISSUE THREAD

**Issue by vortex314** [eranif/codelite#2047]
$ codelite
codelite: error while loading shared libraries: libssh.so.4: cannot open shared object file: No such file or directory
Downloaded the .deb version 12.03 on lubuntu 
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
Package : CodeLite-12.0.3-gtk2-ubuntu-bionic-x86_64.deb

I upgraded from the official version 10.0 because plugins were not available.

**Comment by dghart** [comment]
Sounds as if you need to do:
sudo apt install libssh-4

**Comment by vortex314** [comment]
Great, this worked !
Thanks !
