### ISSUE TITLE
sftp plugin tab dosnt apear in windows 10

### ISSUE THREAD

**Issue by jcbritobr** [eranif/codelite#2055]
How to reproduce:

1 - Install codelite
2 - Enable sftp plugin
3 - restart

expected behavior - see sftp tab in codelite
observed - sftp tab doesnt appear, and there is no option to turn it on.

**Comment by eranif** [comment]
if you click on the 3 dots button,  (it is placed on the top right side of the workspace view), you can pick the sftp from the.

**Comment by jcbritobr** [comment]
cant see this dots, and even in the arrow of tabs, the sftp tool is not there.

![codelite](https://user-images.githubusercontent.com/6579862/42226437-54d59914-7eb5-11e8-9f43-f9374dd1fa57.png)

**Comment by eranif** [comment]
`crtl-f11` or `view->toggle minimal view`
and you will be able to see it

**Comment by jcbritobr** [comment]
Yes, got it here. Thank you. 
Ill close the ticket here.
