### ISSUE TITLE
Workspace parser does not find enum with C++11 typed enum

### ISSUE THREAD

**Issue by jjvbsag** [eranif/codelite#2057]
Take the following sample code

**enums.h**:
```c++
#pragma once

enum E_CLASSIC
{
	CLASSIC_A=1,
	CLASSIC_B=2,
};

enum E_LONG : unsigned long
{
	LONG_A=1L,
	LONG_B=2L,
};
```
**main.cpp**:
```c++
#include <stdio.h>
#include "enums.h"

int main(int argc, char **argv)
{
	E_CLASSIC eClassic=CLASSIC_A;
	E_LONG eLong=LONG_B;
	printf("eClassic=%d\n",eClassic);
	printf("eLong=%ld\n",eLong);
	return 0;
}
```
Let Codelite parse the workspace. 
![image](https://user-images.githubusercontent.com/8567887/42447958-df5bf144-837b-11e8-9112-18710a54858c.png)
You can see, `E_CLASSIC` is colored as a known type, `E_LONG` is not.
Doing RMK/"Goto Declaration" on `E_CLASSIC` will show the correct location in the header file.
Doing RMK/"Goto Declaration" on `E_LONG` does nothing. :cry:

**Comment by jjvbsag** [comment]
Forgot to mention. **CodeLite 12.0.1**

**Comment by eranif** [comment]
Confirmed.
As a workaround, you can use this syntax:

```c++
enum class eLongType : unsigned long
{
	LONG_A = 1L,
	LONG_B = 2L,
};
```

and then in your code:
```c++
int main(int argc, char **argv)
{
    eLongType::LONG_A // Should work
}
```

**Comment by jjvbsag** [comment]
I would not touch a project with ~ 412.000 LoC for this as it would require major edits and then testing. For now my workaround is "Find in files ..." for `enum E_LONG` ¹ 

Regards :beer:

---
¹ Inserting the correct enum name :grin:

**Comment by LCWilliams** [comment]
Just a bump for this.
Is this why my strong/enum class members don't show up in code-completion?  Only the enum class itself shows up.

`enum class ExampleEnum : int{
    item1 = -2;
    item2 = -1;
    item3 = 0;
}`

When typing `ExampleEnum::` none of the items are displayed.

**Comment by jjvbsag** [comment]
Just a hint: First try correct C++
```c++
enum class ExampleEnum : int{
    item1 = -2,
    item2 = -1,
    item3 = 0
};
```
:beer:

**Comment by LCWilliams** [comment]
> Just a hint: First try correct C++
> 
> ```c++
> enum class ExampleEnum : int{
>     item1 = -2,
>     item2 = -1,
>     item3 = 0
> };
> ```

Ha.  force of habit-  it is typed correctly in my code. xD

**Comment by eranif** [comment]
The recommended code completion is the `Language Server`.
You can enable it and this will get fixed for you.

https://wiki.codelite.org/pmwiki.php/Main/LanguageServer

**Comment by LCWilliams** [comment]
hey Erin,
Apologies for being a pain in the arse (and delayed response); do we need to manually set up a language server?
I've had the `Enable language server completion` checked since project creation and still have the issue; so I'm assuming the built-in ctags doesn't cover these enums?

**Comment by eranif** [comment]
Thanks for reporting this, I will try and make the LS with clangd more easy

**Comment by eranif** [comment]
BTW, when you change any settings in the clangd configuration page, you don't need to restart CodeLite, CodeLite will restart the LSP automatically for you

**Comment by morgoth6** [comment]
Try https://github.com/MaskRay/ccls as it seems to be much better than pure clangd and persistent cache gives nice performance boost.

**Comment by eranif** [comment]
@morgoth6 I am using clangd v8 which performs instantly on CodeLite source base (about 2.5k files)
I see no reason to switch
