### ISSUE TITLE
CodeLite immediately exits

### ISSUE THREAD

**Issue by TheComet** [eranif/codelite#2058]
I don't know what I'm doing wrong, but I've tried compiling version 12.0 from the source tarball and master. Both compile fine (apart from having to fix #2052) but when I try to execute the codelite executable it immediately exits. No GUI opens, nothing happens. The process returns exit code 0377.

My build process is:
```sh
git clone https://github.com/eranif/codelite
mkdir build && cd build
cmake ..
make -j32
make install DESTDIR=~/codelite
```
Executing it:
```
cd ~/codelite/bin
LD_LIBRARY_PATH=../lib64/codelite ./codelite
(process exits with 0377)
```

Possibly relevant info?
```
$ uname -a
Linux ripper 4.14.52-gentoo #1 SMP Sat Jun 30 22:50:39 CEST 2018 x86_64 AMD Ryzen Threadripper 1950X 16-Core Processor AuthenticAMD GNU/Linux

$ gcc --version
gcc (Gentoo 7.3.0-r3 p1.4) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ cmake --version
cmake version 3.9.6

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by dghart** [comment]
>LD_LIBRARY_PATH=../lib64/codelite

Presumably that path exists...

I suspect it's your use of DESTDIR that is somehow responsible. If you want to investigate, perhaps running inside gdb will give more information; and the output of ldd might also be of interest.

More usefully I suggest you rebuild, differently. If you want to install to `~/codelite`, do:
`cmake -DCL_PREFIX=~/codelite ..`
(though I'm not sure if cmake can cope with '~' so the full path would be safer). You should then be able to run without specifying a LD_LIBRARY_PATH.

**Comment by TheComet** [comment]
Setting ```-DCL_PREFIX``` fixed it. It would be nice if it used ```CMAKE_INSTALL_PREFIX``` instead though, that's what I tried first.

**Comment by dghart** [comment]
CMAKE_INSTALL_PREFIX worked with earlier cmake versions, but not since 3.0. For details see the top-level [CMakeLists.txt](https://github.com/eranif/codelite/blob/master/CMakeLists.txt), currently line 166 et seq.
