### ISSUE TITLE
Is Database Explorer broken on Windows?

### ISSUE THREAD

**Issue by ptrongithub** [eranif/codelite#2062]
Upon installing the Database Explorer plugin, the only change to the CodeLite interface is a submenu under Plugins -> Database Explorer, with the options About... and Execute SQL. I know there should be more to it, however . . . . (CodeLite 12.0.4, Windows 10 Pro, Cygwin64)
As I am mostly developing with databases, having this feature to work is critical.

**Comment by eranif** [comment]
In the workspace view, in the DbExplorer tab you should have all the options that you need (open database etc)

**Comment by ptrongithub** [comment]
What DbExplorer tab? There is no DbExplorer tab.

**Comment by eranif** [comment]
If you dont have the DbExporer tab, click on the 3 dots button (next to the 'x' button in the workspace view) and select it.

See the image attached:
<img width="432" alt="dbexplorer" src="https://user-images.githubusercontent.com/3677711/43014546-2bf1f972-8c55-11e8-810f-f869bf4ced4f.png">

If you don't have the 3 dots button (or the caption), select from the menu `View->Toggle Minimal View` (twice if needed) to make it visible

**Comment by ptrongithub** [comment]
Problem solved! (Please see my next issue....)
