### ISSUE TITLE
Icons too small

### ISSUE THREAD

**Issue by ptrongithub** [eranif/codelite#2063]
Can you please update the interface for those of us burdened by a UHD/4K display?
![image](https://user-images.githubusercontent.com/26679996/43015034-49a4c384-8c1c-11e8-9bad-5c78400624e3.png)

**Comment by billcxx** [comment]
![image](https://user-images.githubusercontent.com/3356113/60374870-8087a300-99d4-11e9-95e7-3983a3f300e6.png)

Same problem
