### ISSUE TITLE
Unable to open LiteEditor.workspace using Codelite

### ISSUE THREAD

**Issue by stevenleigh** [eranif/codelite#2064]
Opening LiteEditor.workspace in latest master using latest weekly release of Codelite hangs.

Version of LiteEditor.workspace: (SHA1 of commit) 5903ce4224854a4b89ab0d58a2017151c6994ff0
Version of Codelite: v12.0.4 (Weekly build)
OS version: Win 8.1 x64

I tried removing lines from LiteEditor.workspace to try and narrow down the problem.  I've attached a version that now opens
[LiteEditor.workspace.zip](https://github.com/eranif/codelite/files/2217177/LiteEditor.workspace.zip)

but when I select a build configuration Codelite again hangs.  I've attached a log of this
[codelite.log.zip](https://github.com/eranif/codelite/files/2217175/codelite.log.zip)

I have successfully opened the workspace a few months ago using earlier versions of the workspace and Codelite on the same Windows system.

**Comment by eranif** [comment]
Close CodeLite, and try removing the folder `%appdata%\CodeLite\` (or renaming it)
Start CodeLite again and re-open the workspace

Does it help?

**Comment by stevenleigh** [comment]
Thanks for the fast response!  Nope, it didn't help though.  Is it difficult to build Codelite on Windows without the IDE?  Then I could build a debug version to see exactly where it hangs.

**Comment by eranif** [comment]
CodeLite comes with a command line tool that allows building CodeLite projects.
To build CodeLite, you will first need to define the compilers required by CodeLite's workspace (in this case `g++-64`)

* Open CodeLite -> Settings -> Build Settings
* Make sure you have a compiler named `g++-64` (if you don't have, install [this compiler](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/7.1.0/threads-posix/seh/x86_64-7.1.0-release-posix-seh-rt_v5-rev2.7z)) and rename it to `g++-64`

Next, Open a `CMD` terminal, add CodeLite's installation folder to the `PATH` environment variable and define two environment variables required by CodeLite as shown in the below code snippet:

```
cd \path\to\codelite\sources
set PATH=C:\Program Files\CodeLite;%PATH%
set WXWIN=D:\src\wx-src
set WXCFG=gcc_dll\mswu
codelite-make --workspace=LiteEditor.workspace --project=CodeLiteIDE --config=Win_x64_Release --execute
```
NOTE:
`WXWIN` - points to the location where you compiled wxWidgets
`WXCFG` - points to the configuration, use `gcc_dll\mswu` (as written above)

To build the debug version, pass `--config=Win_x64_Debug`, note that you will also need a *debug* build version of wxWidgets for this

**Comment by eranif** [comment]
Another thing to try: 
* Close CodeLite
* Delete the folder `.codelite` under workspace folder

And try again

**Comment by stevenleigh** [comment]
I managed to fix the issue.  I had to delete my user settings.  

When I tried reinstalling codelite to fix the issue I kept the user settings so I guess the issue stayed.  I just uninstalled codelite and deleted the user settings as well and now I reinstalled and everything seems to work fine.
