### ISSUE TITLE
error in git repo locks up user interface

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#2068]
even quit doesn't work :-(
![screenshot from 2018-07-26 10-34-23](https://user-images.githubusercontent.com/796121/43251254-bfca1210-90bf-11e8-863c-2112c7dd519c.png)

**Comment by grandinj** [comment]
clicking ok just makes it go away briefly, then it reappears

the solution is killing codelite, and git fsck, but that's not ideal

**Comment by Gibbon3** [comment]
I'm having the same problem when I open a particular project in a workspace.

Only fix I found was to delete git.conf

**Comment by eranif** [comment]
I have removed these message boxes and instead the git panel should now report the error messages (coloured in red when appropriate)

**Comment by grandinj** [comment]
thanks
