### ISSUE TITLE
Feature request: Make optional the auto creation of main.(c)pp on project creation

### ISSUE THREAD

**Issue by ibroheem** [eranif/codelite#2074]
A situation where by the error in the attached image is prevented by making auto creation of "common name" source files optional during project creation:

Suggestions:
- Optional name, instead "main.cpp", "main.c" etc
- Ability to turn off the feature

![screenshot_20180729_100935](https://user-images.githubusercontent.com/4117847/43364869-a3410be4-9312-11e8-8ae7-481f2cd312c7.png)

**Comment by Flying-Toast** [comment]
You can edit the default project template (~/.codelite/templates/projects/{project template you want to modify}/xxxxx.project). Near the bottom you can change/remove the default files:
`<VirtualDirectory Name="src">`
`<File Name="main.cpp"/>`  <--remove this
`</VirtualDirectory>`
