### ISSUE TITLE
CodeLite and CMake under windows broken

### ISSUE THREAD

**Issue by SteelPh0enix** [eranif/codelite#2075]
CMake support is broken. I've installed fresh CodeLite, and tried to make simple g++ project and simple CMake project. I have MinGW-w64 7.2.0 and CodeBlocks MinGW, and also MSVC compiler and Clang installed, but i've chosen MinGW-w64 everywhere in configuration. This is what i get everytime i try to run CMake using CodeLite (note: the same command entered in cmd works perfectly)

```
"C:\Program Files\CMake\bin\cmake.exe" D:\CodeLite\CPP\test  -G"MinGW Makefiles"
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: C:/Program Files/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev0/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/Program Files/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev0/mingw64/bin/gcc.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "C:/Program Files/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev0/mingw64/bin/gcc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: D:/CodeLite/CPP/cmake-build-Debug/test/CMakeFiles/CMakeTmp

    Run Build Command:"C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/mingw32-make.exe" "cmTC_1a4d4/fast"
    C:/PROGRA~1/MINGW-~1/X86_64~1.0-P/mingw64/bin/mingw32-make.exe -f CMakeFiles\cmTC_1a4d4.dir\build.make CMakeFiles/cmTC_1a4d4.dir/build
    mingw32-make.exe[1]: Entering directory 'D:/CodeLite/CPP/cmake-build-Debug/test/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_1a4d4.dir/testCCompiler.c.obj
    C:\PROGRA~1\MINGW-~1\X86_64~1.0-P\mingw64\bin\gcc.exe    -o CMakeFiles\cmTC_1a4d4.dir\testCCompiler.c.obj   -c D:\CodeLite\CPP\cmake-build-Debug\test\CMakeFiles\CMakeTmp\testCCompiler.c
    mingw32-make.exe[1]: *** [CMakeFiles\cmTC_1a4d4.dir\build.make:65: CMakeFiles/cmTC_1a4d4.dir/testCCompiler.c.obj] Error 1
    mingw32-make.exe[1]: Leaving directory 'D:/CodeLite/CPP/cmake-build-Debug/test/CMakeFiles/CMakeTmp'
    mingw32-make.exe: *** [Makefile:125: cmTC_1a4d4/fast] Error 2




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:7 (project)
-- Configuring incomplete, errors occurred!
See also "D:/CodeLite/CPP/cmake-build-Debug/test/CMakeFiles/CMakeOutput.log".
See also "D:/CodeLite/CPP/cmake-build-Debug/test/CMakeFiles/CMakeError.log".
==== Done ====
```

I've discovered that when i change compiler to MSVC, it works, detects MinGW-w64 properly, but then it uses... make? (ignores compiler configuration, apparently).
in CMake plugin options i've choosen MinGW Makefiles.

I really have no idea what could cause this, every other IDE and CMake itself works properly. I've tried following things:
- Deleted mingw-w64 from PATH variable (it was there at first few tries, i thought it *might* be the problem, but apprently nope)
- Running CodeLite as admin - nothing changed
- Creating workspace in other partition (first time in Documents, second time on D:/) - nope
- Googling a lot and checking out other issues - haven't found anything like that

I include logs from CMake here.
[CMakeError.log](https://github.com/eranif/codelite/files/2241385/CMakeError.log)
[CMakeOutput.log](https://github.com/eranif/codelite/files/2241386/CMakeOutput.log)

**Comment by SteelPh0enix** [comment]
Oh, yeah, GNU Makefile onestep build is broken too in my case 
```
C:\WINDOWS\system32\cmd.exe /C ""C:/Program Files/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev0/mingw64/bin/mingw32-make.exe" -j4 SHELL=cmd.exe -e -f  Makefile"
"----------Building project:[ secondtest - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'D:/CodeLite/CPP/secondtest'
mingw32-make.exe[1]: *** No rule to make target 'Debug/main.cpp.o', needed by 'Debug/secondtest'.  Stop.
mingw32-make.exe[1]: *** Waiting for unfinished jobs....
mingw32-make.exe: *** [Makefile:5: All] Error 2
mingw32-make.exe[1]: Leaving directory 'D:/CodeLite/CPP/secondtest'
====0 errors, 0 warnings====
```

I do create fresh project from simple g++ executable template and i instantly try to build it.

**Comment by eranif** [comment]
Does it work from the command line?
I cant see any specific error coming from CodeLite, it seems like that CMake fails to compile a simple hello world using your GCC compiler...
Have you tried installing the compiler in a folder that does not contain any space? (e.g. D:/MinGW)

**Comment by eranif** [comment]
FYI: It does not broken. It's a mis configuration from your side
You can keep this discussion on the forum
