### ISSUE TITLE
Remove File from Project (feature req/bug) - an easy one!

### ISSUE THREAD

**Issue by kuiperzone** [eranif/codelite#2079]
Hi,

I'm using Codelite Version 12.0.6.

When I first installed CodeLite and wanted to remove a file from the project, it presented me with two dialogs one after the other. One of them asked me if I wanted to remove the file from disk also. I found the two dialogs annoying, but I could live with it. Now it, however, it does not ask me if I want to delete the file on disk any more, but does so by default.

This is not good as it will lead me to the loss of work if I'm not really careful. There seems to be no way to re-enable the delete confirmation.

**Is it possible, when removing a file from the project, to present the user with a single confirmation dialog which also displays a checkbox for the user to check if the file should be deleted from disk as well as being removed from the project?** If the user clicks "OK/Yes" but does NOT check the box, the file will be removed from the project but not the disk. If the user checks the box and clicks "Yes", the file is removed from the both the project and disk. Clicking "No/Cancel" does nothing.

This would streamline the file removal operation as well as making sure the user actually wants the file to be deleted. It is also the way the Qt IDE works.

**Comment by kuiperzone** [comment]
UPDATE: It seems that delete confirmation is only asked when removing multiple files. With single file, however, the behaviour is to delete the file without asking. Quite often I'm simply want to re-organise my files, and deleting them without confirmation means that they cannot be recovered.

Just to add, when removing multiple files, the proposed solution above should/could apply to all files.

**Comment by eranif** [comment]
You can re-enable the annoying dialog from: Settings -> Preferences -> Misc -> History -> Reset annoying dialogs answers

**Comment by kuiperzone** [comment]
That helps. Thanks.
