### ISSUE TITLE
CodeLite tabs unusable at 4K resolution

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#2081]
I've compiled latest CodeLite from Git with latest version of wxWidgets 3.1.1 compiled from sources, running on Fedora 28.

However, CodeLite is still having issues on 4K screen (3840x2160 resolution, 200% scale). All tabs are unusable - they seem to show at 4x size instead of 2x.

![codelite4k](https://user-images.githubusercontent.com/14065837/43690231-69cc5cc8-98cc-11e8-82db-01c4b6390878.png)

**Comment by eranif** [comment]
Which revision are you using?
I did some fixes today

**Comment by eranif** [comment]
Also, which desktop are you using?

**Comment by yunkot** [comment]
I've just updated to 5c52fc2811edb3d9f11d04d5b5b1dbf0ed24ece0 commit and recompiled, but don't see any difference. The desktop is Gnome using Adwaita-dark theme.

**Comment by eranif** [comment]
Is this GTK3 or 2?
Also, how did you change the scale? from settings->display?

**Comment by yunkot** [comment]
GTK3 and yes, Settings - Display.

**Comment by eranif** [comment]
I suspect that the problem is GTK3... 
I did a big effort this weekend to try and make it usable, however, it seems that GKT3 does not behave as good as GTK2 (yet, with wxWidgets)

Can you try this:
In file Notebook.cpp, line 400
Change this:
```c++
#if 0
``` 
to:
```c++
#ifdef __WXGTK3__
```

recompile and let me know if this helps

**Comment by yunkot** [comment]
I have just tested CodeLite from commit 9a074204a31cf4c1c5609f913b87c7c7def8f50e, built with forked wxWidgets for GTK3. Same hardware configuration as before, fully updated Fedora 28 installation.

CodeLite's top menu and project list on the left appear OK, but source code tabs, tabs on the left in project list, tabs in status window, source code and code in status window - all appear way to big (probably twice the size as they should be). It seems that these elements are actually using scale of 4 instead of 2.

![screenshot4k](https://user-images.githubusercontent.com/14065837/45053148-bd9e3580-b04e-11e8-9165-89742b024d96.jpg)

**Comment by yunkot** [comment]
I have just tested CodeLite from commit 9a074204a31cf4c1c5609f913b87c7c7def8f50e, built with forked wxWidgets for GTK3. Same hardware configuration as before, fully updated Fedora 28 installation.

CodeLite's top menu and project list on the left appear OK, but source code tabs, tabs on the left in project list, tabs in status window, source code and code in status window - all appear way to big (probably twice the size as they should be). It seems that these elements are actually using scale of 4 instead of 2.

![screenshot4k](https://user-images.githubusercontent.com/14065837/45053148-bd9e3580-b04e-11e8-9165-89742b024d96.jpg)

I have recompiled wxWidgets for GTK2 - in this case, most elements ap

pear at correct size, except tabs, which appear too small, and some icons on project list on the left. Screenshot attached.

**Comment by yunkot** [comment]
I have recompiled wxWidgets for GTK2 - in this case, most elements appear at correct size, except tabs, which appear too small, and some weirdness with icons on project list on the left. Screenshot attached.
![screenshot4k-gtk2](https://user-images.githubusercontent.com/14065837/45053949-24245300-b051-11e8-853d-0635433ff5fa.jpg)

**Comment by eranif** [comment]
What do you mean by "some weirdness with icons on project list on the left"? 
I am not sure I understand that part

The icons too small, I am familiar with this problem, I am trying to find a solution that will fix this on both GTK3 and GTK2 :/

**Comment by yunkot** [comment]
By "weirdness" I mean some weird placement/spacing - in my understanding, the first icon should appear at the beginning of left edge, but there seem to be some space, along with "bottom arrow", which shouldn't normally be there as icons fit in the space. At least on non-4K resolutions, it is how they seem to appear.

However, the icons don't appear too small - they are at correct size. The tabs are too small in GTK2 build. Other than that, GTK2-based build is usable, unlike GTK3-based one.

P.S. While compiling CodeLite with wxWidgets built for GTK3, there is always a compilation error with missing "wxActionSim" component or something like that, so I always have to edit two files to comment these lines. If this is not a known issue, I can report it separately.

**Comment by eranif** [comment]
I believe most of the GTK3 problems are now solved
