### ISSUE TITLE
Objective-C Support

### ISSUE THREAD

**Issue by DMJC** [eranif/codelite#2082]
Hi, I want to improve the Objective-C support within Codelite and add new templates/Syntax Highlighting for Objective-C/Objective-C++ languages. This will include templates for CommandLine and GNUstep Projects. Is this something that others would be interested in? I have already solved most of the issues with this and have project templates already made. I just need some help removing the -shared compiler option from GCC/G++ on new projects when Objective-C/Objective-C++ is selected (it causes segfaults in builds), as well as making .m and .mm extensions recognised by the program as Objective-C code. I have Syntax Highlighting for Objective-C specific keywords implemented and would just like some assistance getting this into the Codelite repositories.

**Comment by eranif** [comment]
I can assist you with CodeLite issues, but I have zero knowledge about Objective-C
Removing the `-shared` is easy, you just need to define a new compiler and add it to CodeLite.
Basically, CodeLite has a set of detectors that locate and configures all the compilers it can find
See here:

https://github.com/eranif/codelite/blob/master/Plugin/CompilerLocatorCLANG.cpp

You need to write you owen locator (I assume that the CLANG is the default for OSX/Objective-C)
You then just need to add the proper tools.

Once you have created a new compiler locator for Objective-C, you can use that compiler name in your templates. This assures you that the `-shared` is not there.

**Comment by jupeos** [comment]
Did this ever get anywhere? I'm not seeing Objective-C as a language option. 
@DMJC - I would really appreciate it if you could share your syntax highlighting.

**Comment by DMJC** [comment]
I did make progress on this. I'll dig it up for you.

**Comment by eranif** [comment]
FYI: with the latest version of CodeLite and the support of the Language Server (especially `clangd`) you should be able to get a fully functioning code completion for Objective-C/C++ files

**Comment by DMJC** [comment]
Here's my attempts at making Templates/Syntax highlighting for Objective-C
