### ISSUE TITLE
assigned value is garbage or undefined

### ISSUE THREAD

**Issue by 360CodeSafe** [eranif/codelite#2083]
SnipWiz/wxSerialize.cpp in line 531:

in line 525: 'tmpval1' declared without an initial value. and in line 526, calling 'wxSerialize::LoadIntInt'.

in  'wxSerialize::LoadIntInt', when if statement is false. 'tmpval1' is also an uninitialized value.

**Comment by eranif** [comment]
I fixed this, however, its harmless since we only examine the value only if this method returns true
