### ISSUE TITLE
build output tab content

### ISSUE THREAD

**Issue by mashua** [eranif/codelite#2086]
When you are building or rebuilding your project the build tab on the output view does scroll down to the end. It stays somewhere in the middle. This happens when an actual build takes place. It does not happen when "make[1]: Nothing to be done for 'all" message appears, although i don't know if this happens because the output it too small.

**Comment by eranif** [comment]
Can you read the entire output? this is the purpose of this feature. If the entire output is visible, than this is not a bug

**Comment by mashua** [comment]
Yes, i can see the entire output. But is someone's code contains warnings or if you encounter a linking error, then you have to manually scroll down to see that your build have failed.
May i ask why is on purpose to scroll in the middle of the output? I thinks that it scrolls you enough to be able to see the first warning message, am i right?

**Comment by Gibbon3** [comment]
I have an additional request, it would be nice if you could highlight and copy from the build window.  Currently all you can do is select all -> copy.

**Comment by eranif** [comment]
The reason that the ability to "Select" is disabled in that Window is because when adding lines from the background (e.g. the build process) - it causes strange selections to appears.
There are several buttons in the build view, one of them will copy the content and will automatically paste it into an `Untitled` editor.
Also: the fact that you can't see the selection, does not mean you can't select :)
select the text you want, right click and select 'Copy' and voila!

**Comment by flederwiesel** [comment]
@Gibbon3: I fully agree!
@eranif: This is not appropriate. Personally - not meaning to insult you -, I would not even consider it a solution. What use is an IDE, if you have to
- copy the whole build log
- paste the build log
- search for the identifier you wanted to copy ?

This can be achieved from a console window with the same effort...

Especially when building (or _trying_ to build in this case) other people's code, I regularly (have to) copy the identifiers (or else) to search the code. If now someone uses a `horrible_namespace::with_unreadable_class_name::and_horribly_long_function_name` it is hard to read as well as hard to type.
Why should it now be cumbersome to copy/paste also?

Regards,
Tobias

**Comment by flederwiesel** [comment]
Just an example of the above mentioned: How would you trace the stack, if unable to even select a simple file name? You might ask, why I need to, as the point of error is already jumped to in the editor, however, I like (or I feel I need to) understand what is going on...

(Sorry for the huge picture)
![CL build output](https://www.fra-flugplan.de/img/cl-2086-build-output.png)
