### ISSUE TITLE
Ctrl+Caps Lock reduces font size of active editor window, no way to bring it back without closing

### ISSUE THREAD

**Issue by audrius-u** [eranif/codelite#2087]
Accidental press of Ctrl+Caps Lock reduces font size of current editor tab. It seems this is a (mis-)feature of Scintilla, and CodeLite lets the bizzare key combo sneak to the underlying component in an unexpected way. If it is somehow impossible to prevent Ctrl+Capslock, at least there should be an easy way to set font size back to default (I have no mouse and no numpad, so cannot try Ctrl+Wheel up/down and Ctrl+Num/ as common ways to change font size. Ctrl+0 does not help either).

Windows 10 x64, CodeLite v12.0.6 (same happens with older versions of CL as well as under Win7).

**Comment by John-Henrique** [comment]
I have a same problem, I change font size (zoom?) accidentally using CTRL+Caps lock. Thinking in fix I change Settings -> Collors and Fonts -> Global font... now I don't know what is the default font from CodeLite

**Comment by audrius-u** [comment]
Just checked "weekly" build v12.0.11 on Win10 x64 and Ctrl+CapsLock still shrinks text size, sadly bug remains and issue should be re-opened. At least hitting Ctrl+0 (or View->Zoom->Reset) now restores normal zoom.
