### ISSUE TITLE
Nesting two or more deep namespaces breaks auto-complete

### ISSUE THREAD

**Issue by solorvox** [eranif/codelite#2089]
Using two or more deep nested namespaces break auto-complete.
Example: 
https://ideone.com/cFDBYO

Note that the code will compile and run, but does not find any public members to MyClass.  Using less than two namespaces allow auto-complete to work again.

Version: Codelite 12.0.6

**Comment by eranif** [comment]
From what I can see, you don't have `clang` code completion enabled.
The built-in code completion works well, up to a limit.

You will need to enable `clang` code completion in CodeLite to make it work (it's off by default)
When you enable it, CodeLite will use it when the built-in code completion engine fails.

To enable it:
`Settings->Code Completion->Clang->Enable clang code completion`

With `clang` code completion enable:
<img width="652" alt="clang-cc" src="https://user-images.githubusercontent.com/3677711/44323859-49fc0600-a45c-11e8-9d0c-e4f8a5743ecb.png">
