### ISSUE TITLE
UnitTest++ unable to select class

### ISSUE THREAD

**Issue by solorvox** [eranif/codelite#2090]
Following the tutorial here: http://codelite.org/LiteEditor/UnitTestPP

After clicking [...], I am unable to select a class.  No matter what I pick, files, classes, etc., I get the same error:
Could not find match for class ''

![screenshot from 2018-08-21 10-23-56](https://user-images.githubusercontent.com/1246172/44369993-7d0dca80-a52c-11e8-9e9b-4b8cf3b87667.jpg)

Note that codelite sees classes in the project, and shows selection window with choices but none of them work.

![screenshot from 2018-08-21 10-23-20](https://user-images.githubusercontent.com/1246172/44369988-77b08000-a52c-11e8-9164-364bf6ba3f9b.jpg)

**Comment by Gustvo** [comment]
I'm having the same issue.
