### ISSUE TITLE
Code Editor flickers when mouse or edit cursor moves

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#2091]
I've compiled CodeLite from revision 2d721e4b3319d1c1431f00fba2d9b4fa12e40852, using wxWidgets 3.1.1 (also compiled manually as files for Fedora on CodeLite page appear to mismatch wxWidgets version between themselves).

I see  source code flicker in CodeLite when moving mouse cursor or moving edit cursor with keyboard keys, the portions of the source code that flicker appear randomly (not where mouse or edit cursor are).

I'm running Fedora 28 with Gnome/Xorg, on dual-monitor setup using AMDGPU driver (kernel 4.17.14-202.fc28) with Radeon RX 580 graphics card, CodeLite is running on left monitor, which is portrait-oriented. Placing CodeLite on another monitor doesn't seem to remove flickering.

Sometimes (but not always), when flickering occurs, a portion of vertical scrollbar on the right briefly shows (but I have "Auto adjust horizontal scrollbar width" disabled as per #2014). Disabling "Folding Margin" seems to alleviate the issue slightly, but doesn't eliminate it. 

Is there any known workaround for this?

**Comment by yunkot** [comment]
By the way, speaking of which, I don't see vertical scrollbar as such in CodeLite - clicking with the mouse close to right edge does seem to scroll the source code, but there is no visible vertical scrollbar as such (it appears only sometimes during flickering). Not sure if this is related.

**Comment by eranif** [comment]
Which GTK version are you using? This sounds like a GTK3 issues & wxStyledTextCtrl
To fix all your issues: 
Build wxWidgets against GTK2 and from my fork (it contains some flicker fixes)

Here is the steps you need to build wxWidgets correctly (follow the GTK2 section):

http://codelite.org/Developers/Linux

**Comment by yunkot** [comment]
Yes, I was using original wxWidgets compilation with GTK3, which as I understood from #2081, works best for 4K (another configuration of mine). I'll try with GTK2 and will report back.

**Comment by eranif** [comment]
The more important part is to compile the version I forked:
https://github.com/eranif/wxWidgets.git
It will reduce most of the flickers even on GTK3 builds

**Comment by yunkot** [comment]
Unfortunately, I'm unable to compile forked wxWidgets library. After cloning from Git and creating gtk-build sub-folder, I'm using:
```
../configure --enable-uiactionsim --with-opengl --with-gtk=2
make -j12

```
The make process fails with error message:

> make: *** No rule to make target '../src/jpeg/jaricom.c', needed by 'wxjpeg_jaricom.o'.  Stop.

Original wxWidgets 3.1.1 with aforementioned commands compile successfully.

**Comment by eranif** [comment]
After the clone you need to init the submodule:
```
git submodule init
git submodule update
```

**Comment by yunkot** [comment]
Thank you for the instructions! After recompiling forked wxWidgets for GTK2 and CodeLite from aa281a7feffd78ec3f43cde19e926aed20ad1134, I'm not seeing flickering anymore.
