### ISSUE TITLE
SSH plugin suport for id_rsa keys missing on windows

### ISSUE THREAD

**Issue by 07pepa** [eranif/codelite#2095]
On win 10 you can not use the id_rsa key with a combination of the key to authenticate to the remote server

This feature works on Linux if you have your private key in ~/.ssh

**Comment by eranif** [comment]
This feature also works on Windows (I know, cause I use this)
You need to make sure that the key is stored under `%USERPROFILE%/.ssh`
I am using `ssh-keygen` from MSYS to generate my keys

**Comment by 07pepa** [comment]
Well  thanks .... I suspect someting likes this....

**Comment by eranif** [comment]
can you connect from the a terminal? Try using a git / msys shell
They both are using the id_rsa.pub from `%USERPROFILE%/.ssh`

**Comment by 07pepa** [comment]
I have one private key (protected with the password) converted to formats supported by WinSCP, putty, and wsl.
I have converted it also to .pub (all done with puttygen)

I have also ssh server(s) and for authentication, I use "private key" (as identity key) 

in your program, I used ssh account manager for adding appropriate accounts with password empty
so it will try to use %USERPROFILE%/.ssh/id_rsa.pub key

Upon trying to connect in the workspace in SFTP tab with connect button. it will crash if the server has enabled interactive keyboard and will say that server does not have enabled interactive keyboard if not.

**Comment by eranif** [comment]
Ok, so by clicking on this button:
![sftp-connect](https://user-images.githubusercontent.com/3677711/44647116-d327b580-a9e5-11e8-9afc-5c23dac536ef.png)
CodeLite crashes. 
If this is the case, then there is little I can do, as it is probably crashing in libssh. What does work for me is geenrating the key directly with `ssh-keygen`, if you have `git` terminal (MSYS based) you can generate it from there. The SFTP plugin does not support the PuTTY toolchain in anyway
