### ISSUE TITLE
wxCrafter library not loaded

### ISSUE THREAD

**Issue by eranif** [eranif/codelite#210]
When starting CodeLite, wxCrafter.so is not loaded. The following error appears in ~/.codelite/codelite.log: 

```
[ 20:40:38:357 SYS ] Starting codelite...
[ 20:40:39:363 ERR ] Failed to load plugin's dll: /usr/lib64/codelite/wxCrafter.so
[ 20:40:39:363 ERR ] /usr/lib64/codelite/wxCrafter.so: symbol _ZThn744_N14wxPropertyGrid5ClearEv, version WXU_3.0 not defined in file libwx_gtk2u_propgrid-3.0.so.0 with link time reference
[ 20:40:47:480 SYS ] Bye
```

More information:
CodeLite 5.4
wxCrafter 1.4
wxgtk 3.0.0-2
Arch Linux 3.12.7-2-ARCH

**Comment by wallacewinfrey** [comment]
I recently registered wxCrafter, having read this thread and assumed that I'd be able to run it on my arch distro. However, the Arch directories (http://repos.codelite.org/wxCrafter-2.0/ArchLinux/32/ and http://repos.codelite.org/wxCrafter-2.0/ArchLinux/64/) appear to be empty.

Is Arch no longer supported? I tried other wxCrafter.so files but am running into the same "_ZThn720_N14wxPropertyGrid5ClearEv, version WXU_3.0 not defined" issue.

**Comment by eranif** [comment]
> I recently registered wxCrafter, having read this thread and assumed that I'd be able to run it on my 
> Arch distro. However, the Arch directories (http://repos.codelite.org/wxCrafter-2.0/ArchLinux/32/ and 
> http://repos.codelite.org/wxCrafter-2.0/ArchLinux/64/) appear to be empty.

This is why I encourage people to try before they register... 
The Arch wxCrafter is built by CodeLite packager on Arch

We have 2 options here:

* I can send you the tar ball for wxCrafter 2.0 and you can build it
* I can refund you the money

Let me know me what you prefer

**Comment by wallacewinfrey** [comment]
Even if it doesn't work, I don't need a refund. There are plenty of other platforms I can run it on and I support the work you're doing. I mentioned registration in case that was relevant to the issue :-)

Please send me the tarball and I'll build it. Is the tarball for the plugin or the stand-alone?

Thank you for the prompt reply.

**Comment by eranif** [comment]
@wallacewinfrey Please contact me with your private email so I will send you the tar ball + build instructions
