### ISSUE TITLE
Failed to copy wx-config.exe in update64.bat

### ISSUE THREAD

**Issue by leelrep** [eranif/codelite#2101]
When building codelite 12.0.8 on Windows 8.1, Runtime/update64.bat returns
The system cannot find the file specified.

I think it is related to the line:
copy ..\sdk\wxconfig\wx-config.exe "%TARGET_DIR%\CodeLite\" /Y

On my system, wx-config.exe is in ..\sdk\wxconfig\Win_x64_Release

**Comment by eranif** [comment]
This is now fixed
