### ISSUE TITLE
No Output on Console

### ISSUE THREAD

**Issue by tonywei92** [eranif/codelite#2103]
Windows 10 64 Bit
Using Codelite 12.0.8

Config:
![codelite2](https://user-images.githubusercontent.com/20355806/45015279-6ba7e080-b04b-11e8-936d-773a2bdc46a2.PNG)
![codelite3](https://user-images.githubusercontent.com/20355806/45015280-6ba7e080-b04b-11e8-9137-2f32ae8efe38.PNG)

Code:
![codelite1](https://user-images.githubusercontent.com/20355806/45015278-6b0f4a00-b04b-11e8-8884-86ab68c1d146.PNG)

Result:
![codelite4](https://user-images.githubusercontent.com/20355806/45015282-6ba7e080-b04b-11e8-8f55-a46b51cf0122.PNG)

The code is built-in from CodeLite when create project.
I also tried run with Codelite built-in terminal, always no ouput, only "time elapsed ... press any key to continue", but manually open the exe file is normal (print output displayed). please help.

**Comment by tonywei92** [comment]
Ok, I solved this problem by open project setting -> global setting -> linker ->options, set content to:

 -static-libgcc;-static-libstdc++

then save, try again.

**Comment by iwbnwif** [comment]
Also, it is worth making sure that there is no -mwindows flag under Project Settings->Linker->Linker Options.

**Comment by Leon-michael** [comment]
I've been having this same problem. I've changed my settings but still can't get it to show anything other than time elapsed.
is there anything else that might cause this same issue? 
I can't find information on it anywhere.
