### ISSUE TITLE
SublimeText/Atom/VSCode like shortcuts & features

### ISSUE THREAD

**Issue by shemgp** [eranif/codelite#2104]
Just rediscovered this fast and great IDE and realized that has most of the things I need as a PHP developer.  One thing I like is that it analyzes the PHP code and I am able to jump to the definitions quickly. However, I'm used to some things from these other editors and wish it would be available here too:
* CTRL+d Multiple select of words under the cursor (When I press the ctrl+d the word under the cursor will be selected and the words like it below will be selected too as I press ctrl+d more, ctrl+u will undo that selection. I see that codelite is able to do multiple selects already using ctrl+double click so maybe this will be easy to implement).
* CTRL+click a word and it goes to the definition (I know CTRL+click is for multiple selection but maybe a different shortcut for going to the definition, eg. SUPER+Click if CTRL+Click can't be changed)
* CTRL+p for fuzzy opening of files

Thank you for considering this.

**Comment by eranif** [comment]
* Ctrl+D => is `Ctrl-K` in CodeLite, or `Ctrl-Shift-K` for "Select them all"
* Ctrl-P Is mapped into `Ctrl-Shift-R` for opening any symbol / file etc
* `Ctrl-Shift-P` to open execute anything that is offered by the menus
