### ISSUE TITLE
Not compiling again (Ubuntu)

### ISSUE THREAD

**Issue by iHardRock** [eranif/codelite#2108]
> /system/ssd/projects/codelite/codelite_terminal/clTerminalSTC.cpp: In member function ‘void clTerminalSTC::SetPreferences(const wxFont&, const wxColour&, const wxColour&)’:
> /system/ssd/projects/codelite/codelite_terminal/clTerminalSTC.cpp:233:29: error: no matching function for call to ‘clTerminalSTC::StyleSetFont(int&, const wxFont&)’
>          StyleSetFont(i, font);
>                              ^
> /system/ssd/projects/codelite/codelite_terminal/clTerminalSTC.cpp:233:29: note: candidate is:
> In file included from /system/ssd/projects/codelite/codelite_terminal/clTerminalSTC.h:8:0,
>                  from /system/ssd/projects/codelite/codelite_terminal/clTerminalSTC.cpp:1:
> /usr/include/wx-3.0/wx/stc/stc.h:4413:10: note: void wxStyledTextCtrl::StyleSetFont(int, wxFont&)
>      void StyleSetFont(int styleNum, wxFont& font);
>           ^
> /usr/include/wx-3.0/wx/stc/stc.h:4413:10: note:   no known conversion for argument 2 from ‘const wxFont’ to ‘wxFont&’

> /system/ssd/projects/codelite/LLDBDebugger/codelite-lldb/CodeLiteLLDBApp.cpp: In function ‘int {anonymous}::StopReasonToPriority(lldb::StopReason)’:
> /system/ssd/projects/codelite/LLDBDebugger/codelite-lldb/CodeLiteLLDBApp.cpp:140:10: error: ‘eStopReasonInstrumentation’ is not a member of ‘lldb’
>      case lldb::eStopReasonInstrumentation:
>

**Comment by eranif** [comment]
I committed some fixes, hopefully it will be able to compile now.
However, for the LLDB error, you will need to build CodeLite with LLDB support disabled.

Please re-run CMake with this argument passed:
`-DENABLE_LLDB=0`
