### ISSUE TITLE
Gigantic frame titles

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#2109]
Hi Efran,
using the latest HEAD on GTK give me gigantic frame titles which I can't change in size.

![image](https://user-images.githubusercontent.com/1535691/45473136-81e22a80-b736-11e8-888b-98a94b071c5d.png)

![image](https://user-images.githubusercontent.com/1535691/45473215-c8378980-b736-11e8-9a46-0f2feefff328.png)

It would be great if the fontsize could be reduced, or if I could influence this somehow.

Best regards,
  René

**Comment by eranif** [comment]
Hi,
Can you please give more details on your build setup?
- wxWidgets version
- GTK version
- You screen resolution & DPI

Regradless of this info, you can fix this in the code here:
https://github.com/eranif/codelite/blob/master/Plugin/clScrolledPanel.cpp#L306

Remove the `+2`

For some reason, on my GTK without this change, the font is small compared to the other fonts (e.g. the menu bar)

Thanks!

**Comment by upCASE** [comment]
- wxWidgets version: 3.1.1
- GTK: 2.0
- Resolution: Dual screen 1920x1200 & 1600x1200, 96 DPI

Maybe it's because of me using GTK2. I removed the +2 for now and it's indeed back to normal.
The returned sizes are correct btw.

**Comment by eranif** [comment]
Thanks. Fixed

**Comment by eranif** [comment]
Ok, I found the real problem: my screen DPI was set to 120 and the font size returned by wxWidgets was not multiplied by `1.25` (`120/96.0`) using GTK calls directly fixes this
