### ISSUE TITLE
find/replace in selection not working

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#2110]
the new find/replace panel is missing some much-loved feature :-)

i.e. current master

I can no longer select a chunk of text in the editor and do find/replace only in that chunk

**Comment by eranif** [comment]
I committed a fix with the following change:

Select chunk of text -> hit Ctrl-H or Ctrl-F -> the bit "Replace In Selection" is now enabled (but only if the selected text is multiline)

You can now find->replace in selection only

**Comment by grandinj** [comment]
Sorry, not quite there yet:

(*) Start without the find bar closed / not visible
(*) select multiple lines of text
(*) type ctrl-h
(*) start typing the "find" text bar

the selection is dropped and the editor moves to whatever line matches the text just typed into the find bar

**Comment by eranif** [comment]
Did you try it with the latest fix !?

**Comment by eranif** [comment]
This is the commit:
https://github.com/eranif/codelite/commit/0d2dba45ec488e7356b36112564d371a42ad61a5
