### ISSUE TITLE
Unreadable error line with red background

### ISSUE THREAD

**Issue by zufuliu** [eranif/codelite#2113]
Unreadable error line with red background on build error, even after the line is modified.
A red error indicator in the line number, fold margin, or somewhere might be better.

![red-error-line](https://user-images.githubusercontent.com/2289926/45659618-eda60800-bb27-11e8-8995-393dbbee5932.png)

**Comment by eranif** [comment]
This is configurable. You disable this from
Settings->Build Settings->Build Output Appearance->Use annotations (uncheck it)

**Comment by zufuliu** [comment]
This is the current settings (12.0.8):

![marker](https://user-images.githubusercontent.com/2289926/45747943-e53df200-bc39-11e8-8552-d094a42e5f5b.png)

It not mark the line as it said:
![mark-line](https://user-images.githubusercontent.com/2289926/45748206-a0668b00-bc3a-11e8-893a-5c5b0530747a.png)

When annotation is checked, it will display the error / warning message from build output, not related to the red line.

**Comment by eranif** [comment]
This is because you have "hidden" the symbol margin
Settings->Preferences->Bookmarks->Display breakpoints/Bookmarks margin

If CodeLite has no symbols margin, it displays the error bookmark across the entire line

**Comment by zufuliu** [comment]
Thank you, this now works.
