### ISSUE TITLE
[REQUEST] Use full static linking for codelite-make

### ISSUE THREAD

**Issue by iHardRock** [eranif/codelite#2115]
The main idea is to make codelite-make executable independent. It will allow to compile CodeLite projects on computer without CodeLite installed.
It wery usefull when you want to compile your project on different computer (may be with different OS), but don't want to install CodeLite and all dependencies (for example WX) on it.

**Comment by eranif** [comment]
The main idea of having `codelite-make` was to be able to build projects depending on CodeLite that have no GUI support, but only have SSH access terminal. I don't see me investing time on this in the foreseeable future. A pull request with a fix for this will be appreciated. Closing this feature, unless you are willing to invest time on this and on that case, I will re-open this issue
