### ISSUE TITLE
code flickering in editor

### ISSUE THREAD

**Issue by sss123next** [eranif/codelite#2123]
i have flickering problem in editor on code built from master, this does not happens on 12.0, looks like regression.
http://sss.chaoslab.ru/codelite.mkv

**Comment by eranif** [comment]
Some questions and some advises:

First, the flicker comes from wxWidgets and can't be fixed within CodeLite's source base.
HOWEVER, please follow the following steps and it will reduce your flicker considerably to none:

1. Use GTK2 when building wxWidgets (from the scrollbar flickering, I can tell you built GTK3 version), click `Ctrl-Alt-Mouse middle button` to confirm this, but I suspect its true
2. There is a scrollbar issue with GTK3, so add this to your `~/.profile` or whatever: `export GTK_OVERLAY_SCROLLING=0`
3. Disable the feature: `Settings->Preferences->Caret & Scrolling->Auto adjust the scrollbar width`
4. The editor component within wxWidgets is not using a buffered drawing, this causes heavy flicker, I did fix this within wxWidgets library, so make sure you build **my** fork of wxWidgets (as stated in CodeLite's wiki page): https://github.com/eranif/wxWidgets

Following ALL the above will fix this issue for you

**Comment by sss123next** [comment]
thank you for suggestions.
yes, i am using gtk3 based wxwidgets, i will try suggested workarounds and report back here.

**Comment by sss123next** [comment]
switched to gtk2 backend.
working fine now.
