### ISSUE TITLE
Support for D

### ISSUE THREAD

**Issue by ghost** [eranif/codelite#2126]
I am going to make an IDE based on codelite for the [D language](https://dlang.org/). I just wanted to check if you would like D support added to the official codelite, or if I should just create a separate fork instead. Please let me know. Thanks

**Comment by eranif** [comment]
Why not making it a plugin?
It makes more sense (I did that for JavaScript and PHP). Since I have zero knowledge of "D", I can contribute only on design and/or making internal changes to CodeLite to fill that is missing

**Comment by Flatllin** [comment]
I will make it a plugin. How do I get stated with it?

**Comment by eranif** [comment]
Here is a basic HOWTO to start with the plugin tutorial I wrote couple of years ago...
http://codelite.org/Developers/CreatePlugin

I think that it is still valid :)
After you have your first plugin that does nothing ... I suggest having a look at one of the plugins that actually do something, I would start with the "WebTools" plugin as it supports a debugger (NodeJS debugger), code completion for JS and project management- these are the basic for adding new language support.

**Comment by Flatllin** [comment]
This shouldn't be too hard with https://github.com/dlang-community/DCD and https://github.com/dlang-community/D-Scanner

**Comment by eranif** [comment]
I am closing this query (not really an issue). Incase you do want to share your plugin, feel free to contact me directly
