### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#2129]
Hi Eran,

I'm experiencing high CPU load (maxing out one of my eight cores all the time) when running codelite. It's not the indexer, but the IDE itself that's causing this. I did a bisect to figure out when this started and apparently I didn't notice it before, as 662be1fb00ea9c7 is the bad commit. This is on wxGTK, using GTK 2.

Best regards,
  René

**Comment by upCASE** [comment]
Did some more digging: If I comment the while loop starting at line 132 in Plugin/clTreeCtrl.cpp it's back to normal.

**Comment by eranif** [comment]
Hi, thanks for reporting this.
Can you try with latest master and report back?
This commit https://github.com/eranif/codelite/commit/655bd548ab051127e9a90b1b080dd0e695a9b014 should fix it

**Comment by upCASE** [comment]
Yes, works fine!
Thanks heaps!
