### ISSUE TITLE
Error stynax highlighting

### ISSUE THREAD

**Issue by codedcosmos** [eranif/codelite#2131]
I'm hoping I have just missed something and this issue can be closed quick and not bother anyone but, anyway here it goes.

Is there some kind of syntax highlighting or error linting or whatever the official name is, for code lite? The only time stuff like this seems to happen is when manually running cpp code checker, or when building, the latter of which puts the errors readily available where the code actually is rather then in a console somewhere like in cpp error checker.

Also preferably if the error linting could be realtime that would be sweet.

Thanks for any help.

**Comment by eranif** [comment]
In the output view (the one at the bottom of the IDE) select the tab named `Build Q`
Enable it (there is a single checkbox on it)

Now, each time you save a file, it will trigger a compile for this file only, if there are any errors you will get the exact same errors as if you triggered a build

This only works for CodeLite's build system (it does not work with any custom makefiles)
