### ISSUE TITLE
[Feature Request] Add an ability to rearrange watches and locals in the debugger pane

### ISSUE THREAD

**Issue by Greg-21** [eranif/codelite#2135]
As written in the title, add an ability to rearrange watches and locals in the debugger pane by simply dragging and dropping (or, if it's too hard to implement, just by toolbar icons like "Move Up" and "Move Down"). And maybe also add rearrange options, like "Move To Top" (especially this...), "Move Up", "Move Down" and "Move To Bottom" (...and this), to the context menu that appears when you right-click on one of the watches/locals.

**Comment by Greg-21** [comment]
Ping?

**Comment by Greg-21** [comment]
Thanks. I forgot to ping it before these 3 days :/

**Comment by eranif** [comment]
np, I increased the thresholds of the bot from 3 -> 5 days

**Comment by Robin-Whittle** [comment]
This would be a great additional feature.
