### ISSUE TITLE
Unable to use FTP for server connection

### ISSUE THREAD

**Issue by pthoelken** [eranif/codelite#2136]
Hello, 

It's possible to use strict FTP (21) protocol to connect to remote server? If I would use the port 21, the program popup the error window below.  

![image](https://user-images.githubusercontent.com/12643853/46576146-b9ee2d80-c9c3-11e8-8411-45b941f03e15.png)

Thanks in advanced!

**Comment by mtangoo** [comment]
SFTP is different protocol than FTP. So your error message is clear. I doubt if CL supports FTP and even if it does you are looking at wrong plugin.

If you have root access to the server I suggest you move to SSH server

**Comment by eranif** [comment]
As the name of the plugin implies: it's built for SFTP (SSH File Transfer Protocol)
It was never intended to support FTP. Only SSH / SFTP
CodeLite has no FTP plugin

**Comment by pthoelken** [comment]
Yes. It's okey and the question behind my issue was excatly this: Is a plugin for ftp integration in codelite available. Your answere is no. Thats, okey. 

Thanks for your help.
