### ISSUE TITLE
wrong "linker options" handling in cmake mode

### ISSUE THREAD

**Issue by sss123next** [eranif/codelite#2137]
if paths to ".a" archive is set in "projet options->linker->linker options" in CmakeLists.txt added something like this "set(LINK_OPTIONS ${LINK_OPTIONS} ../../3rdparty/libev/build/libev.a)" which lead to error like "/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: cannot find -l../../3rdparty/libev/build/libev.a" on linking stage.

**Comment by eranif** [comment]
The bug is in your settings. You should add the library to the 'Libraries' and not linking directly to the `.a`.  It should produce an output like: `-L/path/to/lib -lev`. The linker options field should be used to add 'options' not libraries

**Comment by sss123next** [comment]
why not ?
all linkers accepting direct path to .a files.
