### ISSUE TITLE
Syntax error on wxWidgets 3.0.x constructor call

### ISSUE THREAD

**Issue by jgmdev** [eranif/codelite#2138]
A syntax error prevents compilation of current code on git repository for systems that still use wxWidgets 3.0.x.

https://github.com/eranif/codelite/blob/master/Plugin/clDataViewListCtrl.cpp#L157

**Comment by pattisahusiwa** [comment]
I've fixed this issue, see 010193547788e2abcf2573c4e40901e083d3208d. However, the issue is reintroduced by eb68f1b824792241654b92a6a17bb6244f8593b7. For a temporary workaround, remove the additional parenthesis and then try to compile again.

cc @eranif

**Comment by jgmdev** [comment]
I did remove the parenthesis locally using sed-replace for the archlinux codelite-git PKG script, but I will wait for that fix to be pushed on the codelite repo instead of me pushing it as a workaround to the Archlinux User Repository.
