### ISSUE TITLE
Codelite Editor window is doesnt show any text

### ISSUE THREAD

**Issue by CStudent747** [eranif/codelite#2139]
Hi when I open Codelite, for some reason the editor window doesn't show any text. I've reinstalled version 12.0 and i've also deleted my appdata by going to %appdata% and deleting the codelite folder. I am working on c++ on windows 7 ultimate 64 bit using mingw
<img width="960" alt="editor missing" src="https://user-images.githubusercontent.com/44012133/46710078-66bee980-cc14-11e8-95ad-18242520c592.png">

**Comment by eranif** [comment]
I suspect that the code is there, but you have some colour issues
Can you go to Settings->Colours and fonts and click on the "Defaults" button?

Thanks

**Comment by leonox747** [comment]
Hi Eranif,

I followed your instructions but still having the same problem
<img width="960" alt="revert to default color" src="https://user-images.githubusercontent.com/44012133/46737714-39048f80-cc6a-11e8-8279-dbecd4e5fb3c.png">
<img width="960" alt="same problem" src="https://user-images.githubusercontent.com/44012133/46737722-3dc94380-cc6a-11e8-8d4f-6b99b6ea35e7.png">

**Comment by eranif** [comment]
Have you tried running CodeLite 12.0.8? 
https://downloads.codelite.org/

**Comment by leonox747** [comment]
Hi Eranif, I've just installed 12.0.8 and I'm still having the same problem
<img width="960" alt="12-0-8" src="https://user-images.githubusercontent.com/44012133/46768822-a7237380-ccb7-11e8-806c-18c17e0a0670.png">

**Comment by eranif** [comment]
I could not reproduce this anywhere, so I have another guess and it related to the DIRECT2D drawing method used by CodeLite in the editor component.
Can you trigger a build (F7) and see if the output in the `Build` tab is showing anything?

**Comment by CStudent747** [comment]
![f7](https://user-images.githubusercontent.com/44012133/48366667-8f575a80-e67c-11e8-96ec-d514da1e491e.png)

**Comment by CStudent747** [comment]
my pc has an i7-5500u and an R9 M275 if that's any help to you

**Comment by eranif** [comment]
Try this build please: 
https://downloads.codelite.org/codelite/wip/codelite-amd64-12.0.10.exe

**Comment by CStudent747** [comment]
Thank you Eranif. It's finally working now!!!
![success](https://user-images.githubusercontent.com/44012133/48372320-41e2e980-e68c-11e8-987a-50d1b2ad96fd.png)

**Comment by eranif** [comment]
Thanks for testing this. This means that the problem with the integration between wxWidgets and your GPU :/ , at least we have a working workaround

**Comment by afonsosantos** [comment]
@eranif Sorry to bother, but my PC, using version 13.0 of CodeLite is like the other user. Any fix?

**Comment by mhassankhan90** [comment]
> Thank you Eranif. It's finally working now!!!
> ![success](https://user-images.githubusercontent.com/44012133/48372320-41e2e980-e68c-11e8-987a-50d1b2ad96fd.png)

I was getting the same error with the latest version 14. I tried previous versions as well but the same error. This thing helped me resolve the issue.
