### ISSUE TITLE
inactive editors tab title ineligible

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#2141]
Testing with commit 40dad4254a3e34c11f94fdd43bba8260ed9ee47b 

it has very light in-active title bars in the file edit tab titles
makes it very hard to read when using the default Fedora 28 theme (Adwaita)
i.e. can't see the names of the files I am __not__ editing

(switching to the dark theme fixes that, but makes the text in the ctrl-F panel sometimes invisible)

![screenshot from 2018-10-12 12-43-14](https://user-images.githubusercontent.com/796121/46865088-90e2f800-ce1c-11e8-982d-6f74a12d82f6.png)

**Comment by grandinj** [comment]
much better thanks!

**Comment by eranif** [comment]
FYI: I also fixed the 'find' bar text is hidden when using dark themes (e.g.  Adwaita-dark)
This is fixed in https://github.com/eranif/codelite/commit/d7fa329eac0e1e6655520d7fe92cf896ffef602f
