### ISSUE TITLE
Feature request: Memory viewer

### ISSUE THREAD

**Issue by mashua** [eranif/codelite#2149]
Adding the ability to copy memory addresses from various point during debugging would be greatly appreciated. Typing addresses on the "Address:" field is a little tiresome, especially on heavy debugging sessions.

**Comment by eranif** [comment]
why do you need to type? cant you just copy / paste?

**Comment by mashua** [comment]
When i have the codelite at a debugging session, on the 'debugger' pane -> 'locals' tab i cannot copy the value of any element. Right clck gives me the 'Change value...' menu option.
 Most of the times these values are addresses that would be handy to throw on the memory view.

**Comment by eranif** [comment]
There is another tab... "memory" - use it
