### ISSUE TITLE
Missing “Make this project output a bundle” option for macOS?

### ISSUE THREAD

**Issue by whabilly** [eranif/codelite#2151]
Where is the “Make this project output a bundle” option in the macOS version of CodeLite v12.*??? It does not seem to be available anymore when right-clicking on the project...
![missing bundle option](https://user-images.githubusercontent.com/44359582/47362925-8f64da00-d710-11e8-8541-53534069f880.png)

**Comment by eranif** [comment]
Have you tried under "Plugins" ?

**Comment by whabilly** [comment]
No, nothing bundle-related under "Plugins" :(

**Comment by eranif** [comment]
I can see it here... it is under: right click project->plugins->make this project output a bundle

**Comment by whabilly** [comment]
Indeed... but only if you know that it is a plugins and that it is not added by default on Mac. Solution is to select "Manage Plugins..." under the "Plugins"  menu, check the "MacBundler" box, click OK and relaunch CodeLite.
