### ISSUE TITLE
wxcrafter: How to close a dialog without the wxCLOSE_BOX checked

### ISSUE THREAD

**Issue by nezos** [eranif/codelite#2152]
My setup: Codelite 12.0, wxCrafter 2.9 (build 2.9) on Devuan Linux
Issue severity: Minor
My current solution: Restart Codelite

A wxWidget project inside Codelite, create a a new dialog in wxCrafter, uncheck the default dialog style and make sure wxClOSE_BOX is unchecked. Now click on Show Preview. How to close the dialog box?

**Comment by eranif** [comment]
Have you tried clicking on the "Close Preview" button?
<img width="528" alt="wxc" src="https://user-images.githubusercontent.com/3677711/47380970-63912680-d707-11e8-9053-ea6751470d62.png">
