### ISSUE TITLE
Find in Files dialog feature req

### ISSUE THREAD

**Issue by Gibbon3** [eranif/codelite#2155]
It would be nice when doing Search -> Find in Files if you had a drop down menu for Look in' that was a tree of the workspace, projects, and virtual folders.

AKA workspace -> projects -> virtual folders.

This would be nice because often I want to search the whole workspace, or just one project, or sometimes just a virtual folder.  It's sort of annoying to keep adding and removing 'look in'.

**Comment by eranif** [comment]
Instead, you can now select the folders / files / projects directly in the C++ workspace view and hit `Ctrl-Shift-F` this will trigger the find-in-files to search only in the selected items
