### ISSUE TITLE
Settings: Colours and Fonts

### ISSUE THREAD

**Issue by davidwed** [eranif/codelite#2156]
After the update to 12.0.9 the options "Global foreground Colour" and "Global background Color" are missing under "Settings->Colours and Fonts".

Codelite 12.0.8:
<img width="454" alt="codelite_12 0 8" src="https://user-images.githubusercontent.com/12169308/47482620-5c693600-d837-11e8-9215-f124273c90d6.PNG">

Codelite 12.0.9:
<img width="538" alt="codelite_12 0 9" src="https://user-images.githubusercontent.com/12169308/47482626-62f7ad80-d837-11e8-8b82-041193d3456f.PNG">

**Comment by eranif** [comment]
Thanks for reporting this.
This is an ongoing work, all of the main controls in CodeLite (tab-controls, tables and trees) were re-written from scratch so the previous settings were no longer affecting them.
The new controls accepts a "base" colour that currently is determined by CodeLite by examining the system face colour (face=panel colour). This allows the application to blend in when dark theme is used (e.g. macOS mojave & Linux Adwaita-Dark themes). I can see the need for this on Window where dark theme is not available (is it?) and I will add an option to manually set the "base" colour to override the default system colour

**Comment by davidwed** [comment]
All right, I use Windows 8.1, there is no dark mode :-). Thanks

**Comment by nazero3** [comment]
Theme and colors dont change in codelite 14 or what is the problem ?

**Comment by sabrinathan-nair** [comment]
Hi.. is there any update on this ? .. I am facing the same issue..

**Comment by nazero3** [comment]
Hi 
the problem mainly was because there was a non English character in the username file so I changed the username so that it wont contain characters from other languages and now the problem is fixxed
