### ISSUE TITLE
Split-screen option not showing up

### ISSUE THREAD

**Issue by stevenleigh** [eranif/codelite#2158]
Right clicking a file tab does not show the option to move tab to other view.

Version: release 12.0.9 x64, Windows 10

![splitscreen](https://user-images.githubusercontent.com/7379112/47550894-eaf5ba00-d900-11e8-8147-12fef32711d9.png)

**Comment by eranif** [comment]
This functionality was removed. It caused some issues with CodeLite (fliker, random crashes) which caused me to spent too much time on it. At the end of the day, I have decided to remove it and invest my time on more productive issues. A PR with this functionality is always welcome (assuming it was thoroughly tested)
