### ISSUE TITLE
Support debugging for current Node.js versions

### ISSUE THREAD

**Issue by lhitc** [eranif/codelite#2160]
Apparently the the parameter names for running Node.js in debug mode have changed, which results in an error when running in debug mode (i.e. "F5"):
``
[DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.
``
Following that, CodeLite runs on a timeout when trying to connect to the debugger.

I could not find a setting to change "--debug" to "--inspect".
Such a setting option should be added for compatibility with current as well as legacy versions of Node.js

I'm using Node.js 8.12.0 LTS with CodeLite 12.0.0 on Linux Mint 18.2

**Comment by eranif** [comment]
:)
My current `nodejs` version is set to:
```
$nodejs --version
v4.8.2
```
this is the stack version that comes with Debian 9 (with back ports)

**Comment by eranif** [comment]
I was too optimistic :(
It seems that the current debugger protocol (the one used up until NodeJS v7) was deprecated.
Passing the argument is not enough. Making a long story short: the debugger needs to be re-written from scratch OO

**Comment by eranif** [comment]
I am sorry for the delay. It turns our that the Nodejs team has deprecated the current protocol (which was used up until v7) and the new protocol (DevTools protocol) is not documented. I opened an issue on their bug tracker, got multiple responses however, I am still waiting for the one developer that can document the protocol. 

My ticket issue: https://github.com/nodejs/node/issues/24025
However, I have decided not to wait for them anymore and instead, I will wrap Nodejs buitin debugger.
If you are not familiar with it, you can run it like this:
```
node --inspect-brk /path/to/script.js
```
This will start node in debugging mod and will break on the first line, next, you can type `help` to see list of available commands

**Comment by eranif** [comment]
UPDATE:
Finally, someone from the NodeJS core developers pointed me to the right direction and provide me some guides about the new protocol. We can now expect a working debugger in matter of days. Stay tuned

**Comment by eranif** [comment]
This is now fixed. I have re-written the debugger to support nodejs version 8 and later (using the new Chrome DevTools debugging protocol)

**Comment by jsangradorp** [comment]
Hi! I am running the 12.0.0 version that install on Debian 10 Buster by default, trying to debug a node.js script, and it looks like the invoked command is still node --debug[-brk] . Is this the case? Is there any way I can change it to --inspect[-brk]?

Thanks!

**Comment by eranif** [comment]
this won't work.  you will need to upgrade your codelite

**Comment by jsangradorp** [comment]
Thank you :-)
