### ISSUE TITLE
codelite locks up and is unresponsive on macOS Mojave

### ISSUE THREAD

**Issue by n0nag0n** [eranif/codelite#2163]
When using the SFTP browser, I open up a new connection and when I'm clicking the triangle to view the contents of a folder, my cursor turns to a spinning wheel and I have to force quit the program. The first time it happened, it was the first folder I clicked the triangle. The second time it happened, it was the 3rd. It just locks up and becomes unresponsive. Just recently upgraded to 12.0.9. Love the dark mode btw :) Running on macOS Mojave

**Comment by eranif** [comment]
Thanks for reporting this. This is now fixed (needed to rebuild OpenSSL + libssh for macOS Mojave)
