### ISSUE TITLE
Doxygen duplication when hitting ENTER after /**

### ISSUE THREAD

**Issue by github678** [eranif/codelite#2164]
When editing C++ code, if you already have a Doxygen comment on your method, and you position your caret right after the /** and then hit ENTER, a new Doxygen comment will be inserted. So it is not possible to extend the beginning of the Doxygen comment in a convenient way. Sure, there is a workaround, but I think it's not very pretty as it is right now.
![screenshot from 2018-11-03 10-31-47](https://user-images.githubusercontent.com/32433870/47950666-a055ec80-df55-11e8-9e8b-2ef36cc09294.png)

**Comment by eranif** [comment]
The code that does that, has no "state" it does not know that the code was there earlier...
IMO, its not worth spending my time on this minor issue. Going to close it, unless you have the urge to fix it yourself :)
