### ISSUE TITLE
Terminal omits "pause when execution ends" setting

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#2166]
Hi Eran,

after switching the terminal configuration  the project setting "pause when execution ends" is apparently omited. At least for me the terminal always pauses after execution, regardless what I configured.

Best,
  René

**Comment by eranif** [comment]
Is this for a console application or console?

**Comment by upCASE** [comment]
Actually the application is GUI, but produces some debug output, which I find easier to read on a console. So "This program is a GUI application" is not checked in project settings, as well as "Pause when execution ends" is unchecked, as I don't need the output after the application closes. However, the console for the output always  pauses after the execution ends.

Best,
  René
