### ISSUE TITLE
Codelight error

### ISSUE THREAD

**Issue by AndreLucien** [eranif/codelite#2168]
Hi I'm having a serious issue with codelit. I open it and the screen goes blank. Even the project bar and other bars vanish. Idk how to fix this

**Comment by eranif** [comment]
Please provide some more information: CodeLite version, your OS etc
Such bug reports are closed without even being checked.

**Comment by AndreLucien** [comment]
I am running on Windows 8

**Comment by eranif** [comment]
And your CodeLite version... ?

**Comment by AndreLucien** [comment]
Thanks and oh sorry. I attached the picture and sent it via email. The same messages sent to Github and your email together. Github took off the pic attachment.

**Comment by eranif** [comment]
Did my workaround help?

**Comment by AndreLucien** [comment]
I'll try out the method you gave tomorrow. Will update once I confirm codelite is working again

**Comment by AndreLucien** [comment]
I currently don't have the PC in question with me right now

**Comment by AndreLucien** [comment]
I tried the method and it still won't let me clean the project

**Comment by eranif** [comment]
Does it still crash? where are the error reports? the build log?

**Comment by AndreLucien** [comment]
It still crashes. The build shows no warnings or errors. As soon as I hit clean, the entire program crashes. If I hit run, it does nothing.

**Comment by eranif** [comment]
I cant really help you as it does not happen elsewhere, except on your machine.So unless you can debug it, I can't do much

**Comment by AndreLucien** [comment]
Ok thanks. No problem. I'll try and figure it out. May reinstall the entire program. See if that works

**Comment by AndreLucien** [comment]
Hey just wanted to update  incase anyone else has this issue in future. I fixed the errors. Turns out my workspace was the error. So I deleted the entire workspace and wrote a new one from scratch. The problem was then resolved. It seems it was not configured correctly.
