### ISSUE TITLE
Icons too large

### ISSUE THREAD

**Issue by kamilizmer** [eranif/codelite#2175]
Can you provide an option to resize these icons (folder, workspace icon, code file icon etc.) according to your own predispositions? They are unfortunately too big.
<img src="https://i.imgur.com/ZQqifnq.png" />

**Comment by eranif** [comment]
There were some hard coded values for the GTK3 build. Should be fixed now

**Comment by mikael1000** [comment]
> There were some hard coded values for the GTK3 build. Should be fixed now

Ok... good. But how do I change the size of the icons?

**Comment by eranif** [comment]
Have you tried -> Settings -> Preferences -> Misc -> General tab -> Toolbar icon size?

**Comment by mikael1000** [comment]
> Have you tried -> Settings -> Preferences -> Misc -> General tab -> Toolbar icon size?

Yes. There is only two options. But no matter what I select of the two the icons are the same size.

Small Icons (16x16)
and
Large Icons (24x24)

By default it was set to the small option.
