### ISSUE TITLE
Codelite always outputs a shared library although the project options is set to executable

### ISSUE THREAD

**Issue by CalielOfSeptem** [eranif/codelite#2176]
Using ubuntu, latest release of codelite.  When I compile the output is always a shared library although I set executable in the project settings...

[BuildLog.txt](https://github.com/eranif/codelite/files/2595557/BuildLog.txt)

**Comment by eranif** [comment]
According to this last line (the link line):
```
/usr/bin/g++ -o ./Debug/septemserver @"septemserver.txt" -L. -L/home/ken/lua-5.3.5/src -L../telnetpp/Debug -L../terminalpp/Debug -L/usr/local/lib -L../SQLiteCpp/Debug  -lboost_system -lboost_program_options -lboost_filesystem -llua -lpthread -lboost_date_time -ltelnetpp -lterminalpp -lcryptopp -lsqlite3 -lSQLiteCpp  -lz -ldl
```
The output is an executable...
Can you confirm that this file do exists under `<PROJECT_PATH>/Debug` ?

**Comment by CalielOfSeptem** [comment]
It exists, and this is the properties..
![image](https://user-images.githubusercontent.com/3701133/48712336-8239ee80-ebdb-11e8-9a78-4c9c339890b7.png)

**Comment by eranif** [comment]
What is the output of the `file` command on that file?

Here is an example of codelite's binary output:
```
file codelite/build-release-gtk3/bin/codelite
codelite/build-release-gtk3/bin/codelite: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=501a0f2d580c973a165c83164f9df50b154b0704, stripped
```
As you can see, it is also described as `shared object`

**Comment by CalielOfSeptem** [comment]
ken@ken-PowerEdge-R420:~/git-repos/septemmud/septemserver/Debug$ file septemserver
septemserver: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=9df5db0ee3dfc296ef8e6e83c51b8ca195566ff2, with debug_info, not stripped
ken@ken-PowerEdge-R420:~/git-repos/septemmud/septemserver/Debug$

**Comment by eranif** [comment]
Read this for more info:
There is no difference between shared-objects and executable on Linux

https://askubuntu.com/questions/690631/executables-vs-shared-objects

**Comment by CalielOfSeptem** [comment]
Ok.  The reason I am attempting to avoid the shared objects is I'm attempting to use netbeans for remote compiling.  Netbeans refuses to recognize the output file as an executable, so my first thought was to ask here.  Perhaps I should go hit up netbeans help

**Comment by eranif** [comment]
One more small clarifications: 
CodeLite does not produce executable /  shared objects. Its the linker that does that.
Looking at your link line, you are linking against various shared objects (boost, dl and others). In order to produce pure executable, you will need to use static linking (not recommended)
