### ISSUE TITLE
shared library issue from earlier today (11-19)

### ISSUE THREAD

**Issue by wagonerd** [eranif/codelite#2177]
The problem with Codelite (and presumably any other IDE) producing a shared library file when the setup is for an executable is a linker issue for Linux. The temporary patch is to add '-no-pie' at Global Options - Linker. I am understanding that this is an issue relative to the latest version of the linker. I'm not sure of the status or if there even is a fix in the works. This patch enables Ubuntu to recognize the file as an executable but, obviously, it is linked without using PIE.

**Comment by eranif** [comment]
This is not a CodeLite issue, but rather a linker issue. CodeLite is not the compiler nor the linker (it uses the toolchain installed on your machine: gcc/ld/clang/cl.exe etc). 
This is configurable and you can add it in the build settings->compilers->your compiler->Tools->linker
