### ISSUE TITLE
Issues on Project Settings -> Global Setting -> Additional Include Paths/Library Paths

### ISSUE THREAD

**Issue by Slavonist** [eranif/codelite#2178]
While it may sound something weird, please read this thoroughly.
First of all, I tried to link my SDL2 project with the proper library via CodeLite, eventually being compiled by MSYS2 compiler toolkit (the version being the newest of the day, used mingw32-make.exe). However it showed some type of error, showing no such file or directory. I felt extremely strange and inconsistent with the issue, so I did the same thing with Code:blocks and did it work, finding out that the toolkit had no issues. Wasting many hours of the day, I did find some workouts(?).
Instead typing 
C:\SDL2-2.0.9\x86_64-w64-mingw32\include (works perfectly fine on Code:blocks) on the Include path
and C:\SDL2-2.0.9\x86_64-w64-mingw32\lib ,
quoting with "" thus 
"C:\SDL2-2.0.9\x86_64-w64-mingw32\include"
and "C:\SDL2-2.0.9\x86_64-w64-mingw32\lib"
each on the Include Paths and Library Include Paths does work somewhat fine.
I think I have found the clues to the issue that thou hadst spent too much money on.
However the question still rises that whether 'quoting' each path directory is intended or not.
If this is not intended, shall be it fixed.

The reason behind that is that the path is directly attached to the option variable (e.g. -I<Path>).
When there are no quotes and the path starts by alphabet or number the variable itself gets distorted, resulting build failure.

Thanks.

**Comment by eranif** [comment]
1. This post should go the forum
2. "showing some kind of an error"  - I am not sure what am I suppose to do with this kind of statement
3. I suspect that since you are using MSYS toolchain, you shouldn't be using `\` but instead use MSYS paths (e.g. `/c/SDL2-2.0.9...`), however, in order for this to work, you should start CodeLite from within the MSYS terminal 
4. Like I said earlier: this should go to the forum (https://forums.codelite.org)

**Comment by Slavonist** [comment]
The thing that I'm explicitly asking is whether the path variable should be quoted "" or not on the Project setting. I apologize that I have written too verbose and that It's my first time writing.

**Comment by eranif** [comment]
If you are using spaces, than YES, you should double quote it.  If not, then no, NO double quotes are needed
