### ISSUE TITLE
CMake: $(WorkspaceConfiguration) not translated to ${CONFIGURATION_NAME} in CMakeLists.txt

### ISSUE THREAD

**Issue by neildarlow** [eranif/codelite#2185]
Reproduced on codelite-12.0.10-gtk3 version.

When adding to the Linker Search Path in Project settings (either the Linker Search path setting or Global linker search path setting:
`$(WorkspacePath)/cmake-build-$(WorkspaceConfiguration)/output`

The $(WorkspaceConfiguration) is passed into CMakeLists.txt verbatim instead of being translated to ${CONFIGURATION_NAME} thus:
`# Library path`
`set(CMAKE_LDFLAGS "${CMAKE_LDFLAGS} -L. -L${WORKSPACE_PATH}/cmake-build-$(WorkspaceConfiguration)/output ")`

If you hack the Linker search path setting as follows:
`$(WorkspacePath)/cmake-build-${CONFIGURATION_NAME}/output`

you get the desired result of:
`# Library path`
`set(CMAKE_LDFLAGS "${CMAKE_LDFLAGS} -L. -L${WORKSPACE_PATH}/cmake-build-${CONFIGURATION_NAME}/output ")`

**Comment by wevsty** [comment]
I have encountered a similar problem,I think the problem seems to happen in the step of custom build.

But i found the a commit https://github.com/eranif/codelite/commit/0de30a8bee3a097f6f42db59bf85f9cc2d24acb2 
I think this commit can solve this problem.

**Comment by wevsty** [comment]
I found that I misunderstood the problem.
In order to fix this problem I added a PR.

**Comment by eranif** [comment]
Thanks, fix merged
