### ISSUE TITLE
Settings - Terminal: grayed out

### ISSUE THREAD

**Issue by Mukrosz** [eranif/codelite#2190]
Hi there,

I've made the unfortunate mistake by selecting "Use CodeLite's built-in terminal emulator" to check what it looks like and now this cannot be undone, the option is grayed out.
I'd like to use Konsole as my terminal of choice.
How can I revert the option above?
Many thanks,

OS: Manjaro Linux 18.0
Codelite 12.0.0 from AUR

**Comment by eranif** [comment]
The entire Terminal concept in CodeLite was re-written in recent builds (12.0.8 I believe it was)
For now, you can simply delete the file `~/.codelite/config/codelite.xml` if this does not help, remove the file `~/.codelite/config/codelite.conf`

**Comment by dghart** [comment]
Debian-derived distros would use update-alternatives to set the preferred terminal. I've no idea if Manjaro has update-alternatives.

If not, 2 alternatives:
1) Use Manjaro's gui for Settings (presumably it has one) to change x-terminal-emulator to konsole.
2) Hack /usr/bin/codelite_xterm to use konsole.
