### ISSUE TITLE
Duplicate files equals wrong file opened on error

### ISSUE THREAD

**Issue by ericwomer** [eranif/codelite#2194]
I have a workspace with two projects with the same boiler code, the second project is in a sub-directory of the first, but are not dependent on each other or compile using files from the others files. When there is an error in the second project, when its selected as the active project, clicking on the build error will open it up in the same named file of the first project.

Project A has WorkspaceRoot/src/application.cpp
Project B has WorkspaceRoot/ProjcetB/src/application.cpp

Clicking on a build error for Project B will cause the source file in Project A to be opened, with the arrows pointing to the wrong lines since Project A has diverged from the base that I cloned. I assume that this behavior is because the editor looks for the first matching file which is in Project A and is not the desired behavior.

**Comment by Gibbon3** [comment]
Same as issue #2214

**Comment by jupeos** [comment]
Not sure why this & #2214 have not been considered as a real problem. Please review.

**Comment by jupeos** [comment]
@eranif - not sure what I'm supposed to do about this??? Your bot seems to want to disregard this issue and you have not commented on it. It's still an issue and needs to be fixed or at the very least an explanation given as to why it's not considered an issue.
