### ISSUE TITLE
Line number is cut at high zoom

### ISSUE THREAD

**Issue by silviulaurentiu** [eranif/codelite#2195]
On windows 7, Codelite v12.0.0 and v12.0.10
Small zoom:
![image](https://user-images.githubusercontent.com/14875058/50388639-31ab3900-0725-11e9-8550-573d14fc1262.png)
High zoom:
![image](https://user-images.githubusercontent.com/14875058/50388656-a1b9bf00-0725-11e9-851f-d18c29f782c8.png)
As can be seen, the number two is cut:
![image](https://user-images.githubusercontent.com/14875058/50388661-e5acc400-0725-11e9-87c2-a299f74a30d7.png)
If the zoom in more increased, then other numbers are cut:
![image](https://user-images.githubusercontent.com/14875058/50388671-3d4b2f80-0726-11e9-8ef7-8932b52c4790.png)

**Comment by zufuliu** [comment]
The width of line number margin not increased or decreased when zooming (tested 12.0.13).
