### ISSUE TITLE
Codelite shows value of some unsigned char's but not others in debug mode inspection, mingw

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#2200]
System:
Codelite non-self-compiled, 12.0.10, win7 x64.
Running either mingw (nuwen) 6.3 or 8.1, codelite shows value of some unsigned char's but not others.

Example:
(skipfield_type is unsigned char in this context)
![bug1](https://user-images.githubusercontent.com/4833954/50426262-a7163580-08ee-11e9-802c-89cbf86c21c6.png)

**Comment by eranif** [comment]
Can you provide a working sample? (1 source file that can be compiled without other dependencies)

Thanks

**Comment by Lyberta** [comment]
I'm pretty sure it only works for ASCII range because it treats `unsigned char` as ASCII character.

**Comment by mattreecebentley** [comment]
You can download the colony container from plflib.org.
