### ISSUE TITLE
Building C++ projects (Mingw-w64) is too slow

### ISSUE THREAD

**Issue by github-mper34** [eranif/codelite#2201]
This is a serious problem for me (and possibly for many other developers) who prefer to use a fast modify-test-debug cycle.
Settings: 
- Project type: executable
- makefile generator: default
- compiler: Mingw-w64 gcc 7.3.0

All versions od CodeLite (7.0-12.0) are affected. 
All versions of Mingw-w64 have the same problem - their own builds at: 
https://mingw-w64.org/doku.php/download/mingw-builds 
Tested on Windows 7 sp3 64-bit.

Use the simplest program for confirming this bug:
#include <stdio.h>
int main(int argc, char **argv){ printf("hello world 2\n"); }

To reproduce follow these steps:
1. select from menu: build / clean project   (just in case, this step is not crucial)
2.  select from menu: build / build and run
3. +++ 5-10 seconds elapse while the program is being built
4. program is run, close the output console
5.  change the program slightly, for example : set the string to "hello world 33333\n"
6.   select from menu: build / build and run
7. ++++ if you did it fast enough , it builds fast. If more than 30 seconds have elapsed since step 2., it will build slowly again (like 5-10 seconds)
8. you can repeat steps 5.-7. as many times as you like to observe the highly variable build time.

The variable time to compile in step 7. indicates that the compile can actually be performed much faster, and , probably, some kind of caching is involved.

In my practice, 5 seconds is unacceptable for such a short program to compile. The time must be shorter than 2 seconds, otherwise the entire IDE is a failure.

**Comment by eranif** [comment]
for me it compiles less than a second. you should also note that codelite doses not compile,  it's the compiler (codelite is not a compiler).  no caching is involved. you might consider checking if an anti virus is enabled

**Comment by github-mper34** [comment]
You are right, it does compile fast on fresh instalaltion of Windows.
I suspect it has something to do with the PATH variable (like searching for executables in too many dirs)
I'll try to find where the issue is, then I'll report here.

**Comment by github-mper34** [comment]
I still can't find what's wrong. It is not the PATH, I tried cleaning it up, tried killing tons of other processs, no change.

CodeLite runs fine on a very similar system, so only my current machine is affected.

When I add a -d option to mingw32-make.exe, I can easily notice that it often pauses after
CreateProcess(...)
, and sometimes after  
Live child ...

If I'm unable to figure it out, I'll probably need to reinstall Windows.
