### ISSUE TITLE
Feature request: Debug / Run-to-cursor 

### ISSUE THREAD

**Issue by github-mper34** [eranif/codelite#2202]
This is a common feature in many IDEs, like Visual Studio, Code blocks, etc.. . 
The first time I have noticed it was in Borland's IDEs from 1990.

The usuall default shortcut is F4.
You can try this feature out in Code::Blocks IDE.

The rationale is that setting a breakpoint is too time consuming, and later you need to manually remove the breakpoint. Instead, Run-to-cursor does it all automatically.

**Comment by eranif** [comment]
right click on the line you want and click 'run to cursor'

**Comment by github-mper34** [comment]
There is no such option (on Windows 7  and for C++ projects).
I can provide  a screenshot if necessary.
Please reopen.

**Comment by github-mper34** [comment]
Here is a screenshot
Os: Windows 7 32-bit sp1, running on virtual machine, fresh installation

https://ibb.co/JpDxhvN

**Comment by github-mper34** [comment]
Not quite.

In all other IDEs you DON'T have to be in debug session to be able to use 'run to cursor', because one of the important aspects of the 'run-to-cursor' feature is that it starts the debug session automatically.

Or at least, the debug session is started automatically in all IDEs that I know of, except CodeLite .

**Comment by github-mper34** [comment]
Well, of course.

Notice:
A) 'run to cursor' is currently crippled in CodeLite to the point where it is completely unusable.

B) that means that CodeLIte doesn't really have 'run-to cursor', a common feature supported by virtually all other IDEs since 20 years ago. CodeLite only has an excuse why not to implement run-to-cursor.

C) this was a 'feature request' where I, as a user, try to explain to you how to make your product better. If I had the time and knowledge to add it myself, I likely wouldn't have posted this entire thread.

D) If you don't want to implement it properly, then say:
"I don't want to do this",
don't say "implement it yourself", because it is rude as I am, OBVIOUSLY, not a CodeLite developer. In fact, I rarely do GUIs, so I would be most useless as an IDE developer.

Anyway thanks for developing CodeLite, it looks like a nice IDE, except that 'run-to-cursor', my favorite debugging method, is missing.

**Comment by eranif** [comment]
I would agree to most of your points, but the fact is:
1. CodeLite is an open source, which means, I work on it on my spare time. I am implementing what seems important to me.
2. You can clone the code and add what you think is missing
3. "crippled" - CodeLite has many (many) users, you are the first to complain about it, so I hardly call it crippled

**Comment by eranif** [comment]
Also, its not "excuses" - I am telling you the truth: not going to implement this... 
I could keep this open, but no one will work on it, so I dont see the point

**Comment by github-mper34** [comment]
Well, you decide what the priorities are, of course.

**Comment by github-mper34** [comment]
Could you be so kind to keep this feature request open?

Maybe someone will stumble upon it and realize the importance of this feature.
