### ISSUE TITLE
"What's New" link broken

### ISSUE THREAD

**Issue by flederwiesel** [eranif/codelite#2203]
On the release page, "What's New" points to http://codelite.org/LiteEditor/ReleaseNotesCodeLite12:
> The requested URL /LiteEditor/ReleaseNotesCodeLite12 was not found on this server.
Same goes for "this wiki page" - and probably everything below http://codelite.org/LiteEditor.

**Comment by eranif** [comment]
I am not sure where you are looking at, but here:
https://downloads.codelite.org all the links are pointing to the correct location

Can you please share the URL where you saw this broken link?

Thanks

**Comment by flederwiesel** [comment]
Do'h! Should have said that this relates to the github release page rather than codelite.org ...
Please see https://github.com/eranif/codelite/releases

**Comment by eranif** [comment]
Fixed, thanks!

**Comment by flederwiesel** [comment]
> Same goes for "this wiki page"
Can you fix this as well?

**Comment by eranif** [comment]
Done
