### ISSUE TITLE
stray clTabCtrl text in editor

### ISSUE THREAD

**Issue by etik61** [eranif/codelite#2206]
From time to time I'm getting "clTabCtrl" inserted into code. It could be related to hide/show of codelite or switchung tabs, but I'm not sure.
OS: Windows 10
Codelite Version: 12.0.11
Compiler used: gcc (MinGW.org GCC-6.3.0-1) 6.3.0

**Comment by eranif** [comment]
This happens when you DnD tab and drop the tab into a text editor

**Comment by XaVieR375** [comment]
This is still an issue. I am experiencing this a lot right now, in Codelite. Any solutions?

**Comment by eranif** [comment]
can you paste a screenshot of the problem?

**Comment by XaVieR375** [comment]
> can you paste a screenshot of the problem?

I was waiting till it happened again and it just did while i was looking at that exact spot it just magically appeared.
)
![Now](https://user-images.githubusercontent.com/67128892/201543805-f988da59-3c9a-4d95-8fdf-29261676d1fa.png)
