### ISSUE TITLE
Codelite MinGW Build Errors

### ISSUE THREAD

**Issue by metalcells** [eranif/codelite#2208]
Using Codelite 12.0.11 on Windows 64bit with MingGW compiler I am getting an error when testing:

#include <iostream>

int main() {
    std::cout << "Hello Testing...";
    return 0;
}

Output panel errors:

C:\Windows\system32\cmd.exe /C C:/MinGW/bin/mingw32-make.exe -j4 SHELL=cmd.exe -e -f  Makefile
"----------Building project:[ Test1 - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'F:/CPlusTraining/CPPWorkspace/Test1'
C:/MinGW/bin/g++.exe  -c  "F:/CPlusTraining/CPPWorkspace/Test1/main.cpp" -std=c++17 -std=c++14 -Wall -g -O0 -Wall  -o ./Debug/main.cpp.o -I. -I.
In file included from c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\cstdio:42,
                 from c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\ext\string_conversions.h:43,
                 from c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\bits\basic_string.h:6391,
                 from c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\string:52,
                 from c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\bits\locale_classes.h:40,
                 from c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\bits\ios_base.h:41,
                 from c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\ios:42,
                 from c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\ostream:38,
                 from c:\mingw\lib\gcc\mingw32\8.2.0\include\c++\iostream:39,
                 from F:/CPlusTraining/CPPWorkspace/Test1/main.cpp:1:
c:\mingw\include\stdio.h:788:34: error: '__off64_t' does not name a type; did you mean '__time64_t'?
 typedef union { __int64 __value; __off64_t __offset; } fpos_t;
                                  ^~~~~~~~~
                                  __time64_t
mingw32-make.exe[1]: *** [Debug/main.cpp.o] Error 1
mingw32-make.exe: *** [All] Error 2
Test1.mk:97: recipe for target 'Debug/main.cpp.o' failed
mingw32-make.exe[1]: Leaving directory 'F:/CPlusTraining/CPPWorkspace/Test1'
Makefile:4: recipe for target 'All' failed
====1 errors, 0 warnings====

**Comment by eranif** [comment]
Not really a CodeLite issue. CodeLite not a compiler, you should seek help in a C++ forum (or MinGW)
