### ISSUE TITLE
Insecure Connection for https://www.codelite.org

### ISSUE THREAD

**Issue by zufuliu** [eranif/codelite#2209]
![clAboutDialog](https://user-images.githubusercontent.com/2289926/51434434-ed1aab00-1c9a-11e9-99c9-b8b7c80433ca.png)

source:
```cpp
m_hyperLink44 = new wxHyperlinkCtrl(m_panel22, wxID_ANY, _("CodeLite IDE"), wxT("https://www.codelite.org"),
                                        wxDefaultPosition, wxDLG_UNIT(m_panel22, wxSize(-1, -1)), wxHL_DEFAULT_STYLE);
```
https://github.com/eranif/codelite/blob/master/Plugin/clAboutDialogBase.cpp#L100

It's https://codelite.org/ ?

The copyright year can also changed to 2019.

**Comment by eranif** [comment]
Fixed
