### ISSUE TITLE
Code completion not working properly

### ISSUE THREAD

**Issue by albertobarbaro** [eranif/codelite#2210]
Hi,
I'm using codelite 12.0.0 and I have some problems with the autocompletion. I can use use it properly almost everywhere apart with variable create in this way:

```
if(MyObject* variable = dyn_cast<MyObject>(another_object.method())) {
}
```

When I type ```var``` no suggestions are shown, so I think for some reason that variable is "not seen". Any idea please?

Happy to test any fix if possible

Thanks

**Comment by eranif** [comment]
Where did you get your CodeLite from?
If both `clang` checkboxes are disabled, it means your CodeLite was built without clang supprot

**Comment by abarbaro** [comment]
I followed the instructions here ```https://wiki.codelite.org/pmwiki.php/Main/Repositories#toc1``` ( ubuntu bionic )

**Comment by eranif** [comment]
I am not sure why is it disabled for you, but if you are using Bionic, download the latest 12.0.11 from https://downloads.codelite.org ( a deb file )
Follow the install instuctions as described here:
https://forums.codelite.org/viewtopic.php?f=20&t=4143

**Comment by abarbaro** [comment]
Honestly, I had the version 12.0.10 and it was enabled but I had the same problem, so I thought it was a bug in codelite. I'll update it ASAP and let you know if it fixes the problem.

Thanks

**Comment by abarbaro** [comment]
Unfortunately this did not fix the problem.

**Comment by eranif** [comment]
which problem? the checkbox disabled, or code completion not working?

**Comment by abarbaro** [comment]
You are right, it did not fix the code completion. In addition, if I try ```Interpreter::method``` where ```Interpreter``` is an LLVM class, the code completion does not kick in showing methods for that class.

**Comment by eranif** [comment]
It does not work like this. In order to get code completion with clang, you need to make sure that the code can compile (or at least, it can find all in the headers)
Do you get any message in `Output View->Clang` tab?

**Comment by albertobarbaro** [comment]
Problem solved. Thanks again :)
