### ISSUE TITLE
Goto Declaration/ Implementation fails with multi project workspace

### ISSUE THREAD

**Issue by jupeos** [eranif/codelite#2214]
When using either command 'Goto declaration' or 'Goto implementation' the incorrect symbol is located.
If there are two projects that have a symbol with the same name and the SECOND project is Active, when a 'Goto XXX' command is executed the file (where the symbol exists) in the FIRST project is opened. These functions need to be project scoped.

**Comment by Gibbon3** [comment]
I have a similar minor annoyance that's due to shared files. But in your case this behavior is actually bad because you'll view/edit the wrong file.

**Comment by jupeos** [comment]
Not sure why this & #2194 have not been considered as a real problem. Please review.

**Comment by jupeos** [comment]
@eranif - not sure what I'm supposed to do about this??? Your bot seems to want to disregard this issue and you have not commented on it. It's still an issue and needs to be fixed or at the very least an explanation given as to why it's not considered an issue.
