### ISSUE TITLE
How to remove icons from tabs.

### ISSUE THREAD

**Issue by david-tamar** [eranif/codelite#2216]
I'm trying to remove the icons from all tabs in CodeLite, like those you see in the output pane. I don't want them.

Another issue: The tabs don't conform to my GTK+ theme.

Another issue: I can't find a way to move the tabs of my editor from top to bottom.

**Comment by eranif** [comment]
I am not sure what do you mean by: "do not confirm to the GTK theme"
Can you post a screenshot?

**Comment by david-tamar** [comment]
Sure, here's a screenshot,
On the left CodeLite's representation of tabs, and on the right you can see how CodeBlocks' representation of tabs is actually conforming to my GTK theme as everywhere else. 
![image](https://user-images.githubusercontent.com/24723374/51998765-ed4c4f00-24c1-11e9-812b-8f22c098bd71.png)

**Comment by eranif** [comment]
This means you are using an old version of CodeLite (maybe its 12.0.0, I cant remember at which version the changes were made, so, which one are you using?)

The current version of CodeLite supports different type of tabs (GTK3 theme, 12.0.11)

You *cant* change the editor's tab orientation to bottom

**Comment by david-tamar** [comment]
Oh, that is true, I'm using CodeLite 10.0.0, which is what available at Debian's Testing repository at the moment.

What about the icons in the output tabs:
![image](https://user-images.githubusercontent.com/24723374/51999636-e3c3e680-24c3-11e9-9e51-50f023b6d25f.png)
Is it possible to hide them in the latest version?

**Comment by eranif** [comment]
No, you cant hide the icons, however the icons are "fade" on the latest CodeLite (attached screenshot taken on Windows):

<img width="836" alt="capture" src="https://user-images.githubusercontent.com/3677711/52002011-829f1180-24c9-11e9-8e1c-9afad660466f.PNG">
