### ISSUE TITLE
What happened to dark theme?

### ISSUE THREAD

**Issue by GeorgeKalovyrnas** [eranif/codelite#2217]
Hi,
I'm using Linux Mint 18.3
I've updated CodeLite to 12.11 and the dark theme is gone! I don't use dark theme for my rest of desktop. But I'm sure that an option existed till 12.06.

The worst is the grey color of non-selected tabs.
![image](https://user-images.githubusercontent.com/25669306/52139476-f4599580-2658-11e9-9b28-55266a0fb37d.png)

Thanks

**Comment by pygmy-octopus** [comment]
CodeLite now follows the themes of the OS (real dark theme cant be achieved with wxWidgets)

**Comment by eranif** [comment]
As pygmy stated...

**Comment by eranif** [comment]
This issue is now fixed in git master
