### ISSUE TITLE
libclang.so.6 missing in fedora 29

### ISSUE THREAD

**Issue by ugol** [eranif/codelite#2220]
libclang.so.6 missing in fedora 29

**Comment by dghart** [comment]
Hi,

I'm not sure what you mean by that. What CodeLite problem is this causing? How can I test it here?

FWIW, my fedora 29 (virtualbox guest) has libclang.so.7, not libclang.so.6.

Regards,

David

**Comment by ugol** [comment]
At startup, apparently it looks for libclang.so.6, but Fedora 29 has libclang.so.7. 
It should be the latest binary (not sure because I am on another laptop now), isn't that lib statically compiled in codelite?

**Comment by dghart** [comment]
That's strange. I haven't updated my fedora for some time, but ldd tells me that CodeLite uses libclang.so.7. And on testing, CodeLite loads and runs OK.

>isn't that lib statically compiled in codelite?

No, not afaik.

Please would you give more information about what happened and how to reproduce it:
 Did you build CodeLite yourself (if so which version) or download it from the CodeLite repo (which binary)?
 What goes wrong when you try to run it?
 Does the output of 
ldd `which codelite`
 help?
 Approximately when did you last update fedora?

Thanks.

**Comment by eranif** [comment]
Closed due to inactivity
