### ISSUE TITLE
Removing "Time elapsed" from the output

### ISSUE THREAD

**Issue by ApexLead** [eranif/codelite#2222]
Whenever I build a project there's "Time elapsed" at the end of the output, how can I remove it?

**Comment by eranif** [comment]
You cant...
Why does it bother you?

**Comment by ApexLead** [comment]
I guess because it changes the way my output looks.. 
Will it cause problems if my stdout will be defined to go through a socket or a pipe?

**Comment by Anupriya1729** [comment]
my codelite is not showing time elapsed, how to enable it?

**Comment by eranif** [comment]
@Anupriya1729 please don't use the ticketing system for asking questions. Use the forum instead

https://forums.codelite.org
