### ISSUE TITLE
Two finger scrolling not working on Fedora29 running wayland

### ISSUE THREAD

**Issue by h181180** [eranif/codelite#2224]
I don't know if this is a known issue or not, but I didn't find any solutions when googling. I'm unable to scroll through code and the output pane using two finger scrolling on the touchpad. However, independent tabs from the menu bar like the 'Keyboard Shortcuts' and 'Manage Plugins' tabs has no problem with two finger scrolling. 

What worked:
It worked when scrolling with a mouse. And if I switch to Xorg instead of wayland, two finger scrolling works.

Is there a fix?

I'm running CodeLite IDE v12.0.0 using kernel version 4.20.6-200.fc29.x86_64 running wayland. I haven't tweaked any settings.
This is on a ThinkPad L380 if that matters.

**Comment by eranif** [comment]
This is probably a wxWidgets bug (the entire GUI is built with it)
Can you open a bug on their github page? (there is nothing I can do from my side)
