### ISSUE TITLE
Cancel command "Duplicate tab.." causes crash

### ISSUE THREAD

**Issue by franku** [eranif/codelite#2227]
How to reproduce: 

- right click on a file tab
- choose "Duplicate Tab.."
- cancel the "Save As" menu
- press "Esc" Key
-> crash

Using Fedora 29, Codelite 12.0.0

**Comment by eranif** [comment]
I am unable to reproduce this on various machines (Linux, Mac and Windows)
However, in all of them, I have used the latest git master.
I assume that this bug is fixed.

**Comment by eranif** [comment]
@dghart explained to me how to reproduce this bug (I too thought that I should cancel the 'Save As' dialog using ESC, I was wrong)
