### ISSUE TITLE
Warn about 'stale' tags database when project is moved

### ISSUE THREAD

**Issue by Gibbon3** [eranif/codelite#2230]
I've run into an annoyance when copying a project to a different directory. 

Because the *.tags database contains hard paths to the previous location, going to the definition or implementation of a symbol opens the file on the old location. Which can lead to editing the wrong file. That can be a bit confusing if you don't notice or know to watch for it.

Would be nice if the .tags database remembered the where it was created and bitch a little if the location changes. Bitching meaning ask if you want to re-parse the project when you open it.

**Comment by mtangoo** [comment]
Just rebuild workspace after moving. Or make full retag if you are not using Clang
