### ISSUE TITLE
non-Latin display problem

### ISSUE THREAD

**Issue by edwardlucas** [eranif/codelite#2234]
When I input simplified Chinese, the characters are displayed but lack of the part of bottom. Some font  more serious. Please see the screenshot below.

Liberation Mono
![image](https://user-images.githubusercontent.com/4361096/53795609-4732af80-3f6d-11e9-926c-950618bf1a64.png)

FreeMono (only can see the top half of Chinese characters)
![image](https://user-images.githubusercontent.com/4361096/53796049-41899980-3f6e-11e9-9f7b-926bc90dfa5e.png)

**Comment by zufuliu** [comment]
What's the system and version and CodeLite version.

The problem not happens on Win10 CodeLite 12.0.13.

**Comment by edwardlucas** [comment]
> What's the system and version and CodeLite version.
> 
> The problem not happens on Win10 CodeLite 12.0.13.

I have tried on Ubuntu 18.04 and linux mint 19.1, CodeLite V10.0.0

**Comment by dghart** [comment]
> I have tried on Ubuntu 18.04 and linux mint 19.1, CodeLite V10.0.0

There have been a lot of changes since v10.0. You need to upgrade to v12.0, which you can get from [here](https://wiki.codelite.org/pmwiki.php/Main/Repositories).

**Comment by edwardlucas** [comment]
I tried on Linux Mint 19.1 Tessa with CodeLite v13.0.0, Problem still there.
Some fonts like "Ubuntu Mono" are very serious, some are not so serious. Only fonts includes Chinese and English characters not have this problem.
![Screenshot from 2019-09-27 18-14-00](https://user-images.githubusercontent.com/4361096/65762068-b6aefd00-e152-11e9-9ae8-e5e574209274.png)

**Comment by edwardlucas** [comment]
Hello, anything in progress?

**Comment by eranif** [comment]
Can this be reproduced on editors like `scite`? 
You can install it by running:
```
sudo apt-get install scite
```

**Comment by eranif** [comment]
Ping?

**Comment by zufuliu** [comment]
Some text in the image:
```
MfConfiguration读取配置文件
```

**Comment by eranif** [comment]
As I suspected. This seems to be a problem in wxWidgets.
See the attached image:
On the left is the `scite` editor while on the right is `stc` sample application provided by wxWidgets
![stc-scite](https://user-images.githubusercontent.com/3677711/67159615-9a683f80-f34f-11e9-9193-83f3088d3a22.png)
Can you please open a bug on wxWidgets?

**Comment by zufuliu** [comment]
How about adding extra line space, in right image `g` is not whole displayed.

https://www.scintilla.org/ScintillaDoc.html#SCI_SETEXTRAASCENT
https://www.scintilla.org/ScintillaDoc.html#SCI_SETEXTRADESCENT

**Comment by eranif** [comment]
Adding extra ascent is not always wanted. This needs to be done via configuration.
However, its still a bug in wxWIdget. As you can see, the same font on scite does not have this issue

**Comment by eranif** [comment]
However, atm, its the only solution available. So I will add this

**Comment by eranif** [comment]
Adding line spacing seems to fix this
![line-spacing](https://user-images.githubusercontent.com/3677711/67164556-973b7680-f384-11e9-9749-98dafeea843d.png)
