### ISSUE TITLE
Codelite not detecting the Visual Studio compilers

### ISSUE THREAD

**Issue by srini2174** [eranif/codelite#2237]
I am running the latest version of Codelite 12.0.13.  When I try to scan for the compilers installed Visual Studio compiler is not found even though the Visual Studio Build tools is installed.

I am working on a Windows 10 machine and the environment variable doesn't point to Visual studio installation as I have multiple versions installed.

Does codelite uses vswhere to find the instance of Visual Studio installed in the machine.  If it is not can this be considered as a feature request.

Srinivasan.B

**Comment by mtangoo** [comment]
I'm not sure how much support VS have in CL. I personally have not used it for years so all I could do is try to help you in right direction. Before that, if VS is not a requirement, I would suggest you switch to MinGW. Its simple and solidly supported in CodeLite. 

That being said you can try helping guide CL to your compiler path. This is how:
1. Go to Settings -> Build settings
2. In compilers tab press the *+* symbol to add existing
3. Point to the root of compiler path. If that doesn't work then you'll have to wait for @eranif

**Comment by srini2174** [comment]
Thanks for your inputs.  I have done that already by adding the VC compiler manually, but it is not a permanent solution.  I feel it should be selected automatically when the compilers are scanned.

Srinivasan.B

**Comment by eranif** [comment]
@srini2174 CodeLite examines the environment variables table for environment variable that matches this pattern: `VS??*COMNTOOLS` . This environment variable is then considered the base path for a specific VC installation. Can you check your environment variables and see if you have this environment variable defiend?

**Comment by srini2174** [comment]
The detection of VS compilers is not consistent.  Today I had downloaded 12.0.15 version and this version has detected the VS compiler but only one version of the compiler has been detected.

I haven't set any environment variable for VS??*COMNTOOLS but still it has been detected.

**Comment by srini2174** [comment]
I still have this issue.  I have tested it with the latest version 13.0.3 as well.  Codelite doesn't detect the visual studio compiler.  I have 2 versions of Visual Studio installed in my machine and none of them are detected.
