### ISSUE TITLE
Configurations Not Settable in Project Settings.

### ISSUE THREAD

**Issue by genusistimelord** [eranif/codelite#2238]
When I create a new Configuration in the configuration Manager and go into the Project Settings the new configuration does not appear in the drop down.

https://imgur.com/hIute4u.jpg

**Comment by eranif** [comment]
You need to create both for the workspace & the project.
Did you create one for the project as well?

**Comment by genusistimelord** [comment]
Oh OK sorry about that. I didn't notice the drop down below for the project. Maybe make the list next to the project name contain a drop down button so its noticeable? As after you said that i just randomly started looking for that and ended up randomly clicking on things in the configuration page XD.
