### ISSUE TITLE
[Info] Release

### ISSUE THREAD

**Issue by aviallon** [eranif/codelite#2242]
Hello, this is typically the "issue" you may hate, but, if I may ask, is there any plan on pushing a new release (or release candidate) ?
Thanks :smile:

**Comment by eranif** [comment]
Yes, hopefully this weekend.
I was working on implementing a huge feature, so no release candidates could be released until its stable.
I have reached the stability point, it's now a matter of completeness.

The feature implemented is: https://wiki.codelite.org/pmwiki.php/Main/LanguageServer
The second one (minor one): folder diff

**Comment by eranif** [comment]
CodeLite 12.0.14 was released today. Hopefully we are not far from a major release now :)
