### ISSUE TITLE
Building on aarch64 (Nvidia Jetson TX2 / Xavier)

### ISSUE THREAD

**Issue by ngjermundshaug** [eranif/codelite#2245]
For aarch64 ubuntu 16/17/18, the libraries and headers are under /usr/lib/aarch64-linux-gnu, so invoking cmake like this is required to build. Perhaps the build files can be modified as include these paths?

**cmake -G "Unix Makefiles" -DCMAKE_INCLUDE_PATH=/usr/lib/aarch64-linux-gnu/ -DCMAKE_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/ -DCMAKE_BUILD_TYPE=Release .. -DCOPY_WX_LIBS=1**

( https://stackoverflow.com/questions/42254969/problems-building-codelite )'

Also - compilation fails:

`[ 13%] Building CXX object CodeLite/CMakeFiles/libcodelite.dir/LSP/DidOpenTextDocumentRequest.cpp.o
In file included from /home/nvidia/Desktop/codelite/CodeLite/LSP/MessageWithParams.h:5:0,
                 from /home/nvidia/Desktop/codelite/CodeLite/LSP/Notification.h:4,
                 from /home/nvidia/Desktop/codelite/CodeLite/LSP/DidChangeTextDocumentRequest.h:5,
                 from /home/nvidia/Desktop/codelite/CodeLite/LSP/DidChangeTextDocumentRequest.cpp:1:
/home/nvidia/Desktop/codelite/CodeLite/LSP/basic_types.h:277:18: error: ‘vector’ in namespace ‘std’ does not name a template type
     typedef std::vector<ParameterInformation> Vec_t;
`

**Comment by ngjermundshaug** [comment]
cmake **-G "Unix Makefiles"** -DCMAKE_INCLUDE_PATH=/usr/lib/aarch64-linux-gnu/ -DCMAKE_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/ -DCMAKE_BUILD_TYPE=Release .. -DCOPY_WX_LIBS=1

might have done the trick.. at 18% now.. still compiling...

**Comment by ngjermundshaug** [comment]
Adding 

`#include <vector>`

to CodeLite/LSP/basic_types.h fixed it

**Comment by eranif** [comment]
This was already fixed earlier today, closing this
