### ISSUE TITLE
Feature Request - Line Spacing

### ISSUE THREAD

**Issue by nomen140** [eranif/codelite#2246]
please add an option for line spacing.

**Comment by eranif** [comment]
I don't think its possible to add this kind of feature to CodeLite.
CodeLite uses this control: https://www.scintilla.org/ScintillaDoc.html for the main editor component.
This feature was requested in the past, the answer remains: to change the spacing, you will need to change the font. There is no other way to do this in using Scintilla.
I presonally am using this font https://github.com/tonsky/FiraCode and I am quite happy with the result (it's also more dense)
