### ISSUE TITLE
Output not working

### ISSUE THREAD

**Issue by ngjermundshaug** [eranif/codelite#2247]
Output (cout / cerr) is never shown in Output Window. Had the same problem on v10 and also on v 12.0.14 (built today).

![image](https://user-images.githubusercontent.com/1677884/55198759-a1631100-51b7-11e9-8d4e-54978a559679.png)

**Comment by eranif** [comment]
CodeLite has no builtin terminal. It uses the system terminamsl (xfce, gnom-terminal etc)
You can choose which terminal is used from settings->preferences->terminal
During debug session, the output is printed to the CMD/iTerm2/iTerm etc (please make sure to specify which OS you are running)

**Comment by ngjermundshaug** [comment]
This is on Ubuntu 18 / on a Jetson TX2 - aarch64). I access the Ubuntu machine from a Windows 10 PRO PC - running MobaXTerm  (with X forwarding). Works great 99% of the time.

The xterm window is not showing on my Windows PC when running it this way - perhaps it is being sent to Display:0? Forgot to test it on at work today - where the TX2 is located.

(This works with Code**Blocks** - I get the Xterm Window appearing (on my Win10 machine) when running/debugging).

**Comment by kermit1981** [comment]
Chose Settings->Preferences->Terminal ->xfce4-terminal
![Screenshot_2019-11-18_14-49-18](https://user-images.githubusercontent.com/22390313/69051859-909d2f00-0a16-11ea-8338-015e7b7816bd.png)

**Comment by eranif** [comment]
Did you install `xfce4-terminal` ?
