### ISSUE TITLE
Unable to change default terminal setting

### ISSUE THREAD

**Issue by Atimlotus** [eranif/codelite#2258]
Using on Windows 10
Codelite Version : 12.0.0

I wanted to be able to change the default terminal window position at project-app launch.  I could not see how to do it with CodeLite's built in terminal so I decided to try a 3rd party console.

When I unchecked the "Use Codelite's built-in terminal emulator" checkbox in Settings->Terminal everything including said checkbox became greyed out.  After reading #1941 I thought that getting the latest version of Codelite ( I was previously on version 10 ) resolve.  However, after installing version 12, the problem remains.  I am currently unable to change any settings in the Settings->Terminal dialogue.

I have not tried a complete uninstall/reinstall (am trying to avoid).  Thank You.

**Comment by eranif** [comment]
The terminal handling was completely re-written in CodeLite 12+ (current release is 12.0.15)
CodeLite supports a fixed list of terminals:

*  CMD only for Windows and the builtin terminal
* macOS: iTerm , iTerm2 and codelite-terminal
* 8 popular terminals

If you want to add a new type of terminal, please open a feature request with the terminal that you want to use.

Note that for the debugger, CMD is always used (this is the only terminal that gdb can work with)

**Comment by Atimlotus** [comment]
Thank you for your response.

After digging around a bit I was able to find the setting to change the launch position for the default terminal ( right-click the title bar on the terminal window after it opens and go to properties (duh!) ).  If I ever find myself in need of additional functionality I will open a feature request as you have suggested.
