### ISSUE TITLE
ARM windows build

### ISSUE THREAD

**Issue by drbree82** [eranif/codelite#2261]
Can someone build codelite for ARM windows so I can run it on my HP envy x2 without needing to use x86 emulation mode? I'm only learning C++ at the moment and am not yet familiar with Cmake, Make, etc. Can only compile cpp files.

Even if I can get an explanation of any changes I'd need to make to the makefiles so I can try it myself, that would be great.

**Comment by eranif** [comment]
Sorry, we don't support ARM and non of the core developers (2...) have the time to do this (not to mention that there is no demand for this)

**Comment by drbree82** [comment]
That's ok, there's a deb in the debian repos that runs on WSL. Works better than the windows version anyway. Thanks for replying.
