### ISSUE TITLE
wx3.1-headers_3.1.2-1.disco_amd64.deb broken

### ISSUE THREAD

**Issue by slodki** [eranif/codelite#2263]
# How to reproduce
With following packages installed:
```
||/ Name                                    Version       Architecture Description
+++-=======================================-=============-============-===========================================================================
ii  libwxbase3.1-0-unofficial:amd64         3.1.2-1.disco amd64        wxBase library (runtime) - non-GUI support classes of wxWidgets toolkit
ii  libwxbase3.1-0-unofficial3:amd64        3.1.2-1.disco amd64        wxBase library (runtime) - non-GUI support classes of wxWidgets toolkit
ii  libwxbase3.1-dev                        3.1.2-1.disco amd64        wxBase library (development) - non-GUI support classes of wxWidgets toolkit
ii  libwxbase3.1unofficial3-dev             3.1.2-1.disco amd64        wxBase library (development) - non-GUI support classes of wxWidgets toolkit
ii  libwxgtk-webview3.1-0-unofficial3:amd64 3.1.2-1.disco amd64        wxWidgets Cross-platform C++ GUI toolkit (webview library runtime)
ii  libwxgtk-webview3.1unofficial3-dev      3.1.2-1.disco amd64        wxWidgets Cross-platform C++ GUI toolkit (webview library development)
ii  libwxgtk3.1-0-unofficial:amd64          3.1.2-1.disco amd64        wxWidgets Cross-platform C++ GUI toolkit (GTK+ runtime)
ii  libwxgtk3.1-0-unofficial3:amd64         3.1.2-1.disco amd64        wxWidgets Cross-platform C++ GUI toolkit (GTK+ runtime)
ii  libwxgtk3.1-dev                         3.1.2-1.disco amd64        wxWidgets Cross-platform C++ GUI toolkit (GTK+ development)
ii  libwxgtk3.1unofficial3-dev              3.1.2-1.disco amd64        wxWidgets Cross-platform C++ GUI toolkit (GTK+ development)
ii  wx-common                               3.1.2-1.disco amd64        wxWidgets Cross-platform C++ GUI toolkit (common support files)
ii  wx3.1-headers                           3.1.2-1.disco amd64        wxWidgets Cross-platform C++ GUI toolkit (header files)
```

**and manually patched `wx-config` scripts for #2262** generate incorrect (non-existing) include dirs:

```bash
$ wx-config --toolkit=gtk2 --cppflags
-I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.1-unofficial -I/usr/include/wx-3.1-unofficial -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__

$ wx-config --toolkit=gtk3 --cppflags
-I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.1-unofficial3 -I/usr/include/wx-3.1-unofficial -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__

$ ls -ld /usr/lib/x86_64-linux-gnu/wx/include/* /usr/include/wx-3.1-unofficial
ls: cannot access '/usr/include/wx-3.1-unofficial': No such file or directory
drwxr-xr-x 3 root root 4096 Apr 23 02:06 /usr/lib/x86_64-linux-gnu/wx/include/base-unicode-3.1-unofficial
drwxr-xr-x 3 root root 4096 Apr 23 02:06 /usr/lib/x86_64-linux-gnu/wx/include/base-unicode-3.1-unofficial3
drwxr-xr-x 3 root root 4096 Apr 23 02:06 /usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.1-unofficial
drwxr-xr-x 3 root root 4096 Apr 23 02:06 /usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.1-unofficial3
```

# How to fix

The [wx3.1-headers_3.1.2-1.disco_amd64.deb](https://repos.codelite.org/wx3.1.2/ubuntu/pool/universe/w/wxwidgets3.1/wx3.1-headers_3.1.2-1.disco_amd64.deb) package contains `/usr/include/wx-3.1-unofficial3` directory with `*.h` files but this should be renamed to `/usr/include/wx-3.1-unofficial`.

Both [libwxgtk3.1-dev_3.1.2-1.disco_amd64.deb](https://repos.codelite.org/wx3.1.2/ubuntu/pool/universe/w/wxwidgets3.1/libwxgtk3.1-dev_3.1.2-1.disco_amd64.deb) and [libwxgtk3.1unofficial3-dev_3.1.2-1.disco_amd64.deb](https://repos.codelite.org/wx3.1.2/ubuntu/pool/universe/w/wxwidgets3.1/libwxgtk3.1unofficial3-dev_3.1.2-1.disco_amd64.deb) use hard-coded `/usr/include/wx-3.1-unofficial` path inside `wx-config` scripts.

**Comment by slodki** [comment]
The previous [wx3.1-headers_3.1.2-1.cosmic_amd64.deb](https://repos.codelite.org/wx3.1.2/ubuntu/pool/universe/w/wxwidgets3.1/wx3.1-headers_3.1.2-1.cosmic_amd64.deb) package has correct `/usr/include/wx-3.1-unofficial` path included.

**Comment by slodki** [comment]
@dghart ?

**Comment by dghart** [comment]
Hi,

Thank you for your report. I agree there is a problem though, as with #2262, I cannot reproduce all your findings here. 

This time I tested on a fresh (Virtualbox) xubuntu disco live cd. Again /bin/ is a symlink to /usr/bin/.

I copy/pasted your list of wx3.1.2 packages and apt-installed them. wx-config then gave the expected output.

However trying to build a (CodeLite) package fails for the reason you say: 
/usr/include/wx-3.1-unofficial3
should be
/usr/include/wx-3.1-unofficial

I'll investigate and fix this. Thank you for reporting it.

**Comment by dghart** [comment]
If you apt update, this should now be fixed (if not, please reopen this bug!)

The problem was that both the wxGTK2 and wxGTK3 builds create identically named header packages. The wxGTK2 one installs to the correct dir, and for cosmic that must have been the one I uploaded.
