### ISSUE TITLE
The same frg and brg color in New project dialog

### ISSUE THREAD

**Issue by zbyna** [eranif/codelite#2267]
Hi,
thanks for the great IDE.
I encounter the following issue in File/New/New Project:
![](https://i.imgur.com/ZHWvQft.png)
After clicking the text is readable:
![](https://i.imgur.com/Bnqq32F.png)
I am using a custom dark theme in Windows 7 64bit and CodeLite:
![](https://i.imgur.com/3ss2X4p.png)
The alternate color for a row is the same even if I use custom base color here:
![](https://i.imgur.com/c3ls4ka.png)
I am a beginner with cpp and wxwidget but if you point me a little bit I will try to fix it myself.
 zbyna

**Comment by zbyna** [comment]
I did small research with these results:
- there is no color for alternate rows in Windows 
- these fixies were created in generic wxWidgets:
        -  ``` automatic inferring``` from  system background  
        -   ```possibility to set custom color```
https://github.com/wxWidgets/wxWidgets/commit/4bdc891f548dce13863001de51327c7f9abaea0d
Discussion here:
http://trac.wxwidgets.org/ticket/12834#no1
Documentation change: https://github.com/wxWidgets/wxWidgets/commit/04fbcdab72315e18039a3f81e1bb4108473d19c9

**Comment by eranif** [comment]
CodeLite is now using its own tree/data view control that I have written (a generic version that does not use the wxWidgets one)
For example, the workspace view is using clTreeCtrl and the `Open Resource` (`Ctrl-Shift-R`) is using `clDataViewListCtrl`. You can compare the visual differences for alternate row colours.

The `New Project Wizard` should also be moving to `clDataViewListCtrl` and dump the `wxDataViewListCtrl` that it currently uses

**Comment by zbyna** [comment]
```clDataViewListCtrl``` looks much better with my configuration:
![](https://i.imgur.com/mwmsgaN.png)
Thank you for the explanation.

**Comment by eranif** [comment]
Fixed. New project dialog was updated
