### ISSUE TITLE
CMake is not running correctly

### ISSUE THREAD

**Issue by mtangoo** [eranif/codelite#2269]
I just started migrating to CMake and would not build anything. Everytime it tells me there is nothing to build.

I have noticed (after hours of course) that CL runs `cmake /path/to/CMakeList.txt` while not in a the required build directory. When I ran cmake manually and generated the project build files, running `build` works

Also there is problem with `STRIP` function and is well documented [here](https://stackoverflow.com/questions/26585513/cmake-error-with-string-sub-command-strip-requires-two-arguments) (Both cause and solution)

Am not sure if anyone have experienced this. I use latest git version on MacOS High Sierra

**Comment by mtangoo** [comment]
I have fixed the second issue of STRIP function (this one was easy), looking at how I can solve the former, If I make it PR will follow.

**Comment by mtangoo** [comment]
So after doing some test I have realized that cmake is not running correctly. Here's why I think so:
1. Right click project and run CMake. The command is printed on Output window but no files is generated
2. Run same command manually on the Terminal and it generates files.

I don't know much of codelite internals so I don't have Idea where to poke around. Here is the command after applying my changes

`cmake -S /WS/Path/Project -B /WS/Path/cmake-build-Debug/Studio/`

@eranif can you advice where should I look further?

**Comment by eranif** [comment]
Are you using custom build setup in CodeLite? or are you using the `CMake` plugin?

**Comment by mtangoo** [comment]
I followed Wiki Instructions so I know its CMake plugin. Moreover changed I did to add quotation marks for `STRIP` is in CMake Plugin ad it resolved the issue. Finally I traced the command that get displayed, which I copy to terminal where it runs fine, it also comes from CMake plugin.

Here is the link I followed: http://codelite.org/pmwiki/pmwiki.php?n=Main.TheCMakePlugin

**Comment by mtangoo** [comment]
I don't know what happened but now it works just fine. 
So strange!
