### ISSUE TITLE
Unreadable Items in a Dark Theme

### ISSUE THREAD

**Issue by vladipus** [eranif/codelite#2271]
Certain items are not visible, when using a dark windowing theme:

![image](https://user-images.githubusercontent.com/468323/57291162-9315e800-70c7-11e9-97a3-6224d49e0c24.png)

And search buttons are also hard to read:

![image](https://user-images.githubusercontent.com/468323/57291225-b04ab680-70c7-11e9-87cd-74391ce888ce.png)

**Comment by eranif** [comment]
Which version of CodeLite?
Which OS?
For the second screenshot, CodeLite should be picking the light icon theme automatically (from the icons, I can tell that you are using an older version of CodeLite)

![Capture](https://user-images.githubusercontent.com/3677711/57292656-eccbe180-70ca-11e9-9173-e69896ce0c59.png)

**Comment by vladipus** [comment]
This is on the latest Linux Mint OS. The CodeLite version is 12.
Thank you for your work, eranif!

**Comment by vladipus** [comment]
Also here:
![image](https://user-images.githubusercontent.com/468323/57295681-b181e080-70d3-11e9-9063-620a4dab52f9.png)

**Comment by eranif** [comment]
All the above screenshots are now fixed in latest git master.
Hopefully, we are planning on releasing CodeLite 13 this weekend
