### ISSUE TITLE
Hidden output pane

### ISSUE THREAD

**Issue by GeorgeKalovyrnas** [eranif/codelite#2272]
Hi,
when opening a workspace, the output pane always hides itself. Am I missing a setting?
I am using the GTK2 version.

P.S. Is there a real advantage to use the GTK2 over the GTK3 version?

**Comment by eranif** [comment]
About GTK2 vs GTK3:
wxWidgets (the underlying toolkit used by CodeLite) seems to be more stable with GTK2.
Some minor issues exists in wxGTK3 which does not exists in wxGTK2 (I doubt if you will notice them)
I use them both on my daily work (different users) to iron out any bugs. At the times of writing this, I couldn't find "show stopper" bug in either of the versions.

GTK3 will give you a more recent GTK  controls (for example, the "Open File" dialog was changed in GTK3)

**Comment by GeorgeKalovyrnas** [comment]
Thanks for the thorough explanation.
What about the hidden output panel?

**Comment by eranif** [comment]
This was a bug which is now fixed
