### ISSUE TITLE
Backspace not working in text boxes

### ISSUE THREAD

**Issue by soo-zie** [eranif/codelite#2273]
As mentioned in title, backspace is not working properly in text boxes such as for creating new projects / new workspace. If I enter any wrong word I have to press esc and start all over again.
If there is a workaround for this kindly suggest.

![image](https://user-images.githubusercontent.com/39080326/57584754-ac21fd00-74fc-11e9-9555-8650dc4397e0.png)

CodeLite: 12.0.0
Debain 9

**Comment by eranif** [comment]
Strange, as I am using Debian 8 (stretch) myself as my desktop and I never encountered this before.
Which desktop environment are you using? (I am using LXQT & Gnome)

**Comment by dghart** [comment]
This may be an ibus issue: see e.g. http://trac.wxwidgets.org/ticket/16840 and https://forums.wxwidgets.org/viewtopic.php?f=1&t=42440 (towards the end of both threads).

**Comment by eranif** [comment]
@dghart  should we add the solution you mentioned in wxTrac  (` wxUnsetEnv("GTK_IM_MODULE")`) ?

**Comment by soo-zie** [comment]
Apologies for late response.

@dghart Thank you. It worked after  `export GTK_IM_MODULE=gtk-im-context-simple`

@eranif I'm using xfce with debian 9 (stretch). I think debian 8 is Jessie.

**Comment by infinit-loop** [comment]
The same problem is occurring with me, I have exported this but nothing works.
