### ISSUE TITLE
Code complete & suggestion while Clang?

### ISSUE THREAD

**Issue by gnt-br** [eranif/codelite#2276]
Hello;
In linux using latest stable codelit (12) 64bit version.
If I select any type of project other than g++ and gcc I don't get any code suggestion (Ctrl+Space)?
for example I am wring a consloe cpp app using clang++ project style. and I have the explained problem.
Do I missed something?

**Comment by eranif** [comment]
This should work out of the box, if it does not, then please provide a minimal example of how to reproduce this. I strongly suggest that you join the Gitter chat or use the forum to ask such questions as this is most likely a configuration issue and not a real bug
