### ISSUE TITLE
Refactoring and Find reference bug

### ISSUE THREAD

**Issue by alex-rass-88** [eranif/codelite#2277]
In the continuation https://codelite.org/forum/viewtopic.php?f=11&t=4233

I turned on the developer log and found the reason: source files with UTF-8 with BOM.
Function has name 'GetErrorDescription', but CodeLite search in DB 'GetErrorDescript'.
If I recode the file to UTF-8 without BOM, everything works correctly.
When using BOM, 3 characters are lost.

**Comment by morgoth6** [comment]
I can observe the same behaviour on some on my source files and after reading this bug description I checked and it seems to afect  files with Polish characters (saved as utf-8 without BOM) and works as expected with files with ascii characters only.

Also searching is affected.The results list at bottom panel looks fine (right portion of linę is highlighted) but after mouse click its shifted by a few characters in editor window.
