### ISSUE TITLE
codelite-make keeps coredumping when using a project with a custom makefile

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2282]
codelite-make keeps coredumping when using a project with a custom makefile 

```
Process 8567 (codelite-make) of user 1000 dumped core.                                  
Stack trace of thread 8567:
#0  0x00007f6a66e7f85f _IO_fwide (libc.so.6)
#1  0x00007f6a66e73521 __vfwprintf_internal (libc.so.6)
#2  0x00007f6a66e7baea fwprintf (libc.so.6)
#3  0x00007f6a6741c665 _ZN10FileLogger5FlushEv (liblibcodelite.so)
#4  0x00007f6a674957d2 _ZN15UnixProcessImpl7ExecuteEP12wxEvtHandlerRK8wxStringmS4_P16IProcessCallback (liblibcodelite.so)
#5  0x00007f6a67b4578c _ZNK8Compiler20POSIXGetIncludePathsEv (libplugin.so)
#6  0x00007f6a67b46205 _ZN8Compiler22GetDefaultIncludePathsEv (libplugin.so)
#7  0x00007f6a67a15ce4 _ZNK19BuildSettingsConfig23GetCompilersGlobalPathsEv (libplugin.so)
#8  0x00007f6a67c3d2cc _ZNK14clCxxWorkspace25CreateCompileCommandsJSONEv (libplugin.so)
#9  0x0000559241447559 _ZN18clMakeGeneratorApp25DoGenerateCompileCommandsEv (codelite-make)
#10 0x0000559241449037 _ZN18clMakeGeneratorApp6OnInitEv (codelite-make)
#11 0x00007f6a67eaa4ea _Z7wxEntryRiPPw (libwx_baseu-3.0.so.0)
#12 0x0000559241443a29 main (codelite-make)
#13 0x00007f6a66e2bce3 __libc_start_main (libc.so.6)
#14 0x0000559241443a9e _start (codelite-make)
```

**Comment by uffejakobsen** [comment]
Seen on archlinux CL-13.0

**Comment by eranif** [comment]
How do I reproduce this?

**Comment by uffejakobsen** [comment]
I have a rather big workspace with three sub projects and after upgrading to CL13.0 codelite-mk began to coredump when building the projects.
Actually is did not disturb my development work - i only discovered the coredumps by looking into the system log.

I'll try to reproduce the problem with a smaller setup - and will update this issue with the details :-)

**Comment by eranif** [comment]
I wasn't able to reproduce this, but I from your backtrace, I can see where it crashes.
In `FileLogger::Flush()`  there is an attempt to write to the log file without checking whether `m_fp` is not NULL. I fixed that and it should fix your crash

**Comment by uffejakobsen** [comment]
Ok, thanks :-)

In the meantime I've managed to cook down an example that easily reproduces the problem on CL13.0

1) create a new workspace
2) create a new project within that workspace - select "Custom makefile" as project type.

Now you have a workspace with one project but no source files in the project.

Both "Build project" and "Clean project" will trigger the coredump.

BTW: what is the purpose of the codelite-make binary ? To get rid of the coredumps - I simply moved the codelite-make binary to another name. The coredumps disappeared and codelite kept working with no notable difference in functionality... I was still able to build and clean my project etc...

**Comment by eranif** [comment]
`codelite-make` allows you to compile CodeLite projects from the command line and without GUI loaded (e.g. over ssh), this small utility reads and understands the workspace/projects and how to build them (the same as CodeLite does, in fact, they are using the same library to do that).

One of the changes in CodeLite 13 was the introduction of Language Servers (for better and more complete code completion). The current C++ language server is `clangd` which requires `compile_commnads.json` or `complie_flags.txt` files to work. This is where `codelite-make` fits in: after each build, CodeLite will trigger `codelite-make` to generate these files

**Comment by wof2** [comment]
Why is this issue closed? codelite-make is keeping high cpu usage while IDE is idle. Renaming the file is a workaround, not a solution.

**Comment by eranif** [comment]
Can this be reproduced with the latest `codelite-make` ? I thought I fixed it...

**Comment by wof2** [comment]
Hi, thanks for answer. I'm running linux mint with CodeLite IDE 13.0.0. Should it be fixed?

**Comment by eranif** [comment]
CodeLite 13 was released on May, 25. The commit that fixed this was committed on Jun 6. So No

**Comment by wof2** [comment]
OK, thanks!

**Comment by eranif** [comment]
BTW, this is the commit that fixed that: https://github.com/eranif/codelite/commit/2f41e951dbbfb352a6320d8a0730ca2beb906739
