### ISSUE TITLE
Compiling CodeLite 13 on MacOS Mojave has problems

### ISSUE THREAD

**Issue by hotdeveloper** [eranif/codelite#2283]
Hello~!

I faced the problem below during compile CodeLite 13.

[  8%] Building CXX object CodeLite/CMakeFiles/libcodelite.dir/clConsoleCMD.cpp.o
[  8%] Building CXX object CodeLite/CMakeFiles/libcodelite.dir/clConsoleCodeLiteTerminal.cpp.o
/Users/slime/codelite-build/codelite-13.0/CodeLite/clConsoleCodeLiteTerminal.cpp:119:29: error: no member named 'wxStringTokenize'
      in the global namespace
    wxArrayString lines = ::wxStringTokenize(psOutput, "\n", wxTOKEN_STRTOK);
                          ~~^
/Users/slime/codelite-build/codelite-13.0/CodeLite/clConsoleCodeLiteTerminal.cpp:119:62: error: use of undeclared identifier
      'wxTOKEN_STRTOK'
    wxArrayString lines = ::wxStringTokenize(psOutput, "\n", wxTOKEN_STRTOK);
                                                             ^
2 errors generated.
make[2]: *** [CodeLite/CMakeFiles/libcodelite.dir/clConsoleCodeLiteTerminal.cpp.o] Error 1
make[1]: *** [CodeLite/CMakeFiles/libcodelite.dir/all] Error 2
make: *** [all] Error 2

This machine running the compiler has Xcode 10.2.1.

**Comment by eranif** [comment]
How did you run CMake?
It might be related to the PCH (Precompiled header)

**Comment by hotdeveloper** [comment]
I added set(CMAKE_MACOSX_RPATH 1) into CMakeLists.txt, and I did the procedure following 'https://wiki.codelite.org/pmwiki.php/Developers/BuildingCodeLiteOnAMac'

and then I got a new error instead I mentioned above. 

Undefined symbols for architecture x86_64:
  "wxArrayString::Init(bool)", referenced from:
      TokenizeWords(wxString const&) in pptable.cpp.o
      PPToken::squeeze() in pptable.cpp.o
      CLReplacePattern(wxString const&, wxString const&, wxString const&, wxString&) in pptable.cpp.o
      PPToken::PPToken() in pptable.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/codelite_indexer] Error 1
make[1]: *** [sdk/codelite_indexer/CMakeFiles/codelite_indexer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
...
...
[ 11%] Building CXX object sdk/codelite_cppcheck/CMakeFiles/codelite_cppcheck.dir/lib/tokenlist.cpp.o
[ 11%] Building CXX object sdk/codelite_cppcheck/CMakeFiles/codelite_cppcheck.dir/lib/valueflow.cpp.o
[ 11%] Linking CXX executable ../../bin/codelite_cppcheck
[ 11%] Built target codelite_cppcheck
make: *** [all] Error 2

Thank you in advance.

**Comment by xukev** [comment]
@hotdeveloper  Hi ,  I am build latest Codelite on Catalina10.15.2. And I saw the same as you. How do you solve this build error? 
/Projects/GIT_SRC/Codelite/codelite/CodeLite/clConsoleCodeLiteTerminal.cpp:120:29: error: 
      no member named 'wxStringTokenize' in the global namespace
    wxArrayString lines = ::wxStringTokenize(psOutput, "\n", wxTOKEN_STRTOK);
                          ~~^
/Projects/GIT_SRC/Codelite/codelite/CodeLite/clConsoleCodeLiteTerminal.cpp:120:62: error: 
      use of undeclared identifier 'wxTOKEN_STRTOK'
    wxArrayString lines = ::wxStringTokenize(psOutput, "\n", wxTOKEN_STRTOK);

Thank you in advance.
