### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by majkinetor** [eranif/codelite#2284]
FYI, chocolatey package that always follows releases on github is available:

* https://chocolatey.org/packages/codelite

Perhaps it could be mentiond as method of installation.
The package is maintained on main community repository, here is the code:
* https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/codelite

**Comment by eranif** [comment]
Sounds great!
Does this package include 32 bit Windows or just 64 bit?

**Comment by majkinetor** [comment]
It included both and installed appropriate one until latest version which doesnt have one AFAIK.

You can see that by looking into package directly on gallery web.

**Comment by eranif** [comment]
Thanks, I added a reference to the package in CodeLite download page
https://downloads.codelite.org/
