### ISSUE TITLE
Bad link SFTP / Workspace Mirroring

### ISSUE THREAD

**Issue by clach04** [eranif/codelite#2285]
https://wiki.codelite.org/pmwiki.php/Main/ReadMore#toc8 links to http://codelite.org/LiteEditor/SFTP which 404s.

I'm not sure if it is supposed to redirect to https://wiki.codelite.org/pmwiki.php/Main/SFTP

**Comment by eranif** [comment]
Thanks, I have fixed the broken link
The correct link is: https://wiki.codelite.org/pmwiki.php/Main/SFTP#toc3
