### ISSUE TITLE
Plugins window list not readable on Microsoft Windows high DPI/UHD/4K display (3840x2160 resolution)

### ISSUE THREAD

**Issue by clach04** [eranif/codelite#2286]
Version 13.0.0
Microsoft Windows 10 64-bit

Plugin window looks like

![image](https://user-images.githubusercontent.com/424032/59069648-b372c700-886c-11e9-8f98-4a6c1a46ad8d.png)

(main window omitted for clarity).

This is related to:
  * issue #2063 
  * maybe? issue #2195
  * issue #2023

I've only tested under Microsoft Windows 10.

The workaround I'm employing is to:
  * right click the shortcut/binary, 
  * properties
  * compatibility (see below)
  * Change high DPI settings
  * High DPI scaling override enabled, select "System" (see below)

![image](https://user-images.githubusercontent.com/424032/59069775-0fd5e680-886d-11e9-981b-8bb600287737.png)

![image](https://user-images.githubusercontent.com/424032/59069793-211ef300-886d-11e9-914a-c1e64c14cf2d.png)

**Comment by eranif** [comment]
Sadly, this is a wxWidgets issue. Looks like `wxListBox` "list" part is not scaling as it should.
The only fix I see here (without waiting for wxWidgets to fix this) is to replace `wxListBox` with `clDataViewListCtrl` which scales properly
