### ISSUE TITLE
Some settings (windows) cannot be closed with escape key (CL13.0)

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2289]
These "windows" in (all accessible from the "Settings" menu) - cannot be closed by pressing escape key:

Preferences
Build settings
GBD settings
Code completion

(the rest of the "windows" accessible from that menu can be closed by pressing escape key - which is really nice for us that wishes to minimize the use of mouse)

CL13.0@archlinux

**Comment by eranif** [comment]
I can close all these windows on Windows & Debian...
Maybe its a wx related?
