### ISSUE TITLE
Build 13.0 release with wxwidgets 3.0.4 fails

### ISSUE THREAD

**Issue by rezso** [eranif/codelite#2292]
> [ 96%] Building CXX object codelite_terminal/CMakeFiles/codelite-terminal.dir/TextView.cpp.o
/var/uhubuild/work/compile/codelite_terminal/TextView.cpp: In constructor ‘TextView::TextView(wxWindow*, wxWindowID)’:
/var/uhubuild/work/compile/codelite_terminal/TextView.cpp:15:27: error: no matching function for call to ‘wxStyledTextCtrl::StartStyling(int)’
   15 |     m_ctrl->StartStyling(0);
      |                           ^
In file included from /var/uhubuild/work/compile/codelite_terminal/TextView.h:5,
                 from /var/uhubuild/work/compile/codelite_terminal/TextView.cpp:1:
/usr/include/wx-3.0/wx/stc/stc.h:2640:10: note: candidate: ‘void wxStyledTextCtrl::StartStyling(int, int)’
 2640 |     void StartStyling(int pos, int mask);
      |          ^~~~~~~~~~~~
/usr/include/wx-3.0/wx/stc/stc.h:2640:10: note:   candidate expects 2 arguments, 1 provided
/var/uhubuild/work/compile/codelite_terminal/TextView.cpp: In member function ‘void TextView::SetDefaultStyle(const wxTextAttr&)’:
/var/uhubuild/work/compile/codelite_terminal/TextView.cpp:64:51: error: no matching function for call to ‘wxStyledTextCtrl::StartStyling(long int)’
   64 |     m_ctrl->StartStyling(m_ctrl->GetLastPosition());
      |                                                   ^
In file included from /var/uhubuild/work/compile/codelite_terminal/TextView.h:5,
                 from /var/uhubuild/work/compile/codelite_terminal/TextView.cpp:1:
/usr/include/wx-3.0/wx/stc/stc.h:2640:10: note: candidate: ‘void wxStyledTextCtrl::StartStyling(int, int)’
 2640 |     void StartStyling(int pos, int mask);
      |          ^~~~~~~~~~~~
/usr/include/wx-3.0/wx/stc/stc.h:2640:10: note:   candidate expects 2 arguments, 1 provided
/var/uhubuild/work/compile/codelite_terminal/TextView.cpp: In member function ‘void TextView::Clear()’:
/var/uhubuild/work/compile/codelite_terminal/TextView.cpp:213:27: error: no matching function for call to ‘wxStyledTextCtrl::StartStyling(int)’
  213 |     m_ctrl->StartStyling(0);
      |                           ^
In file included from /var/uhubuild/work/compile/codelite_terminal/TextView.h:5,
                 from /var/uhubuild/work/compile/codelite_terminal/TextView.cpp:1:
/usr/include/wx-3.0/wx/stc/stc.h:2640:10: note: candidate: ‘void wxStyledTextCtrl::StartStyling(int, int)’
 2640 |     void StartStyling(int pos, int mask);
      |          ^~~~~~~~~~~~
/usr/include/wx-3.0/wx/stc/stc.h:2640:10: note:   candidate expects 2 arguments, 1 provided

**Comment by dghart** [comment]
Thank you for reporting this. I'd tested 13.0 with wx3.0.4 but only for gtk+2 builds, and it's gtk+3 builds that have the problem.

This should now be fixed in git HEAD. That diff,  92ed90e, also works for 13.0 so you could apply it locally; otherwise use gtk+2.
