### ISSUE TITLE
Possible case conflict on windows file names

### ISSUE THREAD

**Issue by jjvbsag** [eranif/codelite#2293]
But running a filechecker tool by luck I detected a possible filename conflict.
In `GitHub/eranif/codelite/Runtime/PHP.zip` there are two files, one named `superglobals.php` and one named `SuperGlobals.php`.
While this is ok for Linux (and I believe, also for Mac), this will surely create problems on Windows, as these two files cannot exist in parallel on windows case-insensitive filesystems.

I don't know, if this causes a problem for codelite, I just wanted to let you know about my observation.

**Comment by eranif** [comment]
It does not real harm as these two files are dummy files for the sake of the PHP code completion (they both define the exact same globals)
