### ISSUE TITLE
Deleting a line with error in leaves wrong error highlighting (CL13.0)

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2294]
Deleting a line with error in leaves wrong error highlighting (CL13.0)

If you delete a line marked with a compile error - the line is deleted - but the error stays visible.
It seems that if there is another error below the deleted line - the error marking for that is removed.

**Comment by eranif** [comment]
Can you post a screenshot?
Do you mean the error produced after build is compeleted?

**Comment by uffejakobsen** [comment]
Yes - sorry my explanation was not good enough.
The error marks are a result of a build performed from CL
The error marks that CL shows are errors in my source code - which CL points me to after a build.
Now if I try to delete a code line marked with an error - the line is deleted but the error mark and error description text remains in the editor.
In situations with multiple error marks within the same group of lines - CL seems to delete the wrong error mark further below the actual deleted line.

I'll post a screenshot when I'm home

**Comment by uffejakobsen** [comment]
screenshot01: starting situation - all ok

![screenshot01](https://user-images.githubusercontent.com/3018239/60188714-0cac9580-9830-11e9-8628-2c3f5626283b.png)

screenshot02: after build - ok

![screenshot02](https://user-images.githubusercontent.com/3018239/60188730-133b0d00-9830-11e9-81e0-6ad64b52a75c.png)

screenshot03: after delete of line 241 containing "error2;"  - not ok

The error msg for "error2" remains - while the error msg for "error3" is gone.

![screenshot03](https://user-images.githubusercontent.com/3018239/60188743-18985780-9830-11e9-95e6-92eff09940d5.png)


NOTE: to delete the "error2;" line - I used the "Delete line" function found in menu "Edit -> Line -> Delete Line"
"Delete Line" was invoked through a hotkey - in my CodeLite it is mapped to CTRL-K - but i do not remember if that is standard.

**Comment by eranif** [comment]
From what I can see, this bug comes from wxWidgets itself and not from CodeLite.
The workaround I can do there, is to clear all compiler markers upon any edit

**Comment by uffejakobsen** [comment]
Hmm that does not really sound as an appealing solution :-)
The usefulness seems individual - maybe an advanced setting should be used to control this wxWidgets "feature" - if it is not fixed in wxWidgets over time :-)

**Comment by eranif** [comment]
I am pretty sure it wont, as it probably comes from the underlying scintilla control (taking an educated guess here :))
