### ISSUE TITLE
wxCrafter add the setting to generate .cpp and .h for each form separately

### ISSUE THREAD

**Issue by billcxx** [eranif/codelite#2296]
I now have one project containing three forms:

![image](https://user-images.githubusercontent.com/3356113/60356725-b3fc0a80-999f-11e9-8590-a43a4b7314cb.png)

And the three derived class that I implement some event functions for the above three forms are 
1. MainFrame
2. FreeFormatInput
3. FreeFormatContentOneLine

In my application, one wxPanel in MainFrameBaseClass is subclassed as FreeFormatInput.

Then there will be a loophole in the header including part,

wxcrafter.h -> declare MainFrameBaseClass
MainFrameBaseClass -> use FreeFormatInput ->so #include "FreeFormatInput.h"
FreeFormatInput -> derived from FreeFormatInputBaseClass -> so #include "wxcrafter.h"

Which cause error during compilation.

My current work around is as follows, 
1. Instead of initializing the panel in MainFrameBaseClass as FreeFormatInput, subclass it as FreeFormatInputBaseClass.
2. Then inside the constructor for MainFrame, which is derived from MainFrameBaseClass, call 
``` 
panel->Destroy();panel=new FreeFormatInput(parent);
```

I think it would be better if in the settings, besides from one single  wxcrafter.h and wxcrafter.cpp file, we can choose to generate separate cpp and h files for each form.

**Comment by eranif** [comment]
You are confusing between 'form' and 'windows'
A simpler workaround would be to create a separate form (i.e. a wxcp file) for each class you need. This will generate separate .h and .cpp for each base classes.

Changing the way it works atm is too much of work and I doubt it will be done
