### ISSUE TITLE
Is there any way to change the font of the suggestions from the code completition ?

### ISSUE THREAD

**Issue by cata0309** [eranif/codelite#2303]
![image](https://user-images.githubusercontent.com/35623921/61271740-192c6a00-a7ae-11e9-81d8-3008e928eb48.png)

**Comment by eranif** [comment]
This window uses the same font as the code font. with a slight smaller font size. So basically, you need to change the editor font to change it

**Comment by cata0309** [comment]
I did that but nothing changed

lun., 22 iul. 2019, 10:30 Eran Ifrah <notifications@github.com> a scris:

**Comment by cata0309** [comment]
I switched to other IDE

**Comment by cata0309** [comment]
I started reusing Codelite and contribute to it as much as I can
