### ISSUE TITLE
why cant i use codelite 13 in high sierra 10.13.6 ?

### ISSUE THREAD

**Issue by mumin16** [eranif/codelite#2305]
why cant i use codelite 13 in high sierra 10.13.6 ?

**Comment by killjoy** [comment]
It was built on Majove, and I understand it is difficult to use cmake to make version compatible with older versions.  My student has built a version on a High Sierra Mac for our own use (I'm not one of the CodeLite Developers) that we are testing for use for teaching in the fall. I can submit the build if someone wants it.

**Comment by eranif** [comment]
@killjoy it's not difficult to build, however, it requires time. Which I don't have :(
if you built CodeLite 13 on High Sierra and are willing to share it - please share it (in a bundle form please) and I will upload it to our download page

**Comment by focussing** [comment]
@killjoy I would be interested in a High Sierra version of codelite. I still have a 2011 iMac.
That would help me a lot!
Looking forward to hearing from you.

**Comment by izan4mixoxo** [comment]
@focussing Did you have any luck? I have High Sierra on my 2011 mac as well, since Catalina just made it way too slow.

**Comment by focussing** [comment]
@izan4mixoxo Did not pursue this...
