### ISSUE TITLE
crash on FreeBSD

### ISSUE THREAD

**Issue by sss123next** [eranif/codelite#2306]
1. all compilers are disappeared from settings for some reason
2. codelite crashed on attempt to add new compiler

[gdb.txt](https://github.com/eranif/codelite/files/3435347/gdb.txt)

P.S. happened on 13.0 and also on git master

**Comment by eranif** [comment]
This looks like a crash of corrupted configurations.
The only fix is to delete `~/.codelite` and launch it again
