### ISSUE TITLE
Codelite debugger

### ISSUE THREAD

**Issue by Navneet12345** [eranif/codelite#2307]
Codelite debugger stops execution after a cout statement c++11.

**Comment by eranif** [comment]
Which OS?
FYI: if it stops execution it means that GDB terminated (exited)

**Comment by Navneet12345** [comment]
Sir I am using windows 10 and while debugging a c++11 project all the other
statements work fine but the debugger stops working as soon as it reaches a
cout statement . In the output pane it shows continuing and if I try to
build and run the project it says it will end the current debugging
session.also the green arrow disappears after clicking the next button two
to three times.i have tried to change the project settings but I didn't
seem to work.The same problem was with codelite12.0

**Comment by eranif** [comment]
I too faced these problems with GDB / MinGW on Windows. The problem is in the underlying GDB and not in CodeLite.
The same will happen if you will debug your program with CodeLite, i.e. using GDB from the command line. You should report this issue to the GDB team
