### ISSUE TITLE
Highlighting text in " " changes letter position

### ISSUE THREAD

**Issue by nickname13** [eranif/codelite#2308]
Hi I have this minor but very strange issue.

When i highlight text inside " " some letters are changing position.

The letters that change positions  are always "on the right" of what I highlight.
see attached photos.
1.png text without highlight
2.png text with highlighting. very minor but if you look close (or live) you will see them "moving"

3.png details without highlight
4.png details with highlight

I am not sure what kind of issue this is.

Also the other "highlited" text (same text) are not affected by this issue. Only the text I highlight. 

I am using Arch and Codelite v13.0.0 created by the aur package.

![1](https://user-images.githubusercontent.com/13780900/62110611-7993cf00-b2b7-11e9-8ad0-b9bd4e757ee8.png)

![2](https://user-images.githubusercontent.com/13780900/62110612-7993cf00-b2b7-11e9-958c-696ddcc0a42c.png)

![3](https://user-images.githubusercontent.com/13780900/62110613-7a2c6580-b2b7-11e9-9cb7-cd4f0faf40e7.png)

![4](https://user-images.githubusercontent.com/13780900/62110610-7993cf00-b2b7-11e9-8070-da6fb18a0ad2.png)

**Comment by eranif** [comment]
I have seen this before, however, it might go away if you change the font
There is nothing that I can do about this as this is not something handled by CodeLite source code but rather by the underlying GUI toolkit (wxWidgets & Scintilla)
