### ISSUE TITLE
Debugger doesn't show backtrace when program receives SIGPIPE

### ISSUE THREAD

**Issue by ozgilat** [eranif/codelite#2315]
When I debug a program, press 'continue', and afterwards it receives SIGPIPE - the IDE doesn't show that it has stopped. I need to click the backtrace tab (or go elsewhere and then come back) in order for it to show the backtrace. 
Maybe you can add a code break on the first line that is a user code...

**Comment by eranif** [comment]
This is now fixed

**Comment by ozgilat** [comment]
Grazie!
