### ISSUE TITLE
CodeLite 13.0.1 Building Problem

### ISSUE THREAD

**Issue by ianrasmussen05** [eranif/codelite#2319]
Every time I try to compile a cpp file on the new 13.0.1 version, CodeLite doesn't build correctly and it says that "build is in progress". It never seems to go away. It worked perfectly fine on CodeLite version 13.

**Comment by eranif** [comment]
Can you please provide more information:
- Which OS?
- Steps to reproduce?
- Does this happen when using a simple hello world ?

**Comment by ianrasmussen05** [comment]
It is on Windows 10, it says "The system cannot find the path specified." and it does not work on a simple hello world project. How can I fix the specific path problem?

**Comment by eranif** [comment]
Again, you are giving partial information..
Please provide all the info I asked: How do I reproduce this? The exact and *complete* error you get (not just the last line...).
there can be many reasons for "The system cannot find the path specified." , for example: do you have a compiler installed? etc..

**Comment by ianrasmussen05** [comment]
I just select build then run at the top, then it comes with this error:
Command line is empty. Build aborted.C:\WINDOWS\system32\cmd.exe /C cd C:\Users\ianra\OneDrive\Desktop\CPPProjects\Section9_v2\cmake-build-Debug\HelloWorld && C:/MinGW/bin/mingw32-make.exe -j6 SHELL=cmd.exe -e
The system cannot find the path specified.
====0 errors, 0 warnings====

I have a compiler installed, I use the MinGW compiler.

**Comment by eranif** [comment]
Do you have CMake installed?
From the build output it seems as if you picked `CMake` as the build environment for you.
If you are not sure, then change the build system back to the default one:

Project Settings->General->Makefile Generator->Default

**Comment by eranif** [comment]
I also changed that in the new project dialog, the "Default" build system is set as the default
