### ISSUE TITLE
Debugger not working

### ISSUE THREAD

**Issue by Evil6969** [eranif/codelite#2320]
When I run the debugger the output windows closes and nothing is happening I cant debug anything its really annoying pls help ty in advance

**Comment by eranif** [comment]
Which OS?

**Comment by Evil6969** [comment]
Windows 10

**Comment by eranif** [comment]
Please use the forum to ask questions.
Also, please follow the guide lines in the forum (see the HOW TO POST thread)
https://forums.codelite.org
