### ISSUE TITLE
libssh4

### ISSUE THREAD

**Issue by sk-jame** [eranif/codelite#2328]
Why codelite-make using it at all??
Anyhow, how I can prepare docker image with codelite, with ubuntu 16.04. When you removing old packages. Why R you doing it??

**Comment by eranif** [comment]
What is the error you are having?
`codelite-make` uses it because it depends on `liblibcodelite.so` which needs it for the various SFTP functionalities used by CodeLite

**Comment by sk-jame** [comment]
```codelite-make: error while loading shared libraries: libssh.so.4: cannot open shared object file: No such file or directory
codelite-make failed
```
why codelite-make need it? Thanks that pretty hard to use codelite-make generator in automotion

**Comment by sk-jame** [comment]
Problem that I can't use it normally with Docker Ubuntu 16.04 (1 month ago it works), but now it asked libssh4.so after 
```
aptitude install -y codelite wxcrafter libssh4
```

**Comment by eranif** [comment]
we are using libssh, I am not familiar with libssh4... 
Where did you obtain this CodeLite? i.e. from which repository?

**Comment by eranif** [comment]
Did you mean? `libssh.so.4`

**Comment by eranif** [comment]
If you just need `codelite-make`, you don't to install `wxCrafter`, just install codelite:

```
sudi apt-get install codelite
```
If you have an error, please paste it here

**Comment by dghart** [comment]
See also https://github.com/eranif/codelite/issues/2047

It seems that 16.04's debian 'Depends' auto-detector is failing to notice libssh, or maybe not requiring exactly the correct package to fulfill the dependency...

For the next CodeLite release I'll explicitly Depend: on libssh (>=4.0)

**Comment by sk-jame** [comment]
In Docker ubuntu:16.04 
I had to do extra steps:
```
RUN apt-get install -y aptitude

RUN apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc \
	&& echo "deb https://repos.codelite.org/ubuntu/ xenial universe" >> /etc/apt/sources.list \
	&& apt-get update && aptitude install -y codelite wxcrafter \
	&& apt-get install -y libssh-4
```

I dunno why, but with apt-get it fails on resolving dependency, but aptitude - works. Also libssh-4 package required
