### ISSUE TITLE
Can't Run Multiple Projects in one Workspace

### ISSUE THREAD

**Issue by dapobelieve** [eranif/codelite#2331]
I can't run different projects in the same workspace, there has to be only one project in that workspace for it to build and run. If I try to build n run a second project, it keeps running the first project that was in the workspace and not the new one I'm trying to run.
![image](https://user-images.githubusercontent.com/15062380/64073173-191af780-cc92-11e9-80df-5049833a02a9.png)
In the snip shot, `Test` was the first project runs well with no issues, `Another` is a new project which is the one I opened when I try to build and run, it still runs `Test's` main.cpp file

**Comment by eranif** [comment]
You need to make `Another` as the active project for the shortcuts to work (`Ctrl-F5`) or you can run it by right clicking the project and select `Run`

To make a project active, double click it (its text will become bold and italic)
