### ISSUE TITLE
Downloading CL 9.2.0 on Mac OS X 10.10.5 

### ISSUE THREAD

**Issue by Baminommi** [eranif/codelite#2332]
As the title states, I'm trying to download CL 9.2.0 on my mac. I am unable to update further from OS X 10.10.5 due to lack of hardware space, and I need CL 9.2.0 specifically for my class. 

I'm very new to all of this.

Apparently, the highest version of Xcode I can download is 7.2.1. I have an external drive, and am trying to download Xcode 7.2.1 directly on to the external hard drive, but keep receiving a 'failed-forbidden' error. 

Also, I could only find CL 9.2.0 on chocolatey, which I have no idea how to use. 

Any one out there willing to explain how I could download CL 9.2.0 and Xcode 7.2.1?

**Comment by eranif** [comment]
See here:
https://github.com/eranif/codelite/releases/
