### ISSUE TITLE
CMake with Ninja

### ISSUE THREAD

**Issue by alex-rass-88** [eranif/codelite#2333]
If using cmake with generator `"CodeLite - Ninja" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON`,
codelite duplicate records in compile_commands.json after every build. The file grows to a huge size.

Codelite 13.0.0 stable. Windows 10 1903 x64.

If using cmake with generator `"CodeLite - MinGW Makefiles" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON` works normal.

**Comment by eranif** [comment]
CodeLite does not create this file, it's created by CMake. You should report this to Cmake
