### ISSUE TITLE
CodeLite 11.0.3 Mac OS X build from git source

### ISSUE THREAD

**Issue by gerhardstraub** [eranif/codelite#2334]
The new builder could not be used on Mac OS X (there are application bundles instead of simple binaries, like you know). Please do not assume others use the same build environment as you did. Constants used as part of the pathname with a fixed form are not practical ($(WorkspacePath)...build-).
After I merged the last version into my current version 11.0.2 I run into trouble with the new "UpgradeBuildSettings" function at project.cpp. This function kills all existing project configurations that are contained in my workspaces without asking. Until I recongnized the problem more than 20 project configurations got corrupted. 
Please restore the old builder (classic) as the default builder, so that CodeLite is kept backwards compatible to existing projects and please remove this UpgradeBuildSettings function, because this function is a project killer. I have to repair all configurations by hand to get them working again. This will costs me hours of working for nothing. I could not understand what is the new builder created for. If you're working on large projects, do cross platform developtment or other stuff like this, that will need a special build infrastructure, you can't do this any longer with the new CodeLite version. Please do not implement functions like this without warning the users about it's dangerous.
This is a serious bug that must be fixed as fast as possible.

**Comment by eranif** [comment]
Thanks. What was corrupted exactly? (except for the build output directory and the executable location) nothing was really changed. Can you please update what was broken? (with a concrete example)

I will probably aim to fix this problem

**Comment by gerhardstraub** [comment]
Exactly the output and executable locations are the problem. The output directory should contain a location like $(IntermediateDirectory)/$(ProjectName).app/Contents/MacOS/$(ProjectName). This was replaced with a concat of Workspace..build-/$(ProjectName) (sorry I have not the exact syntax in mind because I do not have a internet at home, I wrote this from my work place). That means the binaries of the application bundle is no longer found. The same problem occur on the executable path. Building shared libraries, the output file name contains the library version that got lost by this upgrade process. That won't work for a Mac OS X or Linux build environment. So  p l e a s e  do a restore of the build system. If the new builder is really needed, just rename it, but do not set it as default. Before a change on a user system should be done, it is recommend to ask the user if it is accepted. I do the development on three main platforms -> Mac OS X, Linux (Debian) and Windows. My primary environment is Mac OS X using CodeLite and wxWidgets and from this platform I port the applications to the others. I have workspace configurations that contain projects for applications, shared libraries, documentation and testcases that must play together. If one of the configuration at a project is broken, nothing of the workspace will work any longer.
Thanks for your fast response.

**Comment by jm-seabery** [comment]
I've noticed this problem or something similar with 13.0.2 on Ubuntu. The output folder is not being correctly written into the makefile.

I have a directory for the output file like so...
![image](https://user-images.githubusercontent.com/50699991/64428271-9f30a700-d0b3-11e9-8584-bc19e0255e50.png)

However the mk makefile has written this as...
`OutputFile             :=../build-$(ConfigurationName)/bin/$(ProjectName)-d`
