### ISSUE TITLE
Build project does not run

### ISSUE THREAD

**Issue by killjoy** [eranif/codelite#2335]
Running Current MacOs Weekly Build (Aug 26). When a project has the default build system, .o and executable goes to a build-Debug folder in the workspace, but execute tries to run the Debug folder inside of the project Folder. When Project uses the Classic (Deprecated) build system, the .o files are in a Debug folder, the executable is in the project folder, but the run command tries to run from the build-Debug folder in the workspace folder.

Outputs:
================
test1 - Default Builld
===============

Build Window:
/bin/sh -c '/usr/bin/make -j16 -e -f  Makefile'
----------Building project:[ test1 - Debug ]----------
/usr/bin/gcc -c  "/Users/dean/APSC143/test1/main.c" -g -O0 -Wall  -o ../build-Debug/test1/main.c.o -I. -I.
/usr/bin/g++ -o ../build-Debug/bin/test1 @../build-Debug/test1/ObjectsList.txt -L.
====0 errors, 0 warnings====

Terminal Output:
Last login: Sat Sep  7 13:04:04 on ttys009
Thomass-MacBook-Pro:~ dean$ /tmp/codelite-exec.sh ; exit;
/tmp/codelite-exec.sh: line 3: cd: /Users/dean/APSC143/test1/Debug: No such file or directory
Hit any key to continue...

=================
test2 -Classic(Deprecated Build)
==================

/bin/sh -c '/usr/bin/make -j16 -e -f  Makefile'
----------Building project:[ test2 - Debug ]----------
/usr/bin/gcc -c  "/Users/dean/APSC143/test2/main.c" -g -O0 -Wall  -o ./Debug/main.c.o -I. -I.
/usr/bin/g++ -o test2 @"test2.txt" -L.
====0 errors, 0 warnings====

Terminal Output:
Last login: Sat Sep  7 13:10:31 on ttys005
Thomass-MacBook-Pro:~ dean$ /tmp/codelite-exec.sh ; exit;
/tmp/codelite-exec.sh: line 3: /Users/dean/APSC143/build-Debug/bin/test2: No such file or directory
Hit any key to continue...

**Comment by eranif** [comment]
This was fixed earlier today. You will need to update your CodeLite sources or rollback your CodeLite version. Once 13.0.3 is released, you could load your project again and switch between the different builders (Default -> CodeLite Make Generator) - CodeLite will offer to fix the paths for you.

See https://github.com/eranif/codelite/issues/2334

**Comment by killjoy** [comment]
It works, thanks..

**Comment by Gast-dm** [comment]
Hi! I have the same issue with 15.0.0 and 15.0.6. 

When hitting "Rebuild project" there is no errors :
/bin/sh -c '/usr/bin/make -j8 -e -f  Makefile'
----------Building project:[ test - Debug ]----------
/usr/bin/g++  -c  "/Users/gaston/Downloads/test/test/main.cpp" -g -O0 -Wall  -o ../build-Debug/test/main.cpp.o -I. -I.
/usr/bin/g++ -o ../build-Debug/bin/test @../build-Debug/test/ObjectsList.txt -L.
====0 errors, 0 warnings====

But after hitting "run", I receive this message on the console : 
gaston@mbp-de-gaston ~ % /tmp/codelite-exec.sh ; exit;
/tmp/codelite-exec.sh: line 3: cd: /Users/gaston/Downloads/test/build-Debug/lib: No such file or directory
Hit any key to continue...

And the output on codelite shows: 
Working directory is set to: /Users/gastondemourgues/Downloads/test/build-Debug/lib
Executing: open -n -a Terminal /tmp/codelite-exec.sh
Program exited

Should I downgrade to 13.0.3? Or is there an easy way to fix this ?
I'm using GCC compiler, with LLDB debugger and CodeLite Makefile Generator.

Thank you in advance for your help!
