### ISSUE TITLE
Codelite 13.0.2 crashes upon exit

### ISSUE THREAD

**Issue by al20878** [eranif/codelite#2339]
Problem Event Name:	APPCRASH
  Application Name:	codelite.exe
  Application Version:	13.0.0.0
  Application Timestamp:	5d63fd3f
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.24520
  Fault Module Timestamp:	5d673de3
  Exception Code:	c0000005
  Exception Offset:	000000000003fffd
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	abcc
  Additional Information 2:	abcc8f7853b48d9807d6d51eb1fa5df9
  Additional Information 3:	abcc
  Additional Information 4:	abcc8f7853b48d9807d6d51eb1fa5df9

**Comment by eranif** [comment]
Is this consistent? I am unable to reproduce this here.
Can you attach gdb to CodeLite and paste the backtrace here?

**Comment by eranif** [comment]
No response
