### ISSUE TITLE
Bug: [13.0.2] Seems like intermediate path ignored

### ISSUE THREAD

**Issue by iHardRock** [eranif/codelite#2340]
Intermediate path settings in project have no effect. Build always run in "build-$(ConfigurationName)" folder in project folder. This is critical for custom build settings...

**Comment by iHardRock** [comment]
Need to manually set "Classic (DEPRECATED)" makefile generator.
In CMake, Default or GNU one step - Intermediate folder path completly ignored

**Comment by eranif** [comment]
This was fixed last week. https://github.com/eranif/codelite/commit/9d8b5af10f0e49bd1859d84e8d26836135b81b66
