### ISSUE TITLE
Codelite not oppening on Windows 10

### ISSUE THREAD

**Issue by gstocksd** [eranif/codelite#2341]
Over the past month I have been running Codelite on my PC which is a 64bit system so I had the stable 64bit release of Codelite. The problem occurred today when I attempted to open up Codelite and the icon flashed but did not open. Here is a list of things I did to troubleshoot: 

1. Turn off the PC and unplug from the wall so that there was no current going through

2. Deleted all files that had to do with Codelite and uninstalled the program. I attempted to reinstall both the weekly code and the stable release but neither generated results

3. Tried to run as an administrator but it still wouldn't open 

4. Opened task controller and process to try and kill the program but it was not on the list. When I double click the shortcut occasionally Codelite will show up in the list but then disappear. 

I have nothing left to try that I know of. Please help me if you can!

**Comment by eranif** [comment]
Usually deleting the folder `%appdata%\CodeLite` does the trick

**Comment by gstocksd** [comment]
Is there an easy way of getting to that folder? like would I just put that into the search at the bottom left?

**Comment by eranif** [comment]
Just type that in the address bar of Windows File Explorer

**Comment by gstocksd** [comment]
The answer to my above question is yes XD. Well it worked thank you very much! Do you know if this is something that I will have to do frequently or just if the problem occurs?

**Comment by eranif** [comment]
No, some of the config files got corrupted

**Comment by PoojaRSawant** [comment]
I am facing same problem, I am not able to find %appdata%\CodeLite this folder. So please tell me how to find this folder.

**Comment by eranif** [comment]
https://www.howtogeek.com/318177/what-is-the-appdata-folder-in-windows/

**Comment by PoojaRSawant** [comment]
Thank you

**Comment by bmirtsching** [comment]
I have searched my C: drive for this appdata folder by searching the entire disk, hidden items also displaying.  Nothing found. Any way to locate this file?

**Comment by eranif** [comment]
type in the file explorer address bar:
```
%appdata%\codelite
```
