### ISSUE TITLE
Feature request: A single debug/release cmakefile.txt, managed by CodeLite

### ISSUE THREAD

**Issue by davidwed** [eranif/codelite#2342]
Currently only one CMakeFile.txt is generated for release or debug of Codelite. 

It would be nice if CodeLite could only generate a single CMakeFile.txt with the required build information for release/debug.

Otherwise, for an automatic build of debug/release, Codelite must always be installed on the build system.

**Comment by eranif** [comment]
Sounds like a good idea

**Comment by davidwed** [comment]
Bump
