### ISSUE TITLE
Codelite changes build directory

### ISSUE THREAD

**Issue by DustCommander** [eranif/codelite#2343]
Hello,

I recently upgragded to the latest Codelite (version 13.0.2) from one a year or two old. I am building PC applications using TDM64.

When I open my projects, they no longer run the built application. 

It turns out that the build directories are moved. Running the application from Codelite still runs the application from the old directory (a previous build.. If there are multiple projects in the same work space, it puts all the executable in the same bin directory.

The before and after make files are attached.

[NewMakeFile.txt](https://github.com/eranif/codelite/files/3639729/NewMakeFile.txt)
[OldMakeFile.txt](https://github.com/eranif/codelite/files/3639730/OldMakeFile.txt)

**Comment by eranif** [comment]
This was fixed. And will be released today
