### ISSUE TITLE
Can not pause t running console program after upgrade

### ISSUE THREAD

**Issue by DustCommander** [eranif/codelite#2344]
I have an old console program that used to run and pause before updating Codelite. I undated again yesterday and the issue still exists. The application does run. I can stop it using a getch() command. The pause after execution box is checked. I have cleaned the project.

If I create a new console application, It does pause correctly.

**Comment by eranif** [comment]
Please provide more details:

1. Steps to reproduce
2. OS version
3. CodeLite version

**Comment by DustCommander** [comment]
Hi Eran,

Sorry for the late reply. I finally found the root issue. On Windows 10
64bit, Codelite version 13.0.3, TDM64 compiler, the console window does not
stay open if the return code in main is not 0.
Here's the test code:

#include <stdio.h>

int main(int argc, char **argv)
{
printf("hello world\n");
return 0; //console window stays open
//return -1; //console window closes
}

Best regards,
Steve
