### ISSUE TITLE
[Linux] CodeLite build error : hb.h not found

### ISSUE THREAD

**Issue by eric-jcb** [eranif/codelite#2346]
It seems there is a change in pango and at 18% stage of make command there is an error ; that pango complains about hb.h was not found. but harfbuzz is installed
```harfbuzz-2.6.1-1```

```
[ 18%] Building CXX object CodeLite/CMakeFiles/libcodelite.dir/UnixProcess.cpp.o
[ 18%] Building CXX object CodeLite/CMakeFiles/libcodelite.dir/XmlLexer.cpp.o
[ 18%] Building CXX object CodeLite/CMakeFiles/libcodelite.dir/ZombieReaperPOSIX.cpp.o
[ 18%] Building CXX object CodeLite/CMakeFiles/libcodelite.dir/archive.cpp.o
[ 18%] Building CXX object CodeLite/CMakeFiles/libcodelite.dir/asyncprocess.cpp.o
[ 18%] Building CXX object CodeLite/CMakeFiles/libcodelite.dir/cJSON.cpp.o
[ 18%] Building CXX object CodeLite/CMakeFiles/libcodelite.dir/clAnagram.cpp.o
[ 18%] Building CXX object CodeLite/CMakeFiles/libcodelite.dir/clBitmap.cpp.o
In file included from /usr/include/pango-1.0/pango/pango-font.h:25,
                 from /usr/include/pango-1.0/pango/pango-attributes.h:25,
                 from /usr/include/pango-1.0/pango/pango.h:25,
                 from /usr/include/gtk-2.0/gdk/gdktypes.h:37,
                 from /usr/include/gtk-2.0/gdk/gdkscreen.h:32,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from /home/admin/Downloads/NT/codelite/CodeLite/clBitmap.cpp:7:
/usr/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: hb.h: No such file or directory
   28 | #include <hb.h>
      |          ^~~~~~
compilation terminated.
make[2]: *** [CodeLite/CMakeFiles/libcodelite.dir/build.make:1181: CodeLite/CMakeFiles/libcodelite.dir/clBitmap.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:384: CodeLite/CMakeFiles/libcodelite.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
<<latest archlinux.>>

**Comment by eranif** [comment]
Which version? which OS? and which GTK version?

**Comment by eric-jcb** [comment]
```5.3.1-arch1-1-ARCH #1```
```codelite-git HEAD```
```gtk2   2.24.32-1```
```gtk3   1:3.24.11-1```

**Comment by eranif** [comment]
A quick google search gives this:
https://bugs.archlinux.org/task/63460

and also this:

https://github.com/eiskaltdcpp/eiskaltdcpp/issues/413

The bug does not seems to be related to CodeLite specific. From the second bug report, I can see it is cmake related. Can you try and apply the fix suggested?

**Comment by eric-jcb** [comment]
Sure; What exactly should I do? which part of the source code should I change?

**Comment by eranif** [comment]
scroll down https://github.com/eiskaltdcpp/eiskaltdcpp/issues/413

you will see a patch to `FindGTK.cmake` try it

**Comment by eric-jcb** [comment]
It seems to build atm. (at 22% right now).
Q1. Could I build codelite againts gtk3? how?
Q2. Why should I tweak my system internals to build a package? Ss it codelite or is it pango? 
Where is the problem? (pleas explain!)

**Comment by eranif** [comment]
1. You need to build wxWidgets against GTK3 (make sure that the `wx-config` that is used from the command line, prints the GTK3 libraries and include paths)
2. It seems that since pango 1.44 a change was done that requires `hb.h` but this was not fixed in `cmake` so it does not include the location of `hb.h` to the build
