### ISSUE TITLE
Installer for 13.0.3 on Win/x64 skips path update

### ISSUE THREAD

**Issue by luc0x61** [eranif/codelite#2349]
I just installed **directly** version 13.0.3 on Windows/x64 and had always the message 
 _don't know how to make ''_
when trying to build/rebuild any simple/new project. Ended up it couldn't find "makedir.exe", as it hadn't the PATH updated to Codelite install directory.
Then I tried uninstalling, installing first version 13.0.0 and then updating again to 13.0.3: now it works. So the former modifies correctly PATH while the latest just uses what's already there...

This is a very **quick** test I made, hope this helps.

Luc0x61

**Comment by eranif** [comment]
The installer is identical and hasn't been changed since years now.
The error: "I don't know how to make" means you have problem with your MinGW installation or you ran CodeLite from some MSYS path or something
