### ISSUE TITLE
CodeLite Compiling Issue

### ISSUE THREAD

**Issue by DmLopez16** [eranif/codelite#2353]
Hello, I am receiving this error anytime I try to run a program:

C:\WINDOWS\system32\cmd.exe /C C:/TDM-GCC-64/bin/mingw32-make.exe -j4 SHELL=cmd.exe -e -f  Makefile
"----------Building project:[ TEST - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'C:/Users/xboxp/Documents/TEST/TEST'
C:/TDM-GCC-64/bin/g++.exe -o Debug/TEST @"TEST.txt" -L.
g++.exe: error: Debug/main.cpp.o: No such file or directory
mingw32-make.exe[1]: *** [Debug/TEST] Error 1
TEST.mk:76: recipe for target 'Debug/TEST' failed
mingw32-make.exe[1]: Leaving directory 'C:/Users/xboxp/Documents/TEST/TEST'
mingw32-make.exe: *** [All] Error 2
Makefile:4: recipe for target 'All' failed
====1 errors, 0 warnings====

I am using CodeLite(13.0.3) for my principles of C++ class. What are the steps I can take to relieve this?
I've uninstalled and re-installed according to instructions from my class instructor, but that hasn't fixed or changed anything.
I am using the TDM-GCC MinGW Compiler from https://sourceforge.net/projects/tdm-gcc/

It is frustrating that CodeLite won't even run the "Hello World" program, and I'm falling behind in class. Thank you in advanced.

**Comment by eranif** [comment]
From what I can see, CodeLite fails to create the `Debug` folder
What happens when you switch the build system?
`Right click on the project -> project settings -> General tab -> Makefile Generator`
and select `CodeLite Make Generator`

Try and build again, does it help?

**Comment by DmLopez16** [comment]
I still receive the same issue on the build log.

**Comment by eranif** [comment]
Can you please paste the complete build log?

**Comment by eranif** [comment]
Can you run this from the command line?
Open a CMD terminal and do this:

```bat
cd C:/Users/xboxp/Documents/TEST
C:\WINDOWS\system32\cmd.exe /C C:/TDM-GCC-64/bin/mingw32-make.exe -j4 SHELL=cmd.exe -e -f Makefile
```

**Comment by DmLopez16** [comment]
[image: image.png]
This is what I get.

**Comment by eranif** [comment]
The image is not attached
