### ISSUE TITLE
Add python 

### ISSUE THREAD

**Issue by talley** [eranif/codelite#2354]
Add python support to CodeLite

**Comment by eranif** [comment]
What does it mean to "add python support" ?
Atm, you can have code completion + syntax highlight. I am guessing that using the new File System Workspace (new in CodeLite 13.0.4) should provide the full functionality you need

**Comment by talley** [comment]
I never tried python on it.I will try and i will let you know.I just to be able to create python project and do python stuffs

**Comment by eranif** [comment]
You will get python code completion from the `Language Server` plugin. You just need to enable it
https://wiki.codelite.org/pmwiki.php/Main/LanguageServer

**Comment by talley** [comment]
I enabled Language Server from plugins.It has only basic syntax highlighting no code completion

**Comment by eranif** [comment]
You need to enable the `python` to do that. This is done by installing python language server and configure it in CodeLite

**Comment by kenneth-Q** [comment]
I think he means python workspace and project type support.
Python type of workspace and project could use without make, g++, cc commands.
I hope it could be change to:

1. change run command to python [filename]
2. without make, link, gdb
3. create new workspace and project type call python
4. any suitable function for python :)
That could be fun.

I found the amazing software support language server protocol. So it could support most language, but most settings is for c/c++ only. That is frustrating.

Having a nice programming ;P

**Comment by Dreamoochy** [comment]
Sorry for stupid question. How can I configure CodeLite to debug and run python programs?

**Comment by eranif** [comment]
You did not mention your platform, but on Windows, you can do it by installing python debugger.
https://docs.codelite.org/getting_started/windows/#python

The debugger is called `debugpy`, you can then simply make it the active debugger in your file system workspace:
https://docs.codelite.org/workspaces/file_system/

**Comment by Dreamoochy** [comment]
> The debugger is called `debugpy`, you can then simply make it the active debugger in your file system workspace

1. Maybe I'm tired, but I see no way to activate it for **Workspace**. Only for the current project. But to create a project I have to create a new compiler for python (or use some of existing ones).
2. I've created 'dummy' compiler and changed debugger to `debugpy`. Now I'am able to debug, but only partially. E.g. when I debug `print()`, debugging immediately terminates.
3. How can I simply run the code without debug?

My OS is Win11

**Comment by eranif** [comment]
"File system workspace" has no projects...
If you have "projects" than you are using the wrong type of workspace.

You should create a simple "File System Workspace"

https://docs.codelite.org/workspaces/file_system/

**Comment by Dreamoochy** [comment]
Oh, now I see. Sorry. But the questions remain:
1. Is it possible to simply run the code without debug? Like for c++ or rust projects.
2. How can I see the output? Where does the output of `print()` goes?
