### ISSUE TITLE
Find, Find Prev buttons work incorrectly.

### ISSUE THREAD

**Issue by gennadiy1g** [eranif/codelite#2355]
Find, Find Prev buttons work incorrectly if Highlight Matches button is activated: 
- many matches are skipped;
- current match is not highlighted with a different color.

Enter, Shift-Enter work fine when the cursor is in the text search field regardless whether Highlight Matches button is activated:
- matches are not skipped;
- current match is highlighted with a different color.

If this is by design, then I cannot understand the idea behind such design.

This issue existed since I started to use CodeLite on Windows about a year ago.

CodeLite 13.04 (codelite-amd64-13.0.4.exe)

Thank you,
Gennadiy

**Comment by eranif** [comment]
How do I reproduce this?
I just ran a test and it always working for me

**Comment by eranif** [comment]
Ping?

**Comment by gennadiy1g** [comment]
I, probably, replied to the wrong address.

On Tue, 2019-10-15 at 15:50 -0400, Gennadiy wrote:
> Please try the following steps.
> - Search for some sequence of letters.
> - Make sure that (all matches are surrounded by boxes and search
> bookmarks are visible) by using Highlight matches button, if
> necessary.
> - Put the cursor in the search text box.
> - Press Enter, Shift-Enter - works beautifully, the current match is
> highlighted with a different colour, Enter/Shift-Enter jumps to the
> next/previous match.
> - Click Find, Find Prev - the current match is not highlighted any
> more, Find/Find Prev does nothing.
> --
> Gennadiy <gennadiy1g@gmx.com>
> On Tue, 2019-10-15 at 11:06 -0700, Eran Ifrah wrote:
> > How do I reproduce this?
> >
> > I just ran a test and it always working for me
> >
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> >
> > [
> > {
> > "@context": "http://schema.org",
> > "@type": "EmailMessage",
> > "potentialAction": {
> > "@type": "ViewAction",
> > "target": "
> > https://github.com/eranif/codelite/issues/2355?email_source=notifications\u0026email_token=ANHFJPSNVURRFZUEISQEMV3QOYBCPA5CNFSM4JBAB3C2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBJWILA#issuecomment-542336044
> > ",
> > "url": "
> > https://github.com/eranif/codelite/issues/2355?email_source=notifications\u0026email_token=ANHFJPSNVURRFZUEISQEMV3QOYBCPA5CNFSM4JBAB3C2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBJWILA#issuecomment-542336044
> > ",
> > "name": "View Issue"
> > },
> > "description": "View this Issue on GitHub",
> > "publisher": {
> > "@type": "Organization",
> > "name": "GitHub",
> > "url": "https://github.com"
> > }
> > }
> > ]
--
Gennadiy <gennadiy1g@gmx.com>
