### ISSUE TITLE
Getter and setter definition/implementation files

### ISSUE THREAD

**Issue by henrique2d** [eranif/codelite#2356]
It would be great if the getter and setter generator could create a definition in the ".h" file(public) and the implementation in the ".cpp" source file

**Comment by eranif** [comment]
Isn't it how it works today !? I know I am using it ..

**Comment by henrique2d** [comment]
Maybe it could be an option, to do all in a single file or define and implement differently, but still, it generates in the same place, like when i select a variable in private, it generates in private(under the variable)
