### ISSUE TITLE
Cannot set any paths for tools (PHP, Source Code Formatter)

### ISSUE THREAD

**Issue by AJenbo** [eranif/codelite#2357]
It used to be that CodeLite would auto discover tools, but now I can't even set the path manually:

![image](https://user-images.githubusercontent.com/204594/66906245-a5e20080-f007-11e9-9aa7-8f9a422c5499.png)

Browsing works fine, and the path appears in the input, but after clicking OK the setting is discarded. This happens in 13.0.3 and 13.0.4 on Ubuntu 18.04

```
$ which php
/usr/bin/php
```

**Comment by AJenbo** [comment]
This is probably relevant `.codelite/config/php-general.conf`:
```
[{
  "m_phpExe": "",
  "m_errorReporting": "E_ALL & ~E_NOTICE",
  "m_includePaths": []
 }, {
  "m_phpExe": "/usr/bin/php",
  "m_errorReporting": "E_ALL & ~E_NOTICE",
  "m_includePaths": []
 }, {
  "m_phpExe": "/usr/bin/php",
  "m_errorReporting": "E_ALL & ~E_NOTICE",
  "m_includePaths": []
 }, {
  "m_phpExe": "/usr/bin/php",
  "m_errorReporting": "E_ALL & ~E_NOTICE",
  "m_includePaths": []
 }, {
  "m_phpExe": "/usr/bin/php",
  "m_errorReporting": "E_ALL & ~E_NOTICE",
  "m_includePaths": []
 }, {
  "m_phpExe": "/home/ajenbo/.codelite/tags",
  "m_errorReporting": "E_ALL & ~E_NOTICE",
  "m_includePaths": []
 }, {
  "m_phpExe": "/usr/bin/php",
  "m_errorReporting": "E_ALL & ~E_NOTICE",
  "m_includePaths": []
 }]
```

**Comment by AJenbo** [comment]
Changing the file content to `{}` works as a workaround, but basically any one that installs CodeLite from scratch will be unable to configure it for PHP usage.

**Comment by AJenbo** [comment]
This also affects phplint.conf

**Comment by AJenbo** [comment]
Thanks :D

**Comment by eranif** [comment]
I still need you to confirm this :)
Works for me though ...

**Comment by AJenbo** [comment]
I'll race you!

**Comment by AJenbo** [comment]
I can confirm that it work, but only if you delete the broken config first.

**Comment by eranif** [comment]
Even with this commit https://github.com/eranif/codelite/commit/6ff1798dc636dedf313296518b3e01ddaccba402 ?

**Comment by AJenbo** [comment]
Yes
