### ISSUE TITLE
SVN Commit dialogue window size and layout unusable after updating 13.0.2 -> 13.0.4

### ISSUE THREAD

**Issue by Kanimies** [eranif/codelite#2364]
The commit window opens too small / with layout hiding most of it's functions (comment field, Diff window) and only shows Modified Paths -window. Doesn't remember the window layout after resizing so has to be manually adjusted for every commit to be usable which is pretty frustrating.
![svn commit](https://user-images.githubusercontent.com/7421922/67204941-47f25600-f417-11e9-875a-eb4d15c7dae2.png)

**Comment by eranif** [comment]
Closed with this commit: de9aef
