### ISSUE TITLE
Multi cursor pasting no longer working

### ISSUE THREAD

**Issue by AJenbo** [eranif/codelite#2366]
When trying to paste to multiple lines using multi cursors, only the last cursor is actually pasted to.

Select multiple lines, hit ctrl+v
![image](https://user-images.githubusercontent.com/204594/67333186-6db75200-f520-11e9-9dc6-19717ecae098.png)

Expected result:
![image](https://user-images.githubusercontent.com/204594/67333293-9b040000-f520-11e9-9466-e3520c0eef75.png)
(the text is inserted at every cursor position)

Actual result:
![image](https://user-images.githubusercontent.com/204594/67333252-8a538a00-f520-11e9-94b4-c708348d0e3b.png)
The text is only inserted at the last cursor position and the other cursors are dropped

This used to work, around version 12.0 I believe

**Comment by eranif** [comment]
It's working. Tested it on a local build Ubuntu.
The problem is that you are using your own build with an older version of wxStyledTextCtrl (.i.e. an older version of wxWidgets)

**Comment by AJenbo** [comment]
Ok, in that case, I will be looking forward to the next weekly build :P

**Comment by eranif** [comment]
Better yet, why don't you build your own wxWidgets? it's really easy...

**Comment by AJenbo** [comment]
It takes time, something I already have to little of 🙂
