### ISSUE TITLE
In the C/C++ editor the name of the function under the curser is not shown

### ISSUE THREAD

**Issue by franku** [eranif/codelite#2367]
When I edit in a C/C++ file in the middle of a long function whose code overlaps the screen then I cannot see the function's name. 

In a previous version of codelite the name (and signature) of the function in scope was displayed below the editor. This is very helpful when scrolling down a file while refactoring or searching code.

However, this disappeared at least with version 13.0.5. Is there a way to re-enable this helpful feature?

**Comment by eranif** [comment]
This is still there.
You can enable it from View -> Navigation bar

**Comment by franku** [comment]
Was blind, thanks !
