### ISSUE TITLE
exact match in Find Resource should sort first

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#2368]
when doing ctrl-shift-R (search by resource), if there is an exact match found, that match should sort first

(Noticed when I had one file that I was looking for, and a bunch of other files had that same filename as a sub-string)

thanks

**Comment by eranif** [comment]
IIRC, the current behavior is that if there is an exact match - it is selected

**Comment by grandinj** [comment]
thanks, will try again tonight

**Comment by grandinj** [comment]
you are correct

**Comment by grandinj** [comment]
Hmm, no, tested again and it's not quite working right.

This is on OSX, running Codelite 13.0.4

I have two files 
   urlobj.cxx
and
  test_urlobj.cxx
of interest.

If I search for urlobj.cxx, it displays the above two matches, but does not select either one of them

**Comment by eranif** [comment]
This is strange as it does work for me...
![or](https://user-images.githubusercontent.com/3677711/68801705-43f7d380-0665-11ea-995c-b6310cccc92f.png)

**Comment by grandinj** [comment]
Weird. Not worth worrying about
