### ISSUE TITLE
Hidden Workspace view and not able to unhide it

### ISSUE THREAD

**Issue by heheksfi** [eranif/codelite#2373]
Working on latest OS X version. I was poking around the IDE and I hid the tabs in the workspace view panel on the side but I can't get them to appear. I can't even use the IDE at this point.

Here is what I see:

<img width="1643" alt="Screen Shot 2019-10-29 at 9 47 24 AM" src="https://user-images.githubusercontent.com/57141757/67772827-21dd3f00-fa31-11e9-9be1-9f0075ebd28e.png">

Tried:
- delete & re-install
- delete & new workspace
- reloading workspace
- delete & reload workspace
- restore default layout
- restart computer
- downloading earlier version of codelite
- look around library for associated files

**Comment by eranif** [comment]
Try this:

From the main menu: Perspective -> Restore default layout
If this does not work:

- Close CodeLite
- Delete the folder `/Users/<NAME>/Library/Application Support/codelite`
- Start CodeLite
