### ISSUE TITLE
[PHP] Inner heredocs loses html highlighting

### ISSUE THREAD

**Issue by tfryman** [eranif/codelite#2374]
Hopefully I didn't overlook a setting for this, but html will lose it's color highlighting if put inside a heredoc. It would be very nice to have:

```
echo <<<HTML
<!-- put HTML here and it will have syntax highlighting -->
HTML;
```

It seems this works in other editors: https://stackoverflow.com/a/21343916

**Comment by eranif** [comment]
This is a limitation of the editor control (`Scintilla`) this is not supported
