### ISSUE TITLE
hover tooltip function info, any way to trigger or show?

### ISSUE THREAD

**Issue by xekon** [eranif/codelite#2378]
During code completion, for example while typing a function name, you can see the variable info associated with that function such as the pointer **AActor*** :
![screenshot_27](https://user-images.githubusercontent.com/106644/68253916-0b5d5780-ffde-11e9-8959-8530c778c816.png)

I have found that if the popup hides, I can delete some of the function such as GetOwner(), if I delete the parenthesis () so that it is just GetOwner then hold ctrl and press space I can see that popup again.

What I am wondering if there is a way to see this info in a tooltip, or perhaps a way to trigger that popup without deleting some of the function. I know in visual studio you can hover over a function to see this info:
![screenshot_26](https://user-images.githubusercontent.com/106644/68253921-0ef0de80-ffde-11e9-89f0-b28485dc834f.png)

I am not using Visual Studio myself. I am actually following some tutorials for Unreal Engine using CodeLite under Ubuntu, and while doing so noticed that all they had to do was hover over the function to see that info.

That is when I started investigating and found that I could hold ctrl + space to view the popup so long as I deleted the parenthese and placed my cursor at the function name.

Any Help Appreciated.

EDIT: I just found that if I place the cursor at the end of the function name but before the parenthesis and press ctrl+space that it opens the popup, so I am pretty happy about that.

![screenshot_28](https://user-images.githubusercontent.com/106644/68254768-54161000-ffe0-11e9-8af7-df43fb26c271.png)

I will wait to close this though incase there is also a way to show the info in a tooltip that I am unaware of.

**Comment by eranif** [comment]
`Settings->Code completion->General->Display type info tooltip`

**Comment by xekon** [comment]
Thank you so much for the reply! Loving using Codelite, its been a real treat to use so far.
