### ISSUE TITLE
ubuntu menu corruption and/or greyed out 

### ISSUE THREAD

**Issue by NutsAndBolts1701** [eranif/codelite#2379]
I'm having problems with the drop-down menus in latest version 13.0.  
I had an older version installed and it worked just fine.

Issue:
Many of the menu selections are always grayed out.
File->close workspace
Build-><all of them>

However, I can right click items in the workspace pane and use them there.  I can also use the hotkeys (F7 to build etc). 

I've googled around and found several refs to reset perspective, no joy.
I tried completely removing/purging codelite and re-installing / still not working.

codelite installed using apt following method shown on codelite.org 

What am I doing wrong?
Below find versions and screen caps

Thanks,
-Roger

Ubuntu 16.04 LTS
Codelite 13.0 (new download 11/6/2019)

![cl-001](https://user-images.githubusercontent.com/20648693/68322844-6ac07380-0081-11ea-9a4a-60b8d6e2d7f0.png)
![cl-002](https://user-images.githubusercontent.com/20648693/68322845-6ac07380-0081-11ea-8953-05ea36cab949.png)

**Comment by eranif** [comment]
Have you tried changing the DE?
I think its an issue with the DE.  
* Also, which version of Ubuntu are you using? 
* Have you tried a weekly build?

**Comment by NutsAndBolts1701** [comment]
Hi,

Ubutnu 16.04.06 LTS (all updates installed today)
Have not tried the weekly but will do that now.

Any recommends on DE?

Thanks,
-Roger

**Comment by eranif** [comment]
Just for the quick test, I would install lxde, its the lightest of them all. I personally really like it
Also, using GNOME default on 18.04 does not show this bug

**Comment by NutsAndBolts1701** [comment]
Hi,

Lxde fixed it up.
Now I get to figure out which one I really want to use now 😊
Thanks a ton for the amazing quick response!
-Rog
