### ISSUE TITLE
Fedora31 cannot find hb.h

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#2380]
Just updated to Fedora31, and I'm seeing this:

[  4%] Building CXX object CodeLite/CMakeFiles/libcodelite.dir/clBitmap.cpp.o
In file included from /usr/include/pango-1.0/pango/pango-font.h:25,
                 from /usr/include/pango-1.0/pango/pango-attributes.h:25,
                 from /usr/include/pango-1.0/pango/pango.h:25,
                 from /usr/include/gtk-3.0/gdk/gdktypes.h:35,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from /home/noel/codelite/CodeLite/clBitmap.cpp:7:
/usr/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: hb.h: No such file or directory
   28 | #include <hb.h>
      |          ^~~~~~

which looks very similar to 
   https://bugzilla.redhat.com/show_bug.cgi?id=1741077

which seems to indicate that Codelite needs some cmake fix?

**Comment by alukreis** [comment]
Hi,

This is also an issue in Arch Linux/Manjaro. The current workaround I know of is to add the harfbuzz include directory via the CmakeLists.txt file in the root of the repo code. If you add it to the lines that read:

`            include_directories(${GTK3_INCLUDE_DIRS})`

lines 259 and 266, then it should compile up properly.

**Comment by alukreis** [comment]
In arch linux/Manjaro the harfbuzz include is in /usr/include/harfbuzz

**Comment by dghart** [comment]
This is now fixed in #4db88158
