### ISSUE TITLE
[Feature]  Add path builder. 

### ISSUE THREAD

**Issue by genusistimelord** [eranif/codelite#2385]
Please add the capability to have a path builder which can be used to get and see all the current path variables within Codelite and to build a path with them for us with. if not a path builder maybe a button to see a list of current path arguments and what they are currently set as or too. 

Intermediate folder
Output file
Executable/Run
Working Directory 
ETC..

**Comment by eranif** [comment]
Assuming C++ workspace.
Right click on a project and then click the `Help` button

**Comment by genusistimelord** [comment]
ahh thank you and sorry for the late reply back. This is what i see?
![image](https://user-images.githubusercontent.com/1034709/70261215-f9e3a880-175f-11ea-979e-fb225dc917c1.png)

**Comment by genusistimelord** [comment]
Help button is within the project properties. 
![image](https://user-images.githubusercontent.com/1034709/71375532-8f6a9f00-258c-11ea-8f31-e8dc2c0e0c5d.png)
