### ISSUE TITLE
Pressing ENTER in dialogs with cursor in multiline edit fields activates default/OK button

### ISSUE THREAD

**Issue by audrius-u** [eranif/codelite#2389]
When editing text in multiline edit boxes within Project Settings dialog (and some other dialogues) and pressing Enter, the dialog box closes with default button (usually [OK] button) in addition to inserting a new line in edit box.

Expected behavior: [Enter] key should only insert a new line at cursor position and should not close the dialog. Actual behavior: Newline is inserted and dialog is closed with default dialog button.

Examples of affected dialog boxes and text fields - Project settings->Environment->Additional environment variables, or Plugins menu->Source Code Formatter->Options->C++->AStyle->Custom user settings.

CL v13.0.5 x64 on Win10, default settings.

**Comment by eranif** [comment]
This was fixed with the release 13.0.6 (was released today)
