### ISSUE TITLE
Debugger not working

### ISSUE THREAD

**Issue by JacktheRipperRM** [eranif/codelite#2394]
The console for debugger is getting closed just after it started.
Please help.
![image](https://user-images.githubusercontent.com/43293317/70180041-8732e880-16df-11ea-878a-a0d27dc62b07.png)

**Comment by JacktheRipperRM** [comment]
Ver. 13.0.0
Compiler : MinGw 64bit

**Comment by dghart** [comment]
This doesn't sound like a bug. I suggest you ask for help on the [CodeLite forum](https://codelite.org/forum/), after first searching it for similar questions.
