### ISSUE TITLE
The completion system doesn't work without saving the file

### ISSUE THREAD

**Issue by cata0309** [eranif/codelite#2396]
Hello !
I must say that the completion system is doing it's work but I noticed a drawback ! I must save the file after I made the changes to see code completions. Is there any workaround to fix this ? I really do not want to save my files automatically !

**Comment by eranif** [comment]
In more recent versions of CodeLite, the completion system is using Language Server.
Which does not need to save the file for showing completions. You can configure it as described here:
https://wiki.codelite.org/pmwiki.php/Main/LanguageServer

**Comment by cata0309** [comment]
Not much information about how to configure clangd, like arguments, what should I choose?

**Comment by cata0309** [comment]
![image](https://user-images.githubusercontent.com/35623921/70268053-5d91c400-17a8-11ea-8262-1626609cfe35.png)

Is it ok ?

**Comment by eranif** [comment]
Initiate a single build (one time) - this will trigger the required files `compile_flags.txt`

**Comment by cata0309** [comment]
It's not showing any completion, not even the basic ones like `using namespace` or `struct`. Why do you think it's not working?

**Comment by eranif** [comment]
do you have `clangd` installed?

**Comment by cata0309** [comment]
Yes
![image](https://user-images.githubusercontent.com/35623921/70268833-e3fad580-17a9-11ea-8ee0-a22e3b6c79b8.png)

**Comment by eranif** [comment]
which version is this?

**Comment by cata0309** [comment]
clangd version 9.0.0 (tags/RELEASE_900/final)

**Comment by eranif** [comment]
can you run `ps -ef|grep clangd` and see if you have one running?

**Comment by cata0309** [comment]
Yes, it's running
![image](https://user-images.githubusercontent.com/35623921/70269052-47850300-17aa-11ea-803b-ca7686f15dbf.png)

**Comment by cata0309** [comment]
When I click Ctrl-space(some keyboard shortcut that most of the IDE`s use for manual request for completion) it shows me this in the status bar
![image](https://user-images.githubusercontent.com/35623921/70269142-77cca180-17aa-11ea-8894-7ad8336e16eb.png)

**Comment by eranif** [comment]
enable log `settings->preferences->misc->log` and set log verbosity to `Debug`
then from a terminal:
`tail -f ~/.codelite/codelite.log&`
try to code complete something again

**Comment by cata0309** [comment]
![image](https://user-images.githubusercontent.com/35623921/70269438-0e995e00-17ab-11ea-9702-5afce59a2099.png)
It shows me something but there are not in codelite

**Comment by eranif** [comment]
Can you try and code complete some code?
Also, which version of CodeLite is this?

**Comment by cata0309** [comment]
![image](https://user-images.githubusercontent.com/35623921/70270024-245b5300-17ac-11ea-922c-b9889a830ff4.png)

Still nothing in the editor, only in the terminal

**Comment by eranif** [comment]
which version of CodeLite is this?

**Comment by cata0309** [comment]
CodeLite IDE v13.0.0

**Comment by eranif** [comment]
OK. This version has a bug in handling latest `clangd` output
You can either:
- Add this to the `clangd` command line: `-header-insertion-decorators=0`, so your `clangd` command should be now: `/usr/bin/clangd -header-insertion-decorators=0`
- Update to the latest CodeLite 13.0.7

**Comment by eranif** [comment]
Without this directory (`-header-insertion-decorators=0`) `clangd` sends back binary output which is not handled properly by CodeLite... this was fixed in latest CodeLite

**Comment by cata0309** [comment]
It works now but only with primitive types. If I create a struct it's name is not showed in completion system if I do not save the file

**Comment by eranif** [comment]
really? strange, CodeLite sends to clangd the modified buffer **before** you save it...
Let me check this here

**Comment by eranif** [comment]
Seems to work here without saving file

**Comment by cata0309** [comment]
I will try build codelite from source

**Comment by eranif** [comment]
which distro are you using?

**Comment by cata0309** [comment]
I will come with updates next week since I am not having great internet speed until Monday.
