### ISSUE TITLE
CodeLite won't be able to tag prase a file in my workspace, only if I use version 12.0.0 or below it

### ISSUE THREAD

**Issue by TiManGames** [eranif/codelite#2397]
I use version 13.0.7

My workspace is non-code, and most of my code api is coming from a single file. This file does not represent a valid c++ code, but rather a compilation of all the classes and methods I want to use, in a c++ style. 

I uploaded here the file codelite won't be able to parse. It does work perfectly fine in 12.0.0 or versions below it. 

[hps_api.zip](https://github.com/eranif/codelite/files/3932328/hps_api.zip)

Have you updated the tag parser in version 13.0.0? Otherwise I can't see why it won't work in newer versions.

**Comment by eranif** [comment]
The parser was not updated. However, I suspect that the reason is the file extension `hps`
If you will rename it to `hpp` or `h` it will work

**Comment by TiManGames** [comment]
> The parser was not updated. However, I suspect that the reason is the file extension `hps`
> If you will rename it to `hpp` or `h` it will work

It works! Thanks. Any reason it will work only if the extension is  `h` in the newer version?

**Comment by eranif** [comment]
The parser now accepts only C/C++ headers/sources and it identifies them by the file extension or patterns found in the file content. You file did not comply with any of the rules. So changing it to `h` fixes that barrier
