### ISSUE TITLE
Code completion for types declared with "using" (c++)

### ISSUE THREAD

**Issue by Finemechanic** [eranif/codelite#2404]
Codelite 13.0.0 for Windows and MinGW GCC.

It looks like code completion doesn't work for types declared with "using" keyword. In particular it doesn't recognize std::string_view, but recognizes std::basic_string_view<char>.

To demontrate try the following:

using mystring = std::string;
std::string s1;
mystring s2;

s1. - code completion works
s2. - code completion doesn't work

**Comment by eranif** [comment]
Enable Language Server Completion with `clangd` and it will work
