### ISSUE TITLE
A way to start CodeLite in full screen mode

### ISSUE THREAD

**Issue by DaGiHu** [eranif/codelite#2405]
I'm fond of clean interfaces and I love CodeLite. I switched to it after trying CodeBlocks, NetBeans and other environments.

I really like how CodeLite looks in full screen mode (ALT-M shortcut) with no the title bar. I've searched for a way to activate this as default but I guess there's no way to do this in CodeLite.

I'd love to see inside Preferences > Windows & Tabs an option to start in full screen mode.

Thanks in advance.

**Comment by KatiePlayz** [comment]
now how do i exit the fullscreen mode

**Comment by dghart** [comment]
> now how do i exit the fullscreen mode

As that is a question, not a bug-report, it should have been asked on the[ CodeLite forum](https://codelite.org/forum/).

You don't mention your CodeLite version (or your platform) but, at least for the current git, one answer is: press ESC.

**Comment by prawinrajan** [comment]
> now how do i exit the fullscreen mode

You can use Alt + M in windows to exit from full screen mode
