### ISSUE TITLE
Autocompletion problem 

### ISSUE THREAD

**Issue by sergioKon** [eranif/codelite#2406]
Hi I am in 13.0.7 under Mint-16, and autocomplete works, sometimes only ,
I write pri , expecting to be complete to prinf but it  does't happend , when I type pri it'hint complete to private. How solve it ?

**Comment by eranif** [comment]
I suggest that you configure language server (`clangd` in your case)
https://wiki.codelite.org/pmwiki.php/Main/LanguageServer
