### ISSUE TITLE
LLDB Setting menu comes up with items shrunk.

### ISSUE THREAD

**Issue by genusistimelord** [eranif/codelite#2409]
The LLDB Setting menu when opened comes up with everything smaller than the screen size itself.
This is happening on Windows 10 and Codelite version 13.0.7

![image](https://user-images.githubusercontent.com/1034709/71667575-b4e96c80-2d33-11ea-914f-66f10320028f.png)

**Comment by eranif** [comment]
As a workaround, if you resize that window, it will fit itself to the window

**Comment by genusistimelord** [comment]
As to avoid the stale bot from auto closing this so to make sure it does get fixed. I am replying to this. The stalebot is very annoying.
