### ISSUE TITLE
Have a window to show Disassembly when debug?

### ISSUE THREAD

**Issue by eranif** [eranif/codelite#241]
Sorry for my pool english.
Have a window to show Disassembly when debug?
I can't see the ASM when debug a project.
Thanks!
Great Project!

**Comment by eranif** [comment]
Already have one

**Comment by XaVieR375** [comment]
Hi eranif!
Sorry but the disassembly window is no good. It always terminates the debugger mode and closes the assembly code when I try to view it. Can you please fix this?

In the debugger tab, in GDB Windows, I tried both checking and unchecking the Disassembly option but it still crashes.
