### ISSUE TITLE
codelite not opening

### ISSUE THREAD

**Issue by satwikpatel** [eranif/codelite#2411]
I recently downloaded codelite. It was working great for a while until recently. I clicked to try and open codelite and the icon's app appeared on the side flashing and my cursor was a loading symbol. The icon then disappeared and codelite never opened. I've tried turning off my machine and turning it back on. I have uninstalled and reinstalled codelite from the source website and still it been doing the same thing as before. Any help as to why this is occurring and how to fix it would be greatly appreciated. I am using codelite on windows 10. What hould I do?

**Comment by eranif** [comment]
Delete the folder `%appdata%\CodeLite` and it will work again
The content of that folder probably got corrupted for some reason
