### ISSUE TITLE
Code completion stops working after laptop goes stand-by

### ISSUE THREAD

**Issue by Animatedseagull** [eranif/codelite#2416]
Using codelite to start learning C++ i have code completion on as well as the two plugins smart- and word completion. This works fine but after the laptop restarts from sleep the code completion stops to work complete. Only a restart of codelite brings the situation back to normal.
Laptop is DELL precision 7710 with full updated windows 10 pro.
Best regards, Martin.

**Comment by eranif** [comment]
Can you enable `codelite.log` and when it does happen to you, upload the log file content ?
To enable the log: `Settings -> Preferences -> Misc -> Log -> Log verbosity -> DEBUG`
The log is located here:
`%appdata%\CodeLite\codelite.log`

I would recommend you to run off the log once you have uploaded its content (or it will consume disk space)

**Comment by Animatedseagull** [comment]
[codelite.log](https://github.com/eranif/codelite/files/4070925/codelite.log)

Did some more testing: after resuming from sleep: keywords cout, endl (typing end suggests friend) no longer recognized....
Hope the log helps

**Comment by eranif** [comment]
Looks like that after sleeping the symbols db image is corrupted for some reason. I am not really sure why. This is why the completion does not work. You can enable LSP completion 

https://wiki.codelite.org/pmwiki.php/Main/LanguageServer

**Comment by eranif** [comment]
I implemented a fix for this. CodeLite will not detect this case (disk io error) and will re-open the database. This is similar to restarting CodeLite
