### ISSUE TITLE
Mingw Linker failes due to $(Libs) $(LinkOptions) instead of $(LinkOptions) $(Libs) in mk file

### ISSUE THREAD

**Issue by acotty** [eranif/codelite#2417]
On Windows with MINGW64 (not MSYS2) I have a problem where the link stage is failing in Codelite due to the make file having the  exe ld build options in the order "$(Libs) $(LinkOptions)" , BUT in Codeblocks the order is reversed and the exe builds.
I have removed the libraries and hard coded the reversed option in the LinkOptions and the ld now works.

I am not familiar with the GNU LD order requirements. 

What if any problems would I cause if I submitted a patch to change the order in the relevant cpp file that produces the makefile?
If it would cause havoc  then would a better idea be to add an option for a exe file type or add an option to swap the order as a boolean in the build system or add a new build system?

**Comment by acotty** [comment]
More info:
I was able to build a test version of codelite with the $(Libs) $(LinkOptions) swapped in the Plugin\compiler.cpp file as per the snippet below and the build works fine. I suspect the problem is due to the Link Options including a few libs that are part of a "-Wl,--start-group" definition.

m_linkerLines.insert(
    { PROJECT_TYPE_EXECUTABLE,
      { "$(LinkerName) $(OutputSwitch)$(OutputFile) @$(ObjectsFileList) $(LibPath) $(LinkOptions) $(Libs)",
        "$(LinkerName) $(OutputSwitch)$(OutputFile) $(Objects) $(LibPath) $(LinkOptions) $(Libs)" } });

**Comment by eranif** [comment]
You did not specify which version of CodeLite you are using
If you are using one of the latest weekly builds, you can change the link template line from
Settings->build settings->Compilers, select your compiler name from the left side list and then select the tab "Templates"
The lower part of the screen, you find the link line template where you edit and change the order as needed

**Comment by acotty** [comment]
It's not in the latest weekly13.07, but is in the latest trunk code "13.08"

Any ETA on 13.08

**Comment by eranif** [comment]
Tomorrow :)

**Comment by eranif** [comment]
13.0.8 has been released
