### ISSUE TITLE
What gives with Permission denied?

### ISSUE THREAD

**Issue by Iatros55** [eranif/codelite#2418]
/bin/bash: /Users/hoytchilds/Desktop/C++ Source Code/Learning/Learning.workspace: Permission denied

Running CodeLite on macOSX Catalina

**Comment by eranif** [comment]
I am not really sure without some context.
Could you please post questions on the forum and not on the issue tracker?

**Comment by Iatros55** [comment]
Thank you.  How do I go to the forum?

H Childs

**Comment by eranif** [comment]
https://forums.codelite.org
