### ISSUE TITLE
How can I treat my file as an .h file without changing the extension?

### ISSUE THREAD

**Issue by TiManGames** [eranif/codelite#2422]
I'm using version 13.0.8.

I have a project that contains files with the extension .hps that are added to the additional files to parse as C/C++. The parser works fine for the most part, except for .hps files that have no include or class declaration in them. In other words, it won't parse .hps files that contains *only* methods.

The only solution I found was to change the extension to .h

Is there another way to fix this?

**Comment by eranif** [comment]
This was recently fixed. You need to add your `.hps` to the list of valid c++ files under `settings->code completion->general->additional file extensions to parse`

**Comment by TiManGames** [comment]
I did exactly that and it does not work. Here's a file for you:

**Comment by TiManGames** [comment]
I did exactly that and it did not work. Here's a file for you:
[helper_custom_depth_ai_broadcaster.zip](https://github.com/eranif/codelite/files/4082985/helper_custom_depth_ai_broadcaster.zip)

**Comment by TiManGames** [comment]
@eranif  Any luck?
