### ISSUE TITLE
since 9e19a7e: cannot compile codelite-lldb anymore

### ISSUE THREAD

**Issue by kortmannm** [eranif/codelite#2424]
codelive ubuntu, gcc

since 9e19a7e i cannot compile codelite-lldb anymore.
Errors: clFileCache::Clear(), clFileCache::Add(…) and clFileCache::Alloc(…) are undefined

**Comment by eranif** [comment]
Did you run `CMake` again?
These files are new

**Comment by kortmannm** [comment]
oh

thats it, Thank you
