### ISSUE TITLE
Closing parenthesis on functions via code completion

### ISSUE THREAD

**Issue by fmc-coder** [eranif/codelite#2425]
Suggestion:

When I'm typing out a call to a function, it would be nice if, when code completion kicks in to complete the function name, that it would also include the closed parenthesis with the cursor between them. 

![function](https://user-images.githubusercontent.com/57274594/73597352-b653b380-44f0-11ea-993f-4c4c50d3b166.png)

**Comment by eranif** [comment]
I am not sure what you mean here.. but when I pick a function from the code completion box, it kicks in and shows the function signature tip with parameters. Please provide a way to make it _not_ working

**Comment by fmc-coder** [comment]
I apologize, eranif. It works exactly as it shld. I didn't notice that code completion was offering more than one option to complete. It actually offers me three. I was choosing the first one, but the two under it have a small icon to the left with an **f**. I'm so sorry, man. Your IDE rocks! :D
