### ISSUE TITLE
cmake: CL_OUTPUT_DIRECTORY wrong in generated CMakeLists.txt

### ISSUE THREAD

**Issue by nicolaschaufette** [eranif/codelite#2427]
Hello,

In windows, the generated CMakeLists.txt is wrong IF you put your project in subdirectories of your workspace:

set(CL_OUTPUT_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}/..\..\..\CodeLite/cmake-build-Debug/output)

(note the backslashes, that cmake doesn't like)

resulting in :
  Syntax error in cmake code at

    C:/local/CPP_projects/workspaces/prout/test/Test/CMakeLists.txt:12

  when parsing string

    ${CMAKE_CURRENT_LIST_DIR}/..\..\..\CodeLite/cmake-build-Debug/output

  Invalid escape sequence \.

Looks like source code "fnWorkspace.GetPath()" is wrong or not enough.

Best regards,
Nicolas

**Comment by sillick-rfa** [comment]
As of result of fixing this, now the CL_OUTPUT_DIRECTORY can't be changed by CodeLite at all to something custom. Ex. I want to just set it to $WorkspaceDirectory/build but it never changes it in the CMakeLists.txt file when I do Export or Run CMake.
