### ISSUE TITLE
Codelite mistakes subsequent functions as belonging to struct inheriting

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#2429]
Given the following code, Codelite will assume all subsequent members and functions belong to ebco_pair1. This is of course not the case. This is visible in the navigation bar.

Win10, x64, 1909
Codelite non-self-compiled v13.08

	struct ebco_pair1 : pointer_allocator_type // Packaging the allocator with least-used member variables, for empty-base-class optimisation
	{
		size_type first_block_capacity; // This could be unsigned char / char and be the power of two rather than the actual number
		explicit ebco_pair1(const size_type first_capacity) PLF_SEGTOR_NOEXCEPT: first_block_capacity(first_capacity) {}
	}		pointer_allocator_pair;

	iterator begin_iterator, end_iterator;

	segtor(const size_type lowest_block_size = 8) :
		pointers(NULL),
		blocks_capacity(0),
		blocks_size(0),
		elements_capacity(0),
		elements_size(0),
		pointer_allocator_pair(lowest_block_size),
		begin_iterator(this, lowest_block_size),
		end_iterator(this, lowest_block_size)
	{}

	inline void blank()
	{
		pointers = NULL;
		blocks_capacity = 0;
		blocks_size = 0;
		elements_capacity = 0;
		elements_size = 0;
		begin_iterator.block_number = 0;
		begin_iterator.sub_block_index = 0;
		begin_iterator.current_block_capacity = pointer_allocator_pair.first_block_capacity;
		end_iterator = begin_iterator;
	}

**Comment by mattreecebentley** [comment]
ps. PLF_SEGTOR_NOEXCEPT is a macro that expands to noexpect, compiler-dependent

**Comment by eranif** [comment]
Indeed the problem is caused by this macro.
CodeLite uses an external tool to get this layout, so you will need to tell it to ignore this token.
It can be done from:

`Settings->Code Completion->CTags->Advanced->Tokens`
Just add a new line there that contains this macro

`PLF_SEGTOR_NOEXCEPT`

Save the changes and then re-parse the workspace
