### ISSUE TITLE
GDB console: Control C does not copy selected text 

### ISSUE THREAD

**Issue by Robin-Whittle** [eranif/codelite#2431]
I built Codelite from the GitHub code, retrieved as a zip file, about 17 hours ago.  It is built with wxWidgets compiled with GTK+ 3.  This is on Debian 10.2 AMD64, using the native display, not X-forwarding. 

I want to copy and paste some or all of the text in the debugger console.  This is the Output pane in the Debugger set of panes, not the Output Pane in the "Output View" set of panes.  (So perhaps this pane should be renamed "GDB console", "Debugger console" or similar.

Control A selects all text, or I can right click and select all from there.  Alternatively, I can drag the mouse/trackball cursor to select some text.

Control C does nothing, and I think it should copy the selected text to the clipboard.  Right click and copy does work.

Control V works too, to insert clipboard text into the GDB command line editing area at the bottom.  So it seems like a possible oversight that only Control V doesn't work.

The ability to view Codelite's interactions with GDB is extraordinarily valuable.  Likewise the ability to send commands to GDB whenever the debugger is paused somewhere.  Thanks especially for these facilities!  BTW, I am using Codelite with GCC for C++.

**Comment by dghart** [comment]
Yes, I'd noticed that too. It should now be fixed by #1e73c46ed

**Comment by Robin-Whittle** [comment]
Thanks for this change.  Running Codelite on the native screen of a Linux machine (Debian, xfce), the new Control C function works as expected: select the text, including by dragging the cursor, and then press Control C.

Running it via X11-forwarding, with a Windows machine with the screen, using PuTTY and Xming, the Control C is not required, since simply dragging the cursor, or using Control A to select it all,  puts the text into the shared clipboard.  (The Windows clipboard is shared with the clipboard(s) of the user session on the Linux machine.) The same applies when using NoMachine client on Windows and the NoMachine Workstation server on Linux. (This is the fastest way I found, since the screen updates of Codelite when its window is large cause delays with conventional X11-forwarding, even on 1Gbps Ethernet.  The X2Go system should work well in this arrangement, but its Windows client has a bug in its shared clipboard arrangement.)

The two different behaviours are no-doubt related to the finer points of the X11 clipboard: https://mutelight.org/subtleties-of-the-x-clipboard where the "(Default) CLIPBOARD" is for Control C etc. operations and the "PRIMARY Selection" is for dragging the cursor, and pasting via right click.  On the native Linux screen, the two are joined, which suits me fine.  Via X11 forwarding, with Xming or NoMachine, the situation is more complex.
