### ISSUE TITLE
Slow appearance of thin scroll bars for newly loaded text files

### ISSUE THREAD

**Issue by Robin-Whittle** [eranif/codelite#2432]
I built Codelite from the GitHub code, retrieved as a zip file, about 17 hours ago. It is built with wxWidgets compiled with GTK+ 3. This is on Debian 10.2 AMD64, using the native display, not X-forwarding, but the same thing occurs via X-forwarding to Windows, with an ordinary X server, or using X2Go (much faster on a big screen).

When I load a reasonably long source file into a window for editing, or debugging, it takes some time, potentially 10 seconds or more (4GHz i7 machine) for any scroll bar to appear on the right of the screen.  This is a significant problem, since it makes it harder to navigate to the desired position.

When the scroll bar does appear, it is very narrow, but gets wider once the cursor is over it.  I guess this is OK, but I would prefer an ordinary scroll bar with an ordinary, fixed, width.

Trying now with files a few kB or 500kB, with the cursor not at the right of the screen, it took about 5 seconds for the slider to appear, thinly.  Then the slider bar - the only thing visible, since the "scroll bar" is invisible or is white on a white background - fades away, fades into visibility again and then fades away until I move the cursor.  Then it fades in and out again.  

If I place the cursor at the right of the window, the slider widens and the grey bar appears in a wider form, and stays there until I move the cursor somewhere else.  This is all usable but I would prefer an ordinary, non-animated, scroll bar.  Things which are animated for no good purpose are annoying and distracting. 

Thanks for Codelite!

**Comment by eranif** [comment]
What you are seeing is GTK3 issues.
You can disable this scrollbar  by setting this environment variable:

For example, if you are running CodeLite from a terminal, you can do this:
```
export GTK_OVERLAY_SCROLLING=0
codelite&
```

**Comment by Robin-Whittle** [comment]
This works like a charm.  Thanks!
