### ISSUE TITLE
compile error when build with wxgtk3

### ISSUE THREAD

**Issue by playgithub** [eranif/codelite#2438]
codelite 13.0.0
wxgtk3 3.0.4

In 'src/codelite-13.0/codelite_terminal/TextView.cpp':
`void wxStyledTextCtrl::StartStyling(int pos)`

In wxwidgets 3.0.4 doc:
[`void wxStyledTextCtrl::StartStyling(int pos, int mask)`](https://docs.wxwidgets.org/3.0.4/classwx_styled_text_ctrl.html#a6ca352cb6a20c69a9f4bc5001d0fdf25)

It causes compling error.

Thanks

**Comment by dghart** [comment]
Yes, it was fixed soon after the 13.0 release: see 92ed90e07

You could patch your 13.0, or get a more recent CodeLite version e.g. from git, or build against wx3.1; or, easiest, wait until tomorrow when (all being well) CodeLite 14.0 will be released.

Regards,

David
