### ISSUE TITLE
codelite-terminal isn't used while it should

### ISSUE THREAD

**Issue by tGstep** [eranif/codelite#2440]
I'm using Codelite stable 14.0 on Windows 10.
I select codelite-terminal in terminal options but when i run or debug my (console) project, cmd opens instead.

**Comment by tGstep** [comment]
I tested on linux: it works

**Comment by eranif** [comment]
For me (also tested on Windows 10),  `codelite-terminal` opens when you launch your program without debugging using `Ctrl-F5`. However, it can not be launched while debugging because the terminal is launched by `gdb` and not by CodeLite
