### ISSUE TITLE
CodeLite File System Workspace indexes files excluded from view

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2441]
CodeLite File System Workspace indexes files excluded from view

It seems the CodeLite in File System Workspace "mode" indexes all files even when they are excluded from the view

I have a project with a large number of huge .h files that are not supposed to be treated as actual .h files - so I excluded them from the view. Codelite still chokes on indexing them and there seems to be no other way of keeping codelite away from those files.

(CodeLite 14.0, Archlinux)

**Comment by uffejakobsen** [comment]
This feature request is still valid.
I'm making this comment to prevent the "stale bot" from closing it
It seems to be a bad idea to have en automatic bot close feature request

**Comment by uffejakobsen** [comment]
once again....

This is a preventive action - this issue is still valid.
I'm making this comment to prevent the "stale bot" from closing it
It seems to be a bad idea to have en automatic bot close issues

**Comment by uffejakobsen** [comment]
once again again....

This is a preventive action - this issue is still valid.
I'm making this comment to prevent the "stale bot" from closing it
It seems to be a bad idea to have en automatic bot close issues

**Comment by uffejakobsen** [comment]
This is a preventive action - this issue is still valid.
I'm making this comment to prevent the "stale bot" from closing it
It seems to be a bad idea to have en automatic bot close issues

**Comment by uffejakobsen** [comment]
This is a preventive action - this issue is still valid.
I'm making this comment to prevent the "stale bot" from closing it
It seems to be a bad idea to have en automatic bot close issues

**Comment by eranif** [comment]
FYI:
I have added a new option `Right click on a folder in the tree -> Exclude this folder` (this can be done for multiple folders)
All files excluded in this way will be removed from the indexer

**Comment by uffejakobsen** [comment]
> I have added a new option `Right click a folder -> Exclude this folder` (this can be done for multiple folders)

That sounds great - looking forward to test it :-)

It is recursive or does it only work at the exact level where it is applied ?
I'm thinking of scenarios where you'd want to keep the indexer away from a whole subdirectory structure that may be deep/nested

**Comment by eranif** [comment]
You right click 'Exclude' and CodeLite will exclude any files (or subfolders with files) that **contains** this path.
