### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by mhassankhan90** [eranif/codelite#2445]
I just downloaded the latest version and it gets stuck (Not Responding) while I have not even started any project. I was just configuring settings according to my needs and it gets stuck. This has happened twice to me. I closed it and relaunched it and got the same error.

![codelite](https://user-images.githubusercontent.com/60148534/75896067-538b6a00-5e58-11ea-8a94-939f84d114bd.png)

**Comment by eranif** [comment]
I am not sure why this happens. I can only guess that some corrupted file exists somewhere.
Try:
- Close CodeLite
- Delete the folder `%appdata%\CodeLite`
- Start CodeLite

**Comment by mhassankhan90** [comment]
I got my issue resolved by doing the steps mentioned in the link.
Thanks

https://github.com/eranif/codelite/issues/2139#issuecomment-438005358
