### ISSUE TITLE
Line numbers toggling are not working

### ISSUE THREAD

**Issue by blockchaindevel** [eranif/codelite#2447]
I can't seem to tun off line numbers in CodeLite 14.0.0 on Windows 10 or on MacOSX.
I'm unchecking the check box in Guides-General->Show line numbers margin then Apply and OK and no changes occur.
Thanks

**Comment by eranif** [comment]
This was fixed right after 14.0 was released.
1c6d238db9d29b63379228b73923b661225ffa9d
