### ISSUE TITLE
Code Completion not working at all in CodeLite 14.0.0

### ISSUE THREAD

**Issue by Mihi0Solito** [eranif/codelite#2449]
I just built CodeLite **14.0.0**, but the auto completion is not working at all. I checked the cflags window put i didn't really know what to do. Any suggestions ?

**Comment by eranif** [comment]
I can tell you that it works perfectly. So we need to understand why it is not working *for you*
1. Which OS?
2. A minimal workspace to reproduce the problem
3. Did you enable and installed language server?

**Comment by alex-rass-88** [comment]
Auto completion not working if CodeLite builds with wxWidgets 3.0 (tested on windows 10).
More precisely , the pop-up list is displayed incorrectly.

![codelite_completion_bug](https://user-images.githubusercontent.com/7008147/76841065-4bb0ca00-6849-11ea-9757-7a38a96a41e1.png)

**Comment by Mihi0Solito** [comment]
Actually i am using **Ubuntu 18.04.4**
Here's a simple example:
![Capture d’écran de 2020-03-17 10-31-42](https://user-images.githubusercontent.com/62273896/76842556-bdcde280-683a-11ea-8b32-811196ce5dc9.png)

No matter how what function or struct i use i never get any suggetions.
Ps: How to install the language server ?

**Comment by eranif** [comment]
@Mihi0Solito 
If you are working under Ubuntu, you can get `clangd` language server from the command line:

```
sudo apt-get install clang-tools-8
```

If you don't have `clang-tools-8` try without the suffix i.e. just `clang-tools`
Once installed, click : "Plugins -> Language Servers -> Scan"

For Windows, install it from LLVM website (just download the entire compiler `clang` from  https://releases.llvm.org/download.html
Pick the latest version (should be 9) and install it and then do the same steps as advised for Ubuntu.

Also, try remove the space from the `#include` statement see if it helps

@alex-rass-88 
is this a standard CodeLite project? or a custom build project?

**Comment by alex-rass-88** [comment]
CodeLite from msys2

**Comment by Mihi0Solito** [comment]
It is a custom build project. I installed `clang` language server but still nothing changed. 
Ps: I also tried removing spaces frome the `#include` statement,

**Comment by eranif** [comment]
Because it's a custom build project, CodeLite does not really know where to look for the include.
First confirm that `clangd` is installed properly and configured (post a screenshot here so I can help verify it)

Next, do this:

- create a file name `compile_flags.txt`
- place this file at the root folder of your workspace
- in this file add the common build line, for example:

```
-I/usr/include
-I/home/something/include
-DA_MACRO=1
```

Then select from the menu `plugins->language server->restart`
Try completing again

**Comment by Mihi0Solito** [comment]
**@eranif** 
So i thought about what you said about the directories,  so i added my workspace directory to the `ctags
![Capture du 2020-03-17 19-51-31](https://user-images.githubusercontent.com/62273896/76891337-1c21b200-6889-11ea-90c2-7af0962d6dce.png)
` search paths, and it works just fine. Thanks for help **@eranif** .
