### ISSUE TITLE
Same line auto-closing curly brace

### ISSUE THREAD

**Issue by fmc-coder** [eranif/codelite#2451]
Please make it so the CodeLite editor auto-adds a closing curly brace - **}** - on the same line when an opening curly brace - **{** - is given. 

`int myArray[] {} <---  I HAVE TO ADD THE CLOSING CURLY BRACE MYSELF`

My request is to make the opening/closing curly braces act the same as open/close parenthesis `()` and open close square braces `[]` These auto-close immediately after typing opening char.

**Comment by PravinthR** [comment]
I can work on this issue

**Comment by fmc-coder** [comment]
I'll keep my eyes on this and watch for your "completed" post. Thanks, PravinthR.
