### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by fmc-coder** [eranif/codelite#2455]
Please make it so the CodeLite editor auto-adds a closing curly brace - } - on the same line when an opening curly brace - { - is given.

`int myArray[] {} <---  I HAVE TO ADD THE LAST CURLY BRACE MYSELF`

My request is to make the opening/closing curly braces act the same as open/close parenthesis

`()`

and open close square braces

`[]`

These auto-close.

**Comment by PravinthR** [comment]
I can work on this!
