### ISSUE TITLE
Program freezes when clicking Explorer tab

### ISSUE THREAD

**Issue by ImageEngr** [eranif/codelite#2457]
I am using Codelite version 14.0.0 in Debian Linux 10 (Buster)

**Comment by eranif** [comment]
Is this with Wayland or ... ?

**Comment by ImageEngr** [comment]
Yes, it uses Wayland, also running Gnome 3.30.2
cpu is Intel® Core™ i5-3340M CPU @ 2.70GHz × 4

**Comment by eranif** [comment]
Can you login without Waylad? (usually you should have this option in the login screen)

**Comment by ImageEngr** [comment]
It does work properly when I use X.org and Gnome, so the bug appears to be isolated to Wayland.

**Comment by dghart** [comment]
It turned out that this is due to a failed gtk+/wayland interaction when trying to set focus, though I don't understand why it seems to happen only in this situation. I've 'fixed' it by not trying to set focus to the incoming tab.

A patch of that commit should apply cleanly to CodeLite 14.0 too, if you want to try it out.

**Comment by ImageEngr** [comment]
I would be interested in trying the patch.  Please, let me know how I could
get it.

**Comment by dghart** [comment]
The patch is [https://github.com/eranif/codelite/commit/544506798f8fdec136580ff3ead41a25cd7898ee.patch](https://github.com/eranif/codelite/commit/544506798f8fdec136580ff3ead41a25cd7898ee.patch)

That is, the github address of the commit, followed by '.patch'.  (I found out how to do that by reading [this useful page](https://owenou.com/ten-things-you-didnt-know-git-and-github-could-do/), which I found by  googling.)

As I expect you already know, you will need to extract the CodeLite 14 source-code and then, in its top-level dir, do:
patch -p1 < /path/to/544506798f8fdec136580ff3ead41a25cd7898ee.patch
Then build CodeLite as usual.
