### ISSUE TITLE
WX crafter tabs do not show

### ISSUE THREAD

**Issue by DustCommander** [eranif/codelite#2460]
Hello,

I downloaded the wxcrafter demo and started following Tutorial 1. The wxcrafter tab does not show. In fact, there are no tabs. I am running codelite 13.0.3 on a Windows 10 machine using the MinGW compiler. Also, there is no refresh button.

Not sure if it matters, but codelite was installed on D: and wx crafter was installed on C;

**Comment by DustCommander** [comment]
I can use right click on the .wxcp file to open the wxcrafter window.

**Comment by eranif** [comment]
The "tabs" of wxCrafter were removed. The tree view was too small to fit the content of wxCrafter. Instead wxCrafter is now hosted in its own frame. You can either do this:

`Ctrl-Shift-R` and type the name of the wxcp file you want to open, or
Double click it in the tree view, or
`Ctrl-Shift-F12` to bring the designer view to the the front
