### ISSUE TITLE
Can not generate code in wx crafter Tutorial1

### ISSUE THREAD

**Issue by DustCommander** [eranif/codelite#2462]
The generate code option is not available when I am following Tutorial 1
WXCrafter Version 2.9 Codelite version 13.01.
![WxcrafterNoCode](https://user-images.githubusercontent.com/55657495/77910103-8ad51700-725c-11ea-90f9-d54d53ab9275.PNG)

**Comment by eranif** [comment]
The tutorial is out dated..
Click on the grey `cog` icon to generate the code OR from the menu, select `File->Generate Code` (default key binding `Ctrl-G`)
