### ISSUE TITLE
How to create  a custom control

### ISSUE THREAD

**Issue by DustCommander** [eranif/codelite#2464]
How do I create a custom control?

I am moving an application into WX crafter. The following code is used to create a messagePane control based on a wxTextCtrl. I would like to make it a custom control and possibly add the icon in wxCrafter.  I do not know what to enter fot Class and XRC Preview class, assuming that I start with create a custom control.
```c++
messagePane ::messagePane(wxWindow *parent,
               wxWindowID id,
               const wxString& title, 
               const wxPoint& pos, 
               const wxSize& size)
{
                             
    theMessagePane =     new wxTextCtrl(parent, id, title,  pos, size,  
                            wxTE_MULTILINE | wxHSCROLL | wxTE_RICH ,     wxDefaultValidator, 
    wxTextCtrlNameStr);
    maxNumLines = 50;
    minNumLines = 20;
}


void messagePane::addText(const wxString& text){
    int numLines;  
    long position;
    theMessagePane->AppendText(text);  
    numLines = theMessagePane->GetNumberOfLines ();
    if(numLines >= maxNumLines + 1 ){
        position = theMessagePane->XYToPosition(0, numLines- minNumLines);
        theMessagePane->Remove(0,position);
        numLines = theMessagePane->GetNumberOfLines();
    }
}

void messagePane::setmaxNumLines(int max){
    maxNumLines = max;
}

void messagePane::setminNumLines(int min){
    minNumLines = min;
}


void messagePane::blank(){
    theMessagePane->Clear();
}
```

**Comment by eranif** [comment]
First, your code will crash. You must call the parent constructor. I will assume that your class `messagePane` is a subclass of `wxPanel` so your constructor should look like this:

```c++
messagePane ::messagePane(wxWindow *parent,
               wxWindowID id,
               const wxString& title, 
               const wxPoint& pos, 
               const wxSize& size)
: wxPanel(parent, id)
{
...
}
```

So you should make your constructor *identical* to `wxPanel` and then in the wxCrafter whenever you need your custom control, you choose wxPanel. And under the `subclass` section you write the actual class name and include file for it.

NOTE:

please keep the issue tracker for bugs / feature requests and not for asking questions. This can be done on the forum

Thanks!

**Comment by DustCommander** [comment]
Hi Eran,

It does work in the application i used it in. I think the reason is that it
inherits the constructor front the base class.
I have no idea if I stated that correctly. I have limited C++ experience!


Best regards,
Steve
