### ISSUE TITLE
Timer control in wxCrafter

### ISSUE THREAD

**Issue by DustCommander** [eranif/codelite#2465]
Is there a way to add a timer control from wxCrafter?

**Comment by eranif** [comment]
wxC support adding timer to the top level forms (wxPanel, wxFrame and wxDialog)
You do this by right clicking the top level widget and select `Add wxTimer`
<img width="565" alt="timer" src="https://user-images.githubusercontent.com/3677711/78134285-8f4e2b00-7428-11ea-847f-7fa2e80b3050.png">
