### ISSUE TITLE
Forgets the compiler

### ISSUE THREAD

**Issue by fasterME** [eranif/codelite#2466]
Since I have Installed Codelite, I have observed that after every 4-5 days of use it forgets the compiler.  The only way ive found to fix this issue is to reinstall the complete codelite...This is not comfortable and often disturbing!! Please Fix this issue or provide me the appropriate solution before I shift my IDE and stop using codelite..

**Comment by eranif** [comment]
1. Check if you have a cleanup process that cleans `%appdata%\CodeLite` folder - this is where CodeLite saves it's configuration. My CodeLite (and other many many users don't have this issue), so I would guess it is a local issue on your machine
2. I don't understand, is this a threat? feel free to switch now. Don't wait...
