### ISSUE TITLE
Code Completion

### ISSUE THREAD

**Issue by arensonzz** [eranif/codelite#2468]
Code completion doesn't work for multiple variable definitions in single line. It only works for the first variable. Older versions of CodeLite had this issue too.
for example:
int height, weight;

Code completion only works for 'height' it doesn't see 'weight'.

W10 64bit CodeLite 14.0.0

**Comment by eranif** [comment]
You should install a language server for Windows (for Windows this is `clangd`):
https://wiki.codelite.org/pmwiki.php/Main/LanguageServer#toc3

**Comment by arensonzz** [comment]
Thank you for your help man! My issue is solved. I really appreciate your work, and I like version 14 so far.
