### ISSUE TITLE
many crashes

### ISSUE THREAD

**Issue by iplayfast** [eranif/codelite#2469]
built code codelight-14 using commands from readme file.
  ```bash
  cd codelite
  mkdir build-release
  cd build-release
  cmake .. -DCMAKE_BUILD_TYPE=Release
  cmake --build . -j $(nproc)
  sudo cmake --build . --target install
  ```
Everything seemed to work.
Create a workspace /home/chris/clite
Create new project test
gui, wxwidgets, gcc gdb,codelite make generator
click the build icon (hammer)

blank dialog appears with the title codelite crash handler.
can only close with the corner x, and codelite exits after that.

reopening codelight and trying to build seems to succeed. 
running the program pops up the terminal as well as the gui

**Comment by eranif** [comment]
Can you paste the content of `~/.codelite/crash.log` ?
