### ISSUE TITLE
mingw32-make.exe *** [ALL] error 2

### ISSUE THREAD

**Issue by villn52** [eranif/codelite#2470]
I've been learning C++ and using MingGW as my compiler. Learning vectors, anytime I use the #include <vector> library, I get this error when I build or run : mingw32-make.exe *** [ALL] error 2.
Downloaded and used TDM-GCC-64 as a compiler and it temporarily solved the issue. Now the error happens regardless of the libraries I use . Thanks for any help.

**Comment by eranif** [comment]
This is not a bug in CodeLite. Please ask advise on compile issues on the forums not on the issue tracker
