### ISSUE TITLE
wxCrafter rendering windows incorrectly

### ISSUE THREAD

**Issue by richardcrossley** [eranif/codelite#2471]
Hi,
wxCrafter on Linux Mint 19.3 Cinnamon desktop isn't rendering the window correctly.

* Right click the "wxcrafter.wxcp" file and select "Open with wxCrafter..."
* The underlying source code is shown in the client area of the window being designed.
* Changing to the C++ & XRC views an then back to the designer in wxCrafter does the same thing.
* Adding & modifying controls seems to redraw the window correctly.

Versions:
wxCrafter-2.9
Build 2.9

CodeLite: 14.0.0

I tried the same things on the Windows version in a virtual machine (Windows 10). Everything works fine.

**Comment by dghart** [comment]
Hi,

I know the effect you are describing; I've seen it with some distros/DEs in other programs e.g. konsole. However I can't make it happen with CL 14.0 in a Mint 19.1 Cinnamon, or a 19.3 Mate.

I suspect it's a (stupid imho) special effect of the DE or theme or... Could you experiment with changing your theme, your cinnamon settings? (I'd guess that the word 'transparency' is worth looking for.)

Regards,

David

**Comment by richardcrossley** [comment]
Thanks for the confirmation. It's late in the day here, so I'll have a look tomorrow.

**Comment by richardcrossley** [comment]
Hi,
Starting with Linux Mint 19.3 and now using Ubuntu 20.04 I was able to repeat the effect with several applications; some related to wxWidgets, others just using regular GTK. In the end I decided a fresh ${HOME} directory was required, removing 10 years of crufty config that has been created with various Ubuntu and Mint installations. It seems to have resolved the issue.
