### ISSUE TITLE
Cannot detect MinGW64 installed under Windows 10

### ISSUE THREAD

**Issue by richardcrossley** [eranif/codelite#2472]
During the setup wizard I select the option for CodeLite to download the MinGW64 package. 
The file "mingw-w64-v7.0.0.zip" is download and the contents extracted to c:\mingw-w64-v7.0.0

I close the dialog box instructing me to press "Scan" which I do. The response is "Could not locate any MinGW compiler installed on your machine, would like to install one now?" This repeats the process.

I tried installing the regular binaries using an installer in C:\Program Files (x86)\mingw-w64 and the scan function doesn't find that either.

After setting the path and restarting CodelLite, it finds the compiler.

**Comment by eranif** [comment]
If CodeLite does not auto detect your compiler, you can tell it where it is located: Click on the `+` green button, this will open a dialog for you to select a folder. Select the folder where `gcc.exe` exists and click OK. 

A word of advise: avoid installing compilers in locations with space (like: `C:\Program Files (x86)\MinGW`)

<img width="588" alt="add-compiler" src="https://user-images.githubusercontent.com/3677711/79242107-917aa580-7e7c-11ea-9963-e4c7e9eaaf3b.png">
