### ISSUE TITLE
codelite, php and xdebug

### ISSUE THREAD

**Issue by StephanKrauss** [eranif/codelite#2475]
Hello,

a simple question.
Can i use in codelite the php debugger xdebug ?

Your sincerly

Stephan

**Comment by eranif** [comment]
It's been a while, but last time I tried - it worked. So unless the xdebug protocol changed since I last wrote the interface, then it shouldn't be a problem

**Comment by eranif** [comment]
I created a wiki page that explains how to configure CodeLite to debug with XDebug. I tested it with PHP 7.4 and latest XDebug from xdebug.org

https://wiki.codelite.org/pmwiki.php/Main/DebugWithXDebug
