### ISSUE TITLE
Zoom level setting

### ISSUE THREAD

**Issue by biciolea** [eranif/codelite#2477]
Codelite doesn't save the editor zoom level between sessions.
Platform: windows 10 pro
Version: 14.0.0

**Comment by pimlie** [comment]
The default zoom level is also too high for me (ie text is too big, like it a bit smaller) but there doesnt seem to be a config setting for this?

**Comment by biciolea** [comment]
ping

**Comment by biciolea** [comment]
ping

**Comment by biciolea** [comment]
ping

**Comment by biciolea** [comment]
It would be nice and useful to have this feature implemented

**Comment by Eric-01** [comment]
As a good workaround, you can change the global editor font size by going to Settings > Colors and Fonts > Global font. The selected font and its size will persist across sessions.
