### ISSUE TITLE
Searching with F3 key

### ISSUE THREAD

**Issue by biciolea** [eranif/codelite#2479]
Searching words with F3, without opening the search box, doesn't comply with the last "Case Sensitive" and "Whole Word" settings.

Codelite 14.0.0
Windows 10

**Comment by biciolea** [comment]
ping

**Comment by biciolea** [comment]
ping

**Comment by biciolea** [comment]
ping

**Comment by AJenbo** [comment]
To be more specific this is only true when the search box isn't open.
