### ISSUE TITLE
Code Completion Box Closes

### ISSUE THREAD

**Issue by arensonzz** [eranif/codelite#2480]
I assigned ALT + j k l i (home row keys) to arrow keys so I don't have to move my arm to reach arrow keys. When I hit keys like ALT CTRL etc. code completion box immediately closes . That's why I can't choose between suggestions. If there's something I can do to fix this issue It would enhance my CodeLite experience.

Thank you, have a nice day.

**Comment by eranif** [comment]
atm, the code completion will auto dismiss itself when one of the special characters is pressed:

```c++
    case WXK_ESCAPE:
    case WXK_LEFT:
    case WXK_RIGHT:
    case WXK_HOME:
    case WXK_END:
    case WXK_DELETE:
    case WXK_NUMPAD_DELETE:
    case WXK_ALT:
    case WXK_WINDOWS_LEFT:
    case WXK_WINDOWS_RIGHT:
    case WXK_CONTROL:
        DoDestroy();
        event.Skip();
        break;
```

see here: https://github.com/eranif/codelite/blob/master/Plugin/wxCodeCompletionBox.cpp#L481
This needs to be configurable
