### ISSUE TITLE
CMake Ideas - Ninja Multi-Config

### ISSUE THREAD

**Issue by YMba9g8j9CJp0wLoQf5y** [eranif/codelite#2481]
I was experimenting with codelite because I was getting very frustrated with visual studio for a lot of reasons. I believe if codelite could implement these ideas it would really assist developers in using codelite.

As of cmake 3.17 there is now support for Ninja Multi-Config. One of the really appealing things about using visual studio support is that it is a multi configuration generator. I don't have to create multiple builds for Debug, Release, Etc.

I can just click on the UI and switch easily.

Shouldn't codelite be able to do this now with Ninja Multi-Config?
https://cmake.org/cmake/help/latest/generator/Ninja%20Multi-Config.html

**Comment by eranif** [comment]
You can probably achieve this if you will use the `File System Workspace` in CodeLite
With this type of workspace, you can define multiple commands.
So you can basically have a button / menu in CodeLite for every build configuration that you have in `cmake.ninja` file.

https://wiki.codelite.org/pmwiki.php/Main/FileSystemWorkspace
