### ISSUE TITLE
CMake Ideas - IDE Support

### ISSUE THREAD

**Issue by YMba9g8j9CJp0wLoQf5y** [eranif/codelite#2482]
It would be really nice when I generate a codelite project if I could open it like I would xcode/visual-studio.

IE:

cmake -S . -B build

cmake --open build/    <- This doesn't work

**Comment by eranif** [comment]
Nice idea, wrong issue tracker. `CMake` is not maintained by us, to to make the above command working, you need to file a feature request to the `CMake` team
