### ISSUE TITLE
codelite fullscreen

### ISSUE THREAD

**Issue by WalpoleT** [eranif/codelite#2484]
I pressed full screen by accident now I cant get it back to a regular screen. There is also no menu at the top of the screen anymore.

**Comment by WalpoleT** [comment]
Any suggestions on what to do?

**Comment by eranif** [comment]
1. Hit `Alt-M`.
2. If this does not work for you: `Ctrl-Shift-P` type `Full screen` and select
3. `Ctrl-F11`
