### ISSUE TITLE
Numerous link errors when building codelite

### ISSUE THREAD

**Issue by bartgol** [eranif/codelite#2491]
Hello,

I decided to build codelite on my laptop, to give it a try. Unfortunately, I keep getting link error for the plugin library. The errors are many, but all look like the following:

```
../lib/libplugin.so: undefined reference to `non-virtual thunk to wxTextCtrl::HitTest(wxPoint const&, long*) const'
../lib/libplugin.so: undefined reference to `non-virtual thunk to wxTextCtrl::MarkDirty()'
../lib/libplugin.so: undefined reference to `non-virtual thunk to wxTextCtrl::PositionToXY(long, long*, long*) const'
../lib/libplugin.so: undefined reference to `non-virtual thunk to wxTextCtrl::IsEditable() const'
../lib/libplugin.so: undefined reference to `non-virtual thunk to wxStyledTextCtrl::Copy()'
../lib/libplugin.so: undefined reference to `non-virtual thunk to wxTextCtrl::ShowPosition(long)'
../lib/libplugin.so: undefined reference to `non-virtual thunk to wxTextCtrl::GetSelection(long*, long*) const'
../lib/libplugin.so: undefined reference to `non-virtual thunk to wxTextCtrlBase::SetDefaultStyle(wxTextAttr const&)'
../lib/libplugin.so: undefined reference to `non-virtual thunk to wxTextCtrl::GetStyle(long, wxTextAttr&)'
../lib/libplugin.so: undefined reference to `non-virtual thunk to wxTextCtrl::GetEntry() const'
../lib/libplugin.so: undefined reference to `non-virtual thunk to wxTextCtrl::XYToPosition(long, long) const'
../lib/libplugin.so: undefined reference to `non-virtual thunk to wxTextCtrl::DoPositionToCoords(long) const'
../lib/libplugin.so: undefined reference to `non-virtual thunk to wxTextCtrl::DiscardEdits()'
../lib/libplugin.so: undefined reference to `non-virtual thunk to wxTextCtrl::SetStyle(long, long, wxTextAttr const&)
```

A few details:

- OS: RHEL7.5
- Compiler: gcc 8.2
- `wx-config --version` return 3.0.4.
- I manually checked the wx libs and verified those symbols are defined
- My cmake config line was relatively simple:

```
SRC_DIR=${WORK_DIR}/utils/codelite/codelite-src
INSTALL_DIR=${WORK_DIR}/utils/codelite/codelite-install
WX_CONFIG=/usr/libexec/wxGTK3/wx-config

rm -rf CMakeFiles
rm -f  CMakeCache.txt

cmake -Wno-dev  \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE            \
  -D CMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR}   \   
  -D CMAKE_C_COMPILER:STRING=gcc                \
  -D CMAKE_CXX_COMPILER:STRING=g++              \
  \
  -D WITH_WX_CONFIG:FILEPATH=${WX_CONFIG}       \
  -D ENABLE_LLDB:BOOL=FALSE                     \
  \
  ${SRC_DIR}
```

I am not sure whether the error is on a) codelite, b) wxGTK3, c) me. Any help to figure this out would be appreciated.

**Comment by dghart** [comment]
Hi,

This sounds like an issue for the [CodeLite forum](https://codelite.org/forum/), not the bug-tracker. I suggest you repost it there; but first, why not try using the CMakeLists.txt provided with CodeLite? See https://wiki.codelite.org/pmwiki.php/Developers/Linux#toc6

**Comment by bartgol** [comment]
Thanks for pointing me to the right resources.

However, I do not understand what you mean by 'try using the CMakeLists.txt provided with CodeLide'. Do you mean the cmake directives (i.e., "-D blah")? They are pretty standard cmake directives, and the codelite specific ones I got them fromt he commented lines at the beginning of codelite's CMakeLists.txt.

**Comment by dghart** [comment]
I mean do what we do when we want to build CodeLite: 
Open a terminal in its top source dir
If necessary prepend the desired wxWidgets install location to that terminal's $PATH (as I doubt if RHEL has update-alternatives for wx-config; fedora only got that a couple of years ago).
then do e.g.:
`mkdir -p build-dbg3 && cd build-dbg3/ && cmake -G "Unix Makefiles" VERBOSE=1 -DCMAKE_BUILD_TYPE=DebugFull -DWITH_PCH=0 -DCL_PREFIX=$(pwd)/../CLgtk3-install .. && make -j16 && make install)`

Of course you'd amend the options to suit you, but no need to write your own CMakeLists.txt.

**Comment by bartgol** [comment]
I never wrote my own CMakeLists.txt. Thad would make no sense. I think you may be confusing CMakeLists.txt with a configure script (which is just, as you wrote, a bunch of shell commands to invoke cmake).

My cmake script contains commands very similar to what you posted (excep the directory setup, i do that before hand), plus some common cmake command (set compilers, for instance), and the location of wx-config (which I had to specify cause it wasn't in PATH).

Anyhow, I asked on the forum, hopefully some good soul will help me. =)

Thanks.
