### ISSUE TITLE
Constant flickering/redrawing of file tabs & explore area

### ISSUE THREAD

**Issue by pimlie** [eranif/codelite#2493]
The file tabs are constant flicking when I move my mouse over them: 
![output](https://user-images.githubusercontent.com/1067403/81497860-95ee7e80-92c1-11ea-854d-1c0f056fd7dc.gif)

The seem happens as well with the tabs in the Workspace View, but also in the Filetree pane when I scroll my file tree in Explorer. The constant flickering makes it quite 'nervous'  to look at.

Using Ubuntu 18.04 with (I think) GTK2, installed Codelite 14 from the repository. After upgrading I removed my `~/.codelite` profile folder to create a new one

**Comment by eranif** [comment]
You should stop moving your mouse :)
I don't think we provide GTK2 anymore. Can you confirm this?
Use `Ctrl-Alt-Mouse middle click` to see the GTK and wxWiddgets version used

**Comment by pimlie** [comment]
Ah yes, you are right :)

![image](https://user-images.githubusercontent.com/1067403/81502258-3900c180-92dd-11ea-8acf-a952fad4501c.png)

**Comment by dghart** [comment]
It doesn't happen in my bionic virtualbox guest; the 'x' buttons change colour if the pointer touches them, but nothing else happens. I use the 'default' theme, but it didn't happen either with the dark theme 'inkpot'.

That's with a standard ubuntu install. Do you use a different DE/Window manager, or a different 'different' theme?

**Comment by pimlie** [comment]
Yes, I am running XFCE4. Should have mentioned that earlier probably, sry.

**Comment by dghart** [comment]
It doesn't happen in a Xubuntu Bionic guest either :/

![XubuntuBionic](https://user-images.githubusercontent.com/6452587/81563170-d3b8d900-938d-11ea-9547-708b91183f54.png)

**Comment by pimlie** [comment]
Hmm, thanks for checking. Do you maybe know what the relevant packages and/or config options are that I could check? In the past I played around with some settings but have currently no idea anymore what I changed exactly.

**Comment by dghart** [comment]
It's hard to guess what the difference might be. If it's a CodeLite thing, you could temporarily rename your ~/.codelite/ dir; then starting CodeLite will create a fresh default one. If that doesn't show the flicker, then at least you know it _is_ one of it's settings.

If it does still flicker, it must be your XFCE or similar settings. I've no idea which.

The other thing you could try is to install and run the [wxWidgets samples](https://wiki.codelite.org/pmwiki.php/Main/WxWidgets31Binaries); in particular, see if the 'notebook' sample flickers too.

**Comment by eranif** [comment]
@dghart testing the notebook sample is not a good idea. We are using custom drawn notebook control and not the native one. So my guess, it won't flicker.
Probably checking the paint test or custom drawing test will yield similar results

**Comment by pimlie** [comment]
Both notebook as drawing are working just fine (unfortunately?).

Have installed Codelite 14 on an old(er) pc with Linux Mint 19.1 XFCE and that also exhibits the noticeable redrawing. Will upgrade that one to the latest Linux Mint to see if it then still happens

**Comment by dghart** [comment]
Testing with a different DE would be helpful too. FWIW I get no flicker here (debian) with LXQT.

**Comment by pimlie** [comment]
The flickering still occurs after upgrading to Mint 19.3 XFCE. And its not just those headers, I can clearly see the text of the open file to get redrawn too. Tried Mint 19.3 Cinnamon and that seemed to work ok.

Found this issue which sounded similar but manually setting CursorThemeSize didnt help: https://gitlab.gnome.org/GNOME/gtk/issues/1371.

Also looked into recent upgrades but doesnt seem like any DE related packages got upgraded in the last month

**Comment by pimlie** [comment]
After some more googling I found this issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=517671

After installing `ibus-gtk3` and starting codelite with `GTK_IM_MODULE=ibus codelite` I dont seem to be experiencing this issue anymore.

**Comment by dghart** [comment]
Ah, well spotted! So similar to https://trac.wxwidgets.org/ticket/18462

**Comment by pimlie** [comment]
Maybe codelite could show a similar warning as they added to Eclipse about using xim?
