### ISSUE TITLE
Unabe to customize workspace pan shows completely empty

### ISSUE THREAD

**Issue by blueskull654** [eranif/codelite#2495]
I hid all my tabs in workspace pan and I am unable to get them back ..
[
![Capture](https://user-images.githubusercontent.com/65240544/81712451-3a271f80-9492-11ea-97f8-3a5fd22182c1.PNG)

**Comment by dghart** [comment]
I see what you mean. When all the tabs are hidden, the 'dropdown' button disappears too. That's a bug that needs fixing.

Meanwhile, you can recover as follows:
1) Close CodeLite
2) Edit the relevant configuration file, which is probably ...Documents\myworkspace\.config\codelite.conf. It will have a line like:
"VisibleWorkspaceTabs": [],
Edit this to read:
"VisibleWorkspaceTabs": ["Workspace"],

Start CodeLite again; that tab and the dropdown button should now be present.

**Comment by eranif** [comment]
`Perspective->Restore Default Layout`

**Comment by dghart** [comment]
I did try that too but it didn't work for me (in a fresh workspace, no project added, all tabs hidden in the Workspace pane). Did it for you?
