### ISSUE TITLE
Not getting Themes

### ISSUE THREAD

**Issue by antreasm123** [eranif/codelite#2496]
When Installing Codelite and I'm prompted to download the new themes and then restart codelite just restarts with no changes. Also when I'm using ctrl+f9 the program exits imidiately.

**Comment by eranif** [comment]
I am not sure what do you mean by "themes"
CodeLite does not offer to download any themes...

**Comment by antreasm123** [comment]
![image](https://user-images.githubusercontent.com/45568938/81900376-55df1280-95c5-11ea-82e3-1033c43ceaf2.png)
