### ISSUE TITLE
Themes does not appy to all elements

### ISSUE THREAD

**Issue by rozhuk-im** [eranif/codelite#2497]
Now:
![Screenshot_2020-05-14_06-10-32](https://user-images.githubusercontent.com/11380091/81889359-faecf180-95ab-11ea-8212-db4e35e76812.png)
Was month ago:
![Screenshot_2020-05-14_06-10-59](https://user-images.githubusercontent.com/11380091/81889379-07714a00-95ac-11ea-9718-bde60c91d21c.png)

**Comment by rozhuk-im** [comment]
After https://github.com/eranif/codelite/commit/70a96d352342e1380b94649dc6f2c7fbd3ebd2bc
![Screenshot_2020-05-14_17-08-15](https://user-images.githubusercontent.com/11380091/81944556-99f20780-9605-11ea-948d-fc70c0f62457.png)

**Comment by eranif** [comment]
By default CodeLite now is buit with native notebook control.
You can disable this by passing to CMake:
`-DGTK_USE_NATIVEBOOK=0`

**Comment by eranif** [comment]
FYI:
This is how it looks here:
![codelite-gtk3](https://user-images.githubusercontent.com/3677711/81945422-c65a5380-9606-11ea-90c4-a38c4726e286.png)

**Comment by eranif** [comment]
This is with system theme: "Adwaita Dark"

**Comment by rozhuk-im** [comment]
I rebuild with ```-DGTK_USE_CUSTOMBOOK:STRING=1```, ```-DGTK_USE_NATIVEBOOK=0``` - removed in last commits - got back like on first screen with white "debug" and buttons. Graybird style.

With Graybird-dark style all looks like on your screen.
