### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by emmelvira** [eranif/codelite#2504]
I keep running into an issue with the editor when referencing "#include <iostream>" says 'iostream' file not found. I've troubleshot this for days, the program builds and runs with no errors at all yet I continue to get the same message. Have not been able to find anything helpful online...

![Error Message](https://user-images.githubusercontent.com/65464929/82128268-82d72500-977f-11ea-8776-40b3d7fab2a7.png)

**Comment by eranif** [comment]
this error is coming from the `clangd`. the code completion.
Apparently, it can't locate the `iostream`.

The the workspace directory (`C:\Users\E-man\Documents\FirstWorkspacec`) there is a file named `compile_flags.txt`, you paste it's content here?

**Comment by eranif** [comment]
I did further investigation and seems there is a problem with compilers which are installed under a path with spaces (e.g. `C:\Program Files\mingw-w64\mingw64\bin` )

This is now fixed in git master.
As a workaround, you could install your compiler in a different location (e.g. `C:\MinGW-w64`)
