### ISSUE TITLE
Codlite debug need a feature "run to cursor" like code::blocks

### ISSUE THREAD

**Issue by Innocence** [eranif/codelite#2505]

**Comment by eranif** [comment]
right click -> jump to caret line

**Comment by Innocence** [comment]
> `right click -> jump to caret line` & `right click -> run to caret line`

Only if you use 'start/continue debugger' and isnsert  a breakpoint before you start it.

But in C::B,you don't have to  click  start debugging or set up a breakpoint , just click a line where you want to stop, and click 'run to courosr' .And it will start debugging and stop right there.
