### ISSUE TITLE
High CPU usage when idle / Rust

### ISSUE THREAD

**Issue by tzargoth** [eranif/codelite#2508]
I was attempting to see if Codelite can work with Rust projects ... but, I am concerned with the high CPU usage when idle, at 25% (one core).  Causes my laptop fan(s) to run continuously.  Using latest version 14 on Ubuntu 18.04.

I notice that in my task manager there are multiple clangd-6.0 instances constantly starting and stopping.  Perhaps this has something to do with this.

Other than setting up the rust language server and configuring it in Codelite, is there anything else to do to get syntax highlighting to work?  Documentation does not appear to cover this, from what I have been able to find.  Loading my rust project for the first time started the rust language server, but there seemed to be no syntax highlighting or code completion.  After restarting, code completion appears to be working, but no syntax highlighting.  Is there some documentation that covers the particulars on setting this up?

**Comment by dghart** [comment]
Perhaps this would have been more appropriate as a [forum](https://codelite.org/forum/) post...
>there are multiple clangd-6.0 instances constantly starting and stopping. Perhaps this has something to do with this.

>Using latest version 14

Meaning 14.0, or the 'weekly-build' 14.1, which contains code-completion changes?

What happens if you turn off (or turn on if it's currently off) Plugings > Language Server > Settings and/or Settings > Code Completion?

>Is there some documentation that covers the particulars on setting this up?

https://wiki.codelite.org/pmwiki.php/Main/AddingNewLexer which hasn't been updated recently and doesn't mention rust. That was added to wxWidgets in 3.1 (which is what our packages are built against) with the line:
wxSTC_LEX_RUST   111
See https://sourceforge.net/p/scintilla/feature-requests/1024/ for more information.

**Comment by tzargoth** [comment]
Using 14.0, not weekly build.

Didn't realize there was a forum ... Google results didn't show any in the first couple pages when I searched.  When I checked out the forum now, there is no search options ... I am guessing that is only for members.

I disabled Language Server Completion and it stopped loading clangd instances and CPU is normal ... but now, I am assuming code completion for configured languages won't work.  There still seems to be some form of autocomplete, but must be local to the file.  Maybe that is what I was seeing earlier.  Not sure.  Without knowing which forum posts to read (no search), I won't be getting much help there ... not planning to create a user account just for that.

I looked at the lexer information .... it isn't as straight forward as I was hoping.  I can probably figure it out though.  I might try again with the next stable repository release.

**Comment by dghart** [comment]
>I am assuming code completion for configured languages won't work.

Language Server Completion is new, but CodeLite has had code-completion 'forever' (which explains why https://wiki.codelite.org/pmwiki.php/Main/SettingUpCodeCompletion is rather ancient). 
IIUC you will find it continues to work, even without LSP. However if I'm wrong, eranif today made a [commit](https://github.com/eranif/codelite/compare/0bc176e12438...6bcbff616198) which sounds relevant.
