### ISSUE TITLE
Global menu KDE issue

### ISSUE THREAD

**Issue by MrGooogo** [eranif/codelite#2515]
When using global menu KDE widget with the application it seems that it fails to recognize the presence of active workspace. If widget is removed and then added the menu behaves as usual. Apart from the menu itself, ide seems to recognize the presence of the workspace and projects in it, since not only it is displayed in the corresponding window, but it compiles\execute like normal(be that through gui button or shortcut), however codelite terminal doesn`t get invoked for some reason(though konsole does if it is selected as a terminal) 

This behavior is reproducible on versions from 12-14, 12 from debian repo, 13-14 from codelite repo(so those should be 13.00 and 14.00) + tested the freshly compiled version directly from git.

My best guess is that menu gets detached from the main process and it tinkers with initialization routine since it is fixed by turning on the widget mid-way. I am not familiar with wxWidgets framework, so i doubt i`ll be able to debug this behavior on my own.
 
![Screenshot_20200601_105156](https://user-images.githubusercontent.com/20725545/83387740-f02cbc00-a3f5-11ea-8d52-13b23ea76ebe.png)
![image](https://user-images.githubusercontent.com/20725545/83388945-076ca900-a3f8-11ea-8a2f-afed029cbbcc.png)
![image](https://user-images.githubusercontent.com/20725545/83389069-413daf80-a3f8-11ea-8282-cb49affab27d.png)

KDE framework 5.54.0
xcb windowing system

**Comment by dghart** [comment]
There is a similar issue in [a forum post](https://codelite.org/forum/viewtopic.php?f=3&t=4507) .

I just tested in a standard ubuntu 20.04 virtualbox guest and couldn't reproduce this problem either:

![Kubuntu2004Workspace](https://user-images.githubusercontent.com/6452587/83397108-fbcbb300-a3f4-11ea-8df4-fa093fc2a043.png)

I've no idea what might be causing this sort of problem.

**Comment by MrGooogo** [comment]
Maybe it's KDE related issue then, since kubuntu 20.04 runs 5.68 kde framework. 

Though in your screenshot you are using "native" menu to access the workspace submenu(or so it seems atleast), not "global menu" widget that pulls that menu to the panel.

Also i think the guy on the forum does have the same problem, since his selection of the submenu lacks the margin to the left of the menu sections where icons normally can reside(that is present in the native menu in my screenshot, and it is present in yours) and the selection has rounded corners. That probably means that he uses global menu as well(however i can't be sure)

**Comment by MrGooogo** [comment]
Tested under the same VM and environment(virtualbox + kubuntu 20.04) and i managed to recreate the bug, so at least more recent kde framework doesn`t fix it. Iso-mage was downloaded straight from kubuntu.org. Here`s a screen of a bug:
![Screenshot_20200601_154416](https://user-images.githubusercontent.com/20725545/83410687-81645880-a41f-11ea-8e87-1a27747fdefe.png)

On a side note, is it even normal that qemu x86 platform from debian repo is broken?

**Comment by dghart** [comment]
I see. I switched to lxde/lxqt a few years ago and  I'd not realised that kde had implemented a global menu, one of unity's anti-features. 

I was about to say that AFAICT it's not active by default in kubuntu 20.04, and I that couldn't find any way to switch it on. Then you proved it _can_ be done ;) .  How?

Presumably if you turn off the global menu, the normal one works OK...

>On a side note, is it even normal that qemu x86 platform from debian repo is broken?

I've no idea. I'm a happy virtualbox user ;)

**Comment by MrGooogo** [comment]
Well unlike unity in kde it's just a widget, not a default "built-in" feature(so no one forced to use it or even know about it). It's actually quite nice feature in terms of usability and customization.

To turn it on in kubuntu(or any kde) you need to add panel "Application menu bar"(to add panels you need to right click on a panel->"Panel options"->"Add panel"). Or alternatively you can just add widget "Global menu" anywhere on your desktop(since previous actions just create a panel with said widget already in it on top of your screen).

So i'll post actions to recreate the bug, just so everyone could recreate it:
1) Use KDE as your test de.
2) Add widget "Global menu" anywhere to your desktop before the start of the application
3) Start the ide and create any workspace/project
4) Try to access any of the workspace/project functionality through "Global menu" widget.

Workaround: Restart the "Global menu" when application is already running.

**Comment by dghart** [comment]
Thanks for the information. That makes it happen here too.

However this is not a CodeLite-specific issue, but is likely to apply to (at least) any wxWidgets program. I tested one other, 4pane, with similar results. I suspect that any solution will come from wxWidgets or, better, the Global Menu itself. So, unless you discover a fix, I feel this bug can be closed.

Many thanks for your time and effort diagnosing the problem!
