### ISSUE TITLE
Code #if 0 ... #endif colored grey doesn't work

### ISSUE THREAD

**Issue by GiampietroIT** [eranif/codelite#2517]
Hi,
I am using CodeLite 13.0.8

coding with :

**#if 0**
...
...
...
**#endif** 

is not in gray color.

I have already check _Settings->code Completion->Colouring->Track PreProcessors Blocks_
but it doesn't work.

![image](https://user-images.githubusercontent.com/66357764/83614564-a8d53580-a585-11ea-9ddb-71292ed29306.png)

**Comment by eranif** [comment]
which version of wxWidgets is this?

**Comment by GiampietroIT** [comment]
I installed "codelite-amd64-13.0.8.exe"
I use it on windows.

how can i Know the version of wxWidgets?

**Comment by eranif** [comment]
OK, so it's Windows - so it does not matter.
Can you please download the latest?

**Comment by GiampietroIT** [comment]
I installed the version 14.0.0 (codeite-amd64-14.0.0.exe for windows) but the problem is the same.
Also, the font size is different from version 13.0.8 .

**Comment by GiampietroIT** [comment]
There is the same problem. I try also to recreate workspace with version 14.0.0 (codelite-amd64-14.0.0), but the problem is already present.
Also, the font is different: is bigger than before (or the zoom is bigger than before...)
