### ISSUE TITLE
problem with the debugger

### ISSUE THREAD

**Issue by flosi94** [eranif/codelite#2522]
hi, I am new to coding and I have a problem with the debugger, when I put a breakpoint,  and run the code, the breakpoint disappears, and there is no arrow to guide me on which line the code is working, 
Also, what should I put in setting> dbg settings> GNU gdb debugger for it to work properly ?

Thanks.

**Comment by dghart** [comment]
Hi,

You have not provided the minimum information needed for any bug-report: which platform you are using; which version of the platform and, for Linux, which distro; and which CodeLite version. You should also provide details about the CodeLite Workspace and Project type that you are testing.

Without that information it's hard to know even if this should really _be_  a bug-report here, or whether a post on the [CodeLite forum](https://codelite.org/forum/) would be more appropriate.

>Also, what should I put in setting> dbg settings> GNU gdb debugger for it to work properly?

You shouldn't need to do anything there. When you installed CodeLite and ran the Setup wizard, the available debugger(s) should have been discovered and set up correctly. If you didn't run the wizard, do so now (from Help menu). (If you don't _have_ a debugger installed, correct that first!)

**Comment by flosi94** [comment]
thanks for your answer, I am on windows 10, I am using codelite 14.01, , and my compiler is mingw64 8.1, my project is really simple, just a main, a for loop, and a few int,  I am studying c++, via udemy, I have a part of my module is about the debugger, just wanted to put the breakpoint before the loop and see how the loop works. I already tried the wizard, the settings didn't change

**Comment by dghart** [comment]
I don't use Windows, so I personally can't help you. However this doesn't sound like a CodeLite bug; lots of people with a similar setup do succeed in debugging.

I suggest you join the [CodeLite forum](https://codelite.org/forum/). You can then search for previous threads on this subject; I think you'll find several, often to do with spaces in the debugger path.
