### ISSUE TITLE
Suggestion: get rid of initial wizard and default to generic file workspace view for any workspace

### ISSUE THREAD

**Issue by ell1e** [eranif/codelite#2528]
Hi! I just tried codelite, and the way it asks early for the specific language profile seems to be a bit stuck in the past. Specifically, I chose PHP & js & ... anyway, then picked just the generic workspace view for my first workspace, and yet clangd worked just fine. Which led me to wonder, what is even the point of all these dialogs if it's not really relevant for the language backends that I can use later?

Given how streamlined Atom and VS Code and other modern editors are in opening up and just letting you open any folder, I suggest to get rid of that preselection and just allow running any language server or other language suppor just as files with matching extensions are found to be present. (The Workspace settings could still allow disabling some of them if undesired, but by default they could just be all enabled.)

I also got curious and opened up the `.workspace` file, and even with the generic settings, certain `"file_extensions"` are just hardcoded which again seems a bit oddly restrictive and backwards. I suggest to just remove that key (or default it to `"*.*"`) and go by extensions handled by available plugins / language servers, and only add in that key back in if in workspace options the user decides to restrict language processing to certain file extensions in their workspace.

Some more detailed reasons why I think all these language preselection dialogs should go:

* It gives away the wrong impression that outside of PHP, Node.js, Javascript, C, and C++, there really won't be any usable support while you actually seem to support *any* language servers, going as far as letting users manually add them in from anywhere on disk (which is great!)

* What if I have both PHP and C/C++ in a project?

* Why ask at the startup anyway when I haven't even opened up a workspace, what if I use one of these subsets in each workspace, but not the same for all workspaces?

In the end it's therefore not really clear why this is asked at startup anyway, what the selection will do and restrict me to, and I suggest to just get rid of it.

**Comment by eranif** [comment]
You are looking at CodeLite as generic IDE. It is not. It's main purpose is C++/C.
The default workspace (NOT the file workspace) is designed towards that: automatic build system, configured debugger and other features that are meant for C++
The file system workspace is designed to provide another capability to users who wishes to do more. Changing the default for the sake of "minority" users is wrong (imo)

**Comment by ell1e** [comment]
Even if it's for C/C++ users, it doesn't make any sense: why even prominently offer the PHP/webdev alternative then? Why would you ever ask for the language to be mainly used at *IDE initialization time*? It just doesn't make much sense.

**Comment by ell1e** [comment]
> automatic build system, configured debugger and other features that are meant for C++

For what it's worth, couldn't you just make a dialog pop up that asks whether this is to be enabled if any C/C++ file is picked up (either as already present, or when added for the first time later by user) in the workspace?

What really confuses me is how easy it would be to not show all of these wizards and things with a few minor changes. And I don't see how C/C++ users would appreciate confirming 2+ times what language they use either, once at IDE where it does seem pointless and once at workspace creation where it could easily be tied to detecting the .c/.cpp files and only asking then as described above. Instantly would give everyone a better experience, wouldn't it? (C/C++ users or not)
