### ISSUE TITLE
Support building CodeLite on Illumos/OpenIndiana?

### ISSUE THREAD

**Issue by hoper-a11y** [eranif/codelite#2529]
Please consider it. Since there is no guide for this platform (I think it's not supported at all) I don't know how to build CodeLite on it. But at least I could compile wxGTK from source just fine with the system's gcc 7.5.0. Clang also available, though. Do I need to use Clang instead of GCC? Thanks.

C++ IDE is very lacked on this system. There is Qt5 library but no QtCreator. I tried to compile CodeBlocks (another wxGTK based IDE) but failed and I can't access their forum to asking for help. So I think I should go with CodeLite.

**Comment by dghart** [comment]
I create (unofficial) CodeLite packages for some Linux distros and, while I've nothing against OpenIndiana, I have no knowledge of, or experience with it. That situation is highly unlikely to change. So there's approximately zero chance of this feature-request being actioned.

> I could compile wxGTK from source just fine.

Good. You'll need at least wxGTK-3.0.4, and preferably 3.1.3 as that's what we normally use for testing.

>Do I need to use Clang instead of GCC?

I use GCC on Linux so, unless OpenIndiana is in some way different...

>I don't know how to build CodeLite on it.

A CodeLite build uses cmake. You'll no doubt find that you need to amend (at least) the main CMakeLists.txt, but I suggest you start by just building as though you were using Linux. When you get errors, "google is your friend" ;) .

See also [this forum thread](https://codelite.org/forum/viewtopic.php?f=3&t=2308&p=10470&hilit=OpenIndiana#p10470).

Good luck!
