### ISSUE TITLE
How to re-include a file that was excluded from the build

### ISSUE THREAD

**Issue by HarryRexv1** [eranif/codelite#2534]
I have just started using codelite for a small C project. I am impressed. It is certainly quicker than trying to install and use a heavier IDE.  One small aspect - I have excluded a file from the build and now I want to re-include it back into the build. Thank you.
.

**Comment by iHardRock** [comment]
Right click on excluded file and remove check near "Exclude from  Build"

**Comment by HarryRexv1** [comment]
Unfortunately the "Right click on excluded file and remove check near 'Exclude from Build' " recommendation does not work for me.

Right clicking gives me a list of 12 choices. Exclude from build is one of th choices but there is no check box orothe means to reverse the exclude build. I am using Codelite version 14.0.0 and Ubuntu Mate 20.04.

Thank you.

**Comment by dghart** [comment]
Strange. I just tested in Xubuntu focal:
![ExcludeFromBuild](https://user-images.githubusercontent.com/6452587/88475419-85948a00-cf27-11ea-8e0c-1fe9d41e4051.png)

What sort of workspace/project are you using? C++, File System Workspace,...PHP?
