### ISSUE TITLE
Insert Doxygen comment from context menue doesn't work on class metods

### ISSUE THREAD

**Issue by AJenbo** [eranif/codelite#2535]
Right-clicking the method of a class and selecting Code Generation->Insert Doxygen comment doesn't work (no comment added, no errors). Relevant function: `PHPEditorContextMenu::OnInsertDoxyComment)`

Sample, and result:
```PHP
<?php

class test
{
    public function test(): void
    {
    }
}
```

**Expected result:**
```PHP
<?php

class test
{
    /**
     * 
     * @return void 
     */
    public function test(): void
    {
    }
}

```

But if it is instead a function it works as expected.

```PHP
<?php

{
    public function test(): void
    {
    }
}
```

**Comment by AJenbo** [comment]
it's a real bug, but I'm not planing on fixing it my self.

**Comment by eranif** [comment]
this only seems to be broken with the context menu.
Using the keyboard works as expected.

You can type `/**` followed by enter on top of the function method and it will work

**Comment by AJenbo** [comment]
@eranif correct, that's why the title contains "from context menu" :) It's also why I haven't bothered fixing it since I always use the other way of doing it :shrug:
