### ISSUE TITLE
Unable to scroll horizontally to end of long lines using mouse

### ISSUE THREAD

**Issue by Kanimies** [eranif/codelite#2536]
The issues seems to exists both on Windows and OS X platforms; when editing files with long lines, they cannot be browsed by scrolling the screen horizontally to the end of the line either using the horizontal scroll on mouse or using the scroll bar in the bottom of the editor screen. Sometimes moving the caret to the end of such line using cursor keys seems to enable scrolling all the way from that moment onwards.

**Comment by eranif** [comment]
this is a scintilla "feature"... it uses some hard coded default horizontal scrollbar width to increase performance.
if you with be able to scroll with the mouse to the end of the line, you can enable this option in CodeLite:

`Settings -> Preferences -> Caret & Scrolling -> Allow adjust horizontal scrollbar width`
