### ISSUE TITLE
"Clean" command does not delete output file

### ISSUE THREAD

**Issue by davidecapod** [eranif/codelite#2541]
The "clean" command only deletes the "intermediate" folder, but it does not explicitly delete the output file.
So if you change project settings to generate the output OUTSIDE the intermediate folder, it will never be deleted.
This is particularly critical when generating libraries, because .o files will always be added inside the old .a ...

So, the "clean" target in the generated .mk file should add "rm $(OutputFile)"

**Comment by c-plus** [comment]
I got the similar problem. my platform is win7. Maybe CLEAN command needs use "del" instead of "rm".
