### ISSUE TITLE
Codelite weekly build crashes instantly on macOs Catalina 10.15.5. Codelite version 14.0 app and bundle for macOs also crashes instantly.

### ISSUE THREAD

**Issue by MrCherub** [eranif/codelite#2543]
I have removed every single file and directory pertaining to Codelite on Mac terminal and afterwards I tried running the application again after reinstalling but nothing changed; the application crashes regardless. Nothing I do seems to fix this issue.

**Comment by MrCherub** [comment]
The issue was resolved by deleting library/application support/codelite folder

**Comment by FiorellaSieBe** [comment]
where is this folder im on mac
