### ISSUE TITLE
Question about weekly build releases

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2544]
Hi,
I'm maintaining the Arch Linux AUR package for codelite

My current "strategy" has been only to update the package on stable releases - which seems to happen about once every year

I'm thinking of providing another unstable package of codelite that would follow what you call weekly builds.
But in order to follow your weekly build "preview/point releases" I would need some sort of tag - or at least a SHA to base my build on in order to produce builds that (in contents) would match the builds that you provide.

Now I'm not asking you to go through a full-blown release process for your weekly builds - but it would be nice to have some sort of minimal release info (a SHa or something) that us package maintainers could rely on.

My guess is that other distribution packagers have the same need :-)

**Comment by eranif** [comment]
will git tag be sufficient?

**Comment by uffejakobsen** [comment]
> will git tag be sufficient?

Yes, that would be perfect :-)

thanks :+1:

**Comment by uffejakobsen** [comment]
Thanks a lot for the git tag (14.0.2)

I've now created a new AUR package "codelite-unstable" that will follow your weekly/latest tags as they are published

I'm closing this issue - Thanks a lot :+1:
