### ISSUE TITLE
Using SFTP with publickey displays "Interactive Keyboard is not enabled"

### ISSUE THREAD

**Issue by chrisstjohn** [eranif/codelite#2548]
In SSH account manager I leave the password field blank, expecting that PuTTY/Pageant will be used to supply my credentials. When I try "Test Connection" or I attempt to connect using the connection I get a pop-up window (graphic attached).

Using "Quick Connect" with a password works fine.

![image](https://user-images.githubusercontent.com/9963744/88149892-975cf100-cbf8-11ea-97fa-6d99e17179ba.png)

I'm using Codelite 14.0.0 in Windows 10 Pro 64-bit.

**Comment by eranif** [comment]
CodeLite does not support PuTTY keys. only OpenSSH keys
If you can connect using ssh command line tool (NOT putty) with a key (which is usually placed under `%HOMEPATH%\.ssh`)
CodeLite will be able to do that as well
