### ISSUE TITLE
Allow only single instance running not working on Windows

### ISSUE THREAD

**Issue by jupeos** [eranif/codelite#2551]
Windows 10 Pro: 10.0.18363
Codelite: 14.0.0 but also occurs in 14.0.2
A new instance of CodeLite is created when doubling clicking to open a source file from a file manager.

**Comment by jupeos** [comment]
This is still a problem

**Comment by AJenbo** [comment]
I was unable to reproduce this issue with CodeLite 14.0.4 on Ubuntu 20.10 (tested both with a PHP, C++, and no project open).
Could you confirm that you are still seeing this issue since it might be Windows specific?
