### ISSUE TITLE
Blank after closing opened file

### ISSUE THREAD

**Issue by NoorWachid** [eranif/codelite#2552]
OS: Arch Linux
Version: CodeLite IDE 14.0.0

CodeLite goes blank after closing some opened file. I tried to close the program and open it again, still blank. Then I tried to close the workspace and open it again still blank. But when I open another workspace It's fine.

![image](https://user-images.githubusercontent.com/42460975/88241982-01879b80-ccb6-11ea-9784-cec5de88e9e4.png)

**Comment by NoorWachid** [comment]
Addition after I can reopen the workspace this happened.
![image](https://user-images.githubusercontent.com/42460975/88242381-2e887e00-ccb7-11ea-9dab-177b8cbc325e.png)

**Comment by Imsaksham009** [comment]
may be you should try to reinstall it

**Comment by eranif** [comment]
You expanded the 'workspace view' to capture the entire screen.
To fix this, from the main menu: Perspective -> Restore default layout
Please re-open if the problem persist
