### ISSUE TITLE
Crash on RegEx replace

### ISSUE THREAD

**Issue by buergi** [eranif/codelite#2554]
OS: Windows 10,
Version: Codelite 14.0.0

DO
Create a new empty file, insert a single space.
Press CTRL+H, enable Regex and replace " *$" by "" (all without the quotes of course).

HAPPEN
CodeLite hangs indefinitely and can only be force closed.

SHOULD
Remove all spaces at the line endings.

**Comment by Jarod42** [comment]
Even if avoiding crash would be good, should it be ` +$` as currently, eof match in-definitively.
BTW, CL has `Edit/Trim trailing space` and also similar option on `Settings/Preferences/Save options`

**Comment by buergi** [comment]
Thanks @Jarod42 I found this trim option by accident and consider it indeed very useful. Regarding the regex you are of course right that + would be the proper way, however I did never face any problems with infinite recursions in other editors or IDEs (vim, SciTE, Eclipse). Regex should never leed to infinite recursions.
