### ISSUE TITLE
Very high CPU usage on MacOS

### ISSUE THREAD

**Issue by MrCherub** [eranif/codelite#2561]
As soon as I open up codelite the fans start getting loud due to all of my 6 CPU cores coming close to maxing out. It's heating up my MacBook Pro 2018 just as much as Stellaris in max 2k settings with high pop count. What can I do to fix this, I've used numerous IDE's and I haven't had any of them do this.

**Comment by uffejakobsen** [comment]
I've seen problems with the newly introduced language server feature having a (sub) process (clangd) that is constantly using one core - but not 6 cores...

**Comment by MrCherub** [comment]
> I've seen problems with the newly introduced language server feature having a (sub) process (clangd) that is constantly using one core - but not 6 cores...

Yes this was all 6 cores.

**Comment by eranif** [comment]
Is it possible to have a stack trace?
