### ISSUE TITLE
hang on shutdown

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#2562]
100% repeatable, with current codelite trunk,  on Fedora 32.

stacktrace attached.

[codelite-stacktrace.txt](https://github.com/eranif/codelite/files/5055517/codelite-stacktrace.txt)

**Comment by eranif** [comment]
This looks like a corrupted configuration file.
Did you try deleting it?

it's under: `~/.codelite/config/codelite.conf`

**Comment by grandinj** [comment]
The codelite.conf file looks like.

I deleted the codelite.conf and tried again - same problem.

So I rebuilt codellite with symbols and tried again - got the attached stacktrace - notice how it is trying to show a dialog, but no dialog is actually visible.
This smells strongly like a shutdown ordering problem, where something is trying to access code/data that already been freed or unloaded.

[codelite-stack2.txt](https://github.com/eranif/codelite/files/5101358/codelite-stack2.txt)
