### ISSUE TITLE
Stack size limit ?

### ISSUE THREAD

**Issue by peijason** [eranif/codelite#2565]
Hi, @eranif 

I wanna allocate a very big stack, say, 48M in a stack, but always failed with the following **SIGSEGV ERROR**:

![Screenshot from 2020-08-25 15-43-49](https://user-images.githubusercontent.com/68356184/91235190-e27f8d80-e6e9-11ea-9025-132860bbf406.png)

So, where can I enlarge the stack size in **Codelite**? My code snippet is:

```console
typedef struct __capture_image
{
  char data[2160*3840*3];
  unsigned int width;
  unsigned int height;
  unsigned int channels;
} capture_image_t;
```

**Comment by Jarod42** [comment]
Option/flags might depend of OS, compiler:

See for example https://stackoverflow.com/questions/2275550/change-stack-size-for-a-c-application-in-linux-during-compilation-with-gnu-com

In your project settings, in compiler options, set appropriate flags in C compiler options

**Comment by hrithiksh101** [comment]
you can allocate the memory in heap if you want to use this much memory , 

typedef struct __capture_image
{
  char *data = new char[2160*3840*3];
  unsigned int width;
  unsigned int height;
  unsigned int channels;
} capture_image_t;

**Comment by hrithiksh101** [comment]
you can allocate the memory in heap the problem is you can store this amount of memory directly in a address , but you can use
heap . like -

typedef struct __capture_image
{
  char *data = new char[2160*3840*3];
  unsigned int width;
  unsigned int height;
  unsigned int channels;
} capture_image_t;
