### ISSUE TITLE
Code Completion

### ISSUE THREAD

**Issue by petergarcia666** [eranif/codelite#2566]
when I type in three letters, a very small empty square appears where the code completion box should be, and when I press enter, what I assume is the first option in the nonexistent code completion box is entered.

**Comment by dghart** [comment]
Hi,

Which platform and CodeLite version and (maybe most important here) which wxWidgets version?

The last may be relevant as I get a similar problem with the debugger 'tooltip': the dialog that appears when you hover over a variable when the debugger is paused, to show its contents. I can use the mouse to expand it, whereupon it remembers its size for the rest of the debugging session.
My problem occurs only in GTK+3 builds of wxWidgets 3.1.4. If that's what you're using, you have an obvious workaround...

Regards,

David

**Comment by petergarcia666** [comment]
I cant figure out what version of wxWidget I'm using, and if you know how I can find that out, that would be great; but the CodeLite version is 14.0.2..
Some further details I've discovered about the issue; When the code complete box should show up (but doesn't), if I press the down arrow any number of times, then press enter, it inputs the phrase that would've been highlighted in the code completion box, if it were visible.
Thank you for the reply!

**Comment by petergarcia666** [comment]
Sorry, didn't mean to close it.

**Comment by dghart** [comment]
>CodeLite version is 14.0.2.

Thanks. And which platform? Windows? OSX? Linux?

>I cant figure out what version of wxWidget I'm using

With CodeLite open and focused, do: Ctrl+Alt+Middleclick
The resulting dialog will show the wxWidgets toolkit and version, and (for Linux) also the GTK+ version.

**Comment by petergarcia666** [comment]
I actually figured it out through trial and error! Apparently it was because of the font I was using. It was one of the @Microsoft fonts, and I guess code completion doesn't like those ones. Thank you for the replies.
