### ISSUE TITLE
Add Function Implementation only works on saved declarations

### ISSUE THREAD

**Issue by buergi** [eranif/codelite#2572]
OS: Windows 10,
Version: Codelite 14.0.0

DO
Open into any header file, add some declaration, e.g. void foo();
Right click "foo" and Code Generation / Refactoring > Add Function Implementation

HAPPEN
Nothing

SHOULD
"Add Function Implementation" Dialog should open

WORKAROUND
Save the header file and try again => works
While not being a very cumbersome workaround I run into this problem very often and would appreciate if this feature would also work on unsaved changes.

**Comment by eranif** [comment]
this is now fixed in latest git master
