### ISSUE TITLE
Code is built and run fine, but Codelite still shows error!

### ISSUE THREAD

**Issue by MichoHaddad** [eranif/codelite#2573]
I have this error:  'iostream' file not found , which generates follow-up errors like: "use of undeclared identifier 'cout' ".
But when I build the code, it states that there are 0 errors, and the code executes and runs fine.

I am using MinGW as a compiler.

Here is a screenshot of the code:
![Untitled](https://user-images.githubusercontent.com/70548621/91777037-77f1b480-ebf7-11ea-8dda-2fcb96701383.png)

**Comment by Jarod42** [comment]
I would say LSP misconfigured

**Comment by noby1979** [comment]
<img width="6296" height="808" alt="Image" src="https://github.com/user-attachments/assets/f964c9b7-ab48-4667-a2a9-3a50431d7a36" />

<img width="1246" height="808" alt="Image" src="https://github.com/user-attachments/assets/d972eacb-44a5-4e43-ba0f-316e99bec825" />

**Comment by noby1979** [comment]
I am getting it. please create workspace and run.
https://drive.google.com/file/d/16FZ9-Lg9uksczTmrWFcorx3vOqt7bZJI/view?usp=drive_link
it wokrs with c:\MinGW. install mingw installer from sourceforge.Restart codelite and the system.

**Comment by noby1979** [comment]
exit code 32760, there was a problem with earlier configuration.sorry

**Comment by noby1979** [comment]
<img width="6976" height="808" alt="Image" src="https://github.com/user-attachments/assets/b95380a0-dd77-4ea7-9537-a586fba204d3" />

**Comment by noby1979** [comment]
<img width="1213" height="808" alt="Image" src="https://github.com/user-attachments/assets/870d487e-9f1f-4236-93b1-6d822abea36b" />

<img width="1219" height="818" alt="Image" src="https://github.com/user-attachments/assets/961fadbb-3f6b-4cbc-a449-c2b3478ba35b" />

<img width="1207" height="812" alt="Image" src="https://github.com/user-attachments/assets/5f4f815e-6973-4eca-ac92-d344e80a9f90" />

<img width="1245" height="882" alt="Image" src="https://github.com/user-attachments/assets/899f2b2f-4fea-4c21-ba5a-d7c2714d0383" />

<img width="1184" height="834" alt="Image" src="https://github.com/user-attachments/assets/9fe66b97-cab6-407e-ad47-c484b3f26b06" />

<img width="1123" height="847" alt="Image" src="https://github.com/user-attachments/assets/27cf46bf-fdb6-4865-82ca-ca931a92832c" />

**Comment by noby1979** [comment]
https://github.com/skeeto/w64devkit

https://github.com/skeeto/w64devkit/releases/tag/v2.3.0

install widows devlopment kit for c++ form github. 

If you are using MinGW for local use rename "mingw32-make.exe" to "make.exe" and make this 

your make file. In devlopment kit no such problem and use it mirror online gui or console 

devlopment. For local development minimalist gnu enough.

This is link to the windows configuration debug. 

https://drive.google.com/file/d/1C_Ew9O2-efLWZKZ4qvRH5IXEFKqhb3ZY/view?usp=sharing

make sure the "make.exe" file 214 kb in size. You can install mingw32-make.exe using mingw-

get in minimalist gnu using the command "mingw-get install mingw32-make.exe" from cmd 

with administrative priviledges. For remote workspace use widows devlopment kit for c++ form 

github. For local  MinGW. you have to delete C:\Users\noby\AppData\Roaming and the screen 

must refresh in quick debug. The file will be complied in the debug folder in the workspace 

directory.  The details will be in the compile_commands.json file.

<img width="1017" height="700" alt="Image" src="https://github.com/user-attachments/assets/bcb9cc35-fa54-446d-a7d5-3e7be047c760" />

**Comment by noby1979** [comment]
<img width="1241" height="938" alt="Image" src="https://github.com/user-attachments/assets/5630a558-a108-4d21-859c-46cfb92ff0c2" />

<img width="1271" height="674" alt="Image" src="https://github.com/user-attachments/assets/68b2e55f-502c-4132-b3fe-c02820460699" />

I hope you got output in folder debug.
