### ISSUE TITLE
CodeLite doesn't showing the "Elapsed time" in the output

### ISSUE THREAD

**Issue by jack-gcc** [eranif/codelite#2574]
When ai run a project that converting euro into dollar the output doesn't shows the "Elapsed time"

**Comment by dghart** [comment]
(Which platform? Which CodeLite version?)

It works for me.
Maybe your project does not take long enough to build.If you look at the source code:

    long elapsed = m_sw.Time() / 1000;
    if(elapsed > 10) {
        long sec = elapsed % 60;
        long hours = elapsed / 3600;
        long minutes = (elapsed % 3600) / 60;
        term << wxString::Format(wxT(", %s: %02ld:%02ld:%02ld %s"), _("total time"), hours, minutes, sec, _("seconds"));
    }


you will see that time is only output if it's >10sec
