### ISSUE TITLE
Overheating on my Mac

### ISSUE THREAD

**Issue by kartikayprashar** [eranif/codelite#2576]
Hi,

My Mac is running Mac OS Catalina 10.15.6. I am using CodeLite 14.0 App Bundle for OSX 10.15. My Mac is overheating very much and CPU usage is very high. Can anyone help me solve this issue?

Thanks,

Kartikay

**Comment by dghart** [comment]
Hi,

See https://github.com/eranif/codelite/issues/2561. I suggest you disable the Language Server plugin (which was subsequently shown to be the culprit).

Regards,

David

**Comment by kartikayprashar** [comment]
I did though!

**Comment by AJenbo** [comment]
I'm going to mark this as a duplicate of https://github.com/eranif/codelite/issues/2591 despite this one being older, but this issue has little to no info to go one where the other has a bit more and from a glance, they appear to be the same issue even if the actual cause is opaque to us atm.

**Comment by kartikayprashar** [comment]
@AJenbo  Im using Xcode now. Codelite doesn't work on my Mac after the updates unfortunately. Thanks though!
