### ISSUE TITLE
Opening a .txt file with default application in Linux

### ISSUE THREAD

**Issue by tataDan** [eranif/codelite#2577]
I am using CodeLite 14.0.0 in Debian Linux 10 (gnome).

When I right-click on a .txt file in a src folder in a project and choose "Open with Default Application", the file opens with LibreOffice Writer.

I have done some web searching on making gedit the default editor without reaching any definitive conclusions.  The most promising suggestion I found was to use mimeopen. 

When I enter "mimeopen file.txt", gedit does open the file, which, to me, is an indication that gedit might be the default text editor.

How do I make CodeLite open it with gnome gedit (or any other text editor) instead?

Thanks

**Comment by dghart** [comment]
CodeLite is built on the wxWidgets toolkit.  wxWidgets has a function that gets the appropriate mime-type for an ext, and CodeLite uses this in Open with Default Application.

Unfortunately gnome seems to do something strange (well, it does lots of other strange things too): even after using `mimeopen -d`to change the official default, it ignores that setting and uses libreoffice. This can be seen in the 'exec' wxWidgets sample:
![ExecSampleFileExt](https://user-images.githubusercontent.com/6452587/93715988-a0206380-fb64-11ea-940e-f0581264762b.png)
This is  not a CodeLite problem, it's a gnome bug. I don't have any solution to suggest, other than changing to a different DE.

**Comment by tataDan** [comment]
Thank you very much for your detailed explanation.

I believe that I have resolved the problem by adding a file named "defaults.list" to my $HOME/.local/share/applications directory. This file consists of the following lines:

`[Default Applications]

text/plain=org.gnome.gedit.desktop`
