### ISSUE TITLE
Generate a generalized makefile from CodeLite GUI?

### ISSUE THREAD

**Issue by peijason** [eranif/codelite#2580]
Hi, @eranif :

Is there any easy easy to generate a generalized **makefile** from CodeLite GUI? Instead of file.mk ?

Are they the same BTW?

Cheers

**Comment by peijason** [comment]
@eranif 

Got it but failed to build the project from within **CodeLite GUI**.


Always obtained the following **ERROR** message.

```console
libopencv_core.so: file too short
collect2: error: ld returned 1 exit status
make[1]: *** [MyTest.mk:79: Debug/MyTest] Error 1
make[1]: Leaving directory '.../MyTest
make: *** [Makefile:5: All] Error 2
```


Cheers
Pei

**Comment by eranif** [comment]
These are the same files. Different name.
The above error is not Makefile related - it has to do with your setup (truncated files etc)
