### ISSUE TITLE
Styles Error

### ISSUE THREAD

**Issue by VAKHANDER** [eranif/codelite#2587]
Good mormimg, after installing CodeLite i cant choose any themes, Codelite have only default, if i choose Dark theme programm closes. What can i do?

**Comment by VAKHANDER** [comment]
![image](https://user-images.githubusercontent.com/72333765/95009403-7ff3a880-062a-11eb-8e88-172e3ffa5b6e.png)

**Comment by VAKHANDER** [comment]
Also then i try to run the program CodeLite closes with error

**Comment by AJenbo** [comment]
Try deleting the config folder from your %appdata% folder.
