### ISSUE TITLE
Find in files requires explicit left click on Workspace directory even when directory is already selected

### ISSUE THREAD

**Issue by Kanimies** [eranif/codelite#2589]
When a directory is already selected in workspace, right click context menu item "Find in Files" has scope of "* Entire workspace" unless the directory is first selected again with left click first.
<img width="322" alt="html is selected - right click to context menu" src="https://user-images.githubusercontent.com/7421922/95161642-65493d00-07ac-11eb-9b1d-38f8c5c4bac1.png">
<img width="415" alt="search scope entire workspace" src="https://user-images.githubusercontent.com/7421922/95161661-709c6880-07ac-11eb-8dd0-205ecef097c1.png">

**Comment by AJenbo** [comment]
I'm unable to replicate this on Ubuntu 20.10. Whenever I right-click a folder it gets selected and the Find In FIles dialog reflects the folder that I selected.

Could you specify more exactly what needs to be done to replicate this, possibly via a short video?

**Comment by Kanimies** [comment]
I'm working on a Mac so maybe it's OS X version related?

If I select a folder from the explorer, then click in the editing window so the Workspace / explorer component is not the active one and now right click on the previously selected folder and choose Find in Files it gives me <Entire Workspace> scope every time. 

If I first select a folder by left clicking it and immediately proceed to right click the same folder and choose Find in Files, the scope is correct. So I'm assuming it has to do with the explorer element losing focus in between.

**Comment by eranif** [comment]
I believe this is the culprit:
```
void PHPWorkspaceView::OnFindInFilesShowing(clFindInFilesEvent& e)
{
    e.Skip();
    if(!PHPWorkspace::Get()->IsOpen())
        return;

    // Mask is always loaded from the configuration
    wxString mask = "*.php;*.inc;*.phtml;*.js;*.html;*.css;*.scss;*.json;*.xml;*.ini;*.md;*.txt;*.text;.htaccess;*.sql";
    e.SetFileMask(clConfig::Get().Read("FindInFiles/PHP/Mask", mask));

    if(m_treeCtrlView->IsShownOnScreen() && m_treeCtrlView->HasFocus()) {
        // Get list of selected folders
        wxArrayString folders;
        DoGetSelectedFolders(folders);
        if(folders.IsEmpty()) {
            return;
        }

        wxString paths;
        for(size_t i = 0; i < folders.size(); ++i) {
            paths << folders.Item(i) << "\n";
        }
        paths.Trim();
        e.SetTransientPaths(paths);
    } else {
        wxString lookIn;
        lookIn << "<Entire Workspace>\n"
               << "-*vendor*";
        e.SetPaths(clConfig::Get().Read("FindInFiles/PHP/LookIn", lookIn));
    }
}
```

**Comment by eranif** [comment]
what is the expected behavior?

**Comment by Kanimies** [comment]
I would expect the scope to reflect the selected folder / directory as nothing should change between selecting the workspace window and right clicking the folder / directory that already is selected / has focus on the directory tree.

**Comment by eranif** [comment]
the problem might be that usually when you switch to a file in the editor, the file will be selected in the tree view, so should we pick the parent folder?
this might not be the folder that you want to use for find in files.
How about, making it simple: ignore the selection in the tree view just remember what folder I used last time?

**Comment by Kanimies** [comment]
The thing is the active file in the editor will not get selected until it is changed, so if I'm editing a.php, click around the workspace/explorer and say, select html - folder, then go back to editing a.php again, the html-folder will still remain active / have focus in the workspace/explorer. Only when I click on another open file tab on the editor (say, b.php) will that file be highlighted / selected in the tree view.

**Comment by Kanimies** [comment]
So the solution would be that the scope would reflect what is shown visible / having focus in the tree view. If it's a.php, then I'll know to left click on html- folder first, but if the focus is already on html (as in my example above) I'm not expecting that I have to left click it to select it 'again' before the scope and focus will really be on that folder. 

So either unselect it when the tree view loses focus to force the user to left click again, or make the context menu actually act like it's in context to the selected folder

**Comment by Kanimies** [comment]
Seems that now you can't select the project root folder at all for search context - the Find in Files Search in: input won't change to reflect the root folder but stays at whatever was its previous value. The initial bug reported here seems to be fixed now but a new one has been introduced.

**Comment by Kanimies** [comment]
![Folder selected - reflects path](https://user-images.githubusercontent.com/7421922/115955060-18854380-a4fd-11eb-80ba-3ec9a571a405.png)
![Project root selected - path not changed](https://user-images.githubusercontent.com/7421922/115955062-1a4f0700-a4fd-11eb-8c35-0ec7cba8019c.png)

**Comment by eranif** [comment]
this should be fixed now. I also changed the tree to be "multiple selection" enabled
