### ISSUE TITLE
Build options grayed out 

### ISSUE THREAD

**Issue by mgrigoni** [eranif/codelite#2592]
I'm running v14.0.4. For some reasons all options on Build menu are grayed out, but everything functions
properly when using icons or context menus

**Comment by eranif** [comment]
We have seen this issue before and it is related to the selected desktop.
I am guessing you are using ubuntu with the default gnome desktop.
The only way to workaround is, it to use a different desktop environment 
FYI: it's not a CodeLite issue but rather the underlying GUI library

**Comment by mgrigoni** [comment]
Thanks. Yes, Ubuntu, I'm running it on Jetson Xavier. Like some other user noted, the Build menu items are no longer greyed out if I launch codelite under sudo
