### ISSUE TITLE
On startup of Codelite the display become grey 

### ISSUE THREAD

**Issue by Zkitto** [eranif/codelite#2595]
Codelite version: 14.0.2
_When I start Codelite appear for a second the main screen and after the screen become grey. How can I fix?_ 

![Screenshot (3)](https://user-images.githubusercontent.com/72996959/96300309-9a982b00-0ff5-11eb-8662-a4abdbbd7949.png)
![Screenshot (4)](https://user-images.githubusercontent.com/72996959/96300326-9e2bb200-0ff5-11eb-91b8-96a34657b356.png)

**Comment by eranif** [comment]
I think you have a workspace opened, but no files are opened in the session.
The frame title `[ Documents ]` means that you have a workspace named `Documents` opened.
If you click `Ctrl-Alt-W` it will make the workspace pane visible again
