### ISSUE TITLE
Unable to see locals when debugging in latest codelite version..

### ISSUE THREAD

**Issue by KrunalKaneriya** [eranif/codelite#2597]
I have latest codelite weekly build and latest mingw installed but when I start to debug a program I cannot see the local variables defined in locals tab. If I define explicitly in watches tab then it works but in locals tab there is literally nothing showing. 

But in codelite 13 I can see the locals variables in locals tab when debugging. Please any suggesstion and I love your IDE please help.

Here this is the log when starting debugging.

Using gdbinit file: C:\Users\Krunal\.codelite-gdbinit
Current working dir: C:\Users\Krunal\Documents\C++_Programming_Udemy\Classes_and_objects\Practices
Launching gdb from : C:\Users\Krunal\Documents\C++_Programming_Udemy\Classes_and_objects/build-Debug/lib
Starting debugger  : C:/MinGW/bin/gdb.exe --command="C:\Users\Krunal\.codelite-gdbinit" --interpreter=mi "C:\Users\Krunal\Documents\C++_Programming_Udemy\Classes_and_objects/build-Debug/bin/Practices"
DEBUG>>set  new-console on
DEBUG>>set unwindonsignal on
DEBUG>>set breakpoint pending on
DEBUG>>set print object on
DEBUG>>set width 0
DEBUG>>set height 0
DEBUG>>set print elements 200
DEBUG>>python
DEBUG>>import sys
DEBUG>>sys.path.insert(0, 'C:\Users\Krunal\AppData\Roaming\codelite\gdb_printers')
DEBUG>>from libstdcxx.v6.printers import register_libstdcxx_printers
DEBUG>>register_libstdcxx_printers (None)
DEBUG>>from qt4 import register_qt4_printers
DEBUG>>register_qt4_printers (None)
DEBUG>>from wx import register_wx_printers
DEBUG>>register_wx_printers (None)
DEBUG>>end
DEBUG>>00000001-break-insert -f -t main
DEBUG>>00000002-enable-pretty-printing
Debug session started successfully!
DEBUG>>00000003-exec-arguments
DEBUG>>00000004-exec-run
DEBUG>>=thread-group-added,id="i1"
=thread-group-added,id="i1"
DEBUG>>~"GNU gdb (GDB) 7.6.1\n"
GNU gdb (GDB) 7.6.1
DEBUG>>~"Copyright (C) 2013 Free Software Foundation, Inc.\n"
Copyright (C) 2013 Free Software Foundation, Inc.
DEBUG>>~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\n"
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type "show copying"\nand "show warranty" for details.
DEBUG>>~"This GDB was configured as \"mingw32\".\nFor bug reporting instructions, please see:\n"
This GDB was configured as "mingw32".\nFor bug reporting instructions, please see:
DEBUG>>~"<http://www.gnu.org/software/gdb/bugs/>...\n"
<http://www.gnu.org/software/gdb/bugs/>...
DEBUG>>~"Reading symbols from C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\build-Debug\\bin\\Practices.exe..."
Reading symbols from C:\Users\Krunal\Documents\C++_Programming_Udemy\Classes_and_objects\build-Debug\bin\Practices.exe...
DEBUG>>~"done.\n"
done.
DEBUG>>&"C:\\Users\\Krunal\\.codelite-gdbinit:14: Error in sourced command file:\n"
DEBUG>>&"Python scripting is not supported in this copy of GDB.\n"
DEBUG>>&"set  new-console on\n"
DEBUG>>=cmd-param-changed,param="new-console",value="on"
=cmd-param-changed,param="new-console",value="on"
DEBUG>>^done
DEBUG>>&"set unwindonsignal on\n"
DEBUG>>=cmd-param-changed,param="unwindonsignal",value="on"
=cmd-param-changed,param="unwindonsignal",value="on"
DEBUG>>^done
DEBUG>>&"set breakpoint pending on\n"
DEBUG>>=cmd-param-changed,param="breakpoint pending",value="on"
=cmd-param-changed,param="breakpoint pending",value="on"
DEBUG>>^done
DEBUG>>&"set print object on\n"
DEBUG>>=cmd-param-changed,param="print object",value="on"
=cmd-param-changed,param="print object",value="on"
DEBUG>>^done
DEBUG>>&"set width 0\n"
DEBUG>>=cmd-param-changed,param="width",value="4294967295"
=cmd-param-changed,param="width",value="4294967295"
DEBUG>>^done
DEBUG>>&"set height 0\n"
DEBUG>>^done
DEBUG>>&"set print elements 200\n"
DEBUG>>^done
DEBUG>>&"python\n"
DEBUG>>&"Python scripting is not supported in this copy of GDB.\n"
DEBUG>>^error,msg="Python scripting is not supported in this copy of GDB."
^error,msg="Python scripting is not supported in this copy of GDB."
DEBUG>>00000001^done,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x00401426",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="71",thread-groups=["i1"],times="0",original-location="main"}
Storing internal breakpoint ID=1
DEBUG>>00000002^done
DEBUG>>=cmd-param-changed,param="args",value=""
=cmd-param-changed,param="args",value=""
DEBUG>>00000003^done
>> Debuggee process ID: 2240
DEBUG>>=thread-group-started,id="i1",pid="2240"
=thread-group-started,id="i1",pid="2240"
DEBUG>>=thread-created,id="1",group-id="i1"
=thread-created,id="1",group-id="i1"
DEBUG>>~"[New Thread 2240.0x1d80]\n"
[New Thread 2240.0x1d80]
DEBUG>>00000004^running
Continuing...
DEBUG>>*running,thread-id="all"
*running,thread-id="all"
DEBUG>>=library-loaded,id="C:\\Windows\\SysWOW64\\kernel32.dll",target-name="C:\\Windows\\SysWOW64\\kernel32.dll",host-name="C:\\Windows\\SysWOW64\\kernel32.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\SysWOW64\\kernel32.dll",target-name="C:\\Windows\\SysWOW64\\kernel32.dll",host-name="C:\\Windows\\SysWOW64\\kernel32.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\SysWOW64\\KernelBase.dll",target-name="C:\\Windows\\SysWOW64\\KernelBase.dll",host-name="C:\\Windows\\SysWOW64\\KernelBase.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\SysWOW64\\KernelBase.dll",target-name="C:\\Windows\\SysWOW64\\KernelBase.dll",host-name="C:\\Windows\\SysWOW64\\KernelBase.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\Windows\\SysWOW64\\msvcrt.dll",target-name="C:\\Windows\\SysWOW64\\msvcrt.dll",host-name="C:\\Windows\\SysWOW64\\msvcrt.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\Windows\\SysWOW64\\msvcrt.dll",target-name="C:\\Windows\\SysWOW64\\msvcrt.dll",host-name="C:\\Windows\\SysWOW64\\msvcrt.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\MinGW\\bin\\libgcc_s_dw2-1.dll",target-name="C:\\MinGW\\bin\\libgcc_s_dw2-1.dll",host-name="C:\\MinGW\\bin\\libgcc_s_dw2-1.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\MinGW\\bin\\libgcc_s_dw2-1.dll",target-name="C:\\MinGW\\bin\\libgcc_s_dw2-1.dll",host-name="C:\\MinGW\\bin\\libgcc_s_dw2-1.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=library-loaded,id="C:\\MinGW\\bin\\libstdc++-6.dll",target-name="C:\\MinGW\\bin\\libstdc++-6.dll",host-name="C:\\MinGW\\bin\\libstdc++-6.dll",symbols-loaded="0",thread-group="i1"
=library-loaded,id="C:\\MinGW\\bin\\libstdc++-6.dll",target-name="C:\\MinGW\\bin\\libstdc++-6.dll",host-name="C:\\MinGW\\bin\\libstdc++-6.dll",symbols-loaded="0",thread-group="i1"
DEBUG>>=breakpoint-modified,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x00401426",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\\\Users\\\\Krunal\\\\Documents\\\\C++_Programming_Udemy\\\\Classes_and_objects\\\\Practices\\\\main.cpp",line="71",thread-groups=["i1"],times="1",original-location="main"}
=breakpoint-modified,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x00401426",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\\\Users\\\\Krunal\\\\Documents\\\\C++_Programming_Udemy\\\\Classes_and_objects\\\\Practices\\\\main.cpp",line="71",thread-groups=["i1"],times="1",original-location="main"}
DEBUG>>*stopped,reason="breakpoint-hit",disp="del",bkptno="1",frame={addr="0x00401426",func="main",args=[],file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="71"},thread-id="1",stopped-threads="all"
Internal breakpoint was hit (id=1), Applying user breakpoints and continuing
DEBUG>>00000005-break-insert -f "C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:68"
DEBUG>>00000006-break-insert -f "C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:69"
DEBUG>>00000007-break-insert -f "C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:71"
DEBUG>>00000008-break-insert -f "C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:72"
DEBUG>>00000009-break-insert -f "C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:73"
DEBUG>>00000010-break-insert -f "C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:74"
DEBUG>>00000011-break-insert -f "C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:75"
DEBUG>>00000012-break-insert -f "C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:76"
DEBUG>>00000013-file-list-exec-source-file
DEBUG>>00000014-break-list
DEBUG>>=breakpoint-deleted,id="1"
=breakpoint-deleted,id="1"
DEBUG>>00000005^done,bkpt={number="2",type="breakpoint",disp="keep",enabled="y",addr="0x00401426",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="68",thread-groups=["i1"],times="0",original-location="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:68"}
Found the breakpoint ID!
Storing debugger breakpoint Id=2
Successfully set breakpoint 2 at: C:\Users\Krunal\Documents\C++_Programming_Udemy\Classes_and_objects\Practices\main.cpp:68
DEBUG>>00000006^done,bkpt={number="3",type="breakpoint",disp="keep",enabled="y",addr="0x00401426",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="69",thread-groups=["i1"],times="0",original-location="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:69"}
Found the breakpoint ID!
Storing debugger breakpoint Id=3
Successfully set breakpoint 3 at: C:\Users\Krunal\Documents\C++_Programming_Udemy\Classes_and_objects\Practices\main.cpp:69
DEBUG>>00000007^done,bkpt={number="4",type="breakpoint",disp="keep",enabled="y",addr="0x00401426",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="71",thread-groups=["i1"],times="0",original-location="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:71"}
Found the breakpoint ID!
Storing debugger breakpoint Id=4
Successfully set breakpoint 4 at: C:\Users\Krunal\Documents\C++_Programming_Udemy\Classes_and_objects\Practices\main.cpp:71
DEBUG>>00000008^done,bkpt={number="5",type="breakpoint",disp="keep",enabled="y",addr="0x0040142d",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="72",thread-groups=["i1"],times="0",original-location="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:72"}
Found the breakpoint ID!
Storing debugger breakpoint Id=5
Successfully set breakpoint 5 at: C:\Users\Krunal\Documents\C++_Programming_Udemy\Classes_and_objects\Practices\main.cpp:72
DEBUG>>00000009^done,bkpt={number="6",type="breakpoint",disp="keep",enabled="y",addr="0x0040142d",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="73",thread-groups=["i1"],times="0",original-location="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:73"}
Found the breakpoint ID!
Storing debugger breakpoint Id=6
Successfully set breakpoint 6 at: C:\Users\Krunal\Documents\C++_Programming_Udemy\Classes_and_objects\Practices\main.cpp:73
DEBUG>>00000010^done,bkpt={number="7",type="breakpoint",disp="keep",enabled="y",addr="0x0040142d",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="74",thread-groups=["i1"],times="0",original-location="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:74"}
Found the breakpoint ID!
Storing debugger breakpoint Id=7
Successfully set breakpoint 7 at: C:\Users\Krunal\Documents\C++_Programming_Udemy\Classes_and_objects\Practices\main.cpp:74
DEBUG>>00000011^done,bkpt={number="8",type="breakpoint",disp="keep",enabled="y",addr="0x0040143b",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="75",thread-groups=["i1"],times="0",original-location="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:75"}
Found the breakpoint ID!
Storing debugger breakpoint Id=8
Successfully set breakpoint 8 at: C:\Users\Krunal\Documents\C++_Programming_Udemy\Classes_and_objects\Practices\main.cpp:75
DEBUG>>00000012^done,bkpt={number="9",type="breakpoint",disp="keep",enabled="y",addr="0x00401442",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="76",thread-groups=["i1"],times="0",original-location="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:76"}
Found the breakpoint ID!
Storing debugger breakpoint Id=9
Successfully set breakpoint 9 at: C:\Users\Krunal\Documents\C++_Programming_Udemy\Classes_and_objects\Practices\main.cpp:76
DEBUG>>00000013^done,line="71",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",macro-info="0"
DEBUG>>00000015-stack-list-variables --skip-unavailable --all-values
DEBUG>>00000014^done,BreakpointTable={nr_rows="8",nr_cols="6",hdr=[{width="7",alignment="-1",col_name="number",colhdr="Num"},{width="14",alignment="-1",col_name="type",colhdr="Type"},{width="4",alignment="-1",col_name="disp",colhdr="Disp"},{width="3",alignment="-1",col_name="enabled",colhdr="Enb"},{width="10",alignment="-1",col_name="addr",colhdr="Address"},{width="40",alignment="2",col_name="what",colhdr="What"}],body=[bkpt={number="2",type="breakpoint",disp="keep",enabled="y",addr="0x00401426",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="68",thread-groups=["i1"],times="0",original-location="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:68"},bkpt={number="3",type="breakpoint",disp="keep",enabled="y",addr="0x00401426",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="69",thread-groups=["i1"],times="0",original-location="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:69"},bkpt={number="4",type="breakpoint",disp="keep",enabled="y",addr="0x00401426",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="71",thread-groups=["i1"],times="0",original-location="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:71"},bkpt={number="5",type="breakpoint",disp="keep",enabled="y",addr="0x0040142d",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="72",thread-groups=["i1"],times="0",original-location="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:72"},bkpt={number="6",type="breakpoint",disp="keep",enabled="y",addr="0x0040142d",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="73",thread-groups=["i1"],times="0",original-location="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:73"},bkpt={number="7",type="breakpoint",disp="keep",enabled="y",addr="0x0040142d",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="74",thread-groups=["i1"],times="0",original-location="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:74"},bkpt={number="8",type="breakpoint",disp="keep",enabled="y",addr="0x0040143b",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="75",thread-groups=["i1"],times="0",original-location="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:75"},bkpt={number="9",type="breakpoint",disp="keep",enabled="y",addr="0x00401442",func="main()",file="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp",fullname="C:\\Users\\Krunal\\Documents\\C++_Programming_Udemy\\Classes_and_objects\\Practices\\main.cpp",line="76",thread-groups=["i1"],times="0",original-location="C:/Users/Krunal/Documents/C++_Programming_Udemy/Classes_and_objects/Practices/main.cpp:76"}]}
DEBUG>>00000015^error,msg="Usage: PRINT_VALUES"
Usage: PRINT_VALUES

**Comment by eranif** [comment]
You should upgrade your GDB version

**Comment by KrunalKaneriya** [comment]
Can you please give some solution to this either how to update gnu debugger in windows or any other workaround please..

**Comment by KrunalKaneriya** [comment]
> You should upgrade your GDB version. v7.6 does not support this command:
> 
> ```
> -stack-list-variables --skip-unavailable --all-values
> ```

Done man.. updated the compiler and gdb with the latest version and thank you soo much
