### ISSUE TITLE
Codelite latest weekly release is missing a tag

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2601]
Hi,

Referring to our talks in issue #2544 
Codelite latest weekly release (14.0.4) is missing a (github) tag before I can update/publish the codelite-unstable AUR package for ArchLinux

/Uffe

**Comment by uffejakobsen** [comment]
Manual "anti-stale-bot" comment to drag this issue out of stale state...

**Comment by eranif** [comment]
If you just label the issue as "important" -> it will be skipped by the stale bot

**Comment by uffejakobsen** [comment]
> Adding the label `Important` will do the trick

I'm afraid that I do not have the user rights to do so...  :-/

**Comment by uffejakobsen** [comment]
Closing this issue
