### ISSUE TITLE
where is the Linux AppImage executable download??

### ISSUE THREAD

**Issue by Tcll** [eranif/codelite#2605]
one of the first things I look for on the download page is an AppImage I can transfer to my Void Linux development machine and run on there...
but there doesn't seem to be a download I can run :(

**Comment by dghart** [comment]
You are welcome to create one; otherwise see https://github.com/eranif/codelite/issues/1455

**Comment by Tcll** [comment]
I'm unable to create one myself
I guess I'll just stick with IDEA and CLion for the time being

at least it's good to know there's an issue on it
though I'm not sure I'd title it "packaging process"
"build process" might be more appropriate since appimage is executable (unlike deb)

**Comment by dghart** [comment]
Your other alternative is to build CodeLite from source. It's not difficult.

**Comment by Tcll** [comment]
I'll pass, thanks
it shouldn't be the user's responsibility to build the software they want to use
I can wait for an appimage (what KDevelop does) or at least a tar.gz-packaged executable (what blender or IDEA do)
