### ISSUE TITLE
Occasional loss of permissions to delete codelite generated executable

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#2606]
I used to only experience this on an ancient netbook (2008) I was running, but recently have been experiencing it on my main machine, which I never have before.

Win7 x64, Codelite 14.04, non-self-compiled.

Build/run a program (compiler doesn't appear to matter, have used various different GCC's - nuwen 8.2, TDM 9.2, TDM 5.1 as examples). Program hits segfault, goes into debug mode. Stop debug.
Edit code, try to rebuild. Codelite cannot wipe present executable during clean. Trying to manually delete file also doesn't matter. Permissions seem to be set to someone other than current user, or some other process (some remnant of crashed exe in mem?)  is using it. After a period of time (up to 5 min) rebuild becomes possible.
Unsure what causes this.

Example output:
C:\Windows\system32\cmd.exe /C D:/programming/libraries/mingw82/MinGW/bin/make.exe -j4 SHELL=cmd.exe -e -f  Makefile
"----------Building project:[ plf_colonies - Debug ]----------"
make.exe[1]: Entering directory 'D:/programming/Workspaces/plf_colony_x64'
D:/programming/libraries/mingw82/MinGW/bin/g++.exe  -c  "D:/programming/projects/plf_colony/code/plf_colony_test_suite.cpp" -g -O0 -Wall -Wextra -pedantic -std=c++17  -o ./Debug/up_up_projects_plf_colony_code_plf_colony_test_suite.cpp.o -I. -Id:/programming/projects/plf_bench -Id:/programming/projects/plf_colony/code -Id:/programming/projects/plf_nanotimer -Id:/programming/projects/plf_timsort -Id:/programming/libraries/ranges/include -Id:/programming/projects/plf_list/code
D:/programming/libraries/mingw82/MinGW/bin/g++.exe -o ./Debug/plf_colonies @"plf_colonies.txt" -L.
d:/programming/libraries/mingw82/mingw/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file ./Debug/plf_colonies.exe: Permission denied
collect2.exe: error: ld returned 1 exit status
make.exe[1]: *** [plf_colonies.mk:81: Debug/plf_colonies] Error 1
make.exe: *** [Makefile:5: All] Error 2
make.exe[1]: Leaving directory 'D:/programming/Workspaces/plf_colony_x64'
====0 errors, 0 warnings====

**Comment by mattreecebentley** [comment]
This is still happening BTW - does not occur in Windows 10, as far as I can tell.

**Comment by eranif** [comment]
First: CodeLite does not generate executable files, your linker does (which is a separate installation from CodeLite).
So you need to check the issue with the compiler you are using. However, on Windows, a more common issue is that your program is still running so Windows is unable to replace an running executable. Make sure your program is properly terminated before attempting to delete / link it again
