### ISSUE TITLE
Codelite IDE and codelite-make produce different output results directory structures

### ISSUE THREAD

**Issue by twddogen** [eranif/codelite#2609]
I have recently upgraded from Codelite 10 to Codelite 14.  All of my existing workspaces/projects use a very simple directory structure -- release builds go to the **./Release** directory, and debug builds go to the **./Debug** directory.  When I build a workspace using the IDE, this simple output directory structure is preserved.  However, when I build the same  workspace with codelite-make, I get a completely different output directory structure, with multiple tiered subdirectories, at **./build-Release** for release builds, and at **./build-Debug** for debug builds.

This happens regardless of the build system that is selected in the IDE.

How do I change this back to the previous behavior?

**Comment by yunkot** [comment]
I also noticed this behavior, which appears to be something relatively new introduced in recent CodeLite 14.x builds. However, if you go to Project Settings - General - Makefile Generator and select "Default" instead of "CodeLite Makefile Generator", it appears to be using traditional approach with Debug and Release sub-folders inside project folder.

**Comment by twddogen** [comment]
I did exactly that.  Didn't change anything.  I still get traditional behavior with IDE, but command line codelite-make generates the tiered output.

Maybe I'm making an assumption here that's incorrect.  I thought that running the command line codelite-make would build the project according to the settings in the workspace and project files.  Is this actually the "CodeLite Makefile Generator", and always produces this odd output structure?  If that's the case, then how do I build a project from the command line while preserving the output structure of whatever is selected in the "Makefile Generator" settings?
