### ISSUE TITLE
Codelite-terminal no longer works after upgrade to MacOS Big Sur version 11.0.1

### ISSUE THREAD

**Issue by danWDC** [eranif/codelite#2610]
After upgrading MacOS to Big Sur (version 11.0.1) the CodeLite-terminal no longer works.  The terminal window does not open.  Terminal output will work after switching to: Preferences > Terminal > Terminal

**Comment by blockchaindevel** [comment]
I'm seeing the same thing. I'm using CodeLite 14.0.4 and Big Sur 11.0.1

**Comment by joelgasparr** [comment]
Same for me

**Comment by blockchaindevel** [comment]
The codelite-terminal is a very, very useful feature in CodeLite, especially on MacOSX.
I'm surprised this is going stale. Hopefully, it will be addressed in a future release.
Thanks!

**Comment by joel-hai** [comment]
Same issue here.

**Comment by aakardhakal** [comment]
I am on macOS Big Sur 11.5.2 (Intel chip) and using CodeLite version  15.0.0. I have been able to run CodeLite terminal by running the following command from the terminal:`/Applications/codelite.app/Contents/MacOS/codelite-terminal.app/Contents/MacOS/codelite-terminal` . But I want to run the CodeLite terminal when I build and run my C++ code from the IDE when I set my terminal as iTerm the code runs but when I set it as the CodeLite terminal nothing happens.
