### ISSUE TITLE
Windows Tabs have too much blank space around them so only few are visible

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#2611]
I have CodeLite 14.0.2 built from revision 2b75baba84d92218ae96fe372497c9ebdccec4bf (November 8, 2020) on Arch Linux, Gnome 3.38.1 on Wayland, kernel 5.9.8-arch1-1. I am using global dark theme Adwaita-dark.

On my configuration, display is set to Portrait 1200x1920 resolution. Although I have disabled "Show filePath on tabs" option in Preferences - Windows Tabs, it looks like there is still too much blank space around the text of each tab (look on screenshot below, "main.cpp" has so much blank space that would fit its caption twice), so in this configuration I can only see 3-4 tabs at a time. I recall that in earlier versions this was not a problem, the tabs were much more compact, so could see 6-7 tabs simultaneously. Furthermore, it looks like options like "Tab Style" and "Tab Height" are permanently grayed out in Preferences.
![screenshot](https://user-images.githubusercontent.com/14065837/99455349-54343580-28ed-11eb-9f74-256a288948a4.png)

Is there a workaround to use tabs as before or at least reduce the unnecessary blank space in them?

**Comment by eranif** [comment]
this is the native GTK3 notebook control. I am not sure if I can make it smaller...

**Comment by yunkot** [comment]
Thanks for a quick reply. In this case, could this report be changed into a feature request? Maybe to consider adding an option for an alternative tab control component that can be chosen when building CodeLite from sources?
