### ISSUE TITLE
Codelite doesn't recognize my compiler

### ISSUE THREAD

**Issue by beyzus** [eranif/codelite#2615]
I've correctly installed MinGW-w64 for Windows 64 bit and I have checked every possibility that might have gone wrong but I can't find any reason for Codelite to scan and still not find my MinGW-w64 files. I've tried it on command prompt so it works well doesn't give any errors but Codelite setting up wizard still tells me to download the MinGW-w64 files. Please can someone explain to me why this isnt working?
![2020-11-22 22_48_23-Window](https://user-images.githubusercontent.com/74881198/99919367-df119780-2d14-11eb-939c-a82a0b5c8407.png)
![2020-11-22 22_49_05-Window](https://user-images.githubusercontent.com/74881198/99919380-f3ee2b00-2d14-11eb-97c8-51fc8c69240d.png)

**Comment by MarcT512** [comment]
I can't claim to be an expert, but I installed the MinGW based tdm64-gcc from here: [https://jmeubank.github.io/tdm-gcc/](url) and it works fine with CodeLite.

![image](https://user-images.githubusercontent.com/34656315/101808595-709f4880-3b0e-11eb-87b6-7e6477bd2faf.png)

**Comment by yunkot** [comment]
As a workaround, I always install mingw-w64 to commonly recognized folders, e.g. d:\mingw\x64 and d:\mingw\x32. CodeLite seems to be finding both of them.

**Comment by eranif** [comment]
CodeLite compiler detection is not bullet proof it uses some heuristics to guess where compilers are installed.
However, even if it does not detect your compiler installation location you can always help it by telling it where to search.

You can do that from the `settings -> build settings ` and click on the `+` button in the tool bar. In the dialog that opens, select the installation folder of your compiler and CodeLite will pick it up for you
