### ISSUE TITLE
Workspace/Editor indentation settings ignored

### ISSUE THREAD

**Issue by fbo25** [eranif/codelite#2618]
Hi,

The problem is happening in both 14.0.0 and today git/master.

Steps to reproduce :
- Set project or workspace indentation options to something different from global settings.
- Open a file
Result : only global settings indentation is applied.

I'm new to Codelite (and back to C++ after 15 years with Java/Eclipse) but I managed to debug Codelite itself (so good point for intuitiveness ;) ) and found that lexer configuration doesn't load workspace/editor settings (see Plugin/lexer_configuration.cpp:288). Unfortunately, it's the last feature initializing the editor indentation options (and maybe other settings). This is done via editor->SetSyntaxHighlight() call in LiteEditor/mainbook.cpp:663. Stack trace :
```
OptionsConfig::GetIndentWidth  Plugin/optionsconfig.h  394
LexerConf::Apply  Plugin/lexer_configuration.cpp  503
ContextBase::DoApplySettings  LiteEditor/context_base.cpp  98
ContextCpp::ApplySettings  LiteEditor/context_cpp.cpp  2211
clEditor::SetSyntaxHighlight  LiteEditor/cl_editor.cpp  498
MainBook::OpenFile  LiteEditor/mainbook.cpp  663
FileViewTree::DoItemActivated  LiteEditor/fileview.cpp  529

```

Commenting LiteEditor/mainbook.cpp:663 did the trick, apparently there is no regression since lexer configuration is already loaded by contexts (generic and CPP in my case) on editor creation (cl_editor constructor and create() method).
[See patch](https://github.com/eranif/codelite/files/5610087/fix-workspace-project-settings.patch.zip)

Hope it helps.

Thanks

**Comment by eranif** [comment]
it's a bit more complicated than that. 
It is now fixed in the latest git master
