### ISSUE TITLE
Quick code navigation configurable shortcut

### ISSUE THREAD

**Issue by eranif** [eranif/codelite#262]
Currently CTRL+click, CTRL+ALT+Click,MIDDLE MOUSE, CTRL + MIDDLE MOUSE shortucts for code navigation are hardcoded. they should be configurable.

Could be named smtg like. Go to Declaration Modifier (let the click be hardcoded)

also, it would be great if similar shorcuts would exist for items on the current carat position (if that is not done this way already)

**Comment by fadeevab** [comment]
Because I found this post in Google over and over again, I want to leave a short tip here. You can change code navigation shortcut as you wish in CodeLite `Settings -> Preferences -> Tweaks -> Code navigation key -> Mouse click + [Ctrl] + [Alt]`. **Ctrl+Alt+Click** is by default.
