### ISSUE TITLE
gui application can not disable console window

### ISSUE THREAD

**Issue by fxqy** [eranif/codelite#2628]
I set the ‘This program is a GUI application’, but there is a console window when I run it
![image](https://user-images.githubusercontent.com/42601163/102608403-c99d5b00-4164-11eb-8fa1-51788e964a6b.png)
![image](https://user-images.githubusercontent.com/42601163/102608618-1bde7c00-4165-11eb-8653-f0a573453615.png)

**Comment by eranif** [comment]
this is a windows problem, You need to tell the linker to disable it and tell Windows that you are building a GUI application

**Comment by fxqy** [comment]
> this is a windows problem, You need to tell the linker to disable it and tell Windows that you are building a GUI application
Add linker options? I added '-- subsystem, windows' are useless
