### ISSUE TITLE
Default Theme at first startup doesn't enable plugins

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#2631]
As described in a non-related issue #2608, when CodeLite is run for the first time and "Default theme" is selected, it doesn't enable any of the plugins. Selecting "Dark", "Grey" or "White" theme does seem to enable the plugins.

I think this is a bug as a choice to enable or disable plugins shouldn't depend on what type of color theme is chosen at first run. By the way, I remember in some earlier CodeLite versions there was a dialog at startup to ask which plugins should be enabled or disabled - this dialog is no longer presented as far as I can tell.

Reproduced in CodeLite 14.0.4 on Windows and revision 0e12e2d1710dec9a51780a53dedbed4acdb6540c on Ubuntu 20.04.1 LTS 64-bit with kernel 5.4.0-58-generic.

**Comment by eranif** [comment]
This was fixed in CodeLite 15.0
