### ISSUE TITLE
Codelite "output view" tab has been hidden by mistake.

### ISSUE THREAD

**Issue by bishen28** [eranif/codelite#2632]
I use codelite IDE and the "output view" tab got hidden my mistake.
please help how do i  recover the tab.

**Comment by eranif** [comment]
`View->Output Pane` or ``Ctrl-` ``

**Comment by bishen28** [comment]
i have tried this but the issue has not resolved.

**Comment by bishen28** [comment]
> 
> 
> `View->Output Pane` or `` Ctrl-` ``

i have tried this but the issue has not resolved.

**Comment by eranif** [comment]
In that case `Perspective -> Restore Default Layout`

**Comment by bishen28** [comment]
> 
> 
> In that case `Perspective -> Restore Default Layout`

1) This also has not resolved the issue. 
2) when i am doing this (Perspective -> Restore Default Layout`) the (view->output pane) is getting disabled.
3) when i am doing the  (view->output pane) the output view is not getting enabled.
4) I have also uninstalled and then reinstall the "min-gw64" and "codelite-IDE" but the the issue has not resolved. now it is  getting irritating. i am stuck at this for 2 days.
i think i am done some hush mistake by messing with system's setting. is it resolvable of i give up?
