### ISSUE TITLE
There is a problem with the interface display in lubuntu

### ISSUE THREAD

**Issue by fxqy** [eranif/codelite#2633]
The combo box text is incomplete
![asd](https://user-images.githubusercontent.com/42601163/103457227-2e95ab00-4d38-11eb-9148-ea870d50abdb.png)
lubuntu version：
```
Linux dpc 5.8.0-33-generic #36-Ubuntu SMP Wed Dec 9 09:14:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy
```

**Comment by eranif** [comment]
which GTK version?

**Comment by fxqy** [comment]
> Is this a self compiled CodeLite?
> Which wxGTK version and was it compiled against GTK3? (the controls do not seem like GTK3)

I download deb file from codelite.org , not stable version.
![20210210113428](https://user-images.githubusercontent.com/42601163/107460955-05b4d100-6b94-11eb-8030-ccc6be62165d.png)
