### ISSUE TITLE
Output not working

### ISSUE THREAD

**Issue by primpropermaine** [eranif/codelite#2640]
I have a debian9 system and while using codelite I am encountering a display issue or a lack of a display issue rather when I run programs to the terminal. The terminal opens up fine, but there is no output displayed instead all I get is a blank terminal waiting for me to type something to it. The screenshot (smaller window with blacked out name is terminal) I've included shows the result of me running code and the output I get on the terminal. Any help at all would be greatly appreciated, I reinstalled GCC compiler because I thought that was the issue and I have xfce4 installed too if that info helps at all. 
![PicsArt_01-19-12 53 45](https://user-images.githubusercontent.com/62642366/105074145-fbe8f380-5a55-11eb-9c6b-4b471e2e0e4d.jpg)

**Comment by primpropermaine** [comment]
is anyone here?

**Comment by dghart** [comment]
Which CodeLite version are you using?
Debian stretch comes with CodeLite 10.0. We produced unofficial packages of CodeLite 13.0. Or is this a more recent version that you self-built?

FWIW, I failed to reproduce the problem with CodeLite 13.0 in a VirtualBox stretch.

>is anyone here?

No. This is a bug-tracker, not a chat-room.
