### ISSUE TITLE
Code completion not finding wxStatusBar, but finds other wxElements

### ISSUE THREAD

**Issue by FalcoGer** [eranif/codelite#2642]
I made a small reference project to show the basics of how to use wxWidgets.
I noticed that code completion works fine for most cases, but wxStatusBar just doesn't want to work.

I run codelite 14.0.0 on ubuntu mate 20.04 and use the repository version from `https://repos.codelite.org/ubuntu/ focal universe`
I use the wxWidgets version 3.1.4 from the repositores from `https://repos.codelite.org/wx3.1.4/ubuntu/ focal universe`

To get around the bug in wx-config displaying the wrong include path, i made a softlink to the right directory using the wrong name.

I tried adding the include paths from wx-config --cxxflags into the code completion directories, but that didn't help.

**Comment by eranif** [comment]
I highly recommend to enable the language server and use that as your main code completion.
https://wiki.codelite.org/pmwiki.php/Main/LanguageServer

**Comment by FalcoGer** [comment]
I have installed and enabled clangd in codelite. I'm using the "Default" makefile generator, which I believe generates a projectname.mk gnu makefile. However it doesn't generate any json files as described on the page you linked, especially not "automatically"
