### ISSUE TITLE
I can't get codelite to use the right directories.

### ISSUE THREAD

**Issue by vayulove** [eranif/codelite#2645]
I can't get codelite to use the right directories.  If I manually cd to the build directory and type "cmake .." then "make" then ./helloworld it works just fine.  Any sequence of using the GUI interface doesn't find itself working within the build directory.   I'm trying to have a cmake/make project.  What GUI commands should I do to make this project structure:
```
workspace 
      helloworld
                build/
                         Makefile
                         helloworld (executable)
                CMakeLists.txt
                main.cpp
                

```Also separate but part of codelite not doing the right things is the .project file has several lines of rebuild commands with "mingw-make"  and "-G mingw" stuff on my Linux computer.  I went and manually edited it but still nothing works except the CMakelists.txt and main.cpp and manually running cmake from the terminal.

**Comment by vayulove** [comment]
How can I see what the build systems are:?
Default
GNU makefile onestep build
CodeLight Make Generator

**Comment by vayulove** [comment]
I've had some success but I still have questions.
There were two entries under Project Settings that I had to figure out:
Under General/Output File I put:
`$(IntermediateDirectory)/$(ProjectName)`
Under Customize I removed the MingW references and put ""
`make clean && make -j4`
Under Working Directory I put:
`$(WorkspacePath)/$(ProjectName)/build`

Under the pulldown I find a setting for the build directory that I didn't see how to change.
I somehow fudged it by putting literally "build"  in the above "Working Directory"

In the end there was a last thing I had to figure out, I can't remember now but I might have had to edit the .project file because the lowercase name I entered for the Project was changed from "helloworld" to "HelloWorld".
I didn't see a way to enter that from the GUI.

My questions are 

Where can I find the values of the variables used in the settings dialog? 
$(IntermediateDirectory)
$(WorkspacePath)

How can I specify and change the project name from the GUI without going into the .project XML mess? I believe GUI access to $(ProjectName) would solve that.

What is the vaule of the abouve build variable and are there some other ones that would be helpful?

**Comment by eranif** [comment]
If you are using your own CMake, then the best option for you is to use the `File System Workspace`
Using this workspace type, you will be to automate the manual steps you described earlier:

https://wiki.codelite.org/pmwiki.php/Main/FileSystemWorkspace
