### ISSUE TITLE
CodeLite 14.0.1 crashes when opening or creating new workspace on MacOS 11.1

### ISSUE THREAD

**Issue by Joeraw** [eranif/codelite#2654]
Hi,

Ive been having a similar issue to this -  https://github.com/eranif/codelite/issues/2542

However the Codelite file does not exists in application support therefore cannot be deleted....

Similarly to issue #2542 i get no crash report.

Joe

**Comment by adeeldin72** [comment]
I'm in the same situation

**Comment by imhotepper** [comment]
Same here
