### ISSUE TITLE
Tab height is massive

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2657]
With to update to CodeLite-15.0 the tab height have become massive

It is about 3-4 times as high as the tab height in codelite-14.x - which was apropriately fitting/following the font size and did not waste valuable screen height. Now with codelite 15.0 there is room for about 3-4 lines of text within each tab.

Codelite 15.0 @archlinux

**Comment by ChenKE404** [comment]
It seems that this version has a lot of bugs and I have a lot of problems

**Comment by eranif** [comment]
On Linux, we are now building CodeLite against the native GTK3 tab. Compared to the previous versions
This is the tab height difference you are seeing

**Comment by uffejakobsen** [comment]
Argh yes I know - but just I forgot to merge my changes in the aur-package codelite-unstable back to the codelite (stable) aur-package - my fault sorry,

But still with GTK3 the height is about 2-2,5 times higher than with codelite-14.0 
PS: I know that XFCE-Terminal had the same error but got that solved

I hope that there is a similar solution for codelite

PS: thanks for a great project :-) :+1:
