### ISSUE TITLE
Why "Workspace view" and "Output View" is empty?

### ISSUE THREAD

**Issue by ChenKE404** [eranif/codelite#2658]
![new](https://user-images.githubusercontent.com/75658944/107232694-aacc8e00-6a5c-11eb-9576-9b48473e3bd0.png)
CodeLite15.0.0
I created a workspace and project.I can build my project and run it,but i can't find my project files in the "Workspace View",it‘s just a blank box.
"Output View" is also the same.it's a bug?

**Comment by eranif** [comment]
this looks like a corrupted configuration error
to redstore the layout: `perspective -> restore default layout`

**Comment by ChenKE404** [comment]
It doesn't work. It's still empty!
I tried v15amd64,v15x86 and v14.0.4,use default.layout.
It still looks like that.
My system is windows 8.1

**Comment by ChenKE404** [comment]
> this looks like a corrupted configuration error
> to redstore the layout: `perspective -> restore default layout`

It doesn't work. It's still empty!
I tried v15amd64,v15x86 and v14.0.4,use default.layout.
It still looks like that.
My system is windows 8.1

**Comment by ChenKE404** [comment]
> 这看起来像是配置错误
> 以重新存储布局：`perspective -> restore default layout`

**Comment by ChenKE404** [comment]
> this looks like a corrupted configuration error
> to redstore the layout: `perspective -> restore default layout`

Hey, friend:
I think I figured out where the problem was.
First,I deleted my CodeLite Configuration folder - "C:\Users\XDC\AppData\Roaming\codelite".
Then,I restart CodeLite,that created a new Configuration folder.
Now I can see the normal panes(WorkSpace View/Debugger/Output View):
![1](https://user-images.githubusercontent.com/75658944/109150189-7cacb500-77a3-11eb-96b0-d755cb1f5d21.png)

Then,I changed localization to Chinese:
![2](https://user-images.githubusercontent.com/75658944/109150509-ef1d9500-77a3-11eb-9e52-592adf7a6ef1.png)
Apply -> Restart CodeLite.

Then,those panes were all empty!
![3](https://user-images.githubusercontent.com/75658944/109151010-97335e00-77a4-11eb-97ba-577e742f81e0.png)
emmm...... well,look likes I can't useing CodeLite in Chinese coding environment.

Then,I disabled localization, restart. but they still empty:
![4](https://user-images.githubusercontent.com/75658944/109151867-ac5cbc80-77a5-11eb-8a18-31582435615f.png)

So,I learned that changing my localization to Chinese would make them empty.
After my tests,I found that is "codelite.conf" and "codelite.xml".
I have kept the two files that can be used normally before,now I copy and replace them into the "...\codelite\config" folder.
I started CodeLite,Now I can see the normal panes again:
![5](https://user-images.githubusercontent.com/75658944/109153829-60f7dd80-77a8-11eb-91d8-ec8d9ecf2671.png)

??????

@eranif
