### ISSUE TITLE
Global Keyboard shortcuts for moving tabs left/right does not work in codelite-15.0

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2660]
Global Keyboard shortcuts for moving tabs left/right does not work in codelite-15.0

CTRL+SHIFT+PGUP and CTRL+SHIFT+PGDN worked fine in cl-14.x

CL-15.0 @ archlinux (GTK3)

**Comment by eranif** [comment]
This might be related to the move to native GTK notebook control. I will check this on my ubuntu laptop and report back :)

**Comment by eranif** [comment]
confirmed. broken on Ubuntu as well
