### ISSUE TITLE
Question about File System Workspace - indexing ?

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2661]
This is the first time that I try out the File System Workspace feature 

Previously I needed the exclude paths feature with File SystemWorkspace
With that feature delivered in the release of CL-15.0 I decided to take a look at File System Workspace...

I selected a random small C/C++ project at github and made a local clone...

The thing I'm wonderig about is that it does not seem that the indexer (or something) runs over the project...
I've tried to invoke the indexing manually by selecting menu path "Workspace" -> "Parse Workspace"

But still the "Open Resouce.." dialog does not allow me to search for functions, filenames or any other resource...

The wiki does not really give any clue either:
https://wiki.codelite.org/pmwiki.php/Main/FileSystemWorkspace

The .codelite directory in the root of the project does not contain any of the TAGS files that i usually would expect for normal workspace/projects - it only contains a "xxx.db" and a "xxx.session" file...

using CL-15.0 @ archlinux

**Comment by eranif** [comment]
Could you give an example of such project so I can try it locally?
FYI: I am using File System Workspace to develop CodeLite on Linux / macOS and it is working properly so I wonder if this is something that I am doing locally which makes it working for me

**Comment by eranif** [comment]
I just cloned https://github.com/danmar/cppcheck
created a file system workspace on that folder (`file -> new workspace -> file system workspace ->`)
the tree view was built, I see at the bottom that the following messages:
- Generating ctags files
- and then Parsing NN / XX message
- `Ctrl-Shift-R` searched for something (e.g. `options`) -> works

**Comment by uffejakobsen** [comment]
Hi,
I just tried cloning the exact same project...
And unfortunately it does not work...
But based on your comment about file extensions i have an observation that may help...

using ctrl-shift-r I can see files in the project root folder that match the file extensions - but only if i type in a single "." or ".txt" or similar... it does not seem to do any recursion into subdirs.

Also i enabled developer debug log
and see the following:
[18:27:10:347 DBG] [Main] FSW: CacheFiles completed. Found 9 files

That number (9 files) matches exactly with the number of files in the root dir that match this file extension pattern:
```
*.cpp;*.c;*.txt;*.json;*.hpp;*.cc;*.cxx;*.xml;*.h;*.wxcp;*.py;*.php;*.rb;*.html;*.js;*.md
```

PS: i only added '*.md' the rest is the default - and the number of found files reported changes - if I change the extensions






(CL-15.0 @ archlinux)

**Comment by eranif** [comment]
what is the value you have under "exclude paths" and can you paste here the root folder of your workspace

**Comment by uffejakobsen** [comment]
As I'm testing the FSW feature with the suggested cppcheck sources - I'm pretty much running on defaults here
- the "Exclude paths" field is empty (this is the default)
- the root of my workspace is also the root of the cppcheck project from github:

```
% pwd
/tmp/danmar-cppcheck.git

% ls -1
addons/
appveyor.yml
AUTHORS
benchmarks.txt
build-pcre.txt
cfg/
cli/
cmake/
CMakeLists.txt
console_common.pri
COPYING
cppcheck.cppcheck
cppcheck-errors.rng
_CPPCHECK_FSW_TST.workspace
cppcheck.sln
createrelease*
cve-test-suite/
democlient/
doxyfile
externals/
generate_coverage_report*
gui/
htmlreport/
lib/
Makefile
man/
naming.json
oss-fuzz/
philosophy.md
platforms/
pylintrc_travis
readmeja.md
readme.md
readme.txt
requirements.txt
rules/
runastyle*
runastyle.bat
samples/
snap/
test/
tools/
valgrind/
webreport.sh*
win_installer/
```
Is the above what you were asking for ?

I did nothing else than clone the project and create the FSW project inside codelite

**Comment by uffejakobsen** [comment]
It could seem as if your clFilesScanner does not manage to iterate into subdirs on linux (archlinux).
I took a quick look at the impl - it looks correct - and it does indeed work on windows

**Comment by eranif** [comment]
I checked this on Linux (Ubuntu). I wonder why it fails on Arch. 
Can you add some debug messages and test it locally?

**Comment by uffejakobsen** [comment]
> I checked this on Linux (Ubuntu). I wonder why it fails on Arch.

Yes, that is strange---

> Can you add some debug messages and test it locally?

Sure - I'll report results later :-)

**Comment by uffejakobsen** [comment]
Ok, I found the problem

The absolute path to a FSW project was not allowed to contain any of .svn, .git ot .codelite anywhere in the path
My working paths all had "xxxx.codelite" somewhere in the absolute path above the FSW project root.

I've created a PR with fixes/enhancements for the FSW folder exclude option: #2671

**Comment by uffejakobsen** [comment]
Closing this issue
