### ISSUE TITLE
Code Completion in v14.0.0 on Windows 10

### ISSUE THREAD

**Issue by ctchadwick** [eranif/codelite#2663]
I can not seem to get the code completion to work on my install.  I had started with the latest 14+ version but decided to revert back to the stable 14.0.0.  Neither of them seem to have any code completion ability.  This seems that it is likely a configuration error on my part but nothing seems to stick out to me in the settings on how do get this working.  I have the search folders pointing to my code files and the defaults are pointing to the mingw install locations.  Has anyone else had an issue with this and been able to resolve it?  The Wiki is a bit outdated on this.

**Comment by eranif** [comment]
The best thing to do is to:
- Create a simple hello world workspace (use the `CodeLike Makefile Generator`)
- Check that you have `clangd` enabled in `Plugins -> Language Server -> Settings` 
- Build the project once
- You should be able to code complete
- I strongly suggest to use `v15.0.0.`

**Comment by ctchadwick** [comment]
Thanks Eran.  I installed v15.0.0.  Built a new project as mentioned.  Unfortunately the application becomes non-responsive (chewing thru CPU) after typing a couple of characters.  I recall a setting somewhere in an older version that stopped this, but right now it's unusable for me.  Any thoughts?

**Comment by ctchadwick** [comment]
I should mention that I use mingw.  I have tweaked the settings, but no difference.  Either code completion works, or it locks the application up and I have to restart.  I even tried to see if I could generate some logging, but even on debug, nothing is showing up in the log.  Not sure what I don't have configured right, but it's almost unusable like this.

**Comment by eranif** [comment]
enable CodeLite log from settings -> preferences -> misc -> log, and set it to "Debug"
try to code complete something and post here the content of `%appdata%\codelite\codelite.log`

**Comment by ctchadwick** [comment]
Thanks again Eran,
 
I think I am seeing what the issue might be.  I'm picking up the compiler headers now, but I don't see to be picking up personal library files (boost, some custom headers).  I believe they are included.  Below is a log snippet for trying to get something from the boost::asio headers, before that is what is in the Settings->Code Completion->CTags->Search Paths tab.  I had the boost entry also end with \boost with the same result

C:\MinGW\lib\gcc\x86_64-w64-mingw32\8.1.0\include
C:\MinGW\lib\gcc\x86_64-w64-mingw32\8.1.0\include-fixed
C:\MinGW\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++
C:\MinGW\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\backward
C:\MinGW\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\x86_64-w64-mingw32
C:\MinGW\x86_64-w64-mingw32\include
C:\Boost\include\boost-1_71

14:51:59:164 DBG] [Main] Language ID for file C:\Users\ctcha\Desktop\Codes-Etc\Work-Codelite-Workspace\socket-testing\receiver.hpp -> cpp
[14:51:59:166 DBG] [Main] [clangd]  No changes detected in file: C:\Users\ctcha\Desktop\Codes-Etc\Work-Codelite-Workspace\socket-testing\receiver.hpp
[14:51:59:167 DBG] [Main] Language ID for file C:\Users\ctcha\Desktop\Codes-Etc\Work-Codelite-Workspace\socket-testing\receiver.hpp -> cpp
[14:51:59:168 DBG] [Main] Converting C:\Users\ctcha\Desktop\Codes-Etc\Work-Codelite-Workspace\socket-testing\receiver.hpp
[14:51:59:169 DBG] [Main] C:\Users\ctcha\Desktop\Codes-Etc\Work-Codelite-Workspace\socket-testing\receiver.hpp -> file:///C:/Users/ctcha/Desktop/Codes-Etc/Work-Codelite-Workspace/socket-testing/receiver.hpp
[14:51:59:170 DBG] [Main] LSPNetworkSTDIO:
 Content-Length: 244

{"jsonrpc":"2.0","method":"textDocument/completion","params":{"textDocument":{"uri":"file:///C:/Users/ctcha/Desktop/Codes-Etc/Work-Codelite-Workspace/socket-testing/receiver.hpp"},"position":{"line":178,"character":21}},"id":39}
[14:51:59:184 DBG] [Main] I[14:51:59.171] <-- textDocument/completion(39)

I[14:51:59.183] Code complete: sema context Symbol, query scopes [boost::asio::] (AnyScope=false), expected type <none>

I[14:51:59.183] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.

I[14:51:59.183] --> reply:textDocument/completion(39) 12 ms

[14:51:59:186 DBG] [Main] [clangd]  Content-Length: 68

{"id":39,"jsonrpc":"2.0","result":{"isIncomplete":false,"items":[]}}
[14:51:59:187 DBG] [Main] [clangd]  received a response
[14:51:59:188 DBG] [Main] Read 0 completion items
[14:51:59:189 DBG] [Main] Received: 0 completion items

**Comment by eranif** [comment]
which workspace type are you using? can you post screenshot of the project settings?

**Comment by ctchadwick** [comment]
Not sure what you mean by workspace type.  I'm using the default workspace settings, all projects are started in CodeLite, not imported from any other IDE.  Here are some screen shots, not sure what you need specifically.

![image](https://user-images.githubusercontent.com/3092539/107784064-04f97780-6d19-11eb-8cb0-7ad2a62948e7.png)
![image](https://user-images.githubusercontent.com/3092539/107784183-2490a000-6d19-11eb-9cc5-d64f04439df2.png)

**Comment by eranif** [comment]
You should have a file named `compile_flags.txt` under the workspace folder, can you paste it's content here?
this is the actual file used by `clangd`. CodeLite generates this file for `clangd` so it will know where to look for headers etc. thanks

**Comment by ctchadwick** [comment]
Thanks again, sorry to be burning your time with this.  I don't see the `compile_flags.txt` in the workspace folder, but the project folder.  In the workspace folder I see the `compile_commands.json` file (sort of large for posting directly).  Looking at the `txt` file, I see that some locations are not correct, them being environmental vars prepended with the project location when they should only be the environmental vars, might be the issue.  Here is the `txt`
[compile_flags.txt](https://github.com/eranif/codelite/files/5976241/compile_flags.txt)
:

**Comment by eranif** [comment]
Can you do this:
- Delete both of these files
- Make sure that the option `settings -> code completion -> General tab -> Generate compile_commands.json` is **NOT** checked
- Build your project again within CodeLite.

Now check for these files `compile_commands.json` or `compile_flags.txt` (the latter is "stronger", i.e. if it exists it will override the values under `compile_commands.json`)

Can you explain what these values: `$(BoostIncludes)` `$(WorkspaceCodeLib)` ? I see them in the `compile_flags.txt`. Are these environment variables you defined somewhere? if so, where?

**Comment by ctchadwick** [comment]
Thank Eran, 
I'll give these a shot.  The `$(BoostIncludes)` and `$(WorkspaceCodeLib)` are environmental variables defined in Settings->Environmental Variables as part of the  'Default' group of EVs.  These have always worked for me.  Things compile fine with these definitions.  They point to the Boost headers and personal code files in current use.

**Comment by ctchadwick** [comment]
Thought I'd add this as well.  It looks like `clang-tool` is getting passed the incorrect locations concerning the EV above, but `gcc` is getting them correctly expanded.  In the `Settings->CTags->Search Paths` listing, I have the expanded value listed for those EVs instead of using the EVs.  It doesn't seem to make a difference.  Here is a `codelite` log entry and the compile log:

C:\Program Files\CodeLite\lsp\clang-tool -IC:\MinGWx64-810\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++ -IC:\MinGWx64-810\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\x86_64-w64-mingw32 -IC:\MinGWx64-810\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\backward -IC:\MinGWx64-810\lib\gcc\x86_64-w64-mingw32\8.1.0\include -IC:\MinGWx64-810\lib\gcc\x86_64-w64-mingw32\8.1.0\include-fixed -IC:\MinGWx64-810\x86_64-w64-mingw32\include -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Work-Codelite-Workspace\socket-testing -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Work-Codelite-Workspace\socket-testing\$(BoostIncludes) -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Work-Codelite-Workspace\socket-testing\$(WorkspaceCodeLib) -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Work-Codelite-Workspace\socket-testing\$(WorkspaceCodeLib)\strtk -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Work-Codelite-Workspace\socket-testing\$(WorkspaceCodeLib)\rapidjson -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Work-Codelite-Workspace\socket-testing\$(WorkspaceCodeLib)\spdlog -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Work-Codelite-Workspace\socket-testing\$(WorkspaceCodeLib)\date\include -DHAVE_SNPRINTF -DRAPIDJSON_HAS_STDSTRING -DBOOST_COROUTINES_V2 -D_WINDOWS -D_WIN32_WINNT_WIN7 -DFMT_HEADER_ONLY -DBOOST_THREAD_PROVIDES_FUTURE -DBOOST_ASIO_DISABLE_STD_FUTURE -DBOOST_THREAD_USE_LIB -std=c++17 -target x86_64-pc-windows-gnu C:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Work-Codelite-Workspace\socket-testing\receiver.hpp -fsyntax-only -resource-dir=C:\Program Files\CodeLite\lib\clang\10.0.0


C:\Windows\system32\cmd.exe /C C:/MinGWx64-810/bin/mingw32-make.exe -j8 SHELL=cmd.exe -e -f  Makefile
"----------Building project:[ socket-testing - Release ]----------"
mingw32-make.exe[1]: Entering directory 'C:/Users/ctcha/Desktop/MCM-Options-CTC/Codes-Etc/Work-Codelite-Workspace/socket-testing'
C:/MinGWx64-810/bin/g++.exe  -c  "C:/Users/ctcha/Desktop/MCM-Options-CTC/Codes-Etc/Code-Library/fast-log3.cpp" -O2 -std=c++17 -std=c++11 -Wall -Wa,-mbig-obj -D_WIN32_WINNT_WIN7 -D_WINDOWS -DFMT_HEADER_ONLY -DBOOST_THREAD_USE_LIB -DBOOST_THREAD_PROVIDES_FUTURE -DBOOST_ASIO_DISABLE_STD_FUTURE -DBOOST_COROUTINES_V2 -DRAPIDJSON_HAS_STDSTRING -DHAVE_SNPRINTF  -o ./Release/up_up_Code-Library_fast-log3.cpp.o -IC:\Boost\include\boost-1_71  -I. -I. -IC:\Boost\include\boost-1_71 -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Code-Library -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Code-Library/strtk -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Code-Library/rapidjson -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Code-Library/spdlog -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Code-Library/date/include
C:/MinGWx64-810/bin/g++.exe  -c  "C:/Users/ctcha/Desktop/MCM-Options-CTC/Codes-Etc/Work-Codelite-Workspace/socket-testing/main.cpp" -O2 -std=c++17 -std=c++11 -Wall -Wa,-mbig-obj -D_WIN32_WINNT_WIN7 -D_WINDOWS -DFMT_HEADER_ONLY -DBOOST_THREAD_USE_LIB -DBOOST_THREAD_PROVIDES_FUTURE -DBOOST_ASIO_DISABLE_STD_FUTURE -DBOOST_COROUTINES_V2 -DRAPIDJSON_HAS_STDSTRING -DHAVE_SNPRINTF  -o ./Release/main.cpp.o -IC:\Boost\include\boost-1_71  -I. -I. -IC:\Boost\include\boost-1_71 -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Code-Library -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Code-Library/strtk -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Code-Library/rapidjson -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Code-Library/spdlog -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Code-Library/date/include
C:/MinGWx64-810/bin/g++.exe  -c  "C:/Users/ctcha/Desktop/MCM-Options-CTC/Codes-Etc/Code-Library/hi-res-time3.cpp" -O2 -std=c++17 -std=c++11 -Wall -Wa,-mbig-obj -D_WIN32_WINNT_WIN7 -D_WINDOWS -DFMT_HEADER_ONLY -DBOOST_THREAD_USE_LIB -DBOOST_THREAD_PROVIDES_FUTURE -DBOOST_ASIO_DISABLE_STD_FUTURE -DBOOST_COROUTINES_V2 -DRAPIDJSON_HAS_STDSTRING -DHAVE_SNPRINTF  -o ./Release/up_up_Code-Library_hi-res-time3.cpp.o -IC:\Boost\include\boost-1_71  -I. -I. -IC:\Boost\include\boost-1_71 -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Code-Library -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Code-Library/strtk -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Code-Library/rapidjson -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Code-Library/spdlog -IC:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Code-Library/date/include
C:/MinGWx64-810/bin/g++.exe -o C:\Users\ctcha\Desktop\MCM-Options-CTC\Codes-Etc\Work-Codelite-Workspace\bin/socket-testing @"socket-testing.txt" -LC:\Boost\lib  -L. -LC:\Boost\lib  -lmswsock -lws2_32 -lboost_filesystem-mgw81-mt-x64-1_71 -lboost_date_time-mgw81-mt-x64-1_71 -lboost_thread-mgw81-mt-x64-1_71 -lboost_coroutine-mgw81-mt-x64-1_71 -lboost_context-mgw81-mt-x64-1_71 -lboost_chrono-mgw81-mt-x64-1_71 -lboost_random-mgw81-mt-x64-1_71 -lboost_program_options-mgw81-mt-x64-1_71 -lboost_system-mgw81-mt-x64-1_71
mingw32-make.exe[1]: Leaving directory 'C:/Users/ctcha/Desktop/MCM-Options-CTC/Codes-Etc/Work-Codelite-Workspace/socket-testing'
====0 errors, 0 warnings, total time: 00:01:27 seconds====
