### ISSUE TITLE
With CL-15.0 check for external file changes seems to have become unreliable

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2665]
With CL-15.0 check for external file changes seems to have become unreliable

This is an observation after using CL-15 for a few days...

It seems that the CL-15 file-change detection does not work as good as i did in CL-14
Externally modified files does not seem to be detected by CL-15

**Comment by eranif** [comment]
**nothing** was changed in this regard. can you please reset your `preferences -> misc -> history -> reset annoying dialogs answers` and see if fixes this?, maybe for some reason, you have the "don't reload" option remembered...

**Comment by eranif** [comment]
oops... 
https://github.com/eranif/codelite/blob/master/LiteEditor/frame.cpp#L3434

**Comment by eranif** [comment]
fixed
