### ISSUE TITLE
I don't know how to exit full screen mode and "Output view" is a blank pane

### ISSUE THREAD

**Issue by ChenKE404** [eranif/codelite#2666]
![image](https://user-images.githubusercontent.com/75658944/107636592-d42d2a00-6ca7-11eb-9787-dbce69d03032.png)
I just tried the full screen mode, then......  i can't find any way to exit this. >_<
I'm sorry about this,I'm a novice.(My English is poor.) >_<
Besides,my "Workspace view" and "Output view" are still blank(I'm using default.layout,I have no other layout strategy).my system is Windows 8.1,do I need other runtime or component?
I like this IDE's ui style and really want to write my programs in Codelite15,
So I hope you can help me @eranif ,thanks!
version: CodeLite15 or CodeLite14.0.4

**Comment by dghart** [comment]
The default shortcut to toggle full-screen mode is ALT-M, so that is the first thing to try.

If it fails, you have 2 options:
1) With CodeLite closed, open ${CodeLite configuration folder}/config/codelite.xml in an editor. Search for 'm_frameSize'; two lines below that you should have an entry:
<long Value="266" Name="m_flags"/> 
Change the Value setting to "11"
(If you had a different initial value, subtract 255 from that instead.)
Restart CodeLite and it should be OK.

2) If that fails, delete (or rename) your ${CodeLite configuration folder}, which will reset _everything_.

**Comment by ChenKE404** [comment]
> The default shortcut to toggle full-screen mode is ALT-M, so that is the first thing to try.
> 
> If it fails, you have 2 options:
> 
> 1. With CodeLite closed, open ${CodeLite configuration folder}/config/codelite.xml in an editor. Search for 'm_frameSize'; two lines below that you should have an entry:
>    `<long Value="266" Name="m_flags"/> `
>    Change the Value setting to "11"
>    (If you had a different initial value, subtract 255 from that instead.)
>    Restart CodeLite and it should be OK.
> 2. If that fails, delete (or rename) your ${CodeLite configuration folder}, which will reset _everything_.

Oh,thanks. ALT+M can do that.
I have another important question:
I opened a WorkSpace name is "workspace1",but the "WorkSpace View" and" Output view" is empty. I'm using default layout setting.Please take a look at this picture:
![image](https://user-images.githubusercontent.com/75658944/107767877-9ea04380-6d70-11eb-89f1-26205b1e17c1.png)

**Comment by dghart** [comment]
This is a tracker, a place for bug-reports. Both of your questions are indeed _questions_, and are unlikely to be bugs.

I suggest you ask this on the [CodeLite forum](https://codelite.org/forum/).

**Comment by ChenKE404** [comment]
> This is a tracker, a place for bug-reports. Both of your questions are indeed _questions_, and are unlikely to be bugs.
> 
> I suggest you ask this on the [CodeLite forum](https://codelite.org/forum/).

OK,Thank you for your patience in answering my questions.
That helped me a lot。
