### ISSUE TITLE
codelite is not opening

### ISSUE THREAD

**Issue by mayankr2** [eranif/codelite#2669]
Hi I downloaded the codelite version 15.0.0 today and then i tried to open it by double clicking on the shortcut but its not opening. I tried deleting the codelite folder in the app data but still it does not run. My system is windows 8

**Comment by eranif** [comment]
we never tested it on Windows 8. It was built on Windows 10. I can suggest that you try and run it with `--no-plugins` options and see if this helps

**Comment by jacaq** [comment]
I've had the same issue a few days ago. I'm not on windows 8 but my solution was to delete the appData file of codelite,
 try to find it in your pc like so : %appdata%\CodeLite
or just go to your c:/Users/YOURUSERNAME/AppData/roaming/codelite   

afterward you'll have to redo your settings as if new.

Its takes 2mins in all.
