### ISSUE TITLE
15.0.0 source formatter plugin issue

### ISSUE THREAD

**Issue by inalmeh** [eranif/codelite#2672]
I do all settings for source code formatter (c++, astyle), it works, but next time I close and reopen the IDE all settings are gone. I have to do all settings again, or it won't format the code. 

(c++, clang) doesn't work either.

**Comment by sillick-rfa** [comment]
> /home/debian/.codelite/lsp/clang-tools/clang-format: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory

This is what it says in the preview window when I try to adjust settings in clang-format in the plugin. I'm using a Debian Buster 10 VM in VMWare Workstation

**Comment by eranif** [comment]
Try installing `sudo apt-get install libncurses5` (this works at least on Ubuntu)
I will add this to the dependencies

**Comment by eranif** [comment]
This issue was fixed
