### ISSUE TITLE
"An assertion failed!" window appears every time I open Codelite

### ISSUE THREAD

**Issue by datalot-369** [eranif/codelite#2675]
## Summary

Every time I open Codelite with the `./codelite` command at the `bin` directory, codelite display the following backtrace:

```
ASSERT INFO:
../src/common/event.cpp(1926): assert "nNew != dynamicEvents.size()" failed in SearchDynamicEventTable().

BACKTRACE:
[1] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
[2] wxEvtHandler::TryHereOnly(wxEvent&)
[3] wxEvtHandler::ProcessEventLocally(wxEvent&)
[4] wxEvtHandler::ProcessEvent(wxEvent&)
[5] EventNotifier::ProcessEvent(wxEvent&)
[6] wxEvtHandler::ProcessPendingEvents()
[7] wxAppConsoleBase::ProcessPendingEvents()
[8] wxApp::DoIdle()
[9] g_main_context_dispatch
[10] g_main_loop_run
[11] gtk_main
[12] wxGUIEventLoop::DoRun()
[13] wxEventLoopBase::Run()
[14] wxAppConsoleBase::MainLoop()
[15] wxEntry(int&, wchar_t**)
[16] main
[17] __libc_start_main
[18] _start
```

![image](https://user-images.githubusercontent.com/21994415/108218469-107ae300-710b-11eb-9c97-88728696f8ee.png)

## System Description

```
- MX Linux 19.3 amd64 (Basically Debian Buster)
- XFCE 4.14
- GTK 3.24
- libwxgtk3.1-dev 3.1.4-1.buster
```

## Build Command 

> Obtained from the previous issue about compiling errors at https://github.com/eranif/codelite/issues/2674#issuecomment-779734172

```
cmake -G "Unix Makefiles" \
      VERBOSE=1 \
      -DCMAKE_BUILD_TYPE=DebugFull \
      -DCL_PREFIX=$(pwd)/../CLgtk3-install .. &&
make -j 2 &&
make install
```

**Comment by dghart** [comment]
Yes, I've seen it too from time to time. It seems to happen when a CodeLite instance is started without there being a Workspace loaded e.g. with 'Preferences > Misc: Load last settings on startup' not ticked, or when there hasn't been a Workspace created yet. Like all asserts, it will only be seen with a CodeLite debug build.

If you start CodeLite in gdb, you'd be able to get a backtrace which will look similar to this:
<0  0x00007ffff452c819  poll    
1  0x00007ffff76df136  ??    
2  0x00007ffff76df4c2  g_main_loop_run    
3  0x00007ffff7a4f583  gtk_dialog_run    
4  0x00007ffff66726b7  wxGUIAppTraits::ShowAssertDialog  /mnt/everythingelse/devel/git/wx/src/gtk/utilsgtk.cpp  382
5  0x00007ffff60e35a0  ShowAssertDialog  /mnt/everythingelse/devel/git/wx/src/common/appbase.cpp  1383
6  0x00007ffff60e1c53  wxAppConsoleBase::OnAssertFailure  /mnt/everythingelse/devel/git/wx/src/common/appbase.cpp  866
7  0x00007ffff6641b09  wxApp::OnAssertFailure  /mnt/everythingelse/devel/git/wx/src/gtk/app.cpp  515
8  0x00007ffff60e2846  wxDefaultAssertHandler  /mnt/everythingelse/devel/git/wx/src/common/appbase.cpp  1175
9  0x00007ffff60e2fa6  wxOnAssert  /mnt/everythingelse/devel/git/wx/src/common/appbase.cpp  1252
10  0x00007ffff61fcb9c  wxEvtHandler::SearchDynamicEventTable  /mnt/everythingelse/devel/git/wx/src/common/event.cpp  1917
11  0x00007ffff61fc1fa  wxEvtHandler::TryHereOnly  /mnt/everythingelse/devel/git/wx/src/common/event.cpp  1609
12  0x00007ffff61fdc79  wxEvtHandler::TryBeforeAndHere  /mnt/everythingelse/devel/git/wx/include/wx/event.h  3949
13  0x00007ffff61fc06d  wxEvtHandler::ProcessEventLocally  /mnt/everythingelse/devel/git/wx/src/common/event.cpp  1546
14  0x00007ffff61fc005  wxEvtHandler::ProcessEvent  /mnt/everythingelse/devel/git/wx/src/common/event.cpp  1519
15  0x00007ffff512bb32  EventNotifier::ProcessEvent  /mnt/everythingelse/devel/git/CL/CodeLite/event_notifier.cpp  136
16  0x00007ffff61fbbfc  wxEvtHandler::ProcessPendingEvents  /mnt/everythingelse/devel/git/wx/src/common/event.cpp  1383
17  0x00007ffff60e110f  wxAppConsoleBase::ProcessPendingEvents  /mnt/everythingelse/devel/git/wx/src/common/appbase.cpp  563
18  0x00007ffff6640b05  wxApp::DoIdle  /mnt/everythingelse/devel/git/wx/src/gtk/app.cpp  150
19  0x00007ffff6640982  wxapp_idle_callback  /mnt/everythingelse/devel/git/wx/src/gtk/app.cpp  100
20  0x00007ffff76dedd8  g_main_context_dispatch    
21  0x00007ffff76df1c8  ??    
22  0x00007ffff76df4c2  g_main_loop_run    
23  0x00007ffff7ae6b15  gtk_main    
24  0x00007ffff6659179  wxGUIEventLoop::DoRun  /mnt/everythingelse/devel/git/wx/src/gtk/evtloop.cpp  61
25  0x00007ffff6118c76  wxEventLoopBase::Run  /mnt/everythingelse/devel/git/wx/src/common/evtloopcmn.cpp  87
26  0x00007ffff60e0991  wxAppConsoleBase::MainLoop  /mnt/everythingelse/devel/git/wx/src/common/appbase.cpp  377
27  0x00007ffff60e06c7  wxAppConsoleBase::OnRun  /mnt/everythingelse/devel/git/wx/src/common/appbase.cpp  298
28  0x00007ffff67322b5  wxAppBase::OnRun  /mnt/everythingelse/devel/git/wx/src/common/appcmn.cpp  332
29  0x00007ffff614e33a  wxEntry  /mnt/everythingelse/devel/git/wx/src/common/init.cpp  504
30  0x00007ffff614e3fd  wxEntry  /mnt/everythingelse/devel/git/wx/src/common/init.cpp  516
31  0x0000555555a3463c  main  /mnt/everythingelse/devel/git/CL/LiteEditor/app.cpp  236
>
Apart from the first, 31, there's no CodeLite call there; it's all from wxWidgets, and that makes it very hard to debug. And like all such 'for your information' asserts, it's also not important provided nothing then goes wrong.

So I'll close this report; but of course you are welcome to debug the problem if you really want to...
