### ISSUE TITLE
Code Completing not working in the middle of the line (clang engine)

### ISSUE THREAD

**Issue by kasos5000** [eranif/codelite#2677]
Hello. I'm using the latest 15.0.0 version of CodeLite and and a problem has occurred with autocompletion. If there are another symbols in the line after the current position (if to work within parentheses, for example) it either offers incorrect arguments or doesn't work at all. That is, e. g:
set<string> words;
auto Inserted = words.insert(word);
        if (Inserted._offers weird arguments here, when I want to get "second"_) {... 
set<string> words;
But when the braces are wrapped:
auto Inserted = words.insert(word);
	if (Inserted._works well here_
        ) {... 
By reducing Priority of Lang Server I figured out, that the problem is in clangd engine. Smart Completion worked fine in any place, but it doesn't work with c++17 features.

**Comment by kasos5000** [comment]
PS. In VS Code with clangd installed all is working properly.

**Comment by eranif** [comment]
Can you provide a clear example that I can try locally? I do not experience the above behavior as you described it
