### ISSUE TITLE
Code completing for Ubuntu 20.10 doesn't work

### ISSUE THREAD

**Issue by Pioxis** [eranif/codelite#2679]
I installed fresh systems of Ubuntu
For 20.04 code completing is working fine.
For 20.10 code completing is not working.

The same steps, installed packages and configuration in CodeLite.

**Comment by eranif** [comment]
can you provide some steps to reproduce?

**Comment by Pioxis** [comment]
> can you provide some steps to reproduce?

I installed Ubuntu 20.04 like fresh OS. After that I installed build-essentials and CodeLite for 20.04. After that I created C++ project with code:

![image](https://user-images.githubusercontent.com/12051229/108708620-f6c60b00-7511-11eb-8244-2fb9acdcbe2f.png)

And when I'm writing count. <- here I should have code completion popup window with public parameters: x, y abd sum().

Like here:
![image](https://user-images.githubusercontent.com/12051229/108709501-11e54a80-7513-11eb-8a78-3d51e6a26f16.png)

I don't have that completion in fresh Ubuntu 20.10. But in fresh Ubuntu 20.04 it's working fine.

If you want I can do any steps on that virtual machines. 
That machines are implemented on Oracle Virtual Box.

**Comment by sillick-rfa** [comment]
Code completion also doesn't work in my Debian Buster VM.

**Comment by eranif** [comment]
It's hard for me to reproduce from screenshots. Please try and provide a zip workspace so I can open and try it locally

**Comment by Pioxis** [comment]
> It's hard for me to reproduce from screenshots. Please try and provide a zip workspace so I can open and try it locally

No problem, here is workspace from Ubuntu 20.10 where completing doesn't work. 
https://1drv.ms/u/s!AgzQDj-gLHdtkfoaqRuLrEPO9gpciQ?e=cM4Zi0

That workspace is the newest workspace fresh created on fresh installed OS.

**Comment by eranif** [comment]
One simple test to check:

can you open a terminal and type this?

`ps -ef|grep clangd`

Does it run?

**Comment by Pioxis** [comment]
> One simple test to check:
> 
> can you open a terminal and type this?
> 
> `ps -ef|grep clangd`
> 
> Does it run?
> If `clangd` is not running, can you try this?
> 
> ```
> cd ~/.codelite/lsp/clang-tools/
> ldd clangd
> ```
> 
> and print here the output?

`ps -ef|grep clangd`

![image](https://user-images.githubusercontent.com/12051229/108771032-572d6a80-755b-11eb-92d5-372d7b13a525.png)
`ldd clangd`
![image](https://user-images.githubusercontent.com/12051229/108771153-8643dc00-755b-11eb-9be6-9b61a6383c84.png)

**Comment by eranif** [comment]
install `libncurses5`
```
sudo apt-get install libncurses5
```

Then go to:

- plugins -> language server -> settings
- select the clangd tab
- make sure it is enabled
- click OK in the dialog

Build your project once and try to code complete something

**Comment by eranif** [comment]
the other two are placed under the same directory and CodeLite run's it like this:

```
LD_LIBRARY_PATH=~/.codelite/lsp/clang-tools:$LD_LIBRARY_PATH ./clangd
```

so they should be loaded, only `libncurses5` is system library

**Comment by Pioxis** [comment]
> install `libncurses5`
> 
> ```
> sudo apt-get install libncurses5
> ```
> 
> Then go to:
> 
> * plugins -> language server -> settings
> * select the clangd tab
> * make sure it is enabled
> * click OK in the dialog
> 
> Build your project once and try to code complete something

Installing libncurses5 fixed everything.
Thank you very much. You are amazing.
