### ISSUE TITLE
Files modified externally

### ISSUE THREAD

**Issue by HackiWimmer** [eranif/codelite#2680]
Hi, 
I'm using codelite 15.0.0 and I'm lost the functionality that external modified files will be notified - e. g. files which were actualized by a separate wxCrafter.  If I manually reload such a file, I get the actualized content.

May be I'm blind too, but I cant find a corresponding option . . .  and probably this also isn't an issue, but any Idea I can do? 

Many thanks in advance
Stefan

**Comment by eranif** [comment]
This was already reported and fixed.
https://github.com/eranif/codelite/commit/7883c26232247c41346ab5655857e88405ab789a

Hopefully, I will be able to release CodeLite 15.0.1 this week
