### ISSUE TITLE
Implement All Un-Implemented Functions not working

### ISSUE THREAD

**Issue by shadoww1028** [eranif/codelite#2684]
If your folder structure looks like:

Something/include
       -something.hpp
Something
       -something.cpp

if executing Implement All Un-Implemented Functions in the .hpp file it will not find the implementation file unless both files are in the same directory.  In this case they are not.  I have tried moving the files around in different ways and the only way it works is if they are in the same directory.  Version 15.0 on arch Linux using the -2 version from the AUR. 

I can swap between the .hpp and .cpp file just fine.  

Add Function Implementation also does not work.

**Comment by eranif** [comment]
Do you get an error from CodeLite?
something like:
```
Could not locate implementation file!
```

or anything like this?

**Comment by shadoww1028** [comment]
yup I get that exact dialog.

**Comment by eranif** [comment]
thanks, I was able to reproduce this
