### ISSUE TITLE
New stable CL-15.0.x release ?

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2685]
Hello,

Now that the most critical errors in CL-15.0.0 seems to be fixed - would you consider doing a new stable release (CL15.0.x) ?

This is not to offend you in any way - but with the current release frequency the issues mentioned below will appear broken to both new and existing users for the next year (and there are probably numerous other important fixes). 
Those listed below are just the ones that I'm hit by every day:

Issue #2665 - check for external file changes
Issue #2661 and #2671 - FileSystemWorkSpace path handling improvements (that made the indexer work again)
Issue #2660 - not all global shortcuts was working

PS: Especially issue #2665 can be rather dangerous/destructive to your code

Kind regards Uffe :-)

**Comment by eranif** [comment]
release is being processed as we speak. David should be tagging `15.0.1` as I write these lines :)

**Comment by uffejakobsen** [comment]
@eranif thank you so much :+1:  :-)

I'm closing this issue :-)
