### ISSUE TITLE
LLDB Settings

### ISSUE THREAD

**Issue by davidwed** [eranif/codelite#2690]
When I open the "LLDB Settings"( Settings -> LLDB Settings )  window, the controls are not arranged correctly. 
![image](https://user-images.githubusercontent.com/12169308/111301250-464fb080-8652-11eb-9a0f-34e3ee13e9e4.png)

If I then resize the window, the controls arrange themselves correctly.
![image](https://user-images.githubusercontent.com/12169308/111301284-52d40900-8652-11eb-8ab4-e95dd82e9908.png)

**Comment by davidwed** [comment]
Windows 10 / Version 15.0.0

**Comment by eranif** [comment]
:)
I wouldn't bother with this on Windows, since LLDB is not usable under Windows
