### ISSUE TITLE
Code Completition

### ISSUE THREAD

**Issue by davidwed** [eranif/codelite#2691]
The Suggest button does not work anymore.

![image](https://user-images.githubusercontent.com/12169308/111301765-e1e12100-8652-11eb-8f03-a234329a2c41.png)

**Comment by eranif** [comment]
Do you have compilers installed? - seems to be working just fine here on Windows 10

Check under: settings -> build settings

**Comment by davidwed** [comment]
![image](https://user-images.githubusercontent.com/12169308/111322496-4ad39380-8669-11eb-9cc7-71bfa51c2332.png)

**Comment by davidwed** [comment]
if I enter the paths manually, it works.

![image](https://user-images.githubusercontent.com/12169308/111329945-cf291500-866f-11eb-9ae1-cf2c5f8eaff4.png)

The path "c:\msys2\mingw64\bin" is added to the "PATH" variable.

**Comment by davidwed** [comment]
OK, I think I have found the cause.

If I change the compiler name from "MinGW 64bit ( MSYS2 64bit )" to "MinGW", the "Suggest" button works.

![image](https://user-images.githubusercontent.com/12169308/111331373-2085d400-8671-11eb-9ab7-5216d42fb273.png)
![image](https://user-images.githubusercontent.com/12169308/111331419-2b406900-8671-11eb-9c39-0acc18f26380.png)

**Comment by mparuzel** [comment]
I'm seeing something similar on Linux (Manjaro x64). F12 can't goto a symbol or declaration but Ctrl-Shift-R can. 

No change in toolchains or compilers on my end. CodeLite was updated only.
