### ISSUE TITLE
Color themes messed up for C

### ISSUE THREAD

**Issue by rucete** [eranif/codelite#2700]
I updated Codelite 13.0 to 14.0 (on Debian buster) after a full system upgrade and the color themes for C stopped working as they should. Theese pics are from [before](https://i.stack.imgur.com/Y4SjJ.png) the update and [after](https://i.stack.imgur.com/Sr5CX.png) the update. I've seen that @kevinsmia1939 has [the same problem](https://github.com/eranif/codelite/issues/2687#issuecomment-792051188).

This only happens with C, as when I try to manually map the color schemes (that is in preferences > colours and fonts > [customize](https://user-images.githubusercontent.com/57042029/112378280-0722fe80-8ce7-11eb-8f8f-833f435406e5.png)) I can only do it for C++ (and java and html and literally any other language but C).

I tried reinstalling and building from source as I thought the system upgrade would have messed it up, but no. Any help on how to fix this (or downgrade, wich I tried and failed) is welcome. I really like Codelite and would love to have it working again!

**Comment by dghart** [comment]
Hi,

The latest release is 15.0, which you can download from [our repo](https://wiki.codelite.org/pmwiki.php/Main/Repositories). Testing that with the Retta light theme (which I think you're using) looks OK to me: https://img.vim-cn.com/e4/9c5bc4e7d76cc1a55782f230f020728acca8fd.png 

>(or downgrade, which I tried and failed)

If you still want to, and for some reason you can't make apt downgrade it, you can download 13.0 from our repo: https://repos.codelite.org/debian-13.0/pool/devel/c/codelite/codelite_13.0-1unofficial2.buster_amd64.deb or, for gtk+3, https://repos.codelite.org/debian3-13.0/pool/devel/c/codelite/codelite_13.0-1unofficial3.buster_amd64.deb
and then install using dpkg.

Regards,

David
