### ISSUE TITLE
corrupted workspace 

### ISSUE THREAD

**Issue by bishoyzakhary** [eranif/codelite#2708]
every time i open codelite and select a workspace codlite show me this massage corrupted workspace file how can I solve it

**Comment by eranif** [comment]
Please check:
1. Is the workspace file really is corrupted (truncated etc)
2. Is the workspace loaded is provided by plugin (e.g. NodeJS or PHP) and make sure that these plugins are actually loaded in CodeLite

**Comment by bishoyzakhary** [comment]
solved, thank you
