### ISSUE TITLE
Change from external source no longer trigger a "reload"

### ISSUE THREAD

**Issue by Jarod42** [eranif/codelite#2715]
Windows
Codelite 15.0.0

When changing sources/projects from outside of Codelite (as when changing branches in system control, or regenerating project via Premake),
Codelite used to prompt to reload project/source file.

It is no longer the case.

**Comment by eranif** [comment]
This was fixed in `15.0.1` and later

**Comment by eranif** [comment]
this is the fix: https://github.com/eranif/codelite/issues/2665
