### ISSUE TITLE
Feature request: enable/disable LSP setting within each workspace/project

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2717]
Feature request: enable/disable LSP setting within each workspace/project

Example/problem:
When you are using CL for multiple projects - some of them where LSP is quite usefull - and others where LSP is not feasible or desired.

When LSP plugin is enabled the traditional indexer/lookup does not really work

In the above scenarios It would be nice if LSP could be controlled within the workspace or project settings and not globally.

Currently the user have to manually enable/disable LSP for each project that he/she switches between

**Comment by eranif** [comment]
Have you tried lowering the `clang` LSP priority value to `50`?
This way, the old completion engine is always engaged and in case it fails, it will pass over to the next one in chain (in your case `clangd`), below table summarises the default priorities of the builtin completion engines of CodeLite:

Provider|Language|Priority 
--------|--------|--------
C++ by ctags |C/C++ |75
PHP plugin |PHP |50
WebTools |XML |50
WebTools |CSS |50
WebTools |JavaScript |50 

If `clangd` priority (which is `90`) is lowered to value less than `75`, ctags completion engine will kick in first. If it fails, the control is passed to the next one

**Comment by uffejakobsen** [comment]
@eranif thanks for the insight into the priority - I've been wondering about that (but still not enough to go through the code behind it)
I'll give it a try...
But please correct me if I'm wrong - by lowering the priority of the LSP - 
It is a global setting - won't I just create the opposite problem of what I have now ?
Today I have the problem with some projects that LSP fails - and that prevents completion and resource lookup from working.
When lowering the global priority of the LSP the above mentioned projects will now work - but the other projects where LSP is working will now switch to use the old completion ? 

if that is correct then I'll still need to switch the priority between projects - or ?

I guess that the resource lookup window/dialog only uses one source at a time ? either results from the old completion or LSP - it is not mixing results - or ?

**Comment by eranif** [comment]
In case the old code completion will fail, it will trigger the LSP so its like a chain
NOTE that the chain is only working in one direction:

`CTags` -> `LSP`

it does not work in this direction:

`LSP` -> `CTags`

**Comment by uffejakobsen** [comment]
Ah thanks for the clarification. I'll give it a try :-)

**Comment by uffejakobsen** [comment]
Closing this feature request for now :-)
