### ISSUE TITLE
LiteEditor/taskpanel.cpp: No such file or directory

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2718]
There seems to be missing a file from the repo on lateest master

Building on (Arch) Linux 

```
[ 77%] Building CXX object LiteEditor/CMakeFiles/codelite.dir/taskpanel.cpp.o
c++: error: /tmp/codelite-devel.git/LiteEditor/taskpanel.cpp: No such file or directory
c++: fatal error: no input files
compilation terminated.
```

**Comment by eranif** [comment]
You need to re-run `cmake`

**Comment by uffejakobsen** [comment]
thanks
Actually I expected that cmake was able to determine if it should reconfigure itself in these update situations - 
Meson/ninja has some logic that detects these situations - but that does not seem to happen with cmake
