### ISSUE TITLE
Setting WXWIN and WXCFG not working under Workspace -> Settings -> Environment

### ISSUE THREAD

**Issue by MeerMusik** [eranif/codelite#2720]
I either have to copy the PATH from the System -> Environment and add the Directory to Workspace -> Settings -> Environment like
`PATH=$PATH$;C:/Dev/msys64/usr/bin/;C:/Dev/Sources/wxWidgetsx64Release/bin`

or set the Path to wx-config directly like
`Compiler: $(shell /c/Dev/Sources/wxWidgetsx64Release/bin/wx-config --cxxflags --unicode=yes --debug=no)
Linker: $(shell /c/Dev/Sources/wxWidgetsx64Release/bin/wx-config --debug=no --libs --unicode=yes)
Resources: $(shell /c/Dev/Sources/wxWidgetsx64Release/bin/wx-config --rcflags)`

Setting WXWIN and WXCFG under Workspace -> Settings -> Environment gets ignored. No matter what I set there, it simply does not work.

* Codelite 15.0.2 pre-built, April 13th, x86_64
* Windows 10 20H2, x86_64
* MSYS64, MinGW-w64 10.2.0
* wxWidgets self-built from Git Source, latest Version

**Comment by stahta01** [comment]
Did you try using "wx-config.exe" instead of "wx-config" ?
When I was testing this I have some issues where adding the exe help; I forgot when it helped.

I am getting the below to work in "Workspace -> Settings -> Environment"
`WXWIN=C:\src\wxWidgets
WXCFG=gcc_dll\mswu` 

Note: I have to use exactly the above for WXCFG because the real location did not work for me.
So, I copied the folder to that name.

Tim S.

**Comment by MeerMusik** [comment]
Adding '.exe' makes no difference - the symbolic Link Name is 'wx-config' anyway.

My working set up under the Project Settings -> Environment is now:
* WXWIN=C:/Dev/Binaries/wxWidgetsx64Release/
* WXCFG=wx/config

And then I have to add the Path to 'wx-config' to make it work:
* PATH=$PATH$;C:/Dev/Binaries/wxWidgetsx64Release/bin

**Comment by eranif** [comment]
`WXCFG` should be in the format as stahta01 stated: `gcc_dll\mswu` (or gcc_dll/mswu`)
Showing us the build output will be more useful than saying: "it does not work"

**Comment by MeerMusik** [comment]
Of course I have tried `gcc_dll/mswu` - with and without renaming
* `lib/wx/config` to
* `lib/gcc_dll/mswu` - I just forgot to mention it. My fault.

The Build Output is always:
`C:/Dev/msys64/usr/bin/make.exe -e -f  Makefile
----------Building project:[ AKKomPolTool - Releasex64 ]----------
make[1]: Entering directory '/c/Dev/CodeLiteWorkspace/AKKomPolTool'

Please use the --prefix flag (as in wx-config --prefix=C:/wxWidgets)
or set the environment variable WXWIN (as in WXWIN=C:/wxWidgets)
to specify where is your installation of wxWidgets.

Please use the --prefix flag (as in wx-config --prefix=C:/wxWidgets)
or set the environment variable WXWIN (as in WXWIN=C:/wxWidgets)
to specify where is your installation of wxWidgets.
C:/Dev/msys64/mingw64/bin/windres.exe -i "C:/Dev/CodeLiteWorkspace/AKKomPolTool/AKKomPolTool.rc"    -o ../build-Releasex64/AKKomPolTool/AKKomPolTool.rc.o
/bin/sh: -c: line 1: unexpected EOF while looking for matching `''
/bin/sh: -c: line 2: syntax error: unexpected end of file
make[1]: *** [AKKomPolTool.mk:103: ../build-Releasex64/AKKomPolTool/main.cpp.o.d] Error 2
make: *** [Makefile:5: All] Error 2
make[1]: Leaving directory '/c/Dev/CodeLiteWorkspace/AKKomPolTool'
====0 errors, 0 warnings====`

The Workspace / Project -> Settings -> Environment Entries are:
* `WXWIN=C:/Dev/Binaries/wxWidgetsx64Release/`
* `WXCFG=gcc_dll/mswu`

Either way: If you are forced to use `gcc_dll/mswu` by renaming the Default Directories, then this is really bad. I know by now that the wxWidgets Scripts are "messy" (to use a nice word here): I have already add a command to my wxWidgets CMake Build Scripts to copy `include/wx/msw/setup.h` to `include/wx/setup.h` to work around that specific bug.

It is a shame that it is so broken even after all these years. If it is another bug in wxWidgets and not in CodeLite, then feel free to close this BR.

(Yes badly hardcoding things, I do consider a bug instead of a limitation...)

Oliver

**Comment by stahta01** [comment]
wx-config.exe was never supposed to support cmake built wxWidgets!

Tim S.

**Comment by MeerMusik** [comment]
Bug is not solved as CMake seems the way forward or at least full support is planned for it mid-term. But: I have moved on to another Framework. Should I ever come back to wxWidgets, I will re-open it if necessary.

Good Luck with your IDE! Keep up the good work :)
