### ISSUE TITLE
External Tools plugin doesn't work in 15.0.3 

### ISSUE THREAD

**Issue by pawo1** [eranif/codelite#2724]
After update Codelite from 15.0.0 to 15.0.3 (with Keep local settings option) External Tools plugin doesn't run tools. Downgrade to 15.0.0 solves the problem.

**Comment by eranif** [comment]
Can you give an example for such tool? 
I tested it on Linux / Ubuntu and it seems to work as it did before

**Comment by pawo1** [comment]
I use CodeLite on Windows. Here is example of Script i used with External Tools:
`run $(WorkspacePath)/build-$(WorkspaceConfiguration)/bin/$(OutputFile)`
Nothing happens. (`run` is script added to system PATH variable, it's visible via console, and also works with 15.0.0 without any problems)

Tried run cmd.exe and opened new console, but if i add any arguments for tool it stops working (it means that plugin doesn't run tool). On 15.0.0 Tools with arguments works well
