### ISSUE TITLE
Debug into a dynamic library using CodeLite ?

### ISSUE THREAD

**Issue by jiapei100** [eranif/codelite#2726]
Hi, @eranif : haven't used CodeLite for a bit. However, CodeLite is the most convenient IMO.

I'm using Ubuntu 20.04+CodeLite 15.0.3 (built from source ).

I've got 2 projects under the same CodeLite WorkSpace:
- **Project A** built out a dynamic library **A.so**
- **Project B** built out an executable **B**, which calls **A.so**

Both projects A and B have been successfully built in **Debug** mode without errors. 

By running executable **B**, I actually would like to debug into the dynamic library **A.so** . However, CodeLite just igores the dynamic library **ALL the time**, and finished running executable **B** with an **ERROR** unwanted output.

Any suggestions @eranif ?

Looking forward to your reply.

Cheers
Pei

**Comment by eranif** [comment]
Make sure that:
- Both executable and shared objects are built with debug info, preferably `-g -O0`
- Make sure that when loading the executable with the debugger the first path in `LD_LIBRARY_PATH` is pointing to the location of the `A.so`

**Comment by jiapei100** [comment]
Thank you @eranif 

All the shared dynamic libraries are built with the following 
- C++ Compiler Options: `-g;-std=c++17;-Wall;-fPIC`
- C Compiler Options: `-g;-std=c99;-Wall;-fPIC`

And the executable is built with the following
- C++ Compiler Options: `-g;-O0;-std=c++17;-Wall;-fPIC`
- C Compiler Options: `-g;-O0;-std=c99;-Wall;-fPIC`

And for the executable **Linker Libraries**: all my built shared dynamic libraries are put before the other system libaries.

Any other suggestions?
