### ISSUE TITLE
error when I include iostream

### ISSUE THREAD

**Issue by Drummer08** [eranif/codelite#2730]
When I include iostream I got a bookmark error in Codelite.

> In included file: 'stddef.h' file not found
> /usr/include/whar.h:35:10:
> note: error occured here

I got also an bookmark error when I use std::cout.

> No member named 'cout' in namespace 'std'

My code looks like this:
```
#include <iostream>

int main() {
    std::cout << "Hello World" << std::endl;
    return 0;
}
```
For std::endl it doesn't show an error.

In Codelite I use a custom Makefile and my code compiles without any error.
My Makefile looks like this:

```
gpp       = g++
CFLAGS   = -Wall
SRCFILES = main.cpp
OBJFILES = main.o
TARGET   = program

all: $(TARGET) clean

$(TARGET): $(OBJFILES)
	$(gpp) -o $(TARGET) $(OBJFILES)
	
$(OBJFILES): $(SRCFILES)
	$(gpp) -c $(SRCFILES) $(CFLAGS)
	
clean:
	rm -f $(OBJFILES)
```
I use Ubuntu 20.04, gcc-9 and Codelite-Version 15.0.0. 
Why do I get these errors in Codelite.

**Comment by eranif** [comment]
You need to provide `clangd` a `compile_flags.txt` file
see here:
https://docs.codelite.org/plugins/lsp/#compile_flagstxt-compile_commandsjson
