### ISSUE TITLE
codelite with golang server (gopls)

### ISSUE THREAD

**Issue by vnluc** [eranif/codelite#2732]
I am using codelite and want to write go in it. I try to setup golang server in menu
**plugin -> language Server -> Settings**

command: C:\Users\vu\go\bin\gopls.exe
languages: go
connection string: stdio

After that the code screen still not have syntax highlighting or Code completion. 
Anyone have successfully set it? or what else needed to support golang?

**Comment by eranif** [comment]
this is because golang has no syntax highlight support in codelite
this means, no code completion events, hence no completion. You might want to tweak one of the other languages by adding the proper file extension + keywords

**Comment by vnluc** [comment]
Hi @eranif , it seem confusing to me. Is that with Language server then Codelite will be able to get all of syntax Highlighting and Code completion from Language server?  I think language server will handle all language setup and code completion? Then codelite just get those from gopls Language server?
