### ISSUE TITLE
OSX SVN Diff not working 

### ISSUE THREAD

**Issue by Kanimies** [eranif/codelite#2734]
For some files the diff seems to work while for others not - when double clicking a modified file in the SVN tab to show changes in diff I get an error stating "Right Side File does not exist".

<img width="422" alt="Right Side File" src="https://user-images.githubusercontent.com/7421922/118452093-87217f80-b6fe-11eb-9d89-8407d48dec37.png">

**Comment by eranif** [comment]
Does the file is a *new* file?

**Comment by Kanimies** [comment]
No, some of them have been around for 20 years :).

**Comment by Kanimies** [comment]
I'm starting to think this has to do with my SSD failing, I'll close this for now!
