### ISSUE TITLE
Debug configuration not compiling under MinGW

### ISSUE THREAD

**Issue by Zac610** [eranif/codelite#2736]
Compiling any C++ code will produce the error:

`g++.exe: error: /Zi: No such file or directory`

switching to Release configuration does compile without problems.

The issue is that /Zi is not a flag recognized by MingGW g++.exe compiler. This flag is set in auto-genrate .mk file into CXXFLAGS symbol.

**Comment by MeerMusik** [comment]
Can you please post the Output of 'gcc -v' ? I find this very odd and would like to take a look at it - if possible. With GCC (MinGW-w64 on MSYS2, 10.3.0) and CodeLite 15.0.0 upto 15.0.3, I do not have such Issues.

DISCLAIMER: I am not a Developer, only a User who likes to have a working IDE :)

**Comment by Zac610** [comment]
Hey @MeerMusik , follows the output of gcc -v command.

I also have 15.0.3, and I installed mingw-w64-install.exe package. Didn't know about [MSYS2 ](https://www.msys2.org/)project, will try it.

Perhaps the problem lies in the fact I have also some Visual Studio version installed (2010, 2013, 2015, 2019), and during the initial wizard Codelite did find also MSVC environment, which then I have manually deleted from the compilers list. It could be that Codelite still think in some cached file it has to set the MSVC compiler using /Zi flag even for MinGW?

I also like a lot this IDE, and I want to improve it! :)

> C:\Users\zac>gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=C:/Sviluppo/MinGW/Mingw32/bin/../libexec/gcc/i686-w64-mingw32/8.1.0/lto-wrapper.exe
> Target: i686-w64-mingw32
> Configured with: ../../../src/gcc-8.1.0/configure --host=i686-w64-mingw32 --build=i686-w64-mingw32 --target=i686-w64-mingw32 --prefix=/mingw32 --with-sysroot=/c/mingw810/i686-810-posix-dwarf-rt_v6-rev0/mingw32 --enable-shared --enable-static --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --disable-sjlj-exceptions --with-dwarf2 --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=i686 --with-tune=generic --with-libiconv --with-system-zlib --with-gmp=/c/mingw810/prerequisites/i686-w64-mingw32-static --with-mpfr=/c/mingw810/prerequisites/i686-w64-mingw32-static --with-mpc=/c/mingw810/prerequisites/i686-w64-mingw32-static --with-isl=/c/mingw810/prerequisites/i686-w64-mingw32-static --with-pkgversion='i686-posix-dwarf-rev0, Built by MinGW-W64 project' --with-bugurl=https://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -fno-ident -I/c/mingw810/i686-810-posix-dwarf-rt_v6-rev0/mingw32/opt/include -I/c/mingw810/prerequisites/i686-zlib-static/include -I/c/mingw810/prerequisites/i686-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -fno-ident -I/c/mingw810/i686-810-posix-dwarf-rt_v6-rev0/mingw32/opt/include -I/c/mingw810/prerequisites/i686-zlib-static/include -I/c/mingw810/prerequisites/i686-w64-mingw32-static/include' CPPFLAGS=' -I/c/mingw810/i686-810-posix-dwarf-rt_v6-rev0/mingw32/opt/include -I/c/mingw810/prerequisites/i686-zlib-static/include -I/c/mingw810/prerequisites/i686-w64-mingw32-static/include' LDFLAGS='-pipe -fno-ident -L/c/mingw810/i686-810-posix-dwarf-rt_v6-rev0/mingw32/opt/lib -L/c/mingw810/prerequisites/i686-zlib-static/lib -L/c/mingw810/prerequisites/i686-w64-mingw32-static/lib -Wl,--large-address-aware'
> Thread model: posix
> gcc version 8.1.0 (i686-posix-dwarf-rev0, Built by MinGW-W64 project)

**Comment by Zac610** [comment]
Ok, tried on another Windows 10 PC: 
- installed CodeLite Stable (15.0.0)
- installed MSYS2
- Codelite found MSYS2 and other Visual Studio compilers
- set-up the same workspace

The auto-generated .mk file is different:
![Cattura](https://user-images.githubusercontent.com/9107495/119351337-a9883f80-bca0-11eb-8c9e-3a3703c22409.PNG)

what is the component that create that .mk file?

**Comment by MeerMusik** [comment]
Thanks. I downloaded and tested that Version - no Issues here.

But: I do not have VS 2019 installed any longer. In fact, I just removed it a couple of weeks ago and I do not have any Intention to install it again. Ergo: I will not test that Combination

Anyway, I guess either the Makefile Generator you are / were using did not correctly clean the Cache or something else went wrong. There have been a couple reports about Misdetecting MinGW x86_64 for i686 (which I experienced my self) and other things. Some of that is fixed in the latest IDE Version - other things seems to have been improved from looking at commits (but I can not test those cases, as I do not use other Compiler than MinGW-w64 on MSYS2).

Have you fixed that Debug Problem by now? Does '/Zi' still get set when switch back to Debug?

"what is the component that create that .mk file?"
Good Question. I never took a look at the IDE Source Code itself yet - so I can not answer that.

Good luck

**Comment by eranif** [comment]
This means that the compiler set in the project settings is VC and not from the GCC family.
To change it, right click on the project in the tree view (usually a blue folder) and select `Settings -> General` and change the selected compiler on that page
