### ISSUE TITLE
Add "Find File/Typedef/Class/Function in Workspace"

### ISSUE THREAD

**Issue by eranif** [eranif/codelite#274]
It would be useful if there was a single dialog to search for all kinds of "symbols" in a workspace at once - files, typedefs, classes, functions, macros, namespaces... So if I type "print", I get the "PrintStuff()" function as well as the StuffPrinter.c file and the StuffPrinter class and the DEBUG_PRINT() macro etc.

I don't know if that would be possible speed-wise, but it would remove the need to memorize several different key combos for the different dialogs.

**Comment by davidhealey** [comment]
How does one do this? I couldn't find a shortcut key for it.

**Comment by eranif** [comment]
Resurrecting a 9 years old issue :) 

`Ctrl-Shift-R`

**Comment by davidhealey** [comment]
Perfect, thanks :)

**Comment by eranif** [comment]
Tip: go to `Settings -> Keyboard shortcuts` and get a list of all available shortcuts
