### ISSUE TITLE
again: horizontal scroll -> overlapping text

### ISSUE THREAD

**Issue by freanux** [eranif/codelite#2758]
it was fixed, 4 years ago (#1742), but now, it appears again:

![Screenshot from 2021-06-16 08-31-45](https://user-images.githubusercontent.com/11588703/122169792-18128480-ce7e-11eb-814d-780e4203d72a.png)

System: Ubuntu 20.04.2 LTS
Codelite: Version 15.0

![Screenshot from 2021-06-16 08-38-58](https://user-images.githubusercontent.com/11588703/122170023-632c9780-ce7e-11eb-82f1-2085330e6f1f.png)
![Screenshot from 2021-06-16 08-39-17](https://user-images.githubusercontent.com/11588703/122170029-658ef180-ce7e-11eb-94cc-c157a36c9dfd.png)

**Comment by eranif** [comment]
is this something new?
When did you upgrade your CodeLite?

The offending method (at least according to the previous bug commit) was not changed for a long time now)

**Comment by freanux** [comment]
A few day ago, i updated to Ubuntu 20.04, picked CodeLite 15.0.0 and built it. And for this, I built wxWidgets 3.1.5 from scratch. I have no idea, why this happens again... I will poke around a little bit....

**Comment by eranif** [comment]
An update: I managed to reproduce this and pushed a commit that fixes this locally
Something to do with buffered drawing...
