### ISSUE TITLE
Tag 15.0.4 and latest HEAD does not build on archlinux

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2759]
Tag 15.0.4 and latest HEAD does not build on archlinux

Issue can be reproduced on several archlinux installations

Output from 15.0.4 checkout

```
[  4%] Built target databaselayersqlite
[ 14%] Built target libcodelite
Consolidate compiler generated dependencies of target plugin
[ 14%] Building CXX object Plugin/CMakeFiles/plugin.dir/clCaptionBar.cpp.o
/root/uj.dir/codelite.git/Plugin/clCaptionBar.cpp: In member function ‘void clCaptionBar::OnPaint(wxPaintEvent&)’:
/root/uj.dir/codelite.git/Plugin/clCaptionBar.cpp:142:14: error: ‘FromDIP’ was not declared in this scope
  142 |     int xx = FromDIP(SPACER);
      |              ^~~~~~~
/root/uj.dir/codelite.git/Plugin/clCaptionBar.cpp: In member function ‘void clCaptionBar::DoSetBestSize()’:
/root/uj.dir/codelite.git/Plugin/clCaptionBar.cpp:296:15: error: ‘FromDIP’ was not declared in this scope
  296 |     r.Inflate(FromDIP(SPACER));
      |               ^~~~~~~

```

**Comment by eranif** [comment]
wx3.0 issue.
Is it possible to upgrade to wx3.1.x?

**Comment by uffejakobsen** [comment]
It seems that archlinux is only shipping official packages of wxgtk 3.0 as wxgtk 3.1.x unstable

Packaging codelite for archlinux with a wxgtk 3.1.x release that needs to be "built by hand" is likely to give some problems for some of the users...

Anyway - I can see that you have made commits to master that fixes the problem - so I think that I'll just skip the update of the codelite-unstable package for now - and wait for 15.0.5

I'm closing this issue 

Thanks :-)

**Comment by eranif** [comment]
sure, np. Sorry about that :)
