### ISSUE TITLE
More recent version for Linux

### ISSUE THREAD

**Issue by historic1** [eranif/codelite#2762]
I just switched my laptop to LinuxMint and installed CodeLite. Unfortunately Synaptic only offered v.12 but I was able to upgrade to the latest available, which is only 13.0+dfsg-1

Any plans to make v.15 available as well? GIven the huge difference I noticed from 12 to 13 I think it'd be really great.

**Comment by eranif** [comment]
https://docs.codelite.org/downloads/download/#ubuntu-debian
