### ISSUE TITLE
Codelite-terminal not working on MacOS Big Sur 11.4

### ISSUE THREAD

**Issue by TRTurn** [eranif/codelite#2767]
Codelite terminal is not appearing. This issue was previously reported but went stale. My MacBook has an M1 chip in case that is relevant.

**Comment by eranif** [comment]
this should be fixed with the latest commit

**Comment by blockchaindevel** [comment]
Can someone verify that this is fixed in 15.0.5?
I can't get the codelite-terminal to work on Windows or Mac/M1 with CodeLite 15.0.5.
