### ISSUE TITLE
Frame Title: workspace macro seems empty

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2776]
I've  configured Misc/Frame Title like this:

$workspace  -  $filename  -  $fullpath

But only filename and fullpath shows correctly in the window title bar - workspace macro seems empty

**Comment by eranif** [comment]
Can I assume that you are using the file System workspace?

**Comment by uffejakobsen** [comment]
> Can I assume that you are using the file System workspace?

Yes, that is correct (sorry forgot about that detail) :-)
