### ISSUE TITLE
Add ability to not build not needed plugins/features

### ISSUE THREAD

**Issue by salahmak** [eranif/codelite#2779]
Hi, Codelite is a great IDE for C++, but I find myself only using few features, it would be really great if you add support for only building features needed, for example, I don't need web dev support if I'm going to use it for C++, same goes for wxcrafter if I'm only gonna use it for CLI based stuff, so it is better if i don't build it at all in the IDE which would save me some resources on my limited PC.

(smth like the gentoo USE flags, so the user chooses what to build and what to leave)

Thanks

**Comment by stahta01** [comment]
What build method do you use?
cmake, CodeLite project, or what?

Tim S.

**Comment by eranif** [comment]
To add to what Tim asked, which OS are you using?
Adding this to the `CMake` is pretty easy task, for Windows, you can just disable the build order in the IDE
So, some more information will be great

**Comment by salahmak** [comment]
Thanks for reaching out, so here is my system info:
OS: Arch linux (Gentoo too)
build system: cmake (I'm not good at writing cmake tho, I just use it)

**Comment by salahmak** [comment]
@eranif so i have looked though the cmake file, and I have found the lines of `add_subdirectory(smth)`, so do I just have to remove those so they don't compile? or is there smth else to do?
