### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by AscendancyX** [eranif/codelite#2780]
so i accidentally restored my codelite files because codelite wasn't opening, even on administrator, and someone said it would work, but now i lost all my c++ files. is there a way to get them back? please

**Comment by eranif** [comment]
where did you "store" them? CodeLite does not delete files (unless you specifically asked it to do so, and even then, there are multiple dialogs warnings you from doing so).

If your files are not on the file system (trash bin, or somewhere on the disk), or there are not in some kind of source control (like `git`, `svn` etc) then you can't restore them
