### ISSUE TITLE
The new redesigned CodeLite icon doesn't scale well to the default Windows desktop icon size

### ISSUE THREAD

**Issue by Eric-01** [eranif/codelite#2792]
After the recent redesign of the CodeLite icon, the new one doesn't scale well to the default Windows desktop icon size (which is consistently 48×48 px since Windows Vista) and looks rough and chopped. For comparison, the previous one looked much smoother.

The new icon on a white desktop background:
![New-rough-icon](https://user-images.githubusercontent.com/46398175/127854188-325b7ce4-79ef-478e-831f-690d26f29956.png)

**Comment by eranif** [comment]
thanks, i am pretty sure we created a multiple sizes, will check if 48 is missing

**Comment by eranif** [comment]
a quick look at the script that generates the icon confirms this:

https://github.com/eranif/codelite/blob/master/svgs/svgs-dark/create-logo.sh#L65
