### ISSUE TITLE
scan error in wizzard

### ISSUE THREAD

**Issue by ABDULBASITLATIF** [eranif/codelite#2797]
when i click on scan button to scan for mingw code lite close .please solve this issue thank you

**Comment by eranif** [comment]
this sounds like a corrupted configuration.
which CodeLite version are you using and on which OS?

**Comment by ABDULBASITLATIF** [comment]
I downloaded codelite latest version and i have two  C++ compilers one is
mingw64 and other is tdm gcc but when i click on scan in wizzard codelite
closes and nothing happens

**Comment by eranif** [comment]
Which OS? (Windows/macOS/Linux)

**Comment by ABDULBASITLATIF** [comment]
Windows 10

**Comment by eranif** [comment]
Try and delete the folder `%appdata%/CodeLite`

**Comment by Mahmoud-Abdelraouf** [comment]
i download mingw64 and i set the path of mingw64/bin on variable systems, but the codelite cannot find the compiler when i scan for it
