### ISSUE TITLE
Ubuntu Focal Dev Packages Don't work Regardless of Mint

### ISSUE THREAD

**Issue by MadMartian** [eranif/codelite#2801]
On the `WxWidgets31Binaries` Wiki for using pre-built wxWidgets packages, the description below is not strictly correct:

```
For Mint 20 the ubuntu focal dev packages don't work. That is because Mint puts its grep and egrep in /bin/ instead of /usr/bin/. As a result the wx-config script doesn't work properly. See this wxForum thread for possible workarounds. 
```

This applies to **Unbutu Focal in general**, not just _Mint_.  The wiki could suggest as a work-around to symlink `/bin/grep` and `/bin/egrep` to `/usr/bin/grep` and `/usr/bin/egrep`, which is relatively benign and non-intrusive IMHO.

**Comment by dghart** [comment]
Hi,

> This applies to Unbutu Focal in general

I don't think that's true. I have a standard ubuntu focal install, plus virtualbox guests of ubuntu and [klx]ubuntu. In all of these, /bin/ is a symlink to /usr/bin/.

>  The wiki could suggest as a work-around to symlink /bin/grep and /bin/egrep to /usr/bin/grep and /usr/bin/egrep, which is relatively benign and non-intrusive IMHO.

Did you try this? As I mentioned in the linked forum thread, for me, trying to symlink instead caused an infinite loop.

Regards,

David

**Comment by MadMartian** [comment]
Yeah I confirmed this on my Ubuntu distro, and the symlinking work-around worked fine for me.  I suppose the symlink work-around is hit or miss then.

**Comment by dghart** [comment]
That's strange. 

I still have the original ubuntu focal iso that I installed from, so I just created a new virtualbox guest and checked: see https://pasteboard.co/Kf7iG2P.png

Is your ubuntu a standard ubuntu focal, or some variant?

**Comment by MadMartian** [comment]
It's Ubuntu Focal, but I wonder if my `grep` package came from someplace else:

```
Package: grep
Essential: yes
Status: install ok installed
Priority: required
Section: utils
Installed-Size: 496
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: foreign
Version: 3.4-1
Provides: rgrep
Depends: dpkg (>= 1.15.4) | install-info
Pre-Depends: libc6 (>= 2.14), libpcre3
Suggests: libpcre3 (>= 7.7)
Conflicts: rgrep
Description: GNU grep, egrep and fgrep
 'grep' is a utility to search for text in files; it can be used from the
 command line or in scripts.  Even if you don't want to use it, other packages
 on your system probably will.
 .
 The GNU family of grep utilities may be the "fastest grep in the west".
 GNU grep is based on a fast lazy-state deterministic matcher (about
 twice as fast as stock Unix egrep) hybridized with a Boyer-Moore-Gosper
 search for a fixed string that eliminates impossible text from being
 considered by the full regexp matcher without necessarily having to
 look at every character. The result is typically many times faster
 than Unix grep or egrep. (Regular expressions containing backreferencing
 will run more slowly, however.)
Original-Maintainer: Anibal Monsalve Salazar <anibal@debian.org>
Homepage: http://www.gnu.org/software/grep/
```

**Comment by dghart** [comment]
>  I wonder if my grep package came from someplace else

Perhaps; mine has a filesize of 199136 bytes.

What about your /bin/ though? Is that a symlink to /usr/bin/, or a real dir?

**Comment by MadMartian** [comment]
`/bin` is a real dir on a `/` mount point, and `/usr` is on a separate mount point.

**Comment by dghart** [comment]
OK. I don't know how how/why your setup is different from mine, and from the ubuntu focal ISO.

Thank you for reporting it but, until other people also report problems, I don't think it's sensible to alter the wiki text.
