### ISSUE TITLE
Selected theme applies only to the editor window

### ISSUE THREAD

**Issue by wittend** [eranif/codelite#2804]
Setting a theme in settings > Colors and Fonts  only affects editor window, not the rest of the editor chrome.  Use custom base color is greyed, and unavailable.  Codelite 15.04 Running on Ubuntu 18.04.

![Codelite-15 04-Ubuntu18 04theme-issues](https://user-images.githubusercontent.com/337442/128742322-0467934e-804f-46b5-a435-11cb0d0c4eb4.png)

**Comment by Eric-01** [comment]
This is intended I think (and I hope it will stay like that :) ). To change the interface theme, go to Settings -> Colors and Fonts, and then check the "Use custom base color" checkbox and choose a preferred dark color.

**Comment by Eric-01** [comment]
This is intended, I think (and I hope it will stay like that :) ). To change the interface theme, go to Settings -> Colors and Fonts, and then check the "Use custom base color" checkbox and choose a preferred dark color.

**Comment by Eric-01** [comment]
This is intended, I think (and I hope it will stay like that :) ). To change the interface theme, go to Settings -> Colors and Fonts, and then tick the "Use custom base color" checkbox and choose a preferred dark color.

**Comment by wittend** [comment]
Eric,

Thanks for the response.
Unfortunately, "Use custom base color" is greyed out and the checkbox is
inaccessible.

Dave

**Comment by Eric-01** [comment]
Good too know that it works much differently on Linux than on Windows. Do you use a dark GTK theme on your desktop environment?

**Comment by wittend** [comment]
I use a cinnamon desktop. - perhaps that is the problem.  I suspect that I
installed a toned-down theme.  I am having problems with glare as I get
older.
I never liked the Ubuntu desktop but I had to install straight Ubuntu to
make some NVidia dev tools happy back in the day.
Now I really need ro upgrade (probably to Mint) but that is more traumatic
than I can cope with at the moment.

Dave

**Comment by eranif** [comment]
this behavior is on Linux only. In order to allow "full" custom base colour, you will need to build CodeLite with the generic notebook control and not with the native one (which is what we are using on Linux)

Since on Linux, the variety of themes is so large, you can pick `Adwaita Dark` and get a full black IDE.

**Comment by eranif** [comment]
This is how it looks on `Adwaita-dark` on Linux:
![1](https://user-images.githubusercontent.com/3677711/129316264-17d03df6-be31-49d3-8e1b-ff4cf89b465f.png)
