### ISSUE TITLE
"Find Next" (CTRL-G) new undesirable behaviour with CL-15.0.6

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2806]
"Find Next" (CTRL-G) has got new undesirable behaviour with CL-15.0.6

Pressing CTRL-G now opens the bottom search pane and places the cursor focus in the search field - removing the focus from the editor

This new behaviour is quite undesireable as you will have to use the mouse to get the focus back to the editor in order to edit the line that you were searching for...

Previous to CL-15.0.6 only CTRL-F opened the bottom search pane and placed the cursor focus in the search field - not CTRL-G

Seen with CL-15.0.6 on archlinux

**Comment by eranif** [comment]
I see what you mean (you meant: `F3`, which is the default keyboard assignment)
The idea of opening the search bar is for the user to be able to define the search (e.g. whole word, etc)
However, for me, once I find what I am looking for, I am hitting `ESC` which dismisses the search bar and sets the focus back to the editor

**Comment by uffejakobsen** [comment]
> I see what you mean (you meant: `F3`, which is the default keyboard assignment)

Ah, I forgot that I've redefined it  :-)

> The idea of opening the search bar is for the user to be able to define the search (e.g. whole word, etc)

Well, CTRL-F already takes care of that - if the user wishes to redefinie the search - 

> However, for me, once I find what I am looking for, I am hitting `ESC` which dismisses the search bar and sets the focus back to the editor

For advanced search/replace operations that cannot be automated with the regular search and replace - the new behaviour is just plain annoying.

User will have to press F3 followed by ESC for every little code change - where previously F3 would do the job nicely while keeping the focus in the editor.
And if the user wanted to redefine/change the search he/she simple pressed CTRL-F. 

I believe that F3 (CTRL-G) should just continue searching without changing focus - as it now- while increasing the number of keypresses - is reducing productivity - and it would be even better if F3 (CTRL-G) did not open the bottom search pane - CTRL-F is fine for that purpose :-)

**Comment by uffejakobsen** [comment]
I'm closing this issue - thanks for the merge :+1:   :-)
