### ISSUE TITLE
Replace All (cmd+h) broken in 15.0.6

### ISSUE THREAD

**Issue by Kanimies** [eranif/codelite#2815]
When doing replace in editor using the CMD+H dialog and entering text to replace + replacement the Replace button works as before, but Replace All messes things up as demonstrated in the screenshots.
Single "function S" replaced properly
<img width="1146" alt="replace single" src="https://user-images.githubusercontent.com/7421922/131006685-f46be947-f629-448d-bad9-b6a0b9236685.png">

Next replace all "function S" with "function s" and things go wicked.
<img width="1135" alt="replace all" src="https://user-images.githubusercontent.com/7421922/131006677-4207cec6-17bc-4ae9-be77-2503ad3506f3.png">

**Comment by Kanimies** [comment]
Seems to have something to do with having non-us ascii characters present in the file edited.

[sample.txt](https://github.com/eranif/codelite/files/7070272/sample.txt)

<img width="1142" alt="before" src="https://user-images.githubusercontent.com/7421922/131209026-9ddb04f7-2340-4011-b5b4-4f966bf0eebd.png">

<img width="1144" alt="after" src="https://user-images.githubusercontent.com/7421922/131209022-3c5d976d-20bc-4b33-bb04-6153daba8ae4.png">

**Comment by eranif** [comment]
this might explains it, thanks - will check it using the sample.txt file you provided
