### ISSUE TITLE
Enabling the Highlight current number disables the edit margin.

### ISSUE THREAD

**Issue by jasonlogbi** [eranif/codelite#2819]
Enabling the Highlight current number option disables the edit margin that indicates the changes you made in the editor. I hope this is a bug and not a feature.

**Comment by eranif** [comment]
I am afraid you can't have them both.
In order to implement this, the margins are overlapping which causes drawing artifacts to remain
Its a limitation of the editor component

**Comment by Eric-01** [comment]
If this is a limitation of a third-party editor component (wxWidgets?) that you don't think you would like to work around it / submit a PR upstream, maybe you should add a warning in CodeLite that enabling this feature will disable the edit margin.

**Comment by Eric-01** [comment]
If this is a limitation of a third-party editor component (wxWidgets?) that you don't think you would like to work around it or submit a PR upstream, maybe you should add a warning in CodeLite that enabling this feature will disable the edit margin.

**Comment by Eric-01** [comment]
If this is a limitation of a third-party editor component (wxWidgets?) that you don't think you would like to work around it or submit a PR upstream, maybe you should add a warning in CodeLite that enabling this feature will disable the edit margin?
