### ISSUE TITLE
Feature request: select active project

### ISSUE THREAD

**Issue by alex-rass-88** [eranif/codelite#2824]
Would be great if user can be select active project by hotkeys. Maybe from goto anything menu.

**Comment by alex-rass-88** [comment]
Select active project works only if already have selected project. If no project selected dialogue for selecting not show.
For fix i comment line 6073 in frame.cpp (CHECK_COND_RET(!cur_active_project.IsEmpty());)

**Comment by eranif** [comment]
thanks, I removed this check. In normal "workspace" setup, this value should not be empty. Considering your use case - I removed it

**Comment by alex-rass-88** [comment]
Thanks
