### ISSUE TITLE
Feature Request - Embed compilers like codeblocks do

### ISSUE THREAD

**Issue by Felipefpl** [eranif/codelite#2838]
Codeblocks has a nice feature that gives us a compiler to start with, something that codelite should have.

Edit - for some reason the program seems like that came out of windows 98 instead of using the theme of windows 7.

**Comment by Eric-01** [comment]
I don't like this idea at all.

CodeLite used to offer an opportunity to download for you a Mingw-w64-based GCC compiler, but it is no longer the case now. While I agree that the builds provided by https://sourceforge.net/projects/mingw-w64/ are not the best ones, as they are always behind, there is a project https://winlibs.com/ that I discovered some time ago, which is very actively maintained and could be offered by CodeLite instead.

**Comment by eranif** [comment]
tbh, CodeLite is developed on Windows using compiler that comes with MSYS2. Bundling it is not something I would like to do. It is the best (IMO) MinGW offer on Windows. We have a clear documentation on how to install and configure CodeLite to use it:

https://docs.codelite.org/build/mingw_builds/#prepare-a-working-environment

**Comment by Eric-01** [comment]
I don't like this idea at all as well.

CodeLite used to offer an opportunity to download for you a Mingw-w64-based GCC compiler, but it is no longer the case now. While I agree that the builds provided by https://sourceforge.net/projects/mingw-w64/ are not the best ones, as they are always behind, there is a project https://winlibs.com/ I discovered some time ago, which is very actively maintained and could be used by CodeLite instead.

**Comment by Felipefpl** [comment]
eranif - thank you for both links.

Eric-01 - i see, it's a pity since an embedded compiler would save time for everyone but winlibs seems nice too, thanks for the reply.
