### ISSUE TITLE
Feature request: Workspace: Locally remember the active project

### ISSUE THREAD

**Issue by alex-rass-88** [eranif/codelite#2840]
If use CMake as build system, after cmake rebuild cache codelite forgot active project. Would be great if it saves locally and apply after reload workspace.

**Comment by alex-rass-88** [comment]
Generate codelite project by cmake generator (-G Codelite - Ninja), open project in codelite. Edit some cmake file (just add emty line), build project. Codelite say what project or workspace changet and ask for reload. After reloading no active project

**Comment by alex-rass-88** [comment]
Also, when using premake, the active project is also forgotten during regeneration.

**Comment by eranif** [comment]
This means there is a bug with these generators, we can't really fix them

**Comment by alex-rass-88** [comment]
Ok. #2824 may helps. Switch active project by keyboard.
