### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [eranif/codelite#2844]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [App::OnExit](https://github.com/eranif/codelite/blob/b3b359fd7168e7ce593674466a8732894c701bc6/sdk/wxflatnotebook/samples/wxFlatNotebook/App.cpp#L51 "App::OnExit function")
- [FirebirdParameterCollection::SetParam](https://github.com/eranif/codelite/blob/b3b359fd7168e7ce593674466a8732894c701bc6/sdk/databaselayer/src/dblayer/FirebirdParameterCollection.cpp#L80 "FirebirdParameterCollection::SetParam function")
- [MODEL_NAME_Item](https://github.com/eranif/codelite/blob/b3b359fd7168e7ce593674466a8732894c701bc6/wxcrafter/resources/my_tree_list_model.h#L42 "Destructor for MODEL_NAME_Item")

**Comment by eranif** [comment]
I know that its not needed, but on the other hand, it's also harmless

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?
