### ISSUE TITLE
[New request] [Key shortcuts] Please consider implementing modes (explanation in text)

### ISSUE THREAD

**Issue by gadefox** [eranif/codelite#2849]
**Simple use scenario**: Let's say I define the key shortcut for launching the debugger e.g `Ctrl`+`D`. I can't define the same shortcut key for ending the debugger. I think this key should be free in debugging `mode` (the debugger is already launched, so I can't launch the debugger). The same logic applies for `building`, generally speaking every **Start/Stop** process. All `debugger` shortcut keys should be "free" until I'm in `debugging mode` e.g. I could use `step in` or `step out` shortcut keys for launching the `debugger` and then(!) when I'm in debugging mode, these shortcuts are relevant..

**Comment by gadefox** [comment]
Also any idea why I'm getting the following message? I probably need to configure the `gdb` with `codelite`
`"warning: GDB: Failed to set controlling terminal: Operation not permitted"`

**Comment by eranif** [comment]
using the existing mechanism, this change requires a massive code change
Not going to imlement

**Comment by eranif** [comment]
are you mixing libraries here? i.e. do you try to launch codelite 14 with different wx version?

**Comment by eranif** [comment]
have you considered building CodeLite from sources? its a simple process on Linux

**Comment by gadefox** [comment]
Yep, I'm building ver 15 from the source.. Ver 14 is prebuilt package (Debian)..
