### ISSUE TITLE
Option "Trim only modified lines" seems not to work

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2861]
Option "Trim only modified lines" seems not to work anymore

Seen on CL-15.0.7

**Comment by uffejakobsen** [comment]
No, it did not work in 15.0.6 either - I just forgot to report it - sorry :-S

**Comment by eranif** [comment]
Good (kinda) - so its not a regression :)

**Comment by uffejakobsen** [comment]
Closing this issue (was related to #2888)
