### ISSUE TITLE
[BUG] Toolbar missed in Build panel and vscroll out of limits.

### ISSUE THREAD

**Issue by iHardRock** [eranif/codelite#2862]
CodeLite v15.0.8 latest build from master.

There is no toolbar in Build panel. Also vertical scroll runs out the limits.

![bld](https://user-images.githubusercontent.com/8301265/140117410-4ac54ae4-8025-48e3-bceb-09a7835edb8f.png)

Other panels are OK.
![other](https://user-images.githubusercontent.com/8301265/140117657-72e259f9-2c23-4723-9299-7e6cd2b17e0f.png)

**Comment by eranif** [comment]
The build panel was replaced to use a new control that supports terminal colouring and other features. 
Most of the toolbar functionalities are still there using the context menu
