### ISSUE TITLE
How to reopen the menu bar? The shortcut key conflict!

### ISSUE THREAD

**Issue by LuossD** [eranif/codelite#2868]
This shortcut Alt+` clashes with the system shortcut of Ubuntu18.And this shortcut is not in my keyboard options in system settings..How do I reopen the menu bar?

**Comment by eranif** [comment]
`Ctrl-F11` will force it to reappear along with other UI elements, hitting `Ctrl-F11` again, will hide all these extra UI elements.

**Comment by LuossD** [comment]
> `Ctrl-F11` will force it to reappear along with other UI elements, hitting `Ctrl-F11` again, will hide all these extra UI elements. Another option:
> 
> `Ctrl-Shift-P` and type `Menu bar`
> 
> You can change all the keyboard shortcuts from: `settings -> keyboard shortcuts`, again, type `menu bar` in the filter field
Great!Thanks a lot~~
