### ISSUE TITLE
[BUG] LSP is not slow, and autocomplete stops after few minutes 

### ISSUE THREAD

**Issue by CypherpunkSamurai** [eranif/codelite#2878]
# [BUG]
## Description
Hi, I noticed that codelite LSP is automatically closing after few minutes on simple hello world programs. I'm using MSYS2 clang distribution and clangd. The LSP is very slow and often i have to wait for few seconds before autocomplete propmt appears. Please Fix.

## System
Windows 8.1 Pro x64.
Codelite v15.0.6
LSP: clangd (MSYS2 mingw clang-tools)

**Comment by eranif** [comment]
On Windows, CodeLite comes with its own `clangd` - so you don't need to install `clang-tools` from MSYS
Since its pretty fast on huge projects (tens of thousands of source files), I will need a reproduction for this.

Also, if it fails - please provide the LSP output.

1. `Settings -> preferences -> Misc -> Log ` and set the log to `Debug`
2. Try your sample again

Upload / paste here the content of `%appdata%\CodeLite\codelite.log` and ``%appdata%\CodeLite\codelite-lsp.log`

**Comment by CypherpunkSamurai** [comment]
Ah I get it now. I had removed the CodeLite stock LSP and was using the clangd from MSYS2. I guess MSYS2 clangd was incompatible. I changed it back to codelite stock LSP and it works better. Thanks for the tip 😄 

One problem still remains, the LSP is slow. What I mean is, by the time i've completed ```std::cou``` it still wont show suggestions (```std::cout```). Sometimes it completely ignores what i'm typing and i have to either manually type it, or delete the line and start again.

**Comment by CypherpunkSamurai** [comment]
Ok. I understand it now.

So here's the problem, I'm trying to use a library. But the stock codelite clangd is not showing half the stuff in the library. Again when i use llvm ofiicial clangd its showing the library classes and objects perfectly, but the imports are relative paths.

Also secondly, codelite autocompletion does'nt work if i write something, press `Esc` to cancel the autocomplete, and then type again. VScode, Sublime Text and vim lsp trigger lsp autocomplete in these situations too, thats why it feels off.

**Comment by eranif** [comment]
1. I am not familiar with the layout of your workspace or which build type you are using. Assuming you are using `CMake` - then make sure you have `compile_commands.json` on the root folder of your workspace

2. CodeLite uses default of 3 consecutive characters in order to trigger code completion
You can reduce it 1 to trigger it faster

`settings -> preferences -> code completion -> triggering`

You can switch to the `clangd` that comes with `MSYS2` by changing the path in the `Plugins -> Language Server -> Settings -> clangd -> Command`

**Comment by eranif** [comment]
also, adding the log as I asked earlier will help me understand your issue

**Comment by CypherpunkSamurai** [comment]
> 2. CodeLite uses default of 3 consecutive characters in order to trigger code completion
>    You can reduce it 1 to trigger it faster

I already have it set to 1. But when im typing something, then backspace over, then type again the autocomplete isn't triggered automatically. I have to remove the whole word and start again.


> `settings -> preferences -> code completion -> triggering`
> 
> You can switch to the `clangd` that comes with `MSYS2` by changing the path in the `Plugins -> Language Server -> Settings -> clangd -> Command`

I noticed MSYS2 clangd is closing automatically, switching to llvm clangd and codelite stock clang helps.

**Comment by CypherpunkSamurai** [comment]
the problem with clangd im having is that some objects dont appear on autocomplete, no matter how many times i restart the lsp or switch clangd binary.

Suppose autocomplete worked for ```std::cout```, now sometimes it wont just find ```cout``` in the list, no matter how many times i try. But the program compiles and runs perfectly, and all standard headers work.

Same LSP in sublime text however can find the ```cout``` object just on typing `co`.

**Comment by eranif** [comment]
Can you add the logs I asked for?

**Comment by CypherpunkSamurai** [comment]
Sure :) Here's the logs,
First I used the clangd LSP from LLVM github releases. Then used the stock clangd.

Both of them don't show prompt again when I do a backspace and try correcting something. Also, both sometimes fail to detect objects in header files. like `SDL_Window` was detected correctly by only stock LSP, and `SDL_Surface` was just ignored by both the LSP.

**CodeLite Log:** [codelite.log](https://github.com/eranif/codelite/files/7611498/codelite.log)
**CodeLite LSP Log:** [codelite-lsp.log](https://github.com/eranif/codelite/files/7611499/codelite-lsp.log)

**Comment by eranif** [comment]
They are the same .. both the stock is taken from the github release page :)
If the completion does not show again, hit `Ctrl-SPACE` it will re-trigger it

**Comment by CypherpunkSamurai** [comment]
> They are the same .. the "stock" is packaged from the LLVM github release page :) If the completion does not show again, hit `Ctrl-SPACE` it will re-trigger it

oh. but is there any way to trigger it on backspace? I would like to have code completion like other text editors that use LSP.

**Comment by eranif** [comment]
You mean: you want it to be triggered automatically? (`Ctrl-Space` will do this for you)

**Comment by CypherpunkSamurai** [comment]
Yeah, but `Ctrl + Space` is not really what I was looking for :P

![sublimetex-smooth-cpp-hello2](https://user-images.githubusercontent.com/66906402/143776325-5170ded6-f29e-4029-a39d-5f39e227de71.gif)

Is it possible if we can have this for codelite? I mean the smooth autocompletion (and possibly the cool snippets) :)

**Comment by jasonlogbi** [comment]
I did open a ticket about this issue a few months ago. ticket #2821

**Comment by jasonlogbi** [comment]
IMHO. It kinda defeats the purpose of auto code completion/suggestion if you have to press `ctrl + space` every time you want it to appear. I hope it gets fixed.

**Comment by CypherpunkSamurai** [comment]
You're somewhat right. Although this is a foss project, and I really respect the Dev's hard work. I hope he adds it sooner :)

**Comment by CypherpunkSamurai** [comment]
Thank you @eranif 😄
