### ISSUE TITLE
lost projects

### ISSUE THREAD

**Issue by Ahmedmoustafa4444** [eranif/codelite#2880]
hallo, 
since more than 3 months i did not use codelite, today when I opened it to use it again, asked me to update to the last version, and that is what already I made, after finishing the updates, I lost all my old projects which were saved on codelite. my question is: do you know a way to recover these lost projects?

**Comment by eranif** [comment]
CodeLite does not "save" projects on itself. The projects are on the file system.
Go to `File -> Open workspace` and search for the `.workspace` files

Usually, they are under `%USERPROFILE%\Documents`
