### ISSUE TITLE
GNU GDB tooltip

### ISSUE THREAD

**Issue by shadoww1028** [eranif/codelite#2882]
The tool tip that displays the variable contents when the mouse cursor hovers over it, is not appearing under the mouse.  It appears to be using the break point position to display the tooltip instead of the mouse position.

Linux, CodeLite 15.0.8

**Comment by eranif** [comment]
This sounds like a dual monitor bug to me - is this the case?

**Comment by shadoww1028** [comment]
Yes a dual monitor both 2k displays. One is a 144hz and the other 60hz refresh.

**Comment by eranif** [comment]
usually this happens when the displays are not of the same *size*
can you provide a screenshot?

**Comment by shadoww1028** [comment]
https://user-images.githubusercontent.com/38931193/153983473-95d7e7f1-c4f3-4c99-91cb-e9f7483a07c1.mp4
