### ISSUE TITLE
UseDifferentPCHFlags  in old projects not being converted correctly

### ISSUE THREAD

**Issue by shadoww1028** [eranif/codelite#2884]
When the UseDifferentPCHFlags was set in old projects the new value PCHFlagsPolicy is being set to 0 when the UseDifferentPCHFlags was set to "no".  It looks like the PCHFlagsPolicy should be set to 1 instead for "Append" instead of 0 "Replace"

Code lite 15.0.8 (arch linux)

Found this bug while using premake

**Comment by Jarod42** [comment]
Note: Codelite changed that flag in 2014 by fixing #502
Fixing Premake might be sufficient IMO.
