### ISSUE TITLE
CMAKE: use builtin module for SQLite3

### ISSUE THREAD

**Issue by carlo-bramini** [eranif/codelite#2893]
Since version 3.14, CMake provides a module for detecting SQLite3.

https://github.com/Kitware/CMake/blob/master/Modules/FindSQLite3.cmake

Since `cmake_minimum_required()` into the current CMakeLists.txt is set to 3.16, it should not cause restrictions.
By using this module, I'm able to find this library also with CYGWIN, while I cannot with current code.
If I'm not mistaken, your script expects to find a ".so" file, while the shared libraries are ".DLL" on Windows.
That's why it does not work here to me.
Perhaps, you could evaluate the chance to use this feature, because it will allow you to delete existing `codelite/cmake/Modules/FindSqlite3.cmake` and it will simplify a bit your CMakeLists.txt by deleting some checks on the platform, now useless.
Later, after other tests, CMake will stop again on CYGWIN because ".so" library files are searched again, but at least the detection of SQLite3 is fixed.
What do you think?

**Comment by eranif** [comment]
Can you provide a PR so I can review it?

**Comment by carlo-bramini** [comment]
Hello,
> Can you provide a PR so I can review it?

As you requested, I made PR with my fixes.
I hope that you will find this useful.

**Comment by carlo-bramini** [comment]
After the commit of PR #2919, this issue could be safely closed.
Thank you very much!
