### ISSUE TITLE
Unable to build codelite on Haiku...please help.

### ISSUE THREAD

**Issue by khallebal** [eranif/codelite#2894]
The configure phase fails with the below error, i have to mention that i am using wxQt maybe that's why?, so how can i fix the line 280 in CMakeLists.txt ?

```bash
 CMake Error at /boot/system/data/cmake/Modules/FindPackageHandleStandardArgs.cmake:230
 (message):
   Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES)
 Call Stack (most recent call first):
   /boot/system/data/cmake/Modules/FindPackageHandleStandardArgs.cmake:594
 (_FPHSA_FAILURE_MESSAGE)
   /boot/system/data/cmake/Modules/FindwxWidgets.cmake:1025 (find_package_handle_standard_args)
   CMakeLists.txt:280 (find_package)

 Configuring incomplete, errors occurred!
 See also "/boot/home/Desktop/codelite/build/CMakeFiles/CMakeOutput.log".

```
Thanks.

**Comment by eranif** [comment]
CodeLite does not use `wxQt` (a port of wxWidgets), we use GTK3. You should have it installed or build it with sources.
Follow the instructions here: https://docs.codelite.org/build/build_wx_widgets/#linux
there were written for Ubuntu / Debian, but I am sure you will be able to translate them into Haiku

**Comment by khallebal** [comment]
Thanks for your reply, the thing is haiku is not a Linux distro it has it's own kernel and toolkit, so for now we don't have GTK  nor Xserver but only a Qt port, that's why i asked how i could patch the CMakeLists.txt as to at least get the build going. thanks.
