### ISSUE TITLE
CMAKE: 'wxCrafter' does not use WITH_WX_CONFIG option.

### ISSUE THREAD

**Issue by carlo-bramini** [eranif/codelite#2896]
I tried to build Codelite by using a newer build of wxWidgets, compiled by me.
So, I configured with -DWITH_WX_CONFIG option and the libraries have been found successfully.
But later, the configuration process prints this message on the console:

```
-- Generating makefile for wxCrafter
sh: wx-config: No such file or directory
```
Although the configuration seems to complete successfully, this message seems to highlight a problem.
I have not checked all sources and scripts of Codelite, but it seems to me that there are some scripts for CMake that overwrite the content of `${CL_WX_CONFIG}`, like:
* codelite-cli/CMakeLists.txt
* ctagsd/CMakeLists.txt

Then, there are other files that seem to be not using `${CL_WX_CONFIG}` at all but they try to call `wx-config` directly.

**Comment by eranif** [comment]
You should use this option instead:

```
-DWITH_WXPATH...
```

For example, when I build CodeLite with older wxVersion (e.g. wx3.0.5), I am using this command line:

```bash
cmake -DCMAKE_BUILD_TYPE=Debug .. -DCOPY_WX_LIBS=1 -DMAKE_DEB=1 -DCL_PREFIX=$HOME/root_wx30 -Wno-dev -DWITH_WXPATH=/home/eran/root_wx30/bin
```

Where `/home/eran/root_wx30` is where I installed `wx3.0.5` and `/home/eran/root_wx30/bin` is where my `wx-config` located

**Comment by eranif** [comment]
I removed this option from the `CMakeLists.txt` to avoid future confusion
