### ISSUE TITLE
CL plugins "LSP" and "Webtools" is missing from Manage Plugins window

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2904]
CL (debug-build) on latest master seems to miss the following plugins "LSP" and "Webtools"

See screenshots from "Manage Plugins" window:
![clplug01](https://user-images.githubusercontent.com/3018239/147675725-c1ad3605-f8af-4281-85ed-9769a3ff7168.png)
![clplug02](https://user-images.githubusercontent.com/3018239/147675736-ac6ec9fa-59f2-4886-ad57-fbe5122963da.png)

**Comment by eranif** [comment]
1. Try deleting the folder `~/.codelite-dbg`
2. Make sure that the plugins are installed under your installation folder
3. Do you get anything in `codelite.log`?

**Comment by uffejakobsen** [comment]
Hi, sorry but I'm quite busy at $work right now - I'll have to get back to you later - sometimes next week.

**Comment by eranif** [comment]
np!

**Comment by uffejakobsen** [comment]
I'm closing this issue (same explanation as stated in issue #2897)
