### ISSUE TITLE
After settuping and starting Codelite, standard colour themes don`t work. 

### ISSUE THREAD

**Issue by YaroslavHorlach** [eranif/codelite#2907]
Windows 10
Codelite version 15.0.0 and 15.0.8
![image](https://user-images.githubusercontent.com/92679437/147784814-8893ec7b-6159-412c-8c01-2ada24eb2cac.png)
![image](https://user-images.githubusercontent.com/92679437/147784845-32bd6c0e-b60c-4a1c-b55d-039ad6968b8f.png)

**Comment by eranif** [comment]
do you get any errors in `%appdata%\codelite\codelite.log` ?
it should indicate which themes were loaded, if you dont get anything in the log, 
change the log verbosity from: settings -> preferences -> misc -> log -> verbosity -> Debug

start CodeLite, close it and paste here the content of the `codelite.log` thanks!

**Comment by YaroslavHorlach** [comment]
I added valid lexer.json but programm don`t see new colour themes and also it doesn`t save applied settings
![image](https://user-images.githubusercontent.com/92679437/147785198-42f57ed8-1ec6-43a8-b5bf-744b59198a63.png)

**Comment by eranif** [comment]
@YaroslavHorlach it should be `lexers.json` anyways, can you upload the log file? thanks!

**Comment by YaroslavHorlach** [comment]
> do you get any errors in `%appdata%\codelite\codelite.log` ? it should indicate which themes were loaded, if you dont get anything in the log, change the log verbosity from: settings -> preferences -> misc -> log -> verbosity -> Debug
> 
> start CodeLite, close it and paste here the content of the `codelite.log` thanks!

I installed Codelite on disk C, but if I run programm with administration permission, I also have this problem. 
Every time I start programm, setup wizard opens.
![image](https://user-images.githubusercontent.com/92679437/147785706-ca22d3f3-4af7-4bdd-b17d-735023907413.png)

**Comment by eranif** [comment]
I am guessing you have a user name with some Cyrillic characters?

**Comment by YaroslavHorlach** [comment]
> 

Yes

**Comment by eranif** [comment]
Strange though, we have many people with non ASCII names working with CodeLite with no issues (it is fully UNICODE supported)
We could create an override for this:

By default CodeLite installer creates a link to desktop shortcut that simply executes CodeLite.
You can:
- Right click the shortcut
- Select properties
- In the `Target` field, set the command from `"C:\Program Files\CodeLite\codelite.exe"` -> `"C:\Program Files\CodeLite\codelite.exe" --datadir C:\codelite-config`
- Start CodeLite

This way CodeLite will avoid the `%appdata%\codelite` folder and will use the path provided by the `--datadir` switch

**Comment by YaroslavHorlach** [comment]
Thank you very much for help. It worked!

**Comment by eranif** [comment]
Great. 

**Important**

Don't forget to set the logging level back to `ERROR`. The file will get bigger in size in no time
`settings -> preferences -> misc -> log -> verbosity -> Error`
