### ISSUE TITLE
CodeLite randomly crashes when typing and moving cursor

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#2920]
I am using CodeLite built from GitHub, revision ca3ef9ae4a841bdc7e3575d43d47db17c7d0df58. Running on Linux Arch with latest updates up until now and kernel 5.15.13-arch1-1. However, since about 12th of December of 2021, CodeLite crashes few minutes after starting to work with it. The crash usually happens when I am typing something but also happened when I was just moving cursor with mouse keys. 

There was one occasion when I restarted CodeLite multiple times after crashes and then, when it crashed again, it took the whole Wayland session with it.

I have compiled CodeLite for debug and ran it within GDB, but didn't get anything meaningful, only this:
`[Inferior 1 (process 18094) exited with code 01]`

While running CodeLite, I did get something interesting in the journal though:
```
Jan 10 12:29:32 hostname gnome-shell[1828]: WL: file descriptor expected, object (5), message create_pool(nhi)
Jan 10 12:29:32 hostname gnome-shell[1828]: WL: error in client communication (pid 18094)
Jan 10 12:29:33 hostname systemd-coredump[19372]: [🡕] Process 19231 (clangd.main) of user 1000 dumped core.
                                                   
                                                   Module linux-vdso.so.1 with build-id 035c7da8b451e8d19aed30c8ca397>
                                                   Module libicudata.so.70 with build-id e1dcc2a88cfaafed882d09c90c66>
                                                   Module liblzma.so.5 with build-id 8b615460aa230708c5183f16bede67aa>
                                                   Module libicuuc.so.70 with build-id 2e245c2bf12f95fd8ab79b3a4be995>
                                                   Module libxml2.so.2 with build-id b710b880b0d4e9c93554fa632129db44>
                                                   Module libncursesw.so.6 with build-id 859adb8b03a5655151b4da104bc4>
                                                   Module libz.so.1 with build-id 0c1459c56513efd5d53eb3868290e9afee6>
                                                   Module libdl.so.2 with build-id 5abc547e7b0949f89f3c0e21ab0c8331a7>
                                                   Module libedit.so.0 with build-id 4b0babfcad161c2ad0af6e59e2493258>
                                                   Module libffi.so.8 with build-id f90d8b734f6de9b25faedb8cbfab7054d>
                                                   Module libgcc_s.so.1 with build-id 7f8508bb914546ada778809b64b99d2>
                                                   Module ld-linux-x86-64.so.2 with build-id 040cc3dd10461562f177df39>
                                                   Module libc.so.6 with build-id 4b406737057708c0e4c642345a703c47a61>
                                                   Module libm.so.6 with build-id 2b8fd1f869ecab4e0b55e92f2f151897f68>
                                                   Module libstdc++.so.6 with build-id 9b5eeeb149bf3c4efe787fb398b44f>
                                                   Module libpthread.so.0 with build-id 07c8f95b4f3251d08550217ad8a1f>
                                                   Module libLLVM-13.so with build-id 82982c299d46219d0eab8ee9cb8bb73>
                                                   Module libclang-cpp.so.13 with build-id d858da8d8142f46014e024977a>
                                                   Module clangd with build-id a75be25f49b4ef5749516667cf6a8545a76452>
                                                   Stack trace of thread 19231:
                                                   #0  0x00007fffed738d22 raise (libc.so.6 + 0x3cd22)
                                                   #1  0x00007fffed72290e abort (libc.so.6 + 0x2690e)
                                                   #2  0x00007fffee6ff0d4 _ZN4llvm18report_fatal_errorERKNS_5TwineEb >
                                                   #3  0x00007fffee6ff22e _ZN4llvm18report_fatal_errorERKNSt7__cxx111>
                                                   #4  0x00007fffee7b5f81 _ZN4llvm14raw_fd_ostreamD2Ev (libLLVM-13.so>
                                                   #5  0x00007fffed73b4a7 __run_exit_handlers (libc.so.6 + 0x3f4a7)
                                                   #6  0x00007fffed73b64e exit (libc.so.6 + 0x3f64e)
                                                   #7  0x00007fffed723b2c __libc_start_main (libc.so.6 + 0x27b2c)
                                                   #8  0x0000555555649c6e n/a (clangd + 0xf5c6e)
                                                   
                                                   Stack trace of thread 19370:
                                                   #0  0x00007fffed7c2a95 clock_nanosleep@@GLIBC_2.17 (libc.so.6 + 0x>
                                                   #1  0x00007fffed7c7c77 __nanosleep (libc.so.6 + 0xcbc77)
                                                   #2  0x0000555555a78c9f n/a (clangd + 0x524c9f)
                                                   #3  0x00007fffedadf3c4 execute_native_thread_routine (libstdc++.so>
                                                   #4  0x00007fffedc2b259 start_thread (libpthread.so.0 + 0x9259)
                                                   #5  0x00007fffed7fa5e3 __clone (libc.so.6 + 0xfe5e3)
                                                   ELF object binary architecture: AMD x86-64
```
That core dump for clangd.main occurred multiple times - the above is the last one before CodeLite crashed. I've checked CodeLite options but can't find any obvious option where to turn off Clang, I remember in some older versions it was possible to enable/disable it. Is there a way to disable Clang within CodeLite so I can try to see if it still crashes that way?

I am not sure if it could be related, but I similarly see problems with syntax highlight coloring - after opening the project, source code variables are properly colored but after clicking "Ctrl + S" to save file, they lose all coloring and if I use "Parse Workspace - Incremental" they get back some coloring, but somewhat different than the one at startup. I am wondering if this also has to do with the problems related to clangd that lead to crashing.

**Comment by eranif** [comment]
this looks like as if `clangd` (process name `clangd.main`) crashed and for some reason it took CodeLite with it :(
the quickest fix: disable `clangd`:

plugins -> language server -> settings

find the `clangd` entry and disable it

FYI: you won't get anything in CodeLite code, `clangd` as an external process (different executable) maintained by another (LLVM team). 

The colouring is provided by the Language Servers (`clangd` is one of them)
so if it crashed -> CodeLite will not be able to provide the extra colours (e.g. different colour for class, enum, function)

You can activate another C++ language server (ctagsd)
its less accurate than `clangd` but it does the job


Some information:
- Which clangd version are you using?
- What OS

**Comment by yunkot** [comment]
Thanks for a quick reply.

clangd version is 13.0.0, platform x86_64-pc-linux-gnu
OS is Arch Linux

I have disabled clangd and at least no more sudden changes in coloring now. I'm trying to use CodeLite and will report if get any crashes.

**Comment by yunkot** [comment]
Unfortunately, it seems that the crashing persists and it is not related to clangd. I have disabled clangd as I've described above, restarted CodeLite (using debug build) and tried doing normal work (navigate through some C++ source code, edit few lines, etc.). It crashed after 2 minutes, this time when I was scrolling the source code with mouse wheel. No messages in console output, the process simply exited.

In journalctl, I only see this (CodeLite's process id was 6572):
```
Jan 10 14:21:12 hostname gnome-shell[1821]: WL: file descriptor expected, object (5), message create_pool(nhi)
Jan 10 14:21:12 hostname gnome-shell[1821]: WL: error in client communication (pid 6572)
```
I do have a feeling that this is really not CodeLite related - if I revert my Arch packages to a day before December 12th 2021 (it doesn't matter if I recompile CodeLite or not), the problem is gone. But unfortunately, there are many packages that were changed between December 12-13 (these include clang, python, kernel and many other things), and CodeLite seems to be the only application to be affected on my system, at least as far as I can tell, so I wouldn't know where to report this until I figure out what causes these crashes.

**Comment by eranif** [comment]
do you have a backtrace?
"just scrolling" suggests that either GTK3 or wxWidgets issue (I don't think its related to CodeLite core code)

Do you get any warning in `~/.codelite/codelite-stdout-err.log` file?

**Comment by eranif** [comment]
e.g. can you run CodeLite under `gdb`? 

```
gdb /path/to/codelite
..
..
(gdb) continue
```

and when it crashes:

```
(gdb)thread apply all bt
```

**Comment by eranif** [comment]
One last note: 
the error is probably Waylad related: `WL: file descriptor expected` -> `WL` -> Wayland
Can you try with different desktop environment?

**Comment by yunkot** [comment]
In "codelite-stdout-err.log", I was getting this:
```
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

(codelite:6215): Gtk-CRITICAL **: 14:11:56.055: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(codelite:6215): Gtk-CRITICAL **: 14:11:57.025: gtk_widget_set_size_request: assertion 'height >= -1' failed

(codelite:6215): Gtk-CRITICAL **: 14:11:58.593: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook

(codelite:6572): Gtk-CRITICAL **: 14:16:00.947: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
# Option “-e” is deprecated and might be removed in a later version of gnome-terminal.
# Use “-- ” to terminate the options and put the command line to execute after it.

(codelite:6572): Gtk-WARNING **: 14:16:24.657: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node trough, owner GtkProgressBar)

(codelite:6572): Gtk-CRITICAL **: 14:21:12.879: gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed

(codelite:6572): Gtk-CRITICAL **: 14:21:12.923: gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed
Gdk-Message: 14:21:12.936: Error 22 (Invalid argument) dispatching to Wayland display.
```
(I've removed duplicate assertions from above log as many of them repeated many times)

I'm trying now with gdb as you suggested and on x11...

**Comment by yunkot** [comment]
> e.g. can you run CodeLite under `gdb`?
> 
> ```
> gdb /path/to/codelite
> ..
> ..
> (gdb) continue
> ```
> 
> and when it crashes:
> 
> ```
> (gdb)thread apply all bt
> ```
Executing "continue" command shows:
`The program is not being run.`
Therefore, I have to execute "run" command instead.
After CodeLite crashed, the message is:
`[Inferior 1 (process 28196) exited with code 01]`
The command "thread apply all bt" doesn't show anything after that.

Indeed, the crash only occurs while running on Wayland, it doesn't occur under x11. I have attached full log from ~/.codelite-dbg/codelite-stdout-stderr.log: [codelite-stdout-stderr.log](https://github.com/eranif/codelite/files/7872728/codelite-stdout-stderr.log)

P.S. Now I'm using CodeLite revision 0e7e9d1faba817e7ab2b9219838c88677045ef38 and kernel 5.16.0-arch1-1.

**Comment by eranif** [comment]
This issue is out of scope of CodeLite as we don't really handle the connectivity to the underlying X-server but it is being done by wxWidgets - so I am going to close this bug. Can you open this on the wxWidgets page? (https://github.com/wxWidgets/wxWidgets ) thanks!
