### ISSUE TITLE
Link between File tab and Workspace view does not work in CL-15.0.9

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2927]
Link between File tab and Workspace view does not seem work anymore

Tried FSW project with the new release CL-15.0.9

**Comment by uffejakobsen** [comment]
Update is does work with another existing project that I just opened... but the new project that i did for testing the new release does not link... hmm.. digging further...

**Comment by eranif** [comment]
sometimes, when you add new files to the workspace, the tree does not refresh itself (unless you created the file from the tree view). So it can happen that the file does not exist in the view so there is nothing to link to

**Comment by uffejakobsen** [comment]
Well, I found that the problem was that the path down to the FSW project root (not inside the project) contained a symlink... 

If I open the workspace using the real path the workspace-file-tab link works.
If I open the workspace using the symlinked path - the workspace-file-tab link does not works.

The bad thing here is that I use the symlink to shorten a rather deep real path due to project/file hierarchy organisation...

**Comment by eranif** [comment]
The good news:
- not a regression
- can you provide a an example of how to create a such a directory structure?


Thanks

**Comment by uffejakobsen** [comment]
>     * can you provide a an example of how to create a such a directory structure?
 Sure no problem - just follow these steps:

```shell

mkdir -p /tmp/real/path/to/workspace/
ln -s real/path/to/workspace /tmp/symlink-to-workspace

cd /tmp/real/path/to/workspace/
git clone https://github.com/danmar/cppcheck.git cppcheck.git

```
Now create a new FSW project in CL with root in /tmp/real/path/to/workspace/cppcheck.git

Now there is two ways (paths) to open the new FSW project in CL:
- If you open the FSW project file using the full path (/tmp/real/path/to/workspace/cppcheck.git) in the dialog - then link between file tabs and workspace view works
- If you open the FSW project file using the symlink path (/tmp/symlink-to-workspace/cppcheck.git
) - then link between file tabs and workspace view does not work.
