### ISSUE TITLE
Wrong project number arrangement

### ISSUE THREAD

**Issue by 13teju** [eranif/codelite#2933]
![Screenshot (23)](https://user-images.githubusercontent.com/86972434/150332629-13bf723a-edae-45da-a4cc-a1f258f7f5e2.png)
on the left side where projects are it dosent arrange them in proper order.

**Comment by eranif** [comment]
The tree is sorted [lexicographical order](https://en.wikipedia.org/wiki/Lexicographic_order) .
With one exception: we do not distinct between lowercase and uppercase (AKA case-insensitive).
I just tried this on another text editor (Sublime) - same display
