### ISSUE TITLE
codelite crashing 15.0.9

### ISSUE THREAD

**Issue by DrCanna** [eranif/codelite#2945]
codelite 15.0.9 crashing on windows 10 64x when i run it
when im trying to install a lower version of codelite the setting wont save and there is no color option(cant change font no global themes) everything is gray and black
im using mingw64 version 8.1.0

**Comment by eranif** [comment]
usually this happens when your user name (login name) contains non ASCII characters (e.g. cyrillic characters)
Try following this thread: and see if this helps:
https://github.com/eranif/codelite/issues/2907
