### ISSUE TITLE
Flashing background

### ISSUE THREAD

**Issue by shadoww1028** [eranif/codelite#2946]
When scrolling the background will flash on selections and the column with line number and break points also has a flashing background. 

To reproduce:  Double click something to select it and scroll either up or down and all other matching items that are also outlined will have the flashing background.  It appears to flash with a black background.

The other issue is harder to reproduce but sometimes when click on a class name it will flash.

CodeLite 5.0.9 Arch Linux. Duel monitors.

**Comment by shadoww1028** [comment]
I can verify that on my second computer this does not happen with very similar setups.  AMD GPU in my other computer is really the only difference.

**Comment by shadoww1028** [comment]
Reproduced this on Manjaro (second boot drive)  But it didn't update its self correctly.

**Comment by shadoww1028** [comment]
Installed Linux Mint, The flashing was not present.  This is likely a AMD GPU series 6000 issues with Arch Linux with WxWidgets thing.
I can verify that this did not occur in version 15.0.2 on the Arch Linux install With the AMD GPU.

**Comment by shadoww1028** [comment]
I also didn't see this in 15.0.8.

**Comment by eranif** [comment]
if you disable the line margin, does this still happen? 
You can remove it from `settings -> preferences -> Show line numbers margin`

**Comment by shadoww1028** [comment]
Yup that fixed it.

**Comment by eranif** [comment]
ok,  i have a good that i will commit in the coming days that will allow you to keep the line margin while disabling the flicker

**Comment by eranif** [comment]
Fixed in this commit: 
d7c1b41b6e6c775ba2e9b9c2df8d597c52bd5ff6

I added new option to disable the newly added feature `highlight current line number`

**Comment by shadoww1028** [comment]
After installing 15.0.10 I can concur that the flashing stops with the new feature is used.
