### ISSUE TITLE
Mouse over tooltip on functions. 

### ISSUE THREAD

**Issue by shadoww1028** [eranif/codelite#2948]
The mouse over tool tips are looking very good and if they also worked on functions that would be great.  So if you have a Classname.SomeFunction(params)  if the mouse over worked on the SomeFunction listing parameters and return values with comments it would make for fewer lockups. 

CodeLite 5.0.9 Arch Linux. Duel monitors.

**Comment by eranif** [comment]
This is how it looks in the current master:

using `ctagsd` Language Provider (Still WIP):

![tooltip](https://user-images.githubusercontent.com/3677711/152210595-3aef2143-941d-4ff1-aec1-fb089ca03036.png)

using `clangd` Language Provider:
![tooltip-clangd](https://user-images.githubusercontent.com/3677711/152212085-406d1dfb-b4c3-4e63-97b4-36da068686b4.png)
