### ISSUE TITLE
Cland and Code Completion

### ISSUE THREAD

**Issue by shadoww1028** [eranif/codelite#2953]
When creating a UniquePtr with:

std::make_unique<someobj>(
after the "(" is entered the parameter list used to come up but fails to do so now.  

As far as I know it was the clangd engine that was doing this so I tried the priorities of 0, 45, 200 to see if it would start to work again and it didn't.  I found that with calling other functions the parameter list was being covered and hitting the ctrl button would hide it so that one could see the cland completion under it but this doesn't work with the above. 

Arch Linux CodeLite 15.0.9

**Comment by eranif** [comment]
I tried that with both `clangd` and `ctagsd` both showed the parameter list
the priority is not relevant here. you can simply disable the LSP that you are not interested in
![make_unique](https://user-images.githubusercontent.com/3677711/153560802-c616a237-80b9-4887-9108-ebb8ad1f26fb.png)

I am not sure why it does not work for you, maybe a missing header?

**Comment by shadoww1028** [comment]
![Screenshot_2022-02-14_19-27-28](https://user-images.githubusercontent.com/38931193/153982584-1c9c55bb-0afb-4936-8a08-7448f0b6ed7a.png)

https://user-images.githubusercontent.com/38931193/153982652-76010a47-a602-4700-9344-49caf01cb99c.mp4

Default language server configs.

**Comment by shadoww1028** [comment]
I saw that the "compile_flags.txt" files were missing I put them back in and there was no difference.  I'm guessing there were missing because I took them out as I noticed they were no longer doing anything which is good, one less file to keep up to date.

**Comment by shadoww1028** [comment]
I updated to 15.0.10 and I'm still seeing behavior like this But now nothing is coming up at all.
