### ISSUE TITLE
Status of the indexer/parser ctagsd etc

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2955]
Hi,

This is a question about the current status of the indexer/parser ctagsd etc

For the last 2-3-4 unstable CL-15.0.x releases I've had some problems with the indexer/parser.

It seems that it does not work like it used to work...

It does not see all symbols in a project right away - not even if I re-index the project using the Workspace / Parse Workspace menu action

When I open a source file is seems to be indexed - but is that the way it is supposed to be ? 
I guess/hope not - since I would have to open 100's of files in order to achieve the functionality of the old indexer

I wonder if I'm doing anything wrong here ? - because it seems wrong.

Or maybe it is because the new indexing feature is simply not done/ready yet ?

**Comment by eranif** [comment]
which one are you using?
ctagsd indexes the entire workspace once, like the old one.
clangd -> does not. it works per opened file

**Comment by uffejakobsen** [comment]
> which one are you using?

Good question :-D 
From your description is seems that I'm using clangd (I was)

I've not adjusted Language Server priorities and it seems to work better now... 

> note that with the new `ctagds` (unlike the old built in code completion) it will only complete entries that it can **see** (i.e. there is an include to that symbol)

Ok - so that would mean that I cannot use the "Open Resource..." dialog to go to a function  - unless that it is "visible" in the file that is currently focused - or have I mis understood ?

I think that I need to do some more testing with this setup

But thanks for the feedback :-)

**Comment by uffejakobsen** [comment]
> use `ctagsd` to have a better workspace view

Ah now I think that I understand your explanation.
With ctagsd - the include does not have to be in the current file - it does just need to be included somewhere in the source right ?

**Comment by eranif** [comment]
`ctagsd` will parse the entire workspace and store the data in symbols db (it does that on workspace load and it keeps it updated every time you save a file)

so searching for a workspace symbol (`Ctrl-Shift-R`) is simply a database lookup and is fast.

Code completion (trying to code complete inside the code using `->`, `::`, `.` or hitting `Ctrl-Space`) requires that the symbol header is included in source file or in one of its "children". e.g to be able to complete `vector` you need to have `#include <vector>` in the source file, or in one of its "included" headers (or their children)

What was written in `ctagsd` is the context parser. `ctagsd` now "understands" c++14 level of C++ with a much better C++14 template resolving `auto` deduction and other C++ complexities. also, `using namespace` is now excellent (unlike the old built-in code completion). Personally, I switched to `ctagsd` for writing CodeLite (I used to use `clangd`).

In addition, `ctagsd` is being tested extensively with more than 300 checks to ensure that new features will not cause any regressions

**Comment by eranif** [comment]
> I've not adjusted Language Server priorities and it seems to work better now...
I simply disable the one I am not using (it also saves computer resources)

**Comment by uffejakobsen** [comment]
Ok thanks for explaining the different lookups and the way they works :+1: 

One lest question:
Reading the documentation about LSP (https://docs.codelite.org/plugins/lsp/)
Leaves the reader (me at least) with some doubt.
In the example there is mentioned a priority of 74 - is that some magical hardcoded limit or just an example ?

**Comment by eranif** [comment]
looks like a relic from the past, I will fix this part of the docs - thanks

**Comment by uffejakobsen** [comment]
Thanks - I'm closing this issue :-)
