### ISSUE TITLE
Feature request: re-introduce incremental workspace parse

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2959]
Feature request: re-introduce incremental workspace parse

The current option in the menu `Workspace` /  `Parse Workspace` is really good to force a total re-parsing of a workspace.

But it would be nice if the incremental workspace parse option also could be re-introduced.
 
The need for that option comes when remote git updates are pulled (from a terminal/CLI) - generally speaking when files are changed from outside the running CodeLite.
For scenarios like that only re-parsing the updated files based on their timestamp would make sense. Especially when you have a large project and slow hardware.

**Comment by eranif** [comment]
For now, a good workaround is to perform a workspace reload. 
When reloading a workspace, CodeLite generates the file `file_list.txt` with an updated list of files
`ctagsd` will pick it up and will update the database without re-parsing everything

The LSP protocol support this message [DidChangeWorkspaceFolders Notification][1]. A better solution will be to send this message to `ctagsd` after a folder refresh

[1]: https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#workspace_didChangeWorkspaceFolders

**Comment by eranif** [comment]
BTW, the have the exact same effect for parse workspace: `Ctrl-Shift-P` and then type : `Restart Language Server`
when they are restarted, they will reparse (incr)

**Comment by uffejakobsen** [comment]
This is still an issue (anti stale-bot comment) - need to build and check latest master

**Comment by uffejakobsen** [comment]
Closing this issue
