### ISSUE TITLE
GDB not displaying information

### ISSUE THREAD

**Issue by shadoww1028** [eranif/codelite#2960]
GDB sill displays lists and single object just fine but when you try to drill down into the object it has no members anymore to examine data on.  Occurs  on Linux (Arch) using Codelite 15.0.10.

**Comment by shadoww1028** [comment]
LLDB works fine however.  May switch.

**Comment by eranif** [comment]
can you provide an example code that shows the problem?

**Comment by shadoww1028** [comment]
This horrible code really screws it up but it should work

struct Vec3
{
    int x, y, z;
    std::unique_ptr<Vec3> inner;
    Vec3 *ptr;
    
    std::vector<std::unique_ptr<Vec3>> innervec;
 
    // following constructor is no longer needed since C++20
    Vec3(int x = 0, int y = 0, int z = 0) noexcept : x(x), y(y), z(z) { }
 
    friend std::ostream& operator<<(std::ostream& os, const Vec3& v) {
        return os << "{ x=" << v.x << ", y=" << v.y << ", z=" << v.z << " }";
    }
};

int main( int argc, char **argv )
{

   Vec3 a(1, 2, 3);
    
   std::unique_ptr<Vec3> v1 = std::make_unique<Vec3>(1, 2, 3);
   
   std::cout << a.x << a.y;
   std::cout << v1->x << v1->y;
   
   Vec3 *tmp = v1.get();
   std::cout << tmp->x << tmp->y;
   
   v1->inner = std::make_unique<Vec3>(4, 5, 6);
   v1->ptr = v1->inner.get();
   
   v1->inner->inner = std::make_unique<Vec3>(7, 8, 9);
   v1->ptr->ptr = v1->inner->inner.get();
   
   tmp->innervec.push_back(std::make_unique<Vec3>(10, 11, 12));
   tmp->innervec.push_back(std::make_unique<Vec3>(13, 14, 15));
   
    getchar();
}

**Comment by shadoww1028** [comment]
https://user-images.githubusercontent.com/38931193/155847133-b6c09432-6edb-4e95-bc92-98fda144b499.mp4


https://user-images.githubusercontent.com/38931193/155847141-6952e98f-5922-4ab5-bd28-0140030053e7.mp4

Note:  In the GDB one at first I could not get anything to come up.  I do prefer GDB because conditional break points work and watches can have full expressions where in LLDB these do not work currently.

**Comment by shadoww1028** [comment]
GDB version: 11.2
LLDB version: 13.0.1
GCC version: 11.1.0
On latest arch Linux (well as for a few days ago)  CodeLite 15.0.10

**Comment by shadoww1028** [comment]
Actually I'm using Clang to compile everything   Version:  13.0.1
