### ISSUE TITLE
Feature request: add a cancel button in build/debug

### ISSUE THREAD

**Issue by biciolea** [eranif/codelite#2965]
Now after pressing Ctlr+F5 (run) or F5 (start debug) there is no way not to run the active project

**Comment by eranif** [comment]
`Shift-F5` to stop the debugger. or from the `Build` menu

**Comment by biciolea** [comment]
This is what I meant

![image](https://user-images.githubusercontent.com/18002163/157392638-3bdfe026-ed43-4ad3-b240-17edf4abf554.png)

**Comment by eranif** [comment]
Done

**Comment by biciolea** [comment]
Wow thanks!!!
