### ISSUE TITLE
Please update codelite in FreeBSD 

### ISSUE THREAD

**Issue by ykla** [eranif/codelite#2966]
Codelite is marked as broken: outdated, doesn't build with Pango 1.46.2 or newer - PR 249879. https://www.freshports.org/editors/codelite/

Version 12.0_4 in FreeBSD, and the latest version codelite is 15. 

Please update codelite in FreeBSD. 
Thanks a lot.

**Comment by eranif** [comment]
We never supported CodeLite on FreeBSD.. it was a community effort - you will need to find someone that uses FreeBSD to support it. I am willing to help with any technical issues with CodeLite sources, but we have no plans on supporting it  on freshports
