### ISSUE TITLE
Find Symbol

### ISSUE THREAD

**Issue by shadoww1028** [eranif/codelite#2967]
Find symbol stopped working in 15.0.10 where it was working very well back in 15.0.8 on arch Linux.  Using the same example I posted in the GDB not working issue if I try to find the Vec3 class which is just up a bit in the document it instead opens unique_ptr.h at the beginning of the file.  Other times it will either not work at all or just open at the start of the .HPP file and not at the definition of the actual thing.  Find References seems to work correctly however.   It will also find the .CPP file that contains the definitions of classes if used in the HPP file but only opens at the beginning of the file.

**Comment by eranif** [comment]
fixed in this commit: 
82f170ac78d4b3784a9b67ddfb95f42296d53b0f

**Comment by maokecheng** [comment]
thanks bro,i faced the same issue
