### ISSUE TITLE
FSW:  Workspace parse/refresh action inaccessible from keyboard shortcuts

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2969]
FSW:  Workspace parse/refresh actions are inaccessible from keyboard shortcuts

It is impossible to create a keyboard shortcut for menu entry  "Workspace / Parse workspace"

It is also impossible to assign a keyboard shortcut for FSW "refresh" - (it is only accessible by right clicking a folder node in the Workspace Pane/View)

Seen with CL-15.0.11 and latest master

**Comment by eranif** [comment]
I fixed the "unable to add shortcut to parse workspace" issue in this commit:
https://github.com/eranif/codelite/commit/0d35c63ff1e5d12e824963949e37ffbc8464d497

**Comment by uffejakobsen** [comment]
> I fixed the "unable to add shortcut to parse workspace"

:+1: 

Thanks - I guess that the refresh of FSW workspace is more difficult to solve ? again guessing it is because it is a plugin ? or ?

**Comment by eranif** [comment]
No, the plugin has access the keyboard manager and it can register new commands, I will fix this tomorrow probably
