### ISSUE TITLE
What's wrong with my CodeLite's Workspace?

### ISSUE THREAD

**Issue by International-oss** [eranif/codelite#2970]
A long time ago I closed my workspace pane, when I tried to open it again, I found the pane is white and the tree view is gone. I'm currently using CodeLite v15.0 on a Ubuntu computer (20.04).
![2022-03-11 19-32-39 的屏幕截图](https://user-images.githubusercontent.com/58714080/157859263-767590e1-b79c-41dd-bdeb-624059f2f014.png)

**Comment by eranif** [comment]
Looks like you "detached" all the tabs from the workspace tree view and then somehow, the configuration was corrupted.
You try this:

`Perspective -> Restore default layout` if this does not help:

- Close CodeLite
- Delete the folder `~/.codelite/`
- Start CodeLite

**Comment by International-oss** [comment]
> 
"Perspective -> Restore default layout" didn't work and neither did the second. So I followed your third opinion and installed 15.0.11, I found I could get the Workspace Tab back! Thank you so much!
