### ISSUE TITLE
Some problems with ctagsd

### ISSUE THREAD

**Issue by liuanlin-mx** [eranif/codelite#2971]
linuxmint 20.3 mate (ubuntu 20.04)
codelite 16.0
gcc 9.4

**Comment by liuanlin-mx** [comment]
https://user-images.githubusercontent.com/20225987/158021359-8988905a-bbf2-4fb6-82b7-b8e8b9a84fa8.mp4

**Comment by liuanlin-mx** [comment]
https://user-images.githubusercontent.com/20225987/158021662-22e5598e-ed6c-4d6a-b3ea-3da9464b248e.mp4

**Comment by eranif** [comment]
can you provide the test workspace?

**Comment by liuanlin-mx** [comment]
[testclangd.tar.gz](https://github.com/eranif/codelite/files/8350643/testclangd.tar.gz)

**Comment by eranif** [comment]
thanks for providing the input example

- the first issue seems like wrong calculation of the position in the document due to the mixture of spaces and tabs
- the second issue looks like a namespace resolving issue (class should take precedence over the global namespace)
