### ISSUE TITLE
In widget utilized by "Find..", "Replace.." and "Find Resource.." for text input

### ISSUE THREAD

**Issue by nullptrdevs** [eranif/codelite#2972]
characters in text input box appear/disappear between keypresses

have a file open
press Ctrl+F (or Ctrl+H)
type "s", ok
type "t", text disappears, but is "st"
type "a", text reappears, "sta"
and so on

happens on left and right arrow key presses

happens when it gets focus on mouse click but not when it loses it

doesn't happen on getting/losing focus with Tab/Shift+Tab

Windows 10
CodeLite 15.0.11

**Comment by eranif** [comment]
can you make a screenshot with some text printed in the "Find" bar?

**Comment by nullptrdevs** [comment]
well... this is embarassing ..

it's caused by the font I'm using ..

Basically I set out to take a screenshot, but thought to myself
I'd better set the font to something legible so I set it to
Consolas, and lo and behold usability was restored

anyhow, sorry to alarm you

P.S. the font in question:
https://indestructibletype.com/Drafting/
gem of a font, not dropping it XD

**Comment by eranif** [comment]
This is now fixed in recent git master
