### ISSUE TITLE
Bug report: Numerous windows started for no reason, froze computer

### ISSUE THREAD

**Issue by Borregon** [eranif/codelite#2980]
While I was using my computer Codelite started up for no reason, opened _at least_ 30 new windows simultaneously and froze my screen for around 2 minutes. Afterward I couldn't close them all out because there were so many so I had to do a hard shut-off.

**Comment by eranif** [comment]
Hmm... CodeLite does not just starts with no reason, it has to be started. it is not a daemon or service...
So you must have started it by mistake.

Now: "30 windows" -> what do you mean by this? 30 tabs of editors? 30 instances of CodeLite? please be more specific

If it is 30 windows of CodeLite, then you have another software that launches CodeLite and you need to find what it is...

**Comment by Borregon** [comment]
Hello and thank you for getting back to my issue so quickly. What I meant was that 30 new instances of codelite started up. As if I had continuously launched the software. 

I am not sure I can reproduce the steps because at the time I was playing a game (Star Citizen), which also started having issues shortly before this happened. The game does glitch out occasionally but in my years of playing it has never caused something like this to happen. I will look into my installed software and see what may have caused this and if this does happen again I will let you know in detail.

Thank you very much for your insight :)
