### ISSUE TITLE
Question about new version tag format (16.0.0-1)

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2984]
Hello,

This is a question about new version tag format (16.0.0-1)

Most distributions already use the "-x" or "_x" as a way of changing the packaging for specific release.

In fact many distributions prohibit software versions from containing anything other than "Letters, numbers, and periods only"
https://wiki.archlinux.org/title/Arch_package_guidelines#Package_versioning

What is the intention with the added "-1" ?

/Uffe :-)

**Comment by eranif** [comment]
I first created 16.0.0 tag, I was too soon to create it as I found a bug and a new tag was required.
David then suggested that I will delete the old 16.0.0 tag to avoid confusion... I did deleted `16.0.0` but I kept the `-1` version of it

**Comment by uffejakobsen** [comment]
Ok.

As long at you have no immediate plans to issue more releases named 16.0.0-x - everything is good :-)

I'm closing this issue :-)

**Comment by dghart** [comment]
AFAIK there's nothing to stop a commit having two tags; so we could
git tag 16.0.0 70ff06225

**Comment by uffejakobsen** [comment]
I just wanted to make sure that it wasn't a new versioning scheme that was introduced

As long as the newly introduced syntax just relates to the git tag - and not to the identifiable version of codelite - I see no need to to more modifications.

:-)
