### ISSUE TITLE
$(shell ...) variables are not expanding in compiler/linker Path settings

### ISSUE THREAD

**Issue by yzazik** [eranif/codelite#2988]
Hello,
I have compiler and linker settings with $(shell ...) variables like `$(shell perl -e 'some script')`.
Specifically, in **Compiler->Options->Include Paths** and in **Linker->Options->Libraries Search Path** (not plural?).

In CL14 those are working fine, also documentation shows it can be used that way.
In CL16 those get space-delimited and intermix with semicolon-delimited settings, obviously breaks the build.

Tried `"$(shell perl -e 'some script')"`, it applies, but won't save double-quotes next time you edit it, gets space-delimited again.
Tried `$(shell\ perl\ -e\ 'some script')`, it applies, but won't expand.
Tried `$(shell"perl -e 'some script'")`, it applies, but won't expand either.

It does work in **Compiler->Pre Compiled Header->PCH Compile Flags**.

The question is, is there a different syntax for **Paths** or this functionality removed or it's a bug.
Thank you.

**Comment by yzazik** [comment]
@eranif Hello, well, just trying to understand the silence, is it luck of details describing the issue or luck of resources to look into this or something else? Thank you.

**Comment by eranif** [comment]
No, mainly I solve bugs during the weekend :) 
I promise I will give this one a high priority

**Comment by eranif** [comment]
I fixed the parsing, but you should know that what you are looking for, is only supported from the following fields:

- `Compiler -> Options -> C++ compiler options`
- `Compiler -> Options -> C compiler options`
- `Linker -> Linker options`

**Comment by yzazik** [comment]
@eranif Hi, appreciate for your time and efforts. I need a couple of days before I test this as it would require changing my .vcxproj-to-.project generator. I'm curious, what prompted the changes parsing paths after 14.0? Thank you.

**Comment by eranif** [comment]
It should have never worked for the fields you mentioned, syntax in the form of `$(shell..)` or using backticks, are only accepted in the above fields. 

For why it broke, well, I switched to use more a complicated string parsing, we now use `StringUtils::BuildArgv` method.

Prior to this change, input like this:
`word "string with space" second word`  - was broke into array of tokens: `[word, "string, with, space", second, word]` with the update, it is now parsed as `[word, "string with space", second, word]` (it also handles escaping etc). It did not recognize `$(shell.. )` as a string that should be considered as a complete string so it broke it into smaller pieces.

This commit fixed `StringUtils::BuildArgv` to handle `$(..)` properly - 0c0a7bb232ac4ed6b963b9de76275be4bc9f39c4
And this commit fixes a small regression in the above commit (because `$(name)` is a valid syntax for environment variable and should not be handled differently) - 767e0a56c3f6e2d35455d1edd8ceb690012120c4

**Comment by yzazik** [comment]
@eranif
Hit a couple of bumps building
1. wx3.1.6 is now required (due to [wxBitmap::CreateWithDIPSize()](https://docs.wxwidgets.org/trunk/classwx_bitmap.html#a975c964214c3b77f1d639c1c85ebc4a5)), needs [doc](https://docs.codelite.org/downloads/download/#linux) update.
2. `Plugin/clRowEntry.cpp` won't build (missing `#include "clSystemSettings.h"`)
3. `ctags/main/colprint.c` has C99 syntax, so if compiled with C compiler that doesn't have it by default (I had gcc4.8) it would fail, could be remedied with CMAKE_CXX_FLAGS though, but still.

About the fix, well, it works, but it messes up the search order since options come first and includes later.
In my case, it's less critical for linker, but for compiler it's a no go, unless of course I put all includes into options.

Editing includes in options (that would become much longer) is much less convenient than includes (having the same semicolon-separated format), check boxes are nice, but I see more value in option-per-line editing.

The only thing that doesn't work in paths is a construct like this: `$(shell perl -e 'script')/folder`, that `/folder` gets delimited to an extra include (but for example `$(OutDir)/doc` does work), is it something that can be fixed?

Thank you.

**Comment by eranif** [comment]
which commit are you using? what you reported was fixed latest master

**Comment by yzazik** [comment]
@eranif Not sure about commit, pulled master 14h ago, but if everything is fixed then maybe it was just pulled incompletely.
Thank you again for looking into this.

I have one more small issue, not sure if it's known or not, I can open another thread if needed.
I have first three GUI elements in **Settings->Preference->Windows/Tabs->Tabs,** which are **Tab Style**, **Tab Height** and **Active Tab Marker Colour** are greyed out, any reason for that? Thanks again.

**Comment by eranif** [comment]
On Linux, these settings are not relevant as we using the native notebook control which does not allow these modifications. 
You can enable our generic notebook by building CodeLite by passing `-DWITH_NATIVEBOOK=0`  to `CMake` (make sure you delete `CMakeCache.txt` before running CMake)

**Comment by yzazik** [comment]
@eranif
When I add `-DWITH_NATIVEBOOK=0` to `CMake` I get a build failure in `LiteEditor/frame.cpp`, GTK functions undeclared, missing `#include <gtk/gtk.h>`, once added and built those tab controls start working, thanks.

**Comment by eranif** [comment]
> The only thing that doesn't work in paths is a construct like this: `$(shell perl -e 'script')/folder`, that `/folder` gets delimited to an extra include (but for example `$(OutDir)/doc` does work), is it something that can be fixed?

This is now fixed with latest git master

**Comment by yzazik** [comment]
@eranif Confirmed, all good, much appreciate it.
