### ISSUE TITLE
CppCheck guesses wrong language

### ISSUE THREAD

**Issue by buergi** [eranif/codelite#2989]
I'm using CodeLite 15.0.0. When running CppCheck in a simple header file, e.g. `Manager.h`, which contains C++ features e.g.

    namespace abcd
    {
    }

I get this error.

    Starting cppcheck: C:\WINDOWS\system32\cmd.exe /C ""C:\Program Files\CodeLite\codelite_cppcheck.exe"  --enable=style  --enable=performance  --enable=portability  --enable=unusedFunction  --enable=missingInclude  --enable=information  --std=posix  --std=c99  --std=c++11  --template gcc  --file-list=C:\Users\me\dev\abcd\.codelite\cppcheck.list "
    Checking C:\Users\me\dev\abcd\Manager.h ...
    C:\Users\me\dev\abcd\Manager.h:1:0: warning: Code 'namespaceabcd{' is invalid C code. Use --std or --language to configure the language. [syntaxError]
    namespace abcd
    ^
    nofile:0:0: warning: Cppcheck cannot find all the include files (use --check-config for details) [missingIncludeSystem]
    ===== cppcheck analysis ended. Found 2 possible errors=====

Renaming the file into `Manager.hpp` and everything works.

    Starting cppcheck: C:\WINDOWS\system32\cmd.exe /C ""C:\Program Files\CodeLite\codelite_cppcheck.exe"  --enable=style  --enable=performance  --enable=portability  --enable=unusedFunction  --enable=missingInclude  --enable=information  --std=posix  --std=c99  --std=c++11  --template gcc  --file-list=C:\Users\me\dev\abcd\.codelite\cppcheck.list "
    Checking C:\Users\me\dev\abcd\Manager.hpp ...
    ===== cppcheck analysis ended. Found 0 possible errors=====

So it seems, cppcheck always assumes .h files to be C files and only .hpp headers to be C++. I couldn't find any way to add custom command line options to cppcheck in Codelite, which would allow me to force it to use a specified language. And even if there would be, it would probably be a global option, which works when working in a project which is only C or C++. Maybe there is a way to better guess the language.

**Comment by eranif** [comment]
this looks like a bug in CppCheck and not in CodeLite
You should open a bug the CppCheck team

**Comment by buergi** [comment]
According to [this thread](https://sourceforge.net/p/cppcheck/discussion/general/thread/8d40c994/) in the cppcheck forum cppcheck is not meant to run directly on header files. So probably the cppcheck plugin should make this clear by simply not allowing it, or at least issue a warning.

A little but of topic, but clangd by the way has the same problem, that it does not properly detect the language of .h files but it can be fixed by adding a file called `.clangd` to your project root with the content

    CompileFlags:
      Add: [-xc++]

which causes all files to be treated as c++ files.
