### ISSUE TITLE
Codelite 16.1.0 doesn't create tags file

### ISSUE THREAD

**Issue by hobbitdev** [eranif/codelite#2990]
Hallo everybody

I'm experiencing a strange behaviour using codelite 16.1.0 with Rasberry OS (buster) both 32bit and 64bit
I built Codelite form its source code and everythings went fine.

The "problem" arise when I open a workspace as usual.
The "Got to Symbol" option doesn't work and instead of the normal file called "tags" I find into workspace folder the file below.
![image](https://user-images.githubusercontent.com/33904565/166138393-b026bc7c-e10c-4253-9a4e-98e13d56601c.png)

This kind of behaviour using the previous version 15 wasn't present.

This is my "Language Server settings" I normally use
![image](https://user-images.githubusercontent.com/33904565/166138664-a377901c-3366-48ea-b902-0c404bde6907.png)

Regards
Rossano

**Comment by eranif** [comment]
everything should be created under the `.ctagsd` folder
check that folder instead

**Comment by hobbitdev** [comment]
thank you @eranif below I describe CodeLite behaviour ...

**Codelite 16.1.0 - Linux Mint 19.3 64bit**
I start opening my workspace the only two files present into the folder are: gateway.workspace, gateway.project
After loading into the folder this is the content.
![image](https://user-images.githubusercontent.com/33904565/166191930-5460c0e5-a06a-40a0-a40b-fb9011604add.png)
Objects with blu rectangles have been created.
The function "Go to Symbol" works well.

**Codelite 15.0.9 - RaspBerry (Stretch 32 bit)**
I start opening my workspace the only two files present into the folder are: gateway.workspace, gateway.project
After loading into the folder this is the content.
![image](https://user-images.githubusercontent.com/33904565/166190947-c831d81a-98ad-4214-b038-d3f0ea7d47e4.png)
Objects with blu rectangles have been created.
The function "Go to Symbol" works well.

**Codelite 16.1.0 - RaspBerry (Stretch 32bit, Buster 32 bit, Buster 64bit)**
I start opening my workspace the only two files present into the folder are: gateway.workspace, gateway.project
After loading into the folder this is the content.
![image](https://user-images.githubusercontent.com/33904565/166193309-cbb710dc-390e-4432-985c-1b19971a6b15.png)
Objects with blu rectangles have been created.
The function "Go to Symbol" doesn't work.

The file "tags.db" contained in .ctagsd folder seems empty, as it size is 96kB instead of 18MB observed in Linux Mint.
Furthermore a file with a strange name is created with size of 0B outside the .ctagsd folder.

Regards
Rossano

**Comment by eranif** [comment]
With this information, I am not sure why no the database file is small (it probably contains only the schema)
You should increase the verbosity of `ctagsd` and try it again

`plugins -> language servers -> settings -> ctags`
change the command line from:

```
/usr/bin/ctagsd --port 45634 --log-level ERR
```

into:

```
/usr/bin/ctagsd --port 45634 --log-level DBG
```

The log file should be under `~/.ctagsd/`

post it here

**Comment by hobbitdev** [comment]
@eranif please find here attached the log file you need

[ctagsd.log](https://github.com/eranif/codelite/files/8601659/ctagsd.log)

**Comment by eranif** [comment]
From the log:

```
[10:21:45:544 DBG] [Main] Parsing chunk ( 0 ) of 348 files
[10:21:45:568 DBG] [Main] Generating ctags files
[10:21:45:582 DBG] [Main] Running command: /bin/sh -c '/usr/bin/codelite-ctags --options=/home/pi/.ctagsd/options-1933756592.ctags --c-kinds=+pxz --C++-kinds=+pxz  -L /tmp/codelite/1591/file-list-1933756592.txt -f - '
[10:21:45:595 DBG] [Main] Parsing took: 0 secs, 13 ms
[10:21:45:595 DBG] [Main] Generating ctags files... Success
[10:21:45:596 DBG] [Main] 0 tags, ctags output: 
```

clearly it is able to find source file, I wonder why `0` tags generated. The problem is here:

```
[10:21:45:596 DBG] [Main] 0 tags, ctags output:
```
after the `output:` `ctagsd` should print the raw output of `codelite-ctags`, in your case - an empty string.

```c++
    if(tags.empty()) {
        clDEBUG() << "0 tags, ctags output:" << content << endl;
    }
```
can you try and run `codelite-ctags` manually and see what it prints?

**Comment by eranif** [comment]
If I had to guess here, it probably does not run, maybe different arch? (arm vs x86_64 etc)

**Comment by hobbitdev** [comment]
kind @eranif I built CodeLite directly using raspberry HW, as I did with the previos version 15.0.9
The ARCH chosen by the build process should be the right one.

Excuse me, could you please guide me to esecute what you are asking ?
"can you try and run codelite-ctags manually and see what it prints?"

**Comment by eranif** [comment]
Yes, building it is not enough. `codelite-ctags` is part of the repository and is not build with CodeLite (we should probably need to change this)

Can you try and just run `/usr/bin/codelite-ctags --version` ?

**Comment by hobbitdev** [comment]
This is the output:
/usr/bin/codelite-ctags: cannot execute binary file: Exec format error

**Comment by eranif** [comment]
as I suspected :)
wrong arch.
the solution is simple enough:

1. Build `ctags` manually:

```bash
git clone https://github.com/universal-ctags/ctags.git
cd ctags
./autogen.sh
./configure --prefix=/where/you/want # defaults to /usr/local
make -j$(nproc)
make -j$(nproc) install # may require extra privileges depending on where to install
```

Once you have new `ctags` built, delete `/usr/bin/codelite-ctags` and then create a symlink from `ctags` -> `codelite-ctags`
this will fix the problem for you

**Comment by eranif** [comment]
The reason that we have `codelite-ctags` is because it used to contained some fixed that were not available in the upstream version of ctags, things have changed and we no longer require this. I will fix the code base to to ensure that `codelite-ctags` is built as part of CodeLite sources

**Comment by hobbitdev** [comment]
@eranif hats off :)

Following your precuos tips CodeLite 16.1.0 now is working fine.
One again thank you.

Regards
Rossano

**Comment by eranif** [comment]
FYI, I created a fork from `uctags` and added `CMake` build system to it. The next step is to build it as git submodule along with CodeLite sources

https://github.com/eranif/ctags
