### ISSUE TITLE
color issues

### ISSUE THREAD

**Issue by raadapish** [eranif/codelite#2991]
![image](https://user-images.githubusercontent.com/75102485/166586366-540c0ed9-c24a-4fcb-bfbd-3f36e91af4d4.png)
colors arent working properly

**Comment by eranif** [comment]
I am not sure what I am seeing here..

If you are missing semantic highlights, then these colours are coming from the language servers.
Do you have one configured and working? (you will know its working if your code completion is working)

also, try switching themes

**Comment by eranif** [comment]
PIng.
Another thing to try:

- `Settings -> colours and fonts` and click on the `Restore` button
- Choose your theme
- Click `OK`
