### ISSUE TITLE
Text cursor offset compared to mouse pointer position

### ISSUE THREAD

**Issue by jonathanfvmtl** [eranif/codelite#2992]
When clicking on the text editor to position the cursor in the text or to select the text, the cursor is offset to the right compared to the mouse pointer position. I included an image as an example. The selected text is what it is, but the yellow cursor position has been added to demonstrate where the mouse pointer actually was.

![CursorBug](https://user-images.githubusercontent.com/25098082/166609403-b2cb4968-8f9b-40a6-a3c2-4aef5dbcf04c.png)

**Comment by jonathanfvmtl** [comment]
Hi Eran! Thanks for the quick reply, it's much appreciated. I just switched
the font from Noto Sans (default font of the style I was using) to Noto
Mono Regular, and restarted just in case. The problem persists,
unfortunately.

**Comment by jonathanfvmtl** [comment]
Please let me know if I can do anything else to help find the source of the problem. Thank you kindly!

**Comment by eranif** [comment]
can you post a picture of the problem with monospaced font?

**Comment by eranif** [comment]
also, some data is missing:
- which Linux distro?
- is this a self compiled CodeLite + wxWidgets?
- Which GTK version

**Comment by jonathanfvmtl** [comment]
Certainly sir! Please let me know if anything else would be useful. Also, I will certainly understand if there are more pressing problems, as I seem to be the only one with that issue so far.

-Linux Mint 20.3 is my distro
-I am using CodeLite 16.0.0 from the binary packages that come with the Debian repository
-GTK is 3.24.20 (3.24.20-0ubuntu1.1) and libcairo2 (1.16.0-4ubuntu1)

![CodeLite-Problem](https://user-images.githubusercontent.com/25098082/168416635-15e33c60-db44-484c-9164-07df2203b472.png)

**Comment by eranif** [comment]
Is it possible for you to build CodeLite + wxWidgets from sources?

**Comment by jonathanfvmtl** [comment]
Just did! Very clear documentation, btw. I now have version 16.1.0 installed, built from source.

The problem persists. I imagine it must be something on GTK's side then?

**Comment by eranif** [comment]
did you also built wxWidgets?

**Comment by eranif** [comment]
If you did not build wxWidgets - then please do.
Next is to try the `stc` sample and see if the problem persists there as well

**Comment by jonathanfvmtl** [comment]
Hmm, I did build and install wxWidgets from source, as indicated in the documentation.

Just compiled the stc sample as well, and the cursor behaves normally in the sample's text field. I have to go to bed now, and I'll be gone until Sunday, but I'll keep digging as soon as I get back home if you tell me where to look next. Your help is really appreciated. Once again, I want to reiterate that my case should be no priority, as I'm only learning and don't do professional development.

**Comment by jonathanfvmtl** [comment]
But here are some screen captures to better illustrate the problem. First is stc, second is CodeLite.

https://user-images.githubusercontent.com/25098082/168420294-ad3b76ec-da9a-4cfb-8b2a-e12c39ca80c0.mp4


https://user-images.githubusercontent.com/25098082/168420295-a4879fa9-41f5-4503-9b2b-f0e1d0a95644.mp4

**Comment by eranif** [comment]
disable the option:
`settings -> preferences -> guides -> line numbers -> highlight current line number`
does this change anything?

Next thing to try, disable the line numbers margin completly

`settings -> preferences -> guides -> line numbers -> display line numbers`

**Comment by jonathanfvmtl** [comment]
It does not fix the issue, but it does something interesting. Without the
line numbers margin, the offset becomes only two characters. It's still
there, but it's smaller. An other interesting behavior with the line
numbers margin displayed is that sometimes the offset is 4 characters, and
sometimes it's 5.

**Comment by eranif** [comment]
I will release a new CodeLite this weekend with the fix included

**Comment by jonathanfvmtl** [comment]
Awesome, thank you so much again Eran! You rock! And I saw that other report! I hadn't thought about fractional scaling!
