### ISSUE TITLE
Compile error with wx stable (3.0.x)

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#2993]
I see the following compile error with wx stable (3.0.x)

```
 [13%] Building CXX object Plugin/CMakeFiles/plugin.dir/clThemedTextCtrl.cpp.o
/tmp/codelite-devel.git/Plugin/clThemedTextCtrl.cpp: In member function ‘void clThemedTextCtrl::ApplySettings()’:
/tmp/codelite-devel.git/Plugin/clThemedTextCtrl.cpp:111:9: error: ‘class wxBitmap’ has no member named ‘CreateWithDIPSize’
  111 |     bmp.CreateWithDIPSize(wxSize(1, 1), GetDPIScaleFactor());
      |         ^~~~~~~~~~~~~~~~~
/tmp/codelite-devel.git/Plugin/clThemedTextCtrl.cpp:111:41: error: ‘GetDPIScaleFactor’ was not declared in this scope; did you mean ‘GetContentScaleFactor’?
  111 |     bmp.CreateWithDIPSize(wxSize(1, 1), GetDPIScaleFactor());
      |                                         ^~~~~~~~~~~~~~~~~
      |                                         GetContentScaleFactor

```

**Comment by eranif** [comment]
Can you build CodeLite with wx3.1.6?

**Comment by uffejakobsen** [comment]
> Can you build CodeLite with wx3.1.6?

Hmm, good question...

I just tried - and no same error:
```
[ 13%] Building CXX object Plugin/CMakeFiles/plugin.dir/clThemedTextCtrl.cpp.o
/tmp/codelite-devel.git/Plugin/clThemedTextCtrl.cpp: In member function ‘void clThemedTextCtrl::ApplySettings()’:
/tmp/codelite-devel.git/Plugin/clThemedTextCtrl.cpp:111:9: error: ‘class wxBitmap’ has no member named ‘CreateWithDIPSize’
  111 |     bmp.CreateWithDIPSize(wxSize(1, 1), GetDPIScaleFactor());
      |         ^~~~~~~~~~~~~~~~~
/tmp/codelite-devel.git/Plugin/clThemedTextCtrl.cpp:111:41: error: ‘GetDPIScaleFactor’ was not declared in this scope; did you mean ‘GetContentScaleFactor’?
  111 |     bmp.CreateWithDIPSize(wxSize(1, 1), GetDPIScaleFactor());
      |                                         ^~~~~~~~~~~~~~~~~
      |                                         GetContentScaleFactor
```

Archlinux only ships stable wx 3.0.5 - so I needed to manually build wx 3.1.6 - placing it in `/opt/wxgtk-dev/`- allowing it to coexist with wx stable as other installed apps depend on that one...

Using `-DWITH_WX_CONFIG=/opt/wxgtk-dev/bin/wx-config-gtk3` to point it to the right location

Configure output seems to confirm that the right version is picked up:
```
-- BUILD_DIRECTORY is set to /tmp/codelite-devel.git/_build.out
-- OS name Linux
-- wx-config used is: /opt/wxgtk-dev/bin/wx-config-gtk3
-- wxWidgets version is: 3.1.6
-- gtk version is: 3
```

But still fails...

**Comment by eranif** [comment]
I assume that `_build.out` folder is a new one and does not contain any relics from the last time you ran CMake (with the older version of wxWidgets).

Also, can you run `make` like this?

```bash
make VERBOSE=1 -j$(nproc)
```

**Comment by uffejakobsen** [comment]
> I assume that `_build.out` folder is a new one and does not contain any relics from the last time you ran CMake (with the older version of wxWidgets).

It was only cleaned - before (re)configure - will try to remove it completely - build is running now (on slow laptop)

**Comment by uffejakobsen** [comment]
> > I assume that `_build.out` folder is a new one and does not contain any relics from the last time you ran CMake (with the older version of wxWidgets).
> 
> It was only cleaned - before (re)configure - will try to remove it completely - build is running now (on slow laptop)

Ok that may have got me a little longer - It is difficult to say because I've now got a new error:
```
[ 32%] Linking C executable ../bin/codelite-ctags
/usr/bin/ld: cannot find -lseccomp: No such file or directory
```

`libseccomp` is installed:
```
% ls -al /usr/lib/libseccomp.so*
lrwxrwxrwx 1 root root     19 Apr 22 07:56 /usr/lib/libseccomp.so -> libseccomp.so.2.5.4*
lrwxrwxrwx 1 root root     19 Apr 22 07:56 /usr/lib/libseccomp.so.2 -> libseccomp.so.2.5.4*
-rwxr-xr-x 1 root root 124744 Apr 22 07:56 /usr/lib/libseccomp.so.2.5.4*
```
From the error `/usr/bin/ld: cannot find -lseccomp: No such file or directory`
It could look like that `-lseccomp` is taken for a real filename and not a reference to a library - strange
I'll have to look into this next week...

**Comment by eranif** [comment]
I removed `seccomp` dependency from the ctags submodule
You will need to run `update` from the root source tree:

```
git pull --rebase --recurse-submodules
```

**Comment by uffejakobsen** [comment]
Follow up:

Building latest `master` with wx 3.1.6 works 

But building latest `master` from scratch (with wx 3.0.5) still gives the error below:


```
[ 27%] Building CXX object Plugin/CMakeFiles/plugin.dir/clStatusBar.cpp.o
/tmp/codelite-devel.git/Plugin/clScrolledPanel.cpp: In member function ‘void clScrolledPanel::DoInitialize()’:
/tmp/codelite-devel.git/Plugin/clScrolledPanel.cpp:89:14: error: ‘class wxBitmap’ has no member named ‘CreateWithDIPSize’
   89 |     m_tmpBmp.CreateWithDIPSize(1, 1, GetDPIScaleFactor());
      |              ^~~~~~~~~~~~~~~~~
/tmp/codelite-devel.git/Plugin/clScrolledPanel.cpp:89:38: error: ‘GetDPIScaleFactor’ was not declared in this scope; did you mean ‘GetContentScaleFactor’?
   89 |     m_tmpBmp.CreateWithDIPSize(1, 1, GetDPIScaleFactor());
      |                                      ^~~~~~~~~~~~~~~~~
      |                                      GetContentScaleFactor
```

**Comment by eranif** [comment]
We no longer support older versions of wxWidgets.
The latest 3.1.6 is required.

In July 2022, wx3.2 is scheduled to be released. Which will be a requirement for future developments

DPI scaling is something that older versions of wxWidgets are lacking and 3.1.6 fixes this
