### ISSUE TITLE
Codelite 16.0 just crashes after start at once on Windows 7

### ISSUE THREAD

**Issue by kompilainenn** [eranif/codelite#2994]
Codelite 16.0 just crashes after start at once on Windows 7

Steps:
1. Download Codelite 16.0
2. Install Codelite
3. Try start Codelite =>crash

**Comment by eranif** [comment]
Try this:

- Close CodeLite
- Try deleting the folder `%appdata%\CodeLite` 
- Start CodeLite
-

**Comment by stahta01** [comment]
Is there a wiki page with the info you posted of "Try deleting the folder %appdata%\CodeLite"?
I am trying to update CodeLite package for MSys2 MinGW.
Thanks, I had to delete the appdata to get the newer version to run.

Tim S.
