### ISSUE TITLE
Code completion doesn't reappear when the code being typed was interrupted.

### ISSUE THREAD

**Issue by jasonlogbi** [eranif/codelite#2999]
Is there a way to retrigger the code completion when you resume typing the word after it was interrupted? It seems that code completion is only triggered when you hit backspace. It would be nice if there is an option where the code completion **retriggers** when you type the next letter regardless of where it is on the word that is being typed or when you place the caret back on the word.

**Comment by eranif** [comment]
You can re-trigger it by hitting `Ctrl-SPACE` or if you are on macOS `CMD-SPACE`

**Comment by jasonlogbi** [comment]
Yes, but I think hitting `Ctrl-SPACE` every time kinda defeats the purpose of auto code completion. It would be great if it'll be implemented as an option.
