### ISSUE TITLE
Arch Linux Install

### ISSUE THREAD

**Issue by shadoww1028** [eranif/codelite#3007]
On Arch Linux GDB no longer works with codelite version 16 along with the mouse over tool tip on Functions.  On Linux mint one can install the latest packages and everything still works so its not the version of libraries installed but instead something that is different in codelite when building from source vs installing the binaries.  Other programs like Clion work just fine, Kdevelop however also does not work with GDB on arch but that may be been a setup issue on my part.  

Work arounds:
1. Use LLVM as the debugger - not good as well as you can no longer do math in the watches. 
2. To get some information on a function place the cursor in the name and hit CTRL-SPACE and a popup will come up but with no comments. Not great but the best I can see happening.

**Comment by eranif** [comment]
By default, GDB tooltips require the `Ctrl` key to be pressed.
i.e. you need to hover on a variable or something and then hit and hold `Ctrl`
Did you try that?

Also, if the tooltip still does not work for you, please paste here the debugger output:
- Settings -> GDB settings -> GNU gdb debugger -> Misc -> Enable full debugger logging
- And paste the output the CodeLite produces during a failure

**Comment by shadoww1028** [comment]
here is everything, Nothing work, can't run, jump, jump into.  Well Stop works.

Using gdbinit file: /home/shadoww/.codelite-gdbinit
Current working dir: /home/shadoww/Documents/code/GameEngine/UnitTests
Launching gdb from : /home/shadoww/Documents/code/GameEngine/UnitTests
Starting debugger  : /usr/bin/gdb --command="/home/shadoww/.codelite-gdbinit" --tty=/dev/pts/0 --interpreter=mi "../bin/Debug-linux-x86_64/UnitTests/UnitTests"
DEBUG>>set unwindonsignal on
DEBUG>>set breakpoint pending on
DEBUG>>catch throw
DEBUG>>set print object on
DEBUG>>set width 0
DEBUG>>set height 0
DEBUG>>set pagingation off
DEBUG>>set print elements 200
DEBUG>>00000010-break-insert -f -t main
DEBUG>>00000011-break-insert -f -t main
Debug session started successfully!
DEBUG>>00000012-exec-arguments
DEBUG>>00000013-exec-run
DEBUG>>=thread-group-added,id="i1"
=thread-group-added,id="i1"
DEBUG>>~"GNU gdb (GDB) 12.1\n"
GNU gdb (GDB) 12.1
DEBUG>>~"Copyright (C) 2022 Free Software Foundation, Inc.\n"
Copyright (C) 2022 Free Software Foundation, Inc.
DEBUG>>~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law."
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.
DEBUG>>~"\nType \"show copying\" and \"show warranty\" for details.\n"
\nType "show copying" and "show warranty" for details.
DEBUG>>~"This GDB was configured as \"x86_64-pc-linux-gnu\".\n"
This GDB was configured as "x86_64-pc-linux-gnu".
DEBUG>>~"Type \"show configuration\" for configuration details.\n"
Type "show configuration" for configuration details.
DEBUG>>~"For bug reporting instructions, please see:\n"
For bug reporting instructions, please see:
DEBUG>>~"<https://www.gnu.org/software/gdb/bugs/>.\n"
<https://www.gnu.org/software/gdb/bugs/>.
DEBUG>>~"Find the GDB manual and other documentation resources online at:\n    <http://www.gnu.org/software/gdb/documentation/>."
Find the GDB manual and other documentation resources online at:\n    <http://www.gnu.org/software/gdb/documentation/>.
DEBUG>>~"\n\n"
\n
DEBUG>>~"For help, type \"help\".\n"
For help, type "help".
DEBUG>>~"Type \"apropos word\" to search for commands related to \"word\"...\n"
Type "apropos word" to search for commands related to "word"...
DEBUG>>~"File(s) /usr/include/c++/*/*/* will be skipped when stepping.\n"
File(s) /usr/include/c++/*/*/* will be skipped when stepping.
DEBUG>>~"File(s) /usr/include/c++/*/* will be skipped when stepping.\n"
File(s) /usr/include/c++/*/* will be skipped when stepping.
DEBUG>>~"File(s) /usr/include/c++/* will be skipped when stepping.\n"
File(s) /usr/include/c++/* will be skipped when stepping.
DEBUG>>~"Reading symbols from ../bin/Debug-linux-x86_64/UnitTests/UnitTests...\n"
Reading symbols from ../bin/Debug-linux-x86_64/UnitTests/UnitTests...
DEBUG>>&"\"/home/shadoww/.codelite-gdbinit\": No such file or directory.\n"
DEBUG>>&"set unwindonsignal on\n"
DEBUG>>=cmd-param-changed,param="unwindonsignal",value="on"
=cmd-param-changed,param="unwindonsignal",value="on"
DEBUG>>^done
DEBUG>>&"set breakpoint pending on\n"
DEBUG>>=cmd-param-changed,param="breakpoint pending",value="on"
=cmd-param-changed,param="breakpoint pending",value="on"
DEBUG>>^done
DEBUG>>&"catch throw\n"
DEBUG>>~"Catchpoint 1 (throw)\n"
Catchpoint 1 (throw)
DEBUG>>=breakpoint-created,bkpt={number="1",type="catchpoint",disp="keep",enabled="y",what="exception throw",catch-type="throw",thread-groups=["i1"],times="0"}
=breakpoint-created,bkpt={number="1",type="catchpoint",disp="keep",enabled="y",what="exception throw",catch-type="throw",thread-groups=["i1"],times="0"}
DEBUG>>^done
DEBUG>>&"set print object on\n"
DEBUG>>=cmd-param-changed,param="print object",value="on"
=cmd-param-changed,param="print object",value="on"
DEBUG>>^done
DEBUG>>&"set width 0\n"
DEBUG>>=cmd-param-changed,param="width",value="4294967295"
=cmd-param-changed,param="width",value="4294967295"
DEBUG>>^done
DEBUG>>&"set height 0\n"
DEBUG>>=cmd-param-changed,param="height",value="4294967295"
=cmd-param-changed,param="height",value="4294967295"
DEBUG>>^done
DEBUG>>&"set pagingation off\n"
DEBUG>>&"No symbol \"pagingation\" in current context.\n"
DEBUG>>^error,msg="No symbol \"pagingation\" in current context."
^error,msg="No symbol \"pagingation\" in current context."
DEBUG>>&"set print elements 200\n"
DEBUG>>^done
DEBUG>>00000010^done,bkpt={number="2",type="breakpoint",disp="del",enabled="y",addr="0x0000000000027206",func="main(int, char**)",file="src/cpp/main.cpp",fullname="/home/shadoww/Documents/code/GameEngine/UnitTests/src/cpp/main.cpp",line="173",thread-groups=["i1"],times="0",original-location="main"}
Storing internal breakpoint ID=2
DEBUG>>00000011^done,bkpt={number="3",type="breakpoint",disp="del",enabled="y",addr="0x0000000000027206",func="main(int, char**)",file="src/cpp/main.cpp",fullname="/home/shadoww/Documents/code/GameEngine/UnitTests/src/cpp/main.cpp",line="173",thread-groups=["i1"],times="0",original-location="main"}
DEBUG>>00000012^done
>> Debuggee process ID: 6816
DEBUG>>=thread-group-started,id="i1",pid="6816"
=thread-group-started,id="i1",pid="6816"
DEBUG>>=thread-created,id="1",group-id="i1"
=thread-created,id="1",group-id="i1"
DEBUG>>=breakpoint-modified,bkpt={number="1",type="catchpoint",disp="keep",enabled="y",what="exception throw",catch-type="throw",thread-groups=["i1"],times="0"}
=breakpoint-modified,bkpt={number="1",type="catchpoint",disp="keep",enabled="y",what="exception throw",catch-type="throw",thread-groups=["i1"],times="0"}
DEBUG>>=breakpoint-modified,bkpt={number="2",type="breakpoint",disp="del",enabled="y",addr="0x000055555557b206",func="main(int, char**)",file="src/cpp/main.cpp",fullname="/home/shadoww/Documents/code/GameEngine/UnitTests/src/cpp/main.cpp",line="173",thread-groups=["i1"],times="0",original-location="main"}
=breakpoint-modified,bkpt={number="2",type="breakpoint",disp="del",enabled="y",addr="0x000055555557b206",func="main(int, char**)",file="src/cpp/main.cpp",fullname="/home/shadoww/Documents/code/GameEngine/UnitTests/src/cpp/main.cpp",line="173",thread-groups=["i1"],times="0",original-location="main"}
DEBUG>>=breakpoint-modified,bkpt={number="3",type="breakpoint",disp="del",enabled="y",addr="0x000055555557b206",func="main(int, char**)",file="src/cpp/main.cpp",fullname="/home/shadoww/Documents/code/GameEngine/UnitTests/src/cpp/main.cpp",line="173",thread-groups=["i1"],times="0",original-location="main"}
=breakpoint-modified,bkpt={number="3",type="breakpoint",disp="del",enabled="y",addr="0x000055555557b206",func="main(int, char**)",file="src/cpp/main.cpp",fullname="/home/shadoww/Documents/code/GameEngine/UnitTests/src/cpp/main.cpp",line="173",thread-groups=["i1"],times="0",original-location="main"}
DEBUG>>=library-loaded,id="/lib64/ld-linux-x86-64.so.2",target-name="/lib64/ld-linux-x86-64.so.2",host-name="/lib64/ld-linux-x86-64.so.2",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ffff7fc8000",to="0x00007ffff7fee9e5"}]
=library-loaded,id="/lib64/ld-linux-x86-64.so.2",target-name="/lib64/ld-linux-x86-64.so.2",host-name="/lib64/ld-linux-x86-64.so.2",symbols-loaded="0",thread-group="i1",ranges=[{from="0x00007ffff7fc8000",to="0x00007ffff7fee9e5"}]
DEBUG>>~"\nThis GDB supports auto-downloading debuginfo from the following URLs:\nhttps://debuginfod.archlinux.org \nEnable debuginfod for this session? (y or [n]) "
\nThis GDB supports auto-downloading debuginfo from the following URLs:\nhttps://debuginfod.archlinux.org \nEnable debuginfod for this session? (y or [n])

**Comment by eranif** [comment]
From the looks of it, it seems that GDB is expecting some answer from CodeLite...

```
~"\nThis GDB supports auto-downloading debuginfo from the following URLs:\nhttps://debuginfod.archlinux.org \nEnable debuginfod for this session? (y or [n]) "
```
What happens if you add this:

```
set debuginfod enabled off
```

to: `settings -> preferences -> GDB Settings -> GNU gdb debugger -> Startup commands1` (a the bottom)
