### ISSUE TITLE
Editor margin offset with fractional scaling enabled

### ISSUE THREAD

**Issue by iwbnwif** [eranif/codelite#3010]
Codelite version 16.0.0
Ubuntu 22.04
Nvidia nvidia-driver-510

I have fractional scaling enabled (125%) on dual 4K monitors and it is causing a problem with the editor window. 

The text is offset to the right and there is a black gap between the fold margin and the main edit surface.

Left clicking the mouse places the text cursor three characters to the right of the mouse cursor.

If I turn off fractional scaling then the problem goes away.

Possibly related, the font in the Workspace View tree control, drop down and the status bar is also slightly too large.

**Comment by eranif** [comment]
Is it similar to this bug report?

https://github.com/eranif/codelite/issues/2992

**Comment by iwbnwif** [comment]
Yes, it is identical, sorry. I searched for margin offsets, fractional scaling, etc. but didn't find that one.

**Comment by eranif** [comment]
Any idea how to reproduce this locally?

**Comment by iwbnwif** [comment]
Turn on fractional scaling and set it to 125%. I think it is a new problem to 16.0 because it was previously okay. I also tried building from Github previously and had the same problem.

**Comment by eranif** [comment]
I dont have access to Linux atm, except for Windows WSL2 (Ubuntu)
Any environment variable that I can set that enables this? (or config...)

**Comment by iwbnwif** [comment]
![codelite_scaling](https://user-images.githubusercontent.com/11036083/171283770-d54ab68e-5bfa-4132-9f33-84b0a40ec791.png)

**Comment by iwbnwif** [comment]
Just for the record, this is the Ubuntu / Gnome settings app that enables fractional scaling.
![settings_app](https://user-images.githubusercontent.com/11036083/171284075-5e5cdfd6-627d-493e-9432-b8896913fc65.png)

**Comment by eranif** [comment]
As a quick workaround, you can disable all the 3 margins used.
Settings -> Preferences -> Guides -> Enable line numbers
Settings -> Preferences -> Bookmarks -> Enable symbol margin
Settings -> Preferences -> Folding -> Display the folding margin

**Comment by eranif** [comment]
I will release a new CodeLite this weekend with the fix included (or you can build CodeLite from sources)

**Comment by iwbnwif** [comment]
That's amazing - thank you :)

**Comment by iwbnwif** [comment]
Can confirm that the fix works fine on my system. Also, the font issue is fixed, but I think that is to do with a wxWidgets patch as 16.0.0 now also has the correct font size even though it still has the margin issue.
