### ISSUE TITLE
auto-complete doesn't work

### ISSUE THREAD

**Issue by zhenhe168** [eranif/codelite#3018]
codelite version 16.0.0
mingw64 version 8.1: x86_64-8.1.0-release-posix-seh-rt_v6-rev0
windows 11 professional
c/c++ programming

'hello world' program compiles and executes correctly. But auto-complete doesn't happen for e.g. std::cin . It only shows the words of current directory as auto-complete options.
Project Setting -> Code Completion -> Search Path is blank.
Shouldn't the IDE search the default include path based on codelite compiler selection?

**Comment by eranif** [comment]
it should and it does.
You should confirm that you have code completion engine enabled (at least one)
https://docs.codelite.org/plugins/lsp/
