### ISSUE TITLE
Syntax Highlighting Not Displaying Properly (Codelite 1.16.0)

### ISSUE THREAD

**Issue by python3xdev** [eranif/codelite#3031]
Before when I was messing around in the Language Server settings, I noticed that the text changes colors depending on what was selected. Here is the current syntax highlighting:

![image](https://user-images.githubusercontent.com/77379766/175791129-7f7e4b8b-be7a-4fe4-9d53-5d7a0f5ae37d.png)

Right now I'm using clangd. Before when I was using clangd the highlighting was different. `std::cout`, `std::cin` were yellow, but now their not. That makes me think some other syntax highlighting is missing. Any ideas on what's causing this? The theme I'm using is `Atom One-Dark`.

**Comment by eranif** [comment]
CodeLite offers the basic colour syntax highlight (what you see now)
The other colouring stuff comes from the language server. why is this? the language server has the knowledge that `favorite_number` is a member is a variable and should be coloured differently. If the code completion works for you, it should be able to provide the colouring as expected.

Can you share the content of the file `compile_flags.txt` or `compile_commands.json` that you have in the workspace folder?

**Comment by python3xdev** [comment]
Section4\compile_commands.json:
```
[{
  "file": "D:\\---my_path---\\Section4\\Project1\\main.cpp",
  "directory": "D:\\---my_path---\\Section4\\Project1",
  "command": "\"\"C:/Program Files/mingw-w64/bin/g++.exe\"\" -c D:\\---my_path---\\Section4\\Project1\\main.cpp -o D:\\---my_path---\\Section4\\Project1\\main.cpp.o  -I. -I.  -g  -O0  -std=c++17  -Wall"
 }]
```
Section4\Project1\compile_flags.txt:
-ID:\---my_path---\Section4\Project1
-std=c++17
-target

**Comment by eranif** [comment]
nothing after `-target` ??

please follow the docs on how to install a compiler on Windows (follow the instructions step by step):
https://docs.codelite.org/build/mingw_builds/#prepare-a-working-environment

Also, don't use compiler with space in their path ... its just a recipe for problems
without `-target` clangd will fail

I really recommend to uninstall the compiler that you installed here `C:/Program Files/mingw-w64` and use the one in the docs
If you choose to do this:
- After you install the compiler as explained in the docs, go to `settings -> build settings`
- Delete the old compiler you had
- click on the magnifier button and let CodeLite detect the newly installed compiler
- Rebuild your workspace

**Comment by python3xdev** [comment]
I want to do it this way, but how can I use this information on Windows 10? Do these commands work in the MSYS terminal on windows?

**Comment by python3xdev** [comment]
After all this is done installing, where will it all be installed? In a single folder at `C:\msys64`? So if I ever wanted to delete it, its just in one place?

**Comment by eranif** [comment]
Yes, everything is installed under `C:\msys64`

**Comment by python3xdev** [comment]
It's working! Thank you so much for your help today. One last question, what do the red arrows indicate? (next to the line numbers)

![image](https://user-images.githubusercontent.com/77379766/175793293-c4a8adfb-b541-461a-8b86-22e33e2e251c.png)

**Comment by eranif** [comment]
Running CodeLite as admin is **not** advised..
You can put a "post build" event that will accidentally run `rm -fr C:\`

The little red arrows have a tooltip, place your mouse on them and read the message
Usually they come from either the compiler (as errors) or from `clangd`
