### ISSUE TITLE
Opens and closes right after clicking on window (Windows 10 Home 21H2, AMDx64)

### ISSUE THREAD

**Issue by Dm1stry** [eranif/codelite#3032]
Installed codelite 16.0.0 on windows 10 (home 21H2 x64) yesterday (26.06.2022) on "D:" drive (all programs, that i installed like this before, work perfectly, it is actual first time), so it is runs for about a second, then closes, if i try to click on window, when it still open, it closes immediately, so there is no way to use it.

Tried to delete %appdata%/codelite folder, nothing changes
Tried to reinstall program, it starts it's wizard after installation, for configuration of the ide, but on the third step it's closes again, without any warning or anything
Tried using windows 7 compatibility, nothing changes

Always it's just closes, no exceptions, no warnings, no errors, no death screen, nothing, like i just didn't open it

**Comment by eranif** [comment]
this sounds like something environmental, like anti virus
so you anu auch software installed?

**Comment by stahta01** [comment]
FYI: I am trying to update MSys2 codelite package to version 16.1.0 and I am finding that wxcrafter crashes the wizard setup.

**Comment by joao-pinhal-feup** [comment]
Having the same problem here (same specs too), I have tried installing every version until 15.0.0, and the same problem occurs. Although some versions let me go through the setup wizard when I finish, and it restarts the program the setup was not saved. It's a shame, I really like the simplicity of this IDE...

**Comment by eranif** [comment]
fixed with 41ba11a43
