### ISSUE TITLE
[Feature Request] An ability to rearrange watches in the debugger pane

### ISSUE THREAD

**Issue by Eric-01** [eranif/codelite#3034]
It could be a nice addition if you added an ability to rearrange watches (and eventually locals too) in the debugger pane. Three (mutually exclusive?) options for implementing this that come to my mind are by adding:
* support for dragging and dropping particular lines to the desired positions
* a few toolbar buttons like "Move Up", "Move Down", "Move to Top", "Move to Bottom" that would manipulate the position(s) of the currently selected row(s)
* the same options as above to the right-click context menu, however, the downside here is that if you wanted to move a row up by 3, for example, you would have to click 3 times in 3 different positions, because after each single move, the context menu would obviously be moved by several pixels as well.

Another suggestion on this topic, which unfortunately has been closed as stale: #2135.

**Comment by eranif** [comment]
the problem is that there is no persistent id that we can use to associate the ui element with the debugger data. 
I believe this is doable for watches, but not for automatic scope variables

**Comment by Eric-01** [comment]
I would really appreciate it if you implemented something like this even just for watches. However, if you think it will be too difficult and basically not worth the effort, feel free to close this feature request.

**Comment by Eric-01** [comment]
Ping
