### ISSUE TITLE
wxWidget  3.2.0 floating panes drift

### ISSUE THREAD

**Issue by acotty** [eranif/codelite#3037]
Watch the wxWidget 3.1.7 and 3.2.0 as floating panes will drift. For info see:
[See: https://forums.codeblocks.org/index.php/topic,25031.new.html#new](https://github.com/wxWidgets/wxWidgets/issues/22533)

You can use the 3.1.6 src\aui\floatpane.cpp file in 3.1.7 or 3.2.0 as there are no other changes, apart from the change that is causing the problem in 3.1.7 (3.2.0 is the same file as 3.1.7).

C::B discussion thread:
https://forums.codeblocks.org/index.php/topic,25031.new.html#new

**Comment by eranif** [comment]
how is this related to CodeLite?
You should report this in the wxWidgets repository

**Comment by acotty** [comment]
As per the following commit you have started working or getting things in place for using wxWidgets 3.2.0 and as such I thought this may be relevant for you:
https://github.com/eranif/codelite/commit/ffafae6fe82109dfad01fbbbdaff1c31015acc75

It has been reported:
https://github.com/wxWidgets/wxWidgets/issues/22533

Last night after my prodding a PR was done to fix it:
https://github.com/wxWidgets/wxWidgets/pull/22651
