### ISSUE TITLE
Git tag is missing for CodeLite 16.2.0 - Weekly Build July 23, 2022.

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#3040]
Hi,

A git tag is missing for CodeLite 16.2.0 - Weekly Build July 23, 2022.

/Uffe

**Comment by eranif** [comment]
I knew I forgot something :D

**Comment by eranif** [comment]
https://github.com/eranif/codelite/tree/16.2.0

**Comment by uffejakobsen** [comment]
Thanks :+1:  :-)
