### ISSUE TITLE
Codelite 16: Navigation bar is broken

### ISSUE THREAD

**Issue by Itsme456** [eranif/codelite#3043]
Up to codelite 15, the navigation bar contained two buttons, one with the function names and one with the current file name.
On codelite 16.0 there is onle the button with the current file name.

Installation is codelite_16.0-1unofficial.buster_amd64.deb on debian buster.

**Comment by eranif** [comment]
its not broken. if you dont have entries in it, you should make sure that your code completion is working properlyhttps://docs.codelite.org/plugins/lsp/

**Comment by Itsme456** [comment]
Yes, by activating the language server plugin, the list is generated again.

Thank you.
