### ISSUE TITLE
[Feature Request] Add support for Alacritty terminal emulator

### ISSUE THREAD

**Issue by etenium** [eranif/codelite#3044]
From what I read in GitHub issues the list of terminals is fixed, would it be possible to add support for Alacritty Terminal Emulator on Linux or an ability to chose custom Terminal?

Link to Alacritty's GitHub page:
https://github.com/alacritty/alacritty

**Comment by eranif** [comment]
nice. i like the fact that its cross platform. i will definitely look into it

**Comment by Eric-01** [comment]
Ping
