### ISSUE TITLE
Jump to code is broken in compiler output tab

### ISSUE THREAD

**Issue by iHardRock** [eranif/codelite#3045]
On latest master build log tab looks like just a text. 
Very usefull feature - jump to code by clicking on error message is broken now :(

**Comment by iHardRock** [comment]
Very interesting... It sometimes works. Looks like it depends from LanguageServer (that is sometime not works).

**Comment by eranif** [comment]
The output tab is not related to the Language Server plugin. If the output is not working for you, then make sure that the selected toolchain matches the code that you are compiling
You did not provide other information (such as: workspace type, OS etc)

**Comment by iHardRock** [comment]
I can't reproduce this issue anymore. It happened after update with a new deb package, compiled from master. 
After few restarts and work in IDE, i have found that it start to work normally.

Ubuntu 20.04, Unity desktop. File system workspace. Version compiled from master with wxWidgets 3.2, GTK2 and NATIVEBOOK=0
