### ISSUE TITLE
[C++] [Code completion] Floods of error icons "file not found" and "Unknown type name"

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#3046]
CodeLite build b78446b5c7e2e19a1dea0371812bb15d01fc6356 running on Arch and stock wxWidgets version 3.2.
In all of my projects I am getting CodeLite source window flooded with red arrows. All non-standard includes have "file not found" errors, whereas all symbols have "Unknown type name" errors. Also, at the top of each C++ source code file, there is a red arrow with message "Too many errors omitted, stopping now". The project itself compiles just fine both with GCC and Clang compilers with CodeLite's "Default" makefile generator.

I have tried setting both relative and absolute paths in Project Settings - Code Completion - Search paths, as well as doing the same in Workspace Settings - Code Completion - Search paths, but this does not change anything. The issue seems to come from "clangd" language server.

This issue has been for a while now, I think - maybe for one year or so. Because of it, I've been sticking to CodeLite 14.0, but it no longer compiles with new version of wxWidgets 3.2 that is bundled in Arch now.

**Comment by eranif** [comment]
From the description of your problem, I understand that you are using clangd as your code completion engine
It has some drawbacks, one of them is that it stop parsing and yields many errors.

To fix this issue:

- Make sure that there are no `compile_flags.txt` files in your workspace:
```bash
find . -name "compile_flags.txt"
```

if you find some, delete them:

```bash
find . -name "compile_flags.txt"|xargs rm -f
```

- Make sure you **have** a `compile_commands.json` file at the root of your workspace (Use CodeLite Make Generator its your best option), but anyways, CodeLite should produce this file for you
- Use the latest `clangd` you can get
- create a `.clangd` file at the root of your workspace with this content:

```yaml
CompileFlags:
    Add:
        - "-ferror-limit=0"

---

If:
    PathMatch: .*\.h
CompileFlags:
    Add:
        - "-xc++"


```

- Restart the language server: `plugins -> language server -> restart`

If your `compile_commands.json` is valid and you are using `clangd` v13 or above - you should be OK

**Comment by yunkot** [comment]
I've removed "compile_flags.txt" and added ".clangd" as you suggested. In Project Settings, I've changed "Makefile Generator" to "CodeLite Makefile Generator" and indeed "compile_commands.json" has been generated. ".clangd" is located in the same folder as my "MyProject.workspace" file and "compile_commands.json". The project compiles fine. However, the problem remains exactly the same with the same error marks, including the one on top.

clangd --version gives:
> clangd version 14.0.6
> Features: linux
> Platform: x86_64-pc-linux-gnu

**Comment by yunkot** [comment]
Placing ".clangd" at the root of my include/source files (which is located at different location than workspace) does seem to fix the error at top (I suppose the error limit lifted), but none of the others.

**Comment by yunkot** [comment]
I also tried to explicitly add include folder to ".clangd", so now the file looks like:

> CompileFlags:
>     Add:
>         - "-I=/data1/my_include_folder/"
> 
> ---
> 
> If:
>     PathMatch: .*\.h
> CompileFlags:
>     Add:
>         - "-xc++"
However, this still gives the same flood of errors like "MyFile.h is not found" and "Unknown type name".

**Comment by eranif** [comment]
In that case you need to check the content of the `compile_commands.json` and confirm that it is correct and contains the correct paths. Also, which clangd version are you using?

**Comment by eranif** [comment]
CodeLite launches clangd from the workspace folder, so the fact that your workspace is located in a different folder might cause issues. 
Can you provide the directory structure of your workspace? (something like the output of the `tree` command)

**Comment by yunkot** [comment]
"compile_commands.json" appears to have correct (absolute) paths and commands and as I've said, the project compiles just fine.

Regarding the project structure, the workspace location is:
`(base)/(Package)/Projects/CodeLite/MyProject.workspace`

I use only one project per workspace, so my CodeLite project is located at:
`(base)/(Package)/Projects/CodeLite/MyProject/MyProject.project`

Its main source file is located at:
`(base)/(Package)/Projects/Source/MyProject.cpp`

All include files are located at:
`(base)/(Package)/framework/include/*.h`
`(base)/(Package)/framework/include/platforms/*.h`
`(base)/(Package)/framework/include/providers/*.h`

All source files are located at:
`(base)/(Package)/framework/src/*.cpp`
`(base)/(Package)/framework/src/platforms/*.cpp`
`(base)/(Package)/framework/src/providers/*.cpp`

So in CodeLite in Project Settings - Additional Include Paths, I have set: 
`".;../../../framework/include;../../../framework/include/platforms;../../../framework/include/providers"`
All source files are added to CodeLite project tree. The project compiles just fine.

So to make "error-limit=0" cland command work, I had to put ".clangd" file at:
`(base)/(Package)/framework/.clangd`

However, it still can't find any of the include files.

**Comment by eranif** [comment]
If everything is correct in the `compile_commands.json`, then where is it located?

**Comment by eranif** [comment]
For the sake of the test, can you modify `clangd` command line to include this option:

```
 --compile-commands-dir=<string> - Specify a path to look for compile_commands.json. If path is invalid, clangd will look in the current directory and parent paths of each source file
```

**Comment by yunkot** [comment]
According to above structure, it is located at:
`(base)/(Package)/Projects/CodeLite/compile_commands.json`

**Comment by eranif** [comment]
see my prev comment

**Comment by yunkot** [comment]
I've modified ".clangd" like this, but it doesn't change anything:
```
CompileFlags:
    Add:
        - "--compile-commands-dir=/data/my_package/Projects/CodeLite/"

---

If:
    PathMatch: .*\.h
CompileFlags:
    Add:
        - "-xc++"
```
Other than compiling the project, how can I validate the resulting "compile_commands.json"? Or is there anything else I can do to debug the run of "clangd"?

**Comment by eranif** [comment]
No, you need to add it in CodeLite. `--compile-commands-dir` is clangd option, not a compiler option

From:

`Plugins -> Language Server -> Settings -> clangd`

**Comment by yunkot** [comment]
Actually, this one seems to work, the flood of errors are gone. I get some new ones like "Unused variable" on all global static constexpr constants, but I suppose this is a different issue.

But this setting appears to be global to all workspaces and projects, is there a way to make CodeLite feed the correct path? Ideally, it should match that of "IntermediateDirectory".

**Comment by yunkot** [comment]
Actually, CodeLite appears to ignore project directory as well as "Intermediate Directory" option. and produces "compile_commands.json" at the same folder as MyProject.workspace is located. If there are other ".workspace" files at the same directory, I suppose this will overwrite "compile_commands.json" each time? Is there a way to tell CodeLite to place this folder inside project sub-folder (and provide --compile-commands-dir to clangd accordingly)?

**Comment by eranif** [comment]
Your main problem is that your workspace folder is not one of the parent folders of your source files.

i.e. from your structure:

You tree looks something like:

```
--root
    |__Projects
       |_ source files 
    |__CodeLite
        |__ my.workspace
````
clangd will look for `compile_commands.json` starting from the source file and it will check every parent until it finds one
In your case, it will never find it

You need to create a symlink:

`ln -sf  /path/to/compile_commands.json /path/to/Projects/compile_commands.json`
and restart the language server

**Comment by eranif** [comment]
Also, there CodeLite uses the same technique as CMake and generates a single compile_commands.json file. The above solution is the your best bet (this is how I solve the same issue while using CMake to generate my `compile_commands.json` and it is placed in the build directory which is not a direct or in-direct parent of the source files)

**Comment by yunkot** [comment]
That is based on assumption that workspace actually contains all source code files. In my case, workspace is just merely a container for CodeLite project to be able to build my framework, and I have multiple workspaces/projects. I also have containers for Visual Studio and other IDEs there. The relative path from workspace to framework **include** and **src** folders is `../../../framework`. So when **clangd** parses some file at `../../../framework/src/file.cpp`, it needs to locate **compile_commands.json** at its current relative path as `../../Projects/CodeLite/`, which doesn't work because it only checks parents.

For me the final solution is to change Command in Language Server Settings - clangd as the following:
`/usr/bin/clangd -limit-results=500 -header-insertion-decorators=0 --compile-commands-dir=$(WorkspacePath)`

Since this is the hard-coded location, where CodeLite creates such file and there is no UI option in CodeLite to change the behavior, I suggest that the above command should be set by default in Language Server Settings when CodeLite is first run. A better alternative that I would suggest is to provide an UI option in CodeLite to specify where it should generate "compile_commands.json" so it won't pollute folder containing **.workspace** files.

**Comment by eranif** [comment]
IMO, creating a symlink is the cleanest solution and it will not affect the settings globally
have you tried doing that?

**Comment by yunkot** [comment]
The location of workspace folders may vary and there is no way to create a dynamic symlink that will know the location of "compile_commands.json", which would match the location, where CodeLite creates such files each time. In my case, framework location is fixed, but workspace file location may vary.

**Comment by yunkot** [comment]
I actually don't agree that you've closed this issue as complete. In my opinion, this is really a bug in CodeLite: instead of providing the path to the correct file, relying on **clangd** behavior to search for **compile_commands.json** generated by CodeLite, which in your particular tests happens to be within some parent folder (workspace folder), thus not triggering the issue.

I think adding **--compile-commands-dir=$(WorkspacePath)** by default would be the correct behavior.

**Comment by yunkot** [comment]
Thank you. By the way, the current version of CodeLite is really amazing! Just wired you some donation to help with the project. :)
