### ISSUE TITLE
[Bug]: LLDB can't be to used with Codelite 16.0.0 on macOS Monterey 12.5

### ISSUE THREAD

**Issue by z002378** [eranif/codelite#3048]
### What happened?

XCode 13.4.1 is installed but LLDB debugger is unavailable and it can't to be selected in setting->general for my project because Codelite not show it in the combobox. I show only GDB debugger.

### Version

16.0.0

### Operating system

macOS

**Comment by eranif** [comment]
Please upgrade to 16.2.0 and use `DAP` plugin (the LLDB plugin is deprecated)


In CodeLite 16.2.0, we switched to use `lldb-vscode`

- Install latest CodeLite (16.2.0) https://docs.codelite.org/downloads/download/#macos
- To install `lldb-vscode` on macOS: https://docs.codelite.org/plugins/dap/#lldb-vscode
- In your workspace, change the debugger to `lldb-vscode`

**Comment by z002378** [comment]
Hi Eranif,
I have followed your instructions but I can’t to select the lldb-vscode because it not showed when i would to create a new project. Only gdb is showed.
Please help me…
Thanks for your help
Daniel

**Comment by z002378** [comment]
Thank you Eran for your help and efficacy.
I would to say that Codelite is a very amazing tool and I use codelite from many year. Tanks very much
Daniel

PS: scuse me for my poor English because I’m of Switzerland French Part
