### ISSUE TITLE
[Wiki] Mention "git submodule update --init" on documentation page

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#3049]
On CodeLite wiki page:
https://wiki.codelite.org/pmwiki.php/Developers/Linux

It seems that recent versions of CodeLite require Git sub-modules to be initialized and updated. If you don't do this, the first time you execute **cmake** command, it'll fail and explicitly suggest initializing sub-modules. Therefore, I'd suggest on the documentation page changing this command:
```
git clone https://github.com/eranif/codelite.git
```
to these commands:
```
git clone https://github.com/eranif/codelite.git
cd codelite
git submodule update --init --progress
```

**Comment by eranif** [comment]
I am surprised you were able to find these old pages...
all are docs are placed under : 

https://docs.codelite.org

I will remove the entries that lead to the old wiki
