### ISSUE TITLE
minor: Hardcoded specific versions for clangd and clang-format in the .deb package

### ISSUE THREAD

**Issue by nullptrdevs** [eranif/codelite#3050]
this could be just my distro, but i find myself having to repackage the .deb because it has clangd-10 and clang-format-10 as deps

Where:
https://github.com/eranif/codelite/blob/046f27ca511a3e3128069542aa004a32fc96ce8c/CMakeLists.txt#L506-L517

proposed:
```
    set(DEB_DEPS "")
    if ( ${distro} STREQUAL "debian_10" )
        set(DEB_DEPS "clang-tools (>= 7), clang-format (>= 10)")
    endif()


    if ( ${distro} STREQUAL "ubuntu_1804" )
        set(DEB_DEPS "clangd (>= 10), clang-format (>= 10)")
    endif()


    if ( ${distro} STREQUAL "ubuntu_2004" )
        set(DEB_DEPS "clangd (>= 10), clang-format (>= 10)")
    endif()
```

[relevant doc](https://cmake.org/cmake/help/v3.3/module/CPackDeb.html#variable:CPACK_DEBIAN_PACKAGE_DEPENDS)

**Comment by acotty** [comment]
Both LinuxMint  21.0 or Xubuntu 22.04 do not have clang-10 package available by default, but 11, 12 and 14 are available.

Would be nice to be able to install CodeLite 16.2 without doing any rebuild or hacking on LM or Xubutu.

**Comment by eranif** [comment]
Feel free to send a PR and I will merge it
