### ISSUE TITLE
[Bug]: Subclass of wxSpinCtrl crashes wxCrafter

### ISSUE THREAD

**Issue by kortmannm** [eranif/codelite#3054]
### What happened?

Subclass a wxSpinCtrl with wxSpinCtrlDouble crashed wxCrafter.
Subclass manually in the wxcp file crashes wxcrafter also.

Martin

### Version

16.0.2

### Operating system

Windows 10

**Comment by eranif** [comment]
this is fixed with latest master

**Comment by eranif** [comment]
I was able to reproduce it (again)
this seems to be a problem with the fact that `wxSpinCtrlDouble` is not a real subclass of `wxSpinCtrl`

I changed the XRC demo (from wxWIdgets samples) and manually edited the XRC to reflect the same use case - the crash happens there too. The only solution I can think of is to **not** use the `subclass` property in the generated `xrc` file

This will produce a valid working C++ code, but it will break the XRC generation...
