### ISSUE TITLE
[Bug]: Environment crashes when accessing workspaces

### ISSUE THREAD

**Issue by GKrcal** [eranif/codelite#3056]
### What happened?

CodeLite crashes shortly after starting, if its last session refers to a workspace folder.
If you remove the workspace from the _session.xml_ file manually the IDE starts, however. The IDE crashes too, when opening a workspace.

CodeLite Version 16.2.0 (brew installation)
OS: MacOSX 12.5

### Version

Other

### Operating system

macOS

**Comment by 317369225** [comment]
i meet the samle problem

**Comment by eranif** [comment]
- Do you have any log trace (usually, macOS will show a dialog with "send to apple")
- Can you start CodeLite from the command line (`open /path/to/codelite.app`)
- Can you run CodeLite under `lldb` and print the backtrace here when it crashes?

**Comment by GKrcal** [comment]
I hope this is useful:

user@MacOS % lldb /Applications/codelite.app                            
(lldb) target create "/Applications/codelite.app"
Current executable set to '/Applications/codelite.app' (x86_64).
(lldb) breakpoint list
No breakpoints currently set.
(lldb) run
Process 1465 launched: '/Applications/codelite.app/Contents/MacOS/CodeLite' (x86_64)
2022-08-22 18:19:22.033077+0200 CodeLite[1465:45537] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=1465
2022-08-22 18:19:22.033211+0200 CodeLite[1465:45537] SecTaskCopyDebugDescription: CodeLite[1465]/0#-1 LF=0
Process 1465 exited with status = 13 (0x0000000d) Terminated due to signal 13
(lldb) run
Process 1552 launched: '/Applications/codelite.app/Contents/MacOS/CodeLite' (x86_64)
2022-08-22 18:20:44.727294+0200 CodeLite[1552:46776] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=1552
2022-08-22 18:20:44.727433+0200 CodeLite[1552:46776] SecTaskCopyDebugDescription: CodeLite[1552]/0#-1 LF=0
Process 1552 exited with status = 13 (0x0000000d) Terminated due to signal 13
(lldb)

**Comment by GKrcal** [comment]
**Do you have any log trace (usually, macOS will show a dialog with "send to apple")?**
Unfortunatelly with this kind of crash macOS offers no trace

**Can you start CodeLite from the command line (open /path/to/codelite.app)?**
Starting CodeLite with the open command, following the pattern `open ./AppName.app --args -AppCommandLineArg`
works fine. However, `open ./codelite.app` doesn't force macOS to trace something.
Can I pass on some arguments to the CodeLite application, in order that itself will create a tracelog?
E.g. `open ./codelite.app --args -debug`?

**Can you run CodeLite under `lldb` and print the backtrace here when it crashes?**
Unfortunatelly `(lldb) thread backtrace` results in an error.
```
user@macOS /Applications % lldb codelite.app
(lldb) target create "codelite.app"
Current executable set to '/Applications/codelite.app' (x86_64).
(lldb) run
Process 2066 launched: '/Applications/codelite.app/Contents/MacOS/CodeLite' (x86_64)
2022-08-22 19:10:26.666124+0200 CodeLite[2066:75280] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=2066
2022-08-22 19:10:26.666275+0200 CodeLite[2066:75280] SecTaskCopyDebugDescription: CodeLite[2066]/0#-1 LF=0
Process 2066 exited with status = 13 (0x0000000d) Terminated due to signal 13
(lldb) thread backtrace
error: invalid thread
(lldb) quit
```

**Comment by GKrcal** [comment]
Maybe this is useful too. Opening CodeLite from the CLS with `open ./Applications/codelite.app --args -debug` doesn't result in a crash when a workspace folder is opened, closed and reopened again.

**Comment by eranif** [comment]
Have you tried running this command after brew installation completed?

```
xattr -cr /Applications/codelite.app/
```

**Comment by GKrcal** [comment]
The problems seems to be solved.
I removed the installation and restarted a brew installation. Than I run the command `xattr -cr /Applications/codelite.app/`
CodeLite starts without crash.
However I didn't try to upgrade to 16.2.0 version yet.
