### ISSUE TITLE
[Bug]:  CodeLite 12.0.0 build-settings mismatch for CMake projects = won't build #2275 

### ISSUE THREAD

**Issue by milen-prg** [eranif/codelite#3066]
### What happened?

A bug happened! (Windows 10 Pro 64bit, Codelite 15.0)

CMake project not builds as is described in the old ISSUE BUG REPORT (see title).
Additionally - if make manually the folders tricks, described in this old report  and build the project exe, it can't be started and debugged in Codelite.

### Version

Other

### Operating system

Windows 10

**Comment by eranif** [comment]
No information to proceed
