### ISSUE TITLE
[Bug]: Codelite was ended unexpectedly on macOS Monterey 12.6 (M1 Macbook)

### ISSUE THREAD

**Issue by MartinMohammed** [eranif/codelite#3074]
### What happened?

After installing CodeLite through the provided instructions on the official website: 
```
brew tap eranif/codelite
brew uninstall --cask codelite-official
brew install --cask codelite-official

# in order to avoid macOS errors about "damaged app can't be opened"...
xattr -cr /Applications/codelite.app/
```

https://docs.codelite.org/downloads/download/#macos

I ended up getting an error when I try to open the application.
Termination reason: "Namespace DYLD, Code 1 Library missing
Library not loaded: '/opt/homebrew/*/libssh.4.dylib'"

Referenced from: " '/Applications/codelite.app/Contents/MacOS/codelite'"

### Version

16.0.2

### Operating system

macOS

### Steps to reproduce

```text
In the terminal: 


brew tap eranif/codelite
brew uninstall --cask codelite-official
brew install --cask codelite-official

# in order to avoid macOS errors about "damaged app can't be opened"...
xattr -cr /Applications/codelite.app/
```

Open the application through finder program on macbook and start it.

### Relevant log output

```shell
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '/opt/homebrew/*/libssh.4.dylib'
Referenced from: '/Applications/codelite.app/Contents/MacOS/codelite'
Reason: tried: '/opt/homebrew/*/libssh.4.dylib' (no such file), '' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)
```
```

**Comment by eranif** [comment]
I have released CodeLite 16.6.0 can you please try and update?
This binary should be codesigned

**Comment by blockchaindevel** [comment]
I just tried this with 16.6.0 and the app crashes as soon as it is launched.  Same steps as in the previous report.

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /opt/homebrew/*/libpcre2-32.0.dylib
Referenced from: <6AB17E22-F9CD-3741-B50A-08185674310B> /Applications/codelite.app/Contents/MacOS/libwx_osx_cocoau-3.2.0.1.0.dylib
Reason: tried: '/opt/homebrew/*/libpcre2-32.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/*/libpcre2-32.0.dylib' (no such file), '/opt/homebrew/*/libpcre2-32.0.dylib' (no such file), '/usr/local/lib/libpcre2-32.0.dylib' (no such file), '/usr/lib/libpcre2-32.0.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)

**Comment by eranif** [comment]
This is now fixed. CodeLite 16.7.0 should fix this issue
