### ISSUE TITLE
codelite output not opening

### ISSUE THREAD

**Issue by yous2203** [eranif/codelite#3075]
When i run my project the ouput terminal doesnt show up on my screen. Instead I have this message 👍 Working directory is set to: 

/Users/yousramz/Desktop/test/EXERCICES 1/EXERCISE
Executing: /Applications/codelite.app/Contents/MacOS/codelite-terminal.app --working-directory=/Users/yousramz/Desktop/test/EXERCICES 1/EXERCISE --file=/tmp/codelite/67515/codelite-terminal.txt --wait 
Program exited
(Im on Mac)

**Comment by eranif** [comment]
Try switching to a native Terminal:

From the menu bar: CodeLite -> Preferences -> Terminal -> iTerm (or iTerm2)
