### ISSUE TITLE
Environment crashes when accessing workspaces

### ISSUE THREAD

**Issue by GKrcal** [eranif/codelite#3077]
### Issue
_CodeLite 16.3.0_ crashes shortly after starting, if its last session refers to a workspace folder.
After removing the workspace from the _sessions.xml_ file (\~/Library/Application Support/CodeLite/config/sessions.xml) manually, the IDE starts, however. CodeLite crashes too/again, when opening a workspace.

**OS:** MacOSX 12.6 (Monterey)
**CodeLite:** 16.3.0

### Crash report
Following crash report is the Apple given log trace: [CodeLite Apple Crash Report.txt](https://github.com/eranif/codelite/files/9618914/CodeLite.Apple.Crash.Report.txt)

### Background
Installation has been done according [CodeLite Documentation > Downloads > MacOS](https://docs.codelite.org/downloads/download/#macos): 
```
# we need this part since we bring our own libssh bound to version 0.9.6
brew unlink libssh

brew tap eranif/codelite
brew reinstall --cask codelite-official

# in order to avoid macOS errors about "damaged app can't be opened"...
xattr -cr /Applications/codelite.app/
```

#### No work around
Like in [issue 3056](https://github.com/eranif/codelite/issues/3056), removing  _CodeLite_ 16.3.0, and installing _CodeLite_ 16.0.0 results in a stable environment.
```
brew install --cask codelite
xattr -cr /Applications/codelite.app/

```

**Comment by eranif** [comment]
Can you try this please:

- Change the settings (using the stable CodeLite 16.0) `Preferences -> Misc -> Check for new version` and set it to "No" (uncheck it)
- Close CodeLite, update it again and try to open it

If this still fails, can you try and rename the folder:

- Close CodeLite
- Rename `~/Library/Application Support/CodeLite` into `~/Library/Application Support/CodeLite.orig`
- Start CodeLite

**Comment by Soomy06** [comment]
So, I am pretty new to IDE things, I have no clue how to Rename that thing to this thing ~/Library/Application Support/CodeLite.orig How do I do that?

**Comment by Soomy06** [comment]
> So, I am pretty new to IDE things, I have no clue how to Rename that thing to this thing ~/Library/Application Support/CodeLite.orig How do I do that?

@eranif
