### ISSUE TITLE
[Question]: How to fix broken build process?

### ISSUE THREAD

**Issue by EmilySeville7cfg** [eranif/codelite#3086]
![image](https://user-images.githubusercontent.com/42812113/195854505-86285483-3baf-4345-aa1c-b616a3cfd2a2.png)

```
/bin/sh -c '/usr/bin/make -j4 -e -f  Makefile'
----------Building project:[ BinarySearch - Debug ]----------
make[1]: Entering directory '/home/emilyseville7cfg/Documents/work/C++/Tanya Shibko/BinarySearch/BinarySearch'
/usr/bin/g++-11  -c  "/home/emilyseville7cfg/Documents/work/C++/Tanya Shibko/BinarySearch/BinarySearch/main.cpp" -g -O0 -Wall  -o "/home/emilyseville7cfg/Documents/work/C++/Tanya\ Shibko/BinarySearch"/build-Debug/__/__/__/__/__/__/__/__/main.cpp.o -I. -I.
Assembler messages:
Fatal error: can't create /home/emilyseville7cfg/Documents/work/C++/Tanya\ Shibko/BinarySearch/build-Debug/__/__/__/__/__/__/__/__/main.cpp.o: No such file or directory
make[1]: *** [BinarySearch.mk:95: ../build-Debug/BinarySearch/main.cpp.o] Error 1
make[1]: Leaving directory '/home/emilyseville7cfg/Documents/work/C++/Tanya Shibko/BinarySearch/BinarySearch'
make: *** [Makefile:5: All] Error 2
====0 errors, 0 warnings====
```

Makefile is not changed (it's the default one):

```makefile
.PHONY: clean All

All:
	@echo "----------Building project:[ BinarySearch - Debug ]----------"
	@cd "BinarySearch" && "$(MAKE)" -f  "BinarySearch.mk"
clean:
	@echo "----------Cleaning project:[ BinarySearch - Debug ]----------"
	@cd "BinarySearch" && "$(MAKE)" -f  "BinarySearch.mk" clean

```

**Comment by eranif** [comment]
Can you please post here the version of CodeLite + OS you are using?

**Comment by EmilySeville7cfg** [comment]
CodeLite: 14.0.0
OS: Ubuntu 22.04.1 LTS

**Comment by eranif** [comment]
The logic is simple:

- CodeLite builds the file path relative to the project (or workspace, cant remember)
- If the relative path contains `.` or `..` -> they are placed with underscores

The fact that the object file contains multiple `__` suggests that your file main.cpp is not placed in the workspace folder (I am guessing here)

Can you:

- Upload / paste the content of the `.workspace` / `.project` files here?
- Upgrade to a more recent version of CodeLite? (your version is 2.5+ years old)

Try installing CodeLite from our repository:

https://docs.codelite.org/downloads/download/#ubuntu-debian

Eran

**Comment by EmilySeville7cfg** [comment]
Problem disappeared after upgrading to 16 version.
