### ISSUE TITLE
[Bug]: Can't dock panes

### ISSUE THREAD

**Issue by Simbi0z** [eranif/codelite#3088]
### What happened?

version 16.0.0
os: archlinux
sway-git r6975.99fd096d-1
wlroots-git 0.16.0.r5785.a049d66d-1

I am using codelite within sway (wayland) and I am unable to dock dettached panes (the output pane to be precise, I don't want to test detach others and not being able to dock them later). Also tested with GDK_BACKEND=x11 and same issue. There is also no "attach" option when right clicking on the pane.

I found no relevant information in the "developer" codelite log in settings.

### Version

16.0.0

### Operating system

Linux

### Steps to reproduce

```text
1-Detach
2-Try to dock
```

**Comment by Simbi0z** [comment]
Also tested with latest git (by last night) 16.4.0.r96.gda8a3904e-1, same issue. If I delete .codelite* directories, panes are attached again, while they are attached it is possible to move them around, but when detached it is no longer possible.

**Comment by eranif** [comment]
the detaching/docking framework is not really related to CodeLite. Its a "bonus" from the wxWidgets library that I am using.
If you can't dock, then something is broken in wxWidgets. Can you please report this issue to the wxWidgets team?

**Comment by Sod-Almighty** [comment]
This is still broken. At some point, eranif, you have to take responsibility for your bugs.

**Comment by eranif** [comment]
@Sod-Almighty you can always switch and use a different editor...
