### ISSUE TITLE
[Bug]: Generated makefile has syntax errors

### ISSUE THREAD

**Issue by zebra224** [eranif/codelite#3089]
### What happened?

Using CodeLite 16.0.0, MinGW (GNU Make 4.2, g++ 12.2.0) on a Windows10 machine:
I made a very simple "hello world" test project. The generated makefile produces an error when I try to build the project:

sh: syntax error: unexpected end of file (expecting "then")
make.exe[1]: *** [MinwTest.mk:86: MakeIntermediateDirs] Error 2

Plus an identical error for line 90.

If I create the directories myself, remove the directory creation instructions from the makefile, and run the make manually from a command prompt, the rest of the build works fine. I have attached the entire generated makefile for your review. (I added the .txt extension b/c otherwise this website would not permit the attachement.)
[Makefile.txt](https://github.com/eranif/codelite/files/9792725/Makefile.txt)

### Version

16.0.0

### Operating system

Windows 10

### Steps to reproduce

```text
See above description.
```

### Relevant log output

```shell
From the CodeLite output window:

C:/w64devkit/bin/make.exe -j8 SHELL=cmd.exe -e -f  Makefile
"----------Building project:[ MingwTest - Debug ]----------"
make.exe[1]: Entering directory 'C:/Users/zebra/Documents/_Core_/Programming/MingwTest'
sh: syntax error: unexpected end of file (expecting "then")
make.exe[1]: *** [MingwTest.mk:86: MakeIntermediateDirs] Error 2
make.exe[1]: *** Waiting for unfinished jobs....
sh: syntax error: unexpected end of file (expecting "then")
C:/w64devkit/bin/g++.exe  -c  "C:/Users/zebra/Documents/_Core_/Programming/MingwTest/test.cpp" -g -O0 -Wall  -o build-Debug/test.cpp.o -I. -I.
make.exe[1]: *** [MingwTest.mk:90: build-Debug/.d] Error 2
Assembler messages:
Fatal error: can't create build-Debug/test.cpp.o: No such file or directory
make.exe[1]: *** [MingwTest.mk:99: build-Debug/test.cpp.o] Error 1
make.exe: *** [Makefile:5: All] Error 2
make.exe[1]: Leaving directory 'C:/Users/zebra/Documents/_Core_/Programming/MingwTest'
=== build completed successfully (0 errors, 0 warnings) ===
```

**Comment by eranif** [comment]
Your toolchain is expecting "bash" syntax. You need to tell CodeLite to generate Makefile that matches your toolchain.
To change this:

- Project settings
- Select "General" from the left list
- Change the generator to: `CodeLite Makefile Generator - UNIX`

If this does not work, use either `CMake` or switch compiler.
Personally, I recommend using the compiler that [comes with MSYS2][1] - it is always up-to-date and we fully support it

[1]: https://docs.codelite.org/build/mingw_builds/#prepare-a-working-environment
