### ISSUE TITLE
[Bug]: No output from codelite-terminal when using some characters in source code 

### ISSUE THREAD

**Issue by Simbi0z** [eranif/codelite#3090]
### What happened?

Some characters like _**á**_  in the source code make codelite-terminal only print "Hit any key to continue...". Tested both in version 16.0.0 and git da8a3904e4a48eb0772cf79d3a6f8624e8afc16e . Other terminals print these characters fine.

### Version

Self compiled

### Operating system

Linux

### Steps to reproduce

```text
#include <iostream>


using namespace std;

int main(int argc, char **argv)
{
	printf("números");
	
	return 0;
}
```

**Comment by eranif** [comment]
`codelite-terminal` was removed from CodeLite for macOS. Please use `iTerm2` or `iTerm` instead
