### ISSUE TITLE
-DWITH_FLEX=1 fails to compile 

### ISSUE THREAD

**Issue by Simbi0z** [eranif/codelite#3093]
When adding build options -DWITH_FLEX=1 (and -DWITH_MYSQL=1, though it seems to be unrelated), codelite fails to compile.
```
/.src/codelite-git/src/codelite/CodeLite/PhpLexer.cpp: In function ‘bool phpLexerNext(void*, phpLexerToken&)’:       
/.src/codelite-git/src/codelite/CodeLite/PhpLexer.cpp:3562:19: error: ‘std::string phpLexerToken::text’ is private wi
thin this context                                                                                                              
 3562 |             token.text = userData->GetString();
```
Build from:
[PKGBUILD.txt](https://github.com/eranif/codelite/files/9823829/PKGBUILD.txt)

relevant args:

```
 CXXFLAGS="${CXXFLAGS} -fno-devirtualize"

  cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
    -DWITH_WX_CONFIG=/usr/bin/wx-config-gtk3 \
    -DENABLE_LLDB=1 -DWITH_MYSQL=1 -DWITH_FLEX=1\
    -DCMAKE_INSTALL_LIBDIR=lib \
```
git: da8a3904e4a48eb0772cf79d3a6f8624e8afc16e 
OS: archlinux
cmake version 3.24.2
pkg-config :  1.8.0
gcc version 12.2.0 

[CMakeError.log](https://github.com/eranif/codelite/files/9823966/CMakeError.log)

**Comment by eranif** [comment]
Both options are deprecated and will be removed in the very near future - don't use them
