### ISSUE TITLE
[Bug] The bundled clangd language server is no longer automatically configured by CodeLite

### ISSUE THREAD

**Issue by Greg-21** [eranif/codelite#3094]
### What happened?

On Windows, CodeLite comes with a few language servers that should be ready to be used out of the box. In theory, because in practice, CodeLite 16.5.0 seems to have trouble finding and automatically configuring the clangd language server it was bundled with. It is not configured automatically, neither when launching CodeLite for the first time, nor when manually triggering the process by pressing the "Scan..." button in the LanguageServerPlugin plugin settings.

I noticed this first on my Windows 8.1 PC, but Windows 10 installed in a VM seems to be affected as well.

Screenshot showing this issue (freshly installed CodeLite 16.5.0 right after the first launch):
![CodeLite-16-5-0-language-server-settings](https://user-images.githubusercontent.com/34160838/197411466-99fbd05e-fe54-4694-b542-4f0da9bc354f.png)

For comparison, freshly installed CodeLite 16.4.0 right after the first launch:
![CodeLite-16-4-0-language-server-settings](https://user-images.githubusercontent.com/34160838/197411475-1874f46a-c44f-42ee-a5c4-7e022bc3601a.png)

### Version

16.5.0

### Operating system

Windows 10

### Steps to reproduce

1. Launch CodeLite.
2. Make sure that the built-in LanguageServerPlugin plugin is enabled. If it is not, enable it and restart CodeLite.
3. Go to Plugins > Language Server > Settings.
4. Click the "Scan..." button. Then look at the list of language servers found by CodeLite and see that the bundled clangd language server is not listed there.
5. Depending on whether you installed CodeLite 16.5.0 cleanly or with your previous settings, you may also notice that the bundled clangd language server is not present in the "Available Language Servers" section either.

**Comment by eranif** [comment]
FYI: we do plan on removing this binary from our distribution
I have fixed this. But you should install clangd as described here:

https://docs.codelite.org/getting_started/windows/#common

Installing the package: `mingw-w64-clang-x86_64-toolchain` will make sure you have the latest `clangd` on your machine
