### ISSUE TITLE
[Feature Request]: Adding fix-it support to LSP

### ISSUE THREAD

**Issue by Jarod42** [eranif/codelite#3095]
As discussed https://codelite.org/forum/viewtopic.php?p=20135

Enrich LSP (language Support Protocol) support with "fix-it" (as provided by clang-tidy) would be nice.

I seems it would be related to [code action](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeAction).

**Comment by eranif** [comment]
![lsp-apply-fix](https://github.com/eranif/codelite/assets/3677711/f6d864ce-2a58-4fbb-abdf-24f3dce0274e)
