### ISSUE TITLE
[Feature Request]: Output view on left with selected content in the center

### ISSUE THREAD

**Issue by rossanoparis** [eranif/codelite#3096]
It would be useful being able to realise a layout capable to keep on left the "Output view" and in the center the content of related selected tab. 
With such feature the space on screen would be better used, thus avoiding to move continuously window splitters

![image](https://user-images.githubusercontent.com/33904565/198817690-82015126-1cc9-45a0-a169-46542b40813c.png)

Best regads
Rossano

**Comment by eranif** [comment]
What's stopping you from docking your windows that way?

**Comment by hobbitdev** [comment]
That's the way I normaly use, yet what I meant is something different ...
For instance, how could I detach the output tab and dock it in the center as it was a normal code document.

here is an example of what I meant
![image](https://user-images.githubusercontent.com/33904565/198841798-333dd64d-0227-46d9-8a17-c6f85cd4d559.png)

Anyway it doesn't matter it was only an attempt ... 
Thank you for your time

Regards
Rossano

**Comment by rossanoparis** [comment]
...
