### ISSUE TITLE
[Question] How to set nice level when running project? 

### ISSUE THREAD

**Issue by Simbi0z** [eranif/codelite#3097]
Is there a permanent way of setting the nice level of the generated executable when running it?
I put `nice -n num` before  `$(WorkspacePath)/build-$(WorkspaceConfiguration)/bin/$(OutputFile)` in "Executable to Run/Debug" but the program does not run and I get an error.
OS: Linux

Thanks

**Comment by Simbi0z** [comment]
How would you accomplish this on a linux machine without having to manually run the executable from a command line? So as if I press Ctrl+F5 it runs the executable with the desired nice level.

**Comment by eranif** [comment]
You need to set the "nice" as the command and make the remainder as the command arguments
