### ISSUE TITLE
[Bug]: Outline view is unreadable - bad colors

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#3099]
### What happened?

[Bug]: Outline view is unreadable

Bad colors makes it almost impossible to see the light grey font on the slightly more light grey background.

Switching between themes does not seem the have any effect on the outline view colors..

Seen on latest master - debug build on latest Archlinux

### Version

Self compiled

### Operating system

Linux

**Comment by uffejakobsen** [comment]
The `Language Server` tab in `Output View` has the same problem - the timestamps on each line are almost the same color as the background.

**Comment by uffejakobsen** [comment]
More details:

This problem is seen on Linux with nativebook

When using nativebook adjustment of the custom base color is disabled

Modifying CL to allow adjusting the custom base color for nativebook actually works and solves this problem...

I do not know the exact reason for preventing adjustment of custom base color for native book.
Will you accept a patch for this ? this would surely solve this problem and seems to work ok.

**Comment by eranif** [comment]
screenshot?

**Comment by eranif** [comment]
can you also provide a screenshot of the background CodeLite? (preferably with some open files)

**Comment by uffejakobsen** [comment]
Sure :+1: 

PS: selected theme is called "RecognEyes"

![screen-2022-12-04-12-59-16](https://user-images.githubusercontent.com/3018239/205489362-100da059-7454-46cf-a637-04e52a2cdaee.jpg)
