### ISSUE TITLE
[Bug]: Colors and Fonts / Editor colors / Use custom base color - option is disabled

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#3101]
### What happened?

The checkbox in "Colors and Fonts / Editor colors / Use custom base color"  is disabled and cannot be enabled.
Thus it is impossible to adjust the editor base color

Seen with CL-16.5.0 (Archlinux)

### Version

Other

### Operating system

Linux

**Comment by eranif** [comment]
This was never enabled for Linux builds by default. In order to enable it, you will need to build CodeLite with 
`-DWITH_NATIVEBOOK=0`

**Comment by uffejakobsen** [comment]
Thanks for your answer

Well I'm sure that it was active at one point - maybe many years ago..
I've never messed with define `-DWITH_NATIVEBOOK` - so maybe it at one point had other defaults on Linux ?

Help text on `WITH_NATIVEBOOK` states:  use native Notebook on GTK (otherwise, use the default custombook)

I'm not that deep into WxWidgets - what is the difference between native notebook and custombook ?

**Comment by eranif** [comment]
Native book uses GTK3 tab control as defined by your theme, while the non-nativebook uses a tab control that I have implemented and used (by default) on Windows/macOS

**Comment by uffejakobsen** [comment]
Ok  -thanks for explaining :+1: 

Out of interest what is the reason for using a custom tab control on Windows/MacOS ?
