### ISSUE TITLE
[Question] Horizontal mouse wheel scrolling in sway (wayland-Linux)

### ISSUE THREAD

**Issue by Simbi0z** [eranif/codelite#3103]
¿Does horizontal mouse wheel scrolling works for you? I am running codelite in native wayland with sway compositor.

**Comment by eranif** [comment]
You should probably compare CodeLite to other wxWidgets based application (usually, the samples that comes with wxWidgets are good) and see if it works there

**Comment by eranif** [comment]
I see what you mean: placing the mouse pointer on top of the horizontal scrollbar and scrolling the button does indeed execute vertical scrolling. Is this what you mean?
