### ISSUE TITLE
[Bug]: FSW Workspace "Refresh" Icon operation is not identical to "Refresh" in context menu

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#3108]
### What happened?

[Bug]: FSW Workspace "Refresh" Icon operation is not identical to "Refresh" in context menu

The "Refresh" Icon in the Workspace dock does perform the same operation as "Refresh" in the context menu (right click) - also in the Workspace dock...

Selecting "Refresh" in the context menu will refresh the file tree with respect to new and  deleted file, dirs etc...
Hitting the "Refresh" Icon in the Workspace docs - won't perform the same - honestly I do not really know what is does...

### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
I just checked the code, in fact, clicking the `Refresh` icon in the small toolbar, will do the exact same thing as the context menu. 
As you can see in this line:
https://github.com/eranif/codelite/blob/master/Plugin/clFileSystemWorkspaceView.cpp#L174

It will call `clTreeCtrlPanel::OnRefresh(event);` (which is the handler for the context menu).

I suspect that the difference is that when clicking the button, you must have a selected folder or file first in the tree view

**Comment by eranif** [comment]
I did small change here, the new behavior is:
- Choosing the "Refresh" from the context menu, refreshes the selected folder(s)
- Clicking the "Refresh" button, refreshes the entire view, unconditionally

**Comment by uffejakobsen** [comment]
Thanks that sound like the right approach - will pull and it test now :+1:
