### ISSUE TITLE
[Bug]: codelite quit unexpectedly on MacOS Ventura 13

### ISSUE THREAD

**Issue by rababahm** [eranif/codelite#3109]
### What happened?

I have installed Codelite 16.1 and followed all the instructions as per the codelite.org .  However I receive this message when trying to open it. codelite quit unexpectedly.I am using MacOS Ventura 13.0.1.  the details are here:

First step to install codelite  is 

> _brew unlink libssh_ 

as per https://docs.codelite.org/downloads/download/#macos. when I tried to unlink the libssh, I have got this message 

> "_No such keg: /opt/homebrew/Cellar/libssh"._

However o have managed to install codelite, but when trying to open it I got this message "codelite quit unexpectedly ", and when trying to open it through the terminal, I get this message: 

> /Applications/codelite.app/Contents/MacOS/codelite-terminal.app/Contents/MacOS/codelite-terminal ; exit;
> mohammad@mohammads-macbook-air ~ % /Applications/codelite.app/Contents/MacOS/codelite-terminal.app/Contents/MacOS/codelite-terminal ; exit;
> dyld[30169]: Library not loaded: /opt/homebrew/opt/pcre2/lib/libpcre2-32.0.dylib
> Referenced from: <6AB17E22-F9CD-3741-B50A-08185674310B> /Applications/codelite.app/Contents/MacOS/codelite-terminal.app/Contents/MacOS/libwx_osx_cocoau-3.2.0.1.0.dylib
> Reason: tried: '/opt/homebrew/opt/pcre2/lib/libpcre2-32.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/pcre2/lib/libpcre2-32.0.dylib' (no such file), '/opt/homebrew/opt/pcre2/lib/libpcre2-32.0.dylib' (no such file), '/usr/local/lib/libpcre2-32.0.dylib' (no such file), '/usr/lib/libpcre2-32.0.dylib' (no such file, not in dyld cache)
> zsh: abort
> 
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.
> 
> [Process completed]
> 

### Version

Other

### Operating system

macOS

**Comment by eranif** [comment]
this is now fixed with this commit:
14615ca393b8c4175e6c174d3ae680b7cdc949a6

**Comment by eranif** [comment]
I have updated the brew repo, please try again

**Comment by rababahm** [comment]
Thank you! I have tried to reinstall and i haven’t got any errors, so it seems it works just fine.

**Comment by eranif** [comment]
Thanks for confirming this
