### ISSUE TITLE
[Bug]: Problem with new (MacOS compat) tab navigation 

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#3111]
### What happened?

[Bug]: Problem with new (MacOS compat) tab navigation 

The new MacOS compatible tab navigation seems to have introduced some new bugs

after I updated to latest master:

Previously a user could cycle between recent tabs in both forward and backwards direction
Using key combinations CTRL-TAB and CTRL-SHIFT-TAB

Currently CTRL-TAB does not work on linux - but CTRL-SHIFT-TAB does

### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
I did check this on Linux and it does seems to work
What happens when you reset the keyboard shortcuts?

`settings -> preferences -> keyboard shortcuts`

**Comment by uffejakobsen** [comment]
I tried your suggestion resetting key shortcuts to defaults

Now neither CTRL-TAB or CTRL-SHIFT-TAB works - none of them will cycle/shift to other source tabs... the recent file/tab windows does simply not show up...

**Comment by eranif** [comment]
what is the shortcut set for these actions? (you can see it in the keyboard shortcut dialog)

**Comment by uffejakobsen** [comment]
There is only one... (and it is not working)

```
CTRL-TAB     Tab | Show Recent Tabs Dialog
```

**Comment by eranif** [comment]
Do you have an entry in the menu bar: `Search -> Tabs` ?

**Comment by uffejakobsen** [comment]
Yes there is an entry called 'Show Recent Tabs Dialog` in menu bar `Search -> Tabs`

But is does not show the shortcut that the keyshortcut config has registered

**Comment by eranif** [comment]
The problem is that for some reason (I assume its wxWidgets bug), CodeLite is unable to set a menu entry for `Ctrl-TAB`. Removing the menu entry all together `Search -> Tabs` fixes the problem.
You can still edit the shortcut itself from `Settings -> Keyboard shortcuts...` dialog

**Comment by eranif** [comment]
I was able to reproduce this issue using wxWidgets minimal sample and opened a bug

https://github.com/wxWidgets/wxWidgets/issues/23014
