### ISSUE TITLE
[Bug]: Can't run my program on Codelite MacOS???

### ISSUE THREAD

**Issue by nabihamo** [eranif/codelite#3113]
### What happened?

Hi,
I've been trying to run my program on Codelite however whenever the terminal opens up I don't see my program being executed, instead I get this message:

/tmp/codelite-exec.sh ; exit;
nabiha_w@Wahibs-MacBook-Air ~ % /tmp/codelite-exec.sh ; exit;
/tmp/codelite-exec.sh: line 3: cd: /Users/nabiha_w/Downloads/set1/build-macOS/lib: No such file or directory
Hit any key to continue...

Not sure what the issue is. Has anyone had this happening before? And how did you solve this? Been searching and looking everywhere for help but I can't seem to find anything.

### Version

16.0.0

### Operating system

macOS

**Comment by eranif** [comment]
please provide steps to reproduce this

**Comment by eranif** [comment]
No response, closed
