### ISSUE TITLE
Codelite on macOS Ventura (13.1) doesn't find lldb

### ISSUE THREAD

**Issue by prosass83** [eranif/codelite#3118]
Codelite 16.7.0
macOS Ventura (13.1)
xcode installed
llvm@15 available on /usr/local/opt

Codelite doesn't give the option to use lldb as a debugger

**Comment by eranif** [comment]
We no longer support `lldb` directly.

Instead, you need to install `lldb-vscode`  as described [here][1]
And then set `lldb-vscode` as your debugger in the project settings

[1]: https://docs.codelite.org/plugins/dap/#lldb-vscode
