### ISSUE TITLE
[Bug]: wx-config --labs 

### ISSUE THREAD

**Issue by TingGood** [eranif/codelite#3120]
### wx-config --libs issue?

Linker set $(shell wx-config --libs) when project build it output 
"-LD:/wxWidgets-3.2.1/lib/gcc_lib -pipe -lwxmsw32u_xrc -lwxmsw32u_webview -lwxmsw32u_html -lwxmsw32u_qa -lwxmsw32u_adv -lwxmsw32u_core -lwxbase32u_xml -lwxbase32u_net -lwxbase32u"

build.cfg show on blow:

WXVER_MAJOR=3 
WXVER_MINOR=2 
WXVER_RELEASE=1 
BUILD=release 
MONOLITHIC=0 
SHARED=0 
UNICODE=1 
TOOLKIT=MSW 
TOOLKIT_VERSION= 
WXUNIV=0 
CFG= 
VENDOR=custom 
OFFICIAL_BUILD=0 
DEBUG_FLAG=1 
DEBUG_INFO=default 
RUNTIME_LIBS=dynamic 
USE_EXCEPTIONS=1 
USE_RTTI=1 
USE_THREADS=1 
USE_AUI=1 
USE_GUI=1 
USE_HTML=1 
USE_MEDIA=1 
USE_OPENGL=1 
USE_QA=0 
USE_PROPGRID=1 
USE_RIBBON=1 
USE_RICHTEXT=1 
USE_STC=1 
USE_WEBVIEW=1 
USE_XML=1 
USE_XRC=1 
COMPILER=gcc 
COMPILER_VERSION= 
CC=gcc 
CXX=g++ 
CFLAGS= 
CPPFLAGS= 
CXXFLAGS= 
LDFLAGS= 

why wx-config did't read this setting

### Version

16.0.0

### Operating system

Windows 10

**Comment by eranif** [comment]
1. Where is the bug?
2. ANYWAYS, this is not a bug in CodeLite but in the tool `wx-config` which **not** part of CodeLite source tree.

**Comment by iwbnwif** [comment]
I think this is the same problem that I have had with recent versions of Codelite in that the bundled wx-config has some problems. If I overwrite it with an older version then everything is fine. See #2807.

**Comment by TingGood** [comment]
> 
Thanks, I will try
