### ISSUE TITLE
A black (folder like) artefact

### ISSUE THREAD

**Issue by nullptrdevs** [eranif/codelite#3129]
openSuse Tubleweed x64
codelite 17.0.0-14-gaa5f270f8
wxWidgets from the distro's repo, 3.2.1
Xfce/KDE
![cl_artifact_Screenshot_2023-01-13_19-46-54](https://user-images.githubusercontent.com/16590917/212449504-5e4a016e-a00b-4938-956a-9549c4a52b46.png)
![cl_artifact_2_Screenshot_2023-01-13_19-54-05](https://user-images.githubusercontent.com/16590917/212449570-bce2c14b-17a3-46d4-a67e-be99881c1750.png)

**Comment by eranif** [comment]
the common to all these screenshots that the same control is used `clTreeCtrl`. I can only guess that there is a problem with the `wxDC` it uses for drawing. Can I ask you to build CodeLite with stable wx version, e.g. wx3.2.1 or wx3.2.0 ?

**Comment by eranif** [comment]
The strange thing about this, is the the workspace tree view uses the same base control, but I don't see any artifact there
