### ISSUE TITLE
Codelite 17.0 Jammy upgrades 

### ISSUE THREAD

**Issue by shyreth** [eranif/codelite#3133]
Hi Eran, first of all, congratulations for a solid effort with the release of CL 17! It's been a major upgrade in quite a lot of ways, especially as we're actively using it for a C++ university course. 

And secondly, any chance you could let us know when will the current version go live on the Jammy universe channel? 

I tried doing an upgrade and it said that Codelite is already at the newest version (16.7.0 gtk3 - installed using the .deb file from your site), so at the time I'm writing this it doesn't seem to have anything to upgrade to, unless I go ahead and try to build it from source?

Many thanks in advance!

**Comment by dghart** [comment]
It wasn't a bug; it just takes time to build the various packages.
Done now: see https://docs.codelite.org/downloads/download/#ubuntu-debian

**Comment by shyreth** [comment]
Thank you! I just received the update notification from APT install 17.0, all good now
