### ISSUE TITLE
Cannot compile C++ project successfully. (CodeLite 17.0.0)

### ISSUE THREAD

**Issue by python3xdev** [eranif/codelite#3134]
### What happened?

I've recently installed MSYS2, MINGW64 and CodeLite on my new device. CodeLite could not detect MINGW64 so I manually added it by selecting the /bin folder for it. When I build and run a project (simple hello world program), the output on the cmd/terminal is empty:

![image](https://user-images.githubusercontent.com/77379766/212760549-dceae86f-4f22-4679-b729-1e30b606d1c8.png)

And this is the build tab in CodeLite:

![image](https://user-images.githubusercontent.com/77379766/212760879-0c719d97-426c-4942-bad4-5c034b370d8a.png)

I was not able to find anything useful on google.  Maybe it has something to do with the fact that mingw64 is using mingw32-make.exe?

Here is a screenshot of my Build Settings:

![image](https://user-images.githubusercontent.com/77379766/212761294-e311f74a-23c8-4bdb-bcc1-cd84da1afe13.png)

I noticed the mkdir is empty, I didn't do anything about that, because my other device also has nothing chosen and everything is working fine there.

### Version

17.0.0

### Operating system

Windows 10

**Comment by eranif** [comment]
A workaround:

https://stackoverflow.com/questions/75097067/codelite-17-0-0-occurs-process-begin-createprocessnull-makedir-debug-f/75106995#75106995

**Comment by eranif** [comment]
Using `mingw32-make` is exactly what is needed. the  problem with the installer
See the answer I replied to someone on stackoverflow

**Comment by python3xdev** [comment]
**Thank you very much**, it works now. I don't know why that didn't appear in my search results, I googled the same part that was in the title. 

**Have a great day!**

**Comment by eranif** [comment]
I have re-opened it. Since it is still a bug... I will close it once it will get fixed

**Comment by Eric-01** [comment]
Eranif, if you're at it, could you please rename "Default" (which isn't actually the default setting anymore) to something that implies its obsolescence (e.g. "Legacy" or something similar)?

**Comment by mattreecebentley** [comment]
Just a note, 
this appears from 16.80 (at least) onwards, but not in 16.50.
Reverting to 16.50 from 17 or 16.80 removes the bug without changing the projects or compiler settings.

**Comment by eranif** [comment]
Note that this was fixed in https://github.com/eranif/codelite/issues/3134
