### ISSUE TITLE
[Bug]: codelite-terminal (Codelite 17) not working with spaces in path

### ISSUE THREAD

**Issue by ikelaiah** [eranif/codelite#3142]
### What happened?

# Issue

The codelite-terminal (Codelite 17) not working from Codelite IDE (17).

When building and running the project pressing CTRL + F9, `codelite-terminal.exe` doesn't to launch with the following output.

```
Executing: C:\Program Files\CodeLite\codelite-terminal.exe --working-directory=C:\Users\<username>\Documents\CodeLite\Classes101 --file=C:\Users\<username>\AppData\Local\Temp\CodeLite.<username>\.17160\codelite-terminal.txt --wait 
Program exited
```

However, when I copy and paste the outputted command with quotes `"` in CMD, `codelite-terminal` works fine.

```
"C:\Program Files\CodeLite\codelite-terminal.exe" --working-directory=C:\Users\<username>\Documents\CodeLite\Classes101 --file=C:\Users\<username>\AppData\Local\Temp\CodeLite.<username>\.17160\codelite-terminal.txt --wait
```

# Temporary workaround

My temporary workaround, I use `Settings | Preferences | Terminal | ` Choose `CMD`

### Version

Other

### Operating system

Windows 10

### Steps to reproduce

```text
1. Install in default location with spaces; C:\Program Files\CodeLite\

2. Set `Settings | Preferences | Terminal |` Choose `codelite-terminal`

3. Create a project using `Makefile Generator: Default`.

4. Pressing CTRL + F9, it compiles ok, codelite-terminal does not appears on screen.

5. If you get the output command and copy paste it to `CMD` quote the path with `"`, then `codelite-terminal.exe` works fine.
```

**Comment by ikelaiah** [comment]
# Alternative workaround

Do not install in `C:\Program Files\CodeLite\`. Install in a folder with no spaces.

For example, `C:\CodeLite\`. 

When build and run using Ctrl + F9, `codelite-terminal.exe` launches nicely.

**Comment by eranif** [comment]
I am planning on deprecating this terminal - too much effort to maintain it while there are other good alternatives out there. For example: `Alacritty`

**Comment by ikelaiah** [comment]
Understood. It is quite an effort to maintain. 
Thanks for all the work you put into it.
