### ISSUE TITLE
[Bug]: Installing on Arch Linux fails to retrieve dependencies. (404 not found)

### ISSUE THREAD

**Issue by Oglo12** [eranif/codelite#3145]
When I try and install Codelite on Arch Linux, it can't find the needed dependencies!

**Comment by eranif** [comment]
we dont build it for Arch linux. Where did you get it from?

**Comment by Oglo12** [comment]
> we dont build it for Arch linux. Where did you get it from?

I got it from the AUR. It works now for some reason. So, I guess they saw the issue! :-)
