### ISSUE TITLE
[Bug]: Unable to build dynamic library

### ISSUE THREAD

**Issue by jozefcifre** [eranif/codelite#3146]
### What happened?

I literally created my github account just to report this issue because I really like CodeLite and want it to work. 
The issue happened when I was trying to build an example of library but it seemed that something is missing to build the .so file. I added the header.hpp and the source.cpp, wrote a little code on them, then clicked on Build > Build Project expecting it would output libMylibrary.so file but it didn't. This is my first time trying to make a C++ dynamic library, so this problem is probably because I am doing something wrong.

Some info that you may need to know:

Project structure:
```shell
Mylibrary
├── include (virtual folder)
│   └── test.hpp
└── src (virtual folder)
    └── test.cpp
```

### Version

CodeLite 17.00 (Not self compiled)
Downloaded from here: https://repos.codelite.org/rpms-17.0/suse/15.4/codelite-17.0-1.suse.x86_64.rpm

### Operating system

OpenSUSE Tumbleweed Linux

### Steps to reproduce

```text
1. Create a New Project in your Workspace.
2. Set up: Category: Library, Type: Dynamic Library, Compiler: GCC, Debugger: GDB, Build system: CodeLite Makefile Generator.
3. Add a New File (.hpp) in include virtual folder. Write the header.
4. Add a New File (.cpp) in src virtual folder. Write the source.
5. Press F7 to Build your Dynamic Library or click on Build > Run (Ctrl + F5).
Expected terminal output (when the issue happens): 
/home/user/.codelite/tmp/user/codelite-exec.sh: line 3: /home/user/Documents/Projects/build-Release/bin/libGraphitty.so: No such file or directory
Hit any key to continue...
```

### Relevant log output
Full build log:
```shell
/usr/bin/make -j16 -e -f  Makefile
----------Building project:[ Mylibrary - Release ]----------
make[1]: Entering directory '/home/jozef/Documents/Projects/Mylibrary'
/usr/bin/g++  -c  "/home/jozef/Documents/Projects/Mylibrary/test.cpp"  -o ../build-Release/Mylibrary/test.cpp.o -I. -I.
/usr/bin/g++ -shared -fPIC -o ../build-Release/lib/libMylibrary.so @../build-Release/Mylibrary/ObjectsList.txt -L.   -O2
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../build-Release/Mylibrary/test.cpp.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make[1]: *** [Mylibrary.mk:81: ../build-Release/lib/libMylibrary.so] Error 1
make[1]: Leaving directory '/home/jozef/Documents/Projects/Mylibrary'
make: *** [Makefile:5: All] Error 2
=== build completed successfully (0 errors, 0 warnings) ===
```

**Comment by eranif** [comment]
Can you post the full build log, after "clean"?

**Comment by jozefcifre** [comment]
i will but i don't know what is that "clean", where is it? wdym

**Comment by eranif** [comment]
right click the project and then select: "rebuild" or "clean" followed by "build"

**Comment by jozefcifre** [comment]
Ok i got this output:

/usr/bin/make -j16 -e -f  Makefile
----------Building project:[ Mylibrary - Release ]----------
make[1]: Entering directory '/home/jozef/Documents/Projects/Mylibrary'
/usr/bin/g++  -c  "/home/jozef/Documents/Projects/Mylibrary/test.cpp"  -o ../build-Release/Mylibrary/test.cpp.o -I. -I.
/usr/bin/g++ -shared -fPIC -o ../build-Release/lib/libMylibrary.so @../build-Release/Mylibrary/ObjectsList.txt -L.   -O2
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../build-Release/Mylibrary/test.cpp.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make[1]: *** [Mylibrary.mk:81: ../build-Release/lib/libMylibrary.so] Error 1
make[1]: Leaving directory '/home/jozef/Documents/Projects/Mylibrary'
make: *** [Makefile:5: All] Error 2
=== build completed successfully (0 errors, 0 warnings) ===

**Comment by jozefcifre** [comment]
> right click the project and then select: "rebuild" or "clean" followed by "build"

```shell
/usr/bin/make -j16 -e -f  Makefile
----------Building project:[ Mylibrary - Debug ]----------
make[1]: Entering directory '/home/jozef/Documents/Projects/Mylibrary'
/usr/bin/g++  -c  "/home/jozef/Documents/Projects/Mylibrary/test.cpp" -gdwarf-2  -o ../build-Debug/Mylibrary/test.cpp.o -I. -I.
/usr/bin/g++ -shared -fPIC -o ../build-Debug/lib/libMylibrary.so @../build-Debug/Mylibrary/ObjectsList.txt -L.
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: ../build-Debug/Mylibrary/test.cpp.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make[1]: *** [Mylibrary.mk:81: ../build-Debug/lib/libMylibrary.so] Error 1
make[1]: Leaving directory '/home/jozef/Documents/Projects/Mylibrary'
make: *** [Makefile:5: All] Error 2
=== build completed successfully (0 errors, 0 warnings) ===
```

**Comment by eranif** [comment]
the issue is simple: you need to set `-fPIC` in the compile options (in the project settings)
the error message is very clear ;)
