### ISSUE TITLE
Run (CTRL+F5 shortcut) won't work after Build (F7 shortcut) in version 17.1.0 [Bug]: 

### ISSUE THREAD

**Issue by DaGiHu** [eranif/codelite#3152]
### What happened?

If mouse focus is in any tab of Output Pane and Build is invoked pressing F7, CTRL+F5 won't work afterwards to run the program.

Sometimes it also happens when focus in a open file source code tab. F7 works but cursor dissappear from the editor and CTRL+F5 won't run. It ran fine in previous versions.

Build / Run sequence works right if done by clicking on the menus instead of keyboard operation.

### Version

Other

### Operating system

Windows 10

### Steps to reproduce

```text
Click inside Build / Output tabs in Output Pane or in a source code tab. Press F7 to build the current project and after that, press CTRL+F5. The compiled program won't run.

If F7 is pressed and a mouse click is done in any pane or editor tab, CTRL+F5 works fine.
```

**Comment by eranif** [comment]
this seems to be related to a focus issue when nothing is in the build tab (or references tab or ...)
in these cases, the entire keyboard shortcuts are not working

clicking inside the editor or tree view (or anything with something to select) fixes the issue

**Comment by DaGiHu** [comment]
That is the misleading issue in Codelite UX, being unable to run a global keyboard shortcut depending on arbitrary location of focus in the app, One rarely find this limitation in most applications.

I look forward for you to implement global shortcuts in the future.

As usual, I thank you for you incredible work on Codelite.

**Comment by eranif** [comment]
You will notice that this bug was fixed with a commit... (i.e. a fix is available) this is why the issue is closed
