### ISSUE TITLE
Show/Hide Main Toolbar[Feature Request]: 

### ISSUE THREAD

**Issue by DaGiHu** [eranif/codelite#3156]
Main Toolbar to be visible on user request.

I propose to add a checkmark menu item just before _Menu > Main ToolBar Orientation_ as **Show Main ToolBar**.

Thank you.

**Comment by yunkot** [comment]
I would also request this feature as the main toolbar occupies quite some screen space and for some people, myself included, is unnecessary. It would also be consistent with other toolbars, the visibility of which can be controlled.
