### ISSUE TITLE
Alt key as a standard 'show menu' function [Feature Request]: 

### ISSUE THREAD

**Issue by DaGiHu** [eranif/codelite#3158]
Many programs like Firefox browser or Notepad++ among others, keep the main menu hidden because full screen mode or as a user option.

Those programs allow the semi-standard, growing practice of using Alt key release event to show/hide the menu, This only happens if no other key (a shortcut) has been pressed during Alt key down state.

**View > Full Screen** option is a great feature in CodeLite that I use as my default way to work on the IDE because the unobstructed, clean and productive interface it provides but it feels kind of old fashioned not showing the main menu on Alt key release. It is great CodeLite remembers the _Full Screen mode+hidden main menu_ next time the program is started, so please keep this if you implement my new request : )

Please, take a look at Firefox, Notepad++ or even VSCode on fullscreen mode to see how Alt operates.  I use those in Win10.

Thank you.

**Comment by DaGiHu** [comment]
![image](https://user-images.githubusercontent.com/37019540/220072681-30266cca-000d-4898-b119-4a6411c95a3c.png)

The view I propose. Thanks.

**Comment by eranif** [comment]
I too like this, but however, using a cross platform menu to do this requires to implement a complete generic menu.
Too much of an effort

**Comment by DaGiHu** [comment]
I absolutely understand your reply. My contribution is just to help improving Codelite to the current standards.
Thank you.
