### ISSUE TITLE
[Question]: FSW: Workspace tree dir/filenames has light grey text color - what does it mean ?

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#3162]
### What happened?

Hi,

Question: I have one FSW project where the workspace tree shows dirs/filenames with a light grey text color - what does it mean ? (Other FSW projects shows dirs/filenames with black text color)

See with latest CL (not a new problem - it has been like this for some time now)

### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
The light folders with light grey ("disabled") colour & image are folders that in 99% of the cases are not interesting to the user.
For example, hidden folders like `.git` or `.codelite`. Build directories, these are folders with `CMakeCache.txt` files inside them.

I need to check the code for more heuristics that I implemented

**Comment by uffejakobsen** [comment]
Update:
Based on your feedback I looked through dirs/files in the "troubled" project
And I did find a stray CMakeCache.txt in the root dir of my local repo extract.
It was initially overlooked by me because it was mentioned in .gitignore - and hence it would not show up in various git status queries for untracked/stray files.

Thanks a lot for your hint - I'm closing this issue :-)
