### ISSUE TITLE
C++ header files won't compile [Bug]: 

### ISSUE THREAD

**Issue by DaGiHu** [eranif/codelite#3163]
### What happened?

Header .hpp files changes are ignored by compiler in c++ project.

A header file can hold errors or even be emptied and after saved, build action won't detect any error.
Only Rebuild Project will detect the errors.

In version 17.1.0.

### Version

Other

### Operating system

Windows 10

### Steps to reproduce

```text
In a c++ project go to a header file, provoke an error in the code or empty its contents.
Save and Build project; errors won't show up.

Rebuild Project and errors will be apparent.
```

**Comment by DaGiHu** [comment]
A modified .hpp file won't compiler either if **Compile** in its Workspace properties is clicked.
It's always reported as "up to date",

**Comment by eranif** [comment]
- `Settings -> build settings -> Compilers` tab
- Choose your compiler
- Choose the `Advanced` tab
- Check the option `Generate dependencies files`

**Comment by DaGiHu** [comment]
The checkbox is disabled. I cannot set that option on.

![image](https://user-images.githubusercontent.com/37019540/221404625-f5bd6b2d-300b-406b-8f8f-8a668710944d.png)

**Comment by eranif** [comment]
according to the code, this can happen when using non compatible GNU compiler...

```c++
m_checkBoxGenerateDependenciesFiles->Enable(m_compiler->IsGnuCompatibleCompiler());
```
which compiler are you using?
