### ISSUE TITLE
Remember last scroll position in code tabs [Feature Request]: 

### ISSUE THREAD

**Issue by DaGiHu** [eranif/codelite#3165]
Every time CodeLite starts loading the last workspace, each code tab is shown starting from line 1. This is kind of misleading when the coder return to review a project with a lot of intertwined code tabs.

For convoluted projects with a lot of code tabs visible in the workspace, is so convenient the editor to remember the last topmost line position for each tab. Most IDEs and advanced text editors does this by default (vscode, notepad++, etc). I'd almost say it is a standard among this kind of software.

My request is to include this feature in CodeLite.

Thank you very much.

**Comment by eranif** [comment]
I am not following: do you mean to remember it when CodeLite reloads the last session?

**Comment by DaGiHu** [comment]
Thanks a lot for implementing this. Working with CL is even great now.
