### ISSUE TITLE
[Bug]: wrong quoting of mkdir in 17.1

### ISSUE THREAD

**Issue by Jarod42** [eranif/codelite#3167]
### What happened?

As state in https://codelite.org/forum/viewtopic.php?p=20340#p20340

> In build settings I have
>
> -- 8< --
> Make: C:/msys64/mingw64/bin/mingw32-make.exe
> Mkdir: C:/msys64/usr/bin/mkdir.exe -p
> -- >8 --
>
> Since 17.1, generated Makefile quotes mkdir resulting in error ("C:/msys64/usr/bin/mkdir.exe -p" -> file not found).

### Version

Other

### Operating system

Windows 11

### Steps to reproduce

```text
- Change in "Build settings..."

'Mkdir: C:/msys64/usr/bin/mkdir.exe -p'

- run a compilation with selected compiler

message telling that "C:/msys64/usr/bin/mkdir.exe -p" cannot be found.
and indeed, in makefile it is the whole string which is quoted, whereas it should be used as-is (user might add quote if needed).
```

**Comment by eranif** [comment]
which makefile generator are you using? from reading the code, I would guess that you are using the "default". Am I correct to assume this?

**Comment by eranif** [comment]
fixed
