### ISSUE TITLE
[Bug]: "Goto declaration" and "Goto implementation" missing / broken

### ISSUE THREAD

**Issue by kroll-j** [eranif/codelite#3172]
### What happened?

Previous versions of Codelite (15?) had "Goto declaration" and "Goto implementation" in the editor context menu, which would jump to the declaration/implementation of a symbol. In version 17.0.0, the context menu entries are gone. There is "Find symbol", which seems to jump randomly to declaration or implementation. 

The action "Goto declaration" is still available as a keyboard shortcut. When executing it, nothing happens in the GUI, and in the logs, I see the attached output.

### Version

Other

### Operating system

Linux

### Steps to reproduce

```text
Bind action "Goto declaration" to a keyboard shortcut.
Press the keyboard shortcut.
```

### Relevant log output

```shell
==> /home/user/.codelite/codelite.log <==
[11:14:30:747 DBG] [Main] [clangd] FindDeclaration() is called
[11:14:30:748 DVL] [Main] [clangd] No changes detected in file: /mnt/scratch/src/codelite/AutoSave/autosave.h
[11:14:30:748 DBG] [Main] [clangd] Sending GotoDeclarationRequest

==> /home/user/.codelite/codelite-lsp.log <==
[**STDERR**]I[11:13:14.547] --> reply:textDocument/definition(35) 0 ms

************
Content-Length: 188

{"jsonrpc":"2.0","method":"textDocument/declaration","params":{"textDocument":{"uri":"file:///mnt/scratch/src/codelite/AutoSave/autosave.h"},"position":{"line":37,"character":29}},"id":36}
==> /home/user/.codelite/codelite.log <==
[11:14:30:748 DVL] Wrote message of size: 211

==> /home/user/.codelite/codelite-lsp.log <==
[**STDERR**]I[11:14:30.748] <-- textDocument/declaration(36)

************
Content-Length: 177

{"id":36,"jsonrpc":"2.0","result":[{"range":{"end":{"character":36,"line":37},"start":{"character":31,"line":37}},"uri":"file:///mnt/scratch/src/codelite/AutoSave/autosave.h"}]}
==> /home/user/.codelite/codelite.log <==
[11:14:30:748 DBG] [Main] Received data from LSP: 200 bytes
[11:14:30:748 DVL] [Main] -- LSP: Message Method is: 
[11:14:30:749 DVL] [Main] [clangd] received a response
[11:14:30:749 DVL] [Main] GotoDeclarationRequest::OnResponse() is called
[11:14:30:749 DVL] [Main] [{
  "range": {
   "end": {
    "character": 36,
    "line": 37
   },
   "start": {
    "character": 31,
    "line": 37
   }
  },
  "uri": "file:///mnt/scratch/src/codelite/AutoSave/autosave.h"
 }]
[11:14:30:749 DVL] [Main] Unable to read JSON payload
```

**Comment by yunkot** [comment]
I also recall that these options existed. I do use "Find symbol" quite often, but it does seem to be somewhat inconsistent - sometimes it jumps to implementation, sometimes to declaration in the header. It would be nice if such option would at least work consistently - first jump to declaration, then for 2nd time jump to implementation, and/or vice-versa.

**Comment by eranif** [comment]
This is how `clangd` works:

- If you choose `Find symbol` while on a reference -> it will take you to the implementation (but it only if clangd already seen it), otherwise it will take you to the declaration of the method
- If you choose `Find symbol` while on the method **implementation** it will take you to the definition

It's pretty consistent

**Comment by yunkot** [comment]
I think at least once it didn't jump on implementation for me, but now that I'm trying, can't reproduce it anymore. Curiously, using "Find symbol" on an abstract C++ class function, it opens a "Select Symbol" dialog, which is empty, but you can still press "OK" and it will center the view around the same abstract symbol, where you clicked.

**Comment by eranif** [comment]
Yes, this is a bug... clangd does not provide a "preview", so CodeLite should be able to fetch these
Can you open this as a separate issue?
