### ISSUE TITLE
File directory not found

### ISSUE THREAD

**Issue by Ashosha1** [eranif/codelite#3182]
I am new programming on c++ using codelite with gcc compiler and gnu  gdb  debugger Mac M1. I encountered the following error

Last login: Tue Apr  4 02:28:03 on ttys002
/tmp/codelite-exec.sh ; exit;
ashos@Aiss-MacBook-Air-66 ~ % /tmp/codelite-exec.sh ; exit;
/tmp/codelite-exec.sh: line 3: cd: /Users/ashos/Documents/Codelite/ProgrammingFundamentals/build-Debug/lib: No such file or directory
Hit any key to continue...

**Comment by eranif** [comment]
Use `lldb-vscode` on macOS. Not gdb
