### ISSUE TITLE
[Bug]: The bootstrap Wizzard (Setup compilers)  has a wrong text / missing features

### ISSUE THREAD

**Issue by winspool** [eranif/codelite#3183]
### What happened?

When i start Codelite, the Wizzard starts, but the compiler setup is broken:

The text "Let CodeLite configure your installed compilers or help you install one"
in the Wizzard suggest:
* that CodeLite can configure an installed compiler
  That will never happen: There is no button for such a job
  And that should never happen: An ide should never change startup scripts or my environment.
* that i can use CodeLite to install a new compiler
  That will never happen. There is no button for such a job
  My Linux system has a package manager for installing software

CodeLite finds clang, gcc/g++ and gcc cross compiler,
but there is no button to let me select a different compiler:

Where is the Tiny C Compiler? either as tcc (native) or the many available cross compiler.
(tcc is very fast, can cross compile, runs on linux/osx/windows but does only minimal optimizations)
(tcc uses posix command line options similar to gcc)

Where is OpenWatcom-v2 C/C++ Compiler? (Old, but can cross compile and runs on many systems)
(owcc: uses posix command line options, similar to gcc)
(cl.exe: uses command line options similar to msvc)

### Version

Other

### Operating system

Linux

### Steps to reproduce

```text
Just run the configuration wizzard.

My codelite is 17.0.0, but that version is not available in the version list.
```

### Relevant log output

```shell
Codelite has no output on the console
```

**Comment by eranif** [comment]
its accurate. it will configure the compilers **within** CodeLite.
It will help you install one (mainly needed on windows)

to configure an existing compiler, you can do this later from settings -> build settings -> compilers
