### ISSUE TITLE
[Bug]: Update notification for wrong branch

### ISSUE THREAD

**Issue by Klimmbimmel** [eranif/codelite#3187]
### What happened?

I decided for the stable branch and I get an update notication on every start. I can turn off update checking in general, but that's not the right solution

I consider this a bug.

Using v17.0 stable

### Version

Other

### Operating system

Windows 10

### Steps to reproduce

```text
Install stable
Run it
```

**Comment by eranif** [comment]
which OS? I tried with Windows and it works

**Comment by mh-tp** [comment]
Windows as the bugreport sais. At least when using "Help -> Check for updates..." it reproduces it for me
