### ISSUE TITLE
[Bug]: Trim Trailing Spaces (Edit menu) does not work

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#3188]
### What happened?

[Bug]: Trim Trailing Spaces function in Edit menu does not work

If I load a file with trailing spaces and use Trim Trailing Spaces function in Edit menu - nothing happens

Seen on CL-17.3.0

### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
Just tried this. Seems to work. (Windows 10)

**Comment by uffejakobsen** [comment]
Well I guess that your settings saves you

Here is a description:

With these settings - do the following:

![screen-2023-05-01-14-17-24](https://user-images.githubusercontent.com/3018239/235461215-befd6536-ccc9-4a29-8996-cc1d57036c0c.jpg)

1) Introduce trailing spaces into a file from another editor
2) open up the file within CL 
3) select  Trim Trailing Spaces function in Edit menu (do *not* edit the lines with trailing spaces)
4) try to save the file (there is nothing to save - and the externally introduced trailing spaces are still in the file)

**Comment by eranif** [comment]
Yes, this is why I asked. By enabling the bit "trim modified lines only" -> it will not work (since these lines are not marked as "modified" in CodeLite).

IIRC, the "Save" command simply triggers the menu option.
One option is to decouple the two and always trim when using the menu.
Any other suggestions?

**Comment by uffejakobsen** [comment]
I'll vote for decoupling the two and always trim when using the menu - the menu is a separate function that the users manually has chosen to apply on the file.

Also that is what other editors do - I think that most users (including me) would expect that...
