### ISSUE TITLE
Error with configuring MinGW on CodeLite 17.2.0

### ISSUE THREAD

**Issue by jeanftw** [eranif/codelite#3189]
### What happened?

First. Every time I open the app it keeps getting the default configuration.
Second. When I try to add MinGW as a compiler, the app just closes.

### Version

Other

### Operating system

Windows 10

### Steps to reproduce

```text
I start CodeLite, then I got to Preferences/Build Settings, after this I click on the "+" symbol and setup the bin directory of MinGW. Till this point, everything goes as it should, but once I click "Select Folder" the CodeLight app just closes itself and once I run it again no changes were taken
```

**Comment by eranif** [comment]
This sounds like as if CodeLite crashed.
Can you tell me which CodeLite version are you using? (Help -> About)

**Comment by jeanftw** [comment]
I have installed the latest version 11 on my pc

**Comment by eranif** [comment]
This is GCC version.
If you go in CodeLite menu bar: Help -> About you will get CodeLite's version number

**Comment by jeanftw** [comment]
![image](https://user-images.githubusercontent.com/132067388/236123429-1a38e330-1290-45c6-96be-ed6e7d12319a.png)

**Comment by eranif** [comment]
this should be fixed now
