### ISSUE TITLE
[Bug]: Open Include File not working

### ISSUE THREAD

**Issue by XaVieR375** [eranif/codelite#3191]
### What happened?

When I highlight an include and click Open Include File "Filename" to view the header file, nothing happens. No file tab is NOT opened. I would like to be able to view some of the C++ standard header files.

![OpenIncludeFileNowWorking](https://user-images.githubusercontent.com/67128892/236290832-8c9a3ddd-2601-4557-a67c-28c0ee57ee60.png)

^ Fix needed.

### Version

Self compiled

### Operating system

Windows 10

### Steps to reproduce

```text
Highlight an include header and click open include file.
```

**Comment by BillKek** [comment]
Funny enough, a similar action "Open Include File" on C lib-header opens it, but along a completely different path. In Windows PATH and in Project and Compiler settings the paths are set to mingw32, but it opens on mingw64. It is not clear where it gets the path to mingw64 from. Search Path of Workspace is empty.

**Comment by eranif** [comment]
This works fine for me. Can you please check the following:
`Settings -> Plugins -> Language Server -> Settings` and check which servers are installed AND enabled?

**Comment by XaVieR375** [comment]
> This works fine for me. Can you please check the following: `Plugins -> Language Server -> Settings` and check which servers are installed AND enabled?

All I see is clangd
![InstalledAndEnabledServers](https://github.com/eranif/codelite/assets/67128892/661e421d-3e38-45eb-8a69-a9be7b350b63)

**Comment by eranif** [comment]
which version is this? we no longer provide this clangd executable
- Uninstall CodeLite (make sure that the folder is removed completely)
- [Download and Install 17.4.0](https://downloads.codelite.org/downloads.php?windows_weekly_64)
- CodeLite should locate your `clangd`, if non exists, setup the environment [as described here](https://docs.codelite.org/getting_started/windows/)
