### ISSUE TITLE
[Bug]: Code navigation with "Mouse left button and... Control Key" ignored

### ISSUE THREAD

**Issue by buergi** [eranif/codelite#3194]
### What happened?

Actually the issue is identical with #1113, but I didn't want to warm up such an old issue.
In Codelite 17.0.0 when Code navigation keys in Preferences > Code > Mouse left button and: is set to `Alt Key` or `Ctrl Key and Alt Key` the code navigation is working as expected, however when only `Ctrl Key` is selected hovering tokens with Ctrl key held does not underline them, and they cannot be clicked on, instead multiple cursors are set to the clicked positions.
When holding Ctrl + Alt while hovering it works, although only `Ctrl Key` is configured.

### Version

Other

### Operating system

Windows 10

### Steps to reproduce

```text
* Set Preferences > Code > Mouse left button and: to Ctrl Key.
* In code view hold Ctrl and hover the code => nothing gets underlined, clicking causes multiple cursors to be placed.
* Hold Ctrl + Alt while hovering => it works.
```

**Comment by eranif** [comment]
I don't think its possible to use the `Ctrl` key alone. It is hard wired for multiple carets by the entire code editor component (3rd party)

**Comment by buergi** [comment]
Hm, I'm not sure I understand your answer correctly, is this "code editor component" something new? As it used to work before:

I just tried it in CodeLite 16.0.0 with this settings
![grafik](https://github.com/eranif/codelite/assets/1948339/570c562a-987e-49de-a53d-5a06ea1476ac)
When I hold Ctrl key and hover a identifier it gets underlined
![grafik](https://github.com/eranif/codelite/assets/1948339/8213d428-5310-4e3d-b5e7-bcca4a4c749c)
and on click I get to the definition of MainWindow.

In CodeLite 17.0.0 with this settings
![grafik](https://github.com/eranif/codelite/assets/1948339/9efa2e4e-61fb-4a23-929b-8a0fba6904bb)
I need to hold Ctrl AND Alt key to get the same behaviour as above.

So in case the editor changed somehow and does not allow code navigation with Ctrl key alone, then I'd remove the option to select the Ctrl key only as code navigation, otherwise I'd love to get the old behavior back, as I actually prefer navigating with Ctrl key only.

**Comment by buergi** [comment]
@eranif do you think it makes sense to re-open the issue. As I said, it used to work. It is only broken since CodeLite 17. Or were there some underlying changes that makes it very hard to implement the CTRL-only behavior?
In the latter case, to the very least, the settings should be adapted and the "Control Key" option should be removed. However, if possible, I'd prefer to get the Control key shortcut to work.
