### ISSUE TITLE
Fresh installation through brew doesnt install the codelite terminal. 

### ISSUE THREAD

**Issue by Galus75** [eranif/codelite#3198]
### What happened?

While trying to switch terminals to codelites it didnt show up in the default options, upon further inspection using 

 /applications/codelite.app/Contents/MacOS/codelite-terminal.app/Contents/MacOS/codelite-terminal

it shows that there is no such file or directory, when looking in the directory it just does not appear. I was wondering if there was a way to install the Codelite terminal. 

Screenshot is from the codelite applications 

<img width="335" alt="Screenshot 2023-05-23 at 3 18 20 PM" src="https://github.com/eranif/codelite/assets/134441658/b5500876-8d38-4856-8522-3fff65afa4c1">

### Version

16.0.0

### Operating system

macOS

### Steps to reproduce

```text
codelite > Preferences > terminal > Choose your terminal > Only options available "Terminal, iterm2, alacritty". Codelite terminal is not an option. Nor do anyoption besides mac terminal work.
```

**Comment by eranif** [comment]
We dropped the support for `codelite-terminal`. Please other terminal
