### ISSUE TITLE
[Bug]: create new project not have default build system

### ISSUE THREAD

**Issue by heheda123123** [eranif/codelite#3206]
### What happened?

in create new project window, there only four build system option
![image](https://github.com/eranif/codelite/assets/97490782/674a3f20-d084-4930-8019-9e4518fb3a0e)
after create project, in project setting will show there have five build system option
![image](https://github.com/eranif/codelite/assets/97490782/e9482714-249f-47a3-9a0f-95b01ad11ff1)

version 17.3.0
also I was confused what is the difference between five build system , Is there any doc describe them?

### Version

Other

### Operating system

Windows 11

**Comment by eranif** [comment]
We deprecated that build system. Use `CodeLite Makefile Generator`

**Comment by eranif** [comment]
sorry closed by mistake :)

**Comment by eranif** [comment]
You should use `CodeLite Makefile Generator`
