### ISSUE TITLE
[Bug]: Menu action View / Workspace Pane does not work anymore

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#3208]
### What happened?

After the recent commits Menu-action "View | Workspace Pane" does not work anymore - neither from the menu or as a shortcut key

Seen on archlinux with CL latest master 

### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
try pulling? there was a bug in the new terminal control that it captured events while it shouldn't have...

**Comment by uffejakobsen** [comment]
That new commit made a difference - it works again - thanks :+1: :-)
