### ISSUE TITLE
[Bug]: Moving cursor up/down through code with up/down buttons very slow, causes large CPU usage

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#3210]
### What happened?

Note: more noticable on a slower laptop, but:
since (probably 17, but maybe 16, haven't compared,definitely didn't happen in 15),
just holding down/up to move the cursor through C++ code in codelite is unusually slow, causes comparitively large amounts of CPU usage (again, more noticable on slower machines).

Left/right not quite as bad.

### Version

17, non-self-compiled

### Operating system

Windows 10

### Steps to reproduce

```text
Load a C++ project.
Move cursor to middle of code somewhere.
Hold up/down.
Notice lagginess.
Turn on task manager and watch CPU while doing it.
```

**Comment by eranif** [comment]
try this:
- `Settings -> Preferences -> Guides -> Line Numbers`
- Disable the option `Highlight current line number`

**Comment by mattreecebentley** [comment]
Doesn't do anything - as in, disabling that option has no effect on line highlighting in 17.3.0

**Comment by eranif** [comment]
Can you capture a short mp4?

**Comment by mattreecebentley** [comment]
Don't have that capability sorry. 
What are you wanting to see? I could try a screenshot.

**Comment by eranif** [comment]
Another guess (that I know for fact that it affects performance):

- Settings -> preferences
- Disable the option `Use Direct2D editor drawings`
- Restart CodeLite

**Comment by mattreecebentley** [comment]
I think I figured it out (maybe) -
the above setting had no effect,
but by unplugging my laptop and going into the lower power mode, the speed decreases became more obvious, and it seems it's pausing when it hits a curly brace in C++, specifically it seems to be to do with drawing/calculating the distance to the corresponding opening/closing brace.

This is pausing on an i7 9750, so it's a significant delay for that calc/draw.

**Comment by yunkot** [comment]
Could this be related to issue #3232? I'm experiencing a somewhat similar issue when trying to use CodeLite on Raspberry PI 4: normally CodeLite is quite responsive, but in some specific C++ files it becomes quite slow, moving cursor to left - right (not just up and down), or typing text seems like a slide-show. It doesn't "feel" like it is drawing related because in another C++ file with roughly equal quantity of text it appears responsive, so I'm wondering if it has to do with clangd?

**Comment by DamienChoupaux** [comment]
I've been experience the same lags on the latest version 17.8.0 (Windows) and the performance issue seems to be related to the highlighting features in `Preferences -> Guides`, `Indentation lines` and `Matching braces` seems to be main source of those lags, disabling them seems to really improve the responsiveness of codelite while editing/moving around in the code

**Comment by eranif** [comment]
Thanks, will look into the current logic of finding highlight braces

**Comment by eranif** [comment]
This should be fixed - please verify with latest master and re-open if needed
