### ISSUE TITLE
[Bug]: output view pane takes focus and ignores shortcuts

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#3213]
### What happened?

This is a new behaviour - maybe related to the new terminal stuff that you are working on...

Inside the editor I have a (working) shortcut to toggle the Output view - it works fine.

Once I do a build the "Build" pane (and rest of the Output view) appears.

It seems that the "Build" pane in output view takes focus and eats the shortcuts

I can no longer use the existing toggle Output view shortcut - it is ignored - does not react.

I have to use the mouse to transfer focus back to the editor window by clicking inside the editor window - then the shortcut works again....

Seen on latest master (archlinux)

### Version

Self compiled

### Operating system

Linux

**Comment by yunkot** [comment]
Isn't this the same problem as #3216 that was recently fixed?

**Comment by eranif** [comment]
Yes, seems like the same bug...  @uffejakobsen can you please with the latest git master?

**Comment by uffejakobsen** [comment]
I'm on vacation at the moment so I cannot perform the exact same scenario that I created the issue from... but have done some limited tests on a git master build - and it seems to have fixed the problem... thanks

I'm closing this issue
