### ISSUE TITLE
[Bug] CodeLite loses keyboard focus after compilation completes

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#3216]
I'm getting this issue when working with C++ projects, commit 207178f192f54b8c5290079a97547e33328cca5d, running under Arch / Gnome 44.2 / Wayland / wxWidgets 3.2.2.

Steps to reproduce:
1. Open a project in CodeLite.
2. Press F7 (Build Project).
3. Wait until the compilation succeeds (subject to issue #3047) and you will see "build completed successfully" in Output View.
4. Expected: can still control CodeLite using shortcuts or arrow keys.
    Actual: none of shortcuts work, pretty much keyboard input is ignored at this point.
    Workaround: click inside CodeLite window or press Alt+Tab to get back to CodeLite.

**Comment by yunkot** [comment]
FYI, I've tried an older build from commit 2eb94e53b95f92623d6341465f83bac3bcc19bc3 and it works as expected, so it might be some kind of regression.

**Comment by yunkot** [comment]
A more recent commit that is still working correctly is 532a53d9ac60704c60708114cf9506c186e5a050, and problem appears in 865655319231856d43a238ec7c28c4275867ddbc, so regression likely occurred somewhere in between June 11, 2023 and June 19, 2023.

**Comment by yunkot** [comment]
I'm not sure if I understand the question. I'm on a fresh installation of Debian 12 / Gnome, building CodeLite in default configuration according to [build from sources](https://docs.codelite.org/build/build_from_sources) page, but using wxWidgets 3.2 from Debian repository.

**Comment by eranif** [comment]
Let me explain, why I am asking this: I looked at the commit set you mentioned and I saw focus related code, but it affects `clGenericNotebook` -> this class is not built on GTK, but you can enable it. This is why I asked

**Comment by yunkot** [comment]
After a lot of re-compilations and testing of CodeLite, the commit that introduces this issue is 44ebc566928aba3b7e1f53ec6519be59a01e7e4e. Perhaps it's not related to what you are asking?

My build process is the following:
```
git clone https://github.com/eranif/codelite.git
cd codelite && git reset --hard 44ebc566928aba3b7e1f53ec6519be59a01e7e4e
git submodule update --init --progress
mkdir build-release && cd build-release
cmake -DCMAKE_BUILD_TYPE=Release .. -DCOPY_WX_LIBS=1 -DWITH_WX_CONFIG=wx-config
make -j$(nproc) && sudo make install
```
Before running CodeLite, I remove previous ".codelite" and ".codelite" folders, and use default configuration. The only customization I do is enabling "Skip warnings" in Build Settings - Build panel, but the problem occurs independently of this checkbox setting.

**Comment by eranif** [comment]
It's exactly the commit I was looking at, mainly because of this change:

https://github.com/eranif/codelite/commit/44ebc566928aba3b7e1f53ec6519be59a01e7e4e#diff-6e36fd9fef38817b284fad1ab9331cc9515179dc002eda164185746a4a0dd5a6R547

**Comment by yunkot** [comment]
I really can't answer that as I'm not very familiar with CodeLite code base. But if there is anything else I can do to help debug this issue, please let me know.
