### ISSUE TITLE
[Bug]: CodeLite crash

### ISSUE THREAD

**Issue by Viktor-L-v** [eranif/codelite#3219]
### What happened?

OS: Windows 10 Pro 22H2
CodeLite: 17.3.0
Steps to reproduce:
1. Clean install of CodeLite
2. First start (but it repeats on next runs also)
3. Skip welcome wizard
4. Settings -> Build settings -> "+" (Add an existing compiler) -> Set path to bin folder from mingw64 from msys2 folder (D:\msys64\mingw64\bin) -> Select folder -> Set a name to the compiler (gcc-13.1.0) -> Crash

codelite.log attahed (yes, it's a full log - only 6 strings)

Path to %appdata% contains utf-8 (non-latin) symbols in username (if it's may be important)

Version of msys2: msys2-x86_64-20230526

Please write me if some more info needed
[codelite.log](https://github.com/eranif/codelite/files/12029690/codelite.log)

### Version

Other

### Operating system

Windows 10

**Comment by eranif** [comment]
I was unable to reproduce this.
Can you run CodeLite from a terminal, like this, and see if it repeats:

1. Open `MSYS2` terminal
2. From within the terminal, run:

```bash
cd /d/Program\ Files/CodeLite
./codelite -d /tmp/cache
```

3. Repeat the above steps and see if it crashes

Why am I asking you this? in the log you attached, I saw this line:

```
[17:05:03:573 ERR] [Main] Could not locate build configuration! CodeLite installation is broken this might cause unwanted behavior!
```

This suggests a problem while saving data to the user application folder
Using the `-d` instructs CodeLite to use that folder as the settings folder instead of the default one

You should be able to write into `/tmp/cache` (CodeLite will create it if it is missing)

**Comment by Viktor-L-v** [comment]
Thank you, this helped, compiler was added without crash
Temporary folder was created with all config files, but without log (is it weird?)
And why CodeLite has problem with default folder? It's my folder and I have full rights to read/write (codelite subdirectory is created by CodeLite as its own subdirectories too, and log is written)
Could there be a reason in utf-8 symbols?

**Comment by eranif** [comment]
This could explain it.. (the utf-8 symbols), can you paste your folder here path? (or something similar if you are concern with security) so I can try it locally?

OR - can you try and run it with `codelite -d /tmp/SOME-UNICODE-CHARS` and see if it crashes?

**Comment by Viktor-L-v** [comment]
I tried to run "codelite -d /tmp/<SOME-UNICODE-CHARS>" (with utf-8 symbols of course :) ) and got "Segmentation fault" after reproducing steps from first message
But was one difference: on the first start when I tried to add compiler there already was list of some default compilers and I add new one without crash: on the second run list of compilers was already empty and steps from first message led to crash

**Comment by eranif** [comment]
Can you paste me here a string with utf-8 that causes a crash so I can debug it here?

**Comment by Viktor-L-v** [comment]
Of course
"./codelite -d d:/фывапро"
For example
