### ISSUE TITLE
[Bug]: Editor caret fall behind typing

### ISSUE THREAD

**Issue by iHardRock** [eranif/codelite#3220]
### What happened?

v17.4.0 from latest master.
Ubuntu 22.04 Unity

When typing, caret fall behind entered text. Also chars may overlay each other.
Seems like text width is wider than calculated caret position. 
It leads to incorrect text insertion and deletion.  You can't set correct position even with mouse.
Sometime go to the next line with Enter helps.

![simplescreenrecorder-_2_](https://github.com/eranif/codelite/assets/8301265/629b352b-cd97-4557-8bc1-09db1f4458e9)

Another problem is line flickering when just move cursor.

![simplescreenrecorder](https://github.com/eranif/codelite/assets/8301265/feb1fdc3-6d09-4170-8e9a-603961f330cd)

### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
This part is not really handled by CodeLite but by the underlying wxWidgets library
Can you please:

- Tell me the wxWidgets version - if you don't know it, click (at the same time): `Ctrl-Alt-Mouse middle button`
- The font you are using (often, changing font fixes the problem and make sure its a monospaced font)

**Comment by iHardRock** [comment]
Latest wxWidgets from official site, compiled with 
`./configure --with-gtk=3 --prefix=/system/dev/library/wxwidgets-3.2 --enable-stl --with-liblzma`

`wxWidgets Library (wxGTK port)
Version 3.2.2 (Unicode: wchar_t, debug level: 1),
compiled at Jul  6 2023 02:10:02

Runtime version of toolkit used is 3.24.
Compile-time GTK+ version is 3.24.33.

Copyright (c) 1992-2023 wxWidgets team`

![изображение](https://github.com/eranif/codelite/assets/8301265/f21a3dd6-a9ff-4ed2-a7d4-eb75724230f1)

**Comment by eranif** [comment]
Since you built wxWidgets yourself, can you please try the `stc` sample that comes with wxWidgets?

**Comment by iHardRock** [comment]
No issues.

![simplescreenrecorder](https://github.com/eranif/codelite/assets/8301265/493d9fc6-ef62-46c1-a834-691c9bcf8c8e)

**Comment by eranif** [comment]
can you confirm that the same font is being used?

**Comment by iHardRock** [comment]
Don't know how to figure out which font used in stc example. In source code it wxFONTFAMILY_TELETYPE / wxFONTFAMILY_MODERN.

Finally I have found the reason.
Problem happens after import color and fonts settings from an older CodeLite (16.8.0 in my case).

What I have done:
1. Delete self compiled CodeLite, rename .codelite folder to .codelite_old
2. Install CodeLite from APT repository (ubuntu 22.04, CodeLite 14.0.0)
No issues. Default font was Sans, but no issues. After changing font to Monospace Regular - no issues too.

3. Remove CodeLite again, remove .codelite folder.
4. Install compiled CodeLite.
No issues. Default font is Monospace Regular.

5. Import settings ZIP file that was exported from self-compiler 16.8.0 (not exactly, but something between 16.8.0 and 17.0.0, Ubuntu 20.04 Unity, GTK2)
Problem appears.

I love Monokai color scheme, which was removed from CodeLite themes...
May you suggest proper way how to add bring this theme back?

**Comment by iHardRock** [comment]
**UPDATE**

The main reason is not related to the import!

The main reason is change font size. Default font size is 14 (Monospace Regular).
Problem appears with any theme if you change global font size.

**Comment by eranif** [comment]
try a different font, this will make the problem go away. 

About themes:

Since you are using a self compiled CodeLite, you can have many more themes, see here:
https://docs.codelite.org/settings/colours_and_fonts/#installing-new-themes

I suggest to download the `Alacritty` themes (YAML format) from here: https://github.com/alacritty/alacritty-theme/tree/master/themes

and import them into CodeLite

**Comment by iHardRock** [comment]
Please try to reproduce bug yourself by changing global font size to smaller one.

**Comment by eranif** [comment]
I did, can't make it happen here ...

**Comment by iHardRock** [comment]
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```
But shell is Unity, not Gnome 3.


![output](https://github.com/eranif/codelite/assets/8301265/81d1876e-30d6-4b36-a24c-434b855110c9)

**Comment by iHardRock** [comment]
Setting global font and size in CodeLite same as global monospace font and size in Unity settings - solves the problem.
