### ISSUE TITLE
[Feature Request]: block operations: selecting, inserting and deleting 

### ISSUE THREAD

**Issue by BIRooter** [eranif/codelite#3222]
### Describe your idea in details

Feature request description

It's useful if an IDE supports block selecting, inserting and deleting.

Kate in KDE plasma desktop provides those features.

Thansk!

**Comment by Eric-01** [comment]
Does Ctrl + Shift + LMB not meet your expectations? Do you need something else?

**Comment by Eric-01** [comment]
Does Alt + Shift + LMB not meet your expectations? Do you need something else?

**Comment by BIRooter** [comment]
Sorry: the block i mean is a rectangle, not the whole line(s)

**Comment by eranif** [comment]
@BIRooter , @Eric-01  actually answered your question:
CodeLite supports block editing...
- You can hold `Alt + Shift` while creating rectangle selection with the mouse (mouse left button)
- Holding `Ctrl` (`Cmd` on macOS) while clicking with mouse left button will create multiple carets:
  - Typing while insert text at each caret
  - Pasting will paste at each caret
- Select multiple lines (normal selection), then hit `CMD-Shift-L` (macOS) or `Ctrl-Shift-L` (Windows / Linux) - CodeLite will place a caret at the end of each line
- Select word in the editor and then hit `Ctrl-K` or `CMD-K` (macOS) -> multiple selections will appear

There are more editing tips :)

But I suspect that this answers your question

**Comment by BIRooter** [comment]
Yes, thanks for your patient! That's what I need.
