### ISSUE TITLE
[Bug]: Syntax Highlighting not applying

### ISSUE THREAD

**Issue by Nateheff** [eranif/codelite#3224]
### What happened?

My computer crashed while I was using Codelite and upon rebooting, Codelite wouldn't even open, so I uninstalled Codelite and then reinstalled it (version 17.0.0 which is the version I originally had). After reinstalling Codelite, my code looks like this (using the Atom One-Dark theme, but I tried almost every other theme and it looks more or less the same):
<img width="367" alt="Screenshot 2023-07-17 22 51 10" src="https://github.com/eranif/codelite/assets/118491146/6395b103-8bf5-4c42-b0cf-f66bd5f8dcdb">
I uninstalled the mingw-w64 compiler and installed the msys64 compiler as recommended in a solution to a similar problem. As requested in that solution, here is my compile_commands.json for the workspace:
`[{
  "file": "C:\\Users\\Nate\\Workspaces\\learning\\dbsm\\main.cpp",
  "directory": "C:\\Users\\Nate\\Workspaces\\learning\\dbsm",
  "command": "C:/msys64/clang64/bin/clang++.exe -c C:\\Users\\Nate\\Workspaces\\learning\\dbsm\\main.cpp -o C:\\Users\\Nate\\Workspaces\\learning\\dbsm\\main.cpp.o -target x86_64-w64-windows-gnu -IC:\\msys64\\clang64\\include\\c++\\v1 -IC:\\msys64\\clang64\\lib\\clang\\16\\include -IC:\\msys64\\clang64\\include -IC:\\msys64\\clang64\\include\\c++\\v1 -IC:\\msys64\\clang64\\lib\\clang\\16\\include -IC:\\msys64\\clang64\\include -I. -I.  -gdwarf-2  -O0  -Wall"
 }]`

### Version

Other

### Operating system

Windows 10

**Comment by eranif** [comment]
The extra colours (colours for classes, variables etc) are coming from the Language Server (for C++ it usually `clangd`)
Make sure that `clangd` is enabled for you. If you don't know how to check this, click on the magnifier button in the dialog: `plugins -> language server -> settings`  and let CodeLite re-detect it

**Comment by Nateheff** [comment]
Fixed! Thank you so much!
