### ISSUE TITLE
[Feature Request]: Add possibility to remove workspace from "recently used" list on start page

### ISSUE THREAD

**Issue by Viktor-L-v** [eranif/codelite#3228]
### Describe your idea in details

Sometimes may be useful to remove workspace from "recently used" list of workspaces on start page, especially when the workspace file is already deleted
It's may be made by pressing "Del" button or add conext menu with this possibility

**Comment by eranif** [comment]
Non existing files - should be automatically removed, if this is not the case for you, then this is a bug

**Comment by eranif** [comment]
This is now fixed

**Comment by Viktor-L-v** [comment]
Thank you!
Yes, removed workspaces were present in "recently used" list
