### ISSUE TITLE
[Bug]: Shortcuts do not work when editor has no source code files open

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#3231]
### What happened?

When CodeLite has an open workspace, but none of source code files are open in editor, shortcuts do not work. In fact, when creating an empty C++ workspace, or opening an existing C++ workspace that was not previously open (does not have CodeLite temporary files in that folder yet), workspace pane appears hidden and there is no way to open it via shortcuts; in fact, at this moment, none of the shortcuts work.

### Version

Self compiled: 94ab4bddce1b9ebc38b6c4b069587e506d8a9a77

### Operating system

Debian 12 / Gnome / Wayland / wxWidgets 3.2 pre-built

### Steps to reproduce

```text
1. Launch CodeLite
2. Create a new C++ workspace or open an existing C++ workspace that wasn't opened before 
   (alternatively, remove ".cache" and ".codelite" folders from the workspace/project folder)
3. Try shortcuts such as Ctrl + Alt + W or Ctrl + ` to open/close "Workspace View" and/or "Output View". Same happens with other shortcuts, e.g. F6 to open built-in terminal.
   Expected: shortcuts work.
   Actual: nothing happens.
   Workaround: open "Workspace View" manually by going to menu "View" - "Workspace Pane". Click on workspace name in the list. Sometimes this works the first time, sometimes you need to click more - eventually shortcuts start to work.

This can be reproduced again by closing this workspace and then re-opening it, as long as no source code editor files are open in editor.
```

**Comment by yunkot** [comment]
As an additional note, this issue happens often for me because periodically I clean up my project folder from any automatically generated files. After that, when I open some workspace/project, it has no source code files open. Naturally, I immediately press Ctrl+Alt+W to open Workspace pane (which I always hide it as CodeLite is running on a second monitor in portrait orientation), just to realize that shortcuts are not working, so I have to manually go to top menu to open it, which, sometimes, is a long way to go.

**Comment by yunkot** [comment]
I've just updated my build and it looks like this issue is finally fixed, thanks!

**Comment by yunkot** [comment]
The issue occurs again, the steps to reproduce are exactly the same. Revision 84dd6ddd5fd529ef53f224453d33fb6ec43fd11f, Linux Mint 22 (based on Ubuntu 24.04 LTS) / XFCE desktop running on Xorg / wxWidgets 3.2.4.

**Comment by yunkot** [comment]
FYI, on the same configuration, CodeLite revision 6eb52aaff1bb3b999001fbbf56f38bc844000c41 does not seem to suffer from this.

**Comment by yunkot** [comment]
After updating to revision cd2454737c168d6254ab81b86f47c981d45704a4, again I cannot reproduce this anymore (maybe related to change in dd9d5ece4aebf42e3272047db1eceb0c52633440?) This problem seems to be appearing and disappearing, but it feels like the bug is not really fixed, it's just gets hidden after some changes, only to reappear later. Please consider investigating the root cause of this.

**Comment by eranif** [comment]
I am unable to reproduce it, though I did seen it (and dismissed it...)
If you find a reliable way of reproducing this - please post it here

**Comment by UffeJakobsen** [comment]
I have a reliable way of reproducing this problem - actually I see it every day - but never pulled my self together to report it - so I guess that is now it time for me to chime in...  :-)

Whenever I start up CodeLite the focus seems to be somewhere else - no hotkeys works not even menu shortcuts like ALT-E etc...

I have to click somewhere on the "Welcome" page - then the shortcuts works...

This is just reproduced on the CL built from master a few hours ago...

**Comment by eranif** [comment]
@UffeJakobsen can you also specify your setup? (wx version, OS + DE + distro?)

**Comment by UffeJakobsen** [comment]
> @UffeJakobsen can you also specify your setup? (wx version, OS + DE + distro?)

Archlinux (fully updated as of today), LXQt, wxwidgets-gtk3 3.2.6-1

**Comment by eranif** [comment]
Closed by GitHub automatically... please check and see if this fixes the issue for you

**Comment by UffeJakobsen** [comment]
Just built from master - it did not help - problem is still there - sorry

**Comment by UffeJakobsen** [comment]
Ah wait a minute... I think I found something...

I tried deactivating all plugins (followed by CL restart) - and then it works

I've only activated a limited set of the plugins - but it seems that any of these plugins "provoke" the problem:

 - DatabaseExplorer
 - Outline
 - SFTP

**Comment by UffeJakobsen** [comment]
Well - as I've already described I see a variation of the issue.

I just have to open CL (without loading a project/workspace) - and the issue is there - instantly - every time
I have to click somewhere on the Welcome page - button or background - makes no difference - then focus is restored and shortcut/hotkeys work again.

If I disable the the mentioned plugins (or disable all plugins) and start CL - the issue is not there at all

**Comment by eranif** [comment]
> I've only activated a limited set of the plugins - but it seems that any of these plugins "provoke" the problem when active:
> 
>     * DatabaseExplorer
>     * Outline
>     * SFTP

The common thing for these plugins is that they are adding a "page" on the side bar. I have changed the behavior so when adding a page to the sidebar it won't be automatically selected ("steal" the focus)

**Comment by UffeJakobsen** [comment]
Just did a build and tested - it seems to work now - great :+1: 

BTW: in the process the "Recently used workspaces" text and bar have disappeared... is that intentional ?
Now it only states "local workspaces" and "remoty plugin" (if enabled)

**Comment by eranif** [comment]
> BTW: in the process the "Recently used workspaces" text and bar have disappeared... is that intentional ?
Now it only states "local workspaces" and "remoty plugin" (if enabled)

Yes. The "bar" that holds the text is of type `wxStaticText`. Which if you click it by mistake will also break the keyboard shortcuts. (wxStaticText does not handle keyboard events). So i prefer to remove it instead of breaking keyboard shortcuts

**Comment by eranif** [comment]
@yunkot can you also check if this fixes your issue?

**Comment by yunkot** [comment]
I've just build CodeLite from revision fd9220635f7a3243e05aa2d9ac483eafc1cbbc79 few minutes ago. I am not able to reproduce this issue. Hopefully it won't return this time. :) Thanks you guys!
