### ISSUE TITLE
[Bug]: Codelite Not Working !

### ISSUE THREAD

**Issue by samarJ19** [eranif/codelite#3243]
### What happened?

After installing vs studio I started having problems with my debbuger with the error-No executable specified use 'target exec'." then after uninstalling vs studio Now I am not able to run any program the build will show successfully but the output terminal will be empty. Please help ASAP I have searched solutions for this online but was not able to find anything

### Version

Other

### Operating system

Windows 11

### Steps to reproduce

I installed vs studio and changed the environment variable and probably after that I started getting this error. I don't exactly know how to reproduce this error

**Comment by eranif** [comment]
Please fill how to reproduce this step-by-step and how is this relevant to CodeLite
