### ISSUE TITLE
[Bug]: Detached "Watches" box from Debugger pane and it disappeared after closing box - Ubuntu 22.04 Jammy Jellyfish

### ISSUE THREAD

**Issue by dbampoh** [eranif/codelite#3246]
### What happened?

I detached the "Watches" box from the debugger, move it around and settled on leaving it at the bottom right corner of interface. I closed the dialogue box when I was done with it, expecting the typical behavior - that it returns to the debugger pane where all the other debugger boxes/categories (e.g., locals, ouputs) are listed - but it did not. It simply disappeared. Is there a way to recover it or is this a know bug/ issue that will be fixed in upcoming version of codelite?

### Version

Self compiled

### Operating system

Windows 10

### Steps to reproduce

```text
1. Open Codelite 17.0 debugger pane in Ubuntu 22.04 Jammy Jellyfish
2. Detach the "Watches" pane
3. Close the detached "Watches" pane
4. Navigate to Debugger>GDB Windows and not that "Watches" is checked as thought it is still present in Debugger pane.
5. However, it is not present there any more even with restarting, downgrading and re-upgrading, as well as uninstalling and re-installing Codelite 17 (the latest version)
```

### Relevant log output

```shell
No log output to show since this is an interface feature issue.
```

**Comment by eranif** [comment]
Click `View -> Restore Layout`
