### ISSUE TITLE
[Bug/Regression]: Left-click on ruler to place a break-point shows right-click popup menu instead

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#3247]
### What happened?

Previously, one could left-click on left ruler to place debugging break-points. However, in some recent commits, this behavior has changed - now both left-click and right-click open popup-menu. Placing break-points is a rather painful process now, as you have to search somewhere in the middle of popup menu options to place the breakpoint. Same happens if you need to remove it.

This seems to be a regression as before left-clicking on left ruler placed/removed break-points and now there is no distinction between left and right click.

### Version

Commit: 3873b717f1fa35d0ec6b17b954e6d02f59f417bf

### Operating system

Linux

### Steps to reproduce

```text
1. Run CodeLite, open an existing workspace and C++ project.
2. Left-click on left ruler, where bookmarks and breakpoints are displayed.
3. Expected: a break-point is placed at that location.
4. Actual: a popup-menu appears.
   Workaround: search among popup menu options for "Breakpoint" and click on it.
5. Again, left-click on left ruler with the intention to remove the break-point.
6. Expected: a break-point is removed from that location.
7. Actual: a popup-menu appears.
   Workaround: search a longer popup menu list of options for "Remove Breakpoint" option and click on it.
```

**Comment by yunkot** [comment]
This is really inconvenient during debugging. I don't know what the current development priorities for CodeLite are, but I can offer a bounty of $50 USD to get this fixed, as well as another $25 for both #3233 and #3231, which are minor, but when fixed would give more polished feel to CodeLite. Maybe not a big deal, but at least would be a small contribution both to the developer and the product...

**Comment by eranif** [comment]
As a quick workaround, you can use F9 to toggle a breakpoint

**Comment by eranif** [comment]
Thanks for the offering, its not about money … its about what I think is important, I did not realize it is such an annoyance :)

Should now be fixed.

Regarding priority:
I wanted to complete the LSP rename symbol functionality first, it was on my to-do list for a very long time - and not its completed. I will check the other issues you mentioned as well

Eran

**Comment by yunkot** [comment]
The issue with breakpoints did turn to be quite inconvenient during debugging, especially because sometimes you need to place breakpoint very quickly when the application is running. I've verified the fix and it is working, thanks! I also did a quick test for #3233 and it appears to be fixed as well. Could you please also check #3231? Albeit minor, I've commented a bit why it has impact in my case. In either case, I've already wired both promised donations. 

I am really happy to contribute to CodeLite, but I find myself always pressed by work in terms of time, and so far did not have any opportunity to learn CodeLite's code base to be able to help. Therefore, as long as budget allows it, I'm trying to help with bug reports and donations.

Thanks for the explanation regarding LSP rename symbol functionality. I've just tested and it really works! A minor suggestion: shouldn't edit box below "new name" have previous name already typed in, focused and selected so you can immediately adjust it? (right now the box starts empty) Also, after renaming, view seems to scroll up to the declaration of variable that is being renamed, shouldn't it remain in the same position where "rename" command was invoked? (Should I open a separate feature request for that?)

**Comment by eranif** [comment]
Yes, please open separate issues for this - thanks
