### ISSUE TITLE
[Question]: File System Workspace, clangd and remote development

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#3256]
### What happened?

Using CL latest master I've begun to poke into the File System Workspace, clangd and remote development

The basic part seems to work fine - if I edit a file and save it - it will be pushed (SFTP) to the remote host.

CL does not seem to attempt uploading the `codelite-remote` file - when is that supposed happen ?

As far as I can conclude from the docs it is (also) possible to run clangd on the remote host...
My project keeps using the local clangd - even after creating the `.codelite/codelite-remote.json` inside the FS workspace
It is a nice feature that user can select if clangd is to be run either local or remote - keeps flexibility open
But what setting controls if clangd is local or remote ?

### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
When it comes to working on Remote machine (something I have been doing for the last 4 years at work), CodeLite does the following:


- Upload the file `codelite-remote` -> `WORKSPACE/.codelite/codelite-remote`
- Everything is running on the remote machine. CodeLite acts as a mere UI, nothing is expected to run locally

When creating a new workspace, make sure to create a workspace of type `Remote over SSH` this will ensure that the `codelite-remote` is uploaded. Its very similar to `FS-workspace`, it just works remotely (in the code, the Remote-workspace is a thin wrapper around the `FS workspace`).

With remote, the view is similar to the `SFTP` tab: i.e. you get the file system view as it seen on the remote machine, so no need to clone the files locally

**Comment by eranif** [comment]
I will take the time today to write a comprehensive tutorial how to get started with the `Remote over SSH` workspace

**Comment by uffejakobsen** [comment]
Thanks for the reply and explanation.

During the last hours I've been able to make some discoveries on my own...

I'm not new to remote development - until now I've just not used the remote features of CL

It seems to me that CL has several ways to do remote development (with FSW).


Scenario 1: "local FSW"

Using plain FSW - sources are found on the local system. 
In the FSW project settings a remote host can be setup receive the (save) changes to files via SFTP.
All file operations search/replace etc and (clangd) indexing is done on the local system - with the exception that files are also saved to the remote side (is that correct ?)

PS: This was the scenario on which I initially created this issue - at that time I could not see that another way of remote development within CL also was available...



Scenario 2: "remote FSW"
Similar to FSW - except that all source files are found on the remote system.
All file operations search/replace etc and (clangd) indexing is done on the remote system.


Please correct me if my picture of the different remote approaches above are wrong
Both approaches has their advantages and disadvantages.

Some remote development targets may be so low in cpu power and storage that it if not feasible to use them for compiling, indexing and storing the source. Some systems may even be unstable during development with the risk of loosing source and git extract. For such situations the "local FSW" appeoach it a safer way.

**Comment by eranif** [comment]
Yes, the 1st option allows you to work locally, but CodeLite offers the ability to sync via SFTP to the remote machine, it also offers the possibility to trigger the build on the remote machine as well and capture the output locally

The second option (which I am using) is a true remote development. Everything is on the remote machine, including the index service (e.g. clangd, rust-analyzer, pylsp etc). There is no need to prepare something locally, everything is stored on the remote machine (including the workspace file and other files used by CodeLite)

The second options removes the burden of needing to be able to compile the source files locally (sometimes its not even possible: e.g. when running CodeLite on Windows while the remote machine is Linux or macOS). But it offers a better utilization of your local machine (e.g. if the remote target is a small embedded device), all you need on that machine is SFTP server

**Comment by uffejakobsen** [comment]
Thanks for the explanation :+1: 
I'm closing this issue :-)
