### ISSUE TITLE
[Bug]: clangd - differences in options ?

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#3257]
### What happened?

Thank you for re-introducing the ctagsd into the available LSPs

I noticed one thing while doing a new LSP scan:

for `clangd` the command llne looks like this...
```
# Command to execute:

/usr/bin/clangd
  -limit-results=250
  -header-insertion-decorators=0
  --compile-commands-dir=$(WorkspacePath)
```

According to the clangd help (and common conventions) long options should be prefixed with double-hypens (`--`)

Any reason for this ?
 
At first my thought was that this could be due to some Windows special case - but on the other hand the `--compile-commands-dir` uses double-hypens
### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
bug...

**Comment by uffejakobsen** [comment]
Thanks :+1: 

Looking at your commit - shouldn't `-limit-results=250` also have a double-hypen ?

**Comment by eranif** [comment]
Well, back in 2019 -> it was with a single hyphen :)
