### ISSUE TITLE
[Question]: Priority between clangd and ctagsd ?

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#3259]
### What happened?

[Question]: Priority between clangd and ctagsd ?

Background:
I have some projects that are in plain C - builds via Makefile and hence do not have `compile_commands.json`
I do not really feel like using `bear` etc to produce `compile_commands.json` - as the projects are plain C and `ctagsd` used to work fine with those projects.

 CL configuration of `clangd` and `ctagsd` is global to CL - and remembering to  switch (enable/disable) between `clangd` and `ctagsd` is a little cumbersome.

Question:
So what happends if both `clangd` and `ctagsd` are emabled in CL config...

What will `Open Resource` and `lookup symbol` functionality use ?

thanks :-)

### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
Your question reminded me that I had a TODO list to improve `codelite-cc` - and so I did :)

I have updated its [documentation](https://docs.codelite.org/plugins/lsp/#generating-compile_commandsjson-for-a-traditional-makefile-project) 

It basically generates `compile_commands.json` file for classic `Makefile` projects so `clangd` can be used

**Comment by eranif** [comment]
If both are enabled, the priority is undefined.
The servers are kept in an `unordered_map` (`std::unordered_map<wxString, LanguageServerProtocol::Ptr_t> m_servers;`)
to pick a server CodeLite uses this:

```c++
LanguageServerProtocol::Ptr_t LanguageServerCluster::GetServerForEditor(IEditor* editor)
{
    for(const auto& [_, server] : m_servers) {
        if(server->CanHandle(editor)) {
            return server;
        }
    }
    return LanguageServerProtocol::Ptr_t{ nullptr };
}
```

**Comment by uffejakobsen** [comment]
Thanks will do a build of master when I'm back tomorrow :+1:   :-)

**Comment by eranif** [comment]
Update:  since `codelite-cc` is useful outside of CodeLite, I moved it into a separate [repository](https://github.com/eranif/cc-wrapper`) and renamed it into `cc-wrapper`. 

and now CodeLite depends on it as submodule.

So when building CodeLite tomorrow, make sure to run:

```bash
git pull --rebase --recurse-submodules
git submodule update --init --recursive
```

followed by the usual `CMake`
Once CodeLite is installed, you can find the utility named `cc-wrapper`

[I have updated CodeLite docs](https://docs.codelite.org/misc/cc_wrapper/)
