### ISSUE TITLE
Please add a saperate run button in its interface or if it is already there please let me know how to add it ![Feature Request]: 

### ISSUE THREAD

**Issue by ujjwal-7531** [eranif/codelite#3261]
### Describe your idea in details

Feature request description

**Comment by eranif** [comment]
Can you elaborate a bit more? 
- Run what? the debugger? your compiled program? etc
- Where should this button be placed?
- Can you add a screenshot of this button

**Comment by ujjwal-7531** [comment]
I meant the normal run button which is available on other IDEs to simply run a code.

**Comment by ujjwal-7531** [comment]
sorry for taking too long, i was quite busy. I have attached a file and
elaborated the issue in comment of that repository.

**Comment by eranif** [comment]
The button is already there, the toolbar is hidden for you.

Try this `Ctrl-Shift-P`

And type: "tool bar", select the position you want it (i believe its currently hidden for you)

**Comment by ujjwal-7531** [comment]
yeah it was hidden, i set it to top, the run button is with setting logo !,
thanks

**Comment by eranif** [comment]
fixed
