### ISSUE TITLE
libc++.dll is not found 

### ISSUE THREAD

**Issue by comeAndGo** [eranif/codelite#3263]
### What happened?

Using CodeLite 17.0 on Win 11.  Experienced in the language but not with C++ compilers, linkers, etc.

I can compile build, debug, and run my simple console app from the IDE, but when I run the exe directly I get a message **libc++.dll is not found**  . 

![error](https://github.com/eranif/codelite/assets/7242532/933e33b2-ca1a-4db2-90c8-b4cfbcf078ab)

I haven't found **libc++.dll** on my machine at all, but I have found **libstdc++6.dll**. I have added suggested paths to Windows environment options and to compiler directives, etc, and have put **libstdc++6.dll** in the directory with the exe - still get the error.

Here are some of my settings for the project:
![settings1](https://github.com/eranif/codelite/assets/7242532/6cd84571-5d1d-4758-851c-9e33cdf6e0bd)
![settings2](https://github.com/eranif/codelite/assets/7242532/28d79778-d778-4332-9491-1967c605d0f8)

What am I doing wrong? How can I fix this?

 

### Version

Other

### Operating system

Windows 11

### Steps to reproduce

```text
Build simple app C++ in CodeLite, run the generated exe outside the IDE.
```

**Comment by eranif** [comment]
Not really a CodeLite issue..
You used `clang` as your compiler, `libc++.dll` is sitting in the same folder as `clang.exe` is
in your MSYS2 terminal its under `/clang64/bin` - just copy the `libc++.dll` to be next to your executable and it should work
