### ISSUE TITLE
[Question]: Unsetting values in CMake ?

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#3264]
### What happened?

[Question]: Unsetting values in CMake ?

Background:

I've been struggling with some strange behavior of my CodeLite development builds

Every time when switching between my development branches
even just by rebasing a development branch to latest master.

After such operation some of my CMake settings was lost...

Most notably - my "Debug" builds suddenly became "Release" builds etc.. quite annoying...

Now I found the reason it is caused by a 10 years old commit 0a3cccdeafcafca90cdcf8018cca8e2012d6ebca:

```
Author:     dghart
AuthorDate: Fri Jun 28 20:55:03 2013 +0100
Commit:     dghart
CommitDate: Fri Jun 28 21:03:02 2013 +0100
 
    Cmake: Unset the commandline variables after they've been used
    
    Cmake has a regrettable bad habit: it caches command-line options (e.g. -DWITH_PCH) and uses the stale values as future defaults. So if once the user passes a value, it remains in force in future builds until it's explicitly changed by passing a different one.
    
    AFAICT there's no way to turn off this daft behaviour, so instead make a point of unsetting each variable once it's been used (despite the cmake doc, or at least my understanding of it, resetting at the beginning also unsets the passed variable too, despite using unset(... CACHE); perhaps a bug in my cmake version).
```

Well he is right about that - but that is the whole point of CMake - you don't have to type in all options for every invocation - they are actually supposed to be cached

Developers that (think) they know how CMake works will be quite baffled by this approach (that includes me)

Could we have a talk about getting rid of this behavior ?

@dghart - after 10 years - do you still feel the same about this commit ? :-)

### Version

Self compiled

### Operating system

Linux

**Comment by dghart** [comment]
> after 10 years - do you still feel the same about this commit ? :-)

After 10 years I've completely forgotten about it :)   At a guess, it would have been because I was trying to test with different  wx versions, and/or debug versus release builds. When I do so, I want cmake to use my current settings, not some previous choice.

It _has_ been 10 years and nobody else seems to have noticed the change, let alone commented. So I'd be reluctant for it to be reverted. What about adding a CMakeLists.txt setting to make it optional (with the default to be the current behaviour)?

**Comment by dghart** [comment]
I've no knowledge/experience with Ninja, but can't you just change your cmake line to something like:
 cmake --build _build.out -DCMAKE_BUILD_TYPE=Debug

**Comment by uffejakobsen** [comment]
> I've no knowledge of/experience with Ninja, but can't you just change your cmake line to something like: cmake --build _build.out -DCMAKE_BUILD_TYPE=Debug

Yes that would work (would need to include all the other options that are also unset to get a reliable build)

But that needs to be hardcoded into my IDE - and that really defies the whole point of CMake caching settings :-)

**Comment by dghart** [comment]
OK. Then I'd suggest a CmakeLists.txt option, _RETAIN_CACHED_VALUES_ or similar, which when set will disable all those 'unset's.

**Comment by uffejakobsen** [comment]
I'll look into a pull request :-)

**Comment by eranif** [comment]
The CR is now merged. Closing the issue

**Comment by eranif** [comment]
@uffejakobsen : it seems easier if you could commit your changes directly into CodeLite... Let me know if you want to have write access to `eranif/codelite`
