### ISSUE TITLE
[Bug]: ctags include dirs

### ISSUE THREAD

**Issue by alex-rass-88** [eranif/codelite#3280]
### What happened?

A bug happened!
codelite/Plugin/CompileCommandsJSON.cpp has wrong code.

Should be something like this:
`

            CompilerCommandLineParser cclp(command, workingDirectory);
            for(size_t i = 0; i < cclp.GetIncludes().GetCount(); ++i)
                m_includes.Add(cclp.GetIncludes()[i]);
            for(size_t i = 0; i < cclp.GetMacros().GetCount(); ++i)
                m_macros.Add(cclp.GetMacros()[i]);
            for(size_t i = 0; i < cclp.GetOtherOptions().GetCount(); ++i)
                m_others.Add(cclp.GetOtherOptions()[i]);       
`

### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
how is this different from the current code?

```c++
CompilerCommandLineParser cclp(command, workingDirectory);
m_includes = cclp.GetIncludes();
m_macros = cclp.GetMacros();
m_others = cclp.GetOtherOptions();
```

`m_includes` is of type `wxArrayString`, so assigning it another `wxArrayString` (e.g. `cclp.GetIncludes()`) is identical to the code that you wrote

**Comment by alex-rass-88** [comment]
Strange. Not all dirs assigned. But after my fix it's all assigned

**Comment by alex-rass-88** [comment]
https://github.com/wxWidgets/wxWidgets/blob/edd1d758deb70d7a392a23b00fc3b241960b9049/src/common/arrstr.cpp#L133

Assigning clear array and copy new
