### ISSUE TITLE
[Feature Request]: Option to hide left sidebar in "Workspace View"

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#3287]
### Describe your idea in details

I've just noticed that yet an additional sidebar has been introduced, which now appears on the left side of "Workspace View", which has options for "File Explorer", "CMake" or "SFTP", none of which I use. However, since I use CodeLite on a monitor in Portrait mode, this additional vertical sidebar takes precious space, so I can no longer see completely my list of files in workspace, forcing to trade off space between WorkSpace View and source code editor. Normally, I work with "Workspace View" hidden via "Ctrl + Alt + W" shortcut, but nevertheless, when "Workspace View" is shown, I do need to see both the source code and list of files in the project. I'm not sure, but I think this sidebar was previously in horizontal orientation on top inside "Workspace View", but I've never touched it before.

Can you please introduce an option to hide this unnecessary sidebar? Thanks.

**Comment by eranif** [comment]
I am not sure I understand - can you post a screenshot of "before" and "after" ?

**Comment by yunkot** [comment]
These screenshots come from two different machines (Gnome vs XFCE), so please ignore differences in UI.

Before:
![Screenshot from 2023-11-28 14-43-19](https://github.com/eranif/codelite/assets/14065837/1af87927-7149-42f5-96ff-c29d7d53aed4)

Now:
![Screenshot from 2023-11-28 14-32-41](https://github.com/eranif/codelite/assets/14065837/c3b81001-0d69-45fe-bb9b-93b02e4fe1e7)

In the last screenshot, there is a new sidebar on the left, whereas before it was in horizontal orientation and was mostly left unnoticed. In my specific use case, I only use "Workspace" view and since before it was the only one visible (see first screenshot), I didn't even know other options existed; if there would be an option to hide this sidebar completely (so Workspace View is fixed to "Workspace" view tab, as the name implies), it would really save some valuable screen space.

**Comment by yunkot** [comment]
As an alternative idea, the other 6 icons from this sidebar could be moved into a new menu, e.g. "Utility View", which could be optionally visible; this would make more sense because other than "Workspace" tab, other options have nothing to do with "Workspace View". There is also plenty of free space in "Main toolbar", which could be used to accommodate these 6 icons too.

**Comment by eranif** [comment]
I see. 

I will add an option to reposition the buttons bar to either: top, left or vertical 

FYI: the buttons can't be moved out of there, as they are part of the control that displays the files

**Comment by yunkot** [comment]
Many thanks! With the new option, I've switched the orientation to horizontal, which also looks very good aesthetically.
