### ISSUE TITLE
[Bug][Docs]: Trailing spaces makes confusing and failure to install wxWidgets

### ISSUE THREAD

**Issue by Wohlstand** [eranif/codelite#3294]
### What happened?

In the `docs/wxWidgets/repo321.md` (and others too), I got the confusion: because of trailing spaces after some of `\` character in the `apt install` command example, I got a confusion when installing wxWidgets. That was lead "package not found" and "invalid command" errors on attempt to run such command.
Please remove trailing spaces from these blocks to don't confuse newbiews who copying the example commands and attempts to run it. It's absolutely non-intuitive reason of error, I found it accidentally after investigating the source of error by browsing the repository itself via HTTP.

### Operating system

Linux

**Comment by dghart** [comment]
Thank you for reporting this. It's now fixed for the last few releases.
