### ISSUE TITLE
Is it possible to install `wxGTK` on Amazon Linux 2023 (automated or manual)?

### ISSUE THREAD

**Issue by vrej-abramian** [eranif/codelite#3314]
Hello 👋, I need to install `wxGTK` and `wxGTK-devel` packages as a dependency for installing [diff-pdf tool](https://github.com/vslavik/diff-pdf).
Unfortunately, AFAIK there is no supported repository for "Amazon Linux 2023" to deploy `wxGTK` and `wxGTK-devel` packages via `yum` or dnf` 😌.

I'd like to kindly consult you to see if there is any way to reach the goal such as by adding a repository, compiling from source, or download/deploy from rpm package, etc.? **If yes**, providing a relevant structure will be much appreciated 👌

Here are the OS details that I'm using currently:
* AMI: `ami-0a23a9827c6dab833`
* Output of `uname -a` command - showing the cpu architecture, Linux kernel ver. etc. 
  `Linux ip-10-253-2-169.eu-central-1.compute.internal 6.1.77-99.164.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC `

Thank you in advance

**Comment by eranif** [comment]
We don't maintain repositories for `Amazon` Linux. I am afraid you will need to build it from sources
