### ISSUE TITLE
[Bug]: git tag is missing for CodeLite 17.8.0 - Monthly build released on Oct 31, 2023 

### ISSUE THREAD

**Issue by UffeJakobsen** [eranif/codelite#3318]
### What happened?

Hi,

git tag is missing for CodeLite 17.8.0 - Monthly build released on Oct 31, 2023 

/Uffe

### Version

Self compiled

### Operating system

Linux

**Comment by UffeJakobsen** [comment]
I guess that the 17.8.0 tag should be places at commit eb9a07c603e23fdf37ebc66ae88e619c3ba7ffdb

**Comment by eranif** [comment]
Done
