### ISSUE TITLE
[Bug]: build error on latest master

### ISSUE THREAD

**Issue by UffeJakobsen** [eranif/codelite#3319]
### What happened?

Build error on latest master (commit 55c90bf6f5e40c3da03f8a298efc4beda1ff8d0f)

I'm guessing that a changed file needs to be committed :-)

```
/tmp/codelite-devel.git/Plugin/clSideBarCtrl.cpp: In member function ‘void clSideBarCtrl::PlaceButtons()’:
/tmp/codelite-devel.git/Plugin/clSideBarCtrl.cpp:116:54: error: ‘class wxAuiToolBarItem’ has no member named ‘GetClientData’; did you mean ‘GetUserData’?
  116 |         ToolData* cd = dynamic_cast<ToolData*>(tool->GetClientData());
      |                                                      ^~~~~~~~~~~~~
      |                                                      GetUserData
/tmp/codelite-devel.git/Plugin/clSideBarCtrl.cpp: In member function ‘void clSideBarCtrl::AddTool(const wxString&, const wxString&, size_t)’:
/tmp/codelite-devel.git/Plugin/clSideBarCtrl.cpp:153:11: error: ‘class wxAuiToolBarItem’ has no member named ‘SetClientData’; did you mean ‘SetUserData’?
  153 |     tool->SetClientData(new ToolData(bmpname));
      |           ^~~~~~~~~~~~~
      |           SetUserData
/tmp/codelite-devel.git/Plugin/clSideBarCtrl.cpp: In member function ‘wxString clSideBarCtrl::GetPageBitmap(size_t) const’:
/tmp/codelite-devel.git/Plugin/clSideBarCtrl.cpp:231:52: error: ‘class wxAuiToolBarItem’ has no member named ‘GetClientData’; did you mean ‘GetUserData’?
  231 |     auto tool_data = dynamic_cast<ToolData*>(tool->GetClientData());
      |                                                    ^~~~~~~~~~~~~
      |                                                    GetUserData
/tmp/codelite-devel.git/Plugin/clSideBarCtrl.cpp: In member function ‘void clSideBarCtrl::SetPageBitmap(size_t, const wxString&)’:
/tmp/codelite-devel.git/Plugin/clSideBarCtrl.cpp:244:21: error: ‘class wxAuiToolBarItem’ has no member named ‘GetClientData’; did you mean ‘GetUserData’?
  244 |     auto cd = tool->GetClientData();
      |                     ^~~~~~~~~~~~~
      |                     GetUserData
/tmp/codelite-devel.git/Plugin/clSideBarCtrl.cpp:247:11: error: ‘class wxAuiToolBarItem’ has no member named ‘SetClientData’; did you mean ‘SetUserData’?
  247 |     tool->SetClientData(new ToolData(bmpname));
      |           ^~~~~~~~~~~~~
      |           SetUserData
```

### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
seems like wx version mismatch

**Comment by UffeJakobsen** [comment]
> seems like wx version mismatch

I'm using the latest stable wxwidgets-3.2.4 (archlinux)

**Comment by eranif** [comment]
try with latest master

**Comment by domr2695** [comment]
*** hier we have the error.
commit 2803c75cc35fc572e8f7a64c201ab24695acebd9
Author: Eran Ifrah <eran@codelite.org>
Date:   Sat Mar 2 13:01:13 2024

    Restore the secondary side bar functionality

contains an error that is still being issued:

[0/2] Re-checking globbed directories...
[4/1346] Building CXX object Plugin/CMakeFiles/plugin.dir/clSideBarCtrl.cpp.o
FAILED: Plugin/CMakeFiles/plugin.dir/clSideBarCtrl.cpp.o
/usr/bin/c++ -DGTK_USE_NATIVEBOOK=1 -DINSTALL_DIR=\"/usr/local/share/codelite\" -DNDEBUG -DPLUGINS_DIR=\"/usr/local/lib/codelite\" -DUSE_SFTP=1 -DWXUSINGDLL -DWXUSINGDLL_CL -DWXUSINGDLL_WXSQLITE3 -DYAML_CPP_STATIC_DEFINE -DYY_NEVER_INTERACTIVE=1 -D_FILE_OFFSET_BITS=64 -D__WXGTK__ -Dplugin_EXPORTS -DwxUSE_GUI=1 -I/usr/include/gtk-3.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0 -I/media/u1/s1/0/codelite/dtl -I/media/u1/s1/0/codelite/Plugin -I/media/u1/s1/0/codelite/sdk/wxsqlite3/include -I/media/u1/s1/0/codelite/CodeLite -I/media/u1/s1/0/codelite/yaml-cpp/include -I/media/u1/s1/0/codelite/CodeLite/ssh -I/media/u1/s1/0/codelite/PCH -I/media/u1/s1/0/codelite/ThemeImporters -I/media/u1/s1/0/codelite/wxTerminalCtrl -I/media/u1/s1/0/codelite/Interfaces -isystem /usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.2 -isystem /usr/include/wx-3.2 -Wno-deprecated-declarations -isystem /usr/include/harfbuzz -isystem /usr/local/include/harfbuzz -g -O2 -ffile-prefix-map=/media/u1/s1/0/codelite=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -O2 -pthread -fPIC -std=c++17 -fPIC   -Wdate-time -D_FORTIFY_SOURCE=2 -Winvalid-pch -include /media/u1/s1/0/codelite/build/release/Plugin/CMakeFiles/plugin.dir/cmake_pch.hxx -MD -MT Plugin/CMakeFiles/plugin.dir/clSideBarCtrl.cpp.o -MF Plugin/CMakeFiles/plugin.dir/clSideBarCtrl.cpp.o.d -o Plugin/CMakeFiles/plugin.dir/clSideBarCtrl.cpp.o -c /media/u1/s1/0/codelite/Plugin/clSideBarCtrl.cpp
/media/u1/s1/0/codelite/Plugin/clSideBarCtrl.cpp: In member function ‘void clSideBarCtrl::PlaceButtons()’:
/media/u1/s1/0/codelite/Plugin/clSideBarCtrl.cpp:116:54: error: ‘class wxAuiToolBarItem’ has no member named ‘GetClientData’; did you mean ‘GetUserData’?
  116 |         ToolData* cd = dynamic_cast<ToolData*>(tool->GetClientData());
      |                                                      ^~~~~~~~~~~~~
      |                                                      GetUserData
/media/u1/s1/0/codelite/Plugin/clSideBarCtrl.cpp: In member function ‘void clSideBarCtrl::AddTool(const wxString&, const wxString&, size_t)’:
/media/u1/s1/0/codelite/Plugin/clSideBarCtrl.cpp:153:11: error: ‘class wxAuiToolBarItem’ has no member named ‘SetClientData’; did you mean ‘SetUserData’?
  153 |     tool->SetClientData(new ToolData(bmpname));
      |           ^~~~~~~~~~~~~
      |           SetUserData
/media/u1/s1/0/codelite/Plugin/clSideBarCtrl.cpp: In member function ‘wxString clSideBarCtrl::GetPageBitmap(size_t) const’:
/media/u1/s1/0/codelite/Plugin/clSideBarCtrl.cpp:231:52: error: ‘class wxAuiToolBarItem’ has no member named ‘GetClientData’; did you mean ‘GetUserData’?
  231 |     auto tool_data = dynamic_cast<ToolData*>(tool->GetClientData());
      |                                                    ^~~~~~~~~~~~~
      |                                                    GetUserData
/media/u1/s1/0/codelite/Plugin/clSideBarCtrl.cpp: In member function ‘void clSideBarCtrl::SetPageBitmap(size_t, const wxString&)’:
/media/u1/s1/0/codelite/Plugin/clSideBarCtrl.cpp:244:21: error: ‘class wxAuiToolBarItem’ has no member named ‘GetClientData’; did you mean ‘GetUserData’?
  244 |     auto cd = tool->GetClientData();
      |                     ^~~~~~~~~~~~~
      |                     GetUserData
/media/u1/s1/0/codelite/Plugin/clSideBarCtrl.cpp:247:11: error: ‘class wxAuiToolBarItem’ has no member named ‘SetClientData’; did you mean ‘SetUserData’?
  247 |     tool->SetClientData(new ToolData(bmpname));
      |           ^~~~~~~~~~~~~
      |           SetUserData
[13/1346] Building CXX object Plugin/C...plugin.dir/clTableWithPagination.cpp.o
ninja: build stopped: subcommand failed.


*** hier  no error
commit 76490b67fd622b98a8c5fcb1aa756b2d9f757a31
Author: Eran Ifrah <eran@codelite.org>
Date:   Sat Mar 2 01:09:22 2024

    clAuiBook: GTK fixes

**Comment by eranif** [comment]
Please try and update (I just committed a fix)

Thanks

**Comment by UffeJakobsen** [comment]
> try with latest master

I can confirm that latest master now builds with success (commit c77e1e070d81bf392491c87845c818ff2a86f5e2)

Thanks :+1:  :-)
