### ISSUE TITLE
[Bug]: move tab left/right operations does not work anymore

### ISSUE THREAD

**Issue by UffeJakobsen** [eranif/codelite#3320]
### What happened?

I've for many years had the operations/actions `Tab | Move tab left` and `Tab | Move tab right` assigned to keyboard shortcuts.

After introduction of the new Aui-book impl: move tab left/right (keyboard) operations does not work anymore

### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
Thanks, I am working on restoring it (this is the last functionality that the new aui book is missing from the old one)

**Comment by eranif** [comment]
Should be fixed now. I believe that with this change, there are no missing functionalities only new ones...
For example: the ability to split the notebook and displaying two tabs side by side :)
