### ISSUE TITLE
[Bug]: Black theme does not work in CodeLite under Windows 7 

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#3325]
### What happened?

Selecting Dark theme in CodeLite does not work on Windows 7, either when selected in Welcome Screen, or changed manually in options ("Force dark" option in Colors) afterwards - CodeLite appears white regardless.

The last version, where such option worked was CodeLite 16.7, in CodeLite 16.8 it stopped working.

### Version

CodeLite 16.8 or later

### Operating system

Windows 7 SP1 64-bit

**Comment by eranif** [comment]
I just realized that you are talking about Windows 7 -> this is not supported by wxWidgets (IIRC, Windows itself does not support it). So this wont get fixed

**Comment by yunkot** [comment]
But "Dark Theme" have been working successfully in CodeLite up until version of 16.8.
Are you sure wxWidgets does not support Windows 7 anymore? I can't find any information about this.

Assuming the above, I am trying to build CodeLite with wxWidgets 3.2.1, but it fails with:

```
D:\msys64\home\ynkot\codelite\Plugin\drawingutils.cpp:409:48: error: no member named 'SelectLightDark' in 'clSystemSettings'
  409 |     wxColour darkPen = clSystemSettings::Get().SelectLightDark(bgColour.ChangeLightness(95), *wxBLACK);
```
wxWidgets 3.2.1 was released in second half of 2022, so roughly a year and half ago, shouldn't CodeLite still support it? Especially because it still might be used on non-latest versions of Ubuntu/Debian?

**Comment by eranif** [comment]
It does not matter. The new dark theme is now using Windows native API - which is not supported by Windows 7

**Comment by yunkot** [comment]
Thanks for clarifying this. This is sad news, because CodeLite is a strong option for development on Windows 7 (for Windows 10+, there is always newest version of Visual Studio). I myself have to use it occasionally there to target and debug older industrial systems, down to Windows NT 4.0 (using latest GCC with a special C runtime) - as surprising as it may sound, there are still few of these around used in production environments.

After the crash in #3323 has been fixed, I was really excited to be able to update from CodeLite 14, but that unusually white theme is really hard on the eyes, and I'm unable to use versions of CodeLite between 14.02 and 15 because there were some regressions that have been fixed last year.

It would have been great if CodeLite would focus on dark theme, with white theme being optional and specific to Windows 10+.

**Comment by AJenbo** [comment]
@yunkot you could produce a dll wrapper that provides the Windows theme API calls used by CodeLite, and just responds with the values Windows 10 would if set to a dark theme.

**Comment by DEF7** [comment]
Dark mode not working over here either on Windows 10 running v17.0.0. Yes, I hit Apply, yes I restarted CodeLite, multiple times.

![image](https://github.com/user-attachments/assets/05a0b627-8805-484c-b14b-45cb5e030b3f)

When I was installing it the thing showed me 3 different color schemes, I picked gray. Where are those three options accessible from now?

Also, the Restore option at the top of the dialog doesn't change anything, it just leaves everything the way it already is - which is not how they were before I changed them.

**Comment by eranif** [comment]
@DEF7 , can you try this with [CodeLite 17.12](https://downloads.codelite.org/) ? (it is much more stable than `17.0.0`) and soon will be changed into `18.00.0`

**Comment by DEF7** [comment]
Hi Eran,

Still no dice with 17.12.0 :P 

![image](https://github.com/user-attachments/assets/7fcd6e14-158f-4d0b-bb03-38d133fff6ac)

The "Restore" button on the Colors/Fonts dialog also still has no effect. It just causes the dialog to flash once but it doesn't reset any font/color changes. :\
