### ISSUE TITLE
Source Code Formatter option

### ISSUE THREAD

**Issue by Samuelbeausejour** [eranif/codelite#3328]
### Describe your idea in details

Do they have an option in codelite 17.0 that give you the option do modify Source Code Formatter? In the previous version, it was possible to change auto formatting configuration like brackets positionning, space between patenthesis...

![codelite](https://github.com/eranif/codelite/assets/145819724/65746619-d1e9-45ff-b0d5-20b28e3fc4d4)

**Comment by eranif** [comment]
This was removed couple of years ago. CodeLite now supports multiple formatters, each has its own configuration. 
For `C/C++`, the default is `clang-format`, to configure it, you should add a `.clang-format` file.

You can learn about it here:
https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by Samuelbeausejour** [comment]
Ok thank you
