### ISSUE TITLE
[Bug]: Colors and font: Codelite appearance is greyed out ?

### ISSUE THREAD

**Issue by UffeJakobsen** [eranif/codelite#3331]
### What happened?

Just asking/checking:

In menu `Colors and fonts...` - the dropdown `Codelite appearance` is greyed out - is that intentional ?

### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
Yes, on Linux, CodeLite uses the default theme. It is only enabled on Windows (disabled for macOS)
