### ISSUE TITLE
[Bug]: Workspace file-view not usable with dark themes (Linux)

### ISSUE THREAD

**Issue by UffeJakobsen** [eranif/codelite#3332]
### What happened?

[Bug]: Workspace file-view not usable with dark themes (Linux)

See screenshot:

![screen](https://github.com/eranif/codelite/assets/3018239/dadfd71f-5f27-4f3b-9ad5-2f78d5b3c88e)

### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
any tips on how to reproduce this on WSL? (Linux running on Windows)

**Comment by eranif** [comment]
It works nicely for me...

This is how I ran CodeLite:

```bash
GTK_THEME=Adwaita:default codelite
```

<img width="1233" alt="Capture" src="https://github.com/eranif/codelite/assets/3677711/bde690fd-7e83-43c1-9566-4ef422b9c4e1">

**Comment by eranif** [comment]
can you try and rename `~/.codelite` and restart CodeLite?

**Comment by eranif** [comment]
Can you try with latest master? (I did some changes)

**Comment by UffeJakobsen** [comment]
I've just tested latest master and it looks really good :+1:  
I'm closing this issue - thanks :-)
