### ISSUE TITLE
[Bug]: build error on latest master using GCC 14.1.1

### ISSUE THREAD

**Issue by UffeJakobsen** [eranif/codelite#3363]
### What happened?

build error on latest master using GCC 14.1.1

PS: Clang 17.0.6 builds fine

Archlinux GCC 14.1.1 20240507 output below:

```


In file included from /tmp/codelite-devel.git/dtl/dtl/dtl.hpp:44,
                 from /tmp/codelite-devel.git/Plugin/clDTL.cpp:28:
/tmp/codelite-devel.git/dtl/dtl/Diff.hpp: In member function ‘void dtl::Diff<elem, sequence, comparator>::enableTrivial() const’:
/tmp/codelite-devel.git/dtl/dtl/Diff.hpp:168:27: error: assignment of member ‘trivial’ in read-only object
  168 |             this->trivial = true;
      |             ~~~~~~~~~~~~~~^~~~~~

```

### Version

Self compiled

### Operating system

Linux

**Comment by UffeJakobsen** [comment]
https://github.com/cubicdaiya/dtl/issues/20

**Comment by AJenbo** [comment]
Since GCC 14.1.1 appears to not actually be a real version of GCC but and Arch specific build (of what will more likely be part of GCC 14.2.0), and the issue is with an upstream package; I think it's better to close this issue for now.
I have subscribed to https://github.com/cubicdaiya/dtl/pull/18 so that I will know to update the module once the issue is fixed upstream.

**Comment by UffeJakobsen** [comment]
Seems quite wierd to close a case what is not solved...
Also any user that is about to report the similar problem will certainly not check the closed issues/tickets before creating a new one..
Why not use the advantages that the issue/ticket system gives - instead of relying on some personal notification ?

**Comment by AJenbo** [comment]
> Seems quite weird to close a case that is not solved...

There is nothing further that can be done at this time, I'm subscribed to the event that will allow us to move forward so no need to have this as an active reminder.

>  Also any user that is about to report the similar problem will certainly not check the closed issues/tickets before creating a new one..

I hope they do

>  Why not use the advantages that the issue/ticket system gives - instead of relying on some personal notification ?

To get a better overview of renaming addressable issues, the notification system has served me well for years so I trust it. It's how I noticed your comment within a few minutes.

**Comment by UffeJakobsen** [comment]
> > Also any user that is about to report the similar problem will certainly not check the closed issues/tickets before creating a new one..
> 
> I hope they do
> 
I for sure wouldn't waste time going through closed issues before reporting an issue...

**Comment by eranif** [comment]
The only solution I see here is:

- Fork DTL and fix this (just remove the `const`)
- Change the submodule to point to forked version

Other suggestions?

**Comment by eranif** [comment]
@UffeJakobsen I have updated the submodule to https://github.com/eranif/dtl and fixed this specific assignment
Please try with latest master

I believe that you will need to run:

```bash
git submodule update --init --recursive
```

LMK if it works for you

**Comment by UffeJakobsen** [comment]
@eranif It works perfect !!! :+1: 

I'm closing this issue 

Thanks :-)

**Comment by AJenbo** [comment]
https://github.com/cubicdaiya/dtl/pull/18 has now been merged and we can revert back to using upstream DTL.
