### ISSUE TITLE
[Feature Request]: Make codelite packaging friendly on MSYS2

### ISSUE THREAD

**Issue by MehdiChinoune** [eranif/codelite#3400]
### Describe your idea in details

I tried to package codelite 17 (update it) on MSYS2 (https://packages.msys2.org/base/mingw-w64-codelite), but unfortunately the developer made it impossible to package it on MSYS2.

- It uses some custom wxwidgets cmake scripts which could be replaced by CMake builtin FindWxWidgets.
- It hardcodes installation destinations on Windows.
- It installs the runtime dependencies dlls.
- It expects the user to generates an installer.

In other word, the only way to use codelite on Windows is through the official installer.

If that's the only way, just tell us so we could drop it and redirect users to use the official installer.

**Comment by Jarod42** [comment]
I tried CMake builtin FindWxWidgets, but it fails for me: assume gcc|no monolitic, ...
but pretty sure patch welcome ;-)

**Comment by MehdiChinoune** [comment]
> I tried CMake builtin FindWxWidgets, but it fails for me: assume gcc|no monolitic, ... but pretty sure patch welcome ;-)

Maybe that was a long time ago, there were many fixes to FindWxWidgets and now It works fine with both gcc and clang.
As I said the issue is not just about FindWxWdigets.

I assume, that's a No.
Thanks.

**Comment by Jarod42** [comment]
BTW, I'm just a participant of the project, I'm neither owner or collaborator.
I added CI including the one for msys2.
I tried without success but I 'm not expert of neither CMake nor WxWidgets nor msys2.
