### ISSUE TITLE
[Bug]: submodule libssh: checkout is unstable

### ISSUE THREAD

**Issue by UffeJakobsen** [eranif/codelite#3403]
### What happened?

It seems that the newly added submodule libssh has problems - checkouts is quite unstable.

Before the weekend I saw problems and they are still present this week

This is the behavior that I see from several locations (different IP's)
```
% git clone https://git.libssh.org/projects/libssh.git                                                                                                                                                                          
Cloning into 'libssh'...
fatal: the remote end hung up unexpectedly
```
Now this may not sound as a big problem if you manage to get a valid checkout and keep it - but it prevents most users of AUR pkgbuilds from building "latest and greatest" CodeLite

AUR: https://aur.archlinux.org/packages/codelite-git

### Version

Self compiled

### Operating system

Linux

**Comment by UffeJakobsen** [comment]
submodule checkout have been stable for 2 weeks now - closing this issue

**Comment by eranif** [comment]
Just an FYI: `libssh` submodule is needed on macOS only (for Linux, we use the distro's package)

**Comment by UffeJakobsen** [comment]
> Just an FYI: `libssh` submodule is needed on macOS only (for Linux, we use the distro's package)

Yes I know - but I wanted to keep the ArchLinux AUR PKGBUILD scripts as generic as possible - and let git handle the submodule checkout as a whole. 
If I did explicit checkout for each submodule I would have a higher maintenance burden on the AUR PKGBUILD scripts over time....
