### ISSUE TITLE
[Bug]: shortcut of ctrl+shift+U for uppper is out of work

### ISSUE THREAD

**Issue by BIRooter** [eranif/codelite#3415]
### What happened?

A bug happened!

default setting of upper (ctrl+shift+u) is out of work

### Version

Self compiled

### Operating system

Linux

**Comment by eranif** [comment]
I just tested this with CodeLite master, and it is working as expected (Ubuntu 22.04 / macOS Sonoma / Windows 10)

**Comment by BIRooter** [comment]
My environment is kubuntu 24.04 + codelite 14. There is a "U+" displayed at the bottom-left corner of the code view.

**Comment by BIRooter** [comment]
It works if I changed the shortcut to Ctrl+Alt+U.
