### ISSUE TITLE
[Feature Request]: gui of version 17 is chaos, could you roll the gui back to that of version 14

### ISSUE THREAD

**Issue by BIRooter** [eranif/codelite#3416]
### Describe your idea in details

Feature request description

The GUI used in version 17 is bad: jump to definition is missing in context menu, page head is not highlighted for current file, etc.

**Comment by eranif** [comment]
Reverting is not going to happen. If you have a specific issue - please open an issue.
Note that if a "jump to definition" is missing, this is an indication that your language server is not setup for that specific language - this context menu entries are added by the language server.

About highlight of page head ( I am not sure what do you mean by that) - do you mean that the tab label is not lighted? 

For example, see the below image:

<img width="534" alt="Capture" src="https://github.com/eranif/codelite/assets/3677711/02ff2583-ed14-44a6-a817-41250cd1b608">

?

You might want to try CodeLite 17.10 (not sure which OS you are talking here)

**Comment by BIRooter** [comment]
Yes, you are right! 

So, you mean the tab head will be highlighted in 17.1.0. isn't it?

I checked the "Language server" in plugins, the setting is as following:
![image](https://github.com/user-attachments/assets/0fa0774b-fc6b-497a-877d-186a4df7c119)
