### ISSUE TITLE
[Bug]: Repeated crash of codelite

### ISSUE THREAD

**Issue by KUSHAGRA2606** [eranif/codelite#3425]
### What happened?

codelite window sometimes automatically get crashed

### Version

17.10.0

### Operating system

Windows 11

### Steps to reproduce

```text
on running a program sometimes codelite get crashed and get logged out
```

**Comment by eranif** [comment]
Thanks for reporting this.
Since I don't have Windows 11, could you please run CodeLite under `lldb` ? and report back the backtrace when it happens?

**Comment by eranif** [comment]
A duplicate of https://github.com/eranif/codelite/issues/3406
