### ISSUE TITLE
The software does not run smoothly

### ISSUE THREAD

**Issue by tangailiu** [eranif/codelite#3426]
### What happened?

The software run not smoothly and the setting of show close button on tabs doesnot work on every restart.

### Version

17.10.0

### Operating system

Windows 11

### Steps to reproduce

```text
1.Select setting
2.uncheck the checkbox  "show close button on tabs "
```

**Comment by eranif** [comment]
Fixed

**Comment by tangailiu** [comment]
Thanks.


Plan to develop an AI plugin?


| |
18662453926
|
|
***@***.***
|
---- Replied Message ----
| From | Eran ***@***.***> |
| Date | 7/19/2024 09:21 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [eranif/codelite] The software does not run smoothly (Issue #3426) |

Fixed

**Comment by eranif** [comment]
Regarding AI plugin: https://github.com/eranif/codelite/issues/3360
