### ISSUE TITLE
How to remove CodeLite?

### ISSUE THREAD

**Issue by ShuiXiJin** [eranif/codelite#3427]
Hi, 

I am using Macbook and would like to reinstall CodeLite completely. 
For my first time, at the setup wizard page, I click c++ and next, then CodeLite freezes for long time and I have to force it to quit. For the second time I open CodeLite, there is no longer such setup wizard and I don't have GCC for my complier, only clang++. 

I am thinking of completely remove CodeLite and all its relative folders and files and install it all over again. But with macbook, I drag the icon into bin, which doesn't completely remove the files and folders. Can anyone help with this?

Regards
Yuqing

**Comment by eranif** [comment]
The hang is fixed in latest master. To workaround it, start CodeLite from a terminal:

```
open /path/to/codelite.app
```

To remove completely, delete the

```
~/.codelite
```


Folder

**Comment by eranif** [comment]
FYI: I have updated CodeLite for macOS to version 17.11.0 - you can install it via `brew` and hang issue should be resolved with this version
