### ISSUE TITLE
codelite.exe fails to execute after successfull compile and link 

### ISSUE THREAD

**Issue by noeldiviney** [eranif/codelite#3441]
### What happened?

This a follow on from the now closed issue #3197 Unable to build codelite on Windows 10
When double clicking build-release/bin/codelite.exe the following errors are displayed:
1.  wxmsw330u_clang_custom.dll was not found
2.  libssh.dll was not found

Codelite build instructions are from 
https://docs.codelite.org/build/build_from_sources/

Noel Diviney

### Version

Self compiled

### Operating system

Windows 10

### Steps to reproduce

```text
see  https://docs.codelite.org/build/build_from_sources/
```

### Relevant log output

```shell
[codelite-build-log.txt](https://github.com/user-attachments/files/16465681/codelite-build-log.txt)
```

**Comment by eranif** [comment]
Strange, I deleted the `install/` folder, executed `cmake` followed by `mingw32-make install` and the files are there
If you will look in the links below, you can see that the mentioned DLLs are supposed to be installed...

https://github.com/eranif/codelite/blob/master/CMakeLists.txt#L1075
https://github.com/eranif/codelite/blob/master/CMakeLists.txt#L1092

**Comment by noeldiviney** [comment]
Hi Eran
Thank you for your prompt response.
There seems to be a problem with my install of Msys2 something is missing .
Current build logs and the .bashrc: :
[Codelite-build error.txt](https://github.com/user-attachments/files/16478420/Codelite-build.error.txt)
[The-complete-build-log.txt](https://github.com/user-attachments/files/16478424/The-complete-build-log.txt)
[.bashrc.txt](https://github.com/user-attachments/files/16478429/default.bashrc.txt)
Any Suggestions?
Noel

**Comment by Jarod42** [comment]
For the build error, WxWidgets has made an update which requires change in codebase
Using WxWidgets v3.2.5 should fix that.

**Comment by noeldiviney** [comment]
Hi Jarrod,
Thank you for the update.
So what are the steps I have to take to get a successful build of Codelite.
Noel

**Comment by Jarod42** [comment]
Until Codelite trunk is updated to works with latest WxWidgets, use "older" version of WxWidget:

```
git clone https://github.com/wxWidgets/wxWidgets
git checkout 3737245c5195d84f0c788e650c6ad7992eec03d7
cd wxWidgets
git submodule update --init
```

For your missing dlls, you might still have the issue though :-/
I don't know why you got missing dlls at the beginning.

**Comment by noeldiviney** [comment]
Hi Jarrod,
Thank you for the suggestions.
In fact that was going to be my task for today.
The reason for my need to to build Codelite is to add the capability to of Embedded Debugging to Codelite.
Will keep you posted on this.
Many thanks and best regards,
 Noel

**Comment by noeldiviney** [comment]
Successful Build of Codelite IDE.
I had to make a smal;l change to the instructions as follows :

git clone https://github.com/wxWidgets/wxWidgets
cd wxWidgets
git checkout 3737245c5195d84f0c788e650c6ad7992eec03d7
git submodule update --init

[Successful-Codelite-BuildLog.txt](https://github.com/user-attachments/files/16510540/Successful-Codelite-BuildLog.txt)

A Big thank you for the help.
Best regards,
Noel Diviney.

**Comment by noeldiviney** [comment]
Where is the checkout tag 3737245c5195d84f0c788e650c6ad7992eec03d7 obtained from?
Noel

**Comment by Jarod42** [comment]
Some trivial investigation:
- Build error is for a signature change of a virtual function (thanks to `override`).
- `git blame` find the commit (which were the last one :-) )

And finally test that commit.

**Comment by noeldiviney** [comment]
Thank you Jarrod.
Now back to getting my wxPython installer GUI to setup Embedded Systems Environment up and running

Cheers Noell

**Comment by Jarod42** [comment]
Codelite's master has been fixed.
You have to use either WxWidget v2.5.x or master (as 3737245c5195d84f0c788e650c6ad7992eec03d7 is incompatible with the fix).
