### ISSUE TITLE
[Bug]: Cannot build with latest wxWidgets (master branch v3.3.0)

### ISSUE THREAD

**Issue by Jarod42** [eranif/codelite#3442]
### What happened?

Build error with latest wxWidgets (master branch) (since https://github.com/wxWidgets/wxWidgets/commit/3d776fdad44b5e14a65991c35e5893a705e188df)

```
/usr/local/include/wx-3.3/wx/aui/tabart.h:177:12: note: hidden overloaded virtual function 'wxAuiGenericTabArt::GetTabSize' declared here: type mismatch at 1st parameter ('wxReadOnlyDC &' vs 'wxDC &')
```

(That brokes CI for MacOS/Win which use master branch)

### Version

Self compiled

### Operating system

Windows 10

### Steps to reproduce

```text
Build with latest WxWidgets (or use Win/MacOS CI)
```

### Relevant log output

```shell
[ 38%] Building CXX object Plugin/CMakeFiles/plugin.dir/clAuiCaptionEnabler.cpp.o
/Users/runner/work/codelite/codelite/Plugin/clAuiBook.cpp:41:85: error: non-virtual member function marked 'override' hides virtual member function
                      bool WXUNUSED(active), int close_button_state, int* x_extent) override
                                                                                    ^
/usr/local/include/wx-3.3/wx/aui/tabart.h:177:12: note: hidden overloaded virtual function 'wxAuiGenericTabArt::GetTabSize' declared here: type mismatch at 1st parameter ('wxReadOnlyDC &' vs 'wxDC &')
    wxSize GetTabSize(
           ^
1 error generated.
```

**Comment by eranif** [comment]
It seems that wxWidgets changed the API signature which now causes an `override` error. I think that they chose the wrong approach - instead of changing the API, they should have added a new one (overloading...)

I commented on the merged PR. For now, I think we can use the `wxCHECK_VERSION(3,3,0)` in the code
