### ISSUE TITLE
[Feature Request]: Rocky Linux 8 and 9

### ISSUE THREAD

**Issue by zhoub** [eranif/codelite#3470]
### Describe your idea in details

Hi !

Is that possible to offer compatible RPM for Rocky Linux 8 and 9 ? Thanks in advance !

**Comment by dghart** [comment]
Is it possible? I'm sure it is. But there are _lots_ of Linux distros, and I can't provide binaries for them all. And Rocky is only number 50 in the [Distrowatch](https://distrowatch.com/dwres.php?resource=popularity) popularity list.

However if you are volunteering to create the rpms, I'm sure we could host them.

**Comment by eranif** [comment]
What @dghart said: we can't support them all. If you are interested, feel free to package them and we will host them
