### ISSUE TITLE
Dark mode not working on Windows 10.

### ISSUE THREAD

**Issue by DEF7** [eranif/codelite#3482]
Dark mode not working over here either on Windows 10 running v17.0.0. I hit Apply, I restarted CodeLite, multiple times. No dice.

![image](https://github.com/user-attachments/assets/05a0b627-8805-484c-b14b-45cb5e030b3f)

When I was installing it the thing showed me 3 different color schemes, Light/Gray/Dark, I picked gray. Where are those three options accessible from now? All I see is "System Default" and "Force Dark", and neither of those seem to have any effect.

Also, the Restore option at the top of the dialog doesn't change anything, it just leaves everything the way it already is - which is not how they were before I changed them.

_Originally posted by @DEF7 in https://github.com/eranif/codelite/issues/3325#issuecomment-2375462675_

**Comment by eranif** [comment]
I am using Windows 10 and it is working as expected.
Make sure that you are using windows 10 20H1 and later.

([According to this](https://docs.wxwidgets.org/latest/classwx_app.html#af8c93d7e3345e62a58325f3ab1d158d6))
