### ISSUE TITLE
[Bug]: Highlighting missing on header files (C++)

### ISSUE THREAD

**Issue by mattreecebentley** [eranif/codelite#3485]
### What happened?

If you double-click (select) a block of text in a .cpp file, it'll highlight other instances of that same text in the file. This is currently missing on .h files.

### Version

Other

### Operating system

Windows 10

### Steps to reproduce

```text
v17.12.0
Non-self-compiled.

Double-click a phrase in a .h file.
```

**Comment by eranif** [comment]
can you provide a screen shot? this functionality has zero knowledge about the type of file it operates on.
(also, I did check this and it is working as expected)

**Comment by eranif** [comment]
Closing. Unable to reproduce - no response from OP

**Comment by mattreecebentley** [comment]
Top is .cpp
bottom is .h
