### ISSUE TITLE
[Bug]: Garbled / misplaced auto-completion text while typing

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#3490]
### What happened?

I'm using CodeLite built from revision 84dd6ddd5fd529ef53f224453d33fb6ec43fd11f. Running on Linux Mint 22 (based on Ubuntu 24.04 LTS) / XFCE desktop running on Xorg / wxWidgets 3.2.4, on CPU Ryzen 9 5950X, 128Gb RAM. I'm working with C++ source code using clangd LSP. 

Previously, I've been using CodeLite revision 6eb52aaff1bb3b999001fbbf56f38bc844000c41, so roughly 9-10 months ago. I see that there are some new features, which is nice.

However, now I'm experiencing issues with code completion. Here are my steps:

1. Type a long function name, for instance, we are trying to write "interpolateWaypointPosition()".
2. After a couple of characters, e.g. "interp", a code completion popup appears showing the necessary function name. Press Enter to auto-complete it.
3. Immediately after pressing "Enter", continue typing "()" to finish function call.

Expected: you end up with "interpolateWaypointPosition()" written.
Actual: you end up with "interp()interpolateWaypointPosition" written.

The occurrence of the issue is sporadic and seems to be dependent on auto-completion speed. Sometimes after you press "Enter", the response is immediate and issue does not occur, but sometimes CodeLite "lags" a bit, around 200-500ms or so while completing the word, which is slow enough for you to continue typing, which results in the aforementioned issue.

The problem did not happen in older version of CodeLite I was using/ I suspect that in new version, auto-completion is executed asynchronously, which produces the issue due to "racing" condition with your keyboard input.

### Version

Commit 84dd6ddd5fd529ef53f224453d33fb6ec43fd11f

### Operating system

Linux Mint 22 / XFCE / Xorg / wxWidgets 3.2.4

**Comment by yunkot** [comment]
This issue is quite difficult to reproduce when OS is more responsive - on Linux Mint 21 / Ubuntu 22.04 / Debian 12, I practically can't reproduce it because OS is much more responsive, so code completion seems to be always instant. Newer Linux Mint 22 and Ubuntu 24.04 seem to be more sluggish on my hardware configuration, so this issue is more pronounced.

The OS "sluggishness" is another topic, but this issue is quite a showstopper. I'm offering a bounty of 75 USD for a fix as an incentive. Alternatively (or additionally), if you would consider #3494, I'd be the first to add support.

**Comment by eranif** [comment]
This is *probably* because of this line:
https://github.com/eranif/codelite/blob/e83a5fffa4b0f23e92b08ce472b6289824bfb559/Plugin/wxCodeCompletionBox.cpp#L420

Which basically performs the insertion on the next event loop, you can try and pull CodeLite from master and see if this fixes the issue.

**Comment by yunkot** [comment]
I'm using build from commit cd2454737c168d6254ab81b86f47c981d45704a4 and can no longer reproduce this. In fact, code completion seems to be slightly more responsive now. Therefore, I think the issue is fixed. Many thanks!

P.S. I've send the bounty as donation. Please consider request #3494 on opening a sponsors page.
