### ISSUE TITLE
can't install on macos sequoia

### ISSUE THREAD

**Issue by Herzuss** [eranif/codelite#3497]
### What happened?

i can't download codelite via brew.
it says:"This software does not run on macOS versions other than Sonoma."

### Version

Self compiled

### Operating system

macOS

### Steps to reproduce

```text
brew reinstall --cask codelite-official
```

### Relevant log output

```shell
Error: This software does not run on macOS versions other than Sonoma.
```

**Comment by eranif** [comment]
It's probably due to this line in the formula:
https://github.com/eranif/homebrew-codelite/blob/main/Casks/codelite-official.rb#L17

I don't have sequoia to test this, so it will be great if you can test this for me (just install it manually like this):

Open terminal and run:

```bash
wget https://downloads.codelite.org/codelite/17.12.0/codelite-macOS_14.7-arm64.app.tar.gz
tar xvfz codelite-macOS_14.7-arm64.app.tar.gz
open codelite.app
```

**Comment by Herzuss** [comment]
it work.
thanks man
