### ISSUE TITLE
[Bug]: codelite dont find lldb-vscode

### ISSUE THREAD

**Issue by Herzuss** [eranif/codelite#3499]
### What happened?

wheni try to switch debbuger i cant find lldb-vscode.
i installed llvm via brew.
am i doing smth wrong?

### Version

Self compiled

### Operating system

macOS

### Steps to reproduce

```text
settings --> debbug adapter client --> scan
```

### Relevant log output

```shell
nothing
```

**Comment by genpfault** [comment]
Which LLVM version did you end up with?  [`lldb-vscode`](https://github.com/llvm/llvm-project/tree/llvmorg-17.0.6/lldb/tools/lldb-vscode) was renamed to [`lldb-dap`](https://github.com/llvm/llvm-project/tree/llvmorg-18.1.8/lldb/tools/lldb-dap) in LLVM 18 so [`DapLocator::find_lldb_vscode()`](https://github.com/eranif/codelite/blob/17.12.1/DebugAdapterClient/DapLocator.cpp#L61-L72) may not work as well as it used to.

**Comment by eranif** [comment]
@genpfault , thanks for pointing this out!
