### ISSUE TITLE
[Bug]: When moving cursor horizontally or vertically, the column/line numbers are lagging behind

### ISSUE THREAD

**Issue by yunkot** [eranif/codelite#3505]
### What happened?

When moving the cursor in CodeLite with keys horizontally or vertically, or when typing key repeatedly, the column and line numbers seem to be refreshed every 1-2 seconds. Therefore, it is practically impossible to precisely position the cursor, e.g. at specific line and column, without waiting each time until the counter is updated. I don't know of any other text editor that has this kind of input lag.

This could have be a regression after some performance optimizations in CodeLite. However, updating the cursor position is not a performance-intensive task, so in a production environment it should be updated as soon as cursor position has changed.

P.S. Despite this, CodeLite still remains sluggish, to a point of being unusable on Raspberry PI 5, when trying to edit any non-trivial source code files.

### Version

Commit 84dd6ddd5fd529ef53f224453d33fb6ec43fd11f.

### Operating system

Linux Mint 22 (Ubuntu 24.04) / Xfce / X11 / wxWidgets 3.2.4

**Comment by yunkot** [comment]
FYI, CodeLite revision 6eb52aaff1bb3b999001fbbf56f38bc844000c41 doesn't suffer from this.

**Comment by eranif** [comment]
This is because updating the line numbers / column is done in the `OnIdle` event. Indeed, this was done in order to avoid updating the UI while editing.

**Comment by eranif** [comment]
Should be fixed in https://github.com/eranif/codelite/commit/0306ef6de28d7f190f9eee330c70aab96b040418.

Another performance tip, make sure to **disable** the option: `Settings -> Preferences -> Guides -> Highlight current line number`

**Comment by yunkot** [comment]
I can confirm that this issue is fixed.
