### ISSUE TITLE
[Question] wxflatnotebook

### ISSUE THREAD

**Issue by Jarod42** [eranif/codelite#3506]
It is no longer used from what I see.
And, as I understand, it has not been integrated to WxWidgets.

Do you want to make a dedicated repo for it? (I can do it, preserving history as much as I can)
Can I remove it from Codelite repository?

**Comment by eranif** [comment]
Yes, its not used. It was one of the first components I wrote for wxWidgets which I then used incorporated withing CodeLite (I think I used SVN and CodeLite was hosted at Sourceforge when I did that 😄 )
