### ISSUE TITLE
[Bug]: Fedora 41 RPM not working

### ISSUE THREAD

**Issue by intra0** [eranif/codelite#3533]
### What happened?

the rpm package was working fine on 40, but since I've updated to 41, its broken

when I try to use the fedora 41 package listed on codelite's website it fails to install. through gui a rpm window gets instantly created then destoryed and on terminal you get this output and then its not installed
```
fedora@fedora:~$ sudo rpm -Uvh https://repos.codelite.org/rpms-17.0/fedora/codelite-17.0-2.fc.src.rpm
Retrieving https://repos.codelite.org/rpms-17.0/fedora/codelite-17.0-2.fc.src.rpm
Updating / installing...
   1:codelite-17.0-1.fc41             ################################# [100%]
fedora@fedora:~$ 
```

I can successfully install the fedora 39 package but I can't launch it and I dont know how to fix the libtiff.so.5 dependency (was not an issue on fedora 40), I tried googling how to do so but came up with no good answers. I do have libtiff and libtiff devel installed on my system
```
fedora@fedora:~$ sudo   rpm -Uvh https://repos.codelite.org/rpms-17.0/fedora/39/codelite-17.0-1.fc39.x86_64.rpm
Retrieving https://repos.codelite.org/rpms-17.0/fedora/39/codelite-17.0-1.fc39.x86_64.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:codelite-17.0-1.fc39             ################################# [100%]
fedora@fedora:~$ codelite
codelite: error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such file or directory
fedora@fedora:~$ 
```

### Version

17.0.0

### Operating system

Linux

### Steps to reproduce

Try installing the rmp in a fedora 41 vm i guess??

**Comment by dghart** [comment]
> fedora@fedora:~$ sudo rpm -Uvh https://repos.codelite.org/rpms-17.0/fedora/codelite-17.0-2.fc.src.rpm
> Retrieving https://repos.codelite.org/rpms-17.0/fedora/codelite-17.0-2.fc.src.rpm

You seem to have installed the source rpm (srpm) instead of the binary. Did you mean that, or was it a copy/paste error?
It should have been[codelite-17.0-1.fc41.x86_64.rpm]( https://repos.codelite.org/rpms-17.0/fedora/41/codelite-17.0-1.fc41.x86_64.rpm).

**Comment by intra0** [comment]
You are correct, I did accidentally try to install the source RPM instead of the release RPM.
thats a my bad on my part. Just tried the release RPM and its working 100%

The source RPM's have more noticable links and I didn't realize the number inside the box were links to releases RPMs
![image](https://github.com/user-attachments/assets/fb286dfa-f9df-4aa6-8b8e-ebc1631d3891)
