### ISSUE TITLE
[Bug]: IDE doesn't gain focus after running a console application 

### ISSUE THREAD

**Issue by ymioni** [eranif/codelite#3538]
### What happened?

Bug report at **v17.12.0**
Running a simple application which opens the console (using cout and cin commands)
After terminating the application, codelite was supposed to gain back the focus and allow modifying the code, but it doesn't. I need to click my mouse anywhere over the IDE to resume coding.

### Version

Other

### Operating system

Windows 11

### Steps to reproduce

```text
1. Open codelite
2. Write a function like this one:
#include <iostream>
using namespace std;
int main(int argc, char **argv)
{
    unsigned int input {0};
    while ((input == 0) || (input > 100))
    {
        cout << "Enter a number between 1 and 100: ";
        cin >> input;
    }
    return 0;
}
3. Run the application
4. A console is opened, prompting the user to enter a number
5. Once the job is done, the user is requested to "Press any key to continue..."
6. Press any key
7. Console vanished and then we see again codelite IDE visible completely
8. Try to type something (as if you want to change the code). It FAILS!
9. Need to mouse-click anywhere over the IDE to gain back the ability to modify the code
```

**Comment by eranif** [comment]
This can't really be fixed. The problem is that the external terminal is now "owned" by CodeLite and we can't really control which app will get the focus after it closes

**Comment by ymioni** [comment]
Hi Eran,
Is there a way to hold the IDE's handler and resume after the console is closed, using the platform's API's **SetForegroundWindow** ?

**Comment by ymioni** [comment]
Hi Eran,
I'm using Windows 11 (23H2)
codelite v17.12.00
The console is opened by codelite, so I guess I'm using the new one

**Comment by eranif** [comment]
OK, if I set the default terminal to "Terminal" on Windows 10 - then I get the same behavior (no focus)

**Comment by ymioni** [comment]
https://github.com/user-attachments/assets/b9c4b04f-09f1-45d6-9ba5-2d907e2b750e

**Comment by ymioni** [comment]
![image](https://github.com/user-attachments/assets/4472bc71-e8e1-4797-bce7-3746a654d21c)
**Bingo!** Now, the question is if that's the suggested solution, or maybe you can improve codelite to cope with Windows Terminal

**Comment by eranif** [comment]
I added a call to `Raise` (which actually calls : `SetForegroundWindow` under the hood on Windows)

**Comment by ymioni** [comment]
Sounds good. So I guess that will be implemented in the next version of codelite?
