### ISSUE TITLE
Unable to build wxWidgets when building Codelite from sources see https://docs.codelite.org/build/build_from_sources/

### ISSUE THREAD

**Issue by noeldiviney** [eranif/codelite#3541]
### What happened?

I am building Codelite  from sources by following the instructions on https://docs.codelite.org/build/build_from_sources/
* Prepare your working environment       completed successfully
* Build wxWidgets from sources              fails as follows

C:/esdcl/msys64/clang64/include/c++/v1/string:820:42: error: implicit instantiation of undefined template 'std::char_traits<unsigned int>'
  820 |   static_assert(is_same<_CharT, typename traits_type::char_type>::value,
      |                                          ^
C:/esdcl/wxWidgets/include/wx/ustring.h:41:42: note: in instantiation of template class 'std::basic_string<unsigned int>' requested here
   41 | class WXDLLIMPEXP_BASE wxUStc++: ring: public std::basic_string<wxChar32>warning:
      | -lpthread: 'linker' input unused [-Wunused-command-line-argument]                                         ^

The full Build Log  is attached
[wxWidgets-build-log-latest.txt](https://github.com/user-attachments/files/17912206/wxWidgets-build-log-latest.txt)

### Version

Self compiled

### Operating system

Windows 10

### Steps to reproduce

```text
*  Download and install MSYS2, set the installation folder to C:\esdcl\msys64
*  Open MSYS2 terminal, and install the following packages:
   pacman -Sy git openssh  mingw-w64-clang-x86_64-gdb mingw-w64-clang-x86_64-toolchain  \
               mingw-w64-clang-x86_64-python3 mingw-w64-clang-x86_64-cmake              \
               mingw-w64-clang-x86_64-libffi mingw-w64-clang-x86_64-jq                  \
               mingw-w64-clang-x86_64-libxml2 mingw-w64-clang-x86_64-llvm-openmp unzip
*  Next, still in the MSYS2 terminal, Add the /clang64/bin to your ~/.bashrc and source it:
   echo 'export PATH=/clang64/bin:$PATH' >> ~/.$(basename $SHELL)rc
   . ~/.$(basename $SHELL)rc
*  Open MSYS2 terminal, and clone wxWidgets sources:
   git clone https://github.com/wxWidgets/wxWidgets
   cd wxWidgets
   git submodule update --init

*  For a Release build of wxWidgets, run this:
   mkdir build-release
   cd build-release
   cmake .. -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release                 \
            -DwxBUILD_DEBUG_LEVEL=0                                        \
            -DwxBUILD_MONOLITHIC=1 -DwxBUILD_SAMPLES=SOME -DwxUSE_STL=1    \
            -DCMAKE_INSTALL_PREFIX=$HOME/root
   mingw32-make -j$(nproc) install

*  mingw32-make fails to build wxWidgets see in "What Happened?" above for full details 

Appreciate your help.
Noel Diviney
```

### Relevant log output

```shell
See attachment "wxWidgets-build-log-latest.txt" in "What happened?" above
```

**Comment by eranif** [comment]
Not a CodeLite bug.  wxWidgets can not be build with the latest clang-19 compiler. 

You should manually modify wxWidgets sources.  This is how I do it in our CI workflows:

```bash
mkdir -p build-release
cd build-release
cmake .. -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release                 \
            -DwxBUILD_DEBUG_LEVEL=0                                        \
            -DwxBUILD_MONOLITHIC=1 -DwxBUILD_SAMPLES=SOME -DwxUSE_STL=1    \
            -DCMAKE_INSTALL_PREFIX=$HOME/root
sed -i "s/typedef wxUint32 wxChar32;/#include <uchar.h>\n    typedef char32_t wxChar32;/g" ../include/wx/defs.h
mingw32-make -j$(nproc) install
```

**Comment by noeldiviney** [comment]
Many thanks Eran
Noel
