### ISSUE TITLE
The font size isn’t saved after being modified

### ISSUE THREAD

**Issue by eranif** [eranif/codelite#356]
Steps to reproduce:
1. Open a file
2. Hold CTRL and scroll up with the mouse wheel to change the size font
3. Close the file, then reopen it
4. Notice that the font size has been restored to its size in 1.

This is really annoying since some font sizes can only be reached by using the mouse scroll. As a consequence, an user has to change the font size of all its files everytime he opens them.

**Comment by Crafter213** [comment]
When using the setting eranif wrote,
it is only possible to use whole numbers for the front size. (Windows 7, codelite 8.0)
With CTRL + mouse wheel you can get font sizes in between. Is it possible to set these sizes as default?

**Comment by zedxxx** [comment]
+1
