### ISSUE TITLE
easy way to add link library projects as dependencies in the same workspace

### ISSUE THREAD

**Issue by eranif** [eranif/codelite#400]
A way to quickly link library projects in the same workspace is a common feature in many IDE/Language environments (MSVC/C++/C#, Eclipse/C++/Java, Netbeans/Java/C++), it would be really nice to have it in codelite as well

The feature consists of a way to select between libraries in the current workspace, add to the list of current dependencies. The resulting libraries are automatically linked in the resulting target, and build checks that the dependencies are up to date (without relying on the manually set build order.. list)

discussion reference: http://codelite.org/forum/viewtopic.php?f=11&t=1963

**Comment by TurkeyMan** [comment]
I've just stumbled upon this problem, and I'm astonished there's no support for this...
What's the current workflow? If a workspace has multiple projects, how do I assure they are build in the correct order (dependencies built first), and then that the final builds appropriately link against their dependencies?

**Comment by eranif** [comment]
In CodeLite you build projects not workspace.
The workflow is:

* Set one project as the active project (usually, its the project with the end build target)
* To setup dependencies, right click on the project and select `Build Order`
* Build that project (when hitting F7, this is the project that will get build)

**Comment by TurkeyMan** [comment]
I see you closed this issue, which you created yourself over a year ago... does that mean you've had a change of opinion on this?

**Comment by eranif** [comment]
The issues were migrated from SourceForge automatically using a script I wrote, so its not really an issue I think we should implement.

I don't believe in keeping issues open if I, David or Frank (the people who have git commit rights) are going to implement them - and this is why I closed it (because non of us is going to implement this issue)

Ofc, like any other GitHub projects, if someone thinks this issue is important enough to be included in CodeLite, he / she can always submit a Pull request
