### ISSUE TITLE
Turn off code completion, please?

### ISSUE THREAD

**Issue by eranif** [eranif/codelite#416]
Need to be able to turn off code completion. Cannot find an option or help on how to do this anywhere.
Is driving me GODDAMN NUTS.

**Comment by anatooly** [comment]
Good UI solution for this
![phpstorm-inspections-php-html](https://user-images.githubusercontent.com/317380/35213629-f0b36952-ff66-11e7-94ea-11fd4319e473.png)
![phpstorm_inspections](https://user-images.githubusercontent.com/317380/35213636-f2e03778-ff66-11e7-9444-0e2346692134.png)
