### ISSUE TITLE
Visual Studio 2013 solutions import into empty workspace

### ISSUE THREAD

**Issue by Nathilion** [eranif/codelite#460]
In my company we're using Visual Studio 2013 for our C++ projects. But with a recent decision to move to Linux I was tasked to find out means of importing our projects without the hassle of creating new projects. I came across CodeLite and its ability to import VS solution files.

However, when I try to import a VS2013 solution I end up looking at a newly created workspace but with no projects and files imported. However, there are new CodeLite (workspace) related files and folders in the VS solution directory. A dummy VS2008 project imported just fine though. 

This behaviour occured in both the Linux and Windows versions of the CodeLite IDE. For both OSes I downloaded version 5.4. I ran it on Kubuntu 14.04 and Windows 8.1, both with the most recent updates. I could not find anything about an error in log files either.

I would like to end this issue with a question: "Are VS2013 C++ solutions supported?"

**Comment by lpoujoulat** [comment]
Well, I suppose I revive an old subject:
We are in the process of trying out replacements for Visual C++ 2010. Importing a solution with CodeBlocks worked like a charm, with even migration to GCC. When trying with CodeLite 6.1.1, It ends up with an empty workspace and no message at all. Is there something I'm missing ?

**Comment by eranif** [comment]
Hi,
I simply don't have time to learn the MSVS solution file format and convert it into CodeLite project format. Patches are most welcome. If anyone is willing to implement it, I will be more than happy to assist on CodeLite internals. IIRC, the current converter was implemented for VS7 files so it is probably useless now days

**Comment by eranif** [comment]
This https://github.com/eranif/codelite/issues/742 should have addressed and fix this issue
