### ISSUE TITLE
Feature Request - Build projects dependant on a Library

### ISSUE THREAD

**Issue by ColinTaylor** [eranif/codelite#462]
Don't know if this is possible, but I'd like to suggest a feature be added to Codelite to build all projects that are dependant on a selected project. So for example if you use static libraries and make a change to that library, it'd simplify the job of find all projects that should be rebuilt.

**Comment by eranif** [comment]
Did you attempt to use 'Build Order' (right click on your project->build order)

**Comment by ColinTaylor** [comment]
Hi Eran

Yes I use Build Order on every project. Maybe my workspace organisation
isn't ideal but I have about 120 projects in my main workspace and
sometimes, after changing a file in one of the static libraries containing
reusable components, I can forget to rebuild all projects affected by that
change. Yes I can (and do) use Build Workspace, but that takes quite a
while to complete. It would have been useful to be able (e.g.) to right
click on the static library project and click 'Build all projects that use
this library'. Since you've closed this issue, I'm guessing this isn;t
going to be implemented.

Cheers, Colin

**Comment by eranif** [comment]
Indeed, I am doing cleanup and closing issues that I will simply have no time to implement myself (and therefor, I don't see why they should be kept open)

Ofc, pull requests are most welcomed :)

**Comment by ColinTaylor** [comment]
I'm not sure what a 'pull request' is, I'm guessing it's one where I make
the code changes and submit them to you for integration? If so, I doubt my
coding ability would be good enough to implement such a change :-)

**Comment by eranif** [comment]
Just for FYI: https://help.github.com/articles/using-pull-requests/

**Comment by ColinTaylor** [comment]
Thanks a lot for the info. I don't actually use GitHub so am definitely a
long way from creating a pull request!
