### ISSUE TITLE
want fuzzy query in quick outline

### ISSUE THREAD

**Issue by BrentHuang** [eranif/codelite#478]
In the "Open resource" dialog, I see very useful 'fuzzy query'. When I only input some characters with any sequence, codelite lists some matched files. I can even input blank between words, that's great!

But in the "quick outline" dialog, there is no  'fuzzy query'.  It's the greatest regret.

**Comment by eranif** [comment]
Not enough resources to implement this. If you really need this, you can submit a pull request
