### ISSUE TITLE
local rename bug

### ISSUE THREAD

**Issue by BrentHuang** [eranif/codelite#483]
if (num > 0)
{
    int a = 1;
}
else
{
    int a = 2;
}

When I rename the local variable 'a' in the else branch, the variable 'a' in the if branch also be renamed. Seems to be a bug.

**Comment by Cinchspark** [comment]
This definitely is a problem with parsing the code itself...
I have this idea on how to fix it:

1) For each curly brackets block, make local variables local.
2) Recognize references to global/higher scope variables.
3) If local variable, only edit local variable

Now, I gotta download the source code...
