### ISSUE TITLE
'Platforms'

### ISSUE THREAD

**Issue by TurkeyMan** [eranif/codelite#509]
In Visual Studio, there is a parallel configuration selector box called 'Platform'.
When working on cross-platform projects (video games consoles, etc) it's very convenient to be able to switch platform in an instant.
Currently, the workaround is to create a huge matrix of 'Platform|Config' configurations, and when you support a few platforms the square nature of the matrix means the configuration list gets very long very quickly, making it very annoying to work.

Maybe this could be hacked in very easily by supporting the same 'Platform|Config' naming convention that Visual Studio uses, and just parse for the '|'  to populate separate Platform and Configuration selector boxes?

**Comment by eranif** [comment]
Cleaning up features that we don't have enough resources to implement.
Pull requests with fixes / enhancements will be most welcomed

Eran
