### ISSUE TITLE
Use CMAKE_INSTALL_PREFIX instead of PREFIX

### ISSUE THREAD

**Issue by mojca** [eranif/codelite#519]
Please don't use PREFIX to determine where to install CodeLite.

CMake supports CMAKE_INSTALL_PREFIX out-of-the-box. You can probably use its value, but there is no need for you to worry about setting prefix. Introducing variables like PREFIX just adds to confusion and breaks "default builds". Other variable like CL_INSTALL_LIBDIR should also not be needed.

I see that you have some code for CMAKE_INSTALL_LIBDIR with a condition for a version of CMake around 2.8.7. I would suggest simplifying the code and simply requiring CMake 2.8.7 or 2.8.8 or whatever (if that is the version that simplifies things). That version of CMake was released in 2011. You already depend on C++11 which is "hardly supported" on anything but the latest compilers. Similarly, wxWidgets 3.0 is only available in the latest Linux distributions. I don't think that trying to support CMake 2.6 or alike makes much sense when you need other latest dependencies anyway.

**Comment by eranif** [comment]
You can't build CodeLite with a compiler that does not support C++11

**Comment by mojca** [comment]
This ticket wasn't about C++11. It was about `PREFIX` vs. `CMAKE_INSTALL_PREFIX`. Why doesn't the installation simply respect `CMAKE_INSTALL_PREFIX`?

I see that it's used somewhere, but then it's burried inside
```
if (CMAKE_VERSION VERSION_GREATER 2.8.7 AND ( UNIX AND NOT APPLE ))
```
which would probably be false on Mac.

It is true that I didn't test the changes yet, but did you actually change anything with respect to `CMAKE_INSTALL_PREFIX`?

**Comment by ben-ben** [comment]
Please change `PREFIX` to `CMAKE_INSTALL_PREFIX`. This is right way to do in `cmake`. And also, the `PREFIX` variable does not show up in `ccmake`. Some people use `ccmake` instead of `cmake` to set all variables and options.
