### ISSUE TITLE
New class wizard - store files in different folders on the hard drive

### ISSUE THREAD

**Issue by mpreu** [eranif/codelite#522]
Hi,

when I have a project structure on the hard drive like this:

```
--include\folderA
--include\folderB
--src\folderA
--src\folderB
```

and I want to create a new class, the generated files are stored in one folder. So I have to remove them from the project, move them to the correct folders and re-import them to have the correct structure. I want to have the same project structure in the project and on the hard drive as well.

Is it possible to add the option for specifying seperate file paths for header and source files when creating a new class (and considering the information of the subfolders in the generated include string in the header files)?

**Comment by ltqsoft** [comment]
It is better to move the New Class wizard into the project context menu instead of virtual folder. And inside the wizard user can choose where to store header file and source file (if path macros are usable there it should be great).
