### ISSUE TITLE
Support for custom code completion / coloring

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#532]
Hi Eran!

Since we recently started using QtQuick for our development I'm working with a lot of QML files.
I have a custom lexer set up for that and it works nicely, but I wondered what would have to be
done to integrate it even better.

The coloring works using the Keywords I gave the lexer, but it would be nice to have code completion
working for them as well. I know that I can enable that, but that is a general setting and I prefer to
leave it turned off for C++.
In addition it would be nice to have a feature like other editors have, which simply lists all found
"words" for completion. Comments are the same as C++, but my shortcuts for commenting
selections do nothing, as it's not a C++ file.

I'm not really sure whether some of this may be a shortcoming of Scintilla. Creating the lexer took
me some time to get it done right, starting with finding the correct ID for the lexer.

I suppose this is a very general and "almighty" feature to request, but adding new filetypes isn't
as easy as it could be. Maybe creating a special plugin type for that would help. I started writing
one that would handle the code completion, but put it on hold right now, as I guess it could be more
generalized for other filetypes as well.

Maybe treat this as a suggestion, not a real feature request :-)

Regards,
  René

**Comment by eranif** [comment]
Closed. The above is now supported :)
