### ISSUE TITLE
 Contractions not recognized by spelling checker, add checking for hex numbers

### ISSUE THREAD

**Issue by Gibbon1** [eranif/codelite#545]
words like doesn't and aren't etc are flagged as misspelled.

I'm suspecting because the apostrophe causes the full word to not be tokenized

Also a code specific enhancement would be to check for hex numbers such as 0x1234 it appears decimal numbers aren't flagged.

**Comment by AJenbo** [comment]
Commit is a32b5c046cfd09c69ec6fdfce83818cb03b093ed, closing issue
