### ISSUE TITLE
Terminal won't launch with CodeLite on OS X 10.10

### ISSUE THREAD

**Issue by JacksonPeirce** [eranif/codelite#579]
I can't for the life of me get terminal to launch when selecting Build and Run Project in CodeLite. Please advise.

**Comment by Scoobadood** [comment]
The actual problem here is that cod elite does't tolerate spaces in directory names. Hence the 'can't open file' message when it tries to access a file in the Application\ Support directory

**Comment by mosmonov** [comment]
Hello there,
Does anyone can help me with this issue? I am getting an error in the following statement:
codelite-terminal error could not set current working directory (error 2: No such file or directory)
I am trying the basic sample when I open cpp, I have been using it for a long time, but yesterday I updates my OS system and all of a sudden codelite started acting crazy. It was not showing me the right answer etc.
