### ISSUE TITLE
No code-completion for method local variables

### ISSUE THREAD

**Issue by lukriv** [eranif/codelite#591]
I have similar issue with code-completion as in issue number #116, but this problem is with method local variable. I install Codelite version 7.0 BETA over version 6.1.1 (because of same issue) and first time after installation the code-completion seems to be working correctly, but when I want use code-completion second time, no local variables was shown to me as well as the methods for the local variable wasn't shown in code-completion menu.

**Comment by eranif** [comment]
Fixed in git master
