### ISSUE TITLE
Goto declaration don't work on function parameter

### ISSUE THREAD

**Issue by eranif** [eranif/codelite#6]
The features, include [Goto implementation], [Goto declaration] and [Find reference], won't work if the variables are declaration at function parameters, but they work fine on the local, global variables or preprocessors.
As the following sample code, [goto declaration] doesn't work on "para", and [Find reference] will find 0 result.

```
void hellofunction(int para)
{
para = 0;
}
```

**Comment by Dzenly** [comment]
Why this bug is closed? 9.0.2 has the same behaviour. If this is duplicate, please, provide here the link for original bug report.

**Comment by eranif** [comment]
These bug is closed because there is no one to implement it.
I am currently out of resources to handle this bug (I am busy fixing other CodeLite bugs/features which have higher precedence over this one)
Please feel free to contribute by fixing this and sending a pull reuqest
