### ISSUE TITLE
Multiple select (with find next/prev) no longer has a button on quickfind bar.

### ISSUE THREAD

**Issue by caibbor** [eranif/codelite#609]
The quickfind bar used to have a checkbox for adding the next find to the selection. (This is "searchFlags" with "kSearchMultiSelect" in the current sourcecode ).

(bonus: there needs to be a "select next" and "select previous" menuitem in the edit menu)

I noticed this after doing a git pull and attempting to merge my branched with the latest master branch. This searchFlags feature is also not functioning properly at the moment (I've got a menuitem to do what the checkbox mentioned above used to do), but one thing at a time. You'll see how it behaves once you get the checkbox back in there.

The expected behavior is to do the basic find next/prev except retaining the previous selection under a different caret.

check out quickfindbar.cpp around line 246 in function QuickFindBar::DoSearch()

**Comment by caibbor** [comment]
This is still a problem in 7.0.1.

**Comment by caibbor** [comment]
This s still broken in 8.0

**Comment by eranif** [comment]
In 8.1 (the current git master) this is implemented using keyboard shortcut.
- Select a word in the editor
- Click `Ctrl-K` to add the next selection
- Click `Ctrl-Shift-K` to select all
