### ISSUE TITLE
GDB breakpoints disappearing

### ISSUE THREAD

**Issue by ibell** [eranif/codelite#610]
In the main file (in the main() function), sometimes when I set a breakpoint, the next time the program is run, the breakpoint is deleted. It doesn't seem to happen with other files

Mingw, Windows, v7.0 weekly build

**Comment by MicBoucinha** [comment]
Hi,
lately I have been using the Attach to Process functionality (I'm creating a C DLL where I have the breakpoints, that is being used by a Java program)... and whenever I do a new attach, I always lose all the breakpoints that were set.

They stay there if I stop the debugging session, close Codelite and open it again though.

I'm using v7.1 (March 18th 2015 weekly build)

**Comment by drauthev** [comment]
I can confirm this bug as well. I set up breakpoints and when I start debugging they randomly disappear in GUI. However, gdb is still aware of them in the actual debug session.

**Comment by alex-t0** [comment]
It reproduced, https://youtu.be/CDtEoyfZT4A.

**Comment by eranif** [comment]
> It reproduced, https://youtu.be/CDtEoyfZT4A.

No its not. This thread is about GDB breakpoints, you are using LLDB. It's a different issue
