### ISSUE TITLE
Sort the locals by name

### ISSUE THREAD

**Issue by ibell** [eranif/codelite#611]
If I have a lot of variables in local scope, it can sometimes be very hard to find the variables I am interested in.  It would be fantastic if clicking the variables column name would sort the variables by name

**Comment by eranif** [comment]
Are you talking here about the debugger view?

**Comment by ibell** [comment]
Yes - sometimes I have a lot of variables in the debugger namespace and it
is hard to find the one I want.

**Comment by eranif** [comment]
Fixed

**Comment by ibell** [comment]
Thanks!
