### ISSUE TITLE
Code completion gets confused by macros.

### ISSUE THREAD

**Issue by SkyMarshal** [eranif/codelite#620]
When typing, if code completion is turned on and the user uses a preprocessor macro, the code completion will get stuck there and refuse to relinquish the up/down arrow keys until the mouse is physically clicked on the window or the tab key is pressed.

os: Windows 7 Home Premium 64 bit
version: 7.0.0 (Beta?)

**Comment by eranif** [comment]
Sorry, due to resource limitation this I will not be able to implement this.
A pull request with the suggested enhancement will be highly appreciated
