### ISSUE TITLE
Distinct icon for projects that are disabled

### ISSUE THREAD

**Issue by TurkeyMan** [eranif/codelite#625]
If you untick "Enable project" in project settings, it would be really good if that project's icon reflected that it was disabled in the workspace view. Either shade the project icon, or overlay a little 'x' or something. I think you need to know which projects are disabled at a glance.

**Comment by eranif** [comment]
Sorry, we are out of resources and filtering non crucial bugs / feature requests.
Pull request are most welcomed!

**Comment by TurkeyMan** [comment]
Oh come on, this is trivial. I'll make you an icon? :)
