### ISSUE TITLE
Codelite 6.1 is infected

### ISSUE THREAD

**Issue by BrianFONeil** [eranif/codelite#627]
Both windows downloads (direct & source forge) of codelite 6.1 are infected with a trojan. I found this out using trojan killer, my best trojan scanner. Please clean this up so that I can try the program, which looks very interesting.

**Comment by creatorfromhell** [comment]
It's probably a false detection. Of course, you can always compile it yourself if you truly feel that it's "infected with a trojan".

**Comment by eranif** [comment]
There are no Trojans in the binaries. Like the person before me commented: you can compile codelite yourself to be really sure.
