### ISSUE TITLE
Cannot find wx/setup.h

### ISSUE THREAD

**Issue by Azada123** [eranif/codelite#628]
Hi

I have just bought wxCrafter, I have tried to set up the new wxWidgets.

I have set some paths in "Settings->Common Settings->Compiler->Include Paths"

The path Im using is:

/Users/tsandberg/wxmac-3.0.2/include/wx-3.0/
/Users/tsandberg/wxmac-3.02/lib/wx/include/osx_cocoa-unicode-3.0/

the last path should direct me to the setup file, this does not seem to work.

Im making a project Executable (wxWidgets enabled)

btw My OS is Mac OS X Yosemite,

./Azada123

Torben Sandberg 
sandberg.torben@gmail.com

**Comment by eranif** [comment]
Hi,
This does problem is not related to wxCrafter, but in general its a configuration error on your side.
To create a wxCrafter project, you should use one of the wxCrafter templates

> Im making a project Executable (wxWidgets enabled)

This will only create an executable that allows you to use wxWidgets without GUI

You should not set the paths in "Settings->Common Settings->Compiler->Include Paths" manually, but instead, you should use the wx-config tool (if you use the correct template, then it should be set for you in settings->common settings->compiler->compiler options, as `$(shell wx-config --cflags...)`

So in order for this to work, you should make sure that wx-config is in your path

**Comment by eranif** [comment]
Ping.
Did my tips help?

**Comment by Azada123** [comment]
Hi

Yeah it seems the problem was i MAMP PHP ver. 5.6.2
Thanks for the help

./ Torben Sandberg

sandberg.torben@gmail.com

2015-01-28 20:02 GMT+01:00 Eran Ifrah <notifications@github.com>:

**Comment by Azada123** [comment]
hi

sorry about the last post it was of course not MAMP that was the problem,
which is used for PHP
have done a lot af that lately. It was of couse brewmaster that was the
problem it seems there is a bug
in the wxwidgets packet.

./ Torben Sandberg

2015-01-29 12:02 GMT+01:00 Eran Ifrah <notifications@github.com>:
