### ISSUE TITLE
Crashes due to file auto retag on save

### ISSUE THREAD

**Issue by lavyadrian** [eranif/codelite#631]
There are crashes occuring if you do anything when a file retag is in effect. I always enable auto retag on file saving, problem is if I interact with codelite in any way immediatly after saving the file, like if I scroll the file or open a menu or launch a compile, there is great chance codelite will crash on the spot.

**Comment by eranif** [comment]
Which version of codelite?
Which os?

**Comment by lavyadrian** [comment]
codelite 6.1 on windows 7 x64

**Comment by eranif** [comment]
I cant seem to reproduce this... do I need to setup something special? (iirc, "auto retag on file save" is ON by default)

**Comment by lavyadrian** [comment]
Well, its happening a lot here, and it only happens when the message "Retagging X.cpp/.h file" is displayed. I think its easier to reproduce if you run a compile while the message is on. The older versions didn't crash like that. Older than 6.1 that is, if it helps.

**Comment by eranif** [comment]
Can you try this weekly build (built for 64 bit windows machine, uploaded today):
http://codelite.org/downloads/codelite/weekly/wip/codelite-amd64-7.0-BETA.exe

**Comment by eranif** [comment]
Ping

**Comment by lavyadrian** [comment]
OK will try it...Sorry for the long delay, problems like you wouldn't believe...will see if it won't crash with this build

**Comment by eranif** [comment]
Please use the new codelite 7 release. 

Eran

**Comment by lavyadrian** [comment]
Oh codelite 7 huh! will do sir

**Comment by eranif** [comment]
Any updates?

**Comment by eranif** [comment]
Closed. No response from OP
