### ISSUE TITLE
double listing of function in drop down

### ISSUE THREAD

**Issue by hipnition** [eranif/codelite#632]
consider the c file containing:

static void measure(int index);

static void measure(int index)
{
    // code
}

in the drop down listing the <global> functions, measure() will be listed twice. the first occurance actually takes you to the function and the second takes you to the declaration. ideally, the function is only listed once and takes you to theimplementation.

**Comment by hipnition** [comment]
this also occurs in C++ when the class is defined in the same file as the source for the class (like when using a small non-shared class).

**Comment by eranif** [comment]
> ideally, the function is only listed once and takes you to theimplementation.

I disagree. I think that having them both _is_ the correct behavior. since the function declaration might contain information that the implementation does not have e.g. default values, static keyword and other attributes which can only be placed on the function declaration
