### ISSUE TITLE
UnitTest++ Failues crash with Default UnitTest++ Project Generation.

### ISSUE THREAD

**Issue by M-griffin** [eranif/codelite#634]
``` CodeLite 6.1.1 and MingW32-4.8.1 in Windows 7 64 bit. ```

**The issue is documented here.**
https://github.com/unittest-cpp/unittest-cpp/issues/65

**Basic's**
When running tests CHECK(true); works perfectly, but all CHECK(false); results freeze and crash all test results.  After a lot of testing and debugging i found the following fix.

**Fix**
By default CodeLite generates a unittest class example and uses:
```
#include <UnitTest++.h>

int main(int, char const *[])
{
    return UnitTest::RunAllTests();
}
```
Switching the Include file to mimic the tests provided with UnitTest++ has resolved the issue and tests are now running properly.
```
#include "UnitTest++/UnitTestPP.h"
``

**Comment by eranif** [comment]
Some comments:
The above does not work on Linux for 2 reasons:
* The apt repo installs UT++ under `/usr/include/unittest++` (note its lower case)
* The package `libunittest++-dev` does not have the file `UnitTestPP.h` 

Looking at git master for UT++ seems that we should include ``UnitTest++.h` and it will internall include ``UnitTestPP.h` if needed

Notice that the following does work for me on Linux:
`#include <unittest++/UnitTest++.h>`

**Comment by M-griffin** [comment]
The question is not if it works in Linux.  The problem is that it has issues in Windows and MingW32.

If you open ```UnitTest++.h``,  it's useless and points to ```UnitTestPP.h```.  So I suggest using ```UnitTestPP.h``` outright to avoid cross platform issues and so other users don't waste an entire day trying to hunt down why it's crashing and freezing.  Thanks.

**Comment by eranif** [comment]
in any case my fix should work for both OSs

**Comment by M-griffin** [comment]
**That would be a better fix.**
Using ```#include <unittest++/UnitTest++.h>```  instead of just ```#include <UnitTest++.h>``` seems to do the trick.   Thanks for looking into this so quickly!  Love the program.

**Comment by eranif** [comment]
and this is the fix I committed earlier today ...
