### ISSUE TITLE
Bad $PATH value on Mac with custom build

### ISSUE THREAD

**Issue by Razish** [eranif/codelite#638]
Codelite version: 7.0 weekly
OS: Yosemite
Build tool: SCons (via brew)

I'm using SCons as my build tool (located in `/usr/local/bin/scons`), so I've set my custom build command as `scons -Q debug=1`.
When running on Mac with latest Codelite, the output window shows:
![](https://dl.dropbox.com/s/5r69keh2r0sbkoe/Screenshot%202015-02-03%2018.13.12.png?dl=0)
This works fine with the same project on Windows and Linux.

If I run `scons -Q` from a terminal, it finds the binary correctly as my `$PATH` is:
`/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin`
If I use `echo $PATH` as my custom build command, my `$PATH` is:
`/usr/bin:/bin:/usr/sbin:/sbin:/Users/tex/Downloads/codelite.app/Contents/MacOS`

If I attempt to set the $PATH manually via: Settings -> Environment Variables -> `PATH=/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin` I still receive the `/bin/sh: scons: command not found` error.

If I set my custom build command to `/usr/local/bin/scons -Q` it works fine, but this is obviously not desirable.

My project can be found [here](https://github.com/Razish/xsngine)

**Comment by eranif** [comment]
Hi,
I just installed `scons` using `brew`, cloned your repository and launched codelite and hit the build button
It worked...

```

MESSAGE: Entering directory `/Users/eran/devl/xsngine/src'
/bin/sh -c 'scons -Q debug=1'
----------Building project:[ xsngine - Debug ]----------
Building for Darwin 64 bits (gcc 4.2.1, python 2.7.2), debug symbols, SSE, 8 threads
git revision: 0836334
Suggest creating a symlink: "ln -s xsn.x86_64 xsngine"
scons: building associated VariantDir targets: build/debug/gcc/64 XSClient/build/debug/gcc/64
 compiling: XSClient/XSClientGame.cpp
 compiling: XSClient/XSClient.cpp
warning: unknown warning option '-Wlogical-op'; did you mean '-Wlong-long'? [-Wunknown-warning-option]
In file included from XSClient/XSClientGame.cpp:1:
./XSCommon/XSCommon.h:8:10: fatal error: 'cstdint' file not found
#include <cstdint>
```

(Ignore the errors as we don't really care about them now, just to see that it works)
Note that I have started codelite from the command line (via Terminal)

I will try again, but this time I will open CodeLite using the desktop icon

**Comment by eranif** [comment]
I just tried it while launching CodeLite by double clicking the icon the desktop, at first it did not work
However, updating the PATH environment variable like this:
`PATH=/usr/local/bin:$PATH` in settings->environment variables, worked.

Can you try with the latest CodeLite weekly build? ( I have uploaded one on Feb 12 ), see here:
http://codelite.org/downloads/codelite/weekly/codelite.app.zip

**Comment by Razish** [comment]
With the latest build, I can confirm running CodeLite via `open codelite.app` results in the PATH being set correctly, however double-clicking the app still results in "command not found" even after setting the environment variable from within CodeLite.

I'm not familiar enough with Mac to know why the environment is not set up correctly when launched from outside the terminal =\

**Comment by eranif** [comment]
This is strange, because I have tried both ways and both ways worked for me when I set the PATH in the environment variables.
Did you try to set it as I did? i.e. like this: `PATH=/usr/local/bin:$PATH`
I doubt it will help, but I have no idea why this is happening only on your box

**Comment by Razish** [comment]
Yes, that is what I tried. I'll try removing all traces of CodeLite and scons then try again.

**Comment by eranif** [comment]
No, I have an old Mac 10.8
