### ISSUE TITLE
set active project not working correctly

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#639]
Hi Eran,

I have problem setting the active project.
If I change it using the combo box or by double clicking the tree item, the entry will be displayed bold,
but clicking the settings icon I still get the settings of the previous active project.
I have to explicitly right click and use the context menu to access the correct settings.
I'll attach a screenshot. The settings were shown hitting the settings button.

Regards,
  René

![activeproject](https://cloud.githubusercontent.com/assets/1535691/6058342/8fdc5390-ad26-11e4-98d0-ea2febb8745a.png)

**Comment by eranif** [comment]
Not a really a bug, but change in behavior (check the tooltip, it was adjusted)
the settings button now open the settings of the **selected** project (as opposed to the **active** project)
Note that the settings dialog a modeless dialog, i.e. you can simply select the project you want from the tree view while the dialog is opened and it will adjust itself (so there no need to use the context menu)

**Comment by upCASE** [comment]
Hmm, ok. I expected the old behaviour. BTW: the tooltip reads "open active project settings" ;-)
