### ISSUE TITLE
Invoking codelite makefile generation from the command line

### ISSUE THREAD

**Issue by Kludgy** [eranif/codelite#642]
This is something that I'd find very useful for handing off builds to continuous integration. In fact, instead of dragging all of Codelite into a CI system, how does the source code stand in terms of extracting just the project parser and makefile exporter into a command line tool?

Cheers!

**Comment by eranif** [comment]
This tool already exists. Its called `codelite-make` and it is installed with CodeLite 

For example, to build the configuration `Release` of project `wxcrafter` from a workspace named `wxcrafter` you run it like this:

`codelite-make --workspace=.\wxcrafter.workspace --project=wxcrafter --config=Release --execute ` 

here is the complete usage:

```
Usage: codelite-make [/h] /w <str> /c <str> [/d <str>] [/p <str>] [/v] [/e]
  /h, --help            show this help message
  /w, --workspace=<str> codelite workspace file
  /c, --config=<str>    configuration name to generate
  /d, --command=<str>   which command to run? possible values: build, clean or rebuild. The default is to build
  /p, --project=<str>   project to build, if non given codelite will build the active project
  /v, --verbose         Run in verbose move and print all log lines to the stdout/stderr
  /e, --execute         Instead of printing the command line, execute it
A makefile generator based on codelite's workspace
```

**Comment by Kludgy** [comment]
Fantastic thanks for pointing this out!

**Comment by flederwiesel** [comment]
Voting 1 UP!

**Comment by sk-jame** [comment]
> project to build, if non given codelite will build the active project
But how rebuild all projects in workspace?

**Comment by eranif** [comment]
@sk-jame  please open a separate feature request to allow rebuilding the entire workspace.
