### ISSUE TITLE
CODELITE 7

### ISSUE THREAD

**Issue by dgu123** [eranif/codelite#644]
Dear Team
the latest codelite doesnt work properly on ubuntu trusty, the compile times is infinite, freeze my pc..it use to be super fast and fine before the release

**Comment by eranif** [comment]
This is strange, since I am developing CodeLite on Ubuntu 14.04 (trusty) with CodeLite itself and it works just fine.
Do you have any logs? (maybe showing 'top' of which process consumes the memory / CPU)
Build log will also be great

**Comment by eranif** [comment]
I just tried a clean install of codelite on a VM 14.04/64 bit and it works with no problems (I compiled codelite itself)

**Comment by dgu123** [comment]
Hello Eran

when i use a worksapce build with the previous one , i have this problem, i recreated a new one and it s now working fine !

**Comment by dgu123** [comment]
Sorry Eran , i get scared, i was rebuilding as well the tools from scratch

**Comment by eranif** [comment]
So, is the problem solved for you?

**Comment by dgu123** [comment]
Hello Yes it is ,
never load a workspace build from the previous version and it s sper fine ,
best IDE

**Comment by eranif** [comment]
Thanks!
Closing the bug
