### ISSUE TITLE
Installation doesn't work on Ubuntu 14.04 - Dependency resolution problem

### ISSUE THREAD

**Issue by actcontpr** [eranif/codelite#645]
Can't install codelite on Ubuntu, even with the Ubuntu sources added for codelite.

I get the following dependency resolution errors:

Die folgenden Pakete haben nicht erfüllte Abhängigkeiten:
(The following packages have unresolved dependencies)

codelite: Depends: libgcc1 (>= 1:4.1.1) but 1:4.9.1-0ubuntu1 is supposed to be installed
          Depends: zlib1g (>= 1:1.2.0) aber 1:1.2.8.dfsg-1ubuntu1 soll installiert werden

**Comment by dghart** [comment]
Hi,
>Can't install codelite on Ubuntu

Which CodeLite version are you trying to install? The latest, which is 7.0?

>even with the Ubuntu sources added for codelite.

I'm not sure what you mean by that...

Which versions of libgcc1 and zlib1g *do* you have installed (if any)? I have 1:4.9.1 and 1:1.2.8, which are available for trusty (obviously), and are >= 1:4.1.1 and 1:1.2.0

Regards,

David

**Comment by eranif** [comment]
Make sure that you don't confuse between CodeLite that we (codelite.org) provide and the one that comes from the official repositories of Ubuntu.

Make sure you follow the steps as described here:
http://codelite.org/LiteEditor/Repositories#toc1

Pay extra attention to the warning message that suggest to purge any old version:
`sudo apt-get purge codelite codelite-plugins`

Eran

**Comment by actcontpr** [comment]
Ok, some clarifications: I've got Ubuntu 14.04 LTS and the version I'm installing is 7.0.1 - so it must be the one that you provide, since the other Version for Codelite is 2.8.something.

Should I use backports or can I use codelite with those older libs? I do not want to enter backport hell.

**Comment by actcontpr** [comment]
... How about a static linked version? You know, a simple binary to drop in and install? ... Crazy idea?

**Comment by dghart** [comment]
>the version I'm installing is 7.0.1 - so it must be the one that you provide

Yes indeed.

>can I use codelite with those older libs?

But why would you want or need to? I built the package against the standard trusty versions of those libs. Again, which versions of libgcc1 and zlib1g do *you* have installed?

**Comment by eranif** [comment]
> ... How about a static linked version? You know, a simple binary to drop in and install? ... Crazy idea?

This is not acceptable on Linux and we probably won't implement this

**Comment by eranif** [comment]
Any progress?

**Comment by eranif** [comment]
No response. closed
