### ISSUE TITLE
Disabled text color is not adjustable (preprocessor blocks)

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#647]
Disabled text color is not adjustable

If you enable "Track preprocessor blocks" in menu: Settings/Code Completion

Disabled defines are shown with what in the help is called "disabled text" color.

The "disabled text" color is per default a dark grey - not so great is you also use a dark background - and does not seem to be adjustable anywhere ???

Seen with codelite 7.0 on ArchLinux

**Comment by eranif** [comment]
The old settings allowed you to provide a single colour for "disabled text"
My plan (already implemented locally, see attached image) is to use the same style as the "default" code, but with lightness changes (so the "disabled text" will look blurred)

![disable](https://cloud.githubusercontent.com/assets/3677711/6150019/67e4999e-b215-11e4-9cac-494cfacbdf50.png)

**Comment by uffejakobsen** [comment]
Ok, cool :-)

**Comment by eranif** [comment]
Fixed and committed

**Comment by uffejakobsen** [comment]
Hmm in the build (7.1) I just did I cannot see that it works any different than what I originally reported.
A disabled preprocessor block is still given a dark grey - no matter how it was highlighted when active

**Comment by eranif** [comment]
Make sure you have the latest git master.
It works for me on 3 different computers, here is the commit: 
https://github.com/eranif/codelite/commit/bf53803fdd25815bf21c5873272dcdf96d66f5b7

**Comment by uffejakobsen** [comment]
I just did a new build with a clean fresh git extract - still goes all grey

**Comment by eranif** [comment]
I am really clueless here... try reseting the colours:

Settings->Colours and Fonts
and click the "Default" button

Eran
