### ISSUE TITLE
Find in Files dialog box is not focused when invoked

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#649]
When opening the Find in Files Dialog box (in menu: Search/Find in Files) the dialog box is not focused.

Attempts to enter a search phrase will go into the editor window in the back - quite annoying :-)

Seen with Codelite 7.0 on ArchLinux

**Comment by eranif** [comment]
This is probably of the result of changing the FiF from Dialog -> Frame
The reason for this change is >> the focus issue: on OSX, you can "lose" it under the main window, while using a Frame I can set a flag "float-on-parent" to prevent it from going behind the main window

However, this works fine here on Linux Mint / Ubuntu at home
So I am not sure why ArchLinux is different

**Comment by uffejakobsen** [comment]
I think that the behaviour could be Desktop Environment/Window Manager dependant

On ArchLinux I'm using LXDE here (LXDE uses openbox WM behind the scenes).
Unfortunately I cannot try another Desktop Environment - due to diskspace limitation

**Comment by uffejakobsen** [comment]
Another observation: Dialogs like "Goto...", "Find Resource.." and "Quick Outline..." does NOT have the described problem.

**Comment by eranif** [comment]
This is because all of them are **modal** dialogs, while the Find In Files is a frame (which is modeless) based window

Eran

**Comment by uffejakobsen** [comment]
Ok - any reason for the special threatment with "Find In Files" ? I mean shouldn't that also be a modal dialog like the others ? or have I missed something ?

**Comment by eranif** [comment]
It was always a modeless dialog (since codelite 1.X)
The change between CodeLite 6.1 and 7.0 is that the window hosting the find in files dialog is not a wxFrame (it used to be a wxDialog)
This change (switching from wxDialog to wxFrame) caused this behavior.

I will change it into a **modal** dialog and see how it goes  ;)

**Comment by uffejakobsen** [comment]
Thanks :-) let me know if there is something that I should build and test for you

**Comment by eranif** [comment]
Sure. I am currently working on the caret line alpha issue ( I decided to replace this entire page if I am touching it ;) )

**Comment by eranif** [comment]
Fixed, please try it and confirm

**Comment by uffejakobsen** [comment]
The FiF is now focused - BUT the dialog is not resizeable - (could that be the original reason for choosing another window type ?)

The currently size of the dialog is so small that only the top of the Tabs in the Options: section are visible.

**Comment by eranif** [comment]
Fixed, a glitch when re-changing its type to wxDialog 
You can do another git pull and it will be fixed

**Comment by uffejakobsen** [comment]
Confirmed - now it works again - thanks :-)
