### ISSUE TITLE
Segmentation fault on launching Codelite 7.0 on Ubuntu 14.10

### ISSUE THREAD

**Issue by apxen** [eranif/codelite#650]
I am getting a segmentation fault on launching Codelite 7.0 (installed from the codelite repos) on Ubuntu 14.10. I ran it with gdb attached and here is the backtrace. This happens all the time. I had no issues with Codelite 6.x. Please help.

(gdb) bt
#0  __memcpy_sse2 () at ../sysdeps/x86_64/multiarch/../memcpy.S:527
#1  0x00007ffff2bc23c5 in std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::append(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff50b68ae in wxFileName::GetFullName() const ()
   from /usr/lib/x86_64-linux-gnu/codelite/libwx_baseu_unofficial-3.0.so.0
#3  0x000000000092f1a3 in void std::__unguarded_linear_insert<__gnu_cxx::__normal_iterator<clTab*, std::vector<clTab, std::allocator<clTab> > >, __gnu_cxx::__ops::_Val_comp_iter<TabSorter> >(__gnu_cxx::__normal_iterator<clTab*, std::vector<clTab, std::allocator<clTab> > >, __gnu_cxx::__ops::_Val_comp_iter<TabSorter>) ()
#4  0x000000000092ce9e in OpenWindowsPanel::SortAlphabetically() ()
#5  0x00007ffff5039c0e in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const ()
   from /usr/lib/x86_64-linux-gnu/codelite/libwx_baseu_unofficial-3.0.so.0
#6  0x00007ffff51d6218 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()
   from /usr/lib/x86_64-linux-gnu/codelite/libwx_baseu_unofficial-3.0.so.0
#7  0x00007ffff51d6606 in wxEvtHandler::SearchDynamicEventTable(wxEvent&) ()
   from /usr/lib/x86_64-linux-gnu/codelite/libwx_baseu_unofficial-3.0.so.0
#8  0x00007ffff51d668e in wxEvtHandler::TryHereOnly(wxEvent&) ()
   from /usr/lib/x86_64-linux-gnu/codelite/libwx_baseu_unofficial-3.0.so.0
#9  0x00007ffff51d6753 in wxEvtHandler::ProcessEventLocally(wxEvent&) ()
   from /usr/lib/x86_64-linux-gnu/codelite/libwx_baseu_unofficial-3.0.so.0
#10 0x00007ffff51d67b5 in wxEvtHandler::ProcessEvent(wxEvent&) ()
   from /usr/lib/x86_64-linux-gnu/codelite/libwx_baseu_unofficial-3.0.so.0
#11 0x00007ffff51d6527 in wxEvtHandler::SafelyProcessEvent(wxEvent&) ()
   from /usr/lib/x86_64-linux-gnu/codelite/libwx_baseu_unofficial-3.0.so.0
#12 0x00007ffff5e00e4f in wxWindowBase::SendIdleEvents(wxIdleEvent&) ()
   from /usr/lib/x86_64-linux-gnu/codelite/libwx_gtk2u_unofficial_core-3.0.so.0
#13 0x00007ffff5e00e78 in wxWindowBase::SendIdleEvents(wxIdleEvent&) ()
   from /usr/lib/x86_64-linux-gnu/codelite/libwx_gtk2u_unofficial_core-3.0.so.0
#14 0x00007ffff5e00e78 in wxWindowBase::SendIdleEvents(wxIdleEvent&) ()
   from /usr/lib/x86_64-linux-gnu/codelite/libwx_gtk2u_unofficial_core-3.0.so.0
#15 0x00007ffff5e00e78 in wxWindowBase::SendIdleEvents(wxIdleEvent&) ()
   from /usr/lib/x86_64-linux-gnu/codelite/libwx_gtk2u_unofficial_core-3.0.so.0
#16 0x00007ffff5c59c8f in wxFrame::SendIdleEvents(wxIdleEvent&) ()
   from /usr/lib/x86_64-linux-gnu/codelite/libwx_gtk2u_unofficial_core-3.0.so.0
#17 0x00007ffff5ca866d in wxAppBase::ProcessIdle() () from /usr/lib/x86_64-linux-gnu/codelite/libwx_gtk2u_unofficial_core-3.0.so.0
#18 0x00007ffff5b9df9e in wxApp::DoIdle() () from /usr/lib/x86_64-linux-gnu/codelite/libwx_gtk2u_unofficial_core-3.0.so.0
#19 0x00007ffff5b9e0d3 in ?? () from /usr/lib/x86_64-linux-gnu/codelite/libwx_gtk2u_unofficial_core-3.0.so.0
#20 0x00007ffff02b6b6d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff02b6f48 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007ffff02b7272 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff78bc747 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#24 0x00007ffff5bbfc55 in wxGUIEventLoop::DoRun() () from /usr/lib/x86_64-linux-gnu/codelite/libwx_gtk2u_unofficial_core-3.0.so.0
#25 0x00007ffff507ff70 in wxEventLoopBase::Run() () from /usr/lib/x86_64-linux-gnu/codelite/libwx_baseu_unofficial-3.0.so.0
---Type <return> to continue, or q <return> to quit---
#26 0x00007ffff503bf36 in wxAppConsoleBase::MainLoop() () from /usr/lib/x86_64-linux-gnu/codelite/libwx_baseu_unofficial-3.0.so.0
#27 0x00007ffff50d6ec0 in wxEntry(int&, wchar_t**) () from /usr/lib/x86_64-linux-gnu/codelite/libwx_baseu_unofficial-3.0.so.0
#28 0x0000000000550f3e in main ()

**Comment by eranif** [comment]
Try deleting your ~/.codelite folder
See if it helps

FYI: tested here on clean VM and it works without a problem

**Comment by apxen** [comment]
I had to delete ~/.codelite and the .codelite directory in my project directory. That fixed it. Thanks.
