### ISSUE TITLE
Detached workspace tabs lost - how to get them back

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#651]
Some time yesterday I detached The Outline tab from the workspace pane - in order to have it displayed togheter with the with the Workspace virtual file/dir view.

Now after several restarts it (the detached Outline view) is gone (not visible) - and I have a hard time figuring out how to get it back :-)

Any goo ideas ?

Seen with Codelite 7.0 on ArchLinux

**Comment by eranif** [comment]
Perspective -> Restore Default Layout

Eran

**Comment by uffejakobsen** [comment]
Thx :+1:

**Comment by stephenlevitt** [comment]
Hi,
I have hidden all workspace pane tabs and I cannot get them back. Restoring to the default layout has no effect. I just have an empty, grey pane.

Running CodeLite 9.0.1 on Windows 7.

**Comment by mtangoo** [comment]
Click image on the right of the works "workspace view". Its a three vertical blocks image.
then check whatever you want to be seen

**Comment by stephenlevitt** [comment]
@mtangoo Thanks for your suggestion. My entire Workspace View panel was blank after hiding all tabs (using the Windows 32-bit 9.0.1 version of CodeLite) so I could not see those 3 vertically blocks. I uninstalled this version, cleared my personal settings, and installed version 9.0.0 (I'm not sure where 9.0.1 went).

Now, I can no longer reproduce the issue, and clicking those blocks does allow me to restore the tabs.

**Comment by mtangoo** [comment]
@stephenlevitt Enjoy CL then :)
