### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by plombix** [eranif/codelite#652]
Every time i create a new "workspace" it crashes i'm on ubuntu 14.10 on a quite high perf computer ,well

**Comment by eranif** [comment]
Which codelite version?

**Comment by plombix** [comment]
the last one , by command line , after by synapticts package and finally by Ubuntu software center

**Comment by eranif** [comment]
Can you check the version please? 
From the main menu: `Help -> About` it should give you the version number

**Comment by plombix** [comment]
v2.8.0.4237

**Comment by eranif** [comment]
Like I suspected. You are using the latest... of 2010 :D
The current version of CodeLite is 7.0

Follow the instructions here: http://codelite.org/LiteEditor/Repositories#toc1 for installing CodeLite via our repository

Make sure you remove the old CodeLite before installing the new one by typing this in the command line:
`sudo apt-get purge codelite codelite-plugins`

**Comment by plombix** [comment]
sorry , all my appologies for your time , i'm now on v7  & all work fine ....

**Comment by plombix** [comment]
TY i'so dumb pfffff.....
Sorry about the time i cost you ..;
And TY again for all your work
