### ISSUE TITLE
non-free image: codelitephp/resources/php-folder-128.png

### ISSUE THREAD

**Issue by jcowgill** [eranif/codelite#653]
I found that the above image is licensed as CC-BY-NC-ND which is not a free license (no commercial use). It's probably a good idea to find a replacement image or just remove it.

Link I found: http://www.softicons.com/folder-icons/sabre-snow-black-icons-by-minimamente

**Comment by eranif** [comment]
CodeLite is a non commercial project. So I think its OK, but I will check this

**Comment by eranif** [comment]
Removed
