### ISSUE TITLE
Enabling "Track Preprocessor blocks" crashes codelite

### ISSUE THREAD

**Issue by lavyadrian** [eranif/codelite#656]
Found on codelite 7 amd64, running on windows 7.

**Comment by eranif** [comment]
Is this persistent? again, I am unable to reproduce this (its on by default here)
So unless you provide a step-by-step reproduction, I am afraid there isn't anything I can do about this

**Comment by lavyadrian** [comment]
Well, I don't know about step by step because I just did the import local settings after install, and that was enabled. But then since some ifles were open, codelite would not start but crash, until I removed the open files in the .session file. Then I knew it had to be something code completion related so I disabled preprocessor tracking and voila, it didn't crash anymore.

**Comment by eranif** [comment]
Is it possible to have the sources that caused the crash?
Maybe there is some edge case presented in these files that is not handled properly by CodeLite?
Can you create a minimal example that causes a crash?

**Comment by lavyadrian** [comment]
Providing source could be a no go unfortunatly for me... I can tell you im using c++11 with much using of the container classes, I am using glm the math library that is designed to be like glsl, freeimage library, freetype library, boost library, especially the shared_ptr stuff...
I will try with the minimal example and get back to you later. Thanks

**Comment by eranif** [comment]
Closed: could not reproduce the problem + no reproduction was provided
