### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by jonorozcoc** [eranif/codelite#662]
This program is an excellent IDE for C/C++ Projects but i need a portable version of this.

**Comment by RickCHodgin** [comment]
Sounds good. Source code's available. We'll wait for your PULL request. :-)

**Comment by eranif** [comment]
Closed. Not enough resources to implement this. If you are willing to submit a pull request, I will be happy to merge it

**Comment by thdoan** [comment]
FYI MaXiMotion claims to have made a portable version here (although based off an older version):
http://portableapps.com/node/21926
