### ISSUE TITLE
Closing an externally modified file then attempting to reload it crashes CodeLite

### ISSUE THREAD

**Issue by kchalmer** [eranif/codelite#663]
Steps to reproduce:

1. Open a file in CodeLite.
2. Switch focus away from the CodeLite window and modify the file.
3. Middle-click the file's tab to close that file (without first left clicking on the CodeLite window to gain focus).
4. Select "Reload" in the "Some files were modified outside of the editor" dialog that pops up.
5. CodeLite crashes.

Reproduced with x86-64 build of ad6ff8d83bcd604209be881bb87176d8670105f9 on Kubuntu 14.04.

Stack trace:
#0  0x000000000000006d in ?? ()
#1  0x00000000008a54bc in MainBook::ReloadExternallyModified (this=0x1a8ea70, prompt=true) at /data/src/codelite/LiteEditor/mainbook.cpp:832
#2  0x000000000081a2f1 in wxAsyncMethodCallEvent1<MainBook, bool>::Execute (this=0x2ec7c40) at /usr/include/wx-3.0-unofficial/wx/event.h:1415
#3  0x00007ffff545b7d9 in wxEvtHandler::TryHereOnly(wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#4  0x00007ffff545b813 in wxEvtHandler::ProcessEventLocally(wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#5  0x00007ffff545b875 in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#6  0x00007ffff545c8a3 in wxEvtHandler::ProcessPendingEvents() () from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#7  0x00007ffff52ebe77 in wxAppConsoleBase::ProcessPendingEvents() () from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#8  0x00007ffff5e10022 in wxApp::DoIdle() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_unofficial_core-3.0.so.0
#9  0x00007ffff5e10133 in ?? () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_unofficial_core-3.0.so.0
#10 0x00007ffff01a7ce5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff01a8048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff01a830a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff78c9447 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#14 0x00007ffff5e22f05 in wxGUIEventLoop::DoRun() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_unofficial_core-3.0.so.0
#15 0x00007ffff532ab30 in wxEventLoopBase::Run() () from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#16 0x00007ffff52ea38d in wxAppConsoleBase::MainLoop() () from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#17 0x00007ffff537649d in wxEntry(int&, wchar_t**) () from /usr/lib/x86_64-linux-gnu/libwx_baseu_unofficial-3.0.so.0
#18 0x000000000074bffc in main (argc=1, argv=0x7fffffffd6c8) at /data/src/codelite/LiteEditor/app.cpp:252

**Comment by eranif** [comment]
Fixed
