### ISSUE TITLE
New completion not fully working for includes

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#665]
Hi Eran,

the new completion seems to have a small problem with includes.
When I start typing it resolves the include path correctly, showing only
matching entries. But when I accept an entry, the complete entry is append
to the text I already typed. Like:

I entered:
#include <QtCore/QDe
I choose QtCore/QDebug from the list and this is the result:
#include <QtCore/QtCore/QDebug

I'm pretty sure this worked and should be easy to fix, as the correct entries
are listed. BTW: Great work! the new CC box is really cool!

Regards,
 René

**Comment by eranif** [comment]
Fixed
