### ISSUE TITLE
Add support for boost pretty printer

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#666]
Hi Eran,

maybe you could add support for gdb boost pretty printers.
https://github.com/ruediger/Boost-Pretty-Printer

In addition, there is a bug in the Qt printers. The helper.py file
is missing some functionality. Best update it again from https://projects.kde.org/projects/extragear/kdevelop/kdevelop/repository/revisions/master/show/debuggers/gdb/printers

Regards,
 René

**Comment by eranif** [comment]
> In addition, there is a bug in the Qt printers. The helper.py file
> is missing some functionality. Best update it again from > https://projects.kde.org/projects/extragear/kdevelop/kdevelop/repository/revisions/master/show/debuggers/gdb/printers

Maybe it will explain why all my QString are shown as empty string :/ - thanks for the info

**Comment by upCASE** [comment]
Yep, that's why I had a look at this :-)
In addition I found the printers used by QtCreator. I'll check if there are some other
useful things in them and maybe prepeare a patch.
