### ISSUE TITLE
Folder lib\gcc_lib missing during Build of CodeLite IDE.

### ISSUE THREAD

**Issue by timosperisen** [eranif/codelite#669]
Hi,

I tried to build a Windows 64 Bit Build of the most current version on Github.

## Setup :
```
- Windows 7 , 64 Bit
- CodeLite 7.0 (64 Bit, installer version)
- wxWidgets-3.1 (64 Bit from codelite.org
- tdm64-gcc-4.9.2
- codelite code: latest master sha1 id : 687e45fa76714d9d4315bbfa05ff98cdc2d64d96
```
## Issue :

When I start the build inside CodeLite after compilation of sqlite3 I received following error:
```
Executing Post Build commands ...
copy "Win_x64_Release\libsqlite3.a" ..\lib\gcc_lib
The system cannot find the path specified.
```
## Solution :

I was able to solve the issue by creating the folder ```lib``` inside the codelite-source-root and the subfolder ```gcc_lib``` inside it. After I created these everything worked fine. Maybe a step with ```md lib\gcc_lib``` needs to be added as at least windows does not seem to create those folders automatically when copying files.

**Comment by eranif** [comment]
Fixed.
