### ISSUE TITLE
problema codelite 7.0.1

### ISSUE THREAD

**Issue by detranegabriele** [eranif/codelite#671]
in codelite 7.0.1 sotto ubuntu 14.04 e 14.10 non funzionano le graffe, pertanto si è costretti a scriverle su un nuovo documento di testo, copiarle e incollarle ogni volta! vi chiedo gentilmente di risolvere..
cordiali saluti detranegabriele

**Comment by eranif** [comment]
Please open bugs in English and not in Italian - I don't speak Italian
