### ISSUE TITLE
Syntax highlight on string literals not working as expected

### ISSUE THREAD

**Issue by CrHasher** [eranif/codelite#673]
In the following example everything after the string member is highlighted as if it were part of the string:

```cpp
#include <string>

using namespace std;

struct Test
{
    Test() = default;
    virtual ~Test() = default;

    string str_{R"(Test string!)"};
};

int main()
{
    Test t1;
    return 0;
}
```

**Comment by eranif** [comment]
Yes, this was reported on the forum already see this discussion: http://forums.codelite.org/viewtopic.php?f=3&t=2847

Thanks for reporting it here, so it won't be neglected
I assume that you are using Windows / OSX (this bug does not happen on Linux)

**Comment by CrHasher** [comment]
@eranif Yes I'm using windows.

**Comment by eranif** [comment]
Upgrading to a newer version of wxWidgets (current git master)
fixes the problem

**Comment by CrHasher** [comment]
Thanks for fixing this ;)

**Comment by eranif** [comment]
It will be available in next release

**Comment by lnishan** [comment]
Great to know that you're fixing this.  
CodeLite has become my primary tools for writing C++ programs on Windows (for competitive programming as a matter of fact).  
From the bottom of my heart, I thank you for being an extremely nice and active developer : )  
I hope that some day I can be skilled enough to contribute to your awesome project : )
