### ISSUE TITLE
Curly brackets and square brackets

### ISSUE THREAD

**Issue by rabauke** [eranif/codelite#674]
Hi,

I just installed the precompiled Debian package of codelite 7.0 on Ubuntu 14.04.2 (64 bit) with unity desktop and a German keyboard. I am not able to enter curly brackets and square brackets in the main window. Keys [, ] and { are dead, pressing } opens a window »cscope: find symbol«. (Switching to English (USA) keyboard layout curly brackets and square brackets work perfectly.) How can this be fixed?

**Comment by eranif** [comment]
See the following forum discussion: http://forums.codelite.org/viewtopic.php?f=3&t=2837

This was fixed in git master
