### ISSUE TITLE
codelite-make dependencies

### ISSUE THREAD

**Issue by ntpg** [eranif/codelite#676]
It would be nice if the codelite-make tool could be dropped in to a build machine and work without requiring similar dependencies to the codelite editor. I came across these two sets of dependencies:

1. codelite-make currently has (at least) the following shared object dependencies:

libjbig.so.0
liblibcodelite.so
libplugin.so
libssh.so.4
libwx_baseu_unofficial-3.0.so.0
libwx_baseu_unofficial_xml-3.0.so.0
libwx_gtk2u_unofficial_adv-3.0.so.0
libwx_gtk2u_unofficial_aui-3.0.so.0
libwx_gtk2u_unofficial_core-3.0.so.0
libwx_gtk2u_unofficial_html-3.0.so.0
libwx_gtk2u_unofficial_ribbon-3.0.so.0
libwx_gtk2u_unofficial_stc-3.0.so.0
libwx_gtk2u_unofficial_xrc-3.0.so.0
libwxsqlite3.so

It seems like most of these dependencies shouldn't be necessary for this kind of tool. Ideally most, if not all, of these dependencies could be eliminated, or perhaps statically linked into the tool.

2. codelite-make requires that there is a build_settings.xml file located in this directory:

~/.codelite/config/build_settings.xml

I am not sure what parts of the xml file are required by the codelite-make tool. If this file cannot be eliminated as a dependency, it would at least be nice to be able to tell codelite-make where to look for it through a command line option. 

i.e. codelite-make -buildsettings="./"

**Comment by eranif** [comment]
I don't think that we can eliminate much, for example:
`libwxsqlite3.so libssh.so.4` are needed by `libcodelite.so`
`libcodelite.so` is required by `libplugin.so`
 the various libwx_* are required by the executable + libcodelite.so (there are some GUI calls that requires the core/base library + the xml part is also required)

The `build-settings.xml` is required because it contains the toolchain definition (your project only contains the toolchain name)

So the only thing I can take from this bug report, is to allow passing `--build-settings` as a command line argument

**Comment by ntpg** [comment]
The command line argument would still be useful.  I'm currently working around the problem by deploying these dependencies along side codelite-make and then wrapping It up in a bash script that sets the LD_LIBRARY_PATH environment variable. 

If I can set the build settings via command line, I can do the same thing and deploy the xml file along side codelite-make. 

This would solve my problem

**Comment by eranif** [comment]
Added new option to `codelite-make`

Here is the new usage:
```
C:\Program Files\CodeLite>codelite-make
The value for the option 'w (or workspace)' must be specified.
Usage: codelite-make [/h] /w <str> /c <str> [/d <str>] [/p <str>] [/v] [/e] [/s <str>]
  /h, --help            show this help message
  /w, --workspace=<str> codelite workspace file
  /c, --config=<str>    configuration name to generate
  /d, --command=<str>   which command to run? possible values are: build, clean or rebuild. The default is to build
  /p, --project=<str>   project to build, if non given codelite will build the active project as defined in the workspace
  /v, --verbose         Run in verbose mode and print all log lines to the stdout/stderr
  /e, --execute         Instead of printing the command line, execute it
  /s, --settings=<str>  The full path of the build_settings.xml file.
By default, codelite-make will load the compiler definitions from
%appdata%\codelite\config\build_settings.xml (or the equivalent path on
Unix systems). Passing -s|--settings will override the default search
location
A makefile generator based on codelite's workspace
```
You can now pass `--settings` or `-s` to a location of your XML file e.g. `codelite-make --settings=C:\my-settings.xml ... `
