### ISSUE TITLE
PgUp/PgDown does not work in Open Resource and Quick Outline windows

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#678]
PgUp/PgDown does not work in Open Resource and Quick Outline windows

But cursor keys up/down works fine.
In order to make PgUp/PgDown work you have to switch the focus (using tab key) into the listview (grid)

Seen with Codelite 7.0 on ArchLinux

**Comment by uffejakobsen** [comment]
This is still an issue with CodeLite-8.0-1 (ArchLinux)

**Comment by eranif** [comment]
Fixed
