### ISSUE TITLE
Reconcile project closes all open edit tabs

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#679]
Reconcile project closes all open edit tabs - even those unrelated to the reconciliation

The  problem appears when deleting (all) stale files

Seen with CodeLite 7.0 on ArchLinux

**Comment by eranif** [comment]
IIRC, at the end of the reconciliation, a workspace loaded is issued. Could this be the problem?

**Comment by uffejakobsen** [comment]
Hi, I'm not sure what you are asking about here - could you elaborate ?

**Comment by eranif** [comment]
I was mostly talking to myself :)
what I meant in my previous comment is that at the end of the reconciliation process, a workspace reload is taken place and I suspect that this is the reason for the tabs closure

**Comment by uffejakobsen** [comment]
Ok :-)
Well in that case - the reload does not reopen the currently open files - and neither does it reload the files that normally would be opened by loading the workspace in a normal manner.
