### ISSUE TITLE
codelite 7.0.1

### ISSUE THREAD

**Issue by detranegabriele** [eranif/codelite#680]
CodeLite in 7.0.1 under ubuntu 14.04 and 14.10 the clips do not work , so you are forced to write them on a new text document , copy and paste them every time ! I kindly ask you to solve ..

**Comment by eranif** [comment]
I can't seem to reproduce this, 
* Any steps to reproduce? 
* are you using standard keyboard layout?
* does it work when copied using the menu (right click -> Copy)

**Comment by detranegabriele** [comment]
I use the normal layout of the italian keyboard , and for doing square parentheses I have to write it first on an editor and then i have to copy it

Inviata dal mio Windows Phone
________________________________
Da: Eran Ifrah<mailto:notifications@github.com>
Inviato: ‎24/‎02/‎2015 14:04
A: eranif/codelite<mailto:codelite@noreply.github.com>
Cc: detranegabriele<mailto:gabriele_detrane@outlook.it>
Oggetto: Re: [codelite] codelite 7.0.1 (#680)

I can't seem to reproduce this,
* Any steps to reproduce?
* are you using standard keyboard layout?
* does it work when copied using the menu (right click -> Copy)

---

**Comment by detranegabriele** [comment]
Sorry for my bad english

Inviata dal mio Windows Phone
________________________________
Da: Eran Ifrah<mailto:notifications@github.com>
Inviato: ‎24/‎02/‎2015 14:04
A: eranif/codelite<mailto:codelite@noreply.github.com>
Cc: detranegabriele<mailto:gabriele_detrane@outlook.it>
Oggetto: Re: [codelite] codelite 7.0.1 (#680)

I can't seem to reproduce this,
* Any steps to reproduce?
* are you using standard keyboard layout?
* does it work when copied using the menu (right click -> Copy)

---

**Comment by eranif** [comment]
> I use the normal layout of the italian keyboard , and for doing square parentheses I have to write it 
> first on an editor and then i have to copy it

Disable the External Tools plugin + CScope plugin to fix this

To disable the plugins, go to main menu bar and:
`Plugins->Manage plugins`

**Comment by detranegabriele** [comment]
thank you!!
