### ISSUE TITLE
Cannot set shortcut key for Workspace settings and Workspace Editor Preferences

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#681]
Cannot set hotkey for Workspace Settings and Workspace Editor Preferences

The menu entries "Workspace Settings" and "Workspace Editor Preferences" (both in the Workspace menu) are not available in Keyboard shortcuts - and thus it is impossible to setup a shortcut key for them.

Seen on CodeLite 7.0 on ArchLinux

**Comment by eranif** [comment]
Fixed. In order to see the fix, you will need to reload the default keyboard shortcuts from:
`Settings->Keyboard shortcuts->Defaults`
