### ISSUE TITLE
Settings menu does not have a shortcut letter

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#682]
Settings menu does not have a shortcut letter (ALT+something) - all other menus have that...

Seen on CodeLite 7.0 on ArchLinux

**Comment by eranif** [comment]
Alt-G works for me on Windows... will check it on Linux

**Comment by eranif** [comment]
It also works on Linux (Ubuntu) - can you please confirm this?
If for some reason `Alt-G` does not work for you, you can change it to something else by simply editing the XML file: `/usr/share/codelite/rc/menu.xrc` at around line `639` the `&amp;` indicates which char will get the mnemonic

**Comment by uffejakobsen** [comment]
I can confirm that ALT-G works. The problem wass that the underline below the g (in settings) was not visible with the used font. 
Thanks for the tip
