### ISSUE TITLE
Hard binaries in source distribution

### ISSUE THREAD

**Issue by sleary78** [eranif/codelite#684]
Hi there, 

Love codelite... noticed this

In the source distribution there are 2 hard binaries under

codelite/sdk/lldb/unix/lib/

i386
x86_64

This pretty much limits compiling to these platforms. I tried to compile this on Debian GNU/kFreeBSD but it died when trying to link those binaries. Not a big deal but maybe we could make liblldb a dependency and pickup the binary that way?

Cheers
Stephen

**Comment by eranif** [comment]
Fixed. CodeLite now uses the distro lldb.so and libclang.so if provided
