### ISSUE TITLE
Clang completion doesn't support C++14

### ISSUE THREAD

**Issue by matthew-nichols** [eranif/codelite#685]
Using certain features (like loops in constexpr functions) cause clang completion to almost certainly fail for the rest of the file. As far as I can tell Codelite doesn't support something like the "Enable C++11 Standard" for C++14. Codelite is 7.0, latest from repos.codelite.org as of right now. `clang --version` is 3.5.

**Comment by eranif** [comment]
which os do you use?

**Comment by matthew-nichols** [comment]
Ubuntu 14.10 (utopic)

**Comment by eranif** [comment]
this should be fixed now. I have added 2 places where you can add this option:
* Per workspace (right click on the workspace and select **Workspace Settings->Code Completion** page
* Per build configuration, right click on the project and select the **Code Completion**

To get this fix, you can build CodeLite from sources (rather easy task on Linux) as described here:
http://codelite.org/Developers/Linux

**Comment by matthew-nichols** [comment]
Okay, I eventually got this to work by replacing ~/lib/codelite/libclang.so with a link to the system libclang.so. It seems the libclang included with Codelite is very out of date. Wouldn’t it be better to use the system’s libclang, especially on Linux?
