### ISSUE TITLE
C++14 Type Alias doesn't show up in clang completion

### ISSUE THREAD

**Issue by matthew-nichols** [eranif/codelite#687]
For example, `std::common_type_t` doesn't show up in the context menu (having `#include <type_traits>` and C++14 enabled).

However, using it doesn't stop clang completion from working afterwords.

(This all assumes Codelite's `libclang.so` is manually updated, which seems to work.)

**Comment by eranif** [comment]
This should be fixed in git master. CodeLite no longer provide its own libclang.so, instead it uses the distro's one
