### ISSUE TITLE
Cannot search in Makefiles

### ISSUE THREAD

**Issue by jjvbsag** [eranif/codelite#688]
I have a project with a lot of  .cpp, .h files and some files named "Makefile" (all of them spread over different folders) (Project is "Custom build")
When I search for something in the sources, I can enter "*.cpp" in the Filemask and things will be found.
When I search for something in the Makefiles, I would enter "Makefile" in the Filemask, but then I find nothing. Only when I clear the filemask, I can find something in the Makefile, but then also *all* sources and *all* other files will be searched.

[Using Codelite 7.0 on Kubuntu 14.04]

**Comment by eranif** [comment]
Fixed
