### ISSUE TITLE
reload open tabs

### ISSUE THREAD

**Issue by Fritzor** [eranif/codelite#689]
Good day everybody,
I just updated to Codelite7.0 on my Ubuntu14.04. Now I am a little bit frustrated. If I close codelite and open it again, then all open files (tabs) are closed. 
If I close the Workspace before I close Codelite then all tabs are opened again. (as it should be)
Is this a problem with my computer, or a bug?
Please help.

**Comment by eranif** [comment]
this bug is already fixed in git master.
the workaround is simple: close the workspace manually before exiting codelite

**Comment by Fritzor** [comment]
Okay, thank you!
