### ISSUE TITLE
problem building project that has files or directories with space characters

### ISSUE THREAD

**Issue by m-rap** [eranif/codelite#691]
I created a project and added some files that contains space characters. Let's say the file name was "filename with space.cpp" and the directory name was "dirname with space". And then it failed to build and produced this error message:
`
make[1]: *** No rule to make target '../../dirname', needed by 'Debug/dirname'.  Stop.
`

Thank you

I am using CodeLite 7.0 on Debian 8 Squeeze

**Comment by eranif** [comment]
don't use files with spaces.
it's not standard and definitely not worth the effort of fixing this

**Comment by m-rap** [comment]
well if it's not standard then it might be better to deny or at least show a warning dialog for the people who would try to add such files if you dont mind :)
