### ISSUE TITLE
Can't write square brackets on Italian keyboard

### ISSUE THREAD

**Issue by rudarx** [eranif/codelite#694]
Using an Italian keyboard layout and pressing AltGr+'è' ('[') and AltGr+'+' (']') won't write any square bracket.
That's weird because pressing AltGr+'ò' writes '@' and AltGr+'à' writes '#' as it normally should.

**Comment by eranif** [comment]
This is already fixed in git master
See this forum discussion for a simple workaround:
http://forums.codelite.org/viewtopic.php?f=3&t=2837
