### ISSUE TITLE
Make it possible to enter in the "Command" field more than 512 characters for custom build

### ISSUE THREAD

**Issue by NikitaFeodonit** [eranif/codelite#695]
My example:
```
mkdir $(ProjectPath)\$(IntermediateDirectory)\build && cd $(ProjectPath)\$(IntermediateDirectory)\build && cmake -G"MSYS Makefiles" -D"CMAKE_C_FLAGS='-march=i686 -mtune=generic -O2 -pipe'" -D"CMAKE_CXX_FLAGS='-march=i686 -mtune=generic -O2 -pipe -std=c++11'" -D"CMAKE_EXE_LINKER_FLAGS='-pipe'" -D"CMAKE_MODULE_LINKER_FLAGS='-pipe'" -D"CMAKE_SHARED_LINKER_FLAGS='-pipe'"  -DCMAKE_INSTALL_PREFIX=$(ProjectPath)/$(IntermediateDirectory)/$(ProjectName) -DCMAKE_BUILD_TYPE=$(ConfigurationName) -DPOCO_UNBUNDLED=ON -DENABLE_MONGODB=OFF $(ProjectPath)/src
```

I think it would be nice to remove the restriction to 512 characters, as in my example it would be possible to insert more flags.

**Comment by eranif** [comment]
I am not aware of such limitation... why do you think there is a limitation? can you please show where this problem manifested for you?

**Comment by NikitaFeodonit** [comment]
I try insert the command and get error as the command is truncated. Then I copy the text of command to editor and see length of string is 512 characters.

My example is more complex, the last time I forgot to add the necessary commands:
```
mkdir $(ProjectPath)\$(IntermediateDirectory)\build && cd $(ProjectPath)\$(IntermediateDirectory)\build && cmake -G"MSYS Makefiles" -D"CMAKE_C_FLAGS='-march=i686 -mtune=generic -O2 -pipe'" -D"CMAKE_CXX_FLAGS='-march=i686 -mtune=generic -O2 -pipe -std=c++11'" -D"CMAKE_EXE_LINKER_FLAGS='-pipe'" -D"CMAKE_MODULE_LINKER_FLAGS='-pipe'" -D"CMAKE_SHARED_LINKER_FLAGS='-pipe'"  -DCMAKE_INSTALL_PREFIX=$(ProjectPath)/$(IntermediateDirectory)/$(ProjectName) -DCMAKE_BUILD_TYPE=$(ConfigurationName) -DPOCO_UNBUNDLED=ON -DENABLE_MONGODB=OFF $(ProjectPath)/src && make && cd $(ProjectPath)\$(IntermediateDirectory)\build && make install
```

**Comment by NikitaFeodonit** [comment]
I forgot:

Codelite version 7.1 from last weekly build.
Windows 7 Pro

**Comment by NikitaFeodonit** [comment]
Codelite version 7.1 x64
Windows 7 Pro x64 SP1 + updates to Nov 2014

**Comment by eranif** [comment]
Please provide a step by step instructions of how to reproduce the problem.
(where to insert the command, which dialogs to open etc)
As its not clear from the bug report where should I try to insert this command nor that I am aware of such limitation, so I might be missing something here

**Comment by NikitaFeodonit** [comment]
I make release build.
In "Workspace View" right mouse click on project -- Settings
For Release type of build:
Customize -- Custom Build -- New
Target Name == cmake
Command:
```
mkdir "$(ProjectPath)\$(IntermediateDirectory)\build" && cd "$(ProjectPath)\$(IntermediateDirectory)\build" && cmake -G"MSYS Makefiles" -D"CMAKE_C_FLAGS='-march=i686 -mtune=generic -O2 -pipe'" -D"CMAKE_CXX_FLAGS='-march=i686 -mtune=generic -O2 -pipe -std=c++11'" -D"CMAKE_EXE_LINKER_FLAGS='-pipe'" -D"CMAKE_MODULE_LINKER_FLAGS='-pipe'" -D"CMAKE_SHARED_LINKER_FLAGS='-pipe'"  -DCMAKE_INSTALL_PREFIX=$(ProjectPath)/$(IntermediateDirectory)/$(ProjectName) -DCMAKE_BUILD_TYPE=$(ConfigurationName) -DPOCO_UNBUNDLED=ON -DENABLE_MONGODB=OFF "$(ProjectPath)/src" && make && cd "$(ProjectPath)\$(IntermediateDirectory)\build" && make install
```
OK -- OK

Once again:
In "Workspace View" right mouse click on project -- Settings
For Release type of build:
Customize -- Custom Build
Select "cmake" -- Edit
Command look like this:
```
mkdir "$(ProjectPath)\$(IntermediateDirectory)\build" && cd "$(ProjectPath)\$(IntermediateDirectory)\build" && cmake -G"MSYS Makefiles" -D"CMAKE_C_FLAGS='-march=i686 -mtune=generic -O2 -pipe'" -D"CMAKE_CXX_FLAGS='-march=i686 -mtune=generic -O2 -pipe -std=c++11'" -D"CMAKE_EXE_LINKER_FLAGS='-pipe'" -D"CMAKE_MODULE_LINKER_FLAGS='-pipe'" -D"CMAKE_SHARED_LINKER_FLAGS='-pipe'"  -DCMAKE_INSTALL_PREFIX=$(ProjectPath)/$(IntermediateDirectory)/$(ProjectName) -DCMAKE_BUILD_TYPE=$(ConfigurationName) -DPOCO_UNBUNDLED=O
```
lenght == 511 characters

**Comment by eranif** [comment]
Thanks for the detailed steps. I can see the problem now, and it looks like a bug in wxWidgets... in particular with the wxListCtrl widget (this is the control that does the truncation)

**Comment by eranif** [comment]
Fixed. I had to replace the wxListCtrl to wxDataViewCtrl as it looks like its a limitation of that widget
