### ISSUE TITLE
Cannot run Codelite 7.0 on Windows 10 Preview Build 9926

### ISSUE THREAD

**Issue by njZhuMin** [eranif/codelite#696]
I have been using Codelite for long and just updated it to version 7.0 yesterday. However, I found some problem with this version running on Windows 10 Preview Build 9926. I can build a workspace or a project or add source file to my project. Yet every time I double click the .CPP file on the lest list, Codelite just breaks down. And I cannot compile an existing project either. I am now changing back to version 6.1.1 and hope to solve this problem soon.

**Comment by eranif** [comment]
You did not specify which version of CodeLite you used: 32 or 64 bit 
> Codelite just breaks down 

This is not a descriptive message.
Since Windows 10, is not avaliable to the public yet, I don't plan on fixing bugs for a Windows release which I don't have access to
