### ISSUE TITLE
Cannot create new workspace or project

### ISSUE THREAD

**Issue by newhousea7** [eranif/codelite#698]
I just downloaded Codelite 7 for Windows 64bit, however I am unable to create a new workspace or project. The "New project" text is always greyed out and unable to selected. When I try to create a new workspace and select the "C++" workspace, no matter what workspace name I put in I always recieve the error "Invalid Path". Any help with these problems would be greatly appreciated.

**Comment by eranif** [comment]
This is not a bug.
A project is always disabled, until you have a workspace opened

"Invalid Path" means... "Invalid Path", i.e. you need to select a different path to place your workspace.
e.g. `C:\Program Files\CodeLite` is an invalid path for creating workspace. Select a path without spaces and in a location where CodeLite have write permissions

**Comment by nyankana** [comment]
I think that is the problem. If the program is unable to create workspace in the path C:\Program Files\CodeLite, it should not even be defaulted in the first place.

**Comment by h4km** [comment]
I have a problem to create new project? whats wrong with this?
![screenshot 26](https://cloud.githubusercontent.com/assets/18589069/15218104/3856aa72-1813-11e6-92ef-10ef8a3a8f96.png)

**Comment by eranif** [comment]
Close the current one and then you will be able to create a new one

**Comment by RuslanAndrei** [comment]
how can i code in the actual workspace? i installed again the IDE and now,any new file is untitled 
![faracodelite](https://user-images.githubusercontent.com/56681003/67005493-655bb300-f0eb-11e9-8d18-fa1c060f8595.png)
