### ISSUE TITLE
Codelite crash, when using PageUp/PageDown in "Tabs" Tab

### ISSUE THREAD

**Issue by jjvbsag** [eranif/codelite#701]
* Open a project
* Open some files in the project 
* Select the "Tabs" tab in workspace view => Opened files are listed in the view
* Press CursorUp/CursorDown => working fine
* Press PageUp/PageDown => codelite either crashes instantly or freezes for some ten seconds before crash

CodeLite 7.0 on Kubuntu 14.04

**Comment by eranif** [comment]
This looks like a bug in wxWidgets...
The "key down" event does not even go through CodeLite code, so there is _nothing_ CodeLite can do about this (not even disabling the PGDN / PGUP clicks...)

**Comment by eranif** [comment]
Since there is nothing I can do about this - I am closing it. Hopefully it will get fixed during the next wx upgrade
