### ISSUE TITLE
Unable to completely disable "Code navigation key"

### ISSUE THREAD

**Issue by jazztickets** [eranif/codelite#702]
http://i.imgur.com/AfddVGL.png

Unchecking Shift and hitting "Apply" or "Okay" or both will not save. It will revert back to enabling "Shift" as a modifier key.

It's a problem when i'm trying to select text using the shift key and a mouse. A workaround is to enable all modifiers keys so i that i can safely select text.

**Comment by eranif** [comment]
This was fixed already in git master (i.e. shift is no longer a valid navigation key)
