### ISSUE TITLE
Open Tabs were not restored after restarting CodeLite

### ISSUE THREAD

**Issue by D0m1n1k** [eranif/codelite#703]
CodeLite saves all open Tabs when i close the Workspace. After i open the Workspace again all Tabs were restored as they should.
But when i close CodeLite directly without closing the Workspace manually before all open Tabs won't be restored. 
The last opened Workspace opens but without the Tabs that were opened before.
OS: Ubuntu 14.04 64-Bit

**Comment by eranif** [comment]
This is already fixed in git master and will be part of next release

Eran
