### ISSUE TITLE
code completion in range based for loops (for each)

### ISSUE THREAD

**Issue by Repl1cator** [eranif/codelite#705]
Given the following code
```c++
std::vector<int> vec = {1, 2, 3, 4, 5};

for (int element : vec) {
    std::cout << elem
}
```

then the local scope variable "element" is not recognized at all by the code completion.

**Comment by eranif** [comment]
I noticed similar issue when using std::for_each with lambda functions.
However, enabling clang code completion from: `settings->code completion->clang->enable clang completion` fixed this for me, and it will fix this for you as well

**Comment by Repl1cator** [comment]
Ah, wonderful! This works like a charm.
Thank you for your quick reply.
