### ISSUE TITLE
Global colours do not affect debugger windows consistently

### ISSUE THREAD

**Issue by Razish** [eranif/codelite#706]
Codelite 7.1, OS X Yosemite

"Threads", "Callstack" and "Breakpoints" windows do not apply background or foreground colour.
"Locals & Watches" window applies background colour but does not apply foreground colour, making it impossible to read on a dark background.

![codelite-debugger-colours](https://cloud.githubusercontent.com/assets/844370/6862126/445340da-d497-11e4-8675-4290ded77f7a.png)

**Comment by eranif** [comment]
I am afraid this is out of my hands.
Some controls in wxWidgets simply do not play nice with black colour (or any other dark colour as the main background colour)
I will see what else can be done to improve this

**Comment by Razish** [comment]
I would accept that specific window not following the global colours, so long as it's consistent and not hard to read. If the foreground colour is not being applied, neither should the background colour.

**Comment by eranif** [comment]
Fixed
