### ISSUE TITLE
  Hardcoded icon path in launcher for GNU/Linux systems

### ISSUE THREAD

**Issue by palob** [eranif/codelite#707]
Hi,

currently the icon path specified in the created *.desktop* launcher file is set to: 
*Icon=%%PREFIX%%/share/codelite/images/cubes.png* 

(see https://github.com/eranif/codelite/blob/2d5c070c9c8c2b1b14b7c2724f7c98a8b356d183/Runtime/codelite.desktop.template)

This prevents icon theming without editing the launcher file.

I'd like to ask you to change the icon location as well as the icon path line in the launcher according to the freedesktop.org standards.

Please find more info here:
http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
https://github.com/Foggalong/hardcode-fixer/wiki/What,-Why-&-How

---------------------------------
According to the above resources standard icon locations are:

*/usr/share/icons/hicolor/[size]/apps/[icon name]*
*~/.local/share/icons/hicolor/[size]/apps/[icon name]*
*/usr/share/pixmaps/[icon name]*

The standard icon line in the .desktop launcher is:
*Icon=[icon name]*      (without full path, without file extension)

for instance
**Icon=codelite**  
(for an icon *codelite.svg* or *codelite.png* stored in standard location)

Could you please move the icon to one of those locations and adjust the icon path in the .desktop file accordingly?

**Comment by eranif** [comment]
Can you please make the needed changes and send a pull request?

**Comment by palob** [comment]
Thanks, created a PR.

**Comment by eranif** [comment]
Thanks for the PR which I applied.
One minor issue (beside in the typo in `CMakeLists.txt`) :  in order to see the icon I needed to delete the file `/usr/share/icons/hicolor/icon-theme.cache` any idea on how to trigger / reset the cache from CMake / CPack or just deleting the cache will fix this ?

**Comment by palob** [comment]
Oops, sorry for thr typo.
Regarding the icon cache I think the behaviour is different from one DE / file manager to another and depends on the personal thumbnail cache preferences. So I am not sure which side effects a triggered cache reset could have. 

It should show up properly after the next login anyway, doesn't it.
Otherwise we could simply store the icon to */usr/share/pixmaps*

**Comment by eranif** [comment]
I removed the cache file, it does not seem to do any harm anyways ;)

https://github.com/eranif/codelite/commit/b6bbba8f4923ab653691695584dcf79422021d5f
