### ISSUE TITLE
Windows installers detected as malicious by COMODO firewall.

### ISSUE THREAD

**Issue by David-Allison** [eranif/codelite#708]
Upon opening the executable listed: http://downloads.codelite.org/downloads.php?windows_64 , the installer stays open for approximately 5 seconds before unexpectedly closing with no error message. 

No message appears, my firewall log shows:

![image](https://cloud.githubusercontent.com/assets/7842899/6888127/f880449c-d66b-11e4-9af3-5f60ca64c2ba.png)

This is true for both the 64bit and x86 versions.

**Comment by eranif** [comment]
Well, this is one of those cases of "false positive"
I can't really help here. You can always download CodeLite sources and build it manually or disable the firewall during the installation
