### ISSUE TITLE
Hide Docking Windows captions doesn't work in CodeLite 7.1 weekly build

### ISSUE THREAD

**Issue by DoctorRover** [eranif/codelite#711]
The option Hide Docking Windows captions (in Editor Settings -> Windows & Tabs) does not work in CodeLite 7.1 weekly build. Checking or unchecking of this checkbox does not change the state of the captions. It looks like a regression because it used to work in CL7.0.

OS: Windows 7 64bit with all updates installed
CodeLite: 7.1 weekly build (March 18, 2015) installed from binary installer downloaded from http://downloads.codelite.org

**Comment by eranif** [comment]
Fixed
