### ISSUE TITLE
Unfold a fold causing freezing

### ISSUE THREAD

**Issue by gbuntu127** [eranif/codelite#713]
From time to time, when I tried to unfold a folded function, codelite freezes and causing 100% cpu usage. I could not purposely reproduce it, but I think it is almost often the last folding function, i.e., the funciton that is folded at the bottom of the file.

I am using codelite version 7.1 on Linux Mint 17 Qiana. 
Codelite was built using the latest code form github (2015-4-2). 

Thank you for the great tool.

**Comment by eranif** [comment]
Can you debug this issue? I am unable to reproduce this (Linux Mint 17 here as well)

**Comment by eranif** [comment]
Unable to reproduce
