### ISSUE TITLE
Load last session on startup does not restore openned file tabs

### ISSUE THREAD

**Issue by gbuntu127** [eranif/codelite#714]
When codelite starts it only re-load the last openned project, but it does not restore openned file tabs. If I remember correctly, it worked in the 6.x versions. 

I am using codelite version 7.1 on Linux Mint 17 Qiana. 
Codelite was built using the latest code form github (2015-4-2). 

Thank you.

**Comment by eranif** [comment]
Do you have an open workspace? or just open files without any workspace?

**Comment by eranif** [comment]
nvm, I managed to reproduce this (it only happens when no workspace is opened)
Should be fixed now

**Comment by marsender** [comment]
Hi,

I have the same problem with ubuntu and CodeLite version 7.0.
If I close and reopen a worspace, the project files are reopend.
But if I close the application with an opended workspace, when I launch CodeLite again the workspace opens itself but all the file tabs are lost.

Thanks

**Comment by eranif** [comment]
@marsender  this bug is already reported and fixed https://github.com/eranif/codelite/issues/641
