### ISSUE TITLE
codelite doesn't recognize braces on german gentoo

### ISSUE THREAD

**Issue by thigazi** [eranif/codelite#716]
Hi people!

I run XFCE 4.10 and codelite 7.0 and I can't have "{" and "}" braces in the code editor. 
Everywhere else it works fine. Any ideas ?!

My locals:
locale -a
C
de_DE
de_DE.iso88591
de_DE.iso885915
de_DE.utf8
deutsch
german
POSIX
 
and

My Linux System:
Linux tux 3.18.7-gentoo-1 #1 SMP Mon Mar 23 21:46:26 CET 2015 x86_64 Intel(R) Core(TM)2 Quad CPU Q6600 @ 2.40GHz GenuineIntel GNU/Linux

and libc version:

GNU C Library (Gentoo 2.19-r1 p3) stable release version 2.19, by Roland McGrath et al.
Compiled by GNU CC version 4.8.3.
Compiled on a Linux 3.18.0 system on 2015-03-28.
Available extensions:
	C stubs add-on version 2.1.2
	crypt add-on version 2.1 by Michael Glad and others
	GNU Libidn by Simon Josefsson
	Native POSIX Threads Library by Ulrich Drepper et al
	BIND-8.2.3-T5B
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<http://bugs.gentoo.org/>.

best, Tamer

**Comment by eranif** [comment]
This was already fixed in git master. It was due to conflict in (it turns out that AltGr is translated into Ctrl-Alt) shortcuts...

The original problem:
https://github.com/eranif/codelite/issues/612

The workaround:

* Disable the External Tools plugin
* Disable CScope plugin

**Comment by thigazi** [comment]
Thanks!

**Comment by thigazi** [comment]
Works out of the box, after building the master git version, deleting
the old home user .codelite directory.
Without deleting the .codelite directory, the problem still existed.


Thanks, Tamer


Am 06.04.2015 um 06:29 schrieb Eran Ifrah:

**Comment by eranif** [comment]
> Without deleting the .codelite directory, the problem still existed.

This is because CodeLite by default will not override your previous keyboard shortcuts
Another solution (which does not involving deleting the entire `.codelite` folder) is to reset the keyboard shortcuts manually `settings->keyboard shortcuts->defaults button`

This should restore the keyboard settings to "factory defaults" but keep your `~/.codelite` folder content
