### ISSUE TITLE
Weird behaviour with detached windows.

### ISSUE THREAD

**Issue by dmfilho** [eranif/codelite#717]
My operating system is Debian Jessie. My desktop environment is XFCE 4.10.
I'm using Codelite 7.0.
I use to work with two screens, and I usually keep one detached window.

I noticed I can't open the same file on two different tabs or windows, even if it is detached. I'm aware that this is the expected behaviour. 

However if I make a typo on the detached window and try to compile, the compiler error is displayed on the "output view". From the "output view" I'm able to click on the error and open another tab containing the file that is already opened on the detached window. I believe this isn't supposed to happen. But, when this happens things can get weird.

The weird behaviour happens if I make corrections to the code on the tab that is **not** detached, and then save it. Codelite warns about external changes. If I choose to "reload" the code on the detached window, the mouse gets weird. I can barely click on anything or perform any action with the mouse.

If you need a clearer description on how to reproduce, please let me know. Thank you.

**Comment by eranif** [comment]
> If you need a clearer description on how to reproduce, please let me know. Thank you.

Please do, as I am unable to make it happen here

**Comment by eranif** [comment]
No response. Closed
