### ISSUE TITLE
clang causes Codelite to crash

### ISSUE THREAD

**Issue by nezos** [eranif/codelite#718]
While i am typing code codelite crashes. This happened after i pasted around ~1.5k lines of code to my project.

App Name: codelite.exe
App Version: 7.0.0.0
Fault Module Name: libclang.dll
Fault Module Version: 0.0.0.0
Exception Code: c0000005
Exception Offset: c8785
Additional Info 1: 2c53
Additional Info 2: 2c53cb47ec447c62cfd36b791b2df3a1
Additional Info 3: 005b
Additional Info 4: 005bd1802bd09f23b7313c1168bfaad4

**Comment by eranif** [comment]
This only happens on Windows...
( I noticed this as well from time to time )
The problem is that it happens somewhere inside libclang and there is nothing that we can do about it (except disabling clang)

**Comment by eranif** [comment]
I have updated the libclang (64 bit version only) to the latest.
Please test against latest git master

Eran
