### ISSUE TITLE
Tooltip appears trimmed when a function has many variables

### ISSUE THREAD

**Issue by nezos** [eranif/codelite#719]
Declare a function with many variables and long names.

While entering the function variables, the tooltip appears but it is trimmed and will never show all variables, especially the last ones. Even if you scroll to the right the tooltip will remain the same.

Maby a solution would be to wrap the text (occupy 2 or more lines).

**Comment by eranif** [comment]
The solution is to display the parameter hint vertically (and so I did)
Closed
