### ISSUE TITLE
project link failed in codelite 7.0 x86

### ISSUE THREAD

**Issue by zufuliu** [eranif/codelite#722]
just create new workspace test, add new project test, then build.
source main.cpp:
#include <stdio.h>

int main(int argc, char **argv)
{
	printf("hello world\n");
	return 0;
}

build output:
C:\WINDOWS\system32\cmd.exe /C "D:/Dev/gcc4/bin/mingw32-make.exe  SHELL=cmd.exe  -e -f  Makefile"
"----------Building project:[ test - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'D:/Work/test'
codelite-cc D:/Dev/gcc4/bin/g++.exe  -c  "D:/Work/test/main.cpp" -g -O0 -Wall  -o ./Debug/main.cpp.o -I. -I.
D:/Dev/gcc4/bin/g++.exe  -o ./Debug/test @"test.txt" -L.
g++.exe: error: @test.txt -L.: No such file or directory
g++.exe: fatal error: no input files
compilation terminated.
mingw32-make.exe[1]: *** [Debug/test] Error 1
mingw32-make.exe: *** [All] Error 2
test.mk:78: recipe for target 'Debug/test' failed
mingw32-make.exe[1]: Leaving directory 'D:/Work/test'
Makefile:4: recipe for target 'All' failed
1 errors, 0 warnings

gcc version 4.9.2 (i686-posix-dwarf-rev2, Built by MinGW-W64 project)

**Comment by eranif** [comment]
Its not a CodeLite issue, but rather your g++
It seems that your g++ does not accept arguments via file ( `@text.txt` )
You have 2 options here:
* Replace your g++ to a better one (for example, [TDM GCC 64 bit](http://sourceforge.net/projects/tdm-gcc/files/TDM-GCC%20Installer/tdm64-gcc-4.9.2-3.exe/download))
* Disable the option that passes object list to the linker via file from:
`settings->build settings->compilers->your compiler name->advanced tab->Pass object list to the linker via file`

**Comment by zufuliu** [comment]
however it works if I run this line in cmd.exe
D:\Work\test>g++.exe  -o ./Debug/test @"test.txt" -L.

**Comment by zufuliu** [comment]
thanks, disable Pass object list to the linker via file works

**Comment by eranif** [comment]
> however it works if I run this line in cmd.exe
> D:\Work\test>g++.exe -o ./Debug/test @"test.txt" -L.

Notice that you are using `g++` instead of `D:/Dev/gcc4/bin/g++.exe` (which CodeLite does)
Can you confirm its the same `g++` ?

**Comment by zufuliu** [comment]
yes, they are same, I have only one GCC installed.
It seems  there some bugs in the mingw32-make.exe comes with MinGW-W64 GCC.
D:\Dev>mingw32-make -v
GNU Make 4.1
Built for i686-w64-mingw32

D:\Dev>make -v
GNU Make 3.81
This program built for i386-pc-mingw32

Change Make in Tools from
D:/Dev/gcc4/bin/mingw32-make.exe  SHELL=cmd.exe 
to
D:/MinGW/bin/make.exe SHELL=cmd.exe
then enable "Pass object list to the linker via file" works

**Comment by eranif** [comment]
This is why I always recommend to use the TDM builds of GCC - they never failed me
