### ISSUE TITLE
Feature: mark a file tab read only

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#723]
It would be nice with an option to make a file (tab) read only - and in some way show that the tab is read only with color and/or lock icon etc...

Also it would be nice is a file could be opened read-only from the command line eg:

  # codelite -r file-name-to-open-read-only

**Comment by eranif** [comment]
Implemented. However, the second part is not implemented (too much effort... )
As usual, pull requests is more than welcomed!

You can now right click an editor and select `Mark as read only`
