### ISSUE TITLE
Callgraph not working

### ISSUE THREAD

**Issue by hariramsatheesh** [eranif/codelite#727]
I downloaded CodeLIte v. 7.0 and using VC++ 9.0 compiler on windows 7 system. I am unable to generate the call graph. I find gprof.exe in the path while dot.exe is not found.

**Comment by eranif** [comment]
You need to install these external tools. Its not part of CodeLite installation

**Comment by hariramsatheesh** [comment]
Can you tell me where do I get them

**Comment by eranif** [comment]
Its part of the http://www.graphviz.org/Download.php package

The steps to use CallGraph:
* Download http://www.graphviz.org/Download.php and extract it somewhere
* Rebuild your project once with the flag `-pg` enabled for both the compiler and linker
* Execute your program once (this will generate the file `gmon.out`)
* Run CallGrap

**Comment by hariramsatheesh** [comment]
It didn't work

**Comment by eranif** [comment]
I tried it myself and it works.
 If it does not work for you, please post the steps on the forum where other people might assist you
