### ISSUE TITLE
Tabs do not follow system colours

### ISSUE THREAD

**Issue by awsdert** [eranif/codelite#728]
Even when enabling the Tweaks plugin and setting the globals to buttonface/buttontext to get it corrected the tabs do not follow the system upon theme change, instead codelite just SWAPs the colours it already retrieved which looks ugly if switching from High Contrast to Normal, codelite should just update the colours with the system ones if they are not using custom colours.

**Comment by awsdert** [comment]
Related but not as big a deal, the content of those tabs (barring the editor tabs) should also follow the system colours but instead fixates on black on white.

**Comment by eranif** [comment]
The "ButtonFace" et al are not a reference, they are hard coded colours (eventually they are translated into concrete colours).
In anycase, we don't have enough resources to handle this issue - you are welcome to submit a PR (Pull Request) with a fix

**Comment by awsdert** [comment]
They can't be hard-coded since when the system theme changes and I start codelite it definitely retrieves the values (even if codelite's theme code is somewhat buggy), and they were doing that even before activating the tweaks plugin, tweaks just made it easier correct the colours.

**Comment by eranif** [comment]
I agree that it can be improved. 
However, like I mentioned above, we simply have no resources to fix this... looking forward for your pull request fix ;)

**Comment by awsdert** [comment]
I don't fully understand the pull system so I don't use it, furthermore even if I did understand it properly I don't know which revision to reference so be pointless to try. But suffice to say I suspect the update function just needs to remove the swap colour code and just pop in a call to GetSysColor and update the colours to follow that. Alternatively could have everything initiate with a black on white colour scheme and then have the update function retrieve the system colours and follow those on paint.

On another note do you use a 3rd party framework or a custom one? if custom could I suggest switching to IUP on the next major change so that you remove much of the burden of maintaining the GUI section of the framework and still retain the speed of C?
