### ISSUE TITLE
Random crashes before or after file operations

### ISSUE THREAD

**Issue by sethcoder** [eranif/codelite#729]
While using Codelite, I am experiencing seemingly random hard crash when I click on files in the Explorer view.
This doesn't always happen, but it seems like when it does happen I have just written a file, or I am trying to open a new file, or browse to a new folder.
I don't have enough hard evidence that the file i/o is part of the problem, but I suspect it has something to do with the Explorer window and how it stats files.
It happens every time I use Codelite, but I've just ignored it for the most part and restarted Codelite. I work in such a manner that I will not lose data, but I can foresee that this would be a problem if I make a mistake at some point and forget to save something.
This happens on Windows over network mapped folders, and regular system folders.
It happens on Linux version also, and I am using sshfs.

**Comment by eranif** [comment]
I am unable to reproduce this. Can you prepare a small sample (minimal project) that reproduces this?
Thanks

**Comment by sethcoder** [comment]
I don't use projects. I just use the explorer to open files, and edit them. I'll try to see if I can find the source of the problem. Thanks for replying.

**Comment by eranif** [comment]
No response from OP
