### ISSUE TITLE
Cppcheck doesn't work

### ISSUE THREAD

**Issue by Havoc2** [eranif/codelite#731]
Cppcheck doesn't work in the latest weekly build (CodeLite 7.1 weekly build (April 16, 2015) - Windows 64-bit).

You get an error message, when trying to run cppcheck:

> :: information: Failed to load std.cfg. Your Cppcheck installation is broken, please re-install. The Cppcheck binary was compiled with CFGDIR set to "config/cppcheck" and will therefore search for std.cfg in that path.

**Comment by eranif** [comment]
Fixed

**Comment by mattreecebentley** [comment]
Doesn't appear to be working on current version - installed codelite, installed cppcheck, installed cppchecker plugin in codelite, restarted codelite, right-click project run cppcheck, nothing happens.

**Comment by eranif** [comment]
which OS are using?

**Comment by eranif** [comment]
This is now fixed. I have re-written and simplified the plugin

**Comment by mattreecebentley** [comment]
Thank you
