### ISSUE TITLE
codelite crashes every time i open 17 files

### ISSUE THREAD

**Issue by Loae** [eranif/codelite#734]
my system is ubuntu 14.04 x64.
every time i open 17 files, codelite crashes. 
the crash report says 
"codelite crashed with SIGSEGV in __longjmp()".but after so many times of crash, the message gets bored to show up...

**Comment by eranif** [comment]
Thanks for reporting this. This bug was fixed on March 18, see this commit: a7c2c2c8c4f525a57efbefbbd019c3dfb3fb6c58
