### ISSUE TITLE
modified some messages

### ISSUE THREAD

**Issue by huan5765** [eranif/codelite#738]
1. LLDBDebugger/UI.cpp:368
message "The maximum number of **eleements** to display in arrays" 
change to "The maximum number of **elements** to display in arrays" 

2. Gizmos/newclassbasedlg.cpp:320
message "**Inhertiance** Access:"
message "**Inhertance** Access:"

**Comment by eranif** [comment]
Thanks. Notice that the second fix you provided also contains a typo ;)
