### ISSUE TITLE
No IME/Compose support in main editor window

### ISSUE THREAD

**Issue by DarrenCook** [eranif/codelite#739]
If I start codelite with `GTK_IM_MODULE=xim codelite` (which is the default, at least on recent Ubunut/Mint distros), then the keyboard shortcuts to toggle Japanese on/off in ibus-anthy get ignored. If I use the mouse to switch it on, then I can see a little window where the keyboard input goes, but pressing Enter does not put it in the editor window. Keypresses are being swallowed. In addition, the compose key does not work, so £, á, etc. cannot be typed.

If I start with `GTK_IM_MODULE=ibus codelite` then it is almost the same, except no keypresses go to the IME at all. (I.e. I use the mouse to switch anthy into japanese mode, but my keypresses go straight into the editor window as ascii). However, Compose keys do work.

As I just noted in #38 single-line input boxes, such as naming a new workspace, have different behaviour (very bad one with `xim`, working perfectly fine with `GTK_IM_MODULE=ibus`).

Bug #441 might be related, and says Scintilla is to blame. I use SciTE on this machine, which is fine with xim... but a test just showed it does not work at all with `GTK_IM_MODULE=ibus`).

So it may turn out that you are caught in the tight spot between two bugs, neither of which you can do anything about?
  xim does not work with GTK3 programs
  ibus does not work with editors built on top of scintilla

**Comment by eranif** [comment]
Sorry, due to resource limitation this I will not be able to fix this.
A pull request with the suggested fix will be highly appreciated
