### ISSUE TITLE
Screen tearing occurs when scrolling

### ISSUE THREAD

**Issue by Cube777** [eranif/codelite#740]
Running on Ubuntu 15.04 x64 with CodeLite 7.0

When rapidly scrolling up and down in the editor black areas appear (screen tearing?). No screenshot available because it happens to fast.

**Comment by eranif** [comment]
I am pretty sure that this bug was fixed in this commit: https://github.com/eranif/codelite/commit/20f9afbf24aaf14dee40048253c99d0c0dc02a82

(couple of days after codelite 7.0 was released)
