### ISSUE TITLE
Mac os debuger problem

### ISSUE THREAD

**Issue by kobzar** [eranif/codelite#741]
Hi!
First i want say, that CL is very good IDE! Cross-platform, free, small and quickly.
Thanks for it. 

I am try used CL for develop on STM32 from MAC OS.
I am create a new project on C, add some settings and now,  i fully working with code. This is awesome.
But i have a error when try start debugger. 

For debug i am use openocd. After build the project, i am have project.elf file.
I started in console(Terminal.app) openocd and in another screen start arm-none-eabi-gdb. Connect from gdb to localhost:3333 and another command - worked fine.

In CL Debugger settings i am set remote debug, host, port, startup scripts e.t.c... But all time, when i try 
start debug, i am see this error:
"Could not launch terminal for debugger" and i see codelite-terminal window. (why not my system terminal app?)
So, i am try start codelite-terminal manualy, and after this run arm-none-eabi-gdb from it - worked.
Yo can see errror on screen in attach.
My info: 
MacOS 10.10 Yosemite (x64)
CodeLite - latest (CodeLite 7.0 App Bundle for OSX 10.8 )

![snimokekrana2015-04-26v12 1430041403](https://cloud.githubusercontent.com/assets/1912842/7364643/86333056-ed91-11e4-9279-16b0f7939214.png)

**Comment by eranif** [comment]
For OSX, we have a more "latest" version, please give it a try it should have many debugging issues fixed.
Try to download the weekly build version for OSX: http://downloads.codelite.org/

**Comment by kobzar** [comment]
First, when i download a latest weekly build of CodeLite, i have wrong fyle type name
codelite.app.targz
So, i am renamed it to codelite.app.tar.gz and extract.
After i am update Codelite and run it, i have trouble with debugger select in project properties.
I can see GDB debugger in selected list
![2015-04-29 08 49 26](https://cloud.githubusercontent.com/assets/1912842/7385341/bb3fff7a-ee4c-11e4-9f2d-e85d68c4c710.png)

But i am fund fix to my trouble.
I am returned to 7.0 stable version and in project settings select "This application is GUI project"
After this Debug start work correctly.

So, check this in your new version of CL.
Thanks.

**Comment by eranif** [comment]
Thanks this is now fixed in git master
