### ISSUE TITLE
Mac OS Meta keys wrong !!!

### ISSUE THREAD

**Issue by kobzar** [eranif/codelite#744]
Hi. 
As i say before, i am use CL on Mac OS 10 Yosemite.
Today i try change some hotkeys form me.. and stuck....

In settings i see only "Ctrl/Cmd" check box. 
So, example for auto complete i need pressed Command + SPACE. Ctrl + SPACE is not work.
In keybindings.conf i found this:
{
    "description": "Complete Word",
    "accelerator": "Ctrl-SPACE",
    "resourceID": "complete_word",
    "parentMenu": "Edit"
   } 
Why Ctrl worked as Command key?
I have on all of my Mac keyboard Command and Ctrl key.

Do something please. :(
Or say how i can do it myself.

**Comment by kobzar** [comment]
Whats problem to resolve this ticket?

**Comment by eranif** [comment]
There are not technical problems. More of resources issue. 
We are currently 2 developers working on it (David is also managing another open source project...) 
We will fix this once we will get to it... sorry for any inconvenience

**Comment by kobzar** [comment]
OO Thanks!

**Comment by eranif** [comment]
It turns out that its quite impossible to do this using wxWidgets since wxWidgets forces Ctrl to CMD on OSX
