### ISSUE TITLE
All variables in Debugger->Locals view have dissapeared after refresh

### ISSUE THREAD

**Issue by RedSkotina** [eranif/codelite#748]
If you try to open an uninitialized vector_of_int after stopping at the breakpoint 1 in sample, and then press the refresh button, then ALL the variables disappear from view local variables in the debugger.
Pretty print enable.

Sample code:
```c++
#include <vector>
using namespace std;

class Test{
public:
    int s;
    Test(int i){s = i;};
};
int main(int argc, char **argv)
{
    vector<Test*> vector_of_objptr;
    vector_of_objptr.push_back(new Test(11));
    vector_of_objptr.push_back(new Test(22));
    
    Test* ptr = new Test(55);   // here is breakpoint 1
    
    vector<Test> vector_of_obj;
    vector_of_obj.push_back(Test(11));
    vector_of_obj.push_back(Test(22));
    vector<int> vector_of_int;
    vector_of_int.push_back(11);
    vector_of_int.push_back(22);

    return 0;
}
```
output view with comments:
 <pre> DEBUG>>echo open nonexist in this scope vector_of_int
DEBUG>>&"echo open nonexist in this scope vector_of_int\n"
DEBUG>>~"open nonexist in this scope vector_of_int"
open nonexist in this scope vector_of_int
DEBUG>>^done
DEBUG>>00002692-stack-list-variables 2
DEBUG>>00002693-data-list-register-names
DEBUG>>00002694-data-list-register-names
DEBUG>>00002695-data-disassemble -s "$pc -100" -e "$pc + 100" -- 0
DEBUG>>00002696-data-disassemble -s "$pc" -e "$pc + 1" -- 0
DEBUG>>00002692^done,variables=[{name="vector_of_objptr",type="std::vector<Test*, std::allocator<Test*> >"},{name="ptr",type="Test *",value="0x0"},{name="vector_of_obj",type="std::vector<Test, std::allocator<Test> >"},{name="vector_of_int",type="std::vector<int, std::allocator<int> >"},{name="argc",arg="1",type="int",value="1"},{name="argv",arg="1",type="char **",value="0xa12c90"}]
DEBUG>>00002693^done,register-names=["eax","ecx","edx","ebx","esp","ebp","esi","edi","eip","eflags","cs","ss","ds","es","fs","gs","st0","st1","st2","st3","st4","st5","st6","st7","fctrl","fstat","ftag","fiseg","fioff","foseg","fooff","fop","xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7","mxcsr","","","","","","","","","","","","","","","al","cl","dl","bl","ah","ch","dh","bh","ax","cx","dx","bx","","bp","si","di","mm0","mm1","mm2","mm3","mm4","mm5","mm6","mm7"]
DEBUG>>00002697-data-list-register-values N
DEBUG>>00002694^done,register-names=["eax","ecx","edx","ebx","esp","ebp","esi","edi","eip","eflags","cs","ss","ds","es","fs","gs","st0","st1","st2","st3","st4","st5","st6","st7","fctrl","fstat","ftag","fiseg","fioff","foseg","fooff","fop","xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7","mxcsr","","","","","","","","","","","","","","","al","cl","dl","bl","ah","ch","dh","bh","ax","cx","dx","bx","","bp","si","di","mm0","mm1","mm2","mm3","mm4","mm5","mm6","mm7"]
DEBUG>>00002698-data-list-register-values N
DEBUG>>00002695^done,asm_insns=[{address="0x00401583",func-name="main(int, char**)",offset="131",inst="shr    $0xe7,%eax"},{address="0x00401586",func-name="main(int, char**)",offset="134",inst="adc    (%eax),%eax"},{address="0x00401588",func-name="main(int, char**)",offset="136",inst="add    %al,-0x7a74fb14(%ebx)"},{address="0x0040158e",func-name="main(int, char**)",offset="142",inst="jo     0x40158f <main(int, char**)+143>"},{address="0x00401590",func-name="main(int, char**)",offset="144",inst="(bad)  "},{address="0x00401591",func-name="main(int, char**)",offset="145",inst="decl   0x458dcc45(%ecx)"},{address="0x00401597",func-name="main(int, char**)",offset="151",inst="rorb   $0x24,0x1489cc55(%ebp)"},{address="0x0040159e",func-name="main(int, char**)",offset="158",inst="mov    %eax,%ecx"},{address="0x004015a0",func-name="main(int, char**)",offset="160",inst="call   0x4040f0 <std::vector<Test*, std::allocator<Test*> >::push_back(Test* const&)>"},{address="0x004015a5",func-name="main(int, char**)",offset="165",inst="sub    $0x4,%esp"},{address="0x004015a8",func-name="main(int, char**)",offset="168",inst="movl   $0x4,(%esp)"},{address="0x004015af",func-name="main(int, char**)",offset="175",inst="call   0x4017e4 <_Znwj>"},{address="0x004015b4",func-name="main(int, char**)",offset="180",inst="movl   $0x16,(%esp)"},{address="0x004015bb",func-name="main(int, char**)",offset="187",inst="mov    %eax,-0x90(%ebp)"},{address="0x004015c1",func-name="main(int, char**)",offset="193",inst="mov    %eax,%ecx"},{address="0x004015c3",func-name="main(int, char**)",offset="195",inst="call   0x402970 <Test::Test(int)>"},{address="0x004015c8",func-name="main(int, char**)",offset="200",inst="sub    $0x4,%esp"},{address="0x004015cb",func-name="main(int, char**)",offset="203",inst="mov    -0x90(%ebp),%eax"},{address="0x004015d1",func-name="main(int, char**)",offset="209",inst="mov    %eax,-0x30(%ebp)"},{address="0x004015d4",func-name="main(int, char**)",offset="212",inst="lea    -0x40(%ebp),%eax"},{address="0x004015d7",func-name="main(int, char**)",offset="215",inst="lea    -0x30(%ebp),%edx"},{address="0x004015da",func-name="main(int, char**)",offset="218",inst="mov    %edx,(%esp)"},{address="0x004015dd",func-name="main(int, char**)",offset="221",inst="mov    %eax,%ecx"},{address="0x004015df",func-name="main(int, char**)",offset="223",inst="call   0x4040f0 <std::vector<Test*, std::allocator<Test*> >::push_back(Test* const&)>"},{address="0x004015e4",func-name="main(int, char**)",offset="228",inst="sub    $0x4,%esp"},{address="0x004015e7",func-name="main(int, char**)",offset="231",inst="movl   $0x4,(%esp)"},{address="0x004015ee",func-name="main(int, char**)",offset="238",inst="call   0x4017e4 <_Znwj>"},{address="0x004015f3",func-name="main(int, char**)",offset="243",inst="movl   $0x37,(%esp)"},{address="0x004015fa",func-name="main(int, char**)",offset="250",inst="mov    %eax,-0x90(%ebp)"},{address="0x00401600",func-name="main(int, char**)",offset="256",inst="mov    %eax,%ecx"},{address="0x00401602",func-name="main(int, char**)",offset="258",inst="call   0x402970 <Test::Test(int)>"},{address="0x00401607",func-name="main(int, char**)",offset="263",inst="sub    $0x4,%esp"},{address="0x0040160a",func-name="main(int, char**)",offset="266",inst="mov    -0x90(%ebp),%eax"},{address="0x00401610",func-name="main(int, char**)",offset="272",inst="mov    %eax,-0x1c(%ebp)"},{address="0x00401613",func-name="main(int, char**)",offset="275",inst="lea    -0x4c(%ebp),%eax"},{address="0x00401616",func-name="main(int, char**)",offset="278",inst="mov    %eax,%ecx"},{address="0x00401618",func-name="main(int, char**)",offset="280",inst="call   0x403c90 <std::vector<Test, std::allocator<Test> >::vector()>"},{address="0x0040161d",func-name="main(int, char**)",offset="285",inst="lea    -0x2c(%ebp),%eax"},{address="0x00401620",func-name="main(int, char**)",offset="288",inst="movl   $0xb,(%esp)"},{address="0x00401627",func-name="main(int, char**)",offset="295",inst="mov    %eax,%ecx"},{address="0x00401629",func-name="main(int, char**)",offset="297",inst="call   0x402970 <Test::Test(int)>"},{address="0x0040162e",func-name="main(int, char**)",offset="302",inst="sub    $0x4,%esp"},{address="0x00401631",func-name="main(int, char**)",offset="305",inst="lea    -0x4c(%ebp),%eax"},{address="0x00401634",func-name="main(int, char**)",offset="308",inst="lea    -0x2c(%ebp),%edx"},{address="0x00401637",func-name="main(int, char**)",offset="311",inst="mov    %edx,(%esp)"},{address="0x0040163a",func-name="main(int, char**)",offset="314",inst="movl   $0x2,-0x88(%ebp)"},{address="0x00401644",func-name="main(int, char**)",offset="324",inst="mov    %eax,%ecx"},{address="0x00401646",func-name="main(int, char**)",offset="326",inst="call   0x403c20 <std::vector<Test, std::allocator<Test> >::push_back(Test const&)>"}]
DEBUG>>00002696^done,asm_insns=[{address="0x004015e7",func-name="main(int, char**)",offset="231",inst="movl   $0x4,(%esp)"}]
DEBUG>>00002697^done,register-values=[{number="0",value="0"},{number="1",value="2130563072"},{number="2",value="0"},{number="3",value="2686624"},{number="4",value="0x28fe10"},{number="5",value="0x28feb8"},{number="6",value="10562704"},{number="7",value="72"},{number="8",value="0x4015e7 <main(int, char**)+231>"},{number="9",value="[ IF ]"},{number="10",value="35"},{number="11",value="43"},{number="12",value="43"},{number="13",value="43"},{number="14",value="83"},{number="15",value="43"},{number="16",value="0"},{number="17",value="0"},{number="18",value="0"},{number="19",value="0"},{number="20",value="0"},{number="21",value="0"},{number="22",value="0"},{number="23",value="0"},{number="24",value="895"},{number="25",value="0"},{number="26",value="65535"},{number="27",value="0"},{number="28",value="0"},{number="29",value="0"},{number="30",value="0"},{number="31",value="0"},{number="32",value="{v4_float = {0, 0, 0, 0}, v2_double = {0, 0}, v16_int8 = {0 <repeats 16 times>}, v8_int16 = {0, 0, 0, 0, 0, 0, 0, 0}, v4_int32 = {0, 0, 0, 0}, v2_int64 = {0, 0}, uint128 = 0}"},{number="33",value="{v4_float = {0, 0, 0, 0}, v2_double = {0, 0}, v16_int8 = {0 <repeats 16 times>}, v8_int16 = {0, 0, 0, 0, 0, 0, 0, 0}, v4_int32 = {0, 0, 0, 0}, v2_int64 = {0, 0}, uint128 = 0}"},{number="34",value="{v4_float = {0, 0, 0, 0}, v2_double = {0, 0}, v16_int8 = {0 <repeats 16 times>}, v8_int16 = {0, 0, 0, 0, 0, 0, 0, 0}, v4_int32 = {0, 0, 0, 0}, v2_int64 = {0, 0}, uint128 = 0}"},{number="35",value="{v4_float = {0, 0, 0, 0}, v2_double = {0, 0}, v16_int8 = {0 <repeats 16 times>}, v8_int16 = {0, 0, 0, 0, 0, 0, 0, 0}, v4_int32 = {0, 0, 0, 0}, v2_int64 = {0, 0}, uint128 = 0}"},{number="36",value="{v4_float = {0, 0, 0, 0}, v2_double = {0, 0}, v16_int8 = {0 <repeats 16 times>}, v8_int16 = {0, 0, 0, 0, 0, 0, 0, 0}, v4_int32 = {0, 0, 0, 0}, v2_int64 = {0, 0}, uint128 = 0}"},{number="37",value="{v4_float = {0, 0, 0, 0}, v2_double = {0, 0}, v16_int8 = {0 <repeats 16 times>}, v8_int16 = {0, 0, 0, 0, 0, 0, 0, 0}, v4_int32 = {0, 0, 0, 0}, v2_int64 = {0, 0}, uint128 = 0}"},{number="38",value="{v4_float = {0, 0, 0, 0}, v2_double = {0, 0}, v16_int8 = {0 <repeats 16 times>}, v8_int16 = {0, 0, 0, 0, 0, 0, 0, 0}, v4_int32 = {0, 0, 0, 0}, v2_int64 = {0, 0}, uint128 = 0}"},{number="39",value="{v4_float = {0, 0, 0, 0}, v2_double = {0, 0}, v16_int8 = {0 <repeats 16 times>}, v8_int16 = {0, 0, 0, 0, 0, 0, 0, 0}, v4_int32 = {0, 0, 0, 0}, v2_int64 = {0, 0}, uint128 = 0}"},{number="40",value="[ IM DM ZM OM UM PM ]"},{number="55",value="0"},{number="56",value="0"},{number="57",value="0"},{number="58",value="-96"},{number="59",value="0"},{number="60",value="-48"},{number="61",value="0"},{number="62",value="-2"},{number="63",value="0"},{number="64",value="-12288"},{number="65",value="0"},{number="66",value="-352"},{number="68",value="-328"},{number="69",value="11408"},{number="70",value="72"},{number="71",value="{uint64 = 0, v2_int32 = {0, 0}, v4_int16 = {0, 0, 0, 0}, v8_int8 = {0, 0, 0, 0, 0, 0, 0, 0}}"},{number="72",value="{uint64 = 0, v2_int32 = {0, 0}, v4_int16 = {0, 0, 0, 0}, v8_int8 = {0, 0, 0, 0, 0, 0, 0, 0}}"},{number="73",value="{uint64 = 0, v2_int32 = {0, 0}, v4_int16 = {0, 0, 0, 0}, v8_int8 = {0, 0, 0, 0, 0, 0, 0, 0}}"},{number="74",value="{uint64 = 0, v2_int32 = {0, 0}, v4_int16 = {0, 0, 0, 0}, v8_int8 = {0, 0, 0, 0, 0, 0, 0, 0}}"},{number="75",value="{uint64 = 0, v2_int32 = {0, 0}, v4_int16 = {0, 0, 0, 0}, v8_int8 = {0, 0, 0, 0, 0, 0, 0, 0}}"},{number="76",value="{uint64 = 0, v2_int32 = {0, 0}, v4_int16 = {0, 0, 0, 0}, v8_int8 = {0, 0, 0, 0, 0, 0, 0, 0}}"},{number="77",value="{uint64 = 0, v2_int32 = {0, 0}, v4_int16 = {0, 0, 0, 0}, v8_int8 = {0, 0, 0, 0, 0, 0, 0, 0}}"},{number="78",value="{uint64 = 0, v2_int32 = {0, 0}, v4_int16 = {0, 0, 0, 0}, v8_int8 = {0, 0, 0, 0, 0, 0, 0, 0}}"}]
DEBUG>>00002698^done,register-values=[{number="0",value="0"},{number="1",value="2130563072"},{number="2",value="0"},{number="3",value="2686624"},{number="4",value="0x28fe10"},{number="5",value="0x28feb8"},{number="6",value="10562704"},{number="7",value="72"},{number="8",value="0x4015e7 <main(int, char**)+231>"},{number="9",value="[ IF ]"},{number="10",value="35"},{number="11",value="43"},{number="12",value="43"},{number="13",value="43"},{number="14",value="83"},{number="15",value="43"},{number="16",value="0"},{number="17",value="0"},{number="18",value="0"},{number="19",value="0"},{number="20",value="0"},{number="21",value="0"},{number="22",value="0"},{number="23",value="0"},{number="24",value="895"},{number="25",value="0"},{number="26",value="65535"},{number="27",value="0"},{number="28",value="0"},{number="29",value="0"},{number="30",value="0"},{number="31",value="0"},{number="32",value="{v4_float = {0, 0, 0, 0}, v2_double = {0, 0}, v16_int8 = {0 <repeats 16 times>}, v8_int16 = {0, 0, 0, 0, 0, 0, 0, 0}, v4_int32 = {0, 0, 0, 0}, v2_int64 = {0, 0}, uint128 = 0}"},{number="33",value="{v4_float = {0, 0, 0, 0}, v2_double = {0, 0}, v16_int8 = {0 <repeats 16 times>}, v8_int16 = {0, 0, 0, 0, 0, 0, 0, 0}, v4_int32 = {0, 0, 0, 0}, v2_int64 = {0, 0}, uint128 = 0}"},{number="34",value="{v4_float = {0, 0, 0, 0}, v2_double = {0, 0}, v16_int8 = {0 <repeats 16 times>}, v8_int16 = {0, 0, 0, 0, 0, 0, 0, 0}, v4_int32 = {0, 0, 0, 0}, v2_int64 = {0, 0}, uint128 = 0}"},{number="35",value="{v4_float = {0, 0, 0, 0}, v2_double = {0, 0}, v16_int8 = {0 <repeats 16 times>}, v8_int16 = {0, 0, 0, 0, 0, 0, 0, 0}, v4_int32 = {0, 0, 0, 0}, v2_int64 = {0, 0}, uint128 = 0}"},{number="36",value="{v4_float = {0, 0, 0, 0}, v2_double = {0, 0}, v16_int8 = {0 <repeats 16 times>}, v8_int16 = {0, 0, 0, 0, 0, 0, 0, 0}, v4_int32 = {0, 0, 0, 0}, v2_int64 = {0, 0}, uint128 = 0}"},{number="37",value="{v4_float = {0, 0, 0, 0}, v2_double = {0, 0}, v16_int8 = {0 <repeats 16 times>}, v8_int16 = {0, 0, 0, 0, 0, 0, 0, 0}, v4_int32 = {0, 0, 0, 0}, v2_int64 = {0, 0}, uint128 = 0}"},{number="38",value="{v4_float = {0, 0, 0, 0}, v2_double = {0, 0}, v16_int8 = {0 <repeats 16 times>}, v8_int16 = {0, 0, 0, 0, 0, 0, 0, 0}, v4_int32 = {0, 0, 0, 0}, v2_int64 = {0, 0}, uint128 = 0}"},{number="39",value="{v4_float = {0, 0, 0, 0}, v2_double = {0, 0}, v16_int8 = {0 <repeats 16 times>}, v8_int16 = {0, 0, 0, 0, 0, 0, 0, 0}, v4_int32 = {0, 0, 0, 0}, v2_int64 = {0, 0}, uint128 = 0}"},{number="40",value="[ IM DM ZM OM UM PM ]"},{number="55",value="0"},{number="56",value="0"},{number="57",value="0"},{number="58",value="-96"},{number="59",value="0"},{number="60",value="-48"},{number="61",value="0"},{number="62",value="-2"},{number="63",value="0"},{number="64",value="-12288"},{number="65",value="0"},{number="66",value="-352"},{number="68",value="-328"},{number="69",value="11408"},{number="70",value="72"},{number="71",value="{uint64 = 0, v2_int32 = {0, 0}, v4_int16 = {0, 0, 0, 0}, v8_int8 = {0, 0, 0, 0, 0, 0, 0, 0}}"},{number="72",value="{uint64 = 0, v2_int32 = {0, 0}, v4_int16 = {0, 0, 0, 0}, v8_int8 = {0, 0, 0, 0, 0, 0, 0, 0}}"},{number="73",value="{uint64 = 0, v2_int32 = {0, 0}, v4_int16 = {0, 0, 0, 0}, v8_int8 = {0, 0, 0, 0, 0, 0, 0, 0}}"},{number="74",value="{uint64 = 0, v2_int32 = {0, 0}, v4_int16 = {0, 0, 0, 0}, v8_int8 = {0, 0, 0, 0, 0, 0, 0, 0}}"},{number="75",value="{uint64 = 0, v2_int32 = {0, 0}, v4_int16 = {0, 0, 0, 0}, v8_int8 = {0, 0, 0, 0, 0, 0, 0, 0}}"},{number="76",value="{uint64 = 0, v2_int32 = {0, 0}, v4_int16 = {0, 0, 0, 0}, v8_int8 = {0, 0, 0, 0, 0, 0, 0, 0}}"},{number="77",value="{uint64 = 0, v2_int32 = {0, 0}, v4_int16 = {0, 0, 0, 0}, v8_int8 = {0, 0, 0, 0, 0, 0, 0, 0}}"},{number="78",value="{uint64 = 0, v2_int32 = {0, 0}, v4_int16 = {0, 0, 0, 0}, v8_int8 = {0, 0, 0, 0, 0, 0, 0, 0}}"}]
DEBUG>>00002699-var-create - @ "vector_of_int"
DEBUG>>00002699^done,name="var1",numchild="0",value="{...}",type="std::vector<int, std::allocator<int> >",thread-id="1",displayhint="array",dynamic="1",has_more="1"
DEBUG>>00002700-var-evaluate-expression "var1"
DEBUG>>00002701-var-update "var1"
DEBUG>>00002702-var-list-children "var1"
DEBUG>>00002700^done,value="{...}"
DEBUG>>00002701^done,changelist=[]
DEBUG>>00002703-data-list-register-names
DEBUG>>00002704-data-disassemble -s "$pc -100" -e "$pc + 100" -- 0
DEBUG>>00002705-data-disassemble -s "$pc" -e "$pc + 1" -- 0
DEBUG>>echo ok. it is not open
DEBUG>>echo try now press refresh button
DEBUG>>00002706-var-update "var1"
DEBUG>>00002707-stack-list-variables 2
DEBUG>>00002708-data-list-register-names
DEBUG>>00002709-data-list-register-names
DEBUG>>00002710-data-disassemble -s "$pc -100" -e "$pc + 100" -- 0
DEBUG>>00002711-data-disassemble -s "$pc" -e "$pc + 1" -- 0
DEBUG>>00002712-var-delete "var1"
DEBUG>>00002713-stack-list-variables 2
DEBUG>>00002714-data-list-register-names
DEBUG>>00002715-data-disassemble -s "$pc -100" -e "$pc + 100" -- 0
DEBUG>>00002716-data-disassemble -s "$pc" -e "$pc + 1" -- 0
DEBUG>>echo all variables is dissapear </pre> 

Tested with gdb 7.7 and gdb 7.9, Codelite 7.0

Comments:  
Codelite tries to update the variables instead of requesting a complete list of variables

**Comment by eranif** [comment]
This is a bug in GDB and not in CodeLite
GDB simply is spinning trying to expand the uninitialized vector, thus making it unresponsive (notice that you can not even step to the next line)
