### ISSUE TITLE
DatabaseExplorer: ERD view not displayed

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#750]
Hi Eran,

on wxGTK2 and wxGTK3 the ERD view in the DatabaseExplorer plugin seems to be buggy. It simply
displays nothing...
![empty_erd](https://cloud.githubusercontent.com/assets/1535691/7453381/a0f4be2e-f268-11e4-8cd6-d7641470a296.png)

When I import some ERD from an existing DB I can see everything in the print preview, but it won't show up in the GUI. Maybe some resize is missing?

Regards,
  René

**Comment by eranif** [comment]
What happens when you open a DB and dnd one of the tables onto the ERD view? (it works for me)

**Comment by upCASE** [comment]
Nope, stays blank. Also when using "Create ERD from table" on right clicking the table. Starting out with a "fresh" one by clicking "Open ERD view" in the plugin toolbar results in the image above.
BTW: This used to work up until some weeks ago, that's when I last used it...

**Comment by eranif** [comment]
Hmm, the DB explorer was not modified for quite a while now (at least since
7.0 release)

On Mon, May 4, 2015 at 4:00 PM, upCASE <notifications@github.com> wrote:

> Nope, stays blank. Also when using "Create ERD from table" on right
> clicking the table. Starting out with a "fresh" one by clicking "Open ERD
> view" in the plugin toolbar results in the image above.
> BTW: This used to work up until some weeks ago, that's when I last used
> it...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eranif/codelite/issues/750#issuecomment-98699619>.
>



-- 
Eran Ifrah,
Author of codelite, a cross platform open source C/C++ IDE:
http://www.codelite.org
CodeLite IDE Blog: http://codeliteide.blogspot.com/

**Comment by upCASE** [comment]
O.k., could be a problem on my side. Apparently my latest build uses wxWidget git, not stable 3.0.2. I'm recompiling now.

**Comment by eranif** [comment]
Note that recent wxWidgets (git) contains many assert and fixes to various sizer flags
Are you using a debug version of wxWidgets or are you building it without asserts?

**Comment by upCASE** [comment]
That was a simple release build.
Yes, the problem was the wxWidgets version. all fine now. Sorry for the fuzz.
