### ISSUE TITLE
Code Completition regarding MSYS2

### ISSUE THREAD

**Issue by davidwed** [eranif/codelite#752]
Hi,

the "Search Paths" of the Code Completition shows the wrong entries if you chose the mingw64 with MSYS2 ( https://msys2.github.io/ ).

This is what CodeLite suggest ( with the Suggest button ):
°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°

C:\msys64\mingw64\lib\gcc\mingw32\4.9.2\include\c++
C:\msys64\mingw64\lib\gcc\mingw32\4.9.2\include\c++\mingw32
C:\msys64\mingw64\lib\gcc\mingw32\4.9.2\include\c++\backward
C:\msys64\mingw64\lib\gcc\mingw32\4.9.2\include
C:\msys64\mingw64\include
C:\msys64\mingw64\lib\gcc\mingw32\4.9.2\include-fixed

That's how it should be:
°°°°°°°°°°°°°°°°°°°°°°°°°

C:\msys64\mingw64\include\c++\4.9.2
C:\msys64\mingw64\include\c++\4.9.2\x86_64-w64-mingw32
C:\msys64\mingw64\include\c++\4.9.2\backward
C:\msys64\mingw64\include
C:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\4.9.2\include-fixed

C:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\4.9.2\include
C:\msys64\mingw64\x86_64-w64-mingw32\include
C:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\4.9.2\install-tools\include
C:\msys64\mingw64\lib\libffi-3.2.1\include

**Comment by eranif** [comment]
Fixed and closed.
