### ISSUE TITLE
needs a nice big icon for Ubuntu

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#753]
the codelite icon when displayed in the left-hand side taskbar on Ubuntu is clearly pixelated, and it's even worse when doing ALT-TAB window switching.

**Comment by eranif** [comment]
Do you know what is the recommended size?

**Comment by grandinj** [comment]
For the left-hand taskbar, 48 pixels is the default size, 16 the minimum and 64 the maximum.
So if you make it 64, it should scale it down decently enough.

For the application switcher, it seems to be either 96 or 128, depending on which version of Ubuntu you have.

**Comment by eranif** [comment]
I could not find / create such icon...
If your skills are better than mine (new icons is also most welcomed!) a pull request with the new icon will be great ;)
I am going to close this bug (if a PR is arrived, I will apply it)

**Comment by eranif** [comment]
I have created new logo for CodeLite and it now installs a big nice icon for Linux

**Comment by grandinj** [comment]
Yay!​

**Comment by tomay3000** [comment]
Nice
