### ISSUE TITLE
dialog too small when editing custom build commands

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#754]
Select
  Project Settings->Customize->Custom Build
Then double-click on one of the rows in the 
   Target/Command table
The resulting dialog is not resizable, and the editable area is very small

**Comment by grandinj** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/796121/7533649/821cce84-f573-11e4-9fb5-3a712d9301ec.png)

**Comment by eranif** [comment]
Strange, this dialog _is_ resiable... Try capturing it at the bottom right (its resiable on my Jessies / Mint)
See attached screenshot:

![custom-build](https://cloud.githubusercontent.com/assets/3677711/7534238/61acc786-f581-11e4-9573-f05e7ff6b4b5.png)

**Comment by grandinj** [comment]
My mistake, sorry about that
