### ISSUE TITLE
find-in-files dialog, can't edit file mask

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#755]
The "File Mask" dropdown doesn't allow me to add extra items or to edit it.

Specifically, in this case, when I did "Import Files" it imported all of my "*.hxx" files and now I want to be able to search them :-)

It would probably be easiest for me if this was an editable field, with a default value of "*.*" and a short history of values that could be called up via a dropdown list.

Thanks a lot for the great work! I'm using this to work on LibreOffice, which most IDE's choke on, but CodeLite is doing great right now!

**Comment by eranif** [comment]
Its editable...
See attached screenshot ..

![5-8-2015 5-21-27 pm](https://cloud.githubusercontent.com/assets/3677711/7538168/dcf4d92c-f5a6-11e4-81ca-a7fcaf01640b.png)

**Comment by grandinj** [comment]
my humble apologies

**Comment by eranif** [comment]
No need to apologize :) Does it work for you?

**Comment by grandinj** [comment]
Yes, it works fine thank you.
