### ISSUE TITLE
not finding clang when building on latest Ubuntu (15.04)

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#759]
This ubuntu has clang 3.6, so I'm seeing:

noel@librebuild:~/codelite/build-release$ cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
-- BUILD_DIRECTORY is set to /home/noel/codelite/build-release
-- OS name Linux
-- wx-config used is: /usr/bin/wx-config
-- wxWidgets version is: 3.0.2
-- gtk version is: 2
-- LIBSSH_LIB is set to /usr/lib/x86_64-linux-gnu/libssh.so
-- PLUGINS_DIR is set to /usr/lib/x86_64-linux-gnu/codelite
-- Using wxAuiNotebook
-- Building in Release mode
-- Executables will be written into /home/noel/codelite/build-release/bin
-- Shared Objects will be written into /home/noel/codelite/build-release/lib
-- Adding -DNDEBUG to definitions
-- CPACK_SYSTEM_NAME ubuntu-vivid-x86_64
-- ARCH 64
-- ARCH_NAME x86_64
/bin/grep: /usr/lib/llvm-3.5/include/clang-c/Index.h: No such file or directory
-- Find libClang result: 
-- Could not find method clang_getCompletionBriefComment, disabling brief comments support

**Comment by eranif** [comment]
Hi,
Is this a fresh build? or building on a previous build?
If the later is the case, try deleting CMakeCache.txt file

**Comment by grandinj** [comment]
Looks like the upgrade left behind a copy of llvm-3.5 (but without the headers), so I removed that. But it still didn't work.
So I removed CMakeCache.txt as you suggested, and that works.
Thanks!
