### ISSUE TITLE
Colors and Fonts dialog does not remember previously selected font

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#761]
The Global Font field in the General tab in "Settings/Colors and Fonts" dialog does not remember previously selected font.

Example:

If a select "Monospace" font - press apply and ok
The next time I go into the dialog it shows "Ubuntu" (again)

It should remember my previous selection

CodeLite-8.0-1 on ArchLinux

**Comment by tp0** [comment]
Same here. 8.1.0, Ubuntu. Always defaults to the system default font (and not the monospace default font). As long as you don't change the font again in CodeLite, it actually remembers the setting despite not showing it right.
