### ISSUE TITLE
Feature Request: Global theme preview

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#762]
Feature Request: Global Theme preview

it is a cumbersome job finding a suitable theme - you have to select a theme and press apply/ok to close the dialog - and if that theme does not fit your needs - then you'll have to go over that process all over - again and again...  - again and again...  - again and again... :-)

**Comment by eranif** [comment]
As a temporary workaround, you can run the "Help->Run Setup Wizard"
and click next until you find the "Colours" page, there you have preview (don't forget to cancel the wizard instead of finish ;) )

**Comment by uffejakobsen** [comment]
:+1:
