### ISSUE TITLE
codelite 8.0 abbreviation plugin does not work in Ubuntu 14.04

### ISSUE THREAD

**Issue by LCtech** [eranif/codelite#763]
I upgraded from codelite 7.0 to codelite 8.0 in Ubuntu 14.04. Everything works well except the abbreviation plugin. I purged the old version, tried installing from source, tried installing from repository. Same problem, abbreviation still does not work. Any ideas?

**Comment by eranif** [comment]
Thanks for reporting this - fixed in git master

Eran

**Comment by eranif** [comment]
Try building from sources, sorry for this inconvenience (should be fixed now)

**Comment by LCtech** [comment]
OK, thanks, Eran. I will try to reinstall it and see how it works.

**Comment by eranif** [comment]
@LCtech reinstalling won't help, it is a real bug not an installation problem. I just fixed it (after you reported it), so you should build CodeLite from sources to get the fix

**Comment by LCtech** [comment]
OK, Eran, I understand. I mean recompile from the updated sources and reinstall.

**Comment by eranif** [comment]
:+1:
