### ISSUE TITLE
Abbrevation plugins does not work

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#764]
After upgrading to CodeLite-8.0-1 the "Abbrevation" plugin does not "kick-in".

When pressing the assigned hot key it displays the abbrevation list - but selecting one of the abbrevations does not insert the expected test at cursor position.

seen on CodeLite-8.0-1 (archlinux)

PS: worked fine in CL-7.0

**Comment by eranif** [comment]
Already reported and fixed https://github.com/eranif/codelite/issues/763 :+1:

**Comment by uffejakobsen** [comment]
:+1:
