### ISSUE TITLE
ARM arch

### ISSUE THREAD

**Issue by kobzar** [eranif/codelite#765]
Hello. Do you can add arm support for build?
I think CodeLite will be the best choice for Raspberry/Banana PI Users.
(Most popular OS - Raspbian/Bananian linux (Debian fork))
Thanks!

**Comment by Razish** [comment]
+1, this is a big boost to rpi development having a good IDE + debugger front end

**Comment by jcowgill** [comment]
CodeLite should already work on ARM. It's in the Raspbian repositories right now, although I haven't actually tested it.

https://buildd.debian.org/status/package.php?p=codelite
http://archive.raspbian.org/raspbian/pool/main/c/codelite/

It's only 7.0 at the moment, but I'll get 8.0 uploaded soon.

**Comment by kobzar** [comment]
We waiting for 8 version.
In bananian linux i dont see this pkg. I ask bananian developer or try install CL manual from *.deb after you update release

**Comment by RickCHodgin** [comment]
Try building from sources.

**Comment by kobzar** [comment]
Sorry, but this is no good idea to use IDE in future on debian. Because no many people can build it rom sources and not useful method when update or some else.
This got as more bugtrace until uses.

**Comment by RickCHodgin** [comment]
Download source code.  And from the console window:

```javascriptcd codelite
mkdir build-release
cd build-release
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
make -j4
sudo make install
```

Should be that simple.

**Comment by eranif** [comment]
We have no plan on supporting other platforms at this point.
I think the James solution is more than sufficient, if not you can build it from sources. Its really trivial task

Eran

**Comment by kobzar** [comment]
this is very bad.
Today i try compile it on mac os first and cant. Many errors :( And i am not good compiller.
But you ide is very ligthweit, so raspberri/banana PI community users will be happy!!!
At this time we dont have realy good ide on this oneboard PC. %)
