### ISSUE TITLE
Find in Files dialog box changes position and size

### ISSUE THREAD

**Issue by Espyo** [eranif/codelite#766]
Every time I open the Find in Files dialog box, its height increases by around 32px compared to the last time the box was opened. The top also goes down by what appears to be 32px or so. This increases the dialog's size every time it is used, and can get to the point of being gruesomely huge. Once it reaches the bottom of the screen, it does not go any lower, but keeps increasing in height.

I resize it manually when it reaches a level that annoys me, and the next time I open it, it continues increasing from the size I set when I resized.

I'm on Ubuntu 14.04, with a dual-screen setup. This bug started happening since I installed Codelite 7.0, and persists on 8.0. No other dialog box on Codelite or otherwise appears to do this, and I can get this behavior to happen either from the Find in Files shortcut or the Edit menu. Perhaps it might be noteworthy to say that my File Mask field is a bit long, just in case that the glitch happens when Codelite tries to resize the window according to that field's contents or some such.

**Comment by eranif** [comment]
This is a known problem (to me at least) of wxWidgets and the GNOME (new gnome) interface.
It will happen on all the dialogs that are re-sizable (for example, if you hit Ctrl-Shift-O multiple times, the dialog will shrink until you eventually notice this). The best I can do is to open a bug to wxWidgets

This does not happen on KDE, or Cinnamon DE. If you have another DE installed, it will be great if you could give it a try to confirm it

**Comment by eranif** [comment]
Nothing that we can fix within CodeLite, will get fixed automatically once wxWidgets will fix this
