### ISSUE TITLE
Crash when clicking autocomplete menu item

### ISSUE THREAD

**Issue by Razish** [eranif/codelite#769]
Version: 8.0
OS: Mac OS X Yosemite

Steps to reproduce:
```c
#include <iostream>
int main( int argc, char **argv) {
	int test = 10;
	printf( "test: %i", tes
```
At this point, the auto-completion box is already opened and the `test` variable is selected.
CodeLite crashes when I click on `test` in that menu.

This crash is new as of 8.0 (or the new context menu) and happens regardless of the project/code in use.

**Comment by Razish** [comment]
Bump? This is a very annoying, easy to reproduce crash that has caused a fair amount of lost work.

**Comment by eranif** [comment]
Sorry for the delay. I am in the middle of a major refactoring which is not ready to be pushed yet :/
This will be fixed in the coming days (as first step I will commit a fix that will disable the mouse click on OSX)

**Comment by eranif** [comment]
Fixed
