### ISSUE TITLE
Debug - full step

### ISSUE THREAD

**Issue by kobzar** [eranif/codelite#770]
Hi.
I am use CL to develop STM32 on Mac OS.
Some time, in debugger, i am used step by step mode. But usually i am need run full code(run all steps) and looked how it works. I most do it in debugger, be cause debugger connect to st-link(or openocd) and translate code to controller. So, i cant just Run code for resolve it.
Add options "All steps" in debugger please.
Thanks.

**Comment by eranif** [comment]
Did you try to 'Delete all breakpoints' ? from the debugger pane and then Debug->Continue
This will execute the code without stopping

**Comment by kobzar** [comment]
Yes. This is work!
Forgive me for the lamer question. :)

But, have one more questions.
When i start debug i all time see two panels. Compiller + Debug.
I check every settings and dont find how i can disable compiller windows when start debug?
MacOS CL 8.0
![2015-05-14 14 56 52](https://cloud.githubusercontent.com/assets/1912842/7631345/7b9cd682-fa49-11e4-973c-b6fc3321d8da.png)

**Comment by eranif** [comment]
* Close the `Output view ` by clicking on the x button
* From the `Perspective` menu, save it as the debug perspective

Please don't use the tracker for questions. You can ask your questions on the forum (where more people are watching)
