### ISSUE TITLE
Codelite 8 for Windows knows how to run default MS shell CMD.EXE only

### ISSUE THREAD

**Issue by maxpat78** [eranif/codelite#771]
A typical Makefile for a wxWidgets project invokes the command $(shell wx-config --libs) at various stages during compilation and linking: but the Windows default shell (CMD.EXE) can't perform properly that invocation, whose syntax is UNIXish (for example, the compilation of a .rc resource script fails because of this issue, so one has to do it manually from the command line).

In fact, it is impossible to make CodeLite for Windows execute a Unix-style shell like bash or sh from MinGW/CygWin/MSYS2: even after the COMSPEC environment variable has been set to such a shell, CodeLite passes the "/C" option (instead of "-c") and the pathnames in Windows style (look inside CodeLite/TerminalEmulator.cpp).

Windows users with GNU tools should have the opportunity to switch to GNU shells and use them transparently!

**Comment by eranif** [comment]
CodeLite was built around using native tools for the respective OS, CMD is the shell for Windows.
Changing this requires a lot of effort - which I don't have the resources to invest.

Closing this bug/FR, if you wish to implement such functionality, feel free to submit a pull request
