### ISSUE TITLE
Add SCSS files to PHP project tree

### ISSUE THREAD

**Issue by underdoeg** [eranif/codelite#779]
It would be useful for PHP projects if *.scss files were also added to the source tree. For lack of proper support they could use the css highliting. That should be sufficent for most cases.

**Comment by eranif** [comment]
Fixed. The CSS styler is used to colour .css files. Note that you can change the PHP workspace view by changing the "View" from: right click on the `php project->project settings->general->view`
and add `*.scss`
Once you change it, right click the project and select `Sync with file system`

**Comment by underdoeg** [comment]
That was fast, thanks. I guess with "The CSS styler is used to colour .css files" you meant "The CSS styler is used to colour .**s**css files" ?

**Comment by eranif** [comment]
Yes, you are right ;). I updated my original comment
