### ISSUE TITLE
Zeal Integration CodeLite 8

### ISSUE THREAD

**Issue by Brian245** [eranif/codelite#781]
I have the latest version of CodeLite installed and there seems to be a problem with Zeal integration under Ubuntu 14.04 LTS.  If I select text I can 'Right Click" and select the last item on the list - "Search the docs for 'xxxx'" and Zeal will launch and display the appropriate help in the foreground.  F1 now seems to toggle the output view window at the bottom of the screen that has "Build, Search, Replace, etc.".

Prior to installing Zeal, the References tab would select and it appeared to be displaying a text look, probably from 'man' (manpages).  If I go to settings, F1 is mapped to search the docs for the selected text.

Has anyone else has this problem.  Thank you for your help!
Brian

**Comment by eranif** [comment]
This is because you have upgraded your CodeLite from previouse versions where `F1` was the designated key for toggling the output view.

To re-assign the keys: `Settings->Keyboard Shortcuts->Defaults button`
This will fix it for you
