### ISSUE TITLE
Cant install under Ubuntu 14.04

### ISSUE THREAD

**Issue by Murii** [eranif/codelite#783]
When I'm installing codelite from software center I get this: 

The following packages have unmet dependencies:

codelite: Depends: libgcc1 (>= 1:4.1.1) but 1:4.9.1-0ubuntu1 is to be installed
          Depends: zlib1g (>= 1:1.1.4) but 1:1.2.8.dfsg-1ubuntu1 is to be installed

**Comment by eranif** [comment]
Which repo are you using?

**Comment by Murii** [comment]
The one from codelite s site

Trimis de pe iPhone-ul meu

Pe 19.05.2015, la 17:58, Eran Ifrah <notifications@github.com> a scris:

**Comment by Murii** [comment]
Any ideas on how to fix this?

**Comment by eranif** [comment]
Can you please paste here the relevant lines from your `/etc/apt/sources.list`

**Comment by SaintDako** [comment]
FWIW: I'm using Ubuntu 14.04 and was able to install CodeLite following the instructions on the download page today.
