### ISSUE TITLE
wxCrafter Feature Request: generate wxSimplebook XRC

### ISSUE THREAD

**Issue by MaartenBent** [eranif/codelite#785]
Generating XRC for a wxSimplebook with some pages is currently not possible in wxCrafter. It results in the following XRC code:

`<object class="unknown" name="my_simple_book"/>`

The XRC handler for wxSimplebook was added in wxWidgets 3.0.2 (5f9bd367).

**Comment by eranif** [comment]
Implemented

**Comment by MaartenBent** [comment]
Thanks.

There is one small issue. In wxCrafter, wxSimplebook is assigned a style (default is wxBK_DEFAULT) which is not supported in XRC, resulting in ```XRC error: <line>: unknown style flag "wxBK_DEFAULT"```.
Unchecking the style in wxCrafter resolves the issue.
A permanent fix would be to remove the style choice entirely for wxSimplebook.
