### ISSUE TITLE
Regular expression search doesn't handle line anchors (^ and $) properly

### ISSUE THREAD

**Issue by etfb** [eranif/codelite#788]
Searching for something like ^[a-z] and replacing with XXX should turn the following document:

a
1
+
b
3
z

... into this:

XXX
1
+
XXX
3
XXX

but in CodeLite it only finds the first line (the "a").  The reason for this is that the ^ is erroneously anchoring to the beginning of the document or selection, not the beginning of the line; similarly, $ appears to anchor only to the end of the document or selection, not the end of the line.

Obviously, this makes regular expression search & replace much less useful.

**Comment by eranif** [comment]
This is probably because the string passed to the regular expression is the entire file content. So there is only one anchor `^` and this is the beginning of the document. Probably breaking the file into lines makes more sense here

**Comment by etfb** [comment]
That makes sense.  I'm not sure if you're using the Perl RE engine at the back end, but it does have provision for exactly this sort of problem.  From the perlre pod, on the subject of the available modifiers for regexps (stuff like the "i" for case insensitive in regexps like /hello/i, which matches "hello" and "HELLO" and "hElLo"):

/m

Treat string as multiple lines. That is, change "^" and "$" from matching the start of the string's first line and the end of its last line to matching the start and end of each line within the string.

/s

Treat string as single line. That is, change "." to match any character whatsoever, even a newline, which normally it would not match.

Used together, as /ms, they let the "." match any character whatsoever, while still allowing "^" and "$" to match, respectively, just after and just before newlines within the string.


Seems to me you've got the /s modifier working by default, and you need to make that an extra option and add the /m modifier either by default or as an option as well.

**Comment by eranif** [comment]
Fixed, was missing single flag of `wxRegEx` class: `wxRE_NEWLINE`
