### ISSUE TITLE
Crash after folder already exists error during project creation

### ISSUE THREAD

**Issue by lnishan** [eranif/codelite#790]
OS: Windows 7 64bit Professional
CodeLite 8.0
Criteria:
I created a new project under a folder that has already existed. An error popped up.
However, after the error, the workspace shows a unnamed project.
Afterwards, reloading the workspace / restarting CodeLite and dbl-clicking on the workspace crashes the program.

**Comment by eranif** [comment]
Can you please provide step-by-steps instructions on how to reproduce this?
For example: 
- from the menu -> new workspace
- right click new project
...

**Comment by lnishan** [comment]
Sure. I have reproduced the bug again.
Here are the steps
1. "New Workspace" from the welcome page.
2. Workspace Name: "test", Workspace Path: "F:\
3. After the procedure, "F:\test" is created.
(Without exiting the program)
4. Create a folder "F:\test\test_prj".
5. Create a empty file named "main.cpp" (F:\test\test_prj\main.cpp).
6. Create a project (I used my hotkey which is set to Ctrl-Shift+P) named "test_prj".
7. Error popped up.
![Error popped up](http://i.imgur.com/rmPyqzK.png)
8. An unnamed project is created regardless.
![An unnamed project](http://i.imgur.com/jUpEVqJ.png)
9. Double click on "src/main.cpp" crashes the program.
![Crash](http://i.imgur.com/RZY28Gl.png)

**Comment by eranif** [comment]
Fixed
