### ISSUE TITLE
Collapse All function in project explorer leaves content scrolled out of view

### ISSUE THREAD

**Issue by AlexHowansky** [eranif/codelite#794]
# Observed Behavior
In the project explorer pane, I have a number of projects in my workspace: ![codelite1](https://cloud.githubusercontent.com/assets/296121/7839694/c8ecf8be-0461-11e5-87b1-0470ea079806.png)

I drill down into a number of different folders, and get a growing list of visible subfolders and a shrinking scroll bar, as expected. I scroll all the way to the bottom of the list: ![codelite2](https://cloud.githubusercontent.com/assets/296121/7839711/ddf51264-0461-11e5-8b89-eccb4c50aae8.png)

I then hit the plus sign "Collapse All" button. The projects will collapse as expected, but the scroll position and the size of the scroll bar will remain unmodified. This results is the collapsed projects being positioned out of view -- way "past" the top of the pane: 
![codelite3](https://cloud.githubusercontent.com/assets/296121/7839808/65be27b2-0462-11e5-9171-924753140455.png)

I now have to manually scroll through a large empty space to see my projects: ![codelite4](https://cloud.githubusercontent.com/assets/296121/7839737/02d31414-0462-11e5-8d9f-c8818427208f.png)

# Expected Behavior
When you hit the Collapse All button, the pane should be scrolled to the top so that the collapsed projects are visible. In addition, the size of the scroll bar should be adjusted accordingly.

**Comment by eranif** [comment]
Thanks for reporting this, fixed now.
