### ISSUE TITLE
[Windows] CScope not found, executable seems to be missing

### ISSUE THREAD

**Issue by lnishan** [eranif/codelite#795]
OS: Win 7 Pro (64 bit)  
Used installer: codelite-amd64-8.0.exe  
　
The issue this time is rather simple.  
From my installation directory (C:\Program Files\CodeLite), cscope.exe seems to be missing.
```bash
user@user-PC /cygdrive/c/Program Files/CodeLite
$ ls -f *.exe
codelite.exe               codelite-echo.exe      le_exec.exe  unins000.exe
codelite_cppcheck.exe      codelite-make.exe      ls.exe       wx-config.exe
codelite_indexer.exe       codelite-terminal.exe  makedir.exe  yacc.exe
codelite_launcher.exe      cp.exe                 mv.exe
codelite-cc.exe            flex.exe               patch.exe
codelite-clang-format.exe  grep.exe               rm.exe
```
I did find Cscope.dll under plugins though.

**Comment by eranif** [comment]
We no longer provide cscope executable for Windows, just pick one from the internet, for example:
[this one](https://easy-vim.googlecode.com/files/cscope.exe)
And then set it from: `plugins->cscope->settings`
