### ISSUE TITLE
Wish: choose the language with pull-down menu

### ISSUE THREAD

**Issue by Denisov21** [eranif/codelite#796]
Hi,
Now Codelite is translate in any language.

I'd add a 'menu' where you can choose the language.

Image of 'pull-down menu'
![immagine 1 28052015](https://cloud.githubusercontent.com/assets/2547815/7855065/f95ee6e8-051e-11e5-9ff9-09d6d65d1fca.png)

I was thinking of adding it here:
![immagine 3 28052015](https://cloud.githubusercontent.com/assets/2547815/7855176/d1aae8f8-051f-11e5-8609-241c9eff4335.png)

Obviously the new language entry must have the same style ( color and form of the other pull-down menu). 

Inside in 'Pull-down menu' there are items:

System Default 
English
Chinese
Czech

**Comment by eranif** [comment]
It does not work this way..
If you look on the same dialog under "Encoding Locale" you have there the language to use

**Comment by Denisov21** [comment]
Thank @eranif very much!
