### ISSUE TITLE
build output window should wrap

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#797]
Or have an option to enable wrapping, so I can see long error messages without having to scroll horizontally :-)

**Comment by eranif** [comment]
This is impossible (the current implementation uses wxDataViewCtrl, which is a line based control)
It will need to be re-written from scratch to use a different control... 

A PR (Pull Request) will be very much welcomed :/

**Comment by grandinj** [comment]
Perfectly understable, no problem.
