### ISSUE TITLE
Feature Request: Outline View - Hide Anonymous Members

### ISSUE THREAD

**Issue by justinzane** [eranif/codelite#798]
Things like:

    typedef struct { int x; int y; } point_t;

cause 

    [S] __anon123
        [m] x
        [m] y
    ...
    [t] point_t

to show up in the outline view _separate_ from their associated types when viewing C headers in v8.0. I am requesting that typedefs like these show in outline view like:

    [t][S] point_t
        [m] x
        [m] y

and that the anonymous members be hidden, at least by default.

**Comment by eranif** [comment]
I agree, however, due to lack of resources, I am afraid that this one will not get implemented by me (prioritizing issues) 
A pull request is most welcomed
Sorry, Eran
