### ISSUE TITLE
highlight line in Build Output when stepping through bugs

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#799]
Use case: I use F4 to step through the compile bugs.
It would be nice if each time I hit F4, the relevant line in the build output was selected.
Thanks.

**Comment by eranif** [comment]
It is selected...
It might be something with the fact that the control loses the focus for the text editor
and on your platform, when the control has no focus it clears the selection (or uses a hard to notice colours)
![highlight-build](https://cloud.githubusercontent.com/assets/3677711/8053056/b0b86970-0e95-11e5-8fc8-94735c68ac68.png)
