### ISSUE TITLE
CodeLite 8.0 Windows 7 - Cppcheck errors

### ISSUE THREAD

**Issue by M-griffin** [eranif/codelite#800]
I've gotten several errors when trying to run cpp check in windows 7 under a new Codelite 8 install.

It generations the following command line from my project:
```
Starting cppcheck: C:\Windows\system32\cmd.exe /C "C:\Program Files (x86)\CodeLite\codelite_cppcheck.exe"  --enable=style  --enable=performance  --enable=portability  --enable=unusedFunction  --enable=missingInclude  --enable=information  --std=posix  --std=c99  --std=c++11 --force -j100  --template gcc  -IC:\Users\Blue\Desktop\EtherTerm -IC:\Users\Blue\Desktop\EtherTerm -IC:\Users\Blue\Downloads\SDL2-devel-2.0.3-mingw\SDL2-2.0.3\include -IC:\Users\Blue\Downloads\SDL2_net-devel-2.0.0-mingw\SDL2_net-2.0.0\i686-w64-mingw32\include\SDL2 -IC:\Users\Blue\Downloads\libssh-0.6.4\include -IC:\Users\Blue\Downloads\SDL2_ttf-2.0.12\i686-w64-mingw32\include\SDL2 -DNDEBUG --file-list="C:\Users\Blue\Desktop\EtherTerm\.codelite\cppcheck.list"
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
===== cppcheck analysis ended. Found 0 possible errors=====
```

**'C:\Program'** It appears the system doesn't like the initial setup command line:
```
 C:\Windows\system32\cmd.exe /C "C:\Program Files (x86)\CodeLite\codelite_cppcheck.exe"
```
**If I drop the initial call to cmd.exe and Run just "C:\Program Files (x86)\CodeLite\codelite_cppcheck.exe" manually it will then complain about: -j option**

cppcheck: unusedFunction check can't be used with '-j' option. Disabling unusedF
unction check.

**If i remove the -j option,  it will then complain about std.cfg:**
```
:: information: Failed to load std.cfg. Your Cppcheck installation is broken, pl
ease re-install. The Cppcheck binary was compiled with CFGDIR set to "config/cpp
check" and will therefore search for std.cfg in that path.
```

**It will finally worked, if i changed to the actual codelite program folder, then executed my manyally updated cppcheck command line.**

So it appears cppcheck wants to work from the program current working directory.
Is there maybe an issue with the environment variables?

**Comment by eranif** [comment]
Thanks for reporting this, this bug is already fixed on Git master and will be available 
probably next week with the coming weekly build
Eran

**Comment by M-griffin** [comment]
Thanks.
