### ISSUE TITLE
tab bars ignore gnome font scaling factor

### ISSUE THREAD

**Issue by craflin** [eranif/codelite#802]
Hi,

the new tab bars in Codelite 7.0/8.0 ignore the system font scaling factor in Ubuntu. I guess the tab bars are the only affected gui elements, since the font is properly scaled everywhere else. Restarting Codelite does not help.
![codelite-font-scaling](https://cloud.githubusercontent.com/assets/1309556/7896739/d08d9286-06c3-11e5-9c01-2b3bdc753926.png)

**Comment by craflin** [comment]
The buttons in the find&replace bar are also affected.
![codelite-font-scaling-2](https://cloud.githubusercontent.com/assets/1309556/7896904/f072d1e2-06c8-11e5-94b3-e888db642e24.png)

**Comment by eranif** [comment]
The entire tab bar was refactored. See here: http://codelite.org/LiteEditor/ReleaseNotesCodeLite81
It is now using wxWidgets standard method for getting fonts (this should also include the font scaling factor, if it does not, I will open a bug for wxWidgets)

**Comment by craflin** [comment]
Nice work, thank you!

**Comment by cruzdanilo** [comment]
This still is an issue on 9.1.0.
