### ISSUE TITLE
V 8.0 Completion Hint Persistence Bug

### ISSUE THREAD

**Issue by justinzane** [eranif/codelite#803]
![codelite_completion_hint_bug_v8](https://cloud.githubusercontent.com/assets/1724054/7899056/dd7c44b4-06c9-11e5-97f8-5a15761d1c09.png)

When typing through, instead of allowing the completion system to enter text, the completion hints do not disappear after the context is passed. The only way to remove them is to click in the window with the mouse, which moves the cursor. This is on Linux with KDE KF5/Plasma using codelite v8.

**Comment by eranif** [comment]
clicking ESC will also do the trick
