### ISSUE TITLE
Add  c++14 support

### ISSUE THREAD

**Issue by Denisov21** [eranif/codelite#804]
Hi,
I wish add  C++14 support!

**Comment by Razish** [comment]
In which way?
CodeLite already has C++11 code-completion, and the ability to produce a binary from C++14 code is up to the compiler, not the editor.
If you're asking how to enable C++14 support, you can add `-std=c++14` to your C++ compiler flags in your project settings.

**Comment by eranif** [comment]
Like Razish said, CodeLite already supports C++14, just enable the proper flag

Note: you should really start providing more info in your issues, or they will get closed
