### ISSUE TITLE
Crash on loosing focus; Windows

### ISSUE THREAD

**Issue by Crafter213** [eranif/codelite#807]
Using: CodeLite 8.0 on Windows 7, 64-Bit

EDIT:
When I do the following, CodeLite crashes:

```C++

#include <iostream>

using namespace std;

int main(int argc, char **argv)
{
	//////////////// Crash /////////////////////////////////
	//
	// Steps I need to take to make CodeLite Crash:
	// (CodeLite 8.0, Windows 7, 64-Bit)
	
	string Str;
	
	// 1. Type "Str.". There should be suggestion for the member functions.
	//		-> Str.
	// 2. Remove the Dot by pressing Backspace; do not press any other button. There should still be the list of member functions.
	// 3. Change the active window. Do not use Alt+TAB; instead click on the Icon of another program in the Windows-Bar.
	//		Alternativ: Click on the Windows-Logo-Button with the mouse. (Pressing the Windows-Logo-Key does not crash CodeLite)
	// 
	
	
	
	// 
	////////////////////////////////////////////////////////
	
	
	return 0;
}

```

Example project: http://terraniacraft.bplaced.net/br/Codelite_Bugreport_Crash.zip

**Comment by eranif** [comment]
I am afraid that without a reliable steps to reproduce, I can't do much as it does not crash for me
So either debug it or try to provide a step by step reproduction steps

**Comment by Crafter213** [comment]
I testet a little bit changed my comment.
An example project is now linked.

**Comment by eranif** [comment]
I can't seem to get it to crash :/
Whenever codelite loses focus it dismiss the completion box
I followed the steps exactly as described - and no crash for me

**Comment by eranif** [comment]
Based on your observation, I changed CodeLite behavior to dismiss the code completion box when it loses focus to another application

**Comment by Crafter213** [comment]
I do not know why my Codelite crashes..
Thank you; I am going to try when it is released! :)

**Comment by eranif** [comment]
FYI: we have a "weekly build" releases for Windows. so you don't have to wait until new release is available. See the weekly build forum (it does not yet contain this fix):
http://forums.codelite.org/viewforum.php?f=20
