### ISSUE TITLE
Parameter suggestions gets confused with Constructor/function Calls inside a Constructor/Function with external Library

### ISSUE THREAD

**Issue by Crafter213** [eranif/codelite#809]
Using: CodeLite 8.0 on Windows 7 64-Bit, SFML 2.2

The parameter suggestion works fine for
Function(1, 2, 3);.

When replacing 2 with e.g. a constructor, the parameter suggestions does not correctly notice the new layer:
Typing
Function1(1, Vector2f(x,
leads to the parameter suggestion for Function1 again; not for Vector2f.
When typing the closing bracket ")", the parameter suggestion thinks everything for Function1 is filled in and stops working.

Constructor with expected suggestions: Vector2f(float x, float y).

'''C++
# include <iostream>

// Using SFML 2.2 (MinGW)
# include <SFML/Graphics.hpp>

using namespace std;
using namespace sf;

int main(int argc, char **argv)
{
    // Writing "RenderWindow win(" works; parameters are shown. (Codelite opens a box with info)

```
// Writing "Vector2f vec(" parameter info does not work
// but writing "Vector2<floar> vev(" does.
//
// Within SFML: typedef Vector2<float> Vector2f



RenderWindow win(VideoMode(300, 200), "Test", Style::Titlebar | Style::Close);      // works fine
// "win.setSize(Vector2<float>("  -> no new parameter suggestions for Vector2<float>( or Vector2f(

return 0;
```

}
'''

Project: http://terraniacraft.bplaced.net/br/Codelite_Bugreport_ParamSuggestion.zip

**Comment by eranif** [comment]
Please provide a working example on how to reproduce this.
i.e. a zipped minimal project that shows the problems

**Comment by Crafter213** [comment]
Update
I hope you can reproduce this error ;)
