### ISSUE TITLE
Project dependencies

### ISSUE THREAD

**Issue by slycelote** [eranif/codelite#813]
Are there plans to add project dependencies? It's very hard to live without them.
I'm currently configuring include & library paths manually, but it's tedious ~~and, most importantly, dependent project doesn't get rebuild when a dependency changes~~.
Edit: I just found 'Build Order' option which invalidates the last comment.

**Comment by eranif** [comment]
I have no plans on adding such feature, although its tedious, its a one time effort
As usual, pull requests such functionality are most welcomed
