### ISSUE TITLE
PHP Formatter PSR2 standard

### ISSUE THREAD

**Issue by idwaker** [eranif/codelite#817]
Support for php formatter for PSR standards or support tool like php-cs-fix (https://github.com/FriendsOfPHP/PHP-CS-Fixer)

**Comment by eranif** [comment]
This is now implemented as part of the "Code Formatter" plugin.
I have added the ability to select PHP-CS-Fixer as the main PHP source file formatter

See the attached screenshots:
![php-cs-fixer3](https://cloud.githubusercontent.com/assets/3677711/8225051/84c212bc-1598-11e5-82f8-cb1c2e788635.png)

Set the PHP-CS-FIxer as the primary engine for PHP:
![php-cs-fixer2](https://cloud.githubusercontent.com/assets/3677711/8225054/8e574e64-1598-11e5-8de0-15183f3f6c70.png)

Customize PHP-CS-Fixer:
![php-cs-fixer1](https://cloud.githubusercontent.com/assets/3677711/8225058/9a1d4884-1598-11e5-804c-d9195840db67.png)

From this point on, all you need to do is to hit `Ctrl-I` or `CMD-I` (on OSX) - which is the default shortcut for formatting a file
