### ISSUE TITLE
MemCheck plugin can't be loaded

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#818]
Hi Eran,

in the latest HEAD using wxGTK the memcheck plugin can't be loaded:
[ 08:59:38:171 ERR ] /home/rene/bin/codelite/lib/codelite/MemCheck.so: undefined symbol: _ZNK14MemCheckPlugin13GetEventTableEv

Regards,
 René

**Comment by eranif** [comment]
Fixed
