### ISSUE TITLE
Track preprocessor block color dimming does not work

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#819]
Track preprocessor block color dimming does not work

The dialog says that the "disabled text" color controls the color dimming on preprocessor blocks.

I can only find color entry for "disabled code" - but that does not seem to work on preprocessor blocks

**Comment by eranif** [comment]
The actual bug here is that I left it there...
This dialog no longer controls the color of the disabled text, but this is done automatically

**Comment by eranif** [comment]
BTW, do you have this option enabled? from `settings->code completion->colouring->track preprocessor blocks`

**Comment by uffejakobsen** [comment]
Yes it is with "settings->code completion->colouring->track preprocessor blocks" is enabled that I cannot find a way to control the "dimmed" color of preprocessor blocks that evaluate to false.

At least with the theme that I'm using the "dimming" makes preprocessor sections unreadable and hence also difficult to edit unless I disable the "track preprocessor blocks".

That is why I was looking for a place to adjust the color of the "dimming"

**Comment by eranif** [comment]
This should be fixed now. The dimming algorithm is now improved regardless of the theme you are using
