### ISSUE TITLE
Build error anotations are not shown

### ISSUE THREAD

**Issue by MichalBliznak** [eranif/codelite#820]
Build error annotations are not shown in the code editor any more - just arrow marks (with tooltips displayed on mouse hovering) appears in the left margin. Observed in CodeLite 8.0, Ubuntu 14.04 LTS (64bit).

**Comment by eranif** [comment]
Seems to be working just fine here (Windows and Debian Jessie), check that you have this option enabled: `settings->build-settings->build output appearance`
![build-annon](https://cloud.githubusercontent.com/assets/3677711/8145248/ff559d16-1208-11e5-9afd-1027516337a0.png)
