### ISSUE TITLE
Unable to navigate in source code via mouse click

### ISSUE THREAD

**Issue by MichalBliznak** [eranif/codelite#821]
Navigation  in source code via Alt+mouse click doesn't work in CodeLite 8.0 (also, I cannot found a way how to display context menu allowing jumps into function declaration/definition which was present in previous CL's versions) (observed in Ubuntu 14.04, 64-bit).

**Comment by eranif** [comment]
It works here, if it fails, then it means that it is hooked by your OS to something else which you will need to disable locally.

The small menu was removed.
