### ISSUE TITLE
Drag&Drop onto editor/workspace

### ISSUE THREAD

**Issue by flederwiesel** [eranif/codelite#822]
@Codelite 8.0 Win7 Prof 64-bit SP1

Action: Drag&Drop onto editor
Result: Cursor "n/a" shown, file cannot be dropped
Expected: Dropping opens file in editor

Action: Drag&Drop onto workspace
Result: Cursor "drop" shown, nothing happens upon drop
Expected: File(s) will be added to project folder in workspace

Dropping to somewhere else opens file(s) in editor -> OK.

**Comment by eranif** [comment]
CodeLite is using the built-in control `wxStyledTextCtrl` from the wxWidgets library, this control handle internally the DnD (usually for dragging text inside the editor) and CodeLite can not change this behavior to accept both files and text...

As a workaround, if you drop a file from your File Manager / Explorer on the 'Tab Area' it will be opened within CodeLite

See attached screenshot:
![dnd](https://cloud.githubusercontent.com/assets/3677711/8145219/1dee046c-1208-11e5-8376-ae00b8789abf.png)

Adding support for DnD files from the File Manager onto the Workspace is alot of work for a small feature (which does not justified the effort requires to implement this, pull requests for this are most welcomed)
