### ISSUE TITLE
Find "Match whole word" fails

### ISSUE THREAD

**Issue by flederwiesel** [eranif/codelite#823]
@Win7 Prof 64-bit SP1
@Codelite 8.0

Whether or not "Match whole word" is checked, substrings within words will be matched.

**Comment by eranif** [comment]
I cant seem to reproduce it here, can you please provide a steps for reproduction?

**Comment by eranif** [comment]
Ping

**Comment by flederwiesel** [comment]
Ping reply from flederwiesel time=8h:

Sorry for the delay. I had the problem at work. Seems I cannot reproduce it at home. I hope I can figure it out tomorrow....

**Comment by flederwiesel** [comment]
Hi Eran,

I think I figured it out. I must have selected "[x] Regular Expression" in the Find dialog without being aware of it :( Since the button is not highlighted, I think I missed this - and regex search does not apply the "Whole word" flag (I assume you are responsible for whole word matching using the boundary operators).

Maybe the regex selection should be indicated in some way (a ComboBox would be appropriate in my opinion - although I _personally_ prefer the traditional Dialog Box (like the Replace Dialog) - can one configure this?).

So far, sorry for the noise,
Tobias
