### ISSUE TITLE
Code completion engine should optionally parse implementation files

### ISSUE THREAD

**Issue by metameter** [eranif/codelite#824]
Currently, the code completion parser only parses header files. However, there is a good case for putting function documentation in implementation files as discussed in this [StackOverflow post](http://stackoverflow.com/questions/355619/where-to-put-the-doxygen-comment-blocks-for-an-internal-library-in-h-or-in-cpp).

It would be nice if we had the option to have code completion parse implementation files with CodeLite.

**Comment by eranif** [comment]
Although it might be correct in some cases (no argues here), it is not something that I plan on investing time.
PR are welcome to implement such feature
