### ISSUE TITLE
wxwidgets: Mismatch between the program and library build versions detected.

### ISSUE THREAD

**Issue by underdoeg** [eranif/codelite#825]
This is not a bug within codelite per se. On Arch Linux, after building with aur, I get the error
```
Fatal Error: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1002,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1008,wx containers,compatible with 2.8).
Aborted (core dumped)
```
I understand that this is because the installed version of wxwidgets was compiled with a different compiler than the one currently installed. Other programs however only treat this message as a warning and not a Fatal Error. Is there a compile flag that can be set which enables the same behavior for codelite? 

Over here  somebody suggested to use ./configure with --disable-assert when running into the same issue https://aur.archlinux.org/packages/tintii/

**Comment by eranif** [comment]
The problem is not coming from within CodeLite but from wxWidgets, you will need to build wxWidgets without the assertions

**Comment by sciencesdy** [comment]
I have solved this problem by adding in my source code of the following line:
#define __GXX_ABI_VERSION 1002

**Comment by Likai-CK** [comment]
This worked for me too, exept replacing 1002 with whatever the latest version is that was throwing the mismatch error. It was 1011 in my case, clashing with ABI 1009.

**Comment by drdrbergman** [comment]
@sciencesdy would this line work using visual studio?  Thanks.
