### ISSUE TITLE
Build error on Windows 10

### ISSUE THREAD

**Issue by alexsilva** [eranif/codelite#826]
Default config (last version)

```
C:\WINDOWS\system32\cmd.exe /C ""C:/Program Files (x86)/CodeBlocks/MinGW/bin/mingw32-make.exe" -j8 SHELL=cmd.exe -e -f  Makefile"
"----------Building project:[ hello - Debug ]----------"
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
mingw32-make.exe: *** [All] Error 1
Makefile:4: recipe for target 'All' failed
1 errors, 0 warnings
```

Simple Hello c

```
#include<stdio>

int main() {
	
	printf("Hello");
	
	return 0;
}
```

Look this
```
""C:/Program Files (x86)/CodeBlocks/MinGW/bin/mingw32-make.exe" -j8 SHELL=cmd.exe -e -f  Makefile"
```

The right should be like this
```
"C:/Program Files (x86)/CodeBlocks/MinGW/bin/mingw32-make.exe" -j8 SHELL=cmd.exe -e -f  Makefile
```

**Comment by eranif** [comment]
please it install the compiler properly, as described here:

http://codelite.org/AddNewCompiler/AddNewCompiler

**Comment by alexsilva** [comment]
With codeblocks compilation work, but with Codelite not. Note that codelite are using the compiler installed with the IDE codeblocks.
I will have to install another compiler (elsewhere) to solve a problem that codelite not know how to solve ?

This fixes the problem, but you paid no attention:

```
"C:/Program Files (x86)/CodeBlocks/MinGW/bin/mingw32-make.exe" -j8 SHELL=cmd.exe -e -f  Makefile
```

**Comment by eranif** [comment]
I was reading from my mobile and missed the last part.
what you found that fixes the problem is configurable from the menu bar:
`settings/global editor preferences/terminal`
