### ISSUE TITLE
It does not work in Windows 10

### ISSUE THREAD

**Issue by alexsilva** [eranif/codelite#827]
In the table build can not see the error. Already running on the command line,  the real problems appears.

![bugs](https://cloud.githubusercontent.com/assets/2024086/8199946/0ce9bc04-1494-11e5-87cf-9dd9e998d7a4.PNG)

This project needs to be tested in a real machine, several problems in compiling the project.

I tested with two environments (MingGW, Visual C ++ 11) and two failed.

![compiller_settings](https://cloud.githubusercontent.com/assets/2024086/8199999/c4316614-1494-11e5-8314-17e65e50f3ce.PNG)

**Comment by eranif** [comment]
It will be interesting to see the VC++11 settings, not the MinGW one

**Comment by eranif** [comment]
These are all configuration problems, I don't see a real problem here.
