### ISSUE TITLE
link shared library under same workspace problem

### ISSUE THREAD

**Issue by mylady** [eranif/codelite#828]
hi,
when i create two projects in codelite,like helloworld(console app) and libaaa(shared library)
i set flags for console app to link shared library at runtime
it's fine in the during the build process,helloworld and libaaa.so is generated in each project's Debug folder.then i copy the libaaa.so file next to the helloworld and run the execuable file.There's the error called:"image not found", and the first line appear in console is ./Debug/libaaa.so referenced by somepath/helloworld
it seems there's some config save the library's project config like Output File:${IntermediateDirectory}/${ProjectName}.so
when i change the Output File config to ${ProjectName} and it's ok to be called by helloworld,but it's
generated in root path of libaaa project.

So Is this a bug? i did the same test in eclipse CDT and it works fine.
Thanks!

btw: its on osx 10.10.3 :)

**Comment by eranif** [comment]
Its not a bug, you need to adjust your `LD_LIBRARY_PATH` (or `DYLD_LIBRARY_PATH`) to point to the location of the `.so` file
This can be done from `Project Settings->Environment`

However, this is not how it should be done under OSX:
You should be using the `install_name_tool` to alter the binary and use `@execuable_path` or something similar

**Comment by mylady** [comment]
thank you !
