### ISSUE TITLE
Can't Open Workspace

### ISSUE THREAD

**Issue by DontKnowAnything** [eranif/codelite#829]
I am using CodeLite 7 on a laptop running Windows 7 64-bit. For reason, when I try to open the LiteEditor.workspace, CodeLite hangs and won't do anything. But when I try to open code_utils.workspace, It opens up almost automatically.

**Comment by eranif** [comment]
This does not seems like a likely bug but an environment issue (workspace is the core of codelite)
Please discuss this on the forum
