### ISSUE TITLE
Codelite `ar rcus` is not sufficient for incremental builds under file removal

### ISSUE THREAD

**Issue by Kludgy** [eranif/codelite#830]
`ar rcus target.a` retains stale dependencies, as the archive is not purged by the generated makefiles for builds.

Bugs arise when stale dependencies remain in a project, say after a branch change (which is quite common for many of us) or removing a dependency from the project.

Would it make sense to recreate the archive for every incremental build instead? Do the makefiles rely on incremental additions to archives in some other place?

Reproduction steps:
- Create archive project `A` with `foo.cpp` which introduces some symbol. Create executable project `B` with `bar.cpp`. `B` links archive `A`.
- Build `A` and confirm there are no linker errors.
- Remove `foo.cpp` from `A`. Add `foo.cpp` to project `B`.
- Build `A` and notice the duplicate symbol errors.

**Comment by eranif** [comment]
This is configurable, you can change the command from Settings->build Settings->Compilers->YOUR COMPILER->Tools tab->Archive
