### ISSUE TITLE
Show close button at each tab of search result

### ISSUE THREAD

**Issue by benqqq** [eranif/codelite#831]
as title. is it possible to always show close button at each search result tab? thanks!

**Comment by eranif** [comment]
Can you use the moue middle button "scroll" to close it?

**Comment by benqqq** [comment]
I know it support close tabs by clicking the middle button, but some mouse is not handy at clicking middle button, specially when I have to close lots of tabs. Does this feature will take you too much coding loading? If yes, I'm sorry to bother you about this thing and you could ignore it, thanks!

**Comment by benqqq** [comment]
It seem tabs never show closed button even the active one, could you tell me why did you close this issue by "Implemented"?

**Comment by eranif** [comment]
Because I just implemented this: https://github.com/eranif/codelite/commit/5494eb556b82edc914daf2852e7c44450a2553bb

**Comment by benqqq** [comment]
Thanks, I see.
