### ISSUE TITLE
Tooltip popup at incorrect timing and position

### ISSUE THREAD

**Issue by benqqq** [eranif/codelite#832]
It occur when I move mouse cursor to hover at menu bar, the tooltip will pop up and show the information about the top line of current file.
![sc1](https://cloud.githubusercontent.com/assets/13009249/8297527/f62975b6-1990-11e5-8146-b98387e822fa.png)

Besides, this tooltip won't disappear even switch to other applications or desktop.

**Comment by eranif** [comment]
Fixed in git master
