### ISSUE TITLE
self-closing xhtml tags and indentation

### ISSUE THREAD

**Issue by heyyoyo** [eranif/codelite#834]
When HTML tag is self-closed for example <br />, we should not indent the next element when using CTRL+i

**Comment by eranif** [comment]
Can you provide an example of such a file?

**Comment by heyyoyo** [comment]
Sure simple html :
```html
<!DOCTYPE html>
<html>
<head>
<title>TITLE</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="favicon.ico" type="image/vnd.microsoft.icon" />
<script type="text/javascript" src="script.js" />
</head>
<body>
</body>
</html>
```

**Comment by eranif** [comment]
One problem: the `Ctrl-I` does not support indenting HTML files, only PHP / C / C++ and Java

**Comment by heyyoyo** [comment]
Hum I see... PHP could be inserted inside HTML too.

**Comment by eranif** [comment]
Indeed, in such cases, the indenter skips non PHP sections



On Tue, Jun 23, 2015 at 12:16 PM, heyyoyo <notifications@github.com> wrote:

> Hum I see... PHP could be inserted inside HTML too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eranif/codelite/issues/834#issuecomment-114416519>.
>



-- 
Eran Ifrah,
Author of codelite, a cross platform open source C/C++ IDE:
http://www.codelite.org
CodeLite IDE Blog: http://codeliteide.blogspot.com/
