### ISSUE TITLE
ERROR--Setup-Assistant -- SCAN do not find installed MingW

### ISSUE THREAD

**Issue by S466531257BOSS** [eranif/codelite#835]
Hi.

I installed your 8.0 Version of CodeLite IDE ( http://downloads.codelite.org/downloads.php?windows / DATE -- NOW ) and did the SCAN ( Setup Assistant); whereas it should have been showing off, my already installed MINGW-Stable, but it didn't;

So i downloaded and installed via your SetUp-Assistant; After installing the MINGW-Stable Version it can't find either via SCAN.

After ( in case it haven't recognized yet ) shutdown and upstart freshly the whole system, the SetUp Assistant was presented again, i used SCAN one more time: No installation found.

At that moment: MINGW Stable ( Original ) and MingW Stable via the opened SourceForge TDM-GCC Setup downloaded by your Setup-Assistant are existant and functioning ( checked via cmd/shell );

Once again ( in case a special version is needed by CodeLite ) repeated with all 4 PreSets given in the TDM-GCC-SetUp:

- TDM-GCC Recommended C/C++
- MinGW Stable C/C++
- TDM-GCC Recommended All Packages
- MinGW Stable All Packages

Result: Nothing found by your SCAN-Option in Setup Assistant.

Just in case it is OS-dependent i ran the ( exact same behaving ) procedure on these systems:

- Windows 8.1 Industry Embedded x86
- Windows 7 Enterprise x86
- Windows 8 Professional Media Centre x64
- Windows 8.1 Professional x64
( all on different HardWare from Athlon X2 up to i7 )

also in the following VMs ( Virtual Box ):

- Windows 7 Ultimate x64
- Windows 8.1 Enterprise x86

No luck at all.

THANKS FOR YOUR INTEREST.

PAETH CLAUDIUSRAPHAEL
S466531257 BOSS

**Comment by eranif** [comment]
Where did you install the MinGW packages? (i.e. under which paths)
also, there is no need to re-install everything, just from the Help menu: `Help->Run setup wizard`

Does it work when direct it to the installation folder?
`Settings->Build Settings->Compilers->Add Compilers->Add an existing compiler`

**Comment by eranif** [comment]
?

**Comment by S466531257BOSS** [comment]
Hi eranif.

/*
Where did you install the MinGW packages? (i.e. under which paths)
*/

The paths used are the standard paths as given by the packages : 

%SYSTEMDRIVE%\MinGW
%SYSTEMDRIVE%\TDM-GCC-32

00 : CodeLite-8-0-BUGS-00-SYSTEMDRIVE.png
![codelite-8-0-bugs-00-systemdrive](https://cloud.githubusercontent.com/assets/6672657/8507227/7d7f8cac-2239-11e5-9df0-16146d40c44d.png)

/*
also, there is no need to re-install everything, just from the Help menu: Help->Run setup wizard
*/

I did use that one after my original MinGW ( "%SYSTEMDRIVE%\MinGW" ) could not be found. I already explained in detail in the beginning of the original post.

/*
Does it work when direct it to the installation folder?
Settings->Build Settings->Compilers->Add Compilers->Add an existing compiler
*/

Yes, on 64-bit-Systems directing to the 64-bit Compiler Versions works.
Directing to the 32-bit MinGW or TDM-GCC--MinGW is not working. Neither on 32-bit nor on 64-bit host.


It seems the setup-assistant can not access the already given settings ( e.g.: if paths are manually set ) or simple said : it ignores them.

01 : CodeLite-8-0-BUGS-01-SetUp-Assistant-Starts-Independent-of-Settings.png
![codelite-8-0-bugs-01-setup-assistant-starts-independent-of-settings](https://cloud.githubusercontent.com/assets/6672657/8507228/85a24fc8-2239-11e5-94fe-6f646be51e5e.png)

After reducing %PATH% - entries for MinGW / TDM-GCC to "C:\TDM-GCC-32\bin", exclusive, the next time CodeLite is started the setup-assistant comes up again, but now finds the installed compilers via the Scan-Option.

02 : CodeLite-8-0-BUGS-02-Build-Settings--Scan-worked-after-reduce-PATH-entry.png
![codelite-8-0-bugs-02-build-settings--scan-worked-after-reduce-path-entry](https://cloud.githubusercontent.com/assets/6672657/8507358/d3a34942-223f-11e5-83f8-fc7e06bc3bed.png)

In that manner anything is fine from now on, unless :
If entry "C:\TDM-GCC-32\bin" is deleted from %PATH% , again the SetUp-Assistant asks and Scan-Option finds nothing.

I do not would assume that the SetUp-Assistant and/or its Scan-Option is coupled to the Environment-Variable, though it seems so.

Maybe, there is a check for %PATH%-entries or its equivalents in registry built-in ( e.g.: for quicker search ) and it breaks if not finding a specific setup?

For real, there a zillions of possibilities, however i just wanted to give a hint.

Oh, and maybe the case is (to become some more specific ) :

All these systems run off as either
- Native-VHD-Boot
or
- Hyper-V
or
- VirtualBox-Instances
, so all are inside a VHD ( dynamic and fixed , max size 128GiB , 04kB or 64kB Cluster-size, no seperate system-reserved-/boot- -partition, neither in- nor out-side ). Though this is nothing your SoftWare should be aware of, but possibly something becomes confused, due to that.

However, i do not assign this as a BUG; it is a bug under my specific circumstances.

Btw.:

A) I just checked how CodeLite behaves on a fresh install of Windows 7 ( on a real partition no NVHD-Boot , no Hyper-V ) where no MinGW is installed before CodeLite.
CodeLite started - Downloaded TDM-GCC-MingW - Applied - Works well.

B) When running on a standard install of Windows 7 in Virtual-Box ONLY ( so not configured for other usecases ) CodeLite also works as expected.

So in truth, anything is fine in normal use-cases!

However, nowadays it is not common enough, though in some months due to deployment of Windows 10 features like Hyper-V and native VHD-Boot will become common, so maybe you wish to make your own tests in this direction. Just an idea to counter-check your work to prevent possible upcoming bugs.


THANKS FOR YOUR INTEREST.

PAETH CLAUDIUSRAPHAEL
S466531257 BOSS

**Comment by S466531257BOSS** [comment]
P.s.: In Addition to the specifications of tested Setups :
all Systems where CodeLites SetUp-Assistant fails are set to either :
UAC - OFF
or :
UAC - MAX
;

Maybe this could be a boiling point, too. I think standard-installs range inbetween these, right ?

**Comment by eranif** [comment]
Since this is more of an edge case, I am going to close this bug. Pull Requests are most welcomed!
