### ISSUE TITLE
"Trim trailing spaces" only works for unsaved changes

### ISSUE THREAD

**Issue by jacwah** [eranif/codelite#837]
Pressing Trim trailing spaces under Edit does not remove white space in saved parts of a file. I don't know if this is by design or not since I couldn't find any documentation on it, but it's not intuitive. I would at least want to be able to use the tool on a selection (written to disk or not).

I'm running Codelite 8.0 from http://repos.codelite.org/ubuntu/ on Linux Mint 17.

Steps to reproduce:
1. Open a new file and type "example ".
2. Save the file to disk.
3. Press "Trim trailing spaces".

**Comment by eranif** [comment]
Its a feature. You need to uncheck the option: `Trim only modified files`, see attached image:

![mod](https://cloud.githubusercontent.com/assets/3677711/8512640/793e39a0-2355-11e5-91e2-e2429f18eee4.png)

**Comment by Razish** [comment]
Not quite what OP wanted, he said:
> I would at least want to be able to use the tool on a selection (written to disk or not)
