### ISSUE TITLE
Workspace pane layout isn't remembered

### ISSUE THREAD

**Issue by benqqq** [eranif/codelite#839]
As the attachment, if I drag the Workspace tab and Explorer tab to the downside, and let Zoom Navigator tab and Outline tab at the topside, Codelite won't remember the layout and restore to default (all tabs at together) even I save current layout by manual.

![sc3](https://cloud.githubusercontent.com/assets/13009249/8399853/57b31434-1e48-11e5-8ecb-be8aadf5366b.png)

**Comment by eranif** [comment]
This problem is fixed in git master
