### ISSUE TITLE
Found some words spelling mistakes

### ISSUE THREAD

**Issue by huan5765** [eranif/codelite#840]
1 #: LiteEditor/compiler_pages.cpp:343
msgid ""
"On various platform (e.g. Cygwin) it is recommended to use their own **sepcial** "
"gdb executable rather than the global one\n"
"You can specify one here, or leave this empty to use the default"

change to
msgid ""
"On various platform (e.g. Cygwin) it is recommended to use their own **special** "
"gdb executable rather than the global one\n"
"You can specify one here, or leave this empty to use the default"

2 #: MemCheck/memcheckui.cpp:638 MemCheck/memcheckui.cpp:643
msgid ""
"It is used **intenaly** by this plugin. Valgrind outputs to this file and "
"afterwards the plugin processes this file and shows result."

change to 
msgid ""
"It is used **intenally** by this plugin. Valgrind outputs to this file and "
"afterwards the plugin processes this file and shows result."

3 #: MemCheck/memcheckui.cpp:659
msgid ""
"This file is located in workspace private folder.\n"
"If you don't like this option, you have to add at **leas** one file to list "
"below."

change to 
msgid ""
"This file is located in workspace private folder.\n"
"If you don't like this option, you have to add at **least** one file to list "
"below."

4 #: cppchecker/cppcheckreportbasepage.cpp:86
msgid "Stop the **curreny** analysis"

change to 
#: cppchecker/cppcheckreportbasepage.cpp:86
msgid "Stop the **current** analysis"

**Comment by Razish** [comment]
> change to 
#: cppchecker/cppcheckreportbasepage.cpp:86
msgid "Stop the currency analysis"

Current*?
