### ISSUE TITLE
Disabled code blocks & Macros not working after version 6.0

### ISSUE THREAD

**Issue by hipnition** [eranif/codelite#842]
We have a custom build that properly grey'd out the disabled code in versions below 7.0. In 7.0 to 8.0.1, every #ifdef block is disabled despite macros being defined in the active project settings.

The build is custom. The CC/CCX environment variables have been defined (to codelitegcc) in both the local settings and workspace. Clang on or off makes no difference. Code completion seems to basically work.

As a side note, I tried to move the macros from the active project settings to the workspace settings, but that wouldn't take the settings. After entering and pressing OK, I brought up the dialog again and it was empty.

It's possible I need to set up something differently. Let me know and I can try.

**Comment by eranif** [comment]
It only works for non-custom makefiles project

**Comment by hipnition** [comment]
I use Codelite for embedded projects where the compilers are provided by a 3rd party...but frankly their editors are not as good as yours. I don't expect to Codelite to worm it's way through their compilers, settings, etc. Previously, it seemed to just use the macros provided in the project settings. Can this be the default when the project is custom?

**Comment by eranif** [comment]
It can be done, but the current resources for CodeLite is limited... 
Open a feature request please
