### ISSUE TITLE
Change code navigation keys

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#843]
Hi Eran,

it would be nice if you could include the "Meta"/"Super""/Windows" key for code navigation.
Currently, using wxGTK, I have to use CTRL, as ALT is used by the system to move Windows and
the combination CTRL+ALT doesn't seem to be accepted (the checkbox is enabled, but after closing
and opening the dialog ony CTRL is checked).
My Problem with CTRL is that oftentimes after Using Ctrl+V or Ctrl+C, the code navigation is still 
enabled and takes me somewhere else in my code. Maybe I'm too fast (or too slow) :-)

Regards,
 René

**Comment by sergarrido** [comment]
> My Problem with CTRL is that oftentimes after Using Ctrl+V or Ctrl+C, the code navigation is still
enabled and takes me somewhere else in my code. Maybe I'm too fast (or too slow) :-)

I think this happens because a bug in the code navigation functionality. I have sent a PR to fix it: #1592

**Comment by AJenbo** [comment]
Closing this as the PR was merged
