### ISSUE TITLE
Find Resource is slow in very big projects, add Find File alternative

### ISSUE THREAD

**Issue by ntpg** [eranif/codelite#844]
Find Resource periodically stalls while typing in the dialog box for very large workspaces

I personally find that I use Find Resource to mainly find files in the workspace, not so much symbols. I have resorted to commenting out the DoPopulateTags() call in OpenResourceDialog::DoPopulateList() in my local build of codelite to make Find Resource very fast, but for finding files only.

This has been very useful to me, so I thought it might be useful to others for codelite to support an explicit "Find File Only" dialog.

Thanks

**Comment by eranif** [comment]
Fixed.

**Comment by ntpg** [comment]
Works great. Saves me a ton of time now. Thank you
