### ISSUE TITLE
Git-Plugin: Set repository per project

### ISSUE THREAD

**Issue by skasperski** [eranif/codelite#847]
It seems that the git-plugin can handle only one repository per workspace. Is a workspace where every project is in a separate repository, it would be nice to set a git-root per project.

Best regards,
Sebastian

**Comment by eranif** [comment]
can you please tell me which codelite version are you using?
also which workspace type? c++ or php or...

**Comment by skasperski** [comment]
I am using Codelite 8.0 on Ubuntu 14.04 and it is a  C++ Workspace.

**Comment by eranif** [comment]
I just tested the code and it is working as expected: the git plugin follows the active project.
i.e. whenever changing the active project (this is done by context menu or double clicking on the project item in the tree view) the git plugin will change its repo path to match the project one

**Comment by skasperski** [comment]
Oh thanks, I didn't know that! Then it's cool.
