### ISSUE TITLE
File Mask option for Find In Files is always reset

### ISSUE THREAD

**Issue by ntpg** [eranif/codelite#848]
I am pretty sure this option didn't used to reset. So, not sure when this started happening, but I am currently seeing it in version 8.0.4:
- Open the Find In Files.. dialog
- Change the File Mask to anything other than the default (i.e. \*.\*)
- Perform the search
- Reopen the Find In Files.. dialog
- Notice the File Mask is reset

Can be quite annoying when you are doing a lot of successive searches that require the same file mask

**Comment by eranif** [comment]
Fixed

**Comment by ntpg** [comment]
Thanks, works great!
