### ISSUE TITLE
Can't open the Help field menu directly

### ISSUE THREAD

**Issue by ntpg** [eranif/codelite#849]
Just noticed this when trying to get the current version of codelite.
- If you click on the Help file menu directly, it does not open
- If you click on the PHP file menu (or any other file menu) first, then hover over to the Help menu it opens

**Comment by eranif** [comment]
This is a bug on wxWidgets / KDE desktop environment its probably due to the fact that the Help menu 
is using an already used mnemonic (the underscore under the menu when you click ALT) "H"
It works with GNOME, Windows and OSX.
