### ISSUE TITLE
The workspace build configuration dropdown is too small

### ISSUE THREAD

**Issue by Folcogh** [eranif/codelite#852]
Here a screenshot : http://www.mirari.fr/9FZV.png
It appears on Windows 7, with the nightly build 8.0.4

**Comment by eranif** [comment]
A workaround: you can re-size it (the space between the two dropdowns allows you to resize thedrop downs)
In current git master, this is fixed.
![7-14-2015 6-58-05 pm](https://cloud.githubusercontent.com/assets/3677711/8677898/5f018ae0-2a5a-11e5-9bb3-d44eb5a15b32.png)
