### ISSUE TITLE
Feature Request: Support Assign Hotkey to Switch use tab/space

### ISSUE THREAD

**Issue by benqqq** [eranif/codelite#854]
It seem that not exist settings for assign hotkey to switch "use tab" and "use space" functions, is it possible to add this feature? Besides, is there any way to insert tab when "use space" mode? Thank you!

**Comment by eranif** [comment]
> is there any way to insert tab when "use space" mode? Thank you!

No. You need to disable the "Use Spaces" mode to do that

> It seem that not exist settings for assign hotkey to switch "use tab" and "use space" functions, is it 
> possible to add this feature?

Possible? Yes. However, I don't have the time to invest in it. The fastest way to change between SPACES <-> TABS is via the status bar.

See attached screenshot
![7-17-2015 8-51-40 am](https://cloud.githubusercontent.com/assets/3677711/8741428/4acb3144-2c61-11e5-9a72-40e83bf479f8.png)

Pull requests for this functionality are, as usual, most welcomed

**Comment by benqqq** [comment]
Thanks for your reply, I understand!

**Comment by benqqq** [comment]
Sorry to bother you again. Could you tell me color theme and font at the screenshot? it looks clear and comfortable, thanks!

**Comment by eranif** [comment]
No problem.
I am using the Monokai_2 colour theme.
To see a preview of all available themes (see a preview): Help -> Run the setup wizard
The fourth page allows you select a colour theme:
![7-17-2015 9-26-59 am](https://cloud.githubusercontent.com/assets/3677711/8741757/18027c0e-2c66-11e5-91c0-6b06926a4a49.png)

**Comment by eranif** [comment]
Sorry, I did not say the font name :/
I am using a custom font: `WenQuanYi Micro Hei Mono`

**Comment by benqqq** [comment]
Thank you! :)
