### ISSUE TITLE
Col value is incorrect at Status bar

### ISSUE THREAD

**Issue by benqqq** [eranif/codelite#856]
On "Use Tabs" mode:
1. select multi-rows
2. Press tab key to Insert a tab
3. Col value isn't updated at the status bar

On "Use Spaces" mode:
1. select multi-rows
2. Press tab key to insert spaces
3. Col value update to incorrect value at the status bar

Thank you!

**Comment by eranif** [comment]
It seems to work fine.
Notice that the "Col" is updated to the location of the caret, which seems to be correct.
Can you please provide a screenshot with the caret placed on column A while the value is set to position B?

**Comment by benqqq** [comment]
Select rows
![1_select_rows](https://cloud.githubusercontent.com/assets/13009249/8775707/575a02c8-2f1d-11e5-93bc-5e80d1991798.png)

Press tab
![2_press_tab](https://cloud.githubusercontent.com/assets/13009249/8775717/62a4467a-2f1d-11e5-8910-c7ac36789ca8.png)

Press tab again
![3_press_tab_again](https://cloud.githubusercontent.com/assets/13009249/8775721/6a488f8a-2f1d-11e5-8b17-75fdc50dcd7a.png)

**Comment by eranif** [comment]
Fixed
