### ISSUE TITLE
Bad PATH value

### ISSUE THREAD

**Issue by FuzzyWuzzyBMP** [eranif/codelite#857]
When starting CodeLite via double-clicking on a *.workspace file, or from the start menu, $PATH has an incorrect value. But when starting it via the commandline, the value is (almost) as expected. 

I encountered the issue using CodeLite 8.0, first on kubuntu 14.04 LTS 64 bit, then reproduced it on a fresh install of linux mint 17.2 cinnamon, 64 bit, inside a VirtualBox VM. The only thing I did with the mint OS was update it after installation (on 22. July 2015), and installed g++ (sudo apt-get install g++) and CodeLite (Following the instructions at http://codelite.org/LiteEditor/Repositories#toc1, and choosing ubuntu trusty from Table 1.). All settings in CodeLite were left at their default values.

I added
    `PATH=$PATH:/home/<username>/Documents`
to ~/.bashrc, rebooted, and confirmed via
    `echo $PATH`
that PATH was successfully added to - the command yielded
    `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/<username>/Documents`

Then I created a simple hello world C++ program, via Workspace->New Project->Simple executable (g++), and leaving everything at its default value. I only added
    `echo $(PATH)`
to the Pre Build Commands in the Project Settings. It compiled and ran fine.

However, when starting CodeLite via double-clicking on the .workspace file, or via the start menu, the result of the echo command is
    `/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/bin`
Only when starting CodeLite via the commandline, is the result of echo
    `/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/<username>/Documents:/usr/bin`
which is as expected, except for the `:/usr/bin` at the end.

This issue seems very similar to https://github.com/eranif/codelite/issues/638, but it occurs even when using the default build system of CodeLite.

Tangentially related - if I omit the brackets around PATH in the Pre Build Commands, all I get is echo ATH. But it outputs the PATH just fine when I try the bracketless version in the commandline.

**Comment by eranif** [comment]
Not related to CodeLite.
When launching applications by "double clicking" their icon etc, the `~/.bashrc` is not applied.
I think that you should put it in your `~/.profile`
