### ISSUE TITLE
Make the app portable, and apply for inclusion at PortableApps.com.

### ISSUE THREAD

**Issue by Primality** [eranif/codelite#858]
It should be nice if CodeLite were completely portable and included on the list of apps at PortableApps.com.

On the computer at my workplace, I lack Administrator rights to the Program Files folder. Although I can run executables and install apps into a new folder of my making, installing apps anywhere on the computer is not allowed.

Therefore, I have installed CodeLite as a portable app on my USB drive. I’ve opened the app, opened a file and edited it. While the app seems to be working normally, there were two errors during installation. Two attempts were made to create registry keys, each failing with the same error:
	Error creating registry key:
	HKEY_LOCAL_MACHINE\Software\codelite\settings
	
	RegCreateKeyEx failed; code 5.
	Access is denied.

I suppose that the only effect might be that settings are not saved. However, this is not the case, up to now at least. Therefore, I don’t know whether missing the registry keys has any effect. However, in case that it does, a desired feature should be to compensate for a failure in the registry with a text settings file. There does not appear to be any such file.

If the app is completely portable, it should be eligible for inclusion with PortableApps.com. Inclusion should increase the app’s exposure and user base.

**Comment by eranif** [comment]
I fixed the installer and it can now run without admin privileges, this means that you can now install it on a USB drive.

For saving the data on the USB drive, I don't recommend doing this, as it will slow down CodeLite...
If you insist on doing this:
You should run codelite with `--datadir=/path/to/USB/drive/folder`

**Comment by Primality** [comment]
Thank you.

Date: Thu, 30 Jul 2015 23:07:58 -0700
