### ISSUE TITLE
issue installing codelite

### ISSUE THREAD

**Issue by chetan3399** [eranif/codelite#861]
hi,

i am a newbie to linux and have zero knowledge on the OS. however i am trying to understand the OS and how to use it.
I tried installing codelite on Ubuntu14.02 LTS i had follwoing error. Culd someone pls help

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 codelite : Depends: libglib2.0-0 (>= 2.41.1) but 2.40.0-2 is to be installed
            Depends: libhunspell-1.3-0 (>= 1.3.3) but 1.3.2-6ubuntu2 is to be installed
            Depends: libstdc++6 (>= 4.9) but 4.8.4-2ubuntu1~14.04 is to be installed
            Depends: libwxbase3.0-0 (>= 3.0.2) but it is not going to be installed
            Depends: libwxgtk3.0-0 (>= 3.0.2) but it is not going to be installed
            Recommends: lldb (>= 3.4) but it is not installable
            Recommends: nodejs but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

i have followed all the steps listed in http://codelite.org/LiteEditor/Repositories 
i could not edit /etc/apt/sources.list file and hence used command apt-add-repository
i have used http://repos.codelite.org/ubuntu/ vivid universe repositiry 

thanks in anticipation
Chetan

**Comment by eranif** [comment]
This is not a bug, please report this on the forum for help. http://forums.codelite.org

**Comment by chetan3399** [comment]
thanks
