### ISSUE TITLE
Could not find selected compiler

### ISSUE THREAD

**Issue by milottit** [eranif/codelite#867]
I have codelite 8.0. When I want to compile my project a pop up appears saying: "Some of the compilers referred by the workspace no longer exist. Define each missimg compiler by cloning an existing compiler".
When I select gcc I can click on the validate button. Note than my project is well configured with the right compiler. This issue has been encountered on two different computer with codeblocks working like a charm.

**Comment by eranif** [comment]
This is not a bug.
Some of the compilers referred by some of the projects in the workspace, no longer exists...
All you need to do is one of two:

* Open each project and make sure that you select the compiler from the list (project settings->common settings->general)
* In the dialog that shows up, CodeLite gives you the list of the compilers that are referred by some of the projects but are not defined in CodeLite. All you need to do is to tell CodeLite which compiler to use instead

> with codeblocks working like a charm.

?

**Comment by milottit** [comment]
I already tried this two step and it is not working. If you need some more information let me know.

**Comment by milottit** [comment]
No answer?

**Comment by eranif** [comment]
Can you please provide the `.project` and `.workspace` files of you  workspace?
Also, the file `build_settings.xml` from `~/.codelite/config` folder

Eran

**Comment by milottit** [comment]
Hello,

Unfortunately I can't send files other than PNG, GIF or JPG via the github interface. Have you got an email?

Thomas





I can't sebd the files. With the cithub interf





















![300px-noah2](https://cloud.githubusercontent.com/assets/8853905/9613180/23477c7e-50ea-11e5-94d0-7037bc0fa3f8.jpg)

**Comment by milottit** [comment]
Sorry for the picture. It was a test and I thought that I canceled the picture.

Correction typos:

I can't send files with the github interface.

**Comment by eranif** [comment]
eran.ifrah@gmail.com

On Tue, Sep 1, 2015 at 9:47 PM, milottit <notifications@github.com> wrote:

> Sorry for the picture. It was a test and I thought that I canceled the
> picture.
>
> Correction typos:
>
> I can't send files with the github interface.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eranif/codelite/issues/867#issuecomment-136825263>.
>



-- 
Eran Ifrah,
Author of codelite, a cross platform open source C/C++ IDE:
http://www.codelite.org
CodeLite IDE Blog: http://codeliteide.blogspot.com/

**Comment by AchiloNaval** [comment]
oh god please help me im desperate
![Screen Shot 2021-04-25 at 7 37 11 PM](https://user-images.githubusercontent.com/82723074/116021809-caa43480-a5fd-11eb-9baa-8157b65e5660.png)

![Screen Shot 2021-04-25 at 7 38 02 PM](https://user-images.githubusercontent.com/82723074/116021813-cd068e80-a5fd-11eb-86d3-d05958571fff.png)

![Screen Shot 2021-04-25 at 7 36 34 PM](https://user-images.githubusercontent.com/82723074/116021711-916bc480-a5fd-11eb-951f-3a558951138a.png)

I know nothing about what is happening, I've searched up solutions until I've gotten into a "loop" of revisiting sites I've already seen. please help.

I've even reinstalled Command Line Tools from Xcode (I use a Mac), after my compiler just committed "not exist"
