### ISSUE TITLE
Feature request: C++ options and search resault tab feature at Find In Files dialog

### ISSUE THREAD

**Issue by benqqq** [eranif/codelite#872]
About the "C++" tab options and "Display search results in separate tab" feature, I notice they have been simplified and removed(?) from v8.1. Those features are excellent and I often used them to trace symbols between search result, Would they be re-add to CodeLite in the future? Thank you!

**Comment by hipnition** [comment]
I completely agree. This was a great feature which seems to be gone. I use this a ton to help navigate through legacy/unfamiliar code.

**Comment by eranif** [comment]
The reason that it was removed was because it 50% of the times fails to work.
It needs a redesign (which I plan on making) and it will be back in the next release

**Comment by benqqq** [comment]
Thanks for your reply. I understand. :)

**Comment by eranif** [comment]
A new "history" button was added to the find in files which allows you to jump to previous results in a click

**Comment by eranif** [comment]
Since we are short of resources, this will not get implemented.
You are welcome to fork and contribute. 
Note that some of the requested features on this FR is already implemented and there were some nice additions to the Find In Files as well 

http://codelite.org/LiteEditor/ReleaseNotesCodeLite83

**Comment by benqqq** [comment]
The new FInd in File is really handy. thank you!
