### ISSUE TITLE
New Files .tern-port and .tern-project should be stored in the .codelite folder

### ISSUE THREAD

**Issue by jjvbsag** [eranif/codelite#874]
These files now show up as "unversioned Files" in subversion status. 
As we have the .codelite folder in our "svn:ignore", it would be better to store these files in .codelite.

Or , even better, in a pure embedded C++ project, don't generate these useless files at all.

Nevertheless we now have to touch all our projects to ignore .tern-port and .tern-project, because the current codelite generates these files.

Regards anyway ;-)

PS: Codelite 8.1.0 on Kubuntu 14.04LTS

**Comment by eranif** [comment]
Indeed, they should be generated in the `.codelite` folder (if possible, i.e. when not using a `Node.js` workspace

**Comment by eranif** [comment]
Fixed: for non Node.js workspace, these files are now placed under the `.codelite` folder
