### ISSUE TITLE
 SWTLW="No" in workspace file

### ISSUE THREAD

**Issue by jjvbsag** [eranif/codelite#875]
codelite 8 saves this in the workspace file. Because of this we cannot share projects between codelite 8.0 and codelite 8.1.0, because they change the file on every save and subversion would require a commit every time the codelite version has changed.

Please keep .project and .workspace stable as long as possible. It would be ok to add SWTLW="Yes" when used, but remove it when not used.

Regards Jørgen

Codelite 8.0 / 8.1.0 on Kubuntu 14.04LTS

**Comment by eranif** [comment]
Fixed
