### ISSUE TITLE
Mixed Autocomplete for PHP and C++

### ISSUE THREAD

**Issue by mtangoo** [eranif/codelite#876]
I use CL as my default C++ in Windows/Linux for years now, its fine. I saw PHP plugin so I gave it a test. I found that the AC for PHP includes some C++ one. Here is what I did:
Open CL
Load C++ WS
Use it for some time
Load PHP WS
Try Autocomplete.
Didn't debug it, but I guess some cleaning of C++ AC does not work somehwere.

**Comment by eranif** [comment]
I am not sure where the bug is.
Atm, the current design does not allow mixing between PHP and C++ code completion (only one engine can run at a time)

Can you please elaborate on the exact problem?

**Comment by mtangoo** [comment]
As I said above, the C++ Autocomplete for Previously loaded project was shown in currently Opened PHP Projects. That was CL 8.0. I will see if I can reproduce it in 8.1. If I can I will post details, else I will assume bug is fixed in 8.1 and close this ticket :)

**Comment by eranif** [comment]
Ping. Is this reproduced?

**Comment by mtangoo** [comment]
no I could not get time to do so. I use CL mostly for C++
