### ISSUE TITLE
Codelite constantly uses CPU when not accessed

### ISSUE THREAD

**Issue by hipnition** [eranif/codelite#877]
Codelite 8.1 is constantly doing something even with no user interaction. Previous versions always remained at 0% CPU.
![cpu](https://cloud.githubusercontent.com/assets/10632770/9045968/82e89de0-39f5-11e5-9ce7-9ec346311de1.png)

**Comment by eranif** [comment]
On my windows machine all instances remained with 0 CPU :/
Did you try deleting the `%appdata%\codelite` folder and see if it changes anything?

**Comment by hipnition** [comment]
Deleting that directory didn't help. Closing the workspace didn't help. I did notice that removing all plugins help. Right now it look like 8% with all plugins and 2-3 without. Also, when I close the bottom set of tabs, it drops to 6-7. If I additionally close all edit tabs, it drops to 4-5. If in addition, I close the workspace window, it drops to 0. If I try a combination like, only the welcome edit tab, then I get 4%.

**Comment by eranif** [comment]
Please try this build of CodeLite:
http://codelite.org/downloads/codelite/codelite-amd64-8.1.exe

**Comment by hipnition** [comment]
The build works great. 0%. Thanks!

**Comment by eranif** [comment]
@hipnition  can you please give a short test drive to this installer: http://codelite.org/downloads/codelite/codelite-amd64-8.1.1.exe

**Comment by hipnition** [comment]
I downgrade back to 8.0 and then up to 8.1.1. All worked fine and continued with 0% CPU at idle.

**Comment by eranif** [comment]
Thanks for testing this. Closing the bug
