### ISSUE TITLE
Codelite version 8.1.0 crashes on ubuntu 14.04 LTS with wxWidgets-3.0.0 but works fine with wxWidgets-3.0.2

### ISSUE THREAD

**Issue by nemisi** [eranif/codelite#879]
I guess this issue was already reported.
OS:
Linux bwXY-lnx 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Compiler:
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

I can provide you more information if necessary.

**Comment by dghart** [comment]
Hi,
>I guess this issue was already reported.

Not as far as I know.

Is this a self-built CodeLite, or did you install the deb from our repo?

If it's from our package, could you look inside /usr/lib/x86_64-linux-gnu/codelite/ and see if the wx libs are there e.g. does /usr/lib/x86_64-linux-gnu/codelite/libwx_gtk2u_unofficial_core-3.0.so.0.2.0 exist?

Does the output of
ldd `which codelite`
help? Any missing libs? How about:
ldd `which codelite` | grep unofficial
Are the 'unofficial' libs found (they should be)?

Regards,
David

**Comment by nemisi** [comment]
At first I installed CodeLite 8.1 over apt-get on Ubuntu. It crashed every single time simply by clicking on 'workspace' in menu.  I thought it was because of wxWidget ­3.0.0. Then I removed CodeLite 8.1 over apt-get, downloaded the latest source code of CodeLite from your site, compiled it and installed missing libs and built wxWidget 3.0.2 from source. It works fine now.
I attached more information for you.

myLoginName@bwXY-lnx:~$ sudo ldd /usr/local/bin/codelite
	linux-vdso.so.1 =>  (0x00007fff92e77000)
	libgtk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007f8f85897000)
	libwx_gtk2u_aui-3.0.so.0 => /usr/local/lib/libwx_gtk2u_aui-3.0.so.0 (0x00007f8f85603000)
	libwx_gtk2u_propgrid-3.0.so.0 => /usr/local/lib/libwx_gtk2u_propgrid-3.0.so.0 (0x00007f8f8531b000)
	libwx_gtk2u_stc-3.0.so.0 => /usr/local/lib/libwx_gtk2u_stc-3.0.so.0 (0x00007f8f84edf000)
	libwx_gtk2u_xrc-3.0.so.0 => /usr/local/lib/libwx_gtk2u_xrc-3.0.so.0 (0x00007f8f84bd8000)
	libwx_gtk2u_html-3.0.so.0 => /usr/local/lib/libwx_gtk2u_html-3.0.so.0 (0x00007f8f8490d000)
	libwx_gtk2u_adv-3.0.so.0 => /usr/local/lib/libwx_gtk2u_adv-3.0.so.0 (0x00007f8f8452c000)
	libwx_gtk2u_core-3.0.so.0 => /usr/local/lib/libwx_gtk2u_core-3.0.so.0 (0x00007f8f83d4b000)
	libwx_baseu_xml-3.0.so.0 => /usr/local/lib/libwx_baseu_xml-3.0.so.0 (0x00007f8f83b3b000)
	libwx_baseu_net-3.0.so.0 => /usr/local/lib/libwx_baseu_net-3.0.so.0 (0x00007f8f838ef000)
	libwx_baseu-3.0.so.0 => /usr/local/lib/libwx_baseu-3.0.so.0 (0x00007f8f8345a000)
	libclang-3.6.so.1 => /usr/lib/llvm-3.6/lib/libclang-3.6.so.1 (0x00007f8f827dd000)
	liblibcodelite.so => /usr/local/lib/codelite/liblibcodelite.so (0x00007f8f82275000)
	libplugin.so => /usr/local/lib/codelite/libplugin.so (0x00007f8f81be9000)
	libwxsqlite3.so => /usr/local/lib/codelite/libwxsqlite3.so (0x00007f8f8191b000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8f81617000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8f81400000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8f811e2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8f80e1c000)
	libgdk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0 (0x00007f8f80b69000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f8f80965000)
	libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007f8f80758000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f8f80422000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f8f8021c000)
	libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007f8f7fffa000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f8f7fcee000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f8f7facd000)
	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f8f7f75a000)
	libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007f8f7f544000)
	libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f8f7f2f7000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f8f7f0bb000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f8f7ee69000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f8f7eb61000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8f7e85b000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f8f7e654000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007f8f7e44c000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f8f7e225000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f8f7dfd0000)
	libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007f8f7dd5e000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f8f7db33000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8f7d91a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8f7d715000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8f85f03000)
	libLLVM-3.6.so.1 => /usr/lib/x86_64-linux-gnu/libLLVM-3.6.so.1 (0x00007f8f7b824000)
	libssh.so.4 => /usr/lib/x86_64-linux-gnu/libssh.so.4 (0x00007f8f7b5dd000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f8f7b3da000)
	libwx_gtk2u_ribbon-3.0.so.0 => /usr/local/lib/libwx_gtk2u_ribbon-3.0.so.0 (0x00007f8f7b16c000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f8f7af61000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f8f7ad5e000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f8f7ab4e000)
	libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f8f7a943000)
	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f8f7a739000)
	libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007f8f7a536000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f8f7a332000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f8f7a120000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f8f79e7c000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f8f79c5d000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f8f799b3000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f8f797b0000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f8f795a7000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8f7939e000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f8f7917b000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f8f78f5f000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f8f78d0a000)
	libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007f8f78b01000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f8f788f8000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f8f786ba000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007f8f7849d000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f8f78298000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f8f78076000)
	libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007f8f77e67000)
	libedit.so.2 => /usr/lib/x86_64-linux-gnu/libedit.so.2 (0x00007f8f77c37000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f8f77a0e000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f8f77633000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f8f7742f000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f8f77228000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f8f7700c000)
	libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f8f76e04000)
myLoginName@bwXY-lnx:~$ 

Inside of /usr/lib/x86_64-linux-gnu/codelite:
myLoginName@bwXY-lnx:/usr/lib/x86_64-linux-gnu/codelite$ ll
total 5924
drwxr-xr-x   2 root root    4096 Aug  4 10:13 ./
drwxr-xr-x 122 root root  114688 Aug  4 11:15 ../
-rw-r--r--   1 root root 5939264 Mai  9 19:21 wxCrafter.so
myLoginName@bwXY-lnx:/usr/lib/x86_64-linux-gnu/codelite$ 


myLoginName@bwXY-lnx:/usr/local/lib$ ll
total 26096
drwxr-xr-x  7 root root     4096 Aug  4 12:02 ./
drwxr-xr-x 10 root root     4096 Jul 22  2014 ../
drwxr-xr-x  4 root root     4096 Aug  4 12:02 codelite/
lrwxrwxrwx  1 root root       20 Aug  4 11:47 libwx_baseu-3.0.so -> libwx_baseu-3.0.so.0*
lrwxrwxrwx  1 root root       24 Aug  4 11:47 libwx_baseu-3.0.so.0 -> libwx_baseu-3.0.so.0.2.0*
-rwxr-xr-x  1 root root  3103174 Aug  4 11:47 libwx_baseu-3.0.so.0.2.0*
lrwxrwxrwx  1 root root       24 Aug  4 11:47 libwx_baseu_net-3.0.so -> libwx_baseu_net-3.0.so.0*
lrwxrwxrwx  1 root root       28 Aug  4 11:47 libwx_baseu_net-3.0.so.0 -> libwx_baseu_net-3.0.so.0.2.0*
-rwxr-xr-x  1 root root   374337 Aug  4 11:47 libwx_baseu_net-3.0.so.0.2.0*
lrwxrwxrwx  1 root root       24 Aug  4 11:47 libwx_baseu_xml-3.0.so -> libwx_baseu_xml-3.0.so.0*
lrwxrwxrwx  1 root root       28 Aug  4 11:47 libwx_baseu_xml-3.0.so.0 -> libwx_baseu_xml-3.0.so.0.2.0*
-rwxr-xr-x  1 root root    81015 Aug  4 11:47 libwx_baseu_xml-3.0.so.0.2.0*
lrwxrwxrwx  1 root root       24 Aug  4 11:47 libwx_gtk2u_adv-3.0.so -> libwx_gtk2u_adv-3.0.so.0*
lrwxrwxrwx  1 root root       28 Aug  4 11:47 libwx_gtk2u_adv-3.0.so.0 -> libwx_gtk2u_adv-3.0.so.0.2.0*
-rwxr-xr-x  1 root root  2426820 Aug  4 11:47 libwx_gtk2u_adv-3.0.so.0.2.0*
lrwxrwxrwx  1 root root       24 Aug  4 11:47 libwx_gtk2u_aui-3.0.so -> libwx_gtk2u_aui-3.0.so.0*
lrwxrwxrwx  1 root root       28 Aug  4 11:47 libwx_gtk2u_aui-3.0.so.0 -> libwx_gtk2u_aui-3.0.so.0.2.0*
-rwxr-xr-x  1 root root   749074 Aug  4 11:47 libwx_gtk2u_aui-3.0.so.0.2.0*
lrwxrwxrwx  1 root root       25 Aug  4 11:47 libwx_gtk2u_core-3.0.so -> libwx_gtk2u_core-3.0.so.0*
lrwxrwxrwx  1 root root       29 Aug  4 11:47 libwx_gtk2u_core-3.0.so.0 -> libwx_gtk2u_core-3.0.so.0.2.0*
-rwxr-xr-x  1 root root  7229207 Aug  4 11:47 libwx_gtk2u_core-3.0.so.0.2.0*
lrwxrwxrwx  1 root root       23 Aug  4 11:47 libwx_gtk2u_gl-3.0.so -> libwx_gtk2u_gl-3.0.so.0*
lrwxrwxrwx  1 root root       27 Aug  4 11:47 libwx_gtk2u_gl-3.0.so.0 -> libwx_gtk2u_gl-3.0.so.0.2.0*
-rwxr-xr-x  1 root root   130152 Aug  4 11:47 libwx_gtk2u_gl-3.0.so.0.2.0*
lrwxrwxrwx  1 root root       25 Aug  4 11:47 libwx_gtk2u_html-3.0.so -> libwx_gtk2u_html-3.0.so.0*
lrwxrwxrwx  1 root root       29 Aug  4 11:47 libwx_gtk2u_html-3.0.so.0 -> libwx_gtk2u_html-3.0.so.0.2.0*
-rwxr-xr-x  1 root root  1032379 Aug  4 11:47 libwx_gtk2u_html-3.0.so.0.2.0*
lrwxrwxrwx  1 root root       29 Aug  4 11:47 libwx_gtk2u_propgrid-3.0.so -> libwx_gtk2u_propgrid-3.0.so.0*
lrwxrwxrwx  1 root root       33 Aug  4 11:47 libwx_gtk2u_propgrid-3.0.so.0 -> libwx_gtk2u_propgrid-3.0.so.0.2.0*
-rwxr-xr-x  1 root root  1187826 Aug  4 11:47 libwx_gtk2u_propgrid-3.0.so.0.2.0*
lrwxrwxrwx  1 root root       23 Aug  4 11:47 libwx_gtk2u_qa-3.0.so -> libwx_gtk2u_qa-3.0.so.0*
lrwxrwxrwx  1 root root       27 Aug  4 11:47 libwx_gtk2u_qa-3.0.so.0 -> libwx_gtk2u_qa-3.0.so.0.2.0*
-rwxr-xr-x  1 root root   214773 Aug  4 11:47 libwx_gtk2u_qa-3.0.so.0.2.0*
lrwxrwxrwx  1 root root       27 Aug  4 11:47 libwx_gtk2u_ribbon-3.0.so -> libwx_gtk2u_ribbon-3.0.so.0*
lrwxrwxrwx  1 root root       31 Aug  4 11:47 libwx_gtk2u_ribbon-3.0.so.0 -> libwx_gtk2u_ribbon-3.0.so.0.2.0*
-rwxr-xr-x  1 root root   537254 Aug  4 11:47 libwx_gtk2u_ribbon-3.0.so.0.2.0*
lrwxrwxrwx  1 root root       29 Aug  4 11:47 libwx_gtk2u_richtext-3.0.so -> libwx_gtk2u_richtext-3.0.so.0*
lrwxrwxrwx  1 root root       33 Aug  4 11:47 libwx_gtk2u_richtext-3.0.so.0 -> libwx_gtk2u_richtext-3.0.so.0.2.0*
-rwxr-xr-x  1 root root  2076466 Aug  4 11:47 libwx_gtk2u_richtext-3.0.so.0.2.0*
lrwxrwxrwx  1 root root       24 Aug  4 11:47 libwx_gtk2u_stc-3.0.so -> libwx_gtk2u_stc-3.0.so.0*
lrwxrwxrwx  1 root root       28 Aug  4 11:47 libwx_gtk2u_stc-3.0.so.0 -> libwx_gtk2u_stc-3.0.so.0.2.0*
-rwxr-xr-x  1 root root  2597672 Aug  4 11:47 libwx_gtk2u_stc-3.0.so.0.2.0*
lrwxrwxrwx  1 root root       24 Aug  4 11:47 libwx_gtk2u_xrc-3.0.so -> libwx_gtk2u_xrc-3.0.so.0*
lrwxrwxrwx  1 root root       28 Aug  4 11:47 libwx_gtk2u_xrc-3.0.so.0 -> libwx_gtk2u_xrc-3.0.so.0.2.0*
-rwxr-xr-x  1 root root  1263324 Aug  4 11:47 libwx_gtk2u_xrc-3.0.so.0.2.0*
drwxr-xr-x  2 root root     4096 Feb 17 15:54 pkgconfig/
drwxrwsr-x  4 root staff    4096 Jul 23  2014 python2.7/
drwxrwsr-x  3 root staff    4096 Jul 23  2014 python3.4/
drwxr-xr-x  4 root root     4096 Aug  4 11:39 wx/
myLoginName@bwXY-lnx:/usr/local/lib$

**Comment by dghart** [comment]
Thank you for the update, and I'm glad you've got a working Codelite now.

I can click on the Workspace menu here without crashing. Now you've built your own, working, CodeLite it's impossible to be sure what the cause of the crash was, but one possibility is a missing lib on your system, or a different version of a lib. I doubt if it was a wx lib though, or CodeLite would have crashed on starting.

We'll have to wait and see if there are reports from other users.
