### ISSUE TITLE
Cannot jump to errors/warnings from non-English GCC output

### ISSUE THREAD

**Issue by lanurmi** [eranif/codelite#881]
If GCC outputs errors and warnings in non-English, one cannot jump to the corresponding file by double-clicking the lines in the compiler output. It will not work even after adjusting the Patterns in settings.

The error/warnings lines are properly coloured though. Feels like colouring and double-clicking are two distinct features in the source, with the latter one hard-coded to look for "error:" and "warning:" in English. I didn't check whether this is actually the case though.

**Comment by eranif** [comment]
It not really a bug, but more of a configuration issue.
You need to adjust the regex used for parsing the filename:line from:
Settings->Build Settings->Compilers->Your compiler->Patterns tab

**Comment by lanurmi** [comment]
As I said, I have adjusted the patterns and it does not solve the issue. Colouring of warnings is affected though.

**Comment by eranif** [comment]
Oops, I missed that part
However, my answer remains: the file:line is taken from the regex you provide in the settings.
Can you please show an example for error message and the pattern you used?

**Comment by lanurmi** [comment]
Maybe it was a human error after all, as I made it work by adjusting a regex. Unbelievable. However, in my opinion this doesn't invalidate the bug per se. When using the default regex values, double-clicking does not work, yet all the lines that one would like to click are coloured red, and no other lines are.

So why not make every red line double-clickable? That way the regexes wouldn't need any language-specific adjusting. Perhaps the filename + line cannot be parsed from all messages in all languages, but as the filename:line is mostly at the beginning of the line, it would be possible to cover at least those cases out-of-the-box.

**Comment by eranif** [comment]
Sorry, due to resource limitation this I will not be able to implement this.
A pull request with a suggested fix will be highly appreciated

(not to mention that we have a working workaround)
