### ISSUE TITLE
code formater on double template closing symbols : >>

### ISSUE THREAD

**Issue by padget** [eranif/codelite#882]
When the code is written like this : 
![capture1jpg](https://cloud.githubusercontent.com/assets/10959420/9111415/3ccb8abc-3c47-11e5-9438-1437f203af4e.JPG)

The astyle formatter formats the like this :
![capture2](https://cloud.githubusercontent.com/assets/10959420/9111424/5085ba5a-3c47-11e5-90be-b88f51576ff7.JPG)

This is due to the `public with_systems<std::vector<system*>>,` more precisely due to `>>` at the end of the line.

**Comment by eranif** [comment]
which foramtter are you using? which OS and which CodeLite version?

**Comment by eranif** [comment]
Sorry, missed the part that says "the astyle formatter"
I personally don't use, I am using clang-format which is much more versatile and capable.
To configure it: `plugins->source code formatter->settings->general`
Once you go clang, you never go back ...

**Comment by padget** [comment]
Euh... :D the clang formatter erases the containt of my file.
I think it is due to 'C:\Program' n'est pas reconnu en tant que commande interne
ou externe, un programme excutable ou un fichier de commandes.

This is a french error message. 
My option clang-format path is C:\Program Files\CodeLite\codelite-clang-format.exe.
Maybe if add ' " ' character around the option will be enabled, the issue would be fixed.

**Comment by eranif** [comment]
Strange, we have the exact same settings and it works for me :P

Options to solve this:

* Try copying codelite-clang-foramt.exe and place it on some other location without spaces
* Make sure that the option `settings->global editor preferences->terminal->Windows only: commands executed with CMD.EXE..` is checked

**Comment by padget** [comment]
Yeaaaaaah, it works when there no space. 
Move C:\Program Files\CodeLite\codelite-clang-format.exe is really not a good solution to solve this issue. It is just a workaround.

In the meantime, I have C:\codelite-clang-format.exe for this option :D 

Thanks for your IDE
