### ISSUE TITLE
code completion on double template closing symbols : >>

### ISSUE THREAD

**Issue by padget** [eranif/codelite#883]
THe code completion doesn't work when this `>>` is encountered 
![capture1jpg](https://cloud.githubusercontent.com/assets/10959420/9113651/04bf6436-3c56-11e5-8030-ae716ccb34f3.JPG)
:

**Comment by eranif** [comment]
Enable clang code completion:

settings->code completion->enable clang code completion

Once enabled, rebuild you project and it should work
