### ISSUE TITLE
Cpp Check in Windows is still Broken in 8.02 Release

### ISSUE THREAD

**Issue by M-griffin** [eranif/codelite#886]
Starting cppcheck: C:\Windows\system32\cmd.exe /C "C:\Program Files (x86)\CodeLite\codelite_cppcheck.exe"  --enable=style  --enable=performance  --enable=portability  --enable=unusedFunction  --enable=missingInclude  --enable=information  --std=posix  --std=c99  --std=c++11 --force -j100  --template gcc  -IC:\Users\Blue\Desktop\Test2 -IC:\Users\Blue\Desktop\Test2 -IC:\boost\include\boost-1_58 -IC:\boost\include --file-list="C:\Users\Blue\Desktop\Test2\.codelite\cppcheck.list"
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
===== cppcheck analysis ended. Found 0 possible errors=====

CodeLite 64 bit in Windows 7.  Cpp check is still complaining about 'C:\Program' is being cutoff with a space in the path.  

Maybe an option to manually update this command line, it appears to be hard coded so there is no way to test or fix the issue locally.  Thanks.

**Comment by eranif** [comment]
Hmm, works here ...
With the exact same paths. There seems to be missing double quotes in the command you have.
Make sure that the option:

Settings->Global Editor Preferences->Terminal->Windows only: commands executed with CMD.exe are wrapped with double quotes

**Comment by M-griffin** [comment]
Thank you, that seems to have done the trick!! I've done several upgrades with the last few versions. So maybe this option is not carrying over through updates?  Anyhow thanks again. It's working now.

**Comment by eranif** [comment]
this flag was introduced several versions ago, when this problem was first reported.
On clean setups, this flag is set to true by default, otherwise the old value is kept (which is false, since it was not exist...)
