### ISSUE TITLE
SFTP error "remote channel closed"

### ISSUE THREAD

**Issue by nickname13** [eranif/codelite#890]
Hi to all,
 I  have problem on "mirroring"  big files . The upload always fails with "remote channel closed" error and the file on the "mirrored" workspace becomes a zero-size damaged file. I have to use filezilla to fix the remote file. the problem appears and for the .project file.
After some testing in two different files the problem appears when the size of the file is 262120 bytes or bigger.

I am not sure if it's codelite error or my ssh client or ssh server on the mirrored machine but I  was told to post it here.

Currently I am using:

codelite version 8.1 but the problem has there from 6.X version
it is a self compiled from arch aur https://aur4.archlinux.org/packages/cod ... mments=all but the problem existed and in pre-compiled and in ubuntu
Your OS arch linux but the problem existed and in ubuntu

**Comment by eranif** [comment]
Thanks for reporting this, this looks like a bug in libssh. It seems that it can't handle large files (both reading or writing)
This is fixed now, by writing one chunk at a time. I also changed the "write" method so it will first write to a temp file `<FileName>.sftpcodelite` and once write is done, rename it

**Comment by nickname13** [comment]
I patched it and it works like a charm! Thanks a million! Amazingly fast response!
