### ISSUE TITLE
Move internal file from from the workspace/project root folder 

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#891]
It would be nice to get many internal "temporary" files away from the workspace/project root folder

.tern-project
.tern-port
compile_commands.json
etc

An option could be to place them in the ".codelite" folder..

**Comment by eranif** [comment]
I already moved .tern-* to the .codelite folder for non NodeJS workspaces (e.g. C/C++ and PHP)
The compile_commands.json I think is generated by cmake, but I need to check this (can't remember if I generate one as well)

**Comment by uffejakobsen** [comment]
I believe that CodeLite is (also) generating the file "compile_commands.json" because I see the file in projects that do not use Cmake.

**Comment by eranif** [comment]
Indeed, I just saw a message in the "status bar" generating `compile_commands.json`
