### ISSUE TITLE
hotkey for "set as active"

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#892]
I split my workspace into multiple projects because LibreOffice is too big for one project.

So I tend to switch projects a lot. It would be nice if I could just select a project and hit a key combination.

Thanks

**Comment by eranif** [comment]
Double click does that

**Comment by grandinj** [comment]
Thanks. Which there was a way to make actions like that more discoverable. 

Maybe add some text to the "Set As Active" label?

Something like
  Set As Active (double-click)
with the text "(double-click)" set to italic and maybe lighter weight.

**Comment by eranif** [comment]
I don't think that I can prettify part of the menu text (wxWidgets API). But adding (double click) can be a nice addition

**Comment by eranif** [comment]
Fixed
