### ISSUE TITLE
Problem with breakpoints in C++ function templates

### ISSUE THREAD

**Issue by gtzfinance** [eranif/codelite#893]
<b>Scenario:</b> There are C++ function templates defined in header files, and these function templates have been instantiated more than once.

<b>Problem:</b> In this scenario, set several breakpoints before starting the debugger. Everything's fine. Then start the debugger(gdb). The output tab in the debugger pane will indicate that all breakpoints have been successfully set. And indeed, if you control the breakpoints from the output tab (with commands like "info break", "del 1" etc.), everything is fine. However, codelite's breakpoint tab will not show all breakpoints. The ones that are gone will not show up as red dots in the file's margin in the editor either.

If you allow me to venture a guess, it seems pretty clear what's going on here. For a breakpoint in a function template that has been instantiated several times, gdb's "info break" command will show information like this:
<pre>
1       breakpoint     keep y   &lt;MULTIPLE&gt;
1.1                         y     0x00000000004158ea in [...]
1.2                         y     0x0000000000415c60 in [...]
1.3                         y     0x000000000041c2aa in [...]
</pre>

The lines beginning with 1.1, 1.2, and 1.3, respectively, refer to the different template instantiations. It looks like codelite gets confused by these lines. If it were to ignore them, I believe everything would be fine.

**Comment by eranif** [comment]
Fixed
