### ISSUE TITLE
Feature Request: Allow clicking on "required from" lines in the Build tab of the Output view

### ISSUE THREAD

**Issue by gtzfinance** [eranif/codelite#894]
When working with class and function templates, gcc will often give error messages that contain lines of the following form:

<pre>
/development/MedianProject/SourceFiles/median.cpp:79:84:   required from [...]
/development/MedianProject/SourceFiles/median.cpp:496:70:   required from [...]
/development/MedianProject/SourceFiles/median.cpp:438:66:   required from here [...]
./include/any_iterator/any_iterator.hpp:179:7: error: [...]
</pre>

When I click on the last line, where the file location is followd by the word "error", codelite takes me to the file location. For the lines where the file location is followed by "required from", clicking has no effect. My best guess is that it would not be hard to extend the parsing of the compiler output in such a way that the "required from" lines behave like the "error" lines.

**Comment by eranif** [comment]
This one is a simple configuration:
settings->build settings->compilers->[your compiler]->patterns

Under the "Compiler Error patterns", search for the entry that has this pattern:
`^([^ ][a-zA-Z:]{0,2}[ a-zA-Z\.0-9_/\+\-]+ *)(:)([0-9]*)([:0-9]*)(: )((fatal error)|(error)|(undefined reference))`

and change it to:
`^([^ ][a-zA-Z:]{0,2}[ a-zA-Z\.0-9_/\+\-]+ *)(:)([0-9]*)([:0-9]*)(: )((fatal error)|(error)|(undefined reference)|([\t ]*required from))`
