### ISSUE TITLE
editing code and double-clicking on errors in build output page don't mesh well

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#895]
Use-case:
(a) compile some code
(b) make some edits,  removing or adding a couple of lines
(c) notice that the red-error-markers stay attached to the correct lines in the editor
(d) double-lick on a different error in the output pane
(e) the cursor jumps to the incorrect line

**Comment by grandinj** [comment]
This is using version 8.0.2 and the the clang compiler under Linux, if that makes any difference

**Comment by eranif** [comment]
I am aware of this issue and this one is quite tricky to fix :/
I am going to close this (the task queue is full and I don't have the resource to fix this)
ofc, any pull request that fixes this is most welcomed !
