### ISSUE TITLE
Feature Request: Allow the output pane to handle program input/output

### ISSUE THREAD

**Issue by bsdooby** [eranif/codelite#896]
It would be nice to have the Output pane embed input/ouput just like the codelite terminal. This is similar in behaviour to the way Eclipse and XCode handle console applications. In contrast to the way VisualStudio does input/output (always in a separate terminal).

**Comment by eranif** [comment]
This was the way for CodeLite in previous versions, however, there were too many bugs involved with this embedded terminal that did not make it worth while (to name some: running ncurses applications, debug such applications, custom ASCII progress bars, passwords entry and more)
Eventually we fall back to the native OS terminal.
