### ISSUE TITLE
not building on ubuntu-vivid

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#897]
fully patched Ubuntu

/home/noel/codelite/WebTools/CSSCodeCompletion.cpp: In constructor ‘CSSCodeCompletion::CSSCodeCompletion()’:
/home/noel/codelite/WebTools/CSSCodeCompletion.cpp:35:5: error: ‘for_each’ is not a member of ‘std’
     std::for_each(valuesSet.begin(), valuesSet.end(), [&](const wxString& v) {
     ^
/home/noel/codelite/WebTools/CSSCodeCompletion.cpp: In member function ‘void CSSCodeCompletion::CssCodeComplete(IEditor*)’:
/home/noel/codelite/WebTools/CSSCodeCompletion.cpp:78:13: error: ‘find_if’ is not a member of ‘std’
             std::find_if(m_entries.begin(), m_entries.end(), [&](const Entry& e) { return (e.property == word); });
             ^
WebTools/CMakeFiles/WebTools.dir/build.make:169: recipe for target 'WebTools/CMakeFiles/WebTools.dir/CSSCodeCompletion.cpp.o' failed
make[2]: *** [WebTools/CMakeFiles/WebTools.dir/CSSCodeCompletion.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by eranif** [comment]
Should be fixed now

**Comment by grandinj** [comment]
working! :-)
