### ISSUE TITLE
Values for variables in Watch window don't update

### ISSUE THREAD

**Issue by SternAndrew** [eranif/codelite#898]
I’ve pulled down a new version within the past couple days but while debugging an issue within my code I’ve realized that the values within the Watches window don’t updated as I run stopping at a breakpoint.  Here is the commit that I’m using under a 64 bit version of Linux (RHEL).
 
>git log -1
commit e108fb34b353c6ce23012d48a2f9b583f0f41bb5

**Comment by eranif** [comment]
Fixed, thanks for reporting this
