### ISSUE TITLE
Question about refactoring.db 

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#899]
Hi,

Question about refactoring.db:
When is refactoring.db generated and updated ?

The database takes up multi-gigabytes of storage (on selected projects) 

I have a cleanup job that deletes the refactoring.db file - and Codelite seems to work fine without the refactoring.db - at least I haven't found anything that does not work and seems to need the file.

Than at some (to me unknown) point the refactoring.db file reappears automatically

Would it be possible to have an workspace option ala "Do not generate refactoring.db" ? - that would save a lot of diskspace (for me at least)

/Uffe

**Comment by eranif** [comment]
The file `refactoring.db` is used for the "Find References" implementation.
CodeLite caches all the "words" from all the workspace files so the "Find References" will be as fast as it can. This is done via a background thread and it is executed (IIRC) on "Workspace Load" event

**Comment by eranif** [comment]
BTW: disabling the `refactoring.db` will disable your "Find References" ... 
On my workspace at work, it takes 118MB in size... which seems reasonable

**Comment by eranif** [comment]
OK, looking at the database, we can definitly improve it.
For example, there is no need to keep the file name multiple times, we can simply store its ID from the FILES table...

**Comment by eranif** [comment]
The size should be 1/3 of its size if not less
