### ISSUE TITLE
Build view, scrolling and open file dialog

### ISSUE THREAD

**Issue by anderflash** [eranif/codelite#900]
_Build view_ only shows 20% of content (I can't view build process).
And I can't use the wheel to scroll it, just pressing the scrollbar. It's annoying.
In _Open File Dialog_, I can't press keys to select files based on initials.

Thanks

**Comment by eranif** [comment]
Can you please provide more information? OS you are using? CodeLite version? Did you build CodeLite yourself? etc
Screenshots that shows the problem ...

**Comment by anderflash** [comment]
OS: Linux manjaro 3.19.8.5-1-MANJARO SMP PREEMPT Tue Aug 11 21:44:51 UTC 2015 x86_64 GNU/Linux
Red bars indicate lack of visibility and the whole build view doesn't allow me to scroll it by using the wheel
![codelite-error](https://cloud.githubusercontent.com/assets/755287/9429708/a9d34854-49b0-11e5-992e-465e438c9ad1.png)

Another error Open File/Project/Workspace Dialog. When I press _K_ after clicking some file to get focus, for example, it should select the first folder/file whose name starts with K. But this doesn't happen.

Thanks

**Comment by eranif** [comment]
Hmm, this looks like a bug in wxWidgets.
Which wxWidgets version are you using? is this a self compiled one?

the mouse scroll issue was fixed in wxWidgets version 3.0.2, my guess is that you are using 3.0.0

**Comment by anderflash** [comment]
No, I'm using v3.0.2, from official Manjaro Pacman Repository.

**Comment by eranif** [comment]
Sorry, its definitely a wxWidgets bug...
Did it use to work in previous versions? or is it the first time you install CodeLite?

**Comment by anderflash** [comment]
It's the first time. I installed in my notebook at my work. But I've just formatted my home laptop, and I will try to install codelite to see if it works.

**Comment by eranif** [comment]
Any update?

**Comment by anderflash** [comment]
Same bug when installed it in my home laptop.

**Comment by eranif** [comment]
Which DE are you using? is it possible to try another one (for the sake of the test)

**Comment by anderflash** [comment]
I use KDevelop, QtCreator, CodeBlocks, Sublime, Geany and recently Atom. Every tool has advantages and disadvantages, which makes me switch constantly.

**Comment by eranif** [comment]
From the list above non are DE (Desktop Environment)
I meant: Can you switch from (example) Xfce -> Gnome to see if it makes any difference?
Also which DE are you using ? (KDE, GNOME, Xfce etc)

**Comment by anderflash** [comment]
I use i3wm with some LXDE graphical stuff. I will try another DE/WM, like Gnome and KDE, and say whether it has also problems.

**Comment by anderflash** [comment]
I've tried it in another DE (Gnome and KDE), but the problem remains.

I think it's a GTK issue, because the open dialog of __Evince__ has the same "_key for file selection by initial_" problem.
