### ISSUE TITLE
'expand all' in search tab

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#901]
would be nice to have an 'expand all' button or context-menu action here

thanks

**Comment by grandinj** [comment]
note I'm talking about the search results tab, that lives next to the "Build" tab

**Comment by eranif** [comment]
Click on the "air-plane" button it does exactly this

**Comment by grandinj** [comment]
Thanks

Perhaps it's tooltip should read "Expand/collapse results" ?

I scanned the tooltips briefly, but my mind didn't register the "fold" word very well :-)

**Comment by eranif** [comment]
Note, that you can disable this "fold-all" by default from: `settings->global editor preferences->windows and tabs->find in files->Don't automatically fold search results`
