### ISSUE TITLE
Loading PHP Workspace does not allow C++ 

### ISSUE THREAD

**Issue by mtangoo** [eranif/codelite#902]
1. Open C++ project
2. Using Recent workspaces load PHP
3. Using recent WSs Load C++
4. Reload Workspace

As of (4) I expected it to reload C++ WS but it reloads a PHP one. Trying to Run debug on (3) it brings PHP Dialog.

CodeLite 8.1.0 Ubuntu.
Closing CL and Opening C++ WS works fine

**Comment by eranif** [comment]
The actual bug here is that `Recent Workspace` menu should be disabled when a workspace is loaded. This is fixed now. (it should be disabled due to other internal limitations...)

**Comment by mtangoo** [comment]
Thanks!
