### ISSUE TITLE
#include <example> is not working at all.

### ISSUE THREAD

**Issue by Speedicus** [eranif/codelite#908]
I am attempting to use features such as <ctime>, <iostream>, and other common include libraries but I always get the same message, "No such file or directory found", despite all of them being within the include folder. This is preventing me from actually progressing past basic console applications.

#include <stdio.h>
#include <iostream>
#include <ctime>

int main(int argc, char **argv)
{
	printf("hello world\n");
	return 0;
}

-------------------------------------------------------------------------------------------------------

C:\WINDOWS\system32\cmd.exe /C "C:/TDM-GCC-64/bin/mingw32-make.exe -j4 SHELL=cmd.exe -e -f  Makefile"
"----------Building project:[ Time - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'C:/Users/dylan/Desktop/Time'
mingw32-make.exe[1]: Leaving directory 'C:/Users/dylan/Desktop/Time'
mingw32-make.exe[1]: Entering directory 'C:/Users/dylan/Desktop/Time'
C:/TDM-GCC-64/bin/gcc.exe -c  "C:/Users/dylan/Desktop/Time/main.c" -g -O0 -Wall  -o ./Debug/main.c.o -I. -I.
C:/Users/dylan/Desktop/Time/main.c:2:20: fatal error: iostream: No such file or directory
compilation terminated.
mingw32-make.exe[1]: *** [Debug/main.c.o] Error 1
Time.mk:97: recipe for target 'Debug/main.c.o' failed
mingw32-make.exe[1]: Leaving directory 'C:/Users/dylan/Desktop/Time'
Makefile:4: recipe for target 'All' failed
mingw32-make.exe: *** [All] Error 2
2 errors, 0 warnings

**Comment by eranif** [comment]
Really not a CodeLite bug. Check your code.

**Comment by Speedicus** [comment]
Found a solution via the CodeLite forums, all good.
