### ISSUE TITLE
Feature request: Freeze the output console (under debugger) waiting for keystroke before terminating 

### ISSUE THREAD

**Issue by chaosAD** [eranif/codelite#911]
When running till completion under debugger, it will be useful to freeze the output console allowing user to read the content before terminating the program upon any keystroke.

**Comment by eranif** [comment]
This can't be done by CodeLite
The terminal is not created by CodeLite, but rather using gdb's command:
`set new-console on` which launches the console and terminates it when the debugger exits, CodeLite has no control on when the terminal is "going away"
