### ISSUE TITLE
cmd-C closes dialog

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#913]
this is on OSX 10.10.5 running CodeLite 8.2.2

open the project settings dialog.
open Customize->Custom Build
open the 'Build Target' dialog
select all of the text in the command text pane using cmd-A
do cmd-C
and the dialog will close without the text having been copied

**Comment by eranif** [comment]
I already observed this bug and reported it to the wxWidgets without any progress...
http://trac.wxwidgets.org/ticket/15678

**Comment by grandinj** [comment]
Thanks, I did some research and added a link to a potential solution to that ticket.

**Comment by grandinj** [comment]
hmm, it occurs to me that the "fix" I pointed to in the wxwidgets bug could just be easily be implemented in CodeLite, since it doesn't need to touch any WxWidgets code

**Comment by grandinj** [comment]
Could I convince you to implement the solution in the first answer here:
http://stackoverflow.com/questions/970707/cocoa-keyboard-shortcuts-in-dialog-without-an-edit-menu
?
I can understand that wxwidgets might be reluctant to deploy that solution since it affects all text fileds within an application.

**Comment by eranif** [comment]
I would not know where to start since CodeLite has no "Objective-C" files, this needs to be done somewhere inside wxWidgets
