### ISSUE TITLE
Git settings dialog issue

### ISSUE THREAD

**Issue by MichalBliznak** [eranif/codelite#916]
Settings dialog in git plugin sometimes doesn't show left choice widget correctly as can be seen in attached image. Minimal widget size should be set here, I guess.
![git-settings-issue](https://cloud.githubusercontent.com/assets/6472818/9683031/72cd1bfe-530c-11e5-9758-2cd0d2388bfa.png)

**Comment by eranif** [comment]
Its a wxTreeBookCtrl, there is no minimal widget size to set...
This should be done automatically by wxWidgets

**Comment by eranif** [comment]
This looks like a bug in wxWidgets (I could not reproduce this or make it go away)
