### ISSUE TITLE
Codelite auto-generated files line endings always LF

### ISSUE THREAD

**Issue by blounsbury** [eranif/codelite#918]
I'm on Windows 7 and Codelite 8.2.0 is saving files outside of the editor like Makefile and *.workspace and wxcrafter files with LF line endings. I tried switching Settings->Global Editor Preferences->EOL Mode from default to Windows (CRLF) does not help with these auto-generated/saved files.

Maybe this is the designed behavior but seems strange to not follow platform line endings with these files that Codelite is auto-generating. Causes a headache when using Git, as differences are detected simply because of line endings.

**Comment by anatooly** [comment]
What about last stable 9.0 version or dev build 9.0.7?

**Comment by blounsbury** [comment]
Same behavior on stable 9.0 version.

**Comment by AJenbo** [comment]
Just curious but how do you get issues with diffs in git if the file is always saved with LF?

**Comment by blounsbury** [comment]
For some strange reason it appears the files in git were saved with Windows (CRLF) line endings then Codelite would change them to LF and git would show differences. The simple solution obviously is to change them to LF in git which they likely should be anyway. I suppose I thought the Global Editor Preference might apply to auto-generated files. No problem here if this issue should be closed under the assumption that the setting was not intended to apply to auto-generated files.

**Comment by AJenbo** [comment]
Interesting what other programs where used to generate the files?

**Comment by blounsbury** [comment]
Right? I was trying to think of that as well. If Codelite always saves them as LF how did they become CRLF? It was so long ago, 2015, that I don't remember.

**Comment by AJenbo** [comment]
That's fair. Maybe you edited them manually, I often do that when learning a new tool. I think I will close this as we will just say that the code style for those file types is to use LF :)
Thank you for the quick response.
