### ISSUE TITLE
Annotations in Editor not working

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#919]
Hi Eran,

enabling "Use annotations" in the Build Output Appearance dialog doesn't seem to be working.
The annotations never show up.

I enabled annotations an the clang tab and these do show up in the editor. The problem there is, that
this setting ("Inline errors") is not saved in the preferences, so when restarting CL I have to enable it
again.

Regards,
 René

**Comment by eranif** [comment]
The problems seems to be that the build annotations are in conflict with the CC ones.
i.e. when the build ends, the clang cache is cleared, which also triggers an annotations cleanup (which is called after the build annotations were set)

I am working on a fix for this

**Comment by eranif** [comment]
Fixed
