### ISSUE TITLE
Enable mouse zoom -setting doesn't have an effect in Diff Tool plugin

### ISSUE THREAD

**Issue by Kanimies** [eranif/codelite#922]
When disabling mouse zoom from global settings, it doesn't have an effect in Diff Tool view.
Also when activating a Diff Tool window, the UI theme changes - tab colors etc.

**Comment by eranif** [comment]
Can you provide a screenshot of what described here as: "UI theme changes" 

Thanks

**Comment by Kanimies** [comment]
Color of file tabs when in a Diff window

<img width="269" alt="nayttokuva 2015-09-11 kello 9 27 05" src="https://cloud.githubusercontent.com/assets/7421922/9808393/54c7f394-5867-11e5-9100-8aaef6baa06a.png">

Color of tabs when editing a file
<img width="295" alt="nayttokuva 2015-09-11 kello 9 26 51" src="https://cloud.githubusercontent.com/assets/7421922/9808395/570bb1cc-5867-11e5-9962-04da872ba9bc.png">

Just a visual change, it seems.

**Comment by eranif** [comment]
This is by design. 
The tabs colour is inheriting the active editor theme, the diff view has no editor so it defaults to the basic colour ("panel" colour)
The other issue, is an enhancement that should not be too hard to implement

**Comment by eranif** [comment]
Fixed
