### ISSUE TITLE
Workspace tabs missing from submenu View/Workspace View

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#924]
Workspace tabs missing from submenu View/Workspace View

Amongst the missing are: Outline, Explorer

**Comment by eranif** [comment]
This is because the View->Workspace View menu is loaded form menu.xrc file which has no knowledge on the plugin's tabs (Outline, DbExplorer etc.)
For those plugins, if you wish to hide these tabs, just disable the plugin
