### ISSUE TITLE
GIT Plugin Problem with files in Paths with space

### ISSUE THREAD

**Issue by mtangoo** [eranif/codelite#925]
I've noticed that the plugin does not work with paths that contains space

**Comment by eranif** [comment]
Please elaborate on what is "does not work with paths that contains space"
The folder contains path? the file name? which operation did you try to run?

**Comment by mtangoo** [comment]
I thought it's trivial,  sorry. 
The problem is, when you have path like "/home/Stefano/my computer/whatever_file. php"  it recognize path up to my and discard the rest 

Its acts thd same way as Linux acts with spaced paths until they are escaped

**Comment by mtangoo** [comment]
Latest stable CL via repo with Ubuntu 15.04 64

**Comment by eranif** [comment]
Which command are you trying to use? Can you also provide the git console output?

**Comment by mtangoo** [comment]
Pretty much every command under such kind of directory. I tried reset file and commit. 
I will post the output later when am on the machine but it's a dialog complaining the file is not valid or something like that

**Comment by eranif** [comment]
I still gonna need the git console output (_not_ the dialog output)

**Comment by mtangoo** [comment]
Dialog message
There was a problem while performing a git action.
Last command output:
error: pathspec 'My' did not match any file(s) known to git.
error: pathspec 'App/.codelite/My' did not match any file(s) known to git.
error: pathspec 'App.session' did not match any file(s) known to git.

the Git log
>Git repo path is now set to '/home/stefano/Documents/developer/My/'
Get current branch
/usr/bin/git --no-pager branch --no-color. Repo path: /home/stefano/Documents/developer/My/
Git repo path is now set to '/home/stefano/Documents/developer/My/'
Current branch master
Get current branch
/usr/bin/git --no-pager branch --no-color. Repo path: /home/stefano/Documents/developer/My/
Current branch master
Reset file ""My App/.codelite/My App.session"" 
/usr/bin/git --no-pager checkout ""My App/.codelite/My App.session"" . Repo path: /home/stefano/Documents/developer/My/

**Comment by mtangoo** [comment]
ping

**Comment by eranif** [comment]
Thanks for posting this, I will try a local git repo in path with spaces here and try to reproduce the problem

**Comment by eranif** [comment]
I am unable to reproduce this.
For example:

```
Push local changes (origin master)
"C:\Program Files (x86)\Git\cmd\git.exe" --no-pager push origin master. Repo path: C:\Users\PC\Documents\My Notebook\Notebook
To git@github.com:eranif/Notebook.git
   170fddb..759bcaf  master -> master
```

The difference is that I tested this on Windows (where I would expect developers to use spaces in the paths)

However, due to resource limitation I will not be able to fix this (just switch to no-space path)
