### ISSUE TITLE
Find In File Searching miss one result at v8.2.x

### ISSUE THREAD

**Issue by benqqq** [eranif/codelite#926]
About the new Find In Files feature, the second result will be hided/show after click the first result file link.

**Comment by eranif** [comment]
I don't understand the problem. Can you please elaborate? steps to reproduce?
CodeLite version, OS and pretty much anything you can provide
Thanks

**Comment by benqqq** [comment]
sorry for my unclear.

I take the latest v8.2.4 for example, the step as follows:
1. Select the "string" and press Ctrl + Shift + F to open [Find-In-File] dialog.
    
![fif_1](https://cloud.githubusercontent.com/assets/13009249/9842949/c83862be-5ae7-11e5-83be-0e3118172a8d.png)

2. Press [Find] button then CodeLite pop-up the search pane
    
![fif_2](https://cloud.githubusercontent.com/assets/13009249/9842968/213fcb5e-5ae8-11e5-8b25-ab46e4f10054.png)

3. Click the first file link.

![fif_3](https://cloud.githubusercontent.com/assets/13009249/9843014/b1f3d780-5ae8-11e5-9055-2bce0ff2b62b.png)

4. The items of the first file was folding, but some item of the second file was disappear. 
![fif_4](https://cloud.githubusercontent.com/assets/13009249/9843036/ec0e2b46-5ae8-11e5-824e-86507746ffbb.png)

**Comment by eranif** [comment]
Ok, thanks. The title is misleading...

**Comment by benqqq** [comment]
sorry, It seem the second file result will be hide after click to folding.

**Comment by eranif** [comment]
Fixed
