### ISSUE TITLE
Find in Files in Workspace view - no field for replacement text (Php project)

### ISSUE THREAD

**Issue by Kanimies** [eranif/codelite#927]
When editing a PHP project, the workspace / project view's context menu has a Find in Files -feature

<img width="184" alt="find in files context menu" src="https://cloud.githubusercontent.com/assets/7421922/9844126/6a56f5fc-5ac9-11e5-8cce-959243513840.png">

The dialog box for the feature has a Replace button, but there is no field to enter the replacement text so effectively the Replace just runs Find.

![find in files dialogue](https://cloud.githubusercontent.com/assets/7421922/9844137/84da35e2-5ac9-11e5-88eb-11a3948e0ac4.png)

Is this a missing feature or a bug perhaps?

**Comment by eranif** [comment]
Not a bug, an intended behavior.
The Find and Replace (across multiple files) works in 2 steps:
- Click on "Replace" button (it will only perform search, the replace is done in the second phase)
- The Search results will be placed in the "Replace" output view where you can decide which results to replace, replace with what etc

Just try it

**Comment by Kanimies** [comment]
Oh, it just wasn't obvious. Thanks!

**Comment by eranif** [comment]
> Oh, it just wasn't obvious. Thanks!

Any ideas on how to make it more obvious?

**Comment by Kanimies** [comment]
Well, I would've suggested a tooltip on the Replace -button, but as it is there already and my first action wasn't to look for it (it might've explained it and allowed me to actually click on the button, not being afraid that my search text would be replaced with, say, nothing and erasing it), could renaming the action button be a solution? 

As now I'm not really clicking it to Replace something, but something like "Find to replace" or "Find for replace" - that would suggest that by clicking on the button the items would only be searched for being replaced at the next action.

Food for thought!

**Comment by Kanimies** [comment]
Another solution would be to perhaps have a question mark icon or whatnot next to the replace -button with the tooltip text as an obvious place to look for the information of how this is going to work :).

**Comment by eranif** [comment]
Thanks, will see what I can do to make it more clear

**Comment by eranif** [comment]
The solution:
I added a "Replace With" field where the user can type the replacement string, when clicking on the "Replace" the flow is as before, with one minor change: the "Replace With" field content is passed to the "Replace With" field in the "Replace Tab"

![fif](https://cloud.githubusercontent.com/assets/3677711/9856256/3e9a8200-5b1c-11e5-8b61-2c71ef3393bb.png)
