### ISSUE TITLE
Sidebar tabs placements

### ISSUE THREAD

**Issue by chamfay** [eranif/codelite#929]
Hi,

Can you please add an option to switch sidebar tabs placements.
ex: able to move them to Left (for my opinion is more elegant!)
http://www.mrkzgulf.com/do.php?img=46029

especially when there are more of them.

hope youn understand me.

Thanks.

**Comment by eranif** [comment]
Implemented (it required a big effort for extending the tab control to support LEFT and RIGHT orientation...)

**Comment by eranif** [comment]
You can see how it looks here:
![v-tabs](https://cloud.githubusercontent.com/assets/3677711/10121624/4a9766ea-64fe-11e5-9570-397fd3d42401.png)

**Comment by chamfay** [comment]
It looks very nice,
Thank you for the greate work :)
