### ISSUE TITLE
Single instance lock files should go into /tmp

### ISSUE THREAD

**Issue by uffejakobsen** [eranif/codelite#930]
I'm running codelite with "single instance per user" option turned on
The single instance lock file (containing pid) is saved in the user home dir  (name: Codelite-username).

I have 1000's of these files in my hourly incremental backups of my home dir :-)

It would be nice if this file was saved under /tmp (eg /tmp/Codelite-username) - just like the indexer socket file

**Comment by eranif** [comment]
How can you have 1000 of the same file with the exact same name? OO

**Comment by eranif** [comment]
Fixed
