### ISSUE TITLE
SVN Diff nt working

### ISSUE THREAD

**Issue by Kanimies** [eranif/codelite#931]
The right click context selection in Workspace view for SVN -> Create Diff does not create Diffs but opens empty documents in editor instead.

**Comment by eranif** [comment]
OS? CodeLite version? It seems to work fine here (tested on multiple OSs + different projects)
Can you please provide a minimal reproduction?

**Comment by Kanimies** [comment]
OS X, 8.2.4. 

It seems that for some files the diff is generated, but differently from the one created via SVN Output pane -> Modified files -> double click; 
the latter creates a diff in two windows whereas the context menu (as well as "Create diff" -option in the output pane) creates a single window - is this intended behavior?

The empty document might actually be caused by the file in question having no differences, I was just confused because of the two different Diff views.

**Comment by eranif** [comment]
> It seems that for some files the diff is generated, but differently from the one created via SVN Output 
> pane -> Modified files -> double click; 
> the latter creates a diff in two windows whereas the context menu (as well as "Create diff" -option in 
> the output pane) creates a single window - is this intended behavior?

Yes. The "Create diff" is a way of creating an actual diff that can be used with the `patch` utility.

While the "2 Windows" diff is a more visual way to view the differences by the user

**Comment by Kanimies** [comment]
Can we have the option to have the visual diff as well via Workspace, then? I believe that would be more useful most of the time.

**Comment by eranif** [comment]
Sure, I will add this option
