### ISSUE TITLE
some autocompletion function in gtk/c project not working

### ISSUE THREAD

**Issue by chamfay** [eranif/codelite#932]
Hi,
i'm using codelite for creating gtk/c project, but when i use ctrl+space for some function, no menu for autocompletion.
for example gtk_file_chooser_dialog_new function.

i used codlite in both windows and linux (ubuntu) and the same problem happen to me.

screenshot:
http://up.harajgulf.com/do.php?img=217201

hope my question is clear and this the right place.

**Comment by eranif** [comment]
ctags code completion is working up to a certain degree.
To get better code completion results, please enable clang code completion:
http://codelite.org/LiteEditor/ClangIntegration41

If you have questions, please report them on the forum: http://forums.codelite.org
