### ISSUE TITLE
Feature Request: Allow Workspace Macros to work under Ctags

### ISSUE THREAD

**Issue by hipnition** [eranif/codelite#934]
Workspace Macros are great. Developers frequently have shared projects which may have build flags. Depending on the product (or workspace), the build flags may be different. Workspace level macros work great for this. Unfortunately, it is only available for clang users. When developing embedded (non-Windows) code, clang doesn't seem to work correctly. Ctags is fine. 

The request would be to pass the workspace macros to ctag.

I have local changes to make this feature work.

**Comment by hipnition** [comment]
Still trying to make a pull request for review but Git is giving me trouble. It always says I have files to sync which I didnt touch.

**Comment by eranif** [comment]
Maybe you need to revise because I modified the file?

**Comment by hipnition** [comment]
I think I messed it up by cloning first. I start everything again and think you should see a pull request. PC code isn't my forte so please review. I have a small test code base if needed and have been trying it on our larger code base. I do see one issue with Workspace Sync...You have to open/close it an extra time to sync, but I think that issue may have always been there. Thanks.
