### ISSUE TITLE
Comments controls don't work in PHP projects

### ISSUE THREAD

**Issue by jclaveau** [eranif/codelite#940]
Only in PHP project, if you do Edit->Comment->Comment selecton|line, it will work the first time (to add comments) but has unpredictable behavior the second time (when you want to remove them).

Sometimes it will simply do nothing, sometimes a second column of "//" will be added sometimes multiline comments will be added.

It's for me the most bothering bug while coding in PHP and I fond no workaround.

**Comment by eranif** [comment]
Please explain "but has unpredictable behavior the second time" it seems to work as expected.
If you want to remove a comment block (that starts with `/*` and ends with `*/`) you should that block. i.e. the selection must include all comment block

**Comment by jclaveau** [comment]
Okay, I dug a bit and found something reproducible AND understandable! \o/

The main parameter seems to be the position of the carret on the line to comment.
Considering this useless piece of PHP.
```php
<?php
'lala';
```
+ Let's go to line 2 at the full left and do Comment Line two times. It will add "//" at the beginning then remove it as much time as you press the bound up controls (Ctrl+E on my config) which is the expected behaviour.
+ Now go to the end of the line 2, just after the ";" and do "Comment Line" many times. You'll get something like that :
```php
<?php
////////////////'lala';
```
+ Now go back to the first column and do "Comment Line" again but without removing all the "/////" and you'll get something new again : 
```php
<?php
*/*/*/*/*/*/
////////////'lala';
/*/*/*/*/*/*
```

I also have some weird results with "Comment Selection" but one thing at a time :) .

Please, tell me if I can provide something else which could help you.

**Comment by eranif** [comment]
The logic that CodeLite uses is:
* Check the style at the current position
* If the style is Comment, Un-Comment line
* Anything else, comment the entire line

IIRC, when the caret is at the end of line (of a comment line) the "\n" is not included in the comment style, so CodeLite thinks that it needs to add another `//` hence what you see
 
I can see both use cases, I will see what can be done to fix them

**Comment by eranif** [comment]
Fixed
