### ISSUE TITLE
Choose indent type by project or workspace

### ISSUE THREAD

**Issue by jclaveau** [eranif/codelite#941]
I often switch from a c++ project which is space indented to a PHP one which tab indented to other PHP projects (libs) that are space indented too and each time I have to change the setting to fit the code guidelines.

It would be really nice if this option was defined by project.

Thanks for your work!

**Comment by eranif** [comment]
As a workaround, you can do this:
* Set the global spacing to TABS
* In your **C++** workspace, right click on it and select "Workspace Editor Preferences" and set there to use SPACES for this workspace

**Comment by jclaveau** [comment]
I'll try that tomorrow, thanks a lot for the explanation.
