### ISSUE TITLE
Keyboard input ignored / focus lost in some dialog windows [Linux]

### ISSUE THREAD

**Issue by tp0** [eranif/codelite#942]
Keyboard keys are ignored until the some functional part of the dialog is clicked with mouse, altough the window itself already has focus or is the active one. For example:

* Settings > Colours and Fonts
* Settings > Code Completion

Couldn't quite figure out why in some dialogs they sometime work and sometimes not, but above ones seemed to be consistent.

The usecase I'm after: pressing Escape to close / cancel the dialog window.

codelite 8.1.0 (also tested weekly build .deb 8.2.6, no difference)
wxcrafter 2.3-1
Linux Mint 17.2 (Cinnamon, MATE)

Could not repro on 8.2.0 on Windows 7, so I think this is just a Linux thing.

**Comment by eranif** [comment]
Sorry, due to resource limitation this I will not be able to fix this (low importance)
A pull request with the suggested fixed will be highly appreciated
