### ISSUE TITLE
C++ Declaring and initializing multiple variables

### ISSUE THREAD

**Issue by ahmedalshamary** [eranif/codelite#943]
When you try to Declare and initialize multiple variables on one line not all the variables are seen as variables by codelite. It only counts every other one as a variable. I attached an image below showing the problem. Not sure if it is a bug or a mistake on my end. 

Thanks!
![problempic](https://cloud.githubusercontent.com/assets/14957006/10294835/ace9b4e6-6b8a-11e5-9378-508ce19de533.PNG)

**Comment by eranif** [comment]
This is a known issue which resolving it requires some big changes to the lexer code (yacc)
Don't expect it to be resolved anytime soon
