### ISSUE TITLE
Error with #include "name-completion"

### ISSUE THREAD

**Issue by je-so** [eranif/codelite#945]
Problem Description:

Create a new workspace and a new project "simple executable" with gcc.

Create virtual folder "inc" in new project.

Create manually directory "a-b" in project directory and create empty header file "a-b/test.h"

Now write  
  #include "a-
and press ctrl-space for completion of include file-name and select "a-b/test.h"

The completion mechanism now writes  
  #include "a-a-b/test.h

Writing 
#include "a
works well but adding a '-' after the a and then trying to use the completion mechanism
repeats the "a-" at the beginning of the name.

I think the problem is the handling of special characters (-, $, ...).
Choosing a$b as directory name and writing  #include "a$ generates  #include "a$a$b/test.h
instead.

**Comment by eranif** [comment]
Fixed
