### ISSUE TITLE
[RPMLint] Program returns random data in a function

### ISSUE THREAD

**Issue by susnux** [eranif/codelite#946]
I am trying to build CodeLite 8.1 for openSUSE, but build failed with RPMLint report:

    I: Program returns random data in a function
    E: codelite no-return-in-nonvoid-function codelite-8.1-new/CodeFormatter/formatoptions.h:185
    E: codelite no-return-in-nonvoid-function codelite-8.1-new/CodeFormatter/codeformatter.cpp:807

Because the functions:
bool SetPHPFormatterOptions(size_t options)
and
bool CodeFormatter::BatchFormat(const std::vector<wxFileName>& files)
do not have a default return.

For the first one I think it should be simply a void function.
I use a simple patch, if you want to, you can use it.
Direct link to patch: https://build.opensuse.org/source/home:susnux:branches:devel:tools/codelite/fix-no-return-in-nonvoid-function.patch?rev=1a3b55816a0a05f90f822a06fd6e5b58

**Comment by eranif** [comment]
thanks, but this was already fixed in git master.

**Comment by susnux** [comment]
@eranif yes but only formatoptions.h got fixed, not codeformatter.cpp:

    bool CodeFormatter::BatchFormat(const std::vector<wxFileName>& files)
    {
        FormatOptions options;
        m_mgr->GetConfigTool()->ReadObject(wxT("FormatterOptions"), &options);
    
        if(options.GetEngine() == kFormatEngineAStyle) {
            return AStyleBatchFOrmat(files, options);
    
        } else if(options.GetEngine() == kFormatEngineClangFormat) {
            return ClangBatchFormat(files, options);
        }
    }

This function still does not have a default return, if first if and else if does not match it will return random data.
If there are only two possibilities (kFormatEngineAStyle and kFormatEngineClangFormat), then you should probaly remove the seconde if and only use a if ... else...
Or add a default return (e.g. return false).

**Comment by susnux** [comment]
I think in this case simply remove else if with else, because there is no other possible value.

**Comment by eranif** [comment]
Indeed, I missed that one

**Comment by eranif** [comment]
I fixed it now, although the RPMLint was wrong: `options.GetEngine()` can have only 2 values and these 2 values were being handled

**Comment by susnux** [comment]
Yes, but an enum is internally an int which can be casted.
See also the discussion at sfml (same sort of error):

https://github.com/SFML/SFML/issues/935

But thanks for fixing :)
