### ISSUE TITLE
Code completion for boost::shared_ptr not working

### ISSUE THREAD

**Issue by upCASE** [eranif/codelite#947]
Hi Eran,

for some reason the code completion fails for types like boost:shared_ptr.
I do have some typedefed types like
```typedef std::tr1::shared_ptr<MyClass> MyType;```
where std::tr1::shared_ptr really is a boost:shared_ptr. Doing somehting like
```MyType type;
type->get```
gives me no code completion. 
I checked the debug output and apparently "something" correctly happens
```
[ 10:28:14:258 DBG ] Checking ExcuteUserTypes...
[ 10:28:14:258 DBG ] Checking ExcuteUserTypes... done
[ 10:28:14:258 DBG ] Checking DoIsTypeAndScopeExist...
[ 10:28:14:258 DBG ] Checking DoIsTypeAndScopeExist... done
[ 10:28:14:258 DBG ] Checking DoExtractTemplateInitListFromInheritance...
[ 10:28:14:258 DVL ] [CACHED ITEMS] select * from tags where path ='std::tr1' LIMIT 1
[ 10:28:14:258 DBG ] Checking DoExtractTemplateInitListFromInheritance... done
[ 10:28:14:258 DBG ] Checking CheckForTemplateAndTypedef...
[ 10:28:14:258 DVL ] [CACHED ITEMS] select * from tags where path ='std::tr1' LIMIT 1
[ 10:28:14:259 DBG ] Checking CheckForTemplateAndTypedef... done
[ 10:28:14:259 DBG ] PrcocessToken... done
[ 10:28:14:259 DBG ] PrcocessToken...
[ 10:28:14:259 DVL ] [CACHED ITEMS] select * from tags where path='std::tr1' LIMIT 1000
[ 10:28:14:259 DVL ] [CACHED ITEMS] select * from tags where path IN('std::tr1::shared_ptr')
[ 10:28:14:259 DBG ] step 1 completed
[ 10:28:14:259 DBG ] Checking ExcuteUserTypes...
[ 10:28:14:259 DBG ] Checking ExcuteUserTypes... done
[ 10:28:14:259 DBG ] Checking DoIsTypeAndScopeExist...
[ 10:28:14:259 DBG ] Checking DoIsTypeAndScopeExist... done
[ 10:28:14:259 DBG ] Checking DoExtractTemplateInitListFromInheritance...
[ 10:28:14:259 DVL ] [CACHED ITEMS] select * from tags where path ='boost::shared_ptr' LIMIT 1
[ 10:28:14:259 DBG ] Checking DoExtractTemplateInitListFromInheritance... done
[ 10:28:14:259 DVL ] [CACHED ITEMS] select * from tags where path ='boost::shared_ptr' LIMIT 1
[ 10:28:14:260 DBG ] Checking CheckForTemplateAndTypedef...
[ 10:28:14:260 DVL ] [CACHED ITEMS] select * from tags where path ='boost::shared_ptr' LIMIT 1
[ 10:28:14:260 DBG ] Checking CheckForTemplateAndTypedef... done
[ 10:28:14:260 DVL ] [CACHED ITEMS] select * from tags where path='boost::shared_ptr' LIMIT 1000
[ 10:28:14:260 DVL ] [CACHED ITEMS] select * from tags where scope ='boost::shared_ptr' and name like 'operator%->%' LIMIT 1
[ 10:28:14:261 DBG ] Checking CheckForTemplateAndTypedef...
[ 10:28:14:261 DVL ] [CACHED ITEMS] select * from tags where path ='boost::shared_ptr::type' LIMIT 1
[ 10:28:14:262 DBG ] Checking CheckForTemplateAndTypedef... done
[ 10:28:14:262 DVL ] [CACHED ITEMS] select * from tags where path='boost::shared_ptr::type' LIMIT 1000
[ 10:28:14:262 DVL ] [CACHED ITEMS] select * from tags where scope ='boost::shared_ptr::type' and name like 'operator%->%' LIMIT 1
[ 10:28:14:262 DBG ] PrcocessToken... done
[ 10:28:14:262 DBG ]  <<< Language::ProcessExpression started ... done
[ 10:28:14:262 DVL ] [CACHED ITEMS] select * from tags where path='boost::shared_ptr::type' LIMIT 1000
[ 10:28:14:262 DVL ] [CACHED ITEMS] select * from tags where scope in('boost::shared_ptr::type')  AND  name LIKE 'get%%' ESCAPE '^'  LIMIT 1000
```
Seems to me like std::tr1::shared_ptr is actually correctly identified as boost::shared_ptr and in turn boost::shared_ptr is tried for getting the correct completion.
boost::shared_ptr::type seems to be the culprit. I tried adding some user defined types like
std::tr1::shared_ptr=_Tp or boost::shared_ptr=_Tp and boost::shared_ptr::type=_tp, but nothing seems to work. The funny thing is that I tried the same with a std::set::const_iterator and that one works just fine.

Do you have any idea what might be wrong? I'm pretty sure this used to work. Am I doing this user defined type thing wrong?

Regards,
 René

**Comment by eranif** [comment]
As a side note: Why don't use `clang` CC?

Can you provide a short example script that I can test and see where it fails?

Thanks

**Comment by upCASE** [comment]
I would love to use clang CC in such cases, but it always gives me:
clang: "You must build your code with position independent code if Qt was built with -reduce-relocations. "         "Compile your code with -fPIC (-fPIE is not enough)."
And I can't figure out what I could do to stop it from thinking that I don't have -fPIC set...
I'll have a look at this again.

Simple test:
```
struct Test{
  unsigned memberVar;
};

typedef std::tr1::shared_ptr<Test> TestType;
//....
TestType t;
t->     //never gives me "memberVar"
```

The log for this:
```
[ 11:02:24:154 DBG ] step 1 completed
[ 11:02:24:154 DBG ] Checking ExcuteUserTypes...
[ 11:02:24:154 DBG ] Checking ExcuteUserTypes... done
[ 11:02:24:154 DBG ] Checking DoIsTypeAndScopeExist...
[ 11:02:24:154 DBG ] Checking DoIsTypeAndScopeExist... done
[ 11:02:24:154 DBG ] Checking DoExtractTemplateInitListFromInheritance...
[ 11:02:24:154 DVL ] [CACHED ITEMS] select * from tags where path ='std' LIMIT 1
[ 11:02:24:154 DBG ] Checking DoExtractTemplateInitListFromInheritance... done
[ 11:02:24:154 DBG ] Checking CheckForTemplateAndTypedef...
[ 11:02:24:154 DVL ] [CACHED ITEMS] select * from tags where path ='std' LIMIT 1
[ 11:02:24:154 DBG ] Checking CheckForTemplateAndTypedef... done
[ 11:02:24:154 DBG ] PrcocessToken... done
[ 11:02:24:154 DBG ] PrcocessToken...
[ 11:02:24:155 DVL ] [CACHED ITEMS] select * from tags where path='std' LIMIT 1000
[ 11:02:24:155 DVL ] [CACHED ITEMS] select * from tags where path IN('std::tr1')
[ 11:02:24:155 DVL ] [CACHED ITEMS] select * from tags where name='tr1' LIMIT 1000
[ 11:02:24:155 DBG ] step 1 completed
[ 11:02:24:155 DBG ] Checking ExcuteUserTypes...
[ 11:02:24:155 DBG ] Checking ExcuteUserTypes... done
[ 11:02:24:155 DBG ] Checking DoIsTypeAndScopeExist...
[ 11:02:24:155 DBG ] Checking DoIsTypeAndScopeExist... done
[ 11:02:24:155 DBG ] Checking DoExtractTemplateInitListFromInheritance...
[ 11:02:24:155 DVL ] [CACHED ITEMS] select * from tags where path ='std::tr1' LIMIT 1
[ 11:02:24:155 DBG ] Checking DoExtractTemplateInitListFromInheritance... done
[ 11:02:24:155 DBG ] Checking CheckForTemplateAndTypedef...
[ 11:02:24:155 DVL ] [CACHED ITEMS] select * from tags where path ='std::tr1' LIMIT 1
[ 11:02:24:155 DBG ] Checking CheckForTemplateAndTypedef... done
[ 11:02:24:155 DBG ] PrcocessToken... done
[ 11:02:24:155 DBG ] PrcocessToken...
[ 11:02:24:156 DVL ] [CACHED ITEMS] select * from tags where path='std::tr1' LIMIT 1000
[ 11:02:24:156 DVL ] [CACHED ITEMS] select * from tags where path IN('std::tr1::shared_ptr')
[ 11:02:24:156 DBG ] step 1 completed
[ 11:02:24:156 DBG ] Checking ExcuteUserTypes...
[ 11:02:24:156 DBG ] Checking ExcuteUserTypes... done
[ 11:02:24:156 DBG ] Checking DoIsTypeAndScopeExist...
[ 11:02:24:156 DBG ] Checking DoIsTypeAndScopeExist... done
[ 11:02:24:156 DBG ] Checking DoExtractTemplateInitListFromInheritance...
[ 11:02:24:156 DVL ] [CACHED ITEMS] select * from tags where path ='boost::shared_ptr' LIMIT 1
[ 11:02:24:156 DBG ] Checking DoExtractTemplateInitListFromInheritance... done
[ 11:02:24:156 DVL ] [CACHED ITEMS] select * from tags where path ='boost::shared_ptr' LIMIT 1
[ 11:02:24:156 DBG ] Checking CheckForTemplateAndTypedef...
[ 11:02:24:156 DVL ] [CACHED ITEMS] select * from tags where path ='boost::shared_ptr' LIMIT 1
[ 11:02:24:156 DBG ] Checking CheckForTemplateAndTypedef... done
[ 11:02:24:156 DVL ] [CACHED ITEMS] select * from tags where path='boost::shared_ptr' LIMIT 1000
[ 11:02:24:156 DVL ] [CACHED ITEMS] select * from tags where scope ='boost::shared_ptr' and name like 'operator%->%' LIMIT 1
[ 11:02:24:157 DBG ] Checking CheckForTemplateAndTypedef...
[ 11:02:24:157 DVL ] [CACHED ITEMS] select * from tags where path ='boost::shared_ptr::type' LIMIT 1
[ 11:02:24:158 DBG ] Checking CheckForTemplateAndTypedef... done
[ 11:02:24:158 DVL ] [CACHED ITEMS] select * from tags where path='boost::shared_ptr::type' LIMIT 1000
[ 11:02:24:158 DVL ] [CACHED ITEMS] select * from tags where scope ='boost::shared_ptr::type' and name like 'operator%->%' LIMIT 1
[ 11:02:24:158 DBG ] PrcocessToken... done
[ 11:02:24:158 DBG ]  <<< Language::ProcessExpression started ... done
[ 11:02:24:158 DVL ] [CACHED ITEMS] select * from tags where path='boost::shared_ptr::type' LIMIT 1000
[ 11:02:24:158 DVL ] [CACHED ITEMS] select * from tags where scope in ('boost::shared_ptr::type') ORDER BY NAME  LIMIT 1000
```

**Comment by upCASE** [comment]
Ok, I got clang CC working by adding __PIC__ as a macro to the workspace code completion settings.
Why I got that error in the first place still remains a mystery. clang CC however tends to be accurate, yet sloooow on larger sources....
I still don't get what substituting the type with _Tp doesn't work when using ctags.

**Comment by eranif** [comment]
Fixed
