### ISSUE TITLE
[UI] Empty plugins description

### ISSUE THREAD

**Issue by anatooly** [eranif/codelite#949]
CodeLite 8.2.6
Plugins - Manage plugins...
When I select someone plugins, field "Description:" always empty. 
http://screencloud.net/v/kyQP

**Comment by eranif** [comment]
It looks like a bug in wxWidgets... 
If you resize the window (just once) you will get the description properly

**Comment by anatooly** [comment]
@eranif You are right, after resize I see description http://screencloud.net/v/uFT8
Now this not reproduce after close & open application.
