### ISSUE TITLE
[UI] Check for updates...

### ISSUE THREAD

**Issue by anatooly** [eranif/codelite#950]
CodeLite 8.2.6
When click menu: Help - Check for updates...
Result: nothing happens any dialog box or some text field on UI, have new updates or not or some problem network connection/application.

**Comment by eranif** [comment]
Thats because there are not updates..
I agree though, there should be a message that says something like "You are using the latest version"
FYI: CodeLite checks for new version on startup automatically

**Comment by anatooly** [comment]
@eranif Example dialog box like PhpStorm http://screencloud.net/v/2Awp
