### ISSUE TITLE
[UI] Workspace Pane white icons

### ISSUE THREAD

**Issue by anatooly** [eranif/codelite#951]
CodeLite 8.2.6
I think we need black color icon - http://screencloud.net/v/wHdy
May be if I select "Settings - Preferences - Misc - Icon Set: Classic Dark" icons on workspace pane change color white to black.

**Comment by eranif** [comment]
This is a minor issue which I don't have the time to fix.
Pull request with a fix is most welcomed

**Comment by anatooly** [comment]
Thanks for black icons on Workspace pane on CodeLite 9.
