### ISSUE TITLE
[PHP] Create new folder on workspace & delete context menu not work

### ISSUE THREAD

**Issue by anatooly** [eranif/codelite#952]
CodeLite 8.2.6, Ubuntu 14.04, 64-bit.
Linux pcName 3.16.0-50-generic #67~14.04.1-Ubuntu SMP Fri Oct 2 22:07:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Workspace: create new file and new class work correct.
"Create new folder..." not add new folder.

**Comment by eranif** [comment]
CodeLite supports 3 types of workspaces (C++, NodeJS and PHP) can you please provide some more details on the issue? (I tried PHP and C++ and they both are working fine)

**Comment by anatooly** [comment]
Steps for me.
File - New - New Workspace - PHP - checkbox "Create fle in separate directory" only
One checkbox http://screencloud.net/v/uf1i - folder not have name http://screencloud.net/v/iCXR

Plus other bug, not delete folder on all workspaces that I created. Delete folder not work& files too when use context menu.

**Comment by eranif** [comment]
Does `/home/Documents` folder exist?

**Comment by anatooly** [comment]
@eranif Yes. Really path is does /home/{USERNAME}/Documents, I manual delete it for screenshot.

**Comment by eranif** [comment]
Ah, OK... its seems strange to me that you have a folder named `/home/Documents` ;)

**Comment by eranif** [comment]
Can't reproduce this on Windows, will try Debian 8 see if works there

**Comment by eranif** [comment]
Works on Linux / Debian 8 with OpenBox
Do you have another machine to try and see if the problem persist on your side?

**Comment by eranif** [comment]
Also, "New Folder" / "Delete Folder" both working fine ...
