### ISSUE TITLE
[UI][PHP] Default extension on new file

### ISSUE THREAD

**Issue by anatooly** [eranif/codelite#953]
CodeLite 8.2.6
Screenshot: https://screencloud.net/v/w8aH

When I select "New file..." - Set the file name: field have "Untitled.php".
I think field need name without extension by default: "Untitled", but create file + ".php" if value filename without extension.

Example: new file...
Untitled -> create file Untitled.php
Untitled.php -> create file Untitled.php
Untitled.js -> create file Untitled.js
Untitled.php.js -> create file Untitled.php.js
Untitled.css -> create file Untitled.css
Untitled_php -> create file Untitled_php.php

**Comment by eranif** [comment]
what happens when user wants to create a file without an extension?
e.g. `AUTHORS`, `LICENSE`, `COPYRIGHTS` etcetera ?

**Comment by anatooly** [comment]
@eranif Right you are. Possible select all text on field like this http://screencloud.net/v/4eR3
If I always create JavaScript/CSS/HTML files?

When I action rename file it name not selected, like this http://screencloud.net/v/u4YE
