### ISSUE TITLE
"find in files" dialog keeps getting bigger

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#954]
seems to apply to other dialogs as well, but this is the one I notice.

It seems like the height keeps increasing every time I open it, until it extends below the bottom of the screen.

This is running master (from a couple of days ago) on Ubuntu 15.04

**Comment by eranif** [comment]
This is a wxWidgets bug.
It only happens on some desktop manager.
Are you using GTK3 ?

**Comment by grandinj** [comment]
Yup, with Ubuntu's default desktop manager

**Comment by eranif** [comment]
It does not happen with xfce, lxde etc
Only with gnome default DE, I will open a bug to wxWidgets
