### ISSUE TITLE
"Exclude from build" grey filename color not remembered across restarts 

### ISSUE THREAD

**Issue by tp0** [eranif/codelite#958]
`1.c` marked as excluded, shown correctly in grey color:

![1](https://cloud.githubusercontent.com/assets/5863551/10446764/e62e845a-7186-11e5-95cb-32f8e829cc73.png)

Codelite relaunched:

![2](https://cloud.githubusercontent.com/assets/5863551/10446769/eaa3b622-7186-11e5-9c90-f8d6c65eb5bb.png)

![3](https://cloud.githubusercontent.com/assets/5863551/10446771/efdf3954-7186-11e5-9f7d-d329d6a964c8.png)

Codelite 9.0.0
Ubuntu Linux

**Comment by harry-g** [comment]
Just found the same in 9.1.0, so it's still there...

**Comment by michelesalvador** [comment]
Windows Codelite 10.0.0 has still the same problem.
Please fix it!

**Comment by eranif** [comment]
This is now fixed in git master
