### ISSUE TITLE
[UI][Menu] Initialize menu Show Status Bar & Show Toolbar

### ISSUE THREAD

**Issue by anatooly** [eranif/codelite#959]
1) Open application when statusbar is enable for showing;
2) Menu: View - Show Status Bar, not checked but statusbar on bottom is show;
3) Click:  View - Show Status Bar - nothing happens but checked Show Status Bar field on menu;
4) Click:  View - Show Status Bar - hide statusbar and unchecked Show Status Bar field on menu;
5) ... next all work correct.

If statusbar enable when application initialize need checked menu field View - Show Status Bar.

P.S.: View - Show Toolbar too.

---

CodeLite 9.0.0
Linux anatooly 3.16.0-50-generic #67~14.04.1-Ubuntu SMP Fri Oct 2 22:07:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by eranif** [comment]
I am unable to reproduce this one :/
