### ISSUE TITLE
[UI][Workspace Pane] More padding for icons on right Workspace View

### ISSUE THREAD

**Issue by anatooly** [eranif/codelite#960]
Example: http://screencloud.net/v/hYxh
When we have long git branch name we see that right icons padding only for 2 icons, not three. Icons top of text. Need crop text before icons.

---

CodeLite 9.0.0
Linux anatooly 3.16.0-50-generic #67~14.04.1-Ubuntu SMP Fri Oct 2 22:07:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by eranif** [comment]
Due to resource limit, I am not going to fix this.
pull requests are most welcomed
