### ISSUE TITLE
PHP Code completion

### ISSUE THREAD

**Issue by RhynoMeyer** [eranif/codelite#962]
Hi,

On CodeLite 9.0.0

Code completion options don't appear when you have a Class member variable set to a other object that contains its own member variables. ex.

class TestObject {
  public testVar = 'Test';
  ...
}

// In Other Class
$this->testObj = new TestObject();
$this->testObj->(Nothing appears no choices are given)

![screenshot](https://cloud.githubusercontent.com/assets/1029306/10451070/4af1383a-719e-11e5-8431-87a4868e3e08.jpg)

**Comment by eranif** [comment]
OK, this seems like a miss-handled case (with variable which is not a class member this seems to work)
as a workaround, you could "tell" CodeLite that $this->_autoLoader is of type `SplAutoLoader` like this:

```PHP

...
/** @var SplAutoLoader */
protected $_autoLoader;

...
```

**Comment by RhynoMeyer** [comment]
Yes, thanks this works I usually put @var in my comments, except this time lol.

**Comment by MJavad** [comment]
I have the same problem:
```
private $s = new mysqli();
public function __construct()
{
	$this->s->		//code completion doesn't open
	...
}
```
I think this is a common case which and you need to add it :)
