### ISSUE TITLE
"New Workspace" Path @Windows

### ISSUE THREAD

**Issue by flederwiesel** [eranif/codelite#963]

**Comment by flederwiesel** [comment]
Whenever creating a new C++ workspace, "C:\Program Files\CodeLite" is the default workspace path, which normally is not accessible - and a bad choice anyway....

- CL should remember the recently selected workspace path(s)
- CL should initially suggest something like %USERPROFILE%\Codelite

**Comment by eranif** [comment]
which version of codelite?
this was changed in codelite 9

**Comment by flederwiesel** [comment]
Sorry, OS and version info went missing. Was releated to v8.2.3. I did not notice there was a new release :(

Though the second point is fixed, would still be nice if CL could remember the recently selected workspace path(s).

**Comment by eranif** [comment]
Sure. BTW, the new default path is set to `C:\Users\YOU\Documents` (depends on your OS etc)
