### ISSUE TITLE
Bookmarks management

### ISSUE THREAD

**Issue by pedefe** [eranif/codelite#964]
Hello,

On CodeLite 8.x, small problem with bookmark. When adding bookmark (Ctrl + B), new bookmark is correctly recorded.
When I wish to remove it, I have to try at several place (begin of line, end of line, begin of indentation) to find the good place, like bookmark is recorded with the column of caret.
I suggest that bookmark is indexed for the full line only...

Best regards.

**Comment by anatooly** [comment]
@pedefe What about last CL 9 release version? As for me any caret possition on line correct toogle bookmark.

**Comment by pedefe** [comment]
Yes, with release version 9.0.0 installed yesterday, the problem still exist.
Sometimes it works, sometimes it never can me removed, except with popup menu "Remove all bookmarks".
Best regards.

**Comment by eranif** [comment]
I can confirm that this is reproducible

**Comment by eranif** [comment]
This does not seem to be related to column, but to bookmark type.
CodeLite allows to add up to 4 types of bookmarks (not including the compiler error/warnings markers and breakpoints), I suspect that there is something goes out-of-sync with the bookmark type on that line. The `Remove bookmark` menu entry will now remove all 4 of them
