### ISSUE TITLE
Code generation for UI strings (wxCrafter)

### ISSUE THREAD

**Issue by MichalBliznak** [eranif/codelite#966]
wxCrafter should be able to specify which macros will be used for encapsulation of user-defined UI strings during the code generatiom process. At the moment, only _() macro is used which is fine for internationalized applications, but it doesn't allow users to directly enter native text string encapsulated by wxT() macro.

**Comment by eranif** [comment]
Fixed. This is now configurable from the top level tree view item (the project level)
You can now set if wxCrafter generates translatable strings or not
