### ISSUE TITLE
Issue with tabs

### ISSUE THREAD

**Issue by XenoSnowFox** [eranif/codelite#967]
![codelite - display bug](https://cloud.githubusercontent.com/assets/2343992/10500407/b0b09374-7323-11e5-866c-fea029850776.PNG)

My right-most tab seems to be cut off. I'm unable to click the close button on the tab for it.
I'm also unable to scroll through the tabs.

I'm running CodeLite 9.0.0 on a 32bit windows 10 pc.

**Comment by eranif** [comment]
You have 4 other options to close this tab:
* Ctrl-W
* Menu: File->Close
* Click mouse scroll button on the tab
* Right click on the tab -> Close
