### ISSUE TITLE
[Mac] Cause Finder Crash in Multi-language Interface

### ISSUE THREAD

**Issue by sjbsjb** [eranif/codelite#968]
> Version:
> * CodeLite 9.0.0 
> * OS X El Capitan

I'm a Chinese student and my English is so poor, so please ignore my poor grammar and vocabulary...XD

I just installed the latest version of CodeLite(9.0.0). I created a project and then noticed cpu was increasing (up to 90%)...

![screen shot 2015-10-15 at 1 30 24 pm](https://cloud.githubusercontent.com/assets/11750373/10505676/843c774e-7342-11e5-8a9b-57ca576184b8.png)

Then I found CodeLite and Finder engaged most. I quit CodeLite and relaunched Finder. When I re-open CodeLite, I found something interesting.

Finder (system default language is English):
![screen shot 2015-10-15 at 1 35 00 pm](https://cloud.githubusercontent.com/assets/11750373/10505769/8c855a3c-7343-11e5-9b91-0a8b20d60398.png)

Finder Opened by CodeLite:
![screen shot 2015-10-15 at 1 29 26 pm](https://cloud.githubusercontent.com/assets/11750373/10505784/ab1b0078-7343-11e5-95e7-ba7d93654f61.png)

Then (notice that Applications has changed to "应用程序"):
![screen shot 2015-10-15 at 1 29 49 pm](https://cloud.githubusercontent.com/assets/11750373/10505991/7c7ab72a-7345-11e5-915c-acf2e7189934.png)

It seems that CodeLite makes Finder switching language between English and Chinese repeatedly (like an endless loop) and causes this issue. Then I uninstalled and reinstalled CodeLite, it happened again...

Hope you fix it as soon as possible T_T

**Comment by eranif** [comment]
What happens when you set `LC_ALL="C"` in your: Settings->Environment variables
Does this change anything?

**Comment by eranif** [comment]
Ping

**Comment by sjbsjb** [comment]
I've set it and it doesn't change anything...
So sad.

**Comment by sjbsjb** [comment]
@eranif 
In OS X 10.11.1 it is disappeared，so this issue should be closed...
