### ISSUE TITLE
checkboxes in "Build Output Appearance" need two clicks

### ISSUE THREAD

**Issue by grandinj** [eranif/codelite#969]
If I click on one of these checkboxes, the first click does not take effect, it seems to be eaten by the control and functions as "selection".

thanks.

**Comment by eranif** [comment]
Its a problem with the control - please open this bug to wxWidgets

**Comment by grandinj** [comment]
What control is this?

**Comment by eranif** [comment]
`wxPropertyGrid`

**Comment by grandinj** [comment]
Thanks, new ticket created here:

http://trac.wxwidgets.org/ticket/17205

**Comment by grandinj** [comment]
Looks like this has been fixed in wxWidgets 3.0.3 and 3.1, so when they release their new version and you update, it will be fixed.

Thanks, Noel
