### ISSUE TITLE
Node.js debugger opens terminal instead of sending output to Output pane

### ISSUE THREAD

**Issue by walkswiththebear** [eranif/codelite#972]
I am running codelite under Ubuntu 15.04. When I run the Hello World example described in 

http://codelite.org/LiteEditor/Nodejs

the "Hello World" output appears in a newly opened terminal instead of the Output pane. This is a bit inconvenient.

**Comment by eranif** [comment]
We had this in CodeLite 8.1 and we switched to native terminal from various reasons.
The "Output" tab does not have a full terminal capabilities, here is one of the reasons (an email I got from one of CodeLite users) that explains it in details:

> Hi Eran,
> first of all, I'd like to thank you for the new CL 8.1 - it looks great! I tried to create NodeJS workspace and everything works fine except one thing: I cannot send any user input to the java script by using Output pane's input text field. The "Send" button is disabled and ENTER key doesn't work as well. How can I pass some input into scripts like this:
> 
> var readline = require('readline');
> 
> var rl = readline.createInterface({
>   input: process.stdin,
>   output: process.stdout
> });
> 
> rl.question("What do you think of node.js? ", function(answer) {
>   // TODO: Log the answer in a database
>   console.log("Thank you for your valuable feedback:", answer);
> 
>   rl.close();
> });
> 
> Regards,
> Michal

**Comment by walkswiththebear** [comment]
Thanks for your prompt answer. But I just noticed that I have a serious problem now: when there are syntax errors in my JavaScript, the terminal window just flashes open and then closes immediately. A few seconds later, a dialog come up saying, "Failed to connect to Node.js debugger: Connection refused." I can't find a way to see the error message explaining what the syntax error was.

**Comment by eranif** [comment]
* Which OS are you using?
* Which CodeLite version?
* Can you provide a minimal script that shows the problem? (AFIR, I fixed this issue https://github.com/eranif/codelite/issues/917)

**Comment by walkswiththebear** [comment]
I'm using CodeLite 9.0 (downloaded earlier today) under Ubuntu 15.04. A minimal script that produces the behavior is:

var syntaxError = {
    x = 42
};

The syntax error, of course, is that "x = 42" needs to be "x: 42".

**Comment by eranif** [comment]
Thanks
@eranif launches VirtualBox

**Comment by eranif** [comment]
Tested both on Debian 8 and Ubuntu 15.04 using CodeLite 9.0.1

* Make sure you have `xterm` installed 

![10-17-2015 11-14-42 am](https://cloud.githubusercontent.com/assets/3677711/10557732/53c2e786-74c0-11e5-9416-2be752fc7fc2.png)

**Comment by eranif** [comment]
OK I found the reason: when debugging CodeLite is not attempting to launch `xterm` (which supports this **pause after exec**) it launches `gnome-terminal` (or other available terminal)

The screenshot I provided was while using `execute` and not `debug` (the difference is `Ctrl-F5` vs `F5`)
* Execute - run without debugging
* Debug, well, run the app via `Node.js` debugger
I will fix this and upload a new build with the fix availabel

BTW, since Node.js support is pretty new in CodeLite, it will be great to get more feedback

Thanks

**Comment by walkswiththebear** [comment]
Great, thanks! Now rush to fix, because this is a perfectly usable workaround: when the debugger does its flashing thing, I just execute instead, and voila, I can see my syntax errors.

I'll be using CodeLite for Node.js quite a bit, so I'll be happy to give more feedback. Right now, I only have one "complaint," and it's one that you are probably aware of: it would be great to have JavaScript code formatting. I know that clang-format is supposed to support JavaScript. But it doesn't seem to be doing anything with my .js files.

**Comment by eranif** [comment]
It seems to work here..
Which version of `clang-format` are you using, or do you have `clang-format` installed?

Thanks

**Comment by walkswiththebear** [comment]
I'm using clang-format-3.4

**Comment by eranif** [comment]
I think that JS format exists since clang-3.5

**Comment by walkswiththebear** [comment]
Great, thanks for the info! I didn't even know I was behind. I'll update.

**Comment by walkswiththebear** [comment]
Just a quick thank you: I update the whole clang caboodle, and all is well now. It was really easy to make CodeLite aware of the new compiler and formatter version. Awesome!

**Comment by eranif** [comment]
Please try this build:
http://codelite.org/downloads/codelite/weekly/wip/CodeLite-9.0.2-ubuntu-trusty-x86_64.deb

To install it:
```
sudo apt-get purge codelite wxcrafter
sudo gdebi CodeLite-9.0.2-ubuntu-trusty-x86_64.deb
```

**Comment by walkswiththebear** [comment]
I get "gdebi: command not found" when I try to run that.

**Comment by eranif** [comment]
`sudo apt-get install gdebi`

**Comment by walkswiththebear** [comment]
Works! The debugger now opens an xterm as desired. Thanks for fixing this so quickly. I'll send another $25.

**Comment by eranif** [comment]
Thanks!

**Comment by walkswiththebear** [comment]
Ok, one more thing. Suppose a runtime exception occurs, as in the script

var nada = null;
nada.foo();

If I execute this with Ctrl-F5, then the xterm stays open and gives me the error message. When I debug it with F5, the xterm does not stay open, and I can't find the error message anywhere.

**Comment by eranif** [comment]
Fixed. See attached screenshot for how it will look:

![exc](https://cloud.githubusercontent.com/assets/3677711/10559582/0f7b24b6-74fd-11e5-8854-1a95099d730a.png)
