### ISSUE TITLE
CodeLite crashes when showing autocomplete for variables/fields and application loses focus

### ISSUE THREAD

**Issue by yuri-vashchenko** [eranif/codelite#976]
This is a critical bug.
OS: Windows7 x64
CodeLite version: 9.0.1, Win64, the bug was threre in a lot of previous versions.
wxmsw310u_gcc_cl.dll version: 3.01.0.0

How to reproduce:
1. Open any C/C++ project
2. Start typing a function name or a variable, e.g. "pri".
3. Wait until autocompletion window shows up (it'll likely show "private" and/or "printf")
4. While autocompletion window is shown, using mouse click outside the application (ALT-Tab doesn't cause the issue, only mouse click). The application loses focus.
5. CodeLite crashes with Unhandled exception at 0x0000000069C51E0E (wxmsw310u_gcc_cl.dll) in codelite.exe: 0xC000041D: An unhandled exception was encountered during a user callback. 

Please note, that the bug _is not reproduced_ when showing autocompletion for function arguments.

**Comment by eranif** [comment]
I can't seem to reproduce this here (ran steps 1-4 with no crash)
Any suggestions for better reproducing?

Tested on both Debian 8 and Windows 7/64 bit

**Comment by yuri-vashchenko** [comment]
It strange, but it stopped reproducing in my system ether. May be Window Update or something resolved the problem.
Anyway, thanks for spending your time when trying to reproduce it.
I believe we can close this issue for now.

**Comment by hirnstrudel** [comment]
I found this page after it happend to me too:

1. Create new C++ Project with MinGW TDM-GCC-64
2. In main.cpp add a new line after printf(...
3. Type "arg" and wait for the auto completion window
4. Mouse Click on Desktop outside of CodeLite
5. CodeLite crashes with
"Unhandled exception at 0x0000000069C3F20E (wxmsw310u_gcc_cl.dll) in codelite.exe: 0xC000041D: An unhandled exception was encountered during a user callback."

OS: Windows7 x64 Enterprise
CodeLite version: 9.1.6

**Comment by eranif** [comment]
I am unable to reproduce this... 
For me, the completion box simply goes away - no crash

**Comment by hirnstrudel** [comment]
Any chance I could provide useful information to track it down?
I really like using this IDE, but when you loose changes multiple times in a row because you want to look up some API docs, it is nerve wrecking.

**Comment by eranif** [comment]
The only thing I can think of: build CodeLite in debug mode and debug it, other than that, I really have no idea

**Comment by hamlatzis** [comment]
I have the latest version on Ubuntu 18.04 64bit and it crashes if I have code completion enabled when the checkbox "Auto display code completion box when typing" is checked and have a small number of characters eg 3 (which by the way is the default)

If I uncheck it then no crash

**Comment by eranif** [comment]
- Is it a self debugged CodeLite?
- if not, where did you get it from?
- Can you provide the output from: `~/.codelite/crash.log`

**Comment by hamlatzis** [comment]
@eranif 
No it's downloaded, I've followed the guidelines from https://wiki.codelite.org/pmwiki.php/Main/Repositories#toc1

* Added the CodeLite public key to avoid warnings or worse from apt/aptitude
  * sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc
* Added in the file `/etc/apt/sources.list`:
  * deb https://repos.codelite.org/ubuntu/ bionic universe
* sudo apt-get update
* sudo apt-get install codelite

The above steps installed CodeLite 13.0.0 on my system

The crash log:
[crash.log](https://github.com/eranif/codelite/files/4438881/crash.log)

**Comment by eranif** [comment]
Can you please install CodeLite 14? 13 is at least 1 year old
and we do provide 14.0 from our repository. We also dropped the support for GTK2 and only using GTK3 now
Please do:

```
sudo apt-get update
sudo apt-get install codelite
```

This should install CodeLite 14 for you

**Comment by hamlatzis** [comment]
@eranif 

As I said that's what I did in the last two step and installed 13.0.0

But to be safe I repeated them and as you can see from the screenshot I'm still at v13.0.0 and in the terminal you can see
````
codelite is already the newest version (13.0-1unofficial2.bionic)
````
It reports unofficial, is there something I should add in the `/etc/apt/sources.list` to get the official?

![Screenshot from 2020-04-06 22-27-47](https://user-images.githubusercontent.com/761700/78597516-57931900-7856-11ea-9ec9-5c87af89be32.png)

**Comment by eranif** [comment]
Sorry I did not mention this earlier, but we had some issue and the old links are sitill pointing to 13.0.0.
@dghart  is fixing this now

**Comment by eranif** [comment]
OK, @dghart  did that - can you please do another update && install to confirm?

**Comment by hamlatzis** [comment]
ok thnx, updated to v14, but still crashes the same way

Have the setting code completion enabled when the checkbox "Auto display code completion box when typing" is checked and have a small number of characters eg 3 (which by the way is the default), just typed `val` and crashed

[crash.log](https://github.com/eranif/codelite/files/4442304/crash.log)

**Comment by dghart** [comment]
I've just tested with CL 14 and I can't make it crash either.

![CodeCompletion](https://user-images.githubusercontent.com/6452587/78652721-00bf2b00-78ba-11ea-9b8c-b87d2bf6105f.png)

That's on a virtualbox guest ubuntu bionic; it's a default install with XDG_CURRENT_DESKTOP=ubuntu:GNOME, XDG_SESSION_TYPE=x11, LANG=en_GB.UTF8 and GTK_IM_MODULE=ibus. The code-completion setting is the default 3.
How do they compare with your settings?

**Comment by hamlatzis** [comment]
I'm on a native installation (not virtual environment)
````
~ $ echo $XDG_CURRENT_DESKTOP
ubuntu:GNOME
echo $XDG_SESSION_TYPE
x11
~ $ echo $LANG
en_US.UTF-8

~ $ echo $GTK_IM_MODULE
ibus


~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
iosif@iosif-HP-Pavilion-Gaming-Desktop-TG01-0xxx ~ $ 
````

**Comment by dghart** [comment]
I just tried on an old 'real' bionic install. Still no crash.

It's hard to guess why the difference. However it could be something different in your CodeLite configuration, or in your bionic configuration.

The first can be checked easily. Close CodeLite, then temporarily rename your ~/.codelite/ and run CodeLite again. Create a C++ gui workspace/project and test for crashes. If none, the problem must be in your (real) configuration or project.

If it still crashes, it's presumably your bionic configuration. In that case, could you try installing a virtualbox bionic? Or make a new default 'real'  bionic install in a different partition?

**Comment by hamlatzis** [comment]
https://github.com/eranif/codelite/issues/976#issuecomment-610589416

created a new project and no crashes. Tried my previous project and still crashes. Tried other older projects with no problem. So I guess something with the specific project. I will create an empty project and move my code there

thnx for the help

**Comment by dghart** [comment]
Maybe the project's code-completion database is corrupt. IIUC that's the file \<workspace>/\<projectname>/.codelite/\<name>.tags (@eranif: please correct me if that's wrong) so just renaming that file should fix the old project.

Please report the result, so that we'll know what to advise in the future.

**Comment by hamlatzis** [comment]
@dghart 

Grate solution https://github.com/eranif/codelite/issues/976#issuecomment-610842645

Worked like a charm

👍
