### ISSUE TITLE
Find in Files Recent Search grows forever

### ISSUE THREAD

**Issue by hipnition** [eranif/codelite#977]
The new 'Recent Search' button in Find in Files grows forever. I don't know if it crashes at some point or not. Unfortunately, by the time you notice, you only have an option of "clearing all" and potentially lose some searches you intended to "re-search". A limit of 25 or would seem appropriate.

**Comment by eranif** [comment]
Use the `clear history` button. If you prefer a more better solution please submit a pull request as we don't have the resources to fix this
