### ISSUE TITLE
Unexpected termination of some/all user processes (gdb?)

### ISSUE THREAD

**Issue by carnalis** [eranif/codelite#978]
Occasional event which I *think* occurs right after debugging.
The usual result is termination of unrelated processes, quite often javaw.exe if it's running.
The most recent occurance terminated all user processes except CodeLite.
I've found nothing in system event logs or basic codelite.log (which usually only logs "MSYS environment detected").
The event is rare enough (once a month, perhaps) that I don't expect regular command-line gdb to be informative.
This has persisted through CodeLite 7/8/9 and several versions of mingw-w64 (5.x).
Using default gdb/compiler setup - CodeLite's good at this too.
Using only the Outline (1.0) plugin but will disable.

I suspect this is most likely a toolchain or config issue, since CodeLite presumably interfaces on a basic CLI level - in which case, this issue should probably be closed.

**Comment by eranif** [comment]
I have also experienced this (rarely) but it always happens when `gdb` is terminated
I doubt if it is a CodeLite bug and I will probably won't invest time on this bug as its very rare here and I am unable to reproduce it on deman
