### ISSUE TITLE
Multiple Node.js projects in one workspace?

### ISSUE THREAD

**Issue by santo74** [eranif/codelite#982]
Can this be done?
As far as I can see there is no project type for node.js projects, so the closest I can get is to create a workspace in the folder where all my related node.js projects are located (in subfolders).
The problem with this is that the projects aren't treated as separate projects but just as folders.

As a result there is no distinction between e.g. package.json in project A and package.json in project B, they both show up as "package.json" in the tabs / tablist.
Also this doesn't allow the run/debug multiple node.js projects at once.

**Comment by eranif** [comment]
Thanks for this valuable feedback. 
For now, the workspace indeed the entire folders as a bunch of folders.

How would you handle this?, e.g. should I handle each `package.json` as a project file? (with special context menu, maybe even with the a special `Settings` menu?)

Maybe parsing the content and make it somehow visible to the user? or maybe consider the `package.json` parent folder as a project?

Also, which OS are you using?

**Comment by santo74** [comment]
Probably the best approach would be to treat the parent folder of the package.json file as the project?

Additionally, a context menu with run/debug actions and a settings menu (and maybe some other stuff as well?) would be a nice feature I guess
Where settings could be a visual representation of the package.json file

Regarding the OS, I work mainly on windows (7 for now) but sometimes also work on a linux system.

**Comment by eranif** [comment]
Thanks. So as a start, CodeLite will handle any parent folder of a `package.json`  as a project.
The following addition info will be added to the project folder:

* Run 
* Debug
* Open `package.json`

I believe that it will be also nice to give such a folder a distinguish icon.

What do you think?

**Comment by mtangoo** [comment]
>I believe that it will be also nice to give such a folder a distinguish icon.
Definitely.

**Comment by santo74** [comment]
> Thanks. So as a start, CodeLite will handle any parent folder of a package.json as a project.
> The following addition info will be added to the project folder:
> 
>     Run
>     Debug
>     Open package.json
> 
> I believe that it will be also nice to give such a folder a distinguish icon.
> 
> What do you think?

Sounds like a good start, including the icon.
BTW, thanks for accepting this request

**Comment by eranif** [comment]
All of the above is implemented in git master (except for the icon part)
CodeLite will copy the initial settings from the `package.json` into a local file (in a hidden folder `.codelite`) each such project will store its own "main" file + command line arguments to pass to `nodejs` for debugging/running purposes

**Comment by santo74** [comment]
Thanks!

**Comment by eranif** [comment]
I will upload a build (hopefully today) now that I am back from my trip ;) and got access to Windows machine

**Comment by santo74** [comment]
That would be great!
