### ISSUE TITLE
Not running my program

### ISSUE THREAD

**Issue by ah1295** [eranif/codelite#984]
i have installed codelite 9.0 on windows with minGW 4.9. it is not running the program that i have written. it just run the default hello world program without building my written. in others words, i want to open a .c file and build it and run it  directly like the way in Pelles C ide. please tell me why it is not working that simply.

**Comment by ah1295** [comment]
for e.g.  tell me how to run a array sorting program

**Comment by eranif** [comment]
Not really a bug... please google this or ask your questions on the forum.
Not on the issue tracker
