### ISSUE TITLE
Add make rule for uninstall

### ISSUE THREAD

**Issue by nifker** [eranif/codelite#985]
I want to firstly remove the old codelite version and then install the latest.

**Comment by eranif** [comment]
I am not sure I am following here..
Are you talking here about `make uninstall` ? or... ?

**Comment by eranif** [comment]
After re-reading your issue, the only place where `uninstall` target is missing is in the generated makefile.
CodeLite uses `CMake` to generate the makefile, `CMake` does not generate `uninstall` target on purpose (don't ask me why...) luckily, `CMake` does provide a workaround, see the note on CodeLite's page: http://codelite.org/Developers/Linux#toc3
