### ISSUE TITLE
Wrong cursor used for code navigation

### ISSUE THREAD

**Issue by ovk** [eranif/codelite#986]
With *code navigation* feature when you put your mouse over a symbol while holding *code navigation key*, most users would expect the cursor to turn into **pointer** style cursor, since it is the way its done in most IDEs. Please consider this example from Eclipse:

![eclipse](https://cloud.githubusercontent.com/assets/693072/10717275/bea706d6-7b28-11e5-830f-a9913904a416.gif)

However, in CodeLite cursor stays the same (i.e. **select text** style cursor):

![codelite](https://cloud.githubusercontent.com/assets/693072/10717277/d339721e-7b28-11e5-9db6-2c73f3865ce4.gif)

*Its a bit hard to see the cursor on the captured gif animation, but you can test it yourself*

Obviously, this is more of inconvenience than a serious issue.

**Comment by eranif** [comment]
Unfortunately, there is no easy way to fix this without one or more side effects as Scintilla (the editor component) manages the cursor internally.
