### ISSUE TITLE
Request: Make the Node.js debugger show the prototype chain of an object

### ISSUE THREAD

**Issue by walkswiththebear** [eranif/codelite#988]
As far as I can see, the node.js debugger does not currently allow me to inspect the prototype chain of an object. Most of what's in the prototypes is member functions, which of course are not very interesting to look at in the debugger. But the prototypes also contain the static member variables (per-class member variables) of a javascript "class." When debugging, the static variables are just as important to look at as the regular member variables.

**Comment by eranif** [comment]
Can you provide a sample script for me to test and debug?

**Comment by walkswiththebear** [comment]
Here's a "class" with a per-instance variable and a per-class (static) variable:
    function DebuggerTest(){
        this.instanceVariable = 42;
    };
    DebuggerTest.prototype.classVariable = 43;

Next, create an instance:
var debuggerTestObject = new DebuggerTest();

The per-class (static) variable can now be accessed via the object or via the prototype:

    console.log(debuggerTestObject.classVariable); //43
    console.log(DebuggerTest.prototype.classVariable); // 43

The per-instance variable can of course only be access via the object:

console.log(debuggerTestObject.instanceVariable); // 42
console.log(DebuggerTest.prototype.instanceVariable); // undefined

The value of the per-class (static) variable should be visible somehow in the debugger. Please also note that there may be an entire chain of prototypes, that is, one would want to see the prototype of the prototype as well, as in this example:

    function BaseClass(){
        this.baseInstanceVariable = 42;
    };
    BaseClass.prototype.baseClassVariable = 43;

    function DerivedClass(){
        BaseClass.call(this);
        this.derivedInstanceVariable = 44;
    };
    DerivedClass.prototype = Object.create(BaseClass.prototype);
    DerivedClass.prototype.derivedClassVariable = 45;

    derivedClassObject = new DerivedClass();

Per-instance variables can be accessed from object only:

    console.log(derivedClassObject.baseInstanceVariable); // 42
    console.log(derivedClassObject.derivedInstanceVariable); // 44
    console.log(BaseClass.prototype.baseInstanceVariable); // undefined, per-instance variable
    console.log(DerivedClass.prototype.baseInstanceVariable); // undefined, per-instance variable
    console.log(BaseClass.prototype.derivedInstanceVariable); // undefined, doesn't even make sense
    console.log(DerivedClass.prototype.derivedInstanceVariable); // undefined, per-instance variable

Per-class variables can be accessed from object and prototype: 

    console.log(derivedClassObject.baseClassVariable); // 43
    console.log(BaseClass.prototype.baseClassVariable); // 43
    console.log(DerivedClass.prototype.baseClassVariable); // 43

    console.log(derivedClassObject.derivedClassVariable); // 45
    console.log(BaseClass.prototype.derivedClassVariable); // undefined, derived class only
    console.log(DerivedClass.prototype.derivedClassVariable); // 45

BTW, and I hope this won't come across as self-serving, but I've written a tutorial that explains JavaScript's way of supporting OOP, inheritance, etc. Here's the link:

http://thbecker.net/articles/javascript_oo/section_01.html

**Comment by eranif** [comment]
See attached screenshot:

![prototype-chain](https://cloud.githubusercontent.com/assets/3677711/10812424/b892ccaa-7e1e-11e5-9b5e-43a58439b4ff.png)

**Comment by walkswiththebear** [comment]
Great, thanks! Now I'm going to have to send you money again.
