### ISSUE TITLE
Minimal size specified on main sizer is not generated to XRC

### ISSUE THREAD

**Issue by MichalBliznak** [eranif/codelite#989]
Minimal size specified on main application window/dialog's sizer is not generated to XRC file. Generated C++ sources are fine (SetMinSize() function is used here).

**Comment by eranif** [comment]
I don't think that XRC supports `MinSize` attribute. Am I wrong here? I checked the source code of wxWidgets and could not find any ...

**Comment by MichalBliznak** [comment]
Look at the attached code generated from wxFormBuilder. It sets minsize of top level sizer attached to wxFrame. The code resizes the main frame in accordance to the minsize set in the size.

<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<resource xmlns="http://www.wxwindows.org/wxxrc" version="2.3.0.1">
	<object class="wxFrame" name="MyFrame1">
		<style>wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL</style>
		<title></title>
		<centered>1</centered>
		<aui_managed>0</aui_managed>
		<object class="wxBoxSizer">
			<minsize>800,600</minsize>
			<orient>wxVERTICAL</orient>
		</object>
	</object>
</resource>

**Comment by eranif** [comment]
Fixed
