### ISSUE TITLE
sort project in workspace tab

### ISSUE THREAD

**Issue by totokick** [eranif/codelite#991]
The global workspace composed of multiple .project seems to be sorted alphabetically.

Since most project have architecture with high-level and low-level APIs, that would be a great enhancement having control on project sorting in the workspace view, through drag-n-drop or any other way.

I currently have a dozen of projects on my workspace and always spends seconds scrolling around expended tree view looking for the file I want.

Thx

**Comment by eranif** [comment]
What stopping you from using `Ctrl-Shift-R` and typing the name of the file you want to open?

**Comment by eranif** [comment]
Also, due to very low resources, this will probably won't be implemented as we got other priorities (we are 2 developers), You are most welcome to send a pull request with this feature implemented

**Comment by totokick** [comment]
Hi Eranif, thanks for your reply.

I agree `Ctrl-Shif-R` is a good option when you actually know the file name or part of it you want to open (sorry if my use-case example was inappropriate). Developers using codelite here don't necessarily know much about the architecture layer ordering used by the opened workspace. They discover it most likely through pieces of documentation.

I will clone the source code and see if it sounds easy to implement.
Regards,
