### ISSUE TITLE
Compiler errors are sometimes not highlighted when building large workspace

### ISSUE THREAD

**Issue by ntpg** [eranif/codelite#994]
Version 9.0.1 - Linux

Sometimes when building a large number of files in a C++ workspace, compiler errors/warnings are not being highlighted correctly. The bug seems to be related to the amount of output in the build log. 

I have uploaded a gzip archive of a workspace that reproduces the problem here: http://cutpi.com/ndj. There is an intentional compiler error in error.h. Notice the lines in the output are not being highlighted correctly. If you reduce the number of files, or the number of errors, the highlighting starts working again.

If you don't want to download the archive, you can easily produce a workspace that has the same problem. The steps are:
- Create a c++ console workspace with gnu g++ tool chain
- Add two new projects
- Add 100 source files to each project
- Have each source file include a header file with a syntax error in it
- Build solution and you should see the problem

**Comment by eranif** [comment]
Seems to work on Windows without a problem, will try this on Linux

**Comment by eranif** [comment]
Also working on Debian 8. 
I would have notice this by now (CodeLite workspace contains thousands of files...)
I tested using CodeLite 9.0.2 (available for download from the website)

**Comment by ntpg** [comment]
I just grabbed 9.0.2 and I'm having the same problem with the test workspace on rebuild workspace. I', testing on ubuntu 14.04. I attached an example screenshot.

Is it possibly related to my patterns settings? I've attached a screen of that too
![bug](https://cloud.githubusercontent.com/assets/11166961/10826388/d7fa22d4-7e26-11e5-9388-12c015c59358.jpg)
![settings](https://cloud.githubusercontent.com/assets/11166961/10826391/da076884-7e26-11e5-8874-731dca9815c8.jpg)

**Comment by eranif** [comment]
Looks like that the colouring is one line offset. I have re-written the colouring logic to be based on lines instead of position and it should fix your problem (although I could not reproduce it, I believe that it will fix this)
Are you using a self compiled CodeLite?

**Comment by ntpg** [comment]
No, I am using the latest release

**Comment by eranif** [comment]
Please try this build and let me know if it fixes your problem:
http://codelite.org/downloads/codelite/weekly/wip/CodeLite-9.0.3-ubuntu-trusty-x86_64.deb

**Comment by ntpg** [comment]
That appears to have solved the problem! Thanks!
