### ISSUE TITLE
[Ubuntu][Install] CodeLite 9.0.2 - Weekly Build

### ISSUE THREAD

**Issue by anatooly** [eranif/codelite#995]
$uname -a
Linux anatooly 3.16.0-51-generic #69~14.04.1-Ubuntu SMP Wed Oct 7 15:32:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.

Lintian check results for /home/anatooly/Downloads/CodeLite-9.0.2-ubuntu-trusty-x86_64.deb:
E: codelite: control-file-has-bad-permissions md5sums 0664 != 0644

The installation or removal of a software package failed.

(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 278542 files and directories currently installed.)
Preparing to unpack .../CodeLite-9.0.2-ubuntu-trusty-x86_64.deb ...
Unpacking codelite (9.0.2) ...
dpkg: error processing archive /home/anatooly/Downloads/CodeLite-9.0.2-ubuntu-trusty-x86_64.deb (--install):
 trying to overwrite '/usr/share/codelite/wxgui.zip', which is also in package wxcrafter 2.4-1.trusty
dpkg-deb (subprocess): decompressing archive member: internal gzip write error: Broken pipe
dpkg-deb: error: subprocess <decompress> returned error exit status 2
dpkg-deb (subprocess): cannot copy archive member from '/home/anatooly/Downloads/CodeLite-9.0.2-ubuntu-trusty-x86_64.deb' to decompressor pipe: failed to write (Broken pipe)
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Errors were encountered while processing:
 /home/anatooly/Downloads/CodeLite-9.0.2-ubuntu-trusty-x86_64.deb

**Comment by eranif** [comment]
Please read the HOWTO install the package carefully: http://forums.codelite.org/viewtopic.php?f=20&t=3147

Hint: you should remove `wxcrafter` package first

**Comment by anatooly** [comment]
sudo apt-get install gdebi
sudo apt-get purge codelite wxcrafter
sudo gdebi /path/to/codelite/deb/file

**Comment by eranif** [comment]
Did you manage to install it?

**Comment by anatooly** [comment]
@eranif yes, Software Manager show some warning, but install correct.
