### ISSUE TITLE
Dual monitor code suggestion placement

### ISSUE THREAD

**Issue by matosha** [eranif/codelite#997]
Using two monitors with codelite on the second screen. The code suggestion box and account manager display on the first monitor.

-Windows 10, extended display

![screenshot_2](https://cloud.githubusercontent.com/assets/2575626/10842201/73b85f5c-7ef8-11e5-87b0-6042279f86be.jpg)

**Comment by renkun-ken** [comment]
I'm using three monitors 2-1-3, and codelite autocompletion list works perfect in screen 1 (middle) and 2 (left), but not working correctly in screen 3 (right).

**Comment by RyanSW** [comment]
I have noticed this same issue. My far right monitor places the suggestion boxes on the monitor to its immediate left. Works fine on other monitors though.

**Comment by legends2k** [comment]
Same here.  The problem occurs only when Codelite window is in the farthest right monitor.

**Comment by AlexKalopsia** [comment]
DId anyone find a solution to this problem? Dual monitor setup here, and suggestion box always shows on Monitor 1

**Comment by KinsonDigital** [comment]
I have the same issue. I have 2 monitors and when on the second monitor, the code complete window shows on the 1st monitor all the way to the right edge. :(

**Comment by lulou** [comment]
On windows you can temporarily fix this problem if you set your primary monitor to whatever monitor you use codelite on.
