### ISSUE TITLE
Feature goto definition work not well

### ISSUE THREAD

**Issue by silverphoenix1110** [eranif/codelite#998]
Feature goto definition work not well

**Comment by eranif** [comment]
Hmm... it works pretty well

**Comment by silverphoenix1110** [comment]
Your IDE is verry good. But when I work with laravel framework, this feature doesn't work with any classes or functions

**Comment by eranif** [comment]
You need to add paths to laravel to the code completion
From the menu: PHP->settings->code comepltion

**Comment by eranif** [comment]
Did it fix your problem?

**Comment by silverphoenix1110** [comment]
Thanks for your support. It worked! It will perfect if this feature can work with variables.
